### ISSUE TITLE
Craftable Horse Saddles

### ISSUE THREAD

**Issue by sharkfynn1012** [EarthMC/Issue-Tracker#100]
Pretty self explanatory. I'm not sure if this has been implemented yet, although I'd guess not. Is there a plug in that we could get that would allow us to craft horse saddles? It would aid many people when it comes to transportation.

We could add name tags to this but saddles would be my top pick.

**Comment by MSatrokrm** [comment]
Craftable name tags would be awesome.

**Comment by BowShot118** [comment]
This idea would be great as it will help to speed up transport. The name tag is nice as it is very hard to get otherwise as well.

**Comment by shirazmatas** [comment]
Saddles are currently very high price, this would be bad for saddle stakeholders owo. Also theres other means to get them

**Comment by BowShot118** [comment]
> Saddles are currently very high price, this would be bad for saddle stakeholders owo. Also theres other means to get them

The hard to access was directed towards the name tags as they are genuinely very hard to get, and rn I think there is as much of a horse shortage as there is saddles.

**Comment by sharkfynn1012** [comment]
Saddle sellers should be a second priority here, they can currently charge the Earth for a saddle as they are super hard to come by.

**Comment by shirazmatas** [comment]
Name tags should also according to me not get a recipe because they are also obtainable from different routes, and you don't really need a name tag

**Comment by MSatrokrm** [comment]
> Name tags should also according to me not get a recipe because they are also obtainable from different routes, and you don't really need a name tag

My fishings kill is over 150, and i have not gotten a single nametag. My fishing rod has lure 3, luck of the sea 2, unbreaking 3. It's feckin hard to get, and I need like 10 nametags to name all of my pets.

**Comment by PoppyK** [comment]
I personally think that there will be enough tags once players have string to craft fishing poles.  Everyone seems to want everything so soon in the game.  I think it is more fun to work for things.  This also allows those who decide to loot the continued privilege of selling hard to obtain items (tags, saddles, horse armor) for high prices.  

It might be good to check that tags are a fishable item since we are in a new server and all of those items are toggleable in config.  Other than that I would let this be for now.

**Comment by creatorfromhell** [comment]
> I personally think that there will be enough tags once players have string to craft fishing poles. Everyone seems to want everything so soon in the game. I think it is more fun to work for things. This also allows those who decide to loot the continued privilege of selling hard to obtain items (tags, saddles, horse armor) for high prices.
> 
> It might be good to check that tags are a fishable item since we are in a new server and all of those items are toggleable in config. Other than that I would let this be for now.

I think this could be looked at from two angles. If you want to keep any kind of hostile mob from despawning you have to name it. i.e. zombie villagers as villages aren't present. I can also see how it is soon, but I can also see where people are looking to start villager operations.

**Comment by MSatrokrm** [comment]
I'll be a saddle supplier

**Comment by Coffeetom** [comment]
Once people get high MCMMO, name tags will be everywhere
This is because when excavating you end up getting heaps of name tags
And saddles shouldn't get a recipe
People should have to go explore to find to get the privilege of riding a horse

**Comment by sharkfynn1012** [comment]
I’ve explored and not yet found one. If we want a map with realism why do we have to make it harder by not being able to use horses? We got a bigger map, now we need to get something to make walking that map easier.

**Comment by creatorfromhell** [comment]
I wanted to add onto this from my original comment. Once villager farms are up and running saddles will be oh so common. I don't know if it's something that should be made easier, as it'll put pressure on players to cure zombie villagers now that mobs are re enabled.

**Comment by FenZenyatta** [comment]
are mobs re enabled? Haven't seen a wild cow or sheep in ages. No signs of horses either

**Comment by KarlOfDuty** [comment]
As the nether will have semi-regular resets I don't think saddles will be an issue, just an expensive product.
