### ISSUE TITLE
[Feature] Polish channel

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1001]
**Is your feature request related to a problem? Please describe.**
So many players have pain in ass some guys are speaking polish. I'd like to change that!

**Describe the solution you'd like**
Add /polish channel so you can talk here in Polish. My calculations shown that 75% of Polish Kingdom's citizen are IRL Polish + many people comes from Poland

**Comment by docwhomc** [comment]
If they are in the same nation, they can use their nations chat channel.

As for your calculations, show your work.

**Comment by 3meraldK** [comment]
> If they are in the same nation, they can use their nations chat channel.
> As for your calculations, show your work.

As I said many other players comes from Poland IRL but they'd like to live in other nations than Poland. I am sure a lot of players are Polish.

**Comment by JaVolimKatarinu** [comment]
Can you give numbers? This is based on the assumption that there are. If there really is a lot of Polish players, we will add a new channel. But if you are asking us to find out how many there are and is that number enough for a new language channel, I'm gonna tell you right away that won't happen. We have a lot of tickets, a lot of issues with 1.15 still exist, and no one has time for counting how many Polish players there is.

**Comment by Mihailovi** [comment]
I agree, there has been a large community of Polish players on the server and if we're ever going to add other language channels, one of the first should be Polish.

**Comment by Warriorrrr** [comment]
Will be added on next restart
