### ISSUE TITLE
[SUGGESTION] Spawn Trap Problem

### ISSUE THREAD

**Issue by Nerd00110001** [EarthMC/Issue-Tracker#1002]
On the server there is an issue with spawn trapping or even having someone right next to a PVP enabled spawn to kill people who just spawned in which isn't technically in exact violation of rule 2.1 but it does have the same effect by creating a bad experience for players. There are also people who still advertise these traps constantly, evading spam filters while doing so.

To solve this I would suggest to make any nation or town spawn a no PVP zone automatically and disable the allowance of PVP in the spawn chunk only. Chunks around the spawn may have PVP or not depending on the owner's preference but the spawn itself cannot have PVP enabled as long as it is a spawn. If the spawn were to change to another spot where PVP is enabled, the plot would be changed to a non PVP plot automatically and PVP will not be able to be re enabled while the spawn is located there. By doing this you will be able to stop the possibility of spawn trapping/killing, but you as a mod will not have to worry about checking to see if a reported spawn trap is actually a trap or not.

**Comment by KarlOfDuty** [comment]
This was already changed in the rules a few weeks ago but it wasn't very clear so I updated it a bit again.
![image](https://user-images.githubusercontent.com/18099825/76704369-d920dc80-66d8-11ea-84c8-f5b192140513.png)
