### ISSUE TITLE
What's So Good About Oz?

### ISSUE THREAD

**Issue by kaixlz** [EarthMC/Issue-Tracker#1003]
**Is your feature request related to a problem? Please describe.**
Yes. What makes Oz so special that they get bamboo and the rest of us don't? 

**Describe the solution you'd like**
I want the bamboo to either be given to all of us, or taken away from Oz.

**Comment by KarlOfDuty** [comment]
We will not do that at this time. They won and it's up to them to decide on what to do with the reward.
