### ISSUE TITLE
[BUG] Towns without a nation can use /n spawn

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1005]
**Server**
Towny

**Describe the bug**
Towns that aren't in a nation are able to use /n spawn, to any nation except to those that aren't public.

**To Reproduce**
1. Be in a town that isn't in a nation
2. Use the /n spawn command and teleport to any public nation

**Expected behavior**
It's expected that the /n spawn command won't work, since the town isn't in a nation. This can be used to bypass nation enemies by simply leaving the nation, teleporting then rejoining.

**Comment by FutureLemon** [comment]
Not only towns, everyone who isn't part of a nation can teleport to nation capitals with /n spawn?

**Comment by Carabow** [comment]
and town in a nation and town without nation appear in same color on the map.
