### ISSUE TITLE
No dark oak 

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#101]
So far out of all the players and all the places visited, not a single person has found dark oak trees. 

This has lead many to believe that they don’t exist in the game.

Please do significantly increase their rarity as they’re currently in demand by builders

**Comment by FixTheAdmin** [comment]
Thanks for the report, dark oak wood is on its way

**Comment by KarlOfDuty** [comment]
We have started placing dark oak trees in different areas of the world now.
