### ISSUE TITLE
[plugin] COVID-19 and other diseases

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#1010]
**Problem**
EMC lacks realistic diseases, COVID-19 in particular.

**Solution**
Install the [Coronavirus](https://www.spigotmc.org/resources/coronavirus.74655/) plugin:
> Minecraft but with the Coronavirus!
- Not the most realistic implementation, but it's better than not having COVID-19 in game.

Install the [Disease](https://www.spigotmc.org/resources/disease.3911/) plugin:
> Bring the terror of infectious disease to your sleepy minecraft town
- More ralistic, but does not include COVID-19 at present.

**Additional Context**
See also the news (pretty much any of it).

**Comment by Cactusinapumpkin** [comment]
All the bees are dying, how more realistic do you need??

**Comment by KarlOfDuty** [comment]
thonk
