### ISSUE TITLE
World grief and robbery 

### ISSUE THREAD

**Issue by Geeky7105** [EarthMC/Issue-Tracker#1011]
**Describe the issue**
I have a town a little north of Siberia that I made 5 days ago. I've had some issues with the perms, but with some time I was able to fix it. Yesterday at around 10:30am EST I heard that there were some issues with the plugins and town commands, but when I logged on a couple of hours later, my town had no issues. I left my friend to build towns this afternoon (19/3/20) at 2:15pm EST, one of my friends and a fellow nation member CaptainPatakis7 was done building some of my houses in my town. And I gave him permission to build, use chests, and to destroy with the town perms, he only took some wood and stone. But when I logged on 3 hours after, I realized that my chests have been looted and that my Horse was gone with the fences broken. If any mods could check logs or anything that could be a great help, because I don't know if this was a grief with the bug of the town commands.
**Coordinates**
x: 19108 y: 64 z:14009

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how\ you want the terrain to look.
![2020-03-19_16 59 08](https://user-images.githubusercontent.com/62403647/77115919-97a86e00-6a05-11ea-8e0d-39563c96b0af.png)

![2020-03-19_16 59 22](https://user-images.githubusercontent.com/62403647/77115975-b27ae280-6a05-11ea-9cb6-a7af2c543114.png)

![2020-03-19_16 59 25](https://user-images.githubusercontent.com/62403647/77115996-bad31d80-6a05-11ea-8081-4c82445ba831.png)

**Comment by jkmartindale** [comment]
Have you filed a ticket on the [EarthMC support Discord server](https://discord.gg/EZBYmpp)? For stuff like this where's it's not clear what the bug is and it involves a few specific players, you'll get a faster response there.

**Comment by docwhomc** [comment]
@Geeky7105 @jkmartindale Please read the [rules](https://earthmc.net/rules):
> **2.2 Stealing and raiding players/towns/nations.**
> Stealing from and raiding other players is allowed. It’s up to each and every player to protect their assets. (Towny is a bit more strict than the factions server, see rule 3)

Staff does not investigate thefts.
