### ISSUE TITLE
[BUG] /n set title automatically adds an extra space

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1019]
**Server**
Towny

**Describe the bug**
Doing /n set title will automatically add an extra space to the end of it, adding up to a total of 2 spaces.

**To Reproduce**
1. Give someone a title using /n set title
2. Notice how an extra space gets added in the message.

**Expected behavior**
An extra space won't be added.
**Screenshots**
![image](https://user-images.githubusercontent.com/50800980/77256252-51edde80-6c6d-11ea-8410-84dcc74dcb34.png)
![image](https://user-images.githubusercontent.com/50800980/77256234-400c3b80-6c6d-11ea-97a3-a072776de311.png)

**Comment by jkmartindale** [comment]
This will be fixed by TownyAdvanced/Towny@b19bd98 when EarthMC updates their version of Towny

**Comment by Basically-Andrew** [comment]
This I believe is also a related issue with /t set title

**Comment by KarlOfDuty** [comment]
This should be fixed now.
