### ISSUE TITLE
[Feature] Let us turn wool back into string

### ISSUE THREAD

**Issue by Synargle** [EarthMC/Issue-Tracker#102]
With the lack of mobs, string is becoming increasingly rare.

**Comment by creatorfromhell** [comment]
String may be obtained from fishing, so I'm not sure why this is needed?

**Comment by shirazmatas** [comment]
Can't fish if you can't craft a fishing rod 😆 🤔

**Comment by creatorfromhell** [comment]
> Can't fish if you can't craft a fishing rod 😆 🤔

Fair point. The ultimate fix is to just fix certain issues to allow the mob spawns to be turned back on. Otherwise, we're going to be going without various progressiong items, string, bones/bonemeal, gun powder, and zombie villagers.

**Comment by TheGoatOnABoat** [comment]
We can add a shop plugin for the loot.

**Comment by TheGoatOnABoat** [comment]
Also, I saw a spider in Mississippi today.

**Comment by creatorfromhell** [comment]
> Also, I saw a spider in Mississippi today.

It probably spawned before mobs were turned off. Also, you can't add a shop plugin to correct not having villagers.

**Comment by KarlOfDuty** [comment]
Mob spawns have been turned back on.

**Comment by KarlOfDuty** [comment]
As mobs have been turned back on this is no longer needed.
