### ISSUE TITLE
[BUG] Formatting issues with nation and town ranks

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1020]
**Server**
Towny

**Describe the bug**
Town & nation ranks have formatting issues within /resident, self-explanatory

**Expected behavior**
The formatting is normal & doesn't have issues

**Screenshots**
With 1 town rank:
![image](https://user-images.githubusercontent.com/50800980/77256709-346e4400-6c70-11ea-9cab-3b7883a8cd7c.png)
With 2 town ranks:
![image](https://user-images.githubusercontent.com/50800980/77256725-4ea82200-6c70-11ea-8d1d-f4678c1703bb.png)

With 1 nation rank it looks normal:
![image](https://user-images.githubusercontent.com/50800980/77256780-929b2700-6c70-11ea-895f-c1b2ccc114ca.png)
But with 2 nation ranks:
![image](https://user-images.githubusercontent.com/50800980/77256743-62538880-6c70-11ea-8e01-c6f377f6f476.png)

**Additional context**
I hope this is enough context to get this issue fixed and end these formatting issues once and for all

**Comment by jkmartindale** [comment]
What's the formatting issue with nation ranks? I'm not sure what you're pointing out.

**Comment by docwhomc** [comment]
I believe it's about the stray comma before Councillor @jkmartindale.

**Comment by Warriorrrr** [comment]
It's the stray commas, yes. There also isn't a space between each rank that would normally be there.

**Comment by jkmartindale** [comment]
Looks like it's fixed on EarthMC now

![image](https://user-images.githubusercontent.com/11380394/79168149-66be1d80-7da6-11ea-9e49-b3d358f619f2.png)

![image](https://user-images.githubusercontent.com/11380394/79168175-750c3980-7da6-11ea-80b4-193ad632e098.png)
