### ISSUE TITLE
[Feature] Weekly Towny Polls

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1021]
**Is your feature request related to a problem? Please describe.**
EarthMC Towny could see more involvement in the community. Currently, Admins ask a few short questions, while they're online about things coming to the server.

**Describe the solution you'd like**
Adding a _weekly_ polling system either through chat or through a book would allow more community input, involvement, and a more positive community.

**Additional context**
The polling system can include a small question on their thoughts of current features or mechanics to new features or mechanics. A suggestion I have also heard from friends was to do approval polls on mods and to give an extra vote crate for completion of the poll weekly.

**Comment by docwhomc** [comment]
Not sure why this is Towny specific, but okay.

**Comment by KarlOfDuty** [comment]
I recommend using the subreddit for this, we usually check any posts with a lot of upvotes.
