### ISSUE TITLE
[BUG] Two previously claimed chunks no longer claimed

### ISSUE THREAD

**Issue by jmpamc** [EarthMC/Issue-Tracker#1022]
Towny  

**Describe the bug**
Two of my previously claimed chunks on: 
![2020-03-23_16 48 39](https://user-images.githubusercontent.com/62540287/77298814-73f76780-6d26-11ea-902b-eeff1cba9465.png)
and
![2020-03-23_16 48 43](https://user-images.githubusercontent.com/62540287/77298831-7954b200-6d26-11ea-85ee-47ddddd64144.png)
are now "Wilderness".  I claimed them before, and I did not unclaimed them.

The two claims were lost, but fortunately, many of my other claims remained - although their set plot names of them returned back to "~Unowned".

**Expected behavior**
I expected the two chunks in front of my palace to be claimed. I also expected the names of my other plots to be specifically named, not "~Unowned".

**Screenshots**
Unfortunately, the only screenshots I have are when they are no longer claimed. The coordinates above are the previously owned land my town had. 

**Additional context**
Most likely, I claimed the two chunks that were lost on Saturday. But my memory is a little faded. Although I am sure that I have those two claims before since I bothered renaming the plots to the likes of "Baybayin" (although I forgot if that was its last name. But if not, it was the plot's name prior to the final name), and the second plot is named "Barugo Gate" (Or Barugo Building) - to compliment the other side of the palace's "Carigara Plate" (Or Carigara Building).

Perhaps the information above can help you investigate.

**Comment by KarlOfDuty** [comment]
Should be fixed.
