### ISSUE TITLE
[Bug] Claimed chunk unclaimed

### ISSUE THREAD

**Issue by Alferner** [EarthMC/Issue-Tracker#1023]
**Server**
Which server the bug is on.
Towny
**Describe the bug**
I claimed a chunk yesterday and then logged off. When I woke up and logged in the claim was not there anymore. Happend at Kristiansund in central Norway Area

**To Reproduce**

**Expected behavior**

**Screenshots**
![MC failclaim](https://user-images.githubusercontent.com/62553521/77323694-f62b6000-6d15-11ea-8591-872bca40cab3.png)
![MC townmap](https://user-images.githubusercontent.com/62553521/77324195-b44ee980-6d16-11ea-8345-96970c75ef57.png)

**Additional context**

**Comment by jkmartindale** [comment]
Possible duplicate of #1022

**Comment by Carabow** [comment]
maybe just a server rollback, isn't it?

**Comment by KarlOfDuty** [comment]
Should be fixed.
