### ISSUE TITLE
[Bug] I can't do anything at all in my faction.

### ISSUE THREAD

**Issue by InfinityB-mc** [EarthMC/Issue-Tracker#1025]
**Server**
Which server the bug is on.
Faction

**Describe the bug**
Yesterday and most of today, I could do anything I wanted except for commands. Nobody on my faction has been actually on. Just AFK. Then I died in a blaze spawn room, and I could no longer do ANYTHING.

**To Reproduce**
I have no idea how this happened, and DocW is also baffled by this, too.

**Expected behavior**
Nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/62167183/77391501-e38d4700-6d66-11ea-9e14-0b8c87f838d0.png)

**Additional context**
I do not know how this happened, but I was told to put it here, so here you go.

**Comment by SvenPhillips** [comment]
Try getting your faction leader to sort out his perms, or if you are the faction leader, sort out the perms yourself.
