### ISSUE TITLE
[Plugin] Leading more mobs?

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1026]
**Is your feature request related to a problem? Please describe.**
Yeah I am annoyed that I can't normally transport villagers. It's REALLY annoying when I waste one hour of time and finally didn't complete my goal. For example when I transport villagers by river sometimes it has higher levels so my boat can't move up. Even in claimed area so it's impossible because villager can't swim and go up so you can't do it. The same thing is with other mobs and animals.

**Describe the solution you'd like**
Very simple - what if you add the possibility to use a leash on e.g. Villager. I know it's stupid but it will help many players.

**Additional context**
It won't change balance nor economy but players would be happier :)

**Comment by docwhomc** [comment]
Leads already exist in vanilla Minecraft.  However, they cannot be used with villagers.  No plugin suggested.

If you are suggesting we add a plugin to allow you to leash villagers with leads, then please provide a link to the plugin.

Not that plugins must be compatible with PaperSpigot.
