### ISSUE TITLE
[Feature] Towny Annex Command

### ISSUE THREAD

**Issue by kab000m** [EarthMC/Issue-Tracker#1027]
I think there should be an "annex" command added to the game to ease merging of towns. For example, a town should be able to annex a town that is next to it. For example, take Kodiak and Old_Harbor. It would be in Kodiak's best interest to /annex them instead of wasting gold and reclaiming all of it. 
**Describe the solution you'd like**
My solution is adding an /annex commnad that would annex the neighboring town. For example, it could be "/t annex Old_Harbor". This is just a small command that can be used to save people gold.

**Comment by kab000m** [comment]
Obviously it will require the person who is getting annexed to say Yes. Also, maybe the comand can charge the person who is annexing territory gold for the amount of chunks theyre annexing.

**Comment by JaVolimKatarinu** [comment]
This suggestion is not for EarthMC Github. Please suggest this to Lmdl on his Towny repo.

https://github.com/TownyAdvanced/Towny/issues

**Comment by kab000m** [comment]
> This suggestion is not for EarthMC Github. Please suggest this to Lmdl on his Towny repo.
> 
> https://github.com/TownyAdvanced/Towny/issues

Understood.
