### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by Mineturtle795** [EarthMC/Issue-Tracker#1028]
It is I, mineturtle, ggovi alt. 

Don't you fucking dare let factions die. It is my home. It is my place. Classic was my home until you uprooted it, fix. Now you are uprooting my new home, factions. Don't let factions die. I may be the most hated guy on factions but at least I was a factioneer. Don't kill factions or I will doxx you and find you irl. 

Sincerely, 
Ggovi

**Comment by jkmartindale** [comment]
ok, this is epic

**Comment by jkmartindale** [comment]
Though the real ggovi already doxed Fix so...

**Comment by SvenPhillips** [comment]
This is an epic crossover episode
