### ISSUE TITLE
Town Daily Upkeep

### ISSUE THREAD

**Issue by miner-sd** [EarthMC/Issue-Tracker#1029]
Lately, I've seen a lot of 1 person towns and garbage governing in a lot of towns and nations.

I think there should be daily upkeep for towns based on how many members they have which would push governments to get their shit together and deal with inactives effectively

Specifics:
- 5g base cost per day to run a town
- 1g per 5 members in a town (maybe 3 if it's too minimal of an effect) cost per day

The desired outcome for this is to make 1 person towns too costly to use as much as they currently are and also to make big inactive towns need to get their shit together or face collapsing

**Comment by Aitonater** [comment]
Agree. The amount would not need to be very much to have a big impact on inactive towns that take up land that could be used by new active players.

**Comment by geobeeblaster** [comment]
I think that this is a good idea, but I think that the upkeep should be in the realm of 1-3g per week, as one-person towns are quite useful in rural areas, where they are the only breath of civilization in an empty land.

**Comment by DTHMASTER** [comment]
I totally agree

**Comment by Lagann311** [comment]
I agree, but I think 2g upkeep is more than enough for 1 player towns.

**Comment by FutureLemon** [comment]
Towns aren't really the problem, one man nations on the other hand are.

**Comment by Cactusinapumpkin** [comment]
Well sometimes shit happens like the corona virus and how would you like it if your town got removed because you didn’t have enough gold to last past a week of inactivity because something came up in ur life. This idea not only makes the experience of emc less fun but pushes new players away. Maybe one man nations can have a tax once a month since they can waste 1024g on a server spawn point.

**Comment by Prismary** [comment]
No longer a particularly recent nor popular issue, has also been discussed in many other threads. Closing for now.
