### ISSUE TITLE
Increase the AFK kick time back up to 30 minutes

### ISSUE THREAD

**Issue by Taicamila** [EarthMC/Issue-Tracker#103]
It doesn't make sense to lower it to 5 minutes. For example, if somebody wants to go AFK for 5 minutes to make some lunch, they'd come back to see they've been kicked and won't be able to join for another few hours since the player limit still has not been increased. Sometimes bathroom breaks as well can take up to 5 minutes to complete, I'm not sure who would be sitting at their computer holding all their shit in just to play on Terra Nova and not get kicked.

**Comment by Taicamila** [comment]
Yeah, maybe. 15 minutes seems like a good amount of time.

**Comment by KarlOfDuty** [comment]
Done.
