### ISSUE TITLE
Prio should be required to get premium.

### ISSUE THREAD

**Issue by geobeeblaster** [EarthMC/Issue-Tracker#1030]
I have noticed a flaw in the premium/prio system. Say someone is joining the server for the first time, and is faced with a ridiculously long queue. Heading to the earth MC store, they see two options 1: a $15 payment that just skips you ahead in the queue, and 2: an $8 payment, that, while it needs to be payed every month, not only skips you past the players who paid twice as much as you, also gives you several other features, such as queue chat and nicks.

A simple solution to this problem would be to require players to have already purchased prio before they can purchase premium. This should be grandfathered in, as no players should have to lose their premium just because they joined before the rule was implemented.

**Comment by jkmartindale** [comment]
Maybe set it up so that new Premium members are part of the standard Priority queue and the Premium queue unlocks after paying for two months (or whatever is the equivalent of Priority when prices change)

**Comment by FutureLemon** [comment]
It is confusing as of right now it's more profitable to buy a month of premium and join the server instead of buying priority but at the same time you are still passing people in queue with old priority who have been playing much longer and don't have fancy perms.

**Comment by geobeeblaster** [comment]
Yes, that is the exact reason i think we should change it

**Comment by stzups** [comment]
All of this assumes the player quits after two months. 

Players looking to play on the server for more than two months but don't need premium will buy priority, because it costs less. Players who buy premium for two months because it offers more features for less money will eventually have to pay more than players with priority after two months. Players who start with premium because it costs less then cancel and buy priority will end up having paid for premium and priority. 

I don't see a problem here.

**Comment by geobeeblaster** [comment]
The issue is that a new player who paid $8 will be placed ahead of an old
player who paid $15

**Comment by stzups** [comment]
Yes, someone who pays $8 every month will be ahead of someone who paid $15 once.

**Comment by geobeeblaster** [comment]
My main issue is that prio will rarely, if ever, be bought, and premium
used as a substitute for prio, causing all the old paying players to be
placed behind the new paying players. Maybe instead of having
separate premium and prio queues, we could have one "paying" queue, that
can then be subdivided based on prio/premium and time played

**Comment by stzups** [comment]
> premium used as a substitute for prio

The only way this could happen is if players bought premium for two months then quit the server or went back to the regular queue. 

I don't think many players will do this, therefore premium will not be used as a substitute for priority.

**Comment by ogxn** [comment]
I think the solution to this problem is to just allow older players the ability to buy + ranks. They got discontinued, I don_'_t like it, but hey, it's what happened.

**Comment by ogxn** [comment]
+ ranks are just legacy Premium

**Comment by KarlOfDuty** [comment]
We will not be adding this requirement, we may look into other solutions though.
