### ISSUE TITLE
[BUG] Villagers not changing/taking professions.

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#1031]
**Server**
Towny

**Describe the bug**
Villagers will not take up a profession despite having access to a job block and despite never having been traded with before or ever having had a profession previously. Similarly when job blocks are taken away villagers are not returning to a jobless state.

**To Reproduce**
1. Get a villager with no profession/or with a profession (who has not been traded with).
2. Remove/add a job block.
3. Wait for a very long time.
4. See error. They will not take up a new profession/relinquish an old profession from a time before the bug started occurring.

**Expected behavior**
I expect villagers with no access to a job block to change back into a jobless state. I expect villagers with access to job block to take up the appropriate profession.

**Screenshots**
![villagers](https://user-images.githubusercontent.com/47613294/77658397-8d8af000-6f6e-11ea-9c5b-50a013f53bf7.png)
You can see the villager on right. Never been traded with has no job block, been a librarian for days. Villagers on the left have lecterns but will not become librarians.

**Additional context**
This has been happening sporadically for the past week or so, some villagers trades change even once you have traded with them when their trades would normally lock. Some villagers are just completely despawning.

**Comment by Aitonater** [comment]
**Another picture of villagers who will not get professions:**
![won't get jobs](https://user-images.githubusercontent.com/47613294/77676145-d0a48d80-6f85-11ea-90f1-1cafd11a808a.png)

**Comment by FutureLemon** [comment]
It only happens to my villagers when they have been there before the update to 1.15.

**Comment by Aitonater** [comment]
It's happening to my new villagers post 1.15 too. When they reduced the player slots to 150 it seemed to resolve the problem so I imagine its a performance measure being taken with mob AI or something.

**Comment by Aitonater** [comment]
yeah when the player count is below 175 they seem to work fine and smooth

**Comment by JaVolimKatarinu** [comment]
Villager requires bed and job site and space to walk around freely. And yes, it has a connection to server performance, which disables their AI sometimes in order to decrease lag. I believe this would be resolved as soon as performance gets better.

**Comment by Cactusinapumpkin** [comment]
I give them professions in the breeding room and then when I find a trade I like I lock it in and transfer them to a trading hall

**Comment by KarlOfDuty** [comment]
As npc trading is disabled I guess this is not relevant anymore.
