### ISSUE TITLE
More Slots on the server.

### ISSUE THREAD

**Issue by DogeDogIs** [EarthMC/Issue-Tracker#1035]
Put 400 slots on the server. So can decrease the queue and improve the server. Can be more efficient and the people will not complain. More fun, less complain. (I used Google Translator)

**Comment by stzups** [comment]
👏 we did it boys the queue is no more 👏

**Comment by KarlOfDuty** [comment]
I would have never thought of this.

**Comment by Warriorrrr** [comment]
Big Brain

**Comment by Basically-Andrew** [comment]
I am hoping this is a meme, but 150-175 Player Server Slots is the largest Towny Server running 1.15.2. Towny is a heavy plugin not including Dynamap.

**Comment by Nerd00110001** [comment]
Maybe not 400 as the towny plugin is so big but maybe 300 may be more do able or if anything at least 250. Of course though this should be done after 1.15.2 is not an issue with the server running.
