### ISSUE TITLE
[BUG] Nether mobs aren't spawning

### ISSUE THREAD

**Issue by 32Vache** [EarthMC/Issue-Tracker#1037]
**Server**
Towny

**Describe the bug**
Nether mobs (Blazes, Wither Skeletons, Pigmens, Magma Cubes, Skeletons) aren't spawning.

**To Reproduce**
1. Go to the nether
2. Find a fortress
3. Nether mobs do not spawn

**Expected behavior**
A few days back, those mobs were still spawning and now they no longer do, although they should.

**Additional context**
Nether mobs (especially wither skeletons) are important, they provide wither skulls (and beacons), and there's gonna be a lack of stock and a price raise for those. This also makes player built wither skull farms completely useless, resulting on lost time and resources for the players building them.

**Comment by Basically-Andrew** [comment]
Verified this myself, my wither farm assets are worthless profound effects.

**Comment by FutureLemon** [comment]
Same for my wither skeleton farm. The nether spawns seem to be disabled.

**Comment by Cactusinapumpkin** [comment]
Sounds like beacons were getting too cheap

**Comment by JaVolimKatarinu** [comment]
Due to 1.15 performances, the server is really struggling to stay online for a longer time. In situations where the server gets laggy, he disables mob AI and as well mob spawn, to improve itself. This should we resolved once performance issues get resolved.

**Comment by FutureLemon** [comment]
@JaVolimKatarinu are you sure about this? They still haven't been enabled and usually its only the overworld mobs who have been disabled due to lag. Maybe it could very well be a bug? I don't know though.

**Comment by JaVolimKatarinu** [comment]
I don't and can't know for sure. Once performance issues get resolved, we might be able to determine if its a bug or not. Currently, we are not aware of the state of performance upgrades that are being made as well as what are they affecting. From time to time, there is decrease/increase of max players on the server and that is all I know. :/
