### ISSUE TITLE
Plot permissions for item frames bugged

### ISSUE THREAD

**Issue by Neowyld** [EarthMC/Issue-Tracker#1039]
**Towny**

**Basically, you have to set permission to "destroy" rather than "switch" to allow outsiders to use item frames.**

1. /plot set perm switch doesn't work.
2. /plot set perm destroy allows item frame use. 

**Item frame use is categorized as switching, not destroying.**

**Comment by JaVolimKatarinu** [comment]
I believe this is a Towny issue and should be redirected to Towny issue tracker [Click me if you are brave](https://github.com/TownyAdvanced/Towny/issues).
