### ISSUE TITLE
[SUGGESTION] Prismarine

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1040]
The recipe to craft one single prismarine shard currently requires one sand, one dirt and one lapis lazuli. This gets you one shard and you need 9 shards or 8 shards in total to make a lantern or a block of dark prismarine. Perhaps it would be better if the yield of crafting gets a little better since because the investment of 18 blocks to get one single lantern is just ridiculous in my opion. So I think it would be much better if maybe you can get 4 shards per recipe since it makes it more realistic and gives players who do not have the time to grind for sand and dirt all a chance to build some really cool prismarine based builds. 
![image](https://user-images.githubusercontent.com/44688587/78290588-382d8080-7524-11ea-875f-3c4c7936b60c.png)

**Comment by Cactusinapumpkin** [comment]
I like this idea

**Comment by FutureLemon** [comment]
@DasCodes Is this possible anytime in the near future? (:

**Comment by Prismary** [comment]
I would also like to see this happen. Simple change and a big quality of life improvement. I don't see why prismarine should be as hard to gather in bulk as it currently is.

**Comment by AndrewCheedle** [comment]
@Warriorrrr could you consider this

**Comment by CorruptedGreed** [comment]
Old issue from Nova that was done, currently reviewing new additions for Aurora
