### ISSUE TITLE
Inventory dupe bug

### ISSUE THREAD

**Issue by IKHPKalle** [EarthMC/Issue-Tracker#1041]
Hi, I accidentally duped my inventory by putting my inventory in a chest and then logging out before a reset. Could someone with permits please come to Kronoberg (In southern Sweden) and remove the items in the chest besides the cactus-farm that it says "Inventory dupe" on. I think that was everything that was duped.

**Comment by FutureLemon** [comment]
You should make a ticket in the support discord and provide a picture and coords. You can make a support ticket by typing -new in the channel #support-tickets. If you are not already in the support discord here's a link:https://discord.gg/RySahU4.
