### ISSUE TITLE
[Feature] Toggle Players Visibility in Queue Hub

### ISSUE THREAD

**Issue by XioanAskari** [EarthMC/Issue-Tracker#1042]
**Is your feature request related to a problem? Please describe.**
I really do want to try the parkour but it can be hard to focus sometimes when other players block my vision due to their models or them runnign out in front of me.

**Describe the solution you'd like**
An option that allows for toggling other player;s models on and off, especially as it could maybe boost framerates of slower pcss since they do not need to render out so many players.

It could just render the name over their head, or  completely hide the model and any sounds it would produce <burning, damage etc>  

**Additional context**

**Comment by JaVolimKatarinu** [comment]
This concept was used already when we were trying to upgrade performances in the queue world. But it didn't render names nor sounds other players were creating. I think?

**Comment by XioanAskari** [comment]
If so it would be possible to impliment it into the hub as a way to maybe make things more stable for players iin the hub.

**Comment by Prismary** [comment]
Many minigame servers have this feature in their hubs and I don't see a reason why EMC shouldn't have it. As far as I'm aware, there's off-the-shelf plugins that can do this, so it wouldn't be a huge effort either.
