### ISSUE TITLE
[BUG] turtle bug

### ISSUE THREAD

**Issue by SuperDoff** [EarthMC/Issue-Tracker#1043]
**Server**
Earthmc.net

**Describe the bug**
My turtles keep disappearing after they’ve grown up. I’ve tried going through a nether portal and relogging, but none of these has worked. 
**To Reproduce**
1. Place a turtle egg on sand 
2. Wait for it to hatch
3. After it’s hatched, feed it seagrass so it will grow faster
4. After it’s grown, it will disappear

**Expected behavior**
I expected the turtle to be forever there

**Screenshots**

**Additional context**

**Comment by Cactusinapumpkin** [comment]
I have noticed this as well and believe it to be a chunk mob limit issue. It seems to not affect some animals like chickens, cows, and sheep

**Comment by jkmartindale** [comment]
I had an adult turtle disappear in a chunk that contained only turtle eggs and one other adult turtle, so it might be more than just a chunk mob limit.

**Comment by JaVolimKatarinu** [comment]
The server is randomly despawning mobs, literally randomly. I wouldn't say that any particular type of mob is excluded, but I have seen huge amounts of chickens in one chunk. And I saw sheep disappearing as the only mob in that chunk. 
Again, this issue should be resolved once performance upgrades are done. Let's hope that will be soon.

**Comment by Helloguys47** [comment]
there is a bug on tropical fish we can kill them on chunks and they dispawn(but I have put a nametags for them not dispawning)

**Comment by Prismary** [comment]
Known issue, has to do with server lag and entity limits. The settings change every now and then as optimizations are being made, so this particular issue is likely no longer recent. Closing for now.

As a sidenote for users with a similar problem: Staff will refund mobs if their prior existance can be proven. In a case like this, please open a ticket on the [support discord](https://discord.gg/EZBYmpp).
