### ISSUE TITLE
[BUG] Shortcut in Lobby

### ISSUE THREAD

**Issue by JoelESP** [EarthMC/Issue-Tracker#1044]
**Lobby**
**The bug**
There is a shortcut in the long parkour.

**To Reproduce**
1. Go to parkour but don't enter.
2. Go left and next to the wooden balcony you will see some blocks under the normal level of the map.
3. Jump next to the lava.
4. Move around with shift and you will be already on the slimeblocks part.
If you do this correctly you will survive with half a heart.

**Video**
![ezgif-6-c270d2909b79](https://user-images.githubusercontent.com/56233732/78399295-f0c2f500-75f4-11ea-9a3b-532e8afca9e8.gif)

**Comment by shirazmatas** [comment]
it's a feature
