### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by luckz4** [EarthMC/Issue-Tracker#1045]
first off i got kicked out of sever at 20 in q and now haven't moved from 130 in 20 mins

hub

**Comment by Cactusinapumpkin** [comment]
Sometimes the server can experience a process called maintenance and sometimes this leads to irregularities in queue. I am not too sure about what does work specifically but I can guarantee eventually after waiting a long time you will eventually get in. You will have to wait for 130 people to get in before you or buy premium and skip a very large portion of the wait. Please close ticket if you have no other questions or concerns.

**Comment by docwhomc** [comment]
@luckz4 Please elaborate/file a proper bug report.
