### ISSUE TITLE
My nation name got reset

### ISSUE THREAD

**Issue by KaninoPika** [EarthMC/Issue-Tracker#1047]
The 20th Febuary this year I created a nation called "Republic_Sweden". It was when the KalmarUnion was still existing. A month and 5 Days passes and the KalmarUnion change name to "Sweden". Is it just me who don't see the logic why my name got reset even if I was first with the name?

**Comment by FutureLemon** [comment]
Did they change the name of your nation? If so you should make a ticket by typing '-new' in the support discord. If you are not already in the support discord click the following link to join it: https://discord.gg/RySahU4

The current rules regarding Nation Names (4.1) say that a nation cannot be named after a similar nation. 'Nation cannot have a similar name to already established nation to the point where one could easily be confused with the other.' Given this you are most definitely in your right to request your own nation name back and or a name change for the current nation of Sweden previously called Kalmar Union.

**Comment by Cactusinapumpkin** [comment]
Please close this ticket if your issue is resolved

**Comment by docwhomc** [comment]
@KaninoPika Please report this on the [support Discord](https://discord.gg/EZBYmpp).
