### ISSUE TITLE
Bring back the ability to /t join open towns, albeit with a twist.

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#1048]
I think we should bring back the ability for players to /t join open towns. It made recruiting new people much easier than now as we constantly have to scan through the server and manually invite them. It was much easier saying in chat “Hey, looking for a town? Type /t join towname”

I get why it was removed though. Players would abuse it such as GG0VI who would use bots to mass join random towns (although that was months ago) or people would “snipe” open towns by joining them right before their mayors are meant to purge.
Therefor my suggestion would be to make it so that you can only /t join an open town if the mayor is online. This would prevent the issue of sniping inactive towns and a few other issues which existed in the past.

Personally I miss the feature a lot as it made recruiting so easy, and I’m sure many other mayors miss it too. Would be nice to see it return.

**Comment by FutureLemon** [comment]
I once made a request to re-add this too. Back then Karl said they wouldn't bring it back as long as the bot attacks continue but now that the bot attacks are gone there should virtually be no problem to bring it back.

**Comment by Pengun78** [comment]
Fax fax

**Comment by 32Cragno** [comment]
Totally true

**Comment by KarlOfDuty** [comment]
These permissions will likely be returned when some issues in towny have been fixed.
