### ISSUE TITLE
[Suggestion] Make classic map as the hub world

### ISSUE THREAD

**Issue by SuperChrisBoy** [EarthMC/Issue-Tracker#1049]
I believe bringing the classic map to the hub world (maybe replacing the current hub world) can make the queue less boring and can attract more new players. I'm pretty confident that this can be a solution for the players who wanted the classic map back.

Any feedback/additional ideas would be appreciated.

**Comment by docwhomc** [comment]
My understanding is that the file was corrupted, making this impossible, but I will leave this open awaiting confirmation that this is the case.

**Comment by docwhomc** [comment]
Accidentally closed it, undoing.

**Comment by Conmqn** [comment]
The classic map would be a good idea but it would be boring for most people and i think its time for it to be in a resting place for now i would love to go back to it any day.
