### ISSUE TITLE
Bug tropical fish

### ISSUE THREAD

**Issue by Helloguys47** [EarthMC/Issue-Tracker#1050]
hello,there is a bug I wanted to be fixed 3weeks ago:about tropical fish,we can kill them on town claim and some guy come and kill them but even if it doesn't happen,they dispawn even if they have a nametags please staff fix this bug a guy report it 1YEARS AGO and no one wanted to fix this,a lot of emc people need fish for aquarium or lagoon or beach!

**Comment by Cactusinapumpkin** [comment]
We are looking into this issue please be patient there are a lot of newer larger problems since updating to 1.15

**Comment by FutureLemon** [comment]
Any animal or mob on EarthMC is very fragile it would be better to keep them as far as possible from other players to avoid such things because players will always find a way to kill or steal them.

**Comment by Cactusinapumpkin** [comment]
This should be fixed now for water mobs
