### ISSUE TITLE
[BUG] Deposit/Withdraw

### ISSUE THREAD

**Issue by wewewewdafafw** [EarthMC/Issue-Tracker#1051]
**Server**
Which server the bug is on.
Towny
**Describe the bug**
I am the mayor of Union Glacier (not in a country) and it will not let me deposit nor withdraw in a bank or home plot nor anywhere else. It used to work. It shows the message "Not enough permission"
**To Reproduce**

**Expected behavior**
I expected to withdraw and deposit some cash i needed but than it said "Not enough permission"
**Screenshots**

**Additional context**

**Comment by zwiebelslayer** [comment]
just relog or go in the nether

**Comment by Cactusinapumpkin** [comment]
You can try the nether but usually that only works with spawn commands. This might be a bigger issue with the plugin. There’s a lot of people having issues with checking their bal, depositing gold and /pay. We are actively looking into a fix for this issue

**Comment by Cactusinapumpkin** [comment]
Some people are having issues with chatting in global and chatting at all.

**Comment by zwiebelslayer** [comment]
ah ok i also once had this bug and going into the nether fixed it.

**Comment by Cactusinapumpkin** [comment]
You are still experiencing this issue correct?

**Comment by Cactusinapumpkin** [comment]
Karl a bigger issue is b_brothers ticket concerning him accidentally duping gold with a glitch it is possibly effecting more than just him. Ticket 07756 gold dupe
