### ISSUE TITLE
Japanese Chat 

### ISSUE THREAD

**Issue by DuranGan** [EarthMC/Issue-Tracker#1052]
A Japanese chat will nice for the server.
The EMC mechanics are like RPGs, and it's very popular there.
It can be attractive for Japanese players.

 
I'm not very good at English so I can't explain more.

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by DasCodes** [comment]
I don't think I have seen any player speaking in Japanese.

**Comment by FutureLemon** [comment]
> I don't think I have seen any player speaking in Japanese.

Most likely because we can't tell the difference between Japanese, Korean and Chinese.

**Comment by KarlOfDuty** [comment]
We will not be adding any more chat channels at this time as the chat plugin seems pretty buggy when it comes to channels. We may look into getting a different chat plugin in the future though.

**Comment by DuranGan** [comment]
> We will not be adding any more chat channels at this time as the chat plugin seems pretty buggy when it comes to channels. We may look into getting a different chat plugin in the future though.

Yeah because getting into channels has some bugs.
The Japanese chat still has opportunity?
If you guys change the chat plugin?

**Comment by KarlOfDuty** [comment]
Maybe
