### ISSUE TITLE
[Bug] Certain Prefixes Bypass Anti-Spam Measures

### ISSUE THREAD

**Issue by jkmartindale** [EarthMC/Issue-Tracker#1054]
**Server**
Towny

**Describe the bug**
Anti-spam measures that prevent you from spamming the same message multiple times in a row don't apply to messages beginning with these prefixes:
- fix
- gg
- f

I get that this sort of thing is useful sometimes but people are abusing the hell out of it now.

**To Reproduce**
1. Send the message "test test"
1. After 5 seconds, send "test test" again, and the message will be blocked
1. Send the message "gg test"
1. After 5 seconds, send "gg test" again, and the message will send

**Expected behavior**
This message gets blocked.

**Screenshots**
Example of someone successfully using this bypass:
![image](https://user-images.githubusercontent.com/11380394/79095244-25326180-7d17-11ea-8efc-a9c52cf60abf.png)

**Comment by 10op10** [comment]
snitch

**Comment by 10op10** [comment]
How tf am i gonna spam gawain now bro 😭😭😭😭😭😭😭👿👿👿

**Comment by Cactusinapumpkin** [comment]
We are already aware of this issue. 10op10 is that your name or how old you are?

**Comment by Snowyy4K** [comment]
bruh

**Comment by jkmartindale** [comment]
![giphy](https://user-images.githubusercontent.com/11380394/79135171-2f327f80-7d6c-11ea-8d10-02156caaee41.gif)

**Comment by Cactusinapumpkin** [comment]
Thank you

**Comment by 10op10** [comment]
> We are already aware of this issue. 10op10 is that your name or how old you are?

I'm not fucking 10 lmfaoo

**Comment by jkmartindale** [comment]
The "fix" prefix is kind of a red herring, turns out any message starting with "gg" or "f" or any other strings that are whitelisted from spam protection will also be whitelisted, no spaces or whatever needed.

**Comment by Warriorrrr** [comment]
Fixed
