### ISSUE TITLE
[Bug] Phantom Town Plots

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1056]
**Server**
Towny

**Describe the bug**
After Towny died a couple of times, certain plots that used to belong to fallen towns have somehow reappeared. They have the old name, and cannot be claimed, stating that the area belongs to "some town". Only some towns are affected by this, recently fallen towns seem not to.

**To Reproduce**
It's currently unknown how to reproduce this issue, but I think it might have to do with the database running out of space and having to self repair, or another unknown reason.

**Expected behavior**
The plots aren't shown as being part of a town, and are claimable without errors.

**Screenshots**
![2020-04-12_22 28 07](https://user-images.githubusercontent.com/50800980/79127127-9e769680-7da1-11ea-8cef-c9eef71d5ed2.png)
Shown here is that the plot is owned, but doesn't belong to any town. Default wilderness perms apply, but if you'd try to claim it won't work (See below)
![image](https://user-images.githubusercontent.com/50800980/79136237-f49f0600-7db0-11ea-97b3-ec522d67d8d7.png)
This screenshot is from someone in my nation who tried claiming some of these plots to expand his town, he tried claiming it multiple times until it worked, every failed attempt took gold from his town bank.
![image](https://user-images.githubusercontent.com/50800980/79136251-f9fc5080-7db0-11ea-89ce-1149f27fd818.png)

**Additional context**
This issue is very annoying, since it stops people from claiming if there's a bugged fallen town next to theirs. I hope this is enough for it to be fixed, if it isn't, then let me know.

**Comment by Oln123** [comment]
![image](https://user-images.githubusercontent.com/51036095/79154302-389d0580-7dc7-11ea-9b0e-490dacdc1e0c.png)
This may or may not be related to this but shanka who is shown in screenshot 2 is mayor of the town above (in black). There Is a chunk to the southwest which is shown to be part of his town but it is very far away from the towns "mainland".

**Comment by Cactusinapumpkin** [comment]
This should be fixed now
