### ISSUE TITLE
[Feature] Add back space between Title and IGN

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1057]
**Is your feature request related to a problem? Please describe.**
A while ago, I opened an issue (#1019) for a duplicate space between the name and IGN of players. The towny dev fixed this themselves, but on the 27th of March the space was manually removed in the chat config, then later, when Towny updated that space got removed too.

**Describe the solution you'd like**
Add back the space in the chat config, so that titles (finally) look normal again.

**Additional context**
![image](https://user-images.githubusercontent.com/50800980/79148035-29b55380-7dc5-11ea-9966-282ebdabd07a.png)
This screenshot shows there being no space between the title and IGN. (Ignore the 2 errors)

**Comment by jkmartindale** [comment]
Nah that wasn't my fix, that was the main Towny dev

**Comment by Warriorrrr** [comment]
Oh right, confused it with TownyAdvanced/Towny/pull/3820, I'll edit it.

**Comment by Warriorrrr** [comment]
Closed cause it's fixed now
