### ISSUE TITLE
Greifing rule 

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#1058]
**Is your feature request related to a problem? Please describe.**
The request I am requesting would make 3.1 and 3.2 clearer and easier to understand. It will also avoid confusion.

**Describe the solution you'd like**
Rule change to make new player less likely to break the rule and add more concrete explanation. 

**Additional context**
3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing).    

3.2	Destroying land in wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or in close proximity to a claimed area.

I would like to add to add a distance of 5-10 chunks instead of saying around, or in proximity of to avoid confusion of if the mayor greifed his own land and new players thinking it’s an appropriate distance away from the town.

**Comment by Cactusinapumpkin** [comment]
I recommend a solid 5 chunks away should be sufficient enough space.

**Comment by Warriorrrr** [comment]
https://github.com/EarthMC/EarthMC.net/issues is where this is supposed to be posted, but I agree with this rule change

**Comment by Cactusinapumpkin** [comment]
Post in above link
