### ISSUE TITLE
No Terraforming

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#106]
I'd like to see terraforming banned, extreme map changes to clarify as it ruins the dynmap and makes the land look generally ugly. Imo, these'd be things like remove large islands or adding large islands. Removing parts of a landmass or removing large amounts of water in places like an ocean.

**Comment by NilsNyfiken** [comment]
How big terreforming would count as rule breaking then? You would still be allowed to expand some Islands etc if you keep their shape, right?

**Comment by BowShot118** [comment]
I'd only say so if it doesn't change the server's map too much.
