### ISSUE TITLE
Allow nickname option for Discord server

### ISSUE THREAD

**Issue by Bladen2k** [EarthMC/Issue-Tracker#1062]
**Is your feature request related to a problem? Please describe.**
Some Discord users have different names than their Minecraft usernames, creating confusion of identifying players from the Earthmc server on discord.

**Describe the solution you'd like**
Toggle option for discord server members to create a nickname. This will give the ability for people to match their minecraft usernames without completely changing their discord user tag. 

**Additional context**
N/A

**Comment by KarlOfDuty** [comment]
You can use /discord link ingame to do this.

**Comment by jkmartindale** [comment]
Was this not working earlier? I tried unlinking and relinking a couple days ago to get my Premium role added but my nickname on Discord hasn't been updated to match.

**Comment by FutureLemon** [comment]
> Was this not working earlier and then fixed later? I tried unlinking and relinking a couple days ago to get my Premium role added but my nickname on Discord hasn't been updated to match.

I'm pretty sure it links up with your IGN and not /nick.
