### ISSUE TITLE
Premium rank gone even thought it has not been a month

### ISSUE THREAD

**Issue by rustysbro** [EarthMC/Issue-Tracker#1063]
Premium was bought for me on 4/7/2020 my IGN is ShepardN7ME I am assuming the IGN of sacraze since he bought premium the same day he bought it for me and now mines gone I have not had a chance to talk to him yet

**Comment by Cactusinapumpkin** [comment]
You might need to talk to the person who bought it for you. He prolly didn’t want to make auto payments for you and attempted to cancel it

**Comment by Cactusinapumpkin** [comment]
And what do you mean ur ign is Shepard but ur assuming the name sacraze?

**Comment by rustysbro** [comment]
> You might need to talk to the person who bought it for you. He prolly didn’t want to make auto payments for you and attempted to cancel it

He has for me and myself I know for sure but in that case I should it until may correct?

**Comment by rustysbro** [comment]
> And what do you mean ur ign is Shepard but ur assuming the name sacraze?

My IGN is ShepardN7ME and sacraze is who bought it at the same time for himself and me

**Comment by Cactusinapumpkin** [comment]
Sacraze is ur friend that bought you (Sheppard) premium

**Comment by rustysbro** [comment]
> Sacraze is ur friend that bought you (Sheppard) premium

Yes he also bought it for him the same day

**Comment by Cactusinapumpkin** [comment]
But you assume he bought it for you even though he didn’t tell you he bought it for you? Is this what your saying

**Comment by rustysbro** [comment]
> But you assume he bought it for you even though he didn’t tell you he bought it for you? Is this what your saying

No I know 100% he bought it for me since we were in a discord call when he did

**Comment by Cactusinapumpkin** [comment]
Please try to talk to him and try to confirm he didn’t do anything, we also need his input here if he can.

**Comment by Sacraze** [comment]
So essentially Fix (I'm assuming the server's owner?) told Shepard and I that he would give us a temp rank until the e-check cleared. I received an email from Paypal on 04/13/20 that it cleared successfully.

Today, 04/14/20 we logged on exactly a week after getting the temp rank and were defaulted to regular rank despite the check clearing.


![](https://cdn.discordapp.com/attachments/662150812633399297/699801199880306809/unknown.png)

**Comment by Cactusinapumpkin** [comment]
Do u have proof that the e check cleared? Please don’t post any personal info though

**Comment by Cactusinapumpkin** [comment]
And yes fix is the server owner and he handles premium issues directly.

**Comment by Warriorrrr** [comment]
It's probably better to continue this by dming Fix rather than continuing here, or alternatively you could open a ticket in the support discord [here](https://discord.gg/xHMGxNa)
