### ISSUE TITLE
[Feature] Re-enable Acrobatics on Towny

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1065]
**Is your feature request related to a problem? Please describe.**
Acrobatics is a skill that got silently disabled, even though the skill itself was super useful. I haven't seen a reason for why this got disabled, while it was super useful for surviving fall traps/spawn traps.

**Describe the solution you'd like**
That the acrobatics skill gets enabled again, with both the skills & xp gain.

**Comment by FutureLemon** [comment]
The abilities with this skill can be very handy to counter spawn fall traps so you don't die and lose your stuff.

**Comment by Cactusinapumpkin** [comment]
*rolled*

**Comment by Warriorrrr** [comment]
exactly 1 year later.
