### ISSUE TITLE
[BUG] Teleportation in combat.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1066]
**Server**
Towny

**Describe the bug**
The timer to teleport to a nation or town has been reduced to instantly. This means you can instantly teleport out of combat since the anti combat log plugin doesn't cover teleportation. 

**To Reproduce**
1. Tag a player to combat
2. Do /t spawn
3. Instantly get back in your town without the other playing having a chance of killing you

**Expected behavior**
An error message saying you can't teleport or a 3 second timer like before.

**Additional context**
If you want to kill a player right now it's virtualy impossible due to anyone beingable  to teleport out.

**Comment by jkmartindale** [comment]
Why was this closed? 👀
