### ISSUE TITLE
[BUG] My cow disappeared two times

### ISSUE THREAD

**Issue by TheNylox** [EarthMC/Issue-Tracker#1067]
**Server**
I'm playing the EMC Towny

**Describe the bug**
I was travelling through the ocean with a cow from Rimini (Italy) to Dorchester . For two times in a row when i arrived to dorcheste my cow and the leash disappeared . It is possible to get my cow at -14629 71 -7330 ? i payed it two times .
thank for any answer

**To Reproduce**
2. Click on '....'              ????

**Expected behavior**
If possible i want a cow in -14629 71 -7330

**Screenshots**

**Additional context**

**Comment by Cactusinapumpkin** [comment]
Where you arrived at Dorchester did it happen to have a lot of mobs in that chunk already?

**Comment by Cactusinapumpkin** [comment]
It sounds like a mob limit issue

**Comment by TheNylox** [comment]
I dont know that

**Comment by TheNylox** [comment]
Maybe in the town center could be some farms

**Comment by FutureLemon** [comment]
If you want a refund make a support ticket in the support Discord.  https://discord.gg/RySahU4

**Comment by Conmqn** [comment]
If there was more than 16 cows in the chunk then the 2 cows would have despawned to to the mob limit per chunk.
