### ISSUE TITLE
[Feature] Bounce back/Barred when trying to enter claims while combat tagged

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#1069]
One of the main reasons why people demand a war plugin is because town claims pose a huge obstacle while pvping or while in major battles. They allow for people to cheat death by simply running in them when you're low on health or they cause battles to become stale and boring as people simply hog in them and only jumping out every now and then to score a few hits before running back in again. It's frustrating and takes away from what could be a great battlefield experience. A war plugin is popular because it is of course a way around this as it would enable the ability to fight within towns, however I believe there is a simple solution around this.

I've seen other towny servers with this feature which means it is tried and tested. Apparently it isn't too hard to implement either. The request is rather simple: 

**Make it so that if you're in wilderness and combat tagged, you are barred from entering town claims until the combat timer wears off.** 

This is such a simple addition but it's effects would be game changing. Battles would actually occur, no more running in claims to escape death and no more battles that involve staring contests between people standing blocks away from town claims or inside them.

With this feature, battles would take place on huge battlefields as there would be no safespaces to run into and cheat death. With this addition, entering a battle would mean, you either kill or be killed.

Another upside to this is that unlike a war plugin it won't force innocent citizens to take part in battles. If you don't want to fight, just don't exit claims while there's a battle going on outside your town, it's rather simple.

I've been told that there is a way in the combat log config that allows you to make it so that you bounce back when entering claims while combat tagged although I'm not so sure how that all works, that's a matter for the devs to implement. My main point however is that this is such a common feature on many towny servers so I doubt it would take too long to implement here.

This feature gives the benefits of what a war plugin would give, however it does not involve the huge amount of coding or performance issues that a war plugin would also bring. This is such a small feature but would drastically improve the battle experience on emc, creating huge battlefields instead of merely hogging blocks away from town claims while people jump in and out of them to score hits. Unlike a war plugin, this feature would have no effect on the builders or innocent citizens, they'd be able to continue as usual.

I hope this feature is considered and implemented as soon as possible, it really isn't anything too complicated. <3

**Comment by 10op10** [comment]
I think this is good because people always abuse this, especially with pvp plots inside towns, its annoying af and you can't pvp

**Comment by Cactusinapumpkin** [comment]
10op10 I did not know you were able to make a comment without using 11 emojis. They are looking into a warplugin please be patient as we are trying to fix more important issues atm. War plugin has been suggested many times before and may be closer to becoming reality now that we are in 1.15. Please try the factions server in the meantime it is pvp/raid oriented and not really build oriented like towny where you build towns, nations, economies, and relations between others.

**Comment by CasperFactions** [comment]
Cactus stop being a toxic freak, and stop saying "go to factions for pvp" its literally dodging the question, factions is awful and its even worse after the compass got removed and playercount dropped from 80 to 5. Also enable combat mcmmo skills, theyre already nerfed so it will be okay to add them in. It will spice up pvp and make it more fun and enjoyable.

**Comment by Cactusinapumpkin** [comment]
It’s just a suggestion Casper no need for name calling

**Comment by jkmartindale** [comment]
> It’s just a suggestion Casper no need for name calling

...says someone who also seems to enjoy their fair bit of name calling on here. Pretty unprofessional ngl.

**Comment by Cactusinapumpkin** [comment]
I’d be happy to apologize for any unprofessional name calling please quote me and I can assess the issue.

**Comment by MineHero43** [comment]
> 10op10 I did not know you were able to make a comment without using 11 emojis. They are looking into a warplugin please be patient as we are trying to fix more important issues atm. War plugin has been suggested many times before and may be closer to becoming reality now that we are in 1.15. Please try the factions server in the meantime it is pvp/raid oriented and not really build oriented like towny where you build towns, nations, economies, and relations between others.
> 
> It may seem like a doable solution that’s not complicated but we are trying to focus on more complicated detrimental issues affecting the server preformance

If it's doable and not complicated then why not add it? It's a simple and feasible alternative to a war plugin which even if they are "looking into one" as you say, would still take a while to come around.

**Comment by Cactusinapumpkin** [comment]
Well I didn’t say it was doable and not complicated, I said it may seem that way. The people in control of this may not consider enhancing the pvp experience as a useful use of resources due to much more important issues. Please try to be patient as we identify and assess the situation. I have personally offered suggestions on ways to fix the low player count in factions and hopefully it will be implemented soon.

**Comment by MineHero43** [comment]
> Well I didn’t say it was doable and not complicated, I said it may seem that way. The people in control of this may not consider enhancing the pvp experience as a useful use of resources due to much more important issues. Please try to be patient as we identify and assess the situation. I have personally offered suggestions on ways to fix the low player count in factions and hopefully it will be implemented soon.

How is factions relevant to this though? This is a suggestion for towny ._.

**Comment by Cactusinapumpkin** [comment]
I simply suggested trying factions because I believe factions is more “war oriented”.

**Comment by Cactusinapumpkin** [comment]
Please forgive me as I am only trying to enhance your game experience by offering suggestions

**Comment by MineHero43** [comment]
> I simply suggested trying factions because I believe factions is more “war oriented”.

Factions is more raider and mass griefer oriented. When you say "just go play factions" you fail to realise that no one is asking for the ability to be able to mass grief towns or blast them out of existence. We're simply asking for the ability for two rival nations to be able to face each other in an open battlefield. Suggestions like this one aim to further enhance that essential part of a geopolitical server.

**Comment by Cactusinapumpkin** [comment]
I’m sorry you must have misunderstood or accidentally misquoted what I said because I said, “please try the factions server in the meantime it is pvp/raid oriented...”

**Comment by Cactusinapumpkin** [comment]
This is not a new idea, this is a continued attempt to force something that the people in control of this decision do not believe the the towny server is ready for or may be to difficult to implement at the current moment. We will take your ideas into consideration. Thank you

**Comment by Cactusinapumpkin** [comment]
This is not the final word as I am not urging you to close the ticket. It’s still open to suggestions from other players and people in control of the decision whether or not to implement anything. I could be completely wrong and Karl could completely disagree with me and add it tomorrow for all I know. But you will need to be patient until he has the final word.

**Comment by MineHero43** [comment]
> This is not the final word as I am not urging you to close the ticket. It’s still open to suggestions from other players and people in control of the decision whether or not to implement anything. I could be completely wrong and Karl could completely disagree with me and add it tomorrow for all I know. But you will need to be patient until he has the final word.

Alright, fair, thanks for your input anyway

**Comment by jkmartindale** [comment]
> I’d be happy to apologize for any unprofessional name calling please quote me and I can assess the issue.

Literally only because you asked:
["10op10 I did not know you were able to make a comment without using 11 emojis"](https://github.com/EarthMC/Issue-Tracker/issues/1069#issuecomment-614669345)
["I would think minehero of all people would understand..."](https://github.com/EarthMC/Issue-Tracker/issues/1068#issuecomment-614619300)
["10op10 is that your name or how old you are?"](https://github.com/EarthMC/Issue-Tracker/issues/1054#issuecomment-612956882)
["I think asking ur mom for 10 bucks would be faster"](https://github.com/EarthMC/Issue-Tracker/issues/977#issuecomment-596787175)

I misremembered there being more name calling because, full disclosure, I find you annoying for...some reason. That's on me, and I do my bets to stay objective.

**Comment by Cactusinapumpkin** [comment]
Hmm these seem more like observations than actual name calling and full disclosure a lot of people could consider the same for you.

**Comment by stzups** [comment]
@Cactusinapumpkin You should follow the [Github Community Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines).

These are examples from the Community Guidelines

- Don't post anything that a reasonable person would consider offensive
- Treat each other with dignity and consideration in all interactions
- Avoid name-calling, ad hominem attacks, responding to a post's tone instead of its actual content

**Comment by watergod1234** [comment]
Wouldn’t be a hard nor performance heavy to add. I’ve seen this exact suggestion implemented on large servers before through a custom world guard build. Fix or Karl could easily pay a dev maybe $100 to fix up a plugin like this if they’re too busy to make one. It’d just need integration with towny chunk and wilderness borders.

**Comment by Cactusinapumpkin** [comment]
I am truly sorry and will follow the community guild lines continuing into
the future and treat everyone with dignity.

**Comment by unbatedaura409** [comment]
I remember a very long time ago I used to play on prison servers, and in the very middle of the prison there would be a pvp arena. You had to go through it to get to places to enchant, etc... Basically, if you engaged in combat while inside this specified area, if you got within a certain area of the outside, the entrance would be filled with glass, but only for you. I don't feel like this would be hard to add to towny.

**Comment by MineHero43** [comment]
> I remember a very long time ago I used to play on prison servers, and in the very middle of the prison there would be a pvp arena. You had to go through it to get to places to enchant, etc... Basically, if you engaged in combat while inside this specified area, if you got within a certain area of the outside, the entrance would be filled with glass, but only for you. I don't feel like this would be hard to add to towny.

Yup, old towny server I played on had exactly that same feature. If you were combat tagged in wilderness nearby town claims would be block by a layer of glass, making it unable to enter. The glass would vanish when you’re no longer tagged.

**Comment by 10op10** [comment]
> 10op10 I did not know you were able to make a comment without using 11 emojis. They are looking into a warplugin please be patient as we are trying to fix more important issues atm. War plugin has been suggested many times before and may be closer to becoming reality now that we are in 1.15. Please try the factions server in the meantime it is pvp/raid oriented and not really build oriented like towny where you build towns, nations, economies, and relations between others.
> 
> It may seem like a doable solution that’s not complicated but we are trying to focus on more complicated detrimental issues affecting the server preformance

We discover new things everyday

**Comment by SvenPhillips** [comment]
I completely agree with you. If towny gets some kind of plugin that makes sure people wont run off into their own town, i feel like there will be a larger appeal to pvpers. I remember when I first stumbled across earthmc a year ago, i saw a video of a war and people running into thier own claims, just hiding and healing before getting a couple more hits and then running away again. That was what made me, a towny loving player, to turn to factions. If a war plugin is added, it would enhance the gameplay and make it so that  people can actually conquer the world.

**Comment by watergod1234** [comment]
https://www.spigotmc.org/resources/tagspawnprotection-visual-combat-region-protection-1-7%E2%80%931-15.6511/

https://youtu.be/5Lh86rfpXfg?t=50

Something literally exactly like this but with towny claims as opposed to world guard regions.

**Comment by KarlOfDuty** [comment]
That would be a big hit on performance which is something we cannot afford at this time at least.
