### ISSUE TITLE
[BUG] Town Name

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1070]
Bug is only on towny.

Bug does not allow you to change your town name, unless you have a certain amount of gold in the town bank

**To Reproduce**
Remove all gold from town bank
try /t set name (example)

It should change your town name, without having to pay
![townyfucked](https://user-images.githubusercontent.com/42659943/79483749-eaa71e00-7fcf-11ea-96bb-05d534df8093.png)

**Comment by KarlOfDuty** [comment]
This is not a bug, town and nation renaming will cost some gold from now on.
