### ISSUE TITLE
[Feature] Allow Premium Nation Leaders to Change Their Icons

### ISSUE THREAD

**Issue by Mango-Monkey** [EarthMC/Issue-Tracker#1072]
Recently, the new Premium rank was added, with one of its abilities being to change the color of a nation’s towns. I believe this should work to allow a nation’s icon to be changed as well. I have seen on other servers the ability to have all sorts of icons, including nation flags, though I’m sure it could allow custom icons as well. This, like the colors, would allow nations to make themselves distinct from others, as well as promote the Premium rank even more. I think this would be a great addition to the server, and would love to see it added.

**Comment by Conmqn** [comment]
I think this is a good idea but it would be pretty hard and cause more problems as is to the server.

**Comment by jkmartindale** [comment]
> I think this is a good idea but it would be pretty hard

Kinda this, yeah. Dynmap-Towny has the ability to customize icons on a per-nation basis so I don't think it would cause server issues, but as far as I can tell the only built-in way to add new icons is by uploading files to the dynmap server. Unless you're content with the built-in Dynmap icons (below), EarthMC would need to find or develop a plugin to safely add new icons from banners or whatever.  
![image](https://user-images.githubusercontent.com/11380394/79674608-05c98780-81a2-11ea-9d5e-b34463877722.png)

I would like to see flags on the dynmap to make it easier to find specific nations. In crowded places like Europe I have to guess and check by clicking on each nation capital in the area.

**Comment by FutureLemon** [comment]
> I would like to see flags on the dynmap to make it easier to find specific nations. In crowded places like Europe I have to guess and check by clicking on each nation capital in the area.

That just sounds like a problem by itself

**Comment by AndrewCheedle** [comment]
@Fruitloopins idea

**Comment by CorruptedGreed** [comment]
Currently not possible with the technology, but it would be a good feature to add
