### ISSUE TITLE
Towns cost gold to rename?

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1073]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 10op10** [comment]
fuck

**Comment by KarlOfDuty** [comment]
Ah sorry about that, didn't realise that was live yet.

**Comment by 10op10** [comment]
> Ah sorry about that, didn't realise that was live yet.

Was gonna rewrite as i messed it up lmao, but i tried renaming my town but it said "you do not have enough gold in your town"
