### ISSUE TITLE
[BUG] Players are still able to escape combat with /t spawn 

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1074]
**Server**
Towny

**Describe the bug**
Whilst in conbat players can do /t spawn and it teleports them back to the town spawn even though they are moving etc, this can be abused by many players and overall ruin the pvp aspect.

**To Reproduce**
Player hits you then you tpye /t spawn and it teleports you 

**Expected behavior**
Its supposed to say " Teleportation cancelled".

**Screenshots**
https://www.youtube.com/watch?v=NQ3XeH8T2so&feature=youtu.be

**Comment by KarlOfDuty** [comment]
Yes, we are aware. The server needs to restart to fix it.
