### ISSUE TITLE
[BUG] Alchemy Only Giving XP on Third (Redstone / Glowstone) and Fourth Brew (Gunpowder)

### ISSUE THREAD

**Issue by Rndm-Prsn** [EarthMC/Issue-Tracker#1075]
**Server**
Towny

**Describe the bug**
[see title]

**To Reproduce**
1. Try to brew something.

**Expected behavior**
You should get alchemy XP from all of the times you brew.

**Screenshots**

**Additional context**
Yes, I am placing in the ingredients manually.

**Comment by Conmqn** [comment]
Well i think its giving the xp its just a very tiny amount or its just the server has been timing out recently so that might be the case of why it doesn't work all the time.

**Comment by Rndm-Prsn** [comment]
My bad sorry I did not realise you needed to put in ingredients every time.
