### ISSUE TITLE
Dynmap logging.

### ISSUE THREAD

**Issue by OrangeJuiceMoosee** [EarthMC/Issue-Tracker#1076]
**Is your feature request related to a problem? Please describe.**
I want to be able to view dynmap when the server started to present day.

**Describe the solution you'd like**
I would like on the EarthMC website to have a section that you can pick a day and it will load that dynmap, allowing you to scroll in look at the nations and towns, be able to click on them and see how many residents they have and what nation they are in.

**Additional context**
If the staff hasnt saved any it could just be from now until the future.

**Comment by jkmartindale** [comment]
This was suggested in #307. Dynmap doesn't have something built in for that, and if it did that would take up huge amounts of storage.

**Comment by FutureLemon** [comment]
> This was suggested in #307. Dynmap doesn't have something built in for that, and if it did that would take up huge amounts of storage.

Dude lmao you're a legend how did you find that issue so fast?

**Comment by jkmartindale** [comment]
> Dude lmao you're a legend how did you find that issue so fast?

I've been reading past issues to get a little caught up on EarthMC history and come up with things to add to the FAQ page. This was an issue I read a couple days ago so it wasn't hard to find.
