### ISSUE TITLE
[Mechanic] Grant mcmmo.commands.inspect.far permission to all players

### ISSUE THREAD

**Issue by jkmartindale** [EarthMC/Issue-Tracker#1077]
**Is your feature request related to a problem? Please describe.**
Players used to only have access to `/inspect` on players that were online and close to them. However, mcMMO-Dev/mcMMO@38bc60b removed the setting to disable running `/inspect` on offline players. Now we're able to inspect offline players, but if they're online we can only do so if we're close enough.

I don't see the point in having a proximity restriction if we can just wait until the player is offline.

**Describe the solution you'd like**
Remove the `/inspect` proximity restriction by granting the `mcmmo.commands.inspect.far` permission to all players.

**Comment by FutureLemon** [comment]
I approve this is very epic

**Comment by jkmartindale** [comment]
works_on_my_machine.txt

**Comment by jkmartindale** [comment]
no it don't I'm an idiot

**Comment by Prismary** [comment]
Is this still recent?

**Comment by jkmartindale** [comment]
Yeah, nothing has changed. You can still inspect McMMO stats for any offline player but only online players that are near you.

**Comment by Warriorrrr** [comment]
Done
