### ISSUE TITLE
res/n/t spawning

### ISSUE THREAD

**Issue by GitMocc** [EarthMC/Issue-Tracker#1078]
**Is your feature request related to a problem?**The new spawning thing: When I logged in to the server a few days ago you could instantly TP to places, no cooldown, just instantly. Now they have numbed it down to 3 seconds, but you can move now while you are waiting to get teleported. This completely makes PVP futile 

**Describe the solution you'd like**
The server got the combat logging plugin for a reason, so no one can escape a fight by logging. The TP system now is equivalent to combat logging, maybe not in quickness but how you can just TP out while being hit. I request that you either cant TP out when being PVP'd or just make it 3 seconds again and if you move it cancels, like normal

**Additional context**

**Comment by FutureLemon** [comment]
Basically duplicates of #1066, #1068 and #1074. It will be fixed don't worry just be patient.

**Comment by suneettipirneni** [comment]
This is fixed in https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.5 upstream you'll need to wait for the new jar to be deployed.

**Comment by suneettipirneni** [comment]
This is fixed in https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.5 upstream you'll need to wait for the new jar to be deployed.

**Comment by KarlOfDuty** [comment]
Fixed on next restart.
