### ISSUE TITLE
[BUG] I cant put my plot forsale

### ISSUE THREAD

**Issue by Garnmax77** [EarthMC/Issue-Tracker#1079]
**Server**
Earthmc.net

**Describe the bug**
i wanted to leave the town with my friend and i left the town and wanted to put then my house for sale but it says i have no permission

**To Reproduce**
 i left the town and wanted to put then my house for sale but it says i have no permission

**Expected behavior**
that it puts for sale

**Additional context**
i cant put my house for sale

**Comment by FutureLemon** [comment]
When you leave a town it automatically evicts you from that plot unless it's an embassy.

**Comment by DasCodes** [comment]
Please contact the staff on support Discord for this issue.
