### ISSUE TITLE
Air Blocks Turning into Solid Blocks around spawners.

### ISSUE THREAD

**Issue by ProvingUnique** [EarthMC/Issue-Tracker#108]
**Server**
TerraNova

**Describe the bug**
all air blocks around our spawner turn into soild blocks. sometimes when leaving the area and coming back its back to normal. sometimes not

**To Reproduce**
not sure what causes

**Expected behavior**
air to air, not to do this

**Screenshots**
![2018-11-06_20 49 12](https://user-images.githubusercontent.com/44824434/48105687-71b26d00-e206-11e8-8d0b-db80399f1a0e.png)
![2018-11-06_20 56 06](https://user-images.githubusercontent.com/44824434/48105688-71b26d00-e206-11e8-8d2f-ca533fd762d3.png)

**Additional context**

**Comment by ProvingUnique** [comment]
it appears that removing all players from the area and returning fixes this. I don't know what causes it

**Comment by KarlOfDuty** [comment]
wtf

**Comment by MSatrokrm** [comment]
What kind of feckin mob grinders are you making

**Comment by ProvingUnique** [comment]
To be clear, there are four blaze spawners in there, and I did not build this out of red stone and emerald ore. This is the second time this has happened

**Comment by ProvingUnique** [comment]
If you punch them, visually they revert back to air. But physically behave like ghost blocks, won’t let you walk through them.

The first time it happened I called 1212 to come look, he was away from the chunks, and when he got there he couldn’t see the effect.

Gonna be hard for an outsider to experience this

**Comment by KarlOfDuty** [comment]
Is this still happening?

**Comment by ProvingUnique** [comment]
I haven’t only experienced this twice and I know one other had experienced it as well, I haven’t heard of anyone else having this issue lately

**Comment by KarlOfDuty** [comment]
Ok, it's likely it was just an issue with a previous build in that case.
