### ISSUE TITLE
Disallow people to teleport while combat tagged

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#1081]
You can literally run away and /t spawn during PVP it's really annoying and I don't even play anymore. Please revert it back to the way it was where you can't move or be PVP tagged to teleport.

**Comment by suneettipirneni** [comment]
This is the fifth time a ticket has been made for this, the response is the same for each of them:

> This is fixed in https://github.com/TownyAdvanced/Towny/releases/tag/0.96.1.5 upstream you'll need to wait for the new jar to be deployed and/or updated.
