### ISSUE TITLE
[Mechanic] Make combatlog ignore towny claims' non-pvp

### ISSUE THREAD

**Issue by kiadmowi** [EarthMC/Issue-Tracker#1082]
The problem at hand:
Players sitting at the border of their claims, poking out every few seconds to get a free swing off at attackers and hiding in the claim again with no worries or consequence, leaving attackers feeling frustrated and scammed.

Suggested solution:
Make the already existing combatlog ignore towny claims' pvp settings and let any combat-tagged players be attackable in whatever claims they walk into.  If someone attacks a combat-tagged player in claims, they become combat-tagged too and in turn attackable.  This ensures that players can't abuse the safety of their claims to waste enemies' time and instead have to wisely choose when to engage or take the L.
Also, while on the topic of combatlog, I believe towny tp commands work while combat-tagged still, which'd be a nice thing to fix as well.

**Comment by unbatedaura409** [comment]
Agree 100%. I don't think this would take a large hit on server performance, like Karl said in MineHero's ticket. It's not like the server is already on its knees, or anything. All that would be required would be to have a tagged player keep the tag when they re-enter claims. Simple as that.

**Comment by Prismary** [comment]
Not sure how easy this is to implement, but I definetly agree it'd make sense.

**Comment by jkmartindale** [comment]
We've got an anti-claimhiding plugin at this point, it just works a little differently

**Comment by Prismary** [comment]
> We've got an anti-claimhiding plugin at this point, it just works a little differently

Right, I forgot. Don't often PvP myself so I'm not always up to date on topics like these; seems like this is solved then
