### ISSUE TITLE
[Feature] New Collectible item for Premium players

### ISSUE THREAD

**Issue by MrBGuns** [EarthMC/Issue-Tracker#1083]
Last month I bought premium, and I was very pleased with it's features. I loved the collectible item, but when I bought premium this month again I was looking forward to see what the collectible would be now. But it seems that it is the same. I think the Collectible item should change every month. After all that seems fair for the amount of money we are paying monthly for premium. If EMC staff does change this, would it be possible to change the duplicate item I have with the new item? Thanks in advance!
![image](https://user-images.githubusercontent.com/64258983/80205407-d942bf00-862a-11ea-9b98-611b70ab427a.png)

**Comment by Prismary** [comment]
Not sure whether this has ever been changed, is it still a recent issue?

**Comment by jkmartindale** [comment]
Pretty sure this was solved by introducing mystery crates

**Comment by Prismary** [comment]
> Pretty sure this was solved by introducing mystery crates
