### ISSUE TITLE
[Bug] Premium players can use the McMMO party teleport command

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1084]
**Server**
Towny

**Describe the bug**
Currently the new Premium rank can teleport to eachother like /tpa on Factions with a special command from the McMMO Party system. I don't think this is intended to be since this gives them a huge edge over other people in PvP and travelling.

**To Reproduce**
1. As a Premium player do /party teleport [different Premium player in your party]
2. The other Premium will have to do /party teleport accept
3. Quick way to teleport to each other across the map.

**Expected behavior**
The expected thing to happen is to get this message:
![image](https://user-images.githubusercontent.com/44688587/80254117-dec7f580-867a-11ea-8c35-c7c835a7cefc.png)

**Additional context**
Why should it be disabled? Well it should be disabled because it's a very overpowered thing and is really close to be "pay to win" since no one else has access to it except the Premium players.

**Comment by SvenPhillips** [comment]
I agree. There should be the same limiting factors of normal teleports, so then the premium players don't get an advantage over other players.

**Comment by DasCodes** [comment]
This shouldn't be a thing. Is this still an issue?
