### ISSUE TITLE
[Bug] Nether mobs still don't spawn.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1085]
**Server**
Towny

**Describe the bug**
The nether mobs haven't been spawning ever since the upgrade to 1.15. In #1037 we were told it was disabled due to lag, but this has never been the case even in times where EarthMC was laggier than it now is. I don't think it was meant to be since it went paired with the update to 1.15.

**To Reproduce**
1. Go to the Nether
2. See if any mobs spawn
3. They don't

**Expected behavior**
Mobs should spawn and we can get our valued Wither Skeletons to make beacons and continue the importancy of Beacons on the server.

**Comment by Prismary** [comment]
No longer a recent issue, many changes have been made to the nether since including a full reset and numerous updates to spawning behaviour. Mob spawns remain a problem, it isn't easy to solve however as it's crucial in reducing lag. Closing for now.
