### ISSUE TITLE
[BUG] Dynmap Rendering Stones

### ISSUE THREAD

**Issue by TJPlaysNow** [EarthMC/Issue-Tracker#1086]
**Server**
Towny

**Describe the bug**
The Dynmap shows stone, granite, andesite, and diorite slabs as smooth stone slabs.

**To Reproduce**
1. On Dynmap and in game you can view the road created at x -16510, z -7300 and see it shows the smooth stone slab texture in place where it should show the stone texture.

**Expected behavior**
The texture should match the slab and be the stone texture not smooth stone.

**Screenshots**
![image](https://user-images.githubusercontent.com/17147463/80271521-7aab2e80-8686-11ea-8547-830c7915469b.png)
![image](https://user-images.githubusercontent.com/17147463/80272278-89e1aa80-868d-11ea-8ce3-f70c2abfe55e.png)

**Additional context**
Not sure if this is any help, but I believe Dynmap allows you to custom add the textures for the blocks without them having to do any work. https://github.com/webbukkit/dynmap/wiki/Class-org.dynmap.hdmap.renderer.StairBlockRenderer

**Comment by FutureLemon** [comment]
Seems like dynmap isn't fully optimised for 1.15

**Comment by Conmqn** [comment]
I agree with futurelemon here, it could also be since the blocks are basically both stone its programmed to look the same.

**Comment by KarlOfDuty** [comment]
Indeed, we will just have to wait and see if dynmap updates.
