### ISSUE TITLE
[BUG] I cant set my homeblock

### ISSUE THREAD

**Issue by mRNeFF** [EarthMC/Issue-Tracker#1087]
**Server**
Which server the bug is on. : 
On the towny server

**Describe the bug**
When I order /t set homeblock or /t spawn the plugin responds to me:
Town as not set a spawn location
so I can't do anything in my city like claiming a chunk or putting my gold

**Expected behavior**

I thought I could change my spawn point with these commands but that is not the case

**Screenshots**
![gdfg](https://user-images.githubusercontent.com/64364773/80310388-b0f9c280-87da-11ea-9a3e-b503fcbe1b48.PNG)
![gdfgdf](https://user-images.githubusercontent.com/64364773/80310389-b1925900-87da-11ea-8f6e-eacf6fb88969.PNG)

**Additional context**

before changing my spawn point, when I was / t spawn he marked me
t spawn was forbidden

**Comment by Lagann311** [comment]
do /t set homeblock then
/t set spawn
