### ISSUE TITLE
[Bug] Non allies can /n spawn

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#109]
**Server**
Earthmc

**Describe the bug**
Texas_republic allied with my nation Luzon_Empire but we didn't ally back, 1212 were then able to do /n spawn without our approval

**To Reproduce**
1. Create nation
2. Ally any other nation
3. Do /n spawn to them

**Expected behavior**
"this nation has not allied you" to appear

**Comment by shirazmatas** [comment]
Lol im stupid my nation is public

**Comment by KarlOfDuty** [comment]
Should be fixed by #110
