### ISSUE TITLE
[BUG] wither despawn

### ISSUE THREAD

**Issue by Adriix17** [EarthMC/Issue-Tracker#1090]
Earth Mc - Towny

I spawn a wither to rename it and have the nice animation, but he has despawn.

**Comment by FutureLemon** [comment]
This has happened often and even to me. If you want a refund make a ticket in the support Discord by typing -new. Here is the link to the support Discord if you are not already in it: https://discord.gg/RySahU4

**Comment by JaVolimKatarinu** [comment]
Please do refund issue on EMC support discord.
