### ISSUE TITLE
highly requested chat

### ISSUE THREAD

**Issue by TurkDarthJoker** [EarthMC/Issue-Tracker#1091]
Hello Sir, there are quite many turks in EMC, and we find it really hard to communicate with
one another in global chat. I have been muted three times during a normal conversation, so were my many friends. I would like to request /turkish chat to be added to EMC. Thank you, have a nice day.
(I do not request this as a means of joke, some may think this is for meme purposes but it is not)

**Comment by KarlOfDuty** [comment]
As the chat channels are really buggy at the moment we won't be adding any more right now. I recommend using nation orn town chat to talk to your friends for now.

**Comment by TurkDarthJoker** [comment]
They are in other nations, and we dont talk 7/24, can we be allowed to talk turkish in global chat?

> As the chat channels are really buggy at the moment we won't be adding any more right now. I recommend using nation or town chat to talk to your friends for now.

**Comment by FutureLemon** [comment]
> They are in other nations, and we dont talk 7/24, can we be allowed to talk turkish in global chat?

Make an McMMO party and use /pc
