### ISSUE TITLE
Plot amounts

### ISSUE THREAD

**Issue by OrangeJuiceMoosee** [EarthMC/Issue-Tracker#1092]
**Is your feature request related to a problem? Please describe.**
I am always annoyed when I need to claim plots and I can't because of the max of 50. I usually have more than one project on the go and 50 plots just isn't enough.

**Describe the solution you'd like**
I would like the allowed amount of plots to be increased not for a town but for individual people. Maybe double or more. Could possibly be a rank that you have to buy or something. I just need a lot of plots and 50 does not cut it.

**Additional context**
None

Thumbs up if you support! =D

**Comment by NS4530** [comment]
I’ve personally had the issue of having to build large structures but having to build it in sections due to limited numbers of claims. Would be really convenient if there was an increased amount of chunks a person could own.

**Comment by PoppyK** [comment]
This is a great suggestion!  I have noticed since having group plot perms, its been harder to manage my owned plots.  My museum is 16 plots alone, and that is only one build in my town.  I'd love to see personal plot limit increased!

**Comment by JaVolimKatarinu** [comment]
If you are the mayor of the town, you can keep those plots in ownership of town, so that 50 plots limit would be bypassed?

**Comment by Cactusinapumpkin** [comment]
Oh yea I forgot you could own a plot of your own land. I claimed a bunch of my plots and then unclaimed them because I ran out of plots when I tried getting an embassy.

**Comment by FutureLemon** [comment]
> Oh yea I forgot you could own a plot of your own land. I claimed a bunch of my plots and then unclaimed them because I ran out of plots when I tried getting an embassy.

Same the limit is just silly with so many towns being so big you have so much to do and to make sure your builders and trusted can't always touch them.

**Comment by Fruitloopins** [comment]
I would love this feature. I own a map art canvas in my town which is 64 chunks alone and I commonly let players use it but the downside is I have to set up 4 plot groups of 16 chunks, claim half and /res friend add them and let them claim the other half as embassies. It would be great to let someone claim all 64 and not have to heavily alter my plot perms elsewhere to account for a player just using that area.

Although I do not believe these extra plots should be locked behind a paywall as suggested by OrangeJuiceMoosee as that would be pay to win.

**Comment by Scottydude456** [comment]
Maybe it could be a thing that would cost gold?

**Comment by KarlOfDuty** [comment]
Done.
