### ISSUE TITLE
[Feature] Fix !ip command on discord and advertise /joinqueue factions

### ISSUE THREAD

**Issue by SvenPhillips** [EarthMC/Issue-Tracker#1094]
**Is your feature request related to a problem? Please describe.**
With the removal of the compass, no new player will be able to find the factions server from the lobby. And even if they know that the Factions server exists, it would also be difficult for them to find the ip.

**Describe the solution you'd like**
Have a sign at spawn saying that you can access the factions side of the server with /joinqueue factions. Also, when you do /ip, the factions bot says earthmc.net,  which is not the IP for the factions server. 

**Additional Context**
![AC085112-D504-4CD1-B499-4B686CE3F5FF](https://user-images.githubusercontent.com/58676640/80786938-f0f1da00-8b39-11ea-8a3d-c3e365da8456.jpeg)

**Comment by jkmartindale** [comment]
I think this got in because of the last issue asking for Factions to be promoted, lol

![image](https://user-images.githubusercontent.com/11380394/80816811-75217d00-8b8d-11ea-97be-41b61c61af4d.png)

**Comment by SvenPhillips** [comment]
> I think this got put in because of the last issue asking for Factions to be promoted, lol
> 
> ![image](https://user-images.githubusercontent.com/11380394/80816811-75217d00-8b8d-11ea-97be-41b61c61af4d.png)

Didnt see that i guess, but the !ip part of it is still an issue.

**Comment by DasCodes** [comment]
Fixed.
