### ISSUE TITLE
Not being able to join the queue

### ISSUE THREAD

**Issue by Krafff** [EarthMC/Issue-Tracker#1095]
**Server**
Towny

**Describe the bug**
Sometimes when I try and join the towny server it doesn't put me into the queue. 

**To Reproduce**
I don't know what this means

**Expected behavior**
I'm not sure what this means

**Screenshot**
https://imgur.com/gallery/kiURXr6
https://imgur.com/gallery/jTPlSFB

**Additional context**
It's annoying

**Comment by jkmartindale** [comment]
Sometimes you need to kickstart it with `/joinqueue towny`

idk why it sometimes doesn't do that for you automatically, that's just the way it be sometimes

**Comment by JaVolimKatarinu** [comment]
Just use /joinqueue towny if you arent placed in queue automatically.
