### ISSUE TITLE
[BUG] Claim

### ISSUE THREAD

**Issue by Akscoop** [EarthMC/Issue-Tracker#1096]
**Server**
The bug is on the EarthMC Towny Server.

**Describe the bug**
The bug is with the claim command. When I try to claim a land on towny, its say to me that its to close from an other town home block, so I can't claim land anymore. Its happening when I'm doing /t claim. This is a screenshot from the bug.

**To Reproduce**
1. /t claim
2. See error

**Expected behavior**
I was thinking of claiming more land to make my town bigger.

**Screenshots**
![Capture d’écran 2020-05-03 à 22 41 22](https://user-images.githubusercontent.com/64762021/80932924-8a65f980-8d8f-11ea-8905-ab04254fd653.png)
![Capture d’écran 2020-05-03 à 22 04 27](https://user-images.githubusercontent.com/64762021/80932928-8e921700-8d8f-11ea-9723-58efebe4bca4.png)

**Comment by suneettipirneni** [comment]
That’s not a bug, that behavior is completely intentional. It’s there to prevent claim blocking.

**Comment by FutureLemon** [comment]
Where is your town on the Dynmap and is it close to any other towns?

**Comment by jkmartindale** [comment]
Here's where [Ulsan](https://earthmc.net/map/?worldname=earth&mapname=flat&zoom=6&x=23532&y=64&z=-7182) is (right of center)

![image](https://user-images.githubusercontent.com/11380394/80980595-0db23a00-8de6-11ea-8f6d-c1ecf899424c.png)

Just eyeballing it, I'm pretty sure the top left corner is within 6 claim blocks of Koksan so northern expansion would be blocked if Koksan's homeblock is in its bottom right.

**Comment by FutureLemon** [comment]
Seems like it is not a bug but just a game mechanic. If the town is claimblocking you make a ticket in the support Discord by typing '-new'. If you are not in the support Discord yet join here: https://discord.gg/RySahU4

**Comment by riri2010** [comment]
![81488762-0c3ba400-9222-11ea-8394-1e833f833a5d](https://user-images.githubusercontent.com/50254131/81729225-7c277580-9440-11ea-8f49-2150f8d96ca5.png)
I have the same issue. there is no reason I shouldnt be able to claim towards the south-east. I have permission and border agreements with all 4 towns.

**Comment by Prismary** [comment]
Pretty sure this is no longer a thing.
