### ISSUE TITLE
[Feature] Fishing in Queue

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1097]
The concise description of the problem I am having is not being able to fish in the waiting queue. I kinda just want to vibe with a fishing rod and fish.  I dont want to parkour. I dont want to pve. I just want to have a nice rod and cast the line into the water. 

There are two ways to deal with this, build a fishing shack with a pond or just have a command or a way to craft fishing rods and let us fish in the water around the spawnblock.

![image](https://user-images.githubusercontent.com/51977107/81005299-baf37500-8e1b-11ea-8ee7-8eb3b9fe93ee.png)

![image](https://user-images.githubusercontent.com/51977107/81005359-cf377200-8e1b-11ea-98fb-cca270521df9.png)

![image](https://user-images.githubusercontent.com/51977107/81005414-eaa27d00-8e1b-11ea-9841-8b388a8b8c36.png)

![image](https://user-images.githubusercontent.com/51977107/81005479-01e16a80-8e1c-11ea-9998-9f1212e7eaa4.png)

![image](https://user-images.githubusercontent.com/51977107/81005567-2b01fb00-8e1c-11ea-9bd8-ebfd220f8b77.png)

https://www.amazon.in/Minecraft-Role-Play-Fishing-Playset/dp/B07B8ZR8XK

**Comment by Oln123** [comment]
1.This is oddly in depth 
2. This seems like a good idea to add some fun thing to do in queue

**Comment by jkmartindale** [comment]
This is the most important issue filed in the history of GitHub

**Comment by SvenPhillips** [comment]
they used to have some kind of Battle Royale style game to wait right?

**Comment by Colt44Magnum** [comment]
Not sure about that, but they have swim racing around the spawn block

**Comment by nipdip** [comment]
Another thing that could be nice to add is archery, shooting targets with a bow and arrow.

**Comment by Colt44Magnum** [comment]
> Another thing that could be nice to add is archery, shooting targets with a bow and arrow.

If more people comment on this and give it some likes I'll see about just editing this Feature Issue to add other things of peoples ideas, but currently I'll just keep it short and specific in order to hopefully get it through!

**Comment by Cactusinapumpkin** [comment]
dude i would love to fish in queue

**Comment by Colt44Magnum** [comment]
![2020-05-19_20 02 52](https://user-images.githubusercontent.com/51977107/82390121-db225700-9a0b-11ea-8e18-bbb5f1f54e76.png)

Fishing Rods Anyone???

**Comment by RoseBrugs** [comment]
> I think it could be better if there was a /kit fishing command to give you a fishing rod and preferably god fishing rod or you can just /kit fishing again for a new rod

This is a really good idea, would be epic to see in the queue :D

**Comment by nipdip** [comment]
There's one problem. You could use the fish you collect to gain hunger faster than the /feed command in the parkour.

**Comment by jkmartindale** [comment]
> You could use the fish you collect to gain hunger faster than the /feed command in the parkour.

I mean, once upon a time when hostile mobs still spawned in lobby, you could get food items and totems of undying from PVE. I don't see anything wrong with awarding light parkour lifelines for grinding a different lobby "minigame" (if you can call it that). It's not like finishing a parkour course will give you gold or anything other than lame bragging rights.

**Comment by Colt44Magnum** [comment]
Yeah! we gained a spot where we can chill/leave the computer and lean a weight on our spacebar for hours in order to get into the server! It's what I always wanted a place to do nothing! inb4 just do parkour, I hope you realize some people don't like doing parkour and that they do not find it fun. 

thank you for coming to my TED talk,
now please add activities for us to do other than holding spacebar and parkour...

**Comment by Colt44Magnum** [comment]
Gained more buildings no signs of any Fishing spots or the possibility of getting a rod. 

Its great though when the server goes down putting everyone into queue wondering if they really want to play anymore since they will just be waiting aimlessly in the queue. Though I guess we could all just go insane just doing parkour. Since everyone loves parkour

**Comment by MarkusAurelius124** [comment]
![is-your-video-game-good-does-it-have-a-fishing-30928514](https://user-images.githubusercontent.com/44880641/91653769-3274a080-eaac-11ea-8dbb-efc0ca093a27.png)

Absolute Fact.

**Comment by Colt44Magnum** [comment]
RIP Fishing in Queue, now I just finish the maize in a couple seconds once I get to the entrance

**Comment by Colt44Magnum** [comment]
Well since the server has dropped to only allowing 90 people on it at a time, queue is back to being as long as it was back during the summer. I think its prompt then to start again trying to get fishing in queue. I will re-assert my post for this cause

**Is your feature request related to a problem? Please describe.**

The concise description of the problem I am having is not being able to fish in the waiting queue. I kinda just want to vibe with a fishing rod and fish. I dont want to parkour. I can't want to pve since it has been removed a while ago. The maze I have already memorized and now takes a few seconds to complete, plus it doesn't seem like it will be finished and even if finished it will not change the lack of enjoyment I have while doing it.  I just want to have a nice rod and cast the line into the water. 

**Describe the solution you'd like**

There is already many bodies of water to fish in that have been added to the queue server, if some other body of water would be more satisfactory to the builders on the Staff team that seem to enjoy building in the queue world I would suggest building a floating island with a lake/pond with a fishing shack where one could acquire a rod from. Now I could see a problem with the rods being used to rod people off the world, which could annoy the people that enjoy parkour. I would suggest then that the only way to get off of this floating island would be to jump off and die, removing items in the inventory or to travel over a bridge where command blocks would be triggered removing any fishing rod from the inventory. This would satisfy those who want to fish and allow no disturbance in the parkouring communities enjoyment. 

A small fishing hut could be made with the island such as this
![image](https://user-images.githubusercontent.com/51977107/95124353-46ea2f80-0721-11eb-8e65-14920998f9e1.png)

Or a "large" fishing harbour with boats and other vessels of the sea
![image](https://user-images.githubusercontent.com/51977107/95124481-7e58dc00-0721-11eb-809c-538d453ca71b.png)

**Comment by tomatochip** [comment]
![3885BE87-F543-4905-AA8D-FF51FCAF6885](https://user-images.githubusercontent.com/27903218/95409569-e2c99600-08ef-11eb-8a3d-7b40a373c03c.jpeg)

A message for Fix and Karl

**Comment by Colt44Magnum** [comment]
With the new spawn and nothing to do in it after 10 minutes, I think fishing in queue should be added

**Comment by Warriorrrr** [comment]
Queue is literally unplayable without fishing.

**Comment by Colt44Magnum** [comment]
I think Warriorrr has a point, new queue is even further than unplayable because of the lack of fishing

**Comment by Colt44Magnum** [comment]
So with the advent of a new queue I think I need to edit some parts of this issue tracker. 

### Is your feature request related to a problem? Please describe.

The concise description of the problem I am having is not being able to fish in the waiting queue. I kinda just want to vibe with a fishing rod and fish. I dont want to parkour. ~~I can't want to pve since it has been removed a while ago. The maze I have already memorized and now takes a few seconds to complete, plus it doesn't seem like it will be finished and even if finished it will not change the lack of enjoyment I have while doing it.~~ I just want to have a nice rod and cast the line into the water. Currently queue is just people sitting around sometimes complaining about a queue and other times making general banter in the now enabled chat (thank you Warriorrrr).

### Describe the solution you'd like

There are many bodies of water on the queue islands which I think could be sutable for fishing. Previously I had suggested building a shack, that suggestion I think is still proper but it might be best to go another route. Merchants have been added to the server and I think new players should be introduced to the Merchants before getting on the towny server. In queue there should be a merchant that gives a vote crate (though other ways for the player to get gold would probably be better) the merchant then would sell a fishing rod for gold so that players can not only learn that merchants sell things but also that the currency is gold on the server. This in itself is a silent tutorial were the player doesn't actually realize they are in a tutorial and is beneficial because it doesn't lock an old player in a tutorial quest or menu. Then we have a fishing spot, any body of water I think would be good for fishing in, though I think some respect for the Nation of Madagascar should be given by creating a fishing location on the African Island where the Merchant would be located. Now I could see a problem with the rods being used to rod people off the world, which could annoy the people that enjoy parkour though I think the new queue has killed off any parkour enthusiast as there is none quickly accessible until you find it the first time ~~Is there anymore parkour than the pyramids or big ben???~~. This would satisfy those who want to fish and allow no disturbance in the parkouring communities enjoyment since it is dead.

### Suggestion also made by the Mod CactusinaPumpkin:
"I think it could be better if there was a /kit fishing command to give you a fishing rod and preferably god fishing rod or you can just /kit fishing again for a new rod"

### Comment from Warriorrrr (developer)
"Queue is literally unplayable without fishing."

### I think that adding fishing to the queue is beneficial for all plus it gives another place to add in ads for queue priority and premium

**Comment by WeirdGamerAidan** [comment]
Another idea to make the queue more fun is to make some way of getting into the old queue area
I honestly miss the old queue and wish emc mods could at least put out a world download for it

**Comment by jkmartindale** [comment]
> wish emc mods could at least put out a world download for it

👀 funny you should ask...

I made a Litematica schematic of the queue in February 2020 so I could practice the parkour offline. It's really old so it doesn't have the extra buildings branching off from the Atlas statue island, but it's better than nothing I guess.

Litematica schematic: https://files.jkmartindale.dev/EarthMC_Hub_2020-02-01.litematic
1.14.4 world download: https://files.jkmartindale.dev/EarthMC_Hub_2020-02-01.zip

Have fun

**Comment by WeirdGamerAidan** [comment]
Thanks
I had tried to use litematica, but i couldn't figure it out

**Comment by Prismary** [comment]
We have a PvP arena now, but still no fishing...

**Comment by Colt44Magnum** [comment]
Update, Fishing is fun in queue
![2021-12-03_18 31 49](https://user-images.githubusercontent.com/51977107/144686986-ff498f33-83bd-49c4-a847-e803e8da05c0.png)
![2021-12-03_18 34 03](https://user-images.githubusercontent.com/51977107/144686987-87aecbfa-694d-4af7-90b3-a4b080471b7a.png)

During maintenance today Warrior gave IceFrosti and I fishing rods
![2021-12-03_18 51 35](https://user-images.githubusercontent.com/51977107/144687083-7c3fd45d-9f86-43b8-b683-49d4162c12aa.png)

![2021-12-03_18 51 23](https://user-images.githubusercontent.com/51977107/144687082-d866c2b1-9936-45fc-a535-9024a1f7f512.png)
 
We had fun, and people seemed to enjoy the cosmetics

**Comment by Cheeeks** [comment]
i want fishing rod now

**Comment by Colt44Magnum** [comment]
![image](https://user-images.githubusercontent.com/51977107/144687589-cd65c261-70e3-4b8d-8fc0-197e4fb414fa.png)


WE DID IT
