### ISSUE TITLE
XP sharing still isn't working

### ISSUE THREAD

**Issue by MaybeRyan** [EarthMC/Issue-Tracker#1102]
**Server**
Which server the bug is on.
EarthMC Towny

**Describe the bug**
**_In the party we were in that has xp sharing, me and my friend could be right next to each other fishing, and the xp won't share between us._**
**To Reproduce**
1. Have a party where xp sharing is enabled.
2. Fish with your friend.
3. See that the xp is not sharing.

**Expected behavior**
I expected the xp from fishing to share with me and my friend.
**Screenshots**

**Additional context**
The mods said that they fixed it, but it still isn't working.

**Comment by FutureLemon** [comment]
It works for me and my party, you need to be quite close to each other. You can see it by doing /party and if the lights are green you are close enough to share your mcmmo xp.
![image](https://user-images.githubusercontent.com/44688587/81489156-cb1fb000-9272-11ea-8fd6-41ebd58bb937.png)
