### ISSUE TITLE
Clarification on Rule 2.4

### ISSUE THREAD

**Issue by sirinfinity** [EarthMC/Issue-Tracker#1103]
I was recently banned for saying N***** (I said this with the asterisks). I am not sure how this is considered a bypass as the only visible letter is the letter N. I have already made a ticket but the mods have not responded in a few days. If this is not a bypass, could I get unbanned?

**Comment by sirinfinity** [comment]
im literally going everywhere and asking this question, dont be surprised if you find this question elsewhere

**Comment by SvenPhillips** [comment]
Honestly I dont think this is a bypass lol

**Comment by sirinfinity** [comment]
SvvenPhillips who are you

**Comment by SvenPhillips** [comment]
Hehe
