### ISSUE TITLE
[Beta] Up the claim limit

### ISSUE THREAD

**Issue by GRAnimated** [EarthMC/Issue-Tracker#1105]
Right now, there's only 1 or 2 townless players online at a given time. With the influx of gold, we would like to claim chunks but we can't because everyone has started their own towns.

I'm sure everybody would like to see the claim limit raised from something like 10 to 20 for the mayor and for each resident to increase it by something like 12, not 8.

**Comment by FutureLemon** [comment]
Bruh if instead of everyone making their own nation would just play a little bit more together you would get a nation bonus bigger than 10.

**Comment by HydrolienF** [comment]
That’s not complicated to fined a huge nation to have +100 or 200 claim.

**Comment by KarlOfDuty** [comment]
As stated above, this can be increased using the nation bonus.
