### ISSUE TITLE
[bug][beta] Basic Towny perms

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#1106]
**Server**
beta

**Describe the bug**
I don't have perms for `/plot perm hud` or `/res toggle map` (possibly other commands as well).

**To Reproduce**
1. From a Mod account with no town, run a command such as `/plot perm hud` or `/res toggle map`.
2. Get insufficient perms error message.

**Expected behavior**
For `/plot perm hud`: The plot permission heads up display should open.
For `/res toggle map`: the towny map should display when I cross chunk boundaries.

**Comment by KarlOfDuty** [comment]
Is this only for mods or for other players too?

**Comment by FutureLemon** [comment]
Doesn't work for regular players either @KarlOfDuty

**Comment by HelloGaming123** [comment]
> Doesn't work for regular players either @KarlOfDuty

It only works for mayors on many towny servers like S#MPEarth I could not do /plot perm hud till I made a town.
