### ISSUE TITLE
[BUG] /n spawn Australia not autofilling

### ISSUE THREAD

**Issue by VulgarPotato** [EarthMC/Issue-Tracker#1107]
**Server**
Towny

**Describe the bug**
doing "/n spawn Austra" and then pressing tab does not show Australia, instead showing another nation (Australian_Union)

**To Reproduce**
^^^

**Expected behavior**
https://cdn.discordapp.com/attachments/705337866087301130/705338884149739540/image0.jpg

**Screenshots**
![Screen Shot 2020-05-09 at 12 27 28 pm](https://user-images.githubusercontent.com/59647840/81500445-9d3f7780-9315-11ea-98c4-d4cd07c1d88b.png)

**Additional context**
I get that this is a tiny bug that only wastes like 10 seconds, but idk if it affects other nations or not
I think the name itself might be cursed? The current nation of Beresford also used to be called Australia, and back then it also didn't autofill. 
Someone always gets tripped up like at least once a week

**Comment by FutureLemon** [comment]
I have noticed this too, other Australian nations do, but Australia itself doesn't.

**Comment by VulgarPotato** [comment]
![Screen Shot 2020-05-21 at 6 05 10 pm](https://user-images.githubusercontent.com/59647840/82558567-49ece500-9bb1-11ea-8c60-a004dbf4e66a.png)

**Comment by VulgarPotato** [comment]
![Screen Shot 2020-05-24 at 10 39 19 am](https://user-images.githubusercontent.com/59647840/82752606-7c415100-9e02-11ea-86d5-bf21fddb57a2.png)

**Comment by VulgarPotato** [comment]
![Screen Shot 2020-05-24 at 11 20 33 am](https://user-images.githubusercontent.com/59647840/82752616-895e4000-9e02-11ea-833f-ad9835f55a96.png)

**Comment by VulgarPotato** [comment]
![Screen Shot 2020-05-24 at 11 47 12 am](https://user-images.githubusercontent.com/59647840/82752629-9a0eb600-9e02-11ea-8a88-b02d92ba89cc.png)

**Comment by VulgarPotato** [comment]
![Screen Shot 2020-05-27 at 11 34 57 pm](https://user-images.githubusercontent.com/59647840/83099113-b7d46780-a0ef-11ea-9ee4-4fb066152897.png)

**Comment by KarlOfDuty** [comment]
Should be fixed.
