### ISSUE TITLE
{Bug} Animal Spawning and Breeding issues 

### ISSUE THREAD

**Issue by Awesam5555** [EarthMC/Issue-Tracker#1110]
**Server**
Which server the bug is on.
EarthMC-Towny 
**Describe the bug**
Animals such as horses are despawning even though they have nametags. Horses are also now incapable of producing offspring in my town for unknow reasons.We have no clue what is happening! 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Prismary** [comment]
Common issue with the per-chunk entity limit. This is constantly being tweaked for server optimization, as a rule of thumb, make sure not to have many mobs in a single chunk (I think the current limit is 6).
