### ISSUE TITLE
[BUG] Siegewars surrendering doesn't work

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#1111]
**Server**
Beta

**Describe the bug**
When attacking a town the defenders tried to surrender by placing a white banner in their claims as suggested but it didn't let them.

**To Reproduce**
1. Go to a town
2. Make them an enemy
3. Start a war
4. Let the defenders try to surrender
5. Doesn't work and says they don't have the permission to

**Expected behavior**
The war should end and the towns should join the nation that was attacking.

**Additional context**
We (Nation of Accordo) did this at the town of Paramonia at x: 700 y: 76 z: 1050

**Comment by suneettipirneni** [comment]
Forward this to the towny issue tracker and we’ll send it over to Goosius’ branch

**Comment by Goosius1** [comment]
Hi Fyi Im aware of this. Currently I believe this to be an issue with the emc townyperms.yml.

I believe the king and mayor are missing the '...siege.*' nodes.

I can send over a vanilla war enabled townyperms.yml file if staff wish.

**Comment by FutureLemon** [comment]
> Fix says "Alright the correct perms have been added"
> So this bug needs to be retested now
> If surrender is working then it can be closed

Will test later when the server is back up and running. Thanks for the help!

**Comment by KarlOfDuty** [comment]
I'll assume it works then as there has been no more mention of this.
