### ISSUE TITLE
Gold Bug

### ISSUE THREAD

**Issue by HelloGaming123** [EarthMC/Issue-Tracker#1112]
I have 170 gold but it says i have 0 here is an image from yesterday 
![BalGlitch](https://user-images.githubusercontent.com/60282863/81515642-ee397680-92e9-11ea-908d-50648b976b77.png)

**Comment by FutureLemon** [comment]
If the gold is renamed it won't register. Also if you just want to check your balance do /res personally I find it easier and more reliable.

**Comment by HelloGaming123** [comment]
> If the gold is renamed it won't register. Also if you just want to check your balance do /res personally I find it easier and more reliable.

It is not named it may be because of my username change because when I do /warns I see GG0VL warnings. Not HelloGaming123
