### ISSUE TITLE
[Feature] Make wars regional if plugin is added to TN

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#1113]
Personally I’m a huge fan of the war plugin and I hope it does get implemented into TN. It strikes a fine balance between those who’d rather just play towny to build and those who are interested in building empires and warring.

However I believe if the plugin is added to TN, there should be a few tweaks to keep wars between regional powers instead of between big globalist alliances or groups. I’ve listed two suggestions that I came up with to achieve this.

Assuming the plugin were to be added right now, specific groups of pvpers could just teleport around the server and besiege whoever they want to, in my opinion that shouldn’t be a position in which the server ends up.

One of my ideas is that you should only be able to besiege towns that are within your nation range. This would prevent situations where one group of pvpers located on one side of the world can just besiege everyone. It would also remove the worry of one group achieving server wide domination as only regional dominance would be the limit. 

Wars shouldn’t be globalist show offs between big groups and big alliances, they should be for regional nations to achieve regional dominance within their own right.

However an alternative to that suggestion also exists:

I think the addition of the war plugin would be a perfect time to remove /n spawns to allied nations. This would ensure that wars remain regional and you don’t end up with a case where people can just teleport across the world and interrupt battles going on between two regional nations.

Going back on my previous point earlier it would remove the issue of one group achieving total dominance as you’d be limited by your transportation limitations, although if you’re willing to put in the resources to construct inter-continental transportation to besiege far away nations/towns then go for it. This would only encourage more innovation and community projects. 

This would also add a more realistic aspect to the server as manual transportation methods such as ice lines would become essential, especially when an ally wants to assist another ally who is across the world. It would also mean armies need to construct ways of getting to the towns they’re besieging if they are far away.

There are other benefits to removing /n spawn such as regional economies being formed instead of big super stores dominating the economy however this post is purely to focus on the war aspect.

On classic we removed /t spawns to allied nations, the next natural step is removing /n spawns. Regionalism > Globalism.

**Comment by KarlOfDuty** [comment]
You already can't take towns that are outside your nation range, the beta server map is just much smaller than the towny server's map.

**Comment by MineHero43** [comment]
> You already can't take towns that are outside your nation range, the beta server map is just much smaller than the towny server's map.

Oh alright, neat

**Comment by kab000m** [comment]
There's also more suggestions -- 

-Only allow players with 1-2 players online for it to get sieged (It will make it so towns cant just conquer inactive towns)

-Allow buildings to be destroyed but charge a gold fee to repair it. Since there is 65,536 blocks total in one chunk it should be calculated to be like, for example if building_damage > 32.768 (half of 65,536) building_regenerate() function whatever, and vice versa. We can also put the number down and down to accomodate small buildings that have minimal damage. Since 65,536 is a superperfect number we can calculate how much gold is needed to repair buildings based on the amount on blocks lost, which is absolutely perfect. Remember, 2^16 = 65,536, so we have a lot of levels based on each number to work on.

**Comment by 10op10** [comment]
> -Only allow players with 1-2 players online for it to get sieged (It will make it so towns cant just conquer inactive towns)

The whole point of the war plugin is to crackdown on inactive rebel towns/nations to clean up the map a bit

**Comment by kab000m** [comment]
> > -Only allow players with 1-2 players online for it to get sieged (It will make it so towns cant just conquer inactive towns)
> 
> The whole point of the war plugin is to crackdown on inactive rebel towns/nations to clean up the map a bit

That is totally unfair to inactive towns though. It would give welfare to any small town that can provide at least _some_ defense, allowing for 1-2 people to swoop into a town that is fairly active but not online _all the time_ allows for only the big fish to thrive.

**Comment by kab000m** [comment]
Also, if a town is inactive it will eventually die. As long as a person logs in to keep the town "alive" anyone with an active nation can easily swoop in and take it.

**Comment by 10op10** [comment]
> > > -Only allow players with 1-2 players online for it to get sieged (It will make it so towns cant just conquer inactive towns)
> > 
> > 
> > The whole point of the war plugin is to crackdown on inactive rebel towns/nations to clean up the map a bit
> 
> That is totally unfair to inactive towns though. It would give welfare to any small town that can provide at least _some_ defense, allowing for 1-2 people to swoop into a town that is fairly active but not online _all the time_ allows for only the big fish to thrive.

Its the mayors fault for being active end of story.

> Also, if a town is inactive it will eventually die. As long as a person logs in to keep the town "alive" anyone with an active nation can easily swoop in and take it.

Thats the whole point, its to stop rebel nations for staying there inactive months on end like aerfort and ireland, that nation was inactive longer than I have been playing emc

**Comment by kab000m** [comment]
> > ide at least _some_ defense, allowing for 1-2 people to swoop into a town that is fairly active but not online _all the time_ allows for only the big fish to thrive.
> 
> Its the mayors fault for being active end of story.
> 
> > Also, if a town is inactive it will eventually die. As long as a person logs in to keep the town "alive" anyone with an active nation can easily swoop in and take it.
> 
> Thats the whole point, its to stop rebel nations for staying there in

Okay. I am curious to see what happens with this plugin if we are able to freely conquer anyone that cannot fight back...

**Comment by Goosius1** [comment]
- On the suggestion for no siege unless 1-2 people online,
1. I have looked at this extensively.
2. It does not work unfortunately, because it actually encourages players to actually Not play on the server.
3. For example, as a small town mayor, if I am offline, thinking about playing, I take a quick look at the dynmap and see some enemy soldiers near my town.
.....Think I'm gonna log on to the server at that time?. No way, I'm very sensibly gonna wait until they go away, and in the meantime play Roblox(?) or something.
4. Similarly when I am logged on and see enemies approaching, I will of course log out.
5. Similarly if the value is 2, I will just keep my town size to 1
6. This idea has been tried before in other war systems, and did not work that well for the above reasons.

- On the building destruction idea, the system currently focuses very much on non-destructive play. Apart from this, destruction can get complicated with regeneration and duping issues. Tying damage assessment and partial regeneration to a payment system is pretty complex but who knows in (the far) future.

**Comment by kab000m** [comment]
> * On the suggestion for no siege unless 1-2 people online,
> 
> 1. I have looked at this extensively.
> 2. It does not work unfortunately, because it actually encourages players to actually Not play on the server.
> 3. For example, as a small town mayor, if I am offline, thinking about playing, I take a quick look at the dynmap and see some enemy soldiers near my town.
>    .....Think I'm gonna log on to the server at that time?. No way, I'm very sensibly gonna wait until they go away, and in the meantime play Roblox(?) or something.
> 4. Similarly when I am logged on and see enemies approaching, I will of course log out.
> 5. Similarly if the value is 2, I will just keep my town size to 1
> 6. This idea has been tried before in other war systems, and did not work that well for the above reasons.

Thank you for the response. Yes, I think I havent thought out my suggestion very well. It will never allow for any progress in the server happen. I agree.

> * On the building destruction idea, the system currently focuses very much on non-destructive play. Apart from this, destruction can get complicated with regeneration and duping issues. Tying damage assessment and partial regeneration to a payment system is pretty complex but who knows in (the far) future.

That's what I thought of as well. Disregarding the complexity of it, and the potential bugs, it could help with things such as walls. If a wall is built it will be impossible for any soldiers to enter, so allowing for the wall to be destroyed allows for everyone to have a dynamic war. As you said it is pretty complex but if this can be done efficiently in the future without any duping I would love to see it. As for regeneration, EarthMC already allows for griefed buildings to regenerate.

**Comment by kab000m** [comment]
Goosius1, what happens if a nation conquers another nation entirely? Say a nation conquers a one town nation, what happens to the nation?

**Comment by Goosius1** [comment]
Nation is destroyed, and king gets 80% refund of initial nation cost.

**Comment by kab000m** [comment]
I like that idea. Allows for the nation to be rebuilt but not right away.
