### ISSUE TITLE
[feature] Let non-capitals purchase an n-spawn for their town

### ISSUE THREAD

**Issue by barbasmas** [EarthMC/Issue-Tracker#1114]
**I heard you could teleport to any town in the world in classic** but fix disabled it in terra nova coz he wanted more iceways
and infrastructure in the world. ok nice but some big towns will now never be equal to capitals. My town Tsalbarivo is really big and many said it could be a nation in itself, but i really like my nation Madagascar and wouldnt want to break off. We see this happening in a lot of parts of the world tho; towns becoming big and wanting to be equally deluxe to their capital ie they make their own nation and bam we have 3000 nations in europe and the US. Alot of the big nations in emc are techically multiple ones (GRE, Japan, Chile-Argentina...) just to make use of multiple n spawns.

**I suggest enabling towns to purchase a spawn for anyone to tp to**, without becoming an independent nation (cost: perhaps 1500 gold) There will always be smaller towns in a nation that will be dependent on infrastructure but this allows nations to have multiple hubs! 

//barbie

**Comment by shirazmatas** [comment]
that feature request has to be posted here: https://github.com/TownyAdvanced/Towny there is currently no way of doing this.
