### ISSUE TITLE
[BUG] Book and quill crash

### ISSUE THREAD

**Issue by barbasmas** [EarthMC/Issue-Tracker#1115]
**Server**
towny

**Describe the bug**
Game either crashes or freezes for a moment after flipping pages **fast** in a Book and quill with this error message: _The game crashed whilst rendering screen Error: java.lang.StringIndexOutOfBoundsException: String index out of range: 268_ 

**To Reproduce**

1. Join Towny on 1.15.2.
2. Open a Book and Quill with written text in it from 1.13.
3. Flip a few pages by spamming the next page button.
4. Game crashes or freezes.

**Expected behavior**
The Book and Quill shouldn't crash the game if you flip fast

**Additional context**
I'm having the same issue with two Book and Quills that I started writing in before the server upgrade to 1.15. My theory is that the update did something with them. The books are fine to read when turning pages slowly. Important to note that the bug disappears if you sign the book.

**Comment by Warriorrrr** [comment]
This is an error in minecraft itself, that has already been fixed in the future versions of the game.

**Comment by barbasmas** [comment]
Okidoki nice!
