### ISSUE TITLE
[Bug] Staff unable to make two /warn within 30 seconds

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#1117]
**Server**
All

**Describe the bug**
doing /warn shirazmatas too cool
and then /warn karlofduty not cool
says "uhuh you have to wait 30 seconds"
**To Reproduce**
1. Be staff
2. /warn badboy griefing
3. after 3 sec
4. /warn badgirl griefing

**Expected behavior**
both warns issued
**Screenshots**

**Additional context**

**Comment by FutureLemon** [comment]
This obviously indicates shiraz is too good at his job and finds so many cheaters he needs to be admin.

**Comment by SvenPhillips** [comment]
Why even is there a cooldown lol?

**Comment by 32Puschel** [comment]
> 
> 
> This obviously indicates shiraz is too good at his job and finds so many cheaters he needs to be admin.

exacly.

**Comment by shirazmatas** [comment]
Please fix so we can ban botattacks @KarlOfDuty

**Comment by Prismary** [comment]
Didn't have the issue when cleaning up recent bot attacks, assuming this is no longer a thing.
