### ISSUE TITLE
Claiming chunks is broken for me. 

### ISSUE THREAD

**Issue by Krafff** [EarthMC/Issue-Tracker#1118]
**Server**
Towny

**Describe the bug**
There's one chunk next to my town that I want to claim but I can't because it says "This area is too close to another town's  homeblock." But the thing is there is no town near it and I can claim around that one chunk.

**To Reproduce**
Still do not know what this means, needs to be more clear

**Expected behavior**
To be able to claim the damn chunk

**Screenshots**
Can't I am on the mo-bile

**Additional context**
Very rude.

**Comment by jkmartindale** [comment]
It's broken for everyone else too #1096

**Comment by FutureLemon** [comment]
> It's broken for everyone else too #1096

jkm: please don't make another post about not being able to claim it's annoying.
everyone else: haha github goes brrrrrrrrrrrrrrrrrrrrrrrr

**Comment by riri2010** [comment]
Krafff I recommend you leave a comment on #1096 since this issue will be closed for being a duplicate.

**Comment by KarlOfDuty** [comment]
This should be fixed now.
