### ISSUE TITLE
[Feature] Spectator mode!

### ISSUE THREAD

**Issue by DCDylanc123410** [EarthMC/Issue-Tracker#1120]
**Is your feature request related to a problem? Please describe.**
Are you upset that you can't access factions or the classic map anymore and that there is no way to download the world? Well what if there was a way you can! Many players miss the factions and classic map and want to browse around it even if they cant play anymore I am here to propose a solution to this problem

**Describe the solution you'd like**
I want there to be a small server sorta like the survival games that used to be in the queue of EMC but instead of survival games you go into spectator mode and can fly around the classic and factions maps. This server would only allow up to 10 people at a time to improve performance. THe players would not have access to any commands or chat while in this server besides to /tp and to join queue. This will allow players to fly around their old factions and classic maps while still saving the overall server performance. This can be a nice feature for when players get bored or are waiting in queue. Possibly these special servers could be for donators only or premium only to encourage those to buy either. I feel this would be a nice addition to make up for classic and factions disappearing without a download link in site. Along with this due to the server having very low plugins and only spectator mode it wont affect the overall server performance by much if at all. I think this is a good feature to think about even if it does not happen until later down the road.

**Comment by GRAnimated** [comment]
didn't everyone on factions blow their own base up because of it? now they can look at what isn't even there! no, it's a good idea i support it

**Comment by SvenPhillips** [comment]
> didn't everyone on factions blow their own base up because of it? now they can look at what isn't even there! no, it's a good idea i support it

Yeah some of us did. If this world download is to happen, could you do one before we summoned 13 withers on our base lol.

**Comment by FutureLemon** [comment]
Isn't the classic map corrupted?
