### ISSUE TITLE
Name Change economy issue

### ISSUE THREAD

**Issue by Joel-02** [EarthMC/Issue-Tracker#1121]
**Server**
Towny

**Describe the bug**
It is as simple as I cannot use any of the economy features since changing my name to Joel1 from Joel02.
**To Reproduce**
Own a town and change your account name.

**Expected behavior**
If the same happens as what has happened to me, you wont be able to use the economy features. I assume this is a problem with Bungeecord/waterfall or something. 

I have made a ticket but was told to write it here instead.

**Comment by 10op10** [comment]
I had the same issue when I changed my IGN

**Comment by Conmqn** [comment]
I would suggest making a support ticket on the discord and asking any mods to help contact Eagle, Karl and Fix about this bug. Before you change the name i would make a ticket or tell the mods so they are aware of what you will be doing.

**Comment by Joel-02** [comment]
I made a ticket and was directed here, also I already changed my name so its a bit too late now. Thank you anyway though

**Comment by Joel-02** [comment]
To anyone viewing this, I've changed my username back to Joel02 and it works now.
