### ISSUE TITLE
[BUG] Towny charging gold for a town name change when the name change is unsuccessful

### ISSUE THREAD

**Issue by silver-street** [EarthMC/Issue-Tracker#1122]
Towny Server

I went to change my town name, so i deposited 32g into town bank and ran the command to change it. The new town name i entered was 17 characters. I don't know what the character limit is but i assume 17 exceeds it. Anyway, after running the command I attempted to confirm it, but got the message "None of those names are valid". The town name was unchanged, however 16g of the 32g i deposited was removed.

I expected my town bank balance to be unchanged after the name change was unsuccessful.

I made a ticket and got the feedback that it could be a bug and that i should report it here. I've heard one other user complain about a similar experience in global.

**Comment by shirazmatas** [comment]
you should actually report it to towny github https://github.com/TownyAdvanced/Towny. They can fix the bug permanently
