### ISSUE TITLE
Add another discord channel for discord invite links

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#1123]
**Is your feature request related to a problem? Please describe.**
#trading is mostly getting used for discord invite links. Some of them don‘t even have anything to do with trades.

**Describe the solution you'd like**
Add another channel dedicated for discord server invite links only. That would help people to advertise their events, shops or other services better without interfering with trading.
The emc discord has very few channels so I think this would be easily doable.

**Comment by KarlOfDuty** [comment]
I don't think adding another channel is a great idea at this time, advertising your ingame business is kinda what that channel is for anyway. I think it should possibly be renamed though.
