### ISSUE TITLE
Remove 10 Chunk Limit

### ISSUE THREAD

**Issue by timew0rk** [EarthMC/Issue-Tracker#1124]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to claim chunks for my town and I can't

**Describe the solution you'd like**
I would like them to remove the 10 chunk limit because it is not allowing me to expand at all. I have consent from the mayors of towns and they have my consent to expand yet I can't

**Additional context**

**Comment by FutureLemon** [comment]
Join a nation or recruit.

**Comment by timew0rk** [comment]
I am in a nation.

**Comment by nipdip** [comment]
I mean, 10 chunks isn't nearly enough for towns, however I think gigantic towns covering entire continents isn't good for the server. I'd say increase it to 32 or 64 chunks sounds reasonable.

**Comment by timew0rk** [comment]
I wasn't clear and it was my fault I was talking about being too close to one town and can't expand to them.

**Comment by docwhomc** [comment]
This isn't about the number of chunks the town gets, it's about the distance a plot is from another town's home block.  If a plot is within a certain distance (it seems to be 10 chunks) of another town's home block, you cannot claim the chunk.

**Comment by docwhomc** [comment]
Some situations could be resolved making this distance no more than half the distance home blocks need to be separated.  Having this value greater than or equal to the minimum distance between home blocks allows this restriction to be used for claim blocking and creates excessive instances of accidental claim blocking as a player unaware of this issue would not expect this behavior.

**Comment by KarlOfDuty** [comment]
There appears to be an issue where the range now applies to plot claims as well as town creation, should be fixed on next server restart.
