### ISSUE TITLE
[Feature] Allow shopsigns in embassy plots

### ISSUE THREAD

**Issue by remcodd2** [EarthMC/Issue-Tracker#1126]
Currently in the beta, you can only have shop signs in shopplots, which sounds logical. However, this means that other people can not have shops outside their own town. This renders embassy plots useless. If you want to have less nations, dont force people to make shops in their own town and turn it into a nation, just for easy acces. There are (perhaps too) many nations, and new features like this will only encourage more nations, just go get that spawn point. 

If u allow shop signs in embassy plots, people can make shops in capitals, and aren't forced to make a nation themselves.

**Comment by Zardinio** [comment]
I support this idea!

**Comment by IAmUnStTV** [comment]
I would also like the ability to create shop signs within embassys in the Towny server as well

**Comment by Prismary** [comment]
Pretty sure this is no longer an issue.
