### ISSUE TITLE
Change in settings for towny claims

### ISSUE THREAD

**Issue by indian7p** [EarthMC/Issue-Tracker#1132]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I have to deal with the chunk limit as residents leave.

**Describe the solution you'd like**
Ways to pay an extra lets say 8G to buy 1 extra chunk if you have reached or over your limit. However maybe limited to up to 940 chunks per town

**Additional context**
Terraemc has this type of system.

**Comment by indian7p** [comment]
Ok its called bonus chunks.

**Comment by KarlOfDuty** [comment]
We will stick with the per member plots.
