### ISSUE TITLE
[Bug] Siegewar taxes seem to be broken/disabled?

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#1133]
This Bug report relates to the new war plugin currently being tested on the beta server.

![Screenshot (225)](https://user-images.githubusercontent.com/44756360/82754724-3323d980-9dcf-11ea-9d27-fae37d2bf151.png)

On the website detailing how the plugin works, it mentions that captured towns must pay a tax to the occupying nation, otherwise their town will fall.
However I have been testing the plugin for quite sometime now and I have quite a few captured towns, however there doesn't seem to be any mechanism to collect said taxes or enable/disable them?

Towns that I have captured have 0 gold in their banks however still have not fallen. This leads me to believe that the ability is broken.

I assume that the screenshot is referring to the ability to plunder towns by placing a chest outside of their claims after winning the siege. This takes gold from their banks however can only be used once so it isn't really much of a taxing system as the website details. Perhaps if the ability to plunder towns would reset every 24h it could be a way of taxing occupied towns?

Perhaps I am mistaken, however if that is the case could someone please explain how the taxing system works or if it is broken, perhaps take a look into it?

The ability to tax captured towns is pretty interesting and I'd love to see it fully functioning.

**Comment by Goosius1** [comment]
Hi.

The tax mechanic mentioned is just the regular towny tax-nation-towns mechanic.

This is enabled/disabled by configuration.

If this core feature is configured on for Emc nations ....and they then set a nation tax, then the logic will apply, otherwise it will not be applicable.
