### ISSUE TITLE
[Feature] Bulk selling on sign shops

### ISSUE THREAD

**Issue by emmettaaron** [EarthMC/Issue-Tracker#1134]
I have noticed that you cannot sell any bulk potions in the new sign shop system. E.g: selling haste 2 potions 1g for 27 doesn't work. I think the problem here is that the potions themselves are non-stackable. 

Either make potions stackable or making it able to buy bulk potions.

**Comment by JaVolimKatarinu** [comment]
Neither do other items can be sold in multiple stacks.

**Comment by indian7p** [comment]
That does basically mean things such as cobble, stone, sand, gravel and more can't be sold at a good price. Even if you can sell like 1 stack per golden nugget or something, it makes no sense

**Comment by adx31** [comment]
no you can't even use nuggets to buy. even if we could it would still not be the best. so when you are selling blocks or xp bottles we need to sell more than one stack.

**Comment by adx31** [comment]
no you can't even use gold nuggets to buy. even if we could it would still not be the best. so when you are selling blocks or xp bottles we need to sell more than one stack.
