### ISSUE TITLE
More Stacks in sign shops

### ISSUE THREAD

**Issue by billy26274** [EarthMC/Issue-Tracker#1135]
**Is your feature request related to a problem? Please describe.**
I cannot provide and sell some items for a realistic price

**Describe the solution you'd like**
You can alter the code so that we can add it so instead of 1 gold for 1 stack make it so we can do 1g for say 4 stacks
**Additional context**
please add this it will make a lot more shops

**Comment by Fruitloopins** [comment]
I greatly support this change, my friend AD31's nation's economy is based around bulk-selling sand, no one will buy 64 sand for 1g as the standard price is 6 stacks for 1g. This is just one small example though there are many others such as xp bottles that can no longer be sold in sign shops as they are sold at like 10 stacks for 1g or something like that.

**Comment by JaVolimKatarinu** [comment]
#1134
