### ISSUE TITLE
[BUG] Sign dupe using the shop plugin

### ISSUE THREAD

**Issue by theapplesoup** [EarthMC/Issue-Tracker#1136]
While this dupe is not game breaking whatsoever and is harmless to the economy, I thought I would share this here anyways.

**Server**
Towny

**Describe the bug**
Because crafting a sign is not required to create a sign shop, the Quickshop plugin generates one automatically whenever a shop is created. If the owner of the shop breaks the sign instead of the chest, they are given the sign that was automatically generated despite never crafting it.

**To Reproduce**
1. Join Towny
2. Create a chest shop
3. Break the sign on the chest without breaking the chest
4. Get a free sign without crafting it

**Expected behavior**
When breaking a sign, it was expected that the sign would not be dropped.

**Additional context**
Once again, it's extremely harmless but still worth fixing in the future.

**Comment by jkmartindale** [comment]
brb crashing the signs economy

**Comment by indian7p** [comment]
Ye when the new plugin came out, people did almost immediately find out about this sign duping, however the admins already knew about this and said that it will be sorted out soon.

**Comment by Rndm-Prsn** [comment]
signs are renewable anyway
