### ISSUE TITLE
[BUG] God Armour and Shops 

### ISSUE THREAD

**Issue by RainingOranges** [EarthMC/Issue-Tracker#1137]
**Server**
Towny

**Describe the Bug**
So when I create a Sign Shop for something like some god armour in my shop it makes it then I put 9 chestplates in however it only recognised 1 stock. Then when it sells I have to remove the chest and remake the shop to give it another 1 chestplate
**To Reproduce**
1. Go to Towny
2. Make a Shop using a god chestplate, helmet or boots.
3. Put more then 1 stock into the chest

**Expected behavior**
It read the 9 chestplates instead of 1

**Comment by FutureLemon** [comment]
They must all have the same durability

**Comment by Oln123** [comment]
I done this with tools al with the same durability and name and it doesn't work

**Comment by Oln123** [comment]
Idk but I feel like this is related to merging and combining enchanted things

**Comment by shirazmatas** [comment]
Report issue here https://github.com/Ghost-chu/QuickShop-Reremake

**Comment by Oln123** [comment]
They require you to put info in that only fix can know
![image](https://user-images.githubusercontent.com/51036095/83199306-d6128580-a138-11ea-86f6-4a632af43e04.png)
