### ISSUE TITLE
[Plugin] (X,Y,Z) Town plot claiming

### ISSUE THREAD

**Issue by SuperB1aze** [EarthMC/Issue-Tracker#1141]
Some players recently have created an idea of new plot claiming. Almost all of the towns construct buildings higher than one floor. Some towns have giant skyscrapers, which are filling large space in the height.
Nevertheless, there's only (X,Z) chunk claiming on the server. It means that many buildings with huge amount of floors become useless as plot claiming goes from the 1st to the 256th block to one player. Our suggestion is creation of special plugin, which will allow players to (X,Y,Z) plot claiming, it makes an opportunity for us to build large appartment blocks with appartments for everyone. This feature is not so necessary for nation and town claiming as it might cause griefing over the towns. It perfectly fits for houses, department stores, factories, etc.
Idea was suggested and supported by SuperB1aze, Uner, D4 (SejiTheCreator), 
Urakuk, CoronaMixus, Sasai_Kudasai, moldemort.

**Comment by jkmartindale** [comment]
This has been asked for before (see #815 and #822), but modifying the claim system belongs in Towny's issue tracker. It's one of their more common feature requests:
- TownyAdvanced/Towny#143
- TownyAdvanced/Towny#261
- TownyAdvanced/Towny#1291
- TownyAdvanced/Towny#1381
- TownyAdvanced/Towny#1480
- TownyAdvanced/Towny#1498
- TownyAdvanced/Towny#2127
- TownyAdvanced/Towny#3166

Each time these feature requests were denied on the basis that cuboid protection plugins exist.

So our best shot at getting apartments would be to add some sort of lock plugin that has cuboid protection. That might not be able to make granular build/destroy permissions, but you could perhaps control item use. This was proposed by #244, which was closed when LockettePro was abandoned.

#841 suggests adding the LWC plugin and is still open. You might want to consider voicing your support there and giving the thread a bump.

**Comment by shirazmatas** [comment]
> This has been asked for before (see #815 and #822), but modifying the claim system belongs in Towny's issue tracker. It's one of their more common feature requests:
> 
>     * [TownyAdvanced/Towny#143](https://github.com/TownyAdvanced/Towny/issues/143)
> 
>     * [TownyAdvanced/Towny#261](https://github.com/TownyAdvanced/Towny/issues/261)
> 
>     * [TownyAdvanced/Towny#1291](https://github.com/TownyAdvanced/Towny/issues/1291)
> 
>     * [TownyAdvanced/Towny#1381](https://github.com/TownyAdvanced/Towny/issues/1381)
> 
>     * [TownyAdvanced/Towny#1480](https://github.com/TownyAdvanced/Towny/issues/1480)
> 
>     * [TownyAdvanced/Towny#1498](https://github.com/TownyAdvanced/Towny/issues/1498)
> 
>     * [TownyAdvanced/Towny#2127](https://github.com/TownyAdvanced/Towny/issues/2127)
> 
>     * [TownyAdvanced/Towny#3166](https://github.com/TownyAdvanced/Towny/issues/3166)
> 
> 
> Each time these feature requests were denied on the basis that cuboid protection plugins exist.
> 
> So our best shot at getting apartments would be to add some sort of lock plugin that has cuboid protection. That might not be able to make granular build/destroy permissions, but you could perhaps control item use. This was proposed by #244, which was closed when LockettePro was abandoned.
> 
> #841 suggests adding the LWC plugin and is still open. You might want to consider voicing your support there and giving the thread a bump.

Great summary, unless you have another solution in mind show your support on that ticket
