### ISSUE TITLE
shop sign scamming

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1142]
As of a few days ago EMC got a new shop plugin. But this did not come without its problems, as problematic players have discovered you can rename an item to a much more valuable item and it will appear on the shop as the latter. This is being used to trick many new players and even active older ones, I won't stand for it. Please, fix this issue. It's not enough to say "just be careful what you buy". 
Thanks

**Comment by jkmartindale** [comment]
https://discord.com/channels/219863747248914433/221318341166497792/714220428725452851
![Screenshot_20200528-180608](https://user-images.githubusercontent.com/11380394/83206389-08f35400-a10e-11ea-8db4-7faddc5d2230.jpg)

**Comment by jkmartindale** [comment]
This is something to bring up on the QuickShop repo, idk if there's much else EarthMC can do on their end. Looks like they had this issue before and fixed it, so idk what broke it again: Ghost-chu/QuickShop-Reremake#195

**Comment by 32Vache** [comment]
a simple fix to this would be remplacing the item's name on the sign by it's [namespaced id](https://minecraft.gamepedia.com/Namespaced_ID) and obviously remove the `minecraft:` prefix.

**Comment by AmphireYT** [comment]
Ever heard if item preview?

**Comment by pesetz** [comment]
amphire is saying that cause hes a scammer ^
