### ISSUE TITLE
[BUG] Sign Shops Don't Recognize Items

### ISSUE THREAD

**Issue by gawker2** [EarthMC/Issue-Tracker#1144]
**Server**
Towny

**Describe the bug**
When certain items (in my experience all enchanted items are affected by this) are placed in sign shops that they should be able to be sold in, they are not registered by the system. The shop will display a lower number stock than what is in the chest and the unrecognized items are unable to be sold.

**To Reproduce**
1. Make several god-enchanted items of the same type (shovel, axe, helmet, chestplate, etc.)
2. Create a shop with one of the items
3. Fill chest with all of the items
4. See error - shop will not recognize some of the items

**Expected behavior**
A tool/armor/weapon with the same enchants and name should be able to be sold in the same shop. 

**Screenshots**
<img width="400" alt="Screen Shot 2020-05-29 at 10 19 57 PM" src="https://user-images.githubusercontent.com/66154767/83320366-9a8cbf80-a1fb-11ea-8bd5-e1f87f91f3c2.png">
<img width="200" alt="Screen Shot 2020-05-29 at 10 19 57 PM" src="https://user-images.githubusercontent.com/66154767/83320371-a4162780-a1fb-11ea-8e7d-6bbdfe1d7ff1.png">

**Additional context**
This was not an issue with the previous SignShop plugin.

**Comment by jkmartindale** [comment]
As a hunch, it might be only recognizing items with the same `RepairCost` NBT tag. QuickShop currently doesn't like items with different damage counts (below), so I wouldn't be surprised if it's comparing all NBT tags without ignoring unimportant ones

![image](https://user-images.githubusercontent.com/11380394/83320683-f3158a00-a206-11ea-82ca-cbb75d69000c.png)
![image](https://user-images.githubusercontent.com/11380394/83320686-ff99e280-a206-11ea-94e5-e4c89742a250.png)

**Comment by Scorpionzzx** [comment]
The reason it does this is the items cost a different amounts of xp when put into a anvil and it then makes those items separate. I think it has to do with the repair cost like jkmartindale said

**Comment by Prismary** [comment]
Belongs to the QuickShop issue tracker, however I doubt this is easily fixable.

**Comment by Ghost-chu** [comment]
> Belongs to the QuickShop issue tracker, however I doubt this is easily fixable.

https://github.com/Ghost-chu/QuickShop-Reremake/blob/76c1540ec4b531f0c9aadb3620729e72abd08163/src/main/resources/config.yml#L488

**Comment by Prismary** [comment]
My bad, didn't thoroughly check the comments in that thread. Do you (or anyone else for that matter) know whether this is still an issue or has been fixed at some point?

**Comment by Warriorrrr** [comment]
Fixed, will be applied after the next restart.
