### ISSUE TITLE
Gold glitch

### ISSUE THREAD

**Issue by SuperDoff** [EarthMC/Issue-Tracker#1146]
**Server**
EarthMC.net
**Describe the bug**
any command that includes the use of gold doesn't work for me. For example, if someone does /pay to me, i won't recieve the gold even thought it says it in /bal. my /bal doesn't work either. i cannot withdraw nor deposit any gold to my towns bank and i'm not recieving gold from sign shops.

**Expected behavior**
it just happened one day and i do not know why or exactly when it happened.

**Screenshots**
![there](https://user-images.githubusercontent.com/63093039/83334891-d8e0b800-a2a9-11ea-927d-460561f74b60.png)

**Additional context**
Noting more to say.

**Comment by SuperDoff** [comment]
Pls someone help me this is a big problem

**Comment by nipdip** [comment]
It could be a clientside glitch. Maybe try resetting your connection to the server?

**Comment by jkmartindale** [comment]
> It could be a clientside glitch. Maybe try resetting your connection to the server?

I can't see how a server command issue would be a client-side issue tbh

**Comment by Joel-02** [comment]
Did you change your name?
