### ISSUE TITLE
[BUG] Offline shops not giving full gold

### ISSUE THREAD

**Issue by Sirtabascomelon** [EarthMC/Issue-Tracker#1147]
**Server**
Towny

**Describe the bug**
Last night, I set up some new shops selling beehives and when I returned today I was notified that 2 of them had sold (along with 3g worth of diamonds). As I sell these beehives at 7g per, I should have returned to 17g total from both hives and the diamonds. However, I only received 7g. There is also none in my enderchest, and I am tax-exempt in my town.

**To Reproduce**
Not sure.

**Expected behavior**
I was to receive 17g, rather than 7g.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Prismary** [comment]
Probably no longer recent, if so, please open a ticket on the support discord.
