### ISSUE TITLE
Debate/politics Channel

### ISSUE THREAD

**Issue by Oln123** [EarthMC/Issue-Tracker#1148]
Issue = Political arguments clogging up the main chat
Recently A lot of people have been annoyed of the political debates and arguments in emc. While I understand there grievances, I think politics should be allowed. So to solve this I recommend adding a channel called "Debate" or "politics" In the server and/or on discord.

Solution = A new Channel
So to solve this I recommend adding a channel called "Debate" or "politics" In the server and/or on discord.

**Comment by KarlOfDuty** [comment]
We think player run discord servers are best suited for this.
