### ISSUE TITLE
(Rule 2.1) Make trapping in general illegal

### ISSUE THREAD

**Issue by AmphireYT** [EarthMC/Issue-Tracker#1149]
**Is your feature request related to a problem? Please describe.**
Trapping people in embassys/specific plots and getting the item they want.  
**Describe the solution you'd like**
Make them Bannable
**Additional context**
Theres no point on keeping spawn trapping a thing when we have /trade. Also People tend to use this at drop party by tricking the player into a plot full of concrete powder and then some kid switching the lever. ex video here https://vimeo.com/425009035. I see no benefit on keeping them allowed.

**Comment by Lagann311** [comment]
Trapping is part of the game. However I agree that it should be banned when it gets used for scamming. /Trade and sign shops have been introduced to eliminate scamming but there‘s still exceptions like these, so why not enforce rules to make it illegal completely.
Btw, you can escape these kind of traps with jump boost potions if it‘s not a really deep hole and if the top isn‘t closed off.
And isn‘t logg in invincibility a thing anymore? A year ago or so you were invincible for ~5 seconds after joining allowing to tp away.

**Comment by AmphireYT** [comment]
> Trapping is part of the game. However I agree that it should be banned when it gets used for scamming. /Trade and sign shops have been introduced to eliminate scamming but there‘s still exceptions like these, so why not enforce rules to make it illegal completely.
> Btw, you can escape these kind of traps with jump boost potions if it‘s not a really deep hole and if the top isn‘t closed off.
> And isn‘t logg in invincibility a thing anymore? A year ago or so you were invincible for ~5 seconds after joining allowing to tp away.

"jump boost" everythings closed off and also if you log you die instantly

**Comment by Lagann311** [comment]
Although it‘s difficult you could have escaped with jump boost in this one but who carries it around lol.
You sure about that? Afaik you only can‘t logg when a player hit you. If you take damage elsewhere you should be able to logg out without dying instantly.

**Comment by AmphireYT** [comment]
> Although it‘s difficult you could have escaped with jump boost in this one but who carries it around lol.
> You sure about that? Afaik you only can‘t logg when a player hit you. If you take damage elsewhere you should be able to logg out without dying instantly.

the way people scam is by /plot toggle pvp

**Comment by GitMocc** [comment]
Amphire, just because you are dumb and follow someone into an obvious trap doesn't mean it should be outlawed, its your own stupidity.

**Comment by FutureLemon** [comment]
What you are saying to just disable pvp in claims completely or it will be counted as a trap...

**Comment by nipdip** [comment]
It sounds like you want to make the server more PG. This is a PG-13 server, PVP, stealing, minor griefing and trapping should be allowed.

**Comment by 32Puschel** [comment]
> 
> 
> It sounds like you want to make the server more PG. This is a PG-13 server, PVP, stealing, minor griefing and trapping should be allowed.

griefing shouldnt be allowed exept its and odl town that has fallen

**Comment by shirazmatas** [comment]
post on the correct github https://github.com/EarthMC/EarthMC.net/issues
