### ISSUE TITLE
[Feature] Remove Ender pearls

### ISSUE THREAD

**Issue by MarkusAurelius124** [EarthMC/Issue-Tracker#115]
Hey, I wanted to talk about a change that I think would make PVP/War much more interesting.
I've just been working on planning out my city, its defenses specifically, walls and towers and moats et cetra, when I once again realized that in an actual PVP/War situation none of those would matter because people can just almost insta-teleport over anything at a whim if they've got an ender pearl, making any defensive measures I wanna use pointless.
I see how great and more balanced you guys are trying to make the server, to the point where you removed the player-to-player teleportation, which worked incredibly well because now people actually do consider distance in the world as an issue to be solved. I just think it makes sense to remove that element from PVP/War as well if you want it to be as realistic and much more fun as it can be.
My solution is to either remove ender pearls, and if you want to have people reach The End, find a different way (maybe somehow modify endermen drops to drop Eye of Ender instead of Pearls?)
OR somehow disable their teleportation ability.
I just think PVP and fighting would be so much more exciting if you removed that element. Suddenly, walls and a variety of defenses have a meaning other than decoration. People would invest more in actually planning an assault rather then just enderpearl over everything, kill, repeat.
Thanks for reading, and I do hope you apply this because I believe it is one of the final pieces in making new EMC the balanced, both fun and realism wise server I think you're trying to make it.

**Comment by BowShot118** [comment]
If you have perms set correctly non town members can't use enderpearls that land in your claims. I do like the concept though.

**Comment by MarkusAurelius124** [comment]
> If you have perms set correctly non town members can't use enderpearls that land in your claims. I do like the concept though.

So if a person is outside my claim, and he throws a pearl inside, it doesnt teleport him?

**Comment by BowShot118** [comment]
If your perms are correct it wont

**Comment by MarkusAurelius124** [comment]
> If your perms are correct it wont

Ah, well that's cool.
But I still think Pearls are a bit BS if we're also taking player teleportation out the mix

**Comment by BowShot118** [comment]
Thats why I do like the concept.

**Comment by KarlOfDuty** [comment]
Why is that bad? Ender pearls are so short range it is nothing when compared to player teleportation.

**Comment by MarkusAurelius124** [comment]
> Why is that bad? Ender pearls are so short range it is nothing when compared to player teleportation.

They're not as bad as player teleportation when they're used as means of transportation, but are so when used for combat, which is where they're mostly used. I just feel like it would be more natural, and give players far more options if you could actually build traps people cant teleport out of, or for players to not be as fast or even faster than a horse when they're without one, or for troll players with nothing but a diamond sword to not feel like they can just cuck any heavily-armored player just cus' they can teleport away from danger at a whim. I feel like not having a way to just teleport out of situations could make the server much more interesting and require the players to be much more tactical and strategic when building/fighting.

**Comment by MarkusAurelius124** [comment]
#FightLikeMen-NotLikeSuperSayans

**Comment by KarlOfDuty** [comment]
I feel like the advantages far outweigh the disadvantages in this case. This isn't exactly a pvp-focused server even if it is a main part of it.

**Comment by MarkusAurelius124** [comment]
> I feel like the advantages far outweigh the disadvantages in this case. This isn't exactly a pvp-focused server even if it is a main part of it.

So what advantages are there to pearls beside the PVP part? (if you exclude the end portal stuff too using the solution I offered above)

**Comment by KarlOfDuty** [comment]
Vertical movement is incredibly tedious without enderpearls. Also any type of movement when building structures as walkways are usually not finished at that stage.

**Comment by MarkusAurelius124** [comment]
> Vertical movement is incredibly tedious without enderpearls. Also any type of movement when building structures as walkways are usually not finished at that stage.

All the more to increase the realism factor.
As I said, I just feel like taking it away is the next natural step in turning EMC into what I'm seeing you guys want it to be. Same reason nations are expensive, town/nation names should be based in reality, gold scarcity, nation range, no player-to-player teleportation and so forth.

**Comment by Arganog** [comment]
Ender Pearls fall under the "itemuse" permission for towny, so they can be disabled in towns, making walls still effective (except for when people have Elytra)

**Comment by MarkusAurelius124** [comment]
> Ender Pearls fall under the "itemuse" permission for towny, so they can be disabled in towns, making walls still effective (except for when people have Elytra)

Unless people fight in unclaimed territory, which outside of a war event is where most of the fighting is done.

**Comment by MarkusAurelius124** [comment]
Though I do agree I wasn't too familiar with Towny Enderpearl mechanics dx

**Comment by KarlOfDuty** [comment]
We will not be removing ender pearls.
