### ISSUE TITLE
Multi-server world.

### ISSUE THREAD

**Issue by ItsESGO** [EarthMC/Issue-Tracker#1152]
I am requesting this feature in hopes that it can remove the queue in Earth mc. I want to make Earth MC available to everyone. At its current state, it is very difficult to play Earth MC without a priority pass.

I think a good idea to remove the queue is to break the Earth MC world down into multiple servers. This would allow for more than 150 players to be on at one time without any lag. The server regions could be broken down more and more to fit with the player count. To start, The world can be broken into two servers. The servers would be split down the Atlantic ocean.

Adding this may come with some controversy. However, it will be beneficial to the server and the Earth MC community in the long run.

**Comment by suneettipirneni** [comment]
We’ve recently thought about adding multi server support for towny, while we haven’t reached a conclusion I wouldn’t be surprised to see it added. It would alleviate the issue of single instance lag for a lot of users.

**Comment by FutureLemon** [comment]
This might divide the community though.

**Comment by suneettipirneni** [comment]
> This might divide the community though.

This is implementation oriented, but I think most emc users can agree that queue is the most dreadful part of emc, and it would be nice if the lag was reduced. Multi-Server addresses both of these issues.

**Comment by Oln123** [comment]
It would be extremely difficult to split, The main issue i would see it countries that are on the border. 
The atlantic ocean idea seems like the best imo. A "new world" server and an "old world" one.
This would split emc quite nicely as each side would have relatively equal populations in game. I understand the concerns that this would "split" the comunity but i think that depends on how it is implemented.

**Comment by KarlOfDuty** [comment]
This is not possible.

**Comment by KarlOfDuty** [comment]
Well, not in any non-horrible way.
