### ISSUE TITLE
Councillor problem

### ISSUE THREAD

**Issue by KaninoPika** [EarthMC/Issue-Tracker#1155]
**Server**
Towny

**Describe the bug**
A councillor can't open chest etc.
**To Reproduce**
Steps to reproduce the behaviour:
1. Happens randomly

**Expected behaviour**
They can't access things they should

**Comment by 10op10** [comment]
Get the councillor to walk through a nether portal and then try

**Comment by KaninoPika** [comment]
Didn't try that but I kicked him and invited him again and gave him the rank and then it worked

**Comment by FutureLemon** [comment]
This is a bug where sometimes the playerdata doesn't exactly load and they can't do any command. You can fix this by relogging or going through a netherportal.
