### ISSUE TITLE
Make it impossible to hit other players in queue

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#1156]
**Is your feature request related to a problem? Please describe.**
While I‘m writing this, I‘m hearing the sound of multiple people jitter clicking the hell out of everyone that‘s in the lobby spawn block.
It‘s just so annoying when you have to mute your sound everytime when you join the lobby and this happens, then turn it on again when you‘re in the game. 

**Describe the solution you'd like**
make it impossible to hit other players

**Comment by KaninoPika** [comment]
Yes please it's ear cancer

**Comment by 10op10** [comment]
Firstly there is no way to prevent that I believe, also Just turn your sound off

**Comment by Lagann311** [comment]
totally possible. Ever played on hypixel? Never heard that sound there ever in lobbies

**Comment by 10op10** [comment]
> totally possible. Ever played on hypixel? Never heard that sound there ever in lobbies

Just turn your sound off and report them for using an auto clicker because its bannable

**Comment by jkmartindale** [comment]
In the meantime you can also make a resource pack that replaces the punch sounds with silent .ogg files (which won't impact gameplay because nobody PVPs barehanded anyway).  Replacing strong1.ogg-strong6.ogg and weak1.ogg-weak4.ogg might be enough.
