### ISSUE TITLE
[BUG] [TOWNY + BETA] /resident command return corrupted value

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1159]
**Server**
Towny + Beta

**Describe the bug**
So after the implantation of the new shop system i discover a bug,
i have made a shop in both server towny + beta
the think is when you are disconnected you can sell and buy items on you'r shop, because
the server check the player currency when he was disconnected.

The bug aprearing when i connect into the beta server, when im connected on beta im disconnected on towny ... but when you do /resident QJWIN for exemple in towny and im connected in beta , that return the gold i have into the beta ! and that a real problem when you have a buying shop cause i get +3600k in my ender chest on towny server and when im in beta /resident QJWIN typed in towny say i got 2g ... and that the amout i get in my enderchest but in beta ...

**To Reproduce**
1. Go to towny check you personal bank value
2. Go to beta and do /resident in towny ( ask a second mod to do it ....)
3. Normaly you will get the beta value into the towny server ...

**Additional context**
I just test it when i was in beta and my friend do the command on towny so i do not check for other configuration if the bug apearing

**Comment by Luwake29** [comment]
I got a problem I just got 200g and I wanted it to put it in gold blocks to save space so I went to a workbench and made blocks but when they were in the 3x3 square of the crafting bench, my game crashed and I think the game didn’t consider the gold to be in my inventory so when I got back in I couldn’t find my 200 gold I just got.

Would it be possible for a modder / admin to give me back my gold so I don’t have to restart from the beginning.

If you need any information message me on discord : Luwake_29

**Comment by QJWIN** [comment]
if you gold ingot was into the workbench , that mean the item was out of iventory so basicly if you get a game crach that have drop you gold at top of the workbench or into you feet close of the workbench ... Do you succed to reconnect after you crach ? if you do not you item is probably be cleared by the server LOL made a ticket in discord support maybe there is a trace of you gold in to the logs ....

**Comment by Luwake29** [comment]
Ok so how Am I gonna be able to get my gold back and also what ticket are you guys talking about.

**Comment by jkmartindale** [comment]
> Ok so how Am I gonna be able to get my gold back and also what ticket are you guys talking about.

This is a place to report technical issues with the game. If you want a moderator to look through CoreProtect logs and give you a refund, the [support Discord server](https://discord.gg/EZBYmpp) is the place to have that taken care of.
