### ISSUE TITLE
Can't sell the same items in the new sign shop :/

### ISSUE THREAD

**Issue by KaninoPika** [EarthMC/Issue-Tracker#1160]
**Server**
Towny

**Describe the bug**
https://www.youtube.com/watch?v=-Men7Mx9UG0

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft a Sharpness IV with a Sharpness IV and get a Sharpness V
2. Craft a Sharpness III with a Sharpness III and get a Sharpness IV and then do Sharpness IV+ Sharpness IV and then get a Sharpness V

**Expected behavior**
https://www.youtube.com/watch?v=-Men7Mx9UG0 As what happens there!

**Screenshots**
https://www.youtube.com/watch?v=-Men7Mx9UG0

**Additional context**
You guys maybe need to fix that!

**Comment by gazings** [comment]
I had the same problem. The old shop sign plugin didn’t regard useless NBT tags so you wouldn’t encounter this.

**Comment by Ghost-chu** [comment]
Disable repair cost checks in config may resolve this issue.

**Comment by Prismary** [comment]
Duplicate of #1144, refer to my reply there.
