### ISSUE TITLE
[Feature] Give Players the Ability to Refresh Their Perms When Glitched

### ISSUE THREAD

**Issue by gazings** [EarthMC/Issue-Tracker#1161]
**Is your feature request related to a problem? Please describe.**
The most common issue EMC players encounter is the classic “no permissions” glitch. This glitch affects the use of /n spawn, /t spawn, /ptp, and many other rudimentary commands, where one cannot execute them without going through a nether portal or asking a mod to manually refresh their perms. This can happen under many circumstances, but is most found upon logging into the server. It is a pain to new and old players alike, and is especially annoying when one finds themselves without a nether portal & has to relog and wait through queue again and/or there are no moderators online to refresh their permissions. Above all, however, it’s a detractor to new players who might be in this predicament before getting acclimated to the server and ragequit due to misconstruing its severity. I myself can relate to this because when I was a new player I shared many of these intense feelings towards the glitch. In general, it is a simple problem that should not still be extant on a server that is nearly 2 years old.

**Describe the solution you'd like**
Players should be given the ability to refresh their permissions with a command. I’m not certain that this is the way mods can fix the glitch for other players, but I think that whatever method they use should be available to anyone. This would save people from tons of frustration, namely those without priority and access to a portal who are forced to relog and sit through queue again in order to rid themselves of the glitch. I think this is something that should definitely be considered by the admins; despite it not being a game-breaking glitch, it can leave a sour taste in the mouths of new players. It is an early-stage bug that truly is not representative of what EMC has evolved to be nearly 2 years after TN was released.

**Comment by FutureLemon** [comment]
Netherportal is looking
