### ISSUE TITLE
Oak Fence Gates are not protected under the towny "Switch" command as they should be

### ISSUE THREAD

**Issue by Arganog** [EarthMC/Issue-Tracker#117]
**Server**
EarthMC

**Describe the bug**
All of the wooden fence gates except Oak are protected under towny "switch" permissions.

**To Reproduce**
1. Place an Oak fence gate in a town
2. Anybody can open/close it regardless of town permissions

3. It's a feature not a bug /s

**Expected behavior**
Oak Fence Gates should also be protected under the towny "switch" command
(this is working correctly for Birch, Spruce, Dark Oak, and Acacia gates already)

**Comment by Arganog** [comment]
It appears that Stone Pressure Plates and Iron Pressure Plates also need to be added to towny "Switch" permissions.

I believe Wooden Pressure Plates not being protected is intentional.

**Comment by BowShot118** [comment]
Oak doors and all trapdoors aren't protected.
