### ISSUE TITLE
[BUG] Tp glitch 

### ISSUE THREAD

**Issue by Vicdlt** [EarthMC/Issue-Tracker#1170]
**Server**
Towny (earthmc.net)

**Describe the bug**
This bug allows you to combat log using a tp glitch.

**To Reproduce**
1. Type /n spawn or /t spawn twice
2. It will tp you even if taking damage / moving (if you're burning with no fire res it's hard to reproduce the glitch.)

**Expected behavior**
The tp shouldn't work.

**Screenshots**
https://youtu.be/8ee1gXbEFBI

**Additional context**
The glitch is in range of anyone on server though it need a very good timing.

**Comment by Warriorrrr** [comment]
Opened an issue on the towny issue tracker as shown above, so it should be fixed soon:tm:

**Comment by Vicdlt** [comment]
ok thanks ;)

**Comment by Warriorrrr** [comment]
The lead towny dev closed my issue because I couldn't provide server files I didn't have, so either I make my own server to test it on or @KarlOfDuty opens an issue to get this patched :/

**Comment by KarlOfDuty** [comment]
It is likely not a towny issue

**Comment by jkmartindale** [comment]
This was fixed before the new 1.16 server upgrade
