### ISSUE TITLE
Derpymike

### ISSUE THREAD

**Issue by GamingRelfex** [EarthMC/Issue-Tracker#1171]
is derpymike still join server ik its not a feature JUST WANNA KNOW i miss him please tell me tyyyyyyyyyyyyyyyyyyyy

**Comment by GamingRelfex** [comment]
lol

**Comment by GamingRelfex** [comment]
i realy wna know y

**Comment by jkmartindale** [comment]
Probably not lol  
![image](https://user-images.githubusercontent.com/11380394/85605575-85932880-b60f-11ea-9c29-e4f7da846084.png)  
![image](https://user-images.githubusercontent.com/11380394/85605595-8b890980-b60f-11ea-97d0-d3d01b883b40.png)

**Comment by GamingRelfex** [comment]
wait maybes its mikederpy

**Comment by GamingRelfex** [comment]
yep its MikeDerpy

**Comment by GamingRelfex** [comment]
try that

**Comment by jkmartindale** [comment]
bruh you can check yourself, everyone has access to `/resident` (`/res` for short)

but anyway  
![image](https://user-images.githubusercontent.com/11380394/85805180-da669a00-b708-11ea-8e64-cd12d3f11a17.png)
