### ISSUE TITLE
[Feature] Bring back random world spawns

### ISSUE THREAD

**Issue by twomoo** [EarthMC/Issue-Tracker#1173]
This was posted on the wrong repo but I believe its an important issue that needs some attention.

TheSuperGamer20578 posted the following in a different repo:

Hello,

Recently I have come to notice that new players spawn in 1 starting location on the Towny server. I'm personally fine with this, but my issue is with how it is currently being operated.

The way it works allows for the individual in charge of the nation which holds the spawn location to control who has access to it. This means they can ensure only them and their friends have access to it, or only certain nations do or prevent certain nations from accessing it.

Unfortunately, this is what is happening at the moment. The individual in-charge of the spawn location's nation asks recruiters for 50g or enemies their nation, putting them in a severe disadvantage when it comes to recruiting. This allows for this individual to earn a lot of gold from their practices.

The 'king' of the current nation with the world spawn has also built shops, allowing for new players (who can easily be tricked) into spending their money - this means they will receive more traffic then other locations and thus be making a lot more money.

All together, the individuals and ways the current spawn system is run is being abused for the benefit and personal likings of the owner and friends of their nation - I believe this unfair system should not continue and the world spawn should be moved to where a non-partisan individual can handle it allowing for all to access it and not blocking certain people of disliking to them personally.

This is an injustice on the admin's part, and thus it should be up to the admins to make sure this doesn't happen once more.

And then my additional commentary to the issue below:

Lets assume that we don't even care about it being fair. Lets assume that we are simply looking our for the best interest of the server - which is to create as many new active players as possible. A world spawn like this that is completely unregulated by staff is going to be used for the best interest of the owner of the United States, which does not always align with the best interests of the server. Their primary concern is to get citizens to vote and buy from (extremely overpriced) shops and they have no particular interest as to whether or not those citizens stay active. Their n spawn is a little confusing to get out of, especially for newer players which helps to keep them trapped in the shopping area. I personally have seen many newbies confused as to what to do as they can't place blocks or go anywhere.

Secondly, the building quality is a little low. Far below what you'd expect from a server building team and a lot of new players are put off by this. Large servers like EMC usually have relatively high quality spawns, going to the United States - nice as it is - just doesn't compare with spawn points of many other servers. Many new players are heavily put off by this and leave rather quickly.

Overall, United States is a rather confusing choice for a server wide spawn point and is not conducive to creating a more active community. If the server wants to have one spawn point, have one built by and regulated by server moderators who are going to put the best interest of the server first. Personally though, I'm much more in favour of the random wilderness spawn points that the server used to have, I have no idea why those were ever removed.

**Comment by DeadGlamour** [comment]
Maybe letting new players choose their spawn point in the hub would be cool as well, like have in the compass 10 or so general locations in which you could choose, like europe, the middle east north america and so on.

**Comment by unbatedaura409** [comment]
No clue what you are talking about, I spawned in western china

**Comment by twomoo** [comment]
> No clue what you are talking about, I spawned in western china

its a relatively recent addition, within the past few months.

**Comment by 10op10** [comment]
> No clue what you are talking about, I spawned in western china

Theres a new spawn place where you spawn at this nation called baffin the spawn is no longer random

**Comment by Cactusinapumpkin** [comment]
Spawn has never been random. First spawn should be farthest away from civilization. When I first spawned it was off the coast of brazil.

**Comment by unbatedaura409** [comment]
come to think of it, ive not seen a lot of people saying they spawned in china and russia and stuff

**Comment by Cactusinapumpkin** [comment]
> come to think of it, ive not seen a lot of people saying they spawned in china and russia and stuff

I blame the corona virus

**Comment by Krazy5225** [comment]
Yes, when I joined the server I joined on the Russia/China border. Personally I am not against the idea of one spawn point for all, I just think that maybe it should be a staff built structure, maybe including rules and basic commands to get new players going. Or keep it random and have new players rely on chat to get started. Regardless, I don't think having a spawn point in one nation that might be confusing for brand new players isn't the best idea.

**Comment by KarlOfDuty** [comment]
We cannot bring that back at the moment, the plugin we used is broken in 1.15 and we have not found a good replacement.

**Comment by Ghost-chu** [comment]
I have watched this issue in the issue tracker and made this in half-hour.
https://github.com/Ghost-chu/TownyRandomSpawn
It can spawn newbies to a random town if that town passed all limits.

But the plugin still not ready for a production environment.
Needs more tests.

[RandomTownySpawn-1.0-SNAPSHOT.jar.zip](https://github.com/EarthMC/Issue-Tracker/files/4842567/RandomTownySpawn-1.0-SNAPSHOT.jar.zip)

**Comment by KarlOfDuty** [comment]
Hey think there was some misunderstanding, but the plugin we used in the past was specifically for spawning players randomly somewhere away from towns. Many towns have their spawns closed off so the new players would spawn in and be stuck forever. 

Basically the previous plugin would pick a random area on land that did not have any towns and spawn them there the first time they joined.

**Comment by twomoo** [comment]
> Hey think there was some misunderstanding, but the plugin we used in the past was specifically for spawning players randomly somewhere away from towns. Many towns have their spawns closed off so the new players would spawn in and be stuck forever.
> 
> Basically the previous plugin would pick a random area on land that did not have any towns and spawn them there the first time they joined.

Exactly this, bring it back please.

**Comment by GRAnimated** [comment]
How about having them spawn at a random nation spawnpoint? That way they can see some of the better works of EMC and they still go somewhere relatively random.

**Comment by Krazy5225** [comment]
> How about having them spawn at a random nation spawnpoint? That way they can see some of the better works of EMC and they still go somewhere relatively random.

That wouldn't work. If they did this then all nations would have to have an open spawn, to allow for new players to get out. If they did this though then it gives everyone access to the nation and the ability to walk outside the once closed off spawn. Some nations close off the spawn as people land grief around them for sand, ice, etc... So opening all nations for new players would also open it for all old ones.

**Comment by twomoo** [comment]
> > How about having them spawn at a random nation spawnpoint? That way they can see some of the better works of EMC and they still go somewhere relatively random.
> 
> That wouldn't work. If they did this then all nations would have to have an open spawn, to allow for new players to get out. If they did this though then it gives everyone access to the nation and the ability to walk outside the once closed off spawn. Some nations close off the spawn as people land grief around them for sand, ice, etc... So opening all nations for new players would also open it for all old ones.

I mean United States is basically closed off, they have a wall and its quite difficult to get out so that already doesn’t set a good precedent.

Any possibility of maybe staff run spawnpoint?

Maybe also throw in a single use rtp command?

**Comment by Warriorrrr** [comment]
Random spawns for new players have been back for a while now, no longer an issue.
