### ISSUE TITLE
[Feature] Remove/Drastically increase playercap on towns

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#1174]
The title is pretty self explanatory. Placing a playercap on towns does more bad than good in my opinion and frankly I don't see the point of it. It places a limit on one's potential which contributes to a sense of staleness and lack of things to accomplish. This is especially the case as a cap on residents means a cap on town size.

I see placing a cap on a player's and town's potential on the server as a negative thing, especially during these times.

Roughly around this time last year, the playercap was increased from 70 to 100. The reasons why are essentially identical to the reasons why it needs to be increased again or frankly, scrapped entirely. People should be able to grow their cities to not only as many people but also as many claims as they're capable of doing, not what the server limits them to.

Quite a few towns have already reached the 940 claim limit anyway, the same was true for when it was increased last year. We've lived with the 100 cap for long enough.

If the playercap isn't scrapped entirely, it should at least be increased to 150-200 and/or make it so that 1 resident = 16 claims instead of 8.

**Comment by 10op10** [comment]
I agree.

**Comment by Basically-Andrew** [comment]
I think a claim limit of 940 chunks is still a reasonable number for earthmc. However, if any change was made, I think the maximum number of residents should only be raised to 125 or only a ratio of 10, both allowing for a maximum amount of 1140 townblocks. Your suggestion of a 150-200 resident cap and the ratio of 16 would allow towns to claim 1340-1740 townblocks, a considerable amount of land on the Dynmap compared to present max claim towns.

**Comment by Basically-Andrew** [comment]
Below I have explained a few ways this suggestion can be added to earthmc by changing a few lines in the [Towny config.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) file.

The maximum number of residents that can be joined to a town can be raised or lowered from 100 in the *max_residents_per_town* line under the *global_town_settings* section of the config. Changing the number to zero will set no limit.
```yml
global_town_settings:
  max_residents_per_town: '125'
```

The maximum number of townblocks available to a town is (numResidents * ratio). This ratio is set to 8 by default. However, this ratio can be raised and lowered in the *town_block_ratio* line under the *town* section of the config.
```yml
town:
  town_block_ratio: '10'
```

**Comment by Prismary** [comment]
Is this still recent?
