### ISSUE TITLE
[Feature] Add "Mod" Prefix to Mods on Tab List

### ISSUE THREAD

**Issue by Proserrr** [EarthMC/Issue-Tracker#1176]
This is a minor aesthetic addition that i think would be a big help to many.

Firstly, we always see messages on a regular basis that say something to the effect of "Any mods online???". Adding the mod prefix to the tab list and/or putting mods to the top of the tab list will most likely decrease the presence of these messages as players will be able to check this themselves,

Furthermore, adding this will make a great benefit to newer players, who are not as familiar with the staff team and find it difficult to differentiate mods from other players. 

Right now, in game, the only form of staff identification mods possess is the mod prefix in global chat, This is ineffective
at times as mods are frequently absent from chat interaction.

I hope something along the lines of this are added given time, thank you.

**Comment by unbatedaura409** [comment]
I already spoke with Fix about this a while ago, he said it isn't gonna happen because he doesn't want even more clutter on the tab screen

**Comment by jkmartindale** [comment]
If Fix doesn't want the visual clutter, it shouldn't be too difficult to make a chat command that lists moderators and highlights who's online.

**Comment by silver-street** [comment]
Agreed. Even a command similar to Warriorrr's EMC discord bot's /onlinestaff command

**Comment by Prismary** [comment]
I'd say something like this could help a lot and is still very relevant today, even though the issue is quite old already. Maybe just making mod names green in tab would be a good alternative to the clutter.

**Comment by Basically-Andrew** [comment]
I believe `/online` used to be a thing and showed mods and other players by rank but seems to have been taken away from our permission.

**Comment by Proserrr** [comment]
(Its never getting added)

**Comment by Fruitloopins** [comment]
ok

**Comment by CorruptedGreed** [comment]
Denied by Fix.
