### ISSUE TITLE
[Feature] Mending should be obtainable by fishing.

### ISSUE THREAD

**Issue by Vicdlt** [EarthMC/Issue-Tracker#1177]
### Is your feature request related to a problem? Please describe.
Villagers trades not available.

### Describe the solution you'd like
Mending should be obtainable by fishing like on vanilla minecraft.

**Comment by Joel-02** [comment]
They should enable vanilla Minecraft fishing regardless.

**Comment by BreachDGates** [comment]
They should keep McMMO drops (CDs, ghast tears, etc) while adding Mending books under the "Legendary" category.
Above level 1000 fishing, your chances of getting a "Legendary" item (diamond armor and diamond tools) is 5%. (Would be 0,56% chance of getting Mending books if we enabled them)
Why not adding Mending books as a prize in gold crates too?
