### ISSUE TITLE
Dropping items too fast without hacking[BUG]

### ISSUE THREAD

**Issue by PugsRfat** [EarthMC/Issue-Tracker#1182]
The server the bug is on is currently that i know is towny.

Kicking due to a non hacking feature.

How To Reproduce

How to do this bug: Have alot of stacked items (preferably things that stack to 64) and look up. Then Hold q untill u get a loop of which you pickup items as fast as your dropping them on yourself. Soon enough you will be kicked for dropping items too fast.

### Expected behavior
Id expect to not be kicked for showering myself in white concrete.

**Comment by unbatedaura409** [comment]
This is built into minecraft, it is not a server issue. This never happens to me either. Get better internet connection

**Comment by Krazy5225** [comment]
It is to do with how many packets you are sending, packets are basically how you communicate with the server and if you send to many or your connection to the server is to bad and these packets cannot get through it will kick you. This is a "self defence" measure of the server to stop people trying to hack/crash it. (Or at least that is what I believe, if wrong please tell me) Either get a better connection to the server via wired internet or a better router all together, or just don't spam item drops.

**Comment by KarlOfDuty** [comment]
It happens when the server lags, not something we can really do anything about sadly.
