### ISSUE TITLE
Block glitching [BUG]

### ISSUE THREAD

**Issue by Joel-02** [EarthMC/Issue-Tracker#1183]
### Server
Terra Nova

### Describe the bug
The bug allows people to climb walls. It's a particular issue for when the war plugin comes out as it would render town walls pointless. Today there was a massive battle in the area surrounding my town, despite having proper full-on walls and having ensured it's impossible to climb, the enemy simply block glitched into my town. 

### To Reproduce

Jump and place a block against a wall in someone's town, its hard to explain, however, I am sure you are aware of it. The glitch allows people to climb walls.

### Expected behavior
You are able to climb walls in any town, despite having no perms.

**Comment by Lagann311** [comment]
build an overhang on the wall > Problem solved

**Comment by Goosius1** [comment]
Duplicate ticket to  

https://github.com/EarthMC/Issue-Tracker/issues/1127
