### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Krafff** [EarthMC/Issue-Tracker#1185]
### Server
 Hub2

### Describe the bug
 Blocks such as Brewing Stands, Signs, Buttons, can not be removed or replaced with other blocks which leads to grief that can not be fixed or removed.

### To Reproduce

1. Go to Hub2
2. Place a Brewing Stand, Button, Sign down 
3. Cannot be removed nor replaced.

### Expected behavior
 I expected to replace em with other blocks.

### Screenshots
 no

### Additional context
 no

**Comment by Zitrusgewaechs** [comment]
Screenshot: https://giphy.com/gifs/glitch-minecraft-earthmc-l0cqIQYnzrFrbOni6m

**Comment by Krafff** [comment]
> Screenshot: https://giphy.com/gifs/glitch-minecraft-earthmc-l0cqIQYnzrFrbOni6m

Sorry I just saw you made a post about the same bug before me, didnt mean to take your spotlight or whatever.

**Comment by EmattpoYou** [comment]
Just shift+right click, it bypasses Use and just places.

**Comment by Zitrusgewaechs** [comment]
I am shift+right clicking the brewing stand in the gif sent above
