### ISSUE TITLE
[Feature] Plug-in suggestions 

### ISSUE THREAD

**Issue by nl1213** [EarthMC/Issue-Tracker#1189]
Simply put the anti-xray plugin is problematic. It gets the job done sure but it has a tendency to over react when people use superbreaker with a high speed pickaxe. After a small amount of research some plugins have designs like this in mind to prevent x-ray while working with mcmmo abilities.

Particularly no cheat plus seems to describe itself working well with mcmmo. In addition it works as a general anti-cheat for other forms of hacking.

And as a final suggestion although the Dow sides are more obvious with this plugin. Clear lag can destroy entities on the ground and will help deal with high drop counts. However this might cause issues to players who drop items to trade etc ..

**Comment by EmattpoYou** [comment]
ClearLag can and does warn before deleting items on the ground, but it posts this in chat.
I do feel like the anti-xray should be fixed so that you don't have the common phantom ores while mining, since it's just ridiculous considering the lag.

**Comment by KarlOfDuty** [comment]
Thank you but we will stick to the plugins we currently use.
