### ISSUE TITLE
Nation Name Violation - Wabanaki

### ISSUE THREAD

**Issue by MrSnipeHard** [EarthMC/Issue-Tracker#119]
![nation rules](https://user-images.githubusercontent.com/44819388/48243073-57b28f00-e3ac-11e8-9a05-b0f681ca2d3e.jpg)
**_Figure 1: Nation Rules posted in Announcements_**

![response](https://user-images.githubusercontent.com/44819388/48243089-6b5df580-e3ac-11e8-95a9-4287d7fdf5ba.jpg)
**_Figure 2: Contextual Interpretation of the Rules_**

![real wabanaki](https://user-images.githubusercontent.com/44819388/48243163-e58e7a00-e3ac-11e8-9287-9c6880a87602.jpg)
**_Figure 3: Location of the Wabanaki Confederacy circa 18th Century_**

![west](https://user-images.githubusercontent.com/44819388/48243111-8c264b00-e3ac-11e8-8662-7357becde5f7.png)
**_Figure 4: "Wabanaki_West" nation and capital_**

![south](https://user-images.githubusercontent.com/44819388/48243133-a8c28300-e3ac-11e8-82db-61c8cfcb9e16.png)
**_Figure 5: "Wabanaki_South" nation and capital_**

![east](https://user-images.githubusercontent.com/44819388/48243141-b6780880-e3ac-11e8-94b6-72561b098ab7.jpg)
**_Figure 6: "Wabanaki_East" nation and capital and red outline of the actual location of Wabanaki_**

I think that my evidence speaks for itself. The past nation of Wabanaki was located in the area of present day Maine, New Hampshire, Vermont, and Acadia. It did not span the entire continent of North America nor did it reach beyond the St. Lawrence River where "Wabanaki_East" is located. The three nations do not correspond with the map location of the actual Wabanaki. Based on the nation rules, mine and Karl's interpretation of it using an analogy, and the location of the capitals of the nations: "Wabanaki_West", "Wabanaki_South", and "Wabanaki_East" should be forced to move their capitals to the region of real life Wabanaki or change their names.

**Comment by sharkfynn1012** [comment]
All of these nations are under the same rule, we had planned to have our capital located closer to the realistic location but that’s changed with the rules on range. And really if there are enough fucks to give here all that needs to happen is a name change. What is the point in going after nations for their names that are not completely fictional and when all that would come of it would be a nation name change. Ooh, France is is Germany! Ban them! Change their name!

**Comment by MrSnipeHard** [comment]
“We had planned to have our capital located closer to the realistic location”

That is a complete lie, Shark, and you know it. Do you forget that I was a Canadian who was there through the months of Canadian Terra Nova planning and still there a week after full release? Wabanaki’s capital was originally planned to be in the Dakotas until the nation found out about range restrictions days before early release.

**Comment by KarlOfDuty** [comment]
This is for making server changes, not individual matters. Use a support ticket for reporting rule breakers next time.

**Comment by sharkfynn1012** [comment]
I’m fully aware that you were a Canadian. And no, that is not a complete lie. I did say we planned to be closer no? Dakota is a far closer capital than Wabanaki west or south. So no, I didn’t lie.

**Comment by sharkfynn1012** [comment]
Thanks Karl, this really I feel is just a personal issue. Snipe are you going to be the name police for everyone or just guard us? If naming is an issue there are many Native American tribe names to chose from.

**Comment by TypicalFernie** [comment]
What Canadians don't understand is that a lot of people in this server want to replicate the real life nations and then make their own history. There's a reason they play on an earth server on not any other server out there. We all understand that you guys are a community that want to remain in one nation. All you had to do is pick one simple location and settle there as a community. Even if you don't remain in one nation, since a lot of you want to make towns across north america, You still have a community in discord where you can talk and be friends. Y'all not only trying to break the server rules, but also the way towny works. And I can confirm that the capital was always planned to be in Dakota. It was shown in their claims map.

**Comment by sharkfynn1012** [comment]
Yep, the capital was always going to be Dakota. Fernie spied on that and we said that so many times. Anyone can settle where they want, you can roleplay but I can easily say back to you that we want to be a community that isn’t role playing but rather that we are our own thing. Have you ever thought that maybe we also just want to get along and play?

**Comment by Synargle** [comment]
This is the wrong place for this discussion. 

This issue was closed earlier. Please refrain from commenting any further if that's fine.
