### ISSUE TITLE
More potion ingridents 

### ISSUE THREAD

**Issue by Chotobits** [EarthMC/Issue-Tracker#1190]
Hello I am a high level alchemist on the emc server and I have recently been playing on the beta. As a potion brewer valuable items such as spider eyes a phantom membranes that are useful in potion making are hard to come by and very expensive. What I am trying to ask for is a way to get more ingredients such as phantom membranes spider eyes and ghast tears into the emc economy as the wider variety of potions that can come from it will make the gameplay more enjoyable and competitive. 
While this may seem to be only favoring me in reality I already have large stockpiles of both spider eyes and ghast tears which would lose value of more were introduced into circulation. 

I have just seen how much fun me and my friends have had in beta with the increased number of potions and I wish to ask that you consider adding a way for items such as these to be more accessible in game play.

**Comment by Lagann311** [comment]
I agree, if those ingredients could be added as an mcmmo drop from soul sand flr example that would be great. Spider eyes are needed for a lot of potions and phantom membranes are basically unable to obtain atm

**Comment by shirazmatas** [comment]
follow format and repost
