### ISSUE TITLE
Premium Not Working

### ISSUE THREAD

**Issue by RossYoung1690** [EarthMC/Issue-Tracker#1191]
My friend Ernesto3538 Gifted me premium rank on the server and its been 3 hours but the only thing ive obtained from that time is the queue skip. i was wondering if someone could help me get my rank please.

**Comment by 10op10** [comment]
Open a ticket on the emc support discord

**Comment by JaVolimKatarinu** [comment]
If you are on the Towny server, please try linking your Discord and Minecraft profiles. Do /discord the link and follow the steps. After completion, the bot should update your roles in 5-15 minutes since completion.

**Comment by KarlOfDuty** [comment]
As stated above, open a support ticket on our discord instead, this is for more general issues.
