### ISSUE TITLE
[Feature] Very, Very Rare Mob Spawns

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#1193]
### Is your feature request related to a problem? Please describe.
Not really, but it would be cool to have very rare mob spawns as most mobs are basically extinct atm.

### Describe the solution you'd like
Very rare mob spawns.

**Comment by Cactusinapumpkin** [comment]
Do you mean mobs to be spawned rarely, or that you what rare mobs to spawn?

**Comment by Lagann311** [comment]
I love you Cactusinapumpkin

**Comment by jkmartindale** [comment]
Dang, rndm-prsn deleted their account fast lol
