### ISSUE TITLE
[Rule change] 2.4 revision.

### ISSUE THREAD

**Issue by EmattpoYou** [EarthMC/Issue-Tracker#1195]
Let's admit it. Rule 2.4 is broken. Some mods have used this to warn innocent people for slightly toxic comments.

The rule is: (if you haven't seen it enough)

>2.4 Unwanted behavior.
Listed unwanted behavior is not allowed on the server. Unwanted behavior includes:
Explicit forms of bullying.
Repetitive use of derogatory terms.
Comments encouraging self-harm.
Inciting violence or explicit forms of hate speech against racial and social minorities.
Explicit talk about sex.
>
>Toxicity is evaluated on a case by case basis and staff have the final say in what is considered toxic behavior. Repeated behavior may lead to warnings, mutes, and eventually a permanent ban.

The rule should be

>2.4 Common sense.
Act like everyone on the server is your friend group. You may get into fights (just like your IRL friend group), but none of the below is allowed.
>
>Explicit forms of bullying. (warn, and possible ban)
Repetitive use of derogatory terms. (mute and warn)
Comments encouraging self-harm. (warn, if severe, ban)
Inciting violence or explicit forms of hate speech against racial and social minorities. (mute, warn, and if extremely violent/hateful, ban)
Explicit talk about sex. (mute)
Outright toxicity to a group, or a person. (mute)
>
>If you do accuse someone of breaking these rules in a ticket, multiple mods will read through the evidence you have provided, and will come to a consensus if the accused has broken this rule.

This makes the rule more specific and makes it modpr- I mean foolproof and would help the community greatly

**Comment by Nikocholas** [comment]
I don't think the rule is broken. There might be different ways to explain it but it isn't broken.

**Comment by shirazmatas** [comment]
post rule suggestions here https://github.com/EarthMC/EarthMC.net/issues
