### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Tokyorift** [EarthMC/Issue-Tracker#1198]
ME GETTING MY CODE FOR THE THING MAP THINGY WONT WORK D: user : tokyorift

**Comment by glitchism** [comment]
u mean dynmap?

**Comment by Cactusinapumpkin** [comment]
What I think he is trying to say is that the captcha was requesting him to enter the code from the dynamap and when you look at earthmc.net/map it does show anything. I had this same issue so I relogged and got a different captcha, I also have premium so I don’t worry about how long I have to wait in queue.

**Comment by Cactusinapumpkin** [comment]
Also captcha has been removed
