### ISSUE TITLE
My account is bugged

### ISSUE THREAD

**Issue by kitchendroop** [EarthMC/Issue-Tracker#1199]
My ign is "kitchendroop" 

My problem is on Towny,

Info - I try to do /t spawn <any town> and it says in red text in chat,
[Towny] Public spawn travel to other towns is forbidden.

I try to say something in chat and it says again in red text in chat, 

! There is no plot in this location. Your message could not be sent.

How to Reproduce - No way to reproduce the behaviour

1 - Teleport to the town
2 - Say something in chat

Screenshot - ![Small Prob](https://user-images.githubusercontent.com/68329271/88161375-7f11c400-cc42-11ea-82ef-6619085864da.PNG)

Additional info - I have been inactive for more than a month, I don't have priority queue and I use 1.15.2(Optifine)

Hope you can help :)

**Comment by JaVolimKatarinu** [comment]
Please try visiting Nether or relogging. If there is any mod online, ask them to refresh your perms. 
Common issue, methods above should fix this up. 
If issue is still present, please open a support ticket in [EMC Support discord](https://discord.gg/EZBYmpp).
