### ISSUE TITLE
nation tp

### ISSUE THREAD

**Issue by JakubdotPLGB** [EarthMC/Issue-Tracker#120]
we should be able to tp to specific towns in the nation instead of just the capital. it would save time and be more practical, especially for a national market.

**Comment by Jettermann** [comment]
It is this way to add realism and to encourage large transportation systems. This is a feature that will definently not change but lots of players have debated wether or not wanting to remove /n spawn to an allied nation. I personally think there should not be any TP to allied nations.

**Comment by KarlOfDuty** [comment]
We do not feel like this would be beneficial to the server at this point.
