### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DontUwU** [EarthMC/Issue-Tracker#1200]
### Server

play.EarthMC.net

### Describe the bug

When doing potions, locked potion recipes (Haste potion in this case) is unlocked by simply going to another chunk.

### To Reproduce

1. Put in the carrot in the brewing stand, with the akward potions below.
2. Go to another chunk, preferably 2 chunks away.
3. Go back and take your potions.

### Expected behavior

I didn't expect nothing as it was locked but when I came back to make a new potion, I found my haste potion there, ready to be used.

### Screenshots

I don't know a possible way to screenshot it.

### Additional context

This also has to be done for any other extra item in that potion, such as glowstone, redstone and gunpowder.

**Comment by Basically-Andrew** [comment]
Either this is a bug with mcmmo, or you do have hast potions unlocked. If this is a bug with mcmmo, I would close this issue and report it to mcmmo's Github as earthmc can't do anything past changing the config for the plugin.
