### ISSUE TITLE
Cow Disappeared 

### ISSUE THREAD

**Issue by Budzygames** [EarthMC/Issue-Tracker#1204]
Earth.MC Towny

I had just purchased a cow and I was using wheat to move it from my house to a connected one next-door. 

### To Reproduce

1. Place cow on your plot 
2. Grab wheat
3. Try to move the cow 

After I had just spent 9g, I was expecting to move my cow to my lower farm. I was only at the top level of my house and I and the cow weren't touching anything. I just expected the cow to follow me. 

N/A

Chat and logs show that I purchased the cow and the time of the event 

ign:Budzygames

**Comment by Cactusinapumpkin** [comment]
I noticed a lot of issues come from moving the mobs and they just disappear and I havnt seen a correlation with the amount of mobs already in a chuck. Usually the chunk is empty and I also notice that is a chunk that is loaded/active a lot that it will disappear

**Comment by KarlOfDuty** [comment]
This happens in minecraft servers, it can't really be fixed.
