### ISSUE TITLE
Towny rank bug

### ISSUE THREAD

**Issue by 32Puschel** [EarthMC/Issue-Tracker#1205]
### Server
earthMC.net

### Describe the bug
i joined the town Tortuga, part of Haiti the mayor and King bennygaming808 gave me trusted role ect they are getting reseted every like 1,5 days i had a bug that i couldnt change a plot to a shopplot but it was my plot.

### To Reproduce
idk how its just there

### Expected behavior
most of my roles get removed

### Screenshots
none

### Additional context
goinginto the nether doesent help sorry for my bad english Username: 32Puschel

**Comment by SundraLOL** [comment]
Did you try /plot evict /plot fs 0 /plot claim?

**Comment by KarlOfDuty** [comment]
Should be fixed.
