### ISSUE TITLE
[BUG] my maps are broken 

### ISSUE THREAD

**Issue by Krafff** [EarthMC/Issue-Tracker#1206]
### Server
 Towny

### Describe the bug
 11 of my maps are blank,

### To Reproduce

I don't know how to, I logged on and a lot of it was blank.

### Expected behavior
 not to have blank maps

### Screenshots
 no I don't have any but you can see it at /n spawn Orlando.

### Additional context
 contact me at @krafff#4884

**Comment by jkmartindale** [comment]
If it makes you feel any better it's not just you with this issue, there's also #978 and #1163.

**Comment by KarlOfDuty** [comment]
Hopefully fixed now with the new server version.
