### ISSUE TITLE
Invalid payload REGISTER error when Fabric API installed because of server software

### ISSUE THREAD

**Issue by musabagriyanik** [EarthMC/Issue-Tracker#1207]
This server allowing Litematica, but you know Litematica needs Fabric Loader, Fabric API and MaliLib, so we can't use Fabric API because of the server software bug. I contacted with some guy and he said the server developers have to fix this bug or update their server software to fix this, he said we can't do anything. Take a look here: https://github.com/FabricMC/fabric/issues/849#issuecomment-650654110

Fabric is a good mod loader and most of modifications needs Fabric API (Fabric Loader and Fabric API are different things.) please fix it, I can't use Litematica, Replaymod, LambDynamiclights bla bla bla and more. I am on 1.16.1 version of Fabric and Fabric API

My talks with a guy from Fabric Discord
![image](https://user-images.githubusercontent.com/40427422/88500677-0d36d300-cfd2-11ea-846c-48e0137c24a3.png)

**Comment by jkmartindale** [comment]
As mentioned in the issue linked by @musabagriyanik, PaperMC/Paper@d09826f added a flag to disable the channel limit. If EarthMC doesn't use Paper, it's also trivial to patch [CraftPlayer.java](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java) on Bukkit-compatible servers to increase or remove the limit.

> Litematica works fine for me on fabric on the server

Seconded. Litematica uses its own API mod instead of the Fabric API, so using just Litematica (and other mods that don't depend on the Fabric API) with 1.16 works with EarthMC.

**Comment by musabagriyanik** [comment]
> Um do you need help? Litematica works fine for me on fabric on the server. I have only used it once so Idk really what i did but If you need help message me on discord Coblobster#9240

The problem is about 1.16.1, not 1.15.2. Fabric API and 1.16.1 server software conflict.

> You probably use 1.15.2. This version works. However, 1.16.1 dosent. The only fix to allow people using 1.16.1+ fabric has to be made by server admins.

Yes.



> As mentioned in the issue linked by @musabagriyanik, [PaperMC/Paper@d09826f](https://github.com/PaperMC/Paper/commit/d09826f) added a flag to disable the channel limit. If EarthMC doesn't use Paper, it's also trivial to patch [CraftPlayer.java](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java) on Bukkit-compatible servers to increase or remove the limit.
> 
> > Litematica works fine for me on fabric on the server
> 
> Seconded. Litematica uses its own API mod instead of the Fabric API, so using just Litematica (and other mods that don't depend on the Fabric API) with 1.16 works with EarthMC.

EarthMC uses Waterfall and Waterfall forked by PaperMC developers from BungeeCord.

**Comment by jkmartindale** [comment]
This seems to have been fixed, I've been able to play on EarthMC with 1.16.2 and Fabric API 0.20.1 build 401.

**Comment by musabagriyanik** [comment]
> This seems to have been fixed, I've been able to play on EarthMC with 1.16.2 and Fabric API 0.20.1 build 401.

I didn't tried with Fapic API 401 but I tried older versions and yeah it seems it fixed.
