### ISSUE TITLE
[OPEN] Discussion about the war plugin: Tips, suggestions, debate relating to the war plugin

### ISSUE THREAD

**Issue by ketchupdrinker** [EarthMC/Issue-Tracker#1208]
**It seems like many people are excited on EMC for the new war plugin**
Features like this don't come often to the server so it's nice to see change in the way the server runs and functions to keep people active and engaged.
The war plugin was originally developed to enhance the geopolitical experience, but as I've seen with the war plugin in it's final stages and the server preparing for the new feature, players seem to interpret the use of the war plugin differently.

It seems that there are 2 ways players interpret the use of the war plugin on EMC
1. The war plugin was made to enhance the geopolitical aspect of EMC, encourage people to be less toxic, form alliances with more nations, and to have war as a feature for nations that wrongfully invade claims or harass and kill their nations members.
2. For nations with mostly pvpers, they will be able to use this feature to invade all nearby towns and nations and to bully towns and nations not alligned other pvp meganations into submission.

I've seen players on EMC think of war as just a training for PVPers and this worries me greatly because EMC is not a PVP oriented server.

Back to my original point, it seems like one of the intentions of the plugin was to stop toxic players from harassing other nations without circumstances but this defeats the original purpose of that point when the toxic players are often experienced PVPers.

If the war plugin on EMC takes this turn for the worse and people take advantage of it with no geopolitical interest or no reason for warring a nation and invading them, it seems like this would frustrate the non PVPers in the server (because EMC isn't necessarily solely a PVP server).

(Opinion) I want the war plugin to be implemented, but I fear people can take advantage of the power it gives them and make EMC a more hostile environment full of petty PVPers who invade you if you are anywhere close to their nation.

**This is an open debate/discussion chat, please correct me if I've made any mistakes. Aswell feel free to agree or disagree and make points/opinions in the comments**

**Comment by Nikocholas** [comment]
Sounds good. So if an unofficial soldier kills you during a siege (inside the warzone)... do you still keep the inventory?

**Comment by Goosius1** [comment]
Yes, as long as you are official yourself, the cause of death is not relevant, you keep inventory in all cases.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by CorruptedGreed** [comment]
Old SiegeWar discussion
