### ISSUE TITLE
Move the world spawn

### ISSUE THREAD

**Issue by TheSuperGamer20578** [EarthMC/Issue-Tracker#1209]
Hello,

Recently I have come to notice that new players spawn in 1 starting location on the Towny server. I'm personally fine with this, but my issue is with how it is currently being operated.

The way it works allows for the individual in charge of the nation which holds the spawn location to control who has access to it. This means they can ensure only them and their friends have access to it, or only certain nations do or prevent certain nations from accessing it.

Unfortunately, this is what is happening at the moment. The individual in-charge of the spawn location's nation asks recruiters for 50g or enemies their nation, putting them in a severe disadvantage when it comes to recruiting. This allows for this individual to earn a lot of gold from their practices.

The 'king' of the current nation with the world spawn has also built shops, allowing for new players (who can easily be tricked) into spending their money - this means they will receive more traffic then other locations and thus be making a lot more money.

All together, the individuals and ways the current spawn system is run is being abused for the benefit and personal likings of the owner and friends of their nation - I believe this unfair system should not continue and the world spawn should be moved to where a non-partisan individual can handle it allowing for all to access it and not blocking certain people of disliking to them personally.

This is an injustice on the admin's part, and thus it should be up to the admins to make sure this doesn't happen once more.

**Comment by Cactusinapumpkin** [comment]
@World spawn moved to north eastern Asia/Russia
