### ISSUE TITLE
/msg doesn't work

### ISSUE THREAD

**Issue by JakubdotPLGB** [EarthMC/Issue-Tracker#121]
**Server**
Terra Nova

**Describe the bug**
I try to message people using /msg but it says that I don't have access to that command.

**To Reproduce**
/msg [anyone]

**Expected behavior**
being able to message 

**Screenshots**

**Additional context**

**Comment by Jettermann** [comment]
It is temporarily disabled because it put strain on the server. Fix is looking into it.

**Comment by KarlOfDuty** [comment]
Fixed.
