### ISSUE TITLE
Unable to send or read any messages in global or trade chat[BUG]

### ISSUE THREAD

**Issue by HydroSatire** [EarthMC/Issue-Tracker#1211]
Towny

When I try to send a message in global or trade chat, chat replies with "You have no channel to write into. Type /ch for help." I've tried leaving all channels and rejoining, but to no use. I'm able to write in any of the language, nation, and town chats, just not global or trade.

1. Type "/g", "/ch j global" or any other command to join either trade or global chat
2. Send a message in chat
3. The text "You have no channel to write into. Type /ch for help." appears in chat, no matter how many times you attempt to send a message

I should be able to read and send messages in global and trade chat

### Screenshots
![image](https://user-images.githubusercontent.com/69060932/89087399-24731900-d362-11ea-8bb4-43641e29631f.png)

I've tried restarting my computer, leaving and rejoining, basically everything restart related

**Comment by ImNotStealthyBro** [comment]
Ok this has been happening to me to I tried joining town chat and afterward I cant see the global chat, im trying to enjoy my time on the server but i need to ask in chat if anyone needs a worker for money and i cant do that because of this glitch this needs to be fixed immediately

**Comment by ImNotStealthyBro** [comment]
Alright well i have to say my chat was fixed but i have no idea how. Hopefully yours is fixed.
