### ISSUE TITLE
Selling in bulk

### ISSUE THREAD

**Issue by Zardinio** [EarthMC/Issue-Tracker#1212]
I'm frustrated to find out I can't sell sand in bulk because the current store plug in maxes out at a stack. I want to be able to sell sand in bulk. I just spent 20g to buy a store in order to find out I can't actually do anything productive with it. 

 I have to hand off inventories at a time to other players after advertising in chat. Which can get annoying by the fifth dub. Not to mention the fact that none of the many uses for sand can't be sold be sold for 1g per stack. Like, I can't sell glass or sandstone for 1g per stack. Maybe, concrete.

Please allow us to sell certain raw items in bulk, like sand and stone, by increasing the sell limit for these items.

Let the sand flow likes spices.

**Comment by DasCodes** [comment]
You can use `/qs size` in-game to change the amount of items being sold/bought.
