### ISSUE TITLE
Just some changes I'm thinking about

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1213]
I think maybe we should re-add the joining and leaving messages. GGOVI bots caused them to be disabled nearly a year ago, and as of now he spams bots maybe once every 3 months. I believe there's no point for this feature to still be removed if the problem it was created to solve is now mostly gone. I believe the same thing goes for the spam filter, Before the spam filter was introduced people may have spammed but mods would quickly mute them, and again, the problem it was created to solve is mostly gone (GGOVI) I think the same thing applies for the word filter (can you guess what i'm going to say here?) Having the word ggovi still filtered makes 0 sense as he just says gg0vi, same as everybody else on earthmc. I also believe death messages should be re-enabled in the overworld. I'm not too sure why they were disabled but from what I've heard it was because Tom did something with them. Again, this problem is mostly gone and should be gone for a very long time now that /suicide is also gone. Just some thoughts, let me know what u think

**Comment by Zardinio** [comment]
Global Chat right now is still pretty hectic. The only thing I dislike from the current message sending is that I can't send repeated messages. I can't say "Yes." And follow up with "Yes" again.

**Comment by jkmartindale** [comment]
Yeahh, global chat enough of a firehose without join/leave/kill messages that are in Discord anyway
