### ISSUE TITLE
Stuff I'd like to see change about staff and moderation

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1214]
This isn't in regards to any rules or punishments, or any vendettas against or for mods, these are just some things I'd like to see change in how staff are managed.

Firstly I want to start off by saying the new staff introduced this year have been very good at what they do (for the most part). I dislike no staff member.

What I'm suggesting here is that there should be a timer around staff, kind of like the 42 day timer where you get purged from the server if you don't log on. Currently, there are tons of staff members I can name who I either haven't seen in nearly a year, or when I have it has been in short bursts before they quit again. I believe staff should be put on a timer where if they don't log on in that time they are removed from the staff team and must apply again. This helps avoid inactive staff and assures every staff member is an active player and can help accordingly. I'm not sure what this time limit should be, it's merely a suggestion that I think could really help. When new players join EMC, and they need help, they'll go to #general or #memes or whatever and ping the first staff members they see. A lot of the time, that staff member is inactive and will not reply to the ping(s). This leaves the player unhelped and feeling negative about the moderation on EMC. let me know what you think, :)

**Comment by unbatedaura409** [comment]
Maybe they could add a "vacationing staff" or "retired staff" role

**Comment by EstonianMapping** [comment]
> Maybe they could add a "vacationing staff" or "retired staff" role

A "Hiatus" role would probably work since some staff members are just taking a break from EMC.

**Comment by FutureLemon** [comment]
> Maybe they could add a "vacationing staff" or "retired staff" role

I agree I've heard the argument by staff before that EMC isn't that big and doesn't really need it but, even something such as EMCL has something for people on breaks and retired staff just to keep in touch with them and to show that they're not avaible for a while.

**Comment by shirazmatas** [comment]
please follow format
