### ISSUE TITLE
[BUG] Repairing Enchanted Stone Tools with Anvil Crashes Minecraft

### ISSUE THREAD

**Issue by Enigma01x** [EarthMC/Issue-Tracker#1215]
### Server
Earth MC Towny Server

### Describe the bug

When repairing enchanted stone tools (gained from fishing) on an anvil, Minecraft crashes upon placing the stone in the repair slot of an anvil. Unsure if this is due to the tool being from fishing and having conflicting enchants (Smite, Sharpness, and Bane of Arthropods) or if an issue with repair in general.

### To Reproduce

1. Obtain enchanted stone tool from fishing.
2. Place in anvil
3. Place stone in anvil to repair (crashes here)

### Expected behavior

I thought I could repair the sword as normal.

**Comment by glitchism** [comment]
Same, I got like for 4 swords that have that conflicting enchants, useless stuff

**Comment by FutureLemon** [comment]
The special McMMO fishing items with double enchants such as sharpness and smite on one sword or protection and fire protection on one item cannot be repaired.

**Comment by DasCodes** [comment]
@glitchism Do you still have any of those swords?

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/93154228-c0fe3a00-f6c8-11ea-915d-2fd06297caf1.png)
