### ISSUE TITLE
[BUG] Disappearing tamed animals

### ISSUE THREAD

**Issue by EliteFromYT** [EarthMC/Issue-Tracker#1216]
I took some time to transport a cow from sicily to my city in game, palestine, and I had it named with a name tag and I locked it in a never to escape area and an area where they can't glitch. At some point I stopped hearing the mooing of the cow and when I went to check, it disappeared, it's gone and also there is a problem with the gold in ender chests, a piece of it just disappears.

**Comment by Cactusinapumpkin** [comment]
The server mob limit was reduced to 6 I believe. Did you just have one cow?

**Comment by EliteFromYT** [comment]
Your response is so late, I already got a lot of cows and I am getting leather.
