### ISSUE TITLE
[BUG] Switching Towns Unclaims my Embassies

### ISSUE THREAD

**Issue by Enigma01x** [EarthMC/Issue-Tracker#1219]
### Server

EarthMC Towny

### Describe the bug

When switching towns (I do builds for multiple towns), I lose my embassy plot claim (although I only lose my claim in Colorado, not my original house in Tokyo). Is there a plot setting I need to do to not lose the embassy when I switch towns?

### To Reproduce

1.  /t leave
2.  /t accept <new town>
3.  visit previously owned shop, no longer mine

### Expected behavior

I expected to keep my shops, since they are embassy plots.

**Comment by Enigma01x** [comment]
Issue was fixed if I join the town the plot is in before claiming the plot

**Comment by SundraLOL** [comment]
That's not a bug pretty sure it's how towny works. If you need to ask them or report if it's a bug then go to their official discord.
Discord: https://discord.gg/gnpVs5m
GH: https://github.com/TownyAdvanced
