### ISSUE TITLE
Add ViaVersion and ViaBackwards

### ISSUE THREAD

**Issue by TheGoatOnABoat** [EarthMC/Issue-Tracker#122]
**Is your feature request related to a problem? Please describe.**

No, there is no bug or other problem relating to this.

**Describe the solution you'd like**

I think you should add ViaVersion and ViaBackwards plugins so players can connect using 1.13 and 1.13.1, as well as future versions. 

**Additional context**

VoxelMap for 1.13 just came out, so it would be useful to play with since minimaps are allowed.

**Comment by KarlOfDuty** [comment]
Viabackwards does not exist for 1.13
