### ISSUE TITLE
[BUG] "You currently have 0g" BUG

### ISSUE THREAD

**Issue by Detonage** [EarthMC/Issue-Tracker#1222]
### Server
on Main Towny earthMC.net

### Describe the bug
/balance says "you currently have 0g" despite i'm literally holding gold. Also Chest Shop didn't work either. After 10 minutes(or longer) it reads the gold i have in my inventory.

### To Reproduce
1. /res "0g"
2. /balance "You currently have 0g"
3. /money "You currently have 0g"
4. trying to buy anything in chest shop. "It cost Xg ,but you only have 0g"

### Expected behavior
I expected to read gold when it is in my inventory (not waiting like 10 minutes[or more]). 

### Screenshots

https://imgur.com/a/nrqL82p

### Additional context

Also didn't read golds in Echest aswell

**Comment by DasCodes** [comment]
Please make a ticket on our support Discord for this.
