### ISSUE TITLE
[BUG] Dynmap not showing stars for some capitals

### ISSUE THREAD

**Issue by premraghvani** [EarthMC/Issue-Tracker#1224]
### Server
Towny (obviously)

### Describe the bug
I have noticed, if the king of a nation has been offline for a certain period of time (not sure exactly how much),  it doesn't show the star on the dynmap. A few examples are/were:
- Eston // Maldives
- Doha // Qatar
- Suar // Tenjiku

### To Reproduce
Dynmap problem, visible if a king has been offline for a certain period of time

### Expected behavior
The nations listed should have stars indicating it is the capital

### Screenshots
![image](https://user-images.githubusercontent.com/69864865/92305730-cf8a7a00-ef81-11ea-91c1-6cf3655ac891.png)

### Additional context
N/A

**Comment by SuperChrisBoy** [comment]
I noticed this issue as well. Not sure if it's intentional.

**Comment by gazings** [comment]
This is not a bug, it is intentional and it happens when a nation leader is offline for more than week. I believe this is probably to prevent stars from cluttering the dynmap.

**Comment by KarlOfDuty** [comment]
That is correct, yes.
