### ISSUE TITLE
3D Map render on the Homepage

### ISSUE THREAD

**Issue by StatusFlunder22** [EarthMC/Issue-Tracker#1225]
3D Map render on the Homepage

[BlueMap render Plugin URL](https://github.com/BlueMap-Minecraft/BlueMap/)

**Comment by jkmartindale** [comment]
This would be really cool, but with the current performance EarthMC is getting I don't think adding compute and storage load is a good idea. Those are the reasons Dynmap's built-in 3D map was turned off (see #65, #308, #638).

**Comment by StatusFlunder22** [comment]
With BlueMap you can limit the power it needs.
