### ISSUE TITLE
3.3 Text Revision

### ISSUE THREAD

**Issue by Neowyld** [EarthMC/Issue-Tracker#1226]
Current Text: 

> 3.3 Town claims
Towns are not allowed to have areas of unclaimed chunks inside of their borders as this can substantially increase the size of a town without them actually having to increase their claim limit legitimately. Surrounding other towns with claims is also not allowed, about 3/4 of the town has to be surrounded for it to count as illegal. The only exception to this is when a town is created in an area where it is already surrounded.

Proposed Text:

> 3.3 Town Claims
Towns are not allowed to have areas of unclaimed chunks inside of their borders as this can substantially increase the size of a town without them actually having to increase their claim limit legitimately. Surrounding other towns with claims is also not allowed, about 3/4 of the town has to be surrounded for it to count as illegal. The only exception to this is when a town created in an area where it is already surrounded. **Additionally, claim arms which extend beyond a "natural border" by two chunks or more must be at least three chunks wide consistently.**

Many people have called for a revision to 3.3, and some have even said to revert it to the old rule. The iteration of the rule I am proposing will dissuade claim blocking in a severe financial way without staff intervention. It makes it so that it costs 48g per length to arm toward or across another town. It will also encourage more "natural-looking" borders instead of the spaghetti bordergore we are getting currently. 

One thing the current claim rule did was relieve a lot of unnecessary work for the staff team. Claim blocking should be a geopolitical issue, not a staff issue. Extreme cases should be dealt with, but my iteration of the rule would make enforcement easier than enforcing the hollow claim portion of the rule, meaning less tickets and less time a ticket is open of that category. 

The old rule should not make a return because it flooded the claim blocking category with issues the staff team simply should not be dealing with. Borders should be allowed to touch if done so in a natural way. There were so many cases of people simply expanding and the "victim" would make a ticket. Then the mod would have to be a third party in border agreements. Those tickets would be left opened forever, and the mods assigned would have to keep track of every agreement. It was far too impractical. 

I would suggest that players be given about two weeks of preparation to either widen their claims, or submit tickets for refunds if this new rule were to go into effect. 

Discussion can be made about the proposed width and the length which a claim arm starts and what constitutes a "natural border."

**Comment by FutureLemon** [comment]
Wrong page x) https://github.com/EarthMC/EarthMC.net/issues

**Comment by Mikeyreza** [comment]
I get and agree with the general idea of what you're saying here, but 2 chunk limit for how far you can expand with it being more of an arm than a natural extension is just too strict in my opinion. It should be more like 5 chunks since I dont think you can make a gigantic Loopins Wall claimblock with only 5 chunks.

**Comment by Neowyld** [comment]
> Wrong page x) https://github.com/EarthMC/EarthMC.net/issues

yeah theres no link to that on the emc discord, and it's difficult to use this site for anyone who is a newcomer to it or isn't a coder. Still really strange to me that we use github. most people i've come across dont like it, but that's another issue entirely. Thanks for linking me

**Comment by Neowyld** [comment]
Closed because wrong page

**Comment by FutureLemon** [comment]
> > Wrong page x) https://github.com/EarthMC/EarthMC.net/issues
> 
> yeah theres no link to that on the emc discord, and it's difficult to use this site for anyone who is a newcomer to it or isn't a coder. Still really strange to me that we use github. most people i've come across dont like it, but that's another issue entirely. Thanks for linking me

Yeah... When TN started Github was very good and actively used by staff and player for suggestions and bug reports. It was very succesful IMO, but it slowly died once toycat and fuze came due to a lack of promotion regarding the Github. I think it's original reason was to prevent ticket flooding with bug reports to make it lighter work for the devs and staff team seperated.
