### ISSUE TITLE
[FEATURE] Dungeons, Mobs, and Hope

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1227]
EarthMC is declining in quality. But hopefully, it can be saved and made even better.

My first suggestion is arguably my most drastic one. I'd love feedback on it below. But enough stalling, here it is; 

**Remove The Nether.**

By removing the nether, we are denying players the experience of nether exploration and the chance of finding wither skeletons which may (if they're incredibly lucky) lead them to getting a nether star. Rest assured, this is not what I'm concerned with. While in the overworld, you are protected by the rules and conditions of the server. In the Nether however, it is complete anarchy. Anything you build can and most likely will be greifed, and most all the fortresses have been completely robbed.
 It also eats up a ton of the server's data. By deleting the nether's files from the server, along with the nether itself not supplying access anymore, we can free up some space.

One of the big problems you may immediately see may be "well, what about the materials exclusive to the Nether?". Well, strawman, I'm getting to that.

By building a portal, you would essentially be making a generator. From which, items and very rarely, mobs, will spawn from. But you yourself will not be able to go into the portal.

Let's say every few seconds, the portal has a chance of dropping a random nether item. 50% chance of netherrack stacks, 50% for a stack of nether quartz, 25% for nether warts and soulsand. Every hour, it has a chance at spawning a mob from the Nether. As we all know, nether mobs are pretty damn rare. So pigmen would naturally have the highest chance, while something like ghasts or wither skeletons would be much more uncommon.

If this doesn't satisfy, I have an alternative. Craftable nether materials. It's no secret that EMC has some custom crafting recipes (examples being; prismarine, ink from coal, end rods, etc.), and these would fit in nicely.

Let's face it, redstone is EVERYWHERE and so easy to get. So, I think an alternative use for it should be turning items into nether versions of themselves. Gravel, if surrounded by redstone, will turn into a block of soulsand. If you surround white stained glass with redstone, you get 4 pieces of nether quartz. 
![image](https://user-images.githubusercontent.com/46580909/93145957-a5406700-f6bb-11ea-953f-98115eb322e8.png)
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "#W#",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:redstone"
        },
        "W": {
            "item": "minecraft:white_stained_glass"
        }
    },
    "result": {
        "item": "minecraft:quartz",
        "count": 4
    }
}
________________________________________________________________________________________________________

My next suggestion is something the community **was** looking forwards to for quite a while, but it never came to fruition.

**Dungeons.**

Dungeons never really came to EMC, due to a combination of Staff's business and a slight disinterest in PvE combat in the initial community. But allow me to make my argument for them, and how the community can be a big part in this.

User Generated Dungeons. Or UGD for short, is a program I've been thinking of for a while. While not fully fleshed out, I do have a good line of ideas. To become a "Dungeoneer" (a creator of dungeons), you must first apply for it on the EMC GitHub. The application will contain questions such as "What theme will the dungeon have?" "Do you have previous experience designing dungeons?" "What will be the ultimate goal of this dungeon?" and "What level of difficulty will this dungeon be?". Among others. A Dungeoneer will be given access to spawners and spawn eggs for their dungeon. These items will be bound to the player until he puts them down, and won't be able to be picked up by anyone else either. The mobs that spawn from these will also not drop any loot, but they will give experience to MCMMO stats. If the player abuses the items for their own personal gain (beyond setting the dungeon up to collect the items of dead players) such as selling the spawners or making grinders from them somehow, the player will be banned and dropped from the Dungeoneer program indefinitely.

________________________________________________________________________________________________________

And finally, my last suggestion.

**Random mob events.**

I cannot tell you how many times I've been so incredibly bored of walking across Russia with nothing happening. Random events already occur in game with the pillager scouting parties and the wandering traders, but these are unheard of on EMC. I'd love to go up into the arctic some time and suddenly be attacked by a pack of wolves or a pair of polar bears. Or be exploring the ruins of a city, and suddenly I hear a mighty roar of an Ender Dragon that's made the place its home. Well, the dragon one might need to be set up specifically by staff, but what I'm trying to get to is...

Not everyone's great at PvP, and players are unpredictable and greedy. At least with mobs, you might get some of your items back after you get destroyed by them. Plus, you can get mob loot from them if you DO end up defeating them. I'd suggest one of these:
https://www.spigotmc.org/resources/%E2%9A%94elitemobs%E2%9A%94.40090/
https://dev.bukkit.org/projects/randomencounters
________________________________________________________________________________________________________

That's the end of my ramblings and pipe dreams. I hope it's not been too bad of a read, and I hope at least some of these features come to EMC. I've been playing since the days of Classic, and I'm sad to see the server in the state it's in right now. No doubt, the current state of our real world may have something to do with it, but regardless, I wish to see my favorite Minecraft server ever, return to some semblance of its former glory. I believe we're currently experiencing a dark age, but perhaps a renaissance is just around the corner. I realize all this is a lot to ask, and would be a tremendous task on the part of the staff of the server, but if you love this server too, I believe you'll try for it. Yours truly, always and forever, _o_Toast_o_ .

P.S.
       I really like The End, if there's anyway something can make it in from there too, that'd be super.

**Comment by jkmartindale** [comment]
> It also eats up a ton of the server's data. By deleting the nether's files from the server, along with the nether itself not supplying access anymore, we can free up some space.

Granted, the staff haven't made it very clear what are the biggest bottlenecks reducing server performance (other than 1.15 being crap), but I don't think space used by the Nether is a huge part of it. It's got little block variety and not too many structures so I'll bet it's still very compressible. From Karl's replies to various issues in this tracker, it seems like the bigger source of server lag is loading/unloading chunks from server memory when players move around. This matches up with the incredibly aggressive view limit the server enforces.

Since there aren't too many players in the Nether at the same time, I don't think it's responsible for that much of a performance hit. If that's the case, removing the Nether won't have much benefit if at all. Having portals spawn random items/mobs might even be worse because of the entity count increase (though if it does make sense performance-wise I think that's a decent compromise on no Nether).

Obviously this is just me guessing and for all I know Karl is going to come here and destroy me with facts and logic.

**Comment by SundraLOL** [comment]
Nether should have nothing to do with this. Nor' the overworld. It's all bout the dynmap updates and map size. If you want the nether then wouldn't that cause more lag? You seem to be heated about random mobs and no end for an egg or something. The literal only way for less lag is to legit get better server hardware. The "Quartz Craft" is so useless and would kill quartz economy. If this post is just about the lag then give fix or whatever money or ram.

**Comment by SundraLOL** [comment]
The nether is the least visited place on EMC and would make no sense. 2b2t doesnt have this issue and it's way worse than EMC. This could be due because of the 1.12.2 and 1.15.2 differences.

**Comment by DeadGlamour** [comment]
Tbh, none of this would happen, but, I do think EMC could use a 2nd server or so, like beta but shares inventories with emc, this would both increase player count and could be a nice way to add resources unobtainable, cough mending cough.

**Comment by BunbunToast** [comment]
> > It also eats up a ton of the server's data. By deleting the nether's files from the server, along with the nether itself not supplying access anymore, we can free up some space.
> 
> Granted, the staff haven't made it very clear what are the biggest bottlenecks reducing server performance (other than 1.15 being crap), but I don't think space used by the Nether is a huge part of it. It's got little block variety and not too many structures so I'll bet it's still very compressible. From Karl's replies to various issues in this tracker, it seems like the bigger source of server lag is loading/unloading chunks from server memory when players move around. This matches up with the incredibly aggressive view limit the server enforces.
> 
> Since there aren't too many players in the Nether at the same time, I don't think it's responsible for that much of a performance hit. If that's the case, removing the Nether won't have much benefit if at all. Having portals spawn random items/mobs might even be worse because of the entity count increase (though if it does make sense performance-wise I think that's a decent compromise on no Nether).
> 
> Obviously this is just me guessing and for all I know Karl is going to come here and destroy me with facts and logic.

Thank you for your inciteful feedback. I was writing this while slightly tired, nonetheless I admit I was mistaken about a few things.

**Comment by BunbunToast** [comment]
> Nether should have nothing to do with this. Nor' the overworld. It's all bout the dynmap updates and map size. If you want the nether then wouldn't that cause more lag? You seem to be heated about random mobs and no end for an egg or something. The literal only way for less lag is to legit get better server hardware. The "Quartz Craft" is so useless and would kill quartz economy. If this post is just about the lag then give fix or whatever money or ram.

I'm sorry you feel this way. The craftable nether supplies idea was only for **if** the nether was removed, as a way to continue the use of nether quartz. Of course, I also in no way meant to say "oh, this should be exactly like this!", but merely showing a concept with the code provided below.
Nothing here is concrete and is subject to change, and frankly parts of this should be changed. The point of the post is to start a conversation and I thank you for taking part in it, even if you were a bit rude.

**Comment by BunbunToast** [comment]
> The nether is the least visited place on EMC and would make no sense. 2b2t doesnt have this issue and it's way worse than EMC. This could be due because of the 1.12.2 and 1.15.2 differences.

Which is why I feel its just taking up space. No one who plays EMC really interacts with the nether at all. And most every structure there has been raided. You have to travel far far out of your way just for a chance at finding a spawner and even then you probably didn't bring your best stuff, so you have to go all the way back to your base, grab your silk touch pickaxe, then all the way back to the fortress. This can take hours of excruciating work and tedious- boring searching. By deleting the nether, you'd end the fruitless hunts and make all spawners worth far more. It's like when Fix artificially inflated the price of mending books because he didn't like how cheap they were becoming. Or... Whatever the reason was behind the villagers' lobotomy.

**Comment by BunbunToast** [comment]
> Nether should have nothing to do with this. Nor' the overworld. It's all bout the dynmap updates and map size. If you want the nether then wouldn't that cause more lag? You seem to be heated about random mobs and no end for an egg or something. The literal only way for less lag is to legit get better server hardware. The "Quartz Craft" is so useless and would kill quartz economy. If this post is just about the lag then give fix or whatever money or ram.

Also, I'm sorry if I came across as heated. I'm simply passionate about this server and want what's best for it. And what I believe is best for a server is that it's fun.
About "no end for an egg", I'm not sure what you mean about that. No end deminsion? No mob eggs? Gotta be specific with me, I'm not too good at translating.

**Comment by SundraLOL** [comment]
> > Nether should have nothing to do with this. Nor' the overworld. It's all bout the dynmap updates and map size. If you want the nether then wouldn't that cause more lag? You seem to be heated about random mobs and no end for an egg or something. The literal only way for less lag is to legit get better server hardware. The "Quartz Craft" is so useless and would kill quartz economy. If this post is just about the lag then give fix or whatever money or ram.
> 
> I'm sorry you feel this way. The craftable nether supplies idea was only for **if** the nether was removed, as a way to continue the use of nether quartz. Of course, I also in no way meant to say "oh, this should be exactly like this!", but merely showing a concept with the code provided below.
> Nothing here is concrete and is subject to change, and frankly parts of this should be changed. The point of the post is to start a conversation and I thank you for taking part in it, even if you were a bit rude.

I meant like no end and that you want to get some cool items which I understand but honestly that would make things more laggier with those elytras. I do see that you're passionate about the server and using "heated" was a bad word choice. The quarts thing wouldn't be bad but it's just because of the economy aspect of it. With players monopolizing it. With the nether part it just seems like a bad and useless idea to get rid of it. It shouldn't cause any lag cause: One, the players like said hardly interact with the nether. Two, dynmap/dynmap towny do not render the map if command "/dmap" is used with the specific type of world. This is why you cant the see the cave or side view of the map. The main cause of this lag is really the dynmap. It has a couple of image formats and image resolutions. Ex: vlowres, lowres, medres, hi-res. EMC seems to be using lowres from the image provided. Dynmap can struggle with these things and cause lag. If Fix would lower the dynmap updating it would cause less leg since it constantly has to update for every 120 players.

**Comment by DeadGlamour** [comment]
If you want an end just make it the moon smh

**Comment by shirazmatas** [comment]
I agree with the idea of UGD using the planned dungeons plugin. UGDs can even be built on a different (physical) server so that it won't ruin the performance. @FixTheAdmin

**Comment by BunbunToast** [comment]
> 
> 
> I agree with the idea of UGD using the planned dungeons plugin. UGDs can even be built on a different (physical) server so that it won't ruin the performance. @FixTheAdmin
> 
> additionally I think random mobs could drop dungeon keys so people cant grind dungeons

Thank you for the dialogue, sir. I think that dungeon key idea is a pretty good one. Probably could be done by using an item with a function command attached to it which would teleport you to it's corresponding dungeon.
A woodland mansion dungeon for random illager raid groups, a skeleton themed dungeon for skellies, slime themes, etc! It could all be really interesting to work with, and I'd like to be involved with it if the opportunity arose.

**Comment by KarlOfDuty** [comment]
We are not removing the nether, we aren't running out of storage space, not really sure where you got that from. For the other ideas I suggest you split them into different issues so they can be discussed individually. We are not planning on implementing them at this time though.
