### ISSUE TITLE
Ban appeal 

### ISSUE THREAD

**Issue by EloWool** [EarthMC/Issue-Tracker#1228]
Why have I been permuted for more than 15 caps? I didn't know this rule existed or if it is even real

**Comment by RoseBrugs** [comment]
Appeal your mute here, your muting mod likely didn't mean for it to be permanent. 
https://discord.gg/TSTYMe4

**Comment by coblobster2** [comment]
Since when are caps even illegal?

**Comment by shirazmatas** [comment]
Appeals should be made on the support discord

**Comment by EloWool** [comment]
I did but they did not respond
