### ISSUE TITLE
/t spawn

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#123]
This is a weird suggestion, but maybe give nation leaders acces to /t spawn to every town in your nation. This might be a good feature, because as nation leader you need to help your citizens all the time and having to walk is pain IMO and I'm not even an owner of a nation.

**Comment by BowShot118** [comment]
Railways

**Comment by KarlOfDuty** [comment]
Hm, it may actually be, we will have a look next time we update.

**Comment by KarlOfDuty** [comment]
We have decided not to implement this change.
