### ISSUE TITLE
Halloween Event

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1230]
### Is your feature request related to a problem? Please describe.
Yes. Boredom. 

### Describe the solution you'd like
Server's not got too many events. Let's just have it be night time all October or something. Or bump up the difficulty to Hard mode to make it a little scarier. Idk. Something fun. Maybe a haunted house where you can get a special pumpkin that gives you a potion effect when you put it on?

**Comment by DeadGlamour** [comment]
https://discord.gg/f39szMb
cough

**Comment by shirazmatas** [comment]
I agree with OP, more events would be fun.
