### ISSUE TITLE
[Mechanic] Hide player's username in anti-combat log message when player is invisible

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1232]
### Is your feature request related to a problem? Please describe.
Whenever I am fighting someone and am using invisibility potions it is annoying to be hidden in every way possible (dynmap, username, skin etc.) and have my identity revealed because they hit me one time.
### Describe the solution you'd like
I think instead of saying "You were attacked by Username. You will die if you disconnect during combat!" it should say something along the lines of "You have been attacked. You will die if you disconnect during combat!" if the user is invisible.

### Additional context
I think the username showing in the earthmc-towny discord channel upon death would be fine, this would allow people to find who is attacking them if they win the battle and aid players attacking who don't want their identity revealed such as bounty hunters.

**Comment by AndrewCheedle** [comment]
@Fruitloopins do it now

**Comment by CorruptedGreed** [comment]
Can be done with a new combat log plugin
