### ISSUE TITLE
(Mechanic) Hunger going down in towns

### ISSUE THREAD

**Issue by Oln123** [EarthMC/Issue-Tracker#1233]
Problem
Basically I think food should be more important in emc.

Solution
Make it so your Hunger goes down when you are in a town

Additional context
Idk how possible this is but i feel like it would make emc slightly harder and would make food usefull

**Comment by DeadGlamour** [comment]
It wouldn't make EMC harder, just more annoying, I dont see an actual reason for it.

**Comment by shirazmatas** [comment]
Lack of support for this feature
