### ISSUE TITLE
Speaking in earthmc-towny disabled since MARCH.

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1234]
The emc towny chat channel in the discord has been disabled for regular people other than mods to speak in since MARCH 31ST. Thats 6 months it has been disabled and this month it will be 7. This is ridiculous as the double message issue was solved in May. If there's some other horrible glitch that is caused when someone talks in it then why do mods speak in it? Please let me know. If not, I want everybody with the Player role to be given access to speak in that channel again. It's ridiculous that it has been disabled this long.

**Comment by FutureLemon** [comment]
Staff don't want to re enable it because they use it as a flex

**Comment by Basically-Andrew** [comment]
I believe the issue is moderation of the channel msgs, not because mods want to flex.

**Comment by shirazmatas** [comment]
Please follow format andrepost
