### ISSUE TITLE
[FEATURE] Refine dirt into clay and gravel into sand.

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1235]
### Is your feature request related to a problem? Please describe.
The issue is a distinct lack of clay's availability on the server, and the depreciating natural beauty of the world's deserts. I know most of you want to keep the deserts and stuff pretty and not... well... I mean, just fucking look at them dude.

### Describe the solution you'd like
I know sand and clay have certain values to the economy, but honestly it's not anything so substantial that adding a recipe for them would be economic suicide. The following crafting recipes would be added: 
![image](https://user-images.githubusercontent.com/46580909/94846989-040e1c00-03f0-11eb-9db7-035c0e4443c7.png)
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "###",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:gravel"
        }
    },
    "result": {
        "item": "minecraft:sand",
        "count": 9
    }
}

![image](https://user-images.githubusercontent.com/46580909/94847185-3f104f80-03f0-11eb-80b6-d375d33e31a4.png)
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "#B#",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:gravel"
        },
        "B": {
            "item": "minecraft:brick"
        }
    },
    "result": {
        "item": "minecraft:red_sand",
        "count": 8
    }
}

![image](https://user-images.githubusercontent.com/46580909/94847427-931b3400-03f0-11eb-97fb-8b42c2f100cd.png)
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "#W#",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:dirt"
        },
        "W": {
            "item": "minecraft:water_bucket"
        }
    },
    "result": {
        "item": "minecraft:clay",
        "count": 4
    }
}

### Additional context
I think these will serve well and won't be too overpowered. There is a large abundance of dirt and gravel in the server in the form of those large pockets of the stuff underground, so it should be common enough for smart players to take advantage of and continue a stable economic profit while also keeping the world less torn-up.

**Comment by BunbunToast** [comment]
Didn't know I didn't need to include the .json code, just thought it would be helpful lol sorry

**Comment by DeadGlamour** [comment]
lower clay crafting result and sure, seems useful

**Comment by BunbunToast** [comment]
> 
> 
> lower clay crafting result and sure, seems useful

Well yeah, but I figured realistically about 50% of the dirt would be clay. Maybe it should just give you 25%, so that would be 1/4th of 8 and that equals to 2 clay blocks per 8 dirt. How's that?

**Comment by LeninUnion** [comment]
A good idea 10 / 10 would recommend again for multiple reasons, this is a good solution to the sand mining problem in the deserts on the server.

**Comment by ZukiLTU** [comment]
Why not, good idea

**Comment by BunbunToast** [comment]
> 
> 
> Why not, good idea

thank you

**Comment by Basically-Andrew** [comment]
You have a great concept, but I'm not sure these are great ways to handle these issues. Converting 9 gravel to 9 sand will disrupt economies in large sand nations. Converting 8 gravel and 1 brick to 8 red sand will disrupt the Australian sand market. Converting 8 dirt and 1 water bucket to 4 clay will disrupt the American clay market. In the real world, nations have economical advantages over others by geography. These advantages other nations have over each other strengthen the economy. These recipes would weaken our already weak economy.
