### ISSUE TITLE
Shitpost, pls delete

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1236]
![image](https://user-images.githubusercontent.com/46580909/94851994-396a3800-03f7-11eb-8cfe-442c89287e29.png)
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "TBT",
        "SDS"
    ],
    "key": {
        "#": {
            "item": "minecraft:end_crystal"
        },
        "T": {
            "item": "minecraft:trident"
        },
        "B": {
            "item": "minecraft:beacon"
        },
        "S": {
            "item": "minecraft:spawner"
        },
        "D": {
            "item": "minecraft:totem_of_undying"
        }
    },
    "result": {
        "item": "minecraft:end_portal_frame",
        "count": 1
    }
}

**Comment by unbatedaura409** [comment]
Stupid post

**Comment by BunbunToast** [comment]
> 
> 
> Stupid post

y tho

**Comment by unbatedaura409** [comment]
even if you did have the portal blocks the end dimension is disabled in the server config. not to mention what happens if you place a portal block wrong or you put the eye of ender in wrong? purely stupid post

**Comment by jkmartindale** [comment]
Also you don't have to post JSON for the recipes you've been suggesting, we can tell what you mean by the screenshot.

EarthMC doesn't even use JSON recipe configuration, they have a custom plugin: [EarthMC/EMCRecipies](https://github.com/EarthMC/EMCRecipies/blob/master/src/main/java/com/karlofduty/EMCRecipies/EMCRecipies.java)

**Comment by BunbunToast** [comment]
yeah but like shut up lol

**Comment by DeadGlamour** [comment]
Lmao, besides the fact the end is disabled, lets say it was added, now what? They said they wont add shulkers because duping, so the only thing you could get there are elytras (which will prob be disabled because lag), and chorus.
Also, no1 would even get that much items, only like a 5 nations top will get it, and all of this effort, for chorus and a soon to be disabled item.

**Comment by BunbunToast** [comment]
> 
> 
> Lmao, besides the fact the end is disabled, lets say it was added, now what? They said they wont add shulkers because duping, so the only thing you could get there are elytras (which will prob be disabled because lag), and chorus.
> Also, no1 would even get that much items, only like a 5 nations top will get it, and all of this effort, for chorus and a soon to be disabled item.

Yeah but like think about all the space themed builds. Oh hold up that actually gives me an idea-
