### ISSUE TITLE
[BUG] Queue spawn is off

### ISSUE THREAD

**Issue by TheSuperGamer20578** [EarthMC/Issue-Tracker#1238]
### Server

queue

### Describe the bug

I know this is a very minor bug but still, THE QUEUE SPAWN IS OFF BY -2 DEGREES

And now that I've noticed it, it's going to annoy me every time I'm in queue

### To Reproduce

1. Teleport to the queue spawn
2. Press F3
3. Look under the facing part and it will say -2 degrees

Or a less technical way

1. Teleport to queue spawn
2. Walk forward **without touching mouse**

### Expected behaviour

You should be facing straight forward

### Screenshots

![image](https://user-images.githubusercontent.com/30369708/95152862-c3d8e000-07d9-11eb-8845-3106b90c26b5.png)

**Comment by bwilso1** [comment]
1.) "The Grease" https://youtu.be/1T1B-l9RPaQ?t=105
2.) can confirm you do not spawn facing x=0, y=0, you spawn looking -2.0 degrees X and 3.0 degrees Y.  

Vote to buglist, fix when minecraft 1.20 comes out.

== workaround ==
use your mouse.

**Comment by TheSuperGamer20578** [comment]
> == workaround ==
> use your mouse.

this workaround is impractical as you have to still press f3 and get it very precise it would be far better if an admin could change the spawn to be correct

and also if a new player were to press f3 or walk straight forward without using mouse they would notice and it would make the server look bad

> can confirm you do not spawn facing x=0, y=0, you spawn looking -2.0 degrees X and 3.0 degrees Y.

yes

**Comment by Colt44Magnum** [comment]
Staff do not add my fishing idea yet, I repeat do not add my fishing idea yet. This bug is of upmost importance.

**Comment by KarlOfDuty** [comment]
We decided this was too hard to fix in the existing hub so we had to make an entirely new server for it but I am happy to announce it has finally been fixed.
