### ISSUE TITLE
[Plugin], [Mechanic] Auto-Crafting Tables

### ISSUE THREAD

**Issue by Johnsonk2** [EarthMC/Issue-Tracker#124]
**Describe the solution you'd like**
-For this to be added ;)

**Additional context**
I think auto crafting tables will bring a modded like feel into EMC, as vanilla lacks in what you can do. This gives people the chance to mass produce, a great tool for stores.
MAIN plugin suggestion 1.13 - https://www.spigotmc.org/resources/autocrafters.36406/

**Comment by Coffeetom** [comment]
Yeah I love this plugin and it makes it a lot easier

**Comment by KarlOfDuty** [comment]
We also feel like it would bring a modded feel to EMC, but we want the server to have a distinctly vanilla feel to it. This is why we have also not added other forge-like mods to EMC. The other issue being that mods like these which interact changes how mechanics in the world work can easily cause permanent harm to the server if something goes wrong with them not to mention the performance issues associated with them.
