### ISSUE TITLE
[Mechanic]Please fix carpet dupers

### ISSUE THREAD

**Issue by bringbackmapart** [EarthMC/Issue-Tracker#1240]
### Is your feature request related to a problem? Please describe.

Please fix carpet dupers, the mapart community on this server is unlike any other and between the constant map rollbacks and now with the breaking of carpet dupers, you guys have really fucked the mapart community. Pls revert whatever change yall did and bring it back T.T

**Comment by DeadGlamour** [comment]
Based, map art community is 1 of the best, dont ruin it

**Comment by shirazmatas** [comment]
For clarification you want carpet duping to work again?

**Comment by FutureLemon** [comment]
What about all the lag they bring along with them?

**Comment by bringbackmapart** [comment]
> For clarification you want carpet duping to work again?

Yes.

**Comment by bringbackmapart** [comment]
> What about all the lag they bring along with them?

Carpet dupers, (if at all) play a very small role in server lag. The server deletes entities if they start crowding an area. They have messed with render distance which has greatly reduced the lag issues(why we arent seeing as much now)

**Comment by bringbackmapart** [comment]
The Mapart Community on EarthMC is seriously Top 2 (arguably tied with 2B2T but their lack of map-locking makes maps impossible to keep on their server). EarthMC is the perfect platform for Mapart, the community is already established, and thousands of maps have already been made (Map ID's are in the 80,000's atm).  You can see just by looking at the bottom right corner of the Dynmap, people use it as expression, some of us it's all we log in to do nowadays after we have completed everything else there is to do. From EMC-Businesses to Music Album Mapart to just general meme making, mapart fr plays a huge role in the emc playerbase and killing it off would be a horrible horrible idea. Most of the makers of maps have already voiced our frustration at the constant rollbacks of Map ID's causing maps to wipe, limiting how many pieces we can make a week down to 1. With lag for now being "fixed" but leaving our carpet machines broken.

"But this just creates the supply/demand for wool" - nobody wants to pay 100g+ to make a piece. Be realistic, maps will continue to not be made until carpet duping is fixed. Breaking it now serves no purpose but to kill off the community.

**Comment by Fruitloopins** [comment]
I haven't made maps in quite a while but it really is a massive part of the EMC community now and if possible carpet duping should be brought back as it is much more difficult and discouraging to use non-carpet materials for maps.

**Comment by jkmartindale** [comment]
If carpet duping machines are somehow a lag concern, we could have the benefits of carpet duping without the lag by adding a custom crafting recipe that returns multiple carpet for a single carpet.
