### ISSUE TITLE
[Feature] Move info to a more noticeable area

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1241]
### Is your feature request related to a problem? Please describe.

Problem is that I have been on the server since April and did not know about this little box hidden away behind a waterfall that has information on the server. I am glad that I didn't happen upon this server without knowing people from the community before hand. 
### Describe the solution you'd like

I would like this info to be placed in a more easily and noticeable spot, maybe a small hut that drops down just like how the current information area is set up but have it above ground and not behind a waterfall

**Comment by KarlOfDuty** [comment]
Done.
