### ISSUE TITLE
Reintroduce villagers with modified trades (plugin link too)

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#1242]
### Is your feature request related to a problem? Please describe.
Right now villagers, 1 of the most core parts of minecraft and the economy are disabled, I understand why since mending shouldn't cost 1g, but theyre still an important part of minecraft, and this plugin I have here should hopefully solve it without destroying the economy and letting the admins modify the economy if needs be.

### Describe the solution you'd like
https://www.spigotmc.org/resources/custom-villager-modifications.78329/
This plugin lets admins modify trades, setting minimums and changing emeralds as the traded item to lets say gold or other items and even outright canceling the trade entirely.
I think this plugin should at least be tested in beta and hopefully eventually used in the main server.

**Comment by Twitchyyy** [comment]
This would be a great solution! 

Right now some players have basically wasted dozens of playtime hours buying villagers, transporting them, and breeding villagers with the low server tick speed only for them to be yeeted _without notice, warning, or plan of action to fix them._ Removing them is one thing, but doing so literally at random really fucked over the players.

This not only affects mending prices (which have rose to 20-25g each and continue to climb in price), but also bows, crossbows, saddles, chainmail, potion arrows, bells, etc and has destroyed the value of emeralds on the server which used to be at a stable conversion rate. 

Removing villager trades doesn't make things even or fair, it only gives players that stockpiled these items when villagers worked a huge advantage over other players, **especially the new ones**

If not fixing villagers (a core element to vanilla minecraft), then ffs please introduce some custom crafting recipes for these items which would be a very easy fix and has been done before to get endstone and prismarine items. 
Mending could be added to enchant tables with custom enchants to enchant, saddles could be crafted with leather and an iron ingot, chainmail could be craftable with iron ingots; just something to repair the now **devastated** villager-based item economy.

**Comment by KarlOfDuty** [comment]
As villagers lower server performance I think we will keep things the way they are at least for now.
