### ISSUE TITLE
[BUG] Chat filter is biased to languages using the latin alphabet

### ISSUE THREAD

**Issue by TheSuperGamer20578** [EarthMC/Issue-Tracker#1243]
### Server

towny

### Describe the bug

the chat filter thingy sees most if not all non-latin characters as the same so for example, if I said `こんいちわ` and then say `はい` it won't let me send the 2nd message and it will say `Please do not repeat the same (or similar) message`

### To Reproduce

I pretty much described this in the previous section

### Expected behavior

It sends both messages

### Screenshots

![image](https://user-images.githubusercontent.com/30369708/95549577-46b89f80-0a53-11eb-9457-4c3fb0a5e2a5.png)

### Additional context

when Chinese chat is active often people add numbers to the end of their messages I believe that this is to bypass the filter as it is very lenient when it comes to numbers

**Comment by shirazmatas** [comment]
@KarlOfDuty racist fix this

**Comment by Warriorrrr** [comment]
Fixed
