### ISSUE TITLE
Remove the hollow claim rule.

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1245]
I believe that the hollow claiming rule should be removed for 2 reasons.

Reason number one: The hollow claiming rule is easily bypass able by making your claim arm and then leaving a singular chunk unclaimed so it isn't hollow claimed on the map therefor making the rule utterly pointless and allowing hundreds of towns bypassing this rule.

Reason number two: When towns make claim agreements they usually like to make a claim arm around the area which they will claim up, them not being able to will cause towns to be made inside the area because everyone can see the whole area is wilderness and then will cause a situation like France or Ireland.

**Comment by 10op10** [comment]
Here is an example. 
![image](https://user-images.githubusercontent.com/63156735/96915737-8abd9280-149e-11eb-8e56-f467539bed82.png)

**Comment by Pengun78** [comment]
Spain gang let ya nuts hang

**Comment by coblobster2** [comment]
I agree with part 2 but part 1 will probably be illegal soon with the ipdated claiming rule

**Comment by FutureLemon** [comment]
Go to the other page Earthmc.net this is only for the server not website/rules related x)

**Comment by shirazmatas** [comment]
please follow format AND post in the right github https://github.com/EarthMC/EarthMC.net/issues
