### ISSUE TITLE
Entity Purge Plugin

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#1247]
EMC needs an entity clear plugin. It's very obvious. I know admins may not understand as they can't play the server like the normal player, and I understand that, but if anybody has ever rode on a boat through the ocean or even just walked through wilderness long enough you'll know what I'm talking about. The amount of entities on EMC is insane, and a mob chunk limit simply isn't enough. We need a full entity purge plugin, one that happens every 30-45 minutes or so. You'd be surprised how much it helps. It would remove dropped items, regardless of value or usefulness. This would not remove mobs, or maybe it could remove mobs not within towns. It would help with the lag, and anybody who knows about this kind of thing can vouch.

**Comment by BunbunToast** [comment]
Personally I think people just need to fuck off with their billion-spawner grinders.

**Comment by FutureLemon** [comment]
> Personally I think people just need to fuck off with their billion-spawner grinders.

There's a mob limit per chunk so you can have as many spawners as you want, there will never be more than 20 mobs in one chunk

**Comment by nl1213** [comment]
Yea we do need this. One thing id like to mention is a mob cap won't help. Mobs are a huge source of lag but without near as many mobs, to begin with, I don't think any mob farms are causing lag on this scale. Entities however have their own cap. If we could have clear lag then we might be able to deal with things like this. Entities don't seem to despawn in unloaded chunk either. I mainly mine a ton of gravel for gunpowder on the server and when I go back to the pits the multiple stacks of gravel are still there. I honestly don't see a reason why this couldn't have been done sooner.

**Comment by Zardinio** [comment]
I love traveling the oceans and finding cobble and stone floating on top of the water.  One time I found 5 gold, another time I found a god sword. Probably would help the server if we did have a regular entity clear.

**Comment by shirazmatas** [comment]
Please follow format
