### ISSUE TITLE
[BUG]Maps are broken.

### ISSUE THREAD

**Issue by bringbackmapart** [EarthMC/Issue-Tracker#1249]
### Server

Towny main

### Describe the bug

With the constant server crashes and rollbacks, EarthMC maps are now unreliable & broken.
What I mean by this is that every single time the server crashes, or restarts, map ID's created within any timeframe prior to the crash, are reset & maps display a blank square. This causes issues with a couple of different groups of people.

1) The biggest victim to this is Mapart creators. Mapart has come to a standstill due to the fact that we simply cannot keep maps for longer than 2 days without having it wiped, (48 hours falls into the timeframe of MAP ID wipes due to reset). After every restart or crash, mapartists are forced to re-render their maps which includes (including locking, re-creating deleted sections for copyright issues,

2) Town Mayors looking to map out their town.  ; I have had multiple people complain that maps are consistently getting wiped as they are attempting to make a map of their town to display at their t spawn.

3) EMC Business owners- they are unable to hire Mapart makers to make recognizable art for their business (real estate, big business, local business)

### To Reproduce

1. Make a map, lock the map, display the map.
2. Wait 72 Hours
3.  Look at said map, its probably wiped (I have been doing this repeatedly for 2 weeks).

### Additional context

This stuff sucks guys, please implement some sort of system to either save server map ID's once a night, even if it means having a nightly restart, that could potential help some of the lag issues im sure as well. I know some staff has said they are looking into it on server, but this seriously has to get fixed. The mapart community on EMC is top notch, most of the mapartists have quit making mapart entirely. This has been going on for 3+ months, enough is enough. 

OVER 3 MONTHS THIS HAS BEEN GOING ON! https://github.com/EarthMC/Issue-Tracker/issues/1163

**Comment by 3232o** [comment]
Please consider this, map art is a dying artform on EMC because of this very specific issue.

**Comment by Carabow** [comment]
I encounter the issue yesterday evening (2020/11/17 before middnight, UTC+1), some of my maps juste vanished.
What it looks like on the item frame: https://cdn.discordapp.com/attachments/775798569147826219/778045097337946122/unknown.png
What it looks like in my hand: https://cdn.discordapp.com/attachments/775798569147826219/778045346244329483/unknown.png

All my copies of these maps are affected.

**Comment by KarlOfDuty** [comment]
We have switched to a different server software now so hopefully this has solved the issue.
