### ISSUE TITLE
[BUG] Cow  disappear 

### ISSUE THREAD

**Issue by FeaterWolfy** [EarthMC/Issue-Tracker#1250]
### To Reproduce

1. 
2. 
3. 

### Additional context

Iw as buying 2 cow ; and i start travel on the map with them and, suddendly, one of them disappear with the leash, if you don't belive me i can screen that i don't have kill a cow in my life in this serv and the one who sell me can confirm that he sell me 2 cow and lend me 2 leash, he was with a friend of him .
So can i have back my cow please ?

**Comment by FeaterWolfy** [comment]
Same bug now with my second cow ! 

Reproduce : Travel with a leash and a cow, 
                    Make it moove it with you 
                    She disappear
Expected behavior : Aving my 2 cow and my 2 leash back , becaseu i pay it and i lost a long time for nothing

This time a friend of mine see the cow disappear (i'm not crazy x) )

**Comment by jkmartindale** [comment]
Mob despawning is unfortunately just something you have to get used to on EarthMC, with the massive amount of lag hitting the server. This has been going on for quite some time (see #781, #833, #889, #1043, #1067, #1090, #1110, #1181, #1204, #1216, etc.).

You need to talk with moderators in the [support Discord server](https://discord.gg/TFVYpWQ) to get someone to respawn your cows. Problem is the ticket bot over there has issues right now, so you can't file tickets at the moment xd

**Comment by shirazmatas** [comment]
Duplicate issue, open a ticket on the discord for mob refund
