### ISSUE TITLE
Missing stacks of golf

### ISSUE THREAD

**Issue by Hungrey** [EarthMC/Issue-Tracker#1251]
Yesterday Xingu and Brazil had a huge merge and I took out a lot of gold to help fund a one chunk nation for the old Brazilian people to tp too. I took out all of it now knowing how much I would need and then i paid and kept the extra in my inventory. When I get on today all of my gold is missing. I was told today by my friend that when the server gets rolled back the gold disappeared which makes no sense. Idk what happend but i need my fucking gold back. I don't know exactly how much I had not like it was my job to keep track of it when your server makes it disappears.

**Comment by jkmartindale** [comment]
You'd need to talk with moderators in the [support Discord server](https://discord.gg/TFVYpWQ) to get a refund. Problem is right now the ticket bot over there is broken, so you can't file tickets at the moment xd
