### ISSUE TITLE
[World][BUG][Mechanic][Feature][Plugin] How to Make our Server the best it can be Road Map for 2021.

### ISSUE THREAD

**Issue by DarkOakMetarex** [EarthMC/Issue-Tracker#1252]
EarthMc is by all accounts a good server, hell maybe even a great server a great game and I don't think we give Fix enough credit for the work he has done and his team of admins hence why we are in the turmoil Era of the server. However Much I believe that EarthMC is a great game and server to play on I know that it doesn't come without glaring issues and possible set backs. The server is the way it is for a reason but there are some things that can be tackled to get it to be even more highly regarded than it already is being featured as the #1 Earth Server. Here are the many things I believe will be beneficial for the server as a whole and can get us to a new point in EarthMC.

#1: Lag, as a growing concern not going unnoticed isn't a surprise this would be number one but how exactly does one go about fixing such a slightly complicated problem? Well to think for starters we should think of obvious things that trigger lag, Anti X-Ray, Mobs, Chests opening/Closing, Players. All these things cause lag but I feel that Anti X Ray is the largest contributor as when we mine it is the most apparent to cause lag while playing. But wait a second what if it's just lag glitching out the X-Ray and not actually the Anti X-Ray well to look at this in a keen perspective I haven't encountered any other time lag accrues other than when I Mine while there is Anti X-Ray & when opening and shutting chests and going to my mob spots, that said I believe a Better Alternative should be found for Anti X-Ray and maybe the answer is more simpler and can be worked around by using Smaller Load Distance and Render Fog as well as Invisible Ores or another plugin altogether.

#2: Economy, Villagers, as number two it begins as a cross road between what the owner of the server Fix has set in place and what the Players of the server feel is right. Obvious in it's Evaluation it's only up to fix but that doesn't mean there isn't a possibility for a outlying problem and to find a problem where do we search? Players, the player base can give really useful feed back to help make the server better so why does it seem like voices are disregarded and what would really make the game economy better? Well to answer this we need to know two things what is missing and what is currently going wrong or unchecked. From a players perspective the only current thing is heads but this is being currently re accessed as heads have an economy all of their own. Perhaps the problem lies with the currency is question and the lack of resources that can be acquired, but wait nobody said that having less of an item is bad as it drives up price & demand for the product and sure we can see how one can make such an argument but it can also be argued that when too much inflation on particular items occurs it can be very negative to an economy in general practice. Here's an Example, Someone needs mending they haven't any really large sum of gold they are fairly average as a player and in order to go mining for gold they are gonna need mending or risk just having to spend more in the long run. Now when it comes down to it say this player has a town and 41 gold and just had to spend a lot of gold to get mending and then an extra for all the needed enchantment and for the haste, this quickly got very expensive while calculation cost. Now if we were to guess this kind of massive spending would likely Discourage anymore spending likely resulting in the player to want to hold on to as many gold as possible in order to not have to deal with such loss and the issue in question comes from now buying anything. When you learn in school about economics and that money needs to get passed around for a healthy economy to flourish this is the best case of a negative outcome resulting from inflation. Not to only mention the fact gold is rare and not many players get to have a chance to get more than a few gold a day which causes another problem with new players having to live off vote crates and also having to do an assortment of jobs yes you heard me jobs, how many times have I heard it now? I need a Job anyone hiring for work and all the other things of this nature. The Fact of the matter is the economy isn't so hot and needs to come back to a regular state of open sales and affordable prices.

After all the stuff covered I'm sure I could go on all day on the topics that would make our game better as I've already shown. but I believe we should sum of the particular things that will really help out our server in a really quick an reliable manner.

#1: Gold Crates Should have Mission task in order to get monetary things and it will get players more actively involved community wise and it just doesn't make sense for money to be given purely away just for voting.

#2: Bad Plugin Purge, Ends lag makes players happy which will make Fix happy guaranteed.         $$$

#3: Make sure to add some of the commands from the war plugin earlier like (Reclaim Town - As a resident, if your town falls into ruin, then after 24 hrs. have passed, any resident can reclaim it and become mayor, using '/t reclaim'.) Some of these commands are already useful enough to be added now and should be added first and foremost.

#4: Admins, mods need to be checked and screened, ok hold up hold the phone what is this crazy stuff you are saying I don't understand what you mean by that. Ok I'll be clear, are you a mod or an admin who still has interest in the server & are you in a position where you would actively use your power in a negative light or to progress faster in the game & server? This needs to be asked so we can get admins and mods who will take their job seriously and perform properly and also be interested to be on enough at certain times of the day and night and have mods and admins from all corners of the globe.

#5: Claiming Issue's need corrected, People claim blocking is currently being addressed but another issue player seem to be having is a lack of plots to build on. They have gold or maybe they don't but having populations being the main thing to determine size is a problem, I can understand that large populations in real world terms is needed to protect such large land but actually geography is the main driving factor and logistics so I believe at the very least population standards are a negative for claiming.

That's all for now I typed far too much and more than many would be willing to go. If you read this far your awesome and really care about the server as much as I do.

**Comment by BunbunToast** [comment]
Yeah this needs attention from @KarlOfDuty

**Comment by shirazmatas** [comment]
Please break into different issues each following the format and in the correct position or this will be closed

**Comment by KarlOfDuty** [comment]
Separate into different issues.
