### ISSUE TITLE
[Feature] Update the Map in Queue

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1253]
### Is your feature request related to a problem? Please describe.
Map is outdated and should be updated, or add an updated image of it so that you can see the progress that has happened on this server!

### Describe the solution you'd like
Updated Map

**Comment by Basically-Andrew** [comment]
The world is massive, so the map takes a while to update all zoom levels. Be patient and let the plugin update by its self! Admins can't force a server-wide update of the map.
