### ISSUE TITLE
Change rule 1.2

### ISSUE THREAD

**Issue by 13E666L13** [EarthMC/Issue-Tracker#1254]
I'm very frustrated when I hear about cases of people getting banned for doxing even when they didn't deserve to get banned. Like what happend with FutureLemon, he wanted someone to dox a pedo and got banned. 
My solution to this is a change in rule 1.2 that gives curtain cases a different approach.
Most mods and admins already know the details.

**Comment by shirazmatas** [comment]
post on the correct github https://github.com/EarthMC/EarthMC.net/issues
