### ISSUE TITLE
Im unnecessarily banned

### ISSUE THREAD

**Issue by NoEfso** [EarthMC/Issue-Tracker#1255]
Hello mods , admins and EarthMC's best Players . Im unnecessarily banned . Its a ban Appeal !

Banned on: 05-11-2020
Banned by: __Zuki__
Reason: Alt of NoEfso

NoEfso account is hacked and i make ban ticket for my hacked account . NoEfso account now banned . And i buy a new account but I have IP-Ban . @KarlOfDuty Im unnecessarily banned . Pls UnBan me . I want justice !

**Comment by DeadGlamour** [comment]
https://discord.gg/stCg8y548t

**Comment by NoEfso** [comment]
> https://discord.gg/stCg8y548t
Support mods not unban me !

**Comment by jkmartindale** [comment]
Well, posting in the bug tracker about a ban appeal won't help you at all so
