### ISSUE TITLE
[Feature][Plugin] Wandering Trader suggestion

### ISSUE THREAD

**Issue by Twitchyyy** [EarthMC/Issue-Tracker#1257]
### The server could really benefit from having a Wandering Trader.

**Would it be possible to have a Wandering Trader appeared at a random nation /n spawn every night?** 
It would also be cool if there was an announcement in chat as to which nation spawn it is currently spawning in, or perhaps a msg bot like Michele Obama. 

- It would benefit the Economy by giving players a _new way to get items_ that are currently unobtainable

- It gives players, especially new ones, more incentive to _explore the map_ and going to other nation spawns that they otherwise wouldn't have ever visited. 

- It would also benefit the community as it would essentially be a _nightly event_ bringing lots of players to the same area.

**It also would be easy to customize what the Wandering Trader's trades are with this pluggin:** https://github.com/jmanpenilla/WanderingTrades

This might be a good way to reintroduce items that used to come from the now disabled Villagers. Many unique and high demand items are now unobtainable due to that _(Mending, Frost Walker, Curse of Binding, Curse of Vanishing, Chainmail, Bells, Tipped arrows, Saddles, etc)_

If we could have a way to obtain these items from a Wandering Trader each night, it would be a great benefit to the economy. There would also still be scarcity even if high tier items appear, there's still a trading limit.

**Plus we could get llamas!**

**Comment by pesetz** [comment]
nope

**Comment by NS4530** [comment]
I think that’d be a cool idea, it’d make villager items cheaper for people who couldn’t afford them and give emeralds a use besides looking pretty.

**Comment by Zardinio** [comment]
What if you had the wandering villager appear in towns of a nation rather than the specific nation capital? Imagine a wandering trader in Nantes or Lixus. That'd be cool too.

**Comment by Cactusinapumpkin** [comment]
![Uploading 0DBC9E1F-B894-4E6C-814E-77F833F76AFD.png…]()

**Comment by shirazmatas** [comment]
Please follow format
