### ISSUE TITLE
a New Feature

### ISSUE THREAD

**Issue by gfhfdjdfgj** [EarthMC/Issue-Tracker#1258]
are you tired of unused stores that new players make then leave i im too
i say make it were you need you need to be a month old account to make stores
and if you abandon a plot with stores all the items go in your inventory and not stay there

**Comment by JaVolimKatarinu** [comment]
If you are a mayor, I think you can request from Staff that shops from other players be removed if they are inactive. Please open a ticket on [Discord Support server](https://discord.gg/EZBYmpp) to resolve the issue.
