### ISSUE TITLE
[Feature] Add a clearer message to guide new players to the map or info within the queue world.

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1259]
### Is your feature request related to a problem? Please describe.
When connecting to EMC there is a brief message that appears at the bottom of the screen saying to go to https://earthmc.net/map/, this is very unnoticeable due to the text color and the time it appears for.

### Describe the solution you'd like
A clearer message, possibly a wither boss name at the top of the screen directing a player to the website that stays for longer and can be toggled off if possible for players who don't want it in their way.

### Additional context
Further reasoning as to why this is a problem and context:
This is the brief message in question:
![2020-11-17_16 09 14](https://user-images.githubusercontent.com/49851457/99349712-c0fcff00-28f0-11eb-8075-ed472d390f97.png)
Here is a reddit post showing frustration at newbies not being aware of the map and asking in chat: https://www.reddit.com/r/EarthMC/comments/jrdlvt/where_is_the_map_though_boi_you_sat_thru_a_30_min/
I have told many, many players who would otherwise be clueless how to get to the map:
![Capture](https://user-images.githubusercontent.com/49851457/99350082-abd4a000-28f1-11eb-9217-1a45485cf52b.PNG)

**Comment by FutureLemon** [comment]
Weird flex 167 times...

**Comment by KarlOfDuty** [comment]
Done.
