### ISSUE TITLE
[Mechanic] Refund town plots when unclaimed

### ISSUE THREAD

**Issue by sharkfynn1012** [EarthMC/Issue-Tracker#126]
When town plots are unclaimed or a town taken down, would it be possible to implement something that refunds the gold put into it?

**Comment by sharkfynn1012** [comment]
It would be a change that I'm sure some people would appreciate, and would allow people to be more flexible
.

**Comment by KarlOfDuty** [comment]
Might be possible but that might give too much freedom for the mayor to just take everything a town owns one day and move away.

**Comment by sharkfynn1012** [comment]
It would still be a cool feature. I wonder if there is a plug in like it somewhere.

**Comment by KarlOfDuty** [comment]
Not possible.
