### ISSUE TITLE
add the option to not appear on the map

### ISSUE THREAD

**Issue by MuhannadYT** [EarthMC/Issue-Tracker#1260]
### Is your feature request related to a problem? Please describe.

People are sniping players with the map (using it as a radar)
### Describe the solution you'd like

Allow players to toggle the ability to be visible/invisible on the map

**Comment by JaVolimKatarinu** [comment]
Radars are allowed as long as they dont reveal more information than dynmap. You should be aware of going into wilderness. Little tip, open map while playing so you can see if somebody is near you.

**Comment by jkmartindale** [comment]
You're invisible on the map if you're sneaking, invisible, or under a block.
