### ISSUE TITLE
add the ability to buy from the server

### ISSUE THREAD

**Issue by MuhannadYT** [EarthMC/Issue-Tracker#1261]
### Is your feature request related to a problem? Please describe.

it is hard sometimes to find a player selling what you want, or they might be traping you to kill you when you come to buy the item,
### Describe the solution you'd like

being able to buy items from the server, for ex /shopgui then there you can buy blocks, etc from the server and you can sell items to the server to get gold

**Comment by JaVolimKatarinu** [comment]
Server economy is run by players. You can use #trading channel in EMC discord or other various discord shop selling servers.
