### ISSUE TITLE
Disable getting killed for leaving while in combat 

### ISSUE THREAD

**Issue by MuhannadYT** [EarthMC/Issue-Tracker#1262]
### Is your feature request related to a problem? Please describe.

sometimes someone randomly hits you, and you just mined some gold for ex. There is a great chance they have way more robust tools and armor than you. 
### Describe the solution you'd like

disabling being killed for disconnecting while in combat would be helpful to new players, or if Minecraft crashed, you won't lose all your items.

**Comment by JaVolimKatarinu** [comment]
And sometimes people fight with end game gear and want to save it because they are losing the fight.
