### ISSUE TITLE
[BUG]2 channels at the same time

### ISSUE THREAD

**Issue by nopnop100** [EarthMC/Issue-Tracker#1264]
### Server

Towny

### Describe the bug

I am in write mode on 2 channels, nation and global. Leaving global fixes the problem but i want to also see global, leaving nation chat doesnt work. 

### Expected behavior

Being able to write in only one channel but still see the other

### Screenshots

![image](https://user-images.githubusercontent.com/62498021/100095223-d7600900-2e62-11eb-8ca9-e293670af59a.png)

**Comment by JaVolimKatarinu** [comment]
Leaving nation chat should fix the problem. As you can leave channels, you can also rejoin them. So if leaving global helps with the issue, just rejoin it again and you should write only on 1 channel and see both of them. 
/ch leave global, /ch leave nation, /ch join global, /ch join nation

**Comment by nopnop100** [comment]
> gl

global helps because i can leave global, but i cant see global then. the problem is i cannot leave nation chat, it keeps me in even tho it says i left it
![image](https://user-images.githubusercontent.com/62498021/100141279-d8149180-2e9a-11eb-9061-708095f5214c.png)

**Comment by nopnop100** [comment]
forgot to mention i got the issue fixed by doing /nc which registered me in it again and let me leave it
