### ISSUE TITLE
[Feature] Add more variety to vote crates

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/Issue-Tracker#1265]
Just getting gold in vote crates is kinda boring. Yeah, you can get totems or tridents, but it is so rare that most players only ever get gold. More prizes could be added to the crate, some common, to help spice up voting and bringing items that are currently unobtainable into the server. This would be an easy addition to the server, and would not cause more lag or issues. Here are some ideas for what could be inside of them:

A day of premium - It would give players a taste of premium, and encourage more premium sales, while not devaluing buying premium at all, since it would be for a very limited time. It could be able to be won by just a few players every day, so not a crazy amount. It could display a chat message like other prizes. It should not include the exclusive premium item.

Conduits - A useful item that is not available, could be as rare as totems. No reason not to add.

Unavailable villager items - brings back some unobtainable items. These could be semi common prizes, as rare as getting 10-16 gold. It shouldn't be mending or other books but things like chain mail or bells.

Other items that are semi rare or unavailable could be added to vote crates as well. I think just getting gold is not very exciting, especially for older players.

**Comment by FutureLemon** [comment]
Mending and sponges x)

**Comment by MarangaI** [comment]
no sponges
just mending

**Comment by Cactusinapumpkin** [comment]
bells

**Comment by ZGamerz123** [comment]
enchanted god apples, frost walker, maybe a bruh box? spawners, spawn eggs

**Comment by shirazmatas** [comment]
Please follow format or close

**Comment by shirazmatas** [comment]
You didn't follow format now you must perish.
