### ISSUE TITLE
[BUG] towny perms in wild.

### ISSUE THREAD

**Issue by HydrolienF** [EarthMC/Issue-Tracker#1266]
### Server

beta

### Describe the bug

When we connect sometime towny pluging bug and say "Not allowed to Destroy in the wild" or "towny spawn travel is forbiden"

### To Reproduce

1. connect
2. try to break a blocs
3. or try to do /t spawn

### Expected behavior

Fix it plz.

### Additional context

It do this like 20% of the time.

**Comment by Warriorrrr** [comment]
Has since been fixed in Towny.
