### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Woiso** [EarthMC/Issue-Tracker#1267]
### Server
Towny

### Describe the bug
When I vote it says that I already voted today, even though i haven't.

**Comment by Basically-Andrew** [comment]
Please note this issue isn't solvable by EarthMC as all voting is handled on third party websites that manage voting for the server, and only EarthMC can handle the distribution of vote crates, once the third party site has verified the user has voted. As well, you can only vote every 24hrs not every day. Make sure your voting the same time you voted last time for it to properly work. Do you play any other servers? You can't vote for two servers every 24hrs.

**Comment by jkmartindale** [comment]
Yeah this isn't an EarthMC bug at all, you'd have to take this issue to the voting sites.

I'm assuming you're having this issue with MinecraftServers.org, which allows only one vote per IP address per day. You can't vote for multiple servers from the same IP address in the same day regardless of whether you use a different Minecraft username or not. If you share an IP address with someone else and they've already voted that day, you won't be able to vote until the next day.

**Comment by Woiso** [comment]
I dont share an IP address with someone else and i haven't voted for
another server either. What should I do?

James Martindale <notifications@github.com> schrieb am Mo., 30. Nov. 2020,
17:47:

**Comment by shirazmatas** [comment]
As said contact website, dont use same ip as a player, and some have either 24 hours or new day
