### ISSUE TITLE
[BUG] It wont let me join, says i have outdated  server what do i do?

### ISSUE THREAD

**Issue by Zb317812** [EarthMC/Issue-Tracker#1268]
### To Reproduce

1. 
2. 
3.

**Comment by Basically-Andrew** [comment]
EarthMC is only playable through Minecraft 1.15.2.

**Comment by jkmartindale** [comment]
Should be fixed by today's server update

**Comment by KarlOfDuty** [comment]
The server is having some issues with minecraft 1.16.4 at the moment. We always recommend using 1.15.2 as stated above anyway.
