### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MrCombine3** [EarthMC/Issue-Tracker#1269]
### Server
  
EMC

### Describe the bug

after waiting an hour i finally join towny and after 7 min of gameplay i get kicked or my i just leave the server but I did nothing or my minecraft crashes, or my pc crashes. So when i come back i have to wait an whole hour again just to BE KICKED AGAIN!

### To Reproduce

1.  
2. 
3.

**Comment by jkmartindale** [comment]
My best guess is your character joined the server when you were away from your computer. If your character is inactive on the server for 15 minutes, you're kicked so that other players waiting in the queue can join.
