### ISSUE TITLE
The gold in my town vault reset and null gold

### ISSUE THREAD

**Issue by jmills321** [EarthMC/Issue-Tracker#127]
**Server**
Which server the bug is on.
Earthmc.net (terranova)

**Describe the bug**
Yesterday i put 10 gold in my town vault, i came on today and voted to put more gold in so i could expand and it said that i couldnt deposit the gold was null and could not be deposited, then when i did /t to check the amount of people in my town later i saw that there was no gold in the town bank, and I am the only one who has access to it

**To Reproduce**
1. Go to do /t

2. See error "name cannot be null"

**Expected behavior**
I expected to have 10 gold deposited into my towns bank, aswell as to have 10 gold in my towns bank when i came online today 

**Screenshots**
https://imgur.com/a/OM10STz 

**Additional context**
could i possibly be compensated for the gold i lost?

**Comment by KarlOfDuty** [comment]
Issue has been fixed.
