### ISSUE TITLE
[BUG] Attempting to turn on friend perms turns on resident perms.

### ISSUE THREAD

**Issue by sillymilk** [EarthMC/Issue-Tracker#1270]
### Server
Towny

### Describe the bug
When attempting to turn on friend plot perms it instead turns on resident plot perms.

### To Reproduce
1. Own a plot
2. Do /plot set perm friend on while within said plot

### Expected behavior
Instead of friend perms being turned on , resident perms will be turned on.

**Comment by NatFletch** [comment]
You need to actually own the plot to achieve this. Just set it for sale for 0 gold then claim it and it should work.
