### ISSUE TITLE
[Feature] 1.16.4 version support

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1271]
### Is your feature request related to a problem? Please describe.

Currently the latest version you can join with is 1.16.3 for Towny, and 1.15.2 for Beta. It's annoying to have to switch to 1.15.2 whenever I'm trying to log onto there, and any potential new players trying to join on the latest Minecraft versions won't know exactly which version to switch to

### Describe the solution you'd like

Yes

### Additional context

Message you get when trying to join on 1.16.4

![image](https://user-images.githubusercontent.com/50800980/101281809-a7552600-37d1-11eb-8e7e-9f41f8d22420.png)

**Comment by Cactusinapumpkin** [comment]
I think its pretty common knowledge that mmo server are not always on the current version to avoid issues with bugs. If you are concerned about switching versions everytime you switch from towny to beta you could just use 1.15.2 for both because that version works for both.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/101282403-9fc65a80-379a-11eb-87b9-493d76aa294d.png)
It shows 1.16 version when you look at the details. I certain it will not be too confusing except for someone who has never played minecraft entirely before.

**Comment by Warriorrrr** [comment]
![image](https://user-images.githubusercontent.com/50800980/101296845-0a70a800-3826-11eb-9b2a-2cfeb377d050.png)
