### ISSUE TITLE
[Feature] 1.14 crafting blocks in claims

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1272]
### Is your feature request related to a problem? Please describe.

Currently, when you try to open 1.14 crafting stations in claims without permissions, you can't open them. This applies to grindstones, looms and the cartography table. For example, it would be very useful if players could use grindstones at xp grinders without having to take a risk by enabling permissions.

### Describe the solution you'd like

Allow anyone to use grindstones, looms, and cartography tables regardless of permissions.

**Comment by Cactusinapumpkin** [comment]
I think this was because brewing stands were open to everyone and then they remove it and made it a switch perm and then added the new stuff.

**Comment by jkmartindale** [comment]
> I think this was because brewing stands were open to everyone and then they remove it and made it a switch perm and then added the new stuff.

That's a good guess, though grindstones, looms, stonecutters, and cartography tables were added to Towny's default `switch_ids` before brewing stands were [[commit]](https://github.com/TownyAdvanced/Towny/commit/d9137309035228c38c84470a7b502574849260df#diff-435a3fd52ca1461fe77cd98f22a33e698298081586752d9355ee7eed79707ac2). I think this was just an oversight on Towny's end (like forgetting brewing stands), and nobody has bothered to file an issue with them to remove crafting blocks without block entities from the default permissions.

EarthMC admins can fix this in their own `config.yml` without waiting for Towny, but I'll try to file an issue over there as well.

**Comment by Warriorrrr** [comment]
Fixed this in towny a while ago
