### ISSUE TITLE
Allow people with @MC-Banned role to access #earthmc-towny and #earthmc-beta

### ISSUE THREAD

**Issue by MarangaI** [EarthMC/Issue-Tracker#1273]
###
When I was banned from EarthMC, one of the first things I noticed on the EMC discord was that my access to #earthmc-towny and #earthmc-beta was revoked. Ever since March, people have no longer been able to send messages via discord through those two aforementioned channels. Before March, people who wanted to message on #earthmc-towny who were banned in game were blocked from doing so, but today it is no longer necessary.
###
Allow people with @MC-Banned role to view #earthmc-towny and #earthmc-beta

**Comment by shirazmatas** [comment]
post here instead https://github.com/EarthMC/EarthMC.net/issues
