### ISSUE TITLE
[BUG] Glitched town ruins

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#1274]
### Server

Towny

### Describe the bug

The old behaviour of towns falling from inactivity was that the town would be silently deleted, and the chunks would be unclaimed, but with the town ruin thing, this isn't happening at all. When a town becomes a "ruin", the permissions stay the same and there isn't a time remaining given. Any town that falls right now will probably remain there forever. There aren't permissions for the /t reclaim command, so that's also not an option.

### To Reproduce

1.  Wait for a town to die from inactivity
2.  Do /t townnamehere
3.  Observe that permissions are still the same, and the time remaining isn't shown

### Expected behavior

Town permissions are toggled on, or the town disappears like the old behaviour.

### Screenshots

![image](https://user-images.githubusercontent.com/50800980/101350197-de3d4180-388e-11eb-937a-b60761aa71d2.png)

### Additional context

:syn:

**Comment by Basically-Andrew** [comment]
Fallen towns also can't be reclaimed by residents. They give the error msg, "You can not reclaim because the town is not in ruin." I am guessing the feature is in some false state that also causes the perm issues. Please look into fixing this; I would like to raid...

**Comment by Basically-Andrew** [comment]
Also, I don't know if ruins are supposed to display on dynmap, but Himeji's town in Japan is a ruin but displays a nationless town with no mayor or members. It has passed its 72 days, but because the new Towny feature is in some false state, dynmap still recognizes it as a town/claim.

**Comment by KarlOfDuty** [comment]
Is this still an issue?
