### ISSUE TITLE
Tp to any nation

### ISSUE THREAD

**Issue by ZGamerz123** [EarthMC/Issue-Tracker#1276]
This new update is bs. I can't tp to ANY non allied nation. Even nations that aren't enemies, I can't tp to. This needs to be reverted to you can tp to any nation (except enemies) not this where you can only tp to allies. This makes NO sense and is very unhelpful. PLEASE I WANT TO TP TO ANY NATION

**Comment by sillymilk** [comment]
yes i agree this is terrible please fix

**Comment by Basically-Andrew** [comment]
![image](https://user-images.githubusercontent.com/59465284/101836694-7e030580-3b03-11eb-9de6-4a2700c94628.png)
![image](https://user-images.githubusercontent.com/59465284/101836702-81968c80-3b03-11eb-830e-278e8a396317.png)

**Comment by shirazmatas** [comment]
Please follow format or this will be closed

**Comment by shirazmatas** [comment]
Format not followed
