### ISSUE TITLE
[BUG] Shake Being Disabled

### ISSUE THREAD

**Issue by Furballen** [EarthMC/Issue-Tracker#1277]
### Server

Towny

### Describe the bug

The MCMMO fishing ability, shake, which (when working as intended) has a percent chance (based off your fishing level) to make a mob drop items similiar to items they'd drop on death without killing them (only doing 10% of their health) is disabled, this was confirmed by CloackedEagle to not be intentional.

### To Reproduce

1. Get high level fishing
2. Get a mob
3. Spam a fishing rod on it
4. Nothing happens

### Expected behavior

It should do damage and drop the items when shake activates

### Screenshots

[SEE VIDEO]

### Additional context

In this Screenshot, CloakedEagle confirmed this was not intentional
![image](https://user-images.githubusercontent.com/75656920/101441615-61ca5300-38ce-11eb-8df7-e0dc9b084481.png)

The Video of shake not working, despite having a 30% shake chance:

[New Compressed (zipped) Folder.zip](https://github.com/EarthMC/Issue-Tracker/files/5656936/New.Compressed.zipped.Folder.zip)

**Comment by sillymilk** [comment]
please fix. this is the only way to get mob drops.

**Comment by Warriorrrr** [comment]
This seems to be a bug in towny itself, I made a pull request to get this fixed https://github.com/TownyAdvanced/Towny/pull/4547

**Comment by KarlOfDuty** [comment]
> This seems to be a bug in towny itself, I made a pull request to get this fixed [TownyAdvanced/Towny#4547](https://github.com/TownyAdvanced/Towny/pull/4547)

👍 Fixed on next restart.

**Comment by Furballen** [comment]
Thank you KarlOfDuty!
