### ISSUE TITLE
[BUG] Towny Election Parties

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1278]
### Server

Towny.

### Describe the bug

Mcmmo /party command is the same command for Towny Election Parties.

### To Reproduce

1. Run command /party create nation partyname.
2. Fail.

### Expected behavior

Create a political party.

### Screenshots

![image](https://user-images.githubusercontent.com/59465284/101514584-0d14ef80-3943-11eb-8873-cebb76e846cb.png)

### Additional context

/polparty create nation partyname also fails.

**Comment by Basically-Andrew** [comment]
![image](https://user-images.githubusercontent.com/59465284/101515781-5ade2780-3944-11eb-9ae9-2e7f5c926f78.png)

**Comment by jkmartindale** [comment]
Normally you could bypass the command conflict by using the `townyelections` namespace, but players don't have access to any of the commands that aren't just informational.
![image](https://user-images.githubusercontent.com/11380394/101519643-0d17ee00-3949-11eb-8095-5b7ca7beeaa1.png)

I think an admin forgot to add the new permissions.

**Comment by KarlOfDuty** [comment]
I added the permissions but it seems the developer didn't write them correctly in the documentation. And it seems they have had some issues with the command in general too: 
![image](https://user-images.githubusercontent.com/18099825/102099985-33e29280-3e29-11eb-8111-a20055ad0f6e.png)

**Comment by shirazmatas** [comment]
This seems solved?
