### ISSUE TITLE
[BUG] Unable to destroy beds 

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1279]
### Server

Towny

### Describe the bug
I am unable to break beds and I get an error message saying You do not own the land this bed occupies even though I am the mayor

### To Reproduce

1. look at bed
2. break
3. error

### Expected behavior

Bed breaks

### Screenshots

![image](https://user-images.githubusercontent.com/63156735/101676057-8818fb80-3a52-11eb-9125-15ea7283e5ec.png)

**Comment by Basically-Andrew** [comment]
Fix: Set the plot as an Inn and you'll now be able to break the bed.
/plot set Inn

**Comment by Cactusinapumpkin** [comment]
I think this issue has been happening in the wilderness as well

**Comment by KarlOfDuty** [comment]
Fixed in next towny update.
