### ISSUE TITLE
Griefers in Japan 420日本でいるグリーファー

### ISSUE THREAD

**Issue by Triquetrae** [EarthMC/Issue-Tracker#128]
My town and the other towns in our alliance have repeatedly griefed (Animals killed, builds damaged, chests looted, and insufferable faction name). The faction of griefers are Tittyclan (killerplaysxd, SPL1NT3R, Zee_) who are based in Hokkaido (Northern Japan).
 The targets of the griefings were Chikugo and Sendai. Chikugo suffered a moderate amount of damage, and Sendai was griefed to near-destruction. We plead to an end to their destructive antics.

**Comment by BowShot118** [comment]
Shouldn't this be a ticket?

**Comment by KarlOfDuty** [comment]
The issue trackers is for server changes, not individual matters.
