### ISSUE TITLE
[Feature] New Diplomat Nation Rank

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1280]
### Is your feature request related to a problem? Please describe.

Now that nation teleportation has been fixed and only nations allies can teleport to each other's capitals. Only the nation leader and Chancellor can send and accept ally requests. The two other ranks, recruiter and royale-treasure don't have these permissions. Chancellor has many other permissions that a nation leader may not trust someone with.
### Describe the solution you'd like

A new rank called, "Diplomat" would fix this issue by giving permission to send and accept ally requests. A second solution would be giving colonists permission.

**Comment by ZGamerz123** [comment]
yeah that would be amazing especially inactive nation leaders

**Comment by Fruitloopins** [comment]
please

**Comment by Basically-Andrew** [comment]
I believe this feature can be added to EarthMC by adding the following lines of code under the nation ranks section of the [Townyperms.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Townyperms.yml) file.

```yml
        diplomat:
            - towny.command.nation.ally.*
            - towny.command.nation.enemy
```

**Comment by Fruitloopins** [comment]
having perms to enemy could be harmful its basically the same as removing an ally

**Comment by Basically-Andrew** [comment]
I guess this could be a good compromise so diplomats aren't in need of as much trust. Removing towny.command.nation.enemy and only allowing diplomats the following permissions. You can read the specific on each permission node [here](https://github.com/TownyAdvanced/Towny/wiki/Towny-Permission-Nodes).
```yml
        diplomat:
            - towny.command.nation.ally.add
            - towny.command.nation.ally.accept
            - towny.command.nation.ally.deny
            - towny.command.nation.ally.sent
            - towny.command.nation.ally.received
            - towny.command.nation.ally
```

**Comment by DasCodes** [comment]
Okay.

**Comment by DasCodes** [comment]
Done.
