### ISSUE TITLE
Idea 4 Mending

### ISSUE THREAD

**Issue by 1453SPQR** [EarthMC/Issue-Tracker#1283]
Mending is rare and expensive, and it's going to die out with no way of getting it, it's incredibly important, and there should be another way to acquire it,

Can you make It so when you enchant books there is a chance for Mending to show up in the 30 exp options, it would be a good feature and make it so you don't have to keep spending money on God Tools each time they break.

**Comment by shirazmatas** [comment]
please follow format or this will be removed

**Comment by DasCodes** [comment]
Mending was added to vote crates today.
