### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thewhoboy** [EarthMC/Issue-Tracker#1284]
### Server

earth mc

### Describe the bug

so when i try to join it says auth servers are under mantnice but others are joining

help would be great!

**Comment by Basically-Andrew** [comment]
Is this an issue with Towny, Classic, or Beta. You didn't specify under the heading, "Server." I'm going to guess you're trying to join Towny. I have seen messages like this before; usually, rejoining the server fixes any queueing issues for me. If this doesn't permanently block you from joining the server or doing something specific, then consider it a "feature"! 😃

**Comment by jkmartindale** [comment]
Your Minecraft client wasn't able to log in to your Minecraft account. Relaunching Minecraft can help, otherwise check your firewall settings to make sure your client can reach the Minecraft authentication servers. This isn't an EarthMC issue.
