### ISSUE TITLE
[BUG] Nation Ranks Removed

### ISSUE THREAD

**Issue by indian7p** [EarthMC/Issue-Tracker#1286]
### Server
Towny

### Describe the bug
Hello! I keep being notified (twice now) by one of my two Chancellors that his rank keeps getting removed. Both times it turned out both Chancellor's ranks were being removed. 

### To Reproduce

Self explanitory from previous section, automatic?

### Expected behavior
The two chancellors not having the rank

### Screenshots

N/A

### Additional context

Nation - Gujarat
Chancellors - InfiniteTapWater, Mapscientist

**Comment by Basically-Andrew** [comment]
This isn't only your nation, nor just councillors all nation ranks are being cleared.

**Comment by Warriorrrr** [comment]
This seems to be fixed in towny now, so this can probably be closed
https://github.com/TownyAdvanced/Towny/commit/9769a3103b527f29ebbfb641a934600d9cdbad5d

**Comment by shirazmatas** [comment]
Is this fixed @Warriorrrr ?

**Comment by Warriorrrr** [comment]
The server hasn't updated Towny yet so it's still happening
