### ISSUE TITLE
[BUG] redstone is full broken, autofarms are FUBAR

### ISSUE THREAD

**Issue by bwilso1** [EarthMC/Issue-Tracker#1287]
### Server
earthmc.net

### Describe the bug
make any redstone machine or simple circuit over 1 redstone of length to a piston or redstone lamp
use a button or pulse to activate the circuit
Verify: pistion never moves or lamp never lights

### To Reproduce
1.) do anything with redstone
2.) verify, it doesn't work

### Expected behavior
redstone circuits should transfer power up to 15-16 blocks.  I'm getting 1 at best.

### Screenshots
videos too large to upload, posting videos on youtube showcasing the problem.

### Additional context
this broke about a few weeks ago.  Bamboo farm broke a month ago, and now my kelp farm is FUBAR.  Links to videos below showcasing the problem.
https://youtu.be/VzXPCqevBV8
https://youtu.be/WlrhDMtPbiA
https://youtu.be/2DgENC1bzxI

**Comment by Warriorrrr** [comment]
This is happening to my redstone aswell.

**Comment by bwilso1** [comment]
looks like redstone has been un-f**ked since I posted this.  Perhaps the server rebooted, or an admin toggled some plugin setting.  However my bamboo farm will not work automatically, I still need to trigger it manually for bamboo to fall from full grown stalks.  Not sure if logging on/off in between trigger moments has an effect yet.

I have not had a chance to watch my kelp farm grow, but at least no more sticky pistons are getting stuck in the "ON" position by faulty redstone.

If the bamboo farm is a "separate issue", I vote to close this as "can not reproduce" as redstone is no longer broken as of this comment.

**Comment by bwilso1** [comment]
bamboo farm fixed itself, well not by itself.  I'm sure some server setting was tweaked.  marking closed.

**Comment by Scorpionzzx** [comment]
Unsubscribe
