### ISSUE TITLE
Maybe it's time to just end it all.

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1289]
Come on, Fix. It's been a good run. But we both know the server's ran its course. End it on a high note. Sincerely yours, the Ender King, Sigma Fields, D3F3CT1V3, and all the rest of the players who've left. It's time to move on.

**Comment by MarangaI** [comment]
I think somethings wrong with your head

**Comment by BunbunToast** [comment]
> I think somethings wrong with your head

You're the one in denial. You wouldn't get it though. Poor soul.
