### ISSUE TITLE
Saddle's Recipe.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#129]
Maybe there could be a recipe for saddle's i've thinkered with this idea and came with a pretty reasonable recipe. I don't know if you guys like it.

![knipsel](https://user-images.githubusercontent.com/44688587/48363719-de19ea00-e6a6-11e8-89b8-5a3499eab99f.PNG)

**Comment by KarlOfDuty** [comment]
Duplicate of #100
