### ISSUE TITLE
[BUG] Reduced drops from tree feller.

### ISSUE THREAD

**Issue by nsx69420** [EarthMC/Issue-Tracker#1290]
### Server

Towny

### Describe the bug

When using tree feller on a tree saplings/apples/sticks do not drop (I only tried this with dark oak but I assume the bug affects all trees).

### To Reproduce

1. Obtain Tree
2. Activate Tree Feller
3. Cut Tree

### Expected behavior

I expected an amount of saplings, sticks, and apples to drop alongside the wood.

This bug makes farming trees using tree feller impossible as no saplings drop to replant.

**Comment by Warriorrrr** [comment]
This isn't a bug, a new subskill in woodcutting was added that gives you more drops from tree feller

![image](https://user-images.githubusercontent.com/50800980/103374311-8da8b500-4ad7-11eb-96e6-1ec5d736ac8b.png)
