### ISSUE TITLE
[BUG] Queue is broken

### ISSUE THREAD

**Issue by Thebirdsarecommies** [EarthMC/Issue-Tracker#1291]
### Server

Queue server

### Describe the bug

Almost everybody who has joined queue today hasn't been able to join the game.

### To Reproduce

1. Join the server
2. Wait until you are about to be teleported to world

### Expected behavior

An expectation to join the main server

### Screenshots

![image](https://user-images.githubusercontent.com/76791923/103378424-45c26780-4ab0-11eb-9a9a-4707a3178e2b.png)

### Additional context

It's not just me, it seems that everyone's noticed that the tp bot is broken. Several people are discussing it right now.

**Comment by DasCodes** [comment]
Should be fixed now.
