### ISSUE TITLE
Re-enable invite-less joining

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1293]
More than a year ago now GGOVI botted the server and got the feature to join towns without an invite removed, ever since then GGOVI has quit EarthMC and hasn't been seen since. I think this feature should be re-enabled as it costs towns lots of residents so they can't expand further etc and also the threat of bot attacks are not high.

**Comment by shirazmatas** [comment]
please follow format

**Comment by shirazmatas** [comment]
You didn't follow format, now this issue must perish.
