### ISSUE TITLE
[BUG] Anti-advertising plugin detects usernames as websites.

### ISSUE THREAD

**Issue by superiorglitch** [EarthMC/Issue-Tracker#1294]
THIS IS A MAJOR BUG THAT NEEDS IMMEDIATE FIXING!

If you try to perform the following command on someone who contains something that resembles a website link within their IGN it will prevent you from performing the command: /res

For example try it on the user MadisonDotNet
/res MadisonDotNet

It will print the following message: Please do not advertise other websites or IP adresses.

THIS IS A MAJOR BUG THAT NEEDS IMMEDIATE FIXING!

**Comment by gabeeebaby** [comment]
Yes this needs fixing asap. I just added Dotcom to the end of my mc name to try and prove this needs work. Any time someone tries to /res me or /msg me it blocks their message with the advertising filter and staff get majorly annoyed at the giant popup in their chat. I suggest making it so commands and usernames are exempt from the filter.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by shirazmatas** [comment]
You didn't follow format now you must perish.

**Comment by ByeMC** [comment]
Because they didn't follow format my Email notifs must suffer
