### ISSUE TITLE
Return the compass in the lobby

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1296]
In early 2020 the compass in the lobby was removed for unknown reasons, and this caused the factions player base to die and then factions eventually died out. As factions is returning soon I think the compass should be re-added to make sure factions has a stable player base and this could also benefit EarthMC beta

**Comment by shirazmatas** [comment]
Please follow format

**Comment by KarlOfDuty** [comment]
We will not return the compass at this time.
