### ISSUE TITLE
[World] Grand Canyon Fixing 

### ISSUE THREAD

**Issue by americanfrog** [EarthMC/Issue-Tracker#1299]
### Describe the issue
The Grand Canyon was at one point a large supply of terracotta now it has been griefed badly.  The Grand Canyon was added after TN was released and was a cool thing to have. I think it would be nice to see a ungreifed Grand Canyon I don't know if anyone would take this on as it is a massive area. It would also look better on the map.

### Coordinates
-21108,-6843

### Screenshots
![image](https://user-images.githubusercontent.com/73496849/105609893-4500b680-5d7a-11eb-8daf-7b35e260775e.png)

**Comment by shirazmatas** [comment]
please follow format

**Comment by KarlOfDuty** [comment]
We don't really do world editing anymore, as players mined it it would be up to players to fix it.
