### ISSUE TITLE
[Feature] Steve/Alex Heads Are Devalued 

### ISSUE THREAD

**Issue by hydro78878** [EarthMC/Issue-Tracker#1301]
### Is your feature request related to a problem? Please describe.
 steve/alex heads have dropped in value incredibly quickly 

### Describe the solution you'd like
 remove the bug that lets you create more and optionally delete all steve/alex heads that were made after the new crate was added

**Comment by shirazmatas** [comment]
Please make your post more descriptive, what bug?

**Comment by Cactusinapumpkin** [comment]
https://user-images.githubusercontent.com/48000340/108153616-218f0a00-70a1-11eb-96d2-e4e460772f91.mp4

**Comment by Cactusinapumpkin** [comment]
steve/alex heads that flip flop like this are a product of rolling back an area that a mystery crate head was in and doesn't revert back to the original head. I have never seen a alex head and I have a steve head from when my head was rolledback and revert to steve before mystery head crates

**Comment by Cactusinapumpkin** [comment]
This bug cannot be fixed as its not really a bug but a misunderstanding.
