### ISSUE TITLE
Add /bank command to check gold balance

### ISSUE THREAD

**Issue by IAmUnStTV** [EarthMC/Issue-Tracker#1302]
### Is your feature request related to a problem? Please describe.
Sometimes when I am checking my gold balance on EarthMC, I type /bank instead of /player. This gets annoying as /bank doesn't exist. Also, a way of storing gold without e-chests would be cool. 
### Describe the solution you'd like
When I type /bank, it should print out how much gold you have into chat. 
When I type /bank deposit, I would like it to allow me to add gold to my bank. 
When I type /bank withdraw, I would like it to withdraw gold from my bank.

**Comment by jkmartindale** [comment]
> add/withdraw gold to my bank for a small fee.

bruh no

**Comment by IAmUnStTV** [comment]
K forget the fee.

**Comment by jkmartindale** [comment]
If `/player` is too much to type you can type `/res` and if that's too much to read you can type `/bal`

**Comment by shirazmatas** [comment]
I don't think it would be added considering we already have /bal
