### ISSUE TITLE
[BUG] Pinging Players is not consistant

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/Issue-Tracker#1304]
### Describe the bug

Sometimes when you ping a player it doesn't ping them in game. The ping turns green when it pings them in game, otherwise it stays white. There is no pattern to reproducing it, it seems totally random on if it becomes an in game ping. It doesn't matter if there is text after it or not, it still only pings player in game sometimes

### To Reproduce

1. @Fix why are you sexy?
2.  server randomly decides whether to ping player or do nothing

### Expected behavior

It should ping player in game every time as long as they are in game

### Screenshots

<img width="608" alt="Screen Shot 2021-01-23 at 8 08 33 PM" src="https://user-images.githubusercontent.com/61715242/105620973-8a8fa480-5db7-11eb-817d-3bac00eca737.png">
<img width="547" alt="Screen Shot 2021-01-23 at 8 08 25 PM" src="https://user-images.githubusercontent.com/61715242/105620978-90858580-5db7-11eb-94c8-a472b7b2fc97.png">

**Comment by IAmUnStTV** [comment]
You just pinged a random french guy. ![image](https://user-images.githubusercontent.com/77801870/106903854-6fdff880-66f2-11eb-96ed-e4b20ce98210.png)

**Comment by IAmUnStTV** [comment]
A workaround would be to tag their discord username, as the discord bot would then ping them.

**Comment by IAmUnStTV** [comment]
> A workaround would be to tag their discord username, as the discord bot would then ping them.

Never mind, doesn't work

**Comment by Warriorrrr** [comment]
Closing since this isn't very important, if you need to ping someone, either do so manually or just use `<@id>`.
