### ISSUE TITLE
[BUG] Incorrect advertised number of player slots

### ISSUE THREAD

**Issue by jkmartindale** [EarthMC/Issue-Tracker#1305]
### Server
Towny

### Describe the bug
The server advertises 200 player slots, even though EarthMC hasn't let in that many concurrent players in several months. Active EarthMC members are already well aware of the real player count, but this could be disorienting for new and prospective players.

This also affects advertised player slots on the two voting sites EarthMC is listed on, where the conflicting info could be seen as false advertising.

### To Reproduce
1. Add `earthmc.net` to your list of Minecraft servers
1. Wait for the Minecraft client to fetch server info
1. Get excited about there being free slots on the server
1. Join the server and get rekt by the queue

### Expected behavior
Advertised slots match the number of slots listed in-game on the Towny server (currently 100)

### Screenshots
![image](https://user-images.githubusercontent.com/11380394/105621415-c2edad80-5dcc-11eb-9d51-dc7f3f4aceeb.png)

![image](https://user-images.githubusercontent.com/11380394/105621383-7d30e500-5dcc-11eb-84a6-da515a8f6b5a.png)

**Comment by KarlOfDuty** [comment]
The number of player slots shown on the server list cannot be changed without a network restart which we only do a few times per year, so we won't really be changing that as the player count changes on the inner servers.

**Comment by jkmartindale** [comment]
hm, a change

![image](https://user-images.githubusercontent.com/11380394/110975993-fad19580-8325-11eb-945b-a0fbe1d8d140.png)
![image](https://user-images.githubusercontent.com/11380394/110976384-70d5fc80-8326-11eb-851e-c3ee4743afdd.png)
