### ISSUE TITLE
[BUG] Towny Chat

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/Issue-Tracker#1308]
### Describe the bug

Speaking in towny chat is still disabled, with no clear reason why. It is as simple as clicking a few buttons to allow players to talk in it. Staff can talk in it, so there are no issues with it. If players spamming in towny chat is the issue, just add a slow down like in general. Mute bypassing is so rare and easily fixed by just muting the player on discord too. 

### To Reproduce

1. Try and talk in towny chat 
2. Fail

**Comment by DasCodes** [comment]
Is this still an issue? @gabeeebaby

**Comment by gabrielscharff** [comment]
> Is this still an issue? @gabeeebaby

Yes, users with the player role cannot speak in #earthmc-towny

**Comment by jkmartindale** [comment]
As far as I can tell, staff are still the only people who can send messages in #earthmc-towny

**Comment by DasCodes** [comment]
Yes this is intentional. I'm not sure if this will be back or not. So closing this for now.
