### ISSUE TITLE
[BUG] Queue is letting more players in than the main server can handle

### ISSUE THREAD

**Issue by 10op10** [EarthMC/Issue-Tracker#1309]
Server:
Towny

### Describe the bug
The queue is allowing more players in than the cap which causes a shit-ton of lag when the player count goes over 100 which causes players to complain and spams chat.

To Reproduce
1. Press TAB
2. Look at player count
3. Server is over cap

Expected behavior
NO more players than 100

Screenshots
![image](https://user-images.githubusercontent.com/63156735/106459345-9f3ffc80-6489-11eb-89d3-6b1071f99c28.png)
![image](https://user-images.githubusercontent.com/63156735/106459469-cdbdd780-6489-11eb-92b1-bc87d85048f9.png)

Additional context
Yes I follow the format shiraz

**Comment by jkmartindale** [comment]
iirc mods can freely enter the Towny server regardless of player count

**Comment by 10op10** [comment]
It's letting normal players in though, not just mods; name one time you've seen 11 mods on at once let alone 3

**Comment by KarlOfDuty** [comment]
We will just focus on increasing performance rather than add more checks for the queue for the few times the server freezes.
