### ISSUE TITLE
Weapon name in death messages

### ISSUE THREAD

**Issue by xTrainee** [EarthMC/Issue-Tracker#131]
EarthMC Classic had the feature where the user's weapon name would be displayed in the death message when they killed someone.  It would be fun to reinstate this feature.

**Comment by MSatrokrm** [comment]
This would certainly be interesting.

But there would still be people who name their weapons inappropriate words, probably why it got removed.

**Comment by KarlOfDuty** [comment]
Nah it wasn't removed by us, it's just either broken in 1.13 or has been removed from the game.

**Comment by 4noah18** [comment]
I really liked that part of EMC. Collecting other people's named weapons was special. If you killed an infamous player and you held his weapon, that was something you had that no one else had. The idea of certain people's weapons racking up kills is neat to me, it was like a collectors item.

**Comment by 32Gold** [comment]
You can just recreate the sword and lie tho, so it hold no value
