### ISSUE TITLE
[World] Beta plus its dynmap OFF

### ISSUE THREAD

**Issue by Johny2268** [EarthMC/Issue-Tracker#1310]
### Describe the issue
<b>The beta server and its dynmap arent working for about 3,5 hours right now</b>. The server said it was shut down gracefully but I made this ticket in case it crashed.

### Coordinates
WHOLE WORLD

**Comment by 10op10** [comment]
The main EMC map is down aswell

**Comment by Basically-Andrew** [comment]
Dynmap's data available at https://earthmc.net/map/up/world/earth/ is also down.
