### ISSUE TITLE
[BUG] Shop Plugin Cannot Detect Books In Chest The Day After The Store Is Created

### ISSUE THREAD

**Issue by imableeblob** [EarthMC/Issue-Tracker#1311]
I have created numerous shops with books. The day of, they work fine and are fully functional. They detect the correct amount of books. The day after, all the shops inventories go to zero. I presume this is due to NBT data changing? However there is no NBT tag data for written books that would change from day-to-day..

https://minecraft.gamepedia.com/Player.dat_format#Written_Books

Any ideas? Fixes? I would love to have my book shop work :(

**Comment by shirazmatas** [comment]
please follow format

**Comment by imableeblob** [comment]
1.16 update has fixed this problem.
