### ISSUE TITLE
[BUG] I have premium and i have connected my MC username to discord but i still cant fly in queue, it's not a very important bug but i thought still i'd let u guys know. 

### ISSUE THREAD

**Issue by vindvi** [EarthMC/Issue-Tracker#1312]
[BUG] I have premium and i have connected my MC username to discord but i still cant fly in queue, it's not a very important bug but i thought still i'd let u guys know.

**Comment by shirazmatas** [comment]
please follow format, also have you tried /flying

**Comment by Basically-Andrew** [comment]
Has this issue been resolved? If not, your better off creating a ticket in the earthmc support discord server.
