### ISSUE TITLE
[BUG] Golden Bed bug

### ISSUE THREAD

**Issue by LegoVK** [EarthMC/Issue-Tracker#1316]
### Server

EarthMC Towny

### Describe the bug

The problem is that if you place a golden bed from the sleep event on the ground, and then break it to move it. Will it turn into a completely normal yellow bed. I do not have any screenshots or videoes of it happening since i only had one bed and therefor discovered the bug as it happened to me. 

### To Reproduce

1. 
2. 
3.

**Comment by Warriorrrr** [comment]
It's known that blocks lose their nbt data when placed, if you have evidence of owning the item you might be able to get it refunded in the support discord.

**Comment by LegoVK** [comment]
> It's known that blocks lose their nbt data when placed, if you have evidence of owning the item you might be able to get it refunded in the support discord.

Oh yeah, I have also added some proofs to that ;P
