### ISSUE TITLE
Requesting an unban from the community

### ISSUE THREAD

**Issue by Zardinio** [EarthMC/Issue-Tracker#1317]
I wish to request from the community that my recent banishment be overlook or made temporary. Under whichever conditions you deem to be fair, I wish to redeem myself and perhaps be forgiven for my crime of breaking the server 1.1 rules.

The fashion which I broke the server rules were that of x-raying, I had gone to the nether and had x-rayed for ancient debris. Obviously, I won't say how I had gone about doing this, but I thought it would be worth saying that I was not using a cheat client in order to do so.

I am a dedicated member of this community, and while I had cheated to obtain certain wealth in the Nether, I can say all other wealth I accumulated was through legit and fair means. I've been playing on the server for a rather long time and I would rather not see it just end abruptly and in such a disconnected fashion.

Those of you who know me, can trust me on my word, that should I be allowed to return to the server I intend to dedicate myself to the world map project and exclude myself from entering the Nether ever again.

**Comment by jkmartindale** [comment]
Open a ticket in the [support Discord server](https://discord.gg/EZBYmpp). This issue tracker is for feature suggestions and bugs, not personal matters.

**Comment by Zardinio** [comment]
> Open a ticket in the [support Discord server](https://discord.gg/EZBYmpp). This issue tracker is for feature suggestions and bugs, not personal matters.

I did, and I was suggested to come here though Not specifically. I thought I would appeal to the general community as well, because I am fairly desperate.

**Comment by gabeeebaby** [comment]
As jkmartindale just said, this is not the correct place for appeals. Unless you want to try and get the X-raying rule removed or changed. I believe staff don’t give second chances for cheating, as they are likely to offend again.

**Comment by BunbunToast** [comment]
Shouldn't have cheated.

**Comment by Zardinio** [comment]
> Shouldn't have cheated.

True. I regret it.

**Comment by TwitchPid** [comment]
same
