### ISSUE TITLE
[Feature] Increase nation cost and add upkeep

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/Issue-Tracker#1318]
### Is your feature request related to a problem? Please describe.

There are currently way too many nations compared to the amount of towns on the server. Currently 1905 towns and 417 nations. This is way too many, and many of them are single person nations that are inactive, or only point is for the /n spawn. 

### Describe the solution you'd like

Nations should be a collaboration between multiple towns, or at least multiple players in a single town. Just how nations used to cost 512 gold when terra nova was first released, nation prices should be increased again. It should be double or triple the current price. There are already so many nations that it would encourage joining an already established one, instead of making their own. To get rid of inactive one town one man nations, and other nations that are completely dead, there should be an upkeep just on nations. It should be 10-20 gold a week, enough that any active player(s) could save throughout the week just through voting, and if someone needs to go inactive for a bit, its easy enough to save up gold to prevent disbandment. 
In order to satisfy those who want a teleport to their town for trade or other reasons, enabling /t spawn just for towns within the same nation would be a great solution.

**Comment by Zardinio** [comment]
I think increasing the price of a nation is a good thing, but I disagree with the idea of upkeep since we have the 21day kicker. If there ought to be any sort of change to how towns/nations operate, there should instead be more claims for towns who are in nations, that way we can fill the map out even more.

**Comment by DirtyDoctorDan** [comment]
I think a static upkeep of around 100-200 gold per week is a great way for quality/quantity controls of nations
I also think an upkeep which scales per number of players residents (e.g. 1 gold per player per 2 days) would be good for towns.
