### ISSUE TITLE
[SUGGESTION] [FEATURE] [RECIPE] Gravel to Sand Refinement

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1319]
I've long been allied with the thoughts of those who wish to conserve the natural beauty of the world.
One of the greatest threats to this is sand mining. 
Not only does sand mining deface the beautiful deserts that nations like Egypt take great pride in, it's also almost against the rules. Terraforming is defined as "To change the surface to resemble earth". However in the server's case it is more of the opposite. Creating mountains or entire islands is against the rules.
I see no difference between the synthetic islands which are reset and the wastelands of barren stone where once was grand desert, other than their permanence.

My solution to this issue is a rather simple one. 
Allow for conversion of gravel to sand.

It is far beyond the realms of science fiction to say gravel could be refined into sand. And a buffer ingredient could also be used to ensure it's sufficiently balanced. Quartz would be a good choice, as it's found in silica sand which is used to make glass. To balanced further (should we feel inclined), 8 gravel would be used for an output of 4 sand. My own recipe for it would look something like this; 

 
![image](https://user-images.githubusercontent.com/46580909/108381251-a1b68c00-71d5-11eb-8b19-f7275ee7a29e.png)

If the recipe is not to your liking however, there are many other ways we could go about it. I'd LOVE to start a discussion about this in the comments. I also feel that this would not disrupt the market in any meaningful amount, seeing as the miniscule ratio would more be for those desperate for the sand. Sand Mining would be far more profitable and take less time, however this alternative provides a way of restoring the deserts, WITHOUT paying a ransomed fee to get back all the sand. Which, let's face it, is long gone in the construction of glass skyscrapers. Here is the code as well for the recipe above.

`{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        "#Q#",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:gravel"
        },
        "Q": {
            "item": "minecraft:quartz"
        }
    },
    "result": {
        "item": "minecraft:sand",
        "count": 4
    },
    "group": "misc"
}`

**Comment by 10op10** [comment]
But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it

**Comment by BunbunToast** [comment]
> But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it

Well, actually! Gravel is fairly common underground in HUGE pockets and can be mined out fairly easily. I might even go as far to say that all in all, there may be more gravel on EarthMC than sand due to it's sheer quantity underground.

**Comment by 10op10** [comment]
> > But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it
> 
> Well, actually! Gravel is fairly common underground in HUGE pockets and can be mined out fairly easily. I might even go as far to say that all in all, there may be more gravel on EarthMC than sand due to it's sheer quantity underground.
> 
> Come to my town at "/n spawn Arctic_Ocean". I've dug out such big pockets of gravel that I made caves from them!

Yes but A) People don't want to spend ages Mining and looking for gravel
B) It will take longer and will be harder to get a dub of sand than sand mining for 15 minutes and getting a dub of sand

**Comment by BunbunToast** [comment]
> > > But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it
> > 
> > 
> > Well, actually! Gravel is fairly common underground in HUGE pockets and can be mined out fairly easily. I might even go as far to say that all in all, there may be more gravel on EarthMC than sand due to it's sheer quantity underground.
> > Come to my town at "/n spawn Arctic_Ocean". I've dug out such big pockets of gravel that I made caves from them!
> 
> Yes but A) People don't want to spend ages Mining and looking for gravel
> B) It will take longer and will be harder to get a dub of sand than sand mining for 15 minutes and getting a dub of sand

Yes, but we're not taking away the ability to just go sand mining normally. We're just providing an alternative for those who don't want to ruin the deserts.

**Comment by 10op10** [comment]
> > > > But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it
> > > 
> > > 
> > > Well, actually! Gravel is fairly common underground in HUGE pockets and can be mined out fairly easily. I might even go as far to say that all in all, there may be more gravel on EarthMC than sand due to it's sheer quantity underground.
> > > Come to my town at "/n spawn Arctic_Ocean". I've dug out such big pockets of gravel that I made caves from them!
> > 
> > 
> > Yes but A) People don't want to spend ages Mining and looking for gravel
> > B) It will take longer and will be harder to get a dub of sand than sand mining for 15 minutes and getting a dub of sand
> 
> Yes, but we're not taking away the ability to just go sand mining normally. We're just providing an alternative for those who don't want to ruin the deserts. Both sides can exist.

Yes but no one will use this custom recipe and continue mining out the sahara or the arabian desers

**Comment by BunbunToast** [comment]
> > > > > But the issue is Gravel is harder to find compared to sand, and quartz is also quite expensive on the server which would make building using sandstone or concrete a shitload more expensive and not many players would be happy with it
> > > > 
> > > > 
> > > > Well, actually! Gravel is fairly common underground in HUGE pockets and can be mined out fairly easily. I might even go as far to say that all in all, there may be more gravel on EarthMC than sand due to it's sheer quantity underground.
> > > > Come to my town at "/n spawn Arctic_Ocean". I've dug out such big pockets of gravel that I made caves from them!
> > > 
> > > 
> > > Yes but A) People don't want to spend ages Mining and looking for gravel
> > > B) It will take longer and will be harder to get a dub of sand than sand mining for 15 minutes and getting a dub of sand
> > 
> > 
> > Yes, but we're not taking away the ability to just go sand mining normally. We're just providing an alternative for those who don't want to ruin the deserts. Both sides can exist.
> 
> Yes but no one will use this custom recipe and continue mining out the sahara or the arabian desert

So why not add it? You wouldn't lose anything. We only stand to gain from this change. I'd use it a ton. And I've talked to other nations/town members which aren't near those deserts and they would love stuff like this.

**Comment by americanfrog** [comment]
This would help the loads of tickets that I and others have opened about sand mining. It would help to reduce those tickets if people use this way more.

**Comment by sage-blue** [comment]
this is old but I think a good idea. The recipe you put isn't very good, maybe put bonemeal instead of quartz.

**Comment by BunbunToast** [comment]
Sand made for glass production irl has quartz traces in it. I thought it
would be a good way to balance it out. Besides, it's only 1 quartz.
Bonemeal doesn't make much sense.

**Comment by shirazmatas** [comment]
Please follow format and I will reopen.
