### ISSUE TITLE
[World] Lago De Maracaibo bay

### ISSUE THREAD

**Issue by JADENJUMBO** [EarthMC/Issue-Tracker#132]
**Describe the issue**
The Lago De Maracaibo bay is currently a regular ocean biome with a completely dirt bottom that is flat.
I propose that it should be a warm ocean biome. It should also be sand at the bottom and shouldn't be completely flat. It should also have ocean vegetation like seaweed. There should not be coral though because in real life there is no coral in the region. 

**Coordinates**
X -13385.794 Y 63 Z -1817.842

**Screenshots**
How it looks now
![1](https://user-images.githubusercontent.com/44713967/48386337-706dbe00-e6a6-11e8-915b-4b01b01aa2a5.png)
![2018-11-12_17 51 38](https://user-images.githubusercontent.com/44713967/48385560-d0af3080-e6a3-11e8-9772-832598c822b1.png)
![2018-11-12_17 52 20](https://user-images.githubusercontent.com/44713967/48385567-d9a00200-e6a3-11e8-9807-75cfdc42b3a3.png)
![2018-11-12_17 52 25](https://user-images.githubusercontent.com/44713967/48385571-ddcc1f80-e6a3-11e8-891d-3e578257f088.png)

An idea of how it should look
![2018-11-12_18 02 01](https://user-images.githubusercontent.com/44713967/48385898-26d0a380-e6a5-11e8-9476-ddd456dff667.png)
As you can see the bottom of this ocean is not flat, is made of sand, and there is seaweed.

**Comment by JADENJUMBO** [comment]
It might also be a good idea if the entire region was warm ocean. 
![1](https://user-images.githubusercontent.com/44713967/48452787-7e364880-e765-11e8-8a84-7ceafa0e3175.png)

**Comment by JADENJUMBO** [comment]
Maybe in the future you guys could update the entire map to have the correct ocean temperatures like this picture shows. I do think you guys should focus on my first request though.
![image](https://user-images.githubusercontent.com/44713967/48452999-6ad7ad00-e766-11e8-8c82-00fe6c27e914.png)

**Comment by shirazmatas** [comment]
kinda fixed
