### ISSUE TITLE
[BUG]Avatar state occurs when crouch+clicking stairs

### ISSUE THREAD

**Issue by Mrwol6YT** [EarthMC/Issue-Tracker#1321]
### Server

Earth smp-towny

### Describe the bug

when you sit in a stair while crouching twice you stop taking damage and can teleport back to the seat by crouching.

### To Reproduce

1.  Crouch
2.  Left click stair
3.  repeat twice

**Comment by Mrwol6YT** [comment]
i tried to put a video showing it all but it is to big

**Comment by 10op10** [comment]
> i tried to put a video showing it all but it is to big

Upload the video to YouTube then put it in the issue

**Comment by shirazmatas** [comment]
This is epic bug

**Comment by YellowVictini** [comment]
> This is epic bug

Based bug, some might say

**Comment by Warriorrrr** [comment]
I've had this bug happen to me a couple of times, and it can be confusing sometimes. This can't be fixed as far as I know, since it's a bug with the game itself. The bug isn't gamebreaking, because others will still see you sitting on the chair from their perspective.
