### ISSUE TITLE
[World] Grief in Oman

### ISSUE THREAD

**Issue by godlyeriss** [EarthMC/Issue-Tracker#1324]
### Describe the issue
Ebeny, a member of Nejd, came and griefed around my town of the Omani_Sultanate. I need the grief reverted.

### Coordinates
10614 64 -3904

### Screenshots
![Grief1](https://user-images.githubusercontent.com/79424350/108640394-33c8c980-744e-11eb-93cb-ccdd806de0be.png)
![Grief2](https://user-images.githubusercontent.com/79424350/108640395-375c5080-744e-11eb-9de5-c16673dc8afc.png)

**Comment by 10op10** [comment]
Open a ticket in the [Support discord](https://discord.gg/HrBjyt4KEj)

**Comment by shirazmatas** [comment]
What he said
