### ISSUE TITLE
EMC New Update Login Issue 

### ISSUE THREAD

**Issue by kiwifruht** [EarthMC/Issue-Tracker#1325]
<img width="1276" alt="Screen Shot 2021-02-22 at 23 18 17" src="https://user-images.githubusercontent.com/69109187/108737488-3b2ec680-7565-11eb-8a4a-667964a593a7.png">
Hello EMC, 
I am an active player in this server since a year ago but I have no problem in logging in previously. But this time, logging in is really hard ever since the new update is out. Queueing is no problem, but me getting in to the queue itself is hard, the queue world wont load. I have been using my windows to login, it didnt work. I tried on my mac, it didnt work. And if you are talking about my internet speed, I played games like Monster Hunter or Tekken with no problem in my Windows. This have never happened before the update happened. Please help.

*edit: I have attached the picture while I am logging in to the server. And note this, I have no problem in logging in other servers at all.

<img width="1280" alt="Screen Shot 2021-02-22 at 23 18 28" src="https://user-images.githubusercontent.com/69109187/108737599-58fc2b80-7565-11eb-9039-b75991e61833.png">

<img width="1276" alt="Screen Shot 2021-02-22 at 23 18 17" src="https://user-images.githubusercontent.com/69109187/108737633-644f5700-7565-11eb-927c-1de367fd36fa.png">

Thank you,
KiwiFruht

**Comment by shirazmatas** [comment]
Please do a support ticket instead in the support discord https://discord.gg/EZBYmpp
