### ISSUE TITLE
Voteing system[BUG]

### ISSUE THREAD

**Issue by EnderDaWolf** [EarthMC/Issue-Tracker#1326]
### Describe the bug
It's mainly something with the vote systems. So basically what happened is I had voted on one of the sites first, nothing came up so i decided to play it off as the bot taking time to put it in and vote on the 2nd site but once i voted the crate for the 2nd site showed up and the 1st one never did.

### To Reproduce

You can't 100% of the time replicate this situation, it just happens.

### Expected behavior
I'm hoping the bot gets a check and if a bug is seen in the code to be fixed up so the bot properly detects it again

### Screenshots
Dont really have any due to it being the bit not handing the crates out

### Additional context
No additional context

**Comment by Krazy0999** [comment]
I've had this issue. Happens once in a blue moon. I don't think it is fixable, just something that comes with the voting system. A risk of it not working every now and then.

**Comment by jkmartindale** [comment]
There used to be an FAQ evere on the old (better imo) website that said this was a known issue that EarthMC couldn't do anything about.

I've found that sometimes a voting site will register a vote from your IP address without giving you a crate, but if you try again from a different address with the same username it'll register the vote for real and send a crate.
