### ISSUE TITLE
[Important] Nation Chat Is Broken [BUG]

### ISSUE THREAD

**Issue by geobeeblaster** [EarthMC/Issue-Tracker#1327]
### Server
Towny

### Describe the bug
Nation and town chats dont work and say "there is no plot in this location"

### To Reproduce

1. do /ch join nation
2.  type something

### Expected behavior

It should show up in nation chat.

### Additional context

Its been broken for almost a month now, ever since we updated to 1.16

**Comment by Krazy0999** [comment]
Yeah, this is a known issue. As you said, came from the update to 1.16. It sure is annoying but it is making a lot more people talk in global chat, and more people are using the /party feature. I feel more connected, it is annoying but not the worst bug to ever exist on EMC.

**Comment by geobeeblaster** [comment]
But does this issue plan to be fixed? Not many people are in parties, and the nation chat helps people talk to new recruits.

**Comment by Krazy0999** [comment]
> But does this issue plan to be fixed? Not many people are in parties, and the nation chat helps people talk to new recruits.
> […](#)
> Sent from my iPhone
> On Feb 27, 2021, at 7:01 AM, Krazy ***@***.***> wrote: ﻿ Yeah, this is a known issue. As you said, came from the update to 1.16. It sure is annoying but it is making a lot more people talk in global chat, and more people are using the /party feature. I feel more connected, it is annoying but not the worst bug to ever exist on EMC. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No idea, I'm sure it will be as it isn't intentional and something they can repair. Just gotta be patient I suppose.
