### ISSUE TITLE
Fixing Unattainable Block Problem

### ISSUE THREAD

**Issue by GingerThanosShrek** [EarthMC/Issue-Tracker#1328]
There are certain resources on this server that are very annoying to get and just make it super hard for builders to use certain blocks in their builds. With this problem, builders have a harder time building as many blocks are extremely hard to get in bulk, or are running out in the areas where they once were in the 3 year old map.

A solution to this is:
Enabling villager trades for only stone masons 
Doing this would give people something to do with their emeralds, and let builders get blocks that they are desperate of (bricks, quartz, terracotta) 
This would not 'break the economy", like the other villager types do (because they sell enchanted books etc.) My idea would only help builders make cooler builds, and give a value to emeralds, as well as let people be able to use bricks in buildings again. 
Also builders can spend more time on actually building instead spending hours looking for or paying crazy prices for hard to find building blocks

Please consider this <3 <3 <3

**Comment by shirazmatas** [comment]
Please follow format and I will reopen.
