### ISSUE TITLE
[RITUAL] [TRANSMUTATION] CHORUS FLOWER!! 

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1329]
![image](https://user-images.githubusercontent.com/46580909/110447264-0dca3880-808e-11eb-92bf-6e6057b9f6ce.png)

Brain Coral, for the knowledge of how it is to grow itself! Bubble choral, for it's hard husk which shall contain it's being!
End rods, and white mushroom blocks for it's stems and inner stalks!
Magenta concrete, for the hard seedling in the center!
An enchanted Gold Apple as it's host, and a rare vial of Essence of End to complete it's transformation!
I offer these materials to the void, so that it may yield me but 1 singular Chorus Flower!
Should you accept this sacrafice, the chest is at x: 29623 , z:-16522 , y:27
IGN: _o_Toast_o_

Nowhere's Witchking awaits you generosity and alchemical understanding.

**Comment by GingerThanosShrek** [comment]
Yes, give him the one chorus fruit that he wants so that he can eat it then it goes away ;P

**Comment by BunbunToast** [comment]
> Yes, give him the one chorus fruit that he wants so that he can eat it then it goes away ;P

FLOWER, IMBECILE. CHORUS FLOWER.

**Comment by shirazmatas** [comment]
Please follow format and I will reopen.
