### ISSUE TITLE
[BUG] Smh my town was created without name.

### ISSUE THREAD

**Issue by alekxeyuk** [EarthMC/Issue-Tracker#133]
So i created town named Komsomolsk,
but it smh bugged and now i have no name town, pls restore its name - Komsomolsk
![image](https://user-images.githubusercontent.com/9300326/48413433-79888900-e793-11e8-9d09-35f70de5504e.png)

**Comment by KarlOfDuty** [comment]
wtf

**Comment by KarlOfDuty** [comment]
And also this is for server wide issues, not personal ones, make a support ticket instead.
