### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Syko-G** [EarthMC/Issue-Tracker#1331]
There are huge issues with lag on the server right now and im gonna try offer a couple of solutions.

1. Towns where anyone hasnt come online to this server in 2 weeks can be removed to prevent lag.

2. Restart the server occasionally.

3. Now i dont know the solution to this but I believe that the queue causes more lag than the actual server. so it might be better to make the spawn more basic.

And thats about it so i hope this helps the server out

**Comment by jkmartindale** [comment]
>  the queue causes more lag than the actual server

The queue is actually a separate server entirely, which is why everyone gets kicked to the queue when the Towny server crashes instead of being completely disconnected from a server

**Comment by shirazmatas** [comment]
Please follow format and I will reopen when edited
