### ISSUE TITLE
[Plugin][Feature] New Ways to Obtain Mending

### ISSUE THREAD

**Issue by sage-blue** [EarthMC/Issue-Tracker#1332]
As of now, the only way to obtain mending books is to randomly receive them from a vote crate. IMO there needs to be a way to make them/ grind for them. I suggest the following solutions:
-MendingEnchant: This is a plugin that allows mending enchants to be obtained through an enchantment table. It is configurable and mending can be made as rare as desired. https://dev.bukkit.org/projects/mendingenchant
-Fishing Loot: In vanilla Minecraft you can receive mending books and gear as fishing loot. For some reason it has been disabled on EMC. An easy way to make mending accessible but still have it retain some of its current value would be to simply 
enable mending loot from fishing.
-Villager Trading: this would be the easiest solution but Fix said no LOL.

**Comment by jkmartindale** [comment]
+1 for mending from fishing. This was suggested in #1177 but inexplicably closed.

**Comment by shirazmatas** [comment]
Please follow format and reopen
