### ISSUE TITLE
[Feature] Some suggestions about fishing drops

### ISSUE THREAD

**Issue by BreachDGates** [EarthMC/Issue-Tracker#1333]
### Is your feature request related to a problem? Please describe.
Fishing has been nerfed so hard over the years. Fishing drops are now default ones, however they were customized by Fix or the admins before the big update in February 2021. This is not a coherent thing. The music disc economy is ruined because they are not obtainable anymore. Nautilus shells (new fishing drop) are useless without a Heart of the Sea.

Here are 5 suggestions to buff Fishing in decreased order of importance. Choose which ones you prefer to be added.

### Describe the solution you'd like
Suggestion #1: Enable music discs as they used to be before the last update. Disable Pigstep to maintain its rarity, but also Cat and 13 which are worthless. The new McMMO update was not meant to work on EMC, a server where there is an economy about music discs and where you can't let a skeleton hit a creeper to get them (mobs don't spawn). Now you get netherite gear instead of discs, however this is not a good change at all. Music discs are rarer. Disable netherite gear.

Suggestion #2: Only enable the books you can't obtain from enchanting as fishing drops. The chance of getting an enchanted book from fishing at level 1000+ is 0,56%, unfortunately you can get any useless book as well. By removing obtainable enchants, you will have a 0,14% chance of finding Mending, Frost Walker II, Curse of Vanishing, Curse of Binding, which are slighly less common than finding a "Mythic" item (Netherite gear post update, music discs pre update). It would take approximately 2 hours to get Mending from fishing at 20 TPS.

Suggestion #3: Swap the rarity of golden gear and diamond gear. Put diamond gear in the "Uncommon" tier and golden gear in the "Legendary" tier. For players with above level 1000 fishing it would be easier to get 5g and golden armor + items, which can be sold for decorative purposes. Doesn't really make sense to find more diamonds on a server where gold is the rare item for experienced fishermen, and to make it worse, it doesn't make sense for mid-level players (3,5% chance of "Uncommon" drops which include gold) to obtain more gold than max leveled ones (1,5% chance).

Suggestion #4: Enable gold and netherite salvaging

Suggestion #5: Enable Heart of the Sea as a new drop in the rarest tier "Mythic", if music discs are not going to come back. 0,025% chance of finding one with the current drops, 10 times rarer than every music disc combined before the update.

### Additional context
Some McMMO fishing drops don't really make sense on EMC (diamonds being in a higher rarity tier than gold, music disc removal, uselessness of nautilus shells, finding _every_ enchanted book on a server where books and exp bottles are easy to obtain)

A new configuration file for fishing drops was created 3 months ago by the McMMO creator. From "treasures.yml" to "fishing_treasures.yml".
https://github.com/mcMMO-Dev/mcMMO/blob/master/Changelog.txt
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/fishing_treasures.yml

**Comment by JaVolimKatarinu** [comment]
I support this suggestion. 
Music discs were the ultimate goal of every fisherman. That is why I at least fished. 

Books in fishing are a good thing. I would maybe lower the chance to be safe they don't flood the economy. The goal isn't to create a lot of "special" ench books, it is just to enable obtaining them. They should still be extraordinarily rare. If those numbers seem okay with Admins, then go. But lower the chance, it's the safer decision. 

Gold gear vs diamond gear, I don't have a comment on that. But it is somehow weird fishing 5-10 gold ingots... In my opinion, gold ingots should be disabled and diamonds might be more common cause it's cheap and there is a lot of it. 

Salvaging- please bring it back. Burning a piece of gold armor for a nugget is demoralizing. 

When it comes to Heart of Sea, I think that server might thrive with them. As the map is kinda overpopulated, HoS would enable players to start creating deep ocean towns. It would be cool and will give players a more usable living place. It's not just drying up the ocean floor and creating a town, it is about enabling more space for players. Plus they could be cool decorations for towns.

All in all, I support this suggestion and I hope it will come to the server. Fix please bless us. ;)

**Comment by DeadGlamour** [comment]
This is very based, fishing has basically only been used to get a high shake chance, hopefully this will add more uses.

**Comment by BreachDGates** [comment]
> I support this suggestion.
> Music discs were the ultimate goal of every fisherman. That is why I at least fished.
> 
> Books in fishing are a good thing. I would maybe lower the chance to be safe they don't flood the economy. The goal isn't to create a lot of "special" ench books, it is just to enable obtaining them. They should still be extraordinarily rare. If those numbers seem okay with Admins, then go. But lower the chance, it's the safer decision.
> 
> Gold gear vs diamond gear, I don't have a comment on that. But it is somehow weird fishing 5-10 gold ingots... In my opinion, gold ingots should be disabled and diamonds might be more common cause it's cheap and there is a lot of it.
> 
> Salvaging- please bring it back. Burning a piece of gold armor for a nugget is demoralizing.
> 
> When it comes to Heart of Sea, I think that server might thrive with them. As the map is kinda overpopulated, HoS would enable players to start creating deep ocean towns. It would be cool and will give players a more usable living place. It's not just drying up the ocean floor and creating a town, it is about enabling more space for players. Plus they could be cool decorations for towns.
> 
> All in all, I support this suggestion and I hope it will come to the server. Fix please bless us. ;)

Enchanted books are already enabled in the Legandary tier and the chance of finding one is 0,56% at level 1000+, however it's so disappointing to get Riptide I, Smite II, Blast Protection I and similar enchantments. Even any level 30 enchantment is something bad to find since you find 1 book every 20-30 minutes. I personally never got Mending from fishing yet, I have no idea if it's enabled, however I got Frost Walker II more than once

You always get 5 gold ingots, never 10. Super low chance, almost 3 times rarer than obtaining a "Mythic" item, but then again it's easier for someone who is level 400-900 to get gold than someone with a maxed level

**Comment by IAmUnStTV** [comment]
Why would it be just music discs? Surely Mending was available via fishing too?
________________________________

**Comment by jkmartindale** [comment]
> Surely Mending was available via fishing too?

Mending is a drop with vanilla fishing mechanics, but vanilla drops are disabled by default when McMMO is installed. Vanilla drops and Mending books have never been enabled for fishing on EarthMC (or at least not for the past few years).

**Comment by IAmUnStTV** [comment]
Oooohhhh
________________________________

**Comment by shirazmatas** [comment]
yeah because vanilla disabled normal drops its fair to add back normal drops to loot table. Using this https://mcmmo.fandom.com/wiki/Fishing please state what rarity each suggestion should be in a list.

**Comment by DizzyDesert** [comment]
very cool, this would allow the market to be slowly saturated with mending; a viable way for the return of villagers

**Comment by WumianTony** [comment]
As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.

**Comment by BreachDGates** [comment]
> As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.

In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.

What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)

2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.

3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".

4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.

5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.

6. Revert Shake to what it was last year and the beginning of 2021

**Comment by BreachDGates** [comment]
> yeah because vanilla disabled normal drops its fair to add back normal drops to loot table. Using this https://mcmmo.fandom.com/wiki/Fishing please state what rarity each suggestion should be in a list.

old drops vs new suggested drops

![Screenshot_3037](https://user-images.githubusercontent.com/61973209/130316239-e332cb8e-4a8d-4bbc-b923-3eb8cfa8ff13.png)
![Screenshot_3038](https://user-images.githubusercontent.com/61973209/130316240-978862ff-3172-4c25-93b5-1dcdfe881bdd.png)

**Comment by WumianTony** [comment]
> > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> 
> In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> 
> What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> 
> 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> 6. Revert Shake to what it was last year and the beginning of 2021

btw, the uncommon tier is not the 2nd common one, but the most frequent one.

**Comment by BreachDGates** [comment]
> > > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> > 
> > 
> > In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> > It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> > What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> > 
> > 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> > 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> > 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> > 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> > 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> > 6. Revert Shake to what it was last year and the beginning of 2021
> 
> btw, the uncommon tier is not the 2nd common one, but the most frequent one.

I meant Common > Uncommon > Rare > Epic > Legendary > Mythic
2nd most frequent if you've just started, 4th most frequent tier at level 1000+

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/skillranks.yml

**Comment by WumianTony** [comment]
> > > > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> > > 
> > > 
> > > In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> > > It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> > > What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> > > 
> > > 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> > > 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> > > 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> > > 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> > > 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> > > 6. Revert Shake to what it was last year and the beginning of 2021
> > 
> > 
> > btw, the uncommon tier is not the 2nd common one, but the most frequent one.
> 
> I meant Common > Uncommon > Rare > Epic > Legendary > Mythic
> 2nd most frequent if you've just started, 4th most frequent tier at level 1000+
> 
> https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/skillranks.yml

oh, I got it. but what about "(there are no mobs in this server)", is that about canceling shake?

**Comment by BreachDGates** [comment]
> > > > > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> > > > 
> > > > 
> > > > In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> > > > It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> > > > What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> > > > 
> > > > 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> > > > 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> > > > 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> > > > 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> > > > 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> > > > 6. Revert Shake to what it was last year and the beginning of 2021
> > > 
> > > 
> > > btw, the uncommon tier is not the 2nd common one, but the most frequent one.
> > 
> > 
> > I meant Common > Uncommon > Rare > Epic > Legendary > Mythic
> > 2nd most frequent if you've just started, 4th most frequent tier at level 1000+
> > https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/skillranks.yml
> 
> oh, I got it. but what about "(there are no mobs in this server)", is that about canceling shake?

It's about not having any creepers being killed by skeletons to get music discs. Old players from 2018 probably had some music discs from killed creepers. The only way to obtain music discs since when I first joined until February 2021 (nether update and McMMO update) was from fishing. Now they're unobtainable.

**Comment by WumianTony** [comment]
> > > > > > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> > > > > 
> > > > > 
> > > > > In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> > > > > It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> > > > > What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> > > > > 
> > > > > 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> > > > > 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> > > > > 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> > > > > 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> > > > > 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> > > > > 6. Revert Shake to what it was last year and the beginning of 2021
> > > > 
> > > > 
> > > > btw, the uncommon tier is not the 2nd common one, but the most frequent one.
> > > 
> > > 
> > > I meant Common > Uncommon > Rare > Epic > Legendary > Mythic
> > > 2nd most frequent if you've just started, 4th most frequent tier at level 1000+
> > > https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/skillranks.yml
> > 
> > 
> > oh, I got it. but what about "(there are no mobs in this server)", is that about canceling shake?
> 
> It's about not having any creepers being killed by skeletons to get music discs. Old players from 2018 probably had some music discs from killed creepers. The only way to obtain music discs since when I first joined until February 2021 (nether update and McMMO update) was from fishing. Now they're unobtainable.

got that, I'll translate the whole things to my groups of fishers, one of them are able to contact with fix, and I'll let him post this page to fix.

**Comment by WumianTony** [comment]
> > > > > > > As the #2 fisher, I highly agree with Breach. (ps: netherite stuff should be maintained, and they should be able to repair through McMMO) What he mentioned is perfectly the same as what I think.
> > > > > > 
> > > > > > 
> > > > > > In the last months there have been more nerfs (direct and indirect) for Fishing, especially at higher levels. Now there is 1 shake chance for every level from 150+, also nautilus shells (the only good fishing drop) are worthless due to the merchant trade which sells 32 of them for 64g. There is still the "more gold and golden items for mid levels" thing since golden gear is not in a good tier (Uncommon being the 2nd most common tier). Salvaging leather armor is more profitable than salvaging diamond armor.
> > > > > > It's not worth to fish anymore. It's almost as good to be level 150 than level 1000 or more.
> > > > > > What do you think of this idea? Really similar to what I suggested before, except that the following points _as a whole_ is my new suggestion
> > > > > > 
> > > > > > 1. Changes to the Mythic tier: Remove all netherite gear and add music discs (except Cat, 13, Pigstep). Add a netherite ingot too. At this point it's more worth to catch an ingot than broken or badly enchanted netherite gear. Music discs will become obtainable again (there are no mobs in this server)
> > > > > > 2. Move "5 diamonds" from Epic to Legendary tier, then swap all the diamond gear with golden gear. Now the "5 gold ingots" drop is more rewarding and easier to get as you level up. Now golden gear is in the Legendary tier and diamond gear is in the Uncommon tier.
> > > > > > 3. Enable gold salvaging at a reduced rate: maximum 1g for items, maximum 2g for armor. If it's too easy to earn gold, nerf the "5 gold ingots" drop to "3 gold ingots".
> > > > > > 4. It's already too hard to obtain enchanted books, why would you fish a useless one which happens almost all the time? Whitelist Mending, Frost Walker II, Curse of Vanishing, Curse of Binding only.
> > > > > > 5. Enable rain or make the server 20 TPS somehow. Everything is slow motion but we're all used to the lag.
> > > > > > 6. Revert Shake to what it was last year and the beginning of 2021
> > > > > 
> > > > > 
> > > > > btw, the uncommon tier is not the 2nd common one, but the most frequent one.
> > > > 
> > > > 
> > > > I meant Common > Uncommon > Rare > Epic > Legendary > Mythic
> > > > 2nd most frequent if you've just started, 4th most frequent tier at level 1000+
> > > > https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/skillranks.yml
> > > 
> > > 
> > > oh, I got it. but what about "(there are no mobs in this server)", is that about canceling shake?
> > 
> > 
> > It's about not having any creepers being killed by skeletons to get music discs. Old players from 2018 probably had some music discs from killed creepers. The only way to obtain music discs since when I first joined until February 2021 (nether update and McMMO update) was from fishing. Now they're unobtainable.
> 
> got that, I'll translate the whole things to my groups of fishers, one of them are able to contact with fix, and I'll let him post this page to fix.

I've just got another idea. it is good to count the number of materials of gold repairing and salvaging with gold nuggets instead of ingots.

**Comment by JaVolimKatarinu** [comment]
Please stop with quotes.. If you are gonna quote an answer, please remove old quotes. Some unwritten rule of the internet is 5 quotes per post.. 
Otherwise, quote only the relevant part of the post you are talking about.
