### ISSUE TITLE
[BUG] Carpet duping is not working

### ISSUE THREAD

**Issue by BreachDGates** [EarthMC/Issue-Tracker#1334]
### Server
EMC Towny

### Describe the bug
You can't duplicate carpets since the new update. Probably because the "paper.yml" file got updated and left it unedtied.

### To Reproduce
1. Place a carpet on [this](https://www.youtube.com/watch?v=38xRnw1qcbI) machine
2. The carpet will be thrown away without being duplicated

### Expected behavior
Carpets are supposed to be duplicated as before February 2021. 

### Screenshots
Piston duplication is now disabled by default
https://cdn.discordapp.com/attachments/823973836290129943/824923137623457802/Screenshot_1846.png

### Additional context
Fewer people are making maparts because they don't have enough carpets to place.

**Comment by IAmUnStTV** [comment]
This is most likely a bug *fix*, not a bug. Duplicating in Minecraft is not supposed to happen, and while some servers *do* allow this, I'm not so sure about EarthMC. You can correct me on that, but maybe EarthMC staff have decided to turn this off [to minimise server lag].

**Comment by gabeeebaby** [comment]
Instead of allowing carpet dupers that can cause lag (probably very little tho), they could just add custom crafting recipes that 1 carpet = 2 carpet, allowing infinite carpets, without the lag.

**Comment by geobeeblaster** [comment]
> This is most likely a bug _fix_, not a bug. Duplicating in Minecraft is not supposed to happen, and while some servers _do_ allow this, I'm not so sure about EarthMC. You can correct me on that, but maybe EarthMC staff have decided to turn this off [to minimise server lag].

It was a bug fix in a plugin, but it wasn't done intentionally by the server admins, instead, it was done in one of the plugins.

**Comment by FenZenyatta** [comment]
Add a carpet duplication recipe please?

**Comment by CorruptedGreed** [comment]
Solution presented in next changelog
