### ISSUE TITLE
Helper Role

### ISSUE THREAD

**Issue by Conmqn** [EarthMC/Issue-Tracker#1335]
This is a role idea for new staff members to have when added without being called mods which can be misleading to new players that don't know they don't have access to all perms regular moderators do. It will service as training for the position mod and will work on tickets and get the chat rules enforced. The role is just a starter role for new staff members to see if they are ready and want to do the work of mods.

**Comment by IAmUnStTV** [comment]
Alternative role: "Mod-in-training"

**Comment by shirazmatas** [comment]
Please follow format and reopen
