### ISSUE TITLE
store staff

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1337]
As of right now only premium players may use the command /qs staff to add staff to a shop I request this be changed to allow all players use this as I believe it will help the servers player base have shops that can have many operators.

**Comment by 10op10** [comment]
This would make fix lose sales, keep dreaming LOL

**Comment by yankees88888g** [comment]
Ik but still need to put this out here.

**Comment by ByeMC** [comment]
> This would make fix lose sales, keep dreaming LOL

Sales to buy... what? At least make it a $1 purchase or something, like how the queue works.
________________________________

**Comment by geobeeblaster** [comment]
![image](https://user-images.githubusercontent.com/62677716/114653254-a0757d00-9cb5-11eb-89b1-1062949da8af.png)
He is seriously considering this, so it's not as bad as it could be.

**Comment by Taffffy** [comment]
> ![image](https://user-images.githubusercontent.com/62677716/114653254-a0757d00-9cb5-11eb-89b1-1062949da8af.png)
> He is seriously considering this, so it's not as bad as it could be.

I'm more concerned that 25 people voted yes..

**Comment by yankees88888g** [comment]
Bruh wtf

**Comment by shirazmatas** [comment]
Please follow format or this will be closed
