### ISSUE TITLE
[BUG] Furnaces don't seem to be protected by town claims.

### ISSUE THREAD

**Issue by Synargle** [EarthMC/Issue-Tracker#134]
**Server**
Terra Nova

**Describe the bug**
We had an incident of players stealing from a furnace despite the plot permissions. (Ticket-2136)

**To Reproduce**
Have some players access a furnace in a privately-owned plot.

**What's supposed to happen**
The furnace should be protected and unusable.

**Comment by KarlOfDuty** [comment]
Furnaces are, burning furnaces are not.

**Comment by EchoOcelot** [comment]
Will the players who had this happen to them be able to get their gold/ores back?

**Comment by KarlOfDuty** [comment]
Probably, make a support ticket.

**Comment by EchoOcelot** [comment]
Ok thx, it’s ticket 2136
