### ISSUE TITLE
Illegal Mapart Standards

### ISSUE THREAD

**Issue by imableeblob** [EarthMC/Issue-Tracker#1340]
This Github issue is being created because of the unbalanced enforcement of illegal map arts. 

1.  I understand the staff teams reasoning for banning certain map arts. As much as it would be nice to have an unregulated market, Full nudity and explicit sexual content is against Minecraft's EULA. See here: [EULA](https://account.mojang.com/documents/minecraft_eula) (Just control+F and search for "Illegal" to find the correct section regarding this information). 
2.   The EULA only states "porn", I personally believe the staff team has over moderated the map art community and has banned many non-porn pieces.  

See Below:

[Banned 1#](https://cdn.discordapp.com/attachments/743017606369247283/766951215938011156/Ahegao6.png)
[Banned 2#](https://user-images.githubusercontent.com/67532219/114961130-09800080-9e2e-11eb-8ed1-f7090839db73.png)
[Banned 3#](https://cdn.discordapp.com/attachments/743017606369247283/766948885917728768/Ahegao1.png)
[Banned 4#](https://cdn.discordapp.com/attachments/743017606369247283/766946777575981056/2020-10-17_02.44.10.png)
[Banned 5#](https://cdn.discordapp.com/attachments/743017606369247283/766951338553638942/Ahegao8.png)
[Banned 6#](https://cdn.discordapp.com/attachments/743017606369247283/766951373774127124/Ahegao9.png)
[Banned 7#](https://cdn.discordapp.com/attachments/743017606369247283/766951589935185930/Ahegaomaybe2.png)
[Banned 8#](https://cdn.discordapp.com/attachments/743017606369247283/766955033690243072/unknown.png)
[Banned 9#](https://cdn.discordapp.com/attachments/743017606369247283/828489737525526548/unknown.png)
[Banned 10#](https://cdn.discordapp.com/attachments/743017606369247283/757728907574116422/unknown.png)
[Banned 11#](https://cdn.discordapp.com/attachments/743017606369247283/757728947000836170/unknown.png)
[Banned 12#](https://cdn.discordapp.com/attachments/743017606369247283/766949964555223060/Ahegao3.png)

There are many more map arts that will fall under this list. Some in this list have a disputed legality. **_That is the issue here.*_* One mod will say a map is illegal and you will get warned for it. Even though dozens of mods may have walked past and had no issue with it. We need a base line here and no more stupid mod interpretations. 

3.   Maps with over sexualization (Woman in tight bikinis or thongs) are currently banned. I agree with that decision. But maps that show no cleavage and no obvious explicit material should not be banned. For example. "Nice Cock" is a meme and the map art is posted all over the server. You can find this meme all over the internet and **on Google**. Recently a staff member claims "this was banned" even though numerous other staff members have contradicted this statement.  **_If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?_** (FYI they also deem Ahego, non explicit content) (See below)

4.  Many "Ahego" maps are banned because "simply because someone said they are sexually explicit". With that logic I could say a map art of a grapefruit is "something else".... That does not make it sexual explicit. [Vice News article on Ahego.](https://www.vice.com/en/article/7kz7be/anime-porn-fetish-ahegao-hentai-censorship) This article talks about Ahego and how its creation was to circumvent Japanese pornography laws. _**That right there should be enough to show that this is not pornography**_. In other words, Ahego is not defined as explicit pornography in Japan, Its not deemed explicit by Google, and not deemed explicit under US government pornography standards.

**Comment by Chotobits** [comment]
I am going to have to agree with all of this. When I first started on emc the laws in place were fine, they would ban anything deemed overly sexual which is a good bar to set. Overtime moderators without the consent let alone a minority of approval from the community began to vaguely punish map art makers and sellers who had theses maps.

**Comment by CorgiPaws** [comment]
All of the above. Whatever happens, the rules need to be made clear. If staff are not concrete on what counts as legal or illegal how are players supposed to navigate map art rules? 

Specificity with rulings around map art is crucial to avoid vague punishments that discourage creativity.

**Comment by captainb4** [comment]
Love that you are doing something about this ty bleepblob

**Comment by shirazmatas** [comment]
1. Please follow format
2. Post rule suggestions on the rules github here https://github.com/EarthMC/EarthMC.net/issues
