### ISSUE TITLE
[Mechanic] Illegal Map Art

### ISSUE THREAD

**Issue by imableeblob** [EarthMC/Issue-Tracker#1342]
### Is your feature request related to a problem? Please describe.

This Github issue is being created because of the unbalanced enforcement of illegal map arts. 

1.  I understand the staff teams reasoning for banning certain map arts. As much as it would be nice to have an unregulated market, Full nudity and explicit sexual content is against Minecraft's EULA. See here: [EULA](https://account.mojang.com/documents/minecraft_eula) (Just control+F and search for "Illegal" to find the correct section regarding this information). 
2.   The EULA only states "porn", I personally believe the staff team has over moderated the map art community and has banned many non-porn pieces.  

See Below:

[Banned 1#](https://cdn.discordapp.com/attachments/743017606369247283/766951215938011156/Ahegao6.png)
[Banned 2#](https://user-images.githubusercontent.com/67532219/114961130-09800080-9e2e-11eb-8ed1-f7090839db73.png)
[Banned 3#](https://cdn.discordapp.com/attachments/743017606369247283/766948885917728768/Ahegao1.png)
[Banned 4#](https://cdn.discordapp.com/attachments/743017606369247283/766946777575981056/2020-10-17_02.44.10.png)
[Banned 5#](https://cdn.discordapp.com/attachments/743017606369247283/766951338553638942/Ahegao8.png)
[Banned 6#](https://cdn.discordapp.com/attachments/743017606369247283/766951373774127124/Ahegao9.png)
[Banned 7#](https://cdn.discordapp.com/attachments/743017606369247283/766951589935185930/Ahegaomaybe2.png)
[Banned 8#](https://cdn.discordapp.com/attachments/743017606369247283/766955033690243072/unknown.png)
[Banned 9#](https://cdn.discordapp.com/attachments/743017606369247283/828489737525526548/unknown.png)
[Banned 10#](https://cdn.discordapp.com/attachments/743017606369247283/757728907574116422/unknown.png)
[Banned 11#](https://cdn.discordapp.com/attachments/743017606369247283/757728947000836170/unknown.png)
[Banned 12#](https://cdn.discordapp.com/attachments/743017606369247283/766949964555223060/Ahegao3.png)

There are many more map arts that will fall under this list. Some in this list have a disputed legality. **_That is the issue here.*_* One mod will say a map is illegal and you will get warned for it. Even though dozens of mods may have walked past and had no issue with it. We need a base line here and no more stupid mod interpretations. 

3.   Maps with over sexualization (Woman in tight bikinis or thongs) are currently banned. I agree with that decision. But maps that show no cleavage and no obvious explicit material should not be banned. For example. "Nice Cock" is a meme and the map art is posted all over the server. You can find this meme all over the internet and **on Google**. Recently a staff member claims "this was banned" even though numerous other staff members have contradicted this statement.  **_If Google, a multibillion dollar company that uses safe search algorithms to remove porn and sexual content from its image searches, deems this content "Safe" then why cant EMC?_** (FYI they also deem Ahego, non explicit content) (See below)

4.  Many "Ahego" maps are banned because "simply because someone said they are sexually explicit". With that logic I could say a map art of a grapefruit is "something else".... That does not make it sexual explicit. [Vice News article on Ahego.](https://www.vice.com/en/article/7kz7be/anime-porn-fetish-ahegao-hentai-censorship) This article talks about Ahego and how its creation was to circumvent Japanese pornography laws. _**That right there should be enough to show that this is not pornography**_. In other words, Ahego is not defined as explicit pornography in Japan, Its not deemed explicit by Google, and not deemed explicit under US government pornography standards.
### Describe the solution you'd like

Map Art rules need to be reformed in these ways:

- Full nudity and overly sexual mapart with explicit materials stay banned
- Any mapart outside of this category should be deemed legal.
- Ahego map arts are deemed legal as they are not deemed explicit by numerous credible sources. 
- A clear and consise list of banned maps are created and can be referenced by staff. Right now mods go off of judgement and can be biased in some cases. I have had my own legal maps stolen by mods who "thought" they were illegal. I know some maps are recorded in a list but this is far from complete.

### Additional context

Idk why deleting my GitHub request because I did not include the titles is necessary.. #1340 

Players can be homophobic on EMC and not get banned/warned/muted/ and often verbally warned by staff.  I have reported players for homophobic slang and harassments and mods have said they cannot do anything. This is against Minecraft's EULA. Clearly staff don't care so why would looking at a Luigi butt be offensive and a overinterpretation of Minecraft's EULA for pornography be needed?

**Comment by imableeblob** [comment]
Also #1334 
Carpet Duping needs to be re-enabled.

**Comment by jkmartindale** [comment]
> Idk why deleting my GitHub request because I did not include the titles is necessary.. #1340

You're suggesting rule changes for the most part, so your previous issue might've been closed to encourage you to post again in the [EarthMC.net repository](https://github.com/EarthMC/EarthMC.net), which deals with rule changes and website content.

imo that shouldn't be necessary because shiraz can just [transfer the issue](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) to the other repo in 4 clicks.

**Comment by imableeblob** [comment]
> > Idk why deleting my GitHub request because I did not include the titles is necessary.. #1340
> 
> You're suggesting rule changes for the most part, so your previous issue might've been closed to encourage you to post again in the [EarthMC.net repository](https://github.com/EarthMC/EarthMC.net), which deals with rule changes and website content.
> 
> imo that shouldn't be necessary because shiraz can just [transfer the issue](https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) to the other repo in 4 clicks.


I have closed this one and moved it myself. The Github auto message redirected me to this side so I did the same thing. And yes he could have

**Comment by imableeblob** [comment]
New Issue: https://github.com/EarthMC/EarthMC.net/issues/203
