### ISSUE TITLE
[BUG] Vanishing Cows

### ISSUE THREAD

**Issue by cordaxx** [EarthMC/Issue-Tracker#1345]
### Server
Main EarthMC.net Server

### Describe the bug
I originally had 3 cows. 1 cow had already despawned when I arrived. The last 2 were standing close together against a wall and I saw them disappear one after another, a few seconds apart.

### To Reproduce
1. Create a cow enclosure and introduce cows.
2. Watch them look into your eyes then spontaneously vanish.
3. Cry.

### Expected behavior
Cows really shouldn't vanish. Unless these cows have permanent potion of invisibility effect. In that case, they would be very valuable to the right buyer. 

### Additional context
The enclosure is underground with one corner being the cave wall and the other being fence. The inside enclosure is 5x7. Nothing else was inside the enclosure.

**Comment by yankees88888g** [comment]
This is a bug with the anti lag. You can get your mob back by creating a ticket on the EMC support.

**Comment by Warriorrrr** [comment]
Mob refunds are handled on the [support Discord](https://discord.gg/EZBYmpp).
