### ISSUE TITLE
[BUG] Allie Kill

### ISSUE THREAD

**Issue by ltsCheeks** [EarthMC/Issue-Tracker#1346]
### Server

earthmc.net

### Describe the bug

So I don't know if this counts as a bug but I think so, so someone took me into a plot they owned under the river at /n spawn Britain, and they blocked me into a room, but suddenly they turned PVP on, on their plot and started hitting me, in an instant reaction even though it said not to, I logged out, I logged back in around right now as I'm sending this, all of my stuff is gone, I didn't know that that would happen as there was so warning that you would lose items, I logged out also bc I knew I would lose as they were full netherite, however, they are apart of an allied nation of mine, and someone told me that they shouldn't be able to kill me if I am in an allied nation, if someone could please help me with this, that would be great.
I believe their name was _joe76.

### To Reproduce

1. Make it so you can just turn PVP on, on your plot at random
2. Make it so allies can't kill each other (if that's not already a thing)
3. Make it so that you don't lose your items when looking out in a battle.

### Expected behavior

I expected them to not kill me, and also for me to not lose all my items (including items I bought and stuff I worked hard for)

**Comment by ltsCheeks** [comment]
I really need someone to help me with this

**Comment by gabeeebaby** [comment]
There is a plugin that kills you if you log out during combat, to prevent an easy out during pvp. Don't carry your valuables with you, keep them in your ender chest if you don't want to lose them. It's not against the rules for someone to kill you.

**Comment by jkmartindale** [comment]
This is all intended behavior.

While Towny defaults (afaik) prevent friendly fire between players in allied nations, the dynamic on EarthMC is different and friendly fire is intentionally enabled (outside of mcMMO parties). Players can only teleport to allied nations, so the vast majority of players are in nations that are allied with each other, and disabling friendly fire would prevent most PVP even in PVP arenas.

Clearing your inventory if you log out during combat is a specific feature added to EarthMC to discourage combat logging, and last I checked a warning appears saying that whenever someone starts the combat timer by attacking you in a PVP zone.

**Comment by jkmartindale** [comment]
I think we've all been there man, I've lost like 300g worth of stuff in a matter of seconds a couple times by now. That's just part of the survival multiplayer experience.

**Comment by sndor** [comment]
U can't trust anyone one this server, even if u think u can. A coward would quit the server after getting killed/scammed, you honestly should take it as a learning experience.
