### ISSUE TITLE
Enable villagers with some tweaks

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1347]
### Is your feature request related to a problem? Please describe.

Villagers are currently disabled because the game gets un balanced without them.
### Describe the solution you'd like

My solution is to have villager price reduction be disabled. And changing the emeralds to gold it self to the villager. Ex you have to trade in 30 gold to be able to get mending with no way to reduce the price.

**Comment by CorruptedGreed** [comment]
Villagers on Nova are deprecated
