### ISSUE TITLE
A way to obtain tipped arrows/dragon breath

### ISSUE THREAD

**Issue by theJavaWolf** [EarthMC/Issue-Tracker#1348]
### Is your feature request related to a problem? Please describe.
I feel like EarthMC combat is missing on some thrill concerning tipped arrows.
They do exist from past Villagertrades but not anymore.

### Describe the solution you'd like
We could have a custom recipe(breweing or crafting),
where you would be able to make Dragon Breath out of a Dragonhead
(as they have no real use for Dragonheads at the moment).

### Additional context
You need one Dragonbreath to create 8 arrows, so we could make out of one Dragon Head 3 pieces of Dragon Breath.
This would result in 24 Arrows per Head.
I think that would not be too much, but still add some spice to the combat of the server.

**Comment by gabeeebaby** [comment]
I don't think this would be fair. Dragon heads are won through mystery crates, which are paid for with real money. Many think that being able to pay real money for a cosmetic item is unfair in itself, and introducing a in game use would make this even more unfair.

**Comment by theJavaWolf** [comment]
Hm, I did not know that Dragonheads were obtained by real world currency.
Then this will not be a good solution of course.
But you could add Dragon Breath at a high level of alchemy, like as last pot maybe made with nether crystals.
That might be a fair and balanced solution.

As for example resistance exists but only few actually have resistance pots cause it is at a very high alchemy level.

Or if custom alchemy potions are not possible, just have a very expensive crafting recipe for example: by crafting the 9 last of the 12(if I am correct) mcmmo potions together.

**Comment by theJavaWolf** [comment]
I feel like Dragonbreath would really spice EMC pvp up by a LOT.
Everybody I talked to about this was like: "omg yeah!"
But somehow this issue gets like zero attention.
Maybe with the changed title now it will get more attention after a new comment here.

**Comment by QJWIN** [comment]
you can optain typed arrow into the n spawn godthab there is a shop and on the first floor you can buy all typed arrow :+1:

**Comment by theJavaWolf** [comment]
> you can optain typed arrow into the n spawn godthab there is a shop and on the first floor you can buy all typed arrow 👍

Most people already know that on EMC.
Still it is limited supply rn and too valuable to use it.
Also tipped arrows are not the only thing you could create with dragonbreath but also lingering pots...
Imagine it's use in pvp... it would be definatly a new thrill.

**Comment by Basically-Andrew** [comment]
I suggest you close this issue and create a new feature request on mcmmo's Github.

**Comment by AndrewCheedle** [comment]
Currently can be obtained through villager trades

**Comment by theJavaWolf** [comment]
> Currently can be obtained through villager trades

Don't believe we can get lingering potions though!
