### ISSUE TITLE
[Feature] Slimeball Custom Crafting Recipe

### ISSUE THREAD

**Issue by WeirdGamerAidan** [EarthMC/Issue-Tracker#1349]
### Is your feature request related to a problem? Please describe.

slime is getting very rare, making it hard and expensive to make builds using slime blocks or sticky pistons

### Describe the solution you'd like

A custom crafting recipe for slimeballs or modifying MCMMO to make slime come from dirt or something

### Additional context

this is what i'm thinking would be a good recipe for slimeballs:
![image](https://user-images.githubusercontent.com/83551080/116822998-464f3580-ab58-11eb-960f-00c686910fe3.png)

**Comment by gabeeebaby** [comment]
Slime is currently obtainable through the mcmmo excavation skill when you mine clay.

**Comment by WeirdGamerAidan** [comment]
> Slime is currently obtainable through the mcmmo excavation skill when you mine clay.

i am aware of this, but clay is starting to run out

**Comment by Basically-Andrew** [comment]
This could be a worthy crafting recipe addition, but I hope you understand that clay is commonly rolled back by staff, and there are still locations not as terraformed for clay as others. Also, if slime balls get to a limited point, merchants can trade slimeballs to players.
