### ISSUE TITLE
Villager comeback plan

### ISSUE THREAD

**Issue by BigDyna** [EarthMC/Issue-Tracker#1350]
### Is your feature request related to a problem? Please describe.
The villager comeback is a problem, because how do you manage something like villagers? 

### Describe the solution you'd like
Clear out any way of making librarian and Cleric villagers, they are the most overpowered, and could rip the economy in half, and my solution is either reworking villager trades, tweaking them to the point where they are still useful, just not overpowered. E.g: you could farm librarians for mending books, and that would lower mending prices by ALOT, to solve this, just simply either remove that trade or remove mending from the pool of items you could get from it. Another example would be the tool/blacksmiths. They make enchanted tools you could farm enchants for, giving you the almost perfect sword/pickaxe. How to solve this would be to change the enchantments or remove them entirely, just leaving the tools.

### Additional context
[Current villager trades](![image](https://user-images.githubusercontent.com/83775935/117327083-17caa680-ae47-11eb-860d-6184ea165260.png))

**Comment by WeirdGamerAidan** [comment]
my opinion is to raise the lowest possible price of enchanted books to like 15 or 20 emeralds from 5

**Comment by CorruptedGreed** [comment]
Reference #1347
