### ISSUE TITLE
[Feature] New players should be greeted with tutorial room

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#1351]
### Is your feature request related to a problem? Please describe.
New players lack the full grasp of how earthmc works and can often end up being scammed, tricked, get stuck, etc. The first time you join the server you see the same as someone who's been playing forever and there's a lack of easy to read information.

### Describe the solution you'd like
Hub should be changed so new players spawn inside a corridor with information about Earthmc such as everything listed here https://earthmc.fandom.com/wiki/FAQ_(Frequently_Asked_Questions)#The_EarthMC_Getting_Started_Page. New players should also be able to see it translated into popular earthmc languages

### Additional context
Approve this idea and I will look for a crew to translate and assemble this.

**Comment by gabeeebaby** [comment]
Maybe instead of an area in queue, just have all players be given a guide book in queue. It could also be added to the book that you get when you first join, in case there is no queue when they first join.

**Comment by CorruptedGreed** [comment]
We're working on a different approach of integrating a tutorial into the server rather than anything involving the hub
