### ISSUE TITLE
[Mechanic] New commands for New mods

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#1352]
### Is your feature request related to a problem? Please describe.
New mods are handicapped in their ability to learn and help by not being able to use spectator mode, /warn or /ban. 

### Describe the solution you'd like
Give New mods /warn /ban /gamemode spectator

### Additional context
Further limitations on /warn /ban and /gamemode spectator can be specified in staff channels as to tell new mods when they can use it.

**Comment by DasCodes** [comment]
Done.
