### ISSUE TITLE
What Is Being Done About Mending?

### ISSUE THREAD

**Issue by hydro78878** [EarthMC/Issue-Tracker#1353]
i would like to ask what is being done to resolve the mending book crisis? mending is unsustainable and will soon possibly be unobtainable due to its rarity or price and this is worrying due to it being an essential enchantment required for so much of your equipment.
what solution will be put in place to create a sustainable source of mending?

i would recommend creating a crafting recipe for it which would be complicated or expensive
another suggestion would be to have a relatively low chance for it to appear in the enchanting table, maybe something along the lines of a 1 in 20 chance.

**Comment by hydro78878** [comment]
> There are dozens, if not hundreds of double chests full of mending on the server, not even including all the mending gear. There are tons of people winning mending every day. It’s just a matter of people selling for more just because they can and hoarding it. Putting mending in enchanting tables would bring the price down to fewer than 5 gold, even if it was a 1 in 500 chance.

if there was this much mending on the server then clearly the prices shouldn't be as high as they are. even if you were right, is it really fair for an essential item such as mending to be out of reach for the general player base just because a few lucky people had some stored away?

**Comment by Basically-Andrew** [comment]
> if there was this much mending on the server, then clearly, the prices shouldn't be as high as they are.
Yet EarthMC is a "player run economy," so players can control certain economies, raising market prices how they wish.

**Comment by CorruptedGreed** [comment]
Wandering Traders addressed this.
