### ISSUE TITLE
[Plugin] Combat tag wall

### ISSUE THREAD

**Issue by Sakuuzo** [EarthMC/Issue-Tracker#1356]
Hi, this addition could solve an issue that many players complain about during pvp: claim hiding.  Being able to be safe so easily entering city claims during pvp clashes is really annoying, you can go pvp as if you were going to do your shopping at the supermarket and quietly enter a claim if things go wrong. This removes all the stakes of pvp clashes and city assaults and players can attack anyone without fear of dying because of this claim hiding mechanic.

The solution is to add to the "combat tag" a glass wall which is generated when the player in combat approaches an area where the pvp is off like on HCF server and prevents him from entering it while he is in combat. (this does not activate when the player enters claims with pvp enabled like a town with pvp toggled on)

Better than an explication, an exemple: https://www.youtube.com/watch?v=AnU1VsaquHA&ab_channel=Sakuzo

**Comment by yankees88888g** [comment]
Ewwww

**Comment by MineHero43** [comment]
I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.

Good idea, hope the staff consider it

**Comment by yankees88888g** [comment]
it will add lag just an fyi

**Comment by yankees88888g** [comment]
I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.

**Comment by 10op10** [comment]
> I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.

Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch

**Comment by yankees88888g** [comment]
It does mean war ofc but you should have the right to claim hide if someone goes after you simple, it requires skill to be able to run away and still be avile.

> > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> 
> Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch

If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.

**Comment by 10op10** [comment]
> If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.

Claim hiding isn't a skill your just a mf pussy who sits behind his screen scared for some items on a game, actual skill is practising PVP until you're decent. take your copium

**Comment by MineHero43** [comment]
> > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> > 
> > 
> > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> 
> If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.

Claim hiding really isn’t a skill, nor is it comparably to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.

This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.

**Comment by sage-blue** [comment]
> 
> 
> 
> 
> > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> 
> > 
> 
> > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> 
> 
> 
> If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.

claim hiding is not a skill LOL. also how r u gonna talk about claimblocking when u legit made ur town right next to another even though u could have made it anywhere in Antarctica. typical retard behavior

**Comment by yankees88888g** [comment]
> > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> > 
> > 
> > > 
> > 
> > 
> > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> > 
> > 
> > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> 
> claim hiding is not a skill LOL. also how r u gonna talk about claimblocking when u legit made ur town right next to another even though u could have made it anywhere in Antarctica. typical retard behavior

your banned so shut up.

**Comment by yankees88888g** [comment]
> > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> > > 
> > > 
> > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> > 
> > 
> > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> 
> Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> 
> This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.

for the oppressors not the oppressed.

**Comment by sage-blue** [comment]
> > > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> 
> > > > 
> 
> > > > 
> 
> > > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> 
> > > 
> 
> > > 
> 
> > > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> 
> > 
> 
> > Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> 
> > 
> 
> > This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.
> 
> 
> 
> for the oppressors not the oppressed.  

u aren't oppressed u are just retarded. take ur copium

**Comment by yankees88888g** [comment]
> > > > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> > 
> > 
> > > 
> > 
> > 
> > > Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> > 
> > 
> > > 
> > 
> > 
> > > This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.
> > 
> > 
> > for the oppressors not the oppressed.
> 
> u aren't oppressed u are just retarded. take ur copium

what are you on?

**Comment by sage-blue** [comment]
> > > > > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.
> 
> > > 
> 
> > > 
> 
> > > for the oppressors not the oppressed.
> 
> > 
> 
> > u aren't oppressed u are just retarded. take ur copium
> 
> 
> 
> what are you on?
bruv. please tell me who is oppressing u

**Comment by yankees88888g** [comment]
> > > > > > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > for the oppressors not the oppressed.
> > 
> > 
> > > 
> > 
> > 
> > > u aren't oppressed u are just retarded. take ur copium
> > 
> > 
> > what are you on?
> > bruv. please tell me who is oppressing u

owners

**Comment by Sakuuzo** [comment]
> I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> 
> Good idea, hope the staff consider it

Yes i think its already in the combat tag plugin if its not a plugin made by the server.

And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.

**Comment by sage-blue** [comment]
> > > > > > > > > I do think this would be a good idea for the factions server but the towny no because towny isn't supposed to be pvp friendly.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > Ya silly bastard do you even know the meaning of Geo Politics; it involves war you're only against this because your like the other shitters who claim hide 24/7 and won't grind for a new set sym bitch
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > If you have the skill to be able to claim hide you should have the right to be able to. Ofc war will happen but you have to learn claim hiding is apart of it. war isn't supposed to be intense thats why claim blocking isnt allowed.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > Claim hiding really isn’t a skill, nor is it comparable to claim blocking. If you don’t want to fight someone then simply don’t leave your claims in the first place. It ruins the experience for many people when players constantly hop in and out of claims during battles or when someone is at 1 HP and they run to claims in the last second. If you enter a fight with someone, dying should be a natural part of it.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > This combat tag wall is such a simple and small feature yet so useful and impactful at the same time. It would enhance the pvp experience on emc, making battles far more enjoyable and meaningful.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > for the oppressors not the oppressed.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > u aren't oppressed u are just retarded. take ur copium
> 
> > > 
> 
> > > 
> 
> > > what are you on?
> 
> > > bruv. please tell me who is oppressing u
> 
> 
> 
> owners

huh

**Comment by yankees88888g** [comment]
> > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > Good idea, hope the staff consider it
> 
> Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> 
> And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.

yes it is lol you go to the safe zone to reset the fight and heal up.

**Comment by MineHero43** [comment]
> > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > Good idea, hope the staff consider it
> > 
> > 
> > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> 
> yes it is lol you go to the safe zone to reset the fight and heal up.

No, usually you die and then come back..

**Comment by yankees88888g** [comment]
> > > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > > Good idea, hope the staff consider it
> > > 
> > > 
> > > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> > 
> > 
> > yes it is lol you go to the safe zone to reset the fight and heal up.
> 
> No, usually you die and then come back..
> 
> I don’t see the issue anyway, just don’t leave claims in the first place if you’re afraid of an ongoing battle

dont leave claims ofc u need to leave claims to get stuff. If this gets added many n spawns will close

**Comment by Sakuuzo** [comment]
> yes it is lol you go to the safe zone to reset the fight and heal up.

If you need to refill heal pot or repair during a battle so you have lost the battle and you deserve to die. Risk and reward.

**Comment by MineHero43** [comment]
> > > > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > > > Good idea, hope the staff consider it
> > > > 
> > > > 
> > > > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > > > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> > > 
> > > 
> > > yes it is lol you go to the safe zone to reset the fight and heal up.
> > 
> > 
> > No, usually you die and then come back..
> > I don’t see the issue anyway, just don’t leave claims in the first place if you’re afraid of an ongoing battle
> 
> dont leave claims ofc u need to leave claims to get stuff. If this gets added many n spawns will close

You can still leave claims, just perhaps avoid doing that if there’s a battle happening next to your town

**Comment by yankees88888g** [comment]
> > > > > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > > > > Good idea, hope the staff consider it
> > > > > 
> > > > > 
> > > > > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > > > > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> > > > 
> > > > 
> > > > yes it is lol you go to the safe zone to reset the fight and heal up.
> > > 
> > > 
> > > No, usually you die and then come back..
> > > I don’t see the issue anyway, just don’t leave claims in the first place if you’re afraid of an ongoing battle
> > 
> > 
> > dont leave claims ofc u need to leave claims to get stuff. If this gets added many n spawns will close
> 
> You can still leave claims, just perhaps avoid doing that if there’s a battle happening next to your town

theres never like a battle near my town what normally happens is some invisible guy comes along without warning

**Comment by MineHero43** [comment]
> > > > > > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > > > > > Good idea, hope the staff consider it
> > > > > > 
> > > > > > 
> > > > > > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > > > > > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> > > > > 
> > > > > 
> > > > > yes it is lol you go to the safe zone to reset the fight and heal up.
> > > > 
> > > > 
> > > > No, usually you die and then come back..
> > > > I don’t see the issue anyway, just don’t leave claims in the first place if you’re afraid of an ongoing battle
> > > 
> > > 
> > > dont leave claims ofc u need to leave claims to get stuff. If this gets added many n spawns will close
> > 
> > 
> > You can still leave claims, just perhaps avoid doing that if there’s a battle happening next to your town
> 
> theres never like a battle near my town what normally happens is some invisible guy comes along without warning

That’s the game, tough luck. That happens to many people and will continue happening no matter what you do.

**Comment by yankees88888g** [comment]
> > > > > > > > I’ve seen this on other towny servers before and I believe this would make combat more enjoyable for many people on the server. Pretty sure this feature is already built into the existing combat log plugin so it wouldn’t be too hard to implement.
> > > > > > > > Good idea, hope the staff consider it
> > > > > > > 
> > > > > > > 
> > > > > > > Yes i think its already in the combat tag plugin if its not a plugin made by the server. BUT it's probably related to the faction plugin and the faction claim system so im not sure that gonna work so easily with towny.
> > > > > > > And why there is someone crying about that ? You dont want to pvp or you dont want to die in a battle ?? So dont go pvp and keep you ass in your claim, thats simple. It is not normal to be able to alternate between a safe zone and a pvp zone while being in the middle of a fight.
> > > > > > 
> > > > > > 
> > > > > > yes it is lol you go to the safe zone to reset the fight and heal up.
> > > > > 
> > > > > 
> > > > > No, usually you die and then come back..
> > > > > I don’t see the issue anyway, just don’t leave claims in the first place if you’re afraid of an ongoing battle
> > > > 
> > > > 
> > > > dont leave claims ofc u need to leave claims to get stuff. If this gets added many n spawns will close
> > > 
> > > 
> > > You can still leave claims, just perhaps avoid doing that if there’s a battle happening next to your town
> > 
> > 
> > theres never like a battle near my town what normally happens is some invisible guy comes along without warning
> 
> That’s the game, tough luck. That happens to many people and will continue happening no matter what you do.

well i should i have the right to run into claims if that happens

**Comment by yankees88888g** [comment]
or maybe u pay 5g and u get pvp protection for 24h

**Comment by sage-blue** [comment]
> or maybe u pay 5g and u get pvp protection for 24h

🤯🤯🤯

**Comment by Warriorrrr** [comment]
Running into claims while combat tagged is now no longer possible.
