### ISSUE TITLE
[BUG] Feather falling

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1357]
### Server

Towny

### Describe the bug

It appears Feather Falling enchantment is bugged to be super rare or impossible to get though enchanting. 

### To Reproduce

1.  get any boots
2.  get lapis
3.  get a fully powered enchantment table
4. keep enchanting boots and see how often you get feather falling.

### Expected behavior

Father falling is supposed to be likely to get from the enchantment table

### Screenshots

N/A

**Comment by Warriorrrr** [comment]
Chances of getting enchants are the same as vanilla, feather falling is just a bit rarer to get.

**Comment by yankees88888g** [comment]
Are u sure should I do like a ton of testing

**Comment by yankees88888g** [comment]
Cause I did it 60 times and never got it
