### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TimmyOut** [EarthMC/Issue-Tracker#1358]
### Server

EarthMC

### Describe the bug

The whole issue is that I can't chat at all in chat. When i do a big error message comes up and kicks me to the queue server.

### To Reproduce

1. I have no clue how to reproduce this
2. 
3. 

### Expected behavior

I expected to be able to chat normally

### Screenshots

![2021-05-19_21 49 05](https://user-images.githubusercontent.com/84485678/118906640-2788c700-b8ec-11eb-8317-069b04aa0e47.png)

**Comment by Warriorrrr** [comment]
Was fixed by Eagle, chat works normally again
