### ISSUE TITLE
[BUG] Can't chat

### ISSUE THREAD

**Issue by Memetric** [EarthMC/Issue-Tracker#1359]
### Server

EarthMC

### Describe the bug

Whenever I try to chat it throws an error and kicks me out.

### To Reproduce

1. chat
2. 
3. 

### Expected behavior

My message to appear in chat.

### Screenshots

![image](https://user-images.githubusercontent.com/51463559/118908971-5012c000-b8f0-11eb-8ca1-6b608fe3f210.png)

**Comment by Warriorrrr** [comment]
Duplicate of #1358
