### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Talkiestnewt6** [EarthMC/Issue-Tracker#1360]
### Server

 Earthmc.net

### Describe the bug
 
After the last few days of the server being down, i log back in and spawn at my town spawn, Alert Vinland, with an empty inventory however the issue is, i beleive that i logged of with gear and an inventory mining in the nether.

### To Reproduce

1. Unknown, potenially restart the server with players in the nether?
2. 
3. 

### Expected behavior

Perferably my inventory is restored to the state it was in when i last logged out before the server meintnance, or i'm given some level of compensation.

### Screenshots

N/A

### Additional context
 
I i believe that my inventory was mainly an enchanted diamond pick, armor, shovel, sword, some netherite scraps. and some amount of gold.

**Comment by Warriorrrr** [comment]
Github is not the place to get support at, open a ticket in the [support discord](https://discord.gg/EZBYmpp).
