### ISSUE TITLE
[towny] [Feature] [BUG] Missing items into Farm Block list

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1362]
### Is your feature request related to a problem? Please describe.
1. There is a duplication of shears into farm block list
2. I ask to add Bone meal into the farm block list

### Describe the solution you'd like
1. Remove unwanted shears at the end of the list 
2.  Add Bone meal to the list to be able to let our resident/friend/outsider use it on sapling three

Because of that the Farm plot type can be attributed to be a three farm cuz of the restriction by the list > /towny farmblock

### Additional context
![2021-06-11_19 43 55](https://user-images.githubusercontent.com/61435183/121729698-0c763500-caef-11eb-9d7a-c69d788d1ff2.png)
![2021-06-11_19 44 12](https://user-images.githubusercontent.com/61435183/121729705-0e3ff880-caef-11eb-8c55-78bf08e4ea4d.png)

**Comment by sage-blue** [comment]
towny issue

**Comment by QJWIN** [comment]
absolouly not ... that a item to add on the list ...

**Comment by 3meraldK** [comment]
it's towny issue so go to theirs github repo

**Comment by QJWIN** [comment]
why if its a config server to change that should be a towny repo ? did you realise i already ask in official towny discord ? that a item to add in a list what is complicated to understand ? you need to create a issu in official towny to get the awnser that a config server and you should ask you server admin/mod ...

**Comment by QJWIN** [comment]
> 
> 
> it's towny issue so go to theirs github repo

yeah admin and owner don't have any access to config file of course ! [nice joke]

**Comment by Basically-Andrew** [comment]
This feature/bug can be resolved by changing the _farm_plot_allow_blocks:_ line under global town settings in [Towny's config.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml). I've also added Beetroots, Cocoa, Sweet Berry Bush, Carrots, Potatoes, and unattainable blocks (i.e. melon stems, etc.) if they weren't already added.  Below is what the line should look like to be corrected if I didn't miss a block.
```yml
global_town_settings:
  farm_plot_allow_blocks: BAMBOO,BAMBOO_SAPLING,JUNGLE_LOG,JUNGLE_SAPLING,JUNGLE_LEAVES,OAK_LOG,OAK_SAPLING,OAK_LEAVES,BIRCH_LOG,BIRCH_SAPLING,BIRCH_LEAVES,ACACIA_LOG,ACACIA_SAPLING,ACACIA_LEAVES,DARK_OAK_LOG,DARK_OAK_SAPLING,DARK_OAK_LEAVES,SPRUCE_LOG,SPRUCE_SAPLING,SPRUCE_LEAVES,BEETROOTS,COCOA,CHORUS_PLANT,CHORUS_FLOWER,SWEET_BERRY_BUSH,KELP,SEAGRASS,TALL_SEAGRASS,GRASS,TALL_GRASS,FERN,LARGE_FERN,CARROTS,WHEAT,POTATOES,PUMPKIN,PUMPKIN_STEM,ATTACHED_PUMPKIN_STEM,NETHER_WART,COCOA,VINE,MELON,MELON_STEM,ATTACHED_MELON_STEM,SUGAR_CANE,CACTUS,ALLIUM,AZURE_BLUET,BLUE_ORCHID,CORNFLOWER,DANDELION,LILAC,LILY_OF_THE_VALLEY,ORANGE_TULIP,OXEYE_DAISY,PEONY,PINK_TULIP,POPPY,RED_TULIP,ROSE_BUSH,SUNFLOWER,WHITE_TULIP,WITHER_ROSE,CRIMSON_FUNGUS,CRIMSON_STEM,CRIMSON_HYPHAE,CRIMSON_ROOTS,MUSHROOM_STEM,NETHER_WART_BLOCK,BROWN_MUSHROOM,BROWN_MUSHROOM_BLOCK,RED_MUSHROOM,RED_MUSHROOM_BLOCK,SHROOMLIGHT,WARPED_FUNGUS,WARPED_HYPHAE,WARPED_ROOTS,WARPED_STEM,WARPED_WART_BLOCK,WEEPING_VINES_PLANT,WEEPING_VINES,NETHER_SPROUTS,SHEARS,BONE_MEAL
```

**Comment by QJWIN** [comment]
TY andrew so now we can give the possibility to our resident to make tree farm with the bone meal thanks a lot
i close it then

**Comment by Warriorrrr** [comment]
Done
