### ISSUE TITLE
[Plugin] Why would you not have the brewery plugin?

### ISSUE THREAD

**Issue by DirtyDoctorDan** [EarthMC/Issue-Tracker#1364]
The Brewery plugin is a great plugin. It adds a variety of alcoholic beverages with a really well-made drunkenness feature. I think it would work especially well on this server due to the variety of alcoholic beverages you can brew and the potential complexities of the brewing system. I think it could add a whole new dimension to trading and economy, especially if a ton of custom recipes are made and existing recipes are tweaked so that players are able to experiment and keep secrets about how to make the different beverages, and sell them.

I honestly think adding the Brewery plugin would be a GREAT thing, especially if obscurity in recipes exists. I would go as far as to say it would be foolish not to have this plugin due to its exceptional economic potential in the server.

Let me know what you all think!

**Comment by 3meraldK** [comment]
can confirm. it can make a brand new economy system and also bring more fun to EMC because after 2 years of its existence it gets boring
