### ISSUE TITLE
[World] Swastika at California/Oregon Boarder

### ISSUE THREAD

**Issue by Poorlyparkedcars** [EarthMC/Issue-Tracker#1365]
### Describe the issue
 Please remove the symbol.

### Coordinates
 -23098, -8097

### Screenshots
![Capture](https://user-images.githubusercontent.com/86381093/123163458-9646cc00-d426-11eb-8301-18c30c67a2e0.PNG)

**Comment by 3meraldK** [comment]
if you are so worried about a swastika in wilderness, then why dont you go yourself and destroy it? it is only max. 15 blocks of cobblestone

**Comment by coblobster2** [comment]
I will remove but next time make a ticket in the support discord. this is just grief and mods can deal with this

**Comment by Basically-Andrew** [comment]
@Poorlyparkedcars Please close this issue if that's all.
