### ISSUE TITLE
[PLUGIN] Add a plugin who fix villager

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1366]
### Is your feature request related to a problem? Please describe.
villager can be fix with a plugin

### Describe the solution you'd like
add this plugin > [custom-villager-modifications](https://www.spigotmc.org/resources/custom-villager-modifications.78329/?__cf_chl_jschl_tk__=7695ebdbbda7b76c7bbf5b66a6a08e864ffb093c-1624570257-0-AaCL2eTPgFJsSTdmMSgFYmrCvKMJhILRXF86rRgxETYoTMxs5qQvM8vXkMJejyLgmLzYsdzsFIWcYveiwycDtlG_6r5DjE58eGrRB9Xo1Ek7zdnkgMIUMCxA-RAQdvaMqHnEmogwwfBbon2Kqc7gQ4P1qlRbpCdy8e1AOYnzHmLMOz4qqwi21V6AyeenU5maSWP0rX3aiByWnhmVN8hcgccmwKvOt9RQfceP6IU2ck1L-_BG91HbbX7baXkbNHqlZD5eGdA_Mzjzxzg36kNMNVNzfzPV1zJUksiM0Jl-Iw-TFQUARAZIo4VKq1nol8VFKnFeMuwMwjTCeZ65-8SfP9XEc3DBnTbneJtzpXRdhX6jKjouvsmyoYIbt6z-Ca1GR2pSH2ffptMOFec7S7Tw3Ba9Oi3p-cWp-5TGJBT5kxLx8k2uNmn65JGd98vjqlvvQR1NfHcPFHwo6fthGnIXDTw)

### Additional context
that will be great to see them back !

**Comment by 3meraldK** [comment]
yeah and you did not detail the information for the idea, should be closed ASAP. next time give much more info, what to exactly modify/add/remove.

**Comment by QJWIN** [comment]
everything is in the plugin name what do you wan custom villager will block the fact to transform villager to zombie villager and that will bypass the vanilla glitch about get item for only 1 emeralds.
then if we are not able anymore to get glitched villager mabe they can back !

**Comment by coblobster2** [comment]
Problem is similar to animals now only certain people would have them how would you fix that issue. why would anyone sell them?

**Comment by QJWIN** [comment]
before they turn villager off that how that worked ppl sell villager cuz we are able to reproduce them ...

**Comment by Basically-Andrew** [comment]
> before they turn villager off that how that worked ppl sell villager cuz we are able to reproduce them ...

No, poor people can stay in the slums, while we the rich get richer.

**Comment by 3meraldK** [comment]
also villagers might be disabled because of planned deflation of EMC economy, and it went successful. A deflation is a positive event which increased many items' prices, including famous mending (1 > 35 gold)

**Comment by CorruptedGreed** [comment]
Reference #1347
