### ISSUE TITLE
Invisibility appearance [BUG]

### ISSUE THREAD

**Issue by medowastaken** [EarthMC/Issue-Tracker#1367]
### Server
EMC towny

### Describe the bug
Whenever I am killed in combat, every player around me becomes invisible when I respawn.

### To Reproduce

1. Get killed in a crowded area
2. Others become invisible for you 

### Expected behavior
Supposed to see players after dying

### Video
https://streamable.com/u1eosr

### Additional context
The only way to fix is by restarting game

**Comment by jkmartindale** [comment]
Pretty sure this is a bug with your client and not EarthMC, since EarthMC doesn't control client-side display of things

**Comment by 3meraldK** [comment]
cap
its ur client's problem because why would EMC modify these stuff
