### ISSUE TITLE
[BUG] "Green Thumb Fail" chat spam

### ISSUE THREAD

**Issue by Kieubasiarz** [EarthMC/Issue-Tracker#1369]
### Description
MCMMO Green Thumb skill spams main chat with **\*\*GREEN THUMB FAIL\*\*** with every seed used that didn't work.
![obraz](https://user-images.githubusercontent.com/12072485/124383652-e5fe8080-dccd-11eb-914b-f79314645408.png)

### To Reproduce
Use seeds on dirt or cobble.

### Expected behavior
- Less invasive notification, favorably over hotbar.

**Comment by Basically-Andrew** [comment]
This seems to be a mcmmo design flaw. I would recommend closing and recreating this in mcmmo's GitHub.

**Comment by Warriorrrr** [comment]
Might create a pull request to change this if I've got some time, closing this here since it's more of an mcMMO issue.

**Comment by Warriorrrr** [comment]
Looked into this, don't need to make a pull request which is nice. Green thumb messages can be shown in the actionbar by enabling SubSkillFailed in the ActionBarNotifications part of the advanced.yml file.

**Comment by QJWIN** [comment]
then all notifications should be moved at the action bar , i think that will be more ez to see you skill ability that way

**Comment by Warriorrrr** [comment]
Done, will be automatically applied next restart
