### ISSUE TITLE
Add /polish chat

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1370]
Not so many, but still, even more than Swedish or German, there are Polish speakers. That is why /polish chat should be an additional channel added to this server. In my personal opinion, I don't understand the point of adding Swedish. Is that related to Fix? Anyways, we would enjoy to chat on polish chat, because many speakers of EMC are Polish, and we need to chat on general right now, just like turks, but they have their own dedicated channel. Thank you.

**Comment by Tomekirys** [comment]
I agree

**Comment by jkmartindale** [comment]
Might help your case if you can estimate how many Polish speakers there are on EarthMC, like was suggested at #1001

**Comment by Tomekirys** [comment]
@jkmartindale  50 - 100 +/- Polish players, i've seen many like polish cheese, potion07, and neekosfriends, like everyday i see new polish players. Adding Polish chat will be good, many people will speak at it

**Comment by 3meraldK** [comment]
I wanna also mention it again but e.g. a Swedish chat has been added for no literal reason. There are much less Swedish speakers and this chats purpose is very unknown. Well, a polish chat would have more. As ToMeKiRyS said there are plenty Poles around. Not only in Galicia / Poland. Polonia is also huge on EMC.

**Comment by Warriorrrr** [comment]
#1001
