### ISSUE TITLE
Potion stacking 

### ISSUE THREAD

**Issue by Saayuuki** [EarthMC/Issue-Tracker#1373]
Make the potions stackable, this will increase the pvp intensivity and it will help the player base to keep more potions in the inventory. I sugget the maximum number of stacking with the potions 16 or 8 this might not destroy the balance in the game. If u start brewing potions in the brewing stand u can get only 3 in time this May prevent duplications or glitch.

**Comment by Basically-Andrew** [comment]
No.

**Comment by 3meraldK** [comment]
it would be an attack on vanilla and would have a huge impact on pvp. just let emc be more vanilla related and some shitty stackable potions please.
