### ISSUE TITLE
[Feature] Queue Boss Bar

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1375]
### Is your feature request related to a problem? Please describe.

You have to either wait for your queue status to go up or down or run the command _/queue_ in the hub. Queue status messages are also not as friendly as they used to be since players can now talk in the hub. This all makes it annoying to check your queue status quickly.

### Describe the solution you'd like

A boss bar always displaying your current queue status would not only be a great solution but bring a whole new life to the queue. SaltedSuris on Reddit said, "This is what we need , quality of life updates to queue. something to do other than look at landmarks." This feature/solution could be added by converting the queue plugin's messages sent to players to be also displayed or only displayed in the boss bar text with an active moving bar to visualize queue status.
### Additional context

Below is a concept boss bar. I also posted this to earthmc's Reddit [here](https://www.reddit.com/r/EarthMC/comments/ohxyp8/concept_queue_boss_bar/).
![QueueBossBar](https://user-images.githubusercontent.com/59465284/126052998-1b1ebdfa-fa8e-4386-a082-2e500ce70600.gif)

**Comment by KarlOfDuty** [comment]
Sounds cool, I like it.

**Comment by Basically-Andrew** [comment]
If the hub is still operating with the same [forked queue plugin repo](https://github.com/EarthMC/queue) in the EarthMC organization, I'll look into my capabilities of coding this on a few test servers.
