### ISSUE TITLE
[BUG] Suspect 'Death By Lag'

### ISSUE THREAD

**Issue by Rupeto** [EarthMC/Issue-Tracker#1377]
The lag was getting increasingly worse over the course of an hour. When the lag was continuing to get even worse I stopped running and stood completely still for 2-3 minutes. I did afk at this point because the chunks were loading super slow however I'm 99% certain I was not player killed because I was standing wide out in the open and quite a far distance away from the nearest town. I was also checking the Dynmap every 20 seconds and no one was anywhere close to being near me. When I got back to my computer a couple minutes later I had already died, my player was burning and the chunks around me had visually bugged although. I quickly ran back to my death spot but when I returned my inventory and gset had been destroyed. It seems like the lag may of rubber banded and instant killed me due to the fact of my player moving to fast for chunks to render, with a combination of server latency and having my render distance set to high for server to keep up. Because this has happened one time before when I was traveling the nether and took fall damage. The damage didn't even register on my screen for at least 10 seconds and when my player finally registered the fall damage 10-20 seconds after the fall actually happened my player got sent flying into the air and off a cliff.

**Comment by jkmartindale** [comment]
> the lag may of rubber banded and instant killed me due to the fact of my player moving to fast for chunks to render

I don't think that explains why you were on fire though

> I'm 99% certain I was not player killed because I was standing wide out in the open and quite a far distance away from the nearest town

ngl that's a great way to attract invis killers, since you can't as easily run into a non-PVP chunk

**Comment by Rupeto** [comment]
Can an invis potions hide a player on the map

**Comment by Basically-Andrew** [comment]
Yes, but the player who killed should be displayed in the death message in #earthmc-towny or in the combat tag message. Also, This issue has no importance to the Github as lag is a feature that won't be fixed or removed. Look into your death with a ticket in the [support discord](https://discord.gg/EZBYmpp).

**Comment by jkmartindale** [comment]
> Can an invis potions hide a player on the map

You're hidden on the map if you're under a block, sneaking, or have the invisibility effect

> the player who killed should be displayed in the death message in #earthmc-towny

The only death messages show up in #earthmc-towny since early February are people who log out during combat

> or in the combat tag message

This is likely, though if chat was busy it might've scrolled off while OP was AFK
