### ISSUE TITLE
[BUG] Chickens despawn even with nametags.

### ISSUE THREAD

**Issue by SnekCodes** [EarthMC/Issue-Tracker#1381]
### Server

Towny.

### Describe the bug

I had around 10 chickens, but lost 3 of them due to despawning. They had nametags on them, but they still despawned. I now have 6 chickens, and it won't go past 6.

### To Reproduce

1. Get chickens.
2. Breed them in an enclosure until it gets to 6 chickens.
3. Use nametags on all the chickens.
4. Breed the chickens outside of the chunk with all the chickens.
5. Bring all the chickens to the chicken enclosure, then name the new chicken.
6. Go far away from the enclosure, then come back.
One chicken will have despawned, regardless of the naming, leaving you with 6 chickens.

### Expected behavior

The chickens should not have despawned, because they had nametags applied.

### Screenshots

![2021-08-01_20 15 33](https://user-images.githubusercontent.com/69597088/127795446-9c10dacd-140c-4bb6-9121-887d5023a571.png)

^ 7 chickens in an enclosure. (They have nametags.)
![2021-08-01_20 24 08](https://user-images.githubusercontent.com/69597088/127795454-334deec4-6de2-42d1-83fd-7e909d0eb9d4.png)

^ A baby chicken with a nametag, attached to a pole by a lead.

![2021-08-01_21 12 23](https://user-images.githubusercontent.com/69597088/127795459-c6b1fd26-6f72-44cd-8f6c-eba157c14aa2.png)

^ 5 chickens in an enclosure, the last one of the six being the chicken attached to the pole.

### Additional context

The enclosure I have is part of my one-chunk-big house, in a town in South America.

**Comment by gabeeebaby** [comment]
You surpassed the entity limit. I’m pretty sure the max is five entities in a given chunk.
