### ISSUE TITLE
[Feature] the ability to speak in the towny channel on the discord

### ISSUE THREAD

**Issue by kounterkounterkounter** [EarthMC/Issue-Tracker#1383]
One of the best features that the server had was the ability to speak in the towny channel on the Discord. It gave players who weren't in game the chance to talk to everyone in chat. Reenabling it would be beneficial to the community as it allowed easier communication if the person they want to talk to is unavailable on Discord, but is in game. It also allows the player to speak to players in game just to chat if they are waiting in queue and notice that their friend is on or if they want to speak to the people in game. Its a great way to communicate and a lot of old players wish that this feature was reenabled.

**Comment by jkmartindale** [comment]
Linking #1308 for tracking purposes

**Comment by gabeeebaby** [comment]
I was told it was disabled due to it not being able to keep up with messages sent on discord, and that it lags the entire plug-in. Not sure if that issue has been fixed. It seems silly though that staff speak in there if it can cause issues.

**Comment by kounterkounterkounter** [comment]
> I was told it was disabled due to it not being able to keep up with messages sent on discord, and that it lags the entire plug-in. Not sure if that issue has been fixed. It seems silly though that staff speak in there if it can cause issues.

i totally forgot to mention staff speaking in there. but yeah, my point exactly. if the staff can speak in it, why cant everyone else? i mean it doesnt make sense that only staff can talk in there if it causes issues as you said.

**Comment by DasCodes** [comment]
It was disabled due to player abusing the system. In-game chat gets tons of spams through out the day. It won't be back until we find a better solution.
