### ISSUE TITLE
[Feature] Add a dedicated Portuguese channel for global. (request on behalf of Olivio90)

### ISSUE THREAD

**Issue by superiorglitch** [EarthMC/Issue-Tracker#1385]
Portuguese is the 6th most spoken language in the world, and as Olivio is able to demonstrate, he can name several dozen people who speak Portuguese. It is a massive inconvenience to not have a dedicated channel for these users. Mods are frustrated when they talk in global, but alas where else can they speak? They have no channel. They resort to speaking in the Russian channel, but I can't imagine how the Russians feel about this. We request that "/ch j portuguese" be added to resolve the issue. Thanks a million.

**Comment by Warriorrrr** [comment]
Will be added on next restart
