### ISSUE TITLE
[Feature] Add other Rare/Unattainable Trades to Merchants

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1386]
### Is your feature request related to a problem? Please describe.

Many rare and unattainable items have been added to EarthMC with custom Wandering Traders. However, there are still many other items that can't be attained. Currently, it is impossible to obtain a new book of Curse of Binding or Curse of Vanishing since villagers were disabled.

### Describe the solution you'd like

Similar to how the mending crisis was resolved, Curse of Binding and Curse of Vanishing could be added to the possible trades of Wandering Villagers, aka Merchants on EarthMC. To obtain a Curse of Vanishing book a player would trade a book and an 8:00 portion of invisibility. To obtain a Curse of Binding book a player would trade a book and a chain.

### Additional context

![image](https://user-images.githubusercontent.com/59465284/128905839-3e9635f2-5266-4a1a-8e13-aa240367f241.png)
![image](https://user-images.githubusercontent.com/59465284/128905850-21ee3a64-52e6-4d70-8c8f-11695820bccf.png)

**Comment by jkmartindale** [comment]
why the hec is your minecraft so smooth

**Comment by Basically-Andrew** [comment]
> why the hec is your minecraft so smooth

Texture Packs

**Comment by FixTheAdmin** [comment]
Thanks for letting me know. I will also add more 1.17 items soon.

**Comment by Basically-Andrew** [comment]
😔 Fix never added these crafting recipes.

**Comment by CorruptedGreed** [comment]
Unfortunately deprecated so these are not being added
