### ISSUE TITLE
[BUG] Items go Bouncy Bouncy (carma2cn ref) when thrown/dropped on a low-half placed slab

### ISSUE THREAD

**Issue by keijodputt** [EarthMC/Issue-Tracker#1387]
### Server

This bug is in EarthMC towny server.

### Describe the bug

When placing a slab on top of a hopper, in the half-below part of the block, and dropping items on it, these items start bouncing and bouncing until 
a) the hopper catches them in the exact tick the items bounce down, else
b) items despawn in time-out, or else
c) player catches item.
The usual behavior for this was to have the items 'rest' in the 'base' of the slab. If I remove the slab, items rest on top of the block and do not bounce.

### To Reproduce

1. Place chest and hopper pointing to it.
2. Place slab (any type, even a daylight sensor) in the lower-half of the block atop of the hopper
3. Throw an item on top

### Expected behavior

Item should rest and slowly spin until picked up by the hopper

### Screenshots

https://user-images.githubusercontent.com/9009579/129439506-ec7944d8-d43b-4234-a73a-cf3497eb04dd.mp4

### Additional context

I don't really know if it's a bug or a 'feature', but CHICKENFODDER breaks many farms that rely on slabs.

Thanks for the review!

--keijo

**Comment by keijodputt** [comment]
Adding: Bouncy Bouncy also shows in farmed land:

https://user-images.githubusercontent.com/9009579/129450779-b6aec085-fcae-4806-b71e-a3f926cfc3d4.mp4

**Comment by Raurok** [comment]
I've had my fair share of experience with this. It occurs with soul sand, fences, and impartial block and who knows what else.
All my farms are broken by it 😔

**Comment by keijodputt** [comment]
Bouncy Bouncy on a roasted chicken farm:

https://user-images.githubusercontent.com/9009579/132208841-cb42a076-d231-45ca-bf52-73156348e5b4.mp4

**Comment by Warriorrrr** [comment]
Fixed by 1.17
