### ISSUE TITLE
[BUG] Queue chat messages appear twice to sender

### ISSUE THREAD

**Issue by Kieubasiarz** [EarthMC/Issue-Tracker#1388]
### Server
Queue

### Describe the bug
Messages sent in queue chat appear twice to the sender but nobody else. Others in chat confirmed this happens to them too.
![obraz](https://user-images.githubusercontent.com/12072485/129781985-6566953a-407b-4ce1-93c2-8db5a4a2703a.png)

**Comment by Warriorrrr** [comment]
Probably just needed a reload, no longer happens now.
