### ISSUE TITLE
[World]

### ISSUE THREAD

**Issue by PeaceofPoo** [EarthMC/Issue-Tracker#1389]
Portal trap has me stuck, in Chamberlain (Algonquia), can't open chat to respawn. Please get rid of portal or open it up if you can.

### Coordinates
 -14869 / 62.00000 / -9666

thanks - Peace_of_Poo

**Comment by Warriorrrr** [comment]
Open a ticket in the support discord or ask a moderator to teleport you out, you're in the wrong place.
