### ISSUE TITLE
Making horses teleport with you when you use /n spawn

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#1395]
I was talking with Warriorrr this afternoon about teleporting with horses, as I believe they are under used. My point was that if you were able to teleport with your horse, people would utilize them much more readably for map exploration, as it is currently faster to teleport to a n spawn and walk to your location. While talking about this Warriorrr, he mentioned that there is a config for making your mount teleport with you, which is currently disabled. As such my request is that we change this config so that people can teleport with their horses to other locations, as this will greatly increase the variety of transport methods on the server, and help incentivize infrastructure work in nations to accommodate for this type of travel.

**Comment by Prismary** [comment]
Sounds like a solid quality-of-life improvement to me.

**Comment by 3meraldK** [comment]
It seems like a good feature but would somehow ruin the concept of transportation of horses to sell them, however it's tolerable enough to implement it into the game

**Comment by airwheelx** [comment]
Alternative: re-enable summoning of temporary horses via Call of the Wild: https://github.com/mcMMO-Dev/mcMMO/blob/c41d2d1f397bd904a93df89f417024f73c222e8d/src/main/resources/config.yml#L433-L438

Increases the variety of transport methods with these limited lifetime (240 seconds) horses, more utility for apples, while retaining aspects of the existing economy for transporting long-lived horses.

**Comment by AndrewCheedle** [comment]
@Fruitloopins

**Comment by CorruptedGreed** [comment]
Implemented next changelog, assuming nothing breaks
