### ISSUE TITLE
[Feature] --> Adding a /arabic command

### ISSUE THREAD

**Issue by Hno0ony** [EarthMC/Issue-Tracker#1396]
Adding a command for arabian middle eastern players. As there are a lot of middle eastern players on the server who can't communicate using their native language.

It would help out a lot for the arabian players who don't have a clear understanding of English.

**Comment by DeadGlamour** [comment]
Hebrew has way more speakers in EMC, as Minecraft isnt popular in the arab community, yet neither have it, I will say they should add hebrew tho.

**Comment by Warriorrrr** [comment]
Channels are usually added/removed by Fix or Eagle when needed, I don't see any need for an extra channel at this time
