### ISSUE TITLE
[Feature]Add Japanese chat channel and allow /tell in queue server.

### ISSUE THREAD

**Issue by c0mpas5** [EarthMC/Issue-Tracker#1400]
### Is your feature request related to a problem? Please describe.
There are a lot of Japanese players who do not follow the 2.11 of the rules, and as a fellow Japanese, I feel sorry for them.

### Describe the solution you'd like

The title says it all. /chat join Japanese should be enabled. Also, please add a way to chat other than global chat, since the queue server chat is being trolled!

(This sentence was created by DeepL translation. Please let me know if any part of it doesn't make sense!)

**Comment by DasCodes** [comment]
Japanese channel was added but message in the hub will stay disabled.
