### ISSUE TITLE
Ban IP all Japanese players and let them go through a manual verification process

### ISSUE THREAD

**Issue by Deathlife23** [EarthMC/Issue-Tracker#1401]
Safe to say, japanese guy has basically got this server invaded with Japanese 2b2t players. I've seen Japanese 2b2t bots on queue and honestly, it's terrible. Please ban IP all Japanese players and link them with the EarthMC Support discord and let them go through a manual verification process. thank you.

**Comment by stailarg** [comment]
Or just let them host a server that is exacly like earthmc but for people who are from japan

**Comment by shinxe** [comment]
That's Nice
(I'm Japanese)
but They will use VPN...
Can it be bypass?
