### ISSUE TITLE
Apology and suggestion from Japan.

### ISSUE THREAD

**Issue by Namakeya** [EarthMC/Issue-Tracker#1402]
I'm here to appologize the chaos that Japanese player caused. I was chosen as a delegate among fans of the youtuber Oniya to make this chaos end.
First of all, most of Oniya fans are not cheaters nor bots, and we does not want these bad guys ruin EarthMC. For example, players in Kamuy are cheaters called Ghost Hax and they are irrelevant to Oniya fan community. We find the EarthMC very fascinating, and want to sustain peacefully. To achieve this goal, we are ready to collaborate this server by following ways : 
a. We donate to make this server better.
b. We find Japanese trolls and report to moderators.
c. We make effort not to use Japanese in public chat. If someone do, report to moderators.
Repeatedly, we are sorry for trolls ruining the server, but basically not all Japanese are trolls. I hope we can make good relationship and make this server more active. Thank you.

**Comment by Deathlife23** [comment]
Get the fuck out of EarthMC and then maybe we can accept your apology. We don't need your money, just leave.

**Comment by KarlOfDuty** [comment]
Fair enough, although thats not really what the issue tracker is for.
