### ISSUE TITLE
[BUG] Slight problem with getting on the server

### ISSUE THREAD

**Issue by Ninkyo** [EarthMC/Issue-Tracker#1404]
### Server
Both of them

### Describe the bug
The server is garbage

### To Reproduce
Log on to the server

### Expected behavior
wait 6+ hours to get in

### Additional context
Why can't the server be upgraded with all the money you've made from the new Japanese players?
I refuse to pay priority for a unstable server anyways.

**Comment by jkmartindale** [comment]
Minecraft Java Edition servers are very CPU-bound and single-threaded, so there's an inherent limit in how many same-world players the server software can handle at once regardless of hardware

**Comment by Ninkyo** [comment]
> Minecraft Java Edition servers are very CPU-bound and single-threaded, so there's an inherent limit in how many same-world players the server software can handle at once regardless of hardware

But the server struggles with 150+ people, other servers don't have that issue

**Comment by gabeeebaby** [comment]
> But the server struggles with 150+ people, other servers don't have that issue

Servers with lots of players are using something like BungeeCord to spread the players across many servers. I am not aware of any Java Servers with more than 200 players on a single server

**Comment by Warriorrrr** [comment]
Server performance is something we're always working on improving, I've made some fixes that should be implemented soon. Closing this for now since it's invalid.
