### ISSUE TITLE
[BUG]Unauthorized residents in town can't do anything

### ISSUE THREAD

**Issue by kuroobito** [EarthMC/Issue-Tracker#1405]
### Server

EarthMC

### Describe the bug

Unauthorized residents cannot open or close doors or use chests outside of their own land.
When I contacted someone with administrator privileges, they didn't change anything. It is probable that some bugs or changes occurred on the server on October 1st.

**Comment by KOKO0203** [comment]
Our town has same bags.
What country do yo belong to?

**Comment by CobaltB2048** [comment]
Our town has same bug and I can't do anything
please fix it as soon as possible

**Comment by Warriorrrr** [comment]
Fixed in the lates towny pre-release.
