### ISSUE TITLE
[Mechanic] chest shops are too limited. Please improve.

### ISSUE THREAD

**Issue by Punkypal** [EarthMC/Issue-Tracker#1407]
Right now the player chest shops can only sell items for gold ingots, and max 64 items at a time. This very much limits a merchants ability to make good shops. 

______________________________

I would like to see the chest shops improves so that when you go to adjust the shop after creation, you can do a few additional things. Such as: 1) Change what is paid for item sold/bought to additional choices other than only gold ingots. Gold nuggets should be an option that can be selected. Perhaps allow diamond, or iron, or emeralds too. 2) Make it so that larger amounts can be sold in one transaction. It would be efficient to sell nine full stacks of stone all at once for a single price. When editing the max value remains at whatever the max for one stack is. It should be possible to set the shop to sell multiple stacks in bulk.

______________________________

The nice thing about these changes is it would allow merchants more flexibility to set competing prices by being able to change their prices in increments. It also makes it easier to make shops to buy items, because if you sell any item at the price of 1 gold ingot, you can't also buy that item to keep your shops restocked, because you can only buy for 1 ingot, eliminating the ability to make profit. It would also let merchants buy items people want to sell lots of (such as dirt, or cobblestone) by offering to pay with "currency" of lower value than gold, such as emerald or iron. This would also allow a merchant to the following: They buy [item] for X amount of emeralds, then they have another chest that will buy X amount of emeralds for gold. If someone were to do this in their shop they can effectively turn an item like an emerald into a "coin" worth a fraction of a gold, greatly improving a merchants ability to set an exact price that better matches an item's worth.

**Comment by jkmartindale** [comment]
We're currently using a third-party plugin [QuickShop Reremake](https://www.spigotmc.org/resources/quickshop-reremake-1-17-ready-multi-currency.62575/), which doesn't support these changes. I think this would either need to be a feature request for the plugin developers, unless you want to suggest using a different shop plugin that supports these features and works with 1.16.

**Comment by Punkypal** [comment]
I did not know the name of the plugin used. I will look for it and suggest these options there. I will also look to see what other shop plugins are out there. This one certainly seems very easy to create a shop, but it is so basic it leaves much to be desired. If MTC was using a currency other than gold that was less rare some of these problems wouldn't be so bad, but as it is now it's almost as if the smallest size currency is a 100 euro note, which is problematic.

**Comment by Punkypal** [comment]
To properly research plugins, I need to know what economy plugin is being used to treat gold as currency. I don't want to suggest a plugin that isn't compatible with the economy plugin being used.

**Comment by Punkypal** [comment]
So I checked with both the devs for The New Economy and Quickshop.

The New Economy said that having two items as currency (one major and one minor) is "in the default config to have two items". The major currency could be ingots and nuggets can be the minor currency and the value can be set to be 9 nuggets = 1 ingot. 

Quickshop dev said "To change the amounts in one transaction, you should use stacks feature" which can be set in the configuration. Quickshop on the Spigot page says it supports TNE and they have a command, /qs currency that should work to change the type of currency accepted in the shop.

So from what I've learned there seems to be no reason except by intentional choice that the options for shops is so limited and restrictive. Settings are available to allow nuggets to be used for purchases and bulk sales could be made possible.

Having either of these options "turned on" would be a huge advance to player merchants. Both would be a major game changer. 

Please. Being able to run a good shop on a server with an economy is the no. 1 thing I look for in a game. EMC appears to have the ability to do this. If something else is causing a glitch or some other thing that prevents is, please tell me why, because as it is now, the ability to run a shop other than only selling high-end items is very disappointing.

**Comment by Punkypal** [comment]
@jkmartindale Just tagging to see if anyone noticed I replied two weeks ago :)

**Comment by FixTheAdmin** [comment]
Thanks for the thorough feedback. I can say right away that this will not be added. It would cause a race to the bottom in terms of item price since all players have access to the same resources. The 1 gold for 64 items is a fair lowest price cap.

**Comment by Punkypal** [comment]
@FixTheAdmin I can understand that reasoning for not allowing stacks, because that would really allow a race to the bottom on selling common things like dirt or stone and it does get to be a bit too much.

But would you possibly consider just the **nuggets** as minor currency? Right now iron BLOCKS sell for ~1 gold for a stack. Having gold nuggets would make selling ingots reasonable in shops, or loose diamonds, or wood, or many things. I've seen that nuggets once were able to be used by shop signs with a past plugin. Was that really so bad? Rare resources or those that take time and effort to acquire should still maintain their current value and price.
