### ISSUE TITLE
I cannot Invite my friend to my town

### ISSUE THREAD

**Issue by cmandale** [EarthMC/Issue-Tracker#141]
**Server**
EarthMC - around the Hudson bay area

**Describe the bug**
I was trying to invite my friend to my town (Port_Nelson) but everytime i sent /t add EthanJames (his username) it said "you have already invited EthanJamesC to join your town! none of those names were valid!" and if he never got the invite, also if he did try to "accept it", then he never joined.

**To Reproduce**
i do not know if this can be reproduced
**Expected behavior**
him to see the invite and join

**Comment by TypicalFernie** [comment]
Try doing /t -add EthanJamesC or /t -invite EthanJamesC and then re-invite him. If that doesn't work then make your town public and he can join by doing /t join Port_Nelson

**Comment by BowShot118** [comment]
Try voking the invite by doing/t add -EthanJames. Then re-invite him. You can only add every 12 or so hours without revoking.

**Comment by cmandale** [comment]
The issue has been resolved, thank you.
