### ISSUE TITLE
[Feature] Remove wooden pressure plates from the Towny switch list

### ISSUE THREAD

**Issue by Prismary** [EarthMC/Issue-Tracker#1410]
### Is your feature request related to a problem? Please describe.
I noticed this issue while working on an advanced iceroad design that utilizes wooden pressure plates which are run over by boats to move pistons. While testing the concept on EarthMC, I found out that boats will only trigger wooden pressure plates by themselves and won't do so if a player without switch permissions for the plot is sitting inside it. I find this behaviour to be quite odd.

### Describe the solution you'd like
All wood-type pressure plates should be removed from the Towny switch list, thus making them usable by any player, anywhere, regardless of permissions. This may sound a bit drastic at first, however there wouldn't actually be any security concerns, since they can already be triggered by any player simply by throwing items or pushing entities onto them. It would essentially be a quality of life improvement and shouldn't have any significant drawbacks.

### Additional context
`/towny switches` will show all switch blocks.

Screenshot of a boat and an item activating a pressure plate, but a player without switch permissions being unable to:
![Pressure Plate Demo](https://user-images.githubusercontent.com/35495200/136631883-3d0dd3c6-95bd-4e03-b0b2-ef4398b247d9.png)

Here's another screenshot showing the pressure plate not triggering with the player lacking switch permissions sitting inside the boat on top of it:
![Pressure Plate Demo 2](https://user-images.githubusercontent.com/35495200/136632663-0e997006-797a-49cc-be96-f4bf3801aa4a.png)

**Comment by jkmartindale** [comment]
Would it make sense to add weighted pressure plates as well?

**Comment by KarlOfDuty** [comment]
Done, active on next restart.
