### ISSUE TITLE
[Mechanic] Suggest a Queuing Mechanic

### ISSUE THREAD

**Issue by NoMathExpectation** [EarthMC/Issue-Tracker#1411]
### Is your feature request related to a problem? Please describe.

Because of some reasons, the EarthMC server received much more players than usual time, especially during the weekends.
As the players growing, more and more players choose to buy premium and queue priority to join Towny faster.
This created an serious situation that players who didn't have priority seldom have chance to join Towny when queuing, because players who have brought premiums or queue priorities keep pushing the players without any of them backwards in the queue.
For example, today I have queued for about 10 hours and I even didn't get into Towny. My position kept going forward and backward. Sometimes I wait for hours and the position just only go backwards.
It is really annoying that you have queued for long time but you still can't play in Towny.

### Describe the solution you'd like

I suggest that every x players with premium or queue priority joining Towny will let a player without any of them join Towny next time. (x could be defined)
And players with premium can still join Towny before the player mentioned above joins.

This is fair for all the players, whoever is with or without premium or queue priority.
### Additional context

None. If I come up with something I will put it here too.

**Comment by Basically-Andrew** [comment]
A new queuing system was recently added that has appeared to solve unbearable long queue times for new players. Unless you have some other suggestions or critiques, you may close this issue.
