### ISSUE TITLE
[Feature]Lift the ban off of the word "Jew"

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#1415]
### Is your feature request related to a problem? Please describe.
For some reason, the word "Jew" is considered offensive or somethin and you can't type it in chat, you can however, type "Juden" and even worse, "Kike".
this is ridiculous, as a Jew I am actually offended that words such as these aren't censored yet the word "Jew" is, it implies Jews being offensive yet not their actual derogatory slurs.

### Describe the solution you'd like
I ask that similar to the n word the K word will be banned, unlike the word "Jew" which is a perfectly okay word and should be allowed to be said, as it holds no negative meaning.

### Additional context
Can we get an actual reason to why TF this word isn't even allowed?

**Comment by DeadGlamour** [comment]
@KarlOfDuty @fix

**Comment by FixTheAdmin** [comment]
You can say it now. Sorry if it offended you, that was not the intention. I wanted to get rid of nazi spam but I agree that the solution isn't good.

**Comment by ClonedCopier** [comment]
> You can say it now. Sorry if it offended you, that was not the intention. I wanted to get rid of nazi spam but I agree that the solution isn't good.

@FixTheAdmin It's back in the filter, and I need to agree with the parent poster. Jews call themselves the word all the time, and it's not an inherently derogatory word, even if it's sometimes used in derogatory contexts. Someone who wants to be antisemitic will do it regardless of whether or not they can say "jew" by saying "them" with triple parentheses or using an easy bypass like "jeu." This effectively stops jews from using the word without offering a good fix for the issue it was intended to resolve. Besides, allowing this innocent word and filtering #earthmc-towny with `has:jew` would be an easy way to find and reprimand toxic players.
