### ISSUE TITLE
[BUG] Formatting errors in chat: The "ff.bug"

### ISSUE THREAD

**Issue by Prismary** [EarthMC/Issue-Tracker#1419]
### Server
Towny

### Describe the bug
Chat message formatting breaks down if a message starts with and/or contains something like "ff.test". If premium players did this before the server updated to 1.17 the text would be purple, now the entire message reverts back to vanilla formatting. Interestingly, the player sending the message will see it in chat twice, the first has correct and the second one vanilla formatting. All other players will only see the badly formatted one.

### To Reproduce
1. Type "ff.hello" in chat
2. Realize the formatting is broken
3. Lay down on the floor and cry

### Expected behavior
A correctly formatted message should appear in chat.

### Screenshots
Me typing "ff.test" (note the duplicate message):
![ffbug1](https://user-images.githubusercontent.com/35495200/140627012-b475c265-5d6f-4693-8191-0f79ddfe0dca.png)

Other players doing the same (note the correctly formatted message being absent):
![ffbug2](https://user-images.githubusercontent.com/35495200/140627024-5af59ae1-bc9c-4e99-ad4c-f1c932153fad.png)

Another variation with only one 'f':
![ffbug3](https://user-images.githubusercontent.com/35495200/140627058-40a7ff5a-7e61-490e-8e29-763cf66ffca6.png)

An entirely different version:
![ffbug4](https://user-images.githubusercontent.com/35495200/140627066-6c30bcb4-34e9-407e-bf39-146340508ec3.png)

### Additional context
It's worth noting that I'm not exactly sure what causes this and what kinds of combinations are possible. It always involves a dot near the beginning of the message, other than that, the behaviour is more or less arbitrary. The OG version most frequently used seems to be "ff.<mesage>".

**Comment by Warriorrrr** [comment]
Already fixed, just waiting for the plugin to be updated on the server.
