### ISSUE TITLE
[Feature] Remove various utility blocks from the Towny switch list

### ISSUE THREAD

**Issue by Prismary** [EarthMC/Issue-Tracker#1420]
### Is your feature request related to a problem? Please describe.
As of now, some utility blocks can't be used in plots you don't have switch permissions in, even though there's no reason to restrict them.

### Describe the solution you'd like
**The stonecutter, smithing table, loom, grindstone and cartography table should be removed from the Towny switch list.** This will allow all players to use these blocks anywhere regardless of town claims and plot settings. As mentioned earlier, there's no reason to restrict the usage of these blocks, as they function similarly to crafting tables in the way that they can only be used as utility and don't have any storage. There is no security concerns associated with removing the switch restriction on these blocks, it'd simply be a quality of life improvement. Blocks like the crafting table and anvil are already free of this restriction which would also make keeping the blocks mentioned above restricted an inconsistency.

### Additional context
The towny switch list can be viewed by running `/towny switches`.

Here's the first page of it with the mentioned blocks on it:
![switches_page1](https://user-images.githubusercontent.com/35495200/140627453-3cd24767-d906-4350-b077-a74e7bff9dc7.png)

**Comment by Basically-Andrew** [comment]
Admins, this issue can be resolved by updating the _switch_ids_ line in [config.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) to something like this:
```yml
switch_ids: CHEST,SHULKER_BOXES,TRAPPED_CHEST,FURNACE,BLAST_FURNACE,DISPENSER,HOPPER,DROPPER,JUKEBOX,FLETCHING_TABLE,SMOKER,COMPOSTER,BELL,BARREL,BREWING_STAND,LEVER,BUTTONS,WOOD_DOORS,FENCE_GATES,TRAPDOORS,MINECARTS,LODESTONE,RESPAWN_ANCHOR,TARGET,STONE_PRESSURE_PLATE,POLISHED_BLACKSTONE_PRESSURE_PLATE
```

**Comment by Prismary** [comment]
> Admins, this issue can be resolved by updating the _switch_ids_ line in [config.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Config.yml) to something like this:
> 
> ```yaml
> switch_ids: CHEST,SHULKER_BOXES,TRAPPED_CHEST,FURNACE,BLAST_FURNACE,DISPENSER,HOPPER,DROPPER,JUKEBOX,FLETCHING_TABLE,SMOKER,COMPOSTER,BELL,BARREL,BREWING_STAND,LEVER,BUTTONS,WOOD_DOORS,FENCE_GATES,TRAPDOORS,MINECARTS,LODESTONE,RESPAWN_ANCHOR,TARGET,STONE_PRESSURE_PLATE,POLISHED_BLACKSTONE_PRESSURE_PLATE
> ```

The admins are aware of this, Karl already removed wooden pressure plates from the switch list a couple of weeks ago (#1410)

**Comment by Warriorrrr** [comment]
Done
