### ISSUE TITLE
[BUG] Haste/McMMO alchemy custom potions disabled since the 1.17.1 server upgrade.

### ISSUE THREAD

**Issue by Salmon12345** [EarthMC/Issue-Tracker#1421]
### Server
EMC Towny

### Describe the bug
By putting a carrot in the brewing stand with an awkward potion, McMMO plugin would let you make a special potion, such as haste with carrots. Despite having all the requirements it seems that not only you can't make the McMMO potions but you can't level up your Alchemy skill anymore with regular potion brewing.

### To Reproduce
1. Have the appropriate alchemy level and the ingredients for a special potion from here: https://mcmmo.fandom.com/wiki/Alchemy
2. For example, put a carrot in a brewing stand that contains awkward potions with an Alchemy level of at least 100.
3. Wait only for nothing to happen and no experience being gained from potions.

### Expected behavior
Awkward potions should become Haste potions.

### Screenshots
None needed.

### Additional context
McMMO alchemy was enabled before 1.17.1.

**Comment by Warriorrrr** [comment]
Will be fixed next server restart.

**Comment by Warriorrrr** [comment]
Should be fixed now.
