### ISSUE TITLE
[BUG] Villager Breeding glitched

### ISSUE THREAD

**Issue by Duraznita** [EarthMC/Issue-Tracker#1422]
### Server
I installed the Towny plugin on my server spigot/bukkit 1.17.1 with the last Towny Version Released (Stable)

### Describe the bug

Villagers generate hearts and interact to create a baby villager but anger effects come out of nowhere, and nothing happens, this repeats in a loop, and villagers are never generated.

I tried to do this in city protections and outside of them and it did not get it to work.

To clarify doubts, if I have disabled the option "Avoid births of village babies" in the towny cfg

### Expected behavior
A normal villager farm

### Additional context

Removing the plugin the farms if they work

**Comment by Warriorrrr** [comment]
This is the EarthMC issue tracker, not towny support. If you haven't changed anything in the towny config then it will not be caused by towny.
