### ISSUE TITLE
1.17 Items Recipes

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#1424]
### Is your feature request related to a problem? Please describe.
Currently, 1.17 has changed basically nothing over the server, it was a bit of a needless update when you realize the focus of it was exploring caves and buildings blocks, neither of which were added to the server, and while I'd love to give my own idea for how to introduce caves I doubt any admin will actually bother about it. So here I'll just suggest my own recipes for the building blocks aspects of the update, these recipes are easy to add so I don't see a reason to not add them.

### Describe the solution you'd like
Here's a list of all the recipes I propose.
**Tuff**
![‏‏צילום מסך (331)](https://user-images.githubusercontent.com/53373440/141363191-5a99d3a0-fc50-4e12-9c66-e7a614c7e396.png)

**Amethyst Shards**
![‏‏צילום מסך (332)](https://user-images.githubusercontent.com/53373440/141363286-620f4c78-279c-4471-a69a-ed7f6a7be107.png)

**Calcite**
![‏‏צילום מסך (334)](https://user-images.githubusercontent.com/53373440/141363374-2865711a-5f2d-49ac-9b7e-06b9cfc128a1.png)

**Copper Ore**
![‏‏צילום מסך (336)](https://user-images.githubusercontent.com/53373440/141363411-d136f89a-4d97-46f2-a08b-2102cbef60d5.png)

**Deepslate**
![‏‏צילום מסך (338)](https://user-images.githubusercontent.com/53373440/141363467-707a9fc5-347b-41fa-92ab-828587ec7771.png)

**Pointed Dripstone**
![‏‏צילום מסך (340)](https://user-images.githubusercontent.com/53373440/141363571-090f2e80-99c1-451e-9f26-7b662bed2b45.png)

**Powder Snow Bucket**
![‏‏צילום מסך (342)](https://user-images.githubusercontent.com/53373440/141363601-858834b0-8716-43ec-9f71-529bcc9b1cee.png)

_**BONUS**_
**Sculk Sensor**
![‏‏צילום מסך (344)](https://user-images.githubusercontent.com/53373440/141363663-d950330e-da5d-4f82-b5fd-882f68296f98.png)

### Additional context
I also think MCMMO should be further utilized to get more items, Fishing should give Amethyst Buds and Glow Ink Sacs, with the Buds being Epic and Glow Ink Sacs as a legendary.
Another thing which could be used is "Hylian Luck", a perk from Herbalism which gives you items from breaking flowers and such with a sword, it currently gives carrots and other stuff, but I think it should give more items, specifically all the plantlike items from 1,17, which I will list here:

- Azalea | Renewable
- Cave Vines | Renewable
- Dripleaf (Preferably the small one as it can grow to the big 1) | Not Renewable
- Glow Lichen | Renewable
- Spore Blossom | Not Renewable

**Comment by ltsCheeks** [comment]
I really like this idea, I feel like it opens up how many new 1.17 blocks we'd be able to have. I also believe that there are possibly some other recipes that could be good as well! (and now I'm not a mod, I just like this idea a lot, as a player)

**Comment by Prismary** [comment]
Looks good to me. There's a lot of items besides these that need recipes as well, it's really about time the custom recipe list gets expanded.

**Comment by Warriorrrr** [comment]
The following recipes have been added:

1 deepslate + any ore -> deepslate variant of ore
1 end crystal -> 16 amethyst shards
1 diorite -> 1 calcite
1 granite -> 1 dripstone
2 dripstone -> 1 pointed dripstone
2 stone + 2 andesite -> 4 tuff
4 stone/cobblestone -> 4 deepslate
1 raw iron + 1 blaze powder -> 1 copper ore
1 grass block + 1 oak leaves -> 1 moss

**Comment by DeadGlamour** [comment]
Warriorrr ty so much for this I love you but what about all the flora items? Theyre very good lookin and cool :((
