### ISSUE TITLE
[Feature] Play a nice sound when you get into the main server

### ISSUE THREAD

**Issue by Moldytzu** [EarthMC/Issue-Tracker#1425]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I put the game in the taskbar while it's in queue and I do something else like listening to music and then I get in without knowing, after 15 minutes I get kicked to the queue.

### Describe the solution you'd like
When you get into the main server it would be nice to play a sound or a short song (5-10 seconds) to indicate that you're in

**Comment by Basically-Andrew** [comment]
This issue can be resolved simply using a chat filter mod that parses for "You have been sent to EarthMC." in chat.

**Comment by Prismary** [comment]
Might be nice if it was toggleable, would generally be helpful though.

**Comment by DeadGlamour** [comment]
Yes, sounds like honestly sich a lovely little detail whoch could become a very nice meme / iconic for the server, wont really change much but it will def be nice, QoL and not hard to add.

**Comment by Warriorrrr** [comment]
Implemented this a while back, should be active.
