### ISSUE TITLE
Adding a plugin to simplify chest solution for the server to reduce lack and improve quality of life for players

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#1429]
Basically since the Terra Nova server was added back in late 2018 there have been issues with lag. One of these issues are to what i can understand is the large amount of items frames as they act as entities. Other contributors to lag are mass amounts of chests and big redstone machines such as automatic storage systems.

My proposal is that we add a mass storage plugin like Advanced Chests (link is at the bottom). This plugin specifically allows the user to create a large chests with multiple pages which can be sorted with the click of a button. These chests can then be further expanded via payment (idk if this will work with our gold based economy but probably).

Why this will make a difference is that people will no longer need to use mass amounts of item frames and chests when creating their storage system, as instead there will only be a few compact chests for the entire storage system. This will also basically remove the need for auto sorting machines for the server, which undoubtedly also will help reduce lag.

The final reason why this would be a great addition to the server is the simple improvement to the quality of life it brings to the players. Sorting items in Minecraft is one of the worst tasks to do, and is universally dreaded. If anything this should be reason enough alone to do it

https://www.spigotmc.org/resources/%E2%AD%90advancedchests%E2%AD%90-unlimited-sizes-holograms-%E2%9C%A8upgrades-%E2%9C%85sells-%E2%9A%A1sorter-%E2%98%84%EF%B8%8F-compressor.79061/

**Comment by Prismary** [comment]
Item frames do cause some lag, storage however doesn't really, except if it's tied up to a redstone sorting system, but redstone is an entire problem in itself. The plugin you suggested may or may not be a good addition anyway, I personally think it may just further complicate the server and the plugins it relies on, but it could be cool nonetheless.

**Comment by 3meraldK** [comment]
Well you are wrong, because both of them don't make significant lag. Storages cannot lag the game while render of item frames is small enough. While frames are entities, their render on EMC is decreased to 1-2 chunks meaning a player cannot see item frames in distance greater than 16-32 blocks.

**Comment by alekb1** [comment]
I believe that it was Warriorrr who mentioned to me that if all the item frames were banned from the server, ot might reduce lag enough that mobs could be brought back. I'm no expert, but I would like to know what you base your assessment off. Personally I'm not much for banning stuff that is usefull, but rather introduce alternatives which will help reduce the use :))
