### ISSUE TITLE
Pressure plates

### ISSUE THREAD

**Issue by Keennoo** [EarthMC/Issue-Tracker#143]
**Server**
EarthMC Terra Nova
**Describe the bug**
Pressure plates not protected by towny

**To Reproduce**
1. Go to my town
2. Go over my plates
3. See perms broken

**Expected behavior**
anyone can get in

**Comment by KarlOfDuty** [comment]
Could you try it again, stone plates are added to the switch perm.

**Comment by KarlOfDuty** [comment]
There was an issue in that towny version, protections should be fixed now.
