### ISSUE TITLE
[Feature] Teleportation to Trusted Towns

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1430]
### Is your feature request related to a problem? Please describe.

Players with town trusted permissions are almost like Councillors except don't have access to commands for that town. Trusted could include one simple command.

### Describe the solution you'd like

Ability to teleport to trusted towns.

**Comment by Prismary** [comment]
I'm mildly confused by the problem description, but I assume you'd like players that are trusted in a town to be able to teleport to it even though they're not a member?

**Comment by CorruptedGreed** [comment]
Players can now teleport to towns within their nation for some time, but this is probably too much to pursue.
