### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Green-Frog32** [EarthMC/Issue-Tracker#1431]
EarthMC

### Describe the bug
When I type any command, it shows as a unknown command error. The text also displays as red which indicates an error

### To Reproduce
1.Type a towny command
2. Gives unknown command error

### Expected behavior
It is expected that the command shows up automatically so you can hit Tab and fill it in

### Screenshots
![2021-11-22_17 46 42](https://user-images.githubusercontent.com/92001731/142946547-651bcbb8-0eb0-4325-b10e-a756badfffde.png)

**Comment by Warriorrrr** [comment]
Fixed.
