### ISSUE TITLE
[Mechanic] Disable Picking Up Items While Under PvP Protection Upon Death

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1432]
### Is your feature request related to a problem? Please describe.

Upon a player's death, they are given a short-timer of PvP Protection unless they attack a player. The issue with this neat feature is that players can be killed outside of their town but can easily quickly run back to grab things with PvP Protection.
### Describe the solution you'd like

Disabling PvP Protected players after death from having the ability to pick up items would solve this issue. If they wished to attempt to pick up their items they would only need to attack a player.

**Comment by Warriorrrr** [comment]
This is enabled now, will be applied on next restart.
