### ISSUE TITLE
[Feature] DiscordSRV Proximity Voice 

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1433]
### Is your feature request related to a problem? Please describe.

DiscordSRV Proximity Voice isn't enabled. Text Chat is boring.

### Describe the solution you'd like

This neat feature of DiscordSRV allows players to link their Discord and when near another player (configurable distance) can talk with each other in Discord. If your concerned players would know you're nearby, just don't join a voice channel. This feature would make PVP battles, nation spawns, and other collections of players have a fun time easily talking with each other through voice.

### Additional context

https://www.youtube.com/watch?v=3gATervIh7k

**Comment by Colt44Magnum** [comment]
I don't actually see the benefit of this. It just feels like a nintendo gimmick that no one will really use other than the first day its implemented

**Comment by Warriorrrr** [comment]
I agree with Colt, I don't think would be used much a few days after implementation.
