### ISSUE TITLE
Rule 1.1 - Ban & Disable Litematica Easy Place

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1434]
### Is your feature request related to a problem? Please describe.

Litematica is currently allowed instead of Schematica for obvious reasons like its printer function. However, Litematica has some game-breaking features of its own called Easy Place. This includes the ability to place floating blocks, place blocks further than possible in vanilla, and others like placing faster than vanilla.

### Describe the solution you'd like

Ban the use of Litematica's Easy Place under Rule 1.1 on the last bullet point. 

> - Litematica without Easy Place or the printer function (Schematica is not allowed, however).

A custom plugin could also be used to disable its game-breaking features by detecting if the player is attempting to place a block at a non-vanilla distance or without an adjacent block like in vanilla. The player's block wouldn't place and a message and chat could appear for the player.

### Additional context

Placing a Floating Block:
https://youtu.be/SqdJ9vxCyho

Placing at a non-vanilla distance:
https://youtu.be/9HGimSpb3-8

**Comment by DeadGlamour** [comment]
Why??? It's a cool mod and while I didn't use it for a while now I don't see why we should limit builders who do...

**Comment by Basically-Andrew** [comment]
Litematica's Easy Place feature is the only intended ban. Users would still be allowed to view schematics but place blocks by hand instead of using Easy Place which gives the player game play leverage over other players specifically those playing vanilla. If a large enough of the player base don't support or belive this rule against Easy Place is necessary the custom plugin disabling the game breaking features should still be used to balance the game.

**Comment by gabeeebaby** [comment]
Easy Place does indeed help players build faster, but it doesn't hurt players who don't use it. Building in general doesn't really affect the in game economy or anything to do with towny experience. Complex builds where easy place is often used are made for the aesthetics. Banning this feature would only discourage people from investing their time in building. I would also think that a plugin checking every block that every player places would certainly lead to the performance issues getting even worse.

**Comment by Warriorrrr** [comment]
I personally agree with this, I commonly see this used for constructing map art or buildings faster than what is possible without the mod.

**Comment by AndrewCheedle** [comment]
Building is already something most people dont do, so I dont see why we should limit builders to use mods that help them to make bigger builds faster.

**Comment by AndrewCheedle** [comment]
Building is already something most people dont do, so I dont see why we should limit builders to use mods that help them to make bigger builds faster.
