### ISSUE TITLE
[Mechanic] Enable Enderchest Balances

### ISSUE THREAD

**Issue by Punkypal** [EarthMC/Issue-Tracker#1435]
[Mechanic] Problem: The gold in a players ender chest isn't counted as part of their gold balance.

I checked with the developer of The New Economy and was told that the bug that was causing items to disappear has been fixed. 

---------------------------

Not having ender chest balances turned off creates two problems. 

1) If a player with a shop is online, they must keep gold on their personal inventory to allow their shop to buy items from other players. If such a shopkeeper needs to travel outside protected claims, it forces them to either shut down all buying operations, or risk getting mugged. Not a very fun choice. 

2) Players who gank others for their gold can simply do /player and see if anyone on the EMC map is carrying gold and exactly how much because your gold balance only shows if that's how much is actually in your inventory. Gankers shouldn't be able to magically know exactly how much money you have in your pocket from anywhere in the world. If ender chest balances were re-enabled they wouldn't be able to do this so easily because they would see a balance, but that amount could be all in your ender chest, and not actually on you.

Here should be an image of the dev from TNE saying that the ender chest bug in question was fixed:

![echest](https://user-images.githubusercontent.com/91823837/143500117-9b93e47e-e856-480f-854e-6e372a1f3b45.JPG)

**Comment by Basically-Andrew** [comment]
I believe the above-mentioned Enderchest Balances that needs to be enabled is on line 233 of the TNE Bukkit [config.yml](https://github.com/TheNewEconomy/TNE-Bukkit/blob/master/TNE/src/net/tnemc/resources/config.yml) under `Options:`. The line should be changed to something like the following below:

```yml
             #Would you like your item currency balances to also check the player's ender chest?
             EnderChest: true
```

*Note: The issue might not have been an issue with TNE or resolved by TNE as it could be another or several plugins interacting with each other that created whatever caused admins to disable this feature and create this issue. Other plugins might also need config changes to solve this issue.*

**Comment by Punkypal** [comment]
I understand that there could be another issue that's causing separate problems. I tried to explain the issue as best I could for the dev of TNE, and their response seems to me that they knew about an issue just like what I described. I can only hope that there were talking about the same thing, and it is indeed fixed. I can understand that with all the things that it takes to keep a server going, nobody may have been informed that a dev of just one plugin got around to fixing a bug.

Does EMC have a test server that turning ender chest balances could be tested to see if indeed it's working, before risking making it live on the main server? Does the Mods team know how to replicate the issue, or was it random and mysterious? :/

**Comment by Warriorrrr** [comment]
EarthMC switched to a custom made economy plugin a while back, which doesn't have enderchests implemented currently. I'll look into implementing this hopefully sometime soon.

**Comment by asyi0** [comment]
related issue
https://github.com/EarthMC/Issue-Tracker/issues/1475

**Comment by FixTheAdmin** [comment]
I'm not sure how I feel about paying from enderchests, they effectively make the currency virtual and that's what we wanted to get away from with our item based currency. Thoughts?

**Comment by Fruitloopins** [comment]
I feel like EMC is way too connected at this point for that to really make a difference, having to get your gold out of your echest to me just seems like a hindrance when you can teleport to most places in 3 seconds to just drop somebody gold. It's not even like having the gold out physically at a spawn adds a risk factor or something when we prohibit spawn trapping and you can't lose your items in a spawn area anymore.

On the contrary enabling this will prevent people from getting scammed by getting killed while someone else buys from their shop. And it lets people flex more easily.

**Comment by Warriorrrr** [comment]
Added this in a future version of our economy plugin.
