### ISSUE TITLE
[Feature] Change Custom Endstone Crafting Recipe

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1436]
### Is your feature request related to a problem? Please describe.

Many of the new crafting recipes for 1.17 blocks and items are much more logical than their old counterparts. For example, endstone costs 8 sand and 1 cobblestone to return a single piece of endstone, while Tuff and Deepslate cost 4 blocks for a return of 4 blocks.

### Describe the solution you'd like

The custom crafting recipe could instead return 8 or 9 blocks of Endstone. Maybe even 4 but atleast something that isn't as depleting of resources.

**Comment by Punkypal** [comment]
I thought this recipe was not so great also because sand requires the land to be strip mined to gather but cobblestone just piles up so much most players just drop it as trash. I'd suggest the recipe be **8 cobblestone**, but one **sandstone** in the middle

**Comment by Basically-Andrew** [comment]
The current custom crafting recipe structure makes sense, endstone isn't stone with a sandy core. It makes since sand with a cobblestone core makes endstone. Also changing the crafting recipe structure could confuse and frustrate the player base. Simply changing the return of pieces of endstone would be the only great way to solve this issue.

**Comment by Punkypal** [comment]
It isn't sand with a cobble core either. It's endstone. I don't think the recipe is good, and I think only getting one endstone for putting in nine basic "junk" blocks is fine. I think the recipe would be improved by using more cobble though and less sand so less sand strip mining is involved. Maybe make it two sand, two cobble = one endstone.
