### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by Gillypops** [EarthMC/Issue-Tracker#1437]
Hello EarthMC,

The last time I joined this brilliant server was about two years ago. I was banned for the use of a client.

Im ready for a new start to the server and have learnt my lesson. The use of a client is no longer an issue because I am rather ashamed of myself and will longer be if it happens again. 

Please let me know if you are able to get back to me!

Thanks,
Gillypops

**Comment by Basically-Andrew** [comment]
Please use the support Discord, this is only for technical issues.
You can join the support Discord via this link: https://discord.gg/EZBYmpp

**Comment by Gillypops** [comment]
> Please use the support Discord, this is only for technical issues.
> You can join the support Discord via this link: https://discord.gg/EZBYmpp

Thank you. I will do that
