### ISSUE TITLE
[Feature] Glow Berries Custom Recipe 

### ISSUE THREAD

**Issue by whatwhat989** [EarthMC/Issue-Tracker#1439]
**Is your feature request related to a problem? Please describe.**

Glow berries were not added in the recent adding of 1.17 recipes to EMC. They look really good for decoration and I think they should be added

**Describe the solution you'd like.**

I would like for there to be a custom recipe to craft glow berries. I think the I attached is a good solution. 
![Screenshot 2021-12-04 224946](https://user-images.githubusercontent.com/95559150/144764092-d4a56902-b89e-4df3-ada4-025abc35a3cd.png)

**Comment by Warriorrrr** [comment]
This recipe has been added a while back (but with glow ink instead), thanks for the suggestion!
