### ISSUE TITLE
/trade new possibility of trading nations and towns

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1446]
Current Trade plugin would have their own new feature which would be trading towns and nations

Only players which are in same town and the giver is the city mayor (receiver being a resident), or, two players are in same nation, and the giver is the king. (receiver is mayor).

I could make this feature if Warriorrr shared EMC's version of Trade System plugin myself

**Comment by Warriorrrr** [comment]
A suggestion like this would be better suited as a towny suggestion instead of one here, or could be made into a standalone plugin using my command addon API.

EarthMC does not use a fork of tradesystem, and I'd doubt the maintainers would add this integration.
