### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NotAndre1098** [EarthMC/Issue-Tracker#1447]
### Server

 Emc

### Describe the bug

 Mobs despawning

 Hostile Mobs that have been nametagged keep despawning, the plots perms are correct and I have checked numerous times to make sure there arent other mobs in the chunk either, no matter what I do the Hostile mobs keep despawning and its making mcmmo fishing really difficult 
 
### To Reproduce

1.  wait for a mob to spawn and nametag it 
2.  either move from the chunk or bring it somewhere and it will eventually despawn 
3.  

### Expected behavior

 u name tag the mob and as long as you don't put too many in the same chunk it wont despawn

**Comment by Warriorrrr** [comment]
Mobs despawning is not a large issue in my opinion, having less mobs loaded is actually better.
