### ISSUE TITLE
[Feature] Different color nation/town chat

### ISSUE THREAD

**Issue by Zyiah** [EarthMC/Issue-Tracker#1449]
It's hard to read town/nation chat when they are the same colors.

nation and town chat should have different colors from each other (maybe blue for nation and yellow for town)

hell, if it's possible maybe it could be customizable.

**Comment by OzzyKP1** [comment]
I'm not sure how feature requests and such work on GitHub, but I support this change.

**Comment by CorruptedGreed** [comment]
Returned town chat to original aqua color, will be implemented next changelog
