### ISSUE TITLE
 [Plugin] add buyable warps to the server.

### ISSUE THREAD

**Issue by lucasw2011** [EarthMC/Issue-Tracker#1450]
With the only means of transport being /n spawn or walking some popular area's of the server become saturated with nations because the towns of the area want people to be able to use their /n spawn to get to their towns. this is very prevalent in the north east united states area where there are 13 towns that boarder up to each other that are all nation capitols, from Chicago to Boston.
this issue is not just a north American issue it is also seen in Asia for example the Manchuria region with 11 nations in close proximity. nations also are forced to create "unions" which can be supported with discords but in game they Dont really exist you have no really way of telling who is with who unless they are color coded but not everyone can afford to do that.

The solution is easy the server could add purchasable player warps to allow empires to grow again instead of making links of nations to grow empires and keep traffic coming to popular area's like markets, farms, etc. a player would make a one time purchase to create a warp allowing people from anywhere to travel to their desired location. 

here are a few example of oversaturated area
![Screen Shot 2022-01-04 at 4 25 36 PM](https://user-images.githubusercontent.com/45434705/148126144-8ccaa9cb-9151-4344-be3a-323903b621bf.png)
![Screen Shot 2022-01-0
![Screen Shot 2022-01-04 at 4 26 06 PM](https://user-images.githubusercontent.com/45434705/148126167-39aa839a-8e8e-4c80-aee0-fbf0ffb7adaa.png)
4 at 4 25 50 PM](https://user-images.githubusercontent.com/45434705/148126161-6045d523-3699-42d5-bd2d-fb0c736a44a8.png)

**Comment by lucasw2011** [comment]
![Screen Shot 2022-01-04 at 4 26 06 PM](https://user-images.githubusercontent.com/45434705/148126322-3d66e42c-5875-42b7-95aa-182b149011b2.png)
also europe

**Comment by Colt44Magnum** [comment]
I like this idea, but implementing it where it actually effects the problem I think would be hard. Would the cost of a warp be the same as the cost for a nation? But then there's benefits for just purchasing a nation. If warps are made cheaper then they'd have to be significantly cheaper to also ward away from just purchasing a nation. But then we'll just have an oversaturation of warps in these already nation saturated areas.

**Comment by Colt44Magnum** [comment]
So its been over a year since my post before. Looking at other currently open posts I think can give a good perspective on this issue. #1465 #1635 #1627 

Allowing for the creation of 'Mega nations' could make way for the possibility for purchasable warps. Maybe the creation of a 'mega nation' would be required to purchase the warps.

I think further discussion on this topic could help with making our unhinged map painting issues go away.

**Comment by CorruptedGreed** [comment]
Reference #1627
