### ISSUE TITLE
[Bug]Losing named hostile mobs.

### ISSUE THREAD

**Issue by Saayuuki** [EarthMC/Issue-Tracker#1452]
### Server

Towny

### Describe the bug

Today i noticed all of my hostile mobs which kept in a boat and named gone.
I noticed the plotgroup where they was the mobspawn was off.
Yesterday the plot group where they was the mobspawn was enabled. 
I'm the mayor of the town and i dont switched the perms....
The loss is 
1 Witch
1 Zombie
1 Skeleton

### To Reproduce

I Do not have any idea about this incident.

### Expected behavior

Plot perms modified without my permission.

### Screenshots

![2022-01-02_13 29 06](https://user-images.githubusercontent.com/57344428/148650028-a39ab1c8-3be5-47ce-a045-217d8c1d7378.png)
![2021-12-09_19 26 47](https://user-images.githubusercontent.com/57344428/148650032-7321b831-db77-4e50-bacb-4bacf8416e0d.png)

**Comment by Warriorrrr** [comment]
The issue tracker is not the place to get mob refunds.
