### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Dieromancea6429** [EarthMC/Issue-Tracker#1453]
### Server

Towny

### Describe the bug

I had captured two spiders, one zombie, a skeleton, a creeper, an enderman, and a witch. I had an embassy set up in all of my residences because I immigrate frequently from one country to another. When I immigrated this time, believing it to be the case, all the land protections were removed. As a result, mob spawn was turned off and all mobs disappeared. All previous plot bugs were thought to be back to normal, but this time it looks like the embassy settings are still off. Please return the missing mobs to me. It took me a whole day to collect them...

### To Reproduce

1.plot bug has occurred in the state that you own the land where the embassy setting was made.
2.leave the country
3. The embassy setting is removed, so the ownership of the plot is released.
4. The mobs in the plot will disappear when the mob spawn is turned off.

### Expected behavior

I want my missing mobs back. I want you to use spawn egg to do so. I want you to put the witch on the right of the first picture, the enderman in the back, the spider on both sides of the second picture, the husk on the right of the third picture, the skeleton in the back, and the creeper in the glass of the fourth picture.

### Screenshots

![CC2F0934-3084-468E-B5E1-8963E0CC59BE](https://user-images.githubusercontent.com/97371026/148666620-d62ed068-87ac-4cf0-8b09-76ec8b0dd989.png)

![D84E90D3-37D2-41B4-8A1A-0E00109962D4](https://user-images.githubusercontent.com/97371026/148666581-09f93b0d-472b-4f48-b1f2-f236e51cc68a.png)
![854EFE55-DC00-4014-B6FB-2C4F3A0D35BE](https://user-images.githubusercontent.com/97371026/148666584-99cf7a28-0a7d-483d-ba02-8d2d3035c3b5.png)
![A392C452-47AF-48A3-9031-260270C738BD](https://user-images.githubusercontent.com/97371026/148666586-42ea6baf-03c8-4a96-91b1-05f37aad8784.png)

**Comment by Warriorrrr** [comment]
The issue tracker is not the place to get mob refunds.
