### ISSUE TITLE
hub and towny /seen are different

### ISSUE THREAD

**Issue by Jouvental** [EarthMC/Issue-Tracker#1454]
### Server

Towny

### Describe the bug

So i noticed that /seen is inconsistent with both servers hub and towny

### To Reproduce

type /seen and player and sometimes they will be different

### Expected behavior

joining different servers

### Screenshots

In hub:
![inhub](https://user-images.githubusercontent.com/97377648/148672116-55bd94bc-de55-473d-b0cf-e9fa057379e5.PNG)
:

In towny:
![intowny](https://user-images.githubusercontent.com/97377648/148672125-f05ab318-ad67-4c02-b4e3-881a31919c3a.PNG)

### Additional context

hopefully i did the screenshots right..

**Comment by jkmartindale** [comment]
Makes sense to me tbh, they're different servers

**Comment by Jouvental** [comment]
> Makes sense to me tbh, they're different servers

I'd rather log towns in hub instead of in towny wasting a slot for someone.

**Comment by Warriorrrr** [comment]
It is possible for players to join hub without joining towny.

**Comment by jkmartindale** [comment]
> I'd rather log towns in hub instead of in towny wasting a slot for someone.

You should be able to pull any info you need from Dynmap or bots like EarthMC Stats
