### ISSUE TITLE
anti looting-town feature

### ISSUE THREAD

**Issue by theJavaWolf** [EarthMC/Issue-Tracker#1456]
### Is your feature request related to a problem? Please describe.

It is becoming more and more common that seconds after a town falls someone creates a town in it's ruins to claim all the chests and prevent anyone else from looting. This method gives players who do not have their own towns a very unfair advantage towards ones that have their own town, because only people can create a town for looting purposes who can leave their current town at any moment.
The worst of it all is that these towns usually get handed over to a random person imidiately after the looting process or delete the town allthogether. 

### Describe the solution you'd like

Implement a delay or some kind of cooldown how long a mayor has to remain mayor of a town just created before stepping down as mayor or deleting the town.
If a person for example would have to remain for atleast 5 days in such a town which soul purpose is to loot it would prevent people from creating a new looting town on every new day.

### Additional context

If someone has a better solution to this problem, please suggest it.
Also do not forget to give feedback to this issue if you like the idea so this issue gets more attention by the staff!

**Comment by Warriorrrr** [comment]
https://github.com/TownyAdvanced/Towny/pull/5645

**Comment by Warriorrrr** [comment]
Towns deleted for inactivity will fall into ruin for 3 days before full deletion after next restart.
