### ISSUE TITLE
Add /playtime back into Earthmc

### ISSUE THREAD

**Issue by sndor** [EarthMC/Issue-Tracker#1457]
/playtime used to be a nice feature to see how long other people have played for. I know you can see your own playtime in statistics but it would be nice to add this back.

**Comment by Warriorrrr** [comment]
The main drawback of /playtime commands is that minecraft statistics don't account for tps loss. If you want to know how much playtime someone has, you can always just ask them.

**Comment by DuckEpik** [comment]
i want to know how long i hae played but i dont count so thats why we should add it back

**Comment by PlaceReporter99** [comment]
banana???

**Comment by CorruptedGreed** [comment]
This should be back once we have a dedicated plugin for it, not a priority but inevitably.
