### ISSUE TITLE
[Bug]Arrows despawn mid shot.

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1458]
### Server

Towny

### Describe the bug

when shooting an arrow the arrow may get deleted mid flight.

### To Reproduce

1. get a bow and arrow.
2. shoot it 40 blocks many times.
3. look around for lost arrow or do f3 and b to see the hitbox disappear even if your running after it.

### Expected behavior

the arrow is suppose to land and wait 5 minute to be picked up or despawn.

**Comment by Warriorrrr** [comment]
The arrow didn't despawn, it just left the tracking distance. If you walk to where it landed you'll be able to pick it up.
