### ISSUE TITLE
[Feature] Remove "jew" from the filter

### ISSUE THREAD

**Issue by ClonedCopier** [EarthMC/Issue-Tracker#1459]
### Is your feature request related to a problem? Please describe.

I initially commented on a closed issue from Nov 2021, but it's probably better to make a new one. It's been a while since I've used github. #1415

Jews call themselves the word all the time, and it's not an inherently derogatory word, even if it's sometimes used in derogatory contexts. Someone who wants to be antisemitic will do it regardless of whether or not they can say "jew" by saying "them" with triple parentheses or using an easy bypass like "jeu." This effectively stops jews from using the word without offering a good fix for the issue it was intended to resolve. Besides, allowing this innocent word and filtering #earthmc-towny with has:jew would be an easy way to find and reprimand toxic players.

### Describe the solution you'd like

Remove "jew" from the filter

**Comment by Warriorrrr** [comment]
Couldn't find the word "jew" in the filter, so I'll go ahead and close this as completed.
