### ISSUE TITLE
[BUG] Chest Shops aren't working.

### ISSUE THREAD

**Issue by wg93589** [EarthMC/Issue-Tracker#146]
**Server**
EarthMC TerraNova

**Describe the bug**
Chest Shops aren't working

**To Reproduce**
1. Go to a chest shop
2. Click on the sign
3. Nothing Happens

**Expected behavior**
1. Go to a chest shop
2. Click on the sign
3. A message in chat saying what the shop is selling, how much gold it costs and it asking you how much you want to buy appears in chat.

**Additional context**
1. You can tell a shop isn't working when the item that shows what is being sold isn't hovering above the chest

2. I'm not sure if it is server-wide but it has affected Chest shops in Newark and Seoul and others are reporting that their chest shops have broken

3. It also seems like you can't create new shops either.

**Comment by KarlOfDuty** [comment]
Should be fixed now.
