### ISSUE TITLE
[Feature] Put something in the lobby that directly addresses teleportation being tied to nation status

### ISSUE THREAD

**Issue by ClonedCopier** [EarthMC/Issue-Tracker#1461]
### Is your feature request related to a problem? Please describe.

Every day, many new players ask about teleportation and how to join a town. I'm pretty sure the prompt message when you /t invite someone tells the invited player how to join a town, so there's not much that can be done about that one, but the fact that teleportation is tied to nation status is not the first thing you see in the /docs. It's the 10th section down, and it's in the last sentence of that section. Most people joining a server for the first time probably don't want to read its documentation in a separate webpage, and those who do bother reading it will likely skim it or read a portion of it. If it were somehow addressed in the lobby, it would likely reduce the frequency of this question being asked in global.

### Describe the solution you'd like

It could be a line from one of the NPCs or be written on sign. It would probably even help if the docs were transcribed somewhere in-game.

**Comment by Colt44Magnum** [comment]
yeah its almost like the old queue had a tutorial section for the server, too bad it was hidden behind a waterfall right at spawn that I never noticed until 6 months after I started playing. I have no idea why there isn't a tutorial in this queue either. Like they have the spots with text saying its just a placeholder, why don't they just use that.

**Comment by AndrewCheedle** [comment]
I agree with you, they can also add those informations to the book given to new players when they first join. That book has outdated info so it would be nice to get a remake.

**Comment by CorruptedGreed** [comment]
EMC docs can be tied to Fix book directly if not already the case
