### ISSUE TITLE
[Feature] Let people in a nation teleport to other towns in the nation

### ISSUE THREAD

**Issue by TheCoc0nut** [EarthMC/Issue-Tracker#1462]
### Is your feature request related to a problem? Please describe.

It is not related to a problem. However, it is annoying that if you have to visit a town on the other side of the nation, you have to take an ice road or just walk

### Describe the solution you'd like

Similar to the /n spawn feature, residents of a nation would be able to teleport to other towns in the nation. I am sorry if this has been sugested this before

**Comment by Warriorrrr** [comment]
Afaik, this is not something the admins want to enable.
