### ISSUE TITLE
[Bug] Crossbows Will Not Work

### ISSUE THREAD

**Issue by N3G4T1V2** [EarthMC/Issue-Tracker#1464]
### Server

Towny

### Describe the bug

Whenever a crossbow is drawn, upon firing, the arrow does not appear nor do damage.
Please note that bows, however, _do_ fire properly.

### To Reproduce

This can occur in any location including wilderness(nether too) and towns, even those with PVP enabled.

1. Acquire an Arrow and a Crossbow
2. Hold the right mouse button
3. Click it once again to release the Crossbow

Upon firing, nothing happens, excluding the crossbow returning to the unloaded position.

### Expected behavior

I expected the crossbow to spawn an arrow projectile after use.

**Comment by Warriorrrr** [comment]
Unable to reproduce, you probably just need to hold right click longer because of lag. I can add something that lag compensates the draw time, but that's unrelated to this issue.
