### ISSUE TITLE
Stop changing player cap

### ISSUE THREAD

**Issue by lucasw2011** [EarthMC/Issue-Tracker#1466]
### Is your feature request related to a problem? Please describe.

Player cap has been changing once or twice a week for the last few weeks

### Describe the solution you'd like

I believe this is due to fix trying to find the magic number so that the queue world isn’t being overlooked and wasted with all that work put into it. Instead of changing it have players join the queue world no matter what instead of being sent to towny and use it as a hub if The server is under limit. Players would have to walk into a portal to join the towny world or do something to send themselves there this would force people to observe the queue world and would allow the towny world cap to be increased if the cap is met the queue is used

**Comment by AndrewCheedle** [comment]
The increase and decrease of the player cap is probably more tied to server lag and mobs being added and not related to queue. The mobs have been disabled and player cap is decreased so I believe fix is experimenting to find the right cap for least lag.

**Comment by QJWIN** [comment]
As i know Fix say himself in the server chat, there is recently a new server network, and he say they tested it for a week ...
and the queue and the towny was 2 different server so you cannot add the queue cap to the towny cap ...

For let a maximum of feature and get the max of player they should let 150-160 ppl cuz minecraft was not developed for more ^^

**Comment by Warriorrrr** [comment]
The current cap has been at 150 for a while, and it's been pretty "stable". Probably won't change for a while.
