### ISSUE TITLE
[Bug] Redstone tick delay

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1469]
### Server

Towny

### Describe the bug

In Earthmc the piston take like 5 to 6 sec for back at is original position witch is in my circuit extended

### To Reproduce

when you trigger a button attached to a piston
the normal execution is a contraption of the piston
who get in and out in 1 sec or a bit less

### Expected behavior

I have engineering a machin  in redstone who send a redstone pulse to a piston in the air, to let the piston drop 1 anvil per 1 anvil
where all anvil was stock in the top of each other

Then  i stend under it and takedomage dimond helmet in chain every 1.2 sec .
When i get enoff broken helmet, i repair them into a iron block and this way i farm the mcmmo repair skill

### Additional context

The problem apear with everything like door, if you toggle a door with a button the door will take 5 to 6 sec to close, the problem was the tick delay for redstone, that very anoing cuz if you open a door with button or pressure plate you have to wait to make sure no one follow you ...

Fix this plz

**Comment by Warriorrrr** [comment]
This is expected, lower ticks per second means things will take longer to happen.
