### ISSUE TITLE
[Bug] Redstone breaks constantly

### ISSUE THREAD

**Issue by ClonedCopier** [EarthMC/Issue-Tracker#1470]
### Server

Towny

### Describe the bug

Anything redstone-related will not work consistently. I have a connect 4 machine that works reliably in vanilla, but after a couple of uses on this server, some random part of it will break. Redstone torches that are powered infrequently (unless you're doing a connect 4 speedrun) will be deactivated and stay deactivated until I force a block update. Powered redstone dust wiring will break abruptly despite being fewer than 8 blocks long. I'd force block updates with pistons automatically to fix this, but that redstone mechanism would probably break too. This is all in the same chunk.

### To Reproduce

Do anything with redstone

### Expected behavior

Redstone should work consistently

### Screenshots

https://cdn.discordapp.com/attachments/242690021788876810/941389605557645372/unknown.png

https://cdn.discordapp.com/attachments/242690021788876810/941173930826297364/unknown.png

https://cdn.discordapp.com/attachments/242690021788876810/941394986635755520/unknown.png

**Comment by MrToirol** [comment]
I had the same issue where in a single chunk, the redstone would simply stop and wouldn't power, for example of I press a button or switch a lever. I don't think it's linked with chunks unloading, because I saw my redstone contraption stopping right in front of me.

**Comment by CorruptedGreed** [comment]
Unable to replicate redstone breaking currently, make a new issue with coordinates to affected area if this persists
