### ISSUE TITLE
Adding trade to merchant

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1471]
### Is your feature request related to a problem? Please describe.

no problem

### Describe the solution you'd like

i wanna see some item we cannot obtein in the game, into the merchant trade sutch as :

- x16 spore blossom [flower no duplicable with bone meal]
- x16 small dripleaf
- x4 Budding Amethyst

**Comment by Warriorrrr** [comment]
Merchant trades will not be changed anymore on nova probably, once nova updates to 1.18 or above these items will all become available anyways.
