### ISSUE TITLE
Can't use any commands [Bug]

### ISSUE THREAD

**Issue by WildStudios1** [EarthMC/Issue-Tracker#1472]
### Server

Towny

### Describe the bug

Many of the useful commands that I need to use, such as /n spawn or /t spawn, won't work, and it says that I don't have permission to use them.

### To Reproduce

/n spawn New_York

### Expected behavior

to get traveled to new york, wont happen

### Screenshots

![image](https://user-images.githubusercontent.com/99846847/154374302-80ecd581-f5f2-4c38-bcc4-a510d7507d25.png)

### Additional context

just joined the server for the first time in more than a year

**Comment by Warriorrrr** [comment]
You need to be in a town in order to use /n spawn and /t spawn.
