### ISSUE TITLE
Pls fix the biome placement 

### ISSUE THREAD

**Issue by Itzsome1** [EarthMC/Issue-Tracker#1474]
### Describe the issue

Most of Antarctica has biome ocean
Arctic Ocean is not frozen or cold ocean
And I forgot wats the biome for Sahara but I’m sure not all of it is desert or badlands 

pls make all of Antarctica snowy tundra 
Make the mountains snowy mountain
And the shore snowy beach or frozen ocean

 Make Arctic Ocean  cold/frozen ocean or deep cold ocean

make most of EU North America and Russia  forest or forest hills or anything but forest biome

### Coordinates

… anywhere but the places I said 

### Screenshots

*

**Comment by ZGamerz123** [comment]
How would this be fixed?

**Comment by Itzsome1** [comment]
> How would this be fixed?

…
Change the biomes like the one I mentioned
