### ISSUE TITLE
[Bug] Economy plugin bug loosing golds

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#1475]
### Server

Towny

### Describe the bug

When you'r inventory is full, and some one buy something in one of you'r shop, all tthe gold was drop in the ground ...
That a real problem, because if you are afk let say 3 min and you dont see some one buy you a item, few unwanned think can append, some one stole you gold or you dont see the item on ground and he vanish ...

That olso provide a hudge issue like :

lett say you are AFK into you own shop :
well i came i drop 30 stack of dirt in to you feet than you inventory became full so if during you still being AFK i buy all you items i can take my gold back and make you shop empty without spend any gold ... 

That a real problem ...

### To Reproduce

make you inventory full and ask some one to buy into one of you'r shop

### Expected behavior

i expect the plugin change :
instead drop the gold on ground if you inv is full, place it at the same place when we are offline to get it back with /claim !

**Comment by asyi0** [comment]
It is not a good feature that gold suddenly pop into my inventory when someone buy items at my shop.
This annoying feature restricts shop owner. If a player who have shop own unnecessary risk when go to pvp area, and also abuseable for scam.

scam example:
https://www.youtube.com/watch?v=4Lxp5G4wXNw&t=54s

All shop sales gold should go into virtual bank like while offline, and only gettable by /claim command.
Also, gold for buying shop should also be withdrawn from the virtual bank. It is trouble to have to keep gold for buying on hand.

**Comment by Warriorrrr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Riksbank Upgrades](https://trello.com/c/jn46G9fy/2-riksbank-upgrades)

**Comment by Warriorrrr** [comment]
This has been fixed in a future version of our economy plugin, gold will go into your /claim instead of to the ground.
