### ISSUE TITLE
 features  for queue

### ISSUE THREAD

**Issue by Itzsome1** [EarthMC/Issue-Tracker#1477]
### Is your feature request related to a problem? Please describe.

The queue is boring
New players leave just before they joined towny cus they don’t know that they were in queue not on towny
You cant talk to anyone in queue
You cant tp to anyone in queue 
Some info holograms are in cursed spots that even no one can see

### Describe the solution you'd like

Tell the players that their in queue with tittle saying welcome and subtitle your currently in the queue (title <targets> (title|subtitle|actionbar) <title>) if the queue is more than 1 player in it

Allow chat on queue 
Allow tpa on queue

move the cursed holograms to near spawn

### Additional context

Also pls make max player cap higher

**Comment by ZGamerz123** [comment]
Several problems:
As soon as you join the queue, you get a chat message saying you are in the queue for towny, and are in this position, how would you not know?
You can talk to people in the queue
Which holograms are hard to see?

**Comment by jkmartindale** [comment]
> Which holograms are hard to see?

The rules hologram is pretty absurd

![image](https://user-images.githubusercontent.com/11380394/155869253-1e13ef33-d404-427f-8ea5-8109209415e2.png)

**Comment by Itzsome1** [comment]
> the
….
Bro players that don’t speak English mostly don’t notice
And most new players just ignore chat

**Comment by Itzsome1** [comment]
I saw non English speaking YouTubers just left before they join towny and say that the server is bad cus they don’t know its the queue

**Comment by CorruptedGreed** [comment]
Chat is disabled to avoid advertising, tpa requests to avoid unnecessary spam as well
