### ISSUE TITLE
[World] Remove the Eiffel tower from Queue world

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1479]
### Describe the issue

The Eiffel tower no longer exists and should not be used in the queue world. There have been three different variations of the Eiffel tower before and even when they existed they weren't used in the queue world. I think then it makes sense that the queue world remove it as it no longer exists. 

### Coordinates

219, -8954
(that is coords for where the Eiffel tower used to be on the server
I couldn't get the coords in the queue because I purchased premium and the server is so empty I get insta moved into the towny server. 

### Screenshots

![image](https://user-images.githubusercontent.com/51977107/156450407-1221e30e-21e0-4e91-b5bc-23aff773c702.png)

**Comment by Fruitloopins** [comment]
half the things in hub don't exist in game

**Comment by PoppyK** [comment]
I didn't make the queue based off of what I saw in towny.  This was solely based on me representing continents and within that, countries.  I wanted the queue to represent what a geopolitical server hub would look like and get players excited to establish their own identity within a country/nation. 

I was also hoping to inspire players to build more historical and national monuments in-game.  I'm excited to see more of these monuments being built on the map.

**Comment by ZGamerz123** [comment]
_I couldn't get the coords in the queue because I purchased premium and the server is so empty I get insta moved into the towny server._
1st world problems 😞

**Comment by jkmartindale** [comment]
add huge nintendo ds to hub world
