### ISSUE TITLE
[Feature] If a user leaves for 41 days +/ Is banned nation owners can put a leader incharge

### ISSUE THREAD

**Issue by AidanMSad** [EarthMC/Issue-Tracker#148]
**Is your feature request related to a problem? Please describe.**
I am frustrated when a town that is close to me, the owner leaves becomes inactive or becomes banned. I am located in the pearl river delta and all of our towns are really dence and kcod got banned for a hacked client and the town of hong kong is buzzying with people who want to own it who is in it right now.
**Describe the solution you'd like**
For users to either have command to make a town user in the town to own the town with a command
/n set mayor [town] [user]
or to dm staff to do it.
If a town does not have anyone i can do /n set mayor [town] [user]
and it shows *Vented has requested you to become mayor on the town of [town name]

**Additional context**

**Comment by KarlOfDuty** [comment]
If a player is permanently banned and has had their appeal we can put a leader in charge, towny already does that if they leave for 42 days.
