### ISSUE TITLE
/bottle get max [Bug]

### ISSUE THREAD

**Issue by MuratBB** [EarthMC/Issue-Tracker#1480]
### Server

Hub

### Describe the bug

I wrote /bottle get max but I didn't get it because my inventory is full. Where are my XPs?

### To Reproduce

/bottle get max

### Expected behavior

I wrote /bottle get max but I didn't get it because my inventory is full. Where are my XPs?

**Comment by QJWIN** [comment]
There is no bug and you can close this issue !

i made some test and when  you type /bottle get max with a full inventory, 

ALL THE BOTTLE WAS DROP INTO THE GROUND  !!!

So if you not take it well all you xp was gone ...

**Comment by Warriorrrr** [comment]
^, Experience bottles that don't fit in your inventory will be dropped on the floor instead.
