### ISSUE TITLE
[Bug] bug in vote link from servers-minecraft.net

### ISSUE THREAD

**Issue by Absholem** [EarthMC/Issue-Tracker#1483]
### Server

Towny

### Describe the bug

Problem with vote link https://servers-minecraft.net/server-earthmc.1042/vote
When the timer in "You can vote for this server again in:..." goes to 0, it goes back to 24h countdown without letting me vote. Most likely problem with the site itself.

### To Reproduce

What for timer to reach 0

### Expected behavior

No vote section and timer back to 24h

### Screenshots

![image](https://user-images.githubusercontent.com/101382461/157808008-2ae02e91-a24c-4876-bdb6-2d3026fa6c0d.png)

**Comment by jkmartindale** [comment]
EarthMC has no control over the vote website code. You'd need to contact the website itself, though I can't figure out their contact info.
