### ISSUE TITLE
Previous versions can't join (ViaVersion + Viabackwards has been removed)

### ISSUE THREAD

**Issue by Aneroo** [EarthMC/Issue-Tracker#1484]
On the website it says that you can join using any version, but joining in 1.16.5 is apparently an outdated version for the server which runs in 1.17.1. I noticed this because my PC doesn't support 1.17+ so I used 1.16.5 to join, and I got a client outdated error. The problem is that ViaVersion + ViaBackwards has either been disabled, corrupted, or removed from the server.
![image](https://user-images.githubusercontent.com/87947231/157935937-c3fbf9e8-9266-4934-89a3-115178374de4.png)

**Comment by Warriorrrr** [comment]
The text on the website was a bit outdated, should be updated soon. You'll have to use 1.17 or above to connect.

**Comment by Aneroo** [comment]
> The text on the website was a bit outdated, should be updated soon. You'll have to use 1.17 or above to connect.

What about installing ViaVersion + ViaBackwards?

**Comment by Warriorrrr** [comment]
Viaversion is already installed, and I *think* Viabackwards used to be installed, but got removed ages ago. Not a big fan of it myself personally because of how hacky it is.
