### ISSUE TITLE
Queue priority 

### ISSUE THREAD

**Issue by Lopacangaj** [EarthMC/Issue-Tracker#1485]
### Is your feature request related to a problem? Please describe.

People with queue priority not having a colour 

### Describe the solution you'd like

Basically i bought queue priority and it will be nice if people with queue priority will have a coloured name in game like people with premium have.
Please give us a colour 
Thank you for your time and help and i hope my idea gets added soon

-Lopacangaj

**Comment by FixTheAdmin** [comment]
Thanks for the feedback. Queue priority will not get a special color in chat, that is exclusive to players that pay for premium.
