### ISSUE TITLE
[Feature] Realtor rank

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1487]
### Is your feature request related to a problem? Please describe.

There is currently no way to allow a player to sell plots in a town to new citizens without giving them many more perms in the town.

### Describe the solution you'd like

A rank possibly named Realtor that can set plots for sale in a town that are not currently owned, take them off of sale and possibly set them as embassies too but nothing else. It could compliment the recruiter rank nicely to let trusted citizens get new players integrated into their town while not giving the recruiter perms to touch every plot they want.

### Additional context

Not sure if there are permission nodes that could allow just the sale of unowned plots, and some thought would need to be put into making sure this can't be abused in unforeseen ways before introducing it.

**Comment by Warriorrrr** [comment]
Currently, Towny only allows players to set up plots for sale that they personally own. The towny.command.plot.asmayor allows players to bypass the ownership test, but this would make towny treat the realtor as the owner of every plot in the town. I think adding a towny.command.plot.unowned node could probably work.

**Comment by Basically-Andrew** [comment]
@Warriorrrr Has `towny.command.plot.unowned` node been added to Towny. If so this should be an easy config change.

**Comment by Warriorrrr** [comment]
It was added in https://github.com/TownyAdvanced/Towny/pull/5836, but I'm not sure if realtor would be the best name, since it also gives access to /plot set and /plot toggle in unowned plots.

**Comment by Basically-Andrew** [comment]
With those permissions, maybe the town rank could be called Surveyor.

**Comment by Fruitloopins** [comment]
Realtor sounds fine to me still, those perms wouldn't even add that much more. /plot set could let them turn on switch perms for themselves or whatever but they can already claim the plot and do that anyways and /plot toggle isn't very damaging either unless I'm missing something.

**Comment by Basically-Andrew** [comment]
Since no one else has commented a concern, I still think Relator is a well enough name. This can be quickly added in the [Townyperms.yml](https://github.com/TownyAdvanced/Towny/wiki/Default-Townyperms.yml).
```yml
    Realtor :
    - towny.command.plot.unowned
```

**Comment by Fruitloopins** [comment]
@CorruptedGreed
