### ISSUE TITLE
[Mechanic] Gain Herbalism Experience while in Minecarts

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1488]
### Is your feature request related to a problem? Please describe.

If you use minecarts to move around and harvest a farm, you do not receive any MCMMO Herbalism experience. This issue makes it difficult to quickly harvest huge farms and grow Herbalism simultaneously.

### Describe the solution you'd like

Disabling [Prevent_AFK_Leveling](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L384) from the Config.yml would allow players to use minecarts and gain Herbalism experience.

### Additional context

I don't believe this would become an issue of players AFK bypassing. As far as I am aware, the AFK bypass can only be bypassed by users rotating their heads and not just moving, jumping, etc.

**Comment by Warriorrrr** [comment]
Prevent_AFK_Leveling is already set to true in the config

**Comment by Basically-Andrew** [comment]
That's why I'm suggesting it be disabled and set to false. With it set to true currently player can't gain Herbalism in minecarts.

**Comment by Warriorrrr** [comment]
Intentionally enabling afk farming is not something I want to do.

**Comment by pigeon-rock** [comment]
can i get unbanned? all i said was nuggar, which means a cargo sailboat in the nile
