### ISSUE TITLE
[Feature] Auto-expiring town invites.

### ISSUE THREAD

**Issue by Moldytzu** [EarthMC/Issue-Tracker#1489]
### Is your feature request related to a problem? Please describe.

I hate when I'm trying to recruit and I can't because I've sent too many invites 1 week ago. I have to spam `/t invite -<name>` which is a very tedious procedure.

### Describe the solution you'd like

Make invites expire after 1 hour.

**Comment by Warriorrrr** [comment]
https://github.com/TownyAdvanced/Towny/issues/new/choose
