### ISSUE TITLE
[World][Terra Aurora] No teleportation and gold upkeep

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#1490]
### Is your feature request related to a problem? Please describe.

As Terra Nova will not be retired but will rather be an alternative, Terra Aurora should be substantially different so that there is a reason to choose one of the servers over the other. My prediction is that new players will choose Terra Aurora, as overclaiming has not taken over the server yet, effectively just reducing traffic to Terra Nova. To distinguish the two servers I propose the following:

### Describe the solution you'd like

- No teleportation. Have it be the harder server with more immersion which is what got many people interested in EMC in the first place. If you want teleportation, play on Terra Nova.
- 1 gold per chunk per day upkeep. To reduce overclaiming and large inactive stretches of claimed land. If you want a large town without grinding for gold, play on Terra Nova.
- I doubt anything further than this would be applied but read my old GitHub post for inspiration (where I also suggested a price hike in nation cost, which is added now):
https://github.com/EarthMC/Issue-Tracker/issues/840

**Comment by DeadGlamour** [comment]
I have honestly lost hope over this server, this reset is exactly what I expected a reset to be, a lousy and lazy reset simply to wipe the canvas rather than doing anything new, we don't have siege war, we don't have a new map, nothing new, hell, some even say mcmmo won't transfer.

**Comment by alekb1** [comment]
Yeah feel the same way, back when Terra Nova was announced town tp was disabled, nations became regional, the end was removed, and town outposts were disabled, all huge things which ultimately restricted but improved the experience a lot, I just wished that they would have the balls to do something huge again instead of just doing the equivalent of relaunching Skyrim on a toaster

**Comment by CorruptedGreed** [comment]
Fix is not a fan of upkeep and no teleportation seems very hardcore (assuming this was just for Aurora launch as well anyways).
