### ISSUE TITLE
[Feature] Buff fishing

### ISSUE THREAD

**Issue by AndrewCheedle** [EarthMC/Issue-Tracker#1491]
### Is your feature request related to a problem? Please describe.

Fishing in emc has always been a side hustle and was always either underrated or even downright prevented. Fishing in emc has been nerfed for years and every time an update about mcmmo came, it was always to nerf fishing. I have talked with warrior and people in the past made github posts about this issue as well but most of the time it was dismissed and not cared by the staff. Now with terra Aurora on the horizon, I propose fishing to be buffed. 

### Describe the solution you'd like

There are several ways fishing can be buffed. The first option is going back to BreachDGates' post about fishing drops and use his suggestions for start. The second is increasing the mob drops you can get from shaking and enabling shaking. It would also help if you could salvage gold items you get from fishing, even if it's like 2 gold nuggets per piece or something similar. It would make fishing reasonable to grind and another mechanic for the player to engage in whenever they are bored to make builds etc.

**Comment by docwhomc** [comment]
#1333

**Comment by Colt44Magnum** [comment]
I really wanted to get fishing into queue back in the day and I look forward to getting a buff to fishing on Aurora as well. With less need for shake now that mobs can spawn Fishing is in dire need of some love.

**Comment by Aylywyn** [comment]
Simple copy/paste of my side of a Discord thread called "Add Conduit".

How common do you think they should be?  A custom recipe is probably the way to go.  Medium could be Beacon+8 Nautilus Shells=Heart Of The Sea then 8 more Shells to a Conduit.  Easy would swap the Beacon for an Ender Pearl and 4 of the Shells for Lapis.  Hard might be... uh... 4/5 Beacons+5/4 Nautilus Shells=Heart Of The Sea.

Throwing out controversy while here...  Sponge = 5 Horn Coral Blocks + 4 Smooth Quartz Blocks (yellow bumpy sea blocks plus heated quartz (basically silica gel)).

So you'd go the Easy route and have a recipe like Heart Of The Sea = Ender Pearl + 4 Nautilus Shells + 4 Lapis (a sphere plus ocean stuff plus blue stuff,  that conveniently costs about the desired amount).  Then HOTS + 8 NS = Conduit.    And, yeah I agree, that puts a Conduit at around the current cost of a Beacon, maybe 12g.

Ignore the Sponge bit.  Or rather don't :-) ...

**Comment by Colt44Magnum** [comment]
> Simple copy/paste of my side of a Discord thread called "Add Conduit".
> 
> How common do you think they should be? A custom recipe is probably the way to go. Medium could be Beacon+8 Nautilus Shells=Heart Of The Sea then 8 more Shells to a Conduit. Easy would swap the Beacon for an Ender Pearl and 4 of the Shells for Lapis. Hard might be... uh... 4/5 Beacons+5/4 Nautilus Shells=Heart Of The Sea.
> 
> Throwing out controversy while here... Sponge = 5 Horn Coral Blocks + 4 Smooth Quartz Blocks (yellow bumpy sea blocks plus heated quartz (basically silica gel)).
> 
> So you'd go the Easy route and have a recipe like Heart Of The Sea = Ender Pearl + 4 Nautilus Shells + 4 Lapis (a sphere plus ocean stuff plus blue stuff, that conveniently costs about the desired amount). Then HOTS + 8 NS = Conduit. And, yeah I agree, that puts a Conduit at around the current cost of a Beacon, maybe 12g.
> 
> Ignore the Sponge bit. Or rather don't :-) ...

With BreacheDGates #1333 Heart of the Sea would be obtained through a high level of fishing, and have a low chance of getting it. I think adding it to fishing might be a better way than just having a crafting recipe.

**Comment by Aylywyn** [comment]
A buff?  Fishing is already a great source of gold and netherite and rare books and impossible gear.   Plus, other materials/ingredients.  What more do you need?

**Comment by Colt44Magnum** [comment]
According to the treasure.yml netherite isn't on the list unless the file isn't the same as the one on the EMC.mcmmo fork

**Comment by Aylywyn** [comment]
It is most definitely not that chart you have posted.  It is also incorrect on both Books and Records.  And probably more things I didn't have patience to bother to find.

**Comment by Colt44Magnum** [comment]
Okay so then we need @Warriorrrr to update the file on github with the one on the server. That way we can actually see what it is

**Comment by Aylywyn** [comment]
Why should they reveal that?  Um...  Fish around and find out.

**Comment by Colt44Magnum** [comment]
Because it's actual data, obviously the old one was posted before it was updated. I don't see why the new one wouldn't be posted then.

**Comment by Aylywyn** [comment]
You're going to shocked at the data that isn't posted if you think something as complex as Fishing should be immediately published...

**Comment by Colt44Magnum** [comment]
How is fishing complex, it's values are just defined within the treasure.yml 

Also updating/'publish' the files on github is incredible easy. Especially if they aren't even using the current github files. It's just deleting the old one and inserting the new one. There's no issues with needing to make sure other things aren't broken

**Comment by Aylywyn** [comment]
I'm very sleepy going on cranky so this might be brief...

Who says it should published?  Maybe you gave to work it out as a community as a "team-building exercise"?  What's the Passive Mob Chunk Limit?  How many Item Frames or Pistons in a chunk?

Every change will effect everything.  Let's say you add Sponge... what percentage drop will collapse the future banked wealth of those hiardingcall the Sponge?  Just how pissed off will they be, would they quit?  Bump up Netherite a fraction of a percent or two what will that do to the Market?  Add bloody Emeralds to counteract the so-called "Emerald Crisis" and how does that affect Emerald prices and the flow of money?  Hiw mu h more Mending will be available, and at what new lower price?  Put a Consuit in there...  just what the heck would that do and how do we get the desired price at what drop rate?

But, yes, just drop a table into a text editor and whip out a few small changes, eh?  Do go on...

**Comment by Colt44Magnum** [comment]
Cope dude, 

All I asked was for the current one to be posted. All the things you threw into your 'well thought out' paragraph are things you complained about and argued crafting recipes could work for. Yes within a system changes effect everything thank you for the big brain statement. 

You also act like the server admins have never made choices that effected prices of items drastically. Welcome to EMC bud. Enjoy your time here and remember Lag is a feature.

**Comment by AndrewCheedle** [comment]
I will be making a detailed edit or new post about this to consider all the possible changes and how to balance them so it is easier to debate on and consider a reasonable change rather than just my rant here

**Comment by Fruitloopins** [comment]
@CorruptedGreed you should do this and add heart of the sea since it's thematically consistent, and you can close all of these tickets: #1686 #1604 #1333 #343

and you can add some of this stuff to fishing too maybe #1563
