### ISSUE TITLE
[Bug] /map gives old link that no longer works (Nova ofc)

### ISSUE THREAD

**Issue by Hedwig7s** [EarthMC/Issue-Tracker#1492]
### Server

Towny

### Describe the bug

/map gives old link that no longer works
Just gives a 404

### To Reproduce

Run /map
Follow link

### Expected behavior

I expect to get the link to the world map

### Additional context

(not really a bug but oh well)

**Comment by Basically-Andrew** [comment]
Should've been fixed by Warriorrrr in [commit](https://github.com/EarthMC/EMCTools/commit/a350bac4dd3a2f8584896d384efe8315dc4203b3).

**Comment by Warriorrrr** [comment]
Cannot reproduce, works fine for me.
