### ISSUE TITLE
[World] [Aurora] Eastern Europe Rivers

### ISSUE THREAD

**Issue by mihinal** [EarthMC/Issue-Tracker#1494]
### Describe the issue

Some important rivers in Eastern Europe need to be widened a bit, they arent visible on the map. The rivers i saw that needed work were the Tisza, the Danube (mostly the delta) , the Siret, the Prut and the Dniester. Also as an aside there are some wierd mesa biome spots in Australia and Africa.

### Coordinates

4990,-8416 (for Danube)
8248,-1516 (Africa mesa)
25054,4630 (Australia mesa)
3630,-9827 (Vistula)
3516,-8642 (Tisza)
4821,-8677 (Siret)
5184,-8884 (Dniester)

### Screenshots

![unknown](https://user-images.githubusercontent.com/47060356/166118146-3f48c76e-3122-44d9-8b26-c3256b8d8a2e.png)
Panama Canal
![Screenshot_3_LI](https://user-images.githubusercontent.com/47060356/166118148-71ad57aa-6e35-4151-9cec-da51cf4decca.jpg)
Areas on the Danube that need widening, mostly different arms of it
![Raurile-din-Romania](https://user-images.githubusercontent.com/47060356/166118472-37e2610d-b38e-4a62-b3ce-db1367e47368.jpg)
these rivers are the main ones,the ones in thick blue, I would be very thankful if you could add them
![Romanian_states_in_the_9th-13th_centuries](https://user-images.githubusercontent.com/47060356/166137283-c1a54a15-62ad-4618-83c4-4acbf814f4bb.svg)
clearer photo of romanian rivers
![a-l-Schematic-picture-of-the-Danube-Black-Sea-Canal-red-with-the-original-river_Q320](https://user-images.githubusercontent.com/47060356/166137155-402c5cf8-aefd-4495-974b-150e079b8503.jpg)
danube areas that need fixing + danube black sea canal

**Comment by superiorglitch** [comment]
Other incorrect biomes include:
Jamaica (missing a biome completely)
Isla de Juventud (has a biome from when it was terraformed)
Leeward Antilles (Aruba, Curaçao, Isla Margarita)
some of The Bahamas (Nassau, Exuma Island, Long Island, Mayaguana)

also not sure why the Galapagos were changed to be jungle biome, they are more authentic as that desert/mesa biome that they were before

I hope they can be fixed!

**Comment by mihinal** [comment]
minor nitpick
![Screenshot (16)_LI](https://user-images.githubusercontent.com/47060356/168278980-fd8a8418-ad7e-4ce3-a099-73dd403e8344.jpg)
= the swamp borders could use some smoothing 
sorry for being so persistent but i am passionate about the swamp
