### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by diamond101ladylb** [EarthMC/Issue-Tracker#1497]
### Server

Towny

### Describe the bug

I use a silk touch pickaxe try to relocate the spawner but it disappeared. My name is Diamond101ladylb, my XYZ: -216/66/-9558, In Brighton and it happened about 10 minutes ago. Please help me, thank you very much. -Aurora- 

### To Reproduce

Items disappeared 

### Expected behavior

Should be able to pick it up

**Comment by Warriorrrr** [comment]
According to the logs, you broke a spawner but didn't use a pickaxe.

**Comment by diamond101ladylb** [comment]
I used A silk gold pickaxe.
