### ISSUE TITLE
[Bug] [Aurora] Outsiders have Permissions to take & place water/lava in Cauldrons

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1499]
### Server

Towny

### Describe the bug

Outsiders have permission to take and place water/lava in cauldrons.

### To Reproduce

1. Place a cauldron in town claims.
2. Place water/lava in the cauldron.
3. Hava an outsider pick up lava from the cauldron with an empty bottle or bucket.
4. Outsider now has a bucket of water/lava and the cauldron is now empty.
5. Outsider places water/lava in empty cauldron.

### Expected behavior

An outsider shouldn't be able to place or pick up water/lava from a cauldron.

**Comment by Warriorrrr** [comment]
Will be resolved by https://github.com/TownyAdvanced/Towny/pull/5901
