### ISSUE TITLE
[Bug] Diplomats can't view Ally Request Messages

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1501]
### Server

Aurora

### Describe the bug

Diplomats aren't displayed messages by Towny when an ally request is sent to their nation.

### To Reproduce

1. Have another nation send an ally request
2. Diplomats of the nation won't see the message but the leader will

### Expected behavior

Diplomat see all ally messages by Towny

**Comment by Warriorrrr** [comment]
https://github.com/TownyAdvanced/Towny/pull/5903
