### ISSUE TITLE
[World] Add Flower Forests to Aurora

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1502]
### Describe the issue

AFAIK Flower Forests don't seem to be on Aurora. I've checked several locations and talked with a few staff members and it seems there are no flower forests. This makes it impossible to farm flowers.

### Coordinates

N/A

### Screenshots

N/A

**Comment by Warriorrrr** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/151#issuecomment-468705451
