### ISSUE TITLE
Rule 3.3 Town Claims

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1504]
### Is your feature request related to a problem? Please describe.

Since the launch of Aurora, players have begun mass abusing the structure of [Rule 3.3](https://earthmc.net/docs/rules/#33-town-claims). The rule defines a claim arm as a

> protrusions which are often used to block the expansion of other towns _or_ just _**artificially expand the area a town controls without the need to claim all of it.**_

This would mean it is against the rules to claim several chunks extending from my town even if the claim arm isn't claim blocking any other towns. Surprisingly this isn't the case. The last paragraph of Rule 3.3 states: 

> Staff will routinely remove hollow claims as we have automated tools for that, the **_other types of claim blocking will only be removed when reported by the mayor of a blocked town._**

This makes it practically allowed to violate the second sentence of the rule. This goes back to the abuse by players to use claim arms on Aurora. Many players have found it allowed to create claim arms in parts of Europe still secluded. I welcome you to explore the [dynmap](https://earthmc.net/map/aurora/?worldname=earth&mapname=flat&zoom=3&x=2216&y=64&z=-8776) of Europe.

### Describe the solution you'd like

A simple solution to this rule would be

- Stating in the rule to enforce all claim arms that do or do not claim block other towns.
- Enforcing all claim arms that do or do not claim block other towns.

However, I understand the need to limit the number of tickets. By requiring claims arms to only be removed and reported by blocked towns, fewer tickets are made, but this can negatively impact the player base when areas are claimed over by a long line of chunks.

### Additional context

It would become difficult to enforce the already generated claim arms. However, similar to how hollow claims were enforced, time can be given to players to correct their claim arms before getting removed by staff members.

**Comment by Basically-Andrew** [comment]
As I'm already aware staff are currently rewriting the rule, but I'd like to also suggest reading past language of the rule. The rule used to state:
> Surrounding other towns with claims is also not allowed, about 3/4 of the town has to be surrounded for it to count as illegal. The only exception to this is when a town is created in an area where it is already surrounded.

While it was removed from the rule, staff still uphold this policy today. Instead of confusing the player base, why don't we better inform the player base?

**Comment by CorruptedGreed** [comment]
We've made this change in the last 3.3 rule modification.
