### ISSUE TITLE
[Feature] Chunk overlay built into menu of Dynmap

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1505]
### Is your feature request related to a problem? Please describe.

It can be difficult to see exactly how many chunks fill an area on the Dynmap.

### Describe the solution you'd like

An option to enable a grid overlay for chunks on the Dynmap in the top left that you can toggle on and off.

### Additional context

I don't know if there is a config option for this or anything but would be nice if it was custom implemented.

As a sidenote the Dynmap frontend [LiveAtlas](https://github.com/JLyne/LiveAtlas) would be nice to see on EarthMC, it has some useful features and just looks nicer.

**Comment by Basically-Andrew** [comment]
Would this be something you're looking for?
https://gist.github.com/Pisi-Deff/92e00008f809383c82d926f843b6dd0f
Found this [here](https://github.com/webbukkit/dynmap/issues/2488).

**Comment by Warriorrrr** [comment]
Will be visible after next server restart.
