### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FruitUniversity** [EarthMC/Issue-Tracker#1508]
### Server

Aurora

### Describe the bug

DB tags matter on enchantment items in shops.  Would yall be able to make it so DB tags on enchantments/enchanted armor dont affect shop, it says a db tag of 2 is a different item than a db tag 3 armor piece etc.

### To Reproduce

Enchant armor with different DB tags and try to sell at same shop chest

### Expected behavior

Will only see the DB tag you selected when shop created

### Screenshots

N/A

### Additional context

N/A

**Comment by Warriorrrr** [comment]
Will be fixed after the next restart.
