### ISSUE TITLE
[Bug] Incorrect links in /rules and join message

### ISSUE THREAD

**Issue by can30** [EarthMC/Issue-Tracker#1509]
### Server

Aurora

### Describe the bug

both /rules and the server join message link to [https://earthmc.net/rules](https://earthmc.net/rules)

### To Reproduce

type /rules or join the server

### Expected behavior

server message and /rules contain the correct link [https://earthmc.net/docs/rules](https://earthmc.net/docs/rules)

### Screenshots

![image](https://user-images.githubusercontent.com/105682085/168696814-aca63415-3077-4317-afae-76dcf0a14cae.png)
![image](https://user-images.githubusercontent.com/105682085/168696870-379554f1-6667-45da-aa64-54ec247a64d6.png)

**Comment by Warriorrrr** [comment]
Fixed
