### ISSUE TITLE
[World] Flower Forest Biome

### ISSUE THREAD

**Issue by Np241** [EarthMC/Issue-Tracker#151]
**Describe the issue**
In short and simple terms, i was wondering if it were possible to make/edit the EMC map to include a few Flower Forest biomes. I mainly request this so that builders who like extreme attention to detail may be able to use a wide variety of flowers (because if you bone meal inside a F.F biome, you can obtain Tulips, Alliums, Azure Bluits, and Cornflowers in 1.14). i have a link to a tourist website for places around the world that could be turned into F.Fs. 

https://xyuandbeyond.com/flower-tourism/

**Coordinates**
Location A, Washington DC: (-14400X ~Y -7400Z) ,and Location B, The Netherlands: (630X ~Y -9700Z) to name examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/45175296/48717749-a697ca00-ebdf-11e8-8a97-84f6c223c119.png)

^what the biome looks like in a normally generated world, and can be used as an example if you were to generate new chunks based on that biome.

P.S : I tried to make this look at professional and to the point, while maintaining a non-demanding tone as possible.

**Comment by shirazmatas** [comment]
Sure I can add this.

**Comment by PoppyK** [comment]
Flower Biome was added to the following areas on the map:  (Where I am located in each pic)
NOTE: you need to bonemeal to see flowers.

https://i.gyazo.com/1a3f6c84bbf81cfc6a1c20f9a40481ee.jpg
https://i.gyazo.com/40c0f9518b55b61985ee31ce7216228d.png
https://i.gyazo.com/758111f3d8e424b2e06a13835f44ed8b.jpg
https://i.gyazo.com/7fdafee8596d0c2c6f13e0899d3aef16.jpg
https://i.gyazo.com/e5d770722d3be4e67e96a9ed26a164c2.jpg
https://i.gyazo.com/9997a418de6a6a7b99472db465305e09.jpg
