### ISSUE TITLE
[Bug] Towny Permissions to Ranking Commands

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1510]
### Server

Aurora

### Describe the bug

Players don't have the permission level to run the commands `/towny top` or `/t list`.

### To Reproduce

1. Run the command `/towny top` or `/t list`

### Expected behavior

Be able to access the information and contents of these commands.

### Screenshots

![image](https://user-images.githubusercontent.com/59465284/168936357-d7c51cc0-95cf-4a40-af2b-1160de4fb8cc.png)

### Additional context

I'm not sure if this was intentionally disabled, but it would be nice to have it back.

**Comment by Warriorrrr** [comment]
/t list and /n list now both work, /towny top will remain disabled.
