### ISSUE TITLE
[Rule 4.1 & 4.2] Ban Nations & Towns with Special Characters

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1511]
### Is your feature request related to a problem? Please describe.

Frequently, several towns and some nations are created with special characters in their name. These town names and nations break several command functionalities. Of course, if the special character isn't the first letter of the name, the command can be tabbed to fill in the special character. However, this isn't suitable for the future. As more towns and nations are made it will be harder to tab through the similar town and nation names. 

### Describe the solution you'd like

````diff
4.1 Nation names
Before creating a nation, make sure your name complies with the nation naming rules. Nation names may be changed by a staff member if the rule is not followed and may be disbanded if the rule is repeatedly broken.

Nation name cannot be fictional. It has to have the same name as a current or past nation.
Nation can be named after region, province or other large geographical area with defined borders if accurate nation name is already taken.
Nation name must correspond with map location of the nation capital.
Nation cannot have a similar name to already established nation to the point where one could easily be confused with the other.
+ Nation cannot have names with special characters.

4.2 Town names
Before creating a town, make sure your name complies with the naming rules. Names may be changed by a staff member if the rule is not followed.

Fictional town names are allowed. However, we highly recommend towns to have a name tied to the real life town location.
Town names cannot be inappropriate/toxic/offensive.
Towns cannot have similar names to already established towns to the point where one could easily be confused with the other.
+ Towns cannot have names with special characters.
````

### Additional context

Towns and nations already with special characters can be renamed for free by staff or forced renamed by staff.

**Comment by WTDpuddles** [comment]
While it is annoying that I can't teleport to the nation of Rûm, those "special characters" are normal characters in other languages and that's how some towns and nations are spelled in real life.

**Comment by docwhomc** [comment]
If this were to be implemented, it wouldn't need to be added as a rule. It could simply be done by changing the regular expressions used by Towny.

**Comment by CorruptedGreed** [comment]
As long as a nation begins with a normal character it can be tag autocompleted and interacted with, so this isn't really necessary.
