### ISSUE TITLE
[Mechanic] Towny Shop Chest Perm Integration

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1512]
### Is your feature request related to a problem? Please describe.

Currently, players need Towny `build`, `destroy`, and `switch` permissions in a shop plot to make a shop chest. The issue with this is staff will allow any player with Towny `switch` permissions in a plot to remove another player's shop chest. This makes it extremely dangerous to make shared shop plots.

### Describe the solution you'd like

One of the many solutions could include:
1. Towny permissions to make a shop chest in a shop plot can be changed to only `build` and `destroy`.
2. Staff change policy on shop chest removal.
3. A special permission level (probably not possible)

**Comment by WTDpuddles** [comment]
From what I've been told, shop chests aren't supposed to be some impenetrable fortress or an extra enderchest that no one but the creator can open. This is why anyone with switch perms are able to ask for them to be removed. A better idea would be to make it so anyone with switch perms in a plot can access a shop chest in the same plot. They are supposed to just be regular chests but with the ability to sell items out of them, if you don't trust someone to keep out of your chests then take their perms away or change the plot perms to reflect that.

**Comment by Warriorrrr** [comment]
The idea mentioned by puddles was implemented a while ago, closing this.
