### ISSUE TITLE
Allow afking when player cap is not full

### ISSUE THREAD

**Issue by yankees88888g** [EarthMC/Issue-Tracker#1513]
### Is your feature request related to a problem? Please describe.

I am frustrated when the player count is low but i still get afk kicked, since the player count is below the cap this shouldn't be causing issues.

### Describe the solution you'd like

First of all when the player count is full I want the afk kicking to remain the same. But when the player count drops those afk get put in a line from when they started afking. When the player count fills up those afk get kicked in order until there are no players that are afk longer then 15 minutes.

**Comment by Basically-Andrew** [comment]
If you're kicked when the player count is low, why don't you just rejoin the server instantly?

**Comment by yankees88888g** [comment]
> If you're kicked when the player count is low, why don't you just rejoin the server instantly?

If your afk u cant instantly rejoin

**Comment by Basically-Andrew** [comment]
Yes if you are still afk, but if you've been kicked and the server isn't full then you can just rejoin when you're back. I see no argument for your problem.

**Comment by docwhomc** [comment]
It sounds like the point is to allow players to afk in their farms (or perhaps fishing) if the cap isn't full.

**Comment by yankees88888g** [comment]
Ye

**Comment by docwhomc** [comment]
Well AFK fishing isn't allowed at all.
