### ISSUE TITLE
[Feature] Allow Premium to Message in Discord Towny Text Channel

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1514]
### Is your feature request related to a problem? Please describe.

Currently, no one is allowed to send messages in `#terra-aurora` and `#terra-nova` Discord text channels. I remember chat being much more active with players talking on the server and Discord at the same time.

### Describe the solution you'd like

Allow Premium players the exclusive permissions to send messages in these channels as an additional perk of Premium.

### Additional context

I'm not exactly sure why the channel has been closed for messages.

**Comment by Proserrr** [comment]
This exists

**Comment by CorruptedGreed** [comment]
This does in fact exist now, closing issue.
