### ISSUE TITLE
[Feature] Clay block to clay conversion in custom crafting

### ISSUE THREAD

**Issue by doak-m** [EarthMC/Issue-Tracker#1515]
### Is your feature request related to a problem? Please describe.

This feature is not related to a serious problem, rather it's more of a convenient way for players to obtain bricks. 

Bricks can only be obtained by smelting clay pieces _(the non-block clay, I'll be calling it that from now on)_, but each block of clay gives 4 clay pieces when broken. 

This presents a problem where blocks of clay have to be crafted during mining to store more clay, but will then have to be placed and broken again to be turned into bricks.

### Describe the solution you'd like

A simple crafting recipe converting _1 clay block_ to _4 clay pieces_ would suffice to fix this problem entirely. 
This eliminates the time needed to place and break the clay blocks in order to obtain clay pieces for brick production. 

### Additional context

I do not believe that this fix would present any major problems from the time eliminated while producing bricks. 

As EMC doesn't have SiegeWar and thus its highly likely that it has a larger demographic of builders, I believe this would greatly benefit the community as a whole.

**Comment by Basically-Andrew** [comment]
When breaking a clay block you don't always get 4, so this crafting recipe is a bit broken. However I believe this a better suggestion for the minecraft forums.

**Comment by doak-m** [comment]
Shouldn't having a Fortune III shovel always get you 4 clay pieces per block? You would still have to break clay blocks first to get clay pieces, so there shouldn't be any problem with getting more clay than you should.
