### ISSUE TITLE
The Pruth River

### ISSUE THREAD

**Issue by Gamewalker1** [EarthMC/Issue-Tracker#1517]
### Describe the issue

The Pruth doesn't exist

### Coordinates

Around 4831 -8983

### Screenshots

![Screenshot (1018)](https://user-images.githubusercontent.com/105992268/169667391-ec32ad95-5e1b-4a73-a16b-080ca6990b24.png)
![DATA_Q~1](https://user-images.githubusercontent.com/105992268/169667396-55d3c86d-9198-4dfe-a26f-ddb89768dbea.PNG)

**Comment by Gamewalker1** [comment]
pliz

**Comment by Basically-Andrew** [comment]
The area of the river is already partially claimed, so I doubt the river will be added. Most world issues on nova were neglected for months.

**Comment by Gamewalker1** [comment]
Isn't it just claimed by me? (the pink town)

**Comment by BunbunToast** [comment]
It may have been too narrow to have even registered as a river when the world was being converted from a map to a minecraft world. Put simpler, size matters.
