### ISSUE TITLE
[Bug] Nothing I build in my town shows on the dynamap

### ISSUE THREAD

**Issue by Svitloshi** [EarthMC/Issue-Tracker#1518]
### Server

Aurora

### Describe the bug

As the title says, the dynamap just shows the empty land before I claim it. Others in my nation (Ukraine, I’m from the town Dnipro) have this problem as well. 

### To Reproduce

… open the map

### Expected behavior

It shows a few trees and land, however I have built a big apartment complex and bridge

### Screenshots

![002A1837-5DB8-4D35-AB20-1F5B29C2D92A](https://user-images.githubusercontent.com/105992743/169667842-cd00196b-93c4-47ef-8b09-e41475564cea.jpeg)

**Comment by Basically-Andrew** [comment]
Dynmap takes a while to update the large map. This is not a bug. If there is no other issue, please close.

**Comment by Svitloshi** [comment]
> Dynmap takes a while to update the large map. This is not a bug. If there is no other issue, please close.

it’s not a while though, i have had the land since opening day for non premiums. It’s not updating full stop.

**Comment by Basically-Andrew** [comment]
My town on nova hasn't been updated since November. This isn't an issue. More active areas of the map will update more often (i.e. Europe).

**Comment by Svitloshi** [comment]
I am in Europe tho, the town beside me is updating all the time

**Comment by Basically-Andrew** [comment]
There is still nothing that can be fixed about this.

**Comment by Svitloshi** [comment]
Okay
