### ISSUE TITLE
[Bug] Missing & Duplicate Town Ranks

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1520]
### Server

Aurora

### Describe the bug

1. There is currently no way to allow a player to claim townblocks in a town without giving them many more perms in the town. There used to be a `settler` rank that allowed the player to claim chunks for the town with /t claim. It complimented the recruiter rank nicely to let trusted citizens get new players into the town while claiming chunks with the additional town size available to claim.

2. There are two outlaw ranks: `Police` and `sheriff`. While I haven't tested both, I assume they have the same permissions and were accidentally both added in the config. The sheriff's town rank is also missing a capital letter S.

### To Reproduce

- `/t rank add Basically_Andrew Settler`
- Unknown rank Settler. Permissible ranks are Councillor, Builder, Recruiter, Police, Tax-exempt, Treasurer, sheriff.

- `/t rank add Basically_Andrew` 
- Two outlaw ranks on suggested.

### Expected behavior

1. Able to give citizens, settler town rank.

2. No duplicate town ranks with same permissions.

### Screenshots

![image](https://user-images.githubusercontent.com/59465284/170890255-541c7881-4bc6-49cc-b127-ef4b102bf9ac.png)
![image](https://user-images.githubusercontent.com/59465284/170890294-a2d3f8bb-2322-41a0-a149-115e79a58788.png)

### Additional context

I'd like to also recommend renaming the settler rank to Surveyor. IMO it makes more sense with the permissions the rank gives.

**Comment by TenSpacesalc** [comment]
Another missing rank is `Trusted` ([docs for town ranks](https://earthmc.net/docs/town#town-ranks)). I thought these ranks had been intentionally removed so I included them in my PR to update the docs [here](https://github.com/EarthMC/earthmc-docs/pull/26)

**Comment by Basically-Andrew** [comment]
> Another missing rank is `Trusted` ([docs for town ranks](https://earthmc.net/docs/town#town-ranks)). I thought these ranks had been intentionally removed so I included them in my PR to update the docs [here](https://github.com/EarthMC/earthmc-docs/pull/26)

Does `/t trust add Basically_Andrew` not work?

**Comment by Warriorrrr** [comment]
Sheriff was automatically added by towny and will be gone next restart, don't know about settler. Trusted rank was replaced with the /t trust command since they both did the same thing.

**Comment by TenSpacesalc** [comment]
Ahh ok I didn't realize it was changed to be different from a rank now. will update the PR

**Comment by Basically-Andrew** [comment]
> Sheriff was automatically added by towny and will be gone next restart, don't know about settler.

Alright that clears things up about sheriff. What's the problem with adding settler back?
