### ISSUE TITLE
[Mechanic] Combat Tag Players taking Any Damage

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1521]
### Is your feature request related to a problem? Please describe.

Currently, players are able to take damage and log off without being combat logged and dropping their items. This allows players in lava traps, wither rose traps, etc. to escape by logging off

### Describe the solution you'd like

Make any damage the player takes (except fall damage) a combat tag event, so players can't easily escape traps.

### Additional context

There might be some other damages besides fall damage that shouldn't combat tag the player, but lava and wither roses are the main trap killing methods that should combat tag a player.

**Comment by 0xBitMC** [comment]
The plugin is called `CombatLogX` and is designed for Combat Tagging. Placing people in traps isn't Combat Tagging and as far as I could remember it has always been like this. 

Stop being lame and trapping people in your claims.

**Comment by Basically-Andrew** [comment]
I understand plugin changes would need to be made, but you've made no point as to why this is a bad suggestion. If you've fallen into a trap that's your fault and you shouldn't be able to escape by logging off

**Comment by Basically-Andrew** [comment]
> The plugin is called `CombatLogX` and is designed for Combat Tagging. Placing people in traps isn't Combat Tagging and as far as I could remember it has always been like this.
> 

All that would be needed to be done is add NonCombatLogX now known as Damage Tagger Expansion that is heavily configurable for combat tag events on certain damage.

**Comment by RAWRyoutube** [comment]
>Make any damage the player takes (except fall damage) a combat tag event, so players can't easily escape traps.

This needs a major revamp to be reasonably considerable. First of all, there must be some method to differentiate traps from other forms of damage, such as getting hit by lava while mining in the nether or being hit by wither skeletons. If suggestion were accepted, there **must** be a 100% effective way to split damage dealt from other players and damage dealt unintentionally. Are you able to provide said solution?
Secondly, what would happen in a non-pvp plot if the combat tag was activated with the anti-claimhide plug-in already activated?
Lastly, the main tenet of this suggestion is to increase the power of traps. What is the justification of increasing the power of traps? Would this be beneficial for all participants involved in trapping, and for the server? Why do you view players escaping traps in a negative light?
It would be appreciated if responses to each question presented are given.

**Comment by 0xBitMC** [comment]
> > The plugin is called `CombatLogX` and is designed for Combat Tagging. Placing people in traps isn't Combat Tagging and as far as I could remember it has always been like this.
> 
> All that would be needed to be done is add NonCombatLogX now known as Damage Tagger Expansion that is heavily configurable for combat tag events on certain damage.

Reference my Organizational Github. I already built something like this. 

Personally, stubbing your toe and logging out will resulting in you losing all of your stuff sounds pretty stupid.

**Comment by Basically-Andrew** [comment]
> Personally, stubbing your toe and logging out will resulting in you losing all of your stuff sounds pretty stupid.

That's why there are several messages in chat that warn players. Also it's up to every player to securely log out like they do to teleport. You can't teleport away while in lava, so why should you be able to log out? Lastly as I mentioned the plugin is configurable and certain damages like fall damage can not toggle combat for a player. I know I wouldn't want to take fall damage and log out right after to lose my items.

**Comment by RAWRyoutube** [comment]
> That's why there are several messages in chat that warn players.

This will not be enough to stop accidental combat log deaths under your proposed system.

> You can't teleport away while in lava

This is incorrect. Someone who has consumed a potion of fire resistance can teleport away while in lava.

> Lastly as I mentioned the plugin is configurable and certain damages like fall damage can not toggle combat for a player.

Are you able to show this in action?

**Comment by Basically-Andrew** [comment]
API can be used to detect and combat tag player-created damage. Sorry, I wrote that a bit confusing above.

**Comment by RAWRyoutube** [comment]
>API can be used to detect and combat tag player-created damage.

Could you explain this better?

**Comment by RAWRyoutube** [comment]
> Towny API x CombatLogX API. Use both APIs with Minecraft to check placements and claims?

Now, if this system were implemented, what would happen? Would it be worth doing this?

**Comment by Basically-Andrew** [comment]
Players who find themselves in traps wouldn't be able to log off while taking damage to lava, wither roses, etc. It would be worth doing this to prevent players from escaping their mistakes.

**Comment by 0xBitMC** [comment]
> Towny API x CombatLogX API. Use both APIs with Minecraft to check placements and claims?

Yes, but it does this inefficiently but incorrect On Player Move Event checks that grab the location not once but twice and effectively bring down the TPS. 

Now, I have talked with the creator of CombatLogX about this nearly a year ago and he simply replied that it "works" and he wasn't going to fix it. Sure it works on servers with less players but for EarthMC to really hold that 250 playercap, every efficient tick matters.  This being said, your proposal is a waste of efficiency and effectively is just pretty stupid.

**Comment by RAWRyoutube** [comment]
> It would be worth doing this to prevent players from escaping their mistakes.

Now, as far as I can understand, you are referring to someone getting trapped, right? If so, are you saying that it’s the victim’s fault for being trapped, and not the converse?

**Comment by CorruptedGreed** [comment]
Not pursuing all damage as combat logging
