### ISSUE TITLE
[World] Give Polynesia a biome.

### ISSUE THREAD

**Issue by superiorglitch** [EarthMC/Issue-Tracker#1522]
### Describe the issue

This is a special request for my friend, Balankey. He made Tahiti, but most of the islands, including Tahiti and the neighboring islands, are warm ocean biome instead of jungle. A biome adjustment would be a nice and help make Polynesia, a very important cultural center better represented in EMC.

### Coordinates

-27844, 94, 3125

### Screenshots

![2022-05-30_18 55 43](https://user-images.githubusercontent.com/77036270/171072786-be359a3f-5687-4361-974f-f7052db71d46.png)

**Comment by AndrewCheedle** [comment]
Its over
