### ISSUE TITLE
[Bug] Change "That nation is not public."

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1524]
### Server

Aurora

### Describe the bug

Players are shown the message "That nation is not public." when trying to teleport to a nation that isn't allied.

### To Reproduce

/n spawn unAlliedNation

### Expected behavior

Change Towny's message to a more appropriate message that doesn't confuse players.

**Comment by 0xBitMC** [comment]
This isn't an EarthMC "Bug", go report this issue at https://github.com/TownyAdvanced/Towny or make the changes yourself there with a Pull Request.

**Comment by Basically-Andrew** [comment]
This doesn't seem to be a Towny bug as this didn't work on Nova. Appears to be a configuration issue for Aurora. And Wariorr, EarthMC developer, handles this also patches Towny and is happy with them being made here.

**Comment by 0xBitMC** [comment]
> This doesn't seem to be a Towny bug as this didn't work on Nova. Appears to be a configuration issue for Aurora. And Wariorr, EarthMC developer, handles this also patches Towny and is happy with them being made here.

If it has to do with Towny and reproducible without it being on EarthMC, it's a Towny Bug. Simple as that.

> Should just be a change [here](https://github.com/TownyAdvanced/Towny/blob/0e91ac7d89c5467300f201cbe483610494e5ef91/resources/lang/en-US.yml#L699).

Close but this fix does not address the issue that sometimes nations may disable their public nation spawn (if enabled in Towny config to do so). I have completed the changes here: https://github.com/TownyAdvanced/Towny/pull/5940

**Comment by LlmDl** [comment]
This isn't a bug. The nation isn't public so they cannot be spawned to by a non-ally and non-member.

**Comment by Basically-Andrew** [comment]
> This isn't a bug. The nation isn't public so they cannot be spawned to by a non-ally and non-member.

This is still an issue. The message "That nation is not public." Will always display and confuse players when public spawn is disabled in config. If the server has public spawning disabled, a more appropriate message should display that would let the player know they aren't allied and should let their diplomat, chancellor, or nation leader ally the nation.

**Comment by LlmDl** [comment]
Ah well your ticket doesn't say anything about a server having public spawning disabled.

**Comment by 0xBitMC** [comment]
This issue will be resolved in the next Towny Pre-Release: https://github.com/TownyAdvanced/Towny/commit/498b22f794d9132aa47dc78b97e2fcada948d609
