### ISSUE TITLE
[Feature] Romanian Chat

### ISSUE THREAD

**Issue by 32David** [EarthMC/Issue-Tracker#1526]
### Is your feature request related to a problem? Please describe.

The server is getting an increased number of Romanians joining.

### Describe the solution you'd like

I was thinking the Romanian community of EarthMC could get a /romanian chat in which we could discuss in romanian without needing to make party chats or talking in /general

**Comment by CorruptedGreed** [comment]
No indication of many Romanians joining

**Comment by Veyronity** [comment]
> No indication of many Romanians joining

What about Arabic?
There's a fair amount of arabic speakers on emc
