### ISSUE TITLE
[Rule 3.7] Ice Roads 

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#1527]
### Is your feature request related to a problem? Please describe.

If you look across a large body of water, such as the [Mediterranean Sea on Nova](https://earthmc.net/map/nova/?worldname=earth&mapname=flat&zoom=2&x=3136&y=64&z=-6408), you notice heavy lines of ice roads that destroy the terrain of EarthMC.

### 3.7 Ice Roads
Creating ice roads is allowed as long as it does not interfere with the terrain. In order to preserve the accurate geography of the map, ice roads are only allowed below ground. This is done to preserve the natural look of the dynmap.

### Additional context

I have already spoken with a few staff members and ice road communities that support banning ice roads above ground. Since Aurora has just begun this wouldn't be a hard adjustment to move already constructed ice roads to below ground.

**Comment by Fruitloopins** [comment]
Been saying that.

**Comment by docwhomc** [comment]
I agree, except that the nether may be preferable to over underground.

**Comment by AndrewCheedle** [comment]
@CorruptedGreed

**Comment by CorruptedGreed** [comment]
Terraforming rule should cover if the road is egregious
