### ISSUE TITLE
Can't get in without a public key

### ISSUE THREAD

**Issue by CorruptedJarfile** [EarthMC/Issue-Tracker#1528]
### Server

Hub

### Describe the bug

It says I dont have a public key and I don't know what to do. Please Help me! 

### To Reproduce

I don't know, I just tried to join.

### Expected behavior

Not to get into the server?

### Screenshots

![image](https://user-images.githubusercontent.com/99778222/173210626-81f3c7fc-1f48-4ddf-8372-ae17dfeda5ce.png)

**Comment by RAWRyoutube** [comment]
Are you logging on with just a Minecraft account or with a Minecraft account connected to a Microsoft account?

**Comment by CorruptedJarfile** [comment]
> Are you logging on with just a Minecraft account or with a Minecraft account connected to a Microsoft account?

I'm logging on with a Microsoft account

**Comment by RAWRyoutube** [comment]
Is that connected to a Minecraft account as well?

**Comment by CorruptedJarfile** [comment]
> Is that connected to a Minecraft account as well?

I don't know what you mean, but what I am taking it as is a yes

**Comment by RAWRyoutube** [comment]
On your Microsoft account, did you connect an account from minecraft.net like in [this Minecraft help article?](https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account)

**Comment by CorruptedJarfile** [comment]
I never migrated my account.

**Comment by RAWRyoutube** [comment]
This server requires migration, it usually only takes 5-15 minutes to do following the guide I sent earlier.

**Comment by CorruptedJarfile** [comment]
> This server requires migration, it usually only takes 5-15 minutes to do following the guide I sent earlier.

What if my account breaks in during the migration progress?

**Comment by RAWRyoutube** [comment]
Did it?

**Comment by CorruptedJarfile** [comment]
> Did it?

No, but I am worried if it does

**Comment by RAWRyoutube** [comment]
It shouldn’t.

**Comment by CorruptedJarfile** [comment]
> It shouldn’t.

Also, How do I migrate a account that is already a Microsoft account?

**Comment by RAWRyoutube** [comment]
You start the process on Minecraft’s website with a signed-in Minecraft/mojang account.

**Comment by CorruptedJarfile** [comment]
> You start the process on Minecraft’s website with a signed-in Minecraft/mojang account.

I logged in and it says I dont have any minecrafts, but I have both java and bedrock

**Comment by RAWRyoutube** [comment]
Did you ever buy Minecraft from Minecraft’s website?

**Comment by CorruptedJarfile** [comment]
> Did you ever buy Minecraft from Minecraft’s website?

Yes, I think so. I first bought it in/from the minecraft launcher. And it took me to the website. I have multiple accounts but both of them are having the same problem
![image](https://user-images.githubusercontent.com/99778222/173211512-b99c1593-31c6-4180-8470-007557889e89.png)

**Comment by RAWRyoutube** [comment]
Apparently reverting to 1.18.2 might fix your problems, if you’re using 1.19.

**Comment by CorruptedJarfile** [comment]
> Apparently reverting to 1.18.2 might fix your problems, if you’re using 1.19.

What do you mean?

**Comment by RAWRyoutube** [comment]
On the launcher, you should be able to switch versions from the latest (1.19) to 1.18.2. There should be multiple Youtube tutorials for that.

**Comment by CorruptedJarfile** [comment]
> On the launcher, you should be able to switch versions from the latest (1.19) to 1.18.2. There should be multiple Youtube tutorials for that.

I can't
![image](https://user-images.githubusercontent.com/99778222/173211661-9f31c725-511b-45c8-ab0d-9426fb1cbdbd.png)

**Comment by RAWRyoutube** [comment]
Did you quit your 1.19 session before taking that screenshot?

**Comment by CorruptedJarfile** [comment]
> Did you quit your 1.19 session before taking that screenshot?

Nevermind, uh something was wrong with my pc and it was taking me to a different Microsoft account, and all that. But I am still trying to migrate the account

**Comment by CorruptedJarfile** [comment]
When I push the "MIGRATE NOW" button it takes me here, and I dont know what to do next
![image](https://user-images.githubusercontent.com/99778222/173211802-c1d81b70-5748-483a-9f7b-dcd2951b704c.png)

**Comment by RAWRyoutube** [comment]
I don’t know what to do about that either. On your launcher, try changing the version to 1.18.2 and see if you’re able to join that way.

**Comment by CorruptedJarfile** [comment]
> I don’t know what to do about that either. On your launcher, try changing the version to 1.18.2 and see if you’re able to join that way.

![image](https://user-images.githubusercontent.com/99778222/173211934-5ec1d61c-a895-42c4-8824-c8b4fc75583a.png)
I can just make a new one, if thats how that works

**Comment by RAWRyoutube** [comment]
That should work.

**Comment by CorruptedJarfile** [comment]
> That should work.

Then what??

**Comment by RAWRyoutube** [comment]
You should be able to connect to EarthMC as normal when you launch Java in 1.18.2.

**Comment by CorruptedJarfile** [comment]
> You should be able to connect to EarthMC as normal when you launch Java in 1.18.2.

Thanks, but why did you say I needed to migrate my account?

**Comment by RAWRyoutube** [comment]
That error code is new to me, so I didn’t know exactly what would work to fix it.

**Comment by Warriorrrr** [comment]
I already disabled public key checking option in the proxy config a while ago, might need to do a full restart. For now, you'll need to continue using 1.18 (recommended, 1.19 with viaversion might still have some issues) or you'll have to migrate your account.
