### ISSUE TITLE
New chest shop plugin should be improved upon, here's a good reason why.

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#1529]
### Is your feature request related to a problem? Please describe.

I created a unique system at my spawn shop, where 2 chunks branch out in each cardinal direction. Each of these 2 chunks sell their own category of items. In order for someone to sell items, I temporarily /t trust add them, they make their shop, then I remove their trust and leave them with switch perms to whatever chunk their shops are in, allowing them to restock (for this to happen they have to be relatively trusted). This system allows multiple shop owners to sell items in a single chunk (no duplicates of items across sellers). 

This concept was working fine, until the new changes with the chest shop plugin were introduced. Now, having multiple sellers in a single chunk allows them to access each others chests, which makes the amount of people trusted enough to sell at the spawn very low (they can access the shops due to having switch perms in the chunk to restock their own shops).

### Describe the solution you'd like

**MY IDEA**: I propose a system where a shop owner is allowed to set who accesses their shop, via a similar system to plot perm gui. Another way is to allow them to switch between their shop being private, friends only, or accessible by all with switch perms. Additionally, anyone who owns a chest shop should be able to access it regardless of their chunk perms.

### Additional context

**Image underneath shows two shop owners in a single chunk. Both can access each others chests as they both have switch perms**
![image](https://user-images.githubusercontent.com/89758266/173264768-d6344e00-a367-46ae-9931-062574694463.png)

**Comment by rogue-rabbit** [comment]
Please for the love of god implement this

**Comment by Warriorrrr** [comment]
This has been implemented in the latest update, the shop owner and any shop staff are be able to open the chest regardless of towny permissions now. Shops are also locked for others again.
