### ISSUE TITLE
Inappropriate Sexual Behavior

### ISSUE THREAD

**Issue by SleepyChibiChan** [EarthMC/Issue-Tracker#1531]
### Describe the issue

A lot of players are getting away with inappropriate sexual behavior.
Please ban:
•xixk - for sending inappropriate pictures/being inappropriate in general
•Zombieaxes - for inappropriate sexual/pedo behaviour
•MokoPuppet - for inappropriate sexual/pedo behaviour

### Coordinates

No specific coordinates. It happened in Global chat

### Screenshots

![Screen Shot 2022-06-14 at 1 58 34 PM 2](https://user-images.githubusercontent.com/96939261/173532836-a9dd3b5c-d98d-44fc-9635-5579e9574329.jpg)
![Screen Shot 2022-06-14 at 1 58 34 PM](https://user-images.githubusercontent.com/96939261/173532846-a93b9261-e8de-4647-b0cd-7cfdf0dbba4d.jpg)
![Screen Shot 2022-06-14 at 1 59 55 PM](https://user-images.githubusercontent.com/96939261/173532853-97898c6a-bc92-4ad3-aabd-aae067f6cec8.jpg)
![Screen Shot 2022-06-14 at 2 01 28 PM](https://user-images.githubusercontent.com/96939261/173532859-224040fa-5a39-47d8-b467-31d17b69a150.jpg)
![Screen Shot 2022-06-14 at 2 02 07 PM](https://user-images.githubusercontent.com/96939261/173532868-b13785da-8b36-4eef-82c1-f2e611a6e68a.jpg)
![Screen Shot 2022-06-14 at 2 07 55 PM](https://user-images.githubusercontent.com/96939261/173532870-20f177d4-c1cf-4819-a50c-4df0e2a74e73.jpg)

**Comment by Warriorrrr** [comment]
Don't use the issue tracker for support, please use the [support discord](https://discord.gg/EZBYmpp).
