### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SaiphLyra** [EarthMC/Issue-Tracker#1533]
### Server

Aurora

### Describe the bug

Plots are offset from the chunk border (as seen by F3 + G keyboard shortcut). Each plot is offset by 1 row of blocks north and one column of blocks east. Similarly, the row of blocks to the south and east of chunks do not inherit town claim or plot claim
 properties, such as plot / town rank permissions.

### To Reproduce

Town border chunks will have a row or column of wilderness on the inside or outside of the chunk.
Similarly, chunks claimed by citizens and locked by default towny permissions will inherit the privacy permissions of those plots; however, each row that is offset within the chunk will not inherit the same permissions, and the extra row of blocks in the neighboring chunk will instead inherit the permissions. 

### Expected behavior

All plots should begin and end at chunk borders, with permissions and claim applications beginning and ending at the same borders.

### Screenshots

![2022-06-15_14 03 20](https://user-images.githubusercontent.com/107578247/173896475-880e553f-c761-46ba-b81f-359631694d62.png)
![2022-06-15_14 03 54](https://user-images.githubusercontent.com/107578247/173896479-d583014e-2006-41b4-9ec4-59eb4ea4befb.png)
![2022-06-15_14 04 28](https://user-images.githubusercontent.com/107578247/173896480-fc191a65-5a25-4da1-a246-87983b110889.png)

**Comment by Warriorrrr** [comment]
This is a known issue with lunar client, for some reason it offsets the chunk grid by 1 block. This issue doesn't appear when using a vanilla client or when using the /res toggle constantplotborder command.
