### ISSUE TITLE
To see the real time total vote for Earthmc

### ISSUE THREAD

**Issue by YOYOUUlu** [EarthMC/Issue-Tracker#1534]
Hi, I want to develop a new plugin so that players can see the real-time total votes of some servers. Please tell me where I can view the total real-time votes of Earthmc. Thank you!

**Comment by Basically-Andrew** [comment]
Total votes counted and displayed on voting websites.

**Comment by YOYOUUlu** [comment]
I know, but there is a big gap between the website voteparty data and the game voteparty data.

**Comment by Basically-Andrew** [comment]
What you're looking for will never happen. EarthMC API has been denied by admins in the past.

**Comment by Warriorrrr** [comment]
Even if we wanted to, this would not be possible to implement due to the voteparty plugin being closed source.
