### ISSUE TITLE
[Bug] We were traveling by flying machine and this has suddenly happened

### ISSUE THREAD

**Issue by STGWinteam** [EarthMC/Issue-Tracker#1536]
### Server

Aurora

### Describe the bug

We build a flying machine with honey and after ~100 blocks it suddenly stopped above the ocean and blocked all updates on 4 chunks around it. We weren’t able to get off the boat, pick up blocks. Then a lot of mobs spawned like a freezed wall. https://drive.google.com/file/d/1Fe4oRDAhPqfpOJa6swqaL78WD5oZ4LZu/view?usp=sharing

### To Reproduce

Build a simple honey flying machine and go in the wilderness for 3 mins on it activated.

### Expected behavior

We weren’t able to get off the boat and pick up resources.

### Screenshots

https://drive.google.com/file/d/1Fe4oRDAhPqfpOJa6swqaL78WD5oZ4LZu/view?usp=sharing

### Additional context

Chunks after the 2x2 square couldn’t be entered.

**Comment by CorruptedGreed** [comment]
Perpetual flying machines eventually break, most likely stopped by the server to save resources
