### ISSUE TITLE
Ice spawning.

### ISSUE THREAD

**Issue by JuubiNaruto** [EarthMC/Issue-Tracker#1537]
So admins have disabled ice spawning and they say it’s “to increase the player cap” but instead of doing something that A. Makes it so people can’t get ice easily without paying for it. Also Germany sells ice OH WAIT that’s where the mods are and they make profit?? B. The server owner makes a lot of money from premium queue so why can’t he use a little bit of the money and increase the server cap but instead they get rid of something that the community uses. Can’t pay his staff but he’s rolling in cash? Kinda stupid ngl.

**Comment by RAWRyoutube** [comment]
do you have a screenshot of them saying that

**Comment by Warriorrrr** [comment]
I assumed that option was re-enabled long ago, sorry for that. It's back on now but will take a server restart to take effect.
