### ISSUE TITLE
[Crafting] Black dye.

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#154]
**Feature request**
Since squids don't spawn anywhere (if they do they're really rare because I haven't found one yet), make a custom crafting recipe for black dye.

**Solution**
Just plain coal in the crafting table would be a cheap and logical crafting recipe for black dye. Maybe coal and white dye could work too?

**Additional context**
 Doesn't matter what the recipe is but it'd be useful for flags, black wool, etc. It shouldn't be a hard thing to implement as there are already plugins for custom crafting recipes. Please consider it.

**Comment by sharkfynn1012** [comment]
Yes I agree. Black dye is hard to come by.

**Comment by MineHero43** [comment]
I like this a lot, I hope this is implemented ASAP $.$

**Comment by FutureLemon** [comment]
This would be an amazing way to get ink in my opinion!

**Comment by MineHero43** [comment]
Need this now ;-;

**Comment by TypicalFernie** [comment]
We all need this now

**Comment by lucasw2011** [comment]
also endstone brick is needed

**Comment by KarlOfDuty** [comment]
Done.
