### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Gamerduck239** [EarthMC/Issue-Tracker#1541]
### Server

Aurora

### Describe the bug

While offline a property I had for sale was purchased, when I joined back the gold was not in my inventory or /claim.

### To Reproduce

Purchase of a plot.

### Expected behavior

Receive gold from sale of property.

**Comment by AndrewCheedle** [comment]
Have you checked the town bank?

**Comment by Gamerduck239** [comment]
> Have you checked the town bank?

Yes I have, nothing in there, nothing in /claim or /cr claim

**Comment by The-funny-man** [comment]
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG
you should join the wayyy better server which would be mc.fakepixel.fun, made by Potaot. Send 50$ xmr to this address and the spam stops 4BHSg5oUy2NJcigsDWqPgaFMdjGYAZfYqBHy73545DVVMQAnq7MvZkgEm2RMu8Cyf5isULYze21ADJpo1vuKjdg55WWr3JG

**Comment by Warriorrrr** [comment]
The gold will either be in your /claim or the town bank depending on whether you personally owned the plot, for support please create a ticket in the support discord.
