### ISSUE TITLE
[World] Biome Issues in the Yucatan Peninsula

### ISSUE THREAD

**Issue by Spencer9894** [EarthMC/Issue-Tracker#155]
Hey, the Yucatan Peninsula's coast has a lot of land areas as 'ocean' along with some inland areas with the same problem.

**Comment by AndrewCheedle** [comment]
As far as I know the biomes are not changed anymore and this issue is 5 years old. I will close this as it seems it wont be changed soon and If admins change their mind about fixing biomes it will be in the changelogs.
