### ISSUE TITLE
[World]

### ISSUE THREAD

**Issue by Saayuuki** [EarthMC/Issue-Tracker#1550]
### Describe the issue

Claim blocking from the whole town of Obama

### Coordinates

x:24904 y:67 z:-6689

### Screenshots

![Obama_Claimblock](https://user-images.githubusercontent.com/57344428/176362126-19b585cf-974a-4f79-ae41-21032e2a1144.png)

**Comment by Warriorrrr** [comment]
Please use the support discord for support related issues.
