### ISSUE TITLE
[Feature] [Suggestion] Concerning Emeralds

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#1552]
As emeralds are getting rarer, their price is rising to be even with the main currency of the server. In this event, arises an opportunity, to ensure an even playing experience for all players and to further incentivize voting. And in the following paragraph, I hope to convince you of not only its benefits but it's necessity to the server's economy and fun values.
              
              Adding emeralds to the vote crates. Now, one immediate concern would be that not all players want emeralds, but everyone wants gold. Well, the possession of emeralds will validate reasons for direct trade, bolstering the economy and supplying new opportunities for villager-exclusive items, alternative wealth for players in unfortunate circumstances such as those near larger countries where-in the emerald reserves of the area have been depleted, and even provide a reprieve from the worries of the impending "emerald depression". I am unsure however, of the intricacies of adding such means to the existing vote crates, whether it would justify a new head to be used for the crate item, or the amount and odds of them being rolled when compared to gold. I think that is best left to the developers of the server and the administrative team who oversees it.
                     
              Personally, I would be overjoyed should this suggestion get so much as negative feedback, and the idea of it being validated through the implementation of the features suggested, simply throws me into an ecstatic joy. I love this server, and have been playing for many years, despite its often stagnation. I will be suggesting more features, reporting bugs, and giving feedback to future threads. Thank you for your consideration.
              
              - With love and respect, _o_Toast_o_ , hermit of town Gobi.

**Comment by docwhomc** [comment]
Why not just allow villagers to buy items for emeralds as they normally do?

**Comment by BunbunToast** [comment]
> Why not just allow villagers to buy items for emeralds as they normally do?

Potential infinite feedback trades

**Comment by docwhomc** [comment]
> > Why not just allow villagers to buy items for emeralds as they normally do?
> 
> Potential infinite feedback trades

Can you clarify what you meant?

**Comment by BunbunToast** [comment]
> > > Why not just allow villagers to buy items for emeralds as they normally do?
> > 
> > 
> > Potential infinite feedback trades
> 
> Can you clarify what you meant?

Simply put, there are potential trades which can result in an infinite feedback loop, essentially providing the trader with infinite emeralds.

**Comment by docwhomc** [comment]
You mean the reversed versions of the standard trades? Just set them back to normal.

**Comment by CorruptedGreed** [comment]
Emeralds are still acquirable through deep lush caves throughout the map, also added to Celeste as fallenstar loot
