### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by EliteImp23** [EarthMC/Issue-Tracker#1553]

**Comment by AndrewCheedle** [comment]
This is not a bug, it is the anti xray plugin working slow due to low tps of the server. Normally the anti xray prevents you from seeing the actual gold ores and stuff but if you mine fast and the server lags hard you can see the anti xray ores appearing and disappearing a few seconds later

**Comment by AndrewCheedle** [comment]
If the ores disappear after a few seconds then it's not real

**Comment by EliteImp23** [comment]
Oh ok thank you
