### ISSUE TITLE
/vote in chat

### ISSUE THREAD

**Issue by ravenclaw-b** [EarthMC/Issue-Tracker#1555]
### Is your feature request related to a problem? Please describe.

Right now the chat is being completely spammed by people's /vote's.

### Describe the solution you'd like

There should be a way to disable seeing /vote messages in chat, for example /chat toggle vote_message.

### Additional context

![Screenshot from 2022-07-04 10-09-43](https://user-images.githubusercontent.com/89685822/177100834-0c119e4a-56f4-4d9d-af61-dc238036ff72.png)

**Comment by CorruptedGreed** [comment]
When people vote it sometimes reminds others, but this could be pursued in the future with a chat plugin rework
