### ISSUE TITLE
[Bug] Nation perms add perms to town members instead of nation members

### ISSUE THREAD

**Issue by xPlayedit** [EarthMC/Issue-Tracker#1556]
### Server

Aurora

### Describe the bug

When you try to add perms to a certain plot for nation members it adds chosen perms to town members.

### To Reproduce

/plot perm hud 
/plot set perm nation ItemUse on

### Expected behavior

Perm ItemUse should be assigned to nation members instead of town members.

### Screenshots

![Screenshot 2022-07-04 135718](https://user-images.githubusercontent.com/108671503/177150408-cbc424ae-1cca-4fb3-b049-9bb8f21f351f.jpg)
![Screenshot 2022-07-04 135754](https://user-images.githubusercontent.com/108671503/177150430-bffa30f9-cbe7-4ee7-8407-32eb6e4d747b.jpg)

**Comment by Warriorrrr** [comment]
Towny does not allow personally owned plots (plots owned by a player) to have nation perms enabled, use /plot evict and try it again.
