### ISSUE TITLE
[Feature] Stone ore -> Deepslate ore conversion (For coal)

### ISSUE THREAD

**Issue by doak-m** [EarthMC/Issue-Tracker#1557]
### Is your feature request related to a problem? Please describe.

Deepslate coal ore is a pain to find. No, I shouldn't say it's hard, it's literally impossible. (See screenshot attached) 
![image](https://user-images.githubusercontent.com/105933226/177175236-af606b88-22b2-41d5-87a9-96ee785e6e01.png)

### Describe the solution you'd like

Same recipe for deepslate coal ore as for TN. Stone coal ore + Deepslate.

**Comment by CorruptedGreed** [comment]
Being added next changelog
