### ISSUE TITLE
Vote Crate Display Message Formatted Incorrectly

### ISSUE THREAD

**Issue by Aylywyn** [EarthMC/Issue-Tracker#1559]
I noticed it about a week ago when I won 100g in a vote crate.  Didn't think anything of it until I saw the same thing yesterday for someone else.  It displays something along the lines of "g|Player|Name has won dl|100dl| Gold in a vote crate  /vote" instead of "Aylywyn/Someone has won 100 Gold... ...".

**Comment by Aylywyn** [comment]
Adding one more,  apperas "l6Totem of Undying ffrom" a vote crate.

**Comment by Warriorrrr** [comment]
This is now fixed, seemed to only apply to giant gold crates.
