### ISSUE TITLE
[Feature] [Suggestion] Deep Ender Chests

### ISSUE THREAD

**Issue by Aylywyn** [EarthMC/Issue-Tracker#1560]
### Is your feature request related to a problem? Please describe.

1) People complaining about/at least mentioning the lack/scarcity of secure storage (i.e. the size of Ender Chest/no Shulker Boxes);
2) The new Economy with access to Gold in an Ender Chest.

### Describe the solution you'd like

Take a midnight-and-falling-asleep idea as intended...

Let's not add Shulker Boxes or Ender Double Chests but add one more layer to the Ender Chest system, kind of like zooming out on a Map.

The recipe for a Deep Ender Chest is an Ender Chest surrounded by Ender Chests (9xEC...), Hardness and Breaking Time as an EC or, heck, 1.5x more.  Model could just be an EC with a Diamond lock not Gold and maybe purple rather than magenta particles.  A Deep Ender Chest drops nothing if mined without a Pickaxe and always only 64 Obsidian if mined with one; Silk Touch does NOT affect this. 

The DEC acts like an EC in that every DEC is the same DEC for a Player but is separate from an EC.  Contents/Gold do NOT count to the Gold Balance in the Economy plugin.

1) And extra 27 slots of deep, secure storage plus space specifically isolated from the Shops; 2) portable storage in that it somewhat frees up the EC to be used "in the field" with a ST Pick as a pseudo-Shulker Box but NOT particularly portable in and of itself, on purpose, since placing and picking up loses 9 EoE and 8 Obsidian; 3) a "great" way to store 4096 Obsidian in a single stack if you don't mind losing 576 Eyes Of Ender and 512 Obsidian in the process.

EDIT1:  To add, obviously(?) a DEC cannot go in an EC, and the opposite, no ECs in a DEC.

**Comment by jkmartindale** [comment]
Is this even possible to do with vanilla clients? Once you get to custom models, hardness, etc. I don't think that's something you can do without forcing everyone to install a client mod.

**Comment by Aylywyn** [comment]
Absolutely no idea, didn't really look into the midnight-brainstorm.  But I wouldn't be at all shocked if someone hadn't created a plugin that would do multiple, likely coloured, ECs and there is already custom recipes.

**Comment by Warriorrrr** [comment]
This was added, but only for premium players.
