### ISSUE TITLE
[Feature] Allow Premium players to join directly.

### ISSUE THREAD

**Issue by WesleyBryie** [EarthMC/Issue-Tracker#1561]
### Is your feature request related to a problem? Please describe.

I think it would be cool to have a direct way to join the server.

### Describe the solution you'd like

A simple subdomain could work, which would be something like aurora.earthmc.net.

**Comment by Aylywyn** [comment]
What would be the benefit over the current "front-of-the-queue"?

**Comment by jkmartindale** [comment]
> What would be the benefit over the current "front-of-the-queue"?

This is probably in response to yesterday, where a DDoS attack on the server host caused network issues. People already connected to Tera Nova/Aurora were able to stay in the world, but the hub world couldn't connect to the servers and send players from the queue into the worlds.

But yeah, the queue exists. In a case where there's space left in the world for more players, a direct connect saves you like 10 seconds tops and isn't really that much of a benefit. If the world is full, the server shouldn't let you connect anyway and you should sit through the queue in the hub world. The only time this changes anything is if there's a repeat of what happened yesterday. Given that connection issues like that are comparatively rare and opening up direct connects might have a security impact, I'm not sure this justifies the effort.
