### ISSUE TITLE
[Bug] Buying potions shop chest is not working properly.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1562]
### Server

Aurora

### Describe the bug

The count of potions at a buying shop chest is incorrect. 
This shop chest can buy even when the chest is full.
If I sell potions to full chest, the potion will disappear.
This bug has been occurring since the shop plugin update which allows up to 27 potions to be sold for once.

### To Reproduce

1. Make buying shop chest that buy potions.
2. Sell potions to it and full up the chest.
3. Sell more potions and potion will disappear.

### Expected behavior

When the shop chest is full, it stop buying potions.

### Screenshots

https://www.youtube.com/watch?v=TumG9BhAy20

**Comment by asyi0** [comment]
I have found that similar problems occur in the beehive Buying shop.
If you sell bee nests that cannot be stacked due to different bee counts/honey levels to buying shop that does not have enough empty slot, the hives that do not fit in the slots will disappear.

**Comment by CorruptedGreed** [comment]
Should be resolved from eventually migrating to new fork of the shop plugin (Quickshop-Reremake -> QuickShop-Hikari)
