### ISSUE TITLE
Add a method to obtain items that are not available in TA

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1563]
### Is your feature request related to a problem? Please describe.

The following items are available in TN, but there seems to be no method to obtain them in TA.

- Purpur Block
- Heart of the Sea
- Phantom Membrane
- Emerald Ore
- Deepslate Coal Ore

In addition, it would be interesting to obtain the following items, which are disable in the TN.

- Dragon's Breath
- Nether Gold Ore

To be honest, I want Chorus Fruit, Elytra and Shulker Box but I know these items will do something wrong. 
However, I think the above listed items should be added.

### Describe the solution you'd like

I would like to see it added in the Custom Recipe or trading from Villager/Wandering Trader.

####  Purpur Block
![2022-07-27_185711](https://user-images.githubusercontent.com/92248609/181243226-0418a194-dd3c-4e9c-8692-57351d530e59.png)

####  Heart of the Sea
![2022-07-27_185741](https://user-images.githubusercontent.com/92248609/181243435-7f959bef-e0e3-45e2-92ec-cd81fcfd5f6e.png)

####  Phantom Membrane
![2022-07-27_185410](https://user-images.githubusercontent.com/92248609/181243463-be83e882-0a7e-4f54-ad21-ad45b6d7784a.png)

####  Emerald Ore
![2022-07-27_205408](https://user-images.githubusercontent.com/92248609/181243491-e63fc994-f84b-4018-a9b1-b983e6717a1d.png)

####  Deepslate Coal Ore
![2022-07-27_205430](https://user-images.githubusercontent.com/92248609/181243520-001d2c8b-8a49-45c4-95e0-dab37217f037.png)

####  Dragon's Breath
![2022-07-27_185920](https://user-images.githubusercontent.com/92248609/181243541-7490c7c0-e8af-4423-a0c4-62f79024eb6f.png)

####  Nether Gold Ore
![2022-07-27_211045](https://user-images.githubusercontent.com/92248609/181243651-a096302b-138d-4fcc-b174-36f27ceb6cd3.png)

**Comment by CorruptedGreed** [comment]
Purpur/Heart are added, Coal will be soon. The others should be added in different implementation soon

**Comment by Veyronity** [comment]
:soontm:
