### ISSUE TITLE
Nova New Day Broken + /nc and /tc not working [BUG]

### ISSUE THREAD

**Issue by GalaxyGaming200** [EarthMC/Issue-Tracker#1568]
### Server

Nova

### Describe the bug

New Day Towns are meant to fall 42 days after the mayor hasn't been online.
But when new day comes around the towns do not fall.

Also.
/nc and /tc do not work
it comes up with unknown command.
you can use /nation chat and /town chat

### To Reproduce

When New Day Comes nothing will fall.

try /nc and /tc

it will not work.

### Expected behavior

Towns to fall and new day to happen.

/nc and /tc  to go to their channels.

**Comment by GalaxyGaming200** [comment]
/nc and /tc fixed!
new day not

**Comment by jkmartindale** [comment]
![image](https://user-images.githubusercontent.com/11380394/183270062-bba6f213-9520-4d72-971d-e0fc0b49d15b.png)

Fix intentionally disabled the town inactivity timer on Terra Nova

**Comment by GalaxyGaming200** [comment]
oh sad :(
i hope it can come back as maybe lets all people switch instead
