### ISSUE TITLE
Nether portals are not being protected by rules

### ISSUE THREAD

**Issue by Herobrine-bug** [EarthMC/Issue-Tracker#1571]
### Is your feature request related to a problem? Please describe.

The rules protecting railways and ice roads in the wilderness from being destoried. However there's no rules about what to do with nether portals in wilderness. Therefore the nether portals belonging to nether roads network can be destory by anyone and without consequence.

### Describe the solution you'd like

Rules need to protect every nether portal that connect the inside of a town and the nether, just like they protect railways and ice roads. Or they can point out that portals connecting railways or ice roads are considered part of them so will be protect with them.

**Comment by docwhomc** [comment]
As long as the portals in the overworld are in or near a town, they should be covered by Rule 3.1; and as long the portals in the nether are near the ice and/or rails, they sould be covered under Rule 3.2. So I'm not sure why nether portals would need to be explicitly protected; plus, I could see it leading to issues if the rule isn't worded properly.

**Comment by Herobrine-bug** [comment]
> As long as the portals in the overworld are in or near a town, they should be covered by Rule 3.1; and as long the portals in the nether are near the ice and/or rails, they sould be covered under Rule 3.2. So I'm not sure why nether portals would need to be explicitly protected; plus, I could see it leading to issues if the rule isn't worded properly.
