### ISSUE TITLE
Mobs Despawning

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#1574]
### Server

Aurora

### Describe the bug

Mobs are despowning on Aurora when they shouldn't. Specifically, passive and tamed mobs are despawning, even when the number of mobs of their respective type per chunk has not exceeded the limit for the mob type.

For example, I had 5 dogs/tamed wolves in one chunk of my town for weeks without issue. On or about July 27, 2022, one of them despawned. I've spoken with other players who began experiencing similar issues around the same time.

### To Reproduce

Have some number of mobs in a chunk that is under the per chunk limit for their type.
Wait to see if they despawn.

### Expected behavior

Passive, neutral, and tamed mobs should not despawn on their own.

### Additional context

The July 27, 2022 changelog entry states in part:
> Fixed an issue where the blaze mob limit would not be respected by mob spawners.

Perhaps something went wrong when the blaze spawner bug was being fixed, seeing as these issues seem to have started at roughly the same time the changes were made.

**Comment by Aylywyn** [comment]
I'll add information if needed here but see Open Support Ticket #ticket-32293-mob for details and examples.

**Comment by Quandaleslayer2** [comment]
The problem could be other mobs walking into said chunk despawning the others, recently the last sheep i had ( the 5th one) despawned just like the others, i have no other sheep in the chunk and no sheep spawn in my region.
![efaewxdw](https://user-images.githubusercontent.com/110796254/183322514-0f99b320-9e5a-4e0b-a708-fe2f9f85cd85.PNG)

**Comment by Quandaleslayer2** [comment]
blue lines above are chunk borders, red circles are missing sheep

**Comment by docwhomc** [comment]
I don't know if mobs walking into a chunk is supposed to despawn mobs already in the chunk, but it's a horrible idea seeing as it allows players to despawn other players livestock if they can get mobs into the same chunk. If I recall correctly, we had a somewhat similar issue back when I was a mod, it involved entity cramming and chicken egg spamming being used to kill off the mobs in a shop.

I've heard that we aren't supposed to be able to breed mobs when the cap is reached. But I've breed cows in a chunk with 2 cows and 2 sheep, and right after the 3rd cow spawned, one of the 3 despawned.

@Warriorrrr Could you provide some details about this? For instance:
- Which plugin is being used to impose the mob per chunk limits?
- What actually is the expected behavior of the plugin?
- What are the limits for different mobs?

**Comment by Aylywyn** [comment]
Transferring this from the Ticket as per DocW's suggestion.  The examples with fixed time and location.
Concerning the Cow Pen at -20120 -9940 or so and the Chicken Pen a few chunks away (at -20230 -9905) and nearby Sheep in a few locations.
7/28/2022 
"Today, between 12:15 and 12:25 am Sask Time/Mountain (15 minutes ago as of this message).  In the Cow farm mentioned above."
"6:20pm [Saskatchewan Time, currently Mountain] (one minute previous to this).  Cows disappeared in front of my face as I was about to feed them, just the Adults.  Oh, and it did the Adult Pigs and Chickens in to, within the last half hour or so.  Another edit:  And a pen of Sheep for the first time within the last 45 minutes or so (after the original post but before the edit so like 6:30 to 7).
8/2/2022
"5:08, a minute ago.  Two Adult Cows disappeared while I was looking at them.  Two Nametagged Adults and a Baby did not.  Umm... there was the noise of Baby Turtles hatching about a minute or two afterwards in the chunk to the south."

**Comment by Warriorrrr** [comment]
Implemented a possible fix for this, reverted to the old mob limit config and created a seperate plugin for handling spawner mobs.

**Comment by Aylywyn** [comment]
Not OP but I've had no problems with Mobs Despawning and the Bees have been more productive and less "stupid" since the reversion.

**Comment by docwhomc** [comment]
Things seem okay so far. If we could get the official list of the mob per plot limits, that would be great.
