### ISSUE TITLE
i vote but dont get vote crates[Bug]

### ISSUE THREAD

**Issue by bobthecreat0r** [EarthMC/Issue-Tracker#1576]
### Server

Nova

### Describe the bug

for 3 days now i have been voting but no crates

### To Reproduce

i dont get crates after voting

### Expected behavior

getting crates after voting

**Comment by Warriorrrr** [comment]
Are you online when you vote? When you vote offline it's currently only saved for 1 day, after that the vote will expire.

**Comment by Warriorrrr** [comment]
Closing due to no response.
