### ISSUE TITLE
Chat Messages not Visible [Bug]

### ISSUE THREAD

**Issue by HowAboutAStone** [EarthMC/Issue-Tracker#1578]
### Server

Aurora

### Describe the bug

I have been trying too promote my Shop latetly but my GF noticed that even though i was sending chat messages in the Global Chat that she couldnt see any of them. She did not /ignore me and Multiple other People have confirmed that they cannot see my messages even tho they never /ignored me. 
I hope this can get fixed soon as this is detremental too my shops success :/

Thank you for adressing this,
HowAboutAStone

### To Reproduce

I realy dont know

### Expected behavior

My Chat message would be visible in chat

**Comment by FixTheAdmin** [comment]
Hey! Sorry about that. Could you paste the message you sent here? All messages are logged and saved where Minecraft is locally installed.

**Comment by HowAboutAStone** [comment]
It was ▬ Netherite Ingots JUST 13g Each! And More ▬♦♣♦▬ At →→ /n spawn Austria-Hungary ←← "Hanse" Shop

I think the problem is that tried sending the same message twice even if it was 15min or more apart. But even writing something that was similar didnt work.

**Comment by Warriorrrr** [comment]
Sending a message that's similar to the last one you sent will cause it to not get sent to other players.
