### ISSUE TITLE
Shop Purchase to Ender Chest transfer

### ISSUE THREAD

**Issue by HowAboutAStone** [EarthMC/Issue-Tracker#1579]
### Is your feature request related to a problem? Please describe.

Hello,

I propose that the Gold you gain from Shop purchases should go directly in the Ender Chest and only in your inventory when its full.
I have been trapped recently and couple of min after being in this very slow killing trap i got 6 Gold Blocks from my Shop in my inventory while i was being killed, wich i think obviously is an issue that this is possible.
Also yesterday i was walking around with nothing in my Inventory when 2 Hunters came over my way and as i was running from them i got 8 Gold Blocks in my Inventory. 
It just feels unfair that it goes in the Inventory as i barely can walk outside without risking a Gold when someone buys something from my shop.

I hope this described the need for this feature and that its implementation might cause players too travel more and thank you for adressing the Issue,
HowAboutAStone

### Describe the solution you'd like

Gold get directly transfered too your Ender Chest Instead of going in your Inventory unless the Chest is full

**Comment by Warriorrrr** [comment]
This would be a hard thing to add, since the economy plugin doesn't have a guaranteed way of figuring out what plugin caused the deposit. If this was added, it would likely be an opt-in feature.

**Comment by Fruitloopins** [comment]
what

**Comment by Fruitloopins** [comment]
why are you annoying

**Comment by CorruptedGreed** [comment]
Could be pursued in the future
