### ISSUE TITLE
[Mechanic]Repairable tridents

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#158]
**Is your feature request related to a problem? Please describe.**
When people will start to get tridents they will be extremely rare and even when enchanted with mending very few will dare to use it in case it gets broken.

**Describe the solution you'd like**
To solve it I propose a custom crafting recipe (or plugin) be added that makes the repair of tridents possible as they  can currently only be repaired with other tridents! Examples of these crafting recipes could be 8 gold around a trident or use of water based rare items such as nautilus shells, Turtle shells, prismarien shards and crystals. etc

**Comment by NeonKrby** [comment]
Alright so i have one problem with that. Repairing with Mending would be super easy because of blaze spawners. Since they are so common on the server people could easily get back their trident.

**Comment by TypicalFernie** [comment]
Mending books cost 8 gold. I'm sure you don't want to waste 8 gold every time you need to repair your trident when you can just buy a mending book.

**Comment by NeonKrby** [comment]
Fernie mending is an enchantment not a repair item. If you put it on your trident every time you get xp it repairs durability.

**Comment by TypicalFernie** [comment]
I was replying to shiraz, not you.

**Comment by NeonKrby** [comment]
oh

**Comment by BowShot118** [comment]
Am I the only one asking how to get tridents here?

**Comment by AidanMSad** [comment]
@bowshot118 It's by killing drowns  with tridents (the new 1.13 mob)

And they have a 5% of dropping it without looting.


@TypicalFernie mending prices are dropping alot so even less of a reason

**Comment by BowShot118** [comment]
O.o thanks for telling me xD
