### ISSUE TITLE
can you add a custom shukler shell recipe

### ISSUE THREAD

**Issue by aresdog1** [EarthMC/Issue-Tracker#1581]
### Is your feature request related to a problem? Please describe.

i have a tough time geting things back and forth and it sucks cuz if like i wana move to a new town i have 2 move all my stuff chest by chest and it takes a while. so shulkers whould be great if i had some. i i had shulker boxes then i chould move all my stuff much faster. i whould also promote more productivate in nova. and more production means more players which means that the sveaer whould be even better. also all the people of nova whould most likely love the i dea of shulker boxes.  that can help with so many things. 

### Describe the solution you'd like

i whould like it if the recipe was something like this:

gold    eye of ender    gold

end rod    end rod   end rod  

gold       egg    gold

### Additional context

i really hope you can make a comstom recipe becuse that whould relly help us out

**Comment by aresdog1** [comment]
wait you can dupe

**Comment by aresdog1** [comment]
make it impossiboe 2 dupe

**Comment by aresdog1** [comment]
i jsut wana be able 2 move form a town and be able 2 carry all of my stuff that i horded

**Comment by CorruptedGreed** [comment]
Reference #1626
