### ISSUE TITLE
[Bug] Litematica easy place no longer works

### ISSUE THREAD

**Issue by kamaboko1204** [EarthMC/Issue-Tracker#1583]
### Server

Aurora

### Describe the bug

We can't use litematica's easy paste

### To Reproduce

Blocks are no longer placed when using easy paste

### Expected behavior

 I suspect the recent anti cheat plugin is interfering.

### Additional context

EartMC's map art and architecture rely on easy paste.
Especially for map art, a decrease in production will be inevitable.

**Comment by Warriorrrr** [comment]
Likely caused by the new anticheat, easy place causes packets to be sent differently than a vanilla client would.

**Comment by kamaboko1204** [comment]
Do you plan to fix that?

**Comment by Egoogoo** [comment]
I CAN NOT LIVE WITHOUT EASYPLACE, i am addicted to it.

**Comment by kamaboko1204** [comment]
The pace at which architecture and map art is created has slowed considerably since easy paste was disabled.It has led to a decrease in palyer

**Comment by Egoogoo** [comment]
Ye i build 1/4 of my cathedral after easyplace got removed it was not easy to say the least. And i gradually stop playing as well
