### ISSUE TITLE
Multiple People getting stuck in my Shop floor

### ISSUE THREAD

**Issue by HowAboutAStone** [EarthMC/Issue-Tracker#1584]
### Server

Aurora

### Describe the bug

For 3 Days now my plot has expierencing and wierd issue, sometimes the entrance and inner Calcite/Amethist floor causes players (including me) too get stuck in the floor. Its not consitent exept for the places it occures, it happens randomly too everyone and if your stuck you basicly fall halfway in the floor and just get stuck in the block, at the same time others are not affected by this but can cant stuck too (not consitent). 

This has been very annoying as i have gotten stuck over 30 times now and replacing blocks doest help, mods also tried helping but it just temporarily stops it then it comes back at a later date for some unknown reason. I have changed nothing on the plot befor this happend and it just appeared out of nowhere.

Please Help soon its realy debilitating,
HowAboutAStone

### To Reproduce

Dont Know

### Expected behavior

I can walk on my floor and go in my shop

### Additional context

Annoying glitch that only affects 1 of my plots nowhere else.

**Comment by CorruptedGreed** [comment]
Open new issue if not fixed
