### ISSUE TITLE
[Bug]Sometimes A new day don't come and town fallings does not happen.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1585]
### Server

Aurora
(However, it used to occur in Nova as well)

### Describe the bug

Usually, "A new day" comes at 12:00 (UTC+1) and towns that have been inactive for 42 days fall into a ruin, but sometimes "A new day" does not come and the town does not fall.

The reason is unknown, but it seems to me that new day often does not come when TPS is low (around 10).
In most cases, next time after a server restart, a new day comes as usual.

### To Reproduce

Just be online  in the server when 12:00 (UTC+1).

### Expected behavior

A new day comes and  inactive towns fall into a ruin.

**Comment by Warriorrrr** [comment]
Will be fixed after next maintenance when I update Towny.

**Comment by asyi0** [comment]
@Warriorrrr 
There were steady NEW DAY every day for months since the update, but it didn't come today. Could you please check?

**Comment by asyi0** [comment]
This issue seems to be happening again recently..
