### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Nexfuckedyourmom** [EarthMC/Issue-Tracker#1586]
### Server

Nova

### Describe the bug

I have been offline for a while and I came back today and all of my gold is gone, ALL of it. It was Iin an ender chest and o have over 2 stacks because I was saving up to help make a nation and I don't know how it happened since it was in an ender chest.

### To Reproduce

I don't know.

### Expected behavior

For my gold not to be gone?

### Additional context

I've tried looking through the discord but I can't see that anyone is having this issue but I'm going to look some more

**Comment by Warriorrrr** [comment]
Please use the [support discord](https://discord.gg/EZBYmpp) for support.
