### ISSUE TITLE
[Feature] Re-enable weather cycles

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1590]
### Is your feature request related to a problem? Please describe.

I believe that weather enable will change the way the town looks and the landscape and add a new level of fun.
Also, MobHead, powder snow, which are currently unavailable, can be obtained without using custom recipes through weather.

### Describe the solution you'd like

enable weather cycles,
In the early days of Terra Aurora, weather cycles used to exist, and I believe they are still possible.

**Comment by rogue-rabbit** [comment]
dont please this caused a lot of lag from what i remember

**Comment by Warriorrrr** [comment]
Weather cycle is re-enabled for *now*, will monitor to see if any performance issues arise.
