### ISSUE TITLE
Add a way to obtain the Otherside disc. 

### ISSUE THREAD

**Issue by deafkite42** [EarthMC/Issue-Tracker#1591]
### Is your feature request related to a problem? Please describe.

Currently, it is impossible to obtain the Otherside music disc in EarthMC, which is frustrating for people who want a full collection of discs. 

### Describe the solution you'd like

Provide some way to obtain Otherside. This could simply be added to the drop table for creepers killed by skeletons, or perhaps something more creative.

**Comment by Colt44Magnum** [comment]
This could be added through mcmmo:fishing

**Comment by CorruptedGreed** [comment]
Added to vote crate.
