### ISSUE TITLE
[Feature] Added Sculk Vein recipe

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1592]
### Is your feature request related to a problem? Please describe.

In 1.19, Sculk blocks can now be crafted with custom recipes, but only Sculk Vein is missing.
It is not impossible to create, but it is unnatural that only the Sculk Vein.

### Describe the solution you'd like

"Sculk" "Vein" to make it possible to create Sculk Vein.

**Comment by Warriorrrr** [comment]
Sculk vein can be obtained by killing a mob near a sculk catalyst plus silk touch.
