### ISSUE TITLE
Server-side network problems

### ISSUE THREAD

**Issue by Wadamaro** [EarthMC/Issue-Tracker#1593]
### Server

Aurora

### Describe the bug

I was able to log in to the Aurora server without any problems until mid-October, but then until today, after being sent to the Aurora server, I get kicked back to the hub about 30 seconds.
Also, the terrain is slow to load, but more than that, the response to other people's chats and commands I type is terribly slow. The moment the chat box reacts, I get kicked off the Aurora server.
Currently, I am not able to work at EMC at all.
In addition to myself, a small number of other players accessing EMC from Japan have also complained of the same situation.

### To Reproduce

I am login to EMC from Japan and my internet connection is extremely good. I have a wired fiber optic connection and have no speed issues. I can also connect to other minecraft servers without any problems, so I assume the problem is on the EMC server side.
After asking about this in a Discord ticket, I was told that the problem was due to EMC changing proxy servers.
I have been purchasing premiums for a year since June and would like to see an immediate improvement.

### Expected behavior

I would like to see the status of proxy servers, etc. returned to their previous state.

### Screenshots

https://user-images.githubusercontent.com/117238066/199391643-1e1a0662-2f9e-4e56-956f-1adeea3bc370.mp4

**Comment by Wadamaro** [comment]
The symptoms are exactly the same as issue #1594.

**Comment by Warriorrrr** [comment]
I'm personally not sure what's causing this since I'm just the dev, an admin will have to look into this.

**Comment by kamaboko1204** [comment]
> I'm personally not sure what's causing this since I'm just the dev, an admin will have to look into this.

It is especially common in Asia.Since the previous update, I can't log in in the first place.sure me too

**Comment by Warriorrrr** [comment]
![image](https://user-images.githubusercontent.com/50800980/201782002-b6091125-0cbf-464e-9f13-d123f3e66b2a.png)

**Comment by CorruptedGreed** [comment]
Assumingly resolved, open new issue if problem persists
