### ISSUE TITLE
[Bug]Can't open other peoples' lecterns.

### ISSUE THREAD

**Issue by zucaluca** [EarthMC/Issue-Tracker#1595]
### Server

Aurora

### Describe the bug

My issue started when I tried to place a book and quill inside a lectern in my own town. I switched plot residents' permissions to item use and switch on, yet no resident could open the lectern still. I went to n spawn new_york and others to try and open theirs', still nothing.

I can open one made by me but my residents cannot.

### To Reproduce

![2022-11-02_11 31 04](https://user-images.githubusercontent.com/47117287/199532499-363a2690-a81e-4d99-a282-d6c4648da70b.png)
NOTE: the first time you rightclick the lectern, it will say Owner doesn't allow allies to destroy. If you click it again and again thereafter, it says Sorry this event was cancelled.

This is at n spawn new_york. You can see this specific plot's permissions at the bottom of chat cropped. You can notice they don't allow outsiders to switch or use items, though again, I tried this in my town and neither worked.

### Expected behavior

I wanted to read it.

### Screenshots

![2022-11-02_11 31 04](https://user-images.githubusercontent.com/47117287/199532499-363a2690-a81e-4d99-a282-d6c4648da70b.png)

### Additional context

Thanks and best regards,
zucaluca

**Comment by Warriorrrr** [comment]
Working on a fix for this now.

**Comment by Warriorrrr** [comment]
Fixed in next towny update.
