### ISSUE TITLE
[Feature] Add Purpur block recipe

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1596]
### Is your feature request related to a problem? Please describe.

Purpur blocks were available through trade from Merchant in Terra Nova, but not available in Terra Aurora due to lack of Merchant. I hope a recipe will be added as they are useful blocks for building.

### Describe the solution you'd like

Add Purpur block recipe, Terra Nova, was craft with purple dye and stone bricks, 
so a recipe like the one in the image would be good.

### Additional context

Recipe Idea,

![Purpur](https://user-images.githubusercontent.com/86207737/200105708-1bfcec2c-d449-45e6-bc27-9c7607dda361.png)

**Comment by CorruptedGreed** [comment]
We have added a recipe for Purpur blocks.
