### ISSUE TITLE
[Bug] 1.19 related blocks does not support MCMMO.

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1598]
### Server

Aurora

### Describe the bug

EarthMC's MCMMO is not compatible with 1.19 it does not respond to skulk, mud, mangroves, etc.
So the mangroves do not respond to Tree Feller and Skills such as double drop are not triggered.

### To Reproduce

Mangrove‐ Grown and cutting Mangroves from saplings.
Sculk‐ Mine Sculk generated from the erosion of the skulk catarist.
Mud‐ Mine Mud created by using water bottle as dirt.
MCMMO does not respond to 1.19 blocks generated by these methods.

### Expected behavior

Support for version 1.19 or fix of MCMMO plugin

**Comment by ZePua** [comment]
@Warriorrrr 
Is this Issue going to be fixed or is it being put on the back burner?
Very sorry to mention, but it is very troublesome that MCMMO does not apply to Mangrove and Mud.

**Comment by AndrewCheedle** [comment]
a year later

**Comment by CorruptedGreed** [comment]
Should be fixed, otherwise mcMMO has not updated it yet
