### ISSUE TITLE
[Feature] Nation titles set by '/n set title' appear on global chat

### ISSUE THREAD

**Issue by Snowyy4K** [EarthMC/Issue-Tracker#1599]
### Is your feature request related to a problem? Please describe.

It was a minor feature yet very useful or helpful, even if done simply for fun. I was told they're quite long gone.

### Describe the solution you'd like

Bringing back the feature if possible, I'm pretty sure there's still an option for it in the towny plugin release emc runs on.

### Additional context

I'm sure players would love it working again.

**Comment by Murder-Hobo** [comment]
i agree
