### ISSUE TITLE
Claim Limit Increase/New Gold Sink/"Fillager"

### ISSUE THREAD

**Issue by Aylywyn** [EarthMC/Issue-Tracker#1601]
### Is your feature request related to a problem? Please describe.

Some people do not like to recruit and/or deal with too many town members.  A method for raising the Claim Limit may be desirable.  Inflation can be an issue.  A new gold sink will be a side benefit.

### Describe the solution you'd like

The ability to purchase an NPC Town Member for your town in order to get the extra 8 chunks of claim limit.  Essentially spending gold on a villager to help fill you claim limit cap, a "Fillager" if you shouldn't.  A cost of 256g would basically triple the cost of an over-claim limit plot, adding 32g per plot; while a 128g cost would double it to 16g plus 16g.

### Additional context

Provides a way to Mine, Vote, Shopkeep, or Hunt your way to a bigger town (or Buy Mystery Crates and Sell Player Heads...) over the need to recruit bulk inactive players just to cap out.

Gives another Gold Sink to slow server inflation.

Possibly (though inching towards P2W) gives the chance to add, say, "1 Free Fillager Per 3 Months Premium".

Preferrable, IMO, to a simple Over-Limit charge or Towny Bonus Claim as it shows up in Population stats to compare towns and gives an obvious sign that a town is purchasing land over recruiting.

**Comment by CorruptedGreed** [comment]
Denied by Fix previously in the discord forums.
