### ISSUE TITLE
[Recipes] Add the Heart of the Sea recipe, so the Conduit can be crafted.

### ISSUE THREAD

**Issue by keijodputt** [EarthMC/Issue-Tracker#1604]
### Is your feature request related to a problem? Please describe.

In Aurora there is no way to obtain a Heart of the Sea, but Nautilus shells are obtainable by fishing. In Nova you can trade with the Merchants to get the Heart of the Sea, it usually requires a raw porkchop and a bucket of water.

### Describe the solution you'd like

Add a custom recipe to craft the Heart of the Sea, it would help tremendously in ocean biomes. and its humming is pretty unsettling :-)

**Comment by Colt44Magnum** [comment]
Yeah they should either add a recipe for crafting or add it as a trade to villagers

**Comment by Aylywyn** [comment]
Simple copy/paste of my side of a Discord thread called "Add Conduit".

How common do you think they should be?  A custom recipe is probably the way to go.  Medium could be Beacon+8 Nautilus Shells=Heart Of The Sea then 8 more Shells to a Conduit.  Easy would swap the Beacon for an Ender Pearl and 4 of the Shells for Lapis.  Hard might be... uh... 4/5 Beacons+5/4 Nautilus Shells=Heart Of The Sea.

Throwing out controversy while here...  Sponge = 5 Horn Coral Blocks + 4 Smooth Quartz Blocks (yellow bumpy sea blocks plus heated quartz (basically silica gel)).

So you'd go the Easy route and have a recipe like Heart Of The Sea = Ender Pearl + 4 Nautilus Shells + 4 Lapis (a sphere plus ocean stuff plus blue stuff,  that conveniently costs about the desired amount).  Then HOTS + 8 NS = Conduit.    And, yeah I agree, that puts a Conduit at around the current cost of a Beacon, maybe 12g.

Ignore the Sponge bit.  Or rather don't :-) ...
