### ISSUE TITLE
Add controller support to EMC

### ISSUE THREAD

**Issue by Craig1224** [EarthMC/Issue-Tracker#1605]
### Is your feature request related to a problem? Please describe.

Every time I try to play on EarthMC using a controller, it works and then I suddenly get frozen in place without being able to move. It’s very annoying because walking around is basically impossible on a controller since you are always getting glitched into blocks. On other servers, using a controller works fine. I’m using the controllable mod by the way.

### Describe the solution you'd like

I talked to the owner of the mod and he said that it’s because EarthMC has a set player value for walking which is 0 (not moving) and 1 (moving at full speed). I guess that this is to prevent hackers from using fly and speed hacks, but since I’m on a controller, there are many different speeds between 0 and 1 because it’s a joystick and not a key. The server should consider making the allowed speeds between 0 and 1 and not just those numbers so that players aren’t frozen in place while trying to move.

### Additional context

“Controllable allows you to move at speeds and directions not possible with a keyboard. Basically with a keyboard you can move either 0 or 1 (not pressed or pressed), however with a controller you can move 0.25, 0.4, 0.75 (depends how much you push your thumbstick). The server you're on probably doesn't like them values even though they aren't speed hacks and perfectly server accepted values according to vanilla.” - MrCrayFish (creator of the mod)

**Comment by Warriorrrr** [comment]
This is not possible, the anticheat only allows movement that's possible with the vanilla client, and that's not configurable by us.
