### ISSUE TITLE
[Bug] Get kicked when doing instant mining ( You are sending too many packets )

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1607]
### Server

Aurora

### Describe the bug

When I was doing instant mining, I got kicked and a message `You are sending too many packets :( ` was shown.
I think it has been happening since today or yesterday.

### To Reproduce

Just do instant mining for few seconds (e.g: digging dirts with eff4 dia shovels or mining stones with eff5+haste2)

### Expected behavior

Don't be kicked while in instant mining.

### Screenshots

https://www.youtube.com/watch?v=06QHVyQrch8

**Comment by Warriorrrr** [comment]
Fixed
