### ISSUE TITLE
/trade command during events

### ISSUE THREAD

**Issue by B2315** [EarthMC/Issue-Tracker#1608]
### Is your feature request related to a problem? Please describe.

There was recently a hugeee event at Indochina and we had some security system to stop people from sneaking in items which would make it unfair and ruin the race for people.

We wanted there to be able to be spectators + players, so we had spectators on the other side of a glass wall, but people found a way around this by using the /trade command. Then they splashed invis potions on everyone and speed which meant we had a huge issue. Luckily jump boost was not splashed as this would have made the parkour very very easy.

I think this would be very beneficial because what makes EarthMC different to other servers is the community and the events which take place, so help from the admins/mods would make events even more creative and appealing to the EarthMC community.

### Describe the solution you'd like

For large events or places which host events regularly to have something so that people are unable to do /trade within a certain radius and smuggle items in.

**Comment by Warriorrrr** [comment]
If the mayor of the town where an event is taking place creates a ticket at least a few days in advance we can have it blocked temporarily.
