### ISSUE TITLE
[Plugin][Mechanic] Public crafting tables

### ISSUE THREAD

**Issue by BananaPuncher714** [EarthMC/Issue-Tracker#161]
**Links**
https://github.com/BananaPuncher714/PublicCrafters
https://www.spigotmc.org/resources/public-crafting-tables.50686/

**Why this**
For a more team-like feel, and more realism, making crafting tables public would allow town members to see what others are crafting, and help as well. Also, due to the amount of resources and no organization, it is hard to find all the components for crafting recipes, and this plugin allows items to be left in the table like a chest. It does not interfere with any custom or vanilla crafting recipes or mechanics, and does not have any item duplication whatsoever. It is open source and supports 1.13.2.

**Additional context**
I am the creator and maintainer, and am not biased in any way by wanting to add this to the server. I am also an active player and would love the chance to camp crafting tables. The source code is up to date and prevents duplication glitches by creating virtual armorstands to display items on top of the workbenches, making them completely clientside. It is very lightweight and does not cause lag.

This is an **open source** project, and is licensed under the MIT license.

**Comment by KarlOfDuty** [comment]
That looks great! We will test it out when the current server issues are fixed.

**Comment by NigelFarage666** [comment]
Woah thats awesome idea! I love it!

**Comment by Pengun78** [comment]
people can mess up your crafting recipe and be annoying

**Comment by KarlOfDuty** [comment]
I'll give an update on this, we have decided to hold off on implementing this plugin as you have probably noticed. The server is currently incredibly laggy due to the giant amount of entities we have so we don't really want to add a plugin that would increase them even further. At some point in the future though when we have been able to get back to the level of performance we have in november.

**Comment by BananaPuncher714** [comment]
It adds virtual armorstands through packets, so it doesn't really "add" any entities. I can understand not wanting to risk any more lag though.
