### ISSUE TITLE
[Feature] Remove rule 4.1

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1613]
### Is your feature request related to a problem? Please describe.

This is just a game, so why can't you allow nations of any name?

### Describe the solution you'd like

I think rule 4.1 should be removed and we can name our nations anything we like.

**Comment by Fruitloopins** [comment]
💀

**Comment by Aylywyn** [comment]
Elimination 1) Runs counter to the stated spirit/purpose of the server, 2) Opens up gigantic can of worms/headache regarding moderation of appropriate names.  Probably more but those are the two HUGE, OBVIOUS wrong things.

**Comment by Fruitloopins** [comment]
4.1 has been removed...

and moved to 2.1
