### ISSUE TITLE
Add /ch leave discord

### ISSUE THREAD

**Issue by uwuoa** [EarthMC/Issue-Tracker#1616]
### Is your feature request related to a problem? Please describe.

It's nice that premium users can talk on discord, but it's annoying to me because I want to enjoy earthmc in peace and quiet.

### Describe the solution you'd like

Add /ch leave discord
Create a rule that prohibits speaking in languages other than English in discord chat

### Additional context

![image](https://user-images.githubusercontent.com/83058641/210598391-01be80cf-8d58-4812-a245-503ce0a5fc8c.png)

**Comment by Warriorrrr** [comment]
Looked at the discord plugin's events just now and this seems possible to do, I'll work on this soon.

**Comment by Proserrr** [comment]
Is this even needed anymore assuming the discord channels aren't coming back

**Comment by Warriorrrr** [comment]
yeah that's true, when they're back I'll make sure to implement this, but closing it for now.
