### ISSUE TITLE
[Bug] Negative taxes not possible

### ISSUE THREAD

**Issue by PancenNSR** [EarthMC/Issue-Tracker#1618]
### Server

Aurora

### Describe the bug

In the EarthMC docs, it says:

> A negative tax number for residents/plots will pay residents from the virtual town vault every 24 hours for just being in the town. ([link](https://earthmc.net/docs/town/#taxes))

However, when I try to do it in game, it doesn't work.

### To Reproduce

1. Be a town Mayor or Councillor
2. Type `/t set taxes -1` or `/t set plottax -1`

### Expected behavior

I expect the Towny plugin to set the town resident or plot taxes to -1, giving residents/plotowners money each day

### Screenshots

![image](https://user-images.githubusercontent.com/122344652/211485333-c48369f5-0a73-4ab8-87e1-3686dbf3b6c8.png)

### Additional context

The town currently has 29g and 9 residents, so it doesn't seem to be due to a lack of money or too many residents.

**Comment by Fruitloopins** [comment]
taxes don't work at all on earthmc right now afaik

**Comment by PancenNSR** [comment]
Even positive taxes?

**Comment by Warriorrrr** [comment]
Taxes are only collected by towny when the upkeep option is enabled, which is not the case on EarthMC.

**Comment by Aylywyn** [comment]
Would it not be possible to fix Upkeep at a hard 0 then enable it in order to make Taxes work?  Not that Taxes would likely be popular but...  It would let people experiment with them, especially the negative tax rate.

**Comment by PancenNSR** [comment]
I would very much like to see taxes be possible. Would we need to create a separate issue as a feature request, or does keeping it in this thread work?

**Comment by CorruptedGreed** [comment]
Taxes are not enabled on EMC
