### ISSUE TITLE
[Feature] Suggestion: Emerald Recipe

### ISSUE THREAD

**Issue by Aylywyn** [EarthMC/Issue-Tracker#1619]
### Is your feature request related to a problem? Please describe.

Without commenting on the matter, the idea of an Emerald Shortage has come up.  With "sources of emeralds already mined out!" and such.  There is noticable, fairly rapid increaes in the peices of Emeralds and resulting Mending increases.  IF this is undesirable, then another source of Emeralds is required.

### Describe the solution you'd like

A Custom Recipe would be a fast, easy, and tunable solution.   Once it was decided how tough they'd be to get, plus how rare, plus how renewable,  plus any other considerations, a suitable recipe could be chosen.

I am suggesting a Custom Recipe of:

Ghast Tear + Lapis + Gold Nugget  = 1 Emerald

In Minecraft terms, that is something crystal-looking plus a blue thing plus a yellow thing equals a green crystal.
In Game terms, you have an item that is somewhat rare and valuable on it's own, with risks in acquiring (no claims in the Nether plus you are in the Nether...).  Adding a renewable but also low-value thing.  Then adding a hard floor to the value of the resulting product.

I've seen Ghast Tears as low as 4/g, let's call Lapis free, and a hard floor of 1 Nugget.  That puts an Emerald at approximately 3 Ems per Gold.  This could be higher as Tears are not normally seen that cheaply and WILL drop as methods of acquiring Tears improve.  With a Nugget as a component prices are unable to drop below 9Ems/g and unlikely to see 9Ems/2g.

With no comment on necessity (and staring tensely at a large stash of Emeralds).

**Comment by asyi0** [comment]
It would be interesting to add emeralds to the gold crate obtained by vote, 
or add random Pillager Patrols spawn in wilderness that drop emeralds.

**Comment by ZeyaoZhou** [comment]
Funny business people make a play and cause some mass panic in a day, very interesting to see the reactions.

I don't see why emeralds now need an alternate recipe when you can still mine it. I highly doubt all of the supply would have been mined out, we are talking about earthmc. There is no reason to aid the emerald supply when the process for gaining emeralds is still the same, especially when emeralds are still obtainable naturally. This post is similar to saying we need an alternate recipe for quartz or gold as they supposedly have been "depleted" and we need easier access to them. We really do not.

**Comment by Aylywyn** [comment]
I'm going to update this quickly just to say, "I don't think any 'solution' is needed right now.  There's lots of Emeralds in the ground and people are sitting on 4.5 stacks of blocks...

I'm proposing this ahead of there maybe being a problem and in response to a Discord comment saying staff are already looking at proposals.

I don't like the Vote Crate idea.  It has the benefit/drawback of Devs being able to pick the value of an Emerald,  and being able/required to tweak "luck" to adjust things manually (instead of market and game got es doing the adjusting).  Assuming the VC replaces a chance of Gold with a chance at Ems.  You are simply amounting to giving people X Emeralds a day.  And sets the value equal to the average amount of gold in a crate.

**Comment by Colt44Magnum** [comment]
Adding Emeralds to the treasure.yml for Fishing could be a great way to alleviate this Issue. This could work as apart of #1491

**Comment by Fruitloopins** [comment]
emeralds were added to fishing
