### ISSUE TITLE
[World] Add cacti to deserts

### ISSUE THREAD

**Issue by Jacob8858** [EarthMC/Issue-Tracker#162]
**Describe the issue**
There are not any cacti on the server as far as I am aware.
**Coordinates**
Yes

**Screenshots**

<img width="403" alt="capture" src="https://user-images.githubusercontent.com/44347988/48877858-22a63380-edd3-11e8-8ecf-67f840cbebea.PNG">

**Comment by MSatrokrm** [comment]
There are cacti in the server.
There's just none in the desert.

Go ask global chat for cactus, or I could toss you a few.

**Comment by Jacob8858** [comment]
Whats your ign?

**Comment by BowShot118** [comment]
It exists

**Comment by PoppyK** [comment]
Cactus has been added to where it grows naturally in the world.  Western Canada desert, the Okanagan, western US deserts in Utah and CO, the Atacama and Patagonia Desert in S. America, parts of the African Deserts, and SriLanka.
