### ISSUE TITLE
[Mechanic] Run commands as many times as you want without being stopped for spamming.

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1620]
### Is your feature request related to a problem? Please describe.

It's very frustrating when you need to run a command repeatedly and get kicked for doing that.

### Describe the solution you'd like

Remove the command spam protection.

### Additional context

I don't get how spamming commands is going to affect anyone.

**Comment by Fruitloopins** [comment]
Command spam can cause different amounts of server lag depending on what the command does and commands like /w can be used to spam users very easily if the limit were to be removed

**Comment by PlaceReporter99** [comment]
I am using the /bottle command repeatedly. Would that need spam protection? If so, why?

**Comment by AndrewCheedle** [comment]
I think bottle command should be changed in a way that allows multiple bottles of the same xp to be collected at the same time 
For example : /bottle store 310 20 would give you 20 bottles of 310xp. This would effectively remove the need for players to type the command each time or spam it to get the bottles that they sell in shops. This would result in the command cooldown not being removed so server wont have any lag issues

**Comment by Warriorrrr** [comment]
The bottle plugin isn't open source so this can't be changed, just ask the people that buy experience to create a new shop for bottles with more xp.

**Comment by Aylywyn** [comment]
I get why you'd want that.  BUT...  Ah, I see Warriorrrr just commented it isn't possible anyways.

I'll double down then on what I was going to say, "just bake the additional time and effort into your selling price".  Add a nugget or two for the pain in the butt.

**Comment by Warriorrrr** [comment]
Closing this in favour of #1669 (if it's ever possible), there aren't really any other cases where not having spam protection would be helpful. The spam protection on commands is already pretty lenient (2 commands max in a 3 second interval), and to me it seems like the pros of having it outweigh the cons.
