### ISSUE TITLE
Change default town perms

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1624]
### Is your feature request related to a problem? Please describe.

New players have no idea that all town perms are on for residents by default causing them to lose all their items when they eventually recruit. There is no way for them to know about town perms or how they function and the commands to toggle them can be difficult to learn and to explain all the nuances and complexities of.

### Describe the solution you'd like

Set all default perm lines to ---- rather than r---, this will ensure mayors get at least a basic understanding of perm management as they must give ranks to trusted people or sell plots to citizens, no perm should be on by default.

### Additional context

It's easier for somebody with no knowledge of towny to build up the perms that they do want in their town rather than break down the ones they don't want and know nothing about especially when they may need to be doing this while they are actively being stolen from.

**Comment by FixTheAdmin** [comment]
I like it

**Comment by Fruitloopins** [comment]
now add it

**Comment by AndrewCheedle** [comment]
Thats what ive been saying

**Comment by Warriorrrr** [comment]
Done
