### ISSUE TITLE
Fix your website description

### ISSUE THREAD

**Issue by yogi701** [EarthMC/Issue-Tracker#1625]
### Is your feature request related to a problem? Please describe.

Website shows that you can join using every version, unfortunately it's not true 

### Describe the solution you'd like

Show supported versions like on wiki

### Additional context

![Zrzut ekranu z 2023-01-19 11-38-08](https://user-images.githubusercontent.com/80465029/213422855-23983343-5932-4635-8302-05578eebd09b.png)
![Zrzut ekranu z 2023-01-19 11-42-29](https://user-images.githubusercontent.com/80465029/213422884-a2597ef3-6e00-44a8-be99-f7d893374168.png)

**Comment by Warriorrrr** [comment]
Done, thanks
