### ISSUE TITLE
[Feature] Custom crafting recipe for shulker boxes

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1626]
### Is your feature request related to a problem? Please describe.

Sometimes, you have to haul lots of stuff from one place to another, possibly more than you can carry. This is very frustrating, especially when you have to transport them long distances.

### Describe the solution you'd like

Add a custom crafting recipe for shulker boxes, since you cannot access the end in EarthMC.

**Comment by Fruitloopins** [comment]
shulker boxes aren't in the server intentionally since they can make duping (when it does happen) 27x more efficient

**Comment by PlaceReporter99** [comment]
@Fruitloopins aren't all of the known dupe glitches patched?

**Comment by Aylywyn** [comment]
Keyword "known".  I've also heard that, in addition to duping problems, part of the logic is to make players form multiple stashes in many places; make multiple trips to transport items; and generally increase the effort and interaction in moving things around.  It's a purposeful "atmospheric" decision as well as technical.

**Comment by CorruptedGreed** [comment]
Shulkers are not planned to be added to EMC due to potential issues tracking with CoreProtect, and other concerns
