### ISSUE TITLE
[Feature] Enable Jailing of other people

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1629]
### Is your feature request related to a problem? Please describe.

Outlawing someone is pretty much useless.

### Describe the solution you'd like

Allow people to jail other people.

### Additional context

Server: Aurora

**Comment by Aylywyn** [comment]
Do you have any idea how annoying that would be?  That said, I think dome good proposals for expanding/clarifying what Outlaw does might be an idea.

**Comment by AndrewCheedle** [comment]
Jails have been disabled intentionally so you would need to specify how to bring them back without people being trapped for eternity in jails. Although i don't think there are any plans to bring them back considering outlawing is just used as a list of players you don't like and probably won't be useful soon.

**Comment by Murder-Hobo** [comment]
maybe it would just be for a set time and then there is a cool down?

**Comment by Haptror** [comment]
maybe a jail could be where you teleport when u try to visit it

**Comment by CorruptedGreed** [comment]
No, players have abused this in the past. Any implementation of jails would need to come with an actual mechanic aside from just trapping players for no reason/indefinitely.
