### ISSUE TITLE
There are no more turtles

### ISSUE THREAD

**Issue by Zyphlox** [EarthMC/Issue-Tracker#163]
According to Papermikin, him and Magenent killed all the turtles in the entire map and they have the only ones that can breed with eggs.
Thus, they are having a monopoly and only selling turtles. As further inspection, I found out that they apparently will never sell the eggs to anyone and only sell turtles, thus making it impossible to breed any turtles.
I am wondering if we can have more turtles spawned in so other players can have a chance.

It truly is cruel what Papermikin and Magenent did. All I want are some nice turtles for a nice town. That is all. :(

**Comment by Coffeetom** [comment]
Lololol
I'm pretty sure they are trolling, plus more turtles will spawn, so don't worry

**Comment by MSatrokrm** [comment]
Lies, and deception!

Exhibit A : 

![inked2018-11-22_13 32 42_li](https://user-images.githubusercontent.com/23727003/48925885-fa6b1300-ee6c-11e8-8b97-54a52a695301.jpg)

All you want to do is ruin the turtle market!

This is the real world! Monopolies rule the economy!

Early birds get the worms, we came to gather up all the turtles first. And, we're still selling turtles! Which totally makes your claim go kapoof!! 

"There are no more turtles" my left nut.

**Comment by FurdenFuhrer** [comment]
How much are you selling Turtles for?

**Comment by Narwhal2000** [comment]
Also what happened to monopolies in real life, they got broken up

**Comment by KarlOfDuty** [comment]
Turtles will respawn in beach biomes as far as I know. If anyone wants to complain about mob spawn rates you may open a new ticket to do so.
