### ISSUE TITLE
[Bug] Aurora Dynmap is not working

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1630]
### Server

Aurora

### Describe the bug

The Aurora Dynmap does not update anything and says `Could not update map: Not Found`

### To Reproduce

Open Aurora Dynmap and witness the lack of anything happening

### Expected behavior

Aurora Dynmap should do things

### Screenshots

![image](https://user-images.githubusercontent.com/49851457/215337862-bbefc5e0-0513-4d31-8187-3d38eddfef51.png)

**Comment by Warriorrrr** [comment]
done
