### ISSUE TITLE
[Feature] Open discord to in-game chat for all users.

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1631]
### Is your feature request related to a problem? Please describe.

You sometimes need to chat to people in game without joining.

### Describe the solution you'd like

Allow all users that have linked their discord account to their minecraft account to chat in #terra-aurora and #terra-nova.

### Additional context

This would be especially useful when you're on holiday.

**Comment by Haptror** [comment]
> Can you even imagine the chaos? If you didn't limit it to people who had a monetary investment in the game to appeal to/threaten in order to moderate behaviour. Not to mention you'd be lessening the already dubious value of Premium by some tiny amount, reducing income.

this feature actually did exist in 2019 or before

**Comment by CorruptedGreed** [comment]
This has been enabled for Premium players and Nitro Boosters.
