### ISSUE TITLE
[Bug] Nova Dynmap isn't working

### ISSUE THREAD

**Issue by no-seriously** [EarthMC/Issue-Tracker#1632]
### Server

Nova

### Describe the bug

The nova dynmap has been down for days.

### To Reproduce

earthmc.net/map/nova

### Expected behavior

any idea when it'll be back online?

**Comment by Warriorrrr** [comment]
Firewall issue, will be fixed soon.

**Comment by no-seriously** [comment]
> Firewall issue, will be fixed soon.

do you have an ETA of when it'll be fixed? I know you said Fix has to do it.

**Comment by Warriorrrr** [comment]
Fixed now, changed storage medium to mysql so map is currently re-rendering.
