### ISSUE TITLE
[Bug] NPC disappeared...

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1636]
### Server

Hub

### Describe the bug

All of the NPCs have disappeared.

### To Reproduce

1. Join the hub
2. Go to where the NPC would normally be

### Expected behavior

The NPC can be seen.

### Screenshots

![2023-02-05_11 31 00](https://user-images.githubusercontent.com/106759534/216823909-66871586-400b-4f69-a5aa-abf12cf2091e.png)
F3 Debug menu is open

**Comment by Warriorrrr** [comment]
The npc plugin was temporarily removed because it was creating too much lag with tons of players in the hub.
