### ISSUE TITLE
War Negotations

### ISSUE THREAD

**Issue by Murder-Hobo** [EarthMC/Issue-Tracker#1638]
### Is your feature request related to a problem? Please describe.

Lack of war or counseling system.

### Describe the solution you'd like

For war, I believe it would be a good idea to have a system where if nations/towns want to battle it out, they can set war goals and win conditions with each other. That way neither nation nor town will unwillingly lose their town, land, or items, while still having something to truly sacrifice or fight for other than RP and also allowing those who don't want war the ability to deny the war offer.

### Additional context

This would be good to allow nations to test their might while allowing others to continue to grow!

**Comment by Jahner12345** [comment]
Agreed!

**Comment by RAWRyoutube** [comment]
There’s a pretty good reason why this hasn’t happened yet.

**Comment by Aylywyn** [comment]
I have to comment since I can't downvote.  See any number of Forum and likely GitHub (1208 looks open?) discussions on how bad of an idea this is.
