### ISSUE TITLE
[Bug] Periods being removed in website links

### ISSUE THREAD

**Issue by Milgorn123** [EarthMC/Issue-Tracker#1639]
### Server

Aurora

### Describe the bug

Heyo, I'm a recruiter for my nation, and we use a recruitment discord to help aspiring residents find a town and join it in our nation.  I noticed that when I send the discord invite link in a PM, the periods just disappear. This means the link is not a clickable message. In the chat box before I've sent it, they are definitely there, but it disappears. I've heard that this is a known issue, but could it be fixed? Thank you.

### To Reproduce

If you send a PM with any link (and I mean any link), it is automatically removes the period. This also happens if you have two sentence, but you don't put spaces after the periods, so I'm guessing the server is removing the period when it appears with no space afterwards. 

### Expected behavior

Usually, when I send this same message in the public chats the periods appear like normal and can be clicked. 

### Screenshots

![2023-02-08_22 48 55](https://user-images.githubusercontent.com/125206550/218323244-be7996a7-3763-402b-8e14-602c2ea2edc1.png)

If you look at the PM I sent someone, the discord link has the periods missing for some reason.

**Comment by Warriorrrr** [comment]
Done, dots in /msg will no longer be removed and urls will open in web browser as expected.
