### ISSUE TITLE
[Feature] #hub-chat on discord

### ISSUE THREAD

**Issue by PlaceReporter99** [EarthMC/Issue-Tracker#1642]
### Is your feature request related to a problem? Please describe.

Even premium and nitro boosters cannot chat to the hub chat from discord.

### Describe the solution you'd like

Add a channel for premium and nitro boosters to chat into the hub chat.

**Comment by Warriorrrr** [comment]
I don't see the benefit of adding a brand new discord channel just for hub chat, so I'm going to say no to this one.
