### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DaGoodPhrog** [EarthMC/Issue-Tracker#1645]
### Server

Nova

### Describe the bug

Hi, the problem or bug in Minecraft on the server is that I can't use any command or tp anywhere. when I try to use /RTP, it says I can't use the command, or any other command it says the same. while with /t spawn or /n spawn, it always says the 2 same messages for any place that's not Norway, which are:" public spawn travel to other (nations-towns) is forbidden" and "this nation is not affiliated with you" which I dont think all of the towns and nations are not affiliated with Norway and it's getting annoying since I'm trapped at my /t spawn. And I don't think its not a bug because all the people I know from Norway can tp to any nation and it does not say the message

### To Reproduce

type /n spawn /rtp and /t spawn 

### Expected behavior

that I can use /rtp any of the other normal commands and tp to other nations or towns.

### Screenshots

https://user-images.githubusercontent.com/125842071/219992891-166b6450-379e-425e-86ff-e331b4849576.mov

### Additional context

I uploaded a video on 2.3x bc it took to long and it was more than 10mb, but on the chat u can see I put the commands and they don't work, and they don't work just on the towns or nations I showed you but on every single one of them.

**Comment by RAWRyoutube** [comment]
/rtp is not a usable command for anyone.
When you use /t spawn, you can only use it to teleport to your town.
You should be able to use /n spawn (not adding anything else in) to teleport to Norway’s capital. If that doesn’t work, check /t (and see if it says you’re part of a town. If you are, the pop-up from /t will say if it’s part of any nation.)

**Comment by Aylywyn** [comment]
To follow up the above.  These are the Docs, https://earthmc.net/docs/how-to-teleport.  Specifically the section How To Teleport.  The other important thing is you can only /n spawn if the Nation is ALLIED to yours.

**Comment by Warriorrrr** [comment]
Closing, see above comments.

**Comment by DaGoodPhrog** [comment]
Oh btw i think it is a bug becouse on /n spawn I just say that and any nation, and I can’t do any of the nations just Norway. the /rtp was just that I confused with another server and the town Ty
