### ISSUE TITLE
[Feature] Bring Michelle Obama back

### ISSUE THREAD

**Issue by explodingmelons** [EarthMC/Issue-Tracker#1646]
### Is your feature request related to a problem? Please describe.

We don't have Michelle Obama any more. EMC was a better place when Michelle Obama periodically messaged everyone to vote.
New players haven't experienced the joy Michelle Obama brought to EMC.

### Describe the solution you'd like

Re-implement Michelle Obama. Nuff said.

### Additional context

I haven't done a request in eons so I've no idea if I'm doing this right.

**Comment by Colt44Magnum** [comment]
Yes

**Comment by PlaceReporter99** [comment]
lol a dev said yes

**Comment by PlaceReporter99** [comment]
why did you add michelle obama back?
