### ISSUE TITLE
[Bug] Combat Rubberbanding

### ISSUE THREAD

**Issue by ItsEntDev** [EarthMC/Issue-Tracker#1648]
### Server

Aurora

### Describe the bug

If you go into combat with an enemy group and then step into a safe zone or get hit into a safe zone, the server will start freezing you in place/rubber-banding you so it becomes impossible to move. This is an extremely unfair advantage to the attackers.

### To Reproduce

The steps are listed above in the description of the bug.

### Expected behavior

To possibly take you out of combat, or tell you to leave the no-pvp zone?

### Additional context

This happened to a few people during the Koyukuk (my nation) and Arctic war. I presume it's happened to other people.

**Comment by Colt44Magnum** [comment]
That is the intended action occurring. If you are in PVP you are not allowed to run into claims and hide while in PVP. The server determines when your PVP timer is up.

**Comment by ItsEntDev** [comment]
> That is the intended action occurring. If you are in PVP you are not allowed to run into claims and hide while in PVP. The server determines when your PVP timer is up.
> 
> Maybe making it throw you back a couple blocks is better than being stuck though, and sometimes its hard to tell where a pvp chunk and a non pvp chunk begins

Maybe, but in my experience it stops you moving altogether. It may just be in one direction and I am remembering incorrectly, but the person attacking you ends up hitting you into the chunk making it so you can't fight back properly.

**Comment by Warriorrrr** [comment]
The applying backwards velocity was the old behaviour, but after an update to the plugin it suddently broke, so it had to be changed to the current one. It should still be possible to escape if you turn around but I admit it's not ideal, it'll be changed back as soon as it's fixed.

**Comment by Haptror** [comment]
> The applying backwards velocity was the old behaviour, but after an update to the plugin it suddently broke, so it had to be changed to the current one. It should still be possible to escape if you turn around but I admit it's not ideal, it'll be changed back as soon as it's fixed.

fixed yet

**Comment by CorruptedGreed** [comment]
No longer an issue
