### ISSUE TITLE
Please add "tranny" and "trannies" to the disallowed words

### ISSUE THREAD

**Issue by Barbay1** [EarthMC/Issue-Tracker#1651]
### Is your feature request related to a problem? Please describe.

I saw increased use of the words "tranny" and "trannies" to harass others, and it doesn't seem to be filtered.

### Describe the solution you'd like

Add "tranny" and "trannies" to the filter

**Comment by Haptror** [comment]
well this is a terrible idea ngl

**Comment by RAWRyoutube** [comment]
I’ll propose this test:
1. Does the word have a vulgar meaning?
2. Is the word used at least mostly to harass other people in the server?
3. Does using the word usually eventually result in moderation action in the server?
If it passes all three, there’s no good reason to oppose blocking it. If it doesn’t pass one, then there’s a good reason to not block the word.

If we applied it here, it would make sense to block the word if people were already being warned or told off by mods for using it, considering the word has a vulgar meaning and is being used to harass other people.

**Comment by Warriorrrr** [comment]
The former was already part of the filter, I've added the second one now.

**Comment by Haptror** [comment]
> I’ll propose this test:
> 
> 1. Does the word have a vulgar meaning?
> 2. Is the word used at least mostly to harass other people in the server?
> 3. Does using the word usually eventually result in moderation action in the server?
>    If it passes all three, there’s no good reason to oppose blocking it. If it doesn’t pass one, then there’s a good reason to not block the word.
> 
> If we applied it here, it would make sense to block the word if people were already being warned or told off by mods for using it, considering the word has a vulgar meaning and is being used to harass other people.

thing is why im confused, it has real meanings and i dont really get blocking the word outright as opposed to using some regex to filter the word out in bad meanings instead

**Comment by RAWRyoutube** [comment]
Will point out the issue is now closed.
Question number one looks for any vulgar meaning in a word, even if there’s other usage of the word that isn’t vulgar. Obviously, the word in question has a vulgar meaning.
Even then, the three questions I proposed aren’t official and the word was blocked because the former word that was mentioned was already blocked.

**Comment by Haptror** [comment]
you're right, but it's truly unfortunate how everyone has to be babied

**Comment by RAWRyoutube** [comment]
I wouldn’t call this babying.
