### ISSUE TITLE
[Bug] Able to break any quickshop sign.

### ISSUE THREAD

**Issue by Magg27** [EarthMC/Issue-Tracker#1654]
### Server

Aurora

### Describe the bug

If you sneak and break a Quickshop chest, the sign for that Quickshop will be removed, but the chest itself stays.

### To Reproduce

Hold sneak and break a Quickshop chest in a chunk you have no permissions in.

### Expected behavior

The Quickshop sign should remain and not get removed.

### Screenshots

![Screenshot_20230322_210434](https://user-images.githubusercontent.com/84076753/226869412-721ba144-bc4e-43f2-8a59-fb88fd6e11fb.png)

**Comment by Warriorrrr** [comment]
Fixed, this was caused by quickshop removing the shop before towny had any say in preventing the block being broken.
