### ISSUE TITLE
Chat parties got deleted

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1655]
### Server

Aurora

### Describe the bug

Some players have complained that they have been kicked from their chat parties and their parties got deleted.

### To Reproduce

Owners of that parties, premium players, have complained that they have been kicked from their chat parties and their parties got deleted.

### Expected behavior

Chat parties not being deleted.

### Screenshots

![from#quick-questions](https://user-images.githubusercontent.com/128364522/226881955-5140f98e-82c6-4c00-9222-797540545815.png)

**Comment by Warriorrrr** [comment]
I've rolled back parties to 2023-03-21 14:41:31, all old parties are back now.
