### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Crimsonal0wl** [EarthMC/Issue-Tracker#1657]
### Server

Nova

### Describe the bug

Hello, I need some help with the server.
For some reason when I try and join it says "VPN connections are not allowed on EarthMC" when I've never had a VPN, I've tried changing settings and everything yet nothing is working, please help.

### To Reproduce

Tried joining server

### Expected behavior

Didn't work, for some reason.

### Additional context

I have tried to see if I have a VPN, I do not.

**Comment by Warriorrrr** [comment]
The issue tracker is not the correct place for support, the support discord is over at https://discord.gg/EZBYmpp.
