### ISSUE TITLE
[Bug] Gold Crates disappearing after right click.

### ISSUE THREAD

**Issue by Magg27** [EarthMC/Issue-Tracker#1660]
### Server

Aurora

### Describe the bug

When you are in the process of opening a gold crate and it is cycling through the different rewards, if you open another gold crate, that crate will just disappear.

### To Reproduce

Open a gold crate.
While the gold crate is cycling through the rewards, open another gold crate.

### Expected behavior

The second gold crate should not simply vanish from the player's inventory.

**Comment by Haptror** [comment]
then just dont open a gold crate while opening one, simple and easy

**Comment by Magg27** [comment]
it shouldn't happen

**Comment by Haptror** [comment]
well just dont open one while one is being opened. thats a simple question and a simple answer

**Comment by Warriorrrr** [comment]
Can reproduce by spamming escape and right click, but not worth solving since our current crate plugin is closed source. This is not an issue with our upcoming new crate plugin.
