### ISSUE TITLE
No crates after vote

### ISSUE THREAD

**Issue by Blue939** [EarthMC/Issue-Tracker#1665]
### Server

Aurora

### Describe the bug

After I voted on both the webpages for voting and when I logged on the EMC Server I didnt get those crates Ive tried /cr claim but it said "There isnt any rewards you can claim"

### To Reproduce

Vote on the server ,log on...

### Expected behavior

...dont get any crates

**Comment by Proserrr** [comment]
Sometimes the websites can be weird, but theres nothing really we can do. Theres no way to verify vote crates so staff never refund them

**Comment by CorruptedGreed** [comment]
You should be online already while you are using /vote in order to receive the crates.
