### ISSUE TITLE
[Bug] Bone blocks sometimes show as stone

### ISSUE THREAD

**Issue by Thanamossss** [EarthMC/Issue-Tracker#1666]
### Server

Aurora

### Describe the bug

When unloaded chunks, bone blocks turns into stone texture, i'll have to manually reclick on it to make it load properly. I've called a friend to see if it was only for me but it's also for him and he have manually to reclick on every block

### To Reproduce

1. You put a bone block
2. Unload the chunk by moving elsewhere
3. The bone block texture is replaced with stone

### Expected behavior

i don't really know but that's annoying

### Screenshots

![2023-04-09_15 44 11](https://user-images.githubusercontent.com/122749911/230776416-b78cf52c-9b4b-48ba-8a61-6ba48ac50c1b.png)
![2023-04-09_15 44 13](https://user-images.githubusercontent.com/122749911/230776429-32507385-d2b6-4cc6-9969-b1d632bd60e2.png)
![2023-04-09_15 44 18](https://user-images.githubusercontent.com/122749911/230776441-11f9ff7a-8e29-4a5f-89f6-067d5210d782.png)

**Comment by Fruitloopins** [comment]
i've noticed this but it fixes itself shortly after i look at it, i never imagined it could be an earthmc issue though

**Comment by Warriorrrr** [comment]
Bone blocks are hidden by our anti xray, there's been one case as far as I know of it breaking but when I logged on just now it did not seem to be broken.

**Comment by Aylywyn** [comment]
I quite possibly that case...  It happens when the chunk loads under lag and rarely.  If it does get stuck as Stone, which has NOT happened except for the period just after introduction, it self-resolves after a day or two, ikely connected to some sort of update cycle.

It was the Anti-X-Ray specifically targetting Fossils.
