### ISSUE TITLE
Addition of a Polls channel on the Earthmc Discord Server. 

### ISSUE THREAD

**Issue by MonarchTai** [EarthMC/Issue-Tracker#1667]
### Is your feature request related to a problem? Please describe.

Recently, across Earthmc, there has been conflict on a feature that it seems more wouldn't like to be added then would. This is the overclaim feature. There is no clear understanding on who supports it and who doesn't without the community stepping in and try creating polls. 

This is why I suggest the addition of a polls channel. This would be a easy and efficient way to hear opinions fast. Not everyone speaks English, can write long SA's and write them. While polls are short and simple to translate and them a click of a button to submit their opinion. 

Most towny servers use polls to show what their community would like. Maybe Emc could trial one to hear their communities opinions? Not every EMC player uses Github. I never used to, and many still don't. 

A poll channel seems like a beneficial way of negotiating between community and moderation team without sparking detail. But just finding out information in numbers. 

### Describe the solution you'd like

The solution I would like is a polls channel to be created. Moderators who are trusted can post polls here for the community to vote on. The votes will be through reactions on the messages. Here is an example poll formst that I use.

---

" Should Earthmc Implement the Overclaim feature to Earthmc Aurora and Nova? " 
"*(Brief information played here on what this would mean for the server depending on what the community votes)*" 

"✅️  = Yes"
"❌️ = No"

---

If not a channel on the discord, atleast create a PINNED forum where only trusted moderators can create polls for people to react to. People wouldn't be able to type in these.

**Comment by CorruptedGreed** [comment]
Fix has said he is not interested in cluttering the Discord further. We will not be adding a channel for this sole purpose given that forums can be used.
