### ISSUE TITLE
[Feature] Add the ability to get multiple XP storage bottles at a time with one command

### ISSUE THREAD

**Issue by deafkite42** [EarthMC/Issue-Tracker#1669]
### Is your feature request related to a problem? Please describe.

It's very annoying to enter /bottle store [amount] over and over again when trying to bottle xp to sell, with the command cooldown making it very slow, and eventually being kicked for spam. 

### Describe the solution you'd like

Add the ability to specify the amount of bottles you want, with /bottle store [xp amount] [quantity].

**Comment by Warriorrrr** [comment]
This is already suggested to the plugin we use here: https://github.com/Zrips/BottledExp/issues/19

Unfortunately it seems that the source for it doesn't seem doesn't get actively updated, so creating a pull request ourselves isn't really viable.

**Comment by PlaceReporter99** [comment]
> This is already suggested to the plugin we use here: [Zrips/BottledExp#19](https://github.com/Zrips/BottledExp/issues/19)
> 
> Unfortunately it seems that the source for it doesn't seem doesn't get actively updated, so creating a pull request ourselves isn't really viable.

*Hacks in to repo owner's account*

**Comment by Fruitloopins** [comment]
ok

**Comment by Fruitloopins** [comment]
i've created this https://github.com/Fruitloopins/XPManager that adds this feature and some other nice stuff, it should be added once we debug it properly and stuff, if you have any other feature ideas let me know before we add it

**Comment by CorruptedGreed** [comment]
Added in latest changelog
