### ISSUE TITLE
[Bug] Wrong McMMO Power Level for offline players through /mcmmo:inspect

### ISSUE THREAD

**Issue by BreachDGates** [EarthMC/Issue-Tracker#1670]
### Server

Aurora

### Describe the bug

McMMO version 2.1.120-snapshot bug

If you try to type **/mcmmo:inspect [offlineplayer]** it will show you their power level, _but_ it also counts the child skills **Smelting** and **Salvage** in the sum.
When you try to type **/mcmmo:inspect [onlineplayer]** it works fine.

I don't know how old this bug is since I've recently returned, but I think in Nova the command worked fine.
I don't know if this bug is related to McMMO in general or only in EMC, I think the former.

On my test server with McMMO version 2.1.120-snapshot (same as EMC) the same bug happens, Smelting and Salvage are counted too if you check an offline player's skills with /mcmmo:inspect. 

### To Reproduce

1. /mcmmo:inspect onlineplayer --> it works normally
2. wait for the player to disconnect, or inspect any offline player's levels
3. /mcmmo:inspect offlineplayer --> it shows the total power level with Smelting and Salvage

### Expected behavior

Either if you're online or offline it should show the same power level

### Screenshots

![Screenshot_423](https://user-images.githubusercontent.com/61973209/233764090-76a86682-c8ff-4d39-92f0-8c4643bfca86.png)
![Screenshot_424](https://user-images.githubusercontent.com/61973209/233764091-95020493-7277-4950-a75f-3e95bb02803d.png)
![Screenshot_425](https://user-images.githubusercontent.com/61973209/233764093-875149ec-d081-4207-816a-349384b32ca5.png)
![Screenshot_426](https://user-images.githubusercontent.com/61973209/233764094-ed689a5e-23a4-4d97-8d4e-05243cc9a312.png)
![Screenshot_427](https://user-images.githubusercontent.com/61973209/233764095-b0c6a0b2-01e9-45ac-b4fb-11740870e2a0.png)
first 3 screenshots: checking an online player's power level
4th and 5th screenshot: checking an offline player's power level

**Comment by Warriorrrr** [comment]
Done, mcMMO update will be applied automatically after the next server restart.
