### ISSUE TITLE
[Bug] /t spawn ignores "[public]" status.

### ISSUE THREAD

**Issue by Magg27** [EarthMC/Issue-Tracker#1671]
### Server

Aurora

### Describe the bug

When typing `/t spawn` to a town that is in your nation, you get teleported no matter what the `[public]` status is set to.

### To Reproduce

self explanatory 

### Expected behavior

When typing `/t spawn` to a town that is in your nation, you get teleported only if the `[public]` status is togged on.

**Comment by keijodputt** [comment]
This should be the default behavior. Towns may not allow public spawn from other towns from within a nation.

Workaround: cage around spawn with perms to be open only by town residents.

**Comment by Magg27** [comment]
too logical

**Comment by CorruptedGreed** [comment]
This is currently disabled due to a conflict in Towny config with our public upkeep feature, once it comes back we can investigate
