### ISSUE TITLE
All of the 1,400 Gold in My Town Bank Gone [Bug]

### ISSUE THREAD

**Issue by AGR280** [EarthMC/Issue-Tracker#1672]
### Server

Aurora

### Describe the bug

I am the player AGR280. I own a town in the nation California called "San Jose". I had played the Terra Auroura world a TON during its early days, but my activity has died down significantly. Last time that I was on the server, which was two weeks ago, my bank balance was exactly 1,400 gold. Today when I logged on I checked my bank and I had NO gold in my bank. Before you say that someone insided my town and stole all the gold, I have never set my town to public. This has also reset my town board, which I believed I had put a message in before, but now it is the default message. If someone could roll back the information of my town or at least give me my 1,400 gold (which you could find evidence that I had in backups for the world), then it would be appreciated.

### To Reproduce

N/A

### Expected behavior

The expected behavior would be that I still have all of my gold

### Screenshots

<img width="547" alt="Screenshot 2023-04-29 at 11 17 45 AM" src="https://user-images.githubusercontent.com/132162266/235318168-84738f41-a7b8-4a5d-adee-cfc7ffeda245.png">
(When I last logged on there was 1,400 Gold)

### Additional context

I had not logged on for 2 weeks, and had been very inactive since the end of summer 2022.

**Comment by Warriorrrr** [comment]
The issue tracker is not a place for support, please create a ticket in the support discord and ping me for further support.
