### ISSUE TITLE
[Bug] Ally requests feature is broken

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1673]
### Server

Aurora

### Describe the bug

I have recieved an ally request and I tried to accept it, but it seems not working.

### To Reproduce

1. Do `/n ally accept [name]`
2.  No message is displayed and can't TP to the nation.

### Expected behavior

It is possible to accept aly request with  `/n ally accept [name]`

### Screenshots

https://www.youtube.com/watch?v=81t8qR1smwM

### Additional context

Also, it is not possible to cancel the request I sent with `/n ally add -[name]` , and not possible to deny it with `/n ally deny [name]`.

Whole of ally request feature seems to be broken.
Now, it seems that the only way to accept an ally is to click on the message of the request that was sent to me when I was online..

**Comment by keijodputt** [comment]
@asyi0 what's your nation, and what's the nation you want to accept as ally? Maybe I can check logs to see what's going on and, eventually force-add your ally to the nation, if the logs show nothing to the contrary.

**Comment by CorruptedGreed** [comment]
Should be working, open another issue if this persists
