### ISSUE TITLE
[Mechanic] Adding a custom recipe

### ISSUE THREAD

**Issue by HaydenDev3** [EarthMC/Issue-Tracker#1675]
### Is your feature request related to a problem? Please describe.

I would/and others would like a custom recipe for crafting shulker boxes, by implementing a custom recipe for crafting shulker boxes, players would have an alternative and accessible method of acquiring these valuable storage containers. This addition would allow for greater convenience, flexibility, and customization in organizing and managing personal inventories, chests, and storage systems.

### Describe the solution you'd like

Overall, if this mechanic is implemented, like I mentioned previously, players would have an alternative and accessible method of acquiring these valuable storage containers. This addition would allow for greater convenience, flexibility, and customization in organizing and managing personal inventories, chests, and storage systems.

It could possibly be crafted by placing end stone all around the crafting menu but leave out the middle and place a regular chest there, and maybe Premium players could have a “large shulker box”. 

### Additional context

The proposed recipe involves utilizing End stone and a chest, similar to the crafting process for an enderchest. This intuitive approach not only maintains consistency within the game mechanics but also provides an accessible alternative for obtaining shulker boxes.

Your sincerely, Hayden.

**Comment by Aylywyn** [comment]
#1626 and various Discord Forum threads discuss this topic and why it will not be implemented.

Besides, a better recipe is Turtle Helmet + 8 Chorus Flowers = 1Shulker Shell.

**Comment by HaydenDev3** [comment]
Because of duping, indeed, and Fruitloopins disagreed to the idea as I saw in that thread.
