### ISSUE TITLE
[Bug] /bottle get 64 does not give any bottles

### ISSUE THREAD

**Issue by AForAshton** [EarthMC/Issue-Tracker#1676]
### Server

Aurora

### Describe the bug

When typing '/bottle get 64', the levels are taken away but the bottles are not given.

### To Reproduce

?

### Expected behavior

64 XP bottles to be given, whilst having the levels taken away.

**Comment by Warriorrrr** [comment]
Seems like this is only an issue for 64 bottles, when typing /bottle get 63 or 65 everything works fine. Definitely an issue with the new bottledexp update.
