### ISSUE TITLE
Plot color names[Bug]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1678]
### Server

Aurora

### Describe the bug

The colors of the names of the plots have been removed 

### To Reproduce

Instead of the name of the plot in color it appears now the hex color code and the plot name in the default green.

### Expected behavior

If you write an hex color code the plot name should be show with the color of the hex color code as before the update.

### Screenshots

![2023-05-29_14 47 56](https://github.com/EarthMC/Issue-Tracker/assets/128364522/8e771949-3d98-41de-8222-17a9452f8de8)
![2023-05-29_14 48 02](https://github.com/EarthMC/Issue-Tracker/assets/128364522/d58dc327-7cb4-42ad-a7ce-78b977f65307)

**Comment by Warriorrrr** [comment]
That format was removed since it was breaking gradient tags, use `<#hex>`
