### ISSUE TITLE
Add toggle to allow hoppers to suck items from shop chests

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1679]
### Is your feature request related to a problem? Please describe.

The hopper no longer sucks items from the shop chest is a good update for the purpose of preventing scam and stealing .
However, there are problems in some redstone systems that combine shop chests and hoppers.
For example, I was buying potions at shop chest with hopper to avoid #1562. 
This mechanism is the shop will be inaccessible once the potions were in the chest, and be accessible after all potions are sucked by a hopper. However, this system was broken after the 1.19.4 update.

Even if shop chest are using as an item counter, it is still inconvenient.

### Describe the solution you'd like

Add commands like `/qs toggle hopper on` to allow the hopper to suck in items from the shop chest

### Additional context

capture of potion buying  system
https://github.com/EarthMC/Issue-Tracker/assets/92248609/575fdb05-afef-4ce8-a1e8-5d86971c0847

**Comment by Warriorrrr** [comment]
I'll address this soon by allowing hoppers to push/pull items into/from shop chests, placing a hopper next to a shop chest will still be disabled so that stealing isn't possible. The push/pull protection will still apply to minecart hoppers, since those can be pushed into claims

**Comment by Warriorrrr** [comment]
This should be done now
