### ISSUE TITLE
[Bug] Horse breeding

### ISSUE THREAD

**Issue by TwinIceBear** [EarthMC/Issue-Tracker#168]
I was recently trying to breed 2 horses, one MCMMO horse, and one natural horse. When I tried to breed them, the MCMMO horse went into the breeding mode, but when I tried to put the natural horse into breeding mode the golden carrots just disappear.

**Comment by KarlOfDuty** [comment]
Is this still an issue?

**Comment by shirazmatas** [comment]
Seems to be working now.
