### ISSUE TITLE
scam killed

### ISSUE THREAD

**Issue by SkythrillsMC** [EarthMC/Issue-Tracker#1680]
I was killed by the player named Linkuzz after i joined his town , he put lava on me after he kicked me out of the town

**Comment by jkmartindale** [comment]
💀

**Comment by GalaxyGaming2OOO** [comment]
Not Really a bug considering you could do this since the nova days and i doubt its fixable unless they add some sort of recent town join protection

**Comment by AGR280** [comment]
I feel your loss, but this isn't really a bug. If you feel they broke the rules then you should make a ticket on the Support Discord.
