### ISSUE TITLE
Players Able To Show Invalid tools in shop chests [Bug]

### ISSUE THREAD

**Issue by GalaxyGaming2OOO** [EarthMC/Issue-Tracker#1681]
### Server

Aurora

### Describe the bug

Basically people can sell mcmmo items in the quickshop chests
and it will show ex. for a pickaxe efficiency 10(X)

Even worse you can make these in stock by creating a buy shop with one of them and then selling it
once a player buys it they have the old version of the pickaxe
this can be used for scamming and such
since it previews it and other stuff

### To Reproduce

Method One: Unbuyable Invalid Tool
1. Use the tools special if it changes enchantments
2. left click on a chest and sell it for any price
3. check the quickshop

Method Two; Buyable Scam Tool
1. Use the tools special if it changes enchantments
2. left click on a chest and sell it for any price
3. Change shop type to buying
4. Use the tools special again
5. sell the tool
6. change it back to selling

### Expected behavior

Players May not sell items that have invalid enchantments / Unable to sell while using a MCmmo ability

### Screenshots

![2023-06-01_16 33 26](https://github.com/EarthMC/Issue-Tracker/assets/110449790/d30adb4c-e0fe-4479-82ed-448eaf2fd64c)

### Additional context

if you make it so you are Unable to sell while using a MCmmo ability
make sure you also make sure you cant do /qs sell.

Also The shop in the screenshot has been removed by me since i don't want anyone to get confused.

**Comment by GalaxyGaming2OOO** [comment]
This may be able to be fixed with a item blacklist in the quickshop plugin if it has that

**Comment by CorruptedGreed** [comment]
Should be resolved from eventually migrating to new fork of the shop plugin (Quickshop-Reremake -> QuickShop-Hikari)
