### ISSUE TITLE
[Bug] Combat Tag not Working

### ISSUE THREAD

**Issue by mudk2p** [EarthMC/Issue-Tracker#1682]
### Server

Aurora

### Describe the bug

When hitting someone, they can immediately go back into non-pvp town claims.

### To Reproduce

Hit someone in a pvp enabled area and walk back into a safe area.

### Expected behavior

You should be getting blocked from going into the safe area because you are in combat, but instead that doesn't happen. 

### Additional context

This started today, I was pvping yesterday and it was working as intended.

**Comment by CorruptedGreed** [comment]
Fixed in today's changelog
