### ISSUE TITLE
Gold crates

### ISSUE THREAD

**Issue by Vasiliskati** [EarthMC/Issue-Tracker#1683]
### Server

Aurora

### Describe the bug

Voting twice and getting only 1 crate even tho in the chat it appeared 2 times the vote message

### To Reproduce

Vote again

### Expected behavior

I excpected to get 2 crates 

### Additional context

This is the 3rd time thats happening its getting annoying also i tried /cr claim nothing

**Comment by AndrewCheedle** [comment]
The vote sites are at fault in this case and unfortunately we cannot refund gold crates.
