### ISSUE TITLE
Keep inventory for mayors at their towns arenas [request]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1684]
### Is your feature request related to a problem? Please describe.

To avoid townhoppers that join towns, ask for a free plot then turn on pvp on the plot and proceed to kill and steal the mayor, if the mayor keeps their inventory town hoppers won't be able to steal anymore so they probably stop town hopping.

### Describe the solution you'd like

It could be great that mayors could keep their inventory if they are at an arena at their own towns or for instance if the arena is just recently create give them some time in case they are killed to keep their inventory.

### Additional context

Players who are mayors now have to be very careful inviting players and giving them plots so they don't get killed, playing with fear is not nice. If it is implemented it will be easier for mayors to invite and trust, as well as new players will be able to ask for plots or talk calmly because there will be no danger of being killed by town hoppers.

**Comment by CorruptedGreed** [comment]
Implemented
