### ISSUE TITLE
Recipes for Heart of the Sea 

### ISSUE THREAD

**Issue by Gris1gr** [EarthMC/Issue-Tracker#1686]
### Is your feature request related to a problem? Please describe.

Since many towns start to get underwater in Aurora I believe its time to add conduits to help them grow.

### Describe the solution you'd like

I believe conduits should by no means be as expensive as beacons since its buffs are less and god armors can pretty much reach their performance but should still be something unique.
Below I have 2 ideas for a heart of the sea recipe(we can keep conduit as it is) that are not as expensive as a beacon would be, use aquatic items and keep it unique 

### Additional context

![2023-06-10_10 04 26](https://github.com/EarthMC/Issue-Tracker/assets/127773928/b924607a-f844-4aa6-ad2f-95e7c01ee17e)
![2023-06-10_10 06 02](https://github.com/EarthMC/Issue-Tracker/assets/127773928/bfd1482a-ae16-41d9-be57-9ab329872a24)

**Comment by Veyronity** [comment]
No
