### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NiQiuYu1** [EarthMC/Issue-Tracker#1689]
### Server

Aurora

### Describe the bug

I lost all of my gold that i put in my bank temporary

### To Reproduce

put gold in the bank

### Expected behavior

all the gold will disapear temporary

### Screenshots

![WIN_20230612_17_24_36_Pro](https://github.com/EarthMC/Issue-Tracker/assets/136355214/581dada6-f00e-43ad-8b2f-e0aa4963d1e9)

**Comment by AndrewCheedle** [comment]
Make a ticket in https://discord.gg/xpm8vAanxN as this is not support server
