### ISSUE TITLE
[Mechanic]Town Population Limit Removal or Extension

### ISSUE THREAD

**Issue by jabesb2** [EarthMC/Issue-Tracker#169]
I believe a town only being allowed 50 residents is a bit low, I know you want to prevent population stacking, but if a town truly wants to grow to a decent size with a myriad of active players the cap being set to 50 is far too low.

The solution i'd like to see be implemented is either a higher population cap  say around 80 - 100 or a removal of a population limit.

**Comment by Coffeetom** [comment]
I'm going to be honest, no town gets 50 active players. If you're town has reached the limit, get rid of the inactives.

**Comment by jabesb2** [comment]
I agree that not all would be active, but having to kick people in order to try and get new blood seems a bit ridiculous.

**Comment by Coffeetom** [comment]
Personally, I find it pretty reasonable. And this will help prevent nations having massive inactive populations. You won't have towns with like 70+ people, 50 of which would probably be inactive. This was a very common occurrence in classic.

**Comment by BowShot118** [comment]
*See Tokyo On Classic* Reached 100, only about 10 played. It makes nations more spread out instead of contained within 1 town. Coffee's point is very true.

**Comment by MineHero43** [comment]
Just add the inactivity timer like on classic, problem solved.

**Comment by BowShot118** [comment]
> I don't think that this issue would be easy to fix with just an inactivity timer, sure it would help but if an active member has to take a month off from the server due to personal issues when they come back they would be kicked from their town. I guess setting an inactive role to an active member who cannot be active would solve the issue.

It's part of life and it happened on classic. People could just assign themselves the rank, as mayors, and never have their town collapse. Defeats the point of an inactivity kicker. And the kicker was after ~ 40 days, not a month solid.

**Comment by Coffeetom** [comment]
In your example you mention an active player. If a play is active, I'm sure they would take measures to ensure items are not lost when having a planned break. If they are that dedicated, they would probably store them in a secret location, or give them to friends. And if such break is unplanned, if you are gone for over 40 days, you may have to restart, however that is the fact of life. People need to be kicked for towns to collapse and new players to make new towns.

**Comment by Ultil0l** [comment]
hmm, yes, but its kinda shit if lets say your pc fails you for a while and when you get back you got kicked from your town and its full now.

**Comment by BowShot118** [comment]
Contact staff.

**Comment by Ultil0l** [comment]
true

**Comment by JoshsCode** [comment]
I think the 50 player max is good for the server. It maxes out larger towns and encourages people to move to other towns so there isn't just a few huge towns with 100+ people but many towns of close to 50 as we mature in the server age. And I mean most people who join your town might play the day they join but never log on again so just kick them...

**Comment by KarlOfDuty** [comment]
We feel this limit works fine as it is.
