### ISSUE TITLE
KeepInventory rules in Arena plot

### ISSUE THREAD

**Issue by Silent-Note** [EarthMC/Issue-Tracker#1690]
### Is your feature request related to a problem? Please describe.

I would like to propose a feature enhancement to differentiate between **arenas** and **non-arena** plots, implementing the **KeepInventory**  rule exclusively for arenas.

**Description:**

- My suggestion is to introduce a clear distinction between these plot types, where the **KeepInventory** rule will only be applied to designated arenas.
- This distinction will allow players to enjoy the benefits of retaining their items within the arenas, while maintaining the standard rules for **non-arena plots**.

**justification:**

- By distinguishing between **arenas** and **non-arena** plots, we can create a more tailored and immersive gameplay experience.
- Applying the **KeepInventory** rule exclusively to arenas will provide a unique and less restrictive environment where players can engage in battles, duel, training, and focus on skill-building.
- Meanwhile, **non-arena plots** will maintain the standard rules to ensure fairness and consistency across different areas of the game.

**Expected Benefits:**

1. Clear differentiation: The introduction of a clear distinction between arenas and non-arena plots will help players understand the specific rules and expectations associated with each area, promoting a more engaging and immersive gameplay experience.

2. Enhanced arena gameplay: Implementing the **KeepInventory** rule within arenas will significantly improve the battle experience for players. The assurance that their hard-earned items will be preserved, even in the event of defeat, creates a more relaxed and enjoyable environment. This is particularly beneficial for organizations hosting duels and training sessions, as participants can focus on skill development and tactical strategies without the worry of losing valuable items.

3. Consistency in non-arena plots: Maintaining the standard rules for non-arena plots ensures a gameplay experience that embraces the traditional elements of the game.

### Describe the solution you'd like

- Implementation of the **KeepInventory** rule exclusively for **arena plots**.
- This entails that when players enter an **arena plot**, their inventory will be preserved even if they are defeated within the arena.
- The rule should be applicable only to designated **arena plots**, differentiating them from **non-arena plots**.

**Comment by Ervestl** [comment]
Must-have

**Comment by CorruptedGreed** [comment]
Implemented
