### ISSUE TITLE
Mayor of a town being outlawed at his own town [Bug]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1691]
### Server

Aurora

### Describe the bug

The mayor of Zaragoza was outlawed at other town, but when he went back to Zaragoza, the town where he is the mayor find out he was outlawed at his own town.

### To Reproduce

- Mayor outlawed at X town.
- Mayor went back to his town Zaragoza.
- Mayor found out he was outlawed at his own town Zaragoza.
- I tried myself make me an outlaw of my own town, where i'm a mayor, but it did not work.

### Expected behavior

Only mayors or councilors of Zaragoza can outlaw players from Zaragoza

### Screenshots

![IMG_5355](https://github.com/EarthMC/Issue-Tracker/assets/128364522/04dc0379-9e12-49c9-8a90-3fb9d38f5310)

**Comment by CorruptedGreed** [comment]
Should be resolved with Towny update
