### ISSUE TITLE
Bring back Fish Roding People out of claims

### ISSUE THREAD

**Issue by AmphireYT** [EarthMC/Issue-Tracker#1692]
### Is your feature request related to a problem? Please describe.

Because there is no war plugin, there is barely any conflict between nations and bringing back fish Roding (a substitute to creating conflict) can bring that back and make nations more likely to start a war.   

### Describe the solution you'd like

Back in the days this used to be a bug that was not suppose to be indented, but at those times it was fun punishing players being afk out in the open hence it created a lot of conflict between us and the nations which made the server more enjoyable. Slowly it went bannable if you did it and got removed permantly. I and many others would like this "feature" to be brought back. The server kicks you anyways after 15 minutes if the server is full.

**Comment by CorruptedGreed** [comment]
We can add features to bring back PvP, rather than players bypassing the safe zone and getting staff a bunch of tickets involving "why did I die randomly"
