### ISSUE TITLE
[Bug] Invalid Prize Name in gold crates

### ISSUE THREAD

**Issue by GalaxyGaming2OOO** [EarthMC/Issue-Tracker#1693]
### Server

Aurora

### Describe the bug

When winning the 32g prize from a gold crate the message that displays in chat will be:
"[PLAYER] Won Gold 32 gold from a gold crate"
the first gold shouldn't be there.

### To Reproduce

Win a 32g prize from a gold crate

### Expected behavior

The message is:
"[PLAYER] Won 32 Gold from a gold crate"

**Comment by CorruptedGreed** [comment]
Added this to our backlog to address.
