### ISSUE TITLE
Rule about forever ban traps

### ISSUE THREAD

**Issue by MrLgos** [EarthMC/Issue-Tracker#1694]
### Is your feature request related to a problem? Please describe.

Noticed that some players building forever ban traps, once player fall into it then he have to open tickets and wait until moderators to teleport him out which waste their game time. It’s not good but there’s no rules for moderators to punish that guy who building the trap.

### Describe the solution you'd like

A warning should be good, if he still trying to do this for many times then ban.

**Comment by keijodputt** [comment]
Agreed. This type of trap should be declared illegal and the people building it warned accordingly, even if they, allegedly, "don't know how to make an effective kill trap".

In a 'forever ban trap', wither roses can't counter the heal/resistance effects from beacons in current difficulty, armor doesn't wear out fast enough, victims won't take them off to 'die faster' if that means their stuff (armor included) will be lost anyway, and potentially seized by the trap owner(s), so it all reduces to what each mod rules on how much of an 'abuse' it is to tp the alleged victim out of a trap and after how much time.

**Comment by CorruptedGreed** [comment]
I've forwarded this to the other Admins to begin taking a look.

**Comment by CorruptedGreed** [comment]
It's been decided that a plugin to address this issue and prevent the problem is most likely a better solution than a rule addition
