### ISSUE TITLE
[Bug]Not able to pick up items after dying

### ISSUE THREAD

**Issue by cercacerca** [EarthMC/Issue-Tracker#1698]
### Server

Aurora

### Describe the bug

I died on my claim, came back to the pile of items after respawn protection wore off, but I still can't pick them up. Bit disappointing because I had two fresh god picks and shovels (mining out a chunk).

### To Reproduce

dying on the claim and coming back

### Expected behavior

I expected to die, come back to my items, and be able to pick them up.

### Screenshots

![2023-07-11_09 48 59](https://github.com/EarthMC/Issue-Tracker/assets/139243240/b645c99a-90be-4e19-8137-d9c0ebd0f10c)
![2023-07-11_10 06 47](https://github.com/EarthMC/Issue-Tracker/assets/139243240/25da077b-70c5-4a51-ba89-9bf063b253be)
![2023-07-11_10 07 14](https://github.com/EarthMC/Issue-Tracker/assets/139243240/713851d2-1e60-43d9-816d-abbc821cb508)

### Additional context

thank you, appreciate any help.

**Comment by cercacerca** [comment]
quick update - items ultimately disappeared and I didn't get back the majority of what I used to have.

**Comment by Warriorrrr** [comment]
This looks like either client/server desync or an issue with Towny's spawn protection, did you see any messages related to the latter when trying to pick up the items?

**Comment by CorruptedGreed** [comment]
No response from issue creator
