### ISSUE TITLE
[Feature] Make Docs available in other languages.

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1699]
### Is your feature request related to a problem? Please describe.

Supporting Docs in other languages will help increase and keep new players whose primary language is not English.

### Describe the solution you'd like

Add the feature in Docs that allows users to change to other languages.
Translations should be good solicited on the Discord, as was the case with Towny before.
Also, it would be good to be able to translate the Premium as well.

**Comment by CorruptedGreed** [comment]
Not possible unless we have dedicated translators/maintainers
