### ISSUE TITLE
Joining Issues

### ISSUE THREAD

**Issue by Keennoo** [EarthMC/Issue-Tracker#17]
[Screenshot](https://cdn.discordapp.com/attachments/227150661475762177/502744453111611392/unknown.png)

Changed DNS like suggested, restarted MC, PC, tried on two other PC's, still broken. I joined on 1.13 and 1.13.1.

**Comment by KarlOfDuty** [comment]
DNS issues have been resolved, all should be able to connect normally within a few hours or so.
