### ISSUE TITLE
Releasing the Classic Map

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#170]
I'd like to see the EarthMC Classic map released to the public in its current state, as staff can't/aren't re-enabling classic after the closes for maintenance. I don't know how the hosting is managed, but maybe being able to direct the server space to Terra Nova would be the best idea. Despite me wanting to see classic continued, I think this would be best for the server and it makes sense as it's a server that's never re-opened anyway. *Awaits the controversy*

**Comment by KarlOfDuty** [comment]
Rip classic

**Comment by KarlOfDuty** [comment]
We do not feel like classic should be closed at this moment but maybe we can re-open this if it ever is.
