### ISSUE TITLE
War Plugin

### ISSUE THREAD

**Issue by theheroboy** [EarthMC/Issue-Tracker#1700]
There is a war plugin I found that you guys can add, I already made a ticket in the discord earthmc support server before, corruptedgreed told me that if I find another war plugin I come to you guys and here Iam.
This is the link to the war plugin https://dev.bukkit.org/projects/vectron-towny-wars
Pls reply fast

**Comment by Fruitloopins** [comment]
mfw
![image](https://github.com/EarthMC/Issue-Tracker/assets/49851457/06c45684-7121-4855-80d3-02ad38955aa8)

**Comment by theheroboy** [comment]
> mfw
> 
> ![image](https://github.com/EarthMC/Issue-Tracker/assets/49851457/06c45684-7121-4855-80d3-02ad38955aa8)
> 
> 

?

**Comment by CorruptedGreed** [comment]
The plugin was last updated in 2014, considering it's no longer supported and doesn't even work with the current version of Towny we cannot implement it. Please consider these factors when recommending plugins in general.
