### ISSUE TITLE
[Bug]Combat Log plugin is broken

### ISSUE THREAD

**Issue by Stulenkaiser** [EarthMC/Issue-Tracker#1702]
### Server

Aurora

### Describe the bug

The Combat log Plugin is broken, so you can log out while in combat aswell as go back to non PvP chunks.

### To Reproduce

hit a person in a pvp chunk.

### Expected behavior

The person shouldnt be able to Log out or go back to non PvP chunks after getting tagged.

**Comment by Aylywyn** [comment]
Copy of #1682 and several Discord threads.

**Comment by deafkite42** [comment]
It sometimes works and it sometimes doesn't, seemingly at random

**Comment by deafkite42** [comment]
It seems to maybe be related to server TPS, when the player count is below 100 and the TPS is near 20 it seems to work fine, but not when the server is almost full and the TPS is lower

**Comment by CorruptedGreed** [comment]
Fixed in today's changelog
