### ISSUE TITLE
[Mechanic] Be part of multiple towns

### ISSUE THREAD

**Issue by R3dan** [EarthMC/Issue-Tracker#1703]
### Is your feature request related to a problem? Please describe.

As you are able to own plots in any town, it can sometimes be very hard or inconvenient to to to your property. For example if I own a plot in my town, a plot in 2 other towns and 2 in 2 separate nations I can only easily access 2 town plots (/home and /t spawn) and the nation plots with their to command. This is especially annoying if you want to own multiple towns to increase revenue etc.

### Describe the solution you'd like

I would like the /home command to open a gui where you can select which plot to TP to. (Premium users could have the benefit of unlimited plots tps with standard having a max if you wanted). 

**OR**

If you are the mayor of a town you can TP to any of your towns but only be able to select a "main" town from which your nation is displayed.

The only other way for people to effectively run 2 towns is to be able to TP there somehow but also be mayor in both places

**Comment by 1T3Y** [comment]
Everyone would use that mechanic to be a resident of every town in their nation at once and increase max town size / nation bonus. I personally don't like the idea of being in multiple towns at once

**Comment by R3dan** [comment]
Yes, that would be a problem but maybe the ability to TP to your plots or be able to be apart of multiple towns but not in your nation (as you can /t spawn) and it doesn't count as a "resident" you could be a "diplomat" given if you own an embassy

**Comment by 3meraldK** [comment]
Just enable /t spawn to towns in which you have plots

**Comment by R3dan** [comment]
Yes that would work, just thought it would be a bit more complex to code as there are plenty of plugins that allow you to set spawns and towny Devs aren't paid enough so it would have to be enc and that would also require their new plugin to have access to towny info

**Comment by 3meraldK** [comment]
> Yes that would work, just thought it would be a bit more complex to code as there are plenty of plugins that allow you to set spawns and towny Devs aren't paid enough so it would have to be enc and that would also require their new plugin to have access to towny info

It's very easy to code, trust me.

**Comment by Warriorrrr** [comment]
Being part of multiple towns is not something that will be implemented
