### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Rydaan** [EarthMC/Issue-Tracker#1704]
### Server

Aurora

### Describe the bug

Nation I sent ally to has not received it, they have tried sending an ally to me and I have not received their ally request.

### To Reproduce

Send an ally request to a nation then disconnect from the server

### Expected behavior

I expected to be allied with the nation I sent the request to

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/141320630/3b74447d-6ce0-4a63-8b32-3f6129b6d1cf)

**Comment by MrLgos** [comment]
Try /n ally add -African_Coast

**Comment by Rydaan** [comment]
> Try /n ally add -African_Coast

African Coast isn't the issue, Sinaloa is. I'm unable to revoke the request to Sinaloa because it doesn't exist, yet it does somehow.

**Comment by Aylywyn** [comment]
Cooy of #1673 and note information in several Discord threads.

**Comment by Fruitloopins** [comment]
duplicate
