### ISSUE TITLE
mayor stopped playing

### ISSUE THREAD

**Issue by coolepcidude** [EarthMC/Issue-Tracker#1707]
### Describe the issue

The current mayor of the town al habala has stopped playing the game, so i want somebody to make me become mayor bc its a realy cute town  and i dont want it going in to ruin ):

### Coordinates

cords of town: 7475/101/4009

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/142095881/046fa75f-2f83-4268-9771-aae14ab44397)

**Comment by coolepcidude** [comment]
and if you think this is a scam and the mayor hasnt stopped playing ill send a picture
just tell me

**Comment by coolepcidude** [comment]
pls somebody respond ):

**Comment by Aylywyn** [comment]
When the Major goes 42 Days Inactive and his data will be deleted.  And the next highest Ranking then oldest Resident will become Major automatically.

If there is no next Resident, in three days of Ruins, it will fall and you can /t new and /t claim over it.

There is no other way.
