### ISSUE TITLE
[Bug] Gateway timeout when requesting bulk endpoints

### ISSUE THREAD

**Issue by sfs1** [EarthMC/Issue-Tracker#1709]
### Server

Aurora

### Describe the bug

Gateway timeout when requesting `/v2/aurora/towns/` or `/v2/aurora/residents/` from API (`/v2/aurora/nations` is fine though)

### To Reproduce

Visit `https://api.earthmc.net/v2/aurora/towns` or `https://api.earthmc.net/v2/aurora/residents`

### Expected behavior

It should respond with every town or resident.

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/118557104/7852610f-4df7-49c8-a066-f7a97e3603ea)
![image](https://github.com/EarthMC/Issue-Tracker/assets/118557104/bb4fb2f0-db18-4234-b31d-3df8bee03643)

**Comment by Fruitloopins** [comment]
These are all broken currently as they get timed out on CloudFlare's side before loading

**Comment by Fruitloopins** [comment]
And don't trust the data from the nations endpoint, it's very outdated, someone managed to get it to load one time somehow and it's just cached that since

**Comment by sfs1** [comment]
It shouldn't be cloudflare, it responds with a 504 in 5 seconds. Might be something to do with the reverse proxy if its using one?

**Comment by sfs1** [comment]
Any updates?

**Comment by Fruitloopins** [comment]
> Any updates?

no

**Comment by Fruitloopins** [comment]
@sfs1 there is now a v3 in beta that allows you to search for many things at a time by separating them through commas, pre-release docs are at https://github.com/EarthMC/EMCAPI/tree/master/docs

you can request up to 100 things but keep in mind requesting a lot of things can still cause timeouts, but i'm working on multithreading and increasing that timeout time if possible
