### ISSUE TITLE
Set the nation player title from 10 to 16 characters

### ISSUE THREAD

**Issue by SkyMoon1427** [EarthMC/Issue-Tracker#1710]
### Is your feature request related to a problem? Please describe.

It's not a problem but just a request :D

### Describe the solution you'd like

Putting 16 characters for the nation title would be better since emc added the title dye feature and with 10 characters it's just not enough to try them all out. 16 would be better since you can have more colors for names which would give people more interest :D

**Comment by CorruptedGreed** [comment]
Change implemented in last changelog
