### ISSUE TITLE
[Feature] Wildsblock list

### ISSUE THREAD

**Issue by Colt44Magnum** [EarthMC/Issue-Tracker#1712]
### Is your feature request related to a problem? Please describe.

Unable to allow residents to mine within the town without giving them build:destory perms

### Describe the solution you'd like

By adding stone to the wildsblock list Mayors can create mines within their towns and not have to worry about players destroying aesthetic structures at the surface. This allows for better looking mines and for resources underneath towns to be mined up when  its possible that most of the resources would be overlooked in town chunks because of perms.

**Comment by Fruitloopins** [comment]
i brought this up since it seems good to me

**Comment by Fruitloopins** [comment]
would be good to add deepslate ores and maybe some other stuff too if you want to make a list

**Comment by Colt44Magnum** [comment]
I went ahead and made a list, not sure if I got everything. I don't remember seeing copper on the original wildsblock list so I went and added it to my list below. 


minecraft:stone
minecraft:granite
minecraft:diorite
minecraft:andesite
minecraft:gravel
minecraft:dirt
minecraft:clay
minecraft:calcite
minecraft:budding_amethyst
minecraft:copper_ore
minecraft:deepslate
minecraft:deepslate_coal_ore
minecraft:deepslate_copper_ore
minecraft:deepslate_diamond_ore
minecraft:deepslate_emerald_ore
minecraft:deepslate_gold_ore
minecraft:deepslate_iron_ore
minecraft:deepslate_lapis_ore
minecraft:deepslate_redstone_ore
minecraft:dripstone_block
minecraft:tuff
minecraft:large_amethyst_bud
minecraft:medium_amethyst_bud
minecraft:small_amethyst_bud

**Comment by Fruitloopins** [comment]
@CorruptedGreed

**Comment by Fruitloopins** [comment]
done
