### ISSUE TITLE
Following players on map fails when a player is hidden

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1713]
### Server

Aurora

### Describe the bug

This bug is universal, related to the Dynmap. Can't make an issue on webbukkit/Dynmap, because it requires a server configuration to put in. While following a player on a map, in the moment players goes hidden, you are teleported to (0, 0) until the player comes visible back.

### To Reproduce

1. Go to a Dynmap
2. Expand player's sidebar (hover mouse on right side of the website)
3. Click on a visible player's head. The player's label will be highlighted
4. Wait until the player will go underground (or offline, didn't test)

### Expected behavior

After a player goes hidden, camera should stay at place where they were last seen.

**Comment by Fruitloopins** [comment]
@3meraldK wouldn't this apply better as a bug for dynmap devs

**Comment by Warriorrrr** [comment]
It would be better to raise this issue with the dynmap devs yeah. You can obtain a config by running the plugin locally, editing the option that changes visibility based on light level & reproducing it ofc.
