### ISSUE TITLE
Combat changes proposal

### ISSUE THREAD

**Issue by Fruitloopins** [EarthMC/Issue-Tracker#1714]
### Is your feature request related to a problem? Please describe.

It is far too easy to avoid combat when you are caught off guard, you can epearl away or just log off if you haven't been hit yet and there's basically nothing the attacker can do about it.

### Describe the solution you'd like

I would want two changes:
- An extended ender pearl cooldown
With the standard ender pearl cooldown it is very easy for a player to throw multiple ender pearls in several directions in quick succession making it extremely difficult to get enough damage off to kill them as they teleport around, it is also possible for their combat tag to expire while they are teleporting around as it's hard to get a hit on them which will allow them to enter claims and be safe or log off. A cooldown of 15-30 seconds would be better in my opinion.

- NPCs that stay around for a bit if a player logs off in wilderness
This NPC would be able to be attacked. This will keep it possible to log off in wilderness if it safe to do so, but it will prevent players from logging off the instant they see an attacker to circumvent the combat log plugin. The NPC could stick around for 15 seconds or so.

### Additional context

I think this will keep PvP interesting and raise the skill ceiling as you can't just run away the second you start losing. It will also avoid situations such as running out a long distance to attack a player on the Dynmap only for them to log off as soon as they see you, making the entire journey useless.

Neither of these changes would make it impossible to stay safe in wilderness, it would just require more proactive effort from players to make sure they don't get attacked in the first place (invis) if they don't want to fight. If you get caught off guard you shouldn't have a get out of jail free card.

**Comment by Veyronity** [comment]
ok

**Comment by Veyronity** [comment]
ur the dev, so do it

**Comment by MizolyRyo** [comment]
+1
Pearl cooldown of 16s is best choice I guess, same as Loka
Also add /log if you gonna add log NPC, but this update is maybe bad for laggers bc you can’t do anything when you log on and fall into lag void

**Comment by Fruitloopins** [comment]
you can't die from unloaded chunks like that, and we have a plugin to prevent void item loss anyways

**Comment by Fruitloopins** [comment]
log NPCs would only be a thing in wilderness

**Comment by Aylywyn** [comment]
Why not just like current Teleporting?  A 15(?)-second "Waiting to log out..." message.  With "Moving/Being attacked has cancelled your log out."  Seems smoother than using a dummy NPC.

**Comment by Fruitloopins** [comment]
they should be able to just log off if they know they are in a safe spot and they shouldn't be punished if they happen to crash or something when no one is attacking them

**Comment by Aylywyn** [comment]
Okay.  That's probably Edit B) then...

But the "Waiting..." would force people to use a, uh...,  /logout command and who is going to do that?  You'd have to read the Docs to figure that out....

Dummy NPC probably makes the most sense, after some thought/caffeine.  If it is attacked, treat it as combat logging (...used to be treated :-) ).

Overall, higher stakes in the Wilderness is a plus.

**Comment by MizolyRyo** [comment]
> you can't die from unloaded chunks like that, and we have a plugin to prevent void item loss anyways

I have an another question, what will happen if a player kicked for lagout in wilderness? Log NPC would be summoned as always?

**Comment by Fruitloopins** [comment]
> I have an another question, what will happen if a player kicked for lagout in wilderness? Log NPC would be summoned as always?

yes but presumably no one would be nearby so they should be safe

**Comment by AlbanianMan** [comment]
![Screenshot 2023-11-01 193355](https://github.com/EarthMC/Issue-Tracker/assets/149622394/7880202f-d281-487d-861f-3c5d6ec6d28f)
 haste pots do not owkr on nova?

**Comment by cottnn** [comment]
You can just copy the mechanic from DayZ: you can log out at any time by exiting the game normally, but your character will stick around for 15 seconds or so. Or you can quit the game using the command and it will begin a countdown, during which you will be able to see your surroundings.
