### ISSUE TITLE
[Bug] Not able to unclaim some plot

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1715]
### Server

Aurora

### Describe the bug

When I Tried to unclaim in a small town, I got an error message like below. 
`[Towny] You cannot unclaim this townblock because the townblock at -942,-545 would not have enough adjacent claims (2 are required.) `

### To Reproduce

1. Make town and claim some plots ( In my case 1x5 sized. )
2. do `/t unclaim` in some plot

### Expected behavior

Unclaim plot correctly.

### Screenshots

https://www.youtube.com/watch?v=jdKF90pULqI 

### Additional context

I was doing claim to check the current claim spec which requires a certain number of adjacent plots, and ended up with a 1x5 sized town.
Then, I tried to unclaim the unnessesary plots but  could not do so and got an error.
In the case of small towns, it seems that the limit by adjacent plots do not apply when claiming, but do apply when unclaiming.

**Comment by asyi0** [comment]
I have tried a bit more and wondered this might be a correct spec?

- Can not unclaim and make any plot so that adjacent chunks are less than 3 chunks.
- If the town size is less than 4 chunks, the adjacent  plot limit can be ignored.

**Comment by CorruptedGreed** [comment]
Resolved by temporarily toggling off `min_adjacent_blocks` config
