### ISSUE TITLE
[Bug] API Towns Bulk Endpoint Doesn't Work

### ISSUE THREAD

**Issue by DMG1Plays** [EarthMC/Issue-Tracker#1716]
### Server

Aurora

### Describe the bug

The official EarthMC API bulk endpoint for towns ([https://api.earthmc.net/v2/aurora/towns/](https://api.earthmc.net/v2/aurora/towns/)) doesn't work.

### To Reproduce

To reproduce, follow the above hyperlink or paste it into Postman for a GET request.

### Expected behavior

The request should receive all of the towns and their associated data.

**Comment by DMG1Plays** [comment]
I think this specific endpoint was down temporarily when I was trying to use it. It now works at the time of this comment.

**Comment by Fruitloopins** [comment]
all the bulk ones are broken

**Comment by DMG1Plays** [comment]
> all the bulk ones are broken

So do they work on and off then?

**Comment by Fruitloopins** [comment]
if they work it's probably out of date cached data
