### ISSUE TITLE
Prevent people from abusing public /t spawns to trap people

### ISSUE THREAD

**Issue by deafkite42** [EarthMC/Issue-Tracker#1717]
### Is your feature request related to a problem? Please describe.

After allowing public /t spawns, people have been abusing the fact there is no keepinv radius around /t spawn to kill people that tp. Since there has been no rule spawn trapping since the keepinv radius was introduced to nation spawns , public /t spawns allow people to spawn trap as much as they want with zero consequences. Obviously this got overlooked when public /t spawns were added. 

### Describe the solution you'd like

Introduce a 3 chunk keepinv radius for /t spawns (if possible only on public ones) for all players, not just residents of that town.

**Comment by Fruitloopins** [comment]
i made a fix earlier but found an issue with it, but it's being worked on
