### ISSUE TITLE
Grass growth speed

### ISSUE THREAD

**Issue by RoJoGuapo** [EarthMC/Issue-Tracker#172]
I am trying to create raods in my town using paths, but waiting for grass to grow takes ages. It is also harder because the land by my town is mostly podzol and red sand. Beause of this, grass can not really grow, or it just grows really slowly. 

Grass should grow on dirt wherever it is placed and at a quicker speed.

I do not believe it should be a problem for people who like dirt, because the grass can be destroyed and turned back into dirt if the owner wants dirt.

**Comment by MSatrokrm** [comment]
Silktouch shovel mate

**Comment by BowShot118** [comment]
> Silktouch shovel mate

uh huh

**Comment by RoJoGuapo** [comment]
I don't have the resources to make enchanted books yet, and I want to focus on building, and not grinding.

**Comment by BowShot118** [comment]
then double smelting should be re-enabled to cut down on that.

Back onto topic, grass wont be that costly. I can sell you some if you want.

**Comment by RoJoGuapo** [comment]
I don't really want to pay for something that there are millions of in the world, but it just wont grow where I am

**Comment by KarlOfDuty** [comment]
I think you just need to place lots of lights in the area, should speed it up adequately. The random tick rate is the same as any minecraft world as far as I know.

**Comment by BennyBurst** [comment]
Use you mcmmo skill (herbalism)
Use green terra (hold seed in ur hand and rightclick the dirtblock)
You have a chance of making it into grass.
