### ISSUE TITLE
Old Nation Leaders having Full permission

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1721]
### Server

Aurora

### Describe the bug

After a Nation has changed ownership (Town changed) The old nation leader has Chancellor permissions WITHOUT having the rank. This forces the new nation leader to KICK the old leader's town to remove the permissions.

### To Reproduce

- 2 Towns
- One is Nation capital
- Make 2nd join nation and make it capital
- Old capital mayor will have full Chancellor permissions (managing allies/enemies, granting Diplomat rank to himself or others. but no /n say permission which proves Towny KNOWS hes not leader)

### Expected behavior

The old Mayor should NOT have any permissions left after change of ownership

### Additional context

The problem was fixed after the old capital was kicked from the nation and joined back in.

**Comment by Fruitloopins** [comment]
@Veyronity i don't get what this means

**Comment by Veyronity** [comment]
when you sell a nation thru /n set leader
the old leader still has chancellor perms without having rank
@Fruitloopins 

> @Veyronity i don't get what this means

**Comment by Fruitloopins** [comment]
🤯

**Comment by Veyronity** [comment]
💀

**Comment by MizolyRyo** [comment]
😂
