### ISSUE TITLE
[Bug] Deposited gold, lost gold

### ISSUE THREAD

**Issue by Kojabi** [EarthMC/Issue-Tracker#1724]
### Server

Aurora

### Describe the bug

I deposited 64 gold (around 1:30-2:00 am gmt) into my town bank with /t deposit 64 (i did it in bank plot) The gold left my inventory but didn't go into my town bank,

### To Reproduce

I couldn't reproduce it

### Expected behavior

For 64 gold to go in town bank

**Comment by Veyronity** [comment]
Make a ticket
