### ISSUE TITLE
[Bug] Ruined Towns can be bought thru /t buytown - Update:  Mayor is  stuck

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1727]
### Server

Nova

### Describe the bug

When a town falls into Ruin (whether by 42d or /t delete) it's still for sale
This allows other people to /t buytown and become Mayor
so now instead of "Spirit NPC33" its "NPC33, Spirit [player name]" when you  do /t reslist
And that new mayor can /n join WHILE the town is still ruined, Truly Cursed

### To Reproduce

/t new Test
/t forsale 0
/t delete
/t leave
/t buytown test
/t reslist and /n join to confirm this Curse

### Expected behavior

Towns shouldnt still be forsale when fallen

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/0015db6a-1a66-429b-962d-d75db249b4f2)
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/6c4f2173-3920-49b7-b11d-6f7e998b4b43)

**Comment by Veyronity** [comment]
Note: its still (For Sale: 0G) cuz new owner (oisar) that bought it after it fell doesnt want it again so he put it forsale

**Comment by Veyronity** [comment]
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/8ad64a5f-e4ab-45c7-8e34-e50fcd864806)
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/0dc7b6a5-2913-4fba-a090-fecb5c0b6bfd)
It's really cursed to look at, i fr thought he /t set name Makassar_Ruins till i did /t Maka and autofill showed Makassar as only option 
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/d84f4e65-0689-4862-8eac-ba67111d7faf)

**Comment by Veyronity** [comment]
Update: Mayor is stuck
They cant /t leave, /t delete, /t set mayor NPC33
Nothing.
Just wait till the 72 hours are over

**Comment by MrLgos** [comment]
Suggest resolution: after the town get ruined, set town forsale status to false.

**Comment by Fruitloopins** [comment]
warrior fixed this a month ago
