### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1728]
### Server

Aurora

### Describe the bug

When a town falls into ruin / is deleted,
Any quickshop in claims is deleted
What i have noticed tho, is that only the sign is deleted. If i hit the chest it says that quickshop's info and if i try to open the chest it says it is locked
I'm gonna assume that it's not supposed to do that
Correct me if im wrong tho

### To Reproduce

make a test town
make a quickshop
/t delete
hit the chest or try to open

### Expected behavior

not sure tbh but prolly for the system sign to be removed too

**Comment by asyi0** [comment]
When a town is deleted, signs and beds are deleted, but Quickshop does not  to be deleted, in fact only sign deleted shop chest seems to remain.
The shop can be removed by destroying it while sneaking, but if the sign is removed, the contents will not be known until it is destroyed, so it would be better if the sign is not destroyed.

**Comment by MrLgos** [comment]
imo remaining in this way (ppl destroy the chest instead of automatically remove the shop attribution) is way easier and not necessary to fix this.

**Comment by Veyronity** [comment]
okay
