### ISSUE TITLE
VoteParty API endpoint is needed

### ISSUE THREAD

**Issue by MrLgos** [EarthMC/Issue-Tracker#1729]
### Is your feature request related to a problem? Please describe.

VoteParty info is important in players community. Once it added, ppl will remember to vote for EMC even if they are not MC online. We will be available to add alert bots to ask them to vote and get online to get the crates. Also, it just give the public the in game /vp command info, won’t have any possible data leaks.

### Describe the solution you'd like

@Warriorrrr could you pls help us add this to API? I think it will increase the amount that ppl vote for EMC.

**Comment by Veyronity** [comment]
Vouch for Lawyer!!! @MrLgos 
And no warriorrr resigned
Ping Fruit or Greed (72-144 Hour replies)

**Comment by CorruptedGreed** [comment]
Added already
