### ISSUE TITLE
Walking in no perm town and getting "Allies arnet allowed to build" for no reason[Bug]

### ISSUE THREAD

**Issue by JR1258** [EarthMC/Issue-Tracker#1732]
### Server

Aurora

### Describe the bug

Basically whenever I am walking in a area where I have no perms or anything Im getting the "Allies arnet allowed to build" notice even tho im not even building anything nor breaking anything. Im not doing anything that would usually alert this im only waling around.

### To Reproduce

Walking around 

### Expected behavior

"Allies arnet allowed to build" Notification

### Screenshots

[https://drive.google.com/file/d/1zoSbiCI8QiS0Wt3Ls7sVz30tqlkdAnk8/view?usp=sharing](url)
i coudlnt upload video here so its in google drive

**Comment by celerry** [comment]
are you wearing frost walker boots?

**Comment by JR1258** [comment]
Oh shit i am


> are you wearing frost walker boots?

**Comment by MrLgos** [comment]
A funny bug
