### ISSUE TITLE
Beacon Issues

### ISSUE THREAD

**Issue by nagnol** [EarthMC/Issue-Tracker#1733]
### Server

Aurora

### Describe the bug

I have two issues. 

Issue 1: When creating a beacon pyramid and setting the beacon to Haste 2, it only gives the effect of Haste 1. I click Haste 1 and then Haste 2 on the right. Next, add in an iron ingot and click the checkmark. It only gives me Haste 1. This issue happens with all of the other effects as well. (Jump Boost, Resistance, Strength, etc.)

Issue 2: When I do the same exact thing, but for Speed 2, when I click the checkmark, it kicks me out of the Aurora server, then into the hub of the server.

### To Reproduce

Issue 1: Activate beacon with Haste 2 selected

Issue 2: Activate beacon with Speed 2 selected

### Expected behavior

Gives Haste 2 and Speed 2

**Comment by AndrewCheedle** [comment]
Issue is native to 1.20 and above, the bug seems to not exist in 1.19.4 which is the current version of the server so its advised to use that version instead
