### ISSUE TITLE
[Bug] Quickshops can't tell different durabilities apart

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1734]
### Server

Aurora

### Describe the bug

QuickShops can not differentiate between durabilities

### To Reproduce

- Get 2 pickaxes of the same enchants and name
- one of which low durability, the other max / high durability
- put low durability inside the chest
- use the high durability to make a shop

- the low durability pickaxe counts as a sellable item, despite having way lower durability
- Quickshop sign tells you its "100% Remaining" because that's the pickaxe you used to make the shop
- when you end up purchasing, you get surprised that the pickaxe is at low durability, and not max like the preview showed you.

### Expected behavior

Shop should not count that low durability item as part of stock, when the item used to make the shop (and the preview) is at full / high durability

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/38b9eb37-5527-435a-9529-660f58e65fc6)
Preview Showing full durability
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/81fd1f78-c27d-4d34-a963-5751c509bc4e)
"16 in stock", when all the ones inside the chest are at like 5% durability
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/705fdad2-3831-469d-92c6-c3a7fa53d253)
Image of stock

### Additional context

This is literally a scam BY the plugin, most scams are on emc are easy to prevent if you're smart. but with this one, the plugin lies to you, so there's nothing you can do to prevent it.

**Comment by CorruptedGreed** [comment]
If I edit the config now it auto shutdown destroys the plugin so this can most likely be fixed for when we migrate to Quickshop-Hikari

**Comment by Cap-Worm** [comment]
What if I'm selling gold tools from fishing that don't need to be 100%?
