### ISSUE TITLE
[Mechanic] Make it optional to Enable or disable "Friendly Fire"

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1736]
### Is your feature request related to a problem? Please describe.

"Friendly Fire" is where you can /plot toggle pvp on or /t toggle pvp on while a resident is in the plot, while when outsiders are in there you can't. I understand that some people might like this feature, so just make it optional; or remove it entirely. but it really makes recruiting a lot harder, since you don't really know who to trust by giving a plot to and who to not, with overclaiming coming we REALLY don't need more problems with Recruiting

### Describe the solution you'd like

Either Remove it Entirely
Or make it optional with a command like /t set friendlyfire on etc. etc.

### Additional context

It's been a long time problem, but now with overclaim and Recruiting at an all-time high, we don't need more problems.

Thank you.

**Comment by CorruptedGreed** [comment]
Would require a Towny change, go to their GitHub to suggest as a config setting left up to mayors
