### ISSUE TITLE
The New Changelog can be abused easily

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1739]
### Is your feature request related to a problem? Please describe.

- Teleport to a town that you're not outlawed in
- Mayor outlaws you
- You are now stuck in that town if the spawn is closed
- Very risky to teleport to any town or nation now

### Describe the solution you'd like

Just like how you can't toggle on PvP when an outsider is in town claims, make it so that if an outsider is in town claims you can't outlaw them.
Very Simple and effective solution

**Comment by Veyronity** [comment]
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/30ea1dcc-cd9d-4629-abe2-33ab007ba872)
Leaked footage of typing_turtle falling to this scam
He's now stuck here for 15 minutes till staff can teleport him out :D
(Im going to let him out, but not everyone will)

**Comment by turtleexploding** [comment]
he paid me 1 dirt

**Comment by Veyronity** [comment]
Alternative Solution; (Not preferred)
New Policy: Let staff be able to teleport you out of this situation **if its obvious its a trap** after 3 or 5 minutes, cuz 15 minutes is WAY too long

**Comment by turtleexploding** [comment]
nuh uh i want to scam

**Comment by Veyronity** [comment]
> > New Policy: Let staff be able to teleport you out of this situation **if its obvious its a trap** after 3 or 5 minutes
> 
> i am probably going to write a plugin that allows players to teleport themselves out of traps under certain conditions so we can write it off as another "self-enforcing rule" and close [EarthMC/earthmc-docs#46](https://github.com/EarthMC/earthmc-docs/pull/46)

That works
For now Ima close it but this is not over
