### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Flams09g9** [EarthMC/Issue-Tracker#1742]
### Server

Aurora

### Describe the bug

Ultimate X-ray bypassing anti xray

### To Reproduce

Download newest anti X-ray 

### Expected behavior

Bypasses anti X-ray 

### Additional context

Don’t ban me i didn't mine anything with it I just submitted a report to get it fixed

**Comment by Flams09g9** [comment]
I meant for to reproduce download newest X-ray ultimate*

**Comment by Fruitloopins** [comment]
seems to work fine for me

**Comment by CorruptedGreed** [comment]
Works fine according to dev
