### ISSUE TITLE
[Bug] Unable to rotate items in item frames

### ISSUE THREAD

**Issue by UnitiveBog** [EarthMC/Issue-Tracker#1743]
### Server

Aurora

### Describe the bug

When putting an item in an item frame, you are unable to rotate the item with right clicking. This bug only affects aurora

### To Reproduce

Put an item in an item frame and right click, the item shouldn't rotate in the item frame
(I had another person test it to make sure it wasn't just me experiencing it)

### Expected behavior

The item should have rotated when right clicking in the item frame

### Screenshots

https://www.youtube.com/watch?v=zfGle6ASNFA
(Video of item frames not working)

**Comment by CorruptedGreed** [comment]
Fixed
