### ISSUE TITLE
[Mechanic] Decrease resident chunk bonus.

### ISSUE THREAD

**Issue by fritzstick** [EarthMC/Issue-Tracker#1747]
### Is your feature request related to a problem? Please describe.

16 chunks per resident is far too many.

### Describe the solution you'd like

Lower the resident bonus to 12 chunks per resident.

**Comment by Colt44Magnum** [comment]
The current plan by Fix was to decrease the number by 1 per month. I think that 12 though is a good middle ground after looking at maps of overclaimable towns in well known cities. If it would just be dropped to 12 and just stay there I think it would be perfect

**Comment by Proserrr** [comment]
100% agree to this

**Comment by CorruptedGreed** [comment]
It has been lowered to 12 over time
