### ISSUE TITLE
[Bug] Sign Dupe (another shop chest issue)

### ISSUE THREAD

**Issue by Cap-Worm** [EarthMC/Issue-Tracker#1748]
### Server

Aurora

### Describe the bug

Players are able to dupe signs from shop chests.

### To Reproduce

1. Create a chest shop
2. Destroy the sign and the chest
3. Replace the chest and start again

### Expected behavior

I expected the sign not to drop when I destoryed the chest.

### Additional context

I believe this issue has come about since the patching of the shop chest removal bug.

**Comment by Fruitloopins** [comment]
not deemed an issue
