### ISSUE TITLE
[Bug] Hearts are once again viewable by Mods; after 20/12's update

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1750]
### Server

Aurora

### Describe the bug

in 2023/12/08's changelog it was announced that "Mob and player health can no longer be viewed with mods"
Today tho I noticed that I could once again see the hearts of people, so to test it out I called a Mod (fabi) and it worked; his hearts went down as he burned in lava

### To Reproduce

Burn someone else with lava or any source of damage while using a heart-viewing Mod

### Expected behavior

Due to 08's Changelog the hearts shouldn't be viewable

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/b61c823a-7090-4c86-b9fa-332d276ac990)

**Comment by CorruptedGreed** [comment]
I had to disable that change to fix item frame rotations. For some reason the setting hiding player/entity health information from client also hid item frame rotations. Need to find some way to exclude or separate those, so until then this change is disabled
