### ISSUE TITLE
[Bug] Quickshop Quantity limit when buying is broken

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1752]
### Server

Aurora

### Describe the bug

Instead of buying 64 items per empty slot, its buying 3456 Items per empty slot, a total of ~186k per dub
Ofcourse this quantity can't be bought, so we get an error

### To Reproduce

- Make a buying shop buying 64 Dirt
- Make sure only 2 slots are empty 
- Sign will say "Buying 6912 Dirt" even tho it can only buy 128
If you try to sell it'll show u an error [Refer to screenshots]

### Expected behavior

Should only buy 64 per slot empty

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/2586d0e3-8011-4d04-8b48-feb73030ba1a)
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/da503cb3-7be7-4e68-9c2e-ac6f3cf6c52d)
![image](https://github.com/EarthMC/Issue-Tracker/assets/142887488/ea284cc9-699c-464e-93ab-6b4dbd84c7da)

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
