### ISSUE TITLE
[Plugin] Add Quickshop's Discount & Limited Addon plugin

### ISSUE THREAD

**Issue by ZePua** [EarthMC/Issue-Tracker#1755]
### Is your feature request related to a problem? Please describe.

These two plugins are add-ons to QuickShop and will bring new player's services and economic effect to Earthmc.
And, since it's a small Plugin, there will probably be no conflict with other Plugins.

Discount Addon allows players to create a Discount Code setting the amount of remaining usage, expiration time, and discount amount.

Limited Addon allows players to set a limit on the amount of sales per player in the your Shop.

Please check Quickshop's Docs for more information.
https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/category/addon

### Describe the solution you'd like

Please add Addon-Discount and Addon-Limited plugins to server from Files on this site.
https://modrinth.com/plugin/quickshop-hikari/version/5.2.0.8

**Comment by CorruptedGreed** [comment]
Implemented with latest changelog
