### ISSUE TITLE
[Bug] Only stone cannot be set Per bulk amount more than 128x in shop.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1758]
### Server

Aurora

### Describe the bug

Somehow,  only **Stone** cannot  be set Per bulk amount more than 128x in shop, while most all other items can be up to 3456x.

### To Reproduce

1. Make a shop that sell or buy stone
2. Change Per bulk amout to 129 or higher. ( /qs size 129 )
3. You get the following error message: `The given value 129 is larger than the max stack size or below one`

### Expected behavior

As same as other items, be able to  set Per bulk amount up to 3456x.

### Screenshots

![2023-12-25_203009](https://github.com/EarthMC/Issue-Tracker/assets/92248609/fa091618-8a38-4f09-93a6-6da03bb2a22d)

**Comment by asyi0** [comment]
Fixed maybe at last update.
![2024-01-03_193315](https://github.com/EarthMC/Issue-Tracker/assets/92248609/b66bdd08-892d-4f24-9f38-26016694f081)

**Comment by MizolyRyo** [comment]
![huge_2024-01-04_02 26 47](https://github.com/EarthMC/Issue-Tracker/assets/145672028/c4ac7f6b-cdfc-421b-b05b-01097461ffd5)
dad no
