### ISSUE TITLE
Shop selling not working 

### ISSUE THREAD

**Issue by Nxggetz** [EarthMC/Issue-Tracker#1759]
### Server

Nova

### Describe the bug

when trying to sell stuff to a buy shop it gives an error for an internal error while processing the purchase 

### To Reproduce

clicking a buy shop to sell items

### Expected behavior

to get gold from selling items to a buy shop

### Screenshots

<img width="471" alt="image" src="https://github.com/EarthMC/Issue-Tracker/assets/154809664/d514b1c2-9a97-46da-ab8a-39a64bc16a15">

**Comment by asyi0** [comment]
@Nxggetz 
You will get that error if the shop does not have enough space for the item you are trying to sell.
As reported in #1752 , only the buying amount on the sign is broken.
It will be easier to understand if you make your own shop and try it.

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
