### ISSUE TITLE
[Mechanic][Plugin] abandoned structures looking old

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#176]
it would be cool if abandoned buildings, forts, houses, etc can get destroyed as time passed, like vines starts to grow or cobble turns into mossy stone bricks turn cracked tall grass starts to grow
maybe 8 months later the whole building could be totally destroyed which leads to ruins
i think that would be a pretty cool feature
but things that are claimed shouldnt get abandoned
![2018-11-25_19 35 13](https://user-images.githubusercontent.com/44297328/48983004-e122ca80-f0e9-11e8-93c7-13694301ae0d.png)

**Comment by KarlOfDuty** [comment]
Could you describe more on how this would work?

**Comment by Pengun78** [comment]
@KarlOfDuty lets say, a town falls with structures in it or someone is making an unclaimed structure, as time passes the structures doesnt stay well
As you can see on the picture it gets more destroyed every month 
Things break apart, treeed start growing, grass starts growing, cobblestone turns in to mossy stone, maybe even silverfishes.
In real this also happens, this plugin can add a new level of realism and the structures would be fun to explore

**Comment by Ultil0l** [comment]
do it manually lol

**Comment by KarlOfDuty** [comment]
Does this plugin exist?

**Comment by Pengun78** [comment]
It doesnt, but im sure if it existed it would be used alot

**Comment by BowShot118** [comment]
I dislike this idea due to it destroying history.

**Comment by Pengun78** [comment]
The structure can always be repaired or get claimed (if its in claims nothing happens)

**Comment by KarlOfDuty** [comment]
As this plugin does not exist this ticket doesn't really make sense.
