### ISSUE TITLE
Horse Teleportation Improvements. 

### ISSUE THREAD

**Issue by NotAndre1098** [EarthMC/Issue-Tracker#1760]
### Is your feature request related to a problem? Please describe.

With the addition of horse teleportation, a problem has arisen due to the theft opportunities this ft has. All Someone needs to do is sit on your horse and they can teleport with it to wherever they want and you forever will lose your horse.  This is very annoying! 

### Describe the solution you'd like

i would like for a little option to "Lock" the horse. Some other games have a similar option with cars to prevent theft. All this button would do is prevent others from sitting on a horse locked by its owner. 

### Additional context

This is a major problem and causes people to be forced to put their horses into hiding rather then using them.  The pvp fts of horses is amazing, and i really want the horses to have their spotlight in use again. The Lock feature will allow that hopefully.

**Comment by Aylywyn** [comment]
You already cannot get into a chest boat in claims without perms.  Apply the same logic to mounting an animal (I am leaving that phrasing...).

**Comment by NotAndre1098** [comment]
> You already cannot get into a chest boat in claims without perms. Apply the same logic to mounting an animal (I am leaving that phrasing...).

i want it to be locked everywhere tho, imagine being in a pvp fight and getting off your horse for a second, only for someone to get on it and teleport away. theirs just so many problems with someone being able to teleport with someone elses horse.

**Comment by Aylywyn** [comment]
That's a chance you take when PvPing, I guess.  One more thing to risk with your set.

You could talk to Fruitloopins, maybe add a phantom horse like the combat log phantom so if the phantom horse gets hit or mounted it cancels/recalls the horse?

**Comment by CorruptedGreed** [comment]
Horse Teleportation has been disabled, will review if it comes back
