### ISSUE TITLE
[Bug] Shops are rolled back or broken randomly each time the server is restarted

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1761]
### Server

Aurora

### Describe the bug

After Quickshop plugin update at 2023/12/21,  some shops are rolled back randomly each time the server is restarted.
About 30-50% of the shops seem to be broken.

### To Reproduce

1. Place multiple shops with time to time
2. Restart the server

### Expected behavior

None of the shops are rolled back or broken.

### Screenshots

I attach screenshots of a particularly obvious case that occurred in our Mali Shop.

## 1 Spawner shops at -1526 136 2779
![2023-12-29_11 57 19](https://github.com/EarthMC/Issue-Tracker/assets/92248609/42df058b-e10d-498a-b126-09f7c6bd7cef)
Probably around 7 AM CET on 12/27, FG_Kuana removed the shops that sell/buy spawner, blaze egg, and magma cube egg at here, and asyi placed them there. However, after the last reboot at today, that selling shops were back to FG_kuana's shop. To add, FG_Kuana's shop were chests, not barrels.
asyi also has placed buying shop here, but the quickshop was removed and it became normal barrel and sign.

## 2 Armor shops at -1550 135 2768
![2023-12-29_11 57 26](https://github.com/EarthMC/Issue-Tracker/assets/92248609/cdcddd7a-d63b-41ba-be46-ef696c596029)
Probably around 14 AM CET on 12/27, asyi has placed the shops that sell/buy diamond Leggins and diamond boots.
However, after the last reboot, They were back to the arrow shop that there existed in this coordinate before I renovete around here.

## 3 Fish and meat shops at -1464 1335 -2785
![2023-12-29_12 12 30](https://github.com/EarthMC/Issue-Tracker/assets/92248609/10acade0-3599-4f26-8679-4e9bda278e97)
I probably placed these shops around 15 AM CET on 12/26.
However, all of these shops that I placed during this time frame are broken as well.
I assume that shops created during a certain time frame are not being recorded correctly.

### Additional context

This is a critical issue for shop owners. I hope this will be fixed as a top priority.

**Comment by limpoposex** [comment]
From what i have noticed, this issue is happening a lot to shops that disable the item display (the little item that hovers above the shop). I don't think this issue has affected any shop with item display on, but i could be wrong

**Comment by Ultraokasan** [comment]
This happened to me too and I had the item display on

**Comment by CorruptedGreed** [comment]
This is currently an issue I'm investigating, it most likely has to do with too many players making shops before the next server restart.

When the shop plugin was replaced it resulted in people making thousands of shops in the span of a few days, compared to natural growth from the start of the server. All of these shops need to be loaded from server memory when the server restarts, which becomes a problem if there's too many.

A solution that has been discovered involves restarting the server more frequently to cache the shops made before too many exist continuously in memory. So far around 27000 shops have been successfully saved since the last 2 restarts (2024-01-02 and 2024-01-04 changelogs).

**Comment by asyi0** [comment]
Some shops broke or rollbacked again.
It seems shops changes newer than a couple of days are not being saved properly.

**Comment by Ultraokasan** [comment]
And with more of a couple of days too. 
![image](https://github.com/EarthMC/Issue-Tracker/assets/128364522/ba68c2ed-cbbd-44bd-a8b2-2e531013ffe9)
Bulk shops are showed like this but doesn’t work at all.

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
