### ISSUE TITLE
Inactivity timer should be 30 days, not 42 days

### ISSUE THREAD

**Issue by 32danny** [EarthMC/Issue-Tracker#1763]
This is something that should've been changed years ago, it's just too long. Overclaim will not be as effective if we have to wait 42 days for citizens to purge, and town mayors will have to log on once a month instead of every 42 days, which does incentivize them to be more active since they have to log on the server more frequently anyway

**Comment by fritzstick** [comment]
I agree, timer is too generous and far too long but I doubt Fix would want to change this.

**Comment by CorruptedGreed** [comment]
We will not be changing this in the foreseeable future
