### ISSUE TITLE
Add Armor Stands With Configurable Limbs (PLUGIN LINK INCLUDED)

### ISSUE THREAD

**Issue by unbatedaura2281** [EarthMC/Issue-Tracker#1764]
### Is your feature request related to a problem? Please describe.

No, this feature is merely something I think could be useful and cool for EarthMC.

### Describe the solution you'd like

As a kid, I played on a hub server known as PistonMC or Sticky Piston Network. On this server's faction section, there included a plugin which contained a configurable menu that would pop up when you attempted to "configure" an armor stand. I can't exactly remember how you would trigger the configuration menu, but you would. From there, you could change the angle, rotation, and visibility of any aspect of an armor stand: head, torso, limbs. You were also able to place an item in either hand of the armor stand. I believe this would add much more liveliness and personal touch to towns across EarthMC and certainly couldn't hurt. 
I believe I have also found the original plugin utilised on the faction server I played. https://www.spigotmc.org/resources/armor-stand-tools.2237/

### Additional context

N/A

**Comment by Warriorrrr** [comment]
This was added some time after this issue was opened
