### ISSUE TITLE
[Bug] cant buy from or sell to shops

### ISSUE THREAD

**Issue by psllonllc** [EarthMC/Issue-Tracker#1765]
### Server

Aurora

### Describe the bug

Unable to purchase or interact with shops in most areas. Can successfully use some shops in Mali and any new shops placed.  

### To Reproduce

Travel to Brazil and attempt to buy and item or sell something. Get no messages get no prompt 

### Expected behavior

When interacting with the shop I expect to be prompted how many I would like to buy or sell

### Additional context

Affects me and my friends account

**Comment by Veyronity** [comment]
The quickshop plugin has been replaced with another version, the shops you're trying are old shops, so as far the server is concerned that's just a regular sign

**Comment by psllonllc** [comment]
:0 I see, OK. I hope they fix their shops soon.

**Comment by Veyronity** [comment]
Theyre probably busy, use mali or ob or yamato for now

(close the issue please)

**Comment by asyi0** [comment]
As per issue #1761, even if we make new shop, it will randomly break every time the server is restarted, making it difficult to run a large shop.
Mali plans to remake the shops after this issue is fixed.

**Comment by CorruptedGreed** [comment]
These are most likely old shops, you can contact the owners via /mail to remake them.
