### ISSUE TITLE
[Bug] Discord integration for QuickShop sends duplicate messages

### ISSUE THREAD

**Issue by nfish2021** [EarthMC/Issue-Tracker#1766]
### Server

Aurora

### Describe the bug

The EMC Discord bot sends duplicate messages of events that occur at my shops, I have seen this happen with "Somebody bought items from shop" messages, "Your shop has run out of stock" messages, and "Your shop price was changed" messages.

### To Reproduce

1. Connect Discord to EMC
2. Set up shop
3. Have someone buy an item from your shop
4. Check discord

### Expected behavior

It should only send the message once.

### Screenshots

![Screenshot_20240111_055858](https://github.com/EarthMC/Issue-Tracker/assets/150664831/5c46b91e-90fb-44f9-a605-be38f6b9bed4)

### Additional context

When the feature initially came out, it didn't do this

**Comment by Fruitloopins** [comment]
response

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
