### ISSUE TITLE
ChestShop Plugin

### ISSUE THREAD

**Issue by 21eea** [EarthMC/Issue-Tracker#1767]
### Server

Aurora

### Describe the bug

ShopChest plugin send message twice when someone buy/sell item.

### To Reproduce

Probably it just happens to me. I don't know why I tired to unlink my account I did and I connected back and it's still same. I don't know why..

### Expected behavior

I expected just one message but It sends twice.

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/79859120/290a704f-08a0-4579-a4d5-aa61fdf2490b)

### Additional context

IDK

**Comment by jkmartindale** [comment]
#1766

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
