### ISSUE TITLE
Cant use buy or sell shops [Bug]

### ISSUE THREAD

**Issue by Send-Ludes** [EarthMC/Issue-Tracker#1768]
### Server

Aurora

### Describe the bug

When I attempt to use any shops it gives the internal error message and rolls back all changes.

### To Reproduce

Not sure if its client side or not but clicking on shops and inserting a number of items/bulks or amount of gold gives the error message.

### Expected behavior

shops to process transactions give items/gold

### Additional context

started to happen a few days ago

**Comment by Veyronity** [comment]
For the 10th time, the shop is out of space, shop owner doesn't have enough gold, or you dont have enough space in your inventory (if youre buying)

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
