### ISSUE TITLE
[Feature] Change Quickshop finditem GUI from showing warp to showing nation spawn

### ISSUE THREAD

**Issue by PolkadotBlueBear** [EarthMC/Issue-Tracker#1769]
### Is your feature request related to a problem? Please describe.

The quickshop finditem gui, whilst very nice, bizarrely tells people which warp the shop in question is closest too. As warps should not be used for this purpose and are regardless often insanely distant, displaying them in this way creates confusion for newer players and adds unnecessary complexity for shop location for everyone else.
![2024-01-19_13 21 50](https://github.com/EarthMC/Issue-Tracker/assets/125825182/d0d97ce7-c497-46a9-9c29-06b9c5a9cbbc)

### Describe the solution you'd like

A much more helpful piece of information would instead be nearest nation spawn, as that, even if the shop isn't located at a nation spawn, at least helps everyone to navigate. I don't know about the ease of this, but it seems simple. If it can calculate warp it should be able to calculate nation spawn.

**Comment by JR1258** [comment]
This would be fr helpful

**Comment by Startive** [comment]
> This would be fr helpful 

agreed

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
