### ISSUE TITLE
[Bug] Shop Pluggin

### ISSUE THREAD

**Issue by unown006** [EarthMC/Issue-Tracker#1774]
### Server

Nova

### Describe the bug

Shops selling Beenest's do not properly update stock after making 1 sale even if there is stock in the chest

### To Reproduce

Make a shop selling a Beenest
Place 2 Beenest in the shop
Buy a bee Nest
The shop will go red and will not update even with stock inside

### Expected behavior

Shop updates after a sale

### Additional context

The only way to fix it is to redo the shop

**Comment by Aylywyn** [comment]
Try it with empty, new, unplaced Nests.  Full, used, sometimes even just placed, will have NBT tags and be technically different items.

**Comment by asyi0** [comment]
The current shop setup seems that if the number of bees or honey in the Beenest is different, they are recognized as different items in the shop.
Same goes for mob buckets and enchanted tools.

**Comment by CorruptedGreed** [comment]
No longer using this plugin, ported to old plugin
