### ISSUE TITLE
[Bug] unable to connect to earthmc, and only earthmc

### ISSUE THREAD

**Issue by Spencer9894** [EarthMC/Issue-Tracker#1775]
### Server

Hub

### Describe the bug

i cant connect to earthmc, i can connect to other servers just fine its only earthmc

### To Reproduce

be me and try to connect to earthmc

### Expected behavior

it lets me in

### Additional context

i already tried switching networks and devices

**Comment by Warriorrrr** [comment]
connection issues are not bug reports
