### ISSUE TITLE
[Bug] Able to teleport to enemied nations

### ISSUE THREAD

**Issue by deafkite42** [EarthMC/Issue-Tracker#1777]
### Server

Aurora

### Describe the bug

Adding a nation as enemy does not prevent residents of your nation from teleporting there. This could be useful for example for preventing residents of your nation from going to nations that frequently scam or trap. 

### To Reproduce

1. Enemy a nation 
2. Anyone from that nation will be unable to teleport to your nation 
3. However you will still be able to teleport to that nation 

### Expected behavior

If you enemy a nation, you would expect to be unable to teleport to that nation, but that is not the case.

**Comment by CorruptedGreed** [comment]
Enemies are one-way in Towny (unlike allies, which are two-way). The other nation would have to enemy you to restrict access to their spawn if they are a public nation. Therefore this is intended behavior.
