### ISSUE TITLE
[Bug] Everytime Litebans plugin is used by staff (warn/mute/ban) everyone online gets nausea effect for 1 second

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1778]
### Server

Aurora

### Describe the bug

It's been a few days that I've been seeing the effect, but wondering where it came from
Today I realised that it was when someone got warned, muted, or tempbanned
Not sure about ban, but very likely to be the same

### To Reproduce

wait for staff to mute/warn someone and you'll get nausea effect for 1 second

### Expected behavior

Should not get nausea

**Comment by Warriorrrr** [comment]
this makes no sense
