### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MasterEWild** [EarthMC/Issue-Tracker#1779]
### Server

Aurora

### Describe the bug

/t set title doesnt work
I try to /t set title and it says "I dont have enough permissions for this command" even though a own the town

### To Reproduce

Own a town and try /t set title [username] title

### Expected behavior

Lets me set a town title

### Screenshots

After trying /t set title
<img width="631" alt="Screen Shot 2024-02-11 at 6 02 14 PM" src="https://github.com/EarthMC/Issue-Tracker/assets/159741861/99abb055-c8ae-40f0-a34f-c163fa458dc2">

**Comment by Warriorrrr** [comment]
Town titles are not in use on emc, nation titles are.
