### ISSUE TITLE
error message with /town invite sent removeall [Bug]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1780]
### Server

Aurora

### Describe the bug

When i try to run the command  `/town invite sent removeall` it says "_an internal error ocurred while attempting to perform this command_" and does nothing else.

### To Reproduce

Type `/town invite sent removeall` 
No towns invites are remove.
Only you got this message: _an internal error ocurred while attempting to perform this command_
![2024-02-13_18 55 37](https://github.com/EarthMC/Issue-Tracker/assets/128364522/74670534-8bb0-442e-bc32-92bed656581f)

### Expected behavior

"New Command: /town invite sent removeall 
Removes all of the invites which a town has sent."
[Source](https://discord.com/channels/219863747248914433/988199791429320724/1206167134909108294)

### Screenshots

![2024-02-13_18 55 37](https://github.com/EarthMC/Issue-Tracker/assets/128364522/53fcd9a6-5e5a-4479-8d4f-65e1c1981a61)

### Additional context

___

**Comment by Warriorrrr** [comment]
Fixed by https://github.com/TownyAdvanced/Towny/commit/e3ac746ffd2a930f411b0bfe2e50089c753a01b3
