### ISSUE TITLE
[Bug] Plot names cannot be given color, emphasis, etc.

### ISSUE THREAD

**Issue by Wadamaro** [EarthMC/Issue-Tracker#1781]
### Server

Aurora

### Describe the bug

So far, if we wanted the plot name to be in bold yellow, we could set it with "/plot set name &e&l [name]". But now, even if we do that, the plot name will only be "e l [name]".

### To Reproduce

As above.

### Expected behavior

Fixing Bugs.

**Comment by Warriorrrr** [comment]
Minimessage tags like \<red> work fine for me, colors in plot names is also not really an intended feature as far as I know
