### ISSUE TITLE
Banner wont get broken

### ISSUE THREAD

**Issue by mikkeltaco** [EarthMC/Issue-Tracker#1783]
### Server

Nova

### Describe the bug

I have this horizontal banner that for some reason cant be broken
-Im the mayor

### To Reproduce

1. Make a pole out of "cobblestone walls" (the item)
2. Shift right click the banner on the wall
3. Let it sit for some days
4. Try to brake it but it wont

### Expected behavior

I expected it to be break and drop, but it diddent, unlike the other two i had

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/162018009/8a9f268a-886b-4200-b903-826e5634f5b9)

**Comment by CorruptedGreed** [comment]
What are the coordinates of this banner?

**Comment by mikkeltaco** [comment]
sorry for the late answer, i dont check my emails much, 8723 102 -7156

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den søn. 3. mar. 2024 kl. 22.51 skrev CorruptedGreed <
***@***.***>:

**Comment by mikkeltaco** [comment]
and theres also two other banners down the lane

Den fre. 8. mar. 2024 kl. 23.17 skrev Mikkel taco ***@***.***>:

**Comment by Aylywyn** [comment]
Are you sure it isn't just hunting around for the correct spot to punch?  The plugin is not intuitive that way.  Try going half to three-quarters of a block left of where you think you should find the hitbox.

**Comment by mikkeltaco** [comment]
Diddent seem to work

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den fre. 8. mar. 2024 kl. 23.21 skrev Aylywyn ***@***.***>:

**Comment by CorruptedGreed** [comment]
The plugin isn't natively supported for 1.19 so it may be an issue relating to that. If it's unresolvable then we'd just remove it until 1.20.

**Comment by Warriorrrr** [comment]
Flags are no more
