### ISSUE TITLE
[Bug] /qs find may kick a player (1.20.4 client)

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1786]
### Server

Aurora

### Describe the bug

When using /qs find, it may kick a player with a very long message. Happens only? on 1.20.4 client, also tested on 1.19.4 and 1.20.1 with success

### To Reproduce

Known example: on /n spawn Mali, try /qs find netherite_ingot

### Expected behavior

The finder should work as expected

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/48335651/93c6dbd8-afab-4321-8ead-6c8a1bf7e3e6)

**Comment by nfish2021** [comment]
Can confirm this is not just a 3merald problem, I have this problem too

**Comment by CorruptedGreed** [comment]
Should be fixed, otherwise open new issue
