### ISSUE TITLE
[Bug] Crafting for packed ice and blue ice show the recipe twice

### ISSUE THREAD

**Issue by keijodputt** [EarthMC/Issue-Tracker#1787]
### Server

Aurora

### Describe the bug

Just a cosmetic bug, me hopes, but the recipes for packed ice and blue ice are shown twice in the crafting GUI:

### To Reproduce

- Have some stacks of ice and packed ice in your inv
- Open the crafting GUI by clicking on a crafting table

### Expected behavior

One recipe for packed ice, and one for blue ice should show

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/9009579/0f5a9d0a-9159-43d0-bc8d-a314785db6fc)

### Additional context

Any recipe produces the same outcome, so it looks more of a cosmetic bug, but could lead to bigger issues if left unattended.

**Comment by CorruptedGreed** [comment]
Should no longer be the case
