### ISSUE TITLE
[Bug] Fix items which are not protected by Towny

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/Issue-Tracker#179]
The following items are not protected by Towny currently:

- Oak doors
- Oak fence gates
- All trapdoors
- All pressure plates
- All buttons (at least wooden ones)
- Default coloured shulker boxes
- Light grey shulker boxes
- Redstone repeaters
- Redstone comparators

**Comment by KarlOfDuty** [comment]
TownyAdvanced/Towny#3116

**Comment by Magenent** [comment]
Is it fixed yet?

**Comment by KarlOfDuty** [comment]
Yes, should be.
