### ISSUE TITLE
[Plugin] Change the command for switching a sign shop to Buy Mode

### ISSUE THREAD

**Issue by nfish2021** [EarthMC/Issue-Tracker#1791]
### Is your feature request related to a problem? Please describe.

The current `/qs buy` command is vague and for those who aren't familiar with all of the sign shop plugin's commands, it can be used to abuse them. A player might mistakenly think the command will simply buy from a shop, which is not what the command does. And once the command is executed, the mistaken player may quickly be scammed, if he was asked to do the command by someone who the scammed player thought they were assisting.

### Describe the solution you'd like

Change the command for switching a sign shop to Buy Mode so that it is obvious what you're doing (maybe something like `/qs setmode buy`).  One might falsely interpret `/qs buy` as a command to simply buy an item from a shop and that's an issue.

**Comment by Warriorrrr** [comment]
This issue would need to be raised with the developers of the shop plugin themselves, changing subcommands is tricky

**Comment by CorruptedGreed** [comment]
Addressed through another method in next changelog
