### ISSUE TITLE
Neth armor disappeared off armor stand

### ISSUE THREAD

**Issue by AdelinW** [EarthMC/Issue-Tracker#1794]
### Server

Nova

### Describe the bug

I was editing a armor stand and then my neth sword and armor disappeared off it.My Mc user is Adelin_10 and pls give me my gear back

### To Reproduce

Idk really pls give me gear back

### Expected behavior

I expected that my armorstand was gonna do the ting I said it should to instead of eating my gear

**Comment by Fruitloopins** [comment]
don't think there's any way to check but it could have had curse of vanishing @AdelinW

**Comment by Fruitloopins** [comment]
you should make a ticket at discord.gg/EZBYmpp
