### ISSUE TITLE
Bedrock Glitch is Glitched

### ISSUE THREAD

**Issue by OOOO12345234** [EarthMC/Issue-Tracker#1795]
### Server

Aurora

### Describe the bug

I was trying to break some bedrock to make a hole however when I would try the piston would glitch and get half deleted, the tnt would have a massive delay and because of the piston glitching I couldnt break the bedrock.

### To Reproduce

Search up how to break bedrock on java 1.20 + and then follow the steps

### Expected behavior

I expected the bedrock beneath the piston to break

### Screenshots

![Screenshot 2024-04-01 160029](https://github.com/EarthMC/Issue-Tracker/assets/165630026/cc30f054-3142-4dad-a383-39f6ec83e47d)
![Screenshot 2024-04-01 160019](https://github.com/EarthMC/Issue-Tracker/assets/165630026/ffc0313e-0435-4168-b8d6-eb6c7860dca9)

**Comment by turtleexploding** [comment]
its a paper server it not meant to break
