### ISSUE TITLE
Issue with TNT Minecarts

### ISSUE THREAD

**Issue by twomoo1119** [EarthMC/Issue-Tracker#1797]
### Server

Aurora

### Describe the bug

Tnt minecarts do not regenerate terrain upon explosions like regular tnt do.

### To Reproduce

Place a tnt minecart and light it with an activator rail or cause it to explode by running several tnt minecarts into a block.

### Expected behavior

Terrain should regenerate like it does with regular tnt and creeper explosions.

### Screenshots

N/A

**Comment by Warriorrrr** [comment]
Fixed, end crystals seem like they also might've been missing
