### ISSUE TITLE
XP bottles doesn't work[Bug]

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1798]
### Server

Aurora

### Describe the bug

Since April 6th when the server was crashing when I use xp bottles to repair my mending tools it does nothing, no reparation and my level of xp doesn't go up either.

### To Reproduce

When you use xp bottles to repair mending tools it doesn't work.

### Expected behavior

The tools with mending should be repaired while you hold them and break xp bottles.

**Comment by Warriorrrr** [comment]
Unable to reproduce
