### ISSUE TITLE
[Issue] Make Bahamas oceans tropical ocean.

### ISSUE THREAD

**Issue by JoshsCode** [EarthMC/Issue-Tracker#180]
Could the oceans around the Bahamas be tropical and like in real life so it is the light blue color? Thanks would really appreciate it!

**Comment by PoppyK** [comment]
This is a duplicate.   @KarlOfDuty

**Comment by KarlOfDuty** [comment]
Duplicate.

**Comment by JoshsCode** [comment]
Well can this be dealt with then?
