### ISSUE TITLE
[Bug] XP bottles still not working

### ISSUE THREAD

**Issue by Ultraokasan** [EarthMC/Issue-Tracker#1801]
### Server

Aurora

### Describe the bug

As I reported at **Issue#1798** XP bottles looks bugged, this time i could make a video. As you can see i used a stack of XP bottles for a pickaxe with mending and at the beginning of the video they didn't work at all, and at the end you can see a little bit of reparation, but not the amount a stack should repair. I also tried it with no lag.

### To Reproduce

When you are going to repair a tool with mending using XP bottles the bottles seems bugged because them don't repair at all or very little.

### Expected behavior

- You hold the tool with mending with one hand and with the other you break the XP bottles.
- As you break the bottles the tool with mending get repaired.

### Screenshots

https://github.com/EarthMC/Issue-Tracker/assets/128364522/1b2da549-4a48-4f67-85b3-4d5a1c859b72

**Comment by Warriorrrr** [comment]
If you only store 1 xp in a bottle it will only repair 1 xp worth of durability, consider storing more in it
