### ISSUE TITLE
[Bug] Major Bug- Possible to overclaim a town's homeblock

### ISSUE THREAD

**Issue by nfish2021** [EarthMC/Issue-Tracker#1803]
### Server

Aurora

### Describe the bug

Today, I discovered that it was possible to overclaim a town's homeblock.

The town of Chicago was overclaimed today, and with it, it's homeblock, which to my understanding, should not be possible.

### To Reproduce

Not entirely sure how the overclaimer did it, but I'm assuming he just did it through the standard overclaim procedure.

### Expected behavior

It should not be possible to overclaim a town's homeblock, which I confirmed with a developer a few hours ago.

### Screenshots

![image](https://github.com/EarthMC/Issue-Tracker/assets/150664831/290b78db-80b4-46ca-8abd-a75be392118e)
The plot circled in red was the town's homeblock prior to the overclaim.

![image](https://github.com/EarthMC/Issue-Tracker/assets/150664831/557b5f53-331c-4c61-9dbe-badcb6bceb29)
This can be confirmed using the April 6th Wayback Machine page. Nobody in the town who has perms to move the homeblock has been on since April 1st, so this confirms the location of the homeblock prior to the overclaim.

![image](https://github.com/EarthMC/Issue-Tracker/assets/150664831/06fdde1a-897e-43ec-9993-2cd96a325789)
When attempting to `/n spawn illinois` or `/t spawn chicago`, you get errors that there is no spawn location.

**Comment by CorruptedGreed** [comment]
Addressed in next changelog
