### ISSUE TITLE
[Bug] Chest shop signs can be broken and collected.

### ISSUE THREAD

**Issue by SillyDuggo** [EarthMC/Issue-Tracker#1805]
### Server

Aurora

### Describe the bug

If you break a chest sign shop while crouching, the sign breaks and drops as a typical item. The shop is still functional without the sign. You can also destroy the chest to remove the old shop and put it in the same spot to create a new shop too.

### To Reproduce

I used a netherite efficiency five axe to break the sign. Crouch and hold left click on a chest shop sign to break it and it drops. 

### Expected behavior

I don't think the sign is supposed to be able to be broken.

### Additional context

I found this out about a year ago but only signed up for Github recently to download a Windows mod and decided to report now

**Comment by CorruptedGreed** [comment]
Don't see a way to prevent this
