### ISSUE TITLE
[Plugin] Vivecraft Extensions | Anti-Cheat Movement Conflict

### ISSUE THREAD

**Issue by JacobVanWie** [EarthMC/Issue-Tracker#1808]
### Is your feature request related to a problem? Please describe.

When joining using VR through [Vivecraft](https://www.vivecraft.org/), the player initially is able to move (wasd) until looking another direction physically, then the server essentially freezes the player in their spot. The rapid rubber banding behavior indicates to me that the movement packets being sent to the server are being 'rejected' by the anticheat. 

### Describe the solution you'd like

Two solutions may exist to this problem, however, I cannot guarantee that either one on their own may fix it,
- Option 1: The movement packets, at least the Anti-Cheat Event Trigger (or whatever they are called in that specific plugin) be identified and disabled. However, I think this could leave the door open for kill aura to go undetected; something that would have to be tested. Advantageously, the server does not have to be restarted to test this option, simply the anti-cheat reloaded.
- Option 2: This options would be preferred over all else, but could also benefit from option 1. The addition of the plugin [Vivecraft Spigot Extensions](https://www.vivecraft.org/downloads/) and [VivecraftVelocityExtensions](https://github.com/JLyne/VivecraftVelocityExtensions). Both the Server and Proxy plugin would allow for VR movement packets to be sent through the server allowing players with correctly modded clients to be able to see the VR player how they physically are. However, there could be conficts with the anti-cheat and this plugin in regards to movement. Something I cant predict the outcome of.

### Additional context

I am complexly willing to cooperate by joining in VR for testing. @tf_mc on discord

**Comment by Warriorrrr** [comment]
The way that the anticheat works is inherently incompatible with vivecraft, since players in VR do not move the same way that a vanilla player would, the only way that this could be fixed is by exempting VR players completely from the anticheat, which is not possible
