### ISSUE TITLE
[Plugin] Removing chat filter

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#181]
It is highly annoying when the chat filter goes on, because caps are a way to talk in a different way then normal. Over chat there is not much way of conveying your emotions, but caps are since it can differentiate yelling,being mad and happy. Also it doesn't really change anything through spam, it just makes the text a couple pixels larger and you could also spam in lower case and it'd be just as annoying.

Please remove the anti-caps feature of the chat plugin.

**Comment by Ultil0l** [comment]
^

**Comment by Pengun78** [comment]
yes its annoying

**Comment by KarlOfDuty** [comment]
Done.
