### ISSUE TITLE
Animal Stacking Plugin

### ISSUE THREAD

**Issue by Brody0727** [EarthMC/Issue-Tracker#1812]
### Is your feature request related to a problem? Please describe.

Recently, I tried to start up a cow farm in my town. However, throughout it, I discovered the bred cows were randomly despawning after barely any cows. I discovered it was for performance reasons, but the limits basically completely discourage any kind of animal farms whatsoever, especially considering how bad the server's performance and TPS are even with these.

### Describe the solution you'd like

My idea would be to use some kind of mob stacking plugin. It would allow you to be able to safely farm animals inside your borders, and would also reduce animal counts in chunks.
Example one:
https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance.29999/

**Comment by Aylywyn** [comment]
Is that plugin Folia-compliant ;-) ?

**Comment by Warriorrrr** [comment]
Mob stacking plugins are evil
