### ISSUE TITLE
Allied Nation Teleportation[Bug]

### ISSUE THREAD

**Issue by BreadCannon** [EarthMC/Issue-Tracker#1814]
### Server

Aurora

### Describe the bug

I have realized that if a player's nation is allied with a nation and they have a town that has /t toggle outsiderscanspawn on, the player will be unable to teleport to the town

### To Reproduce

1- Try to teleport to a town that has /t toggle outsiderscanspawn on and is allied with your nation

### Expected behavior

A player should be always able to teleport to any town as long as it has /t toggle outsiderscanspawn on and isn't in an enemy nation

**Comment by CorruptedGreed** [comment]
Fixed
