### ISSUE TITLE
[Bug] /trade does not work

### ISSUE THREAD

**Issue by limpoposex** [EarthMC/Issue-Tracker#1815]
### Server

Aurora

### Describe the bug

/trade does not work rn / disabled or something :(

### To Reproduce

uhh type /trade and it doesnt do anything

### Expected behavior

/trade (player name) opens trade gui and you can trade

### Screenshots

im too busy to add a screenshot

### Additional context

:(

**Comment by Warriorrrr** [comment]
This is known, it was disabled intentionally and will be brought back after it's fixed.
