### ISSUE TITLE
My gold crates dissapreared[Bug]

### ISSUE THREAD

**Issue by Nakis122** [EarthMC/Issue-Tracker#1817]
### Server

Aurora

### Describe the bug

I voted but had a full inventory , i said okay theyre gonna be in the echest BUT when i checked my echest it was full and i never got them 

### To Reproduce

vote with a full inventory and full e chest

### Expected behavior

i expect that a mod/staff gives me 2 gold crates

### Screenshots

![2024-06-15_09 02 53](https://github.com/EarthMC/Issue-Tracker/assets/172373198/b1b2f43c-2c5a-4328-baa4-4fc71234bc4e)
![2024-06-15_09 03 03](https://github.com/EarthMC/Issue-Tracker/assets/172373198/ac2d2649-17b9-4c4a-986c-091f7f4a31fd)

**Comment by CorruptedGreed** [comment]
Voting for crates is currently disabled, check out the announcement on Discord
