### ISSUE TITLE
[Bug] globalsoundevents left on after 1.20 upgrade

### ISSUE THREAD

**Issue by GalaxyGaming2000** [EarthMC/Issue-Tracker#1819]
### Server

Aurora

### Describe the bug

After the upgrade to 1.20 it seems globalsoundevents has been left on as people can hear wither spawning from any point in the world, I'm guessing this isn't intended as it can get quite annoying

### To Reproduce

Wait for a Global sound event to happen, ex. wither spawning

### Expected behavior

Global sound events to only be able to be heard when you are nearby.

**Comment by Warriorrrr** [comment]
The global sounds gamerule is off now
