### ISSUE TITLE
Nation Member Perms

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#182]
I'd like to see a difference between Ally and Nation member when it comes to perms. I'd be interested in having national chests/ doors for a grinder but I can only have it so all allies can access it. Just wondering if this is possible.

**Comment by KarlOfDuty** [comment]
This is sadly not possible and can't really be possible. The ally permission doesn't specifically mean nation allies, but everyone who is in your faction whether friend, town member, nation member or allied nation member. Towny would have to completely change their permission system to make this possible.
