### ISSUE TITLE
[Bug] Chat Closes if typing while tping long distances

### ISSUE THREAD

**Issue by GalaxyGaming2000** [EarthMC/Issue-Tracker#1821]
### Server

Aurora

### Describe the bug

Recently, it seems like tping long distances will close the chat when it never used to and also doesn't happen on other servers so my thought is something to do with folia is deleting your chat when you tp far.

so if you tp from Mali (nation) to Mali (town) chat will stay but if you tp from Pilbara (nation) to Mali (Nation OR Town) it will wipe your chat

### To Reproduce

Go to Point A (EX. Pilbara)
Go to another point that is far away from Point A maybe like 5k blocks? {Ex. Mali}
While tping begin typing.
you will see that the chat gets deleted.

### Expected behavior

Chat to stay while tping further away as it does when tping short distances.

**Comment by Veyronity** [comment]
yep, noticed that too. Weird

**Comment by 12bowl** [comment]
1.20.4 is known to wipe chat when changing worlds. It’s an issue Mojang fixes in later versions I believe. In this case, you aren’t changing worlds, but you are changing folia regions, so maybe it’s linked to that.

Maybe using the chat patches mod could fix the problem though, here it is:

https://modrinth.com/mod/chatpatches/version/204.6.2

**Comment by GalaxyGaming2000** [comment]
> 1.20.4 is known to wipe chat when changing worlds. It’s an issue Mojang fixes in later versions I believe. In this case, you aren’t changing worlds, but you are changing folia regions, so maybe it’s linked to that.
> 
> Maybe using the chat patches mod could fix the problem though, here it is:
> 
> https://modrinth.com/mod/chatpatches/version/204.6.2

wow that makes a lot of sense i knew it had something to do with worlds since one time i saw a loading screen for a split second anyhow i may close this now that a explanation has been made and well i doubt it would be fixed
