### ISSUE TITLE
[Bug] Towns are not deleted on new day.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1823]
### Server

Aurora

### Describe the bug

Since the 1.20.4 beta open on 2024/06/14, towns that all residents have not logged in for more than 42 days are not deleted on new day.

### To Reproduce

Check for towns scheduled to be deleted on new day. 
For a concrete example, check the Screenshots.

### Expected behavior

As in before 1.20.4 update, Towns are successfully deleted on new day as in the past..

### Screenshots

![2024-06-17_145838](https://github.com/EarthMC/Issue-Tracker/assets/92248609/a0719ab0-f97a-4f6f-b29a-00c580acd4af)
For example, this ShreksieVille town is scheduled to be deleted on 2024/06/11, but it still hasn't been deleted as of today (2024/06/17).

### Additional context

I'm not sure if this is a bug, or if it was intended setting while beta open period only, or if the deletion of residents' data has been extended from 42 days, but I would like some answers.

**Comment by Veyronity** [comment]
Purging was paused during downtime, and I believe beta too

**Comment by asyi0** [comment]
As the announcement said, I confirmed the resumption of the town's deletion on the last new day.
