### ISSUE TITLE
[Bug] EssentialsX motd is sent twice upon joining

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1824]
### Server

Aurora

### Describe the bug

Upon joining Aurora you get sent EssentialsX's motd twice
the motd is just links to the map, rules, discord, support, wiki etc. but still annoying to view it twice

### To Reproduce

log off
log back on

### Expected behavior

Send once

### Screenshots

<img width="317" alt="image" src="https://github.com/EarthMC/Issue-Tracker/assets/142887488/6c2beac5-f028-401c-acfa-05672c9af099">

**Comment by Warriorrrr** [comment]
Solved this one earlier, essentialsx on the folia branch was having all its listeners registered twice
