### ISSUE TITLE
Sign Dupe Glitch

### ISSUE THREAD

**Issue by pizzaguyy** [EarthMC/Issue-Tracker#1825]
### Server

Aurora

### Describe the bug

When you create a shop barrel/chest, you can crouch, break the sign, and pick it up. Then you can repeat this over and over

https://github.com/EarthMC/Issue-Tracker/assets/87299802/648bebbe-1889-4da3-8278-7e64e8f028c6

### To Reproduce

Place chest.
Punch chest with item you want to sell.
Once sign shows up, hold shift and break it.
When sign drops, pick it up.

### Expected behavior

i was kinda just trying to break the shop chest as a whole

### Additional context

the sign economy will crash because of this (very bad)

**Comment by jkmartindale** [comment]
#1136 #1416 #1654 #1748 #1805

**Comment by CorruptedGreed** [comment]
The sign economy has been through worse

**Comment by pizzaguyy** [comment]
the sign economy will fail from this
