### ISSUE TITLE
I am stuck

### ISSUE THREAD

**Issue by LightningB0LT1** [EarthMC/Issue-Tracker#1827]
### Describe the issue

I fell into someone's hole with no way of getting out, I have tried everything. I can't even starve because there is a regeneration becon. My username is Thelightningb0lt.

### Coordinates

20545 75 -7053

### Screenshots

![2024-06-20_18 42 49](https://github.com/EarthMC/Issue-Tracker/assets/87983696/da95db01-60e9-4468-841d-117f1621c19b)

**Comment by jwkerr** [comment]
you can join a town and teleport with /t spawn or /n spawn, or you can write /suicide

**Comment by jwkerr** [comment]
next time use discord.gg/EZBYmpp for support issues like this

**Comment by Veyronity** [comment]
1. how did bro not die from a fall that big?
2. arent there wither roses there
3. how did he just assign this to Poppy

**Comment by jkmartindale** [comment]
world issue template assigns to poppy
