### ISSUE TITLE
Sitting plugin broke :/ [Bug]

### ISSUE THREAD

**Issue by MagicZel** [EarthMC/Issue-Tracker#1833]
### Server

Aurora

### Describe the bug

Essentially, You just sit too low, not like the old one... it just bothers me... and ruins all... please fixy :(

### To Reproduce

Right click a stair to sit in it, and then you sit inside the stair case

### Expected behavior

Sitting on the stair case

### Screenshots

![2024-06-15_21 05 00](https://github.com/EarthMC/Issue-Tracker/assets/174160179/ddb42b6c-87d1-477b-bf73-1a184df5100f)

### Additional context

Amongus?

**Comment by jkmartindale** [comment]
Critical severity bug

**Comment by CorruptedGreed** [comment]
Sitting a bit low in the chair isn't a development priority, but will probably look into it eventually in the future
