### ISSUE TITLE
[Bug] new hopper filter not working

### ISSUE THREAD

**Issue by GodzillaHawkMama** [EarthMC/Issue-Tracker#1835]
### Server

Aurora

### Describe the bug

I renamed three hoppers:
 Feather 
*Feather*
Feathers
Placed each on top of a barrel and placed a barrel on top of each hopper.
Placed random items and feathers in top barrels and all items filtered to the bottom barrel.

### To Reproduce

Rename a hopper to filter an item.

### Expected behavior

I expected renamed hopper to only allow feathers to move to Bottom barrel.

### Additional context

I even tried using a newly crafted hopper.

**Comment by CorruptedGreed** [comment]
Should be fixed now
