### ISSUE TITLE
[Major Bug] Quickshop Signs Can be broken by anyone even if they do not have perms.

### ISSUE THREAD

**Issue by GalaxyGaming2000** [EarthMC/Issue-Tracker#1838]
### Server

Aurora

### Describe the bug

When crouching with a axe you can break a quickshop chest in any town and the sign on it will disappear permanently,
you dont have to have any sort of perms and it takes little effort.

### To Reproduce

Get An Axe, (Eff 5 in my case)
Crouch And Break The Quickshop chest with the sign on it in a town you dont have perms in
you will see the sign goes away permanently and the quickshop no longer functions 

### Expected behavior

Everyone besides you and people to be not allowed to break quickshop signs

**Comment by jkmartindale** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/1136 https://github.com/EarthMC/Issue-Tracker/issues/1416 https://github.com/EarthMC/Issue-Tracker/issues/1654 https://github.com/EarthMC/Issue-Tracker/issues/1748 https://github.com/EarthMC/Issue-Tracker/issues/1805 #1825

**Comment by GalaxyGaming2000** [comment]
> #1136 #1416 #1654 #1748 #1805 #1825

its not the sign dupe its a different bug

**Comment by CorruptedGreed** [comment]
Resolved in previous changelog
