### ISSUE TITLE
[Bug] Teleporting to towns, nations or homes isn't working

### ISSUE THREAD

**Issue by UnitiveBog10934** [EarthMC/Issue-Tracker#1839]
### Server

Aurora

### Describe the bug

Any sort of teleportation through towny appears to be broken (/t spawn, /n spawn, /home). 
When running the command, it will say it's teleporting you. but it won't. 
No particles appear when running the command either. 

### To Reproduce

Try doing /t spawn, /n spawn or /home. 

### Expected behavior

To be teleported

**Comment by CorruptedGreed** [comment]
Fixed
