### ISSUE TITLE
Quarters being reseted

### ISSUE THREAD

**Issue by BowmanzxD** [EarthMC/Issue-Tracker#1840]
### Server

Aurora

### Describe the bug

After I had logged in, I realised the quarter I had owned before has got reseted. It still exists but I wasn't the owner anymore. Mayor gave me it back, but a few days later the same issue happened.

### To Reproduce

You should probably do the same steps I did.

### Expected behavior

I expect the bug to be fixed.

**Comment by jwkerr** [comment]
quarter were resetting due to server crashes related to folia lag
