### ISSUE TITLE
/plot perm gui [Bug]

### ISSUE THREAD

**Issue by JR1258** [EarthMC/Issue-Tracker#1843]
### Server

Aurora

### Describe the bug

/plot perm gui not working and it gives you the "not compatible with folia" issue

### To Reproduce

/plot perm gui and click add player

### Expected behavior

Gives you the issue msg in chat

### Screenshots

<img width="444" alt="Bildschirmfoto 2024-07-07 um 23 04 42" src="https://github.com/EarthMC/Issue-Tracker/assets/113603723/5552cafc-d9a9-4d74-87cd-678569f22b9b">

**Comment by CorruptedGreed** [comment]
It will eventually be fixed once Towny adopts some packet-based scoreboard system, given you cannot use scoreboards on Folia due to running on main thread.
