### ISSUE TITLE
[Bug] Hoppers can not pull items from shop chest.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1844]
### Server

Aurora

### Describe the bug

Hoppers can not pull items from shop chest.

### To Reproduce

1. put a chest and put a hopper below.
2. make shop at the chest.
3. put items in the chest.

### Expected behavior

The hopper pull items in the chest.

### Screenshots

https://github.com/EarthMC/Issue-Tracker/assets/92248609/548e5b77-d73c-4b64-8ff1-0f966b26c74c

### Additional context

I think this started happening after the filter hopper was added.

**Comment by Veyronity** [comment]
This is not a bug. It's quickshop's safety system against theft, similar to shop locking against SWITCH, it has protection against explosions and hoppers. I'm surprised you even could place a hopper under it :)

**Comment by Veyronity** [comment]
What I said is simply what Fruit did. The event was disabled and now it's back, so.... idk @jwkerr

**Comment by CorruptedGreed** [comment]
The configuration enabled is necessary for HopperFilter to work. The only alternative to fixing this would be turning off QuickShop protections, which we would not want to do. As a result this is no longer intended behavior.
