### ISSUE TITLE
[Bug] Buying potions shop chest is not working properly.

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1846]
### Server

Aurora

### Describe the bug

The count of potions at a buying shop chest is incorrect. 
This shop chest can buy even when the chest is full.
If I sell potions to full chest, the potion will disappear.
This bug has been occurring since the shop plugin update which allows up to 27 potions to be sold for once.

### To Reproduce

1. Make buying shop chest that buy potions.
2. Sell potions to it and full up the chest.
3. Sell more potions and potions will disappear.

### Expected behavior

When the shop chest has not enough space, no one can sell potions there.

### Screenshots

https://github.com/user-attachments/assets/a89d614c-f80a-4ed9-9a09-a29dba42e5a2

I sold 27x Haste potions to the shop chest that has 26 slots, and 1 potion disappeared.

### Additional context

It is repost of #1562 that has closed.
It was fixed once in Quickshop-Hikari, but eventually the shop plugin backed to Quickshop-Reremake, so this issue still exists.

**Comment by CorruptedGreed** [comment]
This is currently an unfixable limitation noted in the [changelog](https://discord.com/channels/219863747248914433/988199791429320724/1201327255993982986) for Reremake.
