### ISSUE TITLE
Special abilities cooldown resets when relogging

### ISSUE THREAD

**Issue by Leonicomil** [EarthMC/Issue-Tracker#1847]
### Server

Aurora

### Describe the bug

Towny's special abilities timer resets when I leave and rejoin the server, allowing me to use them as many times as I wish.

### To Reproduce

Active any special abililties, in my case, it was super breaker. Use it until it expires and then log off and back on. You will be able to use the ability once again.

### Expected behavior

The timer should pause until you log back on, or keep ticking while you're offline

**Comment by CorruptedGreed** [comment]
Updated to mcMMO's fix for this
