### ISSUE TITLE
[Bug] Mapcolor gives "no permission"

### ISSUE THREAD

**Issue by cyberpro-dev** [EarthMC/Issue-Tracker#1849]
### Server

Aurora

### Describe the bug

When I execute /n set mapcolor green it says "No permission"mission"

I am a nation leader and have premium

### To Reproduce

1. Be a nation leader and have premium
2. Execute /n set mapcolor green

### Expected behavior

That it sdays it has been successfully done and takes effect on the map.

### Screenshots

![image_2024-07-15_211512099](https://github.com/user-attachments/assets/e8218e20-36b3-4e8c-9891-95c0a8787c29)

### Additional context

Mods said it is because of Squaremap but said I can let the devs know.

![image](https://github.com/user-attachments/assets/1dac04c4-5268-42fe-9bb9-9425ed654bcc)

**Comment by Veyronity** [comment]
Not a bug. They will make the new map compatible with the emcmap plugin/addon

**Comment by CorruptedGreed** [comment]
Use `/emcmap`
