### ISSUE TITLE
[Bug] Spawn Protection can be bypassed when travelling with Ender Pearl

### ISSUE THREAD

**Issue by wizjanef** [EarthMC/Issue-Tracker#1851]
### Server

Aurora

### Describe the bug

You can bypass the 7 chunk spawn protection limit by using Ender Pearl to travel between chunks ( to keep up infinite spawn protection )

### To Reproduce

- Spawn somewhere
- Use Ender Pearl to move

### Expected behavior

Travelling with Ender Pearl should not be abusable to keep up infinite spawn protection

**Comment by Warriorrrr** [comment]
Relates to https://github.com/EarthMC/Issue-Tracker/issues/1856, should not be a problem anymore now that teleport events work again.
