### ISSUE TITLE
[Bug] Classic and Nova cannot be accessed

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#1853]
### Server

Nova

### Describe the bug

Most importantly, since a few months ago you can't access Classic and Nova worlds as a spectator. Queue to Nova is paused, whereby on Classic it never sends an user. Edit: I understand that Nova may be not ready yet, but make it work for Classic
Secondly, update GitHub issue template and remove Nova from server prompt because it has been shut down.

### To Reproduce

Try to /joinqueue (either nova or classic)

### Expected behavior

You would be sent to both servers as a spectator

**Comment by GalaxyGaming2000** [comment]
Nova shut down, idk about classic tho

**Comment by 3meraldK** [comment]
> Nova shut down, idk about classic tho

They both should be spectatable, like Classic (was)

**Comment by ltown1** [comment]
> man, they are really reading these bug reports

they sure are

**Comment by CorruptedGreed** [comment]
They may eventually come back up pending whatever Fix wants to do with them
