### ISSUE TITLE
[Bug] Grammar Mistake In a towny message.

### ISSUE THREAD

**Issue by GalaxyGaming2000** [EarthMC/Issue-Tracker#1855]
### Server

Aurora

### Describe the bug

so basically i was outlawed overnight and well i did /n spawn (town i was outlawed in) and the message read:

"[Towny] You could not teleport to 2.1IncorrectName as they **has** outlawed you"

And well, that doesn't make too much sense its not a huge issue but i thought i would report this bug anyway

### To Reproduce

Be outlawed in a nations capital (or a normal town maybe i haven't tested that)
try to tp to the nation that the capital is in
observe the message

### Expected behavior

The message to instead say:

"[Towny] You cannot teleport to 2.1IncorrectName as they **have** outlawed you"

### Screenshots

![image](https://github.com/user-attachments/assets/1edd3832-ae98-4797-a4af-358048b5bff8)

**Comment by Warriorrrr** [comment]
https://github.com/jwkerr/TownyCommandAddons/blob/81803885835aaa042f565ddbd37746516b11ba1b/src/main/java/net/earthmc/townycommandaddons/listener/TownySpawnListener.java#L23
