### ISSUE TITLE
[Bug] Ender pearls are available without item use perm

### ISSUE THREAD

**Issue by asyi0** [EarthMC/Issue-Tracker#1856]
### Server

Aurora

### Describe the bug

Ender pearls are available without item use perm.
It was not possible at the time of 1.19, but seems to have been available since the 1.20 update.

### To Reproduce

Throw ender pearl to plots you don't have item use perm from plots you don't have item use perm.

### Expected behavior

Ender pearl not works and show error message.

### Screenshots

https://github.com/user-attachments/assets/2f510110-3dd7-4bc8-9823-c3b3d976d993

### Additional context

It makes it difficult to safely create a casino or a limited area where only those with perm can pass.
It could also allow people to pass through walls in areas where there is no perm.

**Comment by Warriorrrr** [comment]
This was fixed around august 17, the cause was that the teleport event was not implemented yet.
