### ISSUE TITLE
[Plugin] Unable to show the namelist in /plot trust remove (Name)

### ISSUE THREAD

**Issue by Minemetero** [EarthMC/Issue-Tracker#1861]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I forget who did I trusted in this plot.

### Describe the solution you'd like

![image_2024-08-19_114738750](https://github.com/user-attachments/assets/51a06295-2165-407a-852c-dd8f6c14b291)
It shows the people I give trust to.
But in /plot trust remove
![image_2024-08-19_114838081](https://github.com/user-attachments/assets/ad741d2b-b7d7-48d7-bde1-9c9d0d847536)
It shows everyone, and then I don't know who did I trusted.

### Additional context

Better fix it soon; it's's too annoying.

**Comment by Warriorrrr** [comment]
Will be included in the next towny update
