### ISSUE TITLE
[Bug] Mystery Can't be placed in one specific spot in ender chests

### ISSUE THREAD

**Issue by Veyronity** [EarthMC/Issue-Tracker#1862]
### Server

Aurora

### Describe the bug

for some reason, Mystery crates can not be placed in E5 (in double ender chests obviously)
basically middle column, 2nd row from bottom

only mystery crates. items, other heads, can be put fine. crates just are picked up/put back on my mouse tracker

### To Reproduce

summon some crates
open double enderchest
try to put it

### Expected behavior

they should stay

### Screenshots

![image](https://github.com/user-attachments/assets/632cc066-ace5-4d81-9499-21f2622aea1f)

**Comment by Warriorrrr** [comment]
The crate plugin prevents you from putting crates in your offhand, and the slot number for your offhand just so happened to match that slot in a double chest.
