### ISSUE TITLE
/t takeoverclaim chunk limit staying after next towny day

### ISSUE THREAD

**Issue by K1kimor** [EarthMC/Issue-Tracker#1863]
### Server

Aurora

### Describe the bug

There's a chunk limit on overclaims, 24 chunks. This limit should reset every towny day, as CorruptedGreed said. But when you try to overclaim chunks the next day, it says: "Could not overclaim this plot as your town has no remaining overclaims today". Even after 2 towny days, the issue is still there.

### To Reproduce

1. Overclaim 24 chunks
2. Wait for the next towny day
3. The overclaim limit is still there

### Expected behavior

We expected the chunk limit to reset to overclaim the next 24 chunks.

### Screenshots

![image](https://github.com/user-attachments/assets/67d88006-3d74-4f43-abf3-177b4f358aa9)

### Additional context

P.S. This issue is already present for 2 players: me (K1kimor) and MattieMirakel

**Comment by CorruptedGreed** [comment]
The conflicting issue that caused this should be resolved.
