### ISSUE TITLE
[Bug] Low TPS drastically increases Super Breaker 

### ISSUE THREAD

**Issue by Duck5goQuack** [EarthMC/Issue-Tracker#1865]
### Server

Aurora

### Describe the bug

When the TPS is low (feather estimated it to be around 12) when super breaker is activated, it lasts significantly longer than it should otherwise last

### To Reproduce

Check what the TPS is, if it is relatively low activate super breaker and time how long it lasts

### Expected behavior

Super Breaker shouldn't last near as long

**Comment by Veyronity** [comment]
Not a bug. it's how the server works. mcMMO gives you X "seconds" depending on your level, but there are no such thing as seconds in minecraft, so in reality it's ticks. if you get 30 seconds of superbreaker, that means 600 ticks. when TPS is 20, that's a normal 30 seconds. when TPS is 10, it'll take 60 seconds to go through all 600 ticks. basic math.


90% sure

**Comment by CorruptedGreed** [comment]
What Veyron said here explains it, not a bug we would be able to resolve
