### ISSUE TITLE
I voted and no chest

### ISSUE THREAD

**Issue by yenbozo** [EarthMC/Issue-Tracker#1868]
### Server

Aurora

### Describe the bug

"I voted as one dose of gold for the case. I double-checked to ensure my vote was correct, but I received nothing. I checked my inventory, and there's nothing there

### To Reproduce

"I did not get any gold from voting. ???"

### Expected behavior

"Well, I expected to get gold from voting, but I didn’t."

**Comment by ltown1** [comment]
have you checked your enderchest and if that doesn't work do `/cr claim`
