### ISSUE TITLE
Head name bug

### ISSUE THREAD

**Issue by Ko-ha-ru** [EarthMC/Issue-Tracker#1869]
### Server

Aurora

### Describe the bug

The names of the heads I had put before had been changed to " Head Database's Head" or "Player Head".

If you break the head you previously placed, it will be renamed to "Head Database's Head" or "Player Head".
It happened suddenly that I don't remember the details.

### Expected behavior

I want my heads back to their original names.

**Comment by Warriorrrr** [comment]
Was this head placed for a longer time? I can't reproduce this when breaking a freshly placed head

**Comment by Veyronity** [comment]
It was a bug temporarily, pretty sure it's fixed now

I would say it was there for a week max

**Comment by CorruptedGreed** [comment]
Does not seem to happen anymore
