### ISSUE TITLE
[Feature], [Mechanic] Mcmmo Salvaging

### ISSUE THREAD

**Issue by Stilpo** [EarthMC/Issue-Tracker#187]
The problem that we have with salvaging atm is that NOTHING can be salvaged at all. From leather items all the way to higher end items like diamond items. Before double smelt and salvaging were disabled, no matter what the damage value of the item was (1 durability - full durability) it will only drop 1 of that material. Normally if you get salvaging high enough it would eventually drop a full *refund* of what it took to make the item. AKA swords would drop 2 mats(if full durability) and axes/picks would drop 3 mats(if full durability). The problem with having salvaging completely disabled would make it so people can't even salvage the things they fish rendering fishing practically useless or people would just be throwing things such as leather armor away instead of being able to salvage it for leather (books) 
I feel a fix to this issue would be to reenable salvaging to was it was before because the system that was used before only dropped 1 of that material so it wouldn't be quite a viable way to get certain goods but still allows one to get rid of some of the tools and armor that they might pick up from fishing or other means.

**Comment by Arganog** [comment]
I think it would be great to have Mcmmo salvage fully functional for all items that don't give gold, if possible (don't want this to turn into a massive salvage-arms race like a factions server to generate gold), I don't think it negatively affects anything for all of the other resources to be salvage-able

So the question is whether or not it is possible to have salvage for all items excluding gold?

**Comment by KarlOfDuty** [comment]
We are not exactly sure why it wasn't working properly in the first place so it may just be broken in 1.13.

In any case if it is possible we will very likely restore all currently deactivated mcmmo skills with their gold duping components excluded (except those that can be used to greif towny protected areas). 

Neither Fix or I have had time to work on the server since the economy plugin issues so it will have to wait until we have time to have a scheduled maintenance period though.

**Comment by Stilpo** [comment]
There shouldn't be something that conflicts with the plugin for 1.13 as i've done some tests. Might have slight conflict with some of the other plugins that might be causing some problems. Just would love to see this ability back up and running so i can clear some of my chests up.

**Comment by KarlOfDuty** [comment]
Done.
