### ISSUE TITLE
[Bug] Item Lore date is stuck on 2024-09-24

### ISSUE THREAD

**Issue by Proserrr** [EarthMC/Issue-Tracker#1876]
### Server

Aurora

### Describe the bug

All itemlore eligible items created display the date crafted as 2024-09-24 even if the tool was created since.

### To Reproduce

Make a tool or a piece of armour

### Expected behavior

The lore to display the correct date the item was created 

### Screenshots

![2024-09-28_02 43 12](https://github.com/user-attachments/assets/e8fb11fa-6b63-4c87-b910-a5037ae77bdf)
This image shows a pickaxe I crafted today, 28 Sept 24. As you can see the date is incorrect.

**Comment by Veyronity** [comment]
![image](https://github.com/user-attachments/assets/6f6a3193-6f3f-48a1-953d-722b050089d3)
Don't think it's an issue anymore @Proserrr

**Comment by Warriorrrr** [comment]
The date was stuck to the day the server started, now fixed (pending plugin update)
