### ISSUE TITLE
Sometimes on earthmc you cant use your mcmmo ability 

### ISSUE THREAD

**Issue by AdelinW** [EarthMC/Issue-Tracker#1885]
### Server

Aurora

### Describe the bug

When I want to use the mcmmo abilities,  like super breaker, I can't do that, I don't get the message "you ready your pickaxe"

### To Reproduce

Fix it i think?

### Expected behavior

I expect this bug to be fixed

**Comment by CorruptedGreed** [comment]
Should not happen regularly outside of lag, feel free to open a ticket if this is personally happening to you continuously.
