### ISSUE TITLE
[Bug] Players can warp during combat when using /warps instead of /warp

### ISSUE THREAD

**Issue by GalaxyGaming2000** [EarthMC/Issue-Tracker#1886]
### Server

Aurora

### Describe the bug

When you are combat tagged you arent able to use /warp [Name] right? thats a good thing, the thing is if you change it to /warps [Name] that limitation no longer applies

### To Reproduce

1. Get Combat Tagged
2. Use /warps instead of /warp (/warps Parkour for example)
3. Wait 3 Seconds to be tped

### Expected behavior

/warps to be blocked during combat like /warp is.

**Comment by CorruptedGreed** [comment]
This should be fixed now, thanks for your report.
