### ISSUE TITLE
[Bug] can't remove entity banners

### ISSUE THREAD

**Issue by alphawolffurry** [EarthMC/Issue-Tracker#1888]
### Server

Aurora

### Describe the bug

so when we couldn't place banners we had a entity banner
and I CAN'T REMOVE IT

### To Reproduce

if you placd a banner a few weeks ago you got a entity

### Expected behavior

break

**Comment by CorruptedGreed** [comment]
You should be able to remove them now. Any banners from almost a year ago you would have to make a ticket on the Support Discord for.
