### ISSUE TITLE
Make Terra Nova more like how classic was

### ISSUE THREAD

**Issue by lucasw2011** [EarthMC/Issue-Tracker#189]
I had a lot of faith in emc classic unfortunately it was cut short by the staff announcing terra nova. Now that terra nova is here we are experiencing all these new play styles the staff want us to play by. When on the last server you could be free to do what you want when you want. If you were in Antarctica you could be in the same nation as a town in China. You could tp to someone or anllied town. Empires could rule vast areas successfully. You could mine 1 or 2 gold from one ore then smelt it into more. Now you can’t find gold unless you waste hours looking. All because the staff wanted less nations well if you look at the map that idea failed. And now they’ve taken doublesmelt away. Now how are towns suppose to grow? On the last map you could get 12 gold from voting now you only get 10. Anyway it’s more expensive to build nations with a claim cap and harder to get gold. Where is this server going? And how long can it last?

**Comment by lucasw2011** [comment]
I believe if a emc copy server that has what emc classic had comes along it will take business away from terra nova

**Comment by KarlOfDuty** [comment]
You will have to be more specific with whet exactly you want to be changed and you need to put different things in different issues.
