### ISSUE TITLE
Refund towny claims

### ISSUE THREAD

**Issue by SwoopLBP** [EarthMC/Issue-Tracker#190]
Ever since I started playing Earthmc I normally claimed an area that I end up not needing or using , however its  a real waste to unclaim land which is why I never do.

My idea is that Earthmc should refund at least half the gold you spent on a claim when unclaiming (8g) , this would give people an incentive to have a town where they want it to be making them more active and increasing positivity (people make mistakes) , also if someone has claimed in the way of someone or has to remove land in negotiations after a war , they have an incentive to do so. Furthermore , if possible you could make it so they have a set amount of 'free' / refunded claims on their player data which they can use to claim elsewhere or make a new town. This would prevent a giant town from refunding all claims and causing mega inflation.

**Comment by BowShot118** [comment]
I like the counter balance to large towns unclaiming and dumping their money into the eco

**Comment by Arganog** [comment]
Could you explain more what you mean by that BowShot118?

**Comment by KarlOfDuty** [comment]
Right now this is not possible as far as I know.

**Comment by KarlOfDuty** [comment]
Also, duplicate of #126
