### ISSUE TITLE
Armor stand issue

### ISSUE THREAD

**Issue by Envn** [EarthMC/Issue-Tracker#1903]
### Server

Nova

### Describe the bug

When i wanted to change the equipment of my armor stand with the “edit equipment” option it just made everything on the armor stand disappear, the head- the armor- the item on its hand- all gone, i wonder where it gone? i tried on both to make sure it wasnt just lag or a one time thing.

### To Reproduce

Use blazerod, click the “edit equipment” which should be a chest, click the armor stand, it will show a menu, then the armor/head/item on the armor stand just disappears

### Expected behavior

the armorstand shouldve been editable there but all its items will just vanish

**Comment by Nicky-Who** [comment]
![image](https://github.com/user-attachments/assets/ce2ca3b6-c13c-41ad-9271-1ce64a7b99d2)
I had the same issue, went to put an item in the hand slot, armour and the head vanished.
