### ISSUE TITLE
[Bug] Void

### ISSUE THREAD

**Issue by Monke6978** [EarthMC/Issue-Tracker#1912]
### Server

Nova

### Describe the bug

Every time i join the game i spawn in the void and but wont die i would even go to "y -5000" not even chat would work

### To Reproduce

I have no clue

### Expected behavior

I expect to spawn in my town

### Screenshots

![Screenshot 2024-12-17 193633](https://github.com/user-attachments/assets/22634258-6153-4bfc-a535-291d58bc5cf4)

**Comment by jwkerr** [comment]
Does it disconnect you after this?

**Comment by Monke6978** [comment]
no i stay ingame the whole time

**Comment by jwkerr** [comment]
What is your username?

**Comment by Monke6978** [comment]
Mr_Dough_Inc

**Comment by jwkerr** [comment]
![image](https://github.com/user-attachments/assets/496c801d-8a4e-4623-8fd5-22ae73974499)
It's definitely a lag thing, I would recommend you try downgrading to 1.20.4, the server's native version, then if that doesn't work open a ticket at https://discord.gg/EZBYmpp and ping me about a possible next solution.

**Comment by Monke6978** [comment]
. you know that makes sense now
