### ISSUE TITLE
[Bug] No witherskeleton spawns in netherfortesses.

### ISSUE THREAD

**Issue by BennyBurst** [EarthMC/Issue-Tracker#192]
Describe the issue
I have now for days been trying to get more witherskeleton skulls. Every time I goto  nether, there is less than 40 ppl online.
I get no spawns inside the fortress. Even if i kill all surrounding mobs (pigzombie, ghast, magma etc)
There is also not spawning any blaze or magmacube inside the fortress.
I have tried multiple fortesses, but no spawns. Only pigzombie and ghast around the fortress.

At 24. of Nov. Karl opened the server for testing for a short amount of time, to see if the economy was fixed. At that point there was atleast 100 players online, but i got spawns in nether.
Whatever i got that day, was rollbacked because of the economy.
Monday 26. i reported this in a ticket, the day after the server came back up from the downtime because of the economy issues. 24-25 Nov.

That was the last time i saw a witherskeleton.
This is a very fustrating problem, because when i asked karl for help. i found another bug (pigzombie dropping gold) and disabled that instead.

![karlofduty](https://user-images.githubusercontent.com/45021967/49239821-fa868800-f403-11e8-91ac-2ec9dcd972b6.png)

**Comment by KarlOfDuty** [comment]
I haven't done any mobspawn stuff so I don't know anything about that.

**Comment by KarlOfDuty** [comment]
Does this issue still exist?

**Comment by KarlOfDuty** [comment]
Closed due to inactivity.

**Comment by ciel0beats** [comment]
YO BENNY ADD ME IN DISCORD skylimits#8954

i want to join your nation (hawaii) im located at honolulu.
If you are leaving the server i could take care of the nation! Please reply! I tried contacting you everywhere but failed

**Comment by ciel0beats** [comment]
Dont let hawaii fall into ruins :(.

My in game name in earthmc is ciel0beats
