### ISSUE TITLE
[Mechanic] KeepInventory should be disabled.

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#194]
It is very annoying how keepInventory is enabled. There is not too much lag and it really effects gameplay to have it turned off. There are many wars that are full fledged wars for instance the British Norwegian War and the Norwegian Civil War. And killing people is useless because you can't get their stuff, which results in having to fight wars in a very hard war for instance killing their animals and other means. Personally I would want most war to be fought with regular pvp player vs player, but since the war system is so broken where you can't even get their items if you kill them you have you fight in dirty ways. Also the reason why end crystals were so popular before is because people would hide in claims and if they did so there was nothing you could do even though you were at war.

Please disable keepInventory and get a plugin which allows for in depth and good wars.

**Comment by KarlOfDuty** [comment]
The server literally just crashed and sent players into the void.

**Comment by Magenent** [comment]
> The server literally just crashed and sent players into the void. Edit: It didn't actually die completely nvm, but same effect still.

Maybe a plugin where keepInventory gets disabled for you if you are combat tagged?

**Comment by 4noah18** [comment]
Yeah keep inventory should be turned off... Right now there's no consequences for anything

**Comment by MineHero43** [comment]
I think it's been enabled for quite sometime and like Mag said, I think a combat tag plugin would be beneficial. It would mean that you only actually lose your items if in combat with another player.

**Comment by Ultil0l** [comment]
combat tag would only produce more lag tbh

**Comment by TypicalFernie** [comment]
yes that sounds hawt

**Comment by Pengun78** [comment]
it should be like if you're fighting in claims you dont drop stuff but if you're fighting in the wilderniss you drop your stuff

**Comment by Magenent** [comment]
No, because thats stupid if you can already hide in claims if you die in claims you should still drop your stuff.

**Comment by Magenent** [comment]
> Keep inventory only for when you die outside of PVP
> 
> Getting killed by another player = inventory dropped

Arg I think it should be if you get combat tagged, cuz you could just /suicide and it wouldn't count, maybe /suicide would also drop your items but tbh i think it should just be if you get combat tagged but they should also add it so if you log out in pvp then you drop your items.

**Comment by IGNSlaid** [comment]
gae, it should drop your items everytime, stop this bullshit!!!!

**Comment by Arganog** [comment]
I agree Mag
I don't have fond memories of the combat logging plugin we tested in beta.. it tagged you as "in combat" for almost any type of damage

If we can configure a plugin so that it only combat tags you when you are attacked by another player and during that time your keep inventory is off, then that would be better

**Comment by Magenent** [comment]
> The server literally just crashed and sent players into the void. Edit: It didn't actually die completely nvm, but same effect still.

tbh its not that laggy now maybe just make it so if someone is killed then they drop their items but pls make a quick patch

**Comment by Pengun78** [comment]
Keepinv dont leave me

**Comment by BowShot118** [comment]
I don't think the server is stable enough during peak times to disable it as of now.

**Comment by KarlOfDuty** [comment]
Done.
