### ISSUE TITLE
[Plugin] Towny dynamic invite range plugin idea

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/Issue-Tracker#195]
Here is my idea for a new plugin:

Nations start with a small invite radius, this radius emanates from all towns in the nation. 

As nations get bigger their radius grows, maybe also when towns get bigger their individual range grows. 

I think this could stop the randomly inviting someone on the other side of a continent while still being able to add them if your nation actually stretches that long.

**Comment by Dan1804** [comment]
I agree, some of the empires had some musch land that the sun would never set on the empire. Britain is a good example.

**Comment by BowShot118** [comment]
I back the larger nation = larger raduis thing.

**Comment by JoshsCode** [comment]
I like it! Means we could have US towns all over modern US!

**Comment by sharkfynn1012** [comment]
...great, now we propose it :/ after Wabanaki works hard to find a way around the system.

**Comment by fettered** [comment]
Something has to be added, glorious China cannot properly unify until this is fixed. This rule was not put in place with nations such as China in mind, it hampers our growth, and saddens our followers.

**Comment by SoyGalletita** [comment]
I totally support this idea. The radius should be smaller than the actual one (about 1,500 blocks) and it should emanate from all the towns. 

There are many examples of nations that couldn't add towns that obviously belong to them (such as Fortaleza, Brazil; Arica, La Plata; Perth, Australia; Anchorage, United States; Siberia, Russia) and nations that have split into many such as the United States or China. This is not an issue for most european nations, though.

I believe if a town leaves the nation, the radius should automatically get smaller and kick the other towns out of the nation: so we stop people claiming towns and disbanding them until they reach certain point on the map. This also helps the idea that the regions with most towns in a nation will be the least likely to be disbanded, creating densely populated regions where towns are most important to the nation and having a geographical impact on the map.

I don't back this solution for huge empires taking over the whole world, but for a more realistic approach on nations and their base in real life world when nations might be thin and long stretches like Chile or big continents like Australia that cannot be made with the current circle-nation system.

I'll be waiting to see more news about this topic.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by jkmartindale** [comment]
when shiraz goes sicko mode on karl 👀

**Comment by 10op10** [comment]
> when shiraz goes sicko mode on karl 👀

Lmfaoo

**Comment by Pengun78** [comment]
> > when shiraz goes sicko mode on karl 👀
> 
> Lmfaoo

Lmfaoo
