### ISSUE TITLE
[Feature] Marriage Plugin

### ISSUE THREAD

**Issue by MSatrokrm** [EarthMC/Issue-Tracker#197]
It is pretty self-explanatory.

I believe that a marriage plugin would benefit this server.

**Comment by Synargle** [comment]
This would be the only truly important plugin.

**Comment by BowShot118** [comment]
> This would be the only truly important plugin.

If Syn says so, I do to.

**Comment by RoJoGuapo** [comment]
It doesn't really make the game better or worse, and it's just another plug in to burden the server with lag.

**Comment by shirazmatas** [comment]
@FixTheAdmin ❤️

**Comment by Ultil0l** [comment]
@RoJoGuapo go commit not talking

**Comment by RoJoGuapo** [comment]
@Ultil0l Eat my Ass

**Comment by Ultil0l** [comment]
thats not very christian of you right there

**Comment by IGNSlaid** [comment]
stop dating gamer girls

**Comment by Ultil0l** [comment]
I am trying to harvest their pee

**Comment by Pengun78** [comment]
Dont you dare adding this it will turn emc in one of these cringy roleplay servers where people marry a 30 year old

**Comment by Coffeetom** [comment]
Everyone against this are just salty cos they know they will never get anyone

**Comment by BowShot118** [comment]
🤢

**Comment by Pengun78** [comment]
Are you really attracted to Minecraft characters

**Comment by MSatrokrm** [comment]
Are you guys familiar with the phrase, "just for fun"? 

Of course, we're not attracted to Minecraft characters.

**Comment by Pengun78** [comment]
Then why not a sex mod its just for fun right

**Comment by Coffeetom** [comment]
Pengun, how will adding this plugin affect you? If you don't want to use it, that's fine, but don't ruins others fun. As evident by this page, many people want it.

**Comment by Coffeetom** [comment]
You don't have to pay attention to it. And it really isn't going to create much lag, compared to existing plugins. So it should be fine

**Comment by KarlOfDuty** [comment]
We will not be implementing this.
