### ISSUE TITLE
[Other] Nether reset?

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#198]
Tbh the nether is pretty empty atm, a reset would be beneficial for all of us

**Comment by IGNSlaid** [comment]
i made a path till the 5000's in a axis to find the "virgin" nether, and people have buildings in nether aswell

**Comment by Ultil0l** [comment]
I mean like the dungeons

**Comment by IGNSlaid** [comment]
if there is a way, it would be very overpowered for those which have a portal inside a fortress, but i agree they're already raided, thats why i broke 10k blocks on the nether :P

**Comment by Ultil0l** [comment]
maybe like generate a full new nether

**Comment by IGNSlaid** [comment]
bad bad bad, i spent like 5 hours building the damn highway to the 5000's, and i bet i'm not the only one who worked alot in the nether to gather spawners, i heard Armenia has 37 spawners...

**Comment by NeonKrby** [comment]
I think it should be wiped monthly to help the re-population of Quartz and Blaze Spawners.

**Comment by DKS134** [comment]
I'm totally up for this, otherwise the blaze spawners will be concentrated in one group's hand

**Comment by KarlOfDuty** [comment]
We have planned to start having regular nether resets at some point. We are going to change some nether mechanics first so it might be a while before that happens though.

**Comment by IGNSlaid** [comment]
it isnt going to be concentrated since anyone of you guys can go there in the far nether and grab some

**Comment by KarlOfDuty** [comment]
We have decided against this at this time as some have build a bunch of stuff in the nether at this point.
