### ISSUE TITLE
[BUG] Insane constant lag

### ISSUE THREAD

**Issue by IGNSlaid** [EarthMC/Issue-Tracker#199]
EMC Server

The lag is making the server unplayable, because simple tasks are getting impossible to do, such as breaking blocks, moving animals with leads, pvping, killing mobs and stuff. This started yesterday for some reason. The previous lag was not that bad and if we can get back to it, epic.

**Comment by 1stcast** [comment]
The lag started back up when he turned mobs on.
I am unsure if that was the cause but there was a correlation.

**Comment by KarlOfDuty** [comment]
No, there seems to be a memory leak in one of our plugins, probably chatcontrol which was recently added.

**Comment by Ultil0l** [comment]
chatcontrol is for normies

**Comment by BowShot118** [comment]
> No, there seems to be a memory leak in one of our plugins, probably chatcontrol which was recently added.

It isn't really needed :/

**Comment by Ultil0l** [comment]
no one likes it and it just creates lag

**Comment by KarlOfDuty** [comment]
Yeah, it is being removed next maintenance.

**Comment by Pengun78** [comment]
Hell yeah

**Comment by Ultil0l** [comment]
Emc, the land of the free

**Comment by IGNSlaid** [comment]
FREE SPEEEEEEEEEEECH wheres ben saphiro

**Comment by KarlOfDuty** [comment]
Should be fine now.
