### ISSUE TITLE
[World] Puerto Rico water biome is badly botched

### ISSUE THREAD

**Issue by JohnEricoJR** [EarthMC/Issue-Tracker#200]
The water around Puerto Rico is badly botched, the clear sign of World editing where straight line and chunks are missing of tropical water, as well as no sea life that is associated with tropical waters
A clear and concise description of what the issue is. Chunks of tropical water missing, no marine life

**Coordinates**
X Y Z coordinates. -12402X -3443Z and -12504X -3430Z  also -12265, -3540

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how you want the terrain to look.

**Comment by PoppyK** [comment]
Done
