### ISSUE TITLE
[Plugin]War

### ISSUE THREAD

**Issue by 1stcast** [EarthMC/Issue-Tracker#201]
**Is your feature request related to a problem? Please describe.**
So this addresses a problem I have with the server and that I see talked about often.
Currently, pvp has no function outside of annoying other players. This will be somewhat addressed when keep inventory is turned off, but in my opinion that is not enough.

The problem that I am under the impression Karl has, is that he wants a few larger nations rather than many smaller ones. A war plugin will allow nations to consolidate smaller nations near them if they cannot find an alliance or larger nation to assist them in wars.

**Describe the solution you'd like**
Well as the title indicates, I would like to get a war plugin added to the server but from what I understand there is not currently one up to date.  I would like to propose for you guys to allow my friend Bananapuncher714 to make a war plugin for the server. He has agreed to do so if it is something you would be willing to add once it is done, and has a lot of experience making plugins so he is fully capable.

**Additional context**
Now I am just going to go through my mini-brainstorm of ideas to possible have you decide what works best for the server if you choose to allow him to make the plugin for you.
When at war at the very least all involved towns should have pvp forced on to not allow for edge camping of safe zones. It could also enable explosions as the server seems to already have a plugin that regenerates blocks destroyed by TNT. This would discourage pillaring over walls breaking rule 3 because they have a valid rule compliant way of getting in. 

The war itself could be done in several ways. A few I can think of are King of the Hill with some point needing to be placed in the defending town, a race to get to a certain amount of kills, some form of capture the flag, And there are most likely more options I could not think of while writing this.

As for what you might get from wars I can think of a few options at the moment.
First the obvious moving towns from one nation to another. This can, of course, cause problems within a nation if they take people who are not willing to stay within their nation and could open up opportunities for the rebellions to be a real problem.

Other possible options that I think could be a good idea but aren't crucial for the plugin could be Raiding where you can take certain blocks tagged as valuable or open chests. Possibly another option to put a new leader on a town, this one can be fairly problematic but I wanted to put it out there anyway because it could have real use in-in town conflicts where a leader is doing things that don't represent what the citizens want.

Nothing I have said here is really final it's just ideas. He is perfectly willing to make it in any way you want as it is your server and we just want to improve the experience.

**Comment by KarlOfDuty** [comment]
If you do make a war plugin we'd be happy to try it out, but no promises on whether we would use it or not. We have not liked any previous war implementation so it would be nice to see some new options.

**Comment by IGNSlaid** [comment]
how about towny's war system Karl?

**Comment by KarlOfDuty** [comment]
Towny war days are not very interesting I don't think.

**Comment by 1stcast** [comment]
Do you have any preferences on any of the ideas I have stated to avoid unnecessary work on his part?

**Comment by KarlOfDuty** [comment]
I have no idea, no. Just make it configurable so it can be played without stakes in the beginning.

**Comment by owentheguy1** [comment]
That's kind of the problem, isn't it? We're never going to get an actual war system unless we specify what we want.

**Comment by KarlOfDuty** [comment]
That's pretty hard when no one can come up with a good one.

**Comment by NigelFarage666** [comment]
I suggest wars are when 2 nations enemy each other and then all of their towns should have pvp toggled on.
In the mean time only.

**Comment by BowShot118** [comment]
> I suggest wars are when 2 nations enemy each other and then all of their towns should have pvp toggled on.
> In the mean time only.

So like once both nations enemy each other all towns have pvp toggled and it can't be toggled off? That sounds like a great compromise, not making war too destructive but teaching the people who go into war without thinking a lesson. It'd be best if the pvp only applied to nations at war and neutral bystanders aren't effected but idk how that would work.

**Comment by Magenent** [comment]
Can we please make this a thing sooner then later, I know creator will be working on the new towny plugin in janurary, but i think before then we should have a war day or something because there is HUGE tensions with norge, norway, qin, denmark, panama, britain, france and more so we need something to shift the status quo and see who would really win.

**Comment by Pengun78** [comment]
New towny system??

**Comment by BowShot118** [comment]
Honestly, this is towny and not factions. I dislike a war plugin all together

**Comment by NigelFarage666** [comment]
Pock stop commenting and ruining others people game its obvious you are not even playing.
So please leave us alone.
