### ISSUE TITLE
Nation Names Violations

### ISSUE THREAD

**Issue by HaydenTownley** [EarthMC/Issue-Tracker#202]
Quebec- Quebec was never a nation that existed. They have high nationalism and wishes to separate but has never separated and been recognized as a separate nation. 

California- California was never a nation that existed. Yes it rebelled away from Mexico than immediately hoped on ship and joined America. It lasted 25 days in what you would call an independent place. But this by far does not qualify it as a nation. Nobody recognized California as a separate nation. If you state this is true nations that's absurd. The nation will last longer on Terranova then it supposedly existed in real life. 

Florida- Florida was never a nation that existed. They were land claim and territories but never nations. The closet you can get is the West Florida Republic which exited in nowadays Louisan and not Florida. And still in this case no one recognized them as a separate nations

Texas is a true nation that existed and was recognized by a foreign power. 

Wakanda- Its a made up nation that exists only in the Marvel Cinematic Universe...

**Comment by FurdenFuhrer** [comment]
I would have to agree with everything on this list but Wakanda

Wakanda is real in our hearts

#WakandaForever

**Comment by BowShot118** [comment]
And Quebec is a very large and influential province of Canada that has its own independence movement.

**Comment by Pengun78** [comment]
all U.S states are independent in this game tbh

**Comment by Ultil0l** [comment]
Actually, Quebec is de jure its own country

**Comment by Ultil0l** [comment]
as it didnt sign the most recent canadian constitution

**Comment by KarlOfDuty** [comment]
Reporting rule breakers is not what the issue tracker is for. Make a support ticket.
