### ISSUE TITLE
[BUG] Custom Tree McMMO Issues

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#203]
Terra Nova.

Simple, tree feller(mcmmo) does not work on the custom trees with 6 sides logs. Also i believe you woodcutting mcmmo XP from cutting trees.

1. Try to tree fell a custom tree

It is supposed to cut down the whole tree and your supposed to get XP on all logs.

**Comment by sharkfynn1012** [comment]
We will just slowly have to cut them down, if fire spread was tuned back on I'd be happy to do controlled burns and regrow trees.

**Comment by KarlOfDuty** [comment]
I feel like mcmmo won't just have this bug forever, just wait until they have finished their 1.13 version.

**Comment by Pengun78** [comment]
its also annoying you strip a log if you want tree feller to activate

**Comment by KarlOfDuty** [comment]
Closing this as it is nothing we can fix.
