### ISSUE TITLE
Can't connect to EarthMC

### ISSUE THREAD

**Issue by FrozenWaterX1** [EarthMC/Issue-Tracker#206]
I can not connect to the server. I was able to connect yesterday and the day before, but it seems it stopped working. I can connect to all other servers (Hypixel for instance) just not this one for some weird reason. I am running the newest version of MineCraft 1.13.2, I live in Germany. Please help!

**Comment by KarlOfDuty** [comment]
Please make a support ticket instead as this seems to be an individual matter.
