### ISSUE TITLE
[World] Ice in Japan

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/Issue-Tracker#207]
**Describe the issue**
Theres ice surrounding the Japanese Islands, Including warm places like Okinawa. 
**Coordinates**
All of Japan
**Screenshots**
![image](https://user-images.githubusercontent.com/45209878/49463599-d8f01c80-f7c6-11e8-87b1-c04c1df88f9d.png)

**Comment by NeonKrby** [comment]
Back when i first colonized Japan some people from the Philippines were cleaning it up calling it ¨Clearing plastic from the ocean¨ but because their is so much it cant be to full effect.

**Comment by PoppyK** [comment]
Sorted it out.  Closed.
