### ISSUE TITLE
[Plugin] Revert back to 1.8 PVP

### ISSUE THREAD

**Issue by Zyphlox** [EarthMC/Issue-Tracker#209]
**Is your feature request related to a problem? Please describe.**
Whenever I pvp, I find it frustrating to even try to battle. Lag always gets the worst of the fight, and when you think you're going to win, you instead get hit by your opponent 5 times in a row without you having done any single hit. Point is, pvp sucks. If lag is entirely fixed, I would suggest we stick with the current 1.13.2 pvp mechanics. But if lag will never get fixed (I assume because of anti-xray), then I suggest we go to 1.8 pvp mechanics (if this is possible). This way when spamming the sword button has no repercussions because lag will take the place of what 1.13.2 pvp mechanics intended to do, stop you from spamming the sword to do consistent damage. In 1.13.2 pvp, you have a bar that fills after every hit so that you can do more damage when you do 1 single hit rather than spamming the left mouse button.
But lag has made this mechanic inconsistent, and whenever I pvp I feel like it's almost redundant to even try to time all my hits once this meter fills.

**Describe the solution you'd like**
If possible, revert to 1.8 pvp mechanics. I know some servers had this implemented somehow, and doing so would in the meantime (before lag is fix) adjust pvp. If this is not possible, then nothing needs to be changed, this is just a suggestion after all. 

**Additional context**
No other additional context is needed I presume.

**Comment by Coffeetom** [comment]
Yeah can we please add 1.8 pvp. This would make sense as all major pvp servers use 1.8, and due to the lag, it's a lot more practical.

**Comment by Pengun78** [comment]
I think 1.8 pvp is a bit op you just spam click doing 10 damage (with a god sword) i am totally fine with the combat update and glad it happend

**Comment by MSatrokrm** [comment]
No. 1.8 pvp is just a bunch of kids spam clicking the left click button.

**Comment by IGNSlaid** [comment]
yea plz dont bring back the killaura 13 years old kids

**Comment by KarlOfDuty** [comment]
We will not revert back to 1.8 PVP.
