### ISSUE TITLE
Breeding will not work

### ISSUE THREAD

**Issue by 4noah18** [EarthMC/Issue-Tracker#21]
I bred my sheep multiple times with different sheep, got the heart effects, they put their pp's in each other and all, but I received no sheeplings. I would like a refund. Please fix.

**Comment by Arganog** [comment]
We haven't had any issues breeding cows or sheep at Karlskrona -- perhaps this is related to the mob cap limit per chunk?

**Comment by 4noah18** [comment]
I figured out it was that. I split my sheep up into different chunks. Thanks.
