### ISSUE TITLE
[BUG] Inspect command conflict

### ISSUE THREAD

**Issue by itsmeaddof123** [EarthMC/Issue-Tracker#210]
**Server**
Terra Nova

**Describe the bug**
/inspect for mcmmo does not work because it conflicts with /inspect for worldedit

**To Reproduce**
1. Do /inspect

**Expected behavior**
/inspect tells the mcmmo stats of the target player if they are nearby

**Additional context**
Relates to #ticket-2946 on discord

**Comment by KarlOfDuty** [comment]
Will be fixed next server maintenance.

**Comment by KarlOfDuty** [comment]
Or I guess not, for some reason worldedit overrides it even though it loads afterwards. You can use /mcmmo:inspect instead.
