### ISSUE TITLE
[BUG] Trade Signs

### ISSUE THREAD

**Issue by itsmeaddof123** [EarthMC/Issue-Tracker#211]
**Server**
Terra Nova

**Describe the bug**
Users have the ability to create a sign with [item] on it but do not have the perms to actually create the trade sign. After placing the sign, I can't assign an item to the sign.

**To Reproduce**
1. Create a sign saying [item]
2. Either left click or right click the sign with the desired item to buy/sell

**Expected behavior**
It should allow me to assign an item, followed by a price, followed by the sign again and finally a chest.

**Additional context**
Trying to left/right click the sign with an item results in the message "Invalid Permission."

**Comment by KarlOfDuty** [comment]
I'll have a look, should be an easy fix.

**Comment by KarlOfDuty** [comment]
Hmm, says you already have permission for it.

**Comment by itsmeaddof123** [comment]
It's working now, however there is another issue. I've set up some signs to sell a stack of an item, and the sign does indeed say that there are 64 pieces available. However, when someone tries to use the trade, they only receive 1 of the item. The rest of the transaction does work fine.

**Comment by KarlOfDuty** [comment]
Please screenshot the sign and post it here.

**Comment by itsmeaddof123** [comment]
https://i.imgur.com/waQ5RU5.png
https://i.imgur.com/SoZxan4.png

Creating the trade sign confirms it as a 64 black wool to 1 gold ingot trade, but when executing the trade only 1 black wool is traded. This was also tested for 15 other items, so it's not just the one sign.

**Comment by KarlOfDuty** [comment]
Ok, @creatorfromhell can have a look at this.

**Comment by creatorfromhell** [comment]
@KarlOfDuty This has been fixed now.

**Comment by itsmeaddof123** [comment]
Fixed as in fixed upon the next reset, or as in it should be in working order right now?
It's still only doing trades of 1 item despite having 64 items set, however there hasn't been a reset yet so if it's supposed to be fixed after the reset then that'd be it.

**Comment by creatorfromhell** [comment]
> Fixed as in fixed upon the next reset, or as in it should be in working order right now?
> It's still only doing trades of 1 item despite having 64 items set, however there hasn't been a reset yet so if it's supposed to be fixed after the reset then that'd be it.

Considering it's still doing the 1 item instead of 64, I think it's a safe assumption that it will be in the next update, no?
