### ISSUE TITLE
Customised Sign text 

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#213]
Like on classic, I'd love to see the reintroduction of bold and italic lettering to signs on Terra Nova. (Possibly even coloured as a donor perk to differentiate Purple and Yellow Ranks ;) )

**Comment by SlyPrince** [comment]
This would be a great (re-)addition, especially for historical signs on the server. It'd give more creative ability to avid labellers, and more interesting signs to come across when exploring

**Comment by Pengun78** [comment]
I didnt even know that was a thing on classic

**Comment by KarlOfDuty** [comment]
The plugin we used for that does not exist for 1.13.
