### ISSUE TITLE
[World] What nation could I make in Antarctica?

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#214]
**The Issue**
I want to settle in Antarctica, create a town there, and potentially make a nation there. One problem though, I don't know what I would call the nation. I cannot name it "Antarctica" because the rules said that nations can't be named after continents. So if anyone knows what I could name a nation down in Antarctica, I would love to hear it.

Since there are many stations in Antarctica owned by the UK in the real world, I was wondering if I could include "UK" somewhere in the name.

I don't know if I'm even allowed to make a nation in Antarctica. Maybe there can be an exception to the Nation-Naming rules that would allow me to name the nation "Antarctica"?

**Comment by shirazmatas** [comment]
If this isnt fixed ask in a support ticket on discord
