### ISSUE TITLE
Dye Recipes

### ISSUE THREAD

**Issue by fettered** [EarthMC/Issue-Tracker#215]
The scarcity of mobs restricts easy access to all dye types, affecting hardened clay, concrete, wool, and bone block. 

Accessibility through custom recipes.

RecipeManager is not updated to 1.13 :(

**Comment by fettered** [comment]
Forgot to add, could also make fermented spider eye, glistering melon, and golden apples/carrot not so expensive so that horse breeding and potion brewing can happen.

**Comment by SlyPrince2** [comment]
I seem to recall a black dye recipe being mentioned, to fix the squid and ink scarcity. Would be good if this happened especially

**Comment by creatorfromhell** [comment]
Flowers substitute for most dye types.

**Comment by KarlOfDuty** [comment]
We have added a new recipe for ink sacs, if you need anything more, please open a new issue and specify exactly which dyes you want new recipes for.
