### ISSUE TITLE
Custom Villagers for unobtainable items

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#216]
Items which are in demand by builders ranging from specific dyes to sea items or even end materials are currently unobtainable on the server and if the status quo remains, probably won’t ever be.

On classic we had custom villagers located at spawn which sold items such as ink sacks for a small amount of gold.

I think the same should be implemented on TN however we don’t have a spawn and therefor these custom villagers should just be obtained by the same methods used to get regular villagers.

They would sell items like sea lanterns, prismarine, Black dye, purpur, end stone etc etc all for a low amount of gold.

I think this would make things a lot easier for many players.

**Comment by BowShot118** [comment]
Yeah but if they don't like double smelt, why'd they add this.

**Comment by SlyPrince2** [comment]
Pock making some woke comments.

But it'd be nice to have this, and it may be one of the only ways to solve the problem of how we would be able to get materials that dont exist in the map. Except from spawning finite numbers of things in.

**Comment by Ultil0l** [comment]
#fixthemobssmh

**Comment by AidanMSad** [comment]
i'd love that. I love sea lanterns like crazy and it is killing me we cant have it, 

if they want it exclusive make it donator only.

**Comment by KarlOfDuty** [comment]
We are already planning a way to get unobtainable items, but you can open a new ticket if you want to list unobtainable items so we don't overlook anything when we do.
