### ISSUE TITLE
TimeLapse Alt

### ISSUE THREAD

**Issue by DitheryGames** [EarthMC/Issue-Tracker#217]
**Is your feature request related to a problem? Please describe.**
Id like to have an alt as a "Cam" account. This means using an alt. While I know alts are banned I would like to ask if I could use a player with "Cam" in its name (DItheryCam) for me. However The fact that alts are banned and I would like not to have a ton of platforms around my place for the cam to be set up. 

**Describe the solution you'd like**
Id like players with a "Cam" account to be able to have them on as a "timelapse account" with this I see two things that could happen, either those players could get spectator so the need for pillars wouldnt be there, or the timer removed from those "Cams". Im not sure how bad these could be for the server as even if you spy on another players base, if its claimed you really cant do much.

**Additional context**
 
![2018-11-27_23 27 36](https://user-images.githubusercontent.com/45676124/49622913-b9a0ed00-f988-11e8-9560-0311d7ca132c.png)
![2018-11-29_14 41 34](https://user-images.githubusercontent.com/45676124/49622919-be65a100-f988-11e8-9afa-20bd3c8417b9.png)
![pagoda](https://user-images.githubusercontent.com/45676124/49622927-c9b8cc80-f988-11e8-8387-7e5afb264c86.JPG)

**Comment by NeonKrby** [comment]
They wont add this, People wouldn't use it for just flying around with a camera to time lapse shit they would fly around the map and find secret bases or when dungeons are added find those so easily.

**Comment by Coffeetom** [comment]
I don't want them to add this, because I can guarantee people will use this to find caves, dungeons, areas in enemy towns, etc. And people would also use these accounts for AFKing at farms. Overall they will be used for more bad then good.

**Comment by BowShot118** [comment]
If this is added then there is no reason to just allow all alts. These can be very easily abused.

**Comment by Pengun78** [comment]
Walter

**Comment by NeonKrby** [comment]
^ Yeah this is a dumb idea.

**Comment by DitheryGames** [comment]
The idea initially was just for me... I had it on the issue ticket thing and the staff asked me to put it on here. I understand that it'll be abused by others, and I was fine with using platforms. So call out that it's dumb if you want but just know they asked for this to be on here while I got the ok for now for just pillars and an alt, no one else.

**Comment by BowShot118** [comment]
> The idea initially was just for me... I had it on the issue ticket thing and the staff asked me to put it on here. I understand that it'll be abused by others, and I was fine with using platforms. So call out that it's dumb if you want but just know they asked for this to be on here while I got the ok for now for just pillars and an alt, no one else.

I understand why you'd want to have this for yourself, many people are just pointing out how it would be easily abused.

**Comment by NeonKrby** [comment]
they wont give you alone special access

**Comment by NeonKrby** [comment]
And who says you wont abuse it?

**Comment by DitheryGames** [comment]
Well that's the reason it's on here so they can debate what to do. I understand I can't be trusted right away

**Comment by Coffeetom** [comment]
I believe that no single person should get extra power. Maybe if you had a YouTuber channel, you could get YouTube rank, and that would allow you to have stuff such as a camera account. However I don't think individual people should be able to get special treatment.

**Comment by 4noah18** [comment]
I think you should be able to submit a request to be supervised while you capture cinematic views of your whateverthefuck.

**Comment by KarlOfDuty** [comment]
We will not be adding this rank.
