### ISSUE TITLE
Dog Smush

### ISSUE THREAD

**Issue by fettered** [EarthMC/Issue-Tracker#218]
Dogs are affected by mob stacking rules, killing some or all when they tp to you sometimes. Or when they attack.

Exclude dogs from stacking.

**Comment by BowShot118** [comment]
Mobs don't stack here?

**Comment by fettered** [comment]
Too many dogs = they die, they get crushed by a gamerule added in 1.12

**Comment by fettered** [comment]
![image](https://user-images.githubusercontent.com/13987720/49667857-58315a80-fa2a-11e8-92a0-3b1419b658f7.png)

**Comment by Pengun78** [comment]
I cant believe u killed the doggos for images

**Comment by Pengun78** [comment]
Fix ban doggo abuse

**Comment by KarlOfDuty** [comment]
It is set to allow for 20 mobs in a single block, I think that is high enough.
