### ISSUE TITLE
My town has more gold than the next highest town but is not shown on ./baltop.

### ISSUE THREAD

**Issue by Cooliodex** [EarthMC/Issue-Tracker#22]
DESPACITO has 187g in the bank and Karlskrona has 175. For some reason, DESPACITO isn't on the list.

**Comment by creatorfromhell** [comment]
Obviously Despacito is inferior.

**Comment by creatorfromhell** [comment]
Fixed in https://github.com/TheNewEconomy/TNE-Bukkit/commit/d9209d86433146766b173708d55447ff8f6dfbc6 .
