### ISSUE TITLE
[Feature] Enable Gold Double Smelt.

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#221]
Well I don't know why gold double smelt still hasn't been enabled yet? Currently with double smelt disabled for gold it takes a good hour of mining just to get 1 chunk of land, and you would also be spending gold on buying stuff which should be expected, and for the casual players who don't really want to mine for more then 2 hours a week, they are screwed the most since they won't be able to get gold to use and it would stop a lot of new players from becoming active.

  Also it would be balanced because to get the high smelting ability you would have to spend iron or diamonds to fix up the stuff or you'd have to grind mining itself which should be rewarded, also for casual players they could just trade ore for ingots in which both sides win, the casual wins cause he gets more ingots then he got if he were to smelt and the people who grinded and spent time and resources get more ore to get a profit margin.

  All in all I think it's worth it because it increases trade and benefits both casuals and grinders and would also allow more gold into the economy to fund big projects and other stuff.

Enable double smelt for gold ore.

**Comment by TypicalFernie** [comment]
A lot of people have quit because of this or want to quit and it's honestly just sad. Lucas (the leader of New York) hasn't played for a while. He hasn't said why but he did complain a lot of double smelt being disabled, which is most likely the reason. Karl is stopping the development of amazing cities smh. No one wants to mine for a fucken hour just to claim 1 chunk. Also it's fucken finals people just want to join and play in their free time, not grind.

**Comment by g0tg0t6** [comment]
I agree with MineHero43

**Comment by Coffeetom** [comment]
Remember, we are playing Towny, not prison.

**Comment by BowShot118** [comment]
It is stupid that this has not been re-enabled. I myself have not mined in the past week as it just isn't worth it. How do you expect to get massive, impressive builds without giving us a half decent chance of claiming them? Think about this.

**Comment by FenZenyatta** [comment]
We need an update on this. We need to know if we can expect it to come back or if it is a lost cause...

We had double smelt enabled for over 20 days and nobody complained, the economy wasn't shit and everyone was happy. UPDATES, COMMUNICATION, ADMIN PLS

**Comment by KarlOfDuty** [comment]
It is not coming back. Not anytime soon at least.

**Comment by Pengun78** [comment]
Karl how could u

**Comment by TypicalFernie** [comment]
KARL

**Comment by TypicalFernie** [comment]
petition to ban Karl when

**Comment by BowShot118** [comment]
What the fuck Karl.

**Comment by Pengun78** [comment]
Grrrrrrrrrrr rr 😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠😠

**Comment by BowShot118** [comment]
What's @FixTheAdmin's view on this?

**Comment by BowShot118** [comment]
Nice one, Karl and Fix don't play on the server. They just run it.

**Comment by IGNSlaid** [comment]
>:(

**Comment by Coffeetom** [comment]
To Karl and Fix,
I know you guys are trying to do the best for the server, and want to keep the economy balanced, however on this issue it may be better to just give in. This issue has made many stop mining, and play less ingeneral. For the good of the server, I think it would be wise to re enable it.

**Comment by Ultil0l** [comment]
They just dont care and are super dosconnected from the community
