### ISSUE TITLE
European Geography

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#222]
Issue

The issue is there are many players playing in the Europe and Europe is just done Poorly compared to other continents.
Biomes lack detail mountains are almost unexistant or covered with forests rivers aren't wide enough and biomes aren't diverse at all.
I suggest Europe gets its rivers widened,forests fixed,on some spots (small ones) some new biomes added and mountains fixed.

![europe](https://user-images.githubusercontent.com/44730188/49697889-2997b900-fbbd-11e8-8736-2e3d65dc33a3.png)

1.I suggest you make mountains taller,bigger remove Oak Trees and add more Spruce Trees.
-Also place trees in the lower parts of the mountains so the top is rocky.
2. You should expand Seine River here make biome plains add more flower and grass on it and remove more trees possible.Also if possible next to the river add Dark Oak Biome so it looks more like the Old Map and more detailed.(But this is problamatic one because Seine is claimed by Zqppy's town)
3.This is problematic one as well. I remember NS making post about that 10 days ago.
Problem there is Guadiana and Tagus rivers are missing and the whole biome there should just be Oak Forest with Mountains. Whole Savannah thing with no rivers was a big mistake
4. Nothing speical here just more hills and more savannah biome.
5. This is important part. 
-Benelux is made very badly lacking many details.
 First thing-Coast of Belgium should be Dark Oak Biome like Norway same goes for Dutch Rivers and Coastal Areas. 
 Second: Benelux is mostly planes with no mountains and rarely any forests (Few exceptions in Luxembourg and Western Belgium but nothing important) this is why I suggest you remove all those forests and instead of them you make nice plains with Red Tulip flowers and a lot of grass because it currently looks very ugly.
6.South Poland
-Poland overall is great but there is a minor change I suggest in southern part on the Tatra Mountains.
I suggest you make them higher and bigger (nothing special)
7.Now this is Western France and I believe you should add more detailed forests there and a dark oak biome everywhere since Western France is known for deciduous forests.

Thats pretty much it.
Please don't get me wrong I appreciate everything you have done with this map and I believe it was hard to do it.But there are some minor mistakes which would be worth fixing. 

Thank you!
Nigel Farage666.

**Comment by NigelFarage666** [comment]
> If anyone wants to work this out in details (from staff designer team) PM me my discord is:

NigelFarage#3781

**Comment by al802** [comment]
i agree

**Comment by Snowyy4K** [comment]
I agree

**Comment by NigelFarage666** [comment]
Thank you!

**Comment by shirazmatas** [comment]
I'll start work during winter break

**Comment by NigelFarage666** [comment]
Shiraz where can I contact you and are you still planning on fixing the issue?

**Comment by NigelFarage666** [comment]
Shiraz?

**Comment by DasCodes** [comment]
@shirazmatas

**Comment by DasCodes** [comment]
Not even sure if this is possible anymore with so many towns around.
