### ISSUE TITLE
[Feature] claims protect horse

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#223]
I think its really annoying people can just steal horses out of claims, you'll have to make the horse
stable very ugly/unrealistic or even underground
the saddle and horse armor can also get stolen

**Comment by NigelFarage666** [comment]
WHAT !!!!
OH SHIT MY HORSE

**Comment by KarlOfDuty** [comment]
This isn't something we can implement and I assume towny have already fixed this anyway.
