### ISSUE TITLE
Attacking members in your nation 

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#225]
You can kill members of your own nation. I feel like this should be changed, lol.

**Comment by MSatrokrm** [comment]
No

**Comment by Pengun78** [comment]
Its fucking epic

**Comment by KarlOfDuty** [comment]
As Bowshot mentioned above, people had issues with nation allies coming by messing with their towns so we will keep it on so towns can defend themselves.

**Comment by TypicalFernie** [comment]
um /n ally remove (name) or temporarily leave the nation. It's much more important to make it so we can't attack allies than being able to. Since if an "ally" is griefing you, you can kill them by unallying them if you have perms or leaving the nation.

**Comment by KarlOfDuty** [comment]
People would rather keep their claim limit than leave their nation.

**Comment by TypicalFernie** [comment]
"temporarily"

**Comment by BowShot118** [comment]
Fernie you can't if you either don't have the perms or your nation leader is inactive
