### ISSUE TITLE
[Plugin] Lingering Potions

### ISSUE THREAD

**Issue by fettered** [EarthMC/Issue-Tracker#226]
Without any custom recipes for things that don't currently exist, stuff like prismarine and everything in the end is not accessible.

Custom recipes to access items such as dragon's breath, prismarine, and non renewable resources like coral blocks.

**Comment by fettered** [comment]
oh and

**Comment by BowShot118** [comment]
clap

**Comment by fettered** [comment]
the end isn't even confirmed as far as I know
