### ISSUE TITLE
[Feature] Being Able To Tell If Someone Is Banned

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#227]
Well I think it'd be cool if when you did /res [username] if there banned it should say cause for instance if someone gets banned for greifing in your nation then you could know why they haven't been on instead of just wondering when they'd get on.

Add it so when you do /res [username] it has something like Banned: Yes/No and it'd be either of them.

**Comment by KarlOfDuty** [comment]
I feel like there is a command like that but I can't remember what it is.

**Comment by KarlOfDuty** [comment]
I don't think adding an entirely new plugin for this is a good idea.
