### ISSUE TITLE
Town names

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#229]
Town names
Server EarthMC-Terra Nova

In my case I was forming Kingdom of Flanders-Wallonia as a town (since its pretty small irl) 
I asked fellow staff member called PolkadotBlueBear to rename my town to Flanders-Wallonia and he said name was invalid aka too long.
Thing is I can still remember much longer names on classic.

I wanted to ask is it possible to make limit for town names smaller because some people might merge towns or want bigger regions.

Now Im not sure would this be classified as a bug but the fact I couldn't rename my town is kind of buggy and this sorta ruined my idea.

**Comment by KarlOfDuty** [comment]
The limit is 16 characters, I don't think this is too short.

**Comment by NigelFarage666** [comment]
Ok.  I had 17 characters.

**Comment by EchoOcelot** [comment]
Just remove the dash and it should fit

**Comment by KarlOfDuty** [comment]
We will not change the name limits as it would make the chat very cluttered.
