### ISSUE TITLE
Remove the limit on number of shop signs.

### ISSUE THREAD

**Issue by Caeso2** [EarthMC/Issue-Tracker#230]
I do not see why there would be a limit on the number of shop signs you can own unless it is somehow limited by the game. It will be annoyance and unnecessary to have to have someone else set up the rest of my shops and manage them. Hopefully you guys can remove the limit.

**Comment by KarlOfDuty** [comment]
I have now set it to 200 signs, will reload on next server ~~crash~~ restart.

**Comment by Caeso2** [comment]
Thank you!
