### ISSUE TITLE
[Suggestion] Gun Plugin

### ISSUE THREAD

**Issue by PoshTiara** [EarthMC/Issue-Tracker#231]
An issue I and many others that play on a server that has building and some kind of war is regular minecraft PVP which grinds down to how fast a person can click and how much experience they have in minecraft PVP. There is a great divide between people who can and cannot PVP properly. A solution to this would be an introduction of an equalizer that would put everyone on the same playing field when it came to PVP. The solution would be a gun plugin. The introduction of plugin guns chances the dynamic of minecraft PVP and creates more aspects such as actual unit tactics, a reason to use ad hoc fortifications in battle and logistics. I'm not really knowledgeable about plugins or the meta of minecarft in general but from my own experiences on playing on /intcraft/ I fondly remember combat and warfare being much more enjoyable and fair. 

For plugin suggestions it seems there are only two gun plugins that are updated for 1.13. These would be Quality armory and crackshot. On  the various /int/carft servers I played on with gun plugins they seemed to be custom made by the admins and content creators.

**Comment by BananaPuncher714** [comment]
I like guns, but Crackshot and Quality Armory don't qualify as a "gun plugin".

**Comment by KarlOfDuty** [comment]
We do not want to add modded items and stuff like that to the server, it doesn't really fit with EMC.
