### ISSUE TITLE
Town population limit bypass

### ISSUE THREAD

**Issue by CloakedEagle** [EarthMC/Issue-Tracker#232]
The towns can have up to 50 members. However, if you open your town to the public i.e. `/t toggle open` a town can have more than 50+ residents.

**Comment by 32Gold** [comment]
Why limit towns in the first place

**Comment by BowShot118** [comment]
Because people hate decent sized towns?

**Comment by CloakedEagle** [comment]
The limit is there to distribute players all over the map, but not just stacked up in one town.

**Comment by CloakedEagle** [comment]
https://imgur.com/a/GCXyhTT

**Comment by Pengun78** [comment]
U can do /t toggle open and then people can join with /t join townname no mather what player limit

**Comment by Pengun78** [comment]
F word the limit i think this is fine

**Comment by Ultil0l** [comment]
The limit is very not good tbh

**Comment by BowShot118** [comment]
Or at least increase the nation bonus to compensate

**Comment by Ultil0l** [comment]
but what do you do with all the towns over 50? yall cant just kick all the excess people out,,,

**Comment by Ultil0l** [comment]
thats a big oof

**Comment by NigelFarage666** [comment]
There are 5 Megaregions on Earth.
Those are areas filled with great spots where people will live anyways.
Those are 
1.Southern Brazil/Buenos Aires Area
2.California/Northern Mexico/Nevada
3.Northest/Midwest US
4.Europe (as whole yeh)
5.Far Eastern Asia (Northwestern China,Japan,Koreas) 
No matter what you do people will be living there. 
And btw just open irl world map and this server map and you will see what Im talking about most of the towns are in those megaregions rest are bunch of inactive newbie poor towns.

**Comment by KarlOfDuty** [comment]
I have submitted a fix to this issue on the towny repo but there isnt a lot of activity there at the moment.

**Comment by Ultil0l** [comment]
f

**Comment by AlexGamerYTT** [comment]
Agreed.
Smallest towns can't get too much members easily.

**Comment by KarlOfDuty** [comment]
This has been fixed.
