### ISSUE TITLE
Faster carts

### ISSUE THREAD

**Issue by TypicalFernie** [EarthMC/Issue-Tracker#234]
People have been creating railways all over the place and i think a plugin like this will help with transportation a lot. Im not suggesting this plugin because of the train feature, but because it will make the carts go a lot faster. "Infinite minecart speeds are possible, higher speed than vanilla". The train thing looks kinda gay so disable that if you want.

Plugin: https://www.spigotmc.org/resources/traincarts.39592/

**Comment by MSatrokrm** [comment]
I don't think this plugin would work very well in such a laggy server.
