### ISSUE TITLE
[Mechanic] Tropical Fish in claims

### ISSUE THREAD

**Issue by itsmeaddof123** [EarthMC/Issue-Tracker#236]
I would like to suggest enabling protection for tropical fish inside claims. As it stands now, fish inside claims cannot be scooped into a bucket, however they can be killed. I think it would be nice to be able to make a pond with exotic fish inside my town, and having fish be protected would make that possible

**Comment by MSatrokrm** [comment]
Yes! Dolphins too! People keep feckin punching the fish I put in my beach and it's annoying.

#ProtectTheFishies

**Comment by KarlOfDuty** [comment]
Should be fixed.

**Comment by Helloguys47** [comment]
wanted to reporte the same bug

**Comment by Cactusinapumpkin** [comment]
Can you post ss of some person punching ur fishes to death. This might be a chunk mob limit issue
