### ISSUE TITLE
Town Permissions Bug

### ISSUE THREAD

**Issue by DomPedroAlex** [EarthMC/Issue-Tracker#237]
**Server**
Terra Nova

**Describe the bug**
The permissions don't work in towny.It are disabled and players from other towns can break blocks or open chests.When my towny were stolen I thought it was permissions,but when I set them off they can open chests.
**To Reproduce**
1. Set all town permissions off.
2. Call a player(or nation player) who don't  have permission.
3. And see if he can break blocks or open chests.
4. (The bug don't work with some chests)

**Expected behavior**
With disabled permissions the players from another towns in nation(I don't know with other nations players) can open Chests,Furnaces,break blocks,and take the itens.

**Screenshots**
A Screenshot can't explain,but I have a video: https://www.youtube.com/watch?v=S7nxo30g3ws

**Additional context**
The video Explain I think.

**Comment by KarlOfDuty** [comment]
It was probably your plot permissions that were wrong, not your town permissions. Please send a new video showing your `/t`, `/plot perm` on the plot you are in, and `/res` on your friend

**Comment by KarlOfDuty** [comment]
Please respond or your issue will be closed.
