### ISSUE TITLE
Bedrock Edition

### ISSUE THREAD

**Issue by AmirMorocco** [EarthMC/Issue-Tracker#239]
Dear EarthMC, I would love this server to be Bedrock Edition user friendly. Many users don’t have enough money to afford Java so they use Bedrock which is cheaper many players would be very happy to join your server without having to use a PC and play on it on their mobile and Xbox devices. 
Sincerely, Amir

**Comment by KarlOfDuty** [comment]
As far as I know there is no way to let Bedrock players join normal minecraft servers, sorry.

**Comment by AmirMorocco** [comment]
Is there any possible way to create a new EarthMC for Bedrock Edition

**Comment by KarlOfDuty** [comment]
I don't think worlds can be converted from normal minecraft to bedrock and even if that was possible there are basically no mods or plugins available for bedrock so it would just be vanilla minecraft at that point.

**Comment by AmirMorocco** [comment]
I have seen a map of the world in MCpedl but I understand how the whole
plugin stuff is hard to transfer.
Thanks for your time.

**Comment by AmirMorocco** [comment]
Sorry for the interruption but cross-play with Java and Bedrock is possible
including the plugins it just takes some time to install.
