### ISSUE TITLE
Combat plugin problems

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#24]
This plug has many problems but can probably be configured for the server's needs.  These are things we are experiencing.  
1.  when targeted by a mob outside a claim you can't run back to the claim but rather get spammed with this msg and bounced around violently for 30 seconds or so.  https://i.gyazo.com/decbf57683ce73a0881fd0f9a9b8a03c.png

2. anytime you jump down a few blocks you get this msg.  When building on my claim, I am again thrown out of claims and bounced around.  https://i.gyazo.com/65fd4b24aa65ebb806abde922dbf13b2.png

I know Fix said it would be worked on, but just giving specifics that might help for configuring it.

**Comment by Bezod** [comment]
Thanks for reporting. Combat plugin removed.
