### ISSUE TITLE
[Feature] Enable Double Smelt For Gold Read Before You Delete This Karl

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#240]
I know that you should know all the arguements for enabling gold for double smelt, honestly at this point a nerf to how much of gold the max percent is would be fine like maybe only half can double smelt, just as a comprimise, but still you should just plain out re-enable it, the staff are supposed to serve the rules and the rules are supposed to serve the players, but disabling double smelt is not serving the players, but you should've known these arguements before my main point is that most people actually want double smelt back just look at this poll https://www.strawpoll.me/17005961/r

Enable double smelt for gold

**Comment by KarlOfDuty** [comment]
Indeed, this brings nothing new to the conversation from the last issue. Just post there instead.

**Comment by Pengun78** [comment]
aaaaa

**Comment by BowShot118** [comment]
Fucking Hell Karl, what's wrong you with. Genuine question

**Comment by KarlOfDuty** [comment]
> Fucking Hell Karl, what's wrong you with. Genuine question

:thonk:

**Comment by MineHero43** [comment]
> > Fucking Hell Karl, what's wrong you with. Genuine question
> 
> :thonk:

Looks like Double smelt isn't the only thing that's disabled around here

**Comment by Pengun78** [comment]
oh god oh fuck
