### ISSUE TITLE
/ch trade

### ISSUE THREAD

**Issue by Zaspar** [EarthMC/Issue-Tracker#241]
Everyone knows that general chat is straight up cancer most of the time, so much so that muting it is the best option to take when it becomes extremely ass, or when you just want to mine/build. Doing so makes you miss out on trade offers, however. Since general is super crowded anyway, why not make a separate channel for trade offers? This would tremendously reduce the amount of clutter in general, and people who mute general would be able to stay in touch with trade offers.

**Comment by MSatrokrm** [comment]
Not a bad idea, however, there's already a discord channel dedicated for trades.
#trading

**Comment by NigelFarage666** [comment]
That discord is really bad as well because response is slow and not immediate.

**Comment by osnapitzjamie** [comment]
Just link #trading to the ingame trading channel if its added, problem solved

**Comment by NigelFarage666** [comment]
NO.
Response is slow. 
And people which usually respond join 2 days after.

**Comment by KarlOfDuty** [comment]
Done.
