### ISSUE TITLE
Dying by server lag and losing all of my stuff

### ISSUE THREAD

**Issue by JohnEricoJR** [EarthMC/Issue-Tracker#243]
**Server**
Which server the bug is on. The traveling through the ocean and you die from server lag 

**Describe the bug**
A clear and concise description of what the bug is. you go in a boat through the ocean and the server lags out and your in the void and dead

**Expected behavior**
A clear and concise description of what you expected to happen. not fucking dying in the fucking void when your floating on the ocean headed to Europe after spending 13 minutes

**Screenshots**
![image](https://user-images.githubusercontent.com/45521500/50177720-5ab46f80-02c8-11e9-91e6-d4d7ae7d7c07.png)

**Comment by KarlOfDuty** [comment]
This is for server changes, not support matters.

**Comment by KarlOfDuty** [comment]
We do not refund items lost to lag in any case. In the future make a support ticket instead.

**Comment by JohnEricoJR** [comment]
where the hell is that

**Comment by Arganog** [comment]
You can make a support ticket by typing -new in any of the EMC discord channels

**Comment by MSatrokrm** [comment]
rip John
