### ISSUE TITLE
[World] clay oceans

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#245]
Like in classic i think there should be some parts of the ocean where clay blocks lay on the ocean floor
on classic this was a thing at antartica, clay is really rare to find and i think it shouldnt be as there are 
people (like me) that use bricks alot

**Comment by NeonKrby** [comment]
also sand. add more sand.

**Comment by Pengun78** [comment]
just do /n spawn islamic_state and dig there

**Comment by NeonKrby** [comment]
Still should be underwater sand. Like in ®éál lífé

**Comment by Pengun78** [comment]
ah yea

**Comment by Pengun78** [comment]
@KarlOfDuty

**Comment by KarlOfDuty** [comment]
what

**Comment by BowShot118** [comment]
Re-enable Double Smelt :smile:

**Comment by NeonKrby** [comment]
no dont

**Comment by BowShot118** [comment]
REEEEEE

**Comment by PoppyK** [comment]
Clay no longer is generated on the bottom of the oceans.  Any clay that has been found that way was placed there by designers before the map opened.  I will look at adding clay to areas around the world, but probably not in the ocean.  https://i.gyazo.com/f2046658bd199cec790513a3dd63aa98.png
