### ISSUE TITLE
Ban Nether Portal Trapping

### ISSUE THREAD

**Issue by RoJoGuapo** [EarthMC/Issue-Tracker#246]
Nether Portal trapping puts people in a position where it is actually impossible to play the game. If the portal you are trapped in is in someone else's claim, you can not type, which limits you from asking a mod to teleport you out, or teleporting to your town spawn. Even if it isn't in claims, not having the right materials will get you trapped.

I read over the rule book and saw no rule about this. There is a rule stating the permission to tp trap, and someone can assume that this falls into that category, but portal traps make the game unplayable. This should be added next to the rule about tp trapping, and should warn people who make these traps.

I was a victim of one of these traps yesterday, and I had to wait for 40 minutes in the portal, because no mods were responding to my ticket.

**Comment by BowShot118** [comment]
*upvotes* :+1:
