### ISSUE TITLE
Separate chat for spanish people

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#247]
People starting to talk in spanish in this server can sometimes get annoying

**Comment by BowShot118** [comment]
It isn't annoying.

**Comment by Pengun78** [comment]
Deja que esas pobres personas hablen español tu monstruo

**Comment by 32Gold** [comment]
It isn’t annoying, just /ignore them

**Comment by FurdenFuhrer** [comment]
There aren't enough Spanish people to need a whole chat. 

The rules say to speak English if you can't speak English you won't be able to communicate with a majority of any game's player base.

**Comment by Coffeetom** [comment]
A new chat would just divide the community

**Comment by BowShot118** [comment]
I don't see the issue with Spanish and Swedish being spoken in general, a large amount of the playerbase speaks the languages.

**Comment by FenZenyatta** [comment]
> I don't see the issue with Spanish and Swedish being spoken in general, a large amount of the playerbase speaks the languages.

You either allow every language or english only. 
 Giving Swedish special treatment while for example Polish or Turkish wouldn’t be allowed sounds dumb

**Comment by BowShot118** [comment]
> > I don't see the issue with Spanish and Swedish being spoken in general, a large amount of the playerbase speaks the languages.
> 
> You either allow every language or english only.
> Giving Swedish special treatment while for example Polish or Turkish wouldn’t be allowed sounds dumb

It is a Swedish Server.

**Comment by Pengun78** [comment]
Fen is right

**Comment by 32Gold** [comment]
A large amount of the player base speaks Spanish and English, not polish and Turkish. This is a false equivalence

**Comment by FenZenyatta** [comment]
> A large amount of the player base speaks Spanish and English, not polish and Turkish. This is a false equivalence

Still, why would you give Swedish special treatment?

 This might be a bit harder to understand when the community build around your first language isn’t active, but I would still be really pissed if the Swedes were allowed to sing out their language in gc while polish would be made into a sin 😡 

The server is not even located in Sweden anymore, don’t let those peeps think they are more special than the rest of the server

**Comment by BowShot118** [comment]
Fix and Karl are Swedish. A lot of players, are Swedish. Just because the hoster a Swedish man paid for is in Germany doesn't mean it's Swedish.

**Comment by 32Gold** [comment]
I’m not even talking about Swedish bruh, I mean spanish and English

**Comment by FenZenyatta** [comment]
> I’m not even talking about Swedish bruh, I mean spanish and English

Swedish was brought into this when Pock mentioned it. I would be fine with Spanish being allowed, but allowing Swedish while not allowing other languages is a massive gay move tbh

**Comment by BowShot118** [comment]
But a larger portion of the server speaks Swedish then Spanish, so enabling Spanish would be a "massive gay move" :thinking:

**Comment by FenZenyatta** [comment]
> But a larger portion of the server speaks Swedish then Spanish, so enabling Spanish would be a "massive gay move" 🤔

The spanish community is active, creating Spain, La_Plata and planning on doing even greater things while being happy. Meanwhile Sweden is dead ass inactive dude. The Spanish dudes deserve it, Sweden doesn’t. That would be a masssivee gay move

**Comment by Pengun78** [comment]
Ya

**Comment by KarlOfDuty** [comment]
Yes, we may add channels for other languages that we have moderators for. We'll look into it.

**Comment by NigelFarage666** [comment]
Add Slavic chat!!!

**Comment by KarlOfDuty** [comment]
Done.
