### ISSUE TITLE
REMOVE THE BLOODY NEWBIE PROTECTION

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#248]
Ok I can understand 1 day of newbie protection,fine. But two? Are you kidding me? There are annoying newbies going through my town (this is THIRD time already) griefing crops and abusing their protection.
Not to mention griefers (IGZInfinityGame) who is REALLY good example of abuse.
Just remove it its gay and everyone hates it.

**Comment by 4noah18** [comment]
seriously this needs to be fixed its fucking broken

**Comment by KarlOfDuty** [comment]
Yes.

**Comment by KarlOfDuty** [comment]
It has been shortened to a few hours.
