### ISSUE TITLE
[Feature] McMMO Chimaera

### ISSUE THREAD

**Issue by osnapitzjamie** [EarthMC/Issue-Tracker#249]
This item allows you to teleport to your bed.
Basically its an advanced /sethome /home

all that is needed is to give everyone the permission
`mcmmo.item.chimaerawing`

We can already craft the item.

https://github.com/mcMMO-Dev/mcMMO/wiki/Chimaera-Wing

**Comment by NigelFarage666** [comment]
You understand you can already tp back to your bed?

**Comment by KarlOfDuty** [comment]
You should be able to use /res spawn to do that.

We don't want to add more teleportation things from other plugins as they should not respect tp cooldowns and delays.

**Comment by osnapitzjamie** [comment]
Please remove this function then by doing:
```
Items:
    Chimaera_Wing:
        Enabled: false
```

in the mcmmo config

**Comment by BowShot118** [comment]
Lol you can still res spawn. No point removing it

**Comment by osnapitzjamie** [comment]
> Lol you can still res spawn. No point removing it

its a useless item if it doesnt work, no need to have it as craftable
