### ISSUE TITLE
Add the nether or make it possible to get the resources from it

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#25]
I'd like to be able to primarily get soul sand and blaze rods but nether bricks and quartz would be nuice

**Comment by Arganog** [comment]
List of items available in the Nether:

Netherrack (Available from mcmmo excavation levels 850+, rare)
>Netherbrick (smelt Netherrack)
Quartz Ore
Quartz (available from mcmmo excavation, levels 850+, very rare)
Soul Sand (available from mcmmo excavation, levels 650+, rare)
Glowstone (available from mcmmo excavation, levels 80+ common)
Netherwart
Blaze Rods
Ghast Tears
Wither Skulls

https://mcmmo.wikia.com/wiki/Excavation

**Comment by KarlOfDuty** [comment]
We will have a solution for this before release of Terra Nova.

**Comment by KarlOfDuty** [comment]
Done.
