### ISSUE TITLE
[Mechanic] Add 1.13 Oceans

### ISSUE THREAD

**Issue by osnapitzjamie** [EarthMC/Issue-Tracker#250]
Please make the oceans spawn the 1.13 stuff. Its so plain and boring without it.

**Comment by NigelFarage666** [comment]
WE ALREADY HAVE 1.13 OCEANS!!!

**Comment by KarlOfDuty** [comment]
As the above comment says, we already have that.

**Comment by Pengun78** [comment]
Karl he means having sea grass kelp coral etc the oceans really miss such a big part of the 1.13 update in this server

**Comment by KarlOfDuty** [comment]
We cannot make that spawn, so no.

**Comment by osnapitzjamie** [comment]
> We cannot make that spawn, so no.

really? can you please look at an alternative way of doing it?

Its a massive feature. Its bad enough not having caves but the ocean is just a big dirt mess atm
