### ISSUE TITLE
Bring back outposts.

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#251]
Outposts are key part of towny.
Since there is no more /t spawn to other towns why not adding back outposts? Seriously why not?
We could create trading posts and towns which are non capitals would be able to trade easily between each other.Many parts of the nation which are too far away from capital would be again connected. 
And of course for us Europeans colonies. Since there is nation range we aren't able to set up towns in areas which were previously part of (Insertnationname) Empire. We would finally be able to create colonies and bring some sort of new colonial era to the server.I believe this would develop Africa as well.

Now I remember problems with old outpost system people would usually abuse them for claim blocking or annoying other nations. 
My suggestion is that we rise the price of outposts to more like 128g and limit number of them per town to 2. (or even 1) 

Thank you for reading and Merry Christmas!

**Comment by Pengun78** [comment]
Outposts were disabled so people wouldnt claim the good spots with outposts
All the good spots are now taken and i also think they should be enabled again

**Comment by NigelFarage666** [comment]
Agreed!

**Comment by NigelFarage666** [comment]
I understand. 
Thank you for your feedback Karl! 

btw Do you maybe know when will official 1.13 version of towny come out? 
Just askin :P

**Comment by EchoOcelot** [comment]
Will outposts be 500 gold like they’re currently set to in /towny prices, or will they be lowered?

**Comment by NigelFarage666** [comment]
They should be lowered 500 is just too much.

**Comment by NSGamer** [comment]
I think they should cost 48G, slightly more than before. Also the limit could be on 8 or 10 outposts like before. I don't see why not to have many outposts, after all if one is breaking the rules people could just report it. The price is also normal, after all gold is much rarer on the server now, don't make outpost price a torture, we already got a nation price which is a damn torture.

**Comment by NigelFarage666** [comment]
I actually agree with NS.

**Comment by BowShot118** [comment]
2000g outpost when

**Comment by NigelFarage666** [comment]
NO not 2000g please no Pock!!

**Comment by Sulakek** [comment]
One thing is that i think outposts should be more expensive.
And also an outpost range could be interesting aswell

**Comment by DanteB420** [comment]
I think outposts with the enforcement of the no claim blocking rule would be good to have

**Comment by Ultil0l** [comment]
outposts more like inposts

**Comment by Pengun78** [comment]
what

**Comment by KarlOfDuty** [comment]
We will not be re-adding outposts at this time as they were almost exclusively used for claim blocking in the past.
