### ISSUE TITLE
[Feature] Discord nation chat

### ISSUE THREAD

**Issue by osnapitzjamie** [EarthMC/Issue-Tracker#252]
Allow us to link nation chats to our discord servers

Make a second bot that anyone can invite to their server and then setup.

**Comment by KarlOfDuty** [comment]
That is not possible.

**Comment by osnapitzjamie** [comment]
It is.

I've done it on other games before.

I'll just make my own in that case.

**Comment by NSGamer** [comment]
Woah, that would be lit @osnapitzjamie

**Comment by osnapitzjamie** [comment]
> Woah, that would be lit @osnapitzjamie

would only be for my nation, i cant do it for others using my method, sorry.
