### ISSUE TITLE
[Mechanic] PVP Forced on towns & anti warlog plugin

### ISSUE THREAD

**Issue by bapsachiko** [EarthMC/Issue-Tracker#253]
Currently, nothing matters on the server. There is no pressure to do anything, one way or the other.
Take us for example. We have the stockpiles and books and farms to create multiple sets of prot 4 if the need ever arose, but there is nothing forcing us to make it. So the stockpiles sit, and the work done to accumulate them means less as each day passes. We can focus on building, but only for so long before that gets tiring - especially with claim limits and gold costs dissuading expansion somewhat.
If that was because we joined and were incredibly isolationist, or remote, that'd be our problem.

But we haven't been, lots of our guys have antagonized lots of others. Instead of that meaning anything, we collect a series of frivolous enemies. They can't war us, they can't raid us, and if they catch one of us far from home, they can't kill us.
We can declare war on a nation and sit in our claims all day if we wanted that, everything we have to do can be made inside our no pvp zone, the only reason we would ever think of exiting it would be mining but depending on the size of the town as ours is big enough we can sit inside it all day and mine inside our own claims with no risk of dying.
But what if we dont have enough claims? We would teleport to a allied nation and mine there.
War is off, so our buildings or resources can't be threatened, pvp in claims is our choice, so we can easily circumvent raids, and theres no anti-combat logging plugin, any threat outside of claims is made trivial by disconnecting.

Whoever is being attacked controls whether or not combat happens
Meaning we can't forcibly unify our country, because we can't actually affect the other guy, meaning there is no pressure for them to do anything in a geopolitical sense.
Meaning we can accrue as many enemies as we like, because we control whether they're a threat.
That means we always control our situation. Nothing can pressure us, because there is no way to apply pressure. Nothing can incentive us because there is nothing to benefit from by trading or allying.
Without pressure you get only stagnation, and stagnation leads to player count slowly falling.

The solution we want is for PVP to be possible by having it turned on inside towns & a combat log plugin, it would force people to rethink their alliances and wars.
No one knows if a proper war plugin will be released soon or if ever, this is the simplest thing that could keep the server alive and intresting in the meantime.

**Comment by NSGamer** [comment]
Fuck combat log because everyone has combat logged once and it's normal if you don't wanna lose your stuff, it can be taken as a soldier less in the battle anyway. But I agree with PvP being turned on in town for your enemies.

**Comment by BowShot118** [comment]
Logging is part of life.
I've only had bad experiences with pvp plugins.

**Comment by DanteB420** [comment]
I think a territorial/war addition should definitely be added. Along with a combat logger. If there is no risk then what would dissuade someone from engaging in a fight or making enemies with someone. There is no political pressure in this geopolitical sanbox. War is a huge part that should be added.

**Comment by BowShot118** [comment]
I support the idea of forcing town pvp; but I hate the idea of land being transferred to another person/town.

**Comment by Kyoris** [comment]
I mean we could make it so if side A loses to side B, they have to pay side B some amount of gold and be blocked from fighting for say a week.

**Comment by BowShot118** [comment]
Ew no. Don't force people to pay gold via the game mechanics. Leave that to ingame diplomacy

**Comment by Kyoris** [comment]
that's fine, but at least give them like a ceasefire so that they cannot fight anyone unless directly attacked

**Comment by Pengun78** [comment]
i really want this to be added but of course only to enemy nations
it's fine because if u don't wanna fight u can just hide in ur house problem solved
please add this gamer boys

**Comment by DanteB420** [comment]
I used to play another game where land owned was a thing, but they wanted it to be fought over. The way the did that was when a base was created, they set a vulnerability window which it can be attacked. I feel like this is something that could be implemented in the server with wars. Like when someone declares war they would agree on a day, and then on that day the server is only open to those who are at war, (for lag) and then they fight it out. I dont know how this would be implemented directly, but its something to think about

**Comment by NigelFarage666** [comment]
This is true we need all this 

Lol you must be a reall faggot that you need to combat log seriously
Deal with dying kid we all died many times before becoming good in pvp.

**Comment by BowShot118** [comment]
Wtf, this aint factions. Land claims gotta stay out of this.

**Comment by Pengun78** [comment]
Agreed i think pvp should just be enabled in claims of every town inside an enemy nation they can just take shelter if they dont want to fight

**Comment by FurdenFuhrer** [comment]
I think pvp should be enabled in towns no matter what not just with enemies. If you don't want to fight then just go into a house and teleport to an allied capital and go mining for a bit.

**Comment by Pengun78** [comment]
Nah not that, that would just be annoying
Maybe u got some people u wronged in the past they'll attack u 24/7 what will u do

**Comment by FurdenFuhrer** [comment]
Build a wall

**Comment by Pengun78** [comment]
That makes the town ugly

**Comment by DanteB420** [comment]
What happens when there is no more land? theoretically

**Comment by Ultil0l** [comment]
@DanteB420 Just make new land

**Comment by KarlOfDuty** [comment]
We will not be doing this as we have tried it in the past and it just let toxic players spawn camp everyone.

**Comment by Magenent** [comment]
> We will not be doing this as we have tried it in the past and it just let toxic players spawn camp everyone.

Yes but we need some sort of meaningful war system where one nation clearly wins and one nation clearly loses.

**Comment by Magenent** [comment]
> We will not be doing this as we have tried it in the past and it just let toxic players spawn camp everyone.

Considering the trouble of not being in a nation I do think it'd be fair ONLY for nations, so you could not be affected if your not in a nation.

**Comment by bapsachiko** [comment]
Amazing, ignoring everything I wrote and just saying its toxic.
Remove "geopolitics" from your site frontpage then cause I wasted two months on something that should infact be called a building server.
