### ISSUE TITLE
The server lag killed me and I lost everything in the void

### ISSUE THREAD

**Issue by fflip8** [EarthMC/Issue-Tracker#254]
My user is fflip8, and I just joined and was riding a boat in the ocean for quite some time after spending a day mining and gathering materials to start a town, as well as voting. I think I had 16 gold on me (I voted, and mined 6 ingots).
I also had some jungle saplings, oak saplings, a birch sapling, spruce saplings, melon seeds, pumpkin seeds, around 5 stacks of redstone, about a stack of emeralds, about 32 iron, a couple stacks of coal. I think I also had almost a full stack of lapis too. 
I know that my inventory was completely full when I died, and would appreciate if I could get my inventory back, or at least replaced, because I didn't die due to my error. I was simply just traversing the ocean when the world went black and I fell into the void.

**Comment by Coffeetom** [comment]
Do -new in the discord. However I think staff have said that they need proof of items, otherwise they don't do refunds. I'm not sure tho.

**Comment by KarlOfDuty** [comment]
As the others have said, this is a support matter, but we do not refund things lost to lag in any case.
