### ISSUE TITLE
My war system idea.

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#255]
Yes my feature is related to a problem.
Many people wish for a new war system and I have came up with something VERY simple and used before.
I think that taking land and land capture in towny would be pointless especially on a server like this and would drastically change whole gameplay.
Thats why I find it bad.

My idea.
------------------------------------------------------------------------------
This was used before on few war days. 
So, first nations need to enemy each other which would start a war once that happens if Enemy Troops are close to any nation city and if there are active people in that town/city Explosions and Pvp  get toggled. 
As we can see Explosions get automatically rollbacked and this feature would stop people from just hiding in their houses or even underground. 
IMPORTANT if possible chests should not be able to get BLOWN! 
This way towns will be brought to knees because their armies will not be able to hide from pvp in claimed land or even hide in the houses and I believe wars would decrease because nations would understand the risk and people would not be griefing anymore since they can just bomb the town in middle of a battle.
This would make everything more fun and realistic for many people and less dependant on pvp skills.
And wars would finally make sense.

**Comment by NigelFarage666** [comment]
Its really simple can make damage but still cant destroy town completely and isn't complicated.

I think I would save staff from hard work programming and idk what else

**Comment by NigelFarage666** [comment]
No thats terrible.
Destruction is temporary and I don't see how it would crash the server.
What civilians? This is minecraft are you insane? 
No I never tried that because I don't care if I die in a bloody block game.

**Comment by NigelFarage666** [comment]
This worked before on the server and has never crashed it and If you don't want to pvp just go to another town or something.

**Comment by BowShot118** [comment]
I am not on about the plugin crashing the server, the server has crashed on its own and is laggy at peak times. The destruction may not be rolled back if the server crashes during a "raid". If people don't want to fight, don't force them to fight. My issue is when people come out for a fight and go and hide when they start to loose. War plugins, especially on servers with toxic communities, is just a way to be a toxic shit towards people you don't like.

**Comment by NigelFarage666** [comment]
Pock It seems like you dont understand towny.
Read what I have said and stop commenting shit.
Bloody newbie.
"If nations enemy each other" 
That means that both of nations have to enemy each other for example Spain has to enemy Nazi Germany and Nazi Germany has to enemy Spain that was you can decide do you want to go to war or NOT.
But yeah go ahead and comment shit

**Comment by NigelFarage666** [comment]
And its not plugin explosions already automatically rollback.
it wouldn't be anything new

**Comment by BowShot118** [comment]
> And its not plugin explosions already automatically rollback.
> it wouldn't be anything new

Not for TNT

And it is still a way for Toxic communities to target people they don't like. Not everyone is a nation leader and not everyone in a nation wishes to partake in the war. If you want this so much go play a fuckin' factions server.

**Comment by NigelFarage666** [comment]
"Not for TNT"
Do you even play?
TNT is the thing iM talking about it IS ROLLBACKING we just used it in NEW MADRID it has all ROLLBACKED

Yes not everyone wants war so? 
People are still getting attacked point of war system was so we can destroy those who keep hiding in claims.
Because of annoying people like you we can't have a proper war.
And many nations are democracies for example Wabanaki and France.
And attacks usually happen only on capitals.
If you dont want to get killed just leave your town and when outposts get added back it will be even easier.
Its good and simple war system but I see you wouldn't like a single idea anyways.

**Comment by Ultil0l** [comment]
@BowShot118 dude people are starting to want to quit emc bcs its boring

**Comment by BowShot118** [comment]
Staff do rollback things xd
as I stated, it's a towny, not a faction server. If both sides are willing to fight then they'd come out to fight. All we'd see is people not /n enemy-ing or people sticking to this version of war by not enemy-ing them back. The community will just adjust, there server is too laggy rn and it would cause a lot of people becoming rather annoyed. If people don't want to come out and fight, why make them fight. Especially in instances were the person being attacked is the respondent and not the aggressor. Again, this aint a factions server. No one should be dragged out and get toxic shits, like yourself, blowing up their town when they have no clue what's going on because they either don't have discord or haven't been told of the "war." This would just increase a cycle of hate as relatively new players' only experience with certain people is being unnecessarily attacked.

**Comment by Ultil0l** [comment]
and this isnt just a towny server this is a geopolitical towny server bow

**Comment by Ultil0l** [comment]
if new players get stuck in war, too bad

**Comment by BowShot118** [comment]
> @BowShot118 dude people are starting to want to quit emc bcs its boring

I'm wanting to quit because it's boring, I'm barely on. I enjoy pvp but not the unneeded toxicity surrounding a war plugin. This was tried on Tailz's old meme server and all it did was see larger groups picking on smaller groups. It's bad. If two groups are genuinely committed to a destructive war then they should approach staff on a case by case basis instead of people being flung in un-needed.


> and this isnt just a towny server this is a geopolitical towny server bow

It doesn't require a war plugin and the emphasis of this is on towny. All this does it bring back nightmares of the harassment during the Sorongese Independence war and it aint something people should be stuck into. Toggling pvp is fine for me, but not allowing explosions, temp or not, because many newer players wont understand what's going on smh.

**Comment by Ultil0l** [comment]
and? new players already dont understand whats going on...

**Comment by BowShot118** [comment]
> and? new players already dont understand whats going on...

There's no need to exclude newer players for no reason, server's toxic enough. If we wanted toxicity it'd be Praxis that we'd be on and not EarthMC.

**Comment by Ultil0l** [comment]
I read about praxis and that was a whole other level I believe

**Comment by BowShot118** [comment]
I had more fun on their server then this one for a lot of my time here. I actually enjoyed it as there wasn't the constant random hate in chat, unlike EarthMC. 
But I've drifted off-topic. I still believe that a destruction based war plugin is a bad idea.

**Comment by NigelFarage666** [comment]
Staff do rollback things xd

NO STOP IT
STOP SAYING BULLSHIT ITS OBVIOUS YOU DONT KNOW A THING

Its boring without a proper war.
IT GETS TOGGLED ITSELF FOR FUCKS SAKE DO YOU EVEN LISTEN TO ME? 

This is pretty much the BEST war suggestion.
Its based on toggled pvp in towns and explosions won't even be destructive tnt rollbacks in less than a minute you can even hide in underground bunker. 
Point of tnt is to break walls so people stop pussying out in their forts and houses once pvp is toggled.
You can't even lose land....And staff can do it REALLY easy its best and LEAST painful suggestion.
I was quite rude in the beginning of this conversation I'm sorry for that but PLEASE think about what I just said.
and AGAIN you can just go to your outpost where you will be safe ANYWAYS only thing you can lose are things in your inventory! 

And this HELPS staff because its MUCH easier to make and LESS risky for the community as whole!

**Comment by KarlOfDuty** [comment]
Keep this discussion civilised.

**Comment by BowShot118** [comment]
Wooah calm it mate, and I stand by that I believe it's a bad to include destruction in the plugin.

**Regardless of whether it is being rolled back or not**

**Comment by NigelFarage666** [comment]
"Regardless of whether it is being rolled back or not"
You do understand that those explosions main purpose is to kill players if they hide in house? 
Their purpose isn't to destroy a town but to make fights realistic because toggling pvp ON won't make war system better It won't fix the issue.
People will just go in houses or on top of them and hide there.
Its pointless.
But if explosions get added people will enter be able to kill ones who are hiding but still want to fight and battles would actually make sense they would be a bunch of pvp toggling or in this case house hiding.
People who will not want to fight will be able to get to their outposts.

Those explosions will NOT be destructive and their MAIN purpose is to stop house hiding.

**Comment by Pengun78** [comment]
nigel in the name of love calm down!!!!!!!!!!!!!!!!!!!!!!!!!!///

**Comment by NigelFarage666** [comment]
I am calm.
I'm just explaining.
Using caps doesnt make me "angry".

**Comment by BowShot118** [comment]
Builds are designed to keep people out. I stand by **my opinion** that using explosions of any kind is a bad idea. And you can't toggle pvp when you got non residents in claims.

**Comment by NigelFarage666** [comment]
Point of the war is to make people fight not hide in their claims.
Thats the purpose of war system.

**Comment by BowShot118** [comment]
And toggling pvp will do just fine. If they wish to leave the fight but can't toggle pvp, go into a house or behind a wall. It brings a close to it all and is an effective and semi realistic way of ending a battle.

**Comment by NigelFarage666** [comment]
Pock.
I agree I love walls and I love forts! I love bow fights! 
I will tell you something.
I just fought a battle in New Madrid it was Nazi Germany (Perpignan vs Spain) people wanted to fight they really did but thing they didn't want to is die. Thats why they kept running in claims! Thats why we need tnt to destroy houses which will be future claims.
There are times when I didn't want to fight and thats when I just joined the game however people were not attacking me but as I said people can run to outposts which will be safe or even bunkers which will make the enemy leave.

**Comment by BowShot118** [comment]
And forcing a pvp toggle would settle that happily. No need to blow up the houses

**Comment by NigelFarage666** [comment]
I don't think so. People will just hide to houses lol and its not really blowing up tnt is hard to get when there are almost no mobs its so that people cant just hide in the house.
Again it toggles in less than a minute its main purpose is to break walls.

**Comment by BowShot118** [comment]
Again, I believe that a toggle of pvp is enough and nothing more is needed

**Comment by NigelFarage666** [comment]
I will just stop here my point is obvious so is yours  we will let people to decide.

**Comment by Ultil0l** [comment]
Tbh we should still have "safe zones" for people who really dont want to fight

**Comment by 4noah18** [comment]
"and less dependant on pvp skills." Why the hell do people insist on supporting the lowest common denominator. If someone is good at something don't fucking ban them because you're not. Get better at the game.

**Comment by Kyoris** [comment]
I think there should be no safe zones for anyone in participating nation's, since it's a risk that EVERYONE has to take; basically leave the nation for a safer one if you don't like the turmoil in the region. Also no teleports just to keep it from being a game of chase.

**Comment by Pengun78** [comment]
How about healing? U need to heal somewhere i get to 4 hearts in a 6v1 in notime

**Comment by NigelFarage666** [comment]
Indeed Splash Health II potions are always good.

**Comment by NeonKrby** [comment]
Losing nations should be able to be puppeted and have the leader replaced with someone else loyal to the winning nation.

**Comment by NeonKrby** [comment]
Or be able to be annexed and the captured capital city could be used as a nation range extender.

**Comment by KarlOfDuty** [comment]
Any war system ideas should be sent to someone who would actually want to develop one, they don't do much good here.
