### ISSUE TITLE
[Feature] Swedish chat.

### ISSUE THREAD

**Issue by Wextra** [EarthMC/Issue-Tracker#257]
As we've recently gotten a chat for the Spaniards, I think it would also be wise to get a chat for the Swedes.

1. The amount of players who speak Swedish is greater than the amount of players who speak Spanish.
2. Many of the staff members are Swedish so the chat can be moderated.
3. Not all Swedes do speak English, many of the new Swedes who join the server are pretty young and barely knows English.

I'm not the only Swede who wants this, and before people come with stereotypes or negative comments, please be civil and actually read and understand the reasons why I support this idea.

**Comment by BowShot118** [comment]
:+1:

**Comment by Pengun78** [comment]
in swedish chat there will be people laughing with capitals everywhere

**Comment by Wextra** [comment]
Well, I know of no Swedes who laugh in capital letters and if it is too big of an issue you could just /leave the chat.

**Comment by Pengun78** [comment]
I will annex sweden

**Comment by NigelFarage666** [comment]
Im not Swedish but I think that would be just right.

**Comment by BowShot118** [comment]
While we're at it, we need a channel dedicated to our Lord and Saviour, Syn(argle)

**Comment by Sulakek** [comment]
while you're at it, why not just make a Danish chat too I mean there's a nation in Denmark that has real Danes on it.

**Comment by BowShot118** [comment]
We should include a chat for 'hull speak'. After all, we got a staff member from hull!

**Comment by MineHero43** [comment]
I’m still waiting for my German chat and while we’re at it let’s add a Slavic chat (I saw people suggesting it a few days ago) never mind that people can use /tc /nc or /party chat.

In all honesty I think we should add chats for all minority languages on emc, more useless channels that can’t be seen from discord and either abused or not used correctly in game.

**Comment by BowShot118** [comment]
I got an idea, group them all together into a Non-English channel 
Issue solved

**Comment by Wextra** [comment]
The thing is though, not all languages can be moderated as there are no staff members who speak those languages, but for example Swedish (Norwegian and Danish is almost identical to Swedish) and Spanish can be moderated because there are moderators that speak these languages. Therefore I think we should add a Swedish/Nordic chat.

**Comment by Magenent** [comment]
We need to add a Somalian chat or I will hack in free gold.

**Comment by KarlOfDuty** [comment]
We will not open any more channels at this time, the current ones are just for testing the system and we want the developers to resolve a bunch of issues before we add any more.
