### ISSUE TITLE
Inactivity Time needed for a town to disband

### ISSUE THREAD

**Issue by Caeso2** [EarthMC/Issue-Tracker#258]
There are high priority areas that many players want but are taken, such as major cities or areas in their nation boundaries. The problem is many of these areas are claimed by inactive players. Due to this the pace of the server is slowing down to a halt because all wanted areas are claimed and it takes 40 days for someone to get kicked from a town. I propose to reduce the time down to 20 days and special exceptions could be made like if someone from a single person town is going on a trip but will be active again. Also this will result in more accurate nation population totals.

**Comment by NigelFarage666** [comment]
Exactly I hate that sort of situation in Netherlands.
They are FULLY inactive and still major Cities like Amsterdam and Rotterdam are taken.

**Comment by Pengun78** [comment]
Lower the inactivity counter thing to like 12 days
Running a town but not being online for 12 days isnt something someone would do that cared about his town

**Comment by BowShot118** [comment]
30 days max. I've been on holiday for 2 weeks while playing the server. Would've been an awkward end to the IU

**Comment by Pengun78** [comment]
Lol true

**Comment by Caeso2** [comment]
Yeah bowshot I think that why 20 days is go because usually the longest vacations are 2 weeks and if it was longer which would be really rare, you could let staff know

**Comment by Kyoris** [comment]
2-3 weeks seems fair, and for special cases you could always tell staff

**Comment by Caeso2** [comment]
Well that is unfortunate but I still think it should be set to between 2-3 weeks

**Comment by BowShot118** [comment]
30 days

**Comment by DanteB420** [comment]
i think 14-20 days is perfect. With exceptions made to those away for long periods of time. Its not hard to get discord on your phone and hit up a mod "hey im going to be away on vacation for a month"

**Comment by Coffeetom** [comment]
As said by Karl above mods can't change it for individual towns
I think it should be 30 days so only truept inactive towns are kicked. People can go on 3 or 4 week holidays so something like 14 days is impractical

**Comment by MineHero43** [comment]
The one on classic worked fine, 42 days

**Comment by BowShot118** [comment]
30 days Minimum

**Comment by MineHero43** [comment]
Also another thing, these timers don’t delete the towns themselves but rather purge the mayors from the towny database.

If you think adding a timer will free up space claimed by a large town with an inactive mayor who doesn’t build, think again.

As I said above, mayors will just log on every now and then to reset the timer as adding one encourages such behaviour.

And furthermore, if a mayor is purged, the rank is passed on to the next person in the town and so on. You’ll be waiting a damn long time, maybe forever.

These timers mostly delete small towns mostly 1 - 3 chunks ran by new players who get bored.

**Comment by epicsans2003** [comment]
Timer needs to be shorter. 41 days just to wait for an inactive 2 chunk town is just ridicilious.

**Comment by NeonKrby** [comment]
Also Nation decay needs to turn back on.

**Comment by NeonKrby** [comment]
Finland needs to fucking collapse.

**Comment by Sulakek** [comment]
30 days is quite enough time in My opinion
there's already a town called genova that has been inactive for such a long time. I'm still waiting it to die so I can get one from my nation to claim it and make it a much better place.

**Comment by epicsans2003** [comment]
Eagle said today that it actually takes 60 days since towny files of the resident are deleted after 60 days. Sounds like some and hands down Eagle is after all possibly retarded so I wouldn’t trust him too much, but still he denied my request for a 2 chunk town that hasnt had a single member online since 4th of November. I aint waiting 100 days for a dumb town to disappear so I can let my friends make one there

**Comment by BowShot118** [comment]
No

**Comment by Caeso2** [comment]
Vichy is a Nazi annoyance in the middle of France, the mayor is banned and I doubt the other members will continue to play. Another town is completely inactive but the leader logged on for no reason somewhere between 30 and 40 days of inactivity and now we have to wait 40 more. The time is far too and the positives greatly out way any potential accidents

**Comment by Ultil0l** [comment]
Hit or miss

**Comment by BowShot118** [comment]
I guess they never miss huh

**Comment by Ultil0l** [comment]
You got a boyfriend

**Comment by BowShot118** [comment]
I bet he doesn't kiss ya

**Comment by Kyoris** [comment]
Mwah

**Comment by Pengun78** [comment]
He gon' find another girl and he wont miss ya
