### ISSUE TITLE
[Plugin] Anti portal trapping plugin

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/Issue-Tracker#259]

**Comment by Sulakek** [comment]
No description?
what is this post???

**Comment by KarlOfDuty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Anti portal trapping plugin](https://trello.com/c/FjkrsLGS/34-anti-portal-trapping-plugin)

**Comment by Warriorrrr** [comment]
Okay karl

**Comment by KarlOfDuty** [comment]
Best
