### ISSUE TITLE
[Feature] A Slavic or Polish Chat

### ISSUE THREAD

**Issue by Mihailovi** [EarthMC/Issue-Tracker#260]
Now that the language rules have been made clear and there is a channel for Spanish and a petition for Swedish, we should have a channel for the Slavic members of our EMC community, which is growing.

We have many Polish speakers and handfuls of people that speak Russian, Serbo-Croatian, Slovenian, Czech and it would be a good addition to have a language channel for speakers of these languages. It would also be a good thing for new players that speak Slavic languages and/or don't know English well, it could be a place where they can get help from other native speakers. A Polish or Slavic Languages chat would keep all, against the rules, Slavic chatting out of the General/English chat and provide a place for it to be.

Several Poles have stated in their discord that they would use such a channel and a few others, including myself, would use it if it's open to other Slavic languages as well.

**Comment by NigelFarage666** [comment]
Fuck, yeah I Slavic chat is a thing we need!

**Comment by BowShot118** [comment]
While we're at it, we need a channel dedicated to our Lord and Saviour, Syn(argle)

**Comment by FurdenFuhrer** [comment]
Wenn wir einen slawischen chat brauchen, sollten wir einen deutschen chat haben!

**Comment by Mihailovi** [comment]
>           Wenn wir einen slawischen chat brauchen, sollten wir einen deutschen chat haben!

Then make your own "issue" page and propose the idea if you wish.

**Comment by KarlOfDuty** [comment]
We will not open any more channels at this time, the current ones are just for testing the system and we want the developers to resolve a bunch of issues before we add any more.
