### ISSUE TITLE
Religion Plugin

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#261]
I feel like we need a religion plugin.

Long Live Syn(argle)

**Comment by Pengun78** [comment]
Ok nvm i want it

**Comment by FurdenFuhrer** [comment]
I'm for the religion plugin

**Comment by Pengun78** [comment]
I wanna make my own religion tho

**Comment by FurdenFuhrer** [comment]
Yea you would have to let the players make their own religions and have like religious altars and shit

**Comment by Ultil0l** [comment]
lets be honest
Emc is at least a semi rp server
we need religion or else I make ReligionMC

**Comment by NigelFarage666** [comment]
No thats just gay and cringy and would completely ruin EMC.
Go to PMC with that shit.

**Comment by Sulakek** [comment]
crusade? hm..
no really this is a kinda maybe good plugin,the only question is where you would get that plugin from and how does it effect the server? will it crash the server or will it make people too overpowered?

**Comment by FurdenFuhrer** [comment]
How would adding a religion plugin make people over powered?

**Comment by FurdenFuhrer** [comment]
It just adds another aspect that you need to think about

**Comment by Sulakek** [comment]
overpowered as in religious buffs as i played on another server in which they had stupidly weird buffs to religion.

**Comment by NeonKrby** [comment]
Im only for it if we can make Synism

**Comment by Ultil0l** [comment]
inb4 if we add this there will be 11 catholic churches

**Comment by NeonKrby** [comment]
inb4 if we add this there is already Shinto Shrines.

**Comment by FurdenFuhrer** [comment]
Players have already created religions and there have already been religious conflicts adding a religion plugin (maybe Karl could get creatorfromhell to make a simple one?) would just overall be a good addition and will add yet another thing you would have to worry about within your nation to keep it together. Religious differences can now exist and should be able to be publically seen with something like /ReligionList where you can see all of the existing religions and using the name of religions like /CatholicList or /ShintoList to see who is in those religions. Anyway, we would need Karl & Fix to see this before we start talking specifics to see if they would even consider adding a religion plugin that gives no buffs to players and is just for show.

**Comment by LoganCreeper50** [comment]
I agree. With the amount of new religions and the returning old ones it will add a new aspect to EarthMC. It would add more conflicts and have other reasons to go to war. You could 'convert' areas and do other stuff.  If EarthMC gets a religion plugin it would make it a bit more fun.

**Comment by BowShot118** [comment]
Is it a bad time to mention that I opened this as a meme?

**Comment by Ultil0l** [comment]
probably

**Comment by Pengun78** [comment]
Lol i think its a good idea tho

**Comment by NeonKrby** [comment]
Up caret

**Comment by AlexGamerYTT** [comment]
Agreed.

**Comment by KarlOfDuty** [comment]
We will not add this as it is an extra strain on the server which will likely not be very useful to players.

**Comment by BowShot118** [comment]
f in the chat
