### ISSUE TITLE
European Rivers

### ISSUE THREAD

**Issue by NigelFarage666** [EarthMC/Issue-Tracker#263]
Missing Rivers or not properly done rivers are:
-Rhone 
-Ebro DONE
-Rhine DONE
-Tajo DONE
-Duero
-Guadiana DONE
-Danube
-Seine
-Dorogne
-Gorone

-All of those rivers should be expanded and widened.

![alps](https://user-images.githubusercontent.com/44730188/50564299-21e2b480-0d24-11e9-9150-267c9612d4b7.png)
![european rivers](https://user-images.githubusercontent.com/44730188/50564449-35424f80-0d25-11e9-89be-0be752f60a42.png)

**Comment by Ultil0l** [comment]
yes

**Comment by NigelFarage666** [comment]
Thank you Ultil! I just want them to be more visible and able to drive through.

**Comment by Ultil0l** [comment]
epic

**Comment by Mihailovi** [comment]
Columbia River as well

**Comment by BowShot118** [comment]
River Syn aswell

**Comment by epicsans2003** [comment]
Elbe starts in North-Eastern Bohemia yet here it starts outside of the Czech Mountain Border in Germany. Vltava is also missing :shrug:

**Comment by PoppyK** [comment]
Rhine is done.  1/19/19

**Comment by PoppyK** [comment]
Ebro is done. 1/21

**Comment by PoppyK** [comment]
Guadania is done as far as I can take it without running into rail.

**Comment by NigelFarage666** [comment]
PoppyK thank you! you are such an awesome mod!

**Comment by Pengun78** [comment]
Poppy isnt a mod

**Comment by NigelFarage666** [comment]
Oh well he is nice :P since he does all that nice world editing work!

**Comment by Pengun78** [comment]
its a girl lol
