### ISSUE TITLE
Publication Chat

### ISSUE THREAD

**Issue by Sulakek** [EarthMC/Issue-Tracker#264]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated that people announce their own public bank or new monument on the Trade and Spanish chat.

**Describe the solution you'd like**
I wanna make a new chat called Publication Chat and it can be used for all sorts of things, like towns recruting people,world events and much more realistic mass communication.

**Additional context**
This is one example, of a National bank in Romania being Established is more fitting for The Publication channel 
![newthing](https://user-images.githubusercontent.com/44275134/50576516-86c90800-0e13-11e9-8d04-02c77a8ef181.jpg)

Thank you for reading this,I mean it's a small feature but every small feature matters.

(EDIT: Thanks to NigelFarage666, I will note that the publication chat is not for spamming nor toxicity and other types of words that breaks the following rules of Earthmc,The Publication Channel is only for serious public announcements)

**Comment by NigelFarage666** [comment]
I agree.
And btw I suggest Spansh and all language chats get deleted they are used for mass spam and no one is really speaking Spanish in it.
This could really help!
And I suggest rule that is against typing pointless things in chats where it doesnt belong to.
Like I can see 32gold typing "fuck you Nigel" in Publication chat.

**Comment by MineHero43** [comment]
I really don’t see the need for any new chats to be honest. I still don’t get the point of the spanish chat, Nigel already voiced my concerns above.

Adding a new chat for publications just fuels the problem and most likely will easily get misused, as again it can’t be seen from discord and players will most likely use it to spam or whatnot.

I don’t really see what’s wrong with publications in general chat, people still see them no matter how filled up the chat is.

**Comment by KarlOfDuty** [comment]
At the moment we are just testing out the multiple channel system with the spanish and trade chats, there are many issues with it we would like to get resolved by the towny developers before adding any more channels.
