### ISSUE TITLE
change golden carrot to iron carrot

### ISSUE THREAD

**Issue by osnapitzjamie** [EarthMC/Issue-Tracker#265]
change the crafting recipe to make potions easier

**Comment by BowShot118** [comment]
Objection, mining

**Comment by NeonKrby** [comment]
Objection. Night Vision Potions and Invis Potions are gay.

**Comment by NigelFarage666** [comment]
Hey Polish guy quit making dumb posts and give staff some time.

**Comment by NSGamer** [comment]
Statement: This post is stupid, let it die, meatbags.

**Comment by KarlOfDuty** [comment]
We will not add this recipe as we think the cost of the current one is fine.
