### ISSUE TITLE
Enable "The End" 

### ISSUE THREAD

**Issue by ArepaConMayonesa** [EarthMC/Issue-Tracker#266]
Hello.

I think each continent can have various "End Portals", and there could be a rule where people cannot claim chunks near it; if you want to avoid any problems with people taking over the portals and not letting other players go to "The End".

**Comment by BowShot118** [comment]
Yes

**Comment by RoJoGuapo** [comment]
Yes Please, because I want to start using end bricks to build with but I have no access to them

**Comment by NigelFarage666** [comment]
Yes I really have dire need for elytra.

**Comment by Sulakek** [comment]
**ew elytras**

**Comment by NeonKrby** [comment]
I believe that if dungeons ever come out end portals will be in them.

**Comment by KarlOfDuty** [comment]
> I believe that if dungeons ever come out end portals will be in them.

Correct. We just have not been able to work on them for a while with everyone being very busy and worldedit not working.

**Comment by AidanMSad** [comment]
@KarlOfDuty You guys should check out for world edit replacements, or get some new builders. There is probably hundreds of really good builders looking for a break to work for a large server.

**Comment by KarlOfDuty** [comment]
We will not be adding a new world at this time.
