### ISSUE TITLE
[Suggestion] Machine guns and light cannons plugin

### ISSUE THREAD

**Issue by NSGamer** [EarthMC/Issue-Tracker#267]
I know there is another similar thread on this forum, but I wanted to propose my idea of how that plugin could work. This would add 2 new types of bows, the machine gun and the light cannon. 
The machine gun would launch an arrow each 0.25 seconds and would be crafted with a bow + a potion of swiftness.
The light cannon/bazooka would launch an arrow with a TNT entity stuck to it instead of an arrow and would be crafted with a bow + TNT. This one in particular would be useful in battles, as TNT still causes damage in claims and it gives players a chance to move away from it unlike end crystals.
Perhaps if you don't like the 2nd one launching TNT, it could be changed by a fireball and it would shoot ghast fireballs.
This is just my idea of expanding the combat mechanics and making distance PvP more fun, and although I don't know much from plugins, it isnt that hard, I think.

**Comment by Ultil0l** [comment]
oof

**Comment by BowShot118** [comment]
no

**Comment by NSGamer** [comment]
why not

**Comment by NSGamer** [comment]
@Pocc

**Comment by BowShot118** [comment]
It sounds really bad 
@dad11

**Comment by NSGamer** [comment]
why does it sound bad
@pocc

**Comment by BowShot118** [comment]
Guns, We aren't American
@dad11

**Comment by NSGamer** [comment]
But we have wars
@pocc

**Comment by NSGamer** [comment]
@pocc DONT DIE

**Comment by BowShot118** [comment]
Back from the dead @dad11, sorry, but America bad and guns are america

**Comment by epicsans2003** [comment]
This kinda thing would be a good idea.
Would be.
It's really not though.

1 - Lag
2 - This is Minecraft, theres no set time period and anyone can chose what time period they want to play, but for me it makes sense for this to be Medieval kinda times. Since Minecraft only has swords and bows and that kinda simple thing. 

If the server had a set time period and it wouldn't lag, it'd be great!
But since it doesnt, no.

**Comment by Pengun78** [comment]
Ns be thinking of ideas to make machines kill perpignan instead of soldiers he doesnt have

**Comment by NSGamer** [comment]
Lol what

**Comment by NSGamer** [comment]
That is retarded

**Comment by Pengun78** [comment]
so is spain

**Comment by NigelFarage666** [comment]
I agree cannons would be very useful however I do not see a point in machine guns.

BowShot stop commenting you arent even playing.

**Comment by BowShot118** [comment]
> I agree cannons would be very useful however I do not see a point in machine guns.
> 
> BowShot stop commenting you arent even playing.

Very Rude, I still believe it's a bad idea.

**Comment by 4noah18** [comment]
I think that this server should just have the basics. That's kind of it's charm. Towny survival with a twist. This would just over-complicate it needlessly.

**Comment by NigelFarage666** [comment]
Bowshot everything is bad idea to you so please just bug off.

**Comment by Ultil0l** [comment]
war is good, peace is gay

**Comment by Kyoris** [comment]
I want to fite people just for fun lmao

**Comment by Coffeetom** [comment]
EMC is meant to be a vanilla style server (with Towny of course). The admins have turned down plugins which mess with thr vanilla feel. Plus there is nothing wrong with the current combat items. There are swords/axes for close up, and bows for long range (there are also tnt cannons). Adding more items would just complicate combat, and make it even more one sided to the wealthier who will get access to these new weapons.

**Comment by ExplosiveHD** [comment]
this is off topic

staff can you increase server capacity I couldn't join for the rest  of the day
only 100 ppl
there is 200 ppl who play (estimated) so can you change it

or make it 300 just to be sure plz plz plz plz thx

**Comment by KarlOfDuty** [comment]
As for the above already stated reasons this will not be added. Also, please make a new issue for other topics, don't comment in existing ones. @ExplosiveHD
