### ISSUE TITLE
[Bug] Bottom half of doublechests aren't seen by shop signs. 

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#271]
**Server**
EarthMC

**Describe the bug**
When shop signs take from Doublechests, the signs only see the top half of the chest. The bottom 3 rows do not get seen, so if all stock is bought up, and only bottom 3 rows remain, the sign will still tell the buyer that the store is out of stock.

**To Reproduce**
1. Create shop with any product, with doublechest acting as storage
2. Put items only in bottom half of the chest.
3. Attempt to buy items from the sign. It will say Out Of Stock. 
4. Move items to top half of chest. Sign will now have items in stock.

**Expected behavior**
Signs can see all items in the chest, not only the top 3 rows.

**Comment by BowShot118** [comment]
Ouch, I mean this could be solved by using a hopper system but ouch non the less

**Comment by johnyuki** [comment]
> 
> 
> Ouch, I mean this could be solved by using a hopper system but ouch non the less

Yes it can be, but for items that aren't bountiful then it can be an issue. For example if you are offline and the storage chest dries up due to a large quantity of sales, you will still have three rows in there that aren't being seen. This isn't the only issue with doublechests either, I just opened two more tickets about them.

**Comment by KarlOfDuty** [comment]
@creatorfromhell

**Comment by KarlOfDuty** [comment]
Should be fixed.
