### ISSUE TITLE
[Bug] You can do "/n ally add <nation>" to nations you're already allied with

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#274]

**Comment by 4noah18** [comment]
I mean this is probably the lowest priority of anything that needs "fixing".

**Comment by johnyuki** [comment]
> 
> 
> I mean this is probably the lowest priority of anything that needs "fixing".

A bug is a bug, I found it so I reported it.

**Comment by NigelFarage666** [comment]
John you must be a very fun person. 
Give mods a break seriously!
