### ISSUE TITLE
Server Restart Votes

### ISSUE THREAD

**Issue by 4noah18** [EarthMC/Issue-Tracker#275]
The server is always going between laggy and normal (though you could argue laggy is normal). When it's laggy, we have to wait hours for Karl or Fix to get on and restart it. I know a lot of this is caused by the Anti-Xray plugin, but in general having the option to restart the server when shit get's choppy is I think a good idea.

I think a plugin should be implemented that holds a Server Restart Vote. If the majority of people voting in a voting span of 10 minutes vote to restart the server, then the server restarts in another 10 minutes. This time provides people with enough warning to get to a safe place before restart.

Let me know what you think of this, where there's flaws, or anything else.

**Comment by BowShot118** [comment]
Sounds like a decent idea, the sensible side of me just says that it could be easily abused

**Comment by 4noah18** [comment]
The only way I could see it being abused is if there were a shit ton of bots that joined, but that's something that staff should be looking out for anyways. Maybe you could implement a cooldown so like three restarts every 24 hours? The main thing that stops it from being abused is it's the majority of the entire server has to agree to restart the server, and the entire process takes 20 minutes. That's what kind of prevents it from being abused, that massive amount of players.

**Comment by KarlOfDuty** [comment]
Good idea, but the issue is that we have to is balancing how many votes are needed to restart. I expect that someone could get lots of people to vote "for the memes", maybe more than who would vote if the server was actually crashing.

**Comment by 4noah18** [comment]
We could do a 70% vote to pass. That's pretty safe. At that point if 70% of players want a restart, it's probably best to restart the server. The restart limit per day would prevent abuse if for whatever reason 70% of the server was going to all rise up in meme unison. Frankly, even if the restart was a meme, it's still healthy for the server to do it, and because of what I said before you can't just spam restart.

**Comment by FurdenFuhrer** [comment]
I love this idea I don't know why no one has not thought of it yet.

**Comment by BowShot118** [comment]
Bcs John would force everyone to run the command

**Comment by FurdenFuhrer** [comment]
Yeah, fuck John abusing he cannot force anyone to do shit.

**Comment by 4noah18** [comment]
(This wasn't my idea, it was Wildcat_Pvpz, just want to let everyone know)

**Comment by Kyoris** [comment]
My idea for the restarts (compiling the above ideas and some of my own):
-Up to 3 restarts every 24 hours
-Restart cool down of 5 or 6 hours
-Restart requires >70% of online players to agree on said restart
-Restarts can be initiated by any player with a cool down of 15 minutes for said player (to prevent spam)
-Only 1 restart vote at any given moment

**Comment by AlexGamerYTT** [comment]
Excellent idea! Agreed and I also agree with Kyoris's ideas for the Plugin.
