### ISSUE TITLE
[Suggestion] Allow us to blacklist specific players/towns/nations from chunks we own

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#276]
**Additional context**
As a trader, not a fighter, it would be good if I could retaliate to raiders by blacklisting their nation/town from my shops so that they can't buy anything from me as a consequence. If someone were to raid me, I'm not really in a position to do anything as I don't have fighting skills, but I have a lot of commerce. Without the ability to blacklist I have absolutely no way of imposing sanctions on people.

Also, as this is meant to be a geo-political/economy simulation server, placing trade embargoes should absolutely be possible.

**Comment by Pengun78** [comment]
Why not your raiders will literally give u gold u can annoy them with that fact

**Comment by johnyuki** [comment]
> 
> 
> Why not your raiders will literally give u gold u can annoy them with that fact

I would prefer to stop raiders altogether by barring them from my shops as a punishment/deterrent to raiding. I sell items at good enough prices that I have plenty of buyers, so a couple of knobheads raiding isn't going to make me lose much sleep. Not to mention that peace of mind whilst in the Wilderness is worth much more than the couple of gold they'd spend in my shop

**Comment by 4noah18** [comment]
I agree with this. You should have the choice to ban towns, nations, and players from certain shop signs.

**Comment by Ultil0l** [comment]
This idea is fucking retarded

**Comment by ExplosiveHD** [comment]
run it on a gaming pc get a good router put the gaming pc next to it get the server on a usb put it in the gaming pc. if u can't afford that then sell your OLD router and potato pc THEN YOUR DONE!!!!!!!!
unless your lazy

**Comment by johnyuki** [comment]
> 
> 
> This idea is fucking retarded

Maybe elaborate and be constructive?

**Comment by ExplosiveHD** [comment]
can u kick any afk out I cant join the server is full

**Comment by ExplosiveHD** [comment]
the server capasity is 140 but it shows 100 AND I CANT JOIN whats this bull

**Comment by BowShot118** [comment]
Server cap is 100 rn and how is this relevant  in anyway to the issue

**Comment by ExplosiveHD** [comment]
nvm

**Comment by johnyuki** [comment]
> 
> 
> oof, its your responsablility to keep people you dont like out of your town, not the server's

It is meant to be a geopolitical sandbox server. Politics isn't all about fighting and pvp. It's also about trade and partnerships, and reflecting that in game would give a more accurate representation of international politics. It also counters pvpers, as it currently isn't possible to counter them besides cowering inside your base. I assume you dislike my idea because you like to pvp, and don't want to get banned from shops :)

**Comment by johnyuki** [comment]
> 
> 
> Fucking finally, someone who understands that the server isn't entirely stab stab. 👍 for the well written proposal btw

I honestly have so many ideas on how to improve trade and have a greater emphasis on allies and politics.

**Comment by Coffeetom** [comment]
An idea I have for this is that Nation enemies are banned from "shop chunks". This would mean that all chunks you set as a shop (/plot set shop) wouldnt be enterable by Nation enemies

**Comment by Kyoris** [comment]
How about make it so that blacklisted players can enter the chunks, but cannot do ANYTHING, and can be attacked freely with no way to fight back.

**Comment by johnyuki** [comment]
> 
> 
> An idea I have for this is that Nation enemies are banned from "shop chunks". This would mean that all chunks you set as a shop (/plot set shop) wouldnt be enterable by Nation enemies

That isn't what I'm saying at all. I'm not talking about shop plots. I'm talking about shop sign usage. 

```
if(player is not blacklisted){
    Allow them to open shop interface.
}
else {
    Do not allow them to open shop interface.
}
```

I'm not talking about blocking them from entering entire chunks - just blocking them from using the shop signs in specific chunks.

**Comment by Coffeetom** [comment]
It was just a suggestion on a alternative way to deal with this problem. It would take less commands and be simpler for the newer players.

**Comment by Magenent** [comment]
> **Additional context**
> As a trader, not a fighter, it would be good if I could retaliate to raiders by blacklisting their nation/town from my shops so that they can't buy anything from me as a consequence. If someone were to raid me, I'm not really in a position to do anything as I don't have fighting skills, but I have a lot of commerce. Without the ability to blacklist I have absolutely no way of imposing sanctions on people.
> 
> Also, as this is meant to be a geo-political/economy simulation server, placing trade embargoes should absolutely be possible.

Honestly haven't thought of this much but this is a very good idea, because even though I do like pvp I still would love to embargo my enemies and have shops in my town and nation embargo enemies.

**Comment by Magenent** [comment]
> banned



> An idea I have for this is that Nation enemies are banned from "shop chunks". This would mean that all chunks you set as a shop (/plot set shop) wouldnt be enterable by Nation enemies

Yeah but then you could set the parimiter of your town as shop plots to stop anyone from even coming in, it should just be that you can't right click on the trade signs

**Comment by AidanMSad** [comment]
You should have the option - if it is 

> This idea is fucking retarded

Some people will use it, some wont

**Comment by KarlOfDuty** [comment]
This is not currently possible in towny, report it to them instead.
