### ISSUE TITLE
[Plugin] Combat Log

### ISSUE THREAD

**Issue by ArepaConMayonesa** [EarthMC/Issue-Tracker#278]
**Hello,**

When players engage into a battle, usually one of them tends to logout whenever they think they might lose and leaves the other player hanging around. This mostly happens when one of the players are caught  off guard.

This plugin already exists, and how it works is that the server detects when "Player A" hits/attacks "Player B" and both players cannot leave the server for a period of time, this timer resets everytime when the previous condition happens. If any of the 2 players leaves the server during this period, the one that leaves dies.

**Comment by BowShot118** [comment]
No bad idea, this was tested in beta and it caused any form of damage to trigger this

**Comment by ArepaConMayonesa** [comment]
But only triggers it from players

**Comment by ArepaConMayonesa** [comment]
But there's one that only reacts to a player interaction to another player

**Comment by BowShot118** [comment]
Honestly, build a trap. It isn't a major issue and the laggy climate rn is prone to crashed which could cause un-necessary damage

**Comment by ArepaConMayonesa** [comment]
Not all the players PvP, but it is pretty annoying to the ones that do. And you're right about the current condition of the server. 

So there was a player called Celestia something, and he built a trap and got warned from one of the Mod members

**Comment by BowShot118** [comment]
Then that requires a discussion on the rules and what classes as griefing

**Comment by BowShot118** [comment]
Standardization would help https://github.com/EarthMC/Issue-Tracker/issues/277

**Comment by ArepaConMayonesa** [comment]
But this is still a "problem" that can happen to any player, even if fix the current condition of the server.

It may not be a big one, but the own nature of the server encourages players to PvP if they want.

**Comment by BowShot118** [comment]
I see your point, but the server is to laggy for such a beta tested unreliable plugin

**Comment by ArepaConMayonesa** [comment]
There are various plugins, is up to the staff to test which one works best https://dev.bukkit.org/projects/combatlog
https://www.spigotmc.org/resources/combatlogx.31689/

**Comment by 4noah18** [comment]
Can't build cages because you're warned for griefing, can't claim outposts to stop people from having friends come break them out, literally nothing short of having someone log in your claims will let you fucking kill them. It's annoying as hell and we've been asking for a combat log plugin for a long time

**Comment by watergod1234** [comment]
i don't understand why a combat-logging plugin is taking so long. easily one of the worst issues on the server is this and it could be solved by downloading and configuring a plugin from spigot. It's not resource intensive in the slightest either. what's taking so damn long?

**Comment by sawyerc18** [comment]
can an admin please add this! this is a very basic plugin that will make gameplay much more enjoyable
