### ISSUE TITLE
Chests, crafting tables and furnaces occasionally look like smooth stone.

### ISSUE THREAD

**Issue by Cooliodex** [EarthMC/Issue-Tracker#28]
I'm pretty sure this is because of Orebsfucator 4, but certain blocks, like chests, furnaces, and crafting tables look like stone for a couple seconds before they turn into what they're supposed to be. Not too big of an issue but its quite annoying.

**Comment by KarlOfDuty** [comment]
We can probably reduce this effect a bit.

**Comment by Cooliodex** [comment]
alright thanks sounds great

**Comment by KarlOfDuty** [comment]
Done.
