### ISSUE TITLE
MC Max players issue

### ISSUE THREAD

**Issue by ExplosiveHD** [EarthMC/Issue-Tracker#280]
There is a max limit of 100 and how many  people want to join Well 820 ppl play earth mc so about 900 should be max players or the highest peak of players the server was trying to join mc please i want to join people on the server but its full and more and more people are trying to join so make afk timeout 2 min
also have a time where you kill all entities once every 4 mins  to stop lag and named entities can stay.
 and get as many clear lag plugins. and maybe do reasearch on how to stop lag and increase max players.
then more players can join and have fun with the community and youtubers can also start making videos on this server thank you for reading my suggestion if anyone did read this.

**Comment by ExplosiveHD** [comment]
and have a no swear rule in case a 5 year old joins the server

**Comment by BowShot118** [comment]
Top 10 days to crash the server

**Comment by ExplosiveHD** [comment]
yea
if every player makes lag machines and all plugins are removed exept for the crappy lag making one

**Comment by BowShot118** [comment]
You want to remove all the plugins?

**Comment by ExplosiveHD** [comment]
no keep em all unless some cause lag then delete the ones which cause lag

**Comment by BowShot118** [comment]
What if towny caused lag?

**Comment by Pengun78** [comment]
No swear rule is the dumbest idea ever tbh the mods swear too lmao and 900 players at the same time cmon man

**Comment by Kyoris** [comment]
FUCK FUCK FUCK FUCK SHIT FUCK YOU LITTLE BITCH BOY LITTLE SHIT HEAD REEEEE

**Comment by Coffeetom** [comment]
Dude all of your ideas are bad. The server can't handle 900 people. Plus the limit gives people a reason to buy donator. Because without donators there is no server. And EMC is known for being a server that doesn't have stupid chat filters and anti swearing rules, and people like that.

**Comment by NeonKrby** [comment]
Yeah fuck that shit, this server cant handle that. and i bought a rank, you should too

**Comment by NeonKrby** [comment]
also fuck yuo for no swear rule

**Comment by NeonKrby** [comment]
Young children should'nt be playing on this server.

**Comment by KarlOfDuty** [comment]
The server has a player limit of 140, not 100. In any case, no server can handle 900 players, all servers above 200 player limit just have several servers with a combined player count. We will adjust the player count depending on how well the server does when it comes to lag.

**Comment by ExplosiveHD** [comment]
okay then case closed :D
