### ISSUE TITLE
[World] Lakes In Norway

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#281]
In real life there are a lot of lakes in Norway, but in game only a couple of them show up, it would be nice if more could be added since they improve the environment of the countryside. 

All of Norway

**Comment by BowShot118** [comment]
Finland as well

**Comment by NigelFarage666** [comment]
Why don't you tell staff where to place those lakes? And make their job easier? Like there is detailed procedure how to make github post when I make world posts I show screenshots and real life locations and I tell staff what I think it should be done and my discord if they need to contact me.
