### ISSUE TITLE
[World] Chinese Rivers

### ISSUE THREAD

**Issue by Keennoo** [EarthMC/Issue-Tracker#282]
Chinese Lakes.
I'm frustrated as China has little to no lakes. In reality, rivers are a major source and way of trade in China and IG it'd be the same but there are no rivers (e.g Yangtse River).

I am requesting designers to make a lot of rivers in China.

If any players reading this convert to Buddhism, Buddha has reincarnated from EMC Classic into EMC Terra Nova. Also, it should be drivable for trade and navigation.

**Comment by PoppyK** [comment]
The Yellow and Yangtze are the largest so those could be added possibly depending on how free the areas are of claims.

**Comment by NigelFarage666** [comment]
WOAH LIKE I WAS JUST GOING TO WRITE THIS LOL! Thanks Keeno!

**Comment by NigelFarage666** [comment]
No sorry Poppy I cant call that rivers I was many times to China and including the first time when I joined and thought of making Luoyang until I saw San Francisco being free.
Most of the "rivers" are just streams .
And I think those all rivers should be made navigable. Because they are just too small and short.
Just sad

**Comment by Keennoo** [comment]
Towns have settled in these locations and it would be great to avoid and border the towns which settled on this ocean. @PoppyK @NigelFarage666 [https://imgur.com/a/AryjPJn](url)

**Comment by EchoOcelot** [comment]
Would these rivers be able to have the “river” biome when added? I just want to have drowned mobs and more of them spawn in “rivers”

**Comment by BowShot118** [comment]
Probably not

**Comment by EchoOcelot** [comment]
Rip

**Comment by PoppyK** [comment]
@Keenoo I will look at the existing rivers the next time I am able to work.  I can work what is there and widen them if needed.  Also @EchoOcelot we can change the biomes to be rivers,  We just haven't gotten around to doing so as of yet.  It all just takes time, but it can be done.  Please make a separate issue ticket about changing the rivers biomes and start the title with [world].

**Comment by Kyoris** [comment]
Please add the river biome to the Dneiper and Pripyat rivers :3

**Comment by Keennoo** [comment]
I've just made my town Wuhan on the Yangtze river, when you fix it to make it driveable just edit it idrc what you do to my town

**Comment by PoppyK** [comment]
I have looked at both the Yellow and the Yangtze Rivers and both of those will be able to be deepened and in some areas defined.  This will be worked on.

**Comment by NigelFarage666** [comment]
Could someone please assign for Alps and other mountains?

**Comment by PoppyK** [comment]
Yangtze is done.  @Keennoo I couldn't fill water in your claims.  There isn't much to do since the river was wide where your claims were, but there are some bare patches where water needs to be filled.

**Comment by PoppyK** [comment]
Yellow River is complete.  I didn't work in the areas that were already developed but deepened most of it.  I also formed more of the river past New_Xiangyang.

**Comment by PoppyK** [comment]
Liao River done.

**Comment by PoppyK** [comment]
Pearl River done.

**Comment by NeonKrby** [comment]
Poppy your like god in the 1st chapter of Genesis, making rivers and water masses left and right.

**Comment by NeonKrby** [comment]
chill xd

**Comment by PoppyK** [comment]
Done
