### ISSUE TITLE
[Suggestion] When a new day ticks over, show who has paid their tax and how much total tax was paid.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#284]
**Please describe.**
When residency tax is paid in a town, it should pop up saying "x amount of tax has just been paid by: -names-. No tax has been paid by: -names-, and they have been removed from the town. Old town balance was -money-, new town balance is -money-." 

It's always good to see a bit more information pertaining to this stuff.

What would be even better is a log book in-game that shows each day, and who did/didn't pay tax on that date, and how much tax was paid if they did. This way we can keep track over time just in case we weren't logged in to see the tax message.

**Comment by 4noah18** [comment]
Agree

**Comment by KarlOfDuty** [comment]
This is something to report to the towny developers, not us.
