### ISSUE TITLE
[Suggestion] Automatically show "In stock", "Out of Stock" on shop signs

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#285]
**Is your feature request related to a problem? Please describe.**
currently we have to manually add in signs that say whether things are in stock or not, or go through the trouble of setting up comparators to activate a lamp.

**Describe the solution you'd like**
There are 4 lines on a sign, and only 3 are currently used for shop signs. I suggest making the 4th line say "In Stock" or "Out Of Stock" accordingly. Text should be Green/Red respectively.

**Comment by KarlOfDuty** [comment]
Duplicate of #268
