### ISSUE TITLE
[Feature] Remove /n Spawn & /t Spawn

### ISSUE THREAD

**Issue by AidanMSad** [EarthMC/Issue-Tracker#286]
**Is your feature request related to a problem? Please describe.**
I Love the server, and how TN has pressed to make it more work to trade and work around, but we need to continue this way but finishing the work that has been done and end this once and for all
**Describe the solution you'd like**
No /T spawn , No /n spawn ; Make horses do their work, make railways necessary make trade harder.
**Additional context**

**Comment by Ultil0l** [comment]
ok,
1. FUCK OFF
2. FUCK OFF
3. FUCK OFF
4. pls dont delete im just being honest

**Comment by Kyoris** [comment]
I am not taking a 30 min boat ride just to get to a trade and much less BACK the whole way. Also horses are way too rare.
0/10 idea. Only do this if the war plugin is implemented AND a country is in war

**Comment by BowShot118** [comment]
This is a horrific idea, many forms of teleportation were already removed from classic and this aint a map that you can cross in 10 minutes.

0/10

**Comment by BowShot118** [comment]
Ikr

**Comment by NeonKrby** [comment]
no dumb delet

**Comment by Pengun78** [comment]
imagine if this actually got removed lol

**Comment by Kyoris** [comment]
ikr lmao

**Comment by NigelFarage666** [comment]
Amazing idea! I love it! I just think we should leave t spawn for town members!

**Comment by Pengun78** [comment]
no no

**Comment by NigelFarage666** [comment]
A M A Z I N G

**Comment by KillerDuck00** [comment]
I think that we should remove the teleporting commands. It makes the roads actually useful and the world feel larger and more alive. It adds a layer off complexity.

**Comment by BowShot118** [comment]
Yes, a layer of complexity and hours of travelling to buy some steak from Tesco.

**Comment by KillerDuck00** [comment]
That's why you should build ice roads and railroads.

**Comment by MineHero43** [comment]
Bye bye new players

**Comment by KillerDuck00** [comment]
when i first joined the server i crossed the entire us and boated over to europe with no problem

**Comment by NeonKrby** [comment]
your problem not ours

**Comment by KillerDuck00** [comment]
what?

**Comment by Kyoris** [comment]
I ain't boating 20min just for some fucking exp and enchanting

**Comment by BowShot118** [comment]
> That's why you should build ice roads and railroads.

Those ice roads that are allowed to be griefed, and those railways that take nearly as long as walking. 🤔 Yeah makes sense

**Comment by Pengun78** [comment]
Lol i get the idea travelling will be used more ans people with make their own shops and farms so they dont have to buy stuff etc
Also if u wanna explore u gotta travel like irl and you will find places you have never seen yet
I still want it to stay tho

**Comment by BowShot118** [comment]
> Lol i get the idea travelling will be used more ans people with make their own shops and farms so they dont have to buy stuff etc
> Also if u wanna explore u gotta travel like irl and you will find places you have never seen yet
> I still want it to stay tho

Yeah but it's unlike the UN is going to ban planes to "get people to explore more" Irl. This removes a fast means of travel, planes are a fast means of travel irl.

**Comment by Pengun78** [comment]
Ya but dont forget this map is way smaller than the irl map i mean an ice road would be much much faster than a plane on a full scale map

**Comment by Pengun78** [comment]
But ill miss the n spawns so no thanks

**Comment by cat234** [comment]
This would break the economy. Everyone would be disinterested in trading because of the long routes.

**Comment by KarlOfDuty** [comment]
We do not believe the added travel time would be a benefit to the server at this time.
