### ISSUE TITLE
[Suggestion] Vodka! And other alcomahals.

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#287]
I feel like there isn't much in the way of recreational content. So I have a simple idea. Make it to where if you put a potato in a brewing stand with a potion of strength, it gives you back a potion called "Vodka". It applies 30 seconds or so of strength 3, and about 60 or so seconds of nausea. I'm sure those who know about balancing stuff can figure it out. Maybe this same thing can work for other potions too! Like if you add wheat to a potion of slowness, you get beer! Or if you add melon to a regeneration potion, you get Melon Wine! Please give your feedback on this idea in the comments! Or if you have ideas for other alcohols and drinks, leave a comment!

**Comment by Pengun78** [comment]
Lol epic

**Comment by NeonKrby** [comment]
Yes beer.

**Comment by Ultil0l** [comment]
I dont want this.
I NEED THIS

**Comment by Sulakek** [comment]
This is the brewing mod right? 

i was just going to add a new issue related to that 
https://dev.bukkit.org/projects/brewery

**Comment by KarlOfDuty** [comment]
We will not add this.

**Comment by PlaceReporter99** [comment]
banana???
