### ISSUE TITLE
[Feature] Have 'Falling out of the void' in the overworld not be 'lag' and become a issue where your items can be refunded

### ISSUE THREAD

**Issue by AidanMSad** [EarthMC/Issue-Tracker#288]
**Is your feature request related to a problem? Please describe.**
A few days ago, I was in a boat with a villager i got from the magical Eagle the mod's farm. I recently bought a god kit for 40 gold, and i was excited to use it since it is wonderful in collecting quartz due to not loosing that many hearts when falling. Anyway, I got into the boat and was going from Madagascar ---> Macau (China) and some reason i just fell out of the void and lost everything

I was outraged by this and made a ticker #3985 and some reason i find out that they can not refund items due to 'lag' ; this makes me even more outraged due to the fact i have screenshots of the message on both in game & discord SRV.

I have replied with massive anger due to the fact, that with all my items in the void, i cannot do what i was planning to do with the next few days due to the fact it was being read.

**Describe the solution you'd like**
I want that if something , that shows that you have died to a way impossible and obviously a glitch you can have your items back.

**Additional context**

![2019-01-10_22 43 25](https://user-images.githubusercontent.com/37817143/51034743-d4a3f400-15fb-11e9-9c85-18adf3ffbd3d.png)

**Comment by NeonKrby** [comment]
Dont Travel. Ezpz

**Comment by KarlOfDuty** [comment]
You don't lose your items when falling out of the world anymore.
