### ISSUE TITLE
[Feature] Have mobs spawn more

### ISSUE THREAD

**Issue by AidanMSad** [EarthMC/Issue-Tracker#289]
**Is your feature request related to a problem? Please describe.**
Mobs, As much as anyone can see do not spawn at all, only in the nether if lucky
The use of armor is almost useless regarding mobs since all mobs, are either sheep/cows and mostly just bread mobs.
I have seen no mobs in the last week i have played on earthmc
**Describe the solution you'd like**
I want myself to go into the wild and see mobs spawning, or seeing ghasts in the nether. I want to end up finding tridents from mobs underwater.
I really want mobs to be turned on/up until it seems like a normal minecraft world
**Additional context**
I see last posts complains about mobs, but they all say you turned it back on. That's not what anyone sees now.

**Comment by Pengun78** [comment]
We really need squids no one has ink sacks

**Comment by osnapitzjamie** [comment]
yes please, villagers will still be valuable since there are no villages they spawn in so i guess its fine

**Comment by Kyoris** [comment]
Same as pengun

**Comment by NSGamer** [comment]
We need more spiders, zombies and skeletons, the spawn rate is just retarded.

**Comment by AlexGamerYTT** [comment]
The spawn rate of pigs, cows, chickens, etc is also retarded.

**Comment by RoJoGuapo** [comment]
I agree, I can never find animals in Canada

**Comment by Pengun78** [comment]
its because there are none

**Comment by Rokim21** [comment]
I agree, the lack of mobs just makes everything harder regarding crafting.

**Comment by KarlOfDuty** [comment]
They should spawn more now.
