### ISSUE TITLE
[Plugin] Kicking Inactive People

### ISSUE THREAD

**Issue by Brittlewood** [EarthMC/Issue-Tracker#290]
Currently the amount of time it takes for someone to be kicked from a town due to inactivity/and subsquent fall of the town, is around 60 days. I think it should be back to 44 days like on classic. There are a lot of one-dayers on the server and doubling the time it takes for a town to fall means nearly doubling the amount of inactive towns littered all over the place. Going back to 44 days would not only open up more space for settlers quicker, but also clean up massive towns- and nations- that are swollen with people who haven't been on in over a month and give a better representation of how big and how active towns/nations are actually are.

**Comment by KarlOfDuty** [comment]
It has been changed to 42 days.
