### ISSUE TITLE
[World] Need river created that isn't in game

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#291]
**Describe the issue**
I have created a town near the ocean. There is a river there irl, but because of the scaling down that had to be done in-game, the river isn't fully there. I'd like for the River to be added so that I can link it up with my lake so that boats can fit down it without issue.

**Coordinates**
https://earthmc.net/map/index.html?worldname=earth&mapname=flat&zoom=4&x=26260&y=64&z=764

**Screenshots**

Screenshot of the area irl, including the river:
https://cdn.discordapp.com/attachments/533394176058851328/533406608076832789/unknown.png

Google maps link: 
https://www.google.com/maps/search/maps/@-4.2430692,143.0990792,9.48z

**Comment by johnyuki** [comment]
Yes, I need designers to add a river that should be there. I created a ticket on discord and they said to post it here.

**Comment by PoppyK** [comment]
https://i.gyazo.com/88f68374c86f685bd2052b61f3b619e8.png Is this the lake and river, John?

**Comment by johnyuki** [comment]
> https://i.gyazo.com/88f68374c86f685bd2052b61f3b619e8.png Is this the lake and river, John?

Yep, that's the one

**Comment by PoppyK** [comment]
Done
