### ISSUE TITLE
Either remove spawn taxes, or tell people that the nation they are tp'ing to takes their gold

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#292]
**Is your feature request related to a problem? Please describe.**
Some guy in chat just asked "does anyone else lose gold when they teleport?". This is a really stupid feature, especially if you don't get warned for it before you teleport. If you are teleporting to a nation that has spawn tax set, you should have to type /nation spawn -nation- twice before actually teleporting so that you have the choice of not getting taxed.

**Comment by johnyuki** [comment]
Not sure, I didn't ask

**Comment by BowShot118** [comment]
Never had this before

**Comment by AidanMSad** [comment]
It's mostly off and it's quite hard to do it since most people gold is in their town and not their enderchest

**Comment by BowShot118** [comment]
I have my gold in my echest and never get this

**Comment by KarlOfDuty** [comment]
It has been removed.
