### ISSUE TITLE
A epic plugin list

### ISSUE THREAD

**Issue by ExplosiveHD** [EarthMC/Issue-Tracker#293]
please add these plugins I will love this idea

https://www.spigotmc.org/resources/ships.2072/ you can build airships 

https://dev.bukkit.org/projects/ucars you can have cars

https://dev.bukkit.org/projects/silkspawners you can mine spawners with silk touch 1

https://dev.bukkit.org/projects/liftsign elevator signs

https://dev.bukkit.org/projects/pickuparrows allows you to grab arrows form skeletons

https://dev.bukkit.org/projects/newarmor?gameCategorySlug=bukkit-plugins&projectID=281623
Emerald gear

https://dev.bukkit.org/projects/simple-home set home allows you to teleport to your home

https://dev.bukkit.org/projects/hydrate?gameCategorySlug=bukkit-plugins&projectID=61616
Gives a thirst bar to players!

and thats it

**Comment by ExplosiveHD** [comment]
oops

**Comment by creatorfromhell** [comment]
> https://dev.bukkit.org/projects/silkspawners you can mine spawners with silk touch 1

There's already this functionality on the server.

> https://dev.bukkit.org/projects/simple-home set home allows you to teleport to your home

What's wrong with sleeping in a bed and using /res spawn?

> https://dev.bukkit.org/projects/liftsign elevator signs

What's wrong with vanilla water elevators using the 1.13 functionality of soul sand and magma blocks?

**Comment by ExplosiveHD** [comment]
then don't add those but add rest!

**Comment by BowShot118** [comment]
I swear half of this was recommended before and the staff said no

**Comment by Pengun78** [comment]
Thirts bar hell no

**Comment by ExplosiveHD** [comment]
okay then no thirst bar

**Comment by osnapitzjamie** [comment]
stupid plugins all of them.

Half of them not even needed.

**Comment by Pengun78** [comment]
https://dev.bukkit.org/projects/gods

**Comment by KarlOfDuty** [comment]
We already have like half of those features and we do not wish to add the rest.
