### ISSUE TITLE
Frost Walker enchant shouldn't freeze water in other peoples claims

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#294]
**Is your feature request related to a problem? Please describe.**
I have a shopping tower at my nation spawn, and to get from the top to bottom you jump down the middle in to a pool of water. Problem is that when people have Frost Walker boots on they freeze the water at the bottom, so people who jump off lose a lot of hp and/or die.

**Comment by Pengun78** [comment]
The ice dissapears after like 4 sec

**Comment by johnyuki** [comment]
Not in my shop it doesn't. I have to break it manually.

**Comment by AidanMSad** [comment]
It doesn't melt under blocks. And it doesn't melt at night.

I froze all of singapour bay when i was waiting for my villager , finding out only it melts in the day

**Comment by johnyuki** [comment]
> 
> 
> It doesn't melt under blocks. And it doesn't melt at night.
> 
> I froze all of singapour bay when i was waiting for my villager , finding out only it melts in the day

This is probably why it doesn't freeze in my shop then, as the pool of water is indoors.

**Comment by KarlOfDuty** [comment]
This is not something we can fix, you will have to suggest it to the towny developers instead.
