### ISSUE TITLE
[Feature] Add a plane mod.

### ISSUE THREAD

**Issue by AlexGamerYTT** [EarthMC/Issue-Tracker#295]
**Is your feature request related to a problem? Please describe.**
Well, for moving to some towns or nations of which you aren't allied, it is a bit hard for reaching there by boat, because it's slow and the map is huge.

**Describe the solution you'd like**
So, how about having planes as another option to travel faster?

**Additional context**

**Comment by Pengun78** [comment]
I would want this but its just laggy

**Comment by Kyoris** [comment]
I want planes
would be even cooler if we need runways n shit

**Comment by BowShot118** [comment]
eh, I've been on servers with this before and it's quite laggy.

Depends on the plugin I guess

**Comment by AlexGamerYTT** [comment]
You can make a maintenance and try different plugins and see which one causes less lag.

**Comment by AlexGamerYTT** [comment]
You can make a maintenance and try different plugins and see which one causes less lag.

**Comment by BowShot118** [comment]
It's been laggy while you are flying the planes, otherwise it's fine.

**Comment by AidanMSad** [comment]
You need alot more ram for this, and we cannot even have mobs without the server lagging like crazy.

I'd love this but it's too laggy for it at the moment

**Comment by AlexGamerYTT** [comment]
Understood. Hope to see it on a future.

**Comment by AlexGamerYTT** [comment]
Understood. Hope to see it on a future.
