### ISSUE TITLE
[Feature] Remove friendly fire

### ISSUE THREAD

**Issue by NSGamer** [EarthMC/Issue-Tracker#296]
All of us have noticed it, players in YOUR OWN TOWN and even allies can hit and attack themselves, which is stupid. The staff hasnt said anything about it, and nobody either so I am here to say it myself.

Remove friendly fire beetween allies, town members, and nation members, because we can accidentaly hit eachother in battles or enemies can profit of Nation A being allied with Nation B because they can hit people of Nation B and /n spawn to Nation B's spawn.

**Comment by Pengun78** [comment]
No

**Comment by BowShot118** [comment]
1. Pvp tends to be off in towns
2. I've had trouble in the past with "allies" griefing around my town.
3. I agree with nation members friendly fire being removed.
4. Parties stop friendly fire

**Comment by AlexGamerYTT** [comment]
Should be good disabling it only between nation members.

**Comment by Kyoris** [comment]
I would say that only remove it with party members cuz in a battle you can't stop and check your party list every 10 secs

**Comment by BowShot118** [comment]
I mean
if you know who you're fighting with before a battle, for donors at least, you can create and invite people to a party.

**Comment by Pengun78** [comment]
I love hitting my friends in the wild or doing /t toggle pvp and then randomly fighting i wouldnt want this gone just create a party so u cant hit each other

**Comment by NigelFarage666** [comment]
no.

**Comment by KarlOfDuty** [comment]
We will keep friendly fire on at this time as it doesn't really seem like most want it off.

I personally also prefer friendly fire as I think it makes battles much more interesting as you can't just fire randomly into a group of friends and enemies fighting or just randomly hit players around you.
