### ISSUE TITLE
Racial slur ban issue

### ISSUE THREAD

**Issue by medivipuz** [EarthMC/Issue-Tracker#297]
hi! i recently got warned for racial slur for saying ï love niqqas¨ i Think that the racial slur has gone way to far when will u get warned for saying i like the song africa? i Think u should change it so its just when the real Word is used or when its used in an negative way. i also Think that if nibba is a racist Word taht u can get banned for it will also be for saying Words like ¨jew¨in an negative or racist way. and that Towns like n_word and nations like nazi_germany should get warned for promoting anti semenatism they have nazi flags all over the nazi party stands for the Death of 50-56 million people?

**Comment by johnyuki** [comment]
> 
> 
> hi! i recently got warned for racial slur for saying ï love niqqas¨ i Think that the racial slur has gone way to far when will u get warned for saying i like the song africa? i Think u should change it so its just when the real Word is used or when its used in an negative way. i also Think that if nibba is a racist Word taht u can get banned for it will also be for saying Words like ¨jew¨in an negative or racist way. and that Towns like n_word and nations like nazi_germany should get warned for promoting anti semenatism they have nazi flags all over the nazi party stands for the Death of 50-56 million people?

How is saying "I love niqqas" anything to do with a song??

As far banning words like "jew" - Jew is literally the shortened version of Jewish and isn't inherently negative unless you intend it to be negative. 

As for Nazi_Germany - this is a geopolitical server. You can have whatever nation you like as long as you aren't going around saying shit like "lets gas all the jews again".

**Comment by Kyoris** [comment]
lmao auschwitz

**Comment by Ultil0l** [comment]
ContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContext

**Comment by BowShot118** [comment]
> ContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContextContext

👌

**Comment by KarlOfDuty** [comment]
As the other comments stated above says, we will continue to use context in our warns and mutes. I think we all know what word that was supposed to be, we are not chat bots.
