### ISSUE TITLE
Voting almost never works

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#298]
Ok so, for a couple of days now, voting almost never works, at least for me, I dont know... And it is quite infuriating to get the message that I got my voting gold even tho in fact I almost never get it.

**Comment by creatorfromhell** [comment]
This is an issue we're already looking in to as stated in your ticket.

**Comment by AlexGamerYTT** [comment]
Works for me lmfao

**Comment by KarlOfDuty** [comment]
This should be solved.
