### ISSUE TITLE
Admin Island with shop for unobtainable items.

### ISSUE THREAD

**Issue by osnapitzjamie** [EarthMC/Issue-Tracker#299]
Hello,

I think there should be an admin island that has a shop on it with unobtainable items, such as endstone and other blocks that are impossible to obtain due to there being no strongholds etc.

I think this would be a great place and be the main social hub for the server.

**Comment by Kyoris** [comment]
Yeah I think it would be useful especially for builders looking for exotic materials

**Comment by NeonKrby** [comment]
In EMC classic there were villagers who sold custom shit if they make a spawn they could do that.

**Comment by Kyoris** [comment]
maybe at a sky island at 0, 200, 0 would be cool
water elevators to get up and down from it

**Comment by Brittlewood** [comment]
It would be nice to be able to have donkeys... but that’s really the only item I want.

**Comment by KarlOfDuty** [comment]
We are already planning something else to combat the issue of unobtainable items, if you want you can make a new issue listing items which are currently unobtainable so we don't forget any when we add them.
