### ISSUE TITLE
[World]Can't put plants on certain places

### ISSUE THREAD

**Issue by Droper2014** [EarthMC/Issue-Tracker#300]
hello so i have a problem that i can put some plants on my super duper secret farm in St. Zebbs port .here are the problemed cordinantes as it seens
there suppose to be a wheat on : 
X2452 Y 53 Z -8379

there suppose to be potato on:
X2457 Y 53 Z -8380
X2457 Y 53 Z -8379
X2457 Y 53 Z -8378
X2457 Y 53 Z -8377
X2458 Y 53 Z -8379
X2458 Y 53 Z -8378
X2458 Y 53 Z -8377
X2458 Y 53 Z -8376
X2459 Y 53 Z -8378
X2459 Y 53 Z -8377
X2459 Y 53 Z -8376
X2459 Y 53 Z -8375

i do have all of the seed and potato on my inventory
as you cann see on the pictures we noticed that if we dig 1 block down we can place it if it is upper than 52 it doesn't work
![2019-01-16_13 38 00](https://user-images.githubusercontent.com/27211909/51249941-032c2100-19a6-11e9-8021-efcf9a21d850.png)
![2019-01-16_13 38 07](https://user-images.githubusercontent.com/27211909/51249943-045d4e00-19a6-11e9-9cf4-b1ec5d9a311f.png)

**Comment by Pengun78** [comment]
epic

**Comment by Coffeetom** [comment]
Might be due to light level, try adding a piece of glowstone above the block, and try again

**Comment by Droper2014** [comment]
i'll try thanks

**Comment by Droper2014** [comment]
> 
> 
> Might be due to light level, try adding a piece of glowstone above the block, and try again

thank youuu UwU

**Comment by Coffeetom** [comment]
Ahahaha np
