### ISSUE TITLE
[World] Biome change in Russia. 

### ISSUE THREAD

**Issue by Steadlington** [EarthMC/Issue-Tracker#302]
**Describe the issue**
The current biome of the Urals, in Russia, is dark-forest biome. This poses an issue because it effects the way that certain game mechanics are carried out. For example, each biome is assigned a temperature and when a temperature reaches below 0 ice and snow will begin to form.  This creates a much more realistic addition to the landscape. The biome should changed from Dark-forest to snowy taiga mountains. 

**Coordinates**
10716, 125, -11466

**Screenshots**
![image](https://user-images.githubusercontent.com/46766036/51286671-d4389e00-19eb-11e9-8361-ed8e24c1263d.png)

**Comment by AlexGamerYTT** [comment]
Agree.

**Comment by NigelFarage666** [comment]
True they should have placed Dark Oak biome somewhere else.

**Comment by KarlOfDuty** [comment]
I have changed the biome to taiga mountains.
