### ISSUE TITLE
Add a server spawn again

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#303]
Many new players always ask "what can i do here"
Wouldnt it be handy to have a server spawn again, but this time like under the ocean so nobody will make towns close to it etc
Also alot of players want diffrent spawn eggs and i really liked parkour for a spawn egg at the classic spawn
I dont see anything wrong with this and would love to see it back

**Comment by Coffeetom** [comment]
Would be useful, with like a little walkway tell people how the server works. because heaps of new players don't know anything, from towny commands, to the gold economy

**Comment by BowShot118** [comment]
Yes!

**Comment by Ultil0l** [comment]
but maybe not in the middle of the balkans

**Comment by Ultil0l** [comment]
Or in a place where shops could just get built around them

**Comment by Pengun78** [comment]
yeah coffee thats what i meant lol, the players themself are currently the ones that explain the newbies how this server works

**Comment by AlexGamerYTT** [comment]
Good idea!
I guess it would be nice if new players could also teleport directly to América, Europe, Africa or Asia .

**Comment by NeonKrby** [comment]
No teleportation is gay. Make the spawn smack dab in the middle of fucking the Sahara Desert

**Comment by AlexGamerYTT** [comment]
Lol. Teleportation is not gay and.. How's that relevant?

Well. Making the spawn on the Desert isn't a bad idea.

**Comment by Pengun78** [comment]
I think it should be in the ocean as people in the future may wanna make a town in the desert or desert nations but the spawn will just fully be in the way

**Comment by Kyoris** [comment]
Make it in the ocean by the world border lmao

**Comment by NeonKrby** [comment]
Nah 0,0 off the coast of Africa. Also make it so /spawn doesnt exist you only spawn there when you first join.

**Comment by Ultil0l** [comment]
Teleportation is gay

**Comment by NigelFarage666** [comment]
Thats going to ruin the whole anti tp and capital city trade thing.

**Comment by Ultil0l** [comment]
oof

**Comment by Pengun78** [comment]
nigel whats the diffrence between meeting at spawn and meeting at a capital

**Comment by Ultil0l** [comment]
and at this point everyone is allied to everyone

**Comment by KarlOfDuty** [comment]
We do not think adding a server spawn would be better than the current spawn and teleportation system.
