### ISSUE TITLE
[World] Nahuel Huapi Lake missing

### ISSUE THREAD

**Issue by AlexGamerYTT** [EarthMC/Issue-Tracker#304]
**Describe the issue**
Nahuel Huapi Lake, one of the biggest of Argentina irl isn't shown ig, it would be nice to see it included.

**Coordinates**
https://earthmc.net/map/?worldname=earth&mapname=flat&zoom=6&x=-13311&y=64&z=7391
The lake should be located a few chunks to the north of the town "Bariloche" which is shown at the coordinates.

**Screenshots**
Lake in Google Maps: https://cdn.discordapp.com/attachments/522098369339064343/535527283969097728/Screenshot_2019-01-17-15-33-09.png

**Comment by PoppyK** [comment]
-13336 130 7471
Parts of the lake are there but they can be connected to form it as a whole.

**Comment by AlexGamerYTT** [comment]
Oh okay. I saw that though.

**Comment by PoppyK** [comment]
done

**Comment by AlexGamerYTT** [comment]
Thank you so much poppy!
