### ISSUE TITLE
Make Rivers the River Biome

### ISSUE THREAD

**Issue by EchoOcelot** [EarthMC/Issue-Tracker#306]
**Describe the issue**
Hi. I recently discovered that drowned mobs are more likely to spawn in river biomes, but no rivers appear to actually be the “river” biome. With WorldEdit’s /setbiome command, you would be able to change the biome. I suggest that, at least for now, one river is turned into the “river” biome. More can be done later, but I just need one for now.

**Comment by Kyoris** [comment]
Actually thou the Dneiper is a river

**Comment by EchoOcelot** [comment]
Really?

**Comment by Kyoris** [comment]
Yea at least from what ik

**Comment by EchoOcelot** [comment]
Cool thx
