### ISSUE TITLE
[Feature] Bring back 3D dynmap 

### ISSUE THREAD

**Issue by AlexGamerYTT** [EarthMC/Issue-Tracker#308]
**Is your feature request related to a problem? Please describe**
Classic EMC got updated to 1.13 before it closed so.. THERE is no reason to remove the 3d dynmap feature.

It was so nice to see all the map in 3D, the buildings, it almost looked like Google Earth hehe

But now, there is nothing.

We miss 3D at the dynmap.

**Comment by AlexGamerYTT** [comment]
Server will need 2 weeks to render the whole map on 3D.

Closing issue

**Comment by BowShot118** [comment]
f in the chat for this idea
