### ISSUE TITLE
[Suggestion] Remove newbie protection when they attack players

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#311]
It's annoying when I go and attempt to kill some people who are being general douches in chat but have newbie protection. They can fight me but I can't fight them? fucking ridiculous because they're literally invincible but can fight players. I dont wanna get gangbanged by a group of newbie just because i can't fight back.

**Comment by Kyoris** [comment]
Good idea

**Comment by FutureCW** [comment]
> Good idea

thank

**Comment by Coffeetom** [comment]
Yeah this should definitely be a feature

**Comment by cat234** [comment]
Ja
