### ISSUE TITLE
[Mechanic] Dis-Allow people to use the N Word [Plugin]

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#312]
Well the thing is that people get warned for saying the N word and other stuff close to it, its simple why not install a plugin to make it so messages that are the n word and other close replicas so people don't get warned so much.

**Comment by NigelFarage666** [comment]
Oh fuck off snowflake

**Comment by AlexGamerYTT** [comment]
Not a bad idea really.

**Comment by Magenent** [comment]
> Oh fuck off snowflake

Lmao I'd personally want everything to be allowed but if staff warn for saying the n word why not just not allow people to say it so they don't get warned/banned all the time

**Comment by Zasdd** [comment]
+1 common sense plugin with current ruleset

**Comment by KarlOfDuty** [comment]
We may introduce a chat plugin at some point again, but at this time it just takes too much cpu power to be worth it.
