### ISSUE TITLE
[Feature] Discord Design Snapshot Channel

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#314]
With not having tp on this map one thing I really miss is visiting towns to see the different styles and builds.  I think it would be great if we could have a channel where players could upload their builds to be viewed.  Possible names for the channel: "Town Showcase", "Build Design" or "Snapshots".

**Comment by AlexGamerYTT** [comment]
Nice idea!

**Comment by ThePuppay** [comment]
Should be more of a festival of sorts, but agreed

**Comment by johnyuki** [comment]
People can create pages for their town on the wikia. It would be nice to see more use of it.

**Comment by KarlOfDuty** [comment]
I would also say that the wiki is the best place for this, we may want to advertise it a bit more so more players use it.
