### ISSUE TITLE
[Suggestion] Change Commands to Join Towns/Nations

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#315]
Change towny commands so that it's easier to join them. Every time I invite someone to either my nation or town, they never know the command to join

**Comment by AlexGamerYTT** [comment]
They're too easy already... Unnecesary

**Comment by BowShot118** [comment]
^

**Comment by AlexGamerYTT** [comment]
^

**Comment by Pengun78** [comment]
^

**Comment by Coffeetom** [comment]
^

**Comment by FutureCW** [comment]
^

**Comment by NeonKrby** [comment]
^

**Comment by NigelFarage666** [comment]
You gotta be awfully dumb If you can't join a bloody town.

**Comment by KarlOfDuty** [comment]
I don't see how this could possibly be an issue or how changing it would help.
