### ISSUE TITLE
[Suggestion] Raise the Cost to Create a Town

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#316]
Nowadays there's so many towns and nations and a bunch of players who want to go make towns instead of staying in the one they presently reside in. I believe that it's necessary to raise the cost of towns like nations.

**Comment by BowShot118** [comment]
What the absolute fuck

**Comment by BowShot118** [comment]
Sorry I correct myself, now you're all established with a large town, you want to make it harder for people to make their own towns. There is nothing wrong with making new towns whatsoever. The lower price encourages you to get along with town members and make them want to stay, not just give them a plot and tell them to 'have fun'

**Comment by FutureCW** [comment]
> Sorry I correct myself, now you're all established with a large town, you want to make it harder for people to make their own towns. There is nothing wrong with making new towns whatsoever. The lower price encourages you to get along with town members and make them want to stay, not just give them a plot and tell them to 'have fun'

Yeah it's just annoying when before you could recruit people to your town quite easily, but nowadays it has become a competition on who can offer more bonuses to get people to join a town. And then half the time those new players will end up being inactive.

**Comment by BowShot118** [comment]
Most people want residents for claims, and spamming invites to new players tends to work. Raising the town cost would just help to dis-intrest players who are new, or wish to move on EMC

**Comment by PoppyK** [comment]
If a player is disinterested in the server within minutes of logging and finding out that it will take a few days of work to make a town then it probably isn't the right server for them anyways.  This is a server that takes work.  

But back to the topic, I feel there are too many small towns on the map.   Towns that are just a few players, have one structure, possibly a small garden and that might be it.  There is no real infrastructure and stability.  Why not make larger towns that can really support a nation well?  I don't think it is unreasonable at all for a town to cost 50g or a little more.  That would be more in proportion to the new 1000g nation price too.  If towns were more of a sacrifice to make, many players might decide to join an existing town.

**Comment by Coffeetom** [comment]
This is a pretty good idea, because it helps encourage people to be a active citizen (something many towns lack) before becoming a mayor. Like in most non earth towny servers, you have to spend at least a week or 2 before having the funds to start a town. This made sure there weren't too many towns, and all towns had active citizens. This would be great for EMC in my opinion

**Comment by BowShot118** [comment]
Why don't we raise plot costs while we're at it?

**Comment by Pengun78** [comment]
No not plot costs

**Comment by MineHero43** [comment]
If you want more players to come together and form bigger towns, remove the limit of only 50 players being able to join a town

**Comment by Ultil0l** [comment]
If we raise town cost, why not bring back town upkeep! its such a great feature!

**Comment by Ultil0l** [comment]
> This is a pretty good idea, because it helps encourage people to be a active citizen (something many towns lack) before becoming a mayor. Like in most non earth towny servers, you have to spend at least a week or 2 before having the funds to start a town. This made sure there weren't too many towns, and all towns had active citizens. This would be great for EMC in my opinion

This is bullshit

**Comment by Kyoris** [comment]
Like raise town cost is fine BUT NOT PLOT PRICE

**Comment by ThePuppay** [comment]
Well damn, I agree with this reasoning as poppy put it, why don't we reopen the issue?

**Comment by Ultil0l** [comment]
And in real life (ik EMC isnt real life) most towns are small shitty hamlets with 100 people

**Comment by BowShot118** [comment]
Ir's a bad idea, you don't have to introduce guidelines and make it harder for players, you know, play the game....

**Comment by BowShot118** [comment]
Still a bad idea non the less

**Comment by NigelFarage666** [comment]
Such a great idea! Pock fuck off you aren't even playing.

**Comment by Pengun78** [comment]
Nigel why do u hate our blue colored friend so much

**Comment by BowShot118** [comment]
I play xdxd I've been grinding for a  nation @NigelFarage666

**Comment by NeonKrby** [comment]
grinding more like logging on daily for vote gold.

**Comment by BowShot118** [comment]
I've mined over 200g this week tyvm

**Comment by AlexGamerYTT** [comment]
A town which is our enemy has mined 250g in 2 days

**Comment by AlexGamerYTT** [comment]
In like 10 total hours of playing

**Comment by Ultil0l** [comment]
You are being too special for me

**Comment by AlexGamerYTT** [comment]
Agreed, Future.

Town creation cost higher
Town claim cost lower

Perfect!

**Comment by Coffeetom** [comment]
^

**Comment by Ultil0l** [comment]
I think thats the point too

**Comment by BowShot118** [comment]
Exactly what Ult said

**Comment by FutureCW** [comment]
Well it should be a team effort.

**Comment by BowShot118** [comment]
No, it shouldn't.
Nations should be
Towns should not.

**Comment by FutureCW** [comment]
Ok I see your point, but on other towny servers it would atleast take me like a week to form my own town while on here it can take less than a day to a max of 4 days
