### ISSUE TITLE
[World] Canal du midi and Canal de garonne

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#317]
There are 2 big canals in france called Canal du Midi and Canal de Garonne
I want this created as its as big as a river and its visible on the french map just like a normal river
Im on phone and cant include an image, just search it up

**Comment by AlexGamerYTT** [comment]
Good idea, but I never have heard of these canals though.

**Comment by Pengun78** [comment]
Lol theyre pretty big its literally bigger than some rivers its also wide

**Comment by Pengun78** [comment]
Nvm ill make it myself i dont think canels should be made by the design team

**Comment by BowShot118** [comment]
Canals are man-made structures

**Comment by Pengun78** [comment]
Exactly
