### ISSUE TITLE
Earthmc distance to short

### ISSUE THREAD

**Issue by MongoliaTemujin** [EarthMC/Issue-Tracker#318]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MongoliaTemujin** [comment]
I feel to short 
There are 7 Russias Bc They all cant connect 2 Tangs and Its hard for me to even join a town in some places

**Comment by MongoliaTemujin** [comment]
If This cant do Please Please Lower the Cost for Nations

**Comment by BowShot118** [comment]
???

**Comment by AlexGamerYTT** [comment]
What the hell?
I understood the title, but what with the description?

Anyways, I see the map too big so there's no why to make it BIG CHUNGUS

**Comment by Ultil0l** [comment]
too short*

**Comment by Kyoris** [comment]
_too short_

**Comment by MongoliaTemujin** [comment]
500 will be good

**Comment by KarlOfDuty** [comment]
Remake the ticket with a proper description of the issue if it is still a problem, I don't understand what you are talking about.
