### ISSUE TITLE
[Suggestion] Make run speed on paths higher than normal.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#319]
In real life, people make paths through forests, mountains, and plains, because it is quicker to travel along an established path than to treck through the wilderness. I think this should be reflected in-game too. 

You can make paths really easily by right-clicking on grass blocks with a shovel. 

This would encourage people building paths between towns which is what happened in real life before cars and stuff were invented. It's also a much cheaper option than buying a load of ice and making ice roads, and is great for linking towns that are in close proximity to each other.

**Comment by AlexGamerYTT** [comment]
Good idea john like all of yours

**Comment by ScaryDragonn** [comment]
It would mean paths are actually good and useful for once

**Comment by KarlOfDuty** [comment]
If this is even possible it would cause more lag than any of our largest plugins due to the need to do a giant amount of extra block checks.
