### ISSUE TITLE
[Suggestion] Allow us to sort "/n list" by different parameters

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#320]
Currently, _/n list_ only displays top nations sorted by number of residents. It would be good to see this command have a parameter added so that we can choose from the following: 

- Highest bank balance.
- Highest number of towns.
- Chunks claimed (All town sizes added up).
- Active members (This could be calculated by members that have logged on in the last week).

The same would be good to see for towns and players too.

**Comment by AlexGamerYTT** [comment]
gr8 idea. You deserve to be moderator john, hehe

**Comment by KarlOfDuty** [comment]
You would have to go to the towny developers to ask for this: [TownyAdvanced/Towny](https://github.com/TownyAdvanced/Towny)
