### ISSUE TITLE
[Suggestion] Increase mobs per chunk limit

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#321]
I have this large 16x16 room for my cows: https://i.imgur.com/H6ZFNHY.png

I was hoping that it would allow me to get more of them in there without suffocating, but no. They all cram themselves into that corner and begin suffocating. This means that I have to manually drag them apart and spread them around the room. It also means that in this massive amount of space, I have to have a single group of animals, whereas usually I could easily split this room into 2 or 3 grids and have different animals in each grid. It just hurts not having any real organisation because of the entity cramming.

**Comment by AlexGamerYTT** [comment]
Yeah.

**Comment by Kyoris** [comment]
maybe wall them up into 4x4 areas with 2-4 cows each?

**Comment by Magenent** [comment]
The server already lags a lot, and partially due to entity lag, this could be implemented if other lag is cut down on or the server is upgraded to be a better server.

**Comment by KarlOfDuty** [comment]
Should be fixed by the stacking plugin.
