### ISSUE TITLE
[Plugin] /itemfilter plugin

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#322]
It's an inconvenience having to toss out cobble and other non-valuable items while mining or doing anything. It would make mining so much easier as I believe you're able to whitelist items or blacklist items, or even disable picking anything up at all.

**Comment by AlexGamerYTT** [comment]
👏👏👏

**Comment by TypicalFernie** [comment]
are you really that lazy to toss out some stuff

**Comment by Steadlington** [comment]
Just create 1 stacks in your inventory (Of the item you want to pick up), so it blocks the picking up of items that you don't want and allows the items that you do want. You don't need a plugin for this shit.

**Comment by KarlOfDuty** [comment]
As others have mentioned, there is no need to add a plugin for this.
