### ISSUE TITLE
/plot set name character limit extension

### ISSUE THREAD

**Issue by tribubb** [EarthMC/Issue-Tracker#323]
Would it be possible to extend the name of plots, which would make it easier to name streets and places in cities. 

The current character limit of 16, while having some consideration limits the names that can be assigned to landmarks and other significant sites.

**Comment by johnyuki** [comment]
Also, allow us to have underscores in plot names!

**Comment by BowShot118** [comment]
Underscores are replaced with spaces, I don't see the issue myself

**Comment by Coffeetom** [comment]
Yeah spaces get removed, however if you use an underscore "Market_Square", it becomes "Market Square".
And I really doubt you need to have an underscore in your plot name.
Therefore nothing needs to change.

**Comment by KarlOfDuty** [comment]
This can not be changed individually and is the same as the town and nation name lengths.
