### ISSUE TITLE
[Suggestion] Loosen the limitation on characters allowed on town/nation board!

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#324]
A lot of characters are currently prohibited on the /board message. Characters such as commas, slashes. It would be nice to see these restrictions loosened so that I can include a link in my board message, or telling people to do certain commands.

**Comment by BowShot118** [comment]
YAS.

**Comment by KarlOfDuty** [comment]
We cannot change this in the config.
