### ISSUE TITLE
[World] Plains biome in middle of swamp

### ISSUE THREAD

**Issue by mihinal** [EarthMC/Issue-Tracker#325]
The Danube Delta has a river biome in the middle of the swamp biome.
Coordinates 5015,-8538

![screenshot 9](https://user-images.githubusercontent.com/47060356/51789218-36816380-218f-11e9-9a29-aa5bf0fa8659.png)

**Comment by PoppyK** [comment]
I can take care of this early next week.

**Comment by PoppyK** [comment]
done
