### ISSUE TITLE
[Mechanic] Daily Upkeep of 1 Gold

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#326]
If the cost of towns won't be raised I believe it is fair to have a daily town upkeep of 1g. It is low so that active towns can just vote and put some gold in the town to keep it running, but it eliminates inactive towns because they aren't paying the ridiculously small upkeep. If the towns can't pay 1g a day, then they're inactive and don't deserve to be a town.

**Comment by Pengun78** [comment]
Why do you like raising prices so much

**Comment by Kyoris** [comment]
dude like _why_ are you trying to make it even more difficult for me

**Comment by FutureCW** [comment]
Ok town cost may be a bad idea but having a bunch of inactive towns that wont be deleted till like 40 days is useless as well

**Comment by BowShot118** [comment]
What the fuck mate, yeah let's punish the people who don't log on daily

**Comment by FutureCW** [comment]
/vote - 10 gold in bank - 10 days not having to log on daily
Wow what a surprise

**Comment by BowShot118** [comment]
Then it doesn't fix any problem you've stated.

People log in to keep their town alive
People will log in once every 8-10 days to vote. Lmao

**Comment by Pengun78** [comment]
Guys this is absoulte bullshit. FoxFantastic, Fix, Karl, John, and 1212ra all barged into a voice chat and then yelled at raised voices and then attacked me verebally for shit that shouldnt be anywhere close to allowed in these chats. They say stuff that im a 58 year old cat and laugh at me. Then they got my dad to beat me with his belt. They make fun of my speech impeachment and laugh at that. These people are the gods with our nation. People who truley try to raise their voice over others so you cant hear them. These people are the legends here.  People who belive bullying and harrasring others in VC is epic are pretty epic. Take a hard look and see if you want to stand beside someone that thinks its okay to do these gamer things. This is why EchoOcelot should be the new owner of emc. You are improving for what we game for.

**Comment by BowShot118** [comment]
How do I report staff abuse?
EarthMC has zero tolerance for staff abuse. Please contact Fix#0001 or KarlofDuty#5275 through discord and provide as much evidence as possible.

**Comment by Steadlington** [comment]
I agree with your post FutureCW, the amount of noob towns that take up space in Europe. Noob towns also block pvp because anyone can just run into another noob town's claim, that is like 50 blocks away.

**Comment by Kyoris** [comment]
I mean if someone votes for 6 days after making their 1-chunk town they would literally have enough gold on them to last them 2 months, which doesn't help the problem

**Comment by Zasdd** [comment]
+1, purge inactive towns. It's incredibly easy to maintain a 1g/day tax

**Comment by NeonKrby** [comment]
theres no point inactive towns die after 42 days anyways

**Comment by BowShot118** [comment]
^^^^

**Comment by KarlOfDuty** [comment]
As others here have stated, inactive towns are already deleted so there is no reason to add another way of doing that.
