### ISSUE TITLE
[Bug] If your shop signs make some sales while you are offline and you have a full inventory, the gold is dropped on the ground when you log in.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#327]
I feel like it should go into some kind of "waiting" phase, where it waits for you to have inventory space before trying to put it in your inventory.

**Comment by creatorfromhell** [comment]
This isnt a bug, this is the intended functionality. I have no plans to change it from this

**Comment by johnyuki** [comment]
How come? Seems a bit user unfriendly. How about a warning message in chat if the gold gets dropped on the floor when you log in?

**Comment by Steadlington** [comment]
If you know that you may risk losing gold when you have a full inventory, why not keep your inventory less than full when you log out?

**Comment by johnyuki** [comment]
> 
> 
> If you know that you may risk losing gold when you have a full inventory, why not keep your inventory less than full when you log out?

Because I don't have perfect memory. Rule 1 of programming - always assume the user is retarded and account for that when designing.

**Comment by creatorfromhell** [comment]
> > If you know that you may risk losing gold when you have a full inventory, why not keep your inventory less than full when you log out?
> 
> Because I don't have perfect memory. Rule 1 of programming - always assume the user is retarded and account for that when designing.

Indeed you should always assume that the user is incapable of certain things, but including a queue for such a thing is not something that will be added. A message to indicate gold being dropped on the ground will be added, but a queue won't be added.
