### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#330]
Ok so im not doing this for myself or because im a donator myself but i think all donators (yellow purple and blue) should get player heads
they are helping you keep up the server and all they get is a few commands and putting things on their head. I am grateful for the features i got but i just think all donators should get a skull of their head

**Comment by BowShot118** [comment]
🤔 The heads are one of the only 2 things that gives people an incentive to buy Frost over Yellow.

**Comment by Pengun78** [comment]
yeah but they gave money to the server which is why i think they deserve something good back that can actually be used

**Comment by AlexGamerYTT** [comment]
yeah

**Comment by KarlOfDuty** [comment]
This makes no sense. With your logic yellow donators would just get everything that the higher tiers get even though the higher ones have donated much more.
