### ISSUE TITLE
[Mechanic] Add the ability to use treefeller on logs with bark on all 6 sides

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#331]
There's really no downside to being able to actually use treefeller efficiently, and it would probably improve the overall experience of expanding a town as you need to do less work when cutting down custom trees. Also trees in general are supposed to work with Mcmmo but can't due to them being custom, large, and annoying.

**Comment by Kyoris** [comment]
**YES**
Finally cutting down those cursed trees would be easier

**Comment by BowShot118** [comment]
I approve

**Comment by KarlOfDuty** [comment]
This is an mcmmo issue, they are working on it on their end.
