### ISSUE TITLE
[BUG] Villagers being lost to stacking, and then randomly deleted from the stack entirely.

### ISSUE THREAD

**Issue by Englavian** [EarthMC/Issue-Tracker#335]
**Server**
Earthmc.net
**Describe the bug**
Stackmob combining essential and important to seperate mobs (Villagers). Combined mobs are also somehow being deleted and now only displaying a single mob. Goes from bad to worse.

**To Reproduce**
1. Work very hard to assemble a lot of villagers
2. Do nothing beyond secure them as you should
3. Have stackmob added to the server
4. Lose over a dozen vital villagers who sell unique things because theyve been forcibly merged into a butcher, and then deleted.

**Expected behavior**
Villagers should not be stacked. Bottom line.

**Screenshots**
Directly after the stacking, showing that I have lost a dozen villagers https://i.imgur.com/Zwjtt05.jpg
Hours later, showing theyve been removed entirely with no tag https://i.imgur.com/MD4K005.jpg

**Additional context**
Some villagers are not merged for some reason, being in a minecart did not save all of them though.

**Comment by WyWall** [comment]
wait would villagers even be able to breed if they stack?

**Comment by KarlOfDuty** [comment]
Should be fixed now.
