### ISSUE TITLE
Simple Request - clarify what is allowed

### ISSUE THREAD

**Issue by TheObsidianSword** [EarthMC/Issue-Tracker#336]
I was killed and I wanted my stuff back so I messaged the player who killed me and asked them how much for my stuff back. I bargained them down to 9 gold and went to meet them. So I paid them but they wouldn't give me my things. After talking to a mod they told me scamming wasn't breaking any rules. But I had no way to know about this because it was never clarified and I thought that since scamming is usually against the rules on most servers and it would also be against the rules here.

So I am not asking that you making scamming against the rules, I'm only asking that you clarify things that are allowed on the server that aren't usually allowed other servers. And maybe even the other way around things that are against the rules here but most servers allow.

**Comment by Pengun78** [comment]
Whats that dudes name

**Comment by Coffeetom** [comment]
Earthmc.net/rules

This website has all your answers

**Comment by KarlOfDuty** [comment]
If you want anything specific to be added to the rules you can make a new issue about it.
