### ISSUE TITLE
[Feature][Plugin][World] Resource world and Anti-Xray Lag

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#337]
Main Feature
The feature I wanted to discuss is that of a secondary resource world.

Reasons for Resource World - 
A secondary resource world in which people could mass harvest things like sand, ores, ice, etc. Although this would take away from the vanilla feel of the server, it would also prevent massive areas like those around Thebes(Egypt), and Judah from becoming mass sand depots. 

Potential opportunity in solving Anti-Xray Lag issues with secondary resource world - 
with the opening of a secondary resource world the server could potentially remove all gold ore in the current world and have the resource world take the burden of gold mining. Thus the main world could potentially not have anti-xray upon it while the resource world does. This would drastically improve the lag on the server because the sheer amount of resources in terms of computing power would not be taken up by the potentially hundred people who aren't mining while the server would have to only run the anti-xray for whoever is in the resource world to gather resources.

these are just my thoughts and ideas being rambled out, and i don't know if its something people would agree with me on it being a good idea. So i thought id put it out there.

**Comment by KarlOfDuty** [comment]
We will not be adding a resource world at this time.
