### ISSUE TITLE
[Suggestion] inactivity

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#338]
i think that inactivity thing where ur town falls should be lowered to 20-25 days
lets be honest if someone makes a town and doesnt join for another 20 days do you really think he will keep on playing

**Comment by Zasdd** [comment]
+1 Lower inactivity to 20 days (or add upkeep), if people don't play for 3 weeks in a row it's doubtful they will return

**Comment by NeonKrby** [comment]
why the fuck do you do +1 and -1 shit

**Comment by NeonKrby** [comment]
Also fuck upkeep
Only on nations

**Comment by Zasdd** [comment]
As a voting system @Neon, and why don't you want upkeep?

**Comment by AlexGamerYTT** [comment]
They can be on holidays so smh

I would lower the number to 31 days

**Comment by Pengun78** [comment]
if you have to leave for a month just asks the mods to make it not disband itself

**Comment by KarlOfDuty** [comment]
We cannot disable it for specific towns.

**Comment by asher1099** [comment]
Oof

**Comment by AlexGamerYTT** [comment]
Oof
Here 70% of the country can afford a 15 day vacation perfectly and even that we're on a bad economic situation

**Comment by NeonKrby** [comment]
So 15 day vacations is within the inactivity limit. ezpz

**Comment by asher1099** [comment]
Sounds like Greece

**Comment by Pengun78** [comment]
Last vacation was fucking 8 days in spain #epic

**Comment by Coffeetom** [comment]
15 days definitely isn't enough. Many people go on holidays for longer than that. Plus people can have problems with internet (very big issue in Aus). The current system works good enough, so might as well keep it.

**Comment by NeonKrby** [comment]
20 days. should be it. Also fucking log in with pickaxe chat to not let your town die ezpz

**Comment by shirazmatas** [comment]
Guys guys, you don't even need money to be able to stop playing for 20 days.
1. you get a shit ton of work you gotta focus on.
2. you travel to a monastery or go interail
3. you're in hospital

**Comment by BowShot118** [comment]
> Guys guys, you don't even need money to be able to stop playing for 20 days.
> 
> 1. you get a shit ton of work you gotta focus on.
> 2. you travel to a monastery or go interail
> 3. you're in hospital

mhm. lets ban pengun for being rude

**Comment by NilsNyfiken** [comment]
There’s actually this thing called a road trip that proble go on for a couple of weeks in the summer, I also know that many Swedish dudes go to their summer houses and other stuff

**Comment by shirazmatas** [comment]
Yes exactly

**Comment by Pengun78** [comment]
Ban me

**Comment by Pengun78** [comment]
Idk then u can make a ticket telling mods to keep ur town from disbanding

**Comment by NilsNyfiken** [comment]
That might be a good idea, idk how that would work though

**Comment by Toadally** [comment]
I'd be behind lowering it to 30.

**Comment by cat234** [comment]
Das ist blod

**Comment by KarlOfDuty** [comment]
We will not be lowering it at this time as this has been a pretty good limit from past experience.
