### ISSUE TITLE
[Suggestion] Fishing for likes!

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#339]
Hi, I just wanted to suggest a way to get the new 1.13+ items. Since aqautics was the theme of the update, I was thinking maybe you could fish up some of the unobtainable items. Only, they'd have incredibly rare odds. Stuff like... .01% to get a Heart Of The Sea.

 Also, I think that the vanilla fishing drops should be combined with these and the MCMMO ones. Perhaps you could also get stuff like gaurdian drops and stuff. I don't know, I'm not a big brained boy. Maybe you could help out in the comments?

**Comment by KarlOfDuty** [comment]
We are already planning another way to get those items, if you want you can make a new issue stating which items need to be added.
