### ISSUE TITLE
[Suggestion] Summoning/Call Of The Wild enhancements! 

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#340]
As you may or may not know, using 10 of specific items, you can spawn a mob. By default, there are only 3 of these. 10 Apples for a horse, 10 bones for a wolf, and 10 raw fish for a cat. I'd like to begin by saying that this is a criminally under used system, but I understand why. Bones are quite hard to get a hold of due to rarity of skeletal mobs. That's why I think there should be more than just wolves as an attack animal.

What I'm getting at here is that this system could be expanded upon and improved! For example; what if you could use 10 of both mushroom types and 10 beef to spawn a mooshroom. It doesn't have to be 10 either! Imagine if you could spawn a blaze for two sets of 64 blaze rods that wouldn't be hostile towards the one who spawned it.

I personally think this would add a whole new level to combat and battles. Please tell me what you think below in the comments.

**Comment by KarlOfDuty** [comment]
May not be possible but I'll look into it.

**Comment by Steadlington** [comment]
Bones and apples are obtained through excavation, not that rare.

**Comment by BunbunToast** [comment]
> Bones and apples are obtained through excavation, not that rare.

Thank you for the input and info!
