### ISSUE TITLE
[Suggestion] Allow us to edit shop signs without needing to destroy the sign and re-place it.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#342]
In order to edit price or number of items received, you have to destroy the shop sign. This is a pain in the ass because it means you then have to re-set the storage chest and everything as well. If you have shops in multiple locations like I do, then it gets very tiring. 

A way to edit the sign without needing to go through the entire process again would be very nice.

**Comment by PoppyK** [comment]
Oh, this would be so handy!!

**Comment by KarlOfDuty** [comment]
You can ask for this from the economy dev and see what they say. https://github.com/TheNewEconomy/TNE-Bukkit/issues
