### ISSUE TITLE
[Suggestion/Feature] New (and old) Fishing Drops!

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#343]
I have a few thoughts. I mostly fish on the server, because it's one of the easiest ways to get useful junk and exp. However, I've noticed that the loot tables were changed to MCMMO but doesn't have the original loot tables. ( https://minecraft.gamepedia.com/Fishing#Junk_and_treasures )

I'd like to see these added back in. Currently, you can't even really get Nautilus Shells, Leather (although you can still get leather armor) and some of the newer enchantment books from fishing. I'd like to see this fixed very much. 

I would also like to see new drops from fishing as well. I've prepared a little list:

-Prismarine (in all forms)
-Corals (also in all forms)
-Turtle eggs, shells, and helmets
-Fish buckets (salmon, puffer, and tropical)
-Phantom membranes
-Sea grass and sea weed
-Sea pickles
-Forms of ice (perhaps this could be configured to only work in colder biomes)
-Tipped arrows (Maybe even with unique potion effects)

Final thought; while these all pertain to items, I'd also like to see fishing produce mobs every now and then. Imagine the possibility of getting a guardian (possibly even an elder guardian) spawned on your 1000th catch, as punishment for overfishing! Or a horde of drowned zombies! Despite the 1.13 update, the oceans on the server still feel really dead, and I honestly think these changes to Fishing could improve that. Sincerely written- Toast.

P.S.
Please leave comments below on your opinions of this. I love feedback. <3

**Comment by AndrewCheedle** [comment]
This has been dead for a while but I hope it gets added. Fishing has been underrated for a long time because it is nerfed to death. I hope they add these features
