### ISSUE TITLE
[Suggestion] Add a /map command

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#344]
I see people all the time asking how to see the map. Would be nice to have a /map command rather than copy and pasting the map in chat every time.

**Comment by johnyuki** [comment]
Also, adding on to this idea, the /map command could actually open the map at their current location. The map link looks like:

https://earthmc.net/map/index.html?worldname=earth&mapname=flat&zoom=4&x=26260&y=64&z=764

You can see the x and z coordinates there, so it would be very easy to insert the player's current coords in to that link, which would be especially useful for new players asking "where am I".

**Comment by NigelFarage666** [comment]
Is it seriously that hard just to google "Earthmc"?

**Comment by KarlOfDuty** [comment]
I mean the map link is shown in chat every single time you join the server, I don't think adding a new plugin for this is worth it.
