### ISSUE TITLE
[BUG] When I open the EarthMC map, it doesn't load and I'm left with a black chrome tab.

### ISSUE THREAD

**Issue by SaucySalmon** [EarthMC/Issue-Tracker#345]
**Server**
EarthMC non-classic.

**Describe the bug**
When I open the EarthMC map, it doesn't load and I'm left with a black chrome tab.

**To Reproduce**
1. Go to https://earthmc.net/
2. Click on 'MAP' at the centre-top-right of the page
3. See that the tab is black and that the map hasn't loaded.

**Expected behavior**
I expected the map to load as it has done for me in the past.

**Screenshots**

**Additional context**

**Comment by AlexGamerYTT** [comment]
Remove the data and cookies on Chrome. That worked for me (I had the same problem as you do)

**Comment by Ultil0l** [comment]
I restarded my pc and it worked

**Comment by Pengun78** [comment]
lol its a chrome problem i have it too i just use microsoft edge for the map and do all the other things on chrome

**Comment by NigelFarage666** [comment]
We use -new for that.

**Comment by KarlOfDuty** [comment]
This seems to be a local issue for you.

**Comment by PoppyK** [comment]
@SaucySalmon also, just try refreshing the map page.  I have had this happen too but after refreshing, I was able to view the map.
