### ISSUE TITLE
[BUG] Ender Chest Bank Accounts Not Working Properly

### ISSUE THREAD

**Issue by Koriandah** [EarthMC/Issue-Tracker#346]
EarthMC Terra Nova

The gold stored in ender chests is not registered in player's bank accounts when they are offline. It works perfectly ok when the players are online however. 
The reason why this is an issue is towny taxation - when people are offline they have 0G in their bank account and so can't be taxed and automatically lose their shop plot; the mayor doesn't get any gold from taxes and residents lose their plot(s). 

1. Do ./res or ./player on someone who is online and who has gold in his ender chest
2. Check number of Gold Ingots
3. Have that player leave the server
4. Do ./res or ./player again and see that the number of gold in his account is 0

Before, this issue worked fine since most players stored their gold in [safe] chests. Now, however, with their removal, players have been using ender chests. Since those do not work, this means that players have no way of having gold in their bank accounts while they are offline.

Thank you for your work.

**Comment by johnyuki** [comment]
[safe] chests were exactly the same. In fact, they weren't even safe. Town Mayors and Councillors could still take stuff out of them, making them absolutely no different than regular chests in claimed areas.

Also, I wasn't aware that the players balance disappeared when offline, this should definitely be fixed, as tax is something I want to use too, but with how broken it is, it is very difficult.

**Comment by KarlOfDuty** [comment]
That is not up to us, you'll have to talk with the developer of the economy plugin instead.
