### ISSUE TITLE
[Bug] Blazes Not giving xp and vanishing

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#347]
**Server**
EMC

**Describe the bug**
Blazes Will simply vanish and approximately 50 - 75% of the time wont drop xp when killed

**To Reproduce**
1. Mob Grinder in Scotland 
2. Kill blazes/watch blazes simply vanish

**Expected behavior**
Blazes when killed often wont drop xp and will sometimes just vanish out of existence

**Screenshots**

**Additional context**
Issues began occuring after mob stacking was implemented

**Comment by Pengun78** [comment]
Yea idk when i hit them some dissapear and literally almost no blaze spawns anymore after the update it took me long to get some xp at a 50 spawner grindsr

**Comment by KarlOfDuty** [comment]
This should be fixed now.
