### ISSUE TITLE
[Mechanic] Xp bottle command

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#348]
I heard selling xp was something that may come in the near future and Im not sure if it's through xp bottles or just taking levels from the player, but there could be a command like /bottle get # or /bottle get max to take xp from you and turn it into xp bottles. It would be convenient for miners as well. Helps with mending items faster

**Comment by creatorfromhell** [comment]
Selling XP will be through command, via paper notes. So it's all done through the [item] sign system without adding a learning curve

**Comment by NigelFarage666** [comment]
We used to do what on Classic, sad no one remembers.
