### ISSUE TITLE
[Suggestion] Separate /baltop to allow "/baltop [player|town|nation]"

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#349]
Would be nice to see all three lists separately.

**Comment by NeonKrby** [comment]
would have to be a separate plugin as /baltop is an essentials command.

**Comment by creatorfromhell** [comment]
/baltop is an economy command :wot:

But I'm also not adding a nation/town option to baltop, because this shouldn't be an economy plugin command anyways, you may bug towny for the feature in towny form.

**Comment by NeonKrby** [comment]
its an eco command? i thought it was essentials like every other server in existence xd

**Comment by creatorfromhell** [comment]
No, essentials is crappy, so I override their commands.

**Comment by KarlOfDuty** [comment]
As stated above, this is something for towny to add, so you can suggest it to them if you wish instead.
