### ISSUE TITLE
Actual Nation Borders

### ISSUE THREAD

**Issue by cat234** [EarthMC/Issue-Tracker#350]
**Is your feature request related to a problem? Please describe.**
Sort of, I'd like an actual border for a nation so other people can't join another nation that is in your control area.

**Describe the solution you'd like**
Instead of claiming blocks for a town, claim blocks for a nation instead with towns inside the area. The town's mayor can buy land instead of just claiming it and make to where you can move freely between the provinces/states/municipalities.

**Additional context**

**Comment by cat234** [comment]
Kinda like a big town

**Comment by Kyoris** [comment]
I mean the idea is nice but tbh the way you propose is a bit impractical or at least bad in some sense or another.

**Comment by creatorfromhell** [comment]
The major issue with this is that Towny does not support any functionality to allow this.

**Comment by FutureCW** [comment]
There are maps created by players with borders for each ingame nation. Most nations discuss borders with others.

**Comment by Ultil0l** [comment]
that would still be r e t a r d e d

**Comment by cat234** [comment]
So you'd rather have someone build a town for another nationvright next to yours?

**Comment by NeonKrby** [comment]
this is what d i p l o m a c y is for

**Comment by cat234** [comment]
I suppose I could talk to the creator of towny about it.

**Comment by KarlOfDuty** [comment]
This is not possible.
