### ISSUE TITLE
[Rage complaint] LET ME JOIN A FUCKING NATION

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#351]
Alright, listen dipshits. I joined and made a town before the nation price was 1024 (which is fucking outrageous and stupid and only allows the rich 1% to do anything) and I had a plan to make a nation up where I am because I'm too far away. ( WHICH AGAIN IS ALSO FUCKING STUPID )

**Comment by BowShot118** [comment]
You're going to be banned.
But I agree.
Not every nation will accept all nearby towns as well....

**Comment by TypicalFernie** [comment]
Nation range is gay and dumb and should be removed

**Comment by Pengun78** [comment]
nah man emc classic got so fucked up by it 
here are some examples:
somalia owned by japan
mexico owned by canada
peices of south america owned by canada
madagascar owned by japan
bits of greenland owned by rhodesia (zimbabwe)
estonia owned by spain
much more

**Comment by TypicalFernie** [comment]
or at least increased k thx

**Comment by TypicalFernie** [comment]
#5knationrangewhen

**Comment by TypicalFernie** [comment]
people are still finding ways around the nation range anyways. Wabanaki is divided by 4 towny nations and act as one.

**Comment by BunbunToast** [comment]
> You're going to be banned.
> But I agree.
> Not every nation will accept all nearby towns as well....

If that's what it fucking takes for it to be removed, so be it.

**Comment by GamingZone2** [comment]
idk where to post this but i was banned for "Hacked Client" when i was glitched i got off a boat while it was lagging and i was chasing someone down and i used a speed 2 pot. i think it registered as i was moving on  a boat as if i was on water but on land with a potion active.

**Comment by Kyoris** [comment]
do -new in #general

**Comment by cat234** [comment]
Das ist outrageous

**Comment by NigelFarage666** [comment]
REMOVE NATION RANGE! CLASSIC WAS GREAT WITHOUT IT! 

Or at least make some sort of nation range expansion system because this is becoming ....

**Comment by laidang08** [comment]
> REMOVE NATION RANGE! CLASSIC WAS GREAT WITHOUT IT!
> 
> Or at least make some sort of nation range expansion system because this is becoming ....

Please don't remove nation range. I don't want fucking tang in africa, it just doesn't make sense. You can just make colonial nations which makes 100x more sense. The nation range is fine stop complaining. Maybe it could be expanded by another 1k blocks.

**Comment by cat234** [comment]
That's the issue though, nations like Russia, United States, Canada, Brazil, Argentina, and many others cannot be formed.

**Comment by FurdenFuhrer** [comment]
Nation range is gay, it ruined EMC
Classic was great, it lasted for two years just fine. It has history that cut even deeper than with this dumb nation name and range. Two of the most memorable nations, PWW, and Praxis are made up by the players. Empires that are unique to EMC. With the naming rules, we no longer have that.

**Comment by cat234** [comment]
My nation will be Neolia. But! With these naming rules, it makes EarthMC definitely not a geopolitical SANDBOX

**Comment by FurdenFuhrer** [comment]
The staff won't listen to a majority of the playerbase anyway.

**Comment by Ultil0l** [comment]
Creator is also pretty retarded

**Comment by FurdenFuhrer** [comment]
I would love someone to spread a strawpoll around saying 
Get rid of Naming rules and Nation Range?
Yes
No

**Comment by Ultil0l** [comment]
At this point we are all getting snapped by creator so idc anymore

**Comment by Pengun78** [comment]
Keep the nation range it prevents emc from fucking up you saw these examples i gave earlier

**Comment by NeonKrby** [comment]
remove nation range, East Asian Co-Prosperity Sphere needs to be made ;)
