### ISSUE TITLE
[Feature] Can we get Prismarine as a crafting recipe?

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#352]
Title speaks for itself. Theres no prismarine anywhere and i want to use it :/ there was apparently some in madagascar a long time ago but there isnt enough to satisfy building needs on any large or even small scale.

**Comment by Kyoris** [comment]
hmm yeah that would be nice
Maybe shards can be cyan dye + lime dye and crystals (for sea lanterns) shards + glowstone

**Comment by creatorfromhell** [comment]
I've already discussed this, I think the best solution would be to add prismarine as a drop for turtles.

**Comment by WyWall** [comment]
Problem is that turtles would be apain to actually get practical  amounts
maybe if you get it from gravel or dirt through mcmmo you would get the prismarine shards

**Comment by WyWall** [comment]
Or you could have it so you would only get it from gravel and dirt thats underwater through mcmmo

**Comment by Kyoris** [comment]
ooh yes maybe like exca 250 or 375 for prismarine

**Comment by johnyuki** [comment]
I kinda like the idea of adding it to the drop table of Turtles. It makes them actually useful, and makes sense seeing as Prismarine is a water-based block, and a Turtle is a water-based animal. Adding more blocks to the game whilst simultaneously increasing the usefulness of mobs is a good thing. Excavation is already a useful skill, no need to over-saturate it.

**Comment by KarlOfDuty** [comment]
Done.
