### ISSUE TITLE
[Suggestion] Hey, do you think you could talk to us more?

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#353]
We don't get a lot of news or information at all. When we get new crafting recipes, we're not even told. It would be nice if you could actually tell us something from time to time. Oh! Here's an idea! YOU COULD PUT IT ON THE DISCORD INFO SLIDE.
THE THING SPECIFICALLY MEANT TO INFORM US.

**Comment by NeonKrby** [comment]
yeah like if dungeons are ever going to be added. Or if war

**Comment by Ultil0l** [comment]
yea, we really need more transparent staff

**Comment by NeonKrby** [comment]
we need war btw @mod add it now or you dumb

**Comment by PoppyK** [comment]
@BunbunToast The server changelog is always documented in #announcements.  You will find all the new recipes there too.

**Comment by creatorfromhell** [comment]
@BunbunToast imagine not reading the announcements channel before making this http://prntscr.com/mii69e

**Comment by BowShot118** [comment]
> @BunbunToast The server changelog is always documented in #announcements. You will find all the new recipes there too.



> @BunbunToast imagine not reading the announcements channel before making this http://prntscr.com/mii69e

Putting in in #info does make a lot of sense though.

**Comment by Ultil0l** [comment]
Its not about that creator

**Comment by Ultil0l** [comment]
There is also the fact that it would be nice to KNOW WHAT THE F*** IS HAPPENING DURING MAINTENANCES

**Comment by BowShot118** [comment]
I agree.

**Comment by Ultil0l** [comment]
When we ask all we get is nothing

**Comment by creatorfromhell** [comment]
All maintenances are followed up with a changelog in announcements. @Ultil0l

**Comment by Ultil0l** [comment]
Sometimes we can wait 3 hours, 4 hours, 5 hours or more when there is a maintenance and we never know what the heck is happening during that, As a person who spends most of their time on emc, I feel like we should be able to know what is happening with the fucking server when there is a maintenance.

**Comment by BowShot118** [comment]
> All maintenances are followed up with a changelog in announcements. @Ultil0l So tell me what it is about that isn't outline in the announcements channel?

Most Maintenances go without any form of notice or announcement from staff, before, after or during the "event"

**Comment by Ultil0l** [comment]
Savage

**Comment by creatorfromhell** [comment]
All planned maintenances go with a form of changelog @BowShot118 @Ultil0l . Unless you have a specific example you're referring to?

**Comment by NeonKrby** [comment]
you guys just need to be more transparent we have no ideas when or if dungeons have dropped and we want to know if war is coming or not.

**Comment by Ultil0l** [comment]
AFTER GODDAMNIT! WE ARE ASKING FOR FEEDBACK WHILE THERE IS A MAINTENANCE IS THAT TOO MUCH TO ASK? @creatorfromhell

**Comment by BowShot118** [comment]
I rarely ever see planned maintenance. Whenever the server goes down, nothing is said **even after Fix and/or Karl acknowledges the problem**

**Comment by Ultil0l** [comment]
Whenever we ask questions all we get is some vague answers that just makes the matter worse or no answer at all. "its being worked on" "one day"

**Comment by creatorfromhell** [comment]
> you guys just need to be more transparent we have no ideas when or if dungeons have dropped and we want to know if war is coming or not.

Dungeons have not dropped obviously, as for plans that's something you'll have to talk to fix/karl about as they general plan out the future server features.

As for war, the only reason there isn't war is because there's no real good solution out there currently for it.

**Comment by BowShot118** [comment]
> > you guys just need to be more transparent we have no ideas when or if dungeons have dropped and we want to know if war is coming or not.
> 
> Dungeons have not dropped obviously, as for plans that's something you'll have to talk to fix/karl about as they general plan out the future server features.
> 
> As for war, the only reason there isn't war is because there's no real good solution out there currently for it.

and war is shitty and gay af

**Comment by creatorfromhell** [comment]
As for transparency, I think most features that are added that I'm aware of I make pretty transparent, most of the maintenances that come with no feedback are unexpected ones due to plugin errors.

**Comment by Ultil0l** [comment]
No, we dont get feedback even when the maintenance is planned.

**Comment by BowShot118** [comment]
> As for transparency, I think most features that are added that I'm aware of I make pretty transparent, most of the maintenances that come with no feedback are unexpected ones due to plugin errors.

My point is, no one is told that the server is down, even after Karl and/or Fix realizes that the server is down. A temporary announcement will do but not even that is a thing 🤦‍♂️

**Comment by creatorfromhell** [comment]
> > As for transparency, I think most features that are added that I'm aware of I make pretty transparent, most of the maintenances that come with no feedback are unexpected ones due to plugin errors.
> 
> My point is, no one is told that the server is down, even after Karl and/or Fix realizes that the server is down. A temporary announcement will do but not even that is a thing 🤦‍♂️

That's what the server is undergoing maintenance message on join is for 🤦‍♂️ .



> No, we dont get feedback even when the maintenance is planned.

Again, I'm asking for an example as #announcements contains a log of all maintenances.

**Comment by Ultil0l** [comment]
Yes but we never know what the fuck is happening while the maintenance is happening... Is that really so hard to understand?

**Comment by creatorfromhell** [comment]
> Yes but we never know what the fuck is happening while the maintenance is happening... Is that really so hard to understand?

We don't put it out there until after to make sure every functions as it should, is that hard to understand?

**Comment by Ultil0l** [comment]
We just. Want to. know what. Is happening. With the. Server. We waste. most of. our time. on.

**Comment by Ultil0l** [comment]
I feel like talking to an automated bot rn

**Comment by creatorfromhell** [comment]
> We just. Want to. know what. Is happening. With the. Server. We waste. most of. our time. on.

Right, I'm happy to talk with people until they resort to a sarcastic stylized conversation. The issue with these tickets is that nobody can ever be civilized when talking to staff about things such as this.

**Comment by BowShot118** [comment]
> > We just. Want to. know what. Is happening. With the. Server. We waste. most of. our time. on.
> 
> Right, I'm happy to talk with people until they resort to a sarcastic stylized conversation. The issue with these tickets is that nobody can ever be civilized when talking to staff about things such as this.

This is probably because tickets tend to take a long time to resolved, at least the one's I've heard about. This may also be because of a disliking of *certain* staff members.
No Syn,
He's god.
Long Live Syn(argle)

**Comment by Ultil0l** [comment]
🙏Praise syn🙏

**Comment by Ultil0l** [comment]
No but seriously I feel like I have been talking to a wall for half an hour.

**Comment by cat234** [comment]
Das ist unerhört
