### ISSUE TITLE
[Suggestion] Add unobtainable blocks to the droptable of hostile mobs.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#355]
I saw in another thread that creatorfromhell was thinking about adding Prismarine blocks to the droptable of Turtles. I thought this idea was good and figured it could be a good way of getting a lot of use out of hostile mobs. 

Skeletons are currently incredibly useless, as getting enchanted books is really easy, so it makes their enchanted bow drops useless. You can also get bones easily from MCMMO Excavation skill. 

So to make mobs like that useful again, you could add blocks to their droptable such as the aforementioned Prismarine block, as well as things like End Stone, Shulker Boxes, Sea Lanterns, and a few others. These blocks could be added to the droptable of Creepers, Zombies, and Skeletons to make them useful. They are incredibly rare on the server, but considering they have such useless drops it is pointless trying to hunt them down.

**Comment by KarlOfDuty** [comment]
Not really relevant anymore.
