### ISSUE TITLE
Adding mob eggs

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#357]
I propose adding mob eggs, but in a clever way:
So the idea is that we can craft mob eggs using drops from mobs like blaze rods, zombie flesh, bones, gunpowder, string and spider eyes, as this is the drops you get from your spawners.
So the idea is that the eggs are added in tiers, where an example of a potential tier list is listed here:
Tier 0: Mob drops
Tier 1: Cave spider egg
Tier 2: Spider egg
Tier 3: Zombie egg
Tier 4: Skeleton egg
Tier 5: Creeper egg
Tier 6: Wither skeleton egg
Tier 7: Villager egg

You would then combine 9 items from one tier to get the item of the next tier, for example you would need to combine 9 blaze rods in a crafting table to get 1 cave spider egg.

This would help people who like grinding, to have a progression system, in which they could unlock better an better items, thereby expanding the end game of EMC for them.

Here are listed the amount of mob drops needed for each tier after tier 2
Tier 3: zombies (9^3 = 729 or 11,39 stacks)
Tier 4: Skeletons (9^4 = 6561 or 102 stacks or 1,9 double chest of blaze rods)
Tier 5: Creepers (9^5 = 59049 or 922,64 stacks or 17,1 double chest
Tier 6: Wither skeletons (9^6 = 531441 or 8303,8 stacks or 153,8 double chest)
Tier 7: Villagers (9^7 = 4,78 million or 74733,9 stacks or 1384 double chest)

As can be seen, the tiers after tier 4 require massive amounts of drops, but I believe this will be a good thing, as the value of gunpowder, wither heads, and villagers therefore will remain somewhat high, as it requires serious amounts of commitment to unlock them.

I believe that this will be a great way to reintroduce mob drops, while not adding extra mob related stress, as mob spawners already are enabled and used extensively on the server.

**Comment by 4noah18** [comment]
great idea id just tweak how many mob drops are needed for the upper tiers and bring them down a bit

**Comment by alekb1** [comment]
@KarlOfDuty Potential feature for the faction server, as faction servers are generally more focused on grinding?

**Comment by KarlOfDuty** [comment]
No longer needed.
