### ISSUE TITLE
Add a way to get spider eyes

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#358]
There is no way currently to get spider eyes in the game. Maybe add it either with crafting or as a drop from mcmmo excavation

**Comment by johnyuki** [comment]
You can get spider eyes as Spiders do spawn, but obviously with mob spawns being incredibly rare, Spider eyes are also extremely rare.

**Comment by alekb1** [comment]
As far as i know, only nether mobs spawn, no hostile mobs spawn naturally in the overworld

**Comment by Pengun78** [comment]
# Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):

# Floor 0 - Misc
* 32 Bones - < 30g >
* 128 Flint - < 30g >
* 1/5 Enderchest - < 40g/200g > 
* 32 Glowstone - < 30g >
* 2 Bows - < 30g > 
# Floor 1 - Mining
* 14 Diamonds - < 30g > 
* 64 Iron - < 30g > 
* 28 Lapis/Redstone Blocks - <30g >
* 14 Coal Blocks - < 30g >
# Floor 2 - Farming
* 128 Carrots - < 30g >
* 128 Sugarcane - < 30g >
* 128 Wheat - < 30g >
* 128 Wheat Seeds - < 30g >

# Misc Items - Msg me for these
* Dark Oak Logs -  < 30g > per 3 stacks
* Nether Wart - < 30g > per 3 stacks
* Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
* Iron Chainmail sets - < 40g >
* Prot4 Unb3 Dia Chestplates - < 90g > each
* Villagers - Negotiable Price (70g per villager), no delivery.

# Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.
# Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):

# Floor 0 - Misc
* 32 Bones - < 30g >
* 128 Flint - < 30g >
* 1/5 Enderchest - < 40g/200g > 
* 32 Glowstone - < 30g >
* 2 Bows - < 30g > 
# Floor 1 - Mining
* 14 Diamonds - < 30g > 
* 64 Iron - < 30g > 
* 28 Lapis/Redstone Blocks - <30g >
* 14 Coal Blocks - < 30g >
# Floor 2 - Farming
* 128 Carrots - < 30g >
* 128 Sugarcane - < 30g >
* 128 Wheat - < 30g >
* 128 Wheat Seeds - < 30g >

# Misc Items - Msg me for these
* Dark Oak Logs -  < 30g > per 3 stacks
* Nether Wart - < 30g > per 3 stacks
* Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
* Iron Chainmail sets - < 40g >
* Prot4 Unb3 Dia Chestplates - < 90g > each
* Villagers - Negotiable Price (70g per villager), no delivery.

# Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.

**Comment by johnyuki** [comment]
> 
> 
> As far as i know, only nether mobs spawn, no hostile mobs spawn naturally in the overworld

Not true. There are mobs, they're just very rare.

**Comment by alekb1** [comment]
When was the last time you encountered a mob?

**Comment by johnyuki** [comment]
> 
> 
> When was the last time you encountered a mob?

Just a few days ago I found a couple creepers and skeletons.

**Comment by KarlOfDuty** [comment]
In theory mobs should spawn more now, but we are also working on another thing that may give spider eyes and other loot.
