### ISSUE TITLE
The server should get this plugin

### ISSUE THREAD

**Issue by ExplosiveHD** [EarthMC/Issue-Tracker#359]
let's get a airships plugin

https://www.youtube.com/watch?v=BSJ6K7b-b-M

it would be fun making these for battle and then fighting.

**Comment by johnyuki** [comment]
I think maybe fixing all the other bugs in the plugins would be better to do before adding new stuff like this.

**Comment by KarlOfDuty** [comment]
As we have mentioned previously, we are not looking to add vehicle plugins. Performance issues and other world/entity glitches are way too common with them.

**Comment by ExplosiveHD** [comment]
okay
