### ISSUE TITLE
[World] Gothenburg's disappearance

### ISSUE THREAD

**Issue by Egoogoo** [EarthMC/Issue-Tracker#360]
**Describe the issue**
The TheCreepster_21 's town made yesterday (11/Feb) called Gothenburg, and it seems to disappear today. It is only one chunk.

**Coordinates**
3230,-10800

**Screenshots**
![image](https://user-images.githubusercontent.com/47566646/52644105-d15c9a80-2f10-11e9-9d5c-033be36427d9.png)

**Comment by KarlOfDuty** [comment]
You can open a support ticket for this instead, although I don't think we are refunding claims lost to the rollback.
