### ISSUE TITLE
[World] Servograd Claimed Chunks Lost

### ISSUE THREAD

**Issue by NikeSwoosh** [EarthMC/Issue-Tracker#361]
My small town (founded Feb 5) went from 13-14 chunks before the maintenance period to 8, which is a loss of 96G.

Town Coords
(14120, -13517)

![capture](https://user-images.githubusercontent.com/41091653/52656789-f4a12e80-2eab-11e9-8c61-9171727a8f63.PNG)
One chunk was claimed by me today.

**Comment by NigelFarage666** [comment]
WE GOT TICKETS FOR THIS

**Comment by BowShot118** [comment]
Mhm

**Comment by KarlOfDuty** [comment]
^^
