### ISSUE TITLE
Town Mayor /ranklist Command Not Working

### ISSUE THREAD

**Issue by SaucySalmon** [EarthMC/Issue-Tracker#363]
**Server**
EarthMC (non-classic)

**Describe the bug**
I am the new mayor of Lagos - my minecraft username is SaucySalmon. When I type in '/t ranklist' or '/town ranklist', to find out what roles I can give to Lagos residents, a message appears reading 'You don't have enough permissions for that command.'.
 Shouldn't a mayor be able to use this command and if I'm not supposed to use this command, how can I know what roles I can gives to my residents?
**To Reproduce**
1. Be the Mayor of Lagos
2.  type in '/t ranklist' or '/town ranklist'
3. observe the towny message 'You don't have enough permissions for that command.'

**Expected behavior**
I expected to see a list of the roles which I can give to my residents.

**Screenshots**

**Additional context**

**Comment by cat234** [comment]
Yes, it only works by puting in the wrong thing for /t set rank (resident) some text here

**Comment by SaucySalmon** [comment]
What does that mean? How do I see what ranks there are? Can someone just tell me what ranks I can give to my residents, please?

**Comment by TheLoneSperm** [comment]
Saucy, I believe its all listed on the EarthMC website. If it isn't right on the website, there's a link there that sends you to an in-depth page with all the towny commands.

**Comment by PoppyK** [comment]
https://i.gyazo.com/684398f2520fbb0423d1890101d53e16.png
those are the ranks you can add to your members.  

/town rank add/remove (user) (rank)

**Comment by SaucySalmon** [comment]
Thank you.
