### ISSUE TITLE
Mending broken.

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#364]
**Describe the bug**
XP orbs go straight to XP bar without repairing items with mending on it.

**To Reproduce**
Go to a blaze XP grinder or mine a block that drops XP and it won't repair your item or armor it'll just go straight to your XP bar.

**Expected behavior**
Repairs items, then once the item is full durability it goes to XP bar.

When is this being fixed? I haven't been able to go mining or get into major fights due to not being able to repair the items once I'm finished.

**Comment by johnyuki** [comment]
I think it is because XP orbs don't drop - not an issue with mending. XP orbs drop from smelting, so you can still repair your items if you smelt some stuff, and you can just spend a couple diamonds by repairing the item on an anvil.

**Comment by NeonKrby** [comment]
god sets take hella xp to repair so mending is the most viable option

**Comment by HaydenTownley** [comment]
^ this needs to get fixed!

**Comment by Kyoris** [comment]
yes

**Comment by MattD246** [comment]
Why not?

**Comment by HaydenTownley** [comment]
This is still busted...

**Comment by KarlOfDuty** [comment]
It should be fixed on server restart.
