### ISSUE TITLE
Allow tracking of entity position and movement by mods

### ISSUE THREAD

**Issue by Kyoris** [EarthMC/Issue-Tracker#365]
There has been times where I lost stuff because it was an entity (ex. armor stand getting shot from outside of claims and losing armor on said stand), and as of the most recent I lost all my stuff to a retarded newbie that somehow got me out of my claims and drowned me.

All or much of this could be reverted if mods had the ability to track entities, so that maybe said items/entities could be refunded with no chance of scams, or to figure out exactly what happened to said entity for clarification.

Supposedly this would be added upon the plugin that allows for mods to track what happened to blocks at a position, and it should be able to track players, items, and entities.

**Comment by SpookyScoops** [comment]
dont go afk, that simple

**Comment by Kyoris** [comment]
i mean it's not just about being afk, i've had times where an amor stand got shot from outside claims and was broken, though it was in claims (shouldn't happen), and a turtle i found randomly disappearing after transporting it a good distance

**Comment by cat234** [comment]
You could always turn on keepInventory

**Comment by KarlOfDuty** [comment]
It is on again.
