### ISSUE TITLE
[Feature] Real life stock market + Earthmc

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#366]
**Is your feature request related to a problem? Please describe.**
Have you ever felt like "oh boy I have a lot of gold" and not known how to handle it, well then I have the solution for you!

**Describe the solution you'd like**
What if we added a plugin linking earthmc economy to the real world! thats right... our world!

**Additional context**
Either we could use a pre-existing plugin such as (https://www.spigotmc.org/threads/%E2%9E%A1-stock-market-%E2%80%A2-buy-shares-%E2%80%A2-crypto-currencies-%E2%80%A2-real-life-values-paid.316002/) or create a new one that is linked with the real stock market. There could be Courtages that could go to the hosting country (dow jones purchases=USA, OMX SE = Sweden etc) to promote joining a country and making one. Additionally being in the country or allying could make courtage=lower and finally countries in africa and less rich countries could be linked with a bigger stock market.

**Comment by BowShot118** [comment]
> Have you ever felt like "oh boy I have a lot of gold" and not known how to handle it, well then I have the solution for you!
> 
I'll take it  if you don't want it

**Comment by NigelFarage666** [comment]
Wow Shiraz has lots of gold and isn't banned!

**Comment by Pengun78** [comment]
Wait so rephrase this

**Comment by johnyuki** [comment]
Anything to expand the economy plugin is fine with me! I think trading in-game currency against real-world stocks is a good idea.

**Comment by KarlOfDuty** [comment]
This would cause more issues than its worth.
