### ISSUE TITLE
[World] Central Asian Rivers [Syr Darya, Amu Darya, Zeravshan and Panj]

### ISSUE THREAD

**Issue by Koriandah** [EarthMC/Issue-Tracker#367]
Lack of Rivers in Central Asia
There are plenty of notable rivers in central asia that feed the many lakes from the mountains. Some were even used for large scale transportation, since they were essentially highways in the desert. The most important of those are the Syr Darya, Amu Darya, Zeravshan and Panj Rivers.

**Coordinates**
The rivers are located in a box from 10600 -8600 diagonally to 12600, -6800

![image](https://user-images.githubusercontent.com/47318364/52884433-1529fb00-31c2-11e9-8b6c-de76e7788540.png)
![image](https://user-images.githubusercontent.com/47318364/52884454-2410ad80-31c2-11e9-8d18-b63df5a112ea.png)

**Comment by shirazmatas** [comment]
If you want koriandah you could add cobblestone pillars to where the river goes and designers lives become much easier! We'll probably come by doing this when we have free time

**Comment by jumakituno** [comment]
https://youtu.be/OzVB_QXhpn8

**Comment by AndrewCheedle** [comment]
I dont think it will be done after 4 years. Sorry fam
