### ISSUE TITLE
[Feature] Adding nation zones

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/Issue-Tracker#368]
This would make it so only members of the same nation could claim within a certain distance of each other. This might lessen the impact of claim blocking a bit but still let towns in the same nation claim all the way up to each other. I'm thinking a nation zone of one or two plots around all towns.

**Comment by cat234** [comment]
Thank you!
Finally something close to a border!

**Comment by Pengun78** [comment]
I dont get it

**Comment by cat234** [comment]
Could you allow towns that make actual borders so we can actually see the borders of nations? I don't like seeing parts of Nazi Germany in France, although it may be accurate.

**Comment by cat234** [comment]
You could set roads as borders between provinces with 2 chunks in between.

**Comment by johnyuki** [comment]
How would this work in crowded areas though? Such as Europe?

**Comment by FutureCW** [comment]
So when areas on the map become as dense as Europe tf is going to happen?

**Comment by KarlOfDuty** [comment]
Indeed, that would be the issue with doing it. That is why the nation zone should be as small as possible.

**Comment by KarlOfDuty** [comment]
This will not be implemented as according to towny they cause way more lag than normal towny claims.
