### ISSUE TITLE
Nation max range is actually 2900, not 3000

### ISSUE THREAD

**Issue by FranchuFranchu** [EarthMC/Issue-Tracker#369]
So I started a town at the very edge of the 3000 radius of La_Plata, but when the chancellor tried to add me it said it was too far. I claimed south until i got to the 2900 radius and it worked

**Comment by Toadally** [comment]
Nation radius is circular

**Comment by KarlOfDuty** [comment]
The radius is chunk based, not block based so it is not exact and it varies depending on the angle.
