### ISSUE TITLE
PLEASE try out a different anti-xray. It's clear that the current one is a massive problem for lag when the server gets full. It makes playing on the weekend unbearable. 

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#370]
When Orebfuscator was disabled that one time for a couple hours, the server was completely lag-free, even when it had like 100 people on, so it's clear that this plugin is a massive problem. How about instead of sticking with a bad plugin that causes this much lag, try out a different one?

**Comment by 4noah18** [comment]
God knows why they haven't changed it yet

**Comment by KarlOfDuty** [comment]
The current one is not an issue when it comes to lag.

**Comment by johnyuki** [comment]
> 
> 
> The current one is not an issue when it comes to lag.

Wat? Then why was the server completely lag-free when it got disabled that one time?

**Comment by FutureCW** [comment]
Lmao the server was basically lag free when they disabled it and it’s being denied? What???

**Comment by BowShot118** [comment]
If Karl doesn't acknowledge it, it doesn't exist.
*Just like his dad <o/*
