### ISSUE TITLE
Disable players showing on the online map, or make it an adjustable option.

### ISSUE THREAD

**Issue by Thexus** [EarthMC/Issue-Tracker#371]
I've got sniped 3 times in the past 2 days while I was making roads to different cities. I get that when two players randomly meet in the complete wilderness, pvp should be an option, but a few wannabe autist assasins make building roads a pain in the ass. Another solution would be to disable pvp 2 chunks outside of the borders, because if you look at for example Gorod Drakona, you can get killed **inside** of the city.

**Comment by johnyuki** [comment]
Not a good idea. This kind of stuff will have happened in real life. 

I do however hate the live-updating map myself. I think it would be a good idea for the map to only update players' positions once every minute or so, as opposed to essentially having a livefeed of every player on the server that is overground and not invis potted.

**Comment by TheLoneSperm** [comment]
> This kind of stuff will have happened in real life. #
Uhhhh how?

**Comment by cat234** [comment]
> I've got sniped 3 times in the past 2 days while I was making roads to different cities. I get that when two players randomly meet in the complete wilderness, pvp should be an option, but a few wannabe autist assasins make building roads a pain in the ass. Another solution would be to disable pvp 2 chunks outside of the borders, because if you look at for example Gorod Drakona, you can get killed **inside** of the city.

**Comment by cat234** [comment]
Honestly I think it should be disabled all together, it should only be enabled in a warsone.

**Comment by Pengun78** [comment]
No its ebic

**Comment by KarlOfDuty** [comment]
We will not be disabling players on the dynmap at this time, if you want to be hidden you can go inside a building, use an invisibility potion or sneak.
