### ISSUE TITLE
[Feature] Add Swedish chat

### ISSUE THREAD

**Issue by NilsNyfiken** [EarthMC/Issue-Tracker#372]
**Is your feature request related to a problem? Please describe.**
This *used* to be a Swedish server, but now… There is even a spanish chat in game so where is the Swedish one?
**Describe the solution you'd like**
Add /swedish
**Additional context**
Fix your inner Swedish spirit

**Comment by cat234** [comment]
Deutsch bitte?

**Comment by KarlOfDuty** [comment]
We will not be adding any more chats at this time. And I personally don't see the need for a Swedish chat, we have always done well enough in the english one.
