### ISSUE TITLE
Towny-Farm plots

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#373]
I have a lot of community projects in my town and farm plots don't work the way they're supposed to.

Normal residents cannot harvest nor replant on the designated farm plot via /plot set farm.

To work around this, I've been doing 
/plot set perm res build on
/plot set perm res destroy on

Doubt this is of any urgency to be fixed but it'd be heckin' sick if you could get around to it. tyvm.

**Comment by KarlOfDuty** [comment]
This looks more likely to be a towny issue than a config issue.

**Comment by KarlOfDuty** [comment]
As far as I can see from the towny config you are supposed to have those options on and it should still restrict normal members from using other items than farm stuff.
