### ISSUE TITLE
Gold despawn

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#375]
**Server**
Earthmc

**Describe the bug**
Dropping gold randomly despawns immidiately noticed by many (even me)

**To Reproduce**
1. get gold
2. join laggy server
3. drop gold
4. ????
5. lose gold

**Expected behavior**
You lose gold sometimes

**Screenshots**
no not yet (havent recorded)

**Additional context**
its random

**Comment by cat234** [comment]
Oof, talk about loosing change!

**Comment by KarlOfDuty** [comment]
Is this still an issue? We have not had any reports on this since this one.

**Comment by johnyuki** [comment]
I've noticed this happening with Iron too, not just Gold. I thought I was losing my mind when it happens, but turns out I am not crazy after all.

**Comment by shirazmatas** [comment]
I noticed a way to avoid this. Using ctrl+q instead of dragging ensures that it doesn't despawn or get deleted.

**Comment by KarlOfDuty** [comment]
Hmm, I've seen this issue when dragging items from my inventory in creative mode too.

**Comment by KarlOfDuty** [comment]
Yeah hang on, this is a creative mode issue, shiraz pls.
