### ISSUE TITLE
Make rule 4.1 clearer

### ISSUE THREAD

**Issue by FranchuFranchu** [EarthMC/Issue-Tracker#376]
"Nation name must correspond with  map location of the  nation capital."
should be changed with
"Nation name must correspond with in-game map location of the in-game nation capital. "
An example should also be provided

**Comment by Nicoadelpino** [comment]
Agreeeee.

**Comment by Renarchat** [comment]
4.1 seems clear enough to me

**Comment by Nicoadelpino** [comment]
Not clear enough to me, @Ultil0l

**Comment by KarlOfDuty** [comment]
I don't see how this needs to be clarified, I don't think anyone is expecting us to go around renaming nations irl.
