### ISSUE TITLE
(worldissue)

### ISSUE THREAD

**Issue by ardy2001** [EarthMC/Issue-Tracker#377]
**Describe the issue**
A clear and concise description of what the issue is.
world edit 

**Coordinates** 
X Y Z coordinates. 

-18272 63 -4966

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how you want the terrain to look.

i'm wondering if you can make the Rio grande wider and the area around it all to be sandy and have turtles and have it sand hills that look natural

**Comment by PoppyK** [comment]
I just looked at the river.  This river was completed by Arganog back in Nov. 2018.  I know you had talked about widening them, but we really just make all rivers a standard size on the map. Turtle eggs can be acquired but buying them.  There is much sand around the river.  I realize that there aren't as many hills as you might like but you can terraform a little to make it work around your area.  There are more hills around the river but just further north.    https://gyazo.com/11f59c124ce5f4cff804b277732937b9 https://i.gyazo.com/3bbd0d670830e4818b2148fc8a1871dd.png
