### ISSUE TITLE
[Feature] Player Skulls

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#378]
Can we get a pluggin where when you kill a player their skull drops along with their stuff?

**Comment by AlexGamerYTT** [comment]
Didn't you know? This feature is already available but it is for donators only.

**Comment by WyWall** [comment]
that sounds dumb it should be if you kill a=someone you get their skull :p

**Comment by AlexGamerYTT** [comment]
It isn't dumb

**Comment by BowShot118** [comment]
Player skulls are like the only incentive for the top donor rank.

And they're purely cosmetic, so to keep the server you know, alive, I don't think this should be added

**Comment by KarlOfDuty** [comment]
As others have stated, player skulls are donator rewards.
