### ISSUE TITLE
[classic] Says "Invalid String" when trying to set board of your town

### ISSUE THREAD

**Issue by JakubdotPLGB** [EarthMC/Issue-Tracker#38]
When you try "/t set board" with a following message, it just says that the string is invalid. 
![image](https://user-images.githubusercontent.com/32275965/47580170-1cdd3f80-d946-11e8-8697-8dadd3b63c4c.png)

**Comment by KarlOfDuty** [comment]
I mean did you use an invalid string?

**Comment by JakubdotPLGB** [comment]
I wanted to set it to the Wikia link for Zakopane

**Comment by KarlOfDuty** [comment]
Likely has invalid symbols in it then.
