### ISSUE TITLE
Ticket# 4642 villager stacking refund

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#381]
**Is your feature request related to a problem? Please describe.**

Posted ticket 01/02/2019

4 Villagers went missing after stacking plugin update. 
The feather falling villager was found in the nether, it was not retrieved.

**Describe the solution you'd like**

Return the four librarian villagers.
Frost Walker II, Power V, projectile protection III
Mending (26), Unbreaking II, depth strider III
Looting II, channeling, Sweeping edge III 
Feather Falling II, Luck of Sea III, Looting II

Coords XYZ: 580 / 59 / -8285

**Additional context**

![](https://cdn.discordapp.com/attachments/541072321352302610/541078850482995201/unknown.png)

![](https://cdn.discordapp.com/attachments/541072321352302610/541115659057233930/unknown.png)

![](https://cdn.discordapp.com/attachments/541072321352302610/546192545760411657/unknown.png)
https://media.discordapp.net/attachments/541072321352302610/541115846106415104/unknown.png?width=1079&height=600

**Comment by PoppyK** [comment]
Cactus, take all this info and add it to a ticket on discord.  Type -new in #general chat.  It will generate a ticket for you and you can add all this info there.

**Comment by Cactusinapumpkin** [comment]
The Sharpness II, Flame, Smite is also missing but I removed the sign and replaced it with another villager.
@PoppyK ticket# 4642 I made a discord ticket 2 months ago

**Comment by PoppyK** [comment]
Ouch.  Most likely they will just spawn a few more villagers for you.  Ours stacked too and we had to begin again.  I'm sorry.  I hope your ticket gets answered soon!

**Comment by Cactusinapumpkin** [comment]
i got a mending 26 villager
