### ISSUE TITLE
Birch Gods

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#382]
**Server**
Which server the bug is on.
terranova
**Describe the bug**
Two heads, one a clown and the other a jigsaw floating
  
**To Reproduce**
I had just begun settling into nimes, I dont think I even had one chunk. 
I was walking outside of my claims and  toward the river, when I noticed something behind me. It scared the sh*t out of me. I am not sure if they showed on the map, they turned to each other as if they were whispering to each other and messaged me and said to run that this area isn't safe. Afterwards I began asking people what they knew about these people. I went to a couple people but I met cuddlefish at paris and he said they they visited him as well but did not say anything.

**Expected behavior**
More info for Birch Gods as eagle mentioned

**Screenshots**
![capture](https://user-images.githubusercontent.com/48000340/53397824-bc9af080-396d-11e9-9dc3-fa2e8fa00575.PNG)

**Additional context**

**Comment by cat234** [comment]
Wut

**Comment by Toadally** [comment]
...

**Comment by Pengun78** [comment]
Holy fuck lol

**Comment by CloakedEagle** [comment]
Yes, Holy Birch God!

**Comment by Cactusinapumpkin** [comment]
ask cuddlefish

**Comment by KarlOfDuty** [comment]
Wat

**Comment by KarlOfDuty** [comment]
I have no idea what is going on here.
