### ISSUE TITLE
Concrete powder wont become Concrete

### ISSUE THREAD

**Issue by HaydenTownley** [EarthMC/Issue-Tracker#384]
**Server**
Earthmc TN

**Describe the bug**
When attempting to make concrete powder into concrete it wont and will remain as concrete powder.

**To Reproduce**
1. Make concrete powder
2. place it
3. wait

**Expected behavior**
I get concrete not powder

**Comment by Kyoris** [comment]
um you need to pour water over it oof 
do some research before making a bug report idot

**Comment by HaydenTownley** [comment]
i did you dumbass

**Comment by Kyoris** [comment]
oh :thonk:

**Comment by PoppyK** [comment]
Concrete isn't working for me either.  ;-; This just happened after the reset today.  I've been making it all day.  When you pour water on it, it turns to concrete but when you pickaxe it, it goes back to powder.  Frustrating.

**Comment by PoppyK** [comment]
concrete seems to be fixed today! yay :)

**Comment by NilsNyfiken** [comment]
nope

**Comment by NilsNyfiken** [comment]
it isn't working for me

**Comment by PoppyK** [comment]
It was working for me and then we had another restart.  I think Fix disabled water and lava flow for better server performance.

**Comment by Cactusinapumpkin** [comment]
Im building a very large concrete building in the middle of france called citadel, 

![image](https://user-images.githubusercontent.com/48000340/53657201-1542e580-3c1b-11e9-8bee-fdfd61c07743.png)

**Comment by KarlOfDuty** [comment]
I think this should be part of the new resource management system, not 100% sure though. It should only activate when the server is particularly laggy, usually when it is full.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/53703181-7a8e0680-3dd4-11e9-925e-512026d6cded.png)

almost done just keep me updated when it comes back

**Comment by Cactusinapumpkin** [comment]
Its working now

**Comment by NilsNyfiken** [comment]
This getting frustrating... pls fix this soon

**Comment by KarlOfDuty** [comment]
This should be fixed.
