### ISSUE TITLE
[BUG] Hoppers broken.

### ISSUE THREAD

**Issue by vali8203** [EarthMC/Issue-Tracker#385]
**Server**
Earthmc.net

**Describe the bug**
Hoppers will randomly turn into stone blocks.

**To Reproduce**
1. Build a contraption with many hoppers.
2.Operate hoppers with redstone while staying near.

**Expected behavior**
Hoppers should function normally, but in this case, will sometimes randomly turn into stone blocks, leaving their contents to fall out onto the floor. Hoppers should not turn into stone blocks. Hoppers should stay in their hopper forms and continue to hopper.

**Screenshots**
[https://imgur.com/a/4CnL6mL](https://imgur.com/a/4CnL6mL)

**Comment by KarlOfDuty** [comment]
It is part of the new anti lag-machine system. Systems like auto brewing and auto sorting and similar size redstone/hopper systems are some of the things that use the most server resources at the moment. We will keep configuring this system over the next few weeks so it may change.

**Comment by KarlOfDuty** [comment]
Should be fixed.
