### ISSUE TITLE
[BUG] Stack of 30 cows turned into singular cow when I attempted to breed.

### ISSUE THREAD

**Issue by nicksangeorge** [EarthMC/Issue-Tracker#386]
**Server**
Which server the bug is on.
EarthMC

**Describe the bug**
When I attempted to breed the stacked 30 cows I had in my farm, their "30 cows" nametag disappeared and now they function as one. A mega cow if you will.

https://media.discordapp.net/attachments/550499588486725662/550499771195064330/unknown.png?width=832&height=468

**Comment by PoppyK** [comment]
Any interaction with stacked mobs rn negates their numbers.  I tried breeding and my stack disappeared to one mob.  I tried killing my stack of 83 cows, (normally you kill one at a time so it can take time for a stack to die) and the "stack" was killed instantly with a drop of one piece of leather.  ;-;

**Comment by Kyoris** [comment]
same, i sheared my 4x sheep and _boom_, it's a normal sheep now

**Comment by zachkoa** [comment]
I also killed my 99x stack of chicken in hopes to have one dead and the rest alive. i now have no chickens

**Comment by KarlOfDuty** [comment]
Closed as stacking plugin has been removed.
