### ISSUE TITLE
world

### ISSUE THREAD

**Issue by ardy2001** [EarthMC/Issue-Tracker#387]
A clear and concise description of what the issue is.
world edit

**Coordinates**
X Y Z coordinates.

-18272 63 -4966

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how you want the terrain to look.

i'm wondering if you can make the Rio grande wider and the area around it all to be sandy and have turtles and have it sand hills that look natural

**Comment by KarlOfDuty** [comment]
From what I can see the river is already widened.
