### ISSUE TITLE
Spawners are glitched

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#388]
Basically Blazes stop falling when they spawn in spawners, they're completely stuck. I tried toggling mob spawns and then re-enabling but now they don't spawn at all.

Seeing as hoppers and mine carts are all glitching out, I guess spawners are the next phase.

**Comment by BowShot118** [comment]
I blame Anti X-Ray and the fact that Double smelt for gold is disabled.

No meme

**Comment by Pengun78** [comment]
How so

**Comment by KarlOfDuty** [comment]
The blazes don't move as we have turned off the AI of mobs created from spawners. Spawners may be turned off while the server is lagging severely by the new resource handler. We will be configuring the resource handler over the next few weeks to see what does and does not impact lag.
