### ISSUE TITLE
[BUG] Donator head skin

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#389]
**Server**
Which server the bug is on.
terranova
**Describe the bug**
Donator head skin doesnt change when skin is changed.
**To Reproduce**
change skin, look at donator head

**Expected behavior**
donator head skin changes when you change your skin

**Screenshots**
![image](https://user-images.githubusercontent.com/48000340/53622125-6b357000-3bbe-11e9-81ea-5e8181a3bd87.png)

**Additional context**

**Comment by KarlOfDuty** [comment]
Do they usually update? I don't think we have changed anything about that.
