### ISSUE TITLE
[BUG] Item Frames not seen when placed. 

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#390]
I can't see placed item frames.  Each time I try to place, it takes one item frame from my inventory but I can't see it on the wall

I just noticed this bug this morning 3/1

**Comment by KarlOfDuty** [comment]
There is a limit on item frames per chunk now. Didn't know they were no refunds on them.

**Comment by AlexGamerYTT** [comment]
Happened to me too Poppy. I want a leather refund!
