### ISSUE TITLE
Lowering The Player Limit

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#391]
The server is ever so slowing dying, there's heavily lag at most busy times of day. This means that certain features have to be debuffed, or even removed.

I'm gonna be controversal and say that maybe, just maybe, to make the server actually playable, the player count limit thing should be lowered.

Save the death threats for my /mail ingame - Hf

**Comment by cat234** [comment]
I'm ***not*** gonna kill you.

But yes, this is crucial to mining and productivity. With lag, people cannot trade as easily because it's so slow.

**Comment by Kyoris** [comment]
honestly though, it would be annoying in some sense but good the other. What we really need a a balance between allowing players to log in and the amount of lag present.

**Comment by Sabatarge** [comment]
Why is there so much lag for a 140 player server?If it's the anti-xray plugin i'd rather have them allow us to transfer our gold to a digital currency then eventually have digital currency only so we can remove it

**Comment by ZestyPhallus** [comment]
Hey dipshit, you can type /pay [ign] [amount] whenever the gold's in your inv/enderchest/safe. We all just prefer to drop gold for some reason.

**Comment by BowShot118** [comment]
> Hey dipshit, you can type /pay [ign] [amount] whenever the gold's in your inv/enderchest/safe. We all just prefer to drop gold for some reason.

1. Don't be rude!

2. It isn't foolproof

**Comment by Sabatarge** [comment]
It's not just that, he completely missed the point. Doing /pay doesn't help us remove the xray plugin. Switching to an all digital currency with a different means of acquiring it does allow us to

**Comment by ZestyPhallus** [comment]
You're misunderstood; it isn't that I've missed the point. It's that you, Saba, obviously have no idea what you're talking about and you're wasting the admins time.
I'd like to speak on behalf of them and call you an idiot. 
It isn't the anti-xray. Trust the admins who handle this plugin. If it really is the main issue and somehow you know more than the admins, why would they be limiting _**everything**_ else other than the anti-xray?

You speak about digital currency-- /pay is a form of that. 
No pissing contest here, if you wanted to go out for a beer I'd be down. Cheers.

**Comment by KarlOfDuty** [comment]
I mean the anti-xray thing is just a meme like how people were telling others to stop claiming last year several months after the claim lag was fixed. It's understandable that the newer players don't catch on to that though.

**Comment by BowShot118** [comment]
> I mean the anti-xray thing is just a meme like how people were telling others to stop claiming last year several months after the claim lag was fixed. It's understandable that the newer players don't catch on to that though.

I understand the Anti X-Ray meme, and I wasn't on when it was off temp, but multiple players **_did say_** that the lag reduced dramatically.

**Comment by KarlOfDuty** [comment]
I mean we don't even have that anymore.

**Comment by BowShot118** [comment]
So what is causing the lag lol

**Comment by KarlOfDuty** [comment]
Not entirely clear at the moment. Mostly normal server stuff like redstone, entities and such. But we also have some nasty lag spikes that I haven't found the cause of yet.

**Comment by BowShot118** [comment]
Good to know
![synokay](https://user-images.githubusercontent.com/44571571/53686825-58d54680-3d24-11e9-958c-de047f3e205e.jpg)

**Comment by AlexGamerYTT** [comment]
Hmmm, I think it would be a good idea to lower the limit at 130 players but split the server in two synced servers of 130, then.

**Comment by 2018kTwok** [comment]
The player count is not the issue of the server lag. The main thing that causes it is the anti xray it detects stone a lot of the time. Your wrong about the server dying slowly I see the max limit and five over at many times on the weeks and weekends. People also have a life and dont want to just play this game. Also their is not a clear lag plugin with everyone droping items. Yes a virtual currency could work to but even then it takes away the concept of having gold its it's different hope this helps.

**Comment by 2018kTwok** [comment]
Also it may not even be the anti xray it could be something else 1.13 has already been seen to cause heavy performance issues 1.14 is to be said to fix a lot of this.

**Comment by BowShot118** [comment]
> The player count is not the issue of the server lag. The main thing that causes it is the anti xray it detects stone a lot of the time. Your wrong about the server dying slowly I see the max limit and five over at many times on the weeks and weekends. People also have a life and dont want to just play this game. Also their is not a clear lag plugin with everyone droping items. Yes a virtual currency could work to but even then it takes away the concept of having gold its it's different hope this helps.

If the player count isn't a factor in lag, then please explain to me how when the server's down at around 90 plays it runs smooth af?

**Comment by 2018kTwok** [comment]
Depends on the time and day. Yes, there is still lag if you have not noticed I've seen it at 80+ sometimes even 60. Also when we are at a high player count we tend not to restart the server which can also cause lag.

**Comment by 2018kTwok** [comment]
Also, how is lowering the player limit a good idea to you? It causes outrage for one we have a larger community and not everyone wants to buy a rank think my guy.

**Comment by BowShot118** [comment]
> Also, how is lowering the player limit a good idea to you? It causes outrage for one we have a larger community and not everyone wants to buy a rank think my guy.

Mate, I'm anti P2W but this is practically necessary lmfao. The Player base has to adapt. The lag when the server is full is unbearable, nowhere near the levels you claim it is at at 60 players, which, for the record, the lowest I've ever seen is 50 and that was during British Schooling hours. I highly doubt you commonly play with 60 players, especially if you're active at this time of day.

**Comment by 2018kTwok** [comment]
I have. Also if you don't like the lag then donate to fix the server it costs money to upgrade the server hardware plus its 1.13 server performance itself. It is not necessary you can play it just takes longer to mine things and do things. Don't like it then leave it won't get better with complaining.

**Comment by 2018kTwok** [comment]
I don't commonly but I do at times.

**Comment by BowShot118** [comment]
> I have. Also if you don't like the lag then donate to fix the server it costs money to upgrade the server hardware plus its 1.13 server performance itself. It is not necessary you can play it just takes longer to mine things and do things. Don't like it then leave it won't get better with complaining.

I'm a top tier donator btw, I've donated 50 USD to the server.

**Comment by 2018kTwok** [comment]
Okay. Then you should know that this lag is here to stay for a while it used to be lower but the community is not going to adapt easily to anything as we all know just get used to it :/

**Comment by 2018kTwok** [comment]
I still feel with ya it does seem unplayable at times it just is something I got used to it lets just hope it gets fixed soon enough.

**Comment by BowShot118** [comment]
> Okay. Then you should know that this lag is here to stay for a while it used to be lower but the community is not going to adapt easily to anything as we all know just get used to it :/

1. Who *actually* are you?

2. You've missed my point completely. Just because I've donated to the server doesn't mean I **have** to put up with the lag. I believe this is a good idea, alongside an implementation of a queue to give everyone a chance to play. 
![lots of facepalm](https://user-images.githubusercontent.com/44571571/53750543-f3a75f80-3ea1-11e9-9e9d-072d145d72a1.jpg)

**Comment by 2018kTwok** [comment]
You know we used to have it lower right?

**Comment by BowShot118** [comment]
Yes.

**Comment by 2018kTwok** [comment]
How many people do you think would want this after all they would have to wait on hours sometimes to even play let's say someone bots the queue?

**Comment by 2018kTwok** [comment]
I see your point it has perks and downsides I just don't see a  good enough reason to lower the player count beside the lag.

**Comment by BowShot118** [comment]
Quite a few, if you actually care you'd play on the server, and I don't see more then 10-15 people trying to get on during peak hours, when the server's lag. That isn't a lot and wont require a large queue system. 
Alongside this, the server isn't much good when you can't mine, trade or build and all you have to do is get banned by mods for asking for a restart because you pinged them too much.

**Comment by 2018kTwok** [comment]
Not every mod can restart the server only three i believe can syn karl and fix

**Comment by 2018kTwok** [comment]
You can mine just takes longer u can trade just wait you can build maybe not a lot

**Comment by BowShot118** [comment]
Lol do you actually play during peak hours?

**Comment by 2018kTwok** [comment]
Yes and i know the struggle

**Comment by BowShot118** [comment]
Then why the hell do you support the backbreaking lag?

**Comment by 2018kTwok** [comment]
back breaking you mean mining that lags?

**Comment by BowShot118** [comment]
You can't do anything productive without waiting 10s to break 1 block. Sorry but with the rarity of gold, ain't no one getting anything done. You've smoked something.

**Comment by KarlOfDuty** [comment]
Is the lag still severe enough that this issue is relevant?

**Comment by KarlOfDuty** [comment]
Will be done soon.
