### ISSUE TITLE
Account banned Because it was hacked Now I have the account back Can I get it unbanned

### ISSUE THREAD

**Issue by LilPeachyKeen** [EarthMC/Issue-Tracker#392]
Hey , My name is Keith my mc account got hacked the other day I just reset it through mojang and was able to log in today I see my account is banned on the earth mc server witch is nice because I didn't want them destroying our town, Any way My account is LilPeachyKeen I was wondering if it was able to be unbanned so I could get on the earth Mc server and play?

**Comment by AlexGamerYTT** [comment]
You should send a ticket, lmao.

**Comment by LilPeachyKeen** [comment]
im good now thanks
