### ISSUE TITLE
[Suggestion] Allow us to repair items for no xp cost if the item has mending on it

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#393]
It would still cost the diamonds to repair the tool, but it wouldn't cost any xp if the item has mending on it. This is because due to the extreme lag that happens, and more recently, the inability to farm blazes because they don't fall, it is incredibly hard to get enough xp to mend items. I just tried mending my shovel at an anvil, but I couldn't because "that's too expensive". Taking away the experience cost for repairing tools on an anvil would negate this.

**Comment by BowShot118** [comment]
YES

**Comment by KarlOfDuty** [comment]
Mending should be fixed now. Also what lag would that be?
