### ISSUE TITLE
Make In-game perm mutes happen!

### ISSUE THREAD

**Issue by laidang08** [EarthMC/Issue-Tracker#394]
Sorry if this is kind of an angry issue, but for the people who say the n-word a little too much they should get a perm mute and not a perm ban. It isn't fair to prohibit them from playing the server (especially if they're active) just because they broke a language rule. Now, if the person was cheating then of course they get perm banned because that affects their gameplay in a good/cheating way.

**Comment by CrookedToe** [comment]
I think purposely breaking the rules repeatedly after warnings should result in a perm ban. Not to mention Minecraft is a kid's game and people dropping the hard r is not the best thing for servers that want a player base.

**Comment by BowShot118** [comment]
Yeah but, a prevention method is that 5 warns are a perm ban.

**Comment by laidang08** [comment]
> I think purposely breaking the rules repeatedly after warnings should result in a perm ban. Not to mention Minecraft is a kid's game and people dropping the hard r is not the best thing for servers that want a player base.

But why prevent them from playing the game and not a perm mute? And don't start with this "kid's game" bullshit. People are cussing 24/7 on EMC.

**Comment by laidang08** [comment]
> Yeah but, a prevention method is that 5 warns are a perm ban.

How are you supposed to know how many warnings you have?

**Comment by laidang08** [comment]
Also why don't they have a plugin where it deletes the message of someone saying a curse word especially the N-word. Kind of like Mineplex has. It would make their job way easier and people will be less angry.

**Comment by BowShot118** [comment]
That's the point lol.

You shouldn't be saying the word in the first place, so why help the offender by telling them how many times you can do it? Lmfao

**Comment by 2018kTwok** [comment]
They know the rules do /warnings or /history to see your warnings. They dont have a plugin to censor it because its more ussage on the server we offer people to say most things. The rules are stated clearly been warned or muted why do it again?

**Comment by KarlOfDuty** [comment]
Indeed, as others have said the warnings are there for a reason. If you keep breaking the rules we do not want you on our server.
