### ISSUE TITLE
[Feature] Add Tridents by Crafting

### ISSUE THREAD

**Issue by TheLoneSperm** [EarthMC/Issue-Tracker#396]
Seeing as EMC is played on 1.13, I think there are a number of vanilla features missing. Of these, I think the most important are tridents. 

**Reasons:**
1. It is a feature that already exists in vanilla Minecraft, so it wouldn't be difficult for the developers to add it.
2. I've seen a lot of people ask for new methods of transportation since it can be quite tedious. A trident with a riptide enchantment would be very nice as a method of crossing our oceans.
3. The trident would make pvp more interesting as it can be used in both ranged and melee combat. 
4. The developers try to only add features that make sense with the server's geopolitical towny theme and since the trident was a real weapon that was used in the past, I think it'd be worth adding.

**Solution:**
Because tridents are obtained from drowned, and we have so many problems with lag. I think it'd be best if tridents were added via a crafting recipe. I propose making it more on the expensive side because of how versatile they are. The recipe I propose would be just like the pickaxe recipe but with emeralds as the pick and diamonds (in place of sticks) as the handle.

**Comment by KarlOfDuty** [comment]
Do you believe that would be a fair recipe to how rare they would be in the vanilla game?

**Comment by TheLoneSperm** [comment]
@KarlOfDuty I'm not entirely certain but if you think it isn't fair, there are a number of ways you could make it harder to acquire. 
1. Change the recipe from singular ores to blocks of that ore.
2. Change the recipe to include gold or a gold block.
3. A combination of both mentioned above.

**Comment by ZestyPhallus** [comment]
they already have this implemented.
You just need 5 wood planks in a 'u' shape.

**Comment by BowShot118** [comment]
That's a boat...

**Comment by 2018kTwok** [comment]
Tridents are in the game its been stated before they exist and are rare if you look hard enough you can find some drowned still in the world just look. That crafting recipe is so easy to do emeralds and diamonds and any other ore is easy to find even gold is to. This made no point in this crafting recipe.

**Comment by watergod1234** [comment]
This seems like a good and sufficiently expensive recipe to craft a trident: 
<img width="519" alt="screen shot 2019-03-05 at 9 29 42 pm" src="https://user-images.githubusercontent.com/29761502/53858205-229aff80-3f8e-11e9-920e-de1854184e2c.png">

**Comment by WyWall** [comment]
they are difficult to get but obtainable. i have some myself

**Comment by TheLoneSperm** [comment]
> they are difficult to get but obtainable. i have some myself

How long did you have to search before obtaining one?

**Comment by TheLoneSperm** [comment]
> I think the trident should still be extremely valuable and rare, so this seems like a good and sufficiently expensive recipe:
> <img alt="screen shot 2019-03-05 at 9 29 42 pm" width="519" src="https://user-images.githubusercontent.com/29761502/53858205-229aff80-3f8e-11e9-920e-de1854184e2c.png">

I had forgotten about nether stars. That's a pretty good recipe suggestion although considering how you'd have to kill 3 withers to make one trident, I'd suggest something other than stars for the top corners and only leaving the top middle.

**Comment by WyWall** [comment]
i mean its on average 1 trident every 7 hours of farming

**Comment by WhitPlayzYT** [comment]
Not when mob spawning is off @WyWall

**Comment by KarlOfDuty** [comment]
Whenever we bring over the voting system from the factions server it will be used for tridents.
