### ISSUE TITLE
Refund pls

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#397]
Halp we bombed two dumbass towns that had beacons on plots with explosions enabled but when we finally destroyed the beacon, it didn’t drop. **_Twice_** this happened.

We worked hard for that. We demand refund or donator rank. Our methods were **_genius_**.

**Comment by ZestyPhallus** [comment]
Or bacon

**Comment by alekb1** [comment]
Griefing much

**Comment by 2018kTwok** [comment]
First thats counted as grief and you will be warned for this once you post the cords so staff can rollback everything and the damage caused. You wont get a refund nor a rank even if it was not claimed we don't offer that and will never. I highly recommend openkng a ticket on the discord and reporting the cords and saying what happend

**Comment by AlexGamerYTT** [comment]
It's grief you stupid

**Comment by ZestyPhallus** [comment]
Retard alert, retard alert! Allow me to educate you clowns. @alekb1 @2018kTwok @AlexGamerYTT  
Rule#3 Griefing specifically reads “grief **around** claims” and as this was well within town, the only way this **MAY** be counted as grief is TNT craters. But rule 3.4 Stealing specific blocks suggests stealing specific blocks for their value isn’t considered as grief.

I did my best to spare the town from craters but due to their volatile nature, mistakes were made. We only targetted the iron blocks and the beacon and to do that some things had to go.

So if I’m to be warned, rules must be redefined stating “if you’re a dumbfuck and enabled explosions on your town, you are immune to any damage and we will rollback your shit.”

Plus, it was very fun. If I am warned, it was worth the chance. Loot was shit tho.

**Comment by ZestyPhallus** [comment]
Pls gimme baecon

**Comment by Cactusinapumpkin** [comment]
Beacon Nazi says no beacon for you

**Comment by KarlOfDuty** [comment]
Explosions only have a small chance of dropping blocks.
