### ISSUE TITLE
Spanish chat -> iberian chat; add Slavic chat, Scandinavian chat, turkish chat

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#398]
**Is your feature request related to a problem? Please describe.**
Some people are frustrated they can't type in their language in global chat so maybe add new chats for people to join and send their huehues and xaxaxa.

**Describe the solution you'd like**
**Opt-in** chats for Iberian language, scandinavian languages (not an issue), slavic languages, turkish language.

**Additional context**

![bild](https://user-images.githubusercontent.com/44276325/53760602-ac31cb00-3ec3-11e9-8c35-f3e76588b574.png)

**Comment by KarlOfDuty** [comment]
We are not adding new chats at the moment.
