### ISSUE TITLE
[World] Swedish Lakes

### ISSUE THREAD

**Issue by NilsNyfiken** [EarthMC/Issue-Tracker#401]
**Describe the issue**
The biggest lake in Sweden, Vänern, looks very compressed, especially height-wise

**Coordinates**

2281 / 65 / -11055

**Screenshots**
Compare EMC Map vs Real Map

**Comment by Kyoris** [comment]
Since it is up north it would be stretched east-west, thanks to the map projection. The fact that it is thinner north-south is also of the same cause.

**Comment by NilsNyfiken** [comment]
Well even without the stretch the proportions are wrong

**Comment by KarlOfDuty** [comment]
This is what it is supposed to look like in this projection.
