### ISSUE TITLE
[Suggestion] Disable Arcane forging so we could repair our tools since blazes are braindead and we could actually use the repair skill

### ISSUE THREAD

**Issue by Yazzed1** [EarthMC/Issue-Tracker#403]

**Comment by Yazzed1** [comment]
At least just do it for now until you guys find a solution to the blazes problem

**Comment by Kyoris** [comment]
I mean maybe have all ores and smelting drop more exp? I get much of my mending from quartz...

**Comment by Yazzed1** [comment]
And if you think 50 levels in repair is too low for people to start repairing diamonds tools make it higher, anyway just please give us something to fix our tools

**Comment by KarlOfDuty** [comment]
Mending should be fixed as far as I know.
