### ISSUE TITLE
Restart Server

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#404]
I doubt I'm the first to think of this, but here it goes.

Mods constantly get pinged from players regarding restarting server and they eventually get fed up :hyperping: so they mute players. That's besides the issue.

What if when a mod wakes up from a cold sweat and stumbles into the nightmare of EMC literally ablaze due to intense lag, if they can queue up a prompt/petition/tally or whatever--similar to the 0/10 players need to sleep to change day function-- where players can type /endme or /pls to reach a consensus on restarting server. If more than half the players fancy a restart, then the server restarts.

Mods and only mods can run this prompt.
It'd be accessed through discord too!
 
**"!mc snap?"
"/pls" or "/nu"**

ez pz gg wp

I know jack shit about how the server functions so this might be easier said than done, but I imagine this might allow the server to be semi-autonomous. 

Either way, ty for reading.

**Comment by KarlOfDuty** [comment]
Anyway, we can't do an auto restart because if the server restarts on its own it will just die by everyone joining at the same time when it starts back up.
