### ISSUE TITLE
New comfortable, useful and compact nation/town panel

### ISSUE THREAD

**Issue by 3meraldK** [EarthMC/Issue-Tracker#406]
If you are a Mayor, on command /town or /t a GUI will appear (chest with 3-6 rows). You can do here every thing what do you want without typing any complicated commands. Its the same for /nation or /n if you are a founder or king of some nation. Please DM me for more infos and i recommend dp this in Skript lloll

**Comment by ZestyPhallus** [comment]
Delet this

**Comment by Ultil0l** [comment]
its harder to script than it seems

**Comment by ZestyPhallus** [comment]
> its harder to script than it seems

your mom

**Comment by Kyoris** [comment]
Can you like nyet blyat.

**Comment by 3meraldK2** [comment]
> its harder to script than it seems

its just using skript but if you are not make a simple plugin to do that

**Comment by shirazmatas** [comment]
This would probably fit better in Towny's official github than for earthmc.

**Comment by KarlOfDuty** [comment]
As stated by shiraz, put this on the towny repo not this ours.
