### ISSUE TITLE
Connection to the server

### ISSUE THREAD

**Issue by JohnnysonCZ** [EarthMC/Issue-Tracker#407]
I cant connect to the server
![Minecraft 1 12 2 08 03 2019 21_23_27](https://user-images.githubusercontent.com/48366915/54054724-37c09a00-41eb-11e9-8d25-d91b7a61a69a.png)

**Comment by merp59** [comment]
I know this doesn't help, but I'm having the exact same problem.

**Comment by TheLoneSperm** [comment]
Was that while the server was being moved or close to when the server was moved? No one could connect while they moved it, and afterwards, only donators could.
