### ISSUE TITLE
[BUG] Can not create new shop signs. 

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#408]
The day we opened after moving hosts I tried to make a new shop sign.  You do get the GUI to make the sign and set the trade.  No interaction with the shop sign is possible after the initial set up.  You can click the sign but no sell GUI shows.

**Comment by PoppyK** [comment]
3/10 update Now all shops signs appear to be broken.

**Comment by BowShot118** [comment]
That's because they were disabled....

**Comment by KarlOfDuty** [comment]
This was a different issue from the current one and has been solved since.
