### ISSUE TITLE
Crafting recipe for Coral Blocks. 

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#410]
Title basically says it. 

the recipe could be 4 of the coresponding coral plants to make the coral block

**Comment by Magenent** [comment]
they are already adding coral blocks to the map there is no point plus you can't make blocks from plants lol

**Comment by watergod1234** [comment]
Yeah that’s the point magenent. There’s no crafting recipe so he’s suggesting they add one.

**Comment by KarlOfDuty** [comment]
Done.
