### ISSUE TITLE
[World] guidiana river

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#412]
**Describe the issue**
the guadiana is entirely wrong in emc, ive made an image to show it
![river](https://user-images.githubusercontent.com/44297328/54218186-5fff1000-44ed-11e9-9902-8928a91f0c0b.png)
the blue line is the river currently in emc
the red line is how its supposed to be
ive found this out by putting the irl border of portugal on iberia as some parts of the river are actually the borders of portugal and spain

**Comment by shirazmatas** [comment]
Hold up, isnt there one river that then branches off into 2?

**Comment by PoppyK** [comment]
https://i.gyazo.com/86806b470611fe09c669a960039a306b.png
this is what I used to map that river and went by the natural terrain there.
