### ISSUE TITLE
[BUG] Classic Kicks you for spamming

### ISSUE THREAD

**Issue by NilsNyfiken** [EarthMC/Issue-Tracker#413]
**Server**
Classic

**Describe the bug**
You get kicked for talking, especially when performing commands

**To Reproduce**
1. Type something in chat
2. Type a command
3. Get kicked

**Expected behavior**
Command works

**Comment by BowShot118** [comment]
play on 1.12.2, it is a 1.12.2 server. It hates 1.13.2
