### ISSUE TITLE
When tf will the server be accessible by non donors

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#414]
Like srsly. I cant join. I havent been able to join for ages now.  I dont have money to buy donor

**Comment by PoppyK** [comment]
Read announcements, Ian.  This isn't forever....Fix and Karl are working on fixing the problem so all can join again.  Sorry, it's such a bummer but hopefully, all is resolved soon.

**Comment by BowShot118** [comment]
Epic
