### ISSUE TITLE
Server has been disconnecting several people, due to a time out. 

### ISSUE THREAD

**Issue by DarkRush449** [EarthMC/Issue-Tracker#415]
**Server**
Server has been disconnecting several users when they try to join the server,. 

**Describe the bug**
When joining the server the player will connect successfully, however they will be stuck on a "generating terrain" screen until they get either get a "Timed Out" message, or "Remote host has closed." This issue seems to be server side and not client, as the problem only happens on all three of the EarthMC servers.  Logging on a different device also doesn't seem to fix any issues, so there must be a issue with the server connecting to players. Its not an old issue(at least for me) as I have been playing on the server since October with no issues until now.  Issue doesn't seem temporary. as I haven't been able to join for over 5 hours.  

![Screenshot_6](https://user-images.githubusercontent.com/47044217/54249055-6baa0100-4504-11e9-9d95-d48a0ed008b8.png)

**To Reproduce**
Not sure how this issue started in the first place...

**Expected behavior**
1. Connect to any of the three EarthMc servers.
2. Player connects.
3. Player is stuck on generating terrain screen
4. Player gets a error message, and is disconnected.

**Screenshots**
This is a screenshot from another player with the issue, Ryzenix ツ:

![Screenshot_6](https://user-images.githubusercontent.com/47044217/54249055-6baa0100-4504-11e9-9d95-d48a0ed008b8.png) 

-DarkRush449

**Comment by KarlOfDuty** [comment]
It is most likely DNS issues which we can do nothing about and you'll have to try to solve on your own.
