### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by NilsNyfiken** [EarthMC/Issue-Tracker#416]
**Is your feature request related to a problem? Please describe.**
The hub is booring

**Describe the solution you'd like**
Add a pvp arena, etc, so that people have something to do

**Comment by Toadally** [comment]
Change the title. Other than that, I think a pvp arena might be cool in the queue hub, but it would definitely be low priority at the moment.

**Comment by Kyoris** [comment]
Could use a large scale parkour/multiple parkours, as the current one with iron bars are a pain to use with multiple players trying at once. It could be a quick renovation

**Comment by NilsNyfiken** [comment]
Oh lol I didn’t even notice that I never added a proper title

**Comment by KarlOfDuty** [comment]
Done.
