### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by eon-fusion** [EarthMC/Issue-Tracker#417]
I was banned from the server for "client hacking" yet i have no client and recently fought someone in pvp through heavy lag and yet now im being accused of hacking. I have over 50 people that can back me up that i do not hack from various nations as i have partaken in pvp mutiple times before.  I would appreciate a swift response as i have donated.

**Comment by RangerMK01** [comment]
Wrong place my dude. Go to the EMC Ban Appeal Discord and talk to them about it there.

**Comment by BowShot118** [comment]
Epic
