### ISSUE TITLE
[BUG?] Kicked when joining server with queue

### ISSUE THREAD

**Issue by Asteroid1** [EarthMC/Issue-Tracker#418]
I was joining the server after waiting in the queue (obviously, for a pretty long time) and it kicked me out while I was entering.
![2019-03-15_17 17 41](https://user-images.githubusercontent.com/35580783/54468302-58877300-4748-11e9-8252-6a2b099e41ad.png)
As you can see in the attached image, it started to send me to the towny world when it kicked me backed to the hub server saying "Server is full!".

After that, I was still in the hub world and I no longer received queue update messages after waiting for a few minutes, so I had to relog and restart the whole queue over again....

**Comment by KarlOfDuty** [comment]
Should be fixed.
