### ISSUE TITLE
Increase player cap for towns

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#419]
As the server is growing and more players pour in, I think the player cap of 50 is way too small on towns, especially for big capitals of major nations. Many new players wish to join these big cities and a cap of 50 is just way too small.

Therefor I think it should either be completely disabled or increased to 100 or above

**Comment by Aitonater** [comment]
There is not a single town on the server with more than 20 active players, many large cities and towns have full residents lists to give them access to the max number of claims but suggesting that there is a single town with 50 active players is just wrong. The vast majority of towns have large resident lists and the reality is only a handful of residents play and the vast majority joined the server once and the town subsequently and never played again. Just kick inactive  residents from your town. The server's population is 140-300 consistent players maybe and there are 167 pages of towns when you do /t list. There is no mandate or need for towns to have a bigger player cap. If there were 50 active residents in a town it would count for the majority of players on the server which is not the case in any city.

**Comment by Aitonater** [comment]
If there were cities with 50 active players we would have 2 big cities (50/50) and 1 more with 40/50 players increasing the cap isn't viable when the server cap is 140.

**Comment by Aitonater** [comment]
at the moment of the 1,670 towns that exist on the server there are only 3 at maximum capacity

**Comment by KarlOfDuty** [comment]
As mentioned above, I highly doubt anyone would be able to get more than 50 active players in a single town. This would just invite more abuse with alt towns that just have a bunch of alt accounts giving the town voting gold and higher claim amount.
