### ISSUE TITLE
Uluru

### ISSUE THREAD

**Issue by Coffeetom** [EarthMC/Issue-Tracker#42]
Can uluru (the big red Rock in Australia) be added to the map.
It was apart of the old map, and had some story to it. So it would be great to see it added to the new map
Thanks

**Comment by sharkfynn1012** [comment]
Yes, it would be nice to see an Uluru that is not griefed such as the old one was.

**Comment by shirazmatas** [comment]
Uluru constructed, further adjustments can be directed to @PoppyK , Anti grief can also be discussed with @FixTheAdmin
