### ISSUE TITLE
[Feature] Distribute queue players in multiple player-sumbitted lobbies

### ISSUE THREAD

**Issue by FranchuFranchu** [EarthMC/Issue-Tracker#420]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i am making the queue parkour and i get pushed

**Describe the solution you'd like**
The solution would be multiple queue worlds, so that there are less players per parkour and we dont get pushed so much. Another good thing would be make the maps player-sumbitted, so that players feel more integrated with the server.

**Additional context**
None

**Comment by KarlOfDuty** [comment]
This would create way more issues than it solves.
