### ISSUE TITLE
feautre- queue

### ISSUE THREAD

**Issue by endothermic123** [EarthMC/Issue-Tracker#421]
**Describe the issue**
A clear and concise description of what the issue is.
It takes me on average 5 hours longer to join the server with the queue than before it so like 8 or 9 hours total of nothing but waiting only to be kicked by a restart
**Coordinates**
X Y Z coordinates.

**Screenshots**
Please add screenshots to help explain your problem. They can be of both the emc map and of how you want the terrain to look.

**Comment by shirazmatas** [comment]
Is this a feature request, a bug report, or both 🤔 💭 
please follow format or uhhm specify what you want to change

**Comment by FutureCW** [comment]
Queue never takes over 5 hours without donator/priority.

**Comment by Kyoris** [comment]
typically 2 hours is the upper limit tbh

**Comment by KarlOfDuty** [comment]
Please resubmit with a better description of what you want exactly.
