### ISSUE TITLE
No gold from voting

### ISSUE THREAD

**Issue by freatrd** [EarthMC/Issue-Tracker#422]
So, I just voted as soon as I got on after maintenance. And, on my second vote, the server started restarting. I log back on, 5 gold. I voted on both websites and I only got 5 gold.

**Screenshots:**
![Minecraft 1 13 2 3_17_2019 12_51_23 PM](https://user-images.githubusercontent.com/48654158/54494891-542c9880-48b5-11e9-8ad1-bd48753a78f8.png)
![Vote for EarthMC - Google Chrome 3_17_2019 12_51_08 PM](https://user-images.githubusercontent.com/48654158/54494892-542c9880-48b5-11e9-88e0-a4704174d352.png)
![Vote for EarthMC - Google Chrome 3_17_2019 12_51_18 PM](https://user-images.githubusercontent.com/48654158/54494893-542c9880-48b5-11e9-8131-0ca5fdf1588d.png)

**Comment by KarlOfDuty** [comment]
This is not an issue on our end, the voting sites just do that sometimes.
