### ISSUE TITLE
Why isn't the queue hub a battle royale for a spot?

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/Issue-Tracker#423]

**Comment by KarlOfDuty** [comment]
Minecraft hunger games instance joinable from the hub server 💯

**Comment by WyWall** [comment]
Yes. make this a thing please

**Comment by Kyoris** [comment]
Make it like the hypixel uhc lobby where there is a pvp bit

**Comment by Sabatarge** [comment]
Nah, compulsory Battle Royale on regular intervals

**Comment by Kyoris** [comment]
random battle royale events every 10-20min

**Comment by SaucySalmon** [comment]
How about Fix stops being such a jewish faggot and removes the queue? That thing is a fucking Jewish shekel farm.

**Comment by KarlOfDuty** [comment]
Behave yourself or you will be blocked, this is your only warning.

**Comment by KarlOfDuty** [comment]
I like the idea, but it will likely take some time to set up something like this so don't expect it very soon if it is even feasible.

**Comment by SaucySalmon** [comment]
I doubt that Fix would want to make the queue fun though as that would disincentivise donating to the server to skip the queue.

**Comment by SaucySalmon** [comment]
Also, Fix is a Jewish Nigger

**Comment by BowShot118** [comment]
> Minecraft hunger games instance joinable from the hub server 💯

 EarthMC Minigames server when
