### ISSUE TITLE
[Feature] Blue And Purple Donors Don't have priority

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#424]
Please make it so that frost donators (blue donators) get priority in the queue. Then followed by purple donators and then yellow.

**Comment by BowShot118** [comment]
lol, it really doesn't change much...

**Comment by Aitonater** [comment]
I agree I donated in the first place to skip the queue and get priority on the server, I donated considerably more than yellow donators and I have to wait behind them in line.

**Comment by NeonKrby** [comment]
Aitonater that logic is flawed, You chose to pay more. The extra is to help the server and no bonus rewards were promised so chill the fuck out lmao. Also mag same with you, you chose to pay 40$ before the queue even existed so yeah no.

**Comment by Aitonater** [comment]
Its not flawed at all, if you donate more you should not have to wait behind people who have donated less. I got donator so I could actually play on the server before the queue existed and now the queue has been implemented I have to wait despite being donator whereas before I didnt have to wait at all. I wouldn't have donated $40 if it turned out to have the same effect of donating $10 in terms of priority to join the server.

**Comment by NeonKrby** [comment]
You chose to pay more. Never anywhere in the purchase did it state that you would gain a benefit for paying more.

**Comment by NeonKrby** [comment]
The only benefit for buying frost fade was the player skulls.

**Comment by Kyoris** [comment]
dude like compared to non-donators you barely have to wait. please like stop complaining because you have to wait an extra 2 minutes while everyone else has to wait 1 1/2 hours on average.

**Comment by NeonKrby** [comment]
Up caret

**Comment by WhitPlayzYT** [comment]
As a frost/purple donor you didn't "pay" more, you purely donated more. A donation should not have expected perks. I pretty sure even in the ToS it says that buying donor rank is purely a donation and may have no perks whatsoever.

**Comment by BowShot118** [comment]
^^ For once I agree with Whit

**Comment by KarlOfDuty** [comment]
This should be resolved now.
