### ISSUE TITLE
Stuck in a nether portal

### ISSUE THREAD

**Issue by abbeytx** [EarthMC/Issue-Tracker#425]
**Describe the issue**
I went through a nether portal and now I am trapped. I cannot break anything since it is on claimed land and I can not type in chat to teleport out. I've tried everything.

**Coordinates**
My coordinates are x: 19345.7 y: 60.5 z: -2251.075

**Comment by PoppyK** [comment]
are you still stuck?

**Comment by PoppyK** [comment]
I went to the coords and broke the portal, (and remade it) but didn't see you.   You didn't respond when I tried to msg you on discord.  I also tried to get your attention in-game a few times with msgs and global chat.  Hopefully, you have been freed.
