### ISSUE TITLE
[Mechanic] Add something that helps reduce the amount of towns with one player in them.

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#427]
Did y'all know that 43% of towns on EMC have 1 player in them. There's around 1760 towns on EMC, and around 10 new ones are made every day. Something needs to be done to fix this epidemic of towns and the playerbase being spread so thin. I have a few suggestions:

1. Increase the cost of towns to 64 gold or higher. This would remove the ability to make town within your first day of playing, and lets new players have a chance to see if they like the server or not before making a town and possibly going inactive.

2. Lower the inactivity timer to around 20 days or less. This would make sure the inactive towns would surely get kicked in a reasonable amount of time. 

3. Only allow towns to be created by someone who has been on EMC for at least around a week. Like my first suggestion, it would give players a chance to see if they like the server or not in a reasonable amount of time. If they don't, they leave and go inactive, but likely will contribute to claims for a town. If they stay, and they like the server, then they are probably going to make a nice town.

**Comment by Kyoris** [comment]
for the second point make it so only towns of 5 chunks or less will have a shortened timer as if you've took the time to expand your town you probably will stay for longer and should have more leniency, and for the third point maybe make like 3-5 days as a whole week is a bit long and may result in players quitting because they cannot make the town they want quickly.

**Comment by BowShot118** [comment]
yeah I own a my own town, and I have no residents so I'd be against the deleting towns with 1 res like wtf.

**Comment by BowShot118** [comment]
good message though and I agree with the third point ^^

**Comment by FutureCW** [comment]
> yeah I own a my own town, and I have no residents so I'd be against the deleting towns with 1 res like wtf.

It's not really deleting 1 resident towns, it's more for lowering the amount of them as most are inactive, which does not include your town.

**Comment by BowShot118** [comment]
> > yeah I own a my own town, and I have no residents so I'd be against the deleting towns with 1 res like wtf.
> 
> It's not really deleting 1 resident towns, it's more for lowering the amount of them as most are inactive, which does not include your town.

~~yeah but I rarely play~~. Fair

**Comment by KarlOfDuty** [comment]
Players need to be able to protect their things within the first day of playing, everyone can't really go off joining other towns as they are likely to just get scammed out of their stuff.

**Comment by FutureCW** [comment]
@KarlOfDuty I recommend adding it so we can use private signs and mayors can't access other citizens plots.

**Comment by MineHero43** [comment]
Increasing the cost of creating towns seems like the best option imo

**Comment by cat234** [comment]
> Increasing the cost of creating towns seems like the best option imo

Actually, that would probably make the half of the playerbase quit.

**Comment by FutureCW** [comment]
> > Increasing the cost of creating towns seems like the best option imo
> 
> Actually, that would probably make the half of the playerbase quit.

I think we're fine with shorter queue times and the ability to grind more often

**Comment by WhitPlayzYT** [comment]
Fun Fact: There's over 810 towns with 1 person in them. About 800 of them are inactive.

**Comment by AlexGamerYTT** [comment]
1. First suggestion was apparently accepted as now creating a town is worth 64g.

2. I think 20 days of inactivity time for the town to fall is too short, I would prefer 30 days.

3. The third idea is really good! However, I agree with Kyoris to make it less than a week as new players would get tired of waiting.

**Comment by KarlOfDuty** [comment]
We do not want the inactivity time too short and players need to be able to create towns immediately so they can protect their items and structures.
