### ISSUE TITLE
[Mechanic] Command to turn XP into XP bottles

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#429]
I've already suggested this before but it's more relevant now as no one can grind blazes while the server is full. It would be so helpful if I could grind blazes at night while the server isn't full and then turn the XP I get into bottles so I can use them during the next day. Not having XP stops me from mining for resources and terraforming my town. I just think it'd be nice to add a command like /bottle get max where it takes the XP in your XP bar and turns it into XP bottles so people won't have to wait till night to efficiently mend their items.

**Comment by FranchuFranchu** [comment]
yes, this would be great

**Comment by KarlOfDuty** [comment]
Implemented next restart.
