### ISSUE TITLE
[Bug] Horse/Boat Flying bug

### ISSUE THREAD

**Issue by JustAmit** [EarthMC/Issue-Tracker#431]
**Server**
EarthMC Terra Nova

**Describe the bug**
The server kicks you from the map to the queue when you get on a horse or on a boat because it thinks you are FLYING

**To Reproduce**
Go on a boat or a horse and besure you can be kicked like that if you are stuff - then it may happen

**Expected behavior**
That I don't get kicked.

**Screenshots**
No screenshots available

**Additional context**
I have experienced this bug many times and it's annoying that mods can't skip the queue for you when it occurs.

**Comment by KarlOfDuty** [comment]
Should be fixed next restart.
