### ISSUE TITLE
Enabling PvP in larger towns

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#432]
War on EMC is stale and uneventful, as it's mostly people who trash talk each other over discord and sometimes claim fucking each others territory. This is why i propose to enable PvP in all larger towns, as this will allow people to actually fight each other without having to snipe them using the dynmap when they leave their town shortly, or sieging the towns for hours... My proposal is that a town should automatically have PvP enabled when they surpass 8 chunks territory, as they should be big enough to defend themselves at that point. If people dislike this and think it's to early, i believe that PvP should atleast be enabled in capitals. This would also add another depth in town building, as walls could be an effective way to counter attacking forces!

**Comment by PoppyK** [comment]
um, no? I get killed enough out of claim bounds.....don't need to be worried about this the whole time I'm within claims too!  ANY town can toggle pvp.  Your choice.

**Comment by alekb1** [comment]
Well as I stated, a simple wall could protect you as people still can’t fly into your base as the end never seems to come

**Comment by BowShot118** [comment]
It's a dumb idea alek. Not everyone has time to build massive walls

**Comment by Kyoris** [comment]
And I'm not gonna ruin Pripyat with walls God dammit

**Comment by alekb1** [comment]
Bowshot I could build a sufficient fence around a 200 chunk base in an hour or two so I highly doubt anyone would not have the time, and kyoris the era of war Minecraft pvp was modled after had walled cities, as it was the most effective defensive. My point here is mostly that this server is supposed to be a geopolitical experience, and war is one of the incredibly necessary part of that, because without it, people don’t actually have any major repercussions of hostile actions. This might very well not be a perfect solution, but a solution if I non the less. As an example Danelaw made a claim in danish territory and moved their capital there. In any actual geopolitical event this would have been an extremely hostile action, that would have resulted in swift military action. The difference is that we can do absolutely nothing, as Danelaw hide inside their claims and just continue to expand

**Comment by BowShot118** [comment]
^^ Block Glitching and hackers

**Comment by alekb1** [comment]
You can build secure fences from block glitching, and if a hacker attacks You should honestly film it or log out

**Comment by 4noah18** [comment]
I agree with this. And for the fucks who say it’s too hard to make a wall, a two layer cobble wall with stairs lining the bottom can be done easily in a couple hours or less with even moderate sized towns.

**Comment by Kyoris** [comment]
Well not everyone is down to fight, especially in say markets and grinders where people could easily camp out others minding their own business. Basically this makes life a lot more difficult for the peaceful/neutral and helps the retards who just like killing for no reason other than for fun.

**Comment by alekb1** [comment]
So what you’re saying is that we should hinder one of the largest impacter of politics in all of history to protect people who just want to stay neutral? In my opinion you should be able to stand up for yourself if you want to expand your town past 8 chunks, and I don’t believe people will mindlessly start to slaughter people just because they can! Instead I believe that this will make an actual need for alliances and political favors only reinforcing the need to act politically, which I may remind everyone is the actual point of this server. A geopolitical simulator, cannot be complete without consequential war!

**Comment by BowShot118** [comment]
1 Word: ISIS

People like that, the true toxic cunts of the server, would camp out at markets and grinders just to kill people. Tp killing was a thing because the game allowed for it. So, who says camping n spawns wont be too?

**Comment by Kyoris** [comment]
That's what I'm saying. There's always gonna be those cyka blyats trying to kill you for whatever reason, and making pvp enabled in most towns are just going to encourage said behavior and make the problem worse.

**Comment by alekb1** [comment]
But it will solve so much more than it will hurt. Regarding n spawn camping, only allies can go to your n spawn if it’s safely protected, so people camping it would instantly loose them as allies, as they don’t want people like isis to have acces to their town. And remember allies can’t attack you, that is a feature of towny. What it would do on the other hand, is have people actually consider who they want to ally. Rn allying people are just a general acknowledgement of “we’re not at war”, and “I would like to be able to go to your capital”. It’s stupid... allies mean nothing on emc. On the other hand if allying someone meant trusting them not to massacre you town... oh boy would alliances be thought out and tactical. This would also allow for trade unions where trade towns would band together around a code of behavior. IRL only has rules accepted by the public protecting you, so why not try and mimic that here? Let the few drastic terrorist attacks spark furious retaliation! Give people the possibility of protecting their land from invaders! And ffs people who just want a small mountain base enjoying Minecraft at it’s most beautiful still can if we have a limit of chunks before going into the pvp setting

**Comment by BowShot118** [comment]
So basically, it's another gay idea for the strong to pray on the weak. It's very easy to boast about the benefits when you wont feel the negatives lmao

**Comment by alekb1** [comment]
I play because of politics, but the war aspect of politics is currently 90% people raging at each other in chat

**Comment by BowShot118** [comment]
I'll take that as a yes

**Comment by alekb1** [comment]
want To know what you need to be strong on this server, as mcmmo combat is disabled? Combat gear and skills. I’ve seen combat armor go for 20 g which is 2 days of voting. And a combat sword? Maybe 8 g blaze rods? 1 g easy... so 29 g or 3 days of voting... and concrats you’re among the strong

**Comment by alekb1** [comment]
Let’s not pretend that it’s hard to reach top gear of Minecraft

**Comment by BowShot118** [comment]
Still not fucking fair. People to come to build and experience the map. Not be harrassed by toxics who jerk eachother off with their mates has they charge exceptionally high prices to leave people alone.

**Comment by alekb1** [comment]
well then I have another proposal instead that should satisfy you, any town that is in a nation have pvp toggled on. This makes a lot of sense, as rn there is absolutely no downside to joining a nation. This might actually be a better implementation, as if you join a nation, you’re also joining their politics. It could be made so when you join a nation, a warning message appears in chat stating: “You’re about to join a nation and its politics! In doing so your town will have PvP toggled on!”

**Comment by ScaryDragonn** [comment]
alek this isn’t factions. This is towny. It is towny with politics thrown in, that’s true, but it is essentially towny. Not everyone likes being attacked by toxic players who feel like doing some epic pvp and enemying everyone. Some towns just want to build a city on a map of the world.

**Comment by alekb1** [comment]
And people can still easily make towns and enjoy EMC. If you've ever played on factions you would know that it's all about killing people/firing tnt canons to unclaim the chunks where there loot is located. I don't propose that you should be able to steal stuff from other players... I don't propose that you should be able to grief... I on the contrary propose that larger towns just can't claim fuck each other, ruining months of preparations and making a literal mess of the borders, without repercussions being possible! I mean people can't protect their homeland and borders. Currently the only offensive and defensive strategies on the server is spending thousands and thousands of gold, claiming the entire country. Talk about the top 1% dominating, am i right? I mean, please for the love of god try to actually sit down and draw the borders of Europe. It's an absolute clusterfuck. It's simply because nations can bribe smaller towns into joining them, making the borders of your nation only truly depend depend on your pocket. To take an example from all of the guys who are currently arguing against this plan. Scarydragon you live in a 1 chunk 3 person town which belongs to no nation. You'd be safe in both cases to live your peaceful existence in the mountains or whatever. And Pock/bowshot118/aTerraAus (whatever you wanna be named) you live alone in Sorong, in an area where there is no claim fucking each other, to be straight with you, none of the towns you've been in on Terra nova has actually experienced claim fucking of any sort! So you're literally blessed with ignorance of the shear annoyance that it posses. And Kyoris... You're border is currently not the prettiest. Why not have the ability to fight to preserve it? Terra nova was all about having actual borders. But this rapidly feels like the old EMC where on nation just took in any town without a thought of relevance what so ever... So please enlighten me how will you stop claim fucking?

**Comment by ScaryDragonn** [comment]
My town was created literally a few days ago, who the fuck cares if it’s only a couple chunks? I’m in the process of moving towns. I ran a European nation of 150 briefly, so yes, I have actually experienced “claim fucking”. Terra Nova was not all about having actual borders, I have no idea how you even thought of that. Terra Nova was a new map for EarthMC after players starting complaining about the emc Classic map being full (and it was). What does claiming have ANYTHING to do with pvp in towns anyway? tbh this probably makes no sense I’m very tired and don’t have time to be explaining how the server works to a newfag like you but eh

sorry if I’m missing something obvious I’m tired

**Comment by alekb1** [comment]
First of all i've played EMC for more than 2 years, how long do you have to have played to no longer be a newfag? Why do you think they implemented the max range of nations? It's so we have actual nations where the towns are in close proximity...

**Comment by ScaryDragonn** [comment]
epic! Is that you alek? Damn I didn’t know you still played.

**Comment by alekb1** [comment]
Lol yeah, okay to clarify, I'm alek_b leader of Denmark

**Comment by FenZenyatta** [comment]
epic suggestion, I agree

**Comment by NeonKrby** [comment]
No this would ruin the server for many people. The war plugin CFH was or still is developing that should be a feature. If nations are at war all the towns in the nations have pvp toggled. That way smaller kids who have no interest in PVP are safe.

**Comment by BowShot118** [comment]
^^

**Comment by alekb1** [comment]
First of all i've heard rumors about that plugin for over a year or so. Will it ever actually come, do we have any update about a potential ETA? And enlighten me then, because my information about that plugin is lagging at best. If i'd for example would enemy Germany, but they did not want to enemy me, would we be at war?

**Comment by NeonKrby** [comment]
Ask CFH if hes still even making it. Anyways fuck off with your idea alek go play on herclulaneam or whatever the fuck that shitty server is.

**Comment by Aitonater** [comment]
Karl has said on the reddit fairly recently there will never be a war plugin because no functioning war plugins exist. I know this is not exactly what the post is suggesting with pvp being enabled in large towns but I think it is related.

**Comment by diamondkid300** [comment]
yeah, that could work, build a wall and claim around that wall to prevent anyone from building up and jumping on the wall. or at least have this until the war plugin

**Comment by alekb1** [comment]
Thanks diamondkid, and Krby keep a proper tone, rn you’re just highlighting the toxicity that is only worsened by people not being allowed to have a good go at each other.

**Comment by alekb1** [comment]
And thanks for the info aitonater, much appreciated!

**Comment by diamondkid300** [comment]
no problem, I'm just thinkin about what it could do

**Comment by alekb1** [comment]
Yeah I mean it should be a simple implementation, and would be great for like a trial month?

**Comment by alekb1** [comment]
As it is rn, I really think any change in the war system should be tried

**Comment by diamondkid300** [comment]
anything that could bring life into the server really

**Comment by Kyoris** [comment]
I don't want to be chilling in my town or out looking to buy say diamonds and still have to worry about cunts that want to kill you, not to mention how much more difficult it would be to trade hand-to-hand as you really don't know whether is the guy actually just wants to buy stuff or to kill you and steal your shit.

**Comment by BowShot118** [comment]
Yeah but Kyoris, it won't effect Alek as him and his gang are OP so it must be a fucking amazing idea!!!

**Comment by alekb1** [comment]
Kyoris, I don’t believe that a lot will change for the normal day to day life. More than 90% of the EMC population are generally sensible, and don’t go killing everyone. If you think about it no one would actually trade with someone who constantly kills people instead of trading, forcing people to grow reputations

**Comment by alekb1** [comment]
As started earlier, it takes nothing to reach endgame of Minecraft. Vote for three days and you have endgame gear

**Comment by alekb1** [comment]
You can’t really call us op when it’s the equivalent of spending 10 hours to setup and then one hour for each god set

**Comment by alekb1** [comment]
That’s like calling level 10 in wow op

**Comment by BowShot118** [comment]
1. The edit button exists.
2. It doesn't take 3 days of voting to get to the top of the mcmmo leaderboards for most skills.

**Comment by alekb1** [comment]
Have you been sleeping under a rock? All the pvp mcmmo skills except archery has been disabled. And archery is allready seriously underwhelming

**Comment by alekb1** [comment]
And what do you mean about edit button?

**Comment by BowShot118** [comment]
One your post dumbass

**Comment by diamondkid300** [comment]
dude chill out

**Comment by BowShot118** [comment]
Oml another marchfag believing that being killed while trying to buy bread by some toxic shit is a good idea....

**Comment by diamondkid300** [comment]
simple. get someone that can be trusted. simple, farm yourself.

**Comment by BowShot118** [comment]
Sidestepping my point but okay

**Comment by diamondkid300** [comment]
its a solution isn't it

**Comment by Magenent** [comment]
I would rather have this than not, at least until a war plugin, but this is more of a short term solution.

**Comment by diamondkid300** [comment]
yeah, but it is totally possible that plugin won't happen

**Comment by BowShot118** [comment]
To what? This solves fuck all.

All this does is let more OP and pvp active players, conveniently like Alek and his mates, pick and pray on smaller towns just because they're larger then 8 chunks.

People used to tp kill because he was part of the game, it was done just because people were cunts. This is the same toxic shithole of a community so claiming that most people aren't like that won't cut it.

**Comment by alekb1** [comment]
Oh yes! And while we’re at it, the game is a little to hard allready! We should lower the price of nations to 64 again so everyone can get one, because a thousand gold common, that requires at least some commitment, and you know what, that might be a little unfair to the weake players! And honestly only 10 gold for voting!? Should be 32 so you can create a town the minute you touch the ground... and what’s up with me being in danger in the wild! Let’s turn of pvp completly. Talking about other players why can’t I teleport to them? Would make my life easier! And what’s up with me loosing my stuff when I die!? We need keep inventory on! Think of all the progress I made. Also wtf is lavas deal, why does it have to hurt so much? Let’s ban it from the server! *obvious sarcasm is obvious*

**Comment by diamondkid300** [comment]
also if push comes to shove, the devs could just add a specific trading area that can be teleported to

**Comment by BowShot118** [comment]
Alek is sidestepping my points but okay.

And, diamond, the reason there isn't a trading area is so the server runs the ingame stuff itself.

**Comment by diamondkid300** [comment]
no i mean an area where players can trade with each other

**Comment by Kyoris** [comment]
That is basically the nation spawns where people have been content with for however long since nation existed.

**Comment by BowShot118** [comment]
As I said, there is a fucking reason that there isn't a special trading zone lmfao.

**Comment by alekb1** [comment]
you’re afraid that people will just instant kill anyone trading with them? You literally allready can that by toggling pvp in plots or setup killing chambers at n spawn. Now question is... why don’t people do that currently? It’s not because it’s hard, because I could build one in 5-10 min if I wanted, no it’s because it would ruin faith in you and your nations honor.

**Comment by BowShot118** [comment]
Again sidestepping my entire point lmao. My point is, shockingly, people o u t s i d e o f t h e t o w n c a n k i l l p e o p l e i n f o r i e g n c l a i m s :facepalm:

**Comment by diamondkid300** [comment]
just create a wall and claim around the wall to prevent any stack building

**Comment by BowShot118** [comment]
Nation Spawn Teleportation lmfao.

**Comment by diamondkid300** [comment]
something can be done to prevent that

**Comment by BowShot118** [comment]
Run me through how you can stop rogues in allied nations teleporting to your n spawn and killing everyone.

**Comment by diamondkid300** [comment]
allied people cannot kill each other then

**Comment by BowShot118** [comment]
As i said, Rogues in allied nations. You can leave a town or nation you know. And not everyone is allied with everyone else. :facepalm:

**Comment by diamondkid300** [comment]
im not saying everyone is allied with each other then if this would become a plugin it would be useless. but if anything you could be automatically kicked from allied nations area if you leave that town/nation

**Comment by BowShot118** [comment]
Ypu can still kill people in allied lands that you aren't allied with.

Are you fucking retarded or something, or can you just not read?

**Comment by diamondkid300** [comment]
ok no, you are retarded because i can already tell you didn't understand my original statement. go back to what i said.

**Comment by BowShot118** [comment]
Right let me run you through how this works.

1. Allies can Teleport to other allies' n spawn.

2. Not all of the mutual ally's allies are allied.

3. With Pvp on, they can kill eachother as they are not allied.

4. Kicking people out of claimed land when they leave a nation doesn't address the issue that people who aren't allied can kill eachother in a mutual ally's n spawn.

**Comment by diamondkid300** [comment]
yes thats why in that allied land they will be kicked out

**Comment by FutureCW** [comment]
As the leader of one of the most prominent shops on EMC that got it's popularity due to being a huge shopping and trading area, are we just going to fuck over everyone who owns a shop because you want PvP toggled everywhere?

**Comment by diamondkid300** [comment]
Never knew building a wall took that much time

**Comment by BowShot118** [comment]
OMG THIS FUCKING MARCHFAG.
READ
WHAT
I
SAID
1. NOT EVERYONE IS ALLIED. DO YOU FUCKING UNDERSTAND THAT?

2. IF THEY AREN'T ALLIED, THEY CAN KILL EACH OTHER.

3. THEY CAN BOTH BE ALLIED TO THE SAME NATION.
BUT
NOT
TO
EACH
OTHER

**Comment by diamondkid300** [comment]
1RST OF ALL IM NOT SECOND OF ALL WHAT DOES THAT HAVE TO DO WITH BUILDING A FUCKING WALL

**Comment by BowShot118** [comment]
Because you can
T e l e p o r t to nation spawns.

Is that such a fucking hard concept to understand?

**Comment by diamondkid300** [comment]
something can be done to prevent that

**Comment by BowShot118** [comment]
Like what?

Remove the only teleportation in the fucking game?

**Comment by FutureCW** [comment]
Hold on let me just ruin the experience for a whole nation because of a single offending member. Lemme just remove my 100 allies so my citizens can't tp elsewhere to get wood and other materials. Lemme just build an ugly ass wall because the sides of my island don't have enough space. Let me just FUCK OVER THE ENTIRE SERVER

**Comment by diamondkid300** [comment]
no i mean maybe there can be some safe zones that outside members can join into

**Comment by BowShot118** [comment]
And that would defeat the entire point of this lmfao

**Comment by diamondkid300** [comment]
but its limited

**Comment by BowShot118** [comment]
Again, sidestepping my point.

Adding a safezone in nation spawns.... defeats the point of toggling pvp...

**Comment by diamondkid300** [comment]
ok lets say a town had 40 chunks but are only able to have 8 chunks of safe zone, still got taht 32 chunks of pvp

**Comment by BowShot118** [comment]
Shockingly people can walk into the safe zone!!!!!

**Comment by diamondkid300** [comment]
yeah, and?

**Comment by BowShot118** [comment]
It defeats the entire point of toggling the town's pvp lmao.

**Comment by diamondkid300** [comment]
but then you have that other 32 chunks unattended and productivity in the town has plummetted. also the threat is still there

**Comment by BowShot118** [comment]
You can put chest rooms and "productive" stuff into the safezone... :facepalm:

**Comment by RangerMK01** [comment]
You just have a reason as to why this is a terrible idea. Plummeting productivity. I don’t need to spend my time watching my back while I’m trying to farm or build in my town, and my Citizens especially don’t

**Comment by diamondkid300** [comment]
yeah but idk about you but fitting everything in 8 chunks isnt really that nice. also mentioning depending on how much chunks you have goes into the safe chunks

**Comment by Kyoris** [comment]
not to mention a safe zone literally defeats the purpose of this change. People will just have to fiue out where the safe chunks are, and once they do, they can just run into the safe zone LIKE THEY DO RN

**Comment by RangerMK01** [comment]
People will just start building y’all my dude

**Comment by diamondkid300** [comment]
ok now your area is filled with enemies gj

thats why you claim around the wall to prevent that

**Comment by BowShot118** [comment]
~~Here comes the Cavalry~~

**Comment by BowShot118** [comment]
PEOPLE CAN STILL TELEPORT INSIDE THE WALL LMAO

**Comment by diamondkid300** [comment]
THINGS CAN BE DONE TO PREVENT THIS

**Comment by BowShot118** [comment]
Like the fucked up ideas you've already mentioned?

**Comment by Kyoris** [comment]
IF YOU HAVEN'T BEEN PLAYING FOR AT LEAST A FEW FUCKING WEEKS YOU CAN SHUT UP GOD DAMMIT

**Comment by diamondkid300** [comment]
FOR EXAMPLE USING THE SAFE ROOM TO TRAP THE ENEMIES IN A ROOM AND IF THEY TRADE LET PUT SOME SIGNS

**Comment by RangerMK01** [comment]
Like what. Plugins take time, money, and processing power. The benefits are far outweighed by the negatives

**Comment by diamondkid300** [comment]
lucky for me i have played for weeks

**Comment by BowShot118** [comment]
The queue doesn't count retard

**Comment by RangerMK01** [comment]
Then you should realize that combat doesn’t really work unless there is a designated war plugin, which will not be happening as Karl said

**Comment by FutureCW** [comment]
So be extremely active and have your n spawn outside of the wall or just give up and plummet productivity because the amount of useless plots is so large compared to safe zones

**Comment by Kyoris** [comment]
do you actually have an idea of how much shit will go down
are you a fucking trader?
you own a shop?
or do you have a nation spawn?
do you even own a fucking town god dammit

**Comment by diamondkid300** [comment]
yes actually

**Comment by BowShot118** [comment]
Lmfao shall we just ignore the marchfag? He's not actually contributing anything and has no experience with this shit anyway.

**Comment by diamondkid300** [comment]
i still not a "marchfag"

**Comment by BowShot118** [comment]
Sorry, I was wrong.

You're a fucking retarded Marchfag.

**Comment by Kyoris** [comment]
honestly yeah fuck this
if alek wants to discuss this at least he has experience on the server
but not someone who has no idea how this shit works

**Comment by FutureCW** [comment]
According to his answer he has an idea, is a trader, owns a shop, has a nation spawn, and owns a town.

**Comment by diamondkid300** [comment]
well ok bye

**Comment by BowShot118** [comment]
Fucking finally. Back to a sorta civilized discussion. I need a lie down smh

**Comment by diamondkid300** [comment]
na i'm still here, i was referring to you guys leaving

**Comment by BowShot118** [comment]
That's not how that works but okay

**Comment by MineHero43** [comment]
I think enabling pvp in major towns and just leaving it at that essentially turning them into huge battle Royale zones won’t really work well long term, no matter what you do there will always be a group of people who go out killing innocents for fun

However perhaps we could make it so that if you’re enemies/at war with a nation, you’re able to attack them even while they’re inside their claims? I think that’s better than just enabling it for everyone, it would also mean that going to war with someone actually has a real effect in game.

I’m not really sure how that would play out, perhaps we should just wait for an actual towny war plugin to come out but then again I doubt that will be happening anytime soon

**Comment by diamondkid300** [comment]
oh hey look this guy actually has useful insight.

**Comment by Kyoris** [comment]
that's what i would say may work, though like you said i have no idea how the mechanic would work

**Comment by BowShot118** [comment]
So not yourself!

**Comment by diamondkid300** [comment]
his comment does have a valid idea

**Comment by FutureCW** [comment]
I like MineHero’s idea much better than having to waste time fucking up my town because infinite pvp

**Comment by BowShot118** [comment]
I really don't think you can go arguing about Valid Ideas ngl.....

**Comment by diamondkid300** [comment]
well no because then they could start a war with everyone

**Comment by FutureCW** [comment]
Also, if all towns had pvp toggled then people would be sending fucking newfags to trade and buy items. Rampant altinf

**Comment by BowShot118** [comment]
MH makes some good points, It'd be nice to have some form of war plugin that doesn't contain taking/loosing land. Being able to kill enemys in their claims works well imo, not the Battle Royale of Alek's idea xD

**Comment by FutureCW** [comment]
War with everyone turns it into a game of tons of nations vs 1 instead of a battle royale

**Comment by diamondkid300** [comment]
it doesn't necessarily have to be at once

**Comment by Kyoris** [comment]
and i doubt anyone with more than 7 brain cells would do that shit

**Comment by diamondkid300** [comment]
well someone said themselves people can be dicks

**Comment by BowShot118** [comment]
So diamondkid300 would bring his supposed trading nation into war with everyone.

**Comment by FutureCW** [comment]
Only dicks with a few brain cells would want to get pummeled by a shit ton of nations at once

**Comment by diamondkid300** [comment]
not me, others

**Comment by Kyoris** [comment]
:thonk:

**Comment by Kyoris** [comment]
and honestly even isis wouldn't be one to try to fuck over everyone at once. maybe a few, but definitely nothing close to everyone

**Comment by MineHero43** [comment]
Perhaps it would require for both sides to agree to start a war, however if one side refuses to go to war maybe they’d have to pay a sum of gold to the other side in a certain amount of time to prevent a war from being triggered.

Once a war has been triggered, you’d be able to kill eachother in claims

It’s just a rough idea but it’s a possible solution

**Comment by diamondkid300** [comment]
yeah but that wouldn't work either because they start war with everyone and gets free gold

**Comment by diamondkid300** [comment]
unless you have to pay to initiate that war progress

**Comment by Kyoris** [comment]
i think it would be better if it takes a decent sum of gold to declare and you don't have to agree to it, as to stop people from say declaring war with everyone just for the sake of it

**Comment by FutureCW** [comment]
Paying to start war would be nice.

**Comment by diamondkid300** [comment]
Yeah i think paying for both sides would be the best option

**Comment by MineHero43** [comment]
Yeah I definitely agree, nations should have to pay gold to start a war.

Perhaps the sum could vary depending on the size of the nation, let’s say you want to declare war on a nation smaller than yours, you’d have to pay a bit extra.

I think that would solve the issue of bigger nations picking on smaller ones

**Comment by diamondkid300** [comment]
fair point. and it should be both nations will lose an equal amount unless like you said they were smaller

**Comment by Kyoris** [comment]
i think that would be good.

**Comment by diamondkid300** [comment]
if only that could be implemented

**Comment by Aitonater** [comment]
I think you guys are forgetting the key part where karl the main and only dev of the server has said that a war plugin will never happen. 😬

**Comment by Kyoris** [comment]
Well what we have agreed upon should be a quick addition to towny, so if Karl can do it, he probably would, as the reason Karl decided to not have war is that all the plugins available are buggy.

**Comment by Aitonater** [comment]
In reply to should there and will there be war on the server: "There exists no war system that is not entierly broken, so no there will not. " -Karl

**Comment by KarlOfDuty** [comment]
There is no way to selectively force pvp on for specific towns, so this is not possible.

And yes, there is currently no functioning war system so war is impossible too.

**Comment by Aitonater** [comment]
Told you guys. Yeet Karl has spoken.

**Comment by diamondkid300** [comment]
That’s a feelsbadman

**Comment by diamondkid300** [comment]
Worth a try eh?

**Comment by watergod1234** [comment]
Since this thread seems to be getting more attention than #436 I’m going to post what I originally said there in here. 

I agree totally with this! However to others it could seem a tad extreme. So I propose maybe only on Saturdays (could be any day, it doesn’t matter) PVP would be enabled in all towns. It’d be like a dedicated war day (or the next closest thing) for nations to siege and kill their enemies on a periodic basis. Since everyone would know when it is people would prepare or choose not to go outside during wartime. To me, this seems like a good compromise to everything. Not having any war type function makes the geopolitics on a “geopolitical sandbox” kind of stale in my opinion.
