### ISSUE TITLE
[BUG] Villagers (floating and not trading)

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#433]
**Server**
EarthMC (earthmc.net)

**Describe the bug**
Any new villagers that are born are unable to be moved by boats, minecarts, hitting them or bumping into them, water. These new villagers will not trade higher than the first 2 trades available. If you place them in a minecart or a boat and break the minecart or boat they will teleport about 2 blocks higher and still remain immovable and unable to trade as mentioned before. Also the villagers will float and ignore the laws of gravity in the game. (Edit. The new villagers also do not breed)

**To Reproduce**
1. Find any new villager that has just been created by a breeding pair.
2. Attempt to move the villager or unlock more trades when it reaches adulthood.

**Screenshots**
Some screenshots of the villagers floating after trying to move them with boats/minecarts (hitting them and using water does not move them)
![53794693-66f3b480-3f28-11e9-8a73-e2df7d1b4225](https://user-images.githubusercontent.com/47613294/54791170-b1677780-4c30-11e9-9c2c-911c7ff69708.png)
![53824033-edc98100-3f6a-11e9-80b5-6e073176e5b4](https://user-images.githubusercontent.com/47613294/54791178-bcbaa300-4c30-11e9-8456-85cff037affa.png)
![53824173-43059280-3f6b-11e9-88c3-d876d31880cf](https://user-images.githubusercontent.com/47613294/54791181-bfb59380-4c30-11e9-9a81-33167c05479c.png)
![54064990-22129b00-4212-11e9-9f2b-7e93c9c3eed6](https://user-images.githubusercontent.com/47613294/54791185-c3491a80-4c30-11e9-8cc4-e4feb1c7ce80.png)

**Additional context**
This started about 20 days ago I do no know what changed in the server to cause this. Villagers from before this moment in time are unaffected and function normally.

**Comment by KarlOfDuty** [comment]
Villagers should get AI again when they spawn now, I've made it only disable pigs and blazes from spawners instead.

**Comment by Aitonater** [comment]
Thank you! I've been waiting 3 weeks to get breeding/trading back.
