### ISSUE TITLE
Tagging in the Discord using the Bot.

### ISSUE THREAD

**Issue by DePianoman** [EarthMC/Issue-Tracker#434]
**Server**
earthmc.net

**Describe the bug**
You can tag people in the discord using the EarthMC bot.

**To Reproduce**
Right click on the user's name in discord, and click "Copy ID"
On the server, type "<@ID>" without quotes, and replacing ID with the ID you copied.
Send the message, and done.

**Expected behavior**
Although this is expected, it is still proven to not escape characters such as `, *, and other markdown characters with a backslash.

**Screenshots**
![image](https://user-images.githubusercontent.com/23054839/54792472-a43c8f80-4c14-11e9-890a-f6d1b3e4e673.png)

**Comment by KarlOfDuty** [comment]
I mean you don't even have to use the ID to ping, you just type it normally. In any case this is intended behaviour as we just mute ping spammers whether they are ingame or in discord.
