### ISSUE TITLE
[Bug?] The lag killed me

### ISSUE THREAD

**Issue by FireWood66** [EarthMC/Issue-Tracker#435]
So a month ago lag killed me and I lost about 300levels worth of DIAMOND gear. I wasz told it was gonna be refunded my armor and tools.So I waited 2 fucking hours in the god damn queue and guess what? I STILL DONT HAVE MY FUCKING STUFF!!!!!

**Comment by shirazmatas** [comment]
How did lag kill you? Follow format please

**Comment by WhitPlayzYT** [comment]
1 you didnt follow the format
2 youre being extremely rude

**Comment by FutureCW** [comment]
300 levels lmao

**Comment by KarlOfDuty** [comment]
Also, make a support ticket this is not what this is for.
