### ISSUE TITLE
PvP in all towns, as a trial

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#436]
So expanding on #432 
I know that a lot of people feel the idea of PvP in towns are a pretty radical idea. But why don't we try it out for a week or two? As we will never actually have a war plugin, because PvP cannot be toggled in specific towns, we have two options, PvP in all towns, or PvP is up to the individual town. The two main points against the proposal are: Trade would become a more risky business (but is that really bad?), and towns will have to fortify themselves more (The most beautiful builds arise when challenges are faced head on). Despite these inconveniences, the added value of war as a concept of EMC, would greatly improve the power dynamic of the server, away from the wealthy, and towards the champions of the people. I'm sad that some people naturally assume death, destruction and mayhem, whenever this proposal arises, but it's my core belief that we are much better of with this feature, compared to without it! Thanks for reading, and for the love of god, please refrain from calling each other stupid, and generally be toxic!

**Comment by diamondkid300** [comment]
i think it would be better if war is declared and both sides agree on that war. But you have to pay to declare war and gold to refuse war and depending on the size of the town

**Comment by alekb1** [comment]
But Karl said that was impossible

**Comment by alekb1** [comment]
Totally agree btw

**Comment by diamondkid300** [comment]
i thought he said the whole discussion was impossible

**Comment by BowShot118** [comment]
No.
Just
No

**Comment by alekb1** [comment]
Pock, can’t you even agree to a short trial? The foundation of the scientific method that have helped our society become what it is today I fueled by trying

**Comment by BowShot118** [comment]
Of course I wont agree to event a "Short" trial. Why the fuck would forcing everyone to partake in pvp ever be a good idea?

**Comment by Pengun78** [comment]
There are people that focus on building, not everyone focuses on gearing up/battling
A wall would also be annoying for expansion and itll look ugly
I just want a war plugin, where as diamondkid said, u both agree to war
Id just like to see annexing land aswell

**Comment by Kyoris** [comment]
^

**Comment by alekb1** [comment]
Pengun we all want that plugin but we’ll never get it. Karl states so earlier. This is why I propose pvp in all towns. Though it’s nowhere as good a solution, I believe it’s significantly better than having nothing

**Comment by Aitonater** [comment]
I don't expect this to go anywhere Karl has already said this is not possible. The issue isn't whether players would want to have pvp in towns or not. As it stands there is no functioning war plugin. There is also no way to selectively toggle pvp in whole towns.

**Comment by alekb1** [comment]
What Karl said was there were no way to specifically toggle pvp for certain towns depending on different criteria. What is entirely possible is toggling for ALL cities

**Comment by Pengun78** [comment]
I mean cant they make one theirselfs

**Comment by Aitonater** [comment]
Karl has said he does not have the time to make the plugin. Pengun78

**Comment by Pengun78** [comment]
Fuck!!!

**Comment by watergod1234** [comment]
I agree totally with this! However to others it could seem a tad extreme. So I propose maybe only on Saturdays would be enabled in all towns. It’d be like a dedicated war day (or the next closest thing) for nations to siege and kill their enemies on a periodic basis. Since everyone would know when it is people would prepare and choose not to build. Seems like a good compromise to everything. Not having any war type function makes the geopolitics on a “geopolitical sandbox” kind of stale in my opinion.

**Comment by diamondkid300** [comment]
that could work actually

**Comment by alekb1** [comment]
I agree with watergod

**Comment by diamondkid300** [comment]
i would be fine with that really

**Comment by Pengun78** [comment]
I think it should be friday, saturday is when alot of traffic is going on as there are so much people wanting to play in their freetime, also itll have lag

**Comment by watergod1234** [comment]
The problem with it being on Friday is that most people are still in school. I’m in high school myself and I’d be annoyed that half the day I could’ve been whacking people in enemy nations but instead was stuck in school.

**Comment by BowShot118** [comment]
^^ Better then annoying a vast amount of players, lots more builders, trying to play on a weekend

**Comment by Aitonater** [comment]
WoK (a towny server) that had about 100 concurrent players had pvp enabled on weekends. It worked well because players still couldn't switch i.e. get into doors or build over walls.

**Comment by BowShot118** [comment]
Sounds interesting

**Comment by Kyoris** [comment]
I would say to enable pvp on sunday tbh, but i mean either way works, as long as there's a notice and people know to not (or to definitely) log on during that time

**Comment by endothermic123** [comment]
The War Plugin is actually unesscacary if two countries go to war they both enable pvp in their lands allowing them to fight and also letting other nations/militants take advantage just like the real world. No needed changes just an agreement. if this doesn't work i wouldn't be opposed to a once a week free for all

**Comment by cat234** [comment]
I think we should just leave PvP in towns alone and focus on more oppressing matters.

**Comment by watergod1234** [comment]
Should I make a separate thread on the PVP on Saturday idea or just leave it as is?

**Comment by Aitonater** [comment]
I think you should make a new thread. Karl has already said PVP cannot be selectively turned on in towns because there are no war plugins that work atm. The post wants to enable PVP everywhere as a trial but I think the majority of players would be against and without a majority it seems unjustified.

**Comment by KarlOfDuty** [comment]
As the comments above say, I don't think most of the server would be in favor of this.
