### ISSUE TITLE
[Bug] My priority is gone

### ISSUE THREAD

**Issue by Chromeskullss** [EarthMC/Issue-Tracker#437]
McEarth

I got kicked for "flying", even thought I wasn't. I got sent back to the lobby without priorities.

1. Run around
2. Get some lag
3. Get kicked for "flying"

**Additional context**
I'm worried if my money is wasted. I was not flying, I was lagging then I got kicked.

**Comment by cat234** [comment]
Hmm, I smell lawsuits

**Comment by shirazmatas** [comment]
Additionally Chromeskullss is not alone with this occuring. A lot of donators and priorities have experienced this issue.

**Comment by KarlOfDuty** [comment]
This has likely been resolved.
