### ISSUE TITLE
Animals do not seem to be spawning currently

### ISSUE THREAD

**Issue by 1212ra** [EarthMC/Issue-Tracker#44]
Hey, Ive been looking for animals for a very long time and havent found a single one. Pls fix

**Comment by 1212ra** [comment]
Ive only seen hostile mobs

**Comment by 1212ra** [comment]
![welpe](https://user-images.githubusercontent.com/44452582/47607019-1d93d580-da1b-11e8-8dcc-f420b899fe22.PNG)
I just went for a walk to look for animals. Heres how I walked. I found 0 animals.

**Comment by KarlOfDuty** [comment]
Fixed, although reduced again until server performance stabilises.
