### ISSUE TITLE
[Feature] Concrete Power not solidifying, solution

### ISSUE THREAD

**Issue by OyoKenyon** [EarthMC/Issue-Tracker#441]
**Is your feature request related to a problem? Please describe.**
Concrete powder will not solidify when placed in water or when water is poured over it, I assume this is because of an anti-lag plugin but I do not know for sure. 

**Describe the solution you'd like**
To remedy this I suggest the implementation of a custom recipe where you place a block of concrete powder in the crafting menu/table and it crafts a solid concrete block of the same color.

**Additional context**
Proof of the issue.
![2019-03-26_10 58 49](https://user-images.githubusercontent.com/48956449/55007692-3f878900-4fb6-11e9-9385-8a70dc7c29a8.png)

**Comment by NeonKrby** [comment]
is that atlantis?

**Comment by OyoKenyon** [comment]
> is that atlantis?
No

**Comment by NeonKrby** [comment]
good

**Comment by WhitPlayzYT** [comment]
What I would think for a good recipe would be an ice block in the middle with a torch underneath it and powder of the same color in the remaining slots to get 7 concrete

**Comment by Kyoris** [comment]
yeah i don't want to get an uneven amount of concrete
maybe 8 concrete and 1 ice would be better

**Comment by WhitPlayzYT** [comment]
Or maybe 8 powder and a water bucket while consuming the bucket and not just the water to make it a bit more expensive

**Comment by Kyoris** [comment]
you do know that concrete isn't and shouldn't be expensive right

**Comment by WhitPlayzYT** [comment]
Or just fix the damn server

**Comment by JuliusCaesar12** [comment]
You could always set the recipe of Concrete itself to the one of Concrete Powder

**Comment by HaydenTownley** [comment]
This is due to lag on the server not updating the water on the server. A way to get around this is place the blocks and leave them and update them from time to time and evntually they will update its a pain but a temporary soultion for the problem.

**Comment by OyoKenyon** [comment]
The reason I didn't want it to be any more complicated than placing it in the crafting table is cause solidifying concrete is normally very simple. Adding a requirement for ice would make it a lot more difficult to make than it is normally for really no reason.

**Comment by KarlOfDuty** [comment]
The issue should be fixed anyway so this is not needed.
