### ISSUE TITLE
[Feature] Reduce kit pvp cooldown + add new kits

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#442]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't do /kit pvp because game thinks I'm a noob for dieing within 2 minutes. Also I am noob with sword so I would maybe like an archer kit or an axe kit.

**Describe the solution you'd like**
1 minute or less cooldown for /kit pvp, additonally maybe new kits not being op

**Additional context**
This issue has come up often in Hub and seems popular.

**Comment by JuliusCaesar12** [comment]
*clap* *clap* Yes, I don't like it when I die and I can't get the kit because of this. I found a solution by doing the kit thing and storing them in the e-chest.
