### ISSUE TITLE
Unban books

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#443]
We should be able to write books again, maybe with a character limit to avoid duping

**Comment by WhitPlayzYT** [comment]
Or just make a plugin that only allows normal symbols, num pad symbols, aphabetical symbols, and numbers. (If thats possible ofc)

**Comment by Ultil0l** [comment]
Unban books.

**Comment by brayjamin** [comment]
Because Minecraft 1.14 supports dynamic book configuration using the lectern, this should be possible.
