### ISSUE TITLE
[Mechanic] Nation merge

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#446]
**Is your feature request related to a problem? Please describe.**
Sometimes theres two or three "germanies" or "Brazils" but sometimes they're able to put down their differences and reunite, however they'll both lose the nation gold creation cost and the towns in the nation

**Describe the solution you'd like**
two commands /nation merge (nation) and /nation merge accept (nation)
person doing /nation merge will lose their nation and all towns join the nation, they will also get 50% of nation creation cost back (512 gold) (maybe higher?)

**Additional context**
Feedback below

**Comment by KarlOfDuty** [comment]
Put it on the towny repo, not ours.

**Comment by Pengun78** [comment]
Peepeepoopoo

**Comment by Pengun78** [comment]
Epic idea
