### ISSUE TITLE
[complaint]Mod is not obiective.

### ISSUE THREAD

**Issue by Awers97** [EarthMC/Issue-Tracker#447]
I got warning for sending message 3 times "mod please cut their balls of befoe they spread" because i was annoyed about the stupid spam on chat and then i got muted for 3H for that when its my first warning but other players who spammed did not get muted the mod name is Sky somethinf and he dont really deserve to have mod when he acts like that.

**Comment by BowShot118** [comment]
Welcome to EarthMC my friend

**Comment by Kyoris** [comment]
wait
i think i've saw the guy
his name is ssky smth
he somehow had fly in the queue lobby
also spammed player ids before leaving in a bit
probs hacked client

**Comment by Awers97** [comment]
And he is mod and muted me for that shit fcking cunt kid should not be admin but Fix is so taken of server that he cant hire normal people for mod. The requirements should be higher and the mods/admins should act normally not fcking muting and kicking for shit.

**Comment by Awers97** [comment]
Fix will propably not read this and will not do anything with his staff crew

**Comment by KarlOfDuty** [comment]
> Behave yourself, @Awers97 . 

I don't know who you are talking about as I don't think we have any mod by that name. In any case, muting for spam or toxicity is what the mods are supposed to do so I don't see any issue here.

**Comment by Awers97** [comment]
I wasnt Toxic Karl and i didnt spam i sended it 3 times and i stopped other guys who spammed F didnt get muted and they spammed F cause some one wrote lets spam f at 17:34

**Comment by Awers97** [comment]
Player should not be allowed to response on tickets as you have nothing to say in my case

**Comment by BowShot118** [comment]
Epic This man doesn't understand just because someone else is breaking the rules, it doesn't mean he can

**Comment by Pengun78** [comment]
He means Skynet, its that bot thing or something, sometimes its says u get warned by Skynet while its just a mod doing it

**Comment by Awers97** [comment]
I didnt break the rules learn to read.....

Skynet is bot? i didnt know that

**Comment by Awers97** [comment]
Or go back to school amoebas

**Comment by Awers97** [comment]
This topic is closed anyway as my mute on this server expired

**Comment by Awers97** [comment]
Sending message 3 times is not spam learn the rules or ask school to move you back to first grade Bow Shot

**Comment by FutureCW** [comment]
Lmao saying something 3 times in a row is spam ye dumbass

**Comment by Awers97** [comment]
This topic is closed dumb ass learn to read or ask your parent for some home teaching kid

**Comment by FutureCW** [comment]
You're like 9 you shouldn't be swearing at your age.

**Comment by Awers97** [comment]
And you know exactly who i am and how old i am kid? I assume age from people's act and many here are kids under 18 cause Minecraft have less adult community of all games(i guess) easy to say something about someone when you dont know him when you dont have arguments.

**Comment by Awers97** [comment]
The topic is closed you need attention? Go to your parents
