### ISSUE TITLE
[Feature] War Plugin/War Is Seriously Needed

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#448]
Well, this is something most of the community would like, war. War has been needed for a long time now. The thing that spiked my interest enough to make a github post was the fact that KaiserWilhelm_2 is leaving EMC in turn for another smaller server. He has donated the 40$ donor rank and said he would've donated again, before donations were turned off. He was insanely active and has gotten 850 in a single month. He states the reasoning is that not only do Karl and Fix not respond to things the community wants, but that there has been no effort by the admins and the staff to try and en-state a war plugin. Granted this is only one case, but the community needs a war plugin, not only do most of us want some sort of war plugin, but as of now there is no way to fight a proper conflict. And geopolitics is about war.

A way to introduce this with towny (with limited modifications) is to make it so when you do the command to declare war it automatically turns pvp on in all towns in the nation and also allows you to use TNT for temporary explosions (like on the Classic war days). It would also make it so you may not leave a nation at war until 2-3 days after its declared so as not to just leave because you are losing. It would also be so that once you peace out (by commands) you may not declare war on the same person until 1-2 weeks after. It could also be incorporated where your allies automatically join the war if you declare war so as to incentivize not forming alliances with everyone so you can't practically tp all over the world. Personally I believe this is the best system towny can offer. But the much preferable option is to have a re-vamp to towny to allow for in depth wars, peaces, alliances, and the way wars are won. But until a re-vamped version to towny is put out (ahem creator) this is the best option for keeping EMC active.

**Comment by Pengun78** [comment]
We need a feature to annex lands

**Comment by alekb1** [comment]
^ badly

**Comment by Ultil0l** [comment]
Creator is gone :crab:

**Comment by watergod1234** [comment]
I have a similar proposal in #444. The admins have said numerous times that they will not be putting resources toward developing a war plugin (creator is doing it independently I believe). My proposition  doesn’t require any development work. Check it out.
