### ISSUE TITLE
My sign shop isn't working or any other signs i create. All other players seem to be fine

### ISSUE THREAD

**Issue by PreciselyBaked** [EarthMC/Issue-Tracker#449]
**Server**
TerraNova

**Describe the bug**
My signs in my shop don't activate for other players, the shops next to them all work fine.
If I set up a sign for example in my own town it still doesn't work.
Shiraz looked at this and suggested I post here.

**To Reproduce**
1. Go to 'X32228 Y66 Z7305'
2. Click on 'Any signs in the shop'

**Expected behavior**
Signs don't activate for sales

Thank you
Precise

**Comment by PreciselyBaked** [comment]
Also the shop used to work fine.

**Comment by PreciselyBaked** [comment]
Still the same, tried resetting signs.

**Comment by PreciselyBaked** [comment]
@KarlOfDuty

**Comment by PreciselyBaked** [comment]
Dude, theres a new shop just opened up next to mine and all their signs work, why is it only mine that never worked again?

**Comment by NeonKrby** [comment]
redo your signs then

**Comment by PreciselyBaked** [comment]
I've have man, I've tried putting new ones up in my own town aswell. It seems to be an issue only for me. Like signs have been disabled for me.

**Comment by PreciselyBaked** [comment]
Still no change

**Comment by PreciselyBaked** [comment]
@fix This is disappointing man, new players who havn't donated come in and make sign shops and yet my old one doesn't work anymore and any other signs I place anywhere.

**Comment by gabbobler** [comment]
Same for me

**Comment by KarlOfDuty** [comment]
What is your in-game name?

**Comment by PreciselyBaked** [comment]
PreciselyBaked. Thanks for the response man.

**Comment by KarlOfDuty** [comment]
Well, I have it too so I don't need to check out your signs anymore anyway.

**Comment by PreciselyBaked** [comment]
So what's the verdict bro?

**Comment by KarlOfDuty** [comment]
I don't know, it is being investigated.

**Comment by sier** [comment]
I have this issue as well.

Already made signs are working, but since the update/takedown it is not possible to create new ones.

**Comment by gabbobler** [comment]
Have you guys fixed this yet? Some countries's economies are getting kinda screwed

**Comment by KarlOfDuty** [comment]
no, we don't think this is fixable without an update from the dev

**Comment by WhitPlayzYT** [comment]
Im having the same issue it seems to just be new signs that are bugging cus old ones still work

**Comment by PreciselyBaked** [comment]
Yea Whit that's true. Even my old signs dont work though. I think signs placed after a certain date like end of Jan/start of Feb have been disabled as well as any new ones.

**Comment by PreciselyBaked** [comment]
@karlofduty Hey bro can you change the title of this bug? 'All other players seem to be fine'  isn't correct.

**Comment by WhitPlayzYT** [comment]
@PreciselyBaked you made  the issue so u can change the name urself

**Comment by DasCodes** [comment]
Are you still facing this issue? @PreciselyBaked

**Comment by Lagann311** [comment]
@DasCodes I have the same issue. Opened a big report 6 days ago

**Comment by DasCodes** [comment]
This should be fixed. if not, please reopen.
