### ISSUE TITLE
[Feature] Helper Rank 

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/Issue-Tracker#450]
**The Video**
As the Youtube trailer has surpassed 1 million views quite awhile ago and EMC is gaining new players faster than ever. A lot of the new players are toxic and the queue is not a very great place in the EMC community. The bots on the discord also seem to be a big issue as it takes up the time of  

**Solution**
As the community keeps on growing i believe that a new category of staff should be created to help deal with the influx of toxic players in the queue. The Helper rank wouldn't have any real perms in Terra Nova or Classic themselves as that would be left for the mods but they could help in the queue and discord. It would free up the rest of the staff team to deal with bigger issues like griefs or other stuff going on in the main server rather than having to focus on everything. 

**Proof we need it**
![image](https://user-images.githubusercontent.com/45209878/55433200-d332f980-5562-11e9-882b-1016b71c07dd.png)
![image](https://user-images.githubusercontent.com/45209878/55433940-720c2580-5564-11e9-89ca-2ed048a9d00c.png)
![image](https://user-images.githubusercontent.com/45209878/55433960-7f291480-5564-11e9-8e77-f212e5d85a2a.png)

**Comment by FutureCW** [comment]
What perms would they have? Mute or warns or anything?

**Comment by NeonKrby** [comment]
Up to the staff team but i was thinking the ability to warn tempmute and kick from both the queue and discord

**Comment by NeonKrby** [comment]
And probably modify roles on discord

**Comment by FutureCW** [comment]
I like that idea then.

**Comment by Pengun78** [comment]
Lol every player will appeal for it

**Comment by NeonKrby** [comment]
So? Everybody applies for mod lmao

**Comment by Kyoris** [comment]
should help with shit having more people able to mute and kick toxic people. You'll have to look for older players that can be trusted that is.

**Comment by watergod1234** [comment]
What? The examples aren't even that bad.

**Comment by NeonKrby** [comment]
Yeah they arent but they were the best i could get at the time, feel free to post some more toxic material here.

**Comment by Kyoris** [comment]
Just think of the times when a retarded 8yo come online to spam and no mods are online

**Comment by NeonKrby** [comment]
![image](https://user-images.githubusercontent.com/45209878/55505668-9c6fe880-5621-11e9-8bf9-b07668b9ac45.png)

**Comment by WhitPlayzYT** [comment]
Completely unrelated but 1. what texture pack is that? 2. Is that prismerine? If it is Im jealous

**Comment by Kyoris** [comment]
That's atop the spawn and it's like pure bdcraft or smth I forgot

**Comment by NeonKrby** [comment]
^

**Comment by Aitonater** [comment]
This is my opinion on the main issues with new players needing help.
1. No one reads the Fix book.
2. No one goes to the earthmc website.

The questions that bombard chat: how do I tp? How do I join a nation/town? How much does a town/nation cost? Where do I view dyn map? Etc etc...
Now most of these questions would be solved with a quick look at the discord or a quick google however it is in our nature as people to be lazy sadly.

I think it would make the most sense to:
 A. Make a Earthmc video tutorial or 
B. Pack as much information and tutorials into the server queue area as possible.
If someone has to wait 10 to 20 minutes in the queue and the information they need is right in front of them I feel like it might reduce the number of "noob questions" that spam chat.

**Comment by NeonKrby** [comment]
Aitonater this isn't really about helping new players its more about trying to end limit toxicity and free the mods up to help with other shit

**Comment by Aitonater** [comment]
Fair, it makes sense. You also then have the issue of mods then having to micro manage the decisions of helpers if they are appealed potentially.

**Comment by IJustGotKarma** [comment]
This is epic

**Comment by NeonKrby** [comment]
![image](https://user-images.githubusercontent.com/45209878/55882825-2a445a00-5b73-11e9-9e44-c1bb480b3348.png)

**Comment by NeonKrby** [comment]
![image](https://user-images.githubusercontent.com/45209878/55885451-f3247780-5b77-11e9-9459-1d5ad850360a.png)
bot spam

**Comment by shirazmatas** [comment]
Good idea krby, keep it up. I solemnly agree with this.

**Comment by NeonKrby** [comment]
![image](https://user-images.githubusercontent.com/45209878/56094566-912f7f00-5ea3-11e9-8061-bbc9f8f7467e.png)
![toxic](https://user-images.githubusercontent.com/45209878/56094570-9987ba00-5ea3-11e9-864a-8abe08ebe8e2.PNG)

**Comment by NeonKrby** [comment]
sad that everyone stopped talking about it

**Comment by FutureLemon** [comment]
> sad that everyone stopped talking about it

I think everyone can agree it would help it's up to the staff team now I think.

**Comment by KarlOfDuty** [comment]
We will just be adding more normal mods instead.
