### ISSUE TITLE
Add common information/tutorials to the server queue area.

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#452]
**Add common information/explanations/tutorials to the server queue area.** 

- Display all the towny commands.
- Show nation prices and town prices.
- How to create a town.
- What tp commands are available.
- How to join a town.
- How to find yourself and view the     dynamic map.
- etc...

I think there should be signs all around the queue area or dedicated rooms telling players everything they could possibly need to know.

Despite having links to the website and discord and reddit and having the fix book for new players. It is in our nature to be lazy, people still do not read the fix book.

I think introducing this would significantly reduce the number of people spamming chat with very easily answerable questions.

  What I said in response to another issue which supported the idea of a helper rank alluded to this post:
"The questions that bombard chat: how do I tp? How do I join a nation/town? How much does a town/nation cost? Where do I view dyn map? Etc etc...
Now most of these questions would be solved with a quick look at the discord or a quick google however it is in our nature as people to be lazy sadly.

I think it would make the most sense to:
 A. Make a Earthmc video tutorial or 
B. Pack as much information and tutorials into the server queue area as possible.
If someone has to wait 10 to 20 minutes in the queue and the information they need is right in front of them I feel like it might reduce the number of "noob questions" that spam chat."

Any suggestions welcome, please keep it relevant.

**Comment by Aitonater** [comment]
There is too much emphasis and reliance on players going to the website and/or discord. The bottom line is despite several prompts to do so people don't and have no intention. It's better to have as much on the server as possible because its the closest point of contact that requires the least thought from players.

**Comment by shirazmatas** [comment]
Very good to add! @FixTheAdmin @KarlOfDuty @PoppyK @1212ra

**Comment by FixTheAdmin** [comment]
Thanks for the feedback. I agree with your points. The hub will be rebuilt from scratch with a better tutorial area.

**Comment by Aitonater** [comment]
Of all the "new mods" that have been created very few are active and now even less original mods are active on the server to help people too.

**Comment by KarlOfDuty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New hub](https://trello.com/c/YclAfNmf/24-new-hub)

**Comment by KarlOfDuty** [comment]
Fixed in record time.
