### ISSUE TITLE
Ender Chests in Que wont work

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#453]
**Server**
Earthmc que

**Describe the bug**
It wont let me open the ender chests in the que, and i need to deposit my emeralds and my axe earned from killing Evokers

**To Reproduce**
1. Go to ProvingUnique’s castle at spawn
2. Click on the ender chest
3. It wont let normal players open it

**Expected**
I used to be able to open the ender chests and store stuff 

**Additional context**
I wanna store my stuff, but I cant and it makes me upset.

**Comment by KarlOfDuty** [comment]
This can not be fixed at this time.

**Comment by WhitPlayzYT** [comment]
I believe this is because the queue is technically on the same server as the main server so your ender chest would be the same in both worlds so they disabled ender chests in queue to prevent people from getting items from either world/server to the other
