### ISSUE TITLE
[BUG] Gold Disapeared

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#454]
Terra Nova

Basically I had 18G in my inventory then I /pay [user] 0 spammed then got kicked for spamming, then when I reloged the gold was gone (at about 6:00PM EST 4/7/19 if the gold could be refunded)

**To Reproduce**
1. Put gold in your inventory
2. /pay spam 0 someone
3. Get kicked for spamming
4. See gold go missing
**Expected behavior**
Gold to be removed after getting kicked

**Comment by shirazmatas** [comment]
After FutureLemon and Neonkrby tested it, they did not lose their gold.
