### ISSUE TITLE
/discord link command bug and cant said from discord

### ISSUE THREAD

**Issue by SOMEONESTEALMYNAME** [EarthMC/Issue-Tracker#457]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by SOMEONESTEALMYNAME** [comment]
when you do /discord link command its will same at /discord that give a server link

**Comment by SOMEONESTEALMYNAME** [comment]
Fixed do /discordsrv:discord link

**Comment by DasCodes** [comment]
This has been fixed.
