### ISSUE TITLE
[Feature] Private Chests

### ISSUE THREAD

**Issue by 3meraldK2** [EarthMC/Issue-Tracker#458]
**Is your feature request related to a problem? Please describe.**
There is a possibility that your buddy / councillor of your city can steal items from your chest. That can make you angry etc. because you lose ur items

**Describe the solution you'd like**
You should install plugin or make plugin on private chests. 

**Additional context**
Please add this because it's important because of safety of players!

**Comment by watergod1234** [comment]
Or you could just not give people councilor that you don’t trust. Problem solved.

**Comment by shirazmatas** [comment]
Use the emojis to show your opinion about this issue (thumbs up and thumbs down).

**Comment by sier** [comment]
This is one of the main reasons many players create new towns.
Why should I trust someone else with complete authority to all of my belongings?

Making chests private and allowing for a grace period during an eviction would solve these problems greatly, as well as allow multiple people to live in the same building (high rise apartments for example) without having to worry about new neighbours stealing their stuff.

**Comment by watergod1234** [comment]
Having private chests in the wilderness would mean they could never be opened despite not having it claimed. Plus if a player who owned a private chest moved out of a town then the mayor would be stuck with it unable to move or destroy it.

**Comment by ImperialFishy** [comment]
What if private chests can only be created on owned and inn plots? Just thinking outloud not sure if thats possible.

**Comment by sier** [comment]
> Having private chests in the wilderness would mean they could never be opened despite not having it claimed. Plus if a player who owned a private chest moved out of a town then the mayor would be stuck with it unable to move or destroy it.

First of all, no one said you should be able to place them in wilderness.
Secondly, if a mayor evicts someone that would obviously remove the chest protection.

**Comment by xParadoxical69** [comment]
@sier If mayor evicting someone would get that previously locked chest, than some ppl would just evict some players if they would see their private chests in the town - just to get these items from this chest.
I think the private chests should be still private after being evicted, and then they should be still openable.

**Comment by Toadally** [comment]
Protect your stuff using claims. If private chests are added, they should only work within towns and in your own chunks.

**Comment by KarlOfDuty** [comment]
We will not be adding additional protection plugins at this time.
