### ISSUE TITLE
Kicking residents.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#459]
Kicking players. It's a feature every mayor knows about, but what if nation leaders can kick anyone in a nation except mayors.

**Comment by NeonKrby** [comment]
Would have to be brought up in towny shit

**Comment by shirazmatas** [comment]
What Neonkrby said. To allow nation leaders to kick town members it would have to be fixed by towny (even then it doesnt really make sense). If you feel enthusiastic about this you can write a ticket in their github
