### ISSUE TITLE
[BUG] [EarthMC]

### ISSUE THREAD

**Issue by RerTee** [EarthMC/Issue-Tracker#460]
When i`d like to join server it gave me an error "io.netty.channel.abstractchannel$annotatedconnectexception" how can i fix it?

**Comment by RerTee** [comment]
When i`d like to join server it gave me an error "io.netty.channel.abstractchannel$annotatedconnectexception" how can i fix it?

**Comment by RerTee** [comment]
![image](https://user-images.githubusercontent.com/49551315/56021800-03248e80-5d13-11e9-8c5f-ec87710c8bee.png

**Comment by WhitPlayzYT** [comment]
its not a bug the queue server is down

**Comment by RerTee** [comment]
Ohh 
Ok 
Thank you
