### ISSUE TITLE
/ignore command is no longer working

### ISSUE THREAD

**Issue by sier** [EarthMC/Issue-Tracker#461]
**Server**
EMC Main

**Describe the bug**
Before the change in chat system it was possible to /ignore players who were annoying, this is no longer possible for some reason and instead throws an "insufficient permissions" error.

**To Reproduce**
1. Open chat
2. try to ignore a player by entering /ignore <name>
3. See error

**Expected behavior**
Ignoring a player in global and private messaging chat on the servr.

**Screenshots**
N/A

**Additional context**
This has become a rather annoying problem as it's no longer possible to mute players who spam or threaten you via messages.

**Comment by KarlOfDuty** [comment]
Should be fixed now.
