### ISSUE TITLE
Suggestion: More members in current town.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#462]
A lot of new people have been joining EMC and probably will keep joining for some time and that brings problems with it. (eg: 1 man nationless towns) In order to prevent such things they changed the /t new price from 32 to 64gold per new town. This was a great idea and I've personally seen a decline in worthless towns being created. But what if to counter this current flow of of new players we higher the amount of maximum members in a town from 50 to 75 or something like that?

**Comment by KarlOfDuty** [comment]
I don't think all the members in a town that big would be active anyway, I think 50 is big enough.
