### ISSUE TITLE
[BUG] [WORLD] 

### ISSUE THREAD

**Issue by Huggze** [EarthMC/Issue-Tracker#463]
**Towny**

**Unclaiming plots & making new**
So i had my Town in South america for a while and then i took and unclaimed the plots i owned and moved to India and now i can't make new plot because i need to deposit Money into the Town but i need to do that on an owned plot and i have none of owned plots, and i try to leave the Town i need to set an other person Mayor, and its only me left in the Town.  

**To Reproduce**
To help me with this you simply do /t delete Arcton (My Town). then my Town will be deleted and i can create a new one.

**Screenshots**
![2019-04-14_17 54 23](https://user-images.githubusercontent.com/49616928/56095555-71697c80-5ede-11e9-8626-562218388846.png)

![2019-04-14_17 55 37](https://user-images.githubusercontent.com/49616928/56095568-8f36e180-5ede-11e9-8bc7-4656f3857a7e.png)

And i own zero of owned plots. -Huggze

**Comment by KarlOfDuty** [comment]
You can /pay t-arcton if you need to add money to it, otherwise you could just delete the town yourself using /t delete.
