### ISSUE TITLE
[WORLD] Oceans around Fiji

### ISSUE THREAD

**Issue by SuvaFiji** [EarthMC/Issue-Tracker#465]
**Describe the issue**
I'd like the waters surrounding Fiji to be turned warm, the reason being because it looks nicer and the real Fiji is surrounded by beautiful warm oceans too.

**Coordinates**
32700(X), 3100(Z) (No Y)

**Screenshots**
https://gyazo.com/7983301a75d29dd75ab2bb1f79138b28 It'd be awesome if we could have warm water around these parts and surrounding islands.

**Comment by dalicor** [comment]
2 years late big man :(

**Comment by KarlOfDuty** [comment]
Yeah we dont really do world editing on the server anymore.
