### ISSUE TITLE
Full list of server changes to improve performance

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#466]
Now I understand why changes are made to the server to aid performance, reduce stress and the need for resets.

I am in no way contesting the necessity of these performance enhancing measures. I know they have to be done.

What I am proposing is that a list of these changes are available at all times 
-(e.g. Mob AI being turned off, entity limits per chunk, spawners being turned off altogether, mobs being turned off altogether, the really slow tickrate (tps))-
 for everyone to see because when changes are made to enhance performance something along the lines of this happens each time:

1. Change is made to free up resources for the server.

2. Mods are made aware or are not (doesn't matter really the outcome is the same).

3. 10 Tickets get made everyday on the discord by players who don't know about these changes and think they are unintentional bugs.

My point is if this information was readily available it would result in a lot less work for mods and a lot less tickets. 

It would also mean that players are a lot more informed and stop rumours like "the anti xray causes the lag". 

The vast majority of the time, players don't know what has been disabled or what has caused the lag a particular time (lag is a different issue for the most part which doesnt exist anymore but it ties into this). Players are just told the conclusion they have arrived at is wrong, and its totally unessecary.

A lot of the time on the server it seems the mods are just as clueless as players on certain issues and changes but are left to deal with players and try and help them when they themselves don't know the whole picture.

Again this is not a dig at the server or its staff its just a suggestion which I think would make developers, players and mods lives more easy.

Thanks

**Comment by KarlOfDuty** [comment]
We change the performance settings many times a day so we can't keep an active list of them without having to slow down server development to write docs.

I do try to always make changelogs when we change a lot of stuff at a time but that will have to do for now.

**Comment by Aitonater** [comment]
You wouldnt need to change any logs just make a channel on discord. Seems very premature and unfair to close this before even letting people talk about it?

**Comment by Aitonater** [comment]
Just a server with pinned changes it would take a minute max. The same way you use the announcements but with gameplay specific stuff.

**Comment by KarlOfDuty** [comment]
Maybe I misunderstood your issue but you asked us to write about all changes that are made to the server no matter how small? We will not be doing that as I said because we change things literally all day, and it would just be us typing in discord basically all the time.

**Comment by Aitonater** [comment]
Not all changes just fundamental changes to gameplay like e.g. chunk entity limits it would take you 2 seconds. You end up creating more work for yourselves and the mods by not making this information public when they get 100 tickets from players thinking they are bugs.

**Comment by KarlOfDuty** [comment]
If you call that change fundamental then yes, we would have to list basically all changes. We change small things like that all the time, several times a day sometimes.

**Comment by Aitonater** [comment]
Things like trees not growing, concrete, redstone not working because of the tps and mods get asked about this all the time.

**Comment by KarlOfDuty** [comment]
Yes, we change that back and forth like every day to measure the effects.

**Comment by Aitonater** [comment]
You dont need to state the tick rate just say in discord the tickrate changes sometimes to improve performance so if youre trees arents growing this is why etc its really not that difficult you dont need to go into specifics. Saying blaze spawners will turn off on a discord post when the server is full is not an arduous difficult task.

**Comment by Aitonater** [comment]
I understand you don't want to do this but can you at the very least keep the ticket open and let people talk about it before you decide its too much work.

**Comment by KarlOfDuty** [comment]
People can still discuss it, it being closed just means we have already answered it.

**Comment by Aitonater** [comment]
In the space of time you've taken talking to me about it you could have made a channel on discord and and a very general list of the changes.

**Comment by KarlOfDuty** [comment]
No? We have over 50 plugins all of which have between 10-500 different changes?

**Comment by Aitonater** [comment]
Are those all changes which players will see?

**Comment by KarlOfDuty** [comment]
Several of the plugins are only used by staff but the vast majority are for players, yes.

**Comment by Aitonater** [comment]
Something like this would take too much time? Just general useful information for players?
- we mess with the tps (ticks per second) sometimes on the server so if your concrete, redstone or saplings are not working
- mobs will not spawn while the server is full
- blaze ai is turned off
- blazes spawners will not spawn while the server is full

**Comment by Aitonater** [comment]
I didnt ask which are used by staff or players or for you to keep an active log of plugin changes. I'm only asking that you offer general information for fundamental gameplay changes which players are likely to encounter while playing. Not ever tiny change just important ones.

**Comment by KarlOfDuty** [comment]
Yes, we post stuff like that in announcements, but sometimes we do not know all of the effects or remember every detail we have changed.

**Comment by Aitonater** [comment]
You do not post stuff like that in the announcements you post in the announcements when the server has crashed. Not one of the things I have mentioned about spawners or tps being changed or entity limits per chunk has ever made it into announcements. Its just not true.

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/56235356-90574280-6087-11e9-8d73-3d450bc0f8f4.png)

Here is the latest changelog, it specifically mentions the concrete issue you mentioned above.

**Comment by Aitonater** [comment]
You mention concrete which is one of many things. But nothing about any of the other changes to gameplay like the entity limit per chunk or the changes to spawners. It wouldnt be hard to have a dedicated channel for changelogs like this. You post changelogs at the most once a month and they lack a lot of information regarding other changes.

**Comment by KarlOfDuty** [comment]
Indeed, I don't always remember to post changelogs but I do so most of the time, at least for the towny server.

**Comment by Aitonater** [comment]
Could you please at the very very least if its not too much of an ask make a post about the spawners, entity limit and mob spawning as mods get asked a lot. This may be common knowledge among the mods but it is not to players.

**Comment by KarlOfDuty** [comment]
I can but the information will likely be outdated within a day.

**Comment by Aitonater** [comment]
Thank you, jesus christ

**Comment by KarlOfDuty** [comment]
You're welcome, my child
