### ISSUE TITLE
Niger has backdoored/spawned in/unobtainable items

### ISSUE THREAD

**Issue by Lemonlicious** [EarthMC/Issue-Tracker#467]
Terra Nova

The nation of Niger has unobtainable items (at least on the map) and has admitted (albeit proudly) to having received them from an illegitimate source.

Look at their inventories

For them to not have unobtainable items?

Check chat logs in the discord for further evidence
Several witnesses including Shado, myself, Tyce, etc.

The major item is totems of undying.

**Comment by watergod1234** [comment]
Christ, you sure are dense.

**Comment by FutureCW** [comment]
Are you talking about the queue server? Niger doesn’t have totems of undying but we do have 2 tridents that were grinded from drowned

**Comment by cloudy1021** [comment]
I think he is talking about the pork we carry on our offhand. Maybe he thinks that is a totem of undying.... kek

**Comment by FutureCW** [comment]
Oh I forgot to add that we are all Sly alts

**Comment by cloudy1021** [comment]
( ͡° ͜ʖ ͡°)

**Comment by KarlOfDuty** [comment]
What is this about?

**Comment by cloudy1021** [comment]
He thinks we have totems of undying

**Comment by FutureLemon** [comment]
Niger man bad!

**Comment by NeonKrby** [comment]
niger man bad!
Qin Man Bad!
Denmark Man Bad!
Any nation that kills you is bad when you clearly deserve it!

**Comment by gabbobler** [comment]
if you dont shut yo skin tone chicken bone google chrome no homo flip phone disowned ice cream cone garden gnome extra chromosome metronome dimmadome genome full blown monochrome student loan indiana jones over grown flint stone X and Y Chromosome friend zome sylvester stalone sierra leone auto zone friend zone professionally seen silver patrone big headed ass Up

**Comment by watergod1234** [comment]
> Oh I forgot to add that we are all Sly alts

I cannot believe you just exposed us all.

**Comment by FutureCW** [comment]
I’m sorry daddy watergod

**Comment by FutureCW** [comment]
Also Karl that dude saw porkchops in some Niger citizens off-hands and thought they were totems of undying

**Comment by BowShot118** [comment]
Someone tell this man this isn't 2b2t

**Comment by Magenent** [comment]
![2019-04-18_00 28 02](https://user-images.githubusercontent.com/45110731/56344050-54001100-6171-11e9-8146-f0025648c11a.png)

**Comment by watergod1234** [comment]
> Christ, you sure are dense.

>![](https://user-images.githubusercontent.com/45110731/56344050-54001100-6171-11e9-8146-f0025648c11a.png)

Wait

**Comment by WhitPlayzYT** [comment]
Youre just salty and jealous about you not having any totems

**Comment by xParadoxical69** [comment]
@WhitPlayzYT 
>salty and jealous
If totems are unobtainable through the normal gameplay on earthmc, then these should be removed from your inventories, that's the fair way :man_shrugging:

**Comment by KarlOfDuty** [comment]
Its apparently an award from one of the build competitions.
