### ISSUE TITLE
How Will Players Get 1.14 Items?

### ISSUE THREAD

**Issue by EchoOcelot** [EarthMC/Issue-Tracker#468]
1.14 has many new additions to Minecraft, but a good amount of them aren’t obtainable on this earth map. These additions include: bamboo, pandas, bells, new blue, white, and black flowers, scaffolding (crafted with bamboo), sweet berries/sweet berry bushes, pillagers, and other things.

Many additions in this update are things that would make the game much harder and boring to play without. 1.14 releases April 23rd, and while it may take a bit for Spigot and its plugins to update, I am curious if the staff have any planned ways to introduce these items to the game. I know that I and many other players are excited for this update, and it wouldn’t be fun to have half of the new items be just unobtainable due to the limits of the map.

**Comment by Kyoris** [comment]
Maybe custom built bamboo forests in China, berry bushes scattered around Scandinavia, Russia, and East Europe, while pandas and foxes spawn around their respective food sources (when mob spawning is on ofc).
Wither roses could be made to spawn in the nether, and the other flowers can be put in flat plains areas and lightly forested areas.
It's might not exactly work but just gonna throw this out idea out here

**Comment by BowShot118** [comment]
Just get Niger to spawn them in

**Comment by EchoOcelot** [comment]
> Maybe custom built bamboo forests in China, berry bushes scattered around Scandinavia, Russia, and East Europe, while pandas and foxes spawn around their respective food sources (when mob spawning is on ofc).
> Wither roses could be made to spawn in the nether, and the other flowers can be put in flat plains areas and lightly forested areas.
> It's might not exactly work but just gonna throw this idea out here

That would work, let’s see what the staff say

**Comment by Pengun78** [comment]
Well emc would have to make a recipe for the bell as there isnt one and bells are epic

**Comment by Kyoris** [comment]
2 stone slabs on the top corners, a stick in the top center, gold nugs or iron in the remaining slots minus the bottom center (depending on how expensive you want it to be)
Drawn out in text:
S - stone, \ - stick, M - metal
S   \   S
M M M
M      M

**Comment by WhitPlayzYT** [comment]
I think a bell recipe should be
G- Gold / - Stick W - Wooden Slab S - Stone N  - Gold Nugget
/  W  /
/  G  /
S N S

**Comment by WhitPlayzYT** [comment]
Just realized one of the villagers (I think weopnsmith or blacksmith) sells bells

**Comment by KarlOfDuty** [comment]
We will see about this whenever the server will be updated. 1.14 has some large performance issues still so we may need to wait for 1.15.
