### ISSUE TITLE
Regarding the queue.

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#469]
Regarding the queue.

Old players should receive a free veteran status. This is only given if they were here within the first month of the server.

That will be all.

**Comment by BowShot118** [comment]
First Month of TN? ehhhhh

Maybe once TN was announced as a cut off point

**Comment by Kyoris** [comment]
maybe depending on total play time?

**Comment by BowShot118** [comment]
I feel like people who played the first month of TN & played classic, with over x amount of playtime on either, should be yeah

**Comment by Ultil0l** [comment]
it would make priority worthless tho

**Comment by Kyoris** [comment]
being just over a week late hurts me

**Comment by BunbunToast** [comment]
> it would make priority worthless tho

Exactly.

**Comment by KarlOfDuty** [comment]
Ok, since me, fix, shiraz and 1212ra are the only ones still playing since the first month of the server I guess thats fine.

**Comment by RangerMK01** [comment]
roasted
