### ISSUE TITLE
Animals rare in Madagascar.  

### ISSUE THREAD

**Issue by PoppyK** [EarthMC/Issue-Tracker#47]
We have no cows at all.  Sheep are rare but we have found two to breed, as well as one pig.  Can anything be done about this?  I know this isn't a bug but yeah.  Thanks, Karl!  *Karl smirks and takes another swig of Red Bull. xD

**Comment by KarlOfDuty** [comment]
There is already an issue open on the animal spawning. We will look into it soon.
