### ISSUE TITLE
Water Glitching to climb walls/escape traps

### ISSUE THREAD

**Issue by Lemonlicious** [EarthMC/Issue-Tracker#470]
Terra Nova

Water Glitching abuse (to escape spawns, scale walls, etc.)

1. Spam a water bucket on a building-blocked area
2. Watch as you magically spider up a wall

You shouldn't be able to climb walls with water, it defeats the point of a nation/town wall.

![2019-04-19_03 15 23](https://user-images.githubusercontent.com/49698084/56398572-e0820080-6251-11e9-8058-a1bf70d75b74.png)

Used to escape a spawntrap and climb our nation walls by Niger.

**Comment by FutureCW** [comment]
You guys just admitted to having a spawn trap and repeatedly killed me which is illegal and are now reporting people for it.

**Comment by watergod1234** [comment]
Hey i'm just being what my title implies. God of water.

**Comment by FutureLemon** [comment]
Imagine reporting people for desperately escaping your toxic spawn traps... Jeez you guys are going far to get them. *facepalm*

**Comment by BowShot118** [comment]
Jesus these guys really do hate you.

**Comment by FutureCW** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/471

**Comment by WhitPlayzYT** [comment]
the only way I could think for fixing this is making you go into adventure mode when you're in towns you don't have perms in

**Comment by Aitonater** [comment]
I've been told by one mod that common mc glitches are allowed and by another that they are not allowed. Its pretty hard to know what is and what's not allowed. Same with using boats to glitch I've been told different things.

**Comment by KarlOfDuty** [comment]
There isnt really a way to fix this.
