### ISSUE TITLE
Don't requeue afk players

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#474]
Right now when people AFK they get kicked to the queue after 15min, but this is really annoying for people in the queue as Priority and Supporters push the others one spot back even if they are AFK. I often see people that can bypass the queue in AFK loops joining and getting kicked to the queue. Is there any way possible to make it so that if you get kicked from the server for AFK'ing that you get kicked out of the whole server and not just to the queue? It just feels unfair for people without a rank that just want to play with an already really long waitline. 

As seen below the person gets kicked every 15minutes and can join really quickly due to his Supporter rank.
![AFK Loop](https://user-images.githubusercontent.com/44688587/56414696-bcdbac00-628b-11e9-9945-e6ff8069b156.jpg)

**Comment by KarlOfDuty** [comment]
Yes, thats what its supposed to be.

**Comment by FutureLemon** [comment]
Any idea when this might get fixed? It honestly is just so annoying.

**Comment by GitMocc** [comment]
I agree with futurelemon on this one, the punishment for being afk should be the same for all players, donator or not

**Comment by WhitPlayzYT** [comment]
i agree with this I went afk one time cus i forgot to log out then when i came back there was a sign saying "dont afk" which a mod probaly put instead of just kicking me from the queue
