### ISSUE TITLE
[BUG] Eggs Don't Work

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#475]
**Server**
TerraNova

**Describe the bug**
When you throw eggs, no matter how many, chickens wont spawn

**To Reproduce**
1. Get eggs
2. Throw them
3. See that 0 chickens spawn

**Expected behavior**
No chickens will spawn

**Comment by KarlOfDuty** [comment]
Mob spawning turns off when the server is under a certain tps number, which is usually atm.
