### ISSUE TITLE
Maybe consider putting emc on hard mode

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#476]
Its been a while since TN was released and I think we should get hard mode. Why? tbh I just want to be able to work my slaves to death for meme potential...

**Comment by BunbunToast** [comment]
I agree entirely.

**Comment by WhitPlayzYT** [comment]
I think it should be on normal

**Comment by WhitPlayzYT** [comment]
/difficulty hard its not hard at all

**Comment by WhitPlayzYT** [comment]
it takes less than 30 seconds to add it either do it or dont

**Comment by KarlOfDuty** [comment]
We will not do this at this time.
