### ISSUE TITLE
[World] Trapped in a Nether portal trap

### ISSUE THREAD

**Issue by Ther999** [EarthMC/Issue-Tracker#477]
Yesterday I went through a Nether portal and I appeared in this other one, which is a trap. I can`t broke the blocks since it´s in claimed land or use the chat. Please help.

**Coordinates**

XYZ: 2806.300 /  65.00000  /  -10648.700

**Screenshots**
![Screenshot_2019-04-19-15-58-33](https://user-images.githubusercontent.com/49780612/56427410-0ba13a00-62bc-11e9-9f10-5d4feaaf50ba.jpg)

**Comment by Kyoris** [comment]
you make a ticket for this

**Comment by Ther999** [comment]
How do you do that? I entered this server two days ago for the first time and I don´t know much yet

**Comment by Kyoris** [comment]
_-new_ on #general in discord

**Comment by Ther999** [comment]
Thanks, I will try it
