### ISSUE TITLE
Add recipe for shulker boxes

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#478]
Shulker boxes would help reduce the massive lag that comes with the storage systems of larger cities, which is why i propose adding a recipe for them, where they cost 4 iron blocks, 4 diamond block, and 1 chest to craft (picture is added)
<img width="249" alt="Skærmbillede 2019-04-19 kl  18 48 26" src="https://user-images.githubusercontent.com/47500274/56434295-4ca54880-62d4-11e9-9580-f07ab4481d3c.png">

**Comment by BowShot118** [comment]
Maybe not diamond blocks, outside of that YES PLEASE ADD SHULKERS I BEG YOU

**Comment by DorienB** [comment]
This could be very usefull and yeah could be made a bid less exspensive to craft.

**Comment by FutureLemon** [comment]
> This could be very usefull and yeah could be made a bid less exspensive to craft.

Diamond's are really easy to get because people sell 32diamonds for 1 gold ingot it really is not an expensive recipe...

**Comment by DorienB** [comment]
> Diamond's are really easy to get because people sell 32diamonds for 1 gold ingot it really is not an expensive recipe...

Yeah but new players would like it cheaper. And as the map gets older diamonds become rarer.

**Comment by alekb1** [comment]
Well it is an endgame item, the most important thing @KarlOfDuty is that we all agree that it should be added in some way

**Comment by Kyoris** [comment]
Instead of diamond blocks maybe emerald blocks? Or perhaps even quartz blocks?

**Comment by FutureCW** [comment]
Shulkers should be hard to craft because it’s an endgame item that new people shouldn’t be able to get a lot of quickly. The recipe needs to be expensive enough to create a market for it

**Comment by Kyoris** [comment]
Maybe 2 magma cream and 2 string along with 4 diamonds in the corners.
Or craft 4 shulker shells with an epearl and some iron and obsidian.

**Comment by WhitPlayzYT** [comment]
> > Diamond's are really easy to get because people sell 32diamonds for 1 gold ingot it really is not an expensive recipe...
> 
> Yeah but new players would like it cheaper. And as the map gets older diamonds become rarer.

You get diamonds from digging with McMMO (Excavation 350+) So they really arent becoming more rare at all

**Comment by Magenent** [comment]
Just enable the end thats the best option imo.

**Comment by alekb1** [comment]
Yes, but until then... We need those shulkers

**Comment by WhitPlayzYT** [comment]
#456 and really that recipe is too cheap cus its literly not even worth 2g

**Comment by EchoOcelot** [comment]
Yeah maybe just a way to craft the shulker shells, and then you can craft the box the normal way

**Comment by BowShot118** [comment]
I mean anything "valuable" gets the price dropped down to like 1g after a week bcs people desperately want money lol

**Comment by DorienB** [comment]
B

**Comment by lemurbeard** [comment]
Maybe the recipe is with 4 GOLD blocks instead of diamond...therefore there is no fear of the price dropping.

**Comment by BowShot118** [comment]
No, that just makes it really expensive. 36g for 1 box??? No lol

**Comment by lemurbeard** [comment]
Sounds fair imo, that's 4 days of voting, 1-2 hours of mining.

**Comment by Kyoris** [comment]
But like basically nobody will use it and it defeats the purpose of fixing lag from chests and shit

**Comment by DorienB** [comment]
> But like basically nobody will use it and it defeats the purpose of fixing lag from chests and shit

People will use it xd. It is very usefull and shulkers are like a coble block with 1 animation. It isn't like a shit with multiple shapes.

**Comment by BowShot118** [comment]
not spending 36g for one.

**Comment by alekb1** [comment]
i would still have some, but not on a large lag reducing scale, so i think a max of 9 g per shulker

**Comment by Toadally** [comment]
Maybe switch it to gold ingots. Or maybe add a recipe for shulker shells instead of the box itself. The shells will then be able to be used to make boxes

**Comment by Snowyy4K** [comment]
Very good idea!

**Comment by Twitchyyy** [comment]
I like that a lot; a recipe for the shells

**Comment by Twitchyyy** [comment]
What if the recipe used Turtle Shells?

**Comment by Cactusinapumpkin** [comment]
I propose 8 enderchest shaped recipe and maybe a special item in middle

**Comment by Cactusinapumpkin** [comment]
AND Chorus Plants

**Comment by NeonKrby** [comment]
until mob spawning is fixed that wont be helpful as echests are more valuable

**Comment by TheRealSomeoneBetter** [comment]
E chests are very inexpensive. You don’t need endermen for pearls

**Comment by Cactusinapumpkin** [comment]
We need a recipe that is easy enough to make a lot but hard for new ppl to get.
Everyone will sell shulker boxes to people who cant make them easily. 
I purpose 8 ender chests with something in the middle or 9 and it can be shapeless. 
Turtle shells do sound appealing but everyone will want a turtle farm and scutes are hard to come by sometimes.

1 scute = 1 shulker shell 

8 end chest = shulker box

**Comment by TheRealSomeoneBetter** [comment]
Shulker boxers sooner than later

**Comment by Cactusinapumpkin** [comment]
^^^

**Comment by ZestyPhallus** [comment]
I just want an anti-combat log plugin

**Comment by Steadlington** [comment]
18 Gold + some diamond blocks + Ender chest for Shulker box. They increase productivity by a large amount if you take a bunch of them mining with you, so that utility should reflect the cost.

**Comment by Virus-3** [comment]
It should cost about 3g per shell. That way they are relatively expensive but easy to get a stack with just 6 hours of mining

**Comment by Cactusinapumpkin** [comment]
1 scute = 1 shulker shell
or
8 end chest = shulker box

**Comment by Steadlington** [comment]
There should be no need to have stacks of shulker boxes, it just isn't right. The proposed cost i put forth in my previous post reflects what the cost should be and why.

**Comment by TheRealSomeoneBetter** [comment]
The point is to decrease lag, first and foremost. 18g for 1 is still too expensive to create an actual dent in that primary issue.

**Comment by Steadlington** [comment]
18g is an insignificant amount of gold for such an item.

**Comment by DasCodes** [comment]
🤔
