### ISSUE TITLE
Madagascar still cheating?

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#479]
I don't think it's just a coincidence that Madagascar has admins in it and just so happens to be one of the most powerful towns.

**Comment by RangerMK01** [comment]
You're right, it's not a coincidence. By having lots of mods and designers in one place, you have dedicated players who work for and love the server in a single area. Not only that, but toxic players are going to avoid that area like the plague so they don't get warned or punished. If you've talked with any of the Madagascar designers or mods, you'd know that most of them are very committed to their work to create a pleasant community over there. So yes, them being mods does benefit them, but they're not cheating.

**Comment by KarlOfDuty** [comment]
:thonk:

**Comment by RangerMK01** [comment]
:wow:
