### ISSUE TITLE
Salvage skill has been broken for a long time

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#480]
The salvage skill does not work, I only get 1 diamond when salvaging items like a diamond chestplate despite my salvage level being 974. With my skill being so high i should get 7 diamonds when salvaging it. This is a setting that was toggled back when you could salvage gold gear, as they made it so you would only get 1 gold ingot for salvaging any gold item to not make it to op. They mods since removed gold salvaging entirely, but the setting is still set to 1 plank/stone/iron/diamond when salvaging. This makes the entire skill useless, so please toggle this back, as there is no longer a need for the low salvage efficiency. I believe you are one of the few that can toggle this @KarlOfDuty

**Comment by KarlOfDuty** [comment]
It is broken in 1.13 and has not been fixed by the mcmmo devs yet. Nothing we can fix.
