### ISSUE TITLE
[Feature] [Mechanic] More planets

### ISSUE THREAD

**Issue by guapathecat** [EarthMC/Issue-Tracker#482]
You know what would make EMC one of the truly greatest servers of all time? More planets. I mean, most of the EMC _clones_ have at least the Moon. I, and probably lots of other people, would enjoy having full fledged space races with our fellow nations, setting up camp on the Moon or Mars and establishing a colony for our great nations, or even just exploring and mining in a different environment. You could like have it cost gold to travel to and fro (not too much, as having a colony on the Moon would take lots of going back and forth), and it could work like how the queue, classic, and hub servers are all separate worlds, and the Moon could be too. So I'm asking you, Karl or Fix or whatever EMC staff is reading this right now, please add more planets, I assure you it will be one of the best moves that we could possibly make.

have a nice day,
~guapathecat of Bolivia-Peru

**Comment by Kyoris** [comment]
could work - only thing is it would take up a lot of server resources
also what ores would be there?

**Comment by guapathecat** [comment]
like there could be the normal ores, but at different frequencies
like maybe on the moon you could get more valuable ores a bit more or something

also i dont think it would take up a lot of server resources, as we already have 3 worlds in the server, 2 with towns, and adding a fourth or fifth wouldn't hurt very much

**Comment by Pengun78** [comment]
All i want is a war plugin

**Comment by Toadally** [comment]
Seems a little resource intensive. Server is already lagging a ton. Top priorities should be to fix lag and an ANTI COMBAT LOG PLUGIN

**Comment by guapathecat** [comment]
yeah this is a suggestion for the future, when the server doesn't lag as much

**Comment by shirazmatas** [comment]
What planets? Moon and Mars maybe?

**Comment by WhitPlayzYT** [comment]
maybe we shouldnt become craft galaxy (the server that pays minors to advertise in emc nation discords which is against the tos) just sayin

**Comment by guapathecat** [comment]
yeah but i still think planets are a cool idea,as earth mc doesnt do anything like that

**Comment by guapathecat** [comment]
> What planets? Moon and Mars maybe?

yeah that would be cool!

**Comment by WhitPlayzYT** [comment]
Maybe they could make the Nether into Mars and the End into the Moon

**Comment by KarlOfDuty** [comment]
We will not be adding more world at this time.
