### ISSUE TITLE
Make coal blocks craftable with charcoal to reduce server lag

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#484]
This is really a minor quality of life improvement, but I've looked into sources for a large scale production of fuel sources that does not result in a lot of lag. And the most lag friendly solution i have found is charcoal, as large scale blaze and kelp farm put a lot of strain on the server in my experience. The thing holding back charcoal in my experience is the limited fuel efficiency, as you only get 8 smelts per item, compared to the 12 of blaze rods and 20 of kelp blocks. Coal blocks are all ready in the game, but are they are not sustainably. This is why this small improvement would help the server lag a little bit, while not actually being impactfull on the general experience of EMC. In my opinion it's weird that mojang has not made charcoal blocks a thing as of yet. This implementation would make it possible to convert charcoal into coal, but as the 2 items have exactly the same properties, i don't see this actually impacting anything significant, except for lag.

**Comment by Snowyy4K** [comment]
+1

**Comment by DorienB** [comment]
Very smart me aprove.

**Comment by FutureLemon** [comment]
+1 it's only a minor change.

**Comment by WhitPlayzYT** [comment]
i agree but i personally think there should be a "Charcoal Block" just in vanilla, being just as good as coal for fueling just looking slightly different when placed
