### ISSUE TITLE
[BUG] Breeding and Blaze Spawners

### ISSUE THREAD

**Issue by LoganCreeper50** [EarthMC/Issue-Tracker#485]
**Server**
Terra Nova

**Describe the bug**
The lack of breeding and it always being turned off is bad for the servers economy, without being able to get leather for books, and wool for banners makes the server lose the craftablitiy of certain items. And also with Blaze Spawners being off mending becomes basically useless.

**Comment by KarlOfDuty** [comment]
At the moment we have to disable all mob spawning, we are waiting for an update where we can selectively toggle it depending on spawn reason.

**Comment by LoganCreeper50** [comment]
When do you think that mob spawning will be back up?

**Comment by WhitPlayzYT** [comment]
@LoganCreeper50 i recomend making a furnace array for when blaze AIs are off it really helps for me

**Comment by Twitchyyy** [comment]
Since the dynmap takes up so much to run, why not get rid of the dynmap or get rid of live players on it. I'm sure players would prefer things like grinders and breeding and sign shops working and be "waiting on a fix for the dynmap" then the vice versa

**Comment by DasCodes** [comment]
This has been fixed.
