### ISSUE TITLE
Changes to the Dynmap

### ISSUE THREAD

**Issue by RangerMK01** [EarthMC/Issue-Tracker#486]
**Is your feature request related to a problem? Please describe.**
Fix recently mentioned that the two largest consumers of processing power on the server were the Towny Plugin and the Dynmap. Using that information, I took a brief poll about if the commuinty would be willing to accept changes to the Dynmap in favor of better processing. I did this in the Exclusion discord, which contains a large number of donators, old-time players, and honestly the most dedicated portions of the community. With an exact total of 91 votes at the time of writing this, the vote was 58 yes to 33 no, contested for sure, but with a clear majority.

**Describe the solution you'd like**
On behalf of all those who voted, I was hoping for a couple of things.

1. What possible ways could the dynmap be changed for better performance?
2. How much would these affect performance?
3. Would you be willing to carry through with these changes if a significant portion of the community voted in favor?

**Additional context**
![Screen Shot 2019-04-21 at 3 43 48 PM](https://user-images.githubusercontent.com/48573553/56476450-7c775c00-644c-11e9-8483-835e2de21dd8.png)

I hope that we can possibly come to a solution that will improve the server

**Comment by BowShot118** [comment]
I vote we  yeet the Dynmap into the Sun until a towny replacement is found. 

Or at least kill the players on it, but idk if that'd help the performance

**Comment by EchoOcelot** [comment]
We could make the dynmap like it was in Classic, where you had to log in and then you could only see you and your nation members.

**Comment by Pengun78** [comment]
Hell no

**Comment by watergod1234** [comment]
How am I gonna find people to kill then.

**Comment by watergod1234** [comment]
How would I find and kill people then?

**Comment by RangerMK01** [comment]
I’m not denying it would be more difficult and definitely cause some inconvenience, but I think it is a reasonable trade off for freeing up server processing until a better solution can hopefully be found

**Comment by watergod1234** [comment]
Yes, there are pros and cons for each side but in my opinion I’d rather have the dynmap. Although it’d definitely be an interesting mechanic to have in-game maps being useful.

**Comment by alekb1** [comment]
I would rather have semi good server performance and dynmap

**Comment by FutureLemon** [comment]
None of us really know the issue here it might be this it might not be this if it is the dynmap I hope they change it, but no need for a GitHub.

**Comment by RangerMK01** [comment]
My dude, Fix literally said himself that the two biggest consumers of processing power were the towny plugin and Dynmap.
I’m not entirely sure what you mean about not needing a GitHub for this, as this is the whole point of the GitHub.

**Comment by RangerMK01** [comment]
@alexb1, I’m not suggesting removal, though that could be a possibility depending on their response. I’m saying that as Fix said, trying to track 155 players on this large of a map at all times is lag intensive. Therefor, something should probably change to make it more effective

**Comment by Ultil0l** [comment]
remove the players on map dab

**Comment by WhitPlayzYT** [comment]
@Ultil0l  thats one of the main points of the map u fool

**Comment by Ultil0l** [comment]
actually, no
Back in classic you couldnt see the players on the map

**Comment by KarlOfDuty** [comment]
We will not do either of these things, they will likely not affect performance by a noticeable amount.

**Comment by BowShot118** [comment]
(Every little helps)
