### ISSUE TITLE
Nbax being extremely toxic and spawntrapping

### ISSUE THREAD

**Issue by Lemonlicious** [EarthMC/Issue-Tracker#487]
Nbax is attempting to spawntrap me and is camping my log-off point over something that one of my friends did. He was extremely defensive and his friends (namely skater2323) were also suspiciously defensive upon being confronted, to the point where I was kicked from their discord after asking a couple of questions.

Evidence #1 (Discord): https://youtu.be/7yWGSgDRYbE

Evidence #2 (Actual in-game): https://youtu.be/YE0U3ENHfoI?t=181

If you have any questions or need more proof, my discord is Lemonlicious#5122
Thanks!

**Comment by watergod1234** [comment]
Moderators do not moderate what goes on outside of the server. And you logged, so in my opinion you deserve to get spawn camped (which isn’t against the rules, by the way). Also another thing, why do you seem to go to such far lengths to try to get people in and closely associated with Niger in trouble? It’s very petty and this is hardly the place to be making these reports.

**Comment by Lemonlicious** [comment]
Fairly certain he's not spawn trapping me on discord bru, and you can see in the videos provided how rowdy and defensive he gets when confronted.

You're in no position to talk crap considering you folks reported Exodia for something similar and he received a warning.

**Comment by watergod1234** [comment]
As I said in my previous comment, mods do not moderate and they frankly don’t care what people do **outside** of the server. This includes discord. I’m sorry that my group got exodia warned and if it were up to me I wouldn’t have wanted it. However, Nbax isn’t even breaking the rules here and your volume of pointless reports are just a waste of time for you and staff.

**Comment by Lemonlicious** [comment]
They can decide that then, report comments are no place to start petty arguments.

**Comment by watergod1234** [comment]
Very well.

**Comment by FutureLemon** [comment]
When you're waiting for someone to kill outside claims it is not concidered spawn trapping and not toxic. Please stop using GitHub for these unnecessary and false complaints you prevent it from being used as it is suposed to be: eg. Reporting bug's and giving suggestions. If you feel like you need to report people for these worthless things make a report ticket with '-new' and make everyone's lifes more easier. (imo you guys are in fault you shouldn't log)

**Comment by Toadally** [comment]
This isn't against any rules. Don't log.
I recommend you read [the rules](https://earthmc.net/rules).

**Comment by Kyoris** [comment]
Logging is retarded
Also don't be a snowflake on a toxic server

**Comment by FutureCW** [comment]
Reporting players for spawn-trapping when your nation built a spawn trap at their /n spawn. Also even if Nbax is "toxic" in that video, it's not on the EarthMC discord or the server so staff can't do anything about it. Spawncamping when you logged isn't toxic either stop being a fucking retard and behave like a normal player.

**Comment by WhitPlayzYT** [comment]
> Reporting players for spawn-trapping when your nation built a spawn trap at their /n spawn. Also even if Nbax is "toxic" in that video, it's not on the EarthMC discord or the server so staff can't do anything about it. Spawncamping when you logged isn't toxic either stop being a fucking retard and behave like a normal player.

^

**Comment by watergod1234** [comment]
> Reporting players for spawn-trapping when your nation built a spawn trap at their /n spawn. Also even if Nbax is "toxic" in that video, it's not on the EarthMC discord or the server so staff can't do anything about it. Spawncamping when you logged isn't toxic either stop being a fucking retard and behave like a normal player.
 
Ouch!

**Comment by Magenent** [comment]
So your complaining when someone is wasting their time to deal with you logging. lmao

**Comment by KarlOfDuty** [comment]
Use support tickets for this, not the issue tracker.
