### ISSUE TITLE
Re-enable /t spawn [town]

### ISSUE THREAD

**Issue by Lemonlicious** [EarthMC/Issue-Tracker#489]
The /t spawn command has been disabled for some time now, almost a full week.  This disabling has made it increasingly harder for newer towns to trade and newer players to travel to new towns. Players are often forced to make lengthy and often ugly-looking railways or ice highways just to get around. This is also a problem for new towns who are too far away to join any nations, leaving them with two solutions:
1. Travel everywhere manually, which is extremely risky due to roamers looking to slay any off-guard player
2. Save up for a nation of their own, which could take weeks, if not months, of work.

While the disabling of the command does encourage towns to join nations and band together, not all towns are within nation distance, as mentioned above. A good solution would be to enable commands that allow towns to set their publicity status for other towns, not just nations. This will allow newer players and new towns to do business much more efficiently, without the need for delivery or travel across long distances.

An alternative solution would be to extend the nation annexing range, though this could potentially raise more problems such as unrealistic claims.

**Comment by Toadally** [comment]
This removes any need for a transportation networks

**Comment by Lemonlicious** [comment]
>This removes any need for a transportation network

But how are towns without possible nations to join supposed to safely do business? Many of these people are constantly vultured by stronger players because they have no way to get around other than on foot. It ruins the fun for many.

**Comment by FutureCW** [comment]
> > This removes any need for a transportation network
> 
> But how are towns without possible nations to join supposed to safely do business? Many of these people are constantly vultured by stronger players because they have no way to get around other than on foot. It ruins the fun for many.

They just dont be stupid and dont make a town thats not close enough to a nation

**Comment by Lemonlicious** [comment]
>They just don't be stupid and don't make a town that's not close enough to a nation

Thank you for the intellectual input. It's not like there's perfectly usable land out there, and having no nearby nation is a poor excuse to give up a good or fun area.

**Comment by FutureCW** [comment]
> > They just don't be stupid and don't make a town that's not close enough to a nation
> 
> Thank you for the intellectual input. It's not like there's perfectly usable land out there, and having no nearby nation is a poor excuse to give up a good or fun area.

It's not like there's already over 150 nations that are not at full potential and still have lots of land to claim

**Comment by WhitPlayzYT** [comment]
I think you should be able to /t spawn [town inside your nation] but not to any other towns

**Comment by KarlOfDuty** [comment]
Hang on which spawn travel has changed exactly? You still have permission for your own town right?
