### ISSUE TITLE
Increase the amount yielded when crafting sandstone. 

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#490]
Sand for sandstone is very tedious to get and also destroys a lot of terrain around nations in the desert. I propose that crafting sandstone should yield four sandstone as opposed to the vanilla amount of one. This will make it so people don’t have to get as much sand thus making the eyesore of sand deposits smaller and making easier and quicker to get it.

**Comment by WhitPlayzYT** [comment]
Agreed I think the same thing should happen with bricks as well

**Comment by Cactusinapumpkin** [comment]
what about endstone lol

**Comment by Cactusinapumpkin** [comment]
8 sand + 1 cobble = 1 endstone

**Comment by Aitonater** [comment]
I agree, this might curb sand griefs.

**Comment by Prismary** [comment]
Good idea on paper, however much of the sand excavated is also used for glass and concrete powder for example, so it may only make sense in combination with a couple of other changes.
