### ISSUE TITLE
When 1.14?

### ISSUE THREAD

**Issue by BunbunToast** [EarthMC/Issue-Tracker#491]
I get it's probably gonna be a while until all the plugins work with 1.14, but I thought I might as well check.

**Comment by WhitPlayzYT** [comment]
Me knowing how long plugins take to update id give it 2 weeks to 3 months

**Comment by Ultil0l** [comment]
or a year

**Comment by BowShot118** [comment]
probably a year

**Comment by KarlOfDuty** [comment]
likely a year
