### ISSUE TITLE
[Feature] Town Activity Days Requirement

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#492]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I'm in an area where many people have towns that they just log in about once a month to reset the town falling counter and I think that this feature should be removed. I think that there should be an actual minimum amount of time spent on the server for a town not to fall.

**Describe the solution you'd like**
I'm suggesting a minimum amount of activity in a town before it falls, as many people around my town just leave for a month then come back 1 day a month to keep the town from falling (Ex. needing to be on at least 10 days a month with at least 20 hours of playtime)

**Comment by Kyoris** [comment]
I mean maybe only do that with smaller towns with less than 8 or 12 chunks because after that the town would likely be of decent importance .
Also people could take breaks or have to go out on trips lol. 
Another thing is that making people spend a certain amount of time on the server isn't the best considering some people just aren't that devoted into the server or just doesn't have the time.

**Comment by Ultil0l** [comment]
then why are they here?

**Comment by Magenent** [comment]
For casuals this would be crippling, not only would it be passed by just afking, but I think that people should have the right to preserve their towns, active or not, as long as they don't come on the server it should be fine, think of towns that got worked on so hard but mayor's just don't have the time or something and all their work goes to nothing, also anyone with a vacation from 3weeks-1 month would have to spend all day playing video games just so their town doesn't fall. I wouldn't be opposed to it being shortened down to 40 days or something and for it to be clear on when it will fall.

**Comment by WhitPlayzYT** [comment]
Theres over 200 towns with 1-16 chunks and with people either completely inactive or with people that just come on once a month, thats the issue

**Comment by Aitonater** [comment]
We should just have towny upkeep, even something as little as 1 nugget a day would work. Its a feature which already exists in towny and it means that towns would disband before the 42 days and it would probably be more reliable than the 42 day town timer which has been shown not to work.

**Comment by ImperialFishy** [comment]
Yea same with nation upkeep im not sure why it was removed a while ago i think its a great way to keep people active and get rid of inactive town and nations

**Comment by Kyoris** [comment]
I don't want to pay to keep my town thou

**Comment by Aitonater** [comment]
One nugget a day would be nothing if you vote and leave 10 gold in the town bank that would last your town 90 days for example

**Comment by Aitonater** [comment]
The current timer doesnt work and its easy to abuse, if you join an open town thats about to fall and are constantly active make an anti afk machine, you'll be awarded mayor

**Comment by BowShot118** [comment]
Then how will putting such a small daily upkeep change a thing? You said it yourself, 1 days vote = 90 days. Just vote once every 80 days

**Comment by KarlOfDuty** [comment]
This isn't possible currently, especially as towny doesn't even track playtime. You can make a suggestion to add it on the towny repo but I don't think they will as it will require quite a lot to be rebuilt.
