### ISSUE TITLE
Cactus growth slowed down.

### ISSUE THREAD

**Issue by Nominaw123** [EarthMC/Issue-Tracker#493]
**Server**
Earth MC

**Describe the bug**
The groth of cactus is really slowed down.

**Expected behavior**
Restoring normal growth of cactus on EMC.

**Comment by BowShot118** [comment]
probably to stop lag?

Everything's disabled dw about it

**Comment by Nominaw123** [comment]
Well server is not laggy as it used to be, so it can be sped up

**Comment by WhitPlayzYT** [comment]
its because the tps is low (ticks per second) when its lower theres less of a chance for the cactus to grow at each random tick

**Comment by Nominaw123** [comment]
i got info from Eagle that tps is good, cactus is just slowed down

**Comment by KarlOfDuty** [comment]
As stated above, it is just the server not being able to run at top speed so all random ticks are slowed down.
