### ISSUE TITLE
Signshops

### ISSUE THREAD

**Issue by GitMocc** [EarthMC/Issue-Tracker#494]
**Server**
EarthMC/TerraNova

**Describe the bug**
New sign shops are broken, it appears as any sign shop would but it wont let you open the GUI, it really hurts the server

**To Reproduce**
1) Make a sign shop
2) fill up chest with item
3) right click sign
4) and ba-blam, sign shop boke

**Comment by Pengun78** [comment]
Damn everything on emc is broken😤😤😎

**Comment by GitMocc** [comment]
> Damn everything on emc is broken😤😤😎

it really do be like that all the time

**Comment by creatorfromhell** [comment]
Added this to my github as its eadier for me to track it. Follow this for more details and when its fixed. https://github.com/TheNewEconomy/TNE-Bukkit/issues/281

**Comment by GitMocc** [comment]
this has actually been a thing for a while, i just thought someone would have said something about it

**Comment by creatorfromhell** [comment]
> this has actually been a thing for a while, i just thought someone would have said something about it

I don't have the time to read everything on the EMC discord, or go through all the issues on the EMC github.

**Comment by Twitchyyy** [comment]
Yeah it's been a thing for just a little over a month

**Comment by KarlOfDuty** [comment]
Creator has been on hiatus for two months so he hasn't really been keeping up with emc during that time.

**Comment by Pengun78** [comment]
Whats hiatus

**Comment by WhitPlayzYT** [comment]
hopefully its fixed in this maintenance

**Comment by KarlOfDuty** [comment]
This was fixed a while back.
