### ISSUE TITLE
[Feature] towny war

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#495]
add towny war my brothers

**Comment by Ultil0l** [comment]
add towny war my brothers

**Comment by NeonKrby** [comment]
add wowny tar by mrothers

**Comment by unown006** [comment]
Right Before Terra Nova launched Fix said Creator from Hell was working on some system somewhere not sure if that's still the case

**Comment by Pengun78** [comment]
probably not i mean do u remember the dungeons trailer and do u think that will ever happen

**Comment by watergod1234** [comment]
#444

**Comment by Aitonater** [comment]
yeah karl has already said no to war lots and lots of times: here and on reddit. But maybe to war days.

**Comment by Twitchyyy** [comment]
all war needs to be is PvP mutually enabled for the warring nation towns

**Comment by Aitonater** [comment]
Karl has said no because no working war plugin exists and he doesnt have time to make one

**Comment by Pengun78** [comment]
We need creatorfromhell for this😤😤

**Comment by Ultil0l** [comment]
idc that Karl said no

**Comment by Aitonater** [comment]
Are you going to do the coding for it Util?

**Comment by Ultil0l** [comment]
If I knew how to code ~~Unlike Karl~~ I would do it

**Comment by KarlOfDuty** [comment]
Duplicate of #444

**Comment by Pengun78** [comment]
No #444 is war days
