### ISSUE TITLE
Eagle's false mute/warning

### ISSUE THREAD

**Issue by Lemonlicious** [EarthMC/Issue-Tracker#496]
Nowhere do I see in [the rules](https://earthmc.net/rules) any rule against making a complaint or statement about another player so long as it's not toxic.

I simply told people to buy from smaller towns, and then asking Eagle to tell Karl to fix sign shops, at which point I was muted for "being annoying" and then warned for "mute bypass" when confronting him on discord.

Check the rules, no rule against my statements.
![2019-04-27_17 11 53](https://user-images.githubusercontent.com/49698084/56850823-6ec04b80-6910-11e9-844e-03017fdb1204.png)
![2019-04-27_17 14 24](https://user-images.githubusercontent.com/49698084/56850824-6ec04b80-6910-11e9-90dc-23c6e9af0ba2.png)

**Comment by WhitPlayzYT** [comment]
1. A 15 minute mute is nothing 2. Yes it is bypass

**Comment by WhitPlayzYT** [comment]
3. GitHub isnt for player/admin abuse reports

**Comment by Pengun78** [comment]
4. Pengun is epic

**Comment by FutureCW** [comment]
Dude this isn't where you report people stop using GitHub to complain like a lil bitch

**Comment by KarlOfDuty** [comment]
Read above.
