### ISSUE TITLE
False warn (appeal)

### ISSUE THREAD

**Issue by Canuck1** [EarthMC/Issue-Tracker#498]
To start this off, I know I should not be making appeals on the github, but before I could reconnect to the server, Shiraz had gone offline and I could not appeal

I was warned by Shiraz (In my opinion incorrectly) for griefing, by breaking a small hole to jump out of a skyscraper and pvp.

**Coordinates**
-13908, 90, -7749

You can see in the video, I go up the building with incorrect claim permissions, looking for loot and see the person I just killed near me on the dynamic map. I break out of the building with a small hole, in an attempt to re-kill the enemy before they could gear up. This hole was not intended as a grief, or to destroy the building.
Video: https://drive.google.com/file/d/1RtDPrXnICzsSN3ykW3lweh663cMAmYUO/view?usp=sharing
![Appeal](https://user-images.githubusercontent.com/50057382/56854209-dd95a880-6900-11e9-9cb9-dc02ccc73447.png)

**Comment by KarlOfDuty** [comment]
As you say, you know this is not for appeals.

**Comment by Canuck1** [comment]
Should i directly message shiraz through discord?
