### ISSUE TITLE
Please Change the System of how mobs spawn

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#499]
I know much of the reason mobs and their system of spawning is set up the way it is to reduce lag, but with the current system so many things with mobs are broken to the point where I find myself at a loss for what to do. Between the fact that my blaze farm, drowned farm, and wither farm have been broken since the server was finished upgrading because mob spawning has been such a fickle bitch. Or how Cows, Sheep and most importantly Villagers are just straight up not breeding most of the time. All I ask is simple. That the mobs and their mechanics be restored. I get that the server has them off to reduce lag but they are central aspects to the game itself and without them I find the game is missing an enormous chunk of it's content and what is possible.

Sorry if this seems selfish or if i don't have the full picture. Im only coming from the angle of a player and not staff.

If you agree with what I'm saying please voice your opinion so we can hopefully show how truely important mobs and the like are to the game.

**Comment by WhitPlayzYT** [comment]
Fucking yes

**Comment by Canuck1** [comment]
Agreed, i haven't been able to breed my villagers at any time during the past week, it's just barely possible.

**Comment by FutureCW** [comment]
Restoring mobs would honestly restore my interest in playing EarthMC more often

**Comment by BowShot118** [comment]
How many times does this has to be explained, mobs don't spawn because of the lag caused by having the player count as high as it is. This would probably only be added if either Towny is replaced, Dynmap removed or the slots are cut down

**Comment by Pengun78** [comment]
Give war plugin

**Comment by Twitchyyy** [comment]
Honestly, I would be okay if they removed the dynmap OR some functions of the dynmap, even if TEMPORARILY. That way what we're waiting on being fixed isn't basic mob functions, but a pretty add-on

**Comment by FutureCW** [comment]
> Give war plugin

no u

**Comment by FutureCW** [comment]
> How many times does this has to be explained, mobs don't spawn because of the lag caused by having the player count as high as it is. This would probably only be added if either Towny is replaced, Dynmap removed or the slots are cut down

I'd support disabling Dynmap or at least some of the features

**Comment by BowShot118** [comment]
I'd be all for a disable to Dynmap until a towny replacement surfaces

**Comment by Pengun78** [comment]
BowShot118 
commented 2 minutes ago

How many times does this has to be explained, mobs don't spawn because of the lag caused by having the player count as high as it is. This would probably only be added if either Towny is replaced, Dynmap removed or the slots are cut down

**Comment by watergod1234** [comment]
All I want is for villager breeding to be what it used to be. It's so annoying having to wait for low enough player counts to get villagers. But if possible, I'd love for all mob spawning and functionality to come back.

**Comment by unown006** [comment]
"How many times does this has to be explained, mobs don't spawn because of the lag caused by having the player count as high as it is. This would probably only be added if either Towny is replaced, Dynmap removed or the slots are cut down"

Then the game will not be worth playing and the op already stated this however I would rather have 100 slots if it meant the game was playable as lag is still a thing pvp and the other things the op mentioned do not function well or at all.

"Give war plugin"

Yes

**Comment by BowShot118** [comment]
> "How many times does this has to be explained, mobs don't spawn because of the lag caused by having the player count as high as it is. This would probably only be added if either Towny is replaced, Dynmap removed or the slots are cut down"
> 
> Then the game will not be worth playing and the op already stated this however I would rather have 100 slots if it meant the game was playable as lag is still a thing pvp and the other things the op mentioned do not function well or at all.
> 
> "Give war plugin"
> 
> Yes

Nothing wrong with sharing my god damn opinion mate, no need to have a go at me because I see the benefits to less slots (and possible automatic prio queue to people with a day+ playtime on classic 😉)

**Comment by CloakedEagle** [comment]
Mob spawning is enabled on the server. But when TPS goes down below a certain point the server disables mob spawning to help reduce lag. From what I have seen, if the player count stays around 110(ish) mob spawning and other features work perfectly fine. But I have also seen TPS staying where the mobs can spawn even when the server is full.

If we find a way to improve the server performance, we definitely would.

**Comment by WyWall** [comment]
But thats the thing cloakedeagle for the server to start spawning them it must get to a certain amount of people online yet this is always at a time that is inconvienient for myself and a great deal many other players. For the most part dont want to stay up till 1 or 2 am est just to play with mobs that arent broken.

**Comment by CloakedEagle** [comment]
The thing is, we do want to improve the server performance but the issue is on the plugin part. It is not currently able to handle this many of players with a custom currency. Karl is actively working on finding a solution on how to improve server performance.

**Comment by unown006** [comment]
So Question is it possible to improve server performance or is this more like grasping at thin air in hopes of something?

**Comment by Aitonater** [comment]
> Mob spawning is enabled on the server. But when TPS goes down below a certain point the server disables mob spawning to help reduce lag. From what I have seen, if the player count stays around 110(ish) mob spawning and other features work perfectly fine. But I have also seen TPS staying where the mobs can spawn even when the server is full.
> 
> If we find a way to improve the server performance, we definitely would.

The server is never below 155 now because it incorporates such a large player base all around the world in different timezones. To say when it is at 110 it works "perfectly fine" is a fallacy. It is more or less impossible for mobs to spawn or to play mine craft to its fullest extent the way it was intended. How you do this? scrap the dyn map? lower the player cap? no idea but core aspects of the game are missing to reduce lag and it makes people wonder what the point in playing on the server is if its not minecraft but instead a stripped down shit version with none of the key features of gameplay like villagers and animal breeding.

**Comment by CloakedEagle** [comment]
Well, TBH the server didn't use to be full all the time a few days ago.

**Comment by Aitonater** [comment]
@CloakedEagle waiting till 3am to breed your animals for a couple of hours still wasn't that good a solution.

**Comment by CloakedEagle** [comment]
> the server didn't use to be full all the time a few days ago.

**Comment by Aitonater** [comment]
@CloakedEagle I was talking about before it was full. You would have to wait until the early morning for it to be empty.

**Comment by alekb1** [comment]
^
It's true

**Comment by CloakedEagle** [comment]
Well, the thing is admins are doing everything they can to increase the server performance. But not everything depends and can scale with the server hardware. So at this time, they will either have to decrease the player slot or find another way to improve the performance and not sure if they have any other options left as they had been doing that since classic. So if you have any suggestion, please let us know.

**Comment by WyWall** [comment]
Even reintroducing mob stacking would be preferable to what the current state is in my honest opinion or even having mob stacking for the blazes only. Honestly I don't know

**Comment by CloakedEagle** [comment]
It was buggy, we had to deal with hundreds of player tickets refund them for over a few weeks. 😟

**Comment by WyWall** [comment]
That is true but at the same time you could just impliment it for blazes. Or potentially you could increase the amount of xp you get from mining

**Comment by WyWall** [comment]
One of the biggest annoyances for me is trying to get xp. I have not properly been able to grind for any xp since the server first implemted mob stacking

**Comment by CloakedEagle** [comment]
Indeed.

**Comment by WyWall** [comment]
Should the xp thing be it's own thread?

**Comment by CloakedEagle** [comment]
Preferably yes.

**Comment by Aitonater** [comment]
Blazes are spawning at 155 again. They have no AI but you just arrange your spawners in such a way that allows you to wack em till they die. Check out Madagascar's it works pretty well. Takes me 5 mins to repair all my mending now.

**Comment by YellowVictini** [comment]
Blazes work decently fine for me at maximum player count, I just have a floor made out of a few blaze spawners with only the tops exposed. It spawns them really frequently. Enough to grind with, so give that a try

**Comment by WyWall** [comment]
> Blazes work decently fine for me at maximum player count, I just have a floor made out of a few blaze spawners with only the tops exposed. It spawns them really frequently. Enough to grind with, so give that a try

This doesnt solve the main issues though as it is not just limited to blazes. The whole mob spawning system is broken to a point wherein it makes it much more difficult if not impossible to work around. While i will admit the blazes are a good chunk of the problem. I would say villagers and natural spawning mobs like drowned, spiders, witches, zombies, etc are another huge portion of it.

**Comment by JaVolimKatarinu** [comment]
Villagers are the most important aspect of Minecraft and their breeding is disabled due to high player count and low tps. My suggestion is to somehow allow villagers to breed even if tps is a bit low. Server is only under 120 players when it is maintenance.. At least enable it during some hours in few days in week. Disable all other breeding in that time, if it is required. Villagers are important and please do something about it in near future.

**Comment by KarlOfDuty** [comment]
This cannot be done at this point, we have requested the change from the plugin developer.
