### ISSUE TITLE
vote trolling

### ISSUE THREAD

**Issue by SOMEONESTEALMYNAME** [EarthMC/Issue-Tracker#502]
i have some issues to tell you guys there some way that fucking stupid 
so my friend just find way to revenge ppls its vote his name when they are offline so the player that get troll 
will not get any golds cause hes not online when someone vote for him and he will cant vote again cause hes voted thats creppy pls fix it some how 
cause we cant report cause we dont know who is trolling
so easiliy
someone is voting for my friend when he is offline so he is not getting any gold
and cant vote anymore

**Comment by SOMEONESTEALMYNAME** [comment]
so easiliy
someone is voting for my friend when he is offline so he is not getting any gold
and cant vote anymore

**Comment by CloakedEagle** [comment]
> so my friend just find way to revenge ppls its vote his name when they are offline
So is your friend trolling others or he is the one getting trolled?

**Comment by Pengun78** [comment]
his friend is getting trolled

**Comment by CloakedEagle** [comment]
I'm not sure we will be able to do something about it, as the voting websites aren't controlled by us.

**Comment by Kyoris** [comment]
Is it possible to monitor the votes externally and add to the balance in a separate way than currently done?

**Comment by CloakedEagle** [comment]
I'm not aware of what their API offers. But you should be able to see a few top voting players on their website. Again, we don't control the voting sites so we won't be able to stop anyone from voting there.

**Comment by riri2010** [comment]
I think I am the friend that discovered this.
the issue is:
I can go to both vote websites and input somebody else's username.
if they are offline they will get no gold and wont be able to vote later.
unfortunately this is an issue with the website that EMC staff probably cant fix.
the vote websites even warn about it (Any abuse of our vote system will be severely punished)
I DID NOT use this on anybody other than my friend (SOMEONESTEALMYNAME) to test it.
but yes it is possible to prevent other people from voting and I owe my friend 5 gold lol

**Comment by riri2010** [comment]
and another clarification:
nobody is doing this to me.
SOMEONESTEALMYNAME might have misunderstood me.

**Comment by CloakedEagle** [comment]
> if they are offline they will get no gold and wont be able to vote later.

If the offline voting works, this would not be a problem anymore, would it?

**Comment by riri2010** [comment]
yes I think that would fix it.

**Comment by KarlOfDuty** [comment]
This issue is not something we can fix, I think we will be switching to the new voting system on the factions server soon anyway which supports offline voting, making this a non-issue.
