### ISSUE TITLE
wasd

### ISSUE THREAD

**Issue by SOMEONESTEALMYNAME** [EarthMC/Issue-Tracker#503]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
so easiliy
someone is voting for my friend when he is offline so he is not getting any gold
and cant vote anymore

**Comment by Pengun78** [comment]
epic

**Comment by NeonKrby** [comment]
¨someonestealmyname¨

**Comment by Kyoris** [comment]
wasd

**Comment by watergod1234** [comment]
This needs to be looked into immediately.

**Comment by BowShot118** [comment]
wasd

**Comment by Pengun78** [comment]
Please fix the wasd fix

**Comment by WhitPlayzYT** [comment]
fucking close this ur literally just trying to waste staff's time

**Comment by CloakedEagle** [comment]
No information provided. -closing.

**Comment by FutureCW** [comment]
but it was important!

**Comment by BowShot118** [comment]
Rip wasd.. I wanted to see this solved :/

**Comment by NeonKrby** [comment]
f
