### ISSUE TITLE
[Feature] re-enable jailing

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#504]
Everyone wants it back https://strawpoll.com/9xw1b7s7 bruh moment!!!

**Comment by Aitonater** [comment]
Karl has said it cannot and will not be enabled on the grounds of how easy it is to abuse and the lack of control mods/admins have. Mods/Admins cannot overrule towny jail commands so they can't be fully implemented. Imagine a player gets trapped and endlessly spam killed. A ticket gets made. A mod goes to fix it and let them out but they can't without punching a path for the player to escape or totally disabling jails all together which is what we currently have.

**Comment by KarlOfDuty** [comment]
As per the comment above we will have to wait and see if towny wants to implement something to stop abuse of this.
