### ISSUE TITLE
[BUG] Voting gold not received

### ISSUE THREAD

**Issue by SolidShock** [EarthMC/Issue-Tracker#505]
**Server**
Main server

**Describe the bug**
For the past month I was top voter for a long time. From the 30 days in April, I was straight up there first for 23 of them. Then all of a sudden when I voted each day, I got the messages (both of them) in chat, yet didn't receive any gold for it. This has been happening to me to this day. Today I finally got the 10 gold from todays vote aka 03.05.2019

**To Reproduce**
Just voted.

**Expected behavior**
I wanted to see both messages in chat of voting and receive 10 gold from it toal.

**Screenshots**
Can't really show anything, since the problem is that I didn't get it..

**Additional context**
None

**Comment by WhitPlayzYT** [comment]
It happens they cant fix it, its all cus the voting site. Get used to it

**Comment by SolidShock** [comment]
I mean, I wouldn't be so angered if it were a one time thing. The reason I'm here is I missed out on 90 gold!! That's insanity. Once I already had this problem and got quickly responded to and dealt with. Ticket's aren't working and this is a more formal place to write.

**Comment by CloakedEagle** [comment]
There has been some issue with `/voting` recently. I am not sure if it's the issue with the voting websites or EMC. Probably Karl could check.

Were you voting or ever voted offline or while being in the hub?

**Comment by SolidShock** [comment]
I was online in the server even saw both the messages going through. The issue was from the 23rd of April till the 3rd of this moth. The reason I didn't report it sooner is since I thought it'll just be like a one or two day thing, turns out it lasted for 15 days and I lost out on a ton of gold.

**Comment by KarlOfDuty** [comment]
Should be fixed as we changed the voting system a while back now.
