### ISSUE TITLE
Cannot light a fire and need to for a fireplace

### ISSUE THREAD

**Issue by Joel-02** [EarthMC/Issue-Tracker#506]
Quite simply whenever I with a flint and steel try to light a fire on my plot (firespreads on) or in the wilderness, it will not let me. Please fix this , ive now got an empty dim fireplace:) Thanks

**Comment by BowShot118** [comment]
EMC is a fuckfest now Joel.

Half the stuff is disabled, you just gotta get use to it

**Comment by WhitPlayzYT** [comment]
^

**Comment by WhitPlayzYT** [comment]
if you're having issues with portal lighting I've used a dispenser and it work but for a fireplace its completely impossible

**Comment by CloakedEagle** [comment]
Try `/plot toggle fire`. That should enable fire to light on that plot. But the fire spread is disabled.

**Comment by Cactusinapumpkin** [comment]
^^ ive seen fire places at madagascar

**Comment by FutureCW** [comment]
I think fire is unable to be placed when the server is full but I’m not sure

**Comment by PoppyK** [comment]
if you own the plot, Cactus, /plot toggle fire, light your fireplace, then toggle off again with the same command.
