### ISSUE TITLE
[Feature] Better Trading System

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#507]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Currently trading on EMC is very open to scamming and a /trade system would make trading easier and more reliable
**Describe the solution you'd like**
I am suggesting that /trade [username] gives a trade request to a player if they're within 10 or so blocks of you and if they accept it would open a trading GUI with 1 side being for what you're offering and the other for what the other person is offering with an accept and decline trade button. This however would mess with /trade(chat) so I'd also be suggesting that /trade becomes /tr (on every towny server I've every played on except EMC the tradechat shortcut has been /tr) 
**Additional context**
It would be epic so yea

**Comment by GitMocc** [comment]
i support this sounds very epic

**Comment by WhitPlayzYT** [comment]
I think this would work
https://www.spigotmc.org/resources/fairtrade-1-13-2.59702/

**Comment by unown006** [comment]
Agreed

**Comment by Kyoris** [comment]
This would be nice for trading :)

**Comment by Pengun78** [comment]
Lol ofcourse it would be nice for trading kyoris my man

**Comment by Virus-3** [comment]
We Need this

**Comment by WhitPlayzYT** [comment]
added to factions but why not towny yet?

**Comment by KarlOfDuty** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [/trade](https://trello.com/c/NJuFhc9z/13-trade)

**Comment by Aitonater** [comment]
something like the runescape trading would be cool lol

**Comment by shirazmatas** [comment]
added
