### ISSUE TITLE
[World] Crash

### ISSUE THREAD

**Issue by RubyPiec** [EarthMC/Issue-Tracker#509]
**Describe the issue**
THE EARTH CRASHED

**Coordinates**
1124782648724, 32897526, 8397589465983274

**Screenshots**

**Comment by RubyPiec** [comment]
cool

**Comment by RubyPiec** [comment]
idk

**Comment by BowShot118** [comment]
gg on noticing it

**Comment by RubyPiec** [comment]
help i turned into pizza

**Comment by RubyPiec** [comment]
it crashed again

**Comment by RubyPiec** [comment]
#1386

**Comment by RubyPiec** [comment]
Duplicate of #1

**Comment by RubyPiec** [comment]
- [ ] hhhhhhhh

**Comment by RubyPiec** [comment]
__
