### ISSUE TITLE
Veteran queue

### ISSUE THREAD

**Issue by Ultil0l** [EarthMC/Issue-Tracker#510]
Add some 2nd class priority to anyone who joined before may 1st to not ruin the community

**Comment by BowShot118** [comment]
i really like that idea. It means that the new members still have to pay, a massive plus for fix's wallet, and older players who won't pay can still play. Pretty epic imo

**Comment by Ultil0l** [comment]
yea

**Comment by Kyoris** [comment]
ye i don't want to be stuck in queue with entitled toxic kids and lose my mind before hitting 50th in queue

**Comment by FenZenyatta** [comment]
Agreed. 
Shit started to go down badly in March-April 2019 (February was the last chill month), so it would be a great idea to give veteranqueue to everyone who registered before that

**Comment by NeonKrby** [comment]
Veteran Queue should be worse than Prio Queue so it still incentivizes purchase. Possibly putting them in the 20-40 range

**Comment by unown006** [comment]
This is not needed

Why?

Because you can already skip the queue

But I do not want to pay 10.00 USD

Tough Shit stop complaining the only reason there is a skip queue function is to help pay the bills and to add on to that The Server overlords are only doing a one-time payment, not a monthly payment (Not sure why) 

If you think this kills a server think what happens when it stops functioning as that is what you are truly suggesting

**Comment by ImperialFishy** [comment]
Every server needs loyal players especially one like emc where you only achieve anything from playing for a long time. Im all for a veteran queue to keep these players who have put a lot of time and effort  into this server around.

**Comment by Ultil0l** [comment]
@unown006 I have donator I do not need priority

**Comment by CloakedEagle** [comment]
So basically you are asking for free donors perk. 🤔

**Comment by Kyoris** [comment]
i mean like partial donor for those who have been playing for a long time

at this point without the people who have been loyal to the server and been playing for months, the server would be a toxic shithole of retarded 8yo kids and edgy teens spamming the n word

**Comment by BowShot118** [comment]
It already is that.........


(Fuck toycat)

**Comment by KarlOfDuty** [comment]
We will not be implementing this.
