### ISSUE TITLE
[BUG] Whenever i join the new queue i get the Invalid Keepalive error

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/Issue-Tracker#513]
**Server**
Queue

**Describe the bug**
Keeps kicking me when i connect

**To Reproduce**
/shrug
**Expected behavior**
Be able to not be kicked 

**Screenshots**

**Additional context**

**Comment by KarlOfDuty** [comment]
Are you using vanilla Minecraft 1.13.2? The queue isn't a real server anymore, just a very lightweight program holding players until they get onto a minecraft server so there may be bugs with other modded clients sending nonstandard packets.

**Comment by NeonKrby** [comment]
It stopped happening and i was using optifine.

**Comment by WhitPlayzYT** [comment]
so optifine just fucks the queue now?
