### ISSUE TITLE
[Feature] Classic-Priority

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#514]
Well I think the idea is simple, but to have it so that people who have played on classic get the basic priority. It is important, to have the people that have played a bunch on classic be able to get onto EMC quickly. I know a bunch of people who made the server and kept it active on classic not play terra nova mainly because of the queue. An example (yet one not everyone likes) is IanSpace as he has been significantly less active on terra nova after all these new people joined. It would just be a good a idea to help the people who have played and made classic.

**Comment by CloakedEagle** [comment]
The classic map is an archive, more like a showcase. But players are free to play on it still.

**Comment by unown006** [comment]
Not needed at all at this time

**Comment by FutureCW** [comment]
I think Ian losing interest is more my fault when I made Micronesia. He stopped making emc vids and was less active after that

**Comment by Magenent** [comment]
No cloaked, I mean that people who have played on classic get priority in the queue

> The classic map is an archive, more like a showcase. But players are free to play on it still.

**Comment by CloakedEagle** [comment]
Okay.

**Comment by BowShot118** [comment]
On the top of an archived map, re-adding town collapse on classic? :pls:

**Comment by CloakedEagle** [comment]
I don't think the owner would want that. Otherwise, what's the meaning of archived.

**Comment by BowShot118** [comment]
> I don't think the owner would want that. Otherwise, what's the meaning of archived.

If it's archived, what's the actual point of keeping it alive? The fact it's archived makes it unplayable

**Comment by CloakedEagle** [comment]
The point of keeping it alive to showcase it to the players, as Fix had said the Classic map will stay live at its current state. And you can still play on the classic map just like the old days. In fact, some players are still playing on it on a regular basis.

**Comment by KarlOfDuty** [comment]
We will not be implementing this.
