### ISSUE TITLE
[BUG] main server failing to accept players 

### ISSUE THREAD

**Issue by prokillerr** [EarthMC/Issue-Tracker#515]
**Server**
Which server the bug is on.
Earthmc.net 
**Describe the bug**
For the past 2-3 days or so, the players online at queue get an error(shown in the photo Ill upload). Also, since the queue changed to 2b2t style, every 5 mins or so everyone(or at least a lot) gets kicked, but can join back immediately, which means, the queue never crashes, it just kicks people.(I think it also happened to ppl before new queue, when the error in chat appeared but not sure) 

**To Reproduce**
Join queue, without priority acess(dunno how or even if the glitch works with donators) 

**Expected behavior**
The queue moving in acordance with the amount of ppl logging out of the main server(if 1 logs out of main server 1st in queue logins and everyone moves 1 spot near 1st potision). 

**Screenshots**
![15570527196695070663583226115930](https://user-images.githubusercontent.com/8677505/57192618-21a92e80-6f3b-11e9-8db3-cf8b4563c3b3.jpg)

**Additional context**
It might seem like I report 2 bugs, but I think that these 2(server not accepting ppl and queue licking out ppl) are connected.Even if they're not, the fact that this became a widespread problem(its obvious that its not only me cuz I see the playerbase lowering whenever I get kicked) after queue changed is obvious.

**Comment by KarlOfDuty** [comment]
This has been fixed since.
