### ISSUE TITLE
Improve queue time by kicking people that die in PvP

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#516]
It’s annoying that when you kill someone they keep coming after you no matter how many times you kill them, so my proposal is to kick them when they are killed. Their items are collected by the killer anyway, so it’s not like they loose anything. I think it would improve the speed of the queue somewhat, and would make it a little more consequential to die in fights.

**Comment by ImperialFishy** [comment]
I understand your frustration but there are lots of people who have friendly fights for practice. I myself do it relatively often and id hate it if my pvp opponent or me were to be kicked if we just practiced a bit

**Comment by alekb1** [comment]
I don’t care about queue, I’ve donated. I believe that you should donate to improve the server capabilities. But if you want to practice go to cubecraft or hypixel

**Comment by shirazmatas** [comment]
./duel command. loser gets kicked 🤔

**Comment by unown006** [comment]
*Clap* *Clap* *Clap*

Well now you just killed a server

**Comment by CloakedEagle** [comment]
PVP is one of the main parts of the game mechanic and feature. We aren't gonna disable it or kick any player who lost in a PVP battle in Towny server.

**Comment by Pengun78** [comment]
PVP is one of the main parts of the game mechanic and feature. We aren't gonna disable it or kick any player who lost in a PVP battle in Towny server.

**Comment by sawyerc18** [comment]
+1 smart idea. dying should have consequences. it is a pvp towny server after all.
