### ISSUE TITLE
There's a swearing filter on classic

### ISSUE THREAD

**Issue by BowShot118** [EarthMC/Issue-Tracker#517]
**Server**
Classic

**Describe the bug**
Swearing block, to stop me saying "fuck"

**To Reproduce**
just swear on classic

**Expected behavior**
not censored

**Screenshots**
![2019-05-06_11 30 20](https://user-images.githubusercontent.com/44571571/57220317-c3d81d80-6ff2-11e9-856c-2e8a49eb8e52.png)

**Comment by KarlOfDuty** [comment]
Fixed.
