### ISSUE TITLE
[BUG] Nation/Town name doesn't appear in the chat for some players randomly

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#518]
**Server**
Current towny server. TN.

**Describe the bug**
The chat randomly doesn't show town or nation you belong. If it's the town, you won't see town messages and vice versa. Relog fixes it sometimes.

**To Reproduce**
Happens randomly

**Expected behavior**
You can't see nation chat if the chat doesn't recognize you are in a nation. Same with town chat.

**Comment by WhitPlayzYT** [comment]
My nation tag wasn't showing but my nation chat would still show. This is just a really weird bug

**Comment by Aitonater** [comment]
Not sure if this is still subsisting but it happened to me too. Dot.

**Comment by Virus-3** [comment]
When I changed the mayor of my town it seemed to Disappear for me. Idk if this is coincidence or not.

**Comment by CloakedEagle** [comment]
**Temporary fix:** Go through a nether portal, it'll fix the tag and nation/town chat.

**Comment by DasCodes** [comment]
**Update:** Players are unable to do `/t deposit` command until they use a nether portal.

**Comment by KarlOfDuty** [comment]
Seems to be fixed.
