### ISSUE TITLE
Combat logger plugin

### ISSUE THREAD

**Issue by sawyerc18** [EarthMC/Issue-Tracker#519]
https://www.spigotmc.org/resources/combatlogx.31689/

was talking to cloaked eagle and he said to link combat logger plugins on here. this one is 1.13.2 compatible and can be integrated with towny.

**Comment by Toadally** [comment]
#481

**Comment by WhitPlayzYT** [comment]
^

**Comment by watergod1234** [comment]
Yup. I still have no idea why this isn’t a thing when it is widely available, efficient, and easily configurable.
