### ISSUE TITLE
PROXIMITY MIC

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#520]
EMC needs a proximity mic feature so I can harass the players near me

Rust/PUBG shtyle

**Comment by NeonKrby** [comment]
Thats not how Minecraft works

**Comment by ZestyPhallus** [comment]
![angry as fuk](https://user-images.githubusercontent.com/47764467/57257382-196df380-700e-11e9-8ef9-abc22773312a.jpg)

**Comment by CloakedEagle** [comment]
😅
