### ISSUE TITLE
Experience point rework

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#521]
Sub thread based on the mobs spawning being so low, request that either the xp yield from mining be increased to compensate from lack of mobs or the xp amount required to reach lvl 30 be lowered.

**Comment by YellowVictini** [comment]
Just silk touch up loads of Emerald ore or Diamond Ore for later EXP use. It's a temporary fix for getting exp. Also, I'm not sure if the staff can lower the experience points required to get to level 30, but it would be interesting if it was possible.

**Comment by WyWall** [comment]
> Just silk touch up loads of Emerald ore or Diamond Ore for later EXP use. It's a temporary fix for getting exp. Also, I'm not sure if the staff can lower the experience points required to get to level 30, but it would be interesting if it was possible.

I know you can do that and its not overly difficult but its more to offset the fact that you cant get xp easily from mob spawns unless its 3am.

**Comment by WyWall** [comment]
because the time it takes to achieve that double chest of xp bottles from mobs is a fraction of that of mining.

**Comment by Steadlington** [comment]
So what you're saying is you want it easier than it already is? 

Spawners are disabled due to server performance. The current way to get xp is good enough.

**Comment by Kyoris** [comment]
A boost in exp from ores would still be helpful and a decent temporary compensation mechanism for the time being

**Comment by Steadlington** [comment]
I agree but I think having things harder for the time being actually makes it feel like you have something to do. Like grinding out level 30 from mining out ores alone takes a while and it feels rewarding when you get it. However, doing it from smelting ores take next to no time and has the same effect.

**Comment by Aitonater** [comment]
Blaze spawners are working now when the server is full, so I havent had any problems getting xp atm.

**Comment by WhitPlayzYT** [comment]
^ same as Aitonater but I do agree with this idea. Even at 3am the server is full and has lower mob spawns at this point

**Comment by shirazmatas** [comment]
please follow format and repost
