### ISSUE TITLE
[BUG] Auto kicked for "hacking" when dropping items by holding Q

### ISSUE THREAD

**Issue by riri2010** [EarthMC/Issue-Tracker#522]
**On main EMC server**
**Issue with plugin I think**

**Issue**
When holding Q, the player will drop items one after another in quick succession. after my sister gave me a stack of stone in this way, she was kicked with the following message:

**Kick message:**
"You have been kick from the server you where on. Reason:
You dropped your items too quickly (Hacking?)
You have been sent back to the hub world."

**Steps to reproduce issue**
In my attempts to reproduce this issue, I never got kicks
but the steps should be:
1. hold stack of items
2. hold down Q to drop all
3. get kicked
4. see scary message accusing you of hacking

**Expected behavior:**
Not get kicked for using game features

**Possible Solution**
consider changing the message to not say anything about hacking. it made the kick seem more severe that it probably really is.

**Screenshots**
https://drive.google.com/open?id=159igsJR-2tZz_VOON16dxsyghRiF_zwf
^^^ See message

**More**
I would also like to ask: this is only an automatic plugin kick right? does it count as a warning or not?

Thank you

**Comment by FutureCW** [comment]
Yes it’s an automatic kick when you drop items too fast. It’s not gonna be removed either and no warnings are given

**Comment by riri2010** [comment]
goes to dark web
downloads hax
drops items faster than all the other noobs
😎

**Comment by WhitPlayzYT** [comment]
its not even a plugin its just a vanilla anticheat

**Comment by DasCodes** [comment]
It happens if you or server lags while you are dropping items one by one, counting as you are sending too many requests in a short period of time. Vanilla feature.
