### ISSUE TITLE
Priority Not Working

### ISSUE THREAD

**Issue by OJMoose** [EarthMC/Issue-Tracker#524]
**Server**
EarthMC

**Describe the bug**
I joined the server and I was put to 368. Then I rejoined and it put me to 390.

**Expected behavior**
I expect it to put me in queue at a lower queue position ( eg. 5- 30 )

**Comment by KarlOfDuty** [comment]
As it appears to work sometimes but not others, does anyone have any information on when it does and does not happen?

**Comment by KarlOfDuty** [comment]
This was fixed.
