### ISSUE TITLE
Daily Gold Kit for Classic

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#525]
On classic at the moment, there are very few ways to get gold, as voting for classic no longer works. Mining, which requires hours of work for minimal profit, or salvaging, which is equally painful. The last few veins of gold are being mined up on classic, making claiming and starting new towns near impossible. However, I have a solution.

My solution is to simply create a kit that gives 16 gold, (or similar amount) per day as a replacement for gold. This gold kit would easily repair the economy and allow for this to happen. It could also lesson the burden of the queue, as some players might choose to play classic, if getting gold reliably was possible. It is a simple fix, and I hope that staff will concider this.

In addition, a strawpoll has been made with this request. If you do not play classic, or dont care, kindly do not leave a vote. The strawpoll link: https://strawpoll.com/31rwg4z3.  

Thank you for reading. 
-IanSpace71

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/57575678-5e02f000-744f-11e9-9743-d90d01a3448d.png)
 💯

**Comment by KarlOfDuty** [comment]
Done. /kit daily
