### ISSUE TITLE
I cannot join classic.

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#527]
Classic/Queue

I cannot run the command /joinqueue classic, preventing me from joining the game. However, i see others joining classic

**Comment by Skater2323** [comment]
stop trying to bring back classic cause your a non priority and besides , nobody will go back to classic considering that people just don't want to restart , if they are not old fags , or bought prio queue to play TN .

**Comment by IanSpace71** [comment]
Uh, I didnt ask for your opinion, im wondering why I cant join classic

**Comment by FutureCW** [comment]
u got banned nerd

**Comment by FutureCW** [comment]
obv

**Comment by IanSpace71** [comment]
Except i didnt

**Comment by KarlOfDuty** [comment]
Should work now.
