### ISSUE TITLE
I am banned from the webstore without reason.

### ISSUE THREAD

**Issue by GitPotTime** [EarthMC/Issue-Tracker#528]
**Server**
The webstore

**Describe the bug**
I enter my username then I click on add to cart but the button is disabled

**To Reproduce**
1. Go to 'store.earthmc'
2. Enter my username 'KfcGrecTacosMcDo'
3. Click on 'Queue Priority'
4. Try to add the queue priority item to cart
5. A message will show up.

**Expected behavior**
Add the item 'Queue Priority' to the cart

**Screenshots**
http://prntscr.com/nnmobl

**Additional context**
I don't have additional context

**Comment by KarlOfDuty** [comment]
DM fix in discord, if you do bank chargebacks you get banned from payments on all minecraft servers which is why you can't pay here.
