### ISSUE TITLE
[Bug] Can't access chests in faction claims even though full permissions

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#529]
**Server**
Beta server with factions

**Describe the bug**
Chests in claimed territory cant be accesed

**To Reproduce**
1. Join faction
2. access chest
3. fail

**Expected behavior**
the chest opens

**Screenshots**
no

**Additional context**
yes

**Comment by watergod1234** [comment]
Yes fix this.

**Comment by shirazmatas** [comment]
Cant access furnaces

**Comment by KarlOfDuty** [comment]
Is it only containers or are other blocks affected? Also is this happening to everyone or just you?

**Comment by FutureLemon** [comment]
> Is it only containers or are other blocks affected? Also is this happening to everyone or just you?

Every block with an interface can't be opened in claims on factions except by faction leaders. I thought it was a perm done wrong my f leader but it's the server.

**Comment by Pengun78** [comment]
Fuck factions

**Comment by KarlOfDuty** [comment]
Fixed.
