### ISSUE TITLE
Wrong Named Island

### ISSUE THREAD

**Issue by Bergurlc** [EarthMC/Issue-Tracker#530]
[**Describe] the issue**
The Faore Island on the map is wrong, it is called Faroe (Scotland) and that is wrong, It is called "The Faroe Island" or "Faroe Island" and it is part of (Denmark) not (Scotland.)

I always want to ask if a player is inactive does the player lose the claimed area or how does that work? 
Thanks

**Coordinates**
-1470,-11606

**Screenshots**
![fare](https://user-images.githubusercontent.com/46599066/57591587-14d39e80-752a-11e9-8428-5a323d31f4bf.PNG)

**Comment by Kyoris** [comment]
yeah this ain't a mirror of the world so you can claim whatever the hell you want and name it whatever the hell you want (at least for towns)
don't go judging other people's towns' names, especially if it's one of or a rendition of the real life spot's names

**Comment by Bergurlc** [comment]
Ahh I had no idea, see I am from Faroe Island, so thought maybe this was an error or something.So if I wanted to make a kingdom and a player that has been inactive for a long time that has claimed a spot, will he lose it?Thanks for the fast responsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kyoris <notifications@github.com> Date: 13/05/2019  03:27  (GMT+00:00) To: EarthMC/Issue-Tracker <Issue-Tracker@noreply.github.com> Cc: Bergurlc <bergurlc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [EarthMC/Issue-Tracker] Wrong Named Island (#530) yeah this ain't a mirror of the world so you can claim whatever the hell you want and name it whatever the hell you want (at least for towns)
don't go judging other people's towns' names, especially if it's one of or a rendition of the real life spot's names

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EarthMC/Issue-Tracker/issues/530#issuecomment-491655590",
"url": "https://github.com/EarthMC/Issue-Tracker/issues/530#issuecomment-491655590",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KarlOfDuty** [comment]
As have been stated above, this is not against the rules and if it was should be reported in support tickets in Discord instead of here.
