### ISSUE TITLE
[Feature] now add towny war

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#532]
**Is your feature request related to a problem? Please describe.**
Factions get wars and we all want towny wars on the main server

**Describe the solution you'd like**
Towny war

**Additional context**
no

**Comment by watergod1234** [comment]
Why not war days like in #444 where one time a week PVP is enabled in towns? They've already said many times that they're not going to be adding towny war because it's laggy and bad (which is true).

**Comment by Magenent** [comment]
Yeah we want war on towny, not war on a new server no one is invested in.

**Comment by Magenent** [comment]
> Why not war days like in #444 where one time a week PVP is enabled in towns? They've already said many times that they're not going to be adding towny war because it's laggy and bad (which is true).

War days is a step forward, but the long term goal should be some sort of modified towny war where you can declare war and have in depth wars etc. its not bad whatsoever and its the main thing in geopolitics half of it is about some sort of conflict which is entirely removed on EMC

**Comment by Pengun78** [comment]
Well war is there to annex lands not to just fight, the enemy can also just hide in a basement and ignore the raiders

**Comment by dascodes** [comment]
As Karl has told before. Find a working war plugin for towny, we'll add it.

**Comment by CloakedEagle** [comment]
As Karl has said before, find a working war plugin, we'll add it.

**Comment by w0265261** [comment]
drop towny and adopt Townships has wars already and other better features imo

https://www.spigotmc.org/resources/townships-battle-for-resources-control-and-glory.25944/

**Comment by w0265261** [comment]
also this https://www.spigotmc.org/resources/%E2%9A%94-wars-for-towny-%E2%9A%94-conquest-glory.65216/

**Comment by YellowVictini** [comment]
> As Karl has said before, find a working war plugin, we'll add it.

There have been quite a few suggestions to Karl of War plugins using Towny. CorruptedGreed,  for example, had a pretty solid suggestion using a modification version of the default towny war system. So far, there hasn't been much response on these suggestions.

**Comment by watergod1234** [comment]
> As Karl has said before, find a working war plugin, we'll add it.

#444 is completely within the limits of towny @CloakedEagle. So according to your logic, why isn’t it added?

**Comment by CloakedEagle** [comment]
That's not a war plugin and war doesn't work that way. If you force enable PVP on every town many players will not like it as not all players play and live just to PVP. Hence Karl said,

> I'm not saying it will be done but I am saying we are looking into it.

A valid war should only happen when it's declared by both nations, not by forcing it from the console.

**Comment by KarlOfDuty** [comment]
While there are many different types of wars being suggested, there are already issues open on all of these. Use them instead.

As I said a long time ago, we are looking into it. We just got interrupted with having to divert all time to work on big server issues for over a month now, but now that basically all of those are fixed we will be able to look at feature improvements again.

**Comment by bapsachiko** [comment]
Wars mean nothing in this server as there is no way to actually use force on towns, which I already explained in depth how and why but all admins replied with was that it's "toxic" despite advertising geopolitics and wage war.
Nanny server with false advertising is all this is.

**Comment by Pengun78** [comment]
Alright but can we maybe have more updates on the progress so we know how its going

**Comment by Magenent** [comment]
> That's not a war plugin and war doesn't work that way. If you force enable PVP on every town many players will not like it as not all players play and live just to PVP. Hence Karl said,
> 
> > I'm not saying it will be done but I am saying we are looking into it.
> 
> A valid war should only happen when it's declared by both nations, not by forcing it from the console.

not at all because if someone is killing your citizens outside of claims then refuses to go to war thats completely wrong

**Comment by Pengun78** [comment]
But then ppl like jevil would take over the world lol but i get ur point and i kinda agree

**Comment by Pengun78** [comment]
oh and yes i know he got perm banned i mean people that are like him
