### ISSUE TITLE
[BUG] Players get requeued in the last position on the queue instead of the first

### ISSUE THREAD

**Issue by SmileDerp** [EarthMC/Issue-Tracker#533]
[BUG]

**Server**
Which server the bug is on.

Queue

**Describe the bug**

If you are #1 and it cant send you to towny you get requeued and go from #1 to last player

**To Reproduce**
1. Be number one
2. Queue cant send last 5 players to main server
3. You get an error 
4. You get requeued

**Expected behavior**

To go to the main server

**Screenshots**
Here 
![Pls help me](https://user-images.githubusercontent.com/50592243/57640555-1e551900-75b3-11e9-83c4-135811f1ae64.png)

**Additional context**
I would appreciate a rank if thats possible for free :P? for waiting for nothing which happened to many times already.

**Comment by KarlOfDuty** [comment]
Tell me if it happens again, it should force the player back into position 1 if they cant connect now, but I just did a really quick fix while the server was down for a bit before so not sure if it works yet.
