### ISSUE TITLE
[BUG] spawn from queue

### ISSUE THREAD

**Issue by jtgrafisbiggay** [EarthMC/Issue-Tracker#534]
**EarthMC**

**Describe the bug**
I spawned into the server after waiting in the queue. In the queue i was falling and i spawned in as i was falling. right when i spawned, i died and lost all of my items which disappeared because no one picked them up
**To Reproduce**
1. go to queue
2. when you are at #1 jump off (hopefully you spawn as you are falling)
3. spawn in world
4. dies

**Expected behavior**
i did not expect to fall off in the queue

**Comment by KarlOfDuty** [comment]
This is an issue in the minecraft client, nothing we can change.
