### ISSUE TITLE
[Feature] Queue check before joining the world

### ISSUE THREAD

**Issue by Grinfi34** [EarthMC/Issue-Tracker#535]
Introduce a "Type /join to enter the world" when reaching 1 in the queue to avoid Afk players entering the world.

*Eficiency: Queue is taking around 3 hours long or more. A lot of players join the world without noticing and waste 15 min of a server slot just to get kicked. Cutting this unaware access may reduce about 1 hour of afk queue.
*Safety: The abrupt join is dangerous if you disconected in a pvp zone - Risking to lose all items in only a minute out.

Details of the project:
*15 minutes to do the /Join. Then get kicked from the server.
*After 1 minute with no answer, or when a new space is avaliable, the /Join command is enabled for the next in queue
*The /join brings you to a queue that automatically send you to the world (same as now). This one shall take from no time to a few minutes.

**Comment by KarlOfDuty** [comment]
This would significantly slow down the queue so I don't think it would be a great idea.
