### ISSUE TITLE
[Bug] cant use towny map

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#536]
**Server**
Towny

**Describe the bug**
No permissions for /resident toggle map or /towny map

**To Reproduce**
Do the commands as a player

**Expected behavior**
I see the map

**Comment by CloakedEagle** [comment]
Do you mean players can't toggle their visibility on the dynmap?

**Comment by DasCodes** [comment]
@shirazmatas

**Comment by shirazmatas** [comment]
They can't see the Towny map in-game anymore

**Comment by shirazmatas** [comment]
fixed by itself
