### ISSUE TITLE
[BUG] Mob stacking

### ISSUE THREAD

**Issue by Zonzei** [EarthMC/Issue-Tracker#537]
**Server**
Earthmc.net

**Describe the bug**
Stacked mobs randomly disappear.

**To Reproduce**
1. Have sheeps/cows/chicken/etc
2. Crappy plugin stacks them
3. ...
4. Get back later and your stack of mobs has turned to just single mob.

**Expected behavior**
Stack should save the amount of mobs regardless of if you log out or travel away from the mobs or not stacked in the first place.

**Additional context**
Tired of having to breed my sheep over and over again to get decent supply of wool.
Tired of using more eggs to spawn 10 chicken than what they lay before 9 of them randomly disappear.
Tired of hitting stack of 8 cows with my looting III sword get 3 leather as a drop and see the entire stack of cows disappear.

**Comment by WhitPlayzYT** [comment]
happened to me too

**Comment by sjolinder** [comment]
Have had this happen to me multiple times. Tends to happen when they are stacked and I try to bread them.

**Comment by Warriorrrr** [comment]
Mob stacking is even more broken since the restart, even though Fix said they were fixed. All of my cows have destacked/disappeared because of it. Breeding used to work, but not anymore.

**Comment by Twitchyyy** [comment]
Also, the mob numbers are clearly fucked on the code. Killed 256 pigs with a looting III to get 46 cooked porkchops..... yay

**Comment by Zonzei** [comment]
[Video example](https://gfycat.com/FlamboyantCrazyAnole) of breeding working great. Can we just get rid of this shitty plugin already.
