### ISSUE TITLE
Supporter Rank not given and not on /list

### ISSUE THREAD

**Issue by DimitriFTW** [EarthMC/Issue-Tracker#538]
**Server**
EarthMC Towny (not classic or factions)

**Describe the bug**
I basically logged in again got straight into the server with the queue priority I purchased. I then realised that supporter rank was a thing that exists and people in the server were stating "you must donate queue priority to people" but I have already done it to 2 others under my username aswell. I'm also not even appearing on the queue priority /list. (even though it works and everything)

**Expected behavior**
I believed that I should have the rank and be on the /list

**Additional context**
Sorry, if I am understanding this idea wrong or making massive mistakes. Thanks in advanced

**Comment by FutureCW** [comment]
Supporter is for people who donated before they removed actual donator ranks, and not priority

**Comment by DasCodes** [comment]
I apologize for the misunderstanding, we are not offering **Supporter** rank at the moment. Only **Queue Priority** is available for purchase.
