### ISSUE TITLE
Buy the priority but didn't get it ingame

### ISSUE THREAD

**Issue by ahdiua** [EarthMC/Issue-Tracker#539]
**Server**
Towny

**Describe the bug**
Buy the priority at May 12th. But didnt get it ingane

**To Reproduce**

**Expected behavior**
just gift
![Screenshot_20190517_213701](https://user-images.githubusercontent.com/37497758/57931958-3b3a6680-78a9-11e9-9091-4521d1997304.jpg)
![Screenshot_20190517_213112_com paypal android p2pmobile](https://user-images.githubusercontent.com/37497758/57931955-3aa1d000-78a9-11e9-9249-9faf76cb3c93.jpg)

 priority in shop.earthmc.net.

**Screenshots**

**Additional context**
![Uploading Screenshot_20190517_213112_com.paypal.android.p2pmobile.jpg…]()
![Uploading Screenshot_20190517_213701.jpg…]()

**Comment by dascodes** [comment]
This isn't the place to seek support for that but I'll tag the owner.
@FixTheAdmin
