### ISSUE TITLE
Queue is being a bitch

### ISSUE THREAD

**Issue by ARKASKING** [EarthMC/Issue-Tracker#540]
I was waiting in the queue for 6 hours to get into 85th place until when I was disconnected. When I rejoined I was back at 289. 

Could you please fix this issue?

**Comment by Pengun78** [comment]
Lol i lost so much active friends bc of the queue my nation is literally dying rn

**Comment by ARKASKING** [comment]
rip

**Comment by KarlOfDuty** [comment]
Queue now properly remembers players again.
