### ISSUE TITLE
Add more language specific chat

### ISSUE THREAD

**Issue by DasCodes** [EarthMC/Issue-Tracker#541]
**Describe the solution you'd like**
As we have an increased number of players from China, France, and Russia it's hard for players to communicate in /global chat when there are so many players speaking in different languages. So I suggest adding /Chinese, /French, /Russian or maybe in short form /ch, /fr, /ru.

**Comment by HectorMowsMyLawn** [comment]
To add onto that, it might be a good idea to add a feature where if it detects common words in those languages, like bonjour it will encourage you to use /fr to use french chat, and french chat should not show in normal chat like Spanish does now.

**Comment by Warriorrrr** [comment]
The detecting common words thing would in my opinion be helfpful & hopefully decrease the amount of players (especially new players) talking languages other than English in chat. Maybe even a new staff rank, like Helper to moderate these channels, so mods can do whatever else they're busy with.
Also, you can choose not to show the spanish chat in general by typing /leave spanish.

**Comment by DasCodes** [comment]
New chats are available now in-game.
