### ISSUE TITLE
[BUG] Donators cannot do /list

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#543]
Pretty simple donators can't do /list. And it's something we paid our good money for.

**Comment by WhitPlayzYT** [comment]
it was always able to be used by normal people too its just not working recently

**Comment by shirazmatas** [comment]
Duplicate issue

**Comment by DasCodes** [comment]
Wait this is not the one which is duplicate.

**Comment by DasCodes** [comment]
For more information #560.
