### ISSUE TITLE
I can make a working support bot for EarthMC servers

### ISSUE THREAD

**Issue by xParadoxical69** [EarthMC/Issue-Tracker#544]
I couldn't message Karl on discord so i think this is the most suitable place for it xd.

So I know Tickety currently has some problems and they need to rewrite it. But recently there's a lot of ban appeals on the earthmc support server, so I came up with the idea that I could just make my own support bot for the two earthmc discord servers. I know JavaScript well, so with discord.js documentation it's an easy thing to do. My bot would work in the same way as the Tickety bot (each ticket is a separate channel, all ticket channels are in a hidden channel category, there's a command to close the ticket, transcripts on DM, etc etc).
I have already made about a 1/4 of the bot, so I hope you will accept my contribution.

**Comment by KarlOfDuty** [comment]
Maybe? Could you link your repo? I already have one I've started working on but I can have a look.

**Comment by xParadoxical69** [comment]
https://github.com/xParadoxical69/discord-ticketbot

**Comment by xParadoxical69** [comment]
@KarlOfDuty tickety v3 with very basic features is available to use since 3h while they work on a fix for v5. Also you shouldn't touch -setmsg because it sets the same message for all servers. https://discordapp.com/oauth2/authorize?&client_id=583358320790863882&scope=bot&permissions=8

**Comment by KarlOfDuty** [comment]
Yes, I know I was the one who wrote that in the first place... As it is broken AF we will not be using it.

Anyway, as for your bot we are planning for functionality that's a bit different to what yours has. You're welcome to contribute to mine whenever I get that set up though.
