### ISSUE TITLE
not authenticated with Minecraft.net

### ISSUE THREAD

**Issue by notarealboxlol** [EarthMC/Issue-Tracker#546]
when I try to join the server it appears this message "Not authenticated with Minecraft.net". I tried everything and it don't work. Please help I want to play this server so much

**Comment by WhitPlayzYT** [comment]
does it work when u try to join other servers?

**Comment by notarealboxlol** [comment]
no, it doesn't

**Comment by notarealboxlol** [comment]
when I try to join other servers that doesn't happen

**Comment by DasCodes** [comment]
🤔 Have you tried logging out of your Minecraft account in the Minecraft launcher?

**Comment by notarealboxlol** [comment]
yes, I did, but it doesn't work

**Comment by xParadoxical69** [comment]
earthmc doesn't allow cracked accounts to connect.
this error happens when you try to connect to a server with cracked account

**Comment by DasCodes** [comment]
😅

**Comment by shirazmatas** [comment]
@notarealboxlol Do you use a cracked account?
