### ISSUE TITLE
Mobs stopped spawning in Nether

### ISSUE THREAD

**Issue by phillips8** [EarthMC/Issue-Tracker#547]
**Describe the issue**
I set up an area to spawn wither skeletons, which also attracts all the mobs from the Nether. As of today (2019-05-21) there seems to be no mobs spawning and this is with me standing and checking for almost 2 hours in the Nether. I'm just wanting to bring this to your attention as hopefully this can be fixed, or if this was intentionally done. :( Thank you for your time 

**Coordinates**
Nether 

**Screenshots**
![2019-05-21_00 10 57](https://user-images.githubusercontent.com/50856843/58067880-12da9280-7b5d-11e9-87be-238a93e17446.png)
![2019-05-21_00 10 38](https://user-images.githubusercontent.com/50856843/58067883-1837dd00-7b5d-11e9-8926-074446d21322.png)

**Comment by DasCodes** [comment]
This might be related to server lag, as the server disables mob spawning when running at certain TPS. Need more info on this.

**Comment by phillips8** [comment]
They seem to be spawning, I think your right the tps were probably low sorry for the ticket
