### ISSUE TITLE
[Bug] Written books don't work with Sign Shops after 1 day

### ISSUE THREAD

**Issue by Twitchyyy** [EarthMC/Issue-Tracker#549]
**Server**
Towny

**Describe the bug**
Last night I was able to sell copy of copy written books through sign shops. Now, when placing a copy of copy written book in sign shop,  the sign will end up stead selling an "original" of nothing. 

**To Reproduce**
-Create shop sign with [item]
-click to sell a copy of copy written book
-Set gold OR set item trade amount (I was using gold nuggets, in this case 3)
-Assign chest and put copy of copy books in it
-click on sign to buy, scroll mouse over item to read "original"

**Expected behavior**
I expected for the item to sell copy of copy written books. Example, I have 2 other working shops next to the broken one at 1687, 63, -6360

**Screenshots**
I would add a screen to compare the broken vs working, but I do see the icon as "original" on those too. However, those are trading normally despite the item icon looking off.

**Comment by Twitchyyy** [comment]
Update (if this is even being looked at) it appears to be an issue of page count? Formatting? It's unclear

**Comment by KarlOfDuty** [comment]
This is something that I believe has been worked on by the dev, in any case it should go on their issue tracker and not ours.
