### ISSUE TITLE
[Idea] Custom Recipes with coded .json files. (With Explanation)

### ISSUE THREAD

**Issue by phillips8** [EarthMC/Issue-Tracker#550]
So overall the server lately has been wonderful. I thank all the staff team for there dedication towards improving the playing experience. With the decreased lag and accessibility of getting sea lanterns and prismirine, have not stopped using the new blocks. 

However, as I must ask for more, I decided to post pictures and files with code as a suggestion for further idea. These are just ideas. Now let me explain these recipes. Also included are the .json files with the code incorporated for easy work.

**Sheep and Cow Eggs:** With an egg, clicking a spawner changes such egg, which is great. Now the problem lies with the servers decrease to entities and mobs. So Cows and Sheep are highly needed for wool, and leather, so why not make that a little easier (not to easy tho). I have created an egg recipe for both sheep and cow. 
![Sheep Egg](https://user-images.githubusercontent.com/50856843/58144859-1eda5900-7c1e-11e9-93e8-0f7b5b3ad65f.PNG)
![Cow Egg](https://user-images.githubusercontent.com/50856843/58144869-2699fd80-7c1e-11e9-918d-5035d1f105a0.PNG)

**End Rod:** End rods are another light source which are used greatly with many things, more of an ascetic block but one which could be used if we had it. So here is that new recipe idea. 
![End Rod](https://user-images.githubusercontent.com/50856843/58144930-5b0db980-7c1e-11e9-844d-a5c07cfd2434.PNG)

**End Stone:** End stone may look ugly, but can be used for end stone brick. And what better way to get rid of Diorite then to smelt it up into end stone. In the .json file I do have the experience level set to 0.1 as I thought you guys can be the ones to set that if this is something you want to add. 
![End Stone](https://user-images.githubusercontent.com/50856843/58144879-31549280-7c1e-11e9-8a59-840ab94dafdf.PNG)

Now this one is a very huge idea, and an expensive recipe, but maybe ;) but a **shulker egg**, which can be used on spawners, however I made this recipe very expensive so that its a far end game grind item. 
![Shulker Egg](https://user-images.githubusercontent.com/50856843/58145035-b3dd5200-7c1e-11e9-91d6-783ee544b0fa.PNG)

**Code files for all recipes shown** 
[Recipe Folder.zip](https://github.com/EarthMC/EarthMC.net/files/3205427/Recipe.Folder.zip)

Thank you for your time and I hope I can get feedback as well as ideas on these. 

~phillips

**Comment by phillips8** [comment]
Sorry about that. Also would it be okay to suggest a recipe for sand. I only suggest because with earthMC growing and with multiple recipes needing sand now, the deserts will soon start to run out, so a cobble > sand in a crafting table doesn't seem to bad, either way you have time mine that cobble. :)

**Comment by DasCodes** [comment]
I personally don't think that would be necessary, as you can always request for a rollback in the wilderness.

**Comment by WhitPlayzYT** [comment]
wait you can request rollback just to get more sand? XD

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/58909020-a8d2f900-86d7-11e9-960a-d6491548aad3.png)

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/58909072-ca33e500-86d7-11e9-8be7-22bdb75d3fc9.png)

**Comment by Pengun78** [comment]
It seems that Iceland is nothing more but old ruins of a once great nation...when you explore the forgotten towns its quite scary...

**Comment by KarlOfDuty** [comment]
I've added the end rods, I will not be adding the rest. [172da87afb769870e6b71aebe2fd65f6c377df76](https://github.com/EarthMC/EMCRecipies/commit/172da87afb769870e6b71aebe2fd65f6c377df76)
