### ISSUE TITLE
[Bug] MCMMO potions don't work w/sign shops

### ISSUE THREAD

**Issue by Twitchyyy** [EarthMC/Issue-Tracker#551]
self explainable. MCMMO potions will not open up a sign shop GUI

**Comment by DasCodes** [comment]
Time to bug @creatorfromhell. 😛

**Comment by watergod1234** [comment]
Nor do named items work.

**Comment by Twitchyyy** [comment]
Nor do written books over it seems 10 pages

**Comment by KarlOfDuty** [comment]
This is unfixable according to the developer.
