### ISSUE TITLE
[BUG] Gold dissapeared from my inventory

### ISSUE THREAD

**Issue by xPadpai** [EarthMC/Issue-Tracker#552]
I got donated 30g by a guy, the gold didnt appear neither on the ground nor inventory

https://images-ext-1.discordapp.net/external/l0ZEPGGWk8oo5b8qTsMcSnMT7VqyW5nGDe_eEpuUkvM/%3Fwidth%3D1191%26height%3D670/https/media.discordapp.net/attachments/564442583946887169/581096786568151053/unknown.png

https://media.discordapp.net/attachments/580427600992796736/581097759625445396/unknown.png?width=1191&height=670

On the screens, you can see that a guy called jemenik donated me 30g
And after coming to the spawn, the gold dissapeared
The gold wasn't neither in the cave or in the town's spawn at my equipment or in ground.

**Comment by KarlOfDuty** [comment]
Was your inventory full at the time?

**Comment by xPadpai** [comment]
i dropped cobblestone from my inventory to get a place for gold, i couldnt find them on the ground or in my equipment

**Comment by xPadpai** [comment]
@DasCodes

**Comment by DasCodes** [comment]
This sounds more like a support case.
@xPadpai Please make another ticket when requesting a new feature.
