### ISSUE TITLE
[Bug] my 360 gold dissapeared from my town bank this week and my ticket is being ignored

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#553]
**Server**
Emc

**Describe the bug**
Nobody in my town has councillor yet like this month my 360 gold just dissapeared

**Expected behavior**
360g in my bank

**Additional context**
As my ticket is being ignored with several pings to the mods i report it here

**Comment by DasCodes** [comment]
I think you got your refund plus this is not a place to seek support.
