### ISSUE TITLE
Items disappearing from furnace.

### ISSUE THREAD

**Issue by chefmai** [EarthMC/Issue-Tracker#555]
**Server**
Towny

**Describe the bug**
After placing coal and for example iron (full stacks) into the furnace they disappear from the furnace. I have had it on 2 different days now, and re-logging does not help/bring items back. the items disappear in mid-game, not while logging out and back in.  

**Additional context**
I have not heard of anyone else (yet) having the same issue. But it makes very hard for new players to start with anything, if their iron or gold jsut disappears from the furnace. and you can not smelt more than 3-6 pieces at a time. because maybe the glitch will disappear it again.
I do not have my house/furnaces on town area. just on free unclaimed land. Also i have not joined any towns.

**Comment by KarlOfDuty** [comment]
Is this still an issue? I have not heard anyone else ever mention it as you say.
