### ISSUE TITLE
[Feature] Donator Only Days

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#556]
**Is your feature request related to a problem? Please describe.**
I personally think that every so often the server should be on donator (and priority) only mode so people can get items that are practically unobtainable in a full server

**Describe the solution you'd like**
Basically, once every approximately two weeks for one day (Saturday or Sunday) the server would only allow donators (and priority members) to join the server.

**Additional context**
I guarantee many people besides me want this to come true

**Comment by ZestyPhallus** [comment]
Although this sounds great and would definitely benefit our donators / priority members, it'd be a blatant pay-to-win move. I doubt they'll move forward with that.
It was a generous of them to give donator-access during maintenance but I don't expect it to return anytime soon.

**Comment by shirazmatas** [comment]
(saturday or sunday) the most popular times on the server 🤔

**Comment by 32Lavenugly** [comment]
Yes

**Comment by KarlOfDuty** [comment]
While the donator only days were pretty nice back when the server was in maintenance mode I don't think it would be a good idea as a regular thing as regular players would lose a lot of time they could have been playing on the server which is an advantage to donators. 

If for instance a nation with a lot of donators is enemy with a nation with only a few one could see how the nation with a lot of donators would have a gameplay advantage.
