### ISSUE TITLE
Discord Bot For Nation Servers

### ISSUE THREAD

**Issue by w0265261** [EarthMC/Issue-Tracker#557]
We have a large problem with people jumping from nation server to nation server advertising other servers. 

What I would like to be able to do is have a discord bot nations could add that would sync discord bans between nations servers and the EarthMC discord. This would obviously would have to be only actionable from EarthMC moderators to avoid abuse.

**Comment by Ultil0l** [comment]
No.

**Comment by 32Lavenugly** [comment]
no

**Comment by DasCodes** [comment]
🤔

**Comment by KarlOfDuty** [comment]
I'll think about it.

**Comment by KarlOfDuty** [comment]
I think this wouldn't work very well as many nation servers intentionally have banned players on them as well.
