### ISSUE TITLE
[Mechanic] Broadcasted Mob Zone

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#558]
### Title to be workshopped, but essentially, the idea is similar to PUBG's "red zone"or FO76's nuke zone (except less of a disaster)

The idea is, have mobs allowed to spawn, but not actively be spawning as I believe it currently is.

Somehow generate random coordinates or just drink a few, close your eyes and point on the map and have a mod confirm the blast zone. Mods can watch the chaos from above, while gamers battle each other for valuable resources.

### I'll use the map for Factions as an example of how the blast zone will look depending on how freely you can use the red box
![factions](https://user-images.githubusercontent.com/47764467/58290118-6e7b6a80-7d6d-11e9-891f-ac3db25a7937.PNG)

The coordinates will be broadcasted to global. Wherever that may be, mobs will be spawning at a set time, for a certain duration of when "the nuke has landed".

There are many factors to keep in mind: PVP being enabled, DynamicMap showing herds of people flocking toward the coordinates--which could potentially be a temporary 'war' alternative, and hostile mobs being incredibly scarce.

Perhaps it's an ambitious request, but if possible, it'd definitely be a temporary resolve to various issues that everyone can enjoy.

**Comment by FutureCW** [comment]
This is by far the best suggestion I've seen since Watergod's War Days suggestion.

**Comment by DasCodes** [comment]
This is a suggestion for towny right? @ZestyPhallus

**Comment by KarlOfDuty** [comment]
Shouldn't be an issue anymore.
