### ISSUE TITLE
Claim bug on Faction

### ISSUE THREAD

**Issue by DangerstickM** [EarthMC/Issue-Tracker#559]
**Server**
Factions

**Describe the bug**
I can't claim more land in my (newly) made faction. It keeps telling me "Your claim is outside the border." Even tho i'm standing right where I made my faction or a block or 2 away.

**Expected behavior**
Help so I can claim more.

**Screenshots**
http://prntscr.com/nskjuj

**Username**
My IGN is Dangerstick

**Comment by KarlOfDuty** [comment]
Please attach a screenshot of where you are on the dynmap when you use the command.

**Comment by DangerstickM** [comment]
Well after the beta reset I can claim. When I made this it was the first beta round. o no worries sorry .-.
