### ISSUE TITLE
Donator/Priority

### ISSUE THREAD

**Issue by 32Lavenugly** [EarthMC/Issue-Tracker#561]
Earthmc donator serves no purpose. All features people paid 100+ USD for are gone. Can these features be brought back? Like /online, this feature has been removed. All donator is serving is priority. And most people bought the donator packs worth more then 10 USD. 

Personally, I dont think priority should get the same priority as donator, and donator should get /online back. Other features like the plus signs and /sethome(I think having set home would be nice) would make donator different from priority.

**Comment by FutureCW** [comment]
Donators have tiered priority, like frost donator has the highest priority and then down the chain

**Comment by DasCodes** [comment]
Donors have access to many commands that a player with priority doesn't.
