### ISSUE TITLE
[FACTIONS] Firespread

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#563]
Factions is a PvP based type of gameplay and very aggressive. And I think that it would be really cool if we could see some of that aggressive fire spread on the servers to burn other people their factions and such.

**Comment by KarlOfDuty** [comment]
Many areas of emc are filled with very dense forests so having fire spread on would likely create a forest fire big enough to massively lag the server and also destroy giant areas for no reason.
