### ISSUE TITLE
[World] Factions, can the server be upgraded

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/Issue-Tracker#564]
This big deal was made out of being unable to upgrade the towny server and it running on the best servers it can with the plugins and such but does this apply to the factions server or does that not have the same problem

There are tons of faction servers supporting many players and far less lag + mob spawns

just want mobs man

**Comment by DasCodes** [comment]
I think mobs spawn is enabled?

**Comment by KarlOfDuty** [comment]
The factions server seems to run perfectly at 100 players which the towny server doesn't even get close to so it will probably be able to have a much higher player limit and some more features like more mobs. We will slowly add more things to it over time.
