### ISSUE TITLE
[BUG] FACTIONS people in faction cant access brewing stand 

### ISSUE THREAD

**Issue by sawyerc18** [EarthMC/Issue-Tracker#565]
**Server**
Factions

**Describe the bug**
Cant access brewing stands unless u are leader

**To Reproduce**
i switched leader and whoever is leader can open brewing stands no one else

**Expected behavior**
to open brewing stand

**Screenshots**
-

**Additional context**
-

**Comment by FutureLemon** [comment]
Do /f perm and enable 'Items' for the ranks you want to be able to access brewing stands. 
![image](https://user-images.githubusercontent.com/44688587/58370415-98b46000-7f06-11e9-90c3-82b86f90aff8.png)

**Comment by sawyerc18** [comment]
he was coleader and had every perm. i can try again today but it wasnt working at 2am est for me

**Comment by DasCodes** [comment]
Is it working now? @sawyerc18

**Comment by sawyerc18** [comment]
no it is not @dascodes

**Comment by DasCodes** [comment]
Seems to work when you promote them to mod rank and put them back as a normal user.

**Comment by KarlOfDuty** [comment]
Should be fixed.
