### ISSUE TITLE
[BUG] Items glitch above blocks

### ISSUE THREAD

**Issue by FreezeeBurn** [EarthMC/Issue-Tracker#567]
**Server**
This issue affects both servers, the towny and faction server.

**Describe the bug**
The current plugin that stacks items in bunches as to reduce lag on the server will
glitch items into blocks above it which will force it to go above the next block, and so on.

**To Reproduce**
1. Mine a block that has another block above it
2. Repeat untill the item stack glitches into the ceiling

**Expected behavior**
When you mine blocks that have another block above it, the item will glitch into the block
above it and moved to the top of the block stack of whatever was there
so granted, if there is no caves in the way a glitched item would be
pushed all the way to the surface from the bottom of a mineshaft.

This happens with any item, from gold ore to cobble stone.

This bug happens less with faster mining speed as you can mine blocks fast enough
to move the stack to a block that has nothing above it, and be able to get your items
without having it pushed to the surface

**Screenshots**
Even better, I created a video showing me reproducing the glitch
https://youtu.be/cjCvolqiT_4

**Additional context**
I have lost so many stacks of ore due to this problem, it is ruining my experience in the game,
enough to the point where I have to open a ticket for this.

**Comment by FutureLemon** [comment]
I keep having the same problem please fix this.

**Comment by FutureCW** [comment]
Happened on beta factions too.

**Comment by DasCodes** [comment]
And I was wondering how was I losing ores.

**Comment by KarlOfDuty** [comment]
This is not something fixable, it's just how minecraft multiplayer works.
