### ISSUE TITLE
[BUG] Players suddenly have new player's protection

### ISSUE THREAD

**Issue by ooJOSHUA66oo** [EarthMC/Issue-Tracker#568]
**Server**
Towny

**Describe the bug**
When trying to attack players I get the message "you are protected from pvp so you cannot attack others"

**To Reproduce**
Attack me, or be attacked by me.

**Expected behavior**
Damage

**Additional context**
This happened in wilderness and nations were not allied.
I did join the faction server for the first time today, maybe the protection came from there.

**Comment by Kyoris** [comment]
newbie protection. Also you'd appreciate it if a guy in full diamond with a god sword comes up to you

**Comment by alekb1** [comment]
Newbie protection are a curse on the server. We don't need 5000 noobs, we need 500 active players that can rise from defeat and become stronger.

**Comment by Pengun78** [comment]
I have this too and i am not a newbie idk how i suddenly have newbie protection

**Comment by ooJOSHUA66oo** [comment]
However this happened on the towny server I am not new on the towny server.

**Comment by DasCodes** [comment]
@Pengun78 @ooJOSHUA66oo Do you guys still have the protection?

**Comment by DasCodes** [comment]
Did this happen after you went on factions?

**Comment by KarlOfDuty** [comment]
Fixed.
