### ISSUE TITLE
Add gold to realistic town/nation names

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#57]
Add 5-10 gold per realistic town and add 10 gold per realistic nation as a reward.

**Comment by FixTheAdmin** [comment]
I wouldn't mind as long as we keep track of which town got the gold. Perhaps a limited time the first couple of weeks/months of Terra Nova to get us started.

**Comment by KarlOfDuty** [comment]
This idea has been abandoned for now.
