### ISSUE TITLE
Going on factions to have pvp prot on towny

### ISSUE THREAD

**Issue by Skater2323** [EarthMC/Issue-Tracker#572]
Well In Emc , me YellowVictini , and Fritzstick made a Somerset Jewion log . She then went into factions , logged back in , so she can't die and have protected with pvp 
![Skrrtt](https://user-images.githubusercontent.com/50536485/58387575-a9380980-7fde-11e9-8d33-960c3c9eacad.png)
Please report this as a bug thank you

**Comment by DasCodes** [comment]
Oh good finding @Skater2323, TA.

**Comment by KarlOfDuty** [comment]
Fixed.
