### ISSUE TITLE
[Feature] [Factions]

### ISSUE THREAD

**Issue by Refreshedibis** [EarthMC/Issue-Tracker#573]
if u took away actual faction weird lava wall and water bases and also kinda did some rollback with tnt or straight up get rid of it on factions server on emc. wouldnt that be basically a decent war plugin as you can kill people (enemying them first)  and make them lose power and overclaim their land? (i know its a extreme suggestion)

**Comment by FutureCW** [comment]
Water and lava walls are key features to bases on factions and probably won’t be removed

**Comment by Refreshedibis** [comment]
> Water and lava walls are key features to bases on factions and probably won’t be removed
i did say it was a "extreme suggestion"

**Comment by FutureLemon** [comment]
Tbh, the power feature to overclaim and PvP in claims would fit perfect for a PvP type of Towny but EMC's Towny is more peacefull so they wouldn't add PvP in claims.

**Comment by Refreshedibis** [comment]
> Tbh, the power feature to overclaim and PvP in claims would fit perfect for a PvP type of Towny but EMC's Towny is more peacefull so they wouldn't add PvP in claims.

i doubt the majority of players always wants to be peaceful 24/7

**Comment by FutureLemon** [comment]
> > Tbh, the power feature to overclaim and PvP in claims would fit perfect for a PvP type of Towny but EMC's Towny is more peacefull so they wouldn't add PvP in claims.
> 
> i doubt the majority of players always wants to be peaceful 24/7

They do tho, a whole nation invaded my nation, but we can't do anything about them because they don't PvP and want to stay "peacefull" during their invasion.

**Comment by Refreshedibis** [comment]
> > > Tbh, the power feature to overclaim and PvP in claims would fit perfect for a PvP type of Towny but EMC's Towny is more peacefull so they wouldn't add PvP in claims.
> > 
> > 
> > i doubt the majority of players always wants to be peaceful 24/7
> 
> They do tho, a whole nation invaded my nation, but we can't do anything about them because they don't PvP and want to stay "peacefull" during their invasion.

thats why we need it

**Comment by shirazmatas** [comment]
Please follow format

**Comment by KarlOfDuty** [comment]
We will not be removing lava walls and tnt from factions.
