### ISSUE TITLE
[BUG] Stuck in Nether Portal

### ISSUE THREAD

**Issue by Degabait** [EarthMC/Issue-Tracker#574]
**Server**
Factions

**Describe the bug**
Stuck in Nether Portal, can't break

**To Reproduce**
1. Leave Nether
2. Get stuck in faction portal
3.Can't break or TP back

**Expected behavior**
Being able to break portal

**Screenshots**
![2019-05-27_01 00 40](https://user-images.githubusercontent.com/51075553/58405203-c212e000-801b-11e9-90f2-16ae2ed3da34.png)
![2019-05-27_01 02 23](https://user-images.githubusercontent.com/51075553/58405204-c2ab7680-801b-11e9-9c2d-6d94bb338ddf.png)

**Additional context**

**Comment by DasCodes** [comment]
Not a bug, it's a normal game mechanic. Also, this is not a place to seek support, use this [Discord](https://discord.gg/EZBYmpp) instead.
