### ISSUE TITLE
Animals and Spawners

### ISSUE THREAD

**Issue by DangerstickM** [EarthMC/Issue-Tracker#575]
**Is your feature request related to a problem? Please describe.**
I've now been looking for cows, sheeps, pigs .m.m all over the map, and I rarely find any animals, which is a big bummer, for one, they have the main resource of food, and other valuable stuff as of leather or wool.

**Describe the solution you'd like**
I would like that the servers (Both on towny and factions) get higher rates for animal, since right they seem "rare'er" than gold. And if higher rates aren't possible then get an pay option, for example a kit, named "Animal Farmer" or some sort which gives you a spawn of the choice of animal.

**Comment by Kyoris** [comment]
I wouldn't be against the idea of having animals be more common but considering the amount of players active in the server at this point, making animals more common would be more or less impossible for the sake of performance.

you usually can find a person or two selling farm animals, and you can get pig spawners from breaking a blaze spawner with silk touch (you get a pig spawner and a blaze egg). And for food you can just plant some crops (potatoes and carrots do quite well).

**Comment by DasCodes** [comment]
The server disables mob spawning when it's lagging, to prevent more server lag. But they do spawn normally when it's not lagging.
