### ISSUE TITLE
Add back normal login to the server

### ISSUE THREAD

**Issue by Skater2323** [EarthMC/Issue-Tracker#578]
On emc a few months back , There was 80 people in the server with donators pushing the limit of this . No queue , or anything causing lag , So why don't they bring it back ? I understand all of these knew youtubers making videos has a toll on the queue and emc would have to raise the queue . But what if it was just like December and months before times to the login of the server ?

**Comment by KarlOfDuty** [comment]
Please repost and state specifically what you want to happen, I don't understand what you want.
