### ISSUE TITLE
1 gold nugget for town-upkeep

### ISSUE THREAD

**Issue by MSatrokrm** [EarthMC/Issue-Tracker#58]
![nugget](https://user-images.githubusercontent.com/23727003/47640189-2eba1080-db07-11e8-93ed-302cbaad6314.JPG)

Pretty much says everything ^

Since gold is difficult to obtain, a 1 or 2 gold nugget upkeep per day would be reasonable.

**Comment by JakubdotPLGB** [comment]
That's a terrible idea xd

**Comment by Synargle** [comment]
I think this is a good idea. If it's added best make sure people know.

**Comment by JakubdotPLGB** [comment]
Since gold is very hard to find, I think that should be the monthly upkeep, not the daily upkeep.

**Comment by sharkfynn1012** [comment]
Ehhh, this would just create an unnecessary expense. It's only 1 nugget or so but gold is hard to find as is. We don't need something sucking it away on the daily. Thats why the time one is so good, you get kicked if you don't come on. If anything there should maybe be a quota of time in that 40 day period that you have to be on for. An hour? 30 minutes?

**Comment by Keennoo** [comment]
This sounds like a great idea! It will give responsibilities and keeps town that are dead down. But bring this in not straight away

**Comment by BowShot118** [comment]
Personally I think its' a terrible idea due to the lack of gold, atleast early game, due to how hard it is to gain. It might be better for when the server is more established and players have made themselves stable and gold is more plentiful. But, at least at this point, I think it's a terrible idea.

**Comment by Arganog** [comment]
Keep in mind that on the full release, the server universal income (voting) will be back in place.

Everybody will have access to 12 gold ingots daily just from voting.

With that in mind I would certainly be down for a town upkeep

**Comment by KarlOfDuty** [comment]
Because of the floating point errors caused by this on the old server we have decided that gold nuggets do no longer count as economy items so this is not possible.
