### ISSUE TITLE
[BUG] It's impossible to place an armor stand

### ISSUE THREAD

**Issue by nicosecci** [EarthMC/Issue-Tracker#580]
**Server**
Towny

**Describe the bug**
When an armor stand it's placed, it doesn't appear, and the item isn't given back to the player, making it completely gone.

**To Reproduce**
1. Place an armor stand anywhere 

**Expected behavior**
An armor stand should appear.

**Comment by KarlOfDuty** [comment]
Check if it still happens now.

**Comment by nicosecci** [comment]
now everything works, thanks
