### ISSUE TITLE
[BUG] [Factions] stacked mobs converting into singular mobs, reason found

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#581]
So as some are aware, the server has two settings regarding how mobs act. When the server is full mobs stop spawning, and generally go into a "low maintenance" state. Now when the server is not full, mobs act as normal. So if you like me breed mobs when the server is not full, they will breed as normal and produce offspring. if you breed them when the server is full they don't produce offspring. Now that is generally annoying but you still have a general population of mobs. That's how it used to work. Now adding the stacking plugin will stack all the mobs into a singular mob, like a 18x cow. Fine. When you then try to breed that cow when the server is full, and the mobs is in their low maintenance mode, the 18x cow will convert in to a singular normal cow... When the server is back to it's normal unfilled state, the cow will still be a singular cow, and you now only have one cow, which can not be breed, as you don't have a second one.

**Comment by FutureLemon** [comment]
I can confirm this, I had this happen to my mobs too.

**Comment by KarlOfDuty** [comment]
No longer relevant as the stacking plugin has since been removed.
