### ISSUE TITLE
Devu swearing on the chat

### ISSUE THREAD

**Issue by xParadoxical69** [EarthMC/Issue-Tracker#582]
(took screenshots from https://github.com/EarthMC/Issue-Tracker/issues/569#issuecomment-495962526)
https://media.discordapp.net/attachments/566815520377274377/582018213433573396/2019-05-25_21.25.53.png?width=1202&height=677
https://media.discordapp.net/attachments/566815520377274377/582018228726005760/2019-05-25_21.28.06.png?width=1202&height=677

I searched for these messages in #earthmc-towny channel and from the context I deduced Devu was also unfairly muting/banning people, I'm not sure if it's true tho because EarthMC bot doesn't show warn/mute/ban messages in that channel, and it would be helpful in this situation.

@KarlOfDuty

**Comment by watergod1234** [comment]
Really? Swearing? Who cares about swearing it’s not that big of a deal. Devu’s a good mod overall.

**Comment by xParadoxical69** [comment]
Did you even look at the screenshots? He was calling ppl shits and telling them to shut up (rule 2.4 Toxicity). Lol, that's not an appropriate behavior of a mod who is supposed to enforce the rules and be kind.

**Comment by watergod1234** [comment]
Devu frequents the Niger discord in which she talks in voice chat frequently. FutureCW also frequents the Niger discord, without proper context it may look like she’s being an ass for no reason to FutureCW but I can assure you it wasn’t that. 

And hey, whoever she was referring to being a shit, she was probably right. Though I agree that she probably shouldn’t be saying that, it’s not sufficient for demotion in my opinion.

**Comment by Steadlington** [comment]
I'm not a fan of the new mods but this has no ground. Swearing alone doesn't constitute toxicity in any form, unless it is prolonged and excessive towards another player, which Devu hasn't shown. Perhaps the excessive muting and bad handling of situation may be better grounds for demotion but this is just silly.

**Comment by creatorfromhell** [comment]
http://prntscr.com/nw2qcv

**Comment by Pengun78** [comment]
Creator please make us a war plugin brother

**Comment by xParadoxical69** [comment]
@Steadlington Well, you are right, but imo mod shouldn't call anyone a "shit" on the public chat, it just doesn't look good and can make other opinions worse about her.

Idk. If you all say that's acceptable then it's ok.

**Comment by creatorfromhell** [comment]
@xParadoxical69 what's your ign btw just for reference purposes?

**Comment by DasCodes** [comment]
I would very much like to see the entire conversation instead of two screenshots were taken when she swore.

**Comment by xParadoxical69** [comment]
Currently GottaGetPasta, previously pdxx_, xParadoxical_. I was playing on the server only on xParadoxical_.

**Comment by Steadlington** [comment]
This thread should be closed.

**Comment by DasCodes** [comment]
@Steadlington Y U no have us fun? :pepe:

**Comment by xParadoxical69** [comment]
no fun allowed >:]

**Comment by shirazmatas** [comment]
Sometimes in voice chat devy says "fuck" instead of "fruit". I think we should put a stop to this

**Comment by BowShot118** [comment]
Now that's bad, staff really have gone *fricking* insane!

**Comment by xParadoxical69** [comment]
tfw you simply point out something and say what do you personally think about it, and you see ppl making fun of 2yo meme

eternal disappointment in our society

**Comment by FutureCW** [comment]
oh gosh oh frick devy said a naughty word

**Comment by ZestyPhallus** [comment]
omg it's futurecw! the one in the screenshot omg!!
