### ISSUE TITLE
[Feature] higher render distance

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#583]
**Is your feature request related to a problem? Please describe.**
Have higher render distance for everyone except for youtubers only, it just makes the game look much better, now you can only see some chunks and have to explore a whole area just to have all the chunks loaded which is just ugly, i saw truemus vid and it looks much better

**Describe the solution you'd like**
A higher render distance

**Additional context**
32Gold is bi

**Comment by Pengun78** [comment]
Its pretty unfair how youtubers only get this to buttkiss them

**Comment by Kyoris** [comment]
I agree, there should be equal treatment of all players

**Comment by Pengun78** [comment]
Well yeah that too, but to be honest higher render distance is really needed

**Comment by DarkRush449** [comment]
BuT tHe LaG

**Comment by KarlOfDuty** [comment]
This will not be possible unless we also reduce the player count of the server.

**Comment by Pengun78** [comment]
bruh why

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/58765580-bcb21a00-8574-11e9-9fe5-9fa762d3bca5.png)

**Comment by KarlOfDuty** [comment]
More render distance = more chunks loaded = more lag.

**Comment by KarlOfDuty** [comment]
While chunk updates isn't exactly everything when it comes to performance, having more entities loaded is pretty expensive and would only really work on smaller maps when players are closer and thus loading the same chunks.

**Comment by Pengun78** [comment]
But aight
