### ISSUE TITLE
[complain] illegal building near Rostock

### ISSUE THREAD

**Issue by Awers97** [EarthMC/Issue-Tracker#584]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
roll it back maybe warn those who did this as its blocking entrance to my town and its too close to my town.

**Additional context**
screenshots [https://ibb.co/cYSrs8c](url)
[https://ibb.co/FVRRVcY](url)
coords X 1829 Y 71 Z -10059

3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Please note that mayors/kings are responsible for misconfigured town/nation permission settings. Examples of grief:
Cobble monsters - Mountain-like structures that are built using lava and water.
Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
TNT craters.
Mass spawning entities within or around a town (Chickens, Boats, etc.).
3.2	Destroying land in wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or in close proximity to a claimed area. However, any player may request grief to be rolled back even in the wilderness. Breaking railways or ice roads is not allowed even in the wilderness, if willingly connecting two existing towns. This does not only apply to the rails but all blocks the railroad is made of.

**Comment by Awers97** [comment]
3.1	Destroying land around claims.
Players may not damage terrain around claims (griefing). Players breaking this rule will be warned and damage will be rolled back. Players doing this more than once may face a permanent ban. Please note that mayors/kings are responsible for misconfigured town/nation permission settings. Examples of grief:
Cobble monsters - Mountain-like structures that are built using lava and water.
Lava/water curtains - Placing rows of lava/water in the sky to make a wall of falling lava.
TNT craters.
Mass spawning entities within or around a town (Chickens, Boats, etc.).
3.2	Destroying land in wilderness.
Wilderness is defined by Towny as any land not currently claimed. You are allowed to grief structures or terrain as long as they are not within or in close proximity to a claimed area. However, any player may request grief to be rolled back even in the wilderness. Breaking railways or ice roads is not allowed even in the wilderness, if willingly connecting two existing towns. This does not only apply to the rails but all blocks the railroad is made of.

**Comment by DasCodes** [comment]
This is not our support platform. Please use this Discord server for support. [Link](https://discord.gg/EZBYmpp)
