### ISSUE TITLE
[BUG] [FACTIONS] /f tag changing other faction's names

### ISSUE THREAD

**Issue by Darkolop** [EarthMC/Issue-Tracker#585]
I am a leader of a faction and I wanted to change my faction's name from Sovetskaya to Sovet.

I did /f tag Sovet, the command processed and then charged me 32 gold. This gold was pulled from my Ender Chest.

Afterwards, my faction name remained Sovetskaya, but a completely unrelated faction's name, formerly Rage, got changed to Sovet. I essentially payed 32 gold to change another faction's name.

I did not attempt to reproduce the bug, as 32 gold is expensive. 

There is probably a console log where you can see commands given to the SavageFactions plugin and a history of Faction tag changes. I assume that it'd be easy to fix and I just wanted to let the staff know that this bug exists.

![sovet](https://user-images.githubusercontent.com/30184219/58771720-a9f31180-8583-11e9-8c5d-b46ce11594f5.PNG)
![sovetskaya](https://user-images.githubusercontent.com/30184219/58771721-a9f31180-8583-11e9-8ec8-b530def5f10c.PNG)

**Comment by KarlOfDuty** [comment]
Bug should be fixed now that the factions plugin has been updated and is allegedly less buggy.
