### ISSUE TITLE
lily pads

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#586]
Crafting recipe for lily pads

**Comment by sccooottttie** [comment]
Hey @Cactusinapumpkin,

There's no crafting recipe for Lily Pads. But you can obtain them on swamp biomes.

**Comment by DasCodes** [comment]
Any suggestion on the crafting?

**Comment by Warriorrrr** [comment]
Maybe how you would normally make a pressure plate, but with leaves. Going a bit off topic here but maybe also a crafting recipe for vines, because they're incredibly rare. For that recipe you could use leaves in how you would normally craft a ladder.

**Comment by DasCodes** [comment]
Go to Africa or South America, plenty of vines in the forest.

**Comment by Cactusinapumpkin** [comment]
So i looked in 2 of the 5 swamps and found nothing,

![image](https://user-images.githubusercontent.com/48000340/58893618-1e2dd200-86b6-11e9-82c7-5a4dfa26ea5c.png)

**Comment by Cactusinapumpkin** [comment]
Or bone meal swamp water like coral

**Comment by Pengun78** [comment]
That recipe should give 8 lilypads as leaves are way more thick than lilypads. 1 of those blocks could fit like 10 lilypads in them

**Comment by KarlOfDuty** [comment]
Done.

**Comment by WhitPlayzYT** [comment]
ive tried making lilypads with multiple leave types and it isnt working for me at least
