### ISSUE TITLE
Advertising 

### ISSUE THREAD

**Issue by obewan001** [EarthMC/Issue-Tracker#587]
theres a kid spamming in the queue rn https://gyazo.com/e6d7a751c534e976c398a88fe723667b

**Comment by obewan001** [comment]
another one https://gyazo.com/af4e37c92deef6f89f80f1d3d8215ecb

**Comment by Warriorrrr** [comment]
Maybe instead of opening an issue on here, you could've made a ticket on the discord server (If tickety is working), or just reported it to the moderators.

**Comment by DasCodes** [comment]
I appreciate the reports. But please use our [Discord](https://discord.gg/EZBYmpp) instead, to report or seek support in the future.
