### ISSUE TITLE
[Bug] Disappearing gold when town created

### ISSUE THREAD

**Issue by GamingGorillaa** [EarthMC/Issue-Tracker#588]
So, I was the mayor of Vanua, with 1008g in its bank. Me and my friend organized to move to a new town and sell Vanua. I took all the gold and went to my new town's location, which is Winnipeg. I had all the 1008 gold in my enderchest, it was full of other items as well. When I created the town i went to get the gold in my enderchest to transfer it to the town's bank. I take out around 584g and the rest is non-existent. I should have had 944g in the enderchest. Any help would be appreciated.
IGN: GamingGorillaa

**Comment by shirazmatas** [comment]
Please use the format available when creating the bug report.

**Comment by Yazzed1** [comment]
the same thing happened to me but not with that amount.
I managed to recreate the bug.
https://www.reddit.com/r/EarthMC/comments/cdmolm/be_sure_not_to_make_this_mistake_so_you_dont_lose/

**Comment by KarlOfDuty** [comment]
I believe this was solved in a support ticket.
