### ISSUE TITLE
[Plugin] Custom crafting recipes

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#589]
I'd like to add some custom crafting recipe ideas for blocks which one can't get access to in the game or which are almost completely raided. Unfortunately, I don't know how to add a picture of the recipes so I will describe it.

1) Sponge
-Yellow wool in the middle and a water bucket at the top of it.

2) Shulker Box
-Chest in the middle, purple dye at the top middle and gold ingots everywhere else.

3) Corals
-Dye of the respective coral in the middle and grass (not the block) surrounding it.

4) Purple block
-Stonebrick + purple dye

5) Mycelium
-Grass block + grey dye

6) Conduit
-Beacon + water bucket

7) Trident
-One diamond block in the bottom middle, one in the centre and 3 quarz slabs at the top right, top middle and top left

8) Dragon's breath
-glass bottle + lava bucket

By crafting any of those items, I think it's enough to receive only one of each item from crafting

Someone else posted a recipe of an end rod. Could you add that too? I think that's the most important one because it's an important light source and a good looking block at the same time.

It would be nice if you could add those items. It's a shame that such a big server still lacks a lot of these and I think it would improve the experience for every player a lot.

**Comment by Cactusinapumpkin** [comment]
Coral can be obtained by bone mealing tropical water and turned into coral blocks with 9.
Purpur can be added with chorus plants.

**Comment by Lagann311** [comment]
Is there already a recipe for chorus plants or are you suggesting to add one?
Btw is there a list of all custom crafting recipes?

**Comment by Cactusinapumpkin** [comment]
https://github.com/EarthMC/EMCRecipies/commit/d7949b06ee9b06c6463eb9edc526148e1a1183f4

**Comment by WhitPlayzYT** [comment]
you get myclieum with mcmmo by shift right clicking a grass block when you have both types of mushrooms in your inventory

**Comment by Cactusinapumpkin** [comment]
We still need Shulker Boxes, Conduits, chorus flowers, and I guess lingering potions.

![image](https://user-images.githubusercontent.com/48000340/69905391-6897bf00-1378-11ea-8761-ca35502e2b5e.png)

**Comment by Prismary** [comment]
Some of these have since been made obtainable (some are also hard to obtain), pretty sure only purpur blocks, dragon's breath and conduits are missing. Shulker boxes would be quite controversial. Closing this for now as it's very outdated, however recipies for these alongside 1.17 items could be discussed in a new issue.
