### ISSUE TITLE
[World] Mobile River

### ISSUE THREAD

**Issue by Jacob8858** [EarthMC/Issue-Tracker#59]
Please widen the Mobile River. This would be greatly appreciated. I know there are several rivers in NA that make travel impossible. Thanks!

**Comment by KarlOfDuty** [comment]
Add a picture with the entire river marked

**Comment by Jacob8858** [comment]
<img width="831" alt="capture" src="https://user-images.githubusercontent.com/44347988/47680035-22cc5e00-db9c-11e8-8fc2-326a2090e789.PNG">
Basically all of those rivers makes up the Alabama river system. Please widen them. Thanks!

**Comment by PoppyK** [comment]
Done by a player.
