### ISSUE TITLE
[FACTIONS] Add the Obsidian Breaker plugin

### ISSUE THREAD

**Issue by alekb1** [EarthMC/Issue-Tracker#590]
Obsidian is as we all know, quite unbreakable with tnt in vanilla minecraft. While this is a neat feature, it does present a lot of problems on the factions server... Factions is very much about raiding basses, and right now people can simply hide their supplies in obsidian covered chests, and just log out whenever someone comes close by. This is why we need to be able to break obsidian.
I propose this plugin, with a configuration set to 5 tnt blast to destory obsidian :)

https://dev.bukkit.org/projects/obsidianbreaker

**Comment by SnUncle** [comment]
Wither could destory everthing bro

**Comment by KarlOfDuty** [comment]
^^
