### ISSUE TITLE
[Bug] Doors won't open.

### ISSUE THREAD

**Issue by KyleCH** [EarthMC/Issue-Tracker#591]
**Server**
Towny

**Describe the bug**
Trying to open a door (by right clicking) that I have permission to open causes the door to glitch rather than open.

**To Reproduce**
1. Right click door.
2. It doesn't open/glitches (see screenshots)

**Expected behavior**
When I right click on doors I have permission to open, they open.

**Screenshots**
![2019-06-04_21 36 43](https://user-images.githubusercontent.com/10998507/58924580-6aa6fb00-8712-11e9-850b-2e36c325dd04.png)
![2019-06-04_21 36 45](https://user-images.githubusercontent.com/10998507/58924581-6aa6fb00-8712-11e9-9891-270a274cdeae.png)
![2019-06-04_21 36 35](https://user-images.githubusercontent.com/10998507/58924582-6aa6fb00-8712-11e9-9ae6-b91a53433108.png)
![2019-06-04_21 36 39](https://user-images.githubusercontent.com/10998507/58924583-6aa6fb00-8712-11e9-877d-e27eacb362de.png)
![2019-06-04_21 48 57](https://user-images.githubusercontent.com/10998507/58924640-ae9a0000-8712-11e9-9c9a-d1ae0fd0abf3.png)

**Additional context**
I went through a door in the town I'm mayor of (it opened using a pressure plate on the inside of a building). When I tried to open the door to go back inside, it wouldn't open.  This issue is affecting multiple doors (see screenshot 5).

**Comment by KyleCH** [comment]
Pressure plate work file to open doors.
![2019-06-04_21 50 46](https://user-images.githubusercontent.com/10998507/58924690-e3a65280-8712-11e9-91b6-bd3ea0c0d284.png)
![2019-06-04_21 50 50](https://user-images.githubusercontent.com/10998507/58924691-e3a65280-8712-11e9-8102-5349a12c2316.png)

**Comment by WhitPlayzYT** [comment]
If your in 1.14 that could be it

**Comment by KyleCH** [comment]
No, I was on 1.13.2 (with some client side mods, as you can see from the screenshot).

The issue was resolved by disconnecting and reconnecting to the server (without restarting my client).

**Comment by KarlOfDuty** [comment]
This is part of a different issue.
