### ISSUE TITLE
Re-enable cactus farms. 

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#592]
Cactus farms are very needed because they're the only viable way to get XP. The way you get XP through a cactus farm is by continually cooking it through a furnace and taking the green dye to get the XP. Grinding through blaze farms is **very** tedious and it takes forever to even get to level thirty, especially when it's really laggy. 

Please, please re-enable cactus farms. I didn't spend days building my cactus farm for it to be disabled. Thank you.

**Comment by Cactusinapumpkin** [comment]
make auto potato smelter ;)

**Comment by watergod1234** [comment]
> make auto potato smelter ;)

Bro you're literally a god.

**Comment by FutureLemon** [comment]
Is there even a reason why it's disabled?

**Comment by Cactusinapumpkin** [comment]
Big Lag

**Comment by watergod1234** [comment]
Could an admin please respond to this? As we've seen since cactus farms were disable it's still just as laggy as before. Please re-enable them.

**Comment by FutureLemon** [comment]
^^^ What watergod said there's no real difference.

**Comment by DasCodes** [comment]
Fix disabled them for testing purposes, they will be enabled once they are done with testing.

**Comment by docwhomc** [comment]
For testing purposes?  What's being tested that requires cactus farms be disabled?

Is Fix testing the effect of disabling cactus farms?

**Comment by DasCodes** [comment]
This has been fixed.
