### ISSUE TITLE
Don't include forms of block-glitching that are unable to be fixed like bucket climbing or block spam climbing in the rules as bugs.

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#595]
A majority of players have probably block-glitched in some form whether they did it on accident or not at some point while playing a server with a claiming plugin. I can guarantee that a majority of those players also didn't get warned for it as block-glitching cannot be patched. It's essentially a feature anyways, as it's been in the game since plugins that don't allow players to place blocks were created. Why warn for something that can't be fixed and is so widespread that warning everyone would probably make a majority of players leave a server?

**Comment by ImperialFishy** [comment]
I agree its very easy to build structures a certain why to counter act the use of these glitches so if you think someone is using it against you just be more careful when building defensive structures

**Comment by FutureCW** [comment]
Yes @ImperialFishy. It’s not hard to defend against block-glitchers. Literally just place a block outwards and they can’t get out at all

**Comment by WhitPlayzYT** [comment]
Nah just ban the whole server that'll totally be the better option

**Comment by shirazmatas** [comment]
This is the wrong place to post rule suggestions. Please remake it here https://github.com/EarthMC/EarthMC.net/issues
