### ISSUE TITLE
[Feature] social media like site for towns/nation

### ISSUE THREAD

**Issue by Awers97** [EarthMC/Issue-Tracker#596]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I dont know if u can find any engine facebook/twitter looking but i think it would be usefull to see fx if a big town had meetings with many leaders of different nations or doing big building project

**Additional context**
it would be realistic thing to server when we already have own wikipedia with players, nations, events like in real life

**Comment by Warriorrrr** [comment]
Most nations or towns already have their own discord servers they use for this kind of stuff, I don't see why we would need this since we already have said discord servers.

**Comment by Awers97** [comment]
> 

Most nations or towns already have their own discord servers they use for this kind of stuff, I don't see why we would need this since we already have said discord servers.
--> yes but being on many different discord servers is problematic on facebook like page you coul have feed page and like nations you would like to follow. when you are on many servers its hard to find other servers you belong to.

**Comment by Coffeetom** [comment]
There is a reason why this isn't already a thing. There is nothing stopping anyone making a Facebook page for their nation, but they chose to use discord instead, because everyone is on discord, and it's the best option

**Comment by Warriorrrr** [comment]
> being on many different discord servers is problematic on facebook like page you coul have feed page 

If you would really like a feed page, then I suggest you set up something yourself then. Most players are already on discord because it's convenient to use. If your supposed social media site existed, you would have all of the stuff from several nations mixed together, instead of it being about just one. 

> nations you would like to follow 

You can find a list of nation servers in #nation-servers in discord, so you can just join any nation you're intrested in. I wouldn't like to have a list of nations I'm not intrested in in my face every time I want to check something.

> when you are on many servers its hard to find other servers you belong to.

What do you mean with servers? I'm guessing Discord servers, but I don't see whats hard about seeing what servers you belong to. If you have that many servers you can just easily leave some of them.

**Comment by Awers97** [comment]
I didnt really see feed page on any discord server and i was on polish, British i am ofc still on Keisserreich's, Denmarks, Japan people on this server doesnt care about a bit of realism they send alliance to 20 countries without even meeting them. I see that my feature is not usefull cause players on this server didnt grow up to minimum of realism from real life.

**Comment by FutureCW** [comment]
Awers to be honest I can hardly understand you sorry but Facebook and shit would honestly be more cringey than cool. There’s literally no need for it, and people use alliances for teleporting anyways

**Comment by Awers97** [comment]
Yeah i know but sometimes i wish this server is more realistic and not like there is imagine politics and so i dont havr to initate alll political things invite leaders to my town etc. And shitting arounf with alliances is annoying cause when i want my nation to be ablr to come in my town i cant do the /plot set perm ally switch on cause half server will be able to go inside my town. We may close and leave this topic i think there is nothing more to say about it

**Comment by FutureCW** [comment]
If it’s a problem for you just unally people

**Comment by Awers97** [comment]
I am not leader of nation
