### ISSUE TITLE
World

### ISSUE THREAD

**Issue by IlkinAze** [EarthMC/Issue-Tracker#597]
Hello guys, Baku is not belonging to greater armenia, it belongs to the Azerbaijan, you can even google to look at that, we have war between armenia, so they want us to show others as bad, but nope, they can't do that of course, and our religion is Islam, subhannAllah.

![Screenshot_20190607-182943](https://user-images.githubusercontent.com/51485817/59112447-11c6a500-8954-11e9-8393-31f0d8b1a5bc.png)

![Screenshot_20190607-182914](https://user-images.githubusercontent.com/51485817/59112229-a5e43c80-8953-11e9-929e-bad52b7ba654.png)

**Comment by IlkinAze** [comment]
Rename it to Azerbaijan!

**Comment by watergod1234** [comment]
Not everything in the server is 100% accurate to the real world nor should it be.

**Comment by FutureCW** [comment]
lol towns dont have to be in the irl nation they're in

**Comment by IlkinAze** [comment]
@FutureCW ; Azerbaijan and armenia is at war... , me as Azerbaijan citizen, doesn't agreeing with that name, and my family,frends,friends of friends, i showed to all,if it won't be fixed, i will report it to the creator.

**Comment by FutureCW** [comment]
@IlkinAze well they won't fix it because it's allowed

**Comment by Warriorrrr** [comment]
Just because a town irl belongs to a certain nation, doesn't mean it has to be that way in-game. You can't just request a nation to be renamed because they own a town in another irl country. Only the nation leader can decide to change the name of the nation.

**Comment by Coffeetom** [comment]
This is a geo-political server, it isn't meant to perfectly represent real life.

**Comment by IlkinAze** [comment]
What if me with my friends will build near Baku its rural areas, and name it Azerbaijan?

**Comment by IlkinAze** [comment]
And how Baku can leave from that nation?

**Comment by shirazmatas** [comment]
Invalid ticket. Towns can be in whatever nation they want to be in there is no enforcing rule
