### ISSUE TITLE
A request for custom recipes regarding Shulker Boxes and Cobwebs

### ISSUE THREAD

**Issue by SatanV2** [EarthMC/Issue-Tracker#598]
I know there have been requests for Shulker Boxes before, but I think having shulker boxes in EMC could work and still keep the rarity if you use a nether star somewhere in the recipe. Many people in EMC want this item and I think it would be a good benefit to the server, but using a nether star would still keep the rarity and expensiveness of the item.

My other request would be to make some way to turn a cobweb into string. Using MCMMO I've collected a ton of cobwebs and I dont really want them, I want string but to get it I have to sit there and break cobwebs one by one which is really annoying, so this would really just be something for quality of life. (This could also be done with Glowstone since an EMC custom recipe requires glowstone dust)

**Comment by JaVolimKatarinu** [comment]
You get strings from digging gravel..

**Comment by Cactusinapumpkin** [comment]
I never gotten string from gravel but I have gotten string from clay

**Comment by Cactusinapumpkin** [comment]
also how are you getting cobwebs, because cobwebs come after string.

Also france sells string

**Comment by DarkRush449** [comment]
You can craft cobwebs with string, because the server has custom recipes for unobtainable blocks. You can also get cobwebs from clay blocks due to mcmmo. I believe the cobweb recipe is 5 string in a X on the crafting table.

**Comment by Cactusinapumpkin** [comment]
Maybe add it as a loot crate reward?

**Comment by Prismary** [comment]
Beyond recent at this point, also refer to #589.
