### ISSUE TITLE
I went under the map

### ISSUE THREAD

**Issue by Laconek** [EarthMC/Issue-Tracker#599]
I traveled 20 000 blocks to buy 2 cows with my gold and my stuff! When advancing I'm passing under the map and died I would like to recover at least my two cows! please thank you 

I was not able to take screen the message of death it's direct remove but by checking on the server command you could see that my last death is in the void! Nickname LACO_NEK

**Comment by WhitPlayzYT** [comment]
you keep your inventory when you die in the void, stop trying to get free loot

**Comment by shirazmatas** [comment]
This seems to be a discord support issue not really anything fixable.
