### ISSUE TITLE
[Mechanic] Reduced cost of Packed ice and Blue ice.

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#60]
The premise of Terra nova is a more realistic world, a world where magic cannot teleport you to the other side of the world. However in the mist of TPA we now lack a replacement for tpa

Rails have already been discussed but I'm here to discuss Boat on ice travel.
Boat on ice travel is one of the fastest ways to travel (after elytra, ender pearl, and dolphin rings) and is a very realistic approach (see quantum levitation). The only downside is that it is not nearly possible to get the blue ice needed to construct say a road from Asia to Americas. To help reduce the cost of time and global warming I believe lowering the price would prove to be useful. My plan is that the price can be divided by three like this https://i.imgur.com/OJwMHS0.png and then further by doing the same for blue ice

`{"type":"crafting_shapeless","ingredients":[{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"},{"item":"minecraft:ice"}],"result":{"item":"minecraft:packed_ice","count":3}}`

and for blue ice
`{"type":"crafting_shapeless","ingredients":[{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"},{"item":"minecraft:packed_ice"}],"result":{"item":"minecraft:blue_ice","count":3}}`

**Comment by sharkfynn1012** [comment]
Yeah eantirely. The removal of tp is annoying, it would certainly be far less annoying if we had something like this. I think that the removal of tp could be enjoyable though only if it doesn’t make our lives too much harder.

**Comment by TheGoatOnABoat** [comment]
If we want realism, we should turn off hostile mobs. In the real world, there are no six foot spiders, or skeletons coming to life to shoot you with arrows, or zombies, or creepers, or endermen, etc etc.

**Comment by shirazmatas** [comment]
> 
> 
> If we want realism, we should turn off hostile mobs. In the real world, there are no six foot spiders, or skeletons coming to life to shoot you with arrows, or zombies, or creepers, or endermen, etc etc. If you are worried about the loot not being available, a shop can be made for it.

what about Drug dealers, dangerous spiders, and robbers those are real life reprensentations for hostile mobs lol. the rest can also be found. It is still realism

**Comment by shirazmatas** [comment]
MAybe it should even be cheaper at 2 ice for packed and 2 packed for blue

**Comment by Arganog** [comment]
I think this would be a great addition.

**Comment by KarlOfDuty** [comment]
We will have a look at this during our next scheduled maintenance.

**Comment by FranchuFranchu** [comment]
I should also tell that ice roads can be cheaper if you use this layout:
![](https://i.imgur.com/mmPJGgU_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by shirazmatas** [comment]
New recipe even: 4 ice in a square for packed, 4 packed in a square for blue.

**Comment by Kyoris** [comment]
i want a refund for all the packed ice i've made reeeeeeee

**Comment by KarlOfDuty** [comment]
Done.
