### ISSUE TITLE
Banned for no reason 

### ISSUE THREAD

**Issue by ZelpofgamesNL** [EarthMC/Issue-Tracker#601]
hi i wanted to play on the server it seemed like a cool server but when i (try join the server) i get this Banned on 2019-06-10 Banned by: Skynet 
Reason: Using a stolen/hacked account.

Your are permantly banned!

even tho my account is not stolen or hacked i bought it in 2014 so i need to be unbanned

**Comment by KarlOfDuty** [comment]
https://github.com/TheMrGong/MCLeaksApiClient#contact

Follow the instructions here to be unbanned.
