### ISSUE TITLE
Animals can go into nether but can't go back into overworld.

### ISSUE THREAD

**Issue by williamtvcollins** [EarthMC/Issue-Tracker#602]
Villagers and cows teleport instantly into nether when touch portal but when I try to bring them back into overworld, they just sit in portal and can't go back.

**Comment by alekb1** [comment]
This is a basic vanilla mechanic, there's like a 15 min (or 5 can't remember) cooldown before they can transfer through a portal again

**Comment by GetPrankedNerd** [comment]
I have waited the time and still the mobs cannot go through.

**Comment by alekb1** [comment]
Have you waited in the same chunks as the mobs?

**Comment by GetPrankedNerd** [comment]
Yes
