### ISSUE TITLE
[BUG] Cannot receive gold when offline

### ISSUE THREAD

**Issue by ishland** [EarthMC/Issue-Tracker#604]
**Server**
Towny Server

**Describe the bug**
I have just voted every day on the website when i was offline for 5 days. And I got nothing in game.

**To Reproduce**
1. Do /money and get "You currently have 29G on you."
2. Vote on the minecraft-mp.com every day for 5 days when offline
3. Join the towny server
4. Do /money
5. Got "You currently have 29G on you."

**Expected behavior**
I should see "You currently have 54G on you."

**Comment by FutureLemon** [comment]
Offline voting does not work, no point in doing it anymore.

**Comment by ishland** [comment]
Alright thanks
