### ISSUE TITLE
The ranks don't make you go in front of the previous ranks or priority queue. There is also no upgrade option for ranks.

### ISSUE THREAD

**Issue by GetPrankedNerd** [EarthMC/Issue-Tracker#606]
I tested it. Me (as a purple rank) joined at about position 40 in the queue. I asked and there was a priority queue at position 39. I was told ranks go in front of priority. Then a blue joined and they were position 41. They were supposed to be in front of me.

**Comment by GetPrankedNerd** [comment]
I tested it. Me (as a purple rank) joined at about position 40 in the queue. I asked and there was a priority queue at position 39. I was told ranks go in front of priority. Then a blue joined and they were position 41. They were supposed to be in front of me.

**Comment by FutureLemon** [comment]
Maybe your rank wasn't added yet?

**Comment by ImperialFishy** [comment]
As far as i understand it the old donators are ranked according to their colour. So old frost has highest prio, old purple has 2nd highest and old yellow has 3rd highest. After that comes priority. This weekend special that you bought were to get all the donator perks but you did not recieve higher priority becouse you just bought cosmetics in the form of a coloured plus and some extra commands. It was never advertised as a higher form of priority or equal in priority as old donators. New donators still have the same queue priority as priority owners they just recieved things like /nick and access to donator chat as well as a coloured plus

**Comment by KarlOfDuty** [comment]
We are not able to add an upgrade option as the payment system is a third party service outside of our control.
