### ISSUE TITLE
Muted For "Thinking He's Funny"

### ISSUE THREAD

**Issue by Toadnt** [EarthMC/Issue-Tracker#608]
here we go.

I was muted by Justbehonest for "thinking he's funny" and permanently muted on the discord servers discord to Minecraft chat. all that I did was make a joke about "selling justbehonest for one dirt".

This seems to me like mod abuse, if you could talk to him if I'm right about this that would be great.

**Comment by prokillerr** [comment]
If you're not bullshitting, then how tf can someone get triggered by "selling <person> for one dirt"? This is fucking impossible lmao.

**Comment by Kyoris** [comment]
snowflake to the infinitieth lol

**Comment by FutureLemon** [comment]
Lol, maybe you should provide some proof in the first place of this situation ever even happening. Secondly go appeal in the support discord: https://discord.gg/auCvYn . The github was made to report bugs and request features not to rant about silly things like you're worthless joke...

**Comment by shirazmatas** [comment]
What future said, This ticket is invalid for many reasons

1. It lacks the persons username
2. It should be in format
3. It should have a correct title
4. This is the github not the support discord
