### ISSUE TITLE
Final kick before ban

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#609]
**Is your feature request related to a problem? Please describe.**
Yes. I said the word "nibba" (which is not inherently racist in any way shape or form) and Eagle warned and kicked me. The kick message said "Final kick before ban". I am unaware of any warns before this, and feel as if I am being targeted.

**Describe the solution you'd like**
If possible, I want any and all warns removed from my account. I did not do anything wrong in this situation. Nibba is not racist.

**Additional context**

**Comment by FutureCW** [comment]
The kick is automatic on your second warning. Also, “nIbBa iSnT iNhErENtLy rACisT  iN aNy wAY sHaPe oR fORm!1!1! We all know thats a racial slur bypass don’t lie lmao

**Comment by FutureLemon** [comment]
Do /warnings, it shows all active warnings you currently have with an expire date of 60days. As for the warn saying the n-word in any shape or form is just stupid that you think you can get away with changing slurs. The kick happens automatically when you reach your second warn.

**Comment by shirazmatas** [comment]
This is the github, a place for general issues, bugs, and feature request. You have to go to the support discord
