### ISSUE TITLE
Fix Finland

### ISSUE THREAD

**Issue by KarlOfDuty** [EarthMC/Issue-Tracker#61]
Finland is currently largely a cold ocean. Whoops.

**Comment by Arganog** [comment]
Finland is no longer largely a cold ocean

Went over the following area and converted all to dark forest, fairly certain that was all of it

![finlandbiome](https://user-images.githubusercontent.com/44342952/47690002-4ef6d780-dbba-11e8-81cd-45f2ae3aacf9.PNG)
