### ISSUE TITLE
[Feature] Choccy Milk

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#610]
![image](https://user-images.githubusercontent.com/48000340/59733541-db224180-9213-11e9-8b12-d47a2aac9770.png)

why not?

**Comment by Pengun78** [comment]
Choccy milk

**Comment by Pengun78** [comment]
Someone give cactus choccy milk

**Comment by Cactusinapumpkin** [comment]
^^^

**Comment by Cactusinapumpkin** [comment]
we also need something to sell at coffee shop other than "triple shot expresso" speed pots

**Comment by Kyoris** [comment]
My ideas:
Vodka - 15s nausea, 45s speed 2, 15s strength 2, 60s absorption 2
Beer - 10s nausea, 10s regen, 20s strength, 90s luck
Coffee - 30s speed, 30s jump boost, 15s regen
Tea - 30s speed, 30s jump boost, 45s health boost 2
(Don't ask me what ingredients they would be brewed out of, also they shouldn't have a splash variant)

**Comment by BowShot118** [comment]
must have

**Comment by FutureCW** [comment]
Need

**Comment by DarkRush449** [comment]
I think the ability to have combined potion ingredients would be cool

**Comment by FutureLemon** [comment]
EMC can't even handle cactus farms... How are you planning to implement combined potions?

**Comment by shirazmatas** [comment]
Please use the format given for your feature request. And you have to have a better description for what you want.

**Comment by Cactusinapumpkin** [comment]
I dont think I can take feature requests seriously because I never get updates in a timely fashion even if I deo make them in the correct format,
This time I dont follow the format and I actually get a update from a mod 2 days later.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/59893699-60882c00-93a3-11e9-8daf-3e032e16d89a.png)
 
also I thought this was pretty self explanatory of what I want.

**Comment by shirazmatas** [comment]
You didn't follow format in your previous ticket too, and it's a bit spoiled to assume that you will get your ticket looked upon immediately.

Also you still lack a description of what it should give you. And how should it be implemented considering it's a new texture

**Comment by Cactusinapumpkin** [comment]
what do you mean by implemented?

**Comment by watergod1234** [comment]
> You didn't follow format in your previous ticket too, and it's a bit spoiled to assume that you will get your ticket looked upon immediately.

Also you still lack a description of what it should give you. And how should it be implemented considering it's a new texture

It's a joke.

**Comment by shirazmatas** [comment]
joke issue
