### ISSUE TITLE
Distinct Staff roles

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#612]
Can we get distinct staff with specific jobs? It'd be really neat and usefull to have some staff members as ChatMod and some that are specifically designed to handle the support discord and a couple to work on the griefs and rollbacks and such. Personally it would make stuff run much smoother then just adding New-Mod and not informing anyone that they can basically do nothing except /mute and /warn leaving Eagle and Shiraz mainly doing all the rest which ends up with everything slacking and taking ages to be done.

**Comment by FutureCW** [comment]
Karl’s already shot this down when I suggested it in donator chat like a week after the new mods got hired

**Comment by FutureLemon** [comment]
:thonk: But we still need staff for Factions too I know some people that play factions and have on EMC to know how stuff works. I guess factions will just be hackercity...

**Comment by DasCodes** [comment]
> I guess factions will just be hackercity...

It's called hacktion.

**Comment by KarlOfDuty** [comment]
If moderators want to specialize they may do so, but we will not split them up into different areas at this time.
