### ISSUE TITLE
[World] "Deutschland" nation with joke town names

### ISSUE THREAD

**Issue by xpodojo** [EarthMC/Issue-Tracker#613]
**Describe the issue**
The nation of Deutschland holds many joke town names based around southern germany
I'm sure this breaks Rule 4 'Naming' as the names are fictional nor correspond to the location at all. Deutschland town name examples being "Fucking"  "Dick" "Oof" &  "Wank"

**Coordinates**
Majority Southern modern germany. Nation "Deutschland" 

**Screenshots**
![OofTown](https://user-images.githubusercontent.com/52056194/59890292-2445d300-9385-11e9-82ea-85beef9ad2b6.png)
![WankTown](https://user-images.githubusercontent.com/52056194/59890305-2a3bb400-9385-11e9-8577-a2129f0ccfc3.png)
![DickTown](https://user-images.githubusercontent.com/52056194/59890311-30319500-9385-11e9-827c-b4870acdbac0.png)
![FuckingTown](https://user-images.githubusercontent.com/52056194/59890250-f19bda80-9384-11e9-92c4-a1dfdb671b1f.png)

**Comment by shirazmatas** [comment]
This is not the support discord please go to the support discord instead
