### ISSUE TITLE
[Feature] Give temporary highest priority when disconnect by network issues

### ISSUE THREAD

**Issue by ishland** [EarthMC/Issue-Tracker#614]
**Is your feature request related to a problem? Please describe.**
I am in China and I have bad connections between my network and the server. And I am always unhappy when a unexpected disconnection happens.

**Describe the solution you'd like**
After a disconnection which is caused by network, reconnect and get the highest priority to join the server. It does not affects the normal disconnections.

**Comment by creatorfromhell** [comment]
It may be good to note that there is no reliable way to determine the difference between a player losing connection, and one that is disconnecting.

**Comment by ishland** [comment]
> It may be good to note that there is no reliable way to determine the difference between a player losing connection, and one that is disconnecting.

The reason of normal disconnection is "disconnected", and the reason non-normal disconnection is something else.

**Comment by creatorfromhell** [comment]
> > It may be good to note that there is no reliable way to determine the difference between a player losing connection, and one that is disconnecting.
> 
> The reason of normal disconnection is "disconnected", and the reason non-normal disconnection is something else.

There is no disconnect "reason." The only "reason" concerning anything in the bukkit API is if the player is kicked. Otherwise, there is no way to decipher if a player disconnects their ethernet/wireless connection versus a network issue.
