### ISSUE TITLE
[Feature] Shulker Boxes recipe should be a thing, why isnt it already?

### ISSUE THREAD

**Issue by 32Slaid** [EarthMC/Issue-Tracker#615]
basically the staff wont open up the end gates and for this reason we cant get shulker boxes from any method

i would love a EXPENSIVE custom recipe for it. 

more gold blocks would be epic anyway

![image](https://user-images.githubusercontent.com/52091049/59958128-ea092e00-9477-11e9-8851-76541bf99e4f.png)

![image](https://user-images.githubusercontent.com/52091049/59958151-3ce2e580-9478-11e9-90c0-70d924e016cf.png)

![image](https://user-images.githubusercontent.com/52091049/59958153-479d7a80-9478-11e9-91bd-0a02b770f5ea.png)

EXPENSIVER ALTERNATIVE

![image](https://user-images.githubusercontent.com/52091049/59958157-5d12a480-9478-11e9-8f1c-86f639f148f0.png)

IF YALL WANNA MAKE IT EVEN MORE HARD

![image](https://user-images.githubusercontent.com/52091049/59958159-6dc31a80-9478-11e9-84d9-cd0041405445.png)

**Comment by WhitPlayzYT** [comment]
First one sounds epic

**Comment by FutureLemon** [comment]
The first recipe sounds fair to me.

**Comment by brayjamin** [comment]
The first recipe, but change the lapis to end stone. Then you'll recieve a basic shulker box. The colors can then be changed using the generic dyes. Thanks!

**Comment by WhitPlayzYT** [comment]
> The first recipe, but change the lapis to end stone. Then you'll recieve a basic shulker box. The colors can then be changed using the generic dyes. Thanks!

I think the dye should be used in the recipe so bulk crafting of dyed shulker boxes is easier

**Comment by brayjamin** [comment]
True. Perhaps make it interchangeable?

**Comment by Cactusinapumpkin** [comment]
it will prolly be the last one tho

**Comment by FutureLemon** [comment]
> it will prolly be the last one tho

Nether stars are overkill for a shulker box imo

**Comment by BowShot118** [comment]
Nether stars are definitely overkill and how would we get the end stone? I think that 2 gold blocks is enough in terms of literal gold and I'd prefer to see the echest be swapped out with a normal chest as the shulker doesn't link up to your echest, so it makes less sense to include one in the recipe.

**Comment by WhitPlayzYT** [comment]
> Nether stars are definitely overkill and how would we get the end stone? I think that 2 gold blocks is enough in terms of literal gold and I'd prefer to see the echest be swapped out with a normal chest as the shulker doesn't link up to your echest, so it makes less sense to include one in the recipe.

There's a custom recipie to get end stone

**Comment by 32Slaid** [comment]
> Nether stars are definitely overkill and how would we get the end stone? I think that 2 gold blocks is enough in terms of literal gold and I'd prefer to see the echest be swapped out with a normal chest as the shulker doesn't link up to your echest, so it makes less sense to include one in the recipe.

the enderchest is only there to make it harder to craft, assuming the reason they dont want to add it is because of its features being overpowered. but as a month gone by and we have no response to clear things up i rather assume they dont want it ingame.

**Comment by Cactusinapumpkin** [comment]
I just need one or two of them for bulk storage in my echest,, maybe add it to the vote crates?
Its really annoying transporting several inventories of baked potatoes, blaze rods, and just random junk.

**Comment by Lagann311** [comment]
I agree it‘s annoying, but there‘s a reason for it. Imagine someone with a lot of shulkers goes farming sand. He will be twice as fast as people who go with only empty inventory and an enderchest. Resources like sand, clay and also gold would get farmed a lot faster, which is a problem. If they get added, they should be extremely expensive or rare, like 80-200g worth

**Comment by Cactusinapumpkin** [comment]
So yea add them to vote crates

**Comment by DeadGlamour** [comment]
I dont think they want to have shulker boxes, prob due to fear of duping becoming super massive.

**Comment by Cactusinapumpkin** [comment]
The duping methods using shulkers are patched at 1.13. https://minecraft.gamepedia.com/Tutorials/Block_and_item_duplication

**Comment by DeadGlamour** [comment]
I think they are scared from people duping shulker boxes with gold in them, because then all dupes will be like the chunk dupe, in which the server was entirely rolled back.

**Comment by Cactusinapumpkin** [comment]
I think because this is a spigot plugin server that the chunk dupe had been patched.
Chunk memory overflow (Patched in spigot servers)

**Comment by Prismary** [comment]
Shulker box crafting remains controversial, might be worth discussing in an updated issue. Also refer to #589 and #598.
