### ISSUE TITLE
[FEATURE] Enable hunger games on queue

### ISSUE THREAD

**Issue by theEXPERTpt** [EarthMC/Issue-Tracker#617]
The queue was a feature that was welcomed by many players on the server. However, with the high income of new players, the queue can reach sometimes up to 300 people. Obviously, staff has reached to some solutions to solve this queue pressure, like the factions server or the Hunger games mode playable when in queue. However, the Hunger Games seemed to die, as no more games are played or the staff doent worry on starting new matches. The Idea of hunger games is to make a way to entretain people in queue, that can wait hours and hours in the queue before entering the server. Being AFK is an option, but when a person is soo many time AFK in queue, the risk of being kicked from main server for being AFK is also very high. Priority and rank players will not be affected, use well the queue server and add this feature again, so new players can feel less bored when waiting in the enormous queue.

**Comment by KarlOfDuty** [comment]
The hunger games server is in beta and has likely been broken now that I'v been away a week, I will keep working on it in the future.
