### ISSUE TITLE
[FEATURE] add a custom recipe that use wool to make string

### ISSUE THREAD

**Issue by DvirFederacia** [EarthMC/Issue-Tracker#618]
strings are too rare, and there are no mobs, now string has a higher price than diamond, that's ridiculous

**Comment by JaVolimKatarinu** [comment]
![image](https://user-images.githubusercontent.com/41012732/60135838-eab90180-97a2-11e9-9f77-ed679ab071d3.png)
Excavation over 250 level, digging clay blocks can give you some strings

**Comment by WhitPlayzYT** [comment]
String isnt really rare lol

**Comment by KarlOfDuty** [comment]
Shouldn't be an issue anymore.
