### ISSUE TITLE
[Bug] Mob Spawning- Zombie pigman- dropping gold swords

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#619]
**Server**
This bugs affects Towny, dont know about Factions.

**Describe the bug**
Mob spawning in Nether. While mobs are disabled in Overworld, they normally spawn in Nether. And due to mob spawning in Nether, mostly spawned mobs are Zombie Pigmans. Due to plugin that should work, Zombie pigmans arent supposed to drop gold swords when they are killed. Although, I have grinded a lot of gold swords and smelted them into gold nuggets. 

**To Reproduce**
1. Go to Nether and explore it a bit or afk in some chunks. 

**Expected behavior**
https://github.com/EarthMC/GoldDropRemover
I believe this is the plugin responsible for this bug, although I think I saw something else that EMC uses to disable dropping gold swords from Pigmans.

**Screenshots**
![2019-06-21_18 01 54](https://user-images.githubusercontent.com/41012732/60126891-411c4500-978f-11e9-81c2-b523c07e9f45.png)
![2019-06-21_18 01 56](https://user-images.githubusercontent.com/41012732/60126892-41b4db80-978f-11e9-8048-6d97b6948f5b.png)
![2019-06-21_18 01 52](https://user-images.githubusercontent.com/41012732/60126893-41b4db80-978f-11e9-8c68-1b0f02e382a6.png)

![2019-06-25_21 25 19](https://user-images.githubusercontent.com/41012732/60127157-cdc70300-978f-11e9-9bbd-f786be9da968.png)

**Additional context**
Could it be possible to totally disable spawning of Zombie Pigmans, since plugin is not really working and enable some mob spawns in overworld? 
Btw. I alredy "reported" this in my previous issue, but no one replied anything. After that, talked with Shirazmates, where he said that this is a bug. 
@KarlOfDuty

**Comment by BowShot118** [comment]
ssssssshhhhhhhhhhhh don't tell them!

**Comment by JaVolimKatarinu** [comment]
Bug abuse is a permanent ban if you didn't know...
Btw, I would rather trade grinding of gold swords for some spiders or rabbits or Llamas or even for a polar bear.

**Comment by BowShot118** [comment]
It was obviously a joke. I'm aware that abusing a bug is bannable, I know someone *cough* Sly who was perm banned for abusing a gold duplication glitch back on classic.

**Comment by DasCodes** [comment]
I think this is intended.

**Comment by KarlOfDuty** [comment]
Updated the plugin for the next restart.
