### ISSUE TITLE
[Factions] Remove Inactive Factions/Enable Firespread

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/Issue-Tracker#620]
Could you please remove the inactive factions that take a large amount of space/use up names in factions? USA as an example I believe the leader has been banned for hacking yet the territory still remains just wasting space and taking an important name. 

You could add a system like towny that removes players after a number of days but it wouldn't work great, factions are already generally smaller and implementing it without warning would annihilate large factions instantly

Also please enable firespread, a faction server should have this and it's a towny setting that just hasnt been enabled. Let us burn things

**Comment by prokillerr** [comment]
Yeah, why tf is fire spread disabled? That makes zero sense

**Comment by prokillerr** [comment]
Yeah, why tf is fire spread disabled? That makes zero sense

**Comment by DasCodes** [comment]
While I don't know if a faction gets deleted due to inactivity, but the fire spread is off to help the staff reduce griefs. The players usually grief really badly when the fire spread is on by just lighting a few trees.

**Comment by prokillerr** [comment]
Cant that plugin that makes natural terrain fix itself(I know emc has it from a few "tests" in the beta server) also include trees? Other than natural terrain, grief is what makes factions... Factions

**Comment by KarlOfDuty** [comment]
Inactive factions are automatically deleted except that the plugin is buggy af so you can't really trust it to function properly.
