### ISSUE TITLE
[feauture] mobs/mob drops in factions

### ISSUE THREAD

**Issue by prokillerr** [EarthMC/Issue-Tracker#621]
Ever heard of a faction server that allows raids yet doesnt give you access to tnt? Yeah, me neither, till I joined emc factions. Mobs are disabled because of lag right? Well, either add another way to get their so needed drops, or update your hardware(oh yeah, I forgot, you supposedly have the top hardware or something)

**Comment by Arkifios** [comment]
It isn't that difficult to get gunpowder for tnt and Mobs aren't disabled, they are just rare. I even have a couple of chicken and pigs to prove it. Since mobs are rare a majority of the items you need for raiding and other stuff are gotten with mcmmo with gunpowder coming from excavation and leather from fishing and salvaging. You can also get leather from using 10 apples to spawn them for 250 seconds which you then breed to have some that don't despawn.

**Comment by prokillerr** [comment]
Ya, I had totally forgotten huge excavation gives you gunpowder.

**Comment by gayASF** [comment]
uhm, you can get almost any item that a mob can drop just using mcmmo. There's a shortage of mobs, yes, but when you can grind out mcmmo levels and get the exact same loot does it really matter? You get gunpowder, bones, and music discs in gravel with excavation (creepers and skelly drops), glowstone from dirt, sand, and soulsand (witch drops), slime and string from clay (spiders and slime). When fishing, you can collect pearls, blaze rods, ghast tears, and gold swords which drop from all mobs that spawn in the nether regularly (excluding skellies). Also, fishing has a Shake chance that allows you the possibility of taking items in a mobs loot pool before killing it, which is REALLYYY OP for grinding drops like wither heads, ghast tears, and epearls from the more rare mobs. I don't think we need any adjustments to mcmmo other than unarmed skill actually being useful (bc unarmed is such a pain in the booty to grind it should actually be worthwhile, but maybe with Disarm disabled) also a world border should be added so people cant just go in the nether and grab thousands of blaze spawners with ridiculous xray and just come back after loading millions of chunks with their laggy spawners. We aren't allowed to build outside of the world, so why not just add a border and be done with deleting all of that? 
would be nice if overworld had more animals than the nether; ive seen 3 chicken in the overworld and 6 chicken jockey pigmen mofos in the nether :>

sorry for flying off topic 
this is the response of some edgy and cringey ass teen so pls forgive
