### ISSUE TITLE
[BUG] /discord link does not work in lobby

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#622]
**Server**
Hub
**Describe the bug**
/discord link retrives the MOTD instead of linking

**To Reproduce**
1. Go to Hub
2. write /discord link

**Expected behavior**
a link code

**Screenshots**
no

**Comment by KarlOfDuty** [comment]
Shiraz pls, the hub server doesn't even have a discord bot.

**Comment by shirazmatas** [comment]
Im gonna necromance this ticket, I don't see why hub shouldn't allow people to link their discord so they can type in #earthmctowny @KarlOfDuty

**Comment by KarlOfDuty** [comment]
Because that isnt possible.
