### ISSUE TITLE
[BUG] Apply mob to spawner failled

### ISSUE THREAD

**Issue by NoelVarga** [EarthMC/Issue-Tracker#623]
I have tried to click my blaze egg on the spawner. It lagged so i tried one more time. At the end because of the lagg i lost 4 BALZE EGGS because it wasnt apllying!!!

Ive tried to reach out to a mod but he didnt help me because I WASNT RECORDING IT !

**Comment by KarlOfDuty** [comment]
This is a support matter, not for the issue tracker.
