### ISSUE TITLE
[Feature] Add polish chat

### ISSUE THREAD

**Issue by DasCodes** [EarthMC/Issue-Tracker#624]
As many other language chats have been added, I think it would be best if we add a Polish chat as well, as there are plenty of players speaking Polish.

**Comment by prokillerr** [comment]
Might as well add 200 something chats for all languages lol

**Comment by theEXPERTpt** [comment]
No point on adding 200 types of different chats, if it is soo annoying just make an english chat and leave global for other languages.

**Comment by DasCodes** [comment]
We aren't adding 200 different chats, just a few languages with some decent player counts to avoid any conflicts while we try to keep the `/global` chat English and moderated.

**Comment by prokillerr** [comment]
I know, I was just joking...

**Comment by Judestadt** [comment]
Will you ever bring back 3D dynmap view??
