### ISSUE TITLE
Add/Create a page or way to display the custom recipes for items on the server.

### ISSUE THREAD

**Issue by WyWall** [EarthMC/Issue-Tracker#625]
an example of a custom item would be the custom powered rail recipe, or the prismarine recipes.

**Comment by KarlOfDuty** [comment]
Never.

**Comment by JaVolimKatarinu** [comment]
Actually, what you are asking for is already implemented. Just craft it once and that custom recipe stays in your recipe book.

**Comment by KarlOfDuty** [comment]
And ya know this whole thing: https://earthmc.net/faq
