### ISSUE TITLE
Stuck in queue for Factions when their are only around 10-15 players on that server.

### ISSUE THREAD

**Issue by Arkifios** [EarthMC/Issue-Tracker#626]
**Server**
Factions
**Describe the bug**
I have no idea if its just me or not, but when there are very few players on factions the server puts me in the queue instead of sending me to the server. The queue then just stays stuck.

**To Reproduce**
1. Try to join Factions when there are low amounts of players.

**Expected behavior**
Instantly join since the player count is no where close to the max amount.

**Screenshots**
![Evidence1](https://user-images.githubusercontent.com/34319562/60483888-66182880-9c65-11e9-8005-a5d80513f1d5.PNG)
![Evidence2](https://user-images.githubusercontent.com/34319562/60483942-a8416a00-9c65-11e9-86b4-49a43b00ca21.png)
![Evidence3](https://user-images.githubusercontent.com/34319562/60483945-aa0b2d80-9c65-11e9-8aab-82b39ef09e2c.png)

**Comment by KarlOfDuty** [comment]
Fixed.
