### ISSUE TITLE
Language chanels color

### ISSUE THREAD

**Issue by BBrotherss** [EarthMC/Issue-Tracker#628]
When 2 or more languages are spoken in chats other than /global, is rapidly gets difficult to distinguish both channels because all the channels dedicated to language have the same pale green color

I propose that each channel should have its unique color to differentiate them more easily. It would make communication with those channels a lot easier.

**Comment by KarlOfDuty** [comment]
Do people use several language channels at the same time?

**Comment by shirazmatas** [comment]
Multilinguals be like

**Comment by KarlOfDuty** [comment]
Well, in any case we don't really have a lot of colours to pick from so that will not be possible atm.
