### ISSUE TITLE
[BUG] Minecraft Error When Joining server

### ISSUE THREAD

**Issue by TTVSleepyboi** [EarthMC/Issue-Tracker#629]
Hello. So when I try to join EarthMC I get this message:Failed to log in: invalid session (try restarting your game). i tried restarting, trying out different versions, but every time i would get this message.

![image](https://user-images.githubusercontent.com/52593553/60752911-d9a29880-9fcb-11e9-9ad4-117fbb54b015.png)

**Comment by DasCodes** [comment]
Are you using a premium account?

**Comment by TTVSleepyboi** [comment]
yes.

**Comment by DasCodes** [comment]
The only reason you're getting that error because your Mojang is unable to verify your Minecraft account. There are no issues on our end.

**Comment by WhitPlayzYT** [comment]
When it says that it means restart your game and launcher  (close and re open them)
The same issue happens to me all the time but restarting the launcher and game always fixes it

**Comment by DasCodes** [comment]
> i tried restarting, trying out different versions, but every time i would get this message.

@WhitPlayzYT

**Comment by KarlOfDuty** [comment]
As eagle said above, it is a client<->mojang issue, nothing to do with the server.
