### ISSUE TITLE
Mob feeding 

### ISSUE THREAD

**Issue by theEXPERTpt** [EarthMC/Issue-Tracker#630]
Towny

While feeding animals and reproducing them, the close mobs despawn automattically, even if they are different types of mobs.

Steps to show the bug:
1-Have different mobs close to eachother.
2-Feed 2 mobs of the same specie, to make them to reproduce.

The final result will be problably the despawn of one random close mob.

![2019-06-26_00 44 27](https://user-images.githubusercontent.com/52140324/60756213-da9af080-9ff2-11e9-8241-60aa7bb970e0.png)
![2019-07-06_13 28 19](https://user-images.githubusercontent.com/52140324/60756217-df5fa480-9ff2-11e9-806b-438ba68074ea.png)

**Comment by DasCodes** [comment]
This is because of the mob limit per chunk as the plugin only checks mob count in that chunk, not specifically counting each mob type.
