### ISSUE TITLE
[BUG] Removed from town for no reason

### ISSUE THREAD

**Issue by Khorps** [EarthMC/Issue-Tracker#631]
**Server**
Towny

**Describe the bug**
Despite being active (coming on once a day) I, as-well as several other users except for the mayor are suddenly no longer in our town anymore. This probably wasn't everyone being kicked because A there's no reason to do that and B this has happened to me before specifically and I was invited back in as soon as the mayor got online.

**Comment by EchoOcelot** [comment]
What is the town called? Maybe the mayor turned on taxes which kicks you out if you do not have any gold on you

**Comment by KarlOfDuty** [comment]
Is this issue cleared up?
