### ISSUE TITLE
[Feature/Plugin] Increase access to String and Slime

### ISSUE THREAD

**Issue by Locotime** [EarthMC/Issue-Tracker#632]
**Is your feature request related to a problem? Please describe.**
Clay is rare to find naturally, and so getting string or slimeballs in even a small quantity is quite hard.

**Describe the solution you'd like**
Modify the treasure.yml file for mcmmo to have a chance to gain these items from resources other than clay, if at lower rates and higher levels. If doing this, and assuming you cannot create separate drop rates/levels for separate blocks types, my recommendation would be to add 
**Slime**
slimeblocks as a drop from dirt, gravel, or maybe grass. Require level 750 to get, and have the dropped at a rate of .005%. This should be a little bit less than 1/20th of the drop rate of slimeballs from clay, providing an alternative, but later game and slower way.
**String**
change cobwebs to drop from dirt, gravel, or maybe grass instead of clay. Keep level to mine at 750 but decrease drop rate by 10 to 100 times to prevent a massive surge in string or cobwebs to the economy

**Comment by ImperialFishy** [comment]
No if you know what you are doing getting any of those materials is a piece of cake no need to compromise the rarity of it. No point in making everything too accessible. Like i said if you know what your doing you either 1. Dont need string and 2. Finding clay really isnt that hard if you really want it

**Comment by Locotime** [comment]
@DasCodes Sorry, I should have specified, this is on Factions, although the changes would affect towny seeing as how you have shared mcmmo files between them
@ImperialFishy How so (Keeping in mind this is factions as I should have said earlier)?
For 1) String is needed to create bows and fishing rods, let alone repair of them. A similar situation for wool, as the spawn occurrence of sheep is quite rare.
For 2) Where? Perhaps Faction map is different than towny, but clay is only spawned along coastlines and rivers, any deepish ocean area is completely filled dirt from what I can tell, and I followed the amazon for 3-4kish blocks for about 20 string and 8 slimeballs

**Comment by ImperialFishy** [comment]
There is more than enough clay in the world the factions map is very similar to towny, towny has been updated to include some obvious mistakes in the world but i can assure you it is possible to get enough of what you need if you look in the right place

**Comment by Ukai-Oita** [comment]
I would expand this suggestion to say that mcmmo should be customized more in general. Add some super-rare drops that require 1000+ excavation to obtain! Would be neat.

**Comment by KarlOfDuty** [comment]
Shouldn't be an issue anymore.
