### ISSUE TITLE
Fish not spawning

### ISSUE THREAD

**Issue by itzstitch** [EarthMC/Issue-Tracker#633]
**Server**
Towny

**Describe the bug**
Fish don't spawn when placed with a bucket

**To Reproduce**
1. Get a water bucket with a tropical fish in it
2. Place it
4. See that it won't appear

**Expected behavior**
I think this should be fixed and I should be refunded 3 buckets of tropical fish (I don't care which types of tropical fish)

**Comment by prokillerr** [comment]
Mobs have been partially disabled for a long time, maybe that has something to do with it

**Comment by KarlOfDuty** [comment]
Should be fixed now.
