### ISSUE TITLE
[Feature] Bounty Plugin

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#634]
**Is your feature request related to a problem? Please describe.**
As of lately, many bounties have been placed but most of them have never actually been payed, so I think that a bounty plugin should be added to assure people to not scam with bounties

**Describe the solution you'd like**
I'd like to see that when you do /bounty you get to view bounties and by doing /bounty add {username} {bounty in gold} it would take the gold out of your possession and put it in a bounty account. Whenever a player with a bounty is killed, the player who gets the kill (unless the player with a bounty kills themself e.g. bow suicide).

**Comment by Highlander214** [comment]
this is a good idea, would help prevent scamming

**Comment by creatorfromhell** [comment]
The economy plugin is capable of this functionality with the latest releases too. :kappa:

**Comment by Pengun78** [comment]
War plugin when

**Comment by ImperialFishy** [comment]
War plugin when

**Comment by KarlOfDuty** [comment]
It has been added but we have not given out perms yet as we want to do some testing first.
