### ISSUE TITLE
[Feature][Plugin] Add artmap plugin (This might interest you if you like museums or own one)

### ISSUE THREAD

**Issue by Yazzed1** [EarthMC/Issue-Tracker#635]
Idk i just thought it would be nice if we had actual art we could put in museums,
or use artmaps and make decorations like a fridge or smth.
Here's some pics i took on another server for artmaps made by players.
![2019-07-09_14 24 18](https://user-images.githubusercontent.com/48289189/60884717-4cbf3f80-a256-11e9-8788-23764cf1bb8e.png)
![2019-07-09_14 29 45](https://user-images.githubusercontent.com/48289189/60884732-547ee400-a256-11e9-99ea-ed27c93081cf.png)
![2019-07-09_14 32 36](https://user-images.githubusercontent.com/48289189/60884767-6ceefe80-a256-11e9-81f4-dec86179f237.png)
![2019-07-09_14 32 42](https://user-images.githubusercontent.com/48289189/60884773-6f515880-a256-11e9-9c7a-8876f494fea2.png)

So uhh here's a video showing how the plugin works
https://www.youtube.com/watch?v=AZpSYOuxztM

**Comment by FutureCW** [comment]
100% yes

**Comment by ZestyPhallus** [comment]
Can I use it to make anime tiddies

**Comment by ZestyPhallus** [comment]
asking for a friend

**Comment by WhitPlayzYT** [comment]
How would this work? Just another world souly for map art? I think it's a cool concept

**Comment by Yazzed1** [comment]
https://www.youtube.com/watch?v=AZpSYOuxztM

**Comment by Yazzed1** [comment]
Oof didnt mean to do that lmao

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/62381581-6d0ab300-b511-11e9-88a2-6a938f4c57eb.png)

**Comment by MineHero43** [comment]
Yeah I fully agree with this suggestion, it could be used to display things such as store ads, nation borders, memes or just generally have fun with them and they're much easier to use than making a map art by hand.
