### ISSUE TITLE
[BUG] Chinese Chat Anti-Spamming False Positive

### ISSUE THREAD

**Issue by fengshuo2004** [EarthMC/Issue-Tracker#636]
**Server**
EarthMC.net

**Describe the bug**
Anti-Spamming Feature making false positives of messages in Chinese

**To Reproduce**
1. Switch to Chinese channel `/chinese` (this step is optional)
2. Text in Chinese
3. Text something again that is very different
4. Console responds `! Please do not repeat the same (or similar) message.`

**Expected behavior**
Not to block the message because I wasn't spamming.

**Screenshots**
N/A

**Additional context**
I guess you detect spamming by counting the number of repeated characters.
In which case _you need a higher threshold_ for Chinese language because languages work differently. Alternatively, you could _disable Anti-Spamming in the Chinese chat channel_ all together.

**Comment by DasCodes** [comment]
It's just not Chinese chat, but every chat! :harold:

**Comment by DasCodes** [comment]
Try not to include the same word.

**Comment by fengshuo2004** [comment]
> Try not to include the same word.
> 
> Edit: Or the plugin's detection is really bad.

@DasCodes
"Not including the same word" is rather impossible with Chinese, since:
for example: English words "together/harmony/and/kind/mix/peace" all translate to "和" in Chinese.
In summary, a lot of English words map to a single Chinese word (character, rather).
Two Chinese sentences that have 70% similarity by character would mean completely different things.
I suppose that's why this false positive problem happen WAY more often with Chinese messages than English.

**Comment by KarlOfDuty** [comment]
Should be fixed next restart.
