### ISSUE TITLE
Still kicked out of my own town despite being on under 41 days

### ISSUE THREAD

**Issue by TinyFgc** [EarthMC/Issue-Tracker#639]
I also went by "BarrettHans" but now is "TinyFgc"

I used to be the mayor of Neu_Hamburg, and I got bored of EMC after a while. I then started to slow down on playing the game. Only coming on every 10 days or so and staying on for an hour. Only recently I lost the ownership of the town and was passed down to the only member in the town and he is extremely inactive.
 
The point i'm trying to get at here is that I lost the ownership of my town despite me beingg on. I'm extremely angry about it too and i'm not sure if the times I got on "didn't count."

As i'm writing this i'm in another town for now temporarily but I desperately want my town back.

**Comment by YellowVictini** [comment]
Pergamon had the exact same issue a while back. I have seen this happen quite a few times recently, could this be Software side with Towny?

**Comment by TinyFgc** [comment]
@KarlOfDuty I'm on the server now.

**Comment by DasCodes** [comment]
Try pinging him on discord @TinyFgc.

**Comment by TinyFgc** [comment]
In what channel?

**Comment by DasCodes** [comment]
General?
