### ISSUE TITLE
[BUG] i unreasonabily got permernent ban

### ISSUE THREAD

**Issue by StrikeR2018** [EarthMC/Issue-Tracker#640]
**Server**
Which server the bug is on.

**Describe the bug**
i said this is cheat clinet, but actually i did nothing cheats on this client.
also, ban date is wrong, it said was banned on june first, but today is july.
My id in-game is M4ch1nE_StrikeR
Can u please re-check this ban seriously. THANKS.

**Expected behavior**

**Comment by DasCodes** [comment]
This isn't out support or ban appeal platform. Also, getting banned from the server is not a bug. Please use #info in our main Discord server to find our support Discord server and appeal your ban there.
