### ISSUE TITLE
[Feature] Elytra Custom Recipe

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#641]
I just think elytras would be just a cool feature to have, with a custom recipe I think would be a fair way to get them. I am suggesting an expensive recipe (below).
![image](https://user-images.githubusercontent.com/46661028/61194743-7f6f9a80-a691-11e9-8869-f3eee230a83b.png)

**Comment by FutureCW** [comment]
Imo i think they should add the end and just call it "The Moon"

**Comment by WhitPlayzYT** [comment]
I think they shoudnt add the End cus another world would just cause even more lag

**Comment by Highlander214** [comment]
elytras should be very expensive, but just having them available would open up so much more things to do.

**Comment by FutureCW** [comment]
@WhitPlayzYT tons of elytras loading in more chunks all the time when people are flying would cause way more lag

**Comment by WhitPlayzYT** [comment]
@FutureCW people would be flying around in the end to find more end cities and loading in even more chunks which would cause just as much if not more lag

**Comment by FutureCW** [comment]
What? You have people searching for elytra early on which will die out, and then permanently loading chunks in the overworld every day for the rest of the server’s life. It’s not like the search for elytras by people with elytras will continue forever.

**Comment by WhitPlayzYT** [comment]
remade the recipe to prevent people to get them easily 
![Elytra Crafting 2 EMC](https://user-images.githubusercontent.com/46661028/61666342-375e0280-aca5-11e9-8cb4-88084c876de6.png)

**Comment by ImperialFishy** [comment]
Elytras are kinda game breaking on a server like this, id personally prefer it if they arent added at all

**Comment by KarlOfDuty** [comment]
We will not be adding elytras as they will result in a giant amount of additional loaded chunks.
