### ISSUE TITLE
[Suggestion] Enable perms for chancellors and nation leaders to do /n set tag

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#642]
So basically, we used to have these perms and were able to change our nation tags to like "CREE" as an example. They'd be nice to have back as they were cool. Here's an example of how /n set tag and /t set tag could be used.
![happynewyears](https://user-images.githubusercontent.com/46413791/61253875-8e595a00-a730-11e9-9ed0-378ec799cb1b.PNG)

That's from New Years on EMC

**Comment by KarlOfDuty** [comment]
Done on next restart.
