### ISSUE TITLE
[ Feature ] BottleExp plugin recipes.yml

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#643]
I've been messing around with a few plugins on a private server I'm making for build and leisure, and I learned EMC's current plugin for Enchant bottles has a file titled _recipes.yml_ that allows you to craft enchantment bottles.

I recommend the first and second recipes, the third is a bit unobtainable.
It'll make use of another valuable resource and it'd be very epic.

**Comment by FutureCW** [comment]
Since main forms of fast xp are disabled I think this is a really good option

**Comment by Cactusinapumpkin** [comment]
I dont like this because I xp bottles are some what cheap and could lose value if it was easily craftable. 
I get most my xp from the blaze grinder, funaces, ville trading, and fishing.

**Comment by DasCodes** [comment]
You can always get those experience bottles with `/bottle`.

**Comment by Prismary** [comment]
No longer recent, EXP bottles have been obtainable for a long time now.
