### ISSUE TITLE
[BUG] The /n set tag command works but does not show your tag in chat

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#644]
![ntagnowork](https://user-images.githubusercontent.com/46413791/61359736-f603c800-a84a-11e9-824d-2b2dc1c35286.PNG)
I did /n set tag Area and the expected result would be [AREA][Area32] Thicc FutureCW:
Instead it didn't change anything

**Comment by KarlOfDuty** [comment]
Right, we use a different chat plugin now which probably doesn't have that.
