### ISSUE TITLE
[Suggestion] Remove new player's protection

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/Issue-Tracker#647]
Literally nothing good comes of new player resistance, everyone on factions hates it. It's fine for towny not for factions, just had someone come into our base and kill our high value villagers and dogs - no way to stop him because he's immortal to all damage

If we encase them then the new players are having no fun and have no way out as they're immortal

If they grief us then it's bad for us as we can't stop them as they're immortal

Don't give players on a PvP server immortality it's not a strange concept

**Comment by KarlOfDuty** [comment]
Done.
