### ISSUE TITLE
[Suggestion] Make Horses Breedable with Regular Apples/Carrots

### ISSUE THREAD

**Issue by EchoOcelot** [EarthMC/Issue-Tracker#648]
Horses are normally bred using golden apples and carrots. Due to this being the monetary unit on the server, it is essentially wasting money. Along with that, breeding does not always work, meaning that someone can waste tons of gold just to breed two horses. I think that normal apples and carrots should be able to be used to breed them instead.

**Comment by WhitPlayzYT** [comment]
Just get rich owo

**Comment by Aitonater** [comment]
Horses are rare and so is the opportunity to breed them. 2 gold bars essentially to breed a pair of horses is 1/5 of what you can make in a day just from voting. You can mine over 100 gold in an hour. Dont be so stingy. If you are worried about wasting the gold test breeding on other animals like sheep or cows first before trying horses and make sure the mob limit has not been reached on the plot.

**Comment by Cactusinapumpkin** [comment]
All horses have three "equine stats" which vary from horse to horse: health, (maximum) movement speed, and jump strength. These stats are created once the horse is born or spawned, and are not affected by food. You can feed them sugar if you don't want to use gold.

**Comment by DeadGlamour** [comment]
Eh you can only breed horses with golden carrots or golden apples, nothing else works.
Also, since horse breeding sucks in minecraft its better to just spawn them with mcmmo apples.

**Comment by Cactusinapumpkin** [comment]
You still have to breed them to keep the offspring before the parents die most of the time.  8g = 1 stack of gold carrots thats pretty cheap.

**Comment by DeadGlamour** [comment]
This might not be useful rn but, if you move the horse into the nether/out of it, he wi stay forever, I think the same applies if you just unload the chunks with the horse.

**Comment by docwhomc** [comment]
> This might not be useful rn but, if you move the horse into the nether/out of it, he wi stay forever, I think the same applies if you just unload the chunks with the horse.

That sounds like a bug for a separate ticket.

**Comment by docwhomc** [comment]
If you don't think horses are worth the gold it costs to breed them, then don't breed them.
