### ISSUE TITLE
I cant join the server

### ISSUE THREAD

**Issue by Blunder96** [EarthMC/Issue-Tracker#649]
When i want to join the server, i cant.

The message is the next: Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException.

I already tried like 40 times and since one week

**Comment by KarlOfDuty** [comment]
Which minecraft versions have you tried?

**Comment by Blunder96** [comment]
1.12.2

**Comment by KarlOfDuty** [comment]
Indeed, switch to 1.13.2 please.
