### ISSUE TITLE
[BUG] Cannot change faction perms on Factions server

### ISSUE THREAD

**Issue by Locotime** [EarthMC/Issue-Tracker#650]
**Server**
Which server the bug is on.
Factions

**Describe the bug**
Cannot use /f perms to set permissions for faction members

**To Reproduce**
1. Be faction lead and type /f perms
2. On menu that appears try and choose any of the ranks/relations in order to change their permissions

**Expected behavior**
Bugged behavior: nothing happens
Normal behavior: a new menu opens, allowing leader to change permissions of the selected rank

**Comment by Locotime** [comment]
@KarlOfDuty 
An update to this issue, likely caused by the same update, factions cannot disband. User attempted to disband their faction and got an internal error. The faction was not able to disband because of this, even though the event fired, as seen in the image below.
![image](https://user-images.githubusercontent.com/12216178/61668155-86099d80-aca1-11e9-9df3-fbc450b6ea28.png)

**Comment by KarlOfDuty** [comment]
Factions plugin has been updated, seems to work most of the time now.

**Comment by Locotime** [comment]
@KarlOfDuty It is working more of the time now, but any faction that has set any permission to denied can no longer access that rank of /f perms.
I.e. Set chest access to denied for recruits, after setting this, the user will not be able to access the recruits section of their /f perms

**Comment by KarlOfDuty** [comment]
Ok, I see.

**Comment by KarlOfDuty** [comment]
Should be fixed.
