### ISSUE TITLE
It wont let me join the server 

### ISSUE THREAD

**Issue by UltraRetarded** [EarthMC/Issue-Tracker#651]
Everytime I am joining EarthMC server 
and then it just freezes at the "Joining World"
and a few seconds later it just says me the error "Timed Out"
Can please someone help me with this annoying problem
I really need to get in.
#earthmc

**Comment by Warriorrrr** [comment]
Yeah the server isn't accepting any players atm for no particular reason, nobody can get in. Just wait for a bit and it should be all gud

**Comment by UltraRetarded** [comment]
ok thank you
