### ISSUE TITLE
[Suggestion] Make it so you can play on EarthMC while on 1.14.4

### ISSUE THREAD

**Issue by Memetric** [EarthMC/Issue-Tracker#652]
I would appreciate it if you can make it so you can play on EarthMC on version 1.14.4.

**Comment by FutureCW** [comment]
Why? Just load minecraft on the 1.13.2 version

**Comment by WhitPlayzYT** [comment]
Plus some plugins still need to be updated to be patient

**Comment by KarlOfDuty** [comment]
Done.
