### ISSUE TITLE
Connectionlost

### ISSUE THREAD

**Issue by elotendo** [EarthMC/Issue-Tracker#653]
**Server**
EarthMC.net

**Describe the bug**
this message is displayed when I try to connect to the server : "could not connect to a default or fallback server,
![image](https://user-images.githubusercontent.com/53096797/61558722-152b7100-aa68-11e9-8010-e3f5afd0758d.png)
![Capture](https://user-images.githubusercontent.com/53096797/61558767-3ee49800-aa68-11e9-9d4f-e7e4b6105fc9.PNG)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DasCodes** [comment]
What version of Minecraft are you using to connect?

**Comment by elotendo** [comment]
I tried the following versions : 1.12.2 (forge), 1.11.2 and 1.14.4.Same problem for those versions.
    On Saturday, July 20, 2019, 10:59:36 AM GMT+2, CloakedEagle <notifications@github.com> wrote:  
 
 
What version of Minecraft are you using to connect?

**Comment by DasCodes** [comment]
Use 1.13.2.

**Comment by elotendo** [comment]
thank you.It works now.
    On Saturday, July 20, 2019, 02:33:06 PM GMT+2, CloakedEagle <notifications@github.com> wrote:  
 
 
Closed #653.
