### ISSUE TITLE
I want unban 

### ISSUE THREAD

**Issue by Antoine2lop** [EarthMC/Issue-Tracker#655]
Hello I have a problem on Earthmc I'm staying afk to go to the market is coming back me is my sister have been ban ip + account that we do please answer me please

**Comment by FutureCW** [comment]
What did you do

**Comment by Antoine2lop** [comment]
> What did you do

Nothing i'm just staying afk to go to the market

**Comment by FutureCW** [comment]
You obviously did something. What did it say you were banned for

**Comment by FutureCW** [comment]
If you used an afk pool you most likely got banned

**Comment by Antoine2lop** [comment]
![image](https://user-images.githubusercontent.com/38099787/61594499-eee30e00-abec-11e9-9735-5db47b8d7474.png)

**Comment by Antoine2lop** [comment]
its my sister account

**Comment by FutureCW** [comment]
What did Antoine2lop do

**Comment by FutureCW** [comment]
Did she do anything bad?

**Comment by Antoine2lop** [comment]
![Capture](https://user-images.githubusercontent.com/38099787/61594509-03270b00-abed-11e9-9e83-77f7cac2b568.PNG)
my account

**Comment by Antoine2lop** [comment]
![Capturesss](https://user-images.githubusercontent.com/38099787/61594519-1e921600-abed-11e9-9763-48cb2546cd9b.PNG)
My account reconnection

**Comment by FutureCW** [comment]
Yeah you can’t use an afk pool my dude.

**Comment by FutureCW** [comment]
https://discord.gg/EZBYmpp Go here and make a ticket about your sister

**Comment by Antoine2lop** [comment]
I have afk in the exit of my base

**Comment by DasCodes** [comment]
This is not the place to appeal your ban. So if you seek support please use our support discord instead of making an issue on GitHub.
