### ISSUE TITLE
Remove @mod ping

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#656]
If you pay attention to towny chat you can tell that @mod is misused tons of times on EarthMC. Or you could just look at all the staff members with Do Not Disturb on. Why exactly do players need to ping the entire staff team anyways when the most likely scenario is that a player pinged a mod for no reason? That seems counterproductive if you want staff that are going to be proactive and helpful to players.

**Comment by ZestyPhallus** [comment]
@FutureCW

**Comment by FutureCW** [comment]
Bruh

**Comment by DasCodes** [comment]
Any suggestion?

**Comment by FutureCW** [comment]
Suggestion for?

**Comment by DasCodes** [comment]
To improve productivity. The @ tag is there for us to notice it, even though many abuses it all the time but we do notice when we get pinged even if we have DND on, and in a case of emergency.

**Comment by FutureCW** [comment]
A replacement for it would probably be checking the discord and asking for a specific mod instead.

**Comment by FutureCW** [comment]
One that’s online of course ^

**Comment by KarlOfDuty** [comment]
I don't think there really is a valid replacement available.

**Comment by FutureCW** [comment]
bruh. just ping a specific online mod.
