### ISSUE TITLE
[BUG] Donators STILL don't have access to /list

### ISSUE THREAD

**Issue by Magenent** [EarthMC/Issue-Tracker#659]
Donators do not have access to /list which is something I and many others partially paid for. /list is important to tell when mods are on, and what rank certain people have, as well as seeing who is online with one command instead of having to go through nation and town lists. And it is something that was removed for seemingly no reason, not only that but to fix it would be a simple matter of going into the console and typing a couple lines of code to give permissions to donators, or everyone.

  Also there is no arguement of "well we didn't know" since I've made a ticket about this around a month or more ago.

**Comment by WhitPlayzYT** [comment]
they removed it as people were using it to see when mods werent on to break rules and such

**Comment by ImperialFishy** [comment]
Theres more ways to see if mods are on...

**Comment by DasCodes** [comment]
`Still`? Last time you reported, you were bugged. Are you sure you aren't bugged this time?

**Comment by Highlander214** [comment]
same eagle, i dont have perms

**Comment by KarlOfDuty** [comment]
No, /list is turned off like @WhitPlayzYT says.

**Comment by Magenent** [comment]
> No, /list is turned off like @WhitPlayzYT says.

Regardless it comes with negative things as well like i pointed out, and it was also something that everyone before the donator ranks were removed and then put back that people at least partially paid for. So there should be some sort of compensation, in other sorts of trivial perms. Or the best option would be to make it so that mods don't show up, only donators and generic people. And like I said it'd only be given back to donators not everyone, and if you spend money on the server your much less likely to break the rules. Also it gets to an extent where yes there might be minutely more people breaking the rules when staff are offline with /list, but its not like people can't already check since there aren't a lot of mods so you could go out of your way to check with /n online or /t online. But also even with mods online unless they are patrolling 24/7 the only stuff that would be caught is chat rules, which are the least worst, compared to dupes, hacks etc, and usually get reported anyway.

**Comment by WhitPlayzYT** [comment]
Donator didn't pay for anything (it's a donation that should not have expected rewards).
Deal with it

**Comment by Magenent** [comment]
> Donator didn't pay for anything (it's a donation that should not have expected rewards).
> Deal with it

Not really, just because it's called donator doesn't mean its a donation there is stuff that they say they WILL give you and then you pay on terms with that agreement I doubt nearly anyone would donate without these perks so it is effectively a purchase.

**Comment by WhitPlayzYT** [comment]
Look at the ToS

**Comment by Magenent** [comment]
> Look at the ToS

Yeah I know it's not technically a purchase, but effectively it is one, and it is still scummy and terrible business practices to straight up remove something that people paid for.

**Comment by WhitPlayzYT** [comment]
Anyone could use /online for the longest time so it's not removing something people paid for

**Comment by Magenent** [comment]
> Anyone could use /online for the longest time so it's not removing something people paid for

no you can't do /online

**Comment by WhitPlayzYT** [comment]
I said anyone **could** use it for the longest time, it was never a donator perk

**Comment by Magenent** [comment]
> I said anyone **could** use it for the longest time, it was never a donator perk

no it was a donator perk, before they temp removed donator ranks the first time, you are too new to remember this

**Comment by WhitPlayzYT** [comment]
It's not even a command that you really need that Karl has even told you why it's disabled
So
Just
Deal
With 
It

**Comment by KarlOfDuty** [comment]
Indeed, for now you'll just have to use the command autocomplete list instead.
