### ISSUE TITLE
[Feature] Spider Eyes

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#660]
Spider eyes are currently almost impossible to get, so I think a expensive custom recipe would be a fair way to add them. (Recipe below)

![spider eye recipe emc](https://user-images.githubusercontent.com/46661028/61665928-44c6bd00-aca4-11e9-9461-10e40e5e70dd.png)

**Comment by ImperialFishy** [comment]
No

**Comment by WhitPlayzYT** [comment]
that was a quick response

**Comment by ImperialFishy** [comment]
Just happened to be here ¯\_(ツ)_/¯

**Comment by gayASF** [comment]
replace ingot with a block

**Comment by Aitonater** [comment]
This looks decent. Tbh any recipe would do I just want them to be obtainable.

**Comment by Ra2orLeaf** [comment]
Any spider eye recipe would do or a way to spawn a spider like an spider egg recipe

**Comment by DasCodes** [comment]
As mob spawning is enabled this should be sorted now.
