### ISSUE TITLE
[Feature] Plot PVP toggle cooldown

### ISSUE THREAD

**Issue by XioanAskari** [EarthMC/Issue-Tracker#661]
**Is your feature request related to a problem? Please describe.**
Plot owners like to toggle pvp on their land to fight but, then toggle it off if they are losing, making it unfair.

**Describe the solution you'd like**
Give the toggling of pvp on a plot a 1/2/3 min cooldown to stop abusers

**Additional context**
Make it so if a person is constantly running into a no-pvp area while combat tagged they are marked and lost the pvp protection on the plot

**Comment by WhitPlayzYT** [comment]
no

**Comment by XioanAskari** [comment]
So  you prefer people to unfairly have a advantagfe?

**Comment by WhitPlayzYT** [comment]
yes

**Comment by WhitPlayzYT** [comment]
I only say that because if someone is dumb enough to go into a plot where another person there has perms to toggle pvp they deserve to be abused

**Comment by Ukai-Oita** [comment]
Yeah, this seems like a user issue and not a feature issue. Don't duel people in their plots. Go somewhere, like an arena or the wilderness, where PvP is enabled out of both duelers' control.

**Comment by Aitonater** [comment]
I dont agree with this. If you want a fair fight go into the wilderness. If you take the fight to someones home or town then you deserve everything you get for being that stupid. If you continue to roll back any benefit and control of having towns then they become pointless.

**Comment by ImperialFishy** [comment]
I agree with aitonator, home town advantage is a thing

**Comment by KarlOfDuty** [comment]
You should suggest this to the towny developers instead.
