### ISSUE TITLE
could not connect to default or fallback server

### ISSUE THREAD

**Issue by 0n** [EarthMC/Issue-Tracker#663]
**Server**
any

**Describe the bug**
I log in I get this error

**To Reproduce**
1. Go to 'multiplayer'
2. Click on 'earthmc'
3. See error

**Expected behavior**
Get on the queue server

**Screenshots**
![Capture646874](https://user-images.githubusercontent.com/45835056/61671132-44ceb900-acb4-11e9-9e09-03c13bc521f8.PNG)

**Additional context**
happens with a modded client and a vanilla client

**Comment by DasCodes** [comment]
This is not our support platform. If you want to reach us faster, please use our support discord found at #info in EMC discord.

Speaking about your issue, what version are you using?
