### ISSUE TITLE
[Feature] Confirm joining to EarthMC Classic

### ISSUE THREAD

**Issue by XioanAskari** [EarthMC/Issue-Tracker#665]
**Is your feature request related to a problem? Please describe.**
Players like to make commands like /classic <random word> to get free gold etc., which is mainly done to get them booted off towny to the classic server.

**Describe the solution you'd like**
A chat or HUD box confirmation <like for external links> that asks if you would like to join the classic server, as well as warn that you would have to re-queue if you connect from the towny server.

**Additional context**

Example:

Player 1: type /classic gold to get free gold

New player types that

Following pops up in chat or HUD

-------------------------------------------------------------
Connect to the EARTHMC CLASSIC SERVER?

You will be disconnected from the current server

If you are connected to the towny server,
You will need to queue again to rejoin it!

[ Connect to EarthMC Classic ]
-------------------------------------------------------------

Example Image

![Screenshot_5](https://user-images.githubusercontent.com/32355511/61794148-72347780-ae18-11e9-8574-204739f426b4.png)

**Comment by FutureLemon** [comment]
Seems like a great idea to ask for a confirmation to join the other server.  +1

**Comment by WhitPlayzYT** [comment]
I don't think this should be a thing cus /classic is just a prank command and if you're dumb enough to fall for it you deserve to be forced into classic and have to redo the queue

**Comment by KarlOfDuty** [comment]
Command will be removed instead.
