### ISSUE TITLE
[Feature] Make and anti anti-fuze spammers

### ISSUE THREAD

**Issue by RealNigong** [EarthMC/Issue-Tracker#666]
Some (a lot) of people are spamming as fuck when a famous player like Fuze are online, so can a modo put a chat slower when the chat is full of " go kill fuze " or any other useless things like that, i'ts not because i write that that i like fuze, i'ts for the readability of the chat.

**Comment by KarlOfDuty** [comment]
We have requested a slow mode feature from the chat plugin we use but it is not currently possible.
