### ISSUE TITLE
[Feature] Discounted Plus ranks/upgrade rank if you own a lower teir

### ISSUE THREAD

**Issue by XioanAskari** [EarthMC/Issue-Tracker#667]
**Is your feature request related to a problem? Please describe.**
Currently even if you pay $9.99 for JUST priortiy, you have to pay another $19.99 for the basic yellow rank, when plus rank INCLUDES the priority access.

This also includes upgrading your plus rank to a higher 

**Describe the solution you'd like**
Plus ranks would have the priorty amount subtracted and/or the option to buy an upgrade to next teir of plus rank would be avalible

**Additional context**

N/A

**Comment by KarlOfDuty** [comment]
The store is made by a third party called Buycraft, we can't create such a system as we do not have access to their stuff.
