### ISSUE TITLE
[Feature] Thank you for adding CombatlogX

### ISSUE THREAD

**Issue by ZestyPhallus** [EarthMC/Issue-Tracker#669]
**Thank you so much for adding anti-combat log. The community barked, and you listened.**

But now that we're on our very short 1 week trial, I just a have a few suggestions!

When a player is tagged in combat, please do not prevent them from building or performing commands. I've seen this on other servers, it's absolutely trash.

Since nothing currently happens when someone combat logs, it'd be excellent if the following could be implemented:
1. They die immediately upon logging.
2. Duration of combat tag should last around 2-3 minutes. _Too many times, have players on factions run for however long their combat tag lasts, and immediately log once it goes away due to very short timer._
3. An announcement "**[player] has attempted to escape death by logging! Shame!**" Just so the community knows it's frowned upon to log. _(community would flood chat with "Shame!")_

Thanks for your time!

**Comment by ZestyPhallus** [comment]
bump

**Comment by FutureLemon** [comment]
2-3 minutes are quite insane, but I get where you come from tho.

**Comment by WhitPlayzYT** [comment]
I agree with lemon

**Comment by watergod1234** [comment]
Yo, I think I love you.

**Comment by Aitonater** [comment]
I agree with 1. And 3. But I feel that if someone has managed to evade you for 10 or 20 seconds they have earned the right to get away on account of you not being able to hunt them in time, even if the combat log timer is 10 seconds -people can still tp away. It's your job to not let them if you're fighting them. If they manage to get away and not take enough damage to trigger combat logging in that time. I think they've earned it.

**Comment by KarlOfDuty** [comment]
This has already been changed.
