### ISSUE TITLE
[Plugin] Ridables

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#670]
While ago I stumbled upon this plugin, which allows players to ride any kind of mobs in the world. Since turtles are quite useless, could this plugin be added to allow us to use turtles as transportation thru waterways? The plugin is configurable in terms of which mobs, so it wouldn't be bad to see armies of people riding chickens into the enemy base. Or Ghasts. ;)

It could be good for times when mobs start to spawn in wilds, so we could easily bring them home if needed... 
[https://www.spigotmc.org/resources/1-13-2-ridables-ride-and-control-any-mob-with-full-wasd-control.58985/](url)

**Comment by WhitPlayzYT** [comment]
I don't really see the need for this, just my opinion tho

**Comment by docwhomc** [comment]
Dolphins... if we can ride pigs, we should be able to ride dolphins.

**Comment by KarlOfDuty** [comment]
We will not add this due to performance concerns.
