### ISSUE TITLE
[Feature] /ignorelist

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#671]
I just think there should be /ignorelist to make it easier to see who you have ignored in case you forget

**Comment by KarlOfDuty** [comment]
Pretty sure that is already a thing.

**Comment by KarlOfDuty** [comment]
Hmm apparently only the essentials ignore command and not the chatcontrol one has it.

**Comment by WhitPlayzYT** [comment]
Whenever I do /ignorelist it says unknown command

**Comment by Warriorrrr** [comment]
You used to be able to do /ignore ? to see who you have ignored, but trying that now just gives you an unknown command error.

**Comment by KarlOfDuty** [comment]
You can suggest this to the chatcontrol dev if you still want it.
