### ISSUE TITLE
Paid unban system

### ISSUE THREAD

**Issue by YYLIQ** [EarthMC/Issue-Tracker#673]
There should be a paid unban system where people who are not blacklisted from being able to buy unbans (for things like ddosing or doxxing). People who have cheated in the past or broken another rule should be able to get a second chance with paying some money ($10-$30). This insures that players are not abusing this new system. Also players who buy an unban will be unable to purchase another one for life/a long time. With this being added the server should also add a discord chat where mods post evidence for bans. This would make sure that the mods/owners aren't abusing this system for money either.

**Comment by WhitPlayzYT** [comment]
Emc isnt the type of server to have this added

**Comment by YYLIQ** [comment]
Ok then people with vpns don't need to pay and can just keep playing on as many accounts as they can buy. You can get accounts for 5 cents and vpns are not expensive either.

**Comment by WhitPlayzYT** [comment]
It's not gonna happen, mods/Karl are gonna instantly deny this as soon as it's seen

**Comment by YYLIQ** [comment]
No you

**Comment by WhitPlayzYT** [comment]
Quit trying to get yourself unbanned

**Comment by WhitPlayzYT** [comment]
Told ya so

**Comment by docwhomc** [comment]
@YYLIQ Minecraft accounts for 5 cents?  Really?
