### ISSUE TITLE
Priority queu

### ISSUE THREAD

**Issue by CobraStrike133** [EarthMC/Issue-Tracker#675]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by CobraStrike133** [comment]
I buy the priority queue but dont really seem to work ,im in queue for like 30min ^^'

**Comment by WhitPlayzYT** [comment]
It takes time to register that you bought priority

**Comment by KarlOfDuty** [comment]
Please use the discord support server, this is for reporting bugs, not solving payment issues,
