### ISSUE TITLE
[Feature]Classes

### ISSUE THREAD

**Issue by SnUncle** [EarthMC/Issue-Tracker#676]
Hey,

I think factions is in need of some new features to keep people playing and I believe classes might be a good choice. I am happy to make a demo class for you(by skillapipro). If you like the idea just let me know and ill create a local for an admin to test out

**Comment by SnUncle** [comment]
my opinion is divide ppl to diffrent class in combat will be more fun and also make people not useless 
 some basic skills like Assault(jump forward target if hes ur allie he will got a buff or the target will get slowness for 3s)  Requiem(delay 3s and make ur target slowly falling asleep for 2s)  will not affect the balance of the battle, and will add more uncertain factors. 

Restricting class's armor allows different classes to perform their duties so op's class will be weak and need fac's member to protect him

**Comment by SnUncle** [comment]
i did some example on local (Assault and Requiem) if anyadmin wanna check it plz dm me

**Comment by SnUncle** [comment]
Hey guys i got a demo on my server now . if anyone wanna check it plz let me know.

**Comment by watergod1234** [comment]
For the love of god no.

**Comment by WhitPlayzYT** [comment]
^

**Comment by SnUncle** [comment]
https://www.spigotmc.org/resources/skillapi-premium.28029/ this is what plugin i use for classes

**Comment by docwhomc** [comment]
Could be interesting.

**Comment by KarlOfDuty** [comment]
This is not something which we wish to implement.
