### ISSUE TITLE
Crash on joining queue

### ISSUE THREAD

**Issue by informathemusic** [EarthMC/Issue-Tracker#678]
**Server**
**Fallback/Queue** server

**Describe the bug**
It says: **Unknown custom packed identifier : queue:join**

**To Reproduce**
1. Join queue
2. *Crashes*
3. Open logs

**Expected behavior**
I expected to join the queue

**Screenshots**
No screenshots

**Additional context**
My computer is not powerful

**Comment by KarlOfDuty** [comment]
Is that the entire error? When does it happen exactly, when joining the server or when picking the towny/factions server?
