### ISSUE TITLE
[Factions] Wither Changes

### ISSUE THREAD

**Issue by Sabatarge** [EarthMC/Issue-Tracker#679]
I'm writing this on behalf of UncleSnn who speaks good English but it's not his first language

On factions the easiest way to raid someone at the moment is through using a wither, withers break obsidian, water and there is no defense against them no matter how much time or effort you put into a base it can be destroyed with a single use. These have become incredibly common with anyone being able to obtain them with relative ease, this is due to wither farms bringing in 20 skulls a day and the fishing "shake" skill allowing for infinite skulls from just one skeleton. 

This has changed the meta of factions from active raiding to just simply going up to any faction you like and offline withering them, little to no actual fighting. Bases have become near pointless to build as they are so easily destroyed.

No one wants to get rid of withers as they are so useful but people just want them to become less common place instead of having stacks of them in their back pocket

Snn wants to modify an already existing plugin which he can code that will allow for withers or wither skeletons to become a world spawn sending a notification to all players that they are in a certain area encouraging them to be hunted in groups (and of course provide an incentive PvP). They will in turn drop wither skeleton heads at an adjustable rate allowing for staff to control the frequency these nuclear weapons can be used

If you want to message him about the plugin idea just reply to this and i'll pass it on or discord him at Sn#7574

**Comment by SnUncle** [comment]
https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/ this is the plugin i use to make mobs

**Comment by ZestyPhallus** [comment]
You obviously don't have priority or have been on EMC long enough to know we are incapable of running mobs especially at this capacity.
I love the ideas, SnUncle, but your ambition is crippled on this server.

**Comment by SnUncle** [comment]
> You obviously don't have priority or have been on EMC long enough to know we are incapable of running mobs especially at this capacity.
> I love the ideas, SnUncle, but your ambition is crippled on this server.

no i been play on EMC factions 1 mounth and i know the mobs hard o running on the server 
so my idea its like make a mob egg for summon a wither boss and you can get it by vote/donate/or recipe. 
you and summon it at wildness and is also then it will boradcast to every ppl on this server

**Comment by ZestyPhallus** [comment]
It'd be interesting, but I think it's clear Fix & Karl don't want things to be "easy" on EMC.
I feel they should emphasize that so gamer's know what to expect.

**Comment by SnUncle** [comment]
> It'd be interesting, but I think it's clear Fix & Karl don't want things to be "easy" on EMC.
> I feel they should emphasize that so gamer's know what to expect.

sir you should come and play factions server .
i get this idea just becoz one of my fac member had 1000 fishing skill and we are so ez to get wither skulls . besides some another player got a wither skeleton farm and ez to get withers for destory every base 
they cast 2 ~3 withers in oneday and do offline raid ez its destroying the game of all players

**Comment by ZestyPhallus** [comment]
EMC Factions was the unwanted sequel of EarthMC. 
Don't @ me

**Comment by SnUncle** [comment]
hehe

**Comment by Sabatarge** [comment]
This is exclusively for factions, mobs run on factions because the playerbase rarely hits the peak limits. Wither skeletons spawn regardless of it as they are nether mobs and Withers are spawned 3/4 times a day, 5 today I believe

**Comment by SnUncle** [comment]
https://www.youtube.com/watch?v=H1u3pDZ-8oY&feature=youtu.be 
this video is about the wither changes i made today

**Comment by CasperFactions** [comment]
if any of the staff sees this they should implement this change. A faction with the name starting with an S and a faction starting with an O wither pretty much every single day and if they want they can destroy everyone and it completely ruins the fun. As sabatarge said bases are pointless unless you make the walls like 50 blocks thick which nobody will do. The only solution is either making withers harder to get and maybe nerfing them or just disabling them and making tnt able to break obsidian (but dont make it explode the obby like dirt of course). That would also make tnt way more useful.

**Comment by PreciseEMC** [comment]
I agree with this topic, I was part of an OP Faction for a while and its really easy to destroy any other faction base with a wither while they are offline.
If new players knew about this they wouldn't bother creating bases, unfortunately they learn about it a week or so after building.

**Comment by Sabatarge** [comment]
50 layer thick walls won't do anything, if the wither feels suffocated it breaks any of the blocks around it to prevent suffocation so they can easily be pushed into walls repeatedly, 500 layers thick and it still only takes 3 witherheads. I hope Karl sees this thread and considers the changes

**Comment by AlphaiaCP** [comment]
Casperr you gotta add that 'beginning with Y'.

**Comment by DasCodes** [comment]
You can no longer able to get wither skull from mcMMO fishing on factions at this moment. We'll see how it works, depending on it we'll be changing the value in the future.
