### ISSUE TITLE
[World] No Terracotta anywhere on the map

### ISSUE THREAD

**Issue by Sulakek** [EarthMC/Issue-Tracker#68]
so the release of terra nova i was going to build my clock the only problem is that i didn't have any terra cotta i said in the chat:where to find terra cotta
they said it was in australia so i looked at australia, only red sand and grass 
very strange theres no terra cotta anywhere

**Comment by shirazmatas** [comment]
Terracotta can be crafted https://minecraft.gamepedia.com/Terracotta
But it will also probably be added too when worldedit is reenabled and less players online

**Comment by NilsNyfiken** [comment]
There is not that much clay that can be turned into terracotta either

**Comment by PoppyK** [comment]
The Grand Canyon will be all terracotta and is in the process of being made.

**Comment by PoppyK** [comment]
I didn't mean that the canyon would be the only place with terra.  Just that, it was my priority issue atm.

**Comment by PoppyK** [comment]
I have added terracotta to the map in these locations.  More will be added as my time allows.  Africa: https://i.gyazo.com/ac48404f06227e3c57ec4a9441fb852b.jpg  Australia:  https://i.gyazo.com/4d23375b91cdc2bd26ef55baf6c4884a.jpg  United States: https://i.gyazo.com/4a0993a2fc18d405327d12a4ef418bda.png

**Comment by TypicalFernie** [comment]
If y'all are gonna mine the terracotta don't mine it on the surface. The terracotta goes really deep underground. k thx

**Comment by PoppyK** [comment]
Placed another deep terracotta mine in the Somalia/Ethiopia area.  https://i.gyazo.com/a349884796e2b0510ff7f3db04af0f8a.png
