### ISSUE TITLE
[Feature] Change rules for if a town can join a nation

### ISSUE THREAD

**Issue by Ra2orLeaf** [EarthMC/Issue-Tracker#680]
I’ve just created a town that should eventually join Somerset. However I can’t join yet as my town is to far away despite being reasonably close to a Somerset town.

Instead of only being able to join nations where the capital is less than 3000 blocks away I propose that you can join a nation on the condition that there is a town less that 1000 blocks away. To avoid just making towns for the sake of trying to get a big town in your nation you could say the town must have a decent population (you can come up with the number.

I think it would be a good way to see nations continue to expand instead of stopping after they reach a certain point.

**Comment by WhitPlayzYT** [comment]
If this was added that mean nations could have towns on the other side of the world by abusing this as a feature so it's probaly not gonna get added

**Comment by Ra2orLeaf** [comment]
You could combat this by saying the town in question has to has a min population of say 10% of the national population

**Comment by Ukai-Oita** [comment]
This is a profound idea that would change the way nations form and expand for the better.

Is it possible? It sounds difficult.

**Comment by Aitonater** [comment]
This is basically increasing the nation range with extra, more complicated steps. The nation range exists to make nations somewhat realistic and confined to certain areas of the earth. With this you could have a nation that spans the whole earth by piggybacking towns upon towns away from the capital to the other side.

**Comment by Ra2orLeaf** [comment]
Another way to stop piggybacking towns would be just to have staff looking over it. They could always step in and say that ur piggybacking and take according action. Also it would be realistic to have some nations bigger than others. For example irl Russia is much bigger than say japan.

**Comment by docwhomc** [comment]
Require that a minimum of _m_ players in a town have been active in the last _n_ days for the town to count.  Also require that for a town to count, it needs to have a "connected" back to the capital.

By "connected" I mean within range of the capital or within range of another town that is "connected" and counts based on player count and activity.

On a side note, colonial powers like the Britain, Portugal, Spain, etc. were far from confined to one area.

**Comment by DasCodes** [comment]
As @WhitPlayzYT stated above this will easily be abusable and the solution you provided `You could combat this by saying the town in question has to has a min population of say 10% of the national population` will require to define boundaries for each country and etc. Which we are not looking for. So, for now, we'll be keeping the current rule i.e. has to be within the defined range from the capital.
