### ISSUE TITLE
[Player]

### ISSUE THREAD

**Issue by Fougah** [EarthMC/Issue-Tracker#681]
A player scammed me and said that the moderators are useless I would like to prove him the opposite.  He is called ISweaz06 on the server and he took me 3 blocks of gold against emerald but he gave me only 3 stacks of emeralds against the 27 promised.  This situation is embarrassing because I spend more than one day collecting all this and I will not hide that I am deeply saddened.  I hope we can find a solution together.  My username is Fougah in-game

**Comment by WhitPlayzYT** [comment]
Scamming is allowed

**Comment by shirazmatas** [comment]
1. This is not against rules
2. This github is for reporting Bugs, feature requests, and world issues
3. IF you want scamming to be against rules please use the rules github to suggest a rule change https://github.com/EarthMC/EarthMC.net/issues
4. Use trusted shops or shop signs to make trades. you can also use redstone shops.
