### ISSUE TITLE
[Suggestion] Use XYZ coords in "/t" infopane instead of chunk coords.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#682]
You can view a town's info by typing "/t <town name>". One of the bits of information displayed is it's coords. However, it only displays chunk coords, and not it's XYZ coords. This makes looking for locations on dynmap really difficult as you have to manually multiply the chunk coords by 16 to get the XYZ coords.

The infopane should diaplay XYZ coords by default instead of/as well as the chunk coords.

**Comment by WhitPlayzYT** [comment]
That's up to the towny devs not emc

**Comment by johnyuki** [comment]
There will be a local database that stores the information for this specific server.

**Comment by johnyuki** [comment]
Well it is forked, so EMC's version of the source sode is editable. I will post it on the main Towny page too though.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by Ukai-Oita** [comment]
This sounds like something deeply embedded into Towny itself. If this is able to be changed, I agree with you.
