### ISSUE TITLE
[BUG] sg 1 error

### ISSUE THREAD

**Issue by LulleB** [EarthMC/Issue-Tracker#684]
**Server**
sg lobby

**Describe the bug**
in sg 1 all players have died but no one can join since the game won't finish

**To Reproduce**
1. Go to 'the sg lobby join signs'
2. See error

**Expected behavior**
The empty game whould finish

**Additional context**
you can't either join by doing /sg join 1

**Comment by Warriorrrr** [comment]
As far as I'm aware, sg 1 has been broken for a long time, and fixing this is probably not a priority for Karl or whoever works on it, compared to other things.

**Comment by DasCodes** [comment]
Yeah, the plugin breaks often, one of us will have to get on and reset the arenas, we are looking for a fix for this. I had fixed the arenas earlier.
