### ISSUE TITLE
You can only open chests of sign shops you own

### ISSUE THREAD

**Issue by Ratm-n** [EarthMC/Issue-Tracker#685]
**Server**
Happens on towny only as far as I know.

**Describe the bug**
Me and my friends own a sign shop that we all stock together and now we can't open the chests linked to it, only my friend who owns the sign shops can open the chests.

**To Reproduce**
1. Try opening a chest linked to a sign shop you don't own.

**Comment by johnyuki** [comment]
I like it this way. It means that the town's owner can't come in and just steal your stock. This is especially useful for people like me who have large shops and open stores in multiple nations. If you want your friends to be able to deposit stock then you can attach an item hopper to the top of it so that they can just drop things in :)

**Comment by ImperialFishy** [comment]
John yukis shoppe is 🅱️ack!!!

**Comment by johnyuki** [comment]
Soon™

**Comment by Ratm-n** [comment]
> I like it this way. It means that the town's owner can't come in and just steal your stock. This is especially useful for people like me who have large shops and open stores in multiple nations. If you want your friends to be able to deposit stock then you can attach an item hopper to the top of it so that they can just drop things in :)

You can't attach hoppers, or anything to the chest. I've tried and you can't.

**Comment by johnyuki** [comment]
> You can't attach hoppers, or anything to the chest. I've tried and you can't.

That's very strange. If you're the plot owner and shop sign owner, and you still can't place a hopper going in to the chest, then I'd say that's a bug.

**Comment by FutureCW** [comment]
# Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):

# Floor 0 - Misc
* 32 Bones - < 30g >
* 128 Flint - < 30g >
* 1/5 Enderchest - < 40g/200g 

* 32 Glowstone - < 30g >
* 2 Bows - < 30g 

# Floor 1 - Mining
* 14 Diamonds - < 30g 

* 64 Iron - < 30g 

* 28 Lapis/Redstone Blocks - <30g >
* 14 Coal Blocks - < 30g >
# Floor 2 - Farming
* 128 Carrots - < 30g >
* 128 Sugarcane - < 30g >
* 128 Wheat - < 30g >
* 128 Wheat Seeds - < 30g >

# Misc Items - Msg me for these
* Dark Oak Logs -  < 30g 
per 3 stacks
* Nether Wart - < 30g 
per 3 stacks
* Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
* Iron Chainmail sets - < 40g >
* Prot4 Unb3 Dia Chestplates - < 90g 
each
* Villagers - Negotiable Price (70g per villager), no delivery.

# Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.
# Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):

# Floor 0 - Misc
* 32 Bones - < 30g >
* 128 Flint - < 30g >
* 1/5 Enderchest - < 40g/200g 

* 32 Glowstone - < 30g >
* 2 Bows - < 30g 

# Floor 1 - Mining
* 14 Diamonds - < 30g 

* 64 Iron - < 30g 

* 28 Lapis/Redstone Blocks - <30g >
* 14 Coal Blocks - < 30g >
# Floor 2 - Farming
* 128 Carrots - < 30g >
* 128 Sugarcane - < 30g >
* 128 Wheat - < 30g >
* 128 Wheat Seeds - < 30g >

# Misc Items - Msg me for these
* Dark Oak Logs -  < 30g 
per 3 stacks
* Nether Wart - < 30g 
per 3 stacks
* Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
* Iron Chainmail sets - < 40g >
* Prot4 Unb3 Dia Chestplates - < 90g 
each
* Villagers - Negotiable Price (70g per villager), no delivery.

# Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.

**Comment by shirazmatas** [comment]
> 
> # Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):
> # Floor 0 - Misc
> 
>     * 32 Bones - < 30g >
> 
>     * 128 Flint - < 30g >
> 
>     * 1/5 Enderchest - < 40g/200g
> 
>     * 32 Glowstone - < 30g >
> 
>     * 2 Bows - < 30g
> 
> 
> # Floor 1 - Mining
> 
>     * 14 Diamonds - < 30g
> 
>     * 64 Iron - < 30g
> 
>     * 28 Lapis/Redstone Blocks - <30g >
> 
>     * 14 Coal Blocks - < 30g >
> 
> 
> # Floor 2 - Farming
> 
>     * 128 Carrots - < 30g >
> 
>     * 128 Sugarcane - < 30g >
> 
>     * 128 Wheat - < 30g >
> 
>     * 128 Wheat Seeds - < 30g >
> 
> 
> # Misc Items - Msg me for these
> 
>     * Dark Oak Logs -  < 30g
>       per 3 stacks
> 
>     * Nether Wart - < 30g
>       per 3 stacks
> 
>     * Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
> 
>     * Iron Chainmail sets - < 40g >
> 
>     * Prot4 Unb3 Dia Chestplates - < 90g
>       each
> 
>     * Villagers - Negotiable Price (70g per villager), no delivery.
> 
> 
> # Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.
> # Selling at John Yuki's Shoppe ("/n spawn Micronesia", first shop on the right):
> # Floor 0 - Misc
> 
>     * 32 Bones - < 30g >
> 
>     * 128 Flint - < 30g >
> 
>     * 1/5 Enderchest - < 40g/200g
> 
>     * 32 Glowstone - < 30g >
> 
>     * 2 Bows - < 30g
> 
> 
> # Floor 1 - Mining
> 
>     * 14 Diamonds - < 30g
> 
>     * 64 Iron - < 30g
> 
>     * 28 Lapis/Redstone Blocks - <30g >
> 
>     * 14 Coal Blocks - < 30g >
> 
> 
> # Floor 2 - Farming
> 
>     * 128 Carrots - < 30g >
> 
>     * 128 Sugarcane - < 30g >
> 
>     * 128 Wheat - < 30g >
> 
>     * 128 Wheat Seeds - < 30g >
> 
> 
> # Misc Items - Msg me for these
> 
>     * Dark Oak Logs -  < 30g
>       per 3 stacks
> 
>     * Nether Wart - < 30g
>       per 3 stacks
> 
>     * Soul Sand - < 50g > per stack, or < 40g > per stack if you buy at least 4 stacks.
> 
>     * Iron Chainmail sets - < 40g >
> 
>     * Prot4 Unb3 Dia Chestplates - < 90g
>       each
> 
>     * Villagers - Negotiable Price (70g per villager), no delivery.
> 
> 
> # Also I have free untaxed 1x1 plots available in my town and free taxed (40g a day) 2x2 plots. Message me if you are looking to join a town.

Please do not use the github to advertise your in game services

**Comment by johnyuki** [comment]
> 
> 
> > # Selling at
> 
> Please do not use the github to advertise your in game services @FutureCW

This is just a meme. Back before my computer broke I used to advertise my shop on the discord server, and that is the message that I sent. People then just started memeing it.

**Comment by FutureCW** [comment]
Yeah shiraz john is right lmao

**Comment by ImperialFishy** [comment]
Imagine not knowing the meme smh

**Comment by josfire18** [comment]
Is this the same issue that prevents me from destroying signs? I'm not being told any permission red text but I can't destroy the signs at all. I'm the shop/town/and nation owner.

**Comment by Ratm-n** [comment]
> Is this the same issue that prevents me from destroying signs? I'm not being told any permission red text but I can't destroy the signs at all. I'm the shop/town/and nation owner.

Yup. I can't do the same either.

**Comment by SushiRoller** [comment]
Running communal shops in certain chunks where all residents are able to open chests, doors and such depends on this feature to keep everyone's chests protected. If you're going to fix this you should make it that only mayors can interact with residents' shop chests to be able to remove them in case they go inactive, or maybe friends that share the same chunk with each other's chests.

For hoppers, I'm not sure as I haven't tested it myself, but if you genuinely can't introduce items in someone else's protected chests with a hopper, I think it may be a good addition to be able to.

Remember that, since developers have refused to install another protection plugin for not only chests but also other kind of blocks, this is the only feature left that mayors can use if they want people to have, at least, their own protected chests in the same chunk as other residents, so I wouldn't consider this as a bug given the situation. Better be careful with what you change about this because it won't only affect shops but probably also many players sharing chunks.

**Comment by KarlOfDuty** [comment]
Should be fixed.
