### ISSUE TITLE
[Feature] Resource world server

### ISSUE THREAD

**Issue by Ukai-Oita** [EarthMC/Issue-Tracker#687]
**Problem**
Balancing player count with lag is not easy. We want to support a server with a lot of players, but when we increase the capacity, performance suffers as a result. How can we have a large number of people playing at once while retaining adequate performance?

**Factions Solution**
Factions was added to lighten the load. This is no secret. It worked to an extent, and we realized shortened queue times and a somewhat active factions world. Good job. But the thing that's lacking with factions is true *integration* into the main server. It is a separate world, with separate inventories, mcmmo stats, etc. You are playing *in parallel* with the main world, not with it. I do not suggest removing the factions world; just mentioning a shortcoming.

**Resource world solution**
What if we could have another server that is *integrated* into the main (Towny) world? When traveling to this server, you keep the same inventory, mcmmo stats, town affiliation (optional), ender chest inventory, and so on. It is much like traveling to the nether.

What specifically is the resource world? It is another world hosted on a separate server like factions. Players can go here to collect resources. It could be stylized like the moon or Mars.

This allows players to be split between the main world and the resource world. They will *want* to go to the resource world because it is *integrated* with the main world, and players can work on collecting resources/leveling their skills.

We can double player capacity overnight.

**Comment by Ukai-Oita** [comment]
Two scenarios arise:

1. **Many people use the resource world** - excellent, this will take load off the main server and allow many more people to play at once

2. **Only a few people use the resource world** - still good, this makes the resource world a completely lag-free enivronment where you can mine, gather without that horrible block lag. Plus, it will still add a bit of capacity.

**Comment by johnyuki** [comment]
A resource world would be cool, but looking at it from an economic point of view, it is horrible. It will make prices of things like Diamonds plummet even further. When I started playing back in Dec '08, Diamonds went for like 12 per g, and now I am seeing people selling them for 32 per g. Introducing a resource world with fresh cave systems and an untouched underground will make diamonds basically worthless. 

That's just diamonds too, not even mentioning emeralds that are already basically worthless, logs, sand, and other resources that people buy commonly. 

If the economy wasn't such a large part of the server I'd be completely down for this idea. 

Something that could be good though - and following the same reasoning as this post - is a pvp server where you can go to fight people 1v1, 2v2, etc, using the same gear and levels as the main server. Or perhaps a creative world where people can go to try out builds.

**Comment by ImperialFishy** [comment]
One huge problem with having a second world running in tandem with the main one is that if you leave to go to say a resource world, youll be replaced by another player in the main world. Thus people would have to leave the main world for you to join again and if you dont have priority or donor status that is a real problem. And i agree resources really arent that scarce but a lag free pvp world would be nice BUT i do think that would take away lots from the battles that happen in towns and randomly occur because of raids and so on. Thats one of the cool things about emc (rather bad and laggy) pvp

**Comment by Ukai-Oita** [comment]
@johnyuki This is easily remedied by reducing the number of ores in the resource world. Alternatively, the world could be made without caves. But I doubt the impact would be that substantial anyway ("untouched underground"? There are plenty of untouched areas in the main world). I would ultimately deem this a non-issue.

I would be against a PvP world simply because it is more interesting to do it on the main world, building arenas and such. A creative world would be an interesting solution though.

@ImperialFishy The queue is a legitimate concern. It would, however, be easy to implemented a maximum priority option (you are shot into position #1) similar to what occurs when you relog.

As it stands, I see no significant problem with the resource world idea.

**Comment by docwhomc** [comment]
Perhaps another towny world?  Maybe in 1.14 (even if it would need to have a lower player cap as a result) so that there's something to distinguish it from the main world.

**Comment by KarlOfDuty** [comment]
We will not be adding any extra dimensions right now because of the performance and storage issues that would cause.
