### ISSUE TITLE
[World] Fix the Iberian Peninsula

### ISSUE THREAD

**Issue by NSGamer** [EarthMC/Issue-Tracker#69]
The iberian peninsula hasn't any desert IRL except for a small area in Aragon, it should be changed to France terrain but with more mountains, here you got a map of how Spain should really be, the Ebro and Tajo rivers need to be added too: https://cdn.discordapp.com/attachments/477354342819561505/507597011625836551/Actual_spain.png

**Comment by shirazmatas** [comment]
Will probably be fixed when player count drops as to not cause too much lag

**Comment by NigelFarage666** [comment]
Why hasn't anyone added rivers or fixed biomes yet?

**Comment by PoppyK** [comment]
The Ebro and Tajo Rivers have been added.  I appreciate the amount of work put into this diagram you made.  The vast amount of change you want though is really not feasible with lag and player count.  Also, the custom trees might not be an exact fit on the map to each continent but we all deal with them in the best way we can.  I won't remove them for this area, or else I will get 100 more tickets asking for tree removal.  Come to Madagascar and take a look at how I have thinned out and incorporated the trees to fit more my taste.  It can really be easily done, with a little work.  

If you are still wanting a biome change in an area, please make a NEW ticket with coords and the biome it should be.  

Sorry, it has taken so long to get to this ticket.  All map editing and time-consuming.  Thanks for your patience.
