### ISSUE TITLE
[BUG] Dynamic Map not updating correctly

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#690]
**Server**
EMC towny

**Describe the bug**
Dynamic map only displays few chunks correctly. The majority are months out of date from what I have seen in my towns area.

**To Reproduce**
1. Go to an area on the server
2. Open dynamic map
3. Observe as they dont align or match with one another

**Expected behavior**
Make dynamic map accurate and update correctly.

**Screenshots**
![20190805_104124](https://user-images.githubusercontent.com/47613294/62493851-0532c180-b7ca-11e9-8a69-06a74ace15b1.jpg)

These chunks in the red circle are up to date. Everything else is several months old.

**Comment by DasCodes** [comment]
This has been fixed.
