### ISSUE TITLE
[Feature] dont automatically join all language channels

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#691]
**Is your feature request related to a problem? Please describe.**
If you log onto the server say 3 different times in one day. You will have to leave every single language channel 3 times. You will have to do /ch leave French for example, every single time you log back on.
This is a pain and a nuisance.

**Describe the solution you'd like**
The default position for players when they join should be just global and that's it. Language channels should require you to selectively join them upon logging on rather than expect you to leave every one you dont want to be part of.

**Comment by Ra2orLeaf** [comment]
I agree

**Comment by XioanAskari** [comment]
+1

super irratating

**Comment by docwhomc** [comment]
Or make settings carry over from the last time you were logged on.

**Comment by FutureLemon** [comment]
+1

**Comment by KarlOfDuty** [comment]
They should indeed be saved now.

**Comment by Aitonater** [comment]
Thank you
