### ISSUE TITLE
[Feature] Towny, New Town Rank

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#694]
**Is your feature request related to a problem? Please describe.**
There is too big a jump from the Town Rank builder to Trusted and Councillor.
Builder allows players to build and switch on any plots in a town that do not have an owner.

Trusted is the same as builder but the player has access to private plots too.

Councillor has the same perms as the Mayor with a few exceptions.

I'm frustrated because I want residents to he able to assist more in the town and its expansion but Trusted and Councilor giving unlimited access to all plots is too much of a risk.

**Describe the solution you'd like**
A rank such as Town Assistant or Assistant. That only gives players access to public plots but allows them to manage public plots and claim chunks for the town.

**Additional context**
Councillor is effectively mayor and trusted gives too much access to private plots whilst not allowing players to help manage the town and its expansion. I think another rank is needed to fill the void.

**Comment by KarlOfDuty** [comment]
You can try the settler rank for that.

**Comment by Aitonater** [comment]
@KarlOfDuty the only information I can find on the earthmc website about the settler rank is:
 "Settler - (Can create outposts -Classic)"
What perms does the settler rank have access to? what town commands can they use?
Thanks

**Comment by KarlOfDuty** [comment]
I see, that is outdated then, they have all claim permissions.

**Comment by Aitonater** [comment]
Can they also unclaim land too?
