### ISSUE TITLE
[Feature] Add an enchanted apple recipe

### ISSUE THREAD

**Issue by DoctorSnakes** [EarthMC/Issue-Tracker#697]
**Is your feature request related to a problem? Please describe.**
The recipe for the enchanted golden apple was removed in version 1.9, which makes them only obtainable in dungeons/villages etc. However, since there are no generated structures in EMC it is impossible to acquire enchanted golden apples.

I propose a new custom recipe for enchanted golden apples, something like this:
![image](https://user-images.githubusercontent.com/29209584/62729509-605cf200-ba1e-11e9-9453-441a331d436d.png)
The original recipe was an apple surrounded by 8 golden blocks, but I think that might be a bit too expensive considering how rare gold is in this server. So I instead propose the recipe be a normal golden apple surrounded by golden ingots.

And what purpose does the enchanted golden apple serve? Well, the only reason I want it is to be able to use the Mojang pattern for banners. This allows for a lot more different types of flags if we were able to use the Mojang pattern.
![image](https://pm1.narvii.com/6820/7af2404a186bfad3b0486472ea5a92f001368694v2_hq.jpg)

However, one possible problem with the enchanted golden apple might be the effect that it has on PvP in the server. This would essentially make it easier for the richer players to win in PvP against those that can not afford Enchanted Golden Apples. This could be fixed by either:
1. Removing the buffs from the apple entirely.
2. Nerfing the buffs to some degree.
3. Or this is not really an issue at all and it can have the same effects as in Vanilla.

**Comment by DoctorSnakes** [comment]
Another possibility would be to change the recipe for the Mojang pattern entirely and replace it with something else if implementing enchanted golden apples is unnecessary for whatever reasons.

**Comment by johnyuki** [comment]
I don't think richer players having an advantage with this is a bad thing. This is an economy server afterall, and in real life rich people have many many benefits over poor people, so I think it would accurately reflect real life anyway. I give this a +1.

**Comment by prokillerr** [comment]
Rape reflects real life too but we see none of that in emc lol

**Comment by CorruptedGreed** [comment]
I think this would heavily skew pvp as one /vote would turn into the equivalent of essentially temporary invincibility (since some people already use normal golden apples, this would be an insane buff)

**Comment by KarlOfDuty** [comment]
As per the message above this will not be implemented.
