### ISSUE TITLE
[Feature] Leave discord chat

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#698]
I just think there should be a way to /ch leave discord so you dont see the messages said from discord in game

**Comment by FutureCW** [comment]
I wonder what this is about

**Comment by WhitPlayzYT** [comment]
mhm

**Comment by Highlander214** [comment]
This is a good suggestion as there are times when it would be nice to not see discord

**Comment by Highlander214** [comment]
This is a good suggestion as there are times when reading discord msg's ingame is more of a nuisance than anything.

**Comment by FutureCW** [comment]
I’m pretty sure you’re the only player that gets hate through discord Highlander because you just ignore everyone

**Comment by Highlander214** [comment]
Well I should be a bow to play the server in peace, and I only ignore ppl for valid reasons.

**Comment by FutureCW** [comment]
Sure you have valid reasons, but how does 1 person having that problem mean that they should implement a whole feature that really only benefits you? Seems like a waste of time unless other people start demanding it

**Comment by Aitonater** [comment]
@FutureCW do you understand what these threads are for? To gather opinions and ascertain if more people have the same problem. I think it's clear that @Highlander214 isn't the only person who thinks this is a good idea.

I think this is a good idea because when people get muted in game and decide to protest they spam on discord and this would allow players to stop that too, to an extent.

**Comment by CorruptedGreed** [comment]
I agree as this would also help against people trying to circumnavigate /ignore and annoy other players.

+1

**Comment by FutureCW** [comment]
I haven't seen a single instance of people wanting that since I've played emc. sorry for that?

**Comment by DasCodes** [comment]
I don't think this is possible as the messages from Discord gets injected into in-game's global chat. You can leave the global chat if you don't want to see messages from Discord.

**Comment by KarlOfDuty** [comment]
The plugin used to have that feature but not anymore for some reason.
