### ISSUE TITLE
[Feature] Towny. Too many mobs message when you attempt to breed.

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#700]
**Is your feature request related to a problem? Please describe.**
Its easy to accidentally waste resources attempting to breed animals. It can also be very frustrating. This can be due to:
1. The server being too full.
2. There are too many mobs in the chunk you are trying to breed in.

**Describe the solution you'd like**
When attempting to feed, for example, a horse a golden carrot instead of consuming the carrot you receive a message in red text stating:
"There are too many mobs on this plot to breed!"
Or
"The server is at maximum capacity breeding is turned off!"
Or... a combination of the two etc...

**Comment by CorruptedGreed** [comment]
A warning would be nice if it can be feasibly coded in (_towny_).

+1

**Comment by KarlOfDuty** [comment]
This system is not used anymore.
