### ISSUE TITLE
[BUG] /f who don't work properly

### ISSUE THREAD

**Issue by zeldafan00001** [EarthMC/Issue-Tracker#701]
**Server**
Factions

**Describe the bug**
if you type /f who (Faction Name) you get an Error message (see picture)

Edit - Some factions work with /f who and some dont work

**To Reproduce**
1. Open chat 
2. Type '/f who (name)'
3. See error

**Expected behavior**
to see offline player

**Screenshots**
![error](https://user-images.githubusercontent.com/15855860/62857499-17e05580-bcf8-11e9-8e68-c5af8cab4de1.PNG)

**Comment by docwhomc** [comment]
I've been noticing this too. It's rather annoying.

Also, I used to occasionally find that `/f who` didn't give the offline member list, but it would usually work if I reran it.  Now we're getting an error message :), but it seems to be happening more frequently and rerunning the command doesn't seem to help anymore :(.

**Comment by AlphaiaCP** [comment]
Ober on top

**Comment by KarlOfDuty** [comment]
Should be fixed according to the developer.
