### ISSUE TITLE
/eat and /feed dont work

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#703]
**Server**
hub

**Describe the bug**
well its pretty self explanatory

**To Reproduce**
use /feed or /eat

**Additional context**
karl said that "The default player rank decided to roll back about a year for some reason, if anything doesn't work, report it on the issue tracker."
so I think its 1 of those

**Comment by FutureLemon** [comment]
Indeed it didn't work for me either a couple of days ago.

**Comment by KarlOfDuty** [comment]
Should be fixed.
