### ISSUE TITLE
[BUG] User with the "+" Rank don't have permissions for /ignore 

### ISSUE THREAD

**Issue by zeldafan00001** [EarthMC/Issue-Tracker#704]
**Server**
Factions (Towny?)

**Describe the bug**
if you type /ignore (Playername) then you get an Error message 

"! Insufficient permission (chatcontrol.command.ignore)."

Only "+" members get this error non "+" user can ignore other users.

**To Reproduce**
1. Get "+" Rank and Type /ignore NAME
2. Get Error message

**Expected behavior**
ignore an Player

**Comment by KarlOfDuty** [comment]
Should be fixed.
