### ISSUE TITLE
[BUG] Fell under world lost 37 lvls!

### ISSUE THREAD

**Issue by DarkEagle62** [EarthMC/Issue-Tracker#705]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DasCodes** [comment]
Which server? Also, you shouldn't lose anything if you fall into the void.

**Comment by DasCodes** [comment]
Also, this is not our support platform, please use our support Discord to open a new ticket for your refund. Invite link to our support Discord can be found in #info channel in EMC Discord.
