### ISSUE TITLE
[Feature] Re-enable Tree Feller and let us use it on 6-sided logs

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#706]
That's basically it. Custom trees would be way less of a pain to cut down if we could use treefeller on the 6 sided logs that the custom trees were made of

**Comment by ZestyPhallus** [comment]
This would be a great idea if tree feller was enabled x)

**Comment by FutureCW** [comment]
uwu that's why i also have re-enabling tree feller in it

**Comment by FutureLemon** [comment]
I agree but since some annoying people used it to lag the server (probably alts with bad intensions) maybe enable treefeller for everyone with woodcutten 250 and above?

**Comment by FutureCW** [comment]
That seems fair

**Comment by DasCodes** [comment]
Tree-feller is not gone permanently, it was disabled as it was causing a huge lag and players were abusing this. We'll not be enabling it for now, but it may return in future.
