### ISSUE TITLE
[Bug] ServerSelector

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#707]
**Server**
Which server the bug is on.
Hub world

**Describe the bug**
Losing server selector after death

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to hub
2. Die

**Expected behaviour**
I guess you should get compass every time you spawn in hub...

**Additional context**
I died in void, lost compass. Died from mobs, lost compass. So, I think any death removes the compass. Maybe allow keep-inventory in the region. 
Also, idk if maybe it is something wrong in perms and inheritance. I'm the yellow plus donor.

**Comment by KarlOfDuty** [comment]
This shouldn't be an issue anymore.
