### ISSUE TITLE
Skill Stuck / Acrobatics / in Towny

### ISSUE THREAD

**Issue by Xpers07** [EarthMC/Issue-Tracker#708]
**Towny server**

(or other I don't check)

**Acrobatics skill stuck**

- no more xp win
- no more abilities use (no rolled up / gracefull chance)

** Personnal experience on game**

3 days ago, I didn't see any rolled or gracefull, I try to fall many time (30 times) nothing more. Ask in global and all Say me it's work. Restart game same, now I fall over 300 Time and I don't win any xp and no rolled (I'm at 374 lev, that's must work), I lose many stuff because I think that's work

**Solution ?**

I don't know if you can do that but lock all my skill and unlock them After to see.

I just want m'y Acrobatics skill reback again because it's really long, and I don't win xp (so if you can add me some level like go to 374 to 400 Can be really nice XD, I play over 10h from the start of the bug)

** Add context **
I Can do a vidéo and post it on we-transfert or here I will see

**Comment by Xpers07** [comment]
Hello nothing more here, always stuck so if you must test it in game I'm ready it's from 3 weeks now and no more xp won, ....
Please Say when you will work on it

**Comment by KarlOfDuty** [comment]
Mcmmo is buggy due to us not being able to update it at this time.
