### ISSUE TITLE
[Bug] McMMO's Shake Skill Unexpected Drops

### ISSUE THREAD

**Issue by SushiRoller** [EarthMC/Issue-Tracker#709]
**Server**
Towny.

**Describe the bug**
Creepers and zombies don't drop their heads upon being shaked with a fishing rod (passive McMMO skill).

**To Reproduce**
Shake creepers or zombies with a fishing rod until they're supposed to drop their heads; instead, you'll get a skeleton skull with an NBT tag (a different one for each mob).

**Expected behavior**
When shaked, creepers drop a `creeper_head` (1% chance) and zombies drop a `zombie_head` (2% chance).

**Comment by XioanAskari** [comment]
Maybe just really bad luck?

again your talking a 1/100 and a 2/100 chance

**Comment by DeadGlamour** [comment]
He said he got a skull but its not the zombie skull

**Comment by KarlOfDuty** [comment]
Mcmmo is buggy due to us not being able to update it at this time.
