### ISSUE TITLE
[BUG] MCMMO Acrobatics

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#711]
**Server**
Towny

**Describe the bug**
The Acrobatics feature of MCMMO doesn't work whenever I take falldamage I don't roll despite having 1000+ acrobatics

**To Reproduce**
1. Go on a high pillar.
2. Jump off
4. Take a lot of falldamage

**Expected behavior**
You should roll and take less damage.

**Comment by YellowVictini** [comment]
+1
I have the same issue, acro does not proc when it should

**Comment by Xpers07** [comment]
Ok I do a tracker issue before please check #708

**Comment by KarlOfDuty** [comment]
Mcmmo is buggy as we are not able to update it at this time.
