### ISSUE TITLE
Custom Pictures in Item Frames Plugin

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#712]
I'd like to suggest a feature which I believe could be beneficial to the server and it's playerbase in so many ways.
While I have forgotten the name of the plugin specifically, the concept is rather simple.
I think It'd be nice if we had a plugin where we could upload pictures from the internet into the server and display them on item frames. From what I recall, previous servers which I played on had this plugin where you'd type a command, paste in the link of the image and then it would be translated into maps which could be placed on the server.

This could be used to display photoshopped images regarding the server, memes, advertisements for stores or just generally to have some fun. They are also much easier than having to make a custom map art by hand in the south pole.

I hope this feature is considered, I know at least I could use it. L

**Comment by DasCodes** [comment]
There's already a feature request similar to this #635. Please use that thread instead.
