### ISSUE TITLE
[Suggestion] Item packs

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#716]
People commonly buy items together, such as god armour, god tools, as well as building materials. It would be cool if we could combine these items in a crafting bench to create a "pack" that contains all of these items. You could have Armour Packs, Coral Packs, Log Packs, and quite a few more that I can't think of off the top of my head. 

This would allow people to sell these packs as a single item on a shop sign, rather than parting them out over multiple signs.

**Comment by JaVolimKatarinu** [comment]
Totally not possible. And they would need to create the whole plugin for it, and I personally don't see any way of doing it. Every item in Minecraft is having it own ID and you cant merge them to produce new ID with all of the previous IDs. 
Totally stupid suggestion and not possible to produce. 

Another thing, which is quite common is discord shops. Just make an order, talk with the shopkeeper and you will get what you are suggesting.

**Comment by DeadGlamour** [comment]
It is possible, but prob doesnt worth the time, would be simpler to just add shulker boxes and make it that once you click on them on the sign it opens it and show whats in

**Comment by creatorfromhell** [comment]
This is possible with the current sign shops by way of shulker boxes.

**Comment by johnyuki** [comment]
> 
> 
> This is possible with the current sign shops by way of shulker boxes.

Okay great, so when are shulker boxes getting introduced?

**Comment by CorruptedGreed** [comment]
I agree with creator, shulker boxes would be a nice way to create item packs. The only issue is whether or not they will 1) ever enable the End, or 2) get a custom recipe.

**Comment by KarlOfDuty** [comment]
We will not, no.
