### ISSUE TITLE
[Suggestion] Server lottery

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#717]
There is no gold sink in the game except for buying and expanding towns. A server lottery would be hugely popular, and provide a great way to get gold out of the game. 

Each ticket could cost 1g. 

You select 7 numbers between 1 and 20. 

This gives you a chance of 1/77,000 per ticket of winning. You could limit it to 100 tickets per player maximum to stop rich syndicates from buying the lottery. 

60% of the prize pool is shared among the people who match all 7 numbers, 10% is shared among people who match 6/7, and 5% shared among those who match 5/7. The rest is removed from the game - the gold sink.

**Comment by DeadGlamour** [comment]
The town expanding is a pretty big sink, and towns already have casinos so I dont see it as something that is really needed

**Comment by johnyuki** [comment]
> 
> 
> The town expanding is a pretty big sink, and towns already have casinos so I dont see it as something that is really needed

Towns having casinos mean nothing. Casinos don't remove gold from the game. 

Also, towns being a gold sink clearly isn't big enough considering the rampant inflation that has happened the last 4 months. Before my computer died and I couldn't play on the server, Diamonds sold for 1g per 16 on average. So many things are basically worthless now than they were 4 months ago, just imagine what it'll be like in another 4 months. This is a server that is primarily about economy, and a gold sink to keep inflation down is absolutely necessary.

**Comment by DeadGlamour** [comment]
Ehh I think you miss the point, the infaltion isnt in gold, infact it becomes even less cheap, its in everything else, 1g worthes so much more now than it was in the past, so while youre right inflation is real youre missing where it is, the inflation isnt in the gold, gold becomes more valuable with time, its with everything else being inflated

**Comment by johnyuki** [comment]
> 
> 
> Ehh I think you miss the point, the infaltion isnt in gold, infact it becomes even less cheap, its in everything else, 1g worthes so much more now than it was in the past, so while youre right inflation is real youre missing where it is, the inflation isnt in the gold, gold becomes more valuable with time, its with everything else being inflated

Ah that's true that's true. Still though, a lottery can solve this by allowing people to buy tickets with diamonds, emeralds, etc.

**Comment by KarlOfDuty** [comment]
As mentioned above it is normal items that are too common, not the gold.
