### ISSUE TITLE
[Suggestion] Post Notifications to Discord Consistently

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#718]
When making changes to the server(s) (i.e. Towny, Factions, and/or Classic), such as

  * when disabling hoppers,
  * enabling/disabling mob spawning altogether, and
  * changing gamerules,

please make a post notifying players of the change on the server discord.

Please also do so before and after restarts and maintenance so we know what's going on.  Even something as little as

> Shutting down Towny for maintenance; should be back up in about an hour.

would be greatly appreciated.  At least that way we know it's not a connection issue or an issue on our end.

As far as gamerules and configuration settings for the various plugins on the servers go, it would be great if (in addition to the change notifications) there was a list or table somewhere so we could check what the settings are.  Maybe a Google Sheet linked to on the site and in the discords.

**Comment by DeadGlamour** [comment]
I would love it, I think that communiction between the staff and the community has been lacking in this server and it would greatly help to deminish it

**Comment by Aitonater** [comment]
I tried to get karl to do change logs more often and keep people informed. After arguing with him for over an hour he said he would and never did. They cannot be bothered doing this sort of stuff for us they like us to find out the hard way and watch us suffer.

**Comment by Aitonater** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/466

**Comment by docwhomc** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/466#issuecomment-483786812
> Yes, we change that back and forth like every day to measure the effects.

Why not make a post saying
> We will be messing with setting X
and say
> being varied for testing
in the list of settings?  That way it doesn't need to be updated every time it is changed.  Once a value is decided on, make a post saying so and update the settings list accordingly.

**Comment by MikeOuO** [comment]
Yea I agree with the concept of notifying people when the server is changing and post notification consistently so that the players can know what happened recently. And probably add what will be done later. For example, post a notification that u guys are going to disable the hoppers, then the players can get back their hoppers so that their hoppers won't become stone.

**Comment by LavishNick** [comment]
Good idea

**Comment by CorruptedGreed** [comment]
The transparency would immensely help players avoid anything unwanted from happening to them or their items.

+1

**Comment by DasCodes** [comment]
I had asked Karl before to have a new channel dedicated to posting change-logs. I'll ask him again.

**Comment by DasCodes** [comment]
I have talked to him, updates will be posted on the announcement channel like before.

**Comment by Aitonater** [comment]
Hahahahaha he'll post elusive vague updates in the announcements like they always have and make changes that will make hundreds of tickets for mods as per usual karl
