### ISSUE TITLE
[Feature] Enable Query Commands via Discord Bots

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#719]
*I'm posting this on behalf of `@redfox_7#3626`.*

Enable the use of "query commands"---i.e. commands for status queries such as `/f who`---via discord bots.

The functionality could be added to the current EathMC, EarthMC Classic, and EarthMC Factions bots or to new bots created for this purpose.

The commands could be run by DMing the appropriate bot the command (after linking one's discord and Minecraft account so the bot knows what to do if no arguments are given for a command like `/f who`).

`@redfox_7#3626` also asked that I suggest the addition of an `!online` command to check who is on a given server.

**Comment by CorruptedGreed** [comment]
From what I've seen, EarthMC Live is working on something similar to this.

Also you can already check the online list, but checking specific people sounds interesting.

**Comment by KarlOfDuty** [comment]
We will not be opening the servers to receive commands like this.
