### ISSUE TITLE
Weird Joining Problem

### ISSUE THREAD

**Issue by gatobekittenme** [EarthMC/Issue-Tracker#72]
Okay, so my friends are trying to join right? Of course it is difficult to get in because of everyone trying to get on but while i play and when I tell my friends and my brother that someone left the game and that no one joins for a while, they cant get in and it says it is still full while other people are joining. Like 4 people left but my friends and brother still couldnt get in because it says its full, but in 2 minutes, other people can. Idk if its because too many people are joining at once or some regional thing.

**Comment by shirazmatas** [comment]
Donators and staff have join capabilities over 100 players so they are still able to join.
They also contribute to the max of 100/100 players so if there's 104 players and 4 leave donators can still join. 
Also the player count is currently set to earthmc classic + earthmc. You can either wait until the player count drops in the game, or donate @ https://townyearth.buycraft.net/category/789805:
