### ISSUE TITLE
[BUG]/["FEATURE"] Hoppers turning to stone and ejecting their contents

### ISSUE THREAD

**Issue by Zonzei** [EarthMC/Issue-Tracker#720]
**Server**
EMC Towny

**Describe the bug**
Have hopper doing hopper things, server lags and decides hopper doesn't have to do hopper things right now and turns it to stone ejecting all of it's contents to ground where they disappear after short duration unless someone is there to pick up the items.

**Expected behavior**
I get that this is "feature" that is supposed to reduce server lag but for god sake just slow down the hoppers or something instead of turning them to stone and wasting copious amounts of items just because I don't happen to be there to pick them up. 

**Screenshots**

[Things I had to clean up after being afk for few minutes to get supper.
](https://i.imgur.com/3sJuNMg.png)

[More things I had to clean up when I alt tabbed back to game while I was writing this bug report.](https://i.imgur.com/rL3rNkP.png)

**Comment by Aitonater** [comment]
It's also been well tested that furnaces cause more lag than hoppers surprisingly.

**Comment by docwhomc** [comment]
There must be some way to have the plugin that's doing this (or a similar one) freeze hoppers when lag gets to high.

**Comment by DasCodes** [comment]
This has been fixed.
