### ISSUE TITLE
[BUG] no exp being gained.

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#721]
**Server**
Towny

**Describe the bug**
I receive no exp. Not when throwing bottles at my feet, not when killing blazes. It just despawns. 

**To Reproduce**
Throw an exp bottle, kill a blaze. No exp will be gained. It will just despawn, instantly. 

**Expected behavior**
Gain exp.

**Screenshots**
No.

**Additional context**
No.

**Comment by DasCodes** [comment]
This has been fixed.
