### ISSUE TITLE
[Filter] Whenever a ban wave such as the Onearth wave happens, censor the server name

### ISSUE THREAD

**Issue by FutureCW** [EarthMC/Issue-Tracker#722]
Legit just add Onearth and Geonations and other forms of it to the filter so messages that include it don’t go through. It makes all advertisers useless

**Comment by ItzRock** [comment]
make it so if a plugin detect onearth or goenations in the queue with /msg then they get autokicked before the dm gets sent.

**Comment by FutureCW** [comment]
If it’s like saying the n word then the whole message doesn’t show up

**Comment by KarlOfDuty** [comment]
That already exists.
