### ISSUE TITLE
[Suggestion] Something needs to be done about the economy on the server

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#724]
**Is your feature request related to a problem? Please describe.**
I've been away from the server for the last 4 or so months due to my computer breaking. I come back and I see a bunch of things I dislike, but the biggest of all was that the market has completely gone down the drain. Everything is basically worthless now. People don't sell Emeralds anymore, Diamonds go for 1g per stack, you can buy full god armour after 2 or 3 days of voting, and a full set of god tools after another few days. It is absolutely insane that a server that is so reliant on economy has allowed the economy to get this bad. 

I know that a lot of you think this is great, because it is a completely free market, and players decide the prices. And you are right, that is great. However, certain goods (such as the aforementioned enchantments, diamonds, emeralds, etc), *need* to be managed so that the economy doesn't keep inflating. I see places like Romania that basically give their top-tier enchanted books away for free (they charge 64 emeralds, basically what you pay from the villager), and it is things like this that have to be ended for the sake of the economy's health.

I am going to draw on a lot of examples from Runescape. Meme the game all you like, but it is one of the best examples in the gaming industry of an economy that is well-managed. Runescape's economy is run on gold coins, and everything you buy from shops or the grand exchange (basically the game's version of ebay) is bought with gold. The only time bartering comes in to play is when you are trading directly with a player, where you might swap a weapon for a piece of armour or something, but this is rare. Whenever you buy something from a shop, that gold is removed from the game, and whenever you buy something from the grand exchange, a 5% tax is taken (I think it is 5% anyway) and is removed from the game. There are also many other smaller gold sinks in the game, but these two things are the primary thing that Runescape uses to manage it's economy. 

Another major thing that Runescape uses to balance out prices of commonly traded items, is by a thing called "high-alch value". This refers to a spell that you can cast on an item, where you receive coins. So I might cast the spell on a weapon and receive 15,000 coins in return. Now because of this, the value of this item on the grand exchange will NEVER go below 15,000 coins, because if it does then people will start buying the item on the GE in order to cast high alchemy on it and get a small profit, which in turn brings the price of the item back up again. This effectively puts a lower limit on the amount of gold that items can sell for, to stop certain items from plummeting so far that they become worthless. Also, when you cast High Alch on an item, the item is removed from the game, which further helps to keep the value of items from plummeting. 

**Describe the solution you'd like**
Considering the above, I propose the following solutions to help manage the economy: 
- **You can only buy things from shops with gold.** No more selling items in exchange for diamonds or emeralds or some other thing. If Gold is going to be the currency then it needs to be enforced. People can still barter for things in trade chat if they want to swap some diamonds for emeralds or something. 
- **Introduce an admin store**, that will buy and sell items from players at a set limit. For example the admin store might sell Diamonds for 12 per g and buy them for 48 per g, sell Emeralds for 16 per g and buy them for 82 per g, and some of the more common enchantments like Mending, Sharpness 5, Silk Touch, Fortune 3, etc, might buy for 1g and sell for 4g. What this does is stops shops from practically giving away items just to fuck with people's profits and forces them to stay within those limits. So if a shop is trying to sell Diamonds at 64 per g, then people will just say "nah forget that, I'll just go to the admin shop". It gives people the freedom to compete with each other, but the admin shop is there to stop that competition from crashing the economy. More things can be added to the store as and when it is necessary to do so. This also acts as a great item sink, because items sold to the admin store are removed from the game rather than perpetually being in circulation adding to the inflation.
- **Introduce a lottery.** I already made this in a suggestion of it's own, but seeing as I am making a large thread here for the economy, I will add it in here too. A lottery could be run once a week that allows people to select 7 numbers between 1 and 20. This gives them a 1 in 77,000 chance of winning per ticket. Tickets can be bought with gold, emeralds, and diamonds. 60% of the pot is shared among people who match all 7 numbers, 10% is shared among people who match 6 numbers, and 5% is shared among those who match 5 numbers. The remaining 25% is removed from the game. This can act as a sink for the commonly traded items to remove them from the game and stop the prices of those rising too much. 

I will add more economy-balancing methods in as I think of them, but I really feel that some kind of management has to be done to help the economy to balance out.

**Comment by Ukai-Oita** [comment]
I love RuneScape's economy and studied it in the past.

That being said, admin shops are a terrible idea. Player economy or nothing. And players should be able to decide what they buy and sell at their stores. Free economy, free choice, please.

**Comment by johnyuki** [comment]
> 
> 
> I love RuneScape's economy and studied it in the past.
> 
> That being said, admin shops are a terrible idea. Player economy or nothing. And players should be able to decide what they buy and sell at their stores. Free economy, free choice, please.

There is no such thing as a working free economy, because they simply collapse, just like EMC's one is doing. Enchanted books are currently worth nothing, diamonds are slipping towards the same fate. People have got creative with trying to make money by doing Casinos and map art and whatnot, but with more and more diamonds, emeralds, and every other item coming in to the game, they are becoming more and more worthless. 

I'm not saying to remove free trade, but something very evidently needs to be done to nurse the economy back to health, because sooner or later it will be basically impossible to make money. Can you imagine how absolutely shit Runescape would be if they left their economy completely down to the players? A lot of items are already down to their high-alch cap, if the cap would removed their value would plummet. I'm saying that we need the same thing in EMC, and an admin shop of the most commonly sold items is the way to do that.

**Comment by Aitonater** [comment]
I dont think the prices are that bad I dont think a week is too short a period of time for people to have diamond armour and good tools. I've never seen a stack of diamonds go for 1 gold. 
The prices I'm familiar with are:
- 80 to 110g for a Beacon
-  9 Gold for a God pick etc
- 1 gold for 32 diamonds
-  1 gold for 64 emeralds
- 20 gold for a blaze spawner
-  8 to 15 gold for a villager
- animals 10 or less gold 
- horses again 10 or more depends

I really dont see that much of a problem with the pricing. People can get God sets fairly easily which imo just makes pvp more accessible. But for big things like beacons and towns and nations there is still a big effort that goes into getting them.

I dont see how they can control the inflation unless they change the currency or disable voting gold. Certain things like towns and spawners will always be valuable.

**Comment by johnyuki** [comment]
> 
> 
> I dont think the prices are that bad I dont think a week is too short a period of time for people to have diamond armour and good tools. I've never seen a stack of diamonds go for 1 gold.
> The prices I'm familiar with are:
> 
>     * 80 to 110g for a Beacon
> 
>     * 9 Gold for a God pick etc
> 
>     * 1 gold for 32 diamonds
> 
>     * 1 gold for 64 emeralds
> 
>     * 20 gold for a blaze spawner
> 
>     * 8 to 15 gold for a villager
> 
>     * animals 10 or less gold
> 
>     * horses again 10 or more depends
> 
> 
> I really dont see that much of a problem with the pricing. People can get God sets fairly easily which imo just makes pvp more accessible. But for big things like beacons and towns and nations there is still a big effort that goes into getting them.
> 
> I dont see how they can control the inflation unless they change the currency or disable voting gold. Certain things like towns and spawners will always be valuable.

That's a week for a god set and god items *just off of voting gold*. You could easily get max full gear in a day or two if you spent a few hours mining. Towny isn't really about the pvp aspect of it, hence why factions was created, and good luck getting a good fight going on towny with the insane amounts of lag on the server. 

*"I dont see how they can control the inflation"* - this is literally what this thread is about. I outlined three ways that they can control the inflation of items in the game. Currently the only items going out of the game is gold and emeralds, which is fine, but other commonly traded items like diamonds need to also be filtered out of the game to balance everything out. Items rise in price when there are more of them coming in to the game than there are going out.

**Comment by JaVolimKatarinu** [comment]
Getting the admin shop isn't going to fix stuff. Leaving player shops only way of trade isn't going to fix the economy, it is going to worse it. And pretty much from my perspective is that economy cant be fixed, ever. Not on EMC, not in real life. 
For a really long time, even before I came, the exchange rate of Emeralds and gold was 64E for 1G. With new players coming, they started even to lower that. Nothing is sacred to them, except the gold. Current players of EMC are pretty much new players that came from recent youtubers. And they don't read this, they don't read anything. So, this issue is kinda pointless. Removing player shops from EMC and setting up the admin shop won't fix the problem, because people will start creating discord shops and keep their shops on hand to hand trades. Admin shop would just be a place in the world where people will afk. 
We need some creative ideas, something to force the prices. Still allow player shops, but without the permission for own prices, but prices forced by the server. My idea is to create new value. Gold is becoming worthless and we need new item to have an economy based on it. Something like Chorus which wouldnt be able to grow and only be obtainable through votes and trades. 
I believe that is one of the reasons why Staff won't open End Gates, so they can still reserve End items for things like this. Economy failure is always foreseeable. Once it starts to go down, it is only a matter of time. 

This all is a matter that should be Staffs decision. They should ask us what would we like, but the final word and the word that matters should be theirs.

**Comment by johnyuki** [comment]
> Removing player shops from EMC and setting up the admin shop won't fix the problem

I never said to remove them. I said that having an admin shop that sets basline prices would mean that shop owners can't just crash the value of items. 

Also, removing the ability to set your own prices defeats the point of having any player owned shops at all. Runescape's economy has been incredibly solid since release almost 2 decades ago, and this is partly due to the high-alch value that stops items market value from decreasing past a certain point. An admin shop mimicks the high-alch value that Runescape has and also removes items from the game, which is something that is sorely needed to control the flow of items that is coming in to the game.

**Comment by docwhomc** [comment]
It sounds like some of the issues described here could be the result of deflation.

**Comment by FutureCW** [comment]
The admin shop sounds useless but restricting shops to only gold for buying items is a good idea. Letting players sell enchanted books for emeralds instead of gold devalues literally everyone else trying to make a profit because a single person decided to fuck the economy on enchanted books

**Comment by docwhomc** [comment]
Mimicking high-alch to get rid of a flow of items into the game could cause massive inflation by turning an overabundance of an item into an overabundance of gold.

**Comment by docwhomc** [comment]
@FutureCW How is out pricing one's competitors "fuck[ing] the economy"?

**Comment by johnyuki** [comment]
> 
> 
> @FutureCW How is out pricing one's competitors "fuck[ing] the economy"?

Because it is unnecessarily dropping the value of items to the point where the profit is miniscule. A villager might sell a top tier enchanted book for 1 book and 45 emeralds. If someone then sells the enchanted book for 64 emeralds, they get almost no profit. No one else has any chance of competing with that unless they too sell it at this price and make next to no profit. 

So all because one guy is happy to barely break even, it screws over the entire market for those items.

**Comment by docwhomc** [comment]
Unnecessarily?

**Comment by docwhomc** [comment]
One thing that's bothering me about this discussion is that one of the major complaints is a general decline in the value of goods (deflation) while the other is inflation (the opposite of deflation).  A currency can undergo one or the other, but not both.  So which one is it that is currently the problem on the server?

I'm not saying that we shouldn't discuss both, because a measure to avoid one can overcompensate and cause the other, I'm just saying that there seems to be some controversy or confusion as to which one is currently effecting the server.

**Comment by docwhomc** [comment]
Getting back to the argument about the value of items...  if the seller is able to maximize his overall profit by selling cheaper (decreasing the profit made per item) but in greater quantities (due to the lower price), than that is what the seller will do.

He is neither "fuck[ing] up the economy" or "barely break[ing] even" by doing so.

**Comment by johnyuki** [comment]
> 
> 
> One thing that's bothering me about this discussion is that one of the major complaints is a general decline in the value of goods (deflation) while the other is inflation (the opposite of deflation). A currency can undergo one or the other, but not both. So which one is it that is currently the problem on the server?
> 
> I'm not saying that we shouldn't discuss both, because a measure to avoid one can overcompensate and cause the other, I'm just saying that there seems to be some controversy or confusion as to which one is currently effecting the server.

You're my bad, I do mean deflation. 

As for the potential inflation of gold by stopping the deflation of goods, then that is something that can be fixed by having more gold sinks and taxes. There is very little care towards the economy atm and it just needs to change. Whether that is by implemented my suggestions, or doing something else, but either way something needs to be done about it. 

>if the seller is able to maximize his overall profit by selling cheaper (decreasing the profit made per item) but in greater quantities (due to the lower price), than that is what the seller will do.

That isn't what is happening. People sell a single enchanted book for 64 emeralds - which considering villagers sell the enchanted books for like 40 emeralds, is in fact just about breaking even when you factor in the cost of the book you need to give the villager as well. Books are basically at the absolute lowest value they can possibly be now. Any lower and the seller will be making a loss. When items reach their lowest possible price before not being able to make any profit, then I would say that is quite unhealthy. Because of this, people can get a set of god armour for about 15g, so straight off their first day after voting and doing a 30 minute session of mining, they have end-game gear. I know the pvp purists out there would get a boner over that, but it just simply isn't healthy for the server when you can join and immediately get the best shit within an hour.

**Comment by FutureLemon** [comment]
> The admin shop sounds useless but restricting shops to only gold for buying items is a good idea. Letting players sell enchanted books for emeralds instead of gold devalues literally everyone else trying to make a profit because a single person decided to fuck the economy on enchanted books

The server never recovered from Romania's emerald shop and now all books go for junk prices.

**Comment by DeadGlamour** [comment]
just kill all villagers, lets see how cheap books will be then

**Comment by FutureCW** [comment]
Exactly FutureLemon, selling books for emeralds just ranks the economy on it

**Comment by docwhomc** [comment]
How did an emerald shop more or less permanently thank the price of books?

**Comment by johnyuki** [comment]
It's not an Emerald shop. It's a book shop where you buy them with Emeralds instead of gold. 64 Emeralds for a book = basically no profit made. Books are basically worth what the villagers sell them for now.

**Comment by FixTheAdmin** [comment]
Thank you for the well written post. I personally do not like the idea of admin shops. I actually believe we need to make gold less valuable, towny prices are too much of a gold sink making everything else sold worthless. I dislike the fact that new players are able to get all end-game items from two days worth of voting gold.

**Comment by Cactusinapumpkin** [comment]
I pay 10g for a stack of blocks 
pick for 9 g = 9 stacks of emeralds= 10gold

sometimes using villagers requires you to spend emeralds to unlock their trades again and that can be factored in the price of books

**Comment by Shootcity** [comment]
I think something needs to be done, however this economy has forced players to go another direction. Money for services. No longer is it just a goods based system , people are paying for labour and entertainment. I think we are closer to having a better economy just gotta ride through the tough spell of minimal profit.

**Comment by KarlOfDuty** [comment]
We will probably not influence the economy in ways other than changing how much server stuff like towns and nations cost.
