### ISSUE TITLE
[BUG] Transporting a villager on boat then fell into void because of lag

### ISSUE THREAD

**Issue by Hsiao123** [EarthMC/Issue-Tracker#725]
**Server**
Towny server

**Describe the bug**
I bought a villager off Rockiesguy 100 in Midas, Madagascar. I was on my way back to South America with the villager in my boat when the server lagged me into the void with the boat and I died. I havent found the villager and I think it's safe to say he fell in the void as well. 

**Screenshots**
I dont have screenshots but you can check that I did pay 10 gold to Rockiesguy100 and that I fell into the void shortly after

**Comment by Hsiao123** [comment]
My username is Hsiao btw

**Comment by johnyuki** [comment]
This isn't what Iyonc said when he said "make a ticket". There is a support discord server listed in #info. Post your issue there.

**Comment by Hsiao123** [comment]
> This isn't what Iyonc said when he said "make a ticket". There is a support discord server listed in #info. Post your issue there.

Oops sorry on the support discord it said bug issues should go here

**Comment by Aitonater** [comment]
The server staff dont refund things lost to the void or lag. Otherwise I could say I lost 20 horses in diamond armour and there would be no way of them knowing if I was lying.

**Comment by docwhomc** [comment]
@Hsiao123 please close this

**Comment by DasCodes** [comment]
This is not our support platform, please use our support Discord to open a new ticket. Invite link to our support Discord can be found in #info channel in EMC Discord.
