### ISSUE TITLE
[BUG] / [''FEATURE''] Spawners turning into air

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#727]
**Server**
Towny, Unclear if the same happens on factions.

**Describe the bug**
Spawners are slowly disappearing, same with the issue with hoppers turning to stone. This is very annoying, because spawners are worth a lot more than hoppers and harder to get.

**To Reproduce**
1. Place a spawner, it will work normally
2. After some time the spawner disappears, not leaving anything like stone in its place

**Expected behavior**
The spawner doesn't disappear.

**Screenshots**
![2019-08-22_15 39 13](https://user-images.githubusercontent.com/50800980/63521927-abcfcf80-c4f7-11e9-8b93-34f556cd9f1f.png)
There used to be loads of spawners here, but all excluding two have disappeared.

**Additional context**
If anyone else has this happen, please put a screenshot of it below.

**Comment by DeadGlamour** [comment]
https://cdn.discordapp.com/attachments/556621667363848192/614095270178717716/2019-08-22_16.54.59.png

**Comment by Darkovid1** [comment]
![image](https://user-images.githubusercontent.com/54416216/63541864-4099f380-c51f-11e9-9658-ab499797681c.png)
Here is what's left of my 64 spawners

**Comment by L4certa** [comment]
My spawners are disappearing now, is staff going to do something? I really can't afford more spawners.   Town is Montezuma
![Spawners Disappearing](https://user-images.githubusercontent.com/45343589/63547723-99e33200-c4e1-11e9-93c5-1f1ccf8a2802.png)

**Comment by Scorpionzzx** [comment]
I have had the same problem lost 4 spawners that I bough for 80ish gold however I don't have a screen because I have removed them before more can despawn.

**Comment by L4certa** [comment]
Ok this is getting ridiculous now, another spawner has disappeared just poof right before my eyes. Its not safe to keep your spawners up now?   I cant afford to replace these.
![Spawners keep going](https://user-images.githubusercontent.com/45343589/63550108-cfd6e500-c4e6-11e9-9742-fe929008c075.png)

**Comment by theEXPERTpt** [comment]
mines also despawned
![2019-08-22_16 57 58](https://user-images.githubusercontent.com/52140324/63551535-544c5680-c52d-11e9-8315-57d93dc329a2.png)

**Comment by Pengun78** [comment]
Bruh ikr i used to have 32 spawners now i have 10 left and my spawner is shit

**Comment by docwhomc** [comment]
I'm guessing this is related to https://github.com/EarthMC/Issue-Tracker/issues/720, by which I mean that I'm guessing the anti-lag plugin is responsible.

**Comment by Warriorrrr** [comment]
![2019-08-23 23_32_38-Badlion Client 2019 08 23 - 23 31 57 02 DVR mp4 - VLC Media Player](https://user-images.githubusercontent.com/50800980/63625147-01db6a80-c5ff-11e9-8b75-3bb439f8f4d1.png)
Finally we did it gamers. Issue closed.
