### ISSUE TITLE
i got stuck in a nether portal

### ISSUE THREAD

**Issue by sammybam88** [EarthMC/Issue-Tracker#728]
can you teleport me somehow please I wanna play earthmc but I'm stuck in a portal trap in a forest

**Comment by Warriorrrr** [comment]
You can either open a ticket on the [support discord](https://discord.gg/zQsaMx) or use discord chat to ask a mod to get you out, because this isn't the correct spot to post this

**Comment by DasCodes** [comment]
This is not our support platform, please use our support Discord to open a new ticket. Invite link to our support Discord can be found in #info channel in EMC Discord.
