### ISSUE TITLE
The Biomes around the Bahamas should be changed.

### ISSUE THREAD

**Issue by SafariArii** [EarthMC/Issue-Tracker#73]
The biomes around the Bahamas should be changed to increase the appeal of the area and make it more realistic. The Bahamas in real life are known for the very clear blue water and the pristine beaches that make the resorts great. However, on TerraNova the beaches are not actually beach biomes, and the water around it is just plain. The water around the Bahamas should be a warm ocean biome, and the beaches need to be beach biomes. The warm ocean color actually looks like it was probably modeled after the caribbean oceans anyway, so it makes sense for that whole area to be warm ocean.

**Comment by SafariArii** [comment]
All the plateau areas should be warm oceans in that area, like the areas that u can see on the dynmap underwater

**Comment by KarlOfDuty** [comment]
Duplicate #64
