### ISSUE TITLE
Hoppers and Spawners disappearing/turning into stones

### ISSUE THREAD

**Issue by UniBraDa** [EarthMC/Issue-Tracker#730]
**Server**
EarthMC

**Describe the bug**
My blaze spanners are disappearing and some of my hoppers turned into stones. And my items happens to be de-spawned. Basically I lost my spawners and also my blaze eggs.

**To Reproduce**

**Expected behavior**
Giving me back my items or maybe at least Give me back my gold. 

**Screenshots**

**Additional context**

**Comment by DasCodes** [comment]
This has been fixed.

**Comment by DasCodes** [comment]
This is not our support platform, please use our support Discord to open a new ticket for your refund. Invite link to our support Discord can be found in #info channel in EMC Discord.
