### ISSUE TITLE
[Suggestion] Bring back the old chat commands

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#731]
**Is your feature request related to a problem? Please describe.**
After my long break, I come back to find that speaking in different channels is now really annoying. You have to do "/ch j channelname", type your message, then change back to global. 

**Describe the solution you'd like**
Previously you used to just be able to type "/trade msg" and it would get sent to trade chat, or "/nc msg" and it would get sent to your nation chat. It was much simpler, and didn't require people to constantly manually change channels and back every time they wanted to send a single message.

**Comment by Aitonater** [comment]
I agree they should just revert all the changes they made to chat. I hate not being able to see everyone's towns now in nation chat. And the fact it's the same colour as players logging in makes it harder to read.

**Comment by johnyuki** [comment]
Yep, it is objectively worse. Did they ever give a reason to why they changed it?

**Comment by FutureCW** [comment]
Yeah you can’t do /n set tag or /t set tag anymore as it won’t show up in chat. I hate it

**Comment by DasCodes** [comment]
The old chat was buggy and had permission issue, hence we had switched to his chat plugin.
