### ISSUE TITLE
[BUG] Spawners dissapeared

### ISSUE THREAD

**Issue by Rep2g** [EarthMC/Issue-Tracker#732]
**Server**
Towny

**Describe the bug**
My spawners are gone and Fix said to ask for them back. I had 14 blaze spawners and now i have only 2. Thanks
IGN: Reptiluracs
Town: Sahalinsk

**Comment by DasCodes** [comment]
This is not our support platform, please use our support Discord to open a new ticket for your refund. Invite link to our support Discord can be found in #info channel in EMC Discord.
