### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by volleyball4ever1** [EarthMC/Issue-Tracker#735]
Hello. i got banned from the server like 18 days ago i think. I got banned for getting 5 warnings, I know i did many bad things but when i had 4 warnings and it said last warn before perm ban i said to my self that i will never get another warn shirazmates helped me to stop using afk machine you can ask him i am sure he will tell you that i stoped and i stopped griefing because i knew i will get perm ban for that i got my number 5 warning for spaming someone msg i was very mad and i didn't knew i can get ban for this reason i spamed his chat because he scammed me for 50G and i was very angry.

Now i can promise i will read all the server rules and i will not break any rule any more so please give me a real last chance i spend many time on this server and i don't want to lose everything
please unban me  volleyball4ever1

**Comment by Pengun78** [comment]
Rest in peace volleyball4ever1 bruh😔😔

**Comment by DasCodes** [comment]
This is not a platform for support or ban appeal. Please appeal on our support Discord, if you haven't already.
