### ISSUE TITLE
[Feature] Smooth Stone And Smooth Quartz

### ISSUE THREAD

**Issue by SushiRoller** [EarthMC/Issue-Tracker#736]
Smooth stone and smooth quartz are some of the several blocks added in 1.13 that, like smooth sandstone and smooth red sandstone, were unobtainable in vanilla during said version. Since 1.14 is _most likely_ not going to come by during the following months, I suggest to add a temporary custom recipe for both blocks:

![Smooth Stone](https://i.imgur.com/xhQ8Ncc.png)
Description: melt a stone block in a furnace to obtain a smooth stone block.

![Smooth Quartz](https://i.imgur.com/i2eu5wl.png)
Description: melt a quartz block in a furnace to obtain a smooth quartz block.

As a side comment, to note that smooth quartz texture in 1.13.2 is the same as quartz block in all sides except the bottom one, which uses the same texture as the other sides, while quartz block has got a smooth texture on the bottom side. 

The reason behind this is that these blocks were presumably added as an alternative to double slab blocks, but the difference is almost unnoticeable with quartz. I'm just adding smooth quartz in this suggestion for the sake of completion.

**Comment by JaVolimKatarinu** [comment]
That smooth stone custom recipe is an actual recipe for smooth stone...

**Comment by Cactusinapumpkin** [comment]
I particularly like these two blocks especially smooth quartz
