### ISSUE TITLE
Sign Shops are broken

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#737]
**Server:** Towny

**Describe the bug:** My Sign shop doesn't work. It says I don't have enough items in stock, even though I do. I set it up correctly, did every step that's listed in the guide on faq.

**Steps to reproduce the behavior:**
Clicking on the signs that offer the items. It will say not enough items in the chest.

**Expected behavior**
Exchanging gold for items in chest.

**Additional context**
I tested it with leather, clay and brick blocks. All those items can be succesfully purchased in other shops.

I have a few other sign shops in the chunk next to those that won't work that sell all kinds of corals. But these ones **do** work.

**Comment by johnyuki** [comment]
What item are you trying to sell?

**Comment by Lagann311** [comment]
Leather, clay and brick blocks

**Comment by johnyuki** [comment]
What are the exact steps you did

**Comment by Lagann311** [comment]
1. place sign
2. write [item]
3. right click with leather
4. select amount (11)
5. confirm amount
6. left click and select paper with „gold“ written
7. Add gold (1)
8. Confirm Transaction
9. click shop sign
10. click chest (coors of the chest were shown in chat)

**Comment by Lagann311** [comment]
Any news?

**Comment by KarlOfDuty** [comment]
Could you try reversing the selling/buying? Could you try it with both a currency sign and with a trade sign?

**Comment by Lagann311** [comment]
@KarlOfDuty
reptiluracs and me just tested it but it still doesn‘t work.

**Comment by Lagann311** [comment]
Sorry to bother again but did you find a way to fix this bug? I really need those sign shops.

**Comment by Lagann311** [comment]
Sorry for the inconvenience, I found the mistake I made..
I have named items placed in item frames so it shows the text when looking it and I always used these ones for setting up the signs. Well it only works with unnamed items.
Sorry for the inconvenience I caused, topic can be closed.
