### ISSUE TITLE
[BUG] (MCMMO) Acrobatics disabled or not working on Factions and Towny

### ISSUE THREAD

**Issue by vVertex** [EarthMC/Issue-Tracker#739]
**Server**
Which server the bug is on.
EarthMC Factions, EarthMC Towny

**Describe the bug**
The rolling, and graceful rolling function of the MCMMO acrobatics skill is not working correctly. When you jump from a high place, even if you have 100% roll chance you do not end up rolling.

**To Reproduce**
1. Join factions / towny
2. Jump from a high place
3. See if you roll

**Expected behavior**
Expected to roll and negate, or completely remove fall damage.

**Comment by Xpers07** [comment]
Hello Man, I have the same bug on towny from 3 weeks now, nothing more I wait and no more xp, no more rolled up, I Lost many Time my stuff (one god Armor and pick un nether when I fell the first Time).
This is my tracker issue and no more comment #708

**Comment by vVertex** [comment]
> Hello Man, I have the same bug on towny from 3 weeks now, nothing more I wait and no more xp, no more rolled up, I Lost many Time my stuff (one god Armor and pick un nether when I fell the first Time).
> This is my tracker issue and no more comment #708

Ah so acrobatics doesn't work on any of the servers... although I see that the dodge ability still works so I'm not sure how rolling/graceful rolling is disabled.

**Comment by Xpers07** [comment]
How many Time Acrobatics skill doesn't work ? Something same of me ? Or no

**Comment by Silverrlol** [comment]
Can this please get fixed lmao

**Comment by KarlOfDuty** [comment]
There are a lot of mcmmo issues and it is unlikely that they will be fixed soon as newer versions are not compatible with some of our other plugins.
