### ISSUE TITLE
Slow fall potions and why they should be disabled. (ISSUE)

### ISSUE THREAD

**Issue by CasperFactions** [EarthMC/Issue-Tracker#741]
Description
Slow fall potions are really easy to make, because some factions have a nametagged phantom that wont despawn, which they keep shaking (mcmmo fishing) and getting phantom membranes all the time. They make players fall way slower and combining it with jump boost potions it makes a perfect mix for raids. 2 Perfectly designed bases that are really hard to raid have been destroyed with a wither thanks to slow fall potions, making bases completely pointless. You can place some chests in the open, put water on them and call it a day

Solution
The only solution to this issue is disabling the slow fall potions to make actually planning and building a good base worth it. Good bases can get easily raided with slow fall potions and a wither which makes it unfair and pointless to build bases.

**Comment by docwhomc** [comment]
Are you sure it wasn't ggovi using fly hacks?

**Comment by hydrolien** [comment]
😭 29 aug and nothing have change.
