### ISSUE TITLE
[Feature] Sending a message to the town mayor after residents got kicked because of inactivity.

### ISSUE THREAD

**Issue by MikeOuO** [EarthMC/Issue-Tracker#742]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when a resident got kicked from town because of the inactivity of 42 days. And their plot will be for sale for 0g, and causing residents claiming the plot by paying nothing. 

**Describe the solution you'd like**
I suggest sending a message like "The resident [ign] got kicked from town because of inactivity for 42 days.". With that message, I can go to their plot and set their plot for sale for a specific amount, without walking around the town to see which plot is for sale for 0g.

Or another solution to this is that to set up a command for adjusting the default price of a plot. For example, /t plotdefaultprice fs [amount], meaning that the plot will be set to that price after the resident owning it is kicked.

**Comment by ImperialFishy** [comment]
You realize that its already possible to set the default plot price. Go read the towny command guide again

**Comment by MikeOuO** [comment]
... really?

**Comment by MikeOuO** [comment]
lol
