### ISSUE TITLE
[Bug] Respawn point- bed

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#743]
**Server**
Towny

**Describe the bug**
Not able to set up my respawn point.

**To Reproduce**
Steps to reproduce the behaviour:
1. Destroy your bed
2. Die

**Additional context**
Like a week ago, I placed my bed and laid in it and my respawn point was set up successfully. I was able to use /res spawn to tp back home. 2 days ago, I did some redecorating in my house and destroyed the bed. After redecor was done, I put my bed down, lay in it and tried /res spawn but I got tped to my town spawn point. I tried several times to set up the respawn point, destroying bed and placing it again, but not successful. 
Idk if I'm the only person affected by this, but as far as I know, no one else is having this issue.

**Comment by JaVolimKatarinu** [comment]
Bump
Any news?

**Comment by Aitonater** [comment]
Placing the bed is not enough you also need to sleep in it too. Just incase you weren't sleeping in it every subsequent time.

**Comment by Cactusinapumpkin** [comment]
Have you tried the Chimaera Wing?

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/64196406-6ee5d000-ce49-11e9-9d14-54f84f46bba3.png)

**Comment by JaVolimKatarinu** [comment]
Didnt know about that.  :O

**Comment by WhitPlayzYT** [comment]
I've tried it before and it doesnt work on emc

**Comment by Cactusinapumpkin** [comment]
Ive tryed it too it does work

**Comment by Cactusinapumpkin** [comment]
nvm 
![image](https://user-images.githubusercontent.com/48000340/64226788-67a0df80-cea6-11e9-9de3-06333bdea092.png)

they changed the perms for it.
To be able to use a Chimaera Wing, players will need to have the permission node mcmmo.item.chimaerawing.

**Comment by JaVolimKatarinu** [comment]
Fucking slabs. Mine respawn point wasn't working because of the fact that it should spawn me on the slab, but couldn't do it. 
I will open an issue in Towny repo, to maybe get a fix on this. 
Everything is okay now. ;)
