### ISSUE TITLE
Remove/Increase Playercap on towns

### ISSUE THREAD

**Issue by MineHero43** [EarthMC/Issue-Tracker#745]
Quite frankly I don't really see the point of the 75 playercap on towns. While I do appreciate that it has been raised from 50, I do think it should be raised more or removed like it was on classic.

It limits how big nations can grow on /n list and the size which a town can grow to. It's honestly annoying to have to keep going around and kicking "inactive" players from the town simply to allow new people to join who are sometimes deterred from the server when a town they want to join with /t join is full. Sometimes "inactive" players log back on after a few weeks and wonder why their plots have been given to someone else. It also eliminates simple but fun competition for /t list.

One town has already reached the maximum claim limit and more will soon follow.

I think the cap should be either increased to 100 and possibly even more, or completely be removed like it was on classic

**Comment by Pengun78** [comment]
Minehero do be spittin fax doe

**Comment by Pengun78** [comment]
Perpignan gang had 120 ppl

**Comment by BowShot118** [comment]
![brityet](https://user-images.githubusercontent.com/44571571/64062955-a81e0600-cbe5-11e9-8cfe-cdbf98461940.jpg)

**Comment by MineHero43** [comment]
Bump .__.

**Comment by MineHero43** [comment]
W h e n

**Comment by KarlOfDuty** [comment]
Apparently Fix increased them some time ago.
