### ISSUE TITLE
[BUG] Cant use /plots command correctly

### ISSUE THREAD

**Issue by RauchenDym** [EarthMC/Issue-Tracker#748]
**Server**
EarthMC

**Describe the bug**
When any command included in /plots is used this shows up
<img width="553" alt="Screen Shot 2019-09-03 at 11 32 03 AM" src="https://user-images.githubusercontent.com/54855043/64187565-d9454300-ce3e-11e9-966a-857d05e3fe7b.png">

**To Reproduce**
1. Type the command /t plots 
2. See error

**Expected behavior**
The plot goes up for sale when using the command /t plots fs

**Comment by JaVolimKatarinu** [comment]
Command to work with plots is /plot not /t plots...

**Comment by FutureCW** [comment]
Lol that’s because the command is /plot

**Comment by KarlOfDuty** [comment]
This is what /t plots does

![image](https://user-images.githubusercontent.com/18099825/64604537-a06b1800-d3c2-11e9-9d5c-0395b5a848e6.png)

As the comments above say, you are probably looking for /plot
