### ISSUE TITLE
[Bug] McMMO Special Potion Ingredients dont work

### ISSUE THREAD

**Issue by WhitPb7** [EarthMC/Issue-Tracker#749]
**Server**
Towny

**Describe the bug**
Normally youre able to make water breathing with lily pads (1 alchemy) and jump boost with red mushrooms (250 alchemy) but youre not on emc (cant even insert lily pads)
**To Reproduce**
1. Make an awkward potion with a brewing stand
2. Add a red mushroom
3. Wait
4. See that you get no added effects

**Expected behavior**
The awkward potion should turn into jump boost

**Comment by WhitPb7** [comment]
oops hit enter too soon on accident

**Comment by DeadGlamour** [comment]
I had the same problem as well, it should work with red mushroom and lily pad but ist not

**Comment by KarlOfDuty** [comment]
Mcmmo is pretty buggy and as we are unable to update it due to compatibility issues right now it is something we will have to live with.
