### ISSUE TITLE
/res spawn

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#75]
If you do /res spawn you get teleported to your /t spawn and not your bed. Sounds like a mistake IDK tho.

**Comment by KarlOfDuty** [comment]
Have you placed your bed in a plot owned by you?

**Comment by Wextra** [comment]
Just wanted to say; me and my friends tried /res spawn, but they did not have permission to run that command. The bed was placed in their plot and they had slept in it.

**Comment by KarlOfDuty** [comment]
I have tested it and it seems players have permission to use it so you can make a separate issue if specific players still can't.

**Comment by KarlOfDuty** [comment]
It probably cannot be fixed while we use the current respawn system unless towny checks essentials spawn specifically for it or something.
