### ISSUE TITLE
Let Us See Farther Than 4 Chunks

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#750]
Listen, I understand the server is hosted on a 2008 Windows Laptop, but can you at least let us see farther than 4 chunks? It is seriously immersion-ruining. I want the server to get a new anti-lag plugin, one that actually lets us SEE. Thanks

**Comment by FutureCW** [comment]
Minecraft is shit at multiplayer

**Comment by KarlOfDuty** [comment]
Duplicate.
