### ISSUE TITLE
Re-Enable Jails

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#751]
Jails need to be re enabled. What is the point of having the jail plot if you can't have a jail? I understand it's to make it so people aren't trapped, but that's what jails are for whether you like it or not. So please re enable jails.

**Comment by Pengun78** [comment]
Yea bro

**Comment by Pengun78** [comment]
Epic!

**Comment by DeadGlamour** [comment]
They are easy to abuse, people can just trap new people forever, destroying their game and deriving people away from the server, maybe if it had a max time or ways out but not in its current form

**Comment by docwhomc** [comment]
Jails are not allowed as they violate rule 2.1. If you don't like that your jail plot doesn't serve a point, then I'd suggest changing it to another plot type.

**Comment by KarlOfDuty** [comment]
We have made requests for a change to the jail system, making it so players can't be locked up forever. Until Towny has implemented that we will not re-enable the system.

**Comment by Fruitloopins** [comment]
> Rule 2.1 is about nation naming. Totally unrelated.

![image](https://user-images.githubusercontent.com/49851457/214115984-f4d7f896-5acc-421f-8d57-9869170bdada.png)

**Comment by Aylywyn** [comment]
Take a look at the date on this... Then use the Wayback Machine on the Rules.
