### ISSUE TITLE
[BUG] Getting kicked for talking quickly in /msg

### ISSUE THREAD

**Issue by AlexGamerYTT** [EarthMC/Issue-Tracker#752]
**Server**
As I know, Towny.

**Describe the bug**
I chat quickly with a person/friend using /msg command (or global) and anti-spam system thinks it's flood .-. when I'm just talking fast.

**To Reproduce**
1. Talk with a random user
2. Talk normally but quickly
3. Wait a few seconds
4. Get kicked because of spamming

**Expected behavior**
I think what should have to happen is a warning in the worst case or a cooldown, but not kicking. I talk quickly at nation/town chat and nothing happens, just in /msg or global.

**Screenshots**
If you reproduce the bug you will get an specific message when kicked.

**Additional context**

Nothing, that's all.
Hope it can get solved.
Thanks.

**Comment by FutureCW** [comment]
How about longer messages or longer pauses in between messages

**Comment by DasCodes** [comment]
The plugin was a bit aggressive, I believe it was turned down a bit. Do you still see this issue? @AlexGamerYTT

**Comment by KarlOfDuty** [comment]
The issue should be resolved.
