### ISSUE TITLE
Broken Map

### ISSUE THREAD

**Issue by Konradkh** [EarthMC/Issue-Tracker#754]
The map for EarthMC isn't working for me, I tried deleting my cache, I tried going into the server, I'm in the server but the map is still not working, what do I do?
![image](https://user-images.githubusercontent.com/47564782/64479893-13577180-d1be-11e9-89c5-353bd010312e.png)

**Comment by Konradkh** [comment]
I found out the error, when you press Map on the site, it goes to "https://earthmc.net/map" but it should go to "https://earthmc.net/map/" because that one works, so fix that admins

**Comment by KarlOfDuty** [comment]
Fixed.
