### ISSUE TITLE
SignShops (sign shop won't recognise chests)

### ISSUE THREAD

**Issue by Shootcity** [EarthMC/Issue-Tracker#755]
**Server**
Which server the bug is on.
Towny
**Describe the bug**

I have placed the sign for the sign shop selling 50 diamonds at france n spawn. Everything is fine until I am asked to link to a chest. when I do I click on the sign shop then I click on the chest but the chest isnt recognised and then my timeframe to select times out.

**To Reproduce**

1. place sign
2. type [item]
3. click on sign with diamonds, add 50 diamonds
4. click on sign with gold,add one gold.
5. click on sign, receive message (30 seconds to link to a chest)
6. click on chest - no response at all.

**Expected behavior**
chest linked at x y z coord

**Screenshots**

https://cdn.discordapp.com/attachments/571032892273328166/620000341844295699/unknown.png

**Additional context**

**Comment by KarlOfDuty** [comment]
This can be solved for mods by turning off /anychest and /silentchest
