### ISSUE TITLE
Keep getting "[Towny] null"

### ISSUE THREAD

**Issue by Subking** [EarthMC/Issue-Tracker#756]
Towny

Whenever I type /t claim when trying to add new land to my town or when I try to withdraw from my town's bank, I get the following error : [Towny] null

I should be able to simply withdraw my gold from my bank and also claim new land but that is not the case.

![screenshot earthmc](https://user-images.githubusercontent.com/55074189/64503300-40b82400-d27f-11e9-9ec9-acac7821ff8a.jpg)

Is there any way I can fix this? I already tried going into the nether as some players have advised me and also re-logging in and it hasn't worked so far. Please help.

**Comment by SuperChrisBoy** [comment]
One of my friend is having the same problem as well. Whenever he type /t claim or /t withdraw, it always shows “null”

**Comment by KarlOfDuty** [comment]
Should be fixed now.
