### ISSUE TITLE
add public town travel

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#757]
**Is your feature request related to a problem? Please describe.**
It's clear that we have way too many nations in earthmc at the moment. With over 200 nations, they have become very common. Almost every second day you can see another nation being made, and they disband way slower than new ones are getting made. Powerful nations that represent a strong alliance among many towns do no longer exist (and I think it's fair to assume this is what nations meant to be originally). Instead we have hundreds of them where only one or two towns belong to one.

**Describe the solution you'd like**
By adding public town travel (and maybe nation taxes), the amount of nations that will be made in the future will decrease. The most important reason why nations are created, is to have access to a nation travel. So if public town travel would be implemented, people will no longer have to create one only to make it possible for others to tp to their town. It would make things a lot easier in general. People that want to trade but don't have a town yet could trade via /t spawn. Of course one should be able to turn public town travel on and off, so there will be no worries about griefing next to your town.

**Additional context**

**Comment by ImperialFishy** [comment]
The game is way too easy already this would just make it worse. I previously made a suggestion #696 to bring back nation tax. If anything, I would support the complete removal of nation spawn travel as a deterring mechanism for people creating a disgusting amount of 1 man nations. This would also encourage people to explore the beautiful map and not be confined to their town and some nation shops.

**Comment by SuperChrisBoy** [comment]
I would suggest to add a cost to use public town spawn if possible. I think it still can encourage people to explore around and in the same time they can teleport public town spawn if they really need to but with a cost.

**Comment by FutureCW** [comment]
Cost would have to be really high. This is an earth map. Teleportation needs to be low

**Comment by docwhomc** [comment]
A robust ice based, nether transport system would also work.  It would take a lot of work, but it could be done.

**Comment by DasCodes** [comment]
We won't be doing this for now.
