### ISSUE TITLE
/t bank lost all my gold

### ISSUE THREAD

**Issue by Subking** [EarthMC/Issue-Tracker#758]
**Server**
Towny

**Describe the bug**
Deposited my gold into the bank, got an error text stating the deposit didn't work yet I had my gold taken from me either way.

I've had this problem in towny, I lost all the gold that I had deposited into my bank when the bug that gave several people the "[Towny] null" error which happened to me as well on 09/08/19 which was yesterday. I've already made a ticket and everything and several modders have already contacted me but no one has done anything about it and I was already assured that it's something that can be fixed but I have been waiting for several hours already waiting to recover my lost gold. Please help, I just want to enjoy the game and progress in my little town.

**Comment by docwhomc** [comment]
I'm sorry this happened to you Subking, but we can't fix every issue in a couple of hours. We only have a few server admins and mods and many of us have full time jobs and do this on our spare time.

A similar issue happened to me on factions the other day, and it hasn't been resolved yet either, and I'm a mod.

**Comment by docwhomc** [comment]
Related to https://github.com/EarthMC/Issue-Tracker/issues/753

**Comment by DasCodes** [comment]
@Subking Please use our support Discord to request a refund for the golds you had lost.
