### ISSUE TITLE
/t spawn not working, is this a bug or is it intentional?

### ISSUE THREAD

**Issue by AlecGMain** [EarthMC/Issue-Tracker#760]
**Server**
Towny
**Describe the bug**
The /t spawn command does not allow me to teleport to my town. However, /n spawn allows me to teleport to my nation, so what's going on?
**To Reproduce**
1. Go to console
2. Type /t spawn
3. See error

**Comment by KarlOfDuty** [comment]
Should be fixed.

**Comment by GRAnimated** [comment]
It's happening again.

**Comment by KarlOfDuty** [comment]
Could you try going through a nether portal? What error does it show?

**Comment by WhitPlayzYT** [comment]
^
