### ISSUE TITLE
[BUG] /f who (name) cant see offline players (Internal error has occurred)

### ISSUE THREAD

**Issue by vVertex** [EarthMC/Issue-Tracker#761]
**Server**
Which server the bug is on.
Factions

**Describe the bug**
When you type /f who (name of faction) many times you are unable to see offline players of that faction. Offline players can help in many ways, to see the strength of a faction, or to see when someone was last online.

**To Reproduce**
1. Go to 'EarthMC and join the factions subserver'
2. Type '/f who (name of a faction)' ie brutalowl, zimbabwe, yuan, gulag, 
3. View the faction to see if you can see the offline members
4. See error "An internal error occurred while attempting to perform this command."

**Expected behavior**
Expected to be able to view offline members, and see when they were last online, their ranks in the faction, and balance.

**Screenshots**

Screenshot of expected behavior
![80bb6fc80a23a3838b9073d5f2fdf8e0](https://user-images.githubusercontent.com/54566216/64756458-a8c37000-d4f4-11e9-8673-0e7c02e9b95e.png)

Screenshots of what happens when you get the error
![35dbbc454d17b2a82ce3693a0a670912](https://user-images.githubusercontent.com/54566216/64756484-c264b780-d4f4-11e9-8060-e664f43f28a7.png)
![419aa70e7cc721331ed60fed593a54e3](https://user-images.githubusercontent.com/54566216/64756510-da3c3b80-d4f4-11e9-8d9e-b9c662ba2a6b.png)

**Additional context**
none

**Comment by KarlOfDuty** [comment]
The issue should be resolved.
