### ISSUE TITLE
My Opinion on a War Plugin

### ISSUE THREAD

**Issue by WhitPlayzYT** [EarthMC/Issue-Tracker#762]
People always seem to really want a a war plugin, and I want to explain why they shouldn't, and probaly won't be added.

First off, towny is not PvP based, so we shouldn't make it be, if you want PvP go play factions. You may say that war makes the server more realistic so it can be like countries going to battle, but it honestly doesn't.

Secondly, alot of us just want to be peaceful and build, trade, ect. For the ones of us that do, we don't want to just be constantly killed for basically no reason. You may say "Oh you can build, trade, and PvP at once." You shouldn't have to, unless you actually want to.

Lastly, it's not as simple as you think to add. There may be a war plugin already as part of the towny plugin but it barely has any features. To add anti claim hiding would take quiet a bit of code, just as an example. 

As a final conclusion, a war plugin should not be added. I am not saying that war shouldn't be a thing at all, just that a plugin with everyone's requests for war is just unnessicarry. Thank you for taking time to read this all.

**Comment by DeadGlamour** [comment]
I personally think they should just enable pvp only towards enemy nations and add a cool down for towns joining/leaving a nation, sadly tho there is no such option in towny so a war day should at least be tried, I am afraid people will be killed any second as well but 1 test will be fine and we could see what the community actually thinks of it once it becomes practical and not just a theory, just by the ammount of requests for it we should at least try it, I really understand how it feels like to be killed by gangs and how annoying it can be but before we jump into conclusions we should at least try it once and see how it goes.

**Comment by FutureCW** [comment]
Highlander, you’ve seen the war days GitHub post right? A war plugin isn’t what we’re looking for, it’s a way to have pvp in towns without players getting too pissy

**Comment by GreenmanYT** [comment]
I'm not against PvP days, even though I don't PvP, just if you where to enable them, you would have to give a 1 month warning, so that towns that don't want PvP can build walls, etc.

**Comment by FutureCW** [comment]
Towns need to pay gold to be exempt from war days. Letting everyone be exempt for free kind of makes it useless

**Comment by Highlander214** [comment]
or just not attacks random towns

**Comment by FutureCW** [comment]
“Random towns” But your enemy towns could still opt out...

**Comment by Pengun78** [comment]
War days shouldnt be added ppl would just camp at every /n spawn to kill ppl teleporting there u couldnt use grinders without getting killed and you'd get hunted down without being at war

**Comment by FutureCW** [comment]
Then disable /n spawn for war days...

**Comment by DeadGlamour** [comment]
1 day a week of fighting isnt that bad, I am a builder myself and I enjoy building but fighting once a week wouldnt be bad, especially if we warn every1 a few weeks before

**Comment by KarlOfDuty** [comment]
This isn't really about something you want to happen, just something you don't want to happen.
