### ISSUE TITLE
[Feature] Join Queue Message

### ISSUE THREAD

**Issue by MichaelMouseStar** [EarthMC/Issue-Tracker#764]
The server should seriously add something to the queue lobby to remind new players to join queue using the compass or commands. I spend my day on the EMC Discord 24/7 and it's hilarious helping out some new players who ask why queue has taken them 6 hours only to learn that they never actually joined queue, but I think it is a bit cruel. Maybe a message in chat or using the title command (text on screen *vanilla feature) or even a book would be nice. It could save the mods a lot of time as well when they could be working on more urgent issues. It's a simple feature I'm suggesting, so hopefully it's not too much.

**Comment by KarlOfDuty** [comment]
Done.
