### ISSUE TITLE
[Bug] Can't view or send anything in global chat

### ISSUE THREAD

**Issue by SuperChrisBoy** [EarthMC/Issue-Tracker#765]
**Server**
Towny

**Describe the bug**
Can't view or type anything in the global channel. The chat is basically silent for me. Leaving and rejoining the global chat by /ch leave global and /ch join global still doesn't fix. Rejoining the server doesn't work as well. I checked /ch to view the channels available

**To Reproduce**
1. Join Towny
2. Sees no one chatting in global
3. Type anything, maybe "Hi"
4. Receive error "You have no channel to write into. Type /ch for help."

**Expected behavior**
I should be able to view global and chat with others on the channel.

**Attempted**
1. Leaving and rejoining the global chat by /ch leave global and /ch join global. After typing /ch leave global, I received an error saying "You are not in this channel. Type /ch j global to join". However, when I type /ch join global, it says "You have joined the channel: global"
2. Rejoining the server doesn't fix as well.

**Additional context**
I typed /ch to check the available channels it shows this:
--------------------------------------------------------------------------
Available: chinese, french, global, nation, russian, spanish, town, trade

Your channels (7):
 - chinese (read)
 - french (read)
 - nation (read)
 - russian (read)
 - spanish (read)
 - town (read)
 - trade (read)

--------------------------------------------------------------------------

Global is not under "Your channels" list for me.

**Comment by Lee0723** [comment]
I have had the same issue for several days.

**Comment by SuperChrisBoy** [comment]
It’s still happening to me

**Comment by KarlOfDuty** [comment]
Could you try /ch set instead of /ch join? And also try /ch leave on all channels and rejoin them again.

**Comment by SuperChrisBoy** [comment]
I can view and type in global again. Just logged in today and the global chat is working for me. Thanks for your help!

**Comment by KarlOfDuty** [comment]
Yes, it seems to happen whenever the plugin has reloaded.

**Comment by SuperChrisBoy** [comment]
Should I close the issue or should I keep for bug fixing?

**Comment by KarlOfDuty** [comment]
Keep it open, I've linked to it for the devs.

**Comment by SuperChrisBoy** [comment]
Okay, good to hear. Thanks very much.
