### ISSUE TITLE
[Feature] Add Sand and terracotta dimension

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#766]
**Is your feature request related to a problem? Please describe.**
There's too many god damn removed deserts and terracotta mountains. the beauty of Earthmc is suffering in the hands of Anarcho-capitalistic greed.

**Describe the solution you'd like**
/warp sand and /warp terracotta to a monthly reset sand and only terracotta world.

**Comment by ImperialFishy** [comment]
Or just roll back terrain instead of giving people a free stuff world

**Comment by FutureCW** [comment]
I mean Shiraz is a mod, and it would solve the issue of rolling back deserts because people don’t know how to terraform

**Comment by FutureLemon** [comment]
I can't disagree more. This takes away all forms of realism on EMC.

**Comment by FutureCW** [comment]
Idk that’s a good point FutureLemon but also people bitch all the time about sand and then staff don’t seem to roll it back. Numidias got some retards who are trying to plant trees where they got sand griefed

**Comment by DeadGlamour** [comment]
I like the idea of it but I think it misses a bit of potential, why not make it a part of a new end dimension instead? Make a custom map and add some resource deposits like in No Mans Sky, maybe allow us to claim outposts there, also dont add the end cities, so it wont break the little parts of the economy still standing, then we have access to end materials, deposits and pretty much anything else the server wants us to have access to

**Comment by riri2010** [comment]
There was a discussion on a similar thread here: https://github.com/EarthMC/Issue-Tracker/issues/699

**Comment by johnyuki** [comment]
I couldn't agree more. As someone with a sand city, people *always* teleport to my town to try and fuck my shit up. Just look at what people have done to my town's surrounding area - Haima, capital of Arabia on the southern coast of the Arabian peninsula. There is no such desert on the server that is away from towns but people feel the need to immediately fuck up the surrounding area and be dicks about it. 

I'm not in favour of adding mining worlds in general, but Sand is so cheap nowadays that a sand world would hardly affect the price of it anyway, and save a lot of headache for people.

**Comment by KarlOfDuty** [comment]
We will not be adding any more dimensions due to the performance and storage issues that would cause.
