### ISSUE TITLE
[Feature] Disable plot PVP toggling while outsider in town claims

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#767]
Trapping is a thing whether we like it or not. Sadly when people trap they do it unfairly and try to bend the rules as much as they can to their favour.

Eg. People that lure people in a hole and then do /plot toggle pvp. This is the worst type of trapping possible when they kill tons and tons of mediocre people with not the best gear but neither do they have bad gear. The problem is when someone steps up for the little man and the trapper just simply disables pvp in the plot because they can't seem to win a fight already in their odds and with equal gear. 

This is why I am asking all the people in favour of a fair and equal fight to stand up and make EMC save again for the little man! Disable /plot toggle pvp while someone from a different town is in the chunk or during combat just like how you can't do /t toggle pvp. The benefits of not being able to change the plot pvp during combat are imense for quality gameplay.

**Comment by Lagann311** [comment]
Couldn‘t agree more. If I remember correctly it wasn‘t always like this right? A few months before players couldn‘t just toggle pvp on and off when another player is in their chunk.

**Comment by FutureCW** [comment]
You have never been able to /t toggle pvp when another player is in your town @Lagann311. You can still /plot toggle pvp whenever you want

**Comment by FutureLemon** [comment]
> You have never been able to /t toggle pvp when another player is in your town @Lagann311. You can still /plot toggle pvp whenever you want

And that is bad!

**Comment by IanSpace71** [comment]
Bruh dont do it thats my #1 source of income.

**Comment by Alexandre1868** [comment]
I agree with this, trappers who do this are hella scummy.

**Comment by DeadGlamour** [comment]
Why not just turn off pvp everywhere, and make it banable to say crap

**Comment by T0rn4do** [comment]
Hi ,
You should look at that:
https://github.com/EarthMC/EarthMC.net/issues/79

**Comment by FutureLemon** [comment]
I think most people misunderstood me, I meant that you shouldn't be able to disable plot PvP when you lure someone to your town and they end up being better than you. It's to prevent scummy actions and possibilities where the trapper dies for once.

**Comment by T0rn4do** [comment]
Traps should just be forbidden

**Comment by DeadGlamour** [comment]
They can just leave the pvp plot and you got the same result
Also Tornado, no

**Comment by T0rn4do** [comment]
Imagine you are trapped and the guy comes with another entrace without falling damages, you can t do anything not even /t spawn

**Comment by DeadGlamour** [comment]
okay so lets say you died and lost some armor, make some new armor, its not that hard, its not like you lost your house or town

**Comment by T0rn4do** [comment]
I lost 120g

**Comment by ImperialFishy** [comment]
Lmfao who carries 120g on them

**Comment by T0rn4do** [comment]
120g is a lot if you don t have a lot of money

**Comment by FutureLemon** [comment]
> Lmfao who carries 120g on them

It is not about him carrying 120 gold it's all about the fact that WHEN trappers fail they can just /t toggle pvp again to disable it. And that is simply unfair and needs to be changed.

**Comment by DarkRush449** [comment]
You could just have linked to the pvp timer, so when you enter a battle with someone you can't use the /plot toggle pvp command until those 15 seconds are up.

**Comment by DasCodes** [comment]
Similar issue: #661.

**Comment by FutureLemon** [comment]
> Similar issue: #661.

My github is much more popular! Don't link it to theirs smh my head!!! >:(

**Comment by KarlOfDuty** [comment]
You should suggest this to the towny developers, it is not something we can do.
