### ISSUE TITLE
Factions Allies Changed to Enemies

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#768]
**Server:** Factions

**Description:** All allies were changed to enemies without being set as enemies by members of said factions.

**To Reproduce:** currently unclear

**Expected behavior**
Faction relations remaining unchanged unless a member of one of the factions (with appropriate perms) changes them via a command.

**Comment by KarlOfDuty** [comment]
The factions plugin is very buggy, it will likely be fixed when the server is back.
