### ISSUE TITLE
Friend invisible

### ISSUE THREAD

**Issue by EliOfficial** [EarthMC/Issue-Tracker#769]
**Server**
EarthMC lobby

**Describe the bug**
He says hes there like in front of me and stuff but I cant see him at all.

**To Reproduce**

**Expected behavior**

**Screenshots**
Well it would just show him not there.

**Additional context**

**Comment by Warriorrrr** [comment]
People who join before you in the hub world aren't shown, you can only see people who joined after you.

**Comment by DasCodes** [comment]
This has been fixed.
