### ISSUE TITLE
Non-Issue - Recipe Suggestion - Please UpVote

### ISSUE THREAD

**Issue by Johnsonk2** [EarthMC/Issue-Tracker#77]
I think it would be great to include a slimeball recipe. It's quite annoying trying to find slimes or even a slime chunk, so why not huh?

![image](https://user-images.githubusercontent.com/25190838/47941424-06a32680-dee6-11e8-9e9d-a53bad3abc07.png)

-This recipe will also give us a great use of rotten flesh!

**Comment by KarlOfDuty** [comment]
Slimes spawn in swamp biomes. I think that's enough.

**Comment by Johnsonk2** [comment]
> Slimes spawn in swamp biomes. I think that's enough.

Yeah no, that sucks. Its too rare

**Comment by KarlOfDuty** [comment]
I feel like this just makes the game easier than it needs to be. We can revisit this topic in the future if needed.

**Comment by Johnsonk2** [comment]
Its needed.

**Comment by KaueTheTrekker** [comment]
gosh you're making the game just more grindy, at least make the slimes spawn more frequenty ffs
