### ISSUE TITLE
[Feature] Dungeons

### ISSUE THREAD

**Issue by NeonKrby** [EarthMC/Issue-Tracker#770]
Hey remember when this was going to happen.  
https://www.youtube.com/watch?v=xZQFh6Gh--M&feature=youtu.be
can we make it happen

**Comment by DeadGlamour** [comment]
A bit over a month from now is november 1st, so were pretty close

**Comment by NeonKrby** [comment]
november 1st 2018 was the Terra Nova release. Thats what its referring to. Its a year late.

**Comment by DeadGlamour** [comment]
https://imgur.com/a/wDmY27J
Look on the date fix says it

**Comment by NeonKrby** [comment]
![image](https://user-images.githubusercontent.com/45209878/65623837-a81be680-df96-11e9-86dc-442ca55f5614.png)

**Comment by Pengun78** [comment]
Lol it was probably meant for the release but then it never happened

**Comment by KarlOfDuty** [comment]
Yes! One day it will happen, just wait until november.
