### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by AntoanBG** [EarthMC/Issue-Tracker#771]
**Server**
Which server the bug is on.
-towny

**Describe the bug**
-Im on the plot , i have the gold in my hand , i type /t deposit 10 and it says , no permission

**To Reproduce**
1. Go to 'your plot'
2. Type command 't deposit (some amount of gold)'
3. See error

**Expected behavior**
I should deposit the gold in my town bank

**Screenshots**
![image](https://user-images.githubusercontent.com/46416276/65499308-0f1d9a80-dec6-11e9-9ff8-f6a6c5b837c0.png)

**Additional context**
I just was to deposit 10 gold.

**Comment by JaVolimKatarinu** [comment]
Have you tried visiting the Nether? And also, you need to be in home or bank plot. Either go /t spawn or /plot set bank and then try depositing.

**Comment by AntoanBG** [comment]
Fixed: Go to nether and back

**Comment by docwhomc** [comment]
Please close this ticket @AntoanBG.
