### ISSUE TITLE
[Bug]?fr Bug: world border/wrap - no teleported entity

### ISSUE THREAD

**Issue by Barito974** [EarthMC/Issue-Tracker#772]
**Server**
Town

**Describe the bug**
world border/wrap - boat with sheep not teleported at international dateline.

**To Reproduce**
Come with a mutton in a boat in worldborder, go into world border, you are teleported but boat and mutton not

**Expected behavior**
Can you make spawn the sheep at my town ?
Lilypad

**Screenshots**
Video :
https://youtu.be/3yl-hnFiLZk

**Additional context**
I have buy the sheep

**Comment by Barito974** [comment]
Rip me

**Comment by Barito974** [comment]
Rip me

**Comment by docwhomc** [comment]
It's called a sheep, not a mutton.  Mutton is the meat from a sheep.

**Comment by Barito974** [comment]
Thx

**Comment by KarlOfDuty** [comment]
It only works with players I'm afraid.
