### ISSUE TITLE
[Feature] Gui for towny

### ISSUE THREAD

**Issue by Dood9123** [EarthMC/Issue-Tracker#773]
**Is your feature request related to a problem? Please describe.**
as it stands emc towny it more tedius than it need to be
**Describe the solution you'd like**
https://www.spigotmc.org/resources/townygui-4-years-customizable-1-7-10-1-14-4.9493/

easy to use gui that allows customization and is easy to understand.
**Additional context**
all you need to do is type /townygui and a gui pops up
also you can still use regular towny commands and it does not modify existing towny plugin

**Comment by docwhomc** [comment]
We'll look into it.  In the mean time, please clean up your post above (i.e. please remove the instructions).

**Comment by KarlOfDuty** [comment]
I don't think adding more things increasing lag is a good idea at this point right as we have largely eliminated it.
