### ISSUE TITLE
[BUG] Villagers not breeding

### ISSUE THREAD

**Issue by a-111** [EarthMC/Issue-Tracker#774]
**Server**
Happens on towny. Not sure about factions/classic

**Describe the bug**
Many people over the past few weeks have been saying that villagers are not breeding. Some clarification on this would be nice and maybe even the issue being fixed.

**To Reproduce**
1. Attempt to normally breed villagers.

**Comment by FutureLemon** [comment]
They do breed, earlier today I got a sharpness V villager. If you want them to breed more make sure you have doors, food for them, and sunlight. Villagers on EMC especially also need a lot of time to breed they're not as fast as to be expected and if you want them to breed you need the chunks to be loaded.

**Comment by a-111** [comment]
> They do breed, earlier today I got a sharpness V villager. If you want them to breed more make sure you have doors, food for them, and sunlight. Villagers on EMC especially also need a lot of time to breed they're not as fast as to be expected and if you want them to breed you need the chunks to be loaded.

I've done exactly that for a few days. They've been making hearts but they aren't making any villagers. I have no idea why this happens (my town might just be cursed)

**Comment by FutureLemon** [comment]
Then you have to wait longer.

**Comment by Barito974** [comment]
How have you make spawn villager ?

**Comment by KarlOfDuty** [comment]
This should be fixed.
