### ISSUE TITLE
[Feature] Allow to transfer capitals OR decrease nation price

### ISSUE THREAD

**Issue by xCptSpiffyx** [EarthMC/Issue-Tracker#775]
Ran into an issue when coming back to the server. I was aware that staff no longer moved nations for players (understandable). However tried switching capitals and realised this is no longer possible. 

No one wants to buy a nation in Africa, Asia, South America. Even then if it's not in an exact location that they want they are unlikely to buy. 

I don't really see why this feature has been taken away unless it is something to do with town glitching but if that is the case and we can no longer switch over capitals to other town in a nation, does it not make sense to decrease the nation price even just slightly.

**Comment by FutureLemon** [comment]
You can still move nations you just don't know how...

**Comment by docwhomc** [comment]
We aren't going to do that.

Our position is that players should plan carefully when creating a nation (i.e. only do it if they're sure they want the capital to be there).

As for the cost of starting a nation, we will not lower it as there are too many nations with few if any towns besides the capital.  If anything we will increase it.
