### ISSUE TITLE
[Feature]Add a plugin to teleport mobs for 1 gold Ex : /tele aimed entity 26789 64 23856

### ISSUE THREAD

**Issue by Barito974** [EarthMC/Issue-Tracker#777]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i walk with entity for go with them at my town because other guys can kill the entity and me

**Describe the solution you'd like**
For 1 gold, we can teleport entity at coordonates
Specifely

**Additional context**
Nothing

**Comment by KarlOfDuty** [comment]
We will not let players teleport mobs to specific coordinates, that can be very much abused.
