### ISSUE TITLE
[Feature] horse armor recipe

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#779]
**Is your feature request related to a problem? Please describe.**
horse armor is really rare because you can only find it in nether fortresses, while it's not worth being that rare and we need to be able to have our horses protected

**Describe the solution you'd like**
a horse armor recipe like on the picture
![armor](https://user-images.githubusercontent.com/44297328/65835665-59997f80-e2e9-11e9-8fe3-c3eb68bfafc3.png)

**Comment by JaVolimKatarinu** [comment]
Just go nether exploring, you can find a bunch of them...

**Comment by DeadGlamour** [comment]
I have like 2 dubs, that really not that hard

**Comment by Prismary** [comment]
They're novelty items that are obtainable by buying from other players, making a crafting recipe available would kill the rarity of them. Since it's so rarely used I'd say making them craftable isn't necessary, but I'll leave this open for now.

**Comment by AndrewCheedle** [comment]
My brother in christ they are not even that rare anymore

**Comment by CorruptedGreed** [comment]
Rarity seems fine currently, no need to add a recipe
