### ISSUE TITLE
Remove Time Limit For Drowneds

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#781]
**Is your feature request related to a problem? Please describe.**
Yes. Whenever drowneds spawn, there seems to be a set time limit of about 20 seconds before they despawn. I can understand why this is, most likely to control trident amounts, but for real? I had a drowned spawn next to my submarine earlier, it was holding a nautilus shell. I was going to kill it but right before I could it despawned. 

**Describe the solution you'd like**
Remove this supposed time limit for drowneds. Please

**Additional context**

**Comment by KarlOfDuty** [comment]
Mobs can randomly despawn sometimes, it is not something we can do anything about.
