### ISSUE TITLE
[Feature] add a colony option

### ISSUE THREAD

**Issue by Briem04** [EarthMC/Issue-Tracker#782]
![9432F1AE-CFE4-4A4F-8298-02F0E53DEB43](https://user-images.githubusercontent.com/56074802/66042239-399dd200-e51c-11e9-8221-6a900eeb1fbb.jpeg)
With this Feature i do not mean the existing outpost function.
This Feature is ment to help the towns that are too far from any Nation to join it.
Let’s say you spend a week collecting the gold you need to make a town, you make it on a beautiful island in the middle of the ocean. Then you can’t teleport. You ask the people who are online, you have to be in a Nation to teleport they say... you ask to join a Nation, It is not possible because you are too far away from every nation. So no shopping or trading for you until you collect 1000 gold. Which takes 4 months to do without members, and who is gonnan join a town without quick travel? Nobody. 

The Colony should help with that, a Nation must be at least 5000 block from the capital to be made, and functions the same as a regular town

**Comment by KarlOfDuty** [comment]
This should go on the towny issue tracker, not ours.

https://github.com/TownyAdvanced/Towny/issues
