### ISSUE TITLE
Lower or Remove the PVP Protection

### ISSUE THREAD

**Issue by IanSpace71** [EarthMC/Issue-Tracker#783]
**Is your feature request related to a problem? Please describe.**
Lately new players have either greifed my town, or stole from players in my town, and I have been unable to kill them due to the player pvp protection. I get that you don’t want new players to die instantly, but at least lower the time so that they are able to be killed about the same point they are able to join a town, or have it be disabled when they join a town. Overall it is just a major annoyance, and I’d like to see it gone/shortened.
     -IanSpace

**Comment by DeadGlamour** [comment]
I find it susp that some1 who traps people for no reason asks to remove new player protection

**Comment by KarlOfDuty** [comment]
The current time is 12 hours I believe, which seems like a good amount to me.
