### ISSUE TITLE
Increase server render distance.

### ISSUE THREAD

**Issue by watergod1234** [EarthMC/Issue-Tracker#784]
With the recent performance fixes do you think it'd be possible to increase the server render distance? It's set right now at about 3 or 4, maybe a little higher to 6 or maybe even 8 may not hurt performance too badly (I don't know, you'll have to test it). It might be worth a try. 👍

**Comment by DeadGlamour** [comment]
Id love it as well

**Comment by riri2010** [comment]
honestly even 5 would be a huge improvement. but I think they spent all the extra preformance on raising the player limit.
maybe the render distance can change based on how many players are online?

**Comment by KarlOfDuty** [comment]
It is something we will look into at some point in the future but not at this time.
