### ISSUE TITLE
[BUG] Frost Walker

### ISSUE THREAD

**Issue by Zephi** [EarthMC/Issue-Tracker#785]
**Server**
earthmc.net towny

**Describe the bug**
The ice does not vanish under blocks. For example, if there is a block of leaves like 10 blocks above the ice, it does not disappear. It stays until it is manually broken. (The ice does not disappear no matter the block distance, as long as a block is above it it won't vanish.)

**To Reproduce**
1. Go to any covered area with water below it
2. Have frost walker enchant on your boots and walk on the water
3. Wait to see if the ice vanishes

**Expected behavior**
The ice won't disappear, no matter how long you wait

**Screenshots**

**Additional context**

**Comment by FutureLemon** [comment]
This is a minecraft feature and the ice only stays when there's no sunlight (under blocks and during night time).
