### ISSUE TITLE
welp.

### ISSUE THREAD

**Issue by OwOTheGod** [EarthMC/Issue-Tracker#786]

**Comment by OwOTheGod** [comment]
The likely reason I died is that my wifi shuts down after being on for 3 hours, it's likely the game pulled some bullshit along the lines of; You are still online; You are drowning; you died.

**Comment by OwOTheGod** [comment]
Also I put this without a code because I wanted help on this fast. so aight.

**Comment by docwhomc** [comment]
You will not get help for something faster because you didn't "put this without a code".  Since you intentionally filled this out wrong, we will not provide any assistance until you fill it out properly.

**Comment by OwOTheGod** [comment]
aight

**Comment by DasCodes** [comment]
Please don't write the entire issue as a title. Only put a short description of the issue as the title and write the actual issue as a message like this.

**Comment by DasCodes** [comment]
This is not our support platform. Please use our support Discord to make a ticket if you are asking for a refund. @OwOTheGod
