### ISSUE TITLE
Channel stuck - Insufficent Permission (chatcontrol.channel.nation.leave)

### ISSUE THREAD

**Issue by TheRealElonMusk** [EarthMC/Issue-Tracker#788]
When I chat, The message gets sent in global and nation channels. When I do /ch l nation to leave the nation, it gives the message 
![Capture](https://user-images.githubusercontent.com/26727875/66265668-1b133180-e7cf-11e9-80cc-076dfab30e83.PNG)

I Hope this is a bug and not intentional, and Uncle Sn (the mod) says that he thinks it is a bug.

**Comment by KarlOfDuty** [comment]
Should be fixed now.
