### ISSUE TITLE
[BUG] Potions turning into potion.potency.8

### ISSUE THREAD

**Issue by AlphalordYT1** [EarthMC/Issue-Tracker#790]
**Server**
EarthMC Towny

**Describe the bug**
Haste II potions (1:30) are turning to potion.potency.8, and when it's that, they doesn't work.

**To Reproduce**
1. Make a sign shop that sells Haste II
2. Put the potions in it
3. Wait some times - 15 - 30 mins)
4. Buy the potions
5. See error

**Expected behavior**
When buying the potions, it should be "Haste II (1:30) instead of "Potion.potency.8)

**Screenshots**
https://www.noelshack.com/2019-41-1-1570446929-2019-10-07-13-14-41.png
https://www.noelshack.com/2019-41-1-1570446931-2019-10-07-13-14-43.png

**Additional context**
None

**Comment by WhitPb7** [comment]
McMMO potions dont work at all in shop signs, it does this to more than just haste

**Comment by KarlOfDuty** [comment]
Indeed, it is something the developer has tried to fix but it does not seem possible.
