### ISSUE TITLE
Written Book glitch/dupe with Sign Shops

### ISSUE THREAD

**Issue by Twitchyyy** [EarthMC/Issue-Tracker#791]
**Server**
Towny

**Describe the bug**
When selling Written Books (copy of copy) with sign shops, they will initially appear in the shop GUI correctly as a Copy of Copy book. Then after an unknown amount of time, they will revert to selling "Originals" instead. This makes it so the sign shop doesn't recognize the copy of copy books in the storage chest and produces an "Shop doesn't have enough items in storage to offer" error message.

The dupe part comes in here: sometimes as a result of the written books in the  shop GUI being randomly changed to offer "Originals" instead of "copy of copy" or "copy of original", some of the shops will still "work". What will happen is random written book shops will remove the copy of copy from the chest shop storage and give the player an Original copy. I'm not sure why some shops work this way and others just say the shop is out of stock, but page count/data might be a variable.  This effectively dupes written books as a result.

**To Reproduce**
1. Create a sign shop with [item]
2. Set a written book copy of original for sale on the sign
3. Set a gold amount or an item trade (such as gold nuggets)
4. Set the shop chest storage
5. Check what the shop offers. You should see it offers a "copy of copy" currently and will work for trade.
6. Wait, do something, and come back. The sign shop will now be offering "Orignals" instead of a copy of copy or copy of originals

**Expected behavior**
The sign shop GUI should stay as offering copy of copy written books for sale; taking copy of copy books from the storage chest and giving it to the player in exchange for gold or an item trade.

**Screenshots**
I can provide screens if requested. I think this is straight forward enough to not need visuals.

**Additional context**
Tested this twice. Not sure what causes it. Could be time, chunk loading, logging, teleporting, etc but it's a bug with the sign shop pluggin.

**Comment by TheRealElonMusk** [comment]
Its nbt data errors. My theory is that the shopsigns arent recognising the NBT data saying "copy of copy" and as such will glitch itself.

**Comment by Twitchyyy** [comment]
I suppose, but it recognizes the NBT data initially. The shops work for a while but then randomly revert

**Comment by Barbocity** [comment]
The same thing is happening to me.  I tried to sell my book, it's a copy of a copy, but it changed to "Original" in the sign shop, and therefore the sale doesn't go through.  It's impossible to sell more than 1 original.  Can it at least be copy of original?  Thanks.

**Comment by KarlOfDuty** [comment]
This should go on the plugin's issue tracker, not here.

https://github.com/TheNewEconomy/TNE-Bukkit/issues
