### ISSUE TITLE
missing gold

### ISSUE THREAD

**Issue by dayangvvv** [EarthMC/Issue-Tracker#792]
**Server**
emc

i put my gold ore into my furnace
but when i reconnected 3minutes later
they dissappered
i was in my private plot in Lns_chengdu
X Y Z is 19074 61 -5561

**Comment by FutureCW** [comment]
You got your gold stolen then my dude. Unless you own the town and no one else has the rank of Councillor, someone stole it

**Comment by JaVolimKatarinu** [comment]
This isnt a place to report stuff like this. This is Github where you report some plugin related stuff or suggestions. 
Please join our Support discord https://discord.gg/EZBYmpp  and report your problem there.

**Comment by DasCodes** [comment]
What @JaVolimKatarinu said above. Please use our support discord instead. @dayangvvv
