### ISSUE TITLE
Cow disappeared and mob farm not working

### ISSUE THREAD

**Issue by kisotog** [EarthMC/Issue-Tracker#793]
My cows just randomly disappeared in front of me and now there gone also there is no mob spawning in my mob farm. pls help. 
Username Kisoto

**Comment by DasCodes** [comment]
This is not our support platform, please find our support Discord in #info channel of EMC discord and ask for a refund. Also, you have to toggle mobs to enable hostile mob spawning. `/plot toggle mobs`. @kisotog
