### ISSUE TITLE
I GOT BANNED AS ALT FOR GOVI

### ISSUE THREAD

**Issue by Beaver888** [EarthMC/Issue-Tracker#794]
**Describe the issue**
I was just doing stuff tryna make a super smelter then I tped to Perth just to explore
Then I got kicked by some bot/mod called Skynet for being the alt of govi, whats an alt??

**Comment by Beaver888** [comment]
Also who is Govi??

**Comment by Beaver888** [comment]
I am greatly annoyed by this as I was doing my first super smelter :((((((( ever

**Comment by Beaver888** [comment]
Is alt like scamming someone or something? Becasue I havn't ever even heard of a person called Govi

**Comment by Beaver888** [comment]
Also sorry for not posting this on discord  because I dont want to get it.

**Comment by Beaver888** [comment]
Please respond I want to finish the public super smelter :(

**Comment by T0rn4do** [comment]
Hey, beaver .
Ggovi is a guy who got banned but Im not sure.
Alt is for alternative account.
The rule 1.4 says alts aren t allowed. EarthMC.net/rules

**Comment by JaVolimKatarinu** [comment]
This is not a place for your problem. Please create a ticket in our Support Discord. https://discord.gg/EZBYmpp
Join this and appeal for your ban.

**Comment by DasCodes** [comment]
What @JaVolimKatarinu said. Please use our support Discord to appeal.
