### ISSUE TITLE
[feature] Pls remove bot

### ISSUE THREAD

**Issue by TheRealElonMusk** [EarthMC/Issue-Tracker#795]
It gets annoying when the Michelle Obama bot reminds me to vote.

Could you please remove the bot? thanks!

**Comment by JaVolimKatarinu** [comment]
I find bot very funny. It could be more fun if we could use it as chatting bot. Like you talk to her, she gives you some stupid answers and refers you to support discord. 
Btw. she doesnt remind you every hour, just upon a join.

**Comment by KarlOfDuty** [comment]
No, it will not be removed at this time.
