### ISSUE TITLE
/t Deposit isn't working

### ISSUE THREAD

**Issue by ChescopunkYT611** [EarthMC/Issue-Tracker#797]
**Server**
EMC

**Describe the bug**
It is not allowing me to deposit my gold on the town.

**To Reproduce**
1. Go to 'my town "Nuakchot"'
2. Type in the chat '/t deposit'
3. See error "It says [You are not allowed to use that command]"

**Expected behavior**
To deposit my 63 of gold.

**Screenshots**
![2019-10-10_11 52 27](https://user-images.githubusercontent.com/56406451/66589627-8bfe7480-eb54-11e9-9d39-fcfce2bd0e0a.png)

**Additional context**
I think that is happening to everyone in the server.

**Comment by DasCodes** [comment]
Go through a nether portal or relog, should fix that.
