### ISSUE TITLE
Discussion about blast mining (mcmmo) on earthmc

### ISSUE THREAD

**Issue by IWHU** [EarthMC/Issue-Tracker#798]
Blast mining is extremely OP and unbalanced in pvp, one tnt can deal from 5 hearts to even killing with one blow a person in full protection 4 armor. It should be disabled or if it wont get disabled, at least enable axes mcmmo skill, because its not that broken, its at least more balanced than blast mining which shouldnt be used in combat, its literally mining. @KarlOfDuty (sorry for the ping)

**Comment by BommBap** [comment]
hmm blast mining can help u kill someone run to claim when he is low,so it pretty good

**Comment by FutureLemon** [comment]
People were begging for it to be enabled cos it's what helps u in times of lag. Now people want it disabled just figure something out to use it to your own advantage.

**Comment by Prismary** [comment]
TNT has since pretty much been disabled entirely
