### ISSUE TITLE
Villager breeding doesn‘t work

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#799]
**Server**
Towny

**Describe the bug**
Villagers don‘t breed despite every condition is fulfilled

**To Reproduce**
1. Set up a villager breeder 
2. wait (I waited 3 hours)
3. No new villager was bred

**Expected behavior**
Villagers breeding.

**Additional context**
I have 3 villagers in the breeder. There‘s no other villager in the same chunk. I placed enough doors and the inventory of the villagers is filled with carrots. I also made a carrot farm. One villager even planted carrots in the beginning, but now they barely move at all.
The 3nd villager was bred really quickly, however they don‘t reproduce anymore after 3 hours of waiting.

**Comment by johnyuki** [comment]
Do you have any more mobs in the chunk, such as a cow/sheep farm underground beneath the villager farm? How about doors, I believe if you want to breed lots of villagers you have to have lots of doors surrounding the villager pen. 

Send screenshot on your farm.

**Comment by Lagann311** [comment]
I have giant farms under this chunk, but does that really matter? There are no other mobs in the same chunk. 
I have at least 20 doors I think that‘s not the problem

**Comment by DasCodes** [comment]
There's already a discussion going on about this, #774. Please use that issue instead.
