### ISSUE TITLE
You are able to phase through wooden doors with a boat.

### ISSUE THREAD

**Issue by Beaverboy69** [EarthMC/Issue-Tracker#800]
**Server**
Which server the bug is on.
Towny 
**Describe the bug**
While using a boat, and a common known "glitch" with towny or other plugins that use any kind of regions such as World Guard. You are able to get through a 2x2 door (doors placed directly next to each other). 

**To Reproduce**
1. Go to a region or an area that is blocked, where you cannot use doors, make sure that the door is a 2x2 door. 
2. Go to each door and spam it, while attempting to go inside of the door, until (On your screen) the door is open, be sure that it is done on both doors.
3. Spawn in a boat in the wilderness and get it to the area where the door is located, don't unload chunks, if unloaded repeat steps 1 and 2 with the boat. 
4. Go up to the door while riding the boat 
5. Enter the area that is past the doors.

**Expected behavior**
The boat is not able to go through the doors, and remains to be outside. 
**Screenshots**
N/A (Not online, too lazy to wait on queue) 

**Additional context**
The best way for a player to fix this would be using iron doors, or double layered doors (1st set wood of choice, 2nd set iron) For the admin to fix it, not sure if there is a fix that wouldn't largely affect game play.

**Comment by FutureCW** [comment]
They already changed it so you can’t place boats inside of claims. If you’re worried about someone getting a boat into your claims then just raise the door by a block

**Comment by DasCodes** [comment]
I'm afraid that's a vanilla thing of Minecraft unless Mojang fixes it, we can't do anything about it.
