### ISSUE TITLE
Server went down, logged on and I was dead.

### ISSUE THREAD

**Issue by 754c** [EarthMC/Issue-Tracker#802]
The server went down on October 16th, 2019, and members were getting kicked. I was sitting in my town farming blazes, while not in combat and when I logged back on I was dead and my items were not on the ground. I had a protection 4 unbreaking 3 chestplate, unbreaking 3 protection 4 depth strider 3 and mending boots, protection 4 leggings, an aqua affinity protection 4 helmet, all diamond and a sharpness 3, sweeping edge 3 diamond sword.

**Comment by JaVolimKatarinu** [comment]
We dont do refunds on Issue tracker. Please create a ticket on our Support discord server and explain us what has happened.
