### ISSUE TITLE
[Feature] Allow us to block specific people from our shop signs

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#803]
**Is your feature request related to a problem? Please describe.**
There is currently no way to block specific people from accessing shops. You can enemy a whole nation to stop them from teleporting to you or outlaw a specific person, but that doesn't solve the problem as they can just teleport to a nearby nation and then walk. A lot of people like myself like having shops and focusing on that only. It would be nice if we had a way to combat assholes on the server by blocking them from using our shops. This would be akin to trade embargos, or a real life shop banning troublemakers from entering. 

**Describe the solution you'd like**
We could look at one of our shop signs a type a command like */shop sign block name* and it would block that person from using that specific shop sign. Or you could do */shop chunk block name* and it would block that person from interacting with any of the signs in that entire chunk (to speed up the process for people who have like 50 shop signs in a chunk). 

**Additional context**
If people want to go around pvp'ing and fighting there is currently nothing we can do about it other than outlawing them and enemy'ing their nation. Blocking them from our shops gives us merchants a way to at least sort-of fight back in our own way. It also adds a bit more realism.

#MerchantLivesMatter

**Comment by FutureLemon** [comment]
I would love to see a possibility to outlaw people from your shops!

**Comment by WhitPlayzYT** [comment]
Bro I was about to make this

I think it would be cool if you could make certain shop signs whitelist only as well

**Comment by johnyuki** [comment]
> 
> 
> Bro I was about to make this
> 
> I think it would be cool if you could make certain shop signs whitelist only as well

I made the same suggestion a while back too iirc but it didn't get implemented. Hopefully this time around it will, as I can't imagine it is a complex thing at all.

**Comment by DasCodes** [comment]
This isn't the proper place you are requesting this. You should open this issue on the plugin repo of the developer instead. Creatorfromhell made the plugin.

**Comment by DasCodes** [comment]
@johnyuki
