### ISSUE TITLE
[Feature] Make a new github page where the text files from bans and appeals tickets are published.

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#805]
There's a lack of transparency with bans and appeals which causes the community to come to the wrong conclusions.

By making the tickets public there is less likely to be false information spread.

This in turn would benefit moderators and the community.

Here is a link to a discussion on reddit which lays out the idea in more detail between myself and moderator John_Yuki:

https://www.reddit.com/r/EarthMC/comments/djc217/make_text_files_from_bans_and_appeals_available/?utm_medium=android_app&utm_source=share

**Comment by johnyuki** [comment]
I'm not a moderator lmao. Unfortunately.

**Comment by DasCodes** [comment]
I'm afraid ban appeals and tickets will always be public. There are often many cases where private information is shared. We would not like to disclose them in public as they can harm the players.

**Comment by Aitonater** [comment]
You can always redact any sensitive information and resave the text file especially in the instances of doxxing. The final text file can be a version with senstive information removed.

**Comment by DasCodes** [comment]
That would be more work for us, we are already short on staff with the number of tickets we get and the time it takes to resolve them. There are tons of tickets that include a player's personal information. Plus, with privacy players can freely talk about their issue.

**Comment by KarlOfDuty** [comment]
The people who open support tickets can share what they wish, we are not in the business of giving away private information.
