### ISSUE TITLE
[World] Rollback Request

### ISSUE THREAD

**Issue by freatrd** [EarthMC/Issue-Tracker#807]
**Describe the issue**
Where my town is, there is an old town right next to it. It has walls and everything, and I want a rollback on it, not including my claimed chunks.

**Coordinates**
2700 65 -7200

**Screenshots**
=====
![Untitled](https://user-images.githubusercontent.com/48654158/67152503-c62eeb00-f2a5-11e9-8f1b-9f531a7b8c29.png)

**Comment by JC488** [comment]
Please join EMC support discord for grief rollback:
https://discord.gg/ZsPQvBx

**Comment by JC488** [comment]
As the github issue tracker is only for suggestion and bus

**Comment by DasCodes** [comment]
Read the above comments.

**Comment by riri2010** [comment]
hey I know this place, that was the first town I joined on emc, Calabria. I build my first house there and met some great friends. are you sure you want mods the rollback the terrain? that town is a piece of earthmc history and it would be really sad to see it go.
