### ISSUE TITLE
[Feature] Allow /t spawn for towns with 30 players or more.

### ISSUE THREAD

**Issue by gabbobler** [EarthMC/Issue-Tracker#808]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
I would for there to be /t spawn enabled for everyone to spawn in if a town has 30 players or more. This means that instead of doing /n spawn to go to a nation's spawn and not being able to spawn in a town that you're not apart of, you would instead be able to spawn in a town even if youre not apart of it. This makes sense because a town that has 30 players or more is considered a city. If a town has less than 30 people it will not be able to be spawned in by the public. I think this is a very good idea because it can enable some towns to be successful in the server without being close to the nations spawn. It can also ease up with the messy ice roads all around the server.

**Comment by DasCodes** [comment]
We don't want to enable public /t spawn.

**Comment by T0rn4do** [comment]
oof
