### ISSUE TITLE
Petition to remove /n spawn to ally nations, and inn plots

### ISSUE THREAD

**Issue by creatorfromhell** [EarthMC/Issue-Tracker#81]
This feature has proving to be OP in the grand scheme of transportation, and really just leaves it open to players who wish to not expand upon transportation. I believe that inn plots should be removed too as they enable players to fast travel across the world without transportation.

**Comment by creatorfromhell** [comment]
I think being able to tp across the world is fairly OP, no?

**Comment by Synargle** [comment]
Well, I for one find fast travel favourable and I'm sure I speak for a certain number of players as well.

I know it is OP. That is why I'm suggesting to make it cost gold to dissuade players.

**Comment by Synargle** [comment]
You could think of it like paying gold to take a plane.

**Comment by creatorfromhell** [comment]
I think it'll be fine once elytras are available

**Comment by Synargle** [comment]
Well, I just happen to disagree with removing it entirely.

**Comment by creatorfromhell** [comment]
I think if the cost was higher for it then it'd be fine, such as 20->32g per tp. Under that I think it's just too OP. Same with inn plots and being able to /res spawn across the world.

**Comment by Keennoo** [comment]
100% agree, will be better and more realistic. NO tping at all, no inn plots... just t spawn and n spawn. If we don't do it the whole purpose of removing /tp with be removed. Not only that but all nations would be allies to tp everywhere, removing any real drama.

**Comment by sharkfynn1012** [comment]
I’d disagree with removing it too. It takes long enough to get around as it is. The setting is optional too, if you want realism turn it off and don’t ally anyone that uses it. As is there will be a major dependence on rails, elytras boats and ice transportation.

**Comment by creatorfromhell** [comment]
Most people have made the assumption that rail systems like EMRails will be pay-to-use when they're just free-to-use rails. Just seems like there is no valid reason to go against this other than "I can't be asked to use a traditional form of transportation", such as boat, ice road, rail, or elytra when they get added into the mix.

**Comment by Synargle** [comment]
I agree with what sharkfynn is saying here.

Creator, if you really think allowing players to teleporting to allied nation capitals is "OP" then why aren't you calling for both /n spawn and /t spawn to be removed entirely.  By your logic, those commands can be arguably as OP as the feature you want removed. Perhaps you can see how mundane that sounds.

**Comment by creatorfromhell** [comment]
> I agree with what sharkfynn is saying here.
> 
> Creator, if you really think allowing players to teleporting to allied nation capitals is "OP" then why aren't you calling for both /n spawn and /t spawn to be removed entirely. By your logic, those commands can be arguably as OP as the feature you want removed. Perhaps you can see how mundane that sounds.

The nation capital -> town limit for one makes those two entirely different things. TPing from my town to my nation's capital which has to be within a certain range is different than TPing to a nation's capital, which is across the map.

**Comment by sharkfynn1012** [comment]
True, it is the lazy way out, however I don't want to have to walk/rail/boat/horse to a shop that is 30 min away four times in one day. That is so, so boring. Even if the rail system has entertainment like popcorn and a movie, I'd get tired of it and I'm sure that's not just me. If they are not ant will never be a pay to use rail system, more power to you.

**Comment by Synargle** [comment]
> The nation capital -> town limit for one makes those two entirely different things. TPing from my town to my nation's capital which has to be within a certain range is different than TPing to a nation's capital, which is across the map.

But you can teleport to your nation's capital from anywhere on the map. Isn't that a bit overpowered itself and within what you thinking of wanting to remove?

**Comment by creatorfromhell** [comment]
> > The nation capital -> town limit for one makes those two entirely different things. TPing from my town to my nation's capital which has to be within a certain range is different than TPing to a nation's capital, which is across the map.
> 
> But you can teleport to your nation's capital from anywhere on the map. Isn't that a bit overpowered itself and within what you thinking of wanting to remove?

Sure, but I'm not trying to completely slap everyone in the face, just slightly tune it. I'm looking at this as a whole where allowing players to use /n spawn, and /n spawn <ally> is OP together. In order to combat this we cut the OP function to half of its functionality. I.e. remove /n spawn <ally>

**Comment by Synargle** [comment]
> Sure, but I'm not trying to completely slap everyone in the face, just slightly tune it. I'm looking at this as a whole where allowing players to use /n spawn, and /n spawn is OP together. In order to combat this we cut the OP function to half of its functionality. I.e. remove /n spawn

But what you already suggest is a bit of a slap in the face. You just want to force people to use rails more but they're less likely because this feature exists. I'm sure the people who want to use rails like yourself will use them.

I don't think a kid is going to to want to spend an hour travelling from A to B when he could be doing something better. I think your idea discourages travel more than anything. Not to mention the lag that'll somehow drop them into the void when moving in a boat or a minecart.

**Comment by sharkfynn1012** [comment]
People are still going to use rails, even now. Without these changes I could still see myself using them, but I still stress that trade point. True that, how many towns/nations would just completely cut themselves off to become isolationist and only do trade and communicate with themselves.

**Comment by creatorfromhell** [comment]
> > Sure, but I'm not trying to completely slap everyone in the face, just slightly tune it. I'm looking at this as a whole where allowing players to use /n spawn, and /n spawn is OP together. In order to combat this we cut the OP function to half of its functionality. I.e. remove /n spawn
> 
> But what you already suggest is a bit of a slap in the face. You just want to force people to use rails more but they're less likely because this feature exists. I'm sure the people who want to use rails like yourself will use them.
> 
> I don't think a kid is going to to want to spend an hour travelling from A to B when he could be doing something better. I think your idea discourages travel more than anything. Not to mention the lag that'll somehow drop them into the void when moving in a boat or a minecart.

I don't want to force people to use rails at all, I find that laughable at best that is where the thought process went. Yes I started EMCRails, but ultimately I just want people to use more realistic forms of transportation; be it rails, boats, ice roads, elytra

**Comment by NigelFarage666** [comment]
Point of it is to make everything more realistic and ones who made towns in middle of nowhere should deal with consequences of that choice.
And by travelling with rails you will need at least in worst case 10 mins from,A to B.
Except if you wanna get from Alaska to Argentina which is kinda dumb. 
Again it's not about how fun it is to use Tails it's about realistic develop of things. 
And develop of regionalism.

**Comment by sharkfynn1012** [comment]
So what you are suggesting is that people shouldn’t go where they want to go, rather that they should go where they’d be close to other people. That’s just ruining the whole earth map concept. Someone may really want to go to Alaska, and not join an established nation but rather a smaller one. All that would do is make the big players larger. Worse case 10min a-b I’d like to see proof of that, and still the trade factor. People want to be able to do international trade, Britain can trade with say the USA. To do that you’d want teleportation rather than to catch a boat all the way there, or have to use a rail system which would probably take a bit over 10 minutes. Time is a very valuable thing, and without the removal of allied Tp it’s already something that you need to spend getting around your own nation. They’ve removed allied town teleportation a little while back, now you want to take it another step further? This is a debate over something amongst a couple of people, but what does everyone else think? It’s fine to smash away at the keyboard here but what about everyone else, is this what everyone wants, is what I want what others want. We should be speaking for what people want, and as such I’ll be conducting a survey on this.

**Comment by sharkfynn1012** [comment]
It’d also make things cost more and take longer. I’d be fine paying a shipping service but costs add up.

**Comment by BowShot118** [comment]
The Economy wouldn't exist.

**Comment by sharkfynn1012** [comment]
Well I hate to break this bubble but so far it seems as though 70-80% of people are against the idea, based on people surveyed of which there’s around 45.

**Comment by creatorfromhell** [comment]
Closing this as I no longer find it relevant, and would rather not get the notifications from it(am too lazy to modify my notifications).
