### ISSUE TITLE
Take away the Councillor unclaim option and let settler claim land

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#811]
As you all know, theres a big jump between trusted and councillor, and nothing is there to fill it, add to that that settler has no powers, and you can clearly see theres room for improvment, need another reason? Not long ago dukasv got all of his town unclaimed, and while its 100% dukasv's fault it just comes to show you the dangers here, councillor is such a useful rank, but 1 feature (the unclaim perm) is just taking all away, no1 is really using this anyway, so why even let any1 but the mayor do it.

**Comment by johnyuki** [comment]
This would have to be suggested to the Towny github page.

**Comment by DeadGlamour** [comment]
Admins can change/create ranks permission, if you want to read more, enjoy
https://github.com/TownyAdvanced/Towny/wiki/Towny-Permission-Nodes#town-nodes

**Comment by johnyuki** [comment]
Ahh very nice indeed. In that case, yes, it would be nice to add another rank or two to bridge the gaps.

**Comment by JaVolimKatarinu** [comment]
Err no? Those perm nodes are used in plugins like GroupManager or LuckPerms, which manages which perms do players have. You cant remove unclaim perm from Councillor rank. 
So this goes to Towny git, not here.

**Comment by KarlOfDuty** [comment]
No, we can edit towny perms as much as we want. The unclaim permission has been disabled and settlers can already claim.
