### ISSUE TITLE
I got banned for msging people

### ISSUE THREAD

**Issue by BasherEDF** [EarthMC/Issue-Tracker#812]
EarthMC

I got perma banned for msging new players "hi" "wanna join my town" never sent it to the same person twice and I got banned for it

Can I plz get unbanned

![image](https://user-images.githubusercontent.com/56851600/67251279-2a7fb500-f434-11e9-882a-04dd87b67302.png)

**Additional context**

**Comment by johnyuki** [comment]
Looks like you might have been banned by mistake during yesterday's spam bot wave. I looked at the chatlogs on Discord and you didn't seem to be spamming, but the logs don't show private messages - I assumine only admins can see the chatlogs for PMs too. Make a ticket on the support discord (see #info channel), and wait.

**Comment by KarlOfDuty** [comment]
The issue tracker is for technical issues, you can get support on the support server in discord.
