### ISSUE TITLE
Limit claim hiding

### ISSUE THREAD

**Issue by BommBap** [EarthMC/Issue-Tracker#814]
pvpers is so hard to fight people to death in this server,people just go claim then we cant do anything.
I think it should have a system that if someone is in a Combat,though he run to a claim,he can still be attacked.And some builders can still avoid fighting by never go out of claim.I know that it hard to have a war plugin,i think my idea is pretty good lmao.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by KarlOfDuty** [comment]
Players should have the freedom to decide if they want to fight or not, players shouldn't have to be afraid to take a step outside of their borders when they are just building or something.
