### ISSUE TITLE
[Feature] Cuboid plots

### ISSUE THREAD

**Issue by defvs** [EarthMC/Issue-Tracker#815]
We currently only can sell / give a full chunk as a plot. This doesn't give any flexibility at all.

My request would be to implement a secondary plot system that allows for cuboids. That could allow more flexible towns with smaller plots, or "flats" with plots one above each other which is not currently possible.

My town of Naryn is a bit stuck because of that, we intended to build a huge "cave" themed city vertically because of our position in the himalayan mountains. We can't secure one chunk for multiple residents as this would lead to chaos.

Second possibility, reduce Towny's "plot size" from 16x16x256 to 16x16x16 for coherent chunk-based houses and possibility of building towers / floors.

**Comment by T0rn4do** [comment]
This is a feature for the towny plugin and not EarthMc.

**Comment by defvs** [comment]
Proof that you didn't read correctly. towny plot size is configurable in config file.

**Comment by JaVolimKatarinu** [comment]
And if you @defvs read it, you would see that dev explained why is it very bad move to do it after the plots have been made.
Configuring plot size after the plots have been created will lead to the change of size of current plots. Tldr, if you built some building with a size of 32x18, and configure plot size to 8x8, you would have 2 columns not claimed and possible to grief. 
Or if you have several plots with custom perms for residents and you change the size, first you would have to make perms again second, maybe other parts of towns and even buildings will be accessible and you maybe don't want that.

**Comment by defvs** [comment]
sure, it would need a workaround.

**Comment by shirazmatas** [comment]
town plots can't be changed on y-level basis, only on x and z, where x=z always. requesting to change plot size would drastically change all current plots on earthmc.

**Comment by KarlOfDuty** [comment]
Closed as per the previous posts here.
