### ISSUE TITLE
[Feature] remove gapples from votecrates

### ISSUE THREAD

**Issue by ogxn** [EarthMC/Issue-Tracker#816]
**Is your feature request related to a problem? Please describe.**
It hurts me when I get a golden apple that no one will buy from a vote crate. There goes any luck of getting a sustainable income from vote crates.

**Describe the solution you'd like**
I think the chance of getting a golden apple should be nonexistent.

**Additional context**
What am I supposed to do with an apple and 2g?  I'm going bankrupt!
![image](https://user-images.githubusercontent.com/41548573/67521595-360fed80-f679-11e9-946c-bc38067c4755.png)

**Comment by ImperialFishy** [comment]
Unluckyyyyyyy. Maybe you shouldnt live off social grants ¯\_(ツ)_/¯

**Comment by shirazmatas** [comment]
One golden apple requires 8 gold ingot to make, which is more than the 5 gold you used to gain per vote. you should be able to at least fetch 6 gold for it. If people agree or disagree with you they can use the emojis on your suggestion

**Comment by KarlOfDuty** [comment]
As per shiraz post.
