### ISSUE TITLE
[Plugin] add an alcohol plugin

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#817]
Alcohol is a very liked thing in emc, so far so players even famed it using custom mcmmo potions, or even poison, and for a good reason, its fun and we all love partying, so while yes its not a war plugin or the end, but its something fun which could be easily added as potions are already a thing, I saw a lot of people enjoying stuff like that so imagine adding alcohol for real, it will be much bettet and a lot of fun.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by KarlOfDuty** [comment]
You can just use name tags and potions for this, no need to impact the server with new plugins.
