### ISSUE TITLE
[BUG] i went to france as i saw a sign that was buying sponges, i had my sponge in my invitory and i clicked it once then i was angry then spammed it then i went huh because it gave me another sponge, 2 sponges, hmmmm then i clicked the sign again and it bought from me

### ISSUE THREAD

**Issue by Uglyspider** [EarthMC/Issue-Tracker#818]
**Server**
Which server the bug is on.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shirazmatas** [comment]
Please also fill in the spots instead of making the title be the whole description

**Comment by KarlOfDuty** [comment]
As shiraz said.
