### ISSUE TITLE
Create a command to allow access to the end

### ISSUE THREAD

**Issue by taytaytorro** [EarthMC/Issue-Tracker#819]
If possible there should be a command to allow access to the end. To make it so there isn't issues with the spawn island for the end getting griefed you could have it set up so killing mobs and using ender pearls are the only things allowed. This would lead to many new item being brought into the economy including shulker boxes and elytras.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by KarlOfDuty** [comment]
We will not be adding the end at this time, both for performance and storage issues.
