### ISSUE TITLE
[World] Replaced dirt with sand.

### ISSUE THREAD

**Issue by Wextra** [EarthMC/Issue-Tracker#82]
So, there used to be no sand at all under my town and only dirt, but when some designer changed the bottom of the lakes/oceans/seas or whatever, it changed the underground of my town too, so I have a lot of sand where there used to be dirt now. My town's coords are -14280 and -7320.

**Comment by PoppyK** [comment]
@Wextra, has this been done yet?

**Comment by KarlOfDuty** [comment]
Closed due to inactivity.

**Comment by PoppyK** [comment]
Wextra msg'd me.  This hasnt' been done as of yet.  Reopening.

**Comment by shirazmatas** [comment]
Closed, wextra moved it prob fixed
