### ISSUE TITLE
[Feature] Emc is getting too borring 

### ISSUE THREAD

**Issue by T0rn4do** [EarthMC/Issue-Tracker#820]
**Is your feature request related to a problem? Please describe.**
In my town and my nation, I got some projects:

-a Bigger Shop
-Houses for new residents
-redstone farms

That's cool, but when I ll finish these projects, maybe I ll get some new ones but **emc will surely get more boring** and will be the same thing over and over.

**Describe the solution you'd like**
**So I purpose some ideas for emc** (this is only my point of view tho)

-A War plugin, so nations could fight eachothers.
-Events, like a PvP event maybe Parkour or building  event and even quests.
_-1st november's update (dungeons) shhh_
-End Portal research maybe 🤔

**Additional context**
I think it could be really cool for emc, so players will not be getting so much borred and will be more active on emc.

Tell me what do you think about that and purpose your ideas in the comments.

**Comment by GazerBazer** [comment]
I think we need end portals

**Comment by Noahjohnminer** [comment]
In my opinion, If you think its getting to boring, just leave.
Not leave the server, but make someone else leader of your nation, leader of your town, then start from scratch somewhere else

**Comment by DeadGlamour** [comment]
1. Sadly they said they are not going to add it, idk why, would be nice if theyd explain.
2. Yeah that could be cool, bonus point if it relates to normal gameplay and benefits it.
3.still waiting lol.
4. They dont want us to have elytras, prob due to lag, and they dont want us to have shulker boxes, prob due to dupes, idk why not adding a custom end tho, with like rich deposits and chorus fruit.

**Comment by T0rn4do** [comment]
>     1. Sadly they said they are not going to add it, idk why, would be nice if theyd explain.
> 
>     2. Yeah that could be cool, bonus point if it relates to normal gameplay and benefits it.
>        3.still waiting lol.
> 
>     3. They dont want us to have elytras, prob due to lag, and they dont want us to have shulker boxes, prob due to dupes, idk why not adding a custom end tho, with like rich deposits and chorus fruit.

@DeadGlamour You're totally right on all of the points,
But an access to the end would be great for purpur blocks and additionnal gameplay like an ender dragon battle event....

**Comment by oreotoast** [comment]
No war plugin.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by T0rn4do** [comment]
@shirazmatas Done
Bruh

**Comment by shirazmatas** [comment]
Good work dude. now to each suggestion

> A War plugin, so nations could fight eachothers.
Karl and fix have no interest in spending time to code a war plugin, and as it's just something they do for fun, another plugin developer has to be found and given a solid 100% working gameplay idea.

> -Events, like a PvP event maybe Parkour or building event and even quests.
We had subreddit events before, and an attempted (succesful?) Olympic games. Anyone can suggest in-game events like PvP or whatevs to the reddit publicly, me privately, on the discord or with fix and karl. 

Quests would need to find an already existing plugin (if you can) or have a solid design.

> 1st november's update (dungeons) shhh
pls @FixTheAdmin 

>  -End Portal research maybe 🤔
also suggested this to Fix. no response

**Comment by T0rn4do** [comment]
Ok.
So I found this plugin could be fine for a server like EarthMC :
https://www.spigotmc.org/resources/quests.3711/

**Comment by KarlOfDuty** [comment]
Shiraz' post sums this up pretty well, we will likely not add any major plugins in the near future in any case.
