### ISSUE TITLE
[plugin] /n help

### ISSUE THREAD

**Issue by rainbowssdoggo** [EarthMC/Issue-Tracker#821]
Its a struggle for inexperienced and experienced players as nation commands are very vague, and unavailable on display in-game. 
It frustrates me that such a late-game feature with over a 1000 gold doesn't have a help section so you can make informative decisions on whether your going to make such a purchase. I was looking forward to later converting the capital of my nation later in-game however i couldn't even see if there was a command for this or what options were available to me. I found myself wasting over 1000 gold because of the unclear plugin capability
I suggest we create a /n help . Where all the nation commands can be listed for easy accessibility rather than limiting the games features and creating a situation where nation commands don't have to be self-researched an limited to those with experience. Such an expensive feature should be clearly laid out to avoid frustration and uneducated decisions.
I would recommend formatting this with the /t help however EMC is a great server and would love to see the idea and plugins advance in future updates :D

**Comment by JaVolimKatarinu** [comment]
/t mayor ?
/n king ?
Gives you all possible commands if you are Mayor/King.. ;)

**Comment by rainbowssdoggo** [comment]
okay thanks, was unaware of this feature :/
