### ISSUE TITLE
[mechanic] adding multiple resident to one plot and /lock within that

### ISSUE THREAD

**Issue by rainbowssdoggo** [EarthMC/Issue-Tracker#822]
Lack of space can be a big issue for small nations like Hawaii / Honolulu and densely populated areas.
However its frustrating because its difficult to replicate this when each resident needs 16 x 16 x Infinite plots. If we could create a feature in which residents can share plots so apartment blocks and city life can be replicated so EMC's realism and advanced concepts can be taken to a much more advanced level.  Without this feature i just feel like the realism of creating cities and densely populated areas is somewhat lacking.

I suggest a simple command tbh i'm not sure how it would work since i don't work on content personally
Additionally i would suggest a personal lock feature withing shared plots to allow players to protect there items from other apartment members otherwise it'd be somewhat annoying.

Thank-you for reading, just a thought :D

**Comment by shirazmatas** [comment]
Multiple resident can be on same plot if the plot owner does /resident friend add (name) but that will apply to all owned plots of that resident.

If you wish to suggest features to the towny plugin you may do so in the towny github:https://github.com/TownyAdvanced/Towny/issues?q=is%3Aopen+is%3Aissue

Lock command can be suggested in a issue following template for mechanic suggestions

**Comment by KarlOfDuty** [comment]
You will have to bring this to the towny developers, this isn't something that is currently possible outside of the solution shiraz gave.
