### ISSUE TITLE
Can't invite towns even though I have colonist rank

### ISSUE THREAD

**Issue by Max-FI** [EarthMC/Issue-Tracker#823]
**Server**
Towny

I have colonist rank in my nation and when I try to invite a town, the invite shows to me as normal but the invite doesn't show up to the person who receives it.  When they try to accept the invite, the plugin says they don't have any invites.

**Comment by JaVolimKatarinu** [comment]
Are you issuing invite while they are offline? 
Try /n invite -town_name and try reinvite them again, while they are online.

**Comment by Max-FI** [comment]
In the case which I described here, I invited their town when they were online and it didn't work.

**Comment by shirazmatas** [comment]
Please follow format

**Comment by Max-FI** [comment]
Well, now the problem is solved since I successfully invited a town and they joined.
