### ISSUE TITLE
[Feature] To be able to buy claims in the EarthMC store

### ISSUE THREAD

**Issue by Darkovid1** [EarthMC/Issue-Tracker#826]
Hi,
It is more and more difficult to get new players active (even more so when we are foreigners) and inactivity makes the person leave the town. For cities specializing in builds, there is a significant lack of claims.
So I was wondering if a possibility of putting paid claims in the EarthMC store would be a good idea for towns that are unable to recruit.
Of course, we could not exceed the authorized limit with players, so as not to favour the towns too much. and that would create a revenue stream for the server.

Ayame

**Comment by shirazmatas** [comment]
P2W features are not allowed ethically and according to TOS on the minecraft server
