### ISSUE TITLE
[Bug] T join issue 

### ISSUE THREAD

**Issue by amirmin** [EarthMC/Issue-Tracker#827]
**Server**
Which server the bug is on.

**Describe the bug**
A clear and concise description of what the bug is. I cannot join to town by typing /t join command. It writes:u don't have enough perms to do it. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shirazmatas** [comment]
Please Use format @amirmin or your issue will get closed

**Comment by KarlOfDuty** [comment]
Tell the mayor to /t add you.
