### ISSUE TITLE
[BUG] Lighting glitch

### ISSUE THREAD

**Issue by imabritishcow** [EarthMC/Issue-Tracker#828]
**Server**
Towny

**Describe the bug**
After removing blocks under torches, the light source still stays. I have tried F3 + T

**To Reproduce**
1. Place a torch
2. Destroy the block under it

**Screenshots**
![image](https://user-images.githubusercontent.com/49381066/68519922-23450d80-0262-11ea-8015-95b569d3f28a.png)
![image](https://user-images.githubusercontent.com/49381066/68519930-2cce7580-0262-11ea-8157-bff3699fa3e9.png)

**Comment by shirazmatas** [comment]
DId the problem remain after rejoining?

**Comment by imabritishcow** [comment]
Yes. I also noticed it only happens if i use haste or super breaker on the blocks

**Comment by KarlOfDuty** [comment]
It's an old minecraft server bug that got a lot worse in 1.13, it isn't really something we can solve sadly.
