### ISSUE TITLE
[Feature] Let us have elytras, but only for donators / nation leaders.

### ISSUE THREAD

**Issue by UnbatedAura** [EarthMC/Issue-Tracker#829]
I have been wanting elytras since I first joined, and it seems like we may never have them. So here's my proposal: Let us be able to get elytras, but limit them to donators or nation leaders. Add a sort of /warp, maybe, restricted only to certain people, a /warp that leads to the end. Restrict the world border of the end to a select area, so that not too many elytras can be obtained. My recommendation would be about 10000x10000. This should give the first few people who learn about it the chance to *earn* an elytra. I really hope to see this added.

**Comment by DeadGlamour** [comment]
1.I dont think Mojang allows such an unfair advantage for donors.
2. Doing it so only nation leaders have access gives just another reason to create a nation, and I think we can all agree we dont want even more of those.

**Comment by Pengun78** [comment]
Bruh chunks barely load ur gonna just fall all the time cuz ur in unloaded chunks

**Comment by shirazmatas** [comment]
Please use format provided

**Comment by riri2010** [comment]
in my opinion players should be able to win elytras and shulker boxes from the vote crates. then they can be distributed through sale and the mods can easily control the amount of elytras by changing the vote crate.

**Comment by KarlOfDuty** [comment]
Adding elytras would likely cause a lot of lag on the server due to the large amount of chunks that would be rapidly loaded frequently. Perhaps at some point in the future but not at this time.
