### ISSUE TITLE
Plots become susceptible to grief in public towns when residents leave

### ISSUE THREAD

**Issue by TheLoneSperm** [EarthMC/Issue-Tracker#832]
**Server**
EarthMC Towny

**Describe the bug**
When residents of a sold plot leave the town or are kicked due to inactivity, the plot goes back to being for sale. If your town is "public" anyone is able to join, buy the plot, and grief/steal anything in that plot.

**To Reproduce**
1. Set town to public.
2. Give a new town resident a free plot.
3. Have the new town resident leave the town.
4. Plot is still set to "for sale" for 0 gold. 

If it is possible, I think plots should go back to being "not for sale" when a resident leaves the town.

**Comment by shirazmatas** [comment]
It's a mechanic that towny added intentionally as usually you sell the plots for a value. This should be brought up with the towny creator on their github:https://github.com/TownyAdvanced/Towny/issues
