### ISSUE TITLE
BUG, Mob despawning

### ISSUE THREAD

**Issue by MCPBuilderguy** [EarthMC/Issue-Tracker#833]
**Server**
Which server the bug is on.
Earth.MC
**Describe the bug**
Ride-able mobs despawning
**To Reproduce**
1. (how it happen to me) Get on a horse
2. Click a chest
3. Mob disappears

**Expected behavior**
I was on a journey to my base with a skeleton horse I found in the woods. On my way I stumbled upon a town. I clicked a chest to see if it was in their town, & my horse de-spawned as soon as I clicked it. I was still on my horse & I want to know If there is a way to role this back.
**Screenshots**
https://user-images.githubusercontent.com/57657611/68651380-192e4380-04dc-11ea-9a2a-78f0ba9717c3.png

*I'd like to get my horse back, since it didn't die or get greifed by any other players*

**Comment by KarlOfDuty** [comment]
Mobs despawning is just something that happens in minecraft, it is not something we consider a bug which we can solve.
