### ISSUE TITLE
Custom Food Recipes

### ISSUE THREAD

**Issue by xCptSpiffyx** [EarthMC/Issue-Tracker#834]
Wondering if it'd be possible to add custom food recipes as it'd be great for an extra level of roleplay to the server as well as opening up another route for the servers economy as food can easily be mass produced on the server and would also add some realism to the game. 

Depending on the nation it could add a lot. Depending on the plugin and recipes you could add stuff associated a lot with certain countries/ regions like rice and Teriyaki for east asian countries, tiramisu, pasta, cottage pie for europe and stuff like apple pie and hamburgers for America. 

It'd also be very good for holdiays like Halloween and Christmas as again depending on the plugin used you can have candy bars, christmas pudding and many other foods. 

I think this would be a great addition to the server.

**Comment by LemonPickles** [comment]
That would be difficult to implement without interfering with EarthMC's mostly vanilla gameplay. I don't think the server would benefit from this and I don't think it matches with other elements of the server.

**Comment by shirazmatas** [comment]
it would just be renamed items with different properties. texture would be the same

**Comment by KarlOfDuty** [comment]
@LemonPickles put it very well and we do not wish to add a bunch of custom items for the reasons they described.
