### ISSUE TITLE
[Feature] Increase claim limit with gold

### ISSUE THREAD

**Issue by imabritishcow** [EarthMC/Issue-Tracker#835]
**Is your feature request related to a problem? Please describe.**
Sometimes you cant invite players to your town for reasons and your nation bonus isnt enough so there is no way to expand and get members if i cant claim

**Describe the solution you'd like**
I want to be able to buy claims for like 16-32G/chunk

**Comment by Aitonater** [comment]
You shouldn't be in a position where you don't have enough plots to support inviting new residents. It's possible you have too many town plots dedicated to community or personal areas. For example my town has 40 something residents and my claim limit is about 500 or so, if you mean to tell me you have so disproportionately claimed land and used it for something other than housing and roads then WHAT THE HELL HAVE YOU BEEN USING THE LAND FOR. So say if I have 40 residents and 40 houses and that then requires a road which is 20 chunks long to connect all the houses on either side of this long road. I would still have 440 chunks left of town space. This is stupid just plan your town design better. Part of the balancing act of what makes towny fun is your ability as a mayor to recruit and retain new players to your town to increase your town claim limit. If you allow players to just increase the size of their town with no residents you will end up with lots of giant one man towns with no population.
