### ISSUE TITLE
My Grievances Regarding DocW (The_Doctor)

### ISSUE THREAD

**Issue by Judemeiser** [EarthMC/Issue-Tracker#836]
DocW, as many of my fellow players can agree, is known for being very agressive & unpredictable regarding important issues such as land claiming and town/nation names. In adittion, DocW is also known for having a short temper and lack of ability to communicate effectively when talking with alleged rulebreakers. DocW has also been observed banning players for vague reasons and/or reasons that aren't against the rules, such as closing a ticket. 

![20191117_161903](https://user-images.githubusercontent.com/57871146/69014231-27ee7d80-0956-11ea-86c3-dbfd7377f53b.jpg)

Many of DocW's actions have been reversed such as the renaming of the town, "Dildo" because it was found that the town's didn't break any of the rules. This shows a lack of understanding EMC's rules.

![20191117_162317](https://user-images.githubusercontent.com/57871146/69014285-9fbca800-0956-11ea-94cb-89cc525f233a.jpg)

DocW wrongfully saying hollow claims are against the rules (ticket 03874): 
![20191117_171933](https://user-images.githubusercontent.com/57871146/69015092-b7982a00-095e-11ea-89a7-20afb8b3a986.jpg)

Today and in the last few days, it is in my opinion that they have crossed the line. Therefore, I have chosen to voice my opinions on this github, hoping I can draw support in order to create change that would benifit the players and the staff team. I have never, in my over 10 months of being on Terra Nova, encountered something so unreasonable to create a github regariding the issue.

Today, DocW completely disregarded the rules by not only completely removing Aceshooter's town (Yes, every chunk of it) for allegedly claimblocking even though its neighbors agreed with it, DocW also ordered a "restraining order ", the likes of which I have never seen before on EMC, against Aceshooter when he was peacefully protesting in Laniebell's town, Dorchester. 

![20191117_161529](https://user-images.githubusercontent.com/57871146/69014179-9848cf00-0955-11ea-8cef-a728b68ed552.jpg)

![20191117_161020](https://user-images.githubusercontent.com/57871146/69014122-ddb8cc80-0954-11ea-9084-407de2b9e15f.jpg)

Proof DocW was aware of DC's claims 7 days before Doc decided to remove all it's chunks (ticket 04133): 
![20191117_170551](https://user-images.githubusercontent.com/57871146/69014912-deedf780-095c-11ea-9e65-613f4ea89fdc.jpg)

Time and time again, I have watched as EarthMC's admins continue to justify DocW's actions despite major pushback from the playerbase. I think it is time for the admins to sit down with DocW and adress the concerns revolving around them in the EMC community which I have listed above. I also think the extreme vagueness of the staff punishments should be clarified for the playerbase. Thank you.

Edit: I have attatched a message from Barbay regarding the DC unclaiming and also some screenshots of Aceshooter's ticket to justify my allegations of DocW's short temperedness and lack of effective communication skills.

2nd Edit: Here is a screenshot of a github ticket in which the github writer voices his complaints about DocW's unprofessional & insensitive handling of a ticket, evidence for my allegations of Doc's lack of effective communication when dealing with alleged rulebreakers. 
![20191117_162555](https://user-images.githubusercontent.com/57871146/69014355-6f293e00-0957-11ea-8e16-a79229262240.jpg)
Edit 3: Even more screenshots to proove points stated above: 
![20191117_170114](https://user-images.githubusercontent.com/57871146/69014819-35a70180-095c-11ea-9581-076139bdb574.jpg)

**Comment by Ra2orLeaf** [comment]
I agree with this post, Doc has constantly been making new rules to ban people and has a short temper. I think atm Karl and Fix have kinda been ignoring this and assuming he’s doing fine rather than actually acting on what the community are saying and at least checking out if he’s been bending or making server rules. Given his logic with Aceshooter’s town New York or Newark should have all the chunks deleted which fairly obviously shouldn’t happen.

**Comment by DoctorSnakes** [comment]
I think the fault is with the rules and leadership. The rules are in some cases very imprecise, such as the toxicity rule. Depending on who you ask, anything can be perceived as toxic. These rules have to be changed and made more precise so that it's harder for abuse of power to happen. Secondly, the problem lies with the leadership. We are supposed to report abusive mods directly to Fix/Karl, but they are very often busy, especially Fix. They should get some people that they trust to handle the community, including the moderators. If these two things can be fixed then I think this situation can be avoided in the future.

**Comment by Judemeiser** [comment]
Additional info on DocW (presented by @Spiffles#3796 via discord)

(inconsistent enforcement of rules + going against the main consensus of the rest of the staff team regarding claim blocking issues)

![Screen Shot 2019-11-17 at 7 09 08 PM](https://user-images.githubusercontent.com/57871146/69016627-f4b7e880-096d-11ea-814c-4d9048f34e1b.png)
![Screen Shot 2019-11-17 at 7 09 20 PM](https://user-images.githubusercontent.com/57871146/69016628-f8e40600-096d-11ea-81be-1fbed48ecd76.png)

**Comment by KarlOfDuty** [comment]
The issue tracker is for technical issues, this is for the Discord support server.
