### ISSUE TITLE
[Feature] Reduce the number of inactive nations

### ISSUE THREAD

**Issue by Koriandah** [EarthMC/Issue-Tracker#837]
**Problem:**

Currently on EarthMC there are more than 270 nations. Around 15 of those at the time of writing consist of 1 man and 1 town. This is far too many, as some of them simply take up space with their owners logging in once a month just to keep their town alive and not do anything else. In my opinion, this is clearly a problem. 

One of the examples of this behaviour is the leader of Venice, jabesb2. He just logs in once a month keeping his town alive. This has been going on for months now (Since the end of March), with not a single block being changed. The town is just there, taking up space of a beautiful city with so much potential. The nation of Rome is just sitting there in Venice, for no other reason than out of spite, leaving the actual Rome with subpar naming choices for their nation. I mean, how is this fun for anyone? Why does this player who doesn't play get to hog land he doesn't deserve or do anything with? This needs to stop. 

![image](https://user-images.githubusercontent.com/47318364/69016876-c29e9900-09f6-11ea-8b78-9bb66b1e9546.png)

This is a significant issue because it keeps other players, who are active and motivated, from making their own town/nation/community. These players are instead forced into making nation clones that are far from their IRL location or simply are forced to move to areas like Siberia where there is nothing to do. Even worse, sometimes those nations are kept by alt accounts or "siblings" who just deny new players the opportunity to make their own nation.

I will propose several solutions I came up with, however if anyone has any ideas, mods or otherwise, feel free to say them below. 

**Solutions:**

First, the softer option:
Implement a mandatory nation upkeep. This was a feature on EMC Classic and at first it was sort of nice not to have it as a feature. However, now that most active people can afford it, it's time for it to be added again so that the inactive nations are purged. It will be extremelly simple for a nation with many players to just deposit, say, 20G per week (Ammounts are up to Admins to decide) into their nation bank but much harder for a player who is by himself holding a nation and a town. Yes, this might prove unpopular with some, but it will purge the inactives and free up land, making the map seem freer-er and less used. 

Second, the harder option:
Set a hard player floor to the nations. For example, say that a nation needs to have at least 20 or so players in order for it to exist, so that City-States are still possible but not to the point where gangs of 3 or so inactives can take up swathes of land in places like Europe where land is very sparse these days. And yes, the numbers are up to the admins, however I think that a limit of around 10-20 players should be fine for the vast majority of nations.

Third, perhaps mandatory:
Increase the price to create a nation. The nation price was raised up to 1000G once the server passed the 100 nation limit however such a decision was not made when it passed 200 nations. Now that we are nearing 300 nations on EMC, it might be time to double the price to make a nation up to 2000G or even higher. 

Finally I would just like to say: to any one-man nation leaders out there, if you guys wanted to build a town by yourself, just go to singleplayer. 

- End

**Comment by ImperialFishy** [comment]
Just linking this here #696

**Comment by Lagann311** [comment]
Has this been given a second thought, especially the part with nation / town taxes?
Most towny servers don‘t even have as many towns as emc has nations... Maybe there can be added a gold refundal whenever someone disbands there nation to promote the merging of tiny nations to a big one.

**Comment by Prismary** [comment]
The player minimum may be worth a thought, however I don't think there's plans to make changes like these anytime soon. Nation taxes are being discussed every now and then but have been rejected before (as seen in #696). Closing this for now.
