### ISSUE TITLE
[BUG] MCMMO Drops get pushed to the surface while mining/digging

### ISSUE THREAD

**Issue by vVertex** [EarthMC/Issue-Tracker#838]
**Server**
Which server the bug is on.
Factions, and Towny

**Describe the bug**
MCMMO double drops, and special percentage rate drops go into the ceiling and get pushed up to the surface.

**To Reproduce**
1. Minestone, ores, anything that gives double drops / special drops from dirt/sand/gravel rise as well. ie nametags, glowstone, diamonds
2. The double drops/items go into the ceiling if you don't preemptively mine out a space above the ores/dirt/gravel/sand.
3. Mine to the top to find the items have risen. 

**Expected behavior**
Expected items to drop on the floor instead of losing the items due to them rising to the surface.
**Screenshots**

**Additional context**
Can be an issue when trying to mine ores especially if you're close to bedrock.

**Comment by KarlOfDuty** [comment]
Not sure if this is something we can do anything about, we have been stuck on a specific mcMMO version as some of our plugins don't support their new API, so not sure if there is an update to solve it. In any case this cannot be fixed at this time.
