### ISSUE TITLE
[BUG] /t add problem

### ISSUE THREAD

**Issue by WeesnawNation** [EarthMC/Issue-Tracker#839]
**Server**
Towny

**Describe the bug**
when i try to invite someone to my town it sends a blank box and that the player's name is "invalid"

**To Reproduce**
1. do /t add (name)

**Expected behavior**
for it to say that i invited that person to my town

**Screenshots**
![image](https://user-images.githubusercontent.com/58280144/69772444-9650ee00-1155-11ea-8dd3-5e1a53186f15.png)

**Comment by JaVolimKatarinu** [comment]
Have you tried with /t invite <name> ?

**Comment by WeesnawNation** [comment]
> Have you tried with /t invite ?

yes i have and it still said the same thing

**Comment by KarlOfDuty** [comment]
Could you type out the exact command you used so I can search for it in the logs?

**Comment by WeesnawNation** [comment]
> Could you type out the exact command you used so I can search for it in the logs?

i did /t add (name) and /t invite (name)

**Comment by KarlOfDuty** [comment]
I know that, could you type it out?

**Comment by WeesnawNation** [comment]
> I know that, could you type it out?

ok i did it

**Comment by KarlOfDuty** [comment]
I mean here.

**Comment by KarlOfDuty** [comment]
Seems to be an issue of your town having sent out too many invites and that error message appears to be bugged. 
![image](https://user-images.githubusercontent.com/18099825/70100896-8f354e80-1633-11ea-8cc8-29fab4558d7a.png)
