### ISSUE TITLE
Server being full 24/7 (litterally) 

### ISSUE THREAD

**Issue by Colombusss** [EarthMC/Issue-Tracker#84]
**Describe the issue**
Not being able to join because the server being full 24/7 since the first hour when it opened. 
There are almost 400 people into the discord server, and the fact that only 100 can join the server at any moment is very miscalculated or maybe even made by purpose. 

I really hope this gets fixed once for all because I have been into (i think) 3 of your servers in the past and this problem was never a thing. I was always paying attention to people and the previous admins knew me very well.

PD: I havent been able to even see the world by myself as I have not found any moment in the past two days when i could log in. Please fix it guys.

**Comment by KarlOfDuty** [comment]
What do you suggest we do about it? Also 3 of our servers? We have only ever had one server before.

**Comment by KarlOfDuty** [comment]
Player limit will be increased to 120 in the near future.
