### ISSUE TITLE
Invitation to town

### ISSUE THREAD

**Issue by zerkillor** [EarthMC/Issue-Tracker#842]
hello it's been 3 days since I can not invite a member to my town on earthmc towny

I am making  /t invites [player] and /t add [player]
And the chat writes 
![JPEG_20191129_172856](https://user-images.githubusercontent.com/57627920/69882383-46e2fd00-12d0-11ea-90d5-0ecb9912cd92.jpg)

**Comment by KarlOfDuty** [comment]
Duplicate of #839
