### ISSUE TITLE
kick serv, bug serv, clear inventory ?

### ISSUE THREAD

**Issue by Z75064** [EarthMC/Issue-Tracker#846]
**Server**
Which server the bug is on.
**main serv Towny serv**

**Describe the bug**
**While I was in my inventory with an open chest. The server kicked me while I played. Once back on the server several players talked about a crash.
Returning to the server I lost several items
About 50 golds, 35 diamonds, 40 emerald, 50 iron bloc, 10 magma and 10 soul sand.
As well as other less important items.**

**To Reproduce**
**I do not know**

**Expected behavior**
**I did not expect to lose half of my inventory.**

**Screenshots**
**I did not have time to do a screenshoot**

**Additional context**
**Can you return my inventory or at least my 50 golds, 35 diamonds, 40 emerald, 50 iron bloc, 10 magma and 10 soul sand.
Thank you and have a good day

Sorry for my english i use google translate**

**Comment by T0rn4do** [comment]
Create a ticket on the support server : https://discord.gg/TTzZ8r

**Comment by Z75064** [comment]
But or on discord
I did -new but no one answers

**Comment by Z75064** [comment]
Bravo
On the site we say goes on discord.
And on discord goes to the site.
As no support possible, it is well done.

**Comment by DasCodes** [comment]
Always use the support discord when asking refunds. We have over 300+ tickets all the time hence it takes time to get a reply on every ticket. It doesn't mean we are ignoring.

**Comment by Z75064** [comment]
ok, but i have no answer either on discord. :(

**Comment by DasCodes** [comment]
> We have over 300+ tickets all the time

It takes time.

**Comment by Z75064** [comment]
And would it be possible to tell me if at least the ticket is well created because I do not see anything on my side.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/70675748-ad143c00-1c4f-11ea-80d4-e6b2de318c72.png)
ill give you this if you close the ticket

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/70676245-1e082380-1c51-11ea-8d32-30232e397ab9.png)

right here waiting for you

**Comment by Z75064** [comment]
Hi,
I did not have as many magma and soul sand.
But if you want me it suits me.
How do I get there?
The tp refuses all the time to work.
I still have a message that I am not allowed to use the tp :(
Is it far from Australia?

Thx

**Comment by Z75064** [comment]
![tp earthmc](https://user-images.githubusercontent.com/58528658/70721368-b6f07a80-1cf5-11ea-99ca-6bd90202ef7f.PNG)

**Comment by Z75064** [comment]
It s ok.
Thanks you

**Comment by Cactusinapumpkin** [comment]
:)

**Comment by Z75064** [comment]
Is there a wiki help to make tp spawn, because I can not, and I find no info :(
