### ISSUE TITLE
[Feature] Town Refunds

### ISSUE THREAD

**Issue by NintendoughYT** [EarthMC/Issue-Tracker#847]
**Is your feature request related to a problem? Please describe.**
A few days ago, I made a town. I accidentally made it in the wrong location, not knowing that I had enough gold on me at that moment. I did it to see how much more I needed. The town was created over 10000 blocks away from where I wanted it to be. I decided to just make do with what I had, and built a little house and expanded it a little. I hated the location, though, because I was so far away from my friends. I almost gave it away, but decided against it, because I wanted to see if anyone would buy it for any amount of gold. The greatest offer I have gotten has been 4 gold.

**Describe the solution you'd like**
I would like for there to be a command, like /town sell or /town refund, that would give all the gold you have put into the town back to you. It would also kick all members of the town and delete it from the map.
**Additional context**
I know a lot of people who have had the same problem I have and would really enjoy this new feature. Thanks for at least looking at my feature request!

**Comment by riri2010** [comment]
this is a good Idea exept for 2 problems I notice with it.

1: Emc staff can't add this feature unless the towny plugin already supports it.

2: this would make it too easy to move towns. there would less repercussions for claimblocking. 
someone with a large town could just up and move. 
imagine logging in and seeing a 100+ chunk town

**Comment by Aitonater** [comment]
This would be insane if you could get refunds for town claims and would create a whole pile of problems. There has to be consequences for where you decide to make a town. I.e. I would be able to take my 400 chunk town and more or less make a new 400 chunk town anywhere else I wanted in the world. People would claim fallen towns like this and towns would become mobile throughout the map if they could get refunds for chunks.

**Comment by KarlOfDuty** [comment]
As the previous comment suggested, we feel like being able to get the gold back from selling a town would ruin what is supposed to be a more permanent investment.
