### ISSUE TITLE
potential shop sign bug

### ISSUE THREAD

**Issue by wysx** [EarthMC/Issue-Tracker#848]
while testing out my shop to see if it worked, i purchased a stack of gunpowder for 3 gold with a full inventory, the gunpowder entered my inventory because i had several slots filled with 1 powder each. i had 64 gold when i started and only 61 gold after the transaction. the gold that i should have received upon the sale was not deposited into my full inventory, it is not in the chest with the powder from my store and it is not in my town funds. what happened to my missing 3 gold?

**Comment by JaVolimKatarinu** [comment]
Have you checked ender chest? And your /balance? If you bought your own plot, you should have received that gold. Otherwise, gold wouldnt move anywhere cause you bought your own plot.?

**Comment by wysx** [comment]
i have 3 gold in my balance, thank you
