### ISSUE TITLE
Duplicating gold

### ISSUE THREAD

**Issue by CapCreeperGR** [EarthMC/Issue-Tracker#849]
**Server**
Towny

**Describe the bug**
I can duplicate golf by putting 2 gold in a chest and then adding a sign shop to that chest and make it so 2 gold costs 1 gold

**To Reproduce**
1. Create a sign shop
2. Set the amount to 2
3. Set the price to 1
4. Buy the gold
5. Get dubbled gold

**Expected behavior**
Show an error and that it is not possible to sell gold

**Screenshots**
I am using my phone to make this issue report so I don't have screenshots

**Comment by T0rn4do** [comment]
Dude, just, no, cause if you sell 2 gold for 1 gold you'll pay 1 gold from your inventory or ender chest and you'll get 2 gold from the chest so you'll get also the gold you paid cause you are the seller so there is no duplication...
