### ISSUE TITLE
[BUG] Creeper's head and zombie's head have the normal skeleton's head design

### ISSUE THREAD

**Issue by shagone** [EarthMC/Issue-Tracker#850]
**Server**
Towny

**Describe the bug**
Creeper and zombie's head item are replaced by normal Skeleton's head when loot, but have is own item_ID and do no stack

**To Reproduce**
1. Take a fishing rod
2. Try to "fishing" a creeper or a zombie
3. Loot the head
4. See the error

**Expected behavior**
Loot the correct head

**Comment by T0rn4do** [comment]
Why would you fish a zombie or a creeper ?

**Comment by Cactusinapumpkin** [comment]
Shake
From fishing level 150 onwards, the player will be able to shake items loose from mobs by hooking them with the fishing pole.

Shake can be used repeatedly for a large number of items depending on the remaining health of the mob (Fishing Rod deals 1 damage to mobs). For instance, a Skeleton at full health can drop up to 37 arrows before they die.

**Comment by Cactusinapumpkin** [comment]
Creeper | 99% Gunpowder, 1% Creeper head

Zombie | 98% Rotten flesh, 2% Zombie Head

49% Bone, 49% Coal (1-3), 2% Wither Skeleton Skull
--




49% Bone, 49% Coal (1-3), 2% Wither Skeleton Skull
--



49% Bone, 49% Coal (1-3), 2% Wither Skeleton Skull
--



-- | --




Skeleton | 49% Bone, 49% Arrow (1-3) 2% Skeleton Skull
-- | --

**Comment by shagone** [comment]
Yes, but Creeper's head and zombie's head have the normal skeleton's head design

**Comment by KarlOfDuty** [comment]
Please put a title on your issue.

**Comment by shagone** [comment]
done :)

**Comment by DasCodes** [comment]
Tested on a creeper, it drops skeleton head.

**Comment by shagone** [comment]
it drop a skeleton's head, but it's not stacking with the skeleton's head from a true normal skeleton, so they have different ID but same name and look.
So I have 3 differents type of skeleton's head:
normal skeleton's head from normal skeleton
skeleton's head from creeper
skeleton's head from zombie
each one of these do not stack together

**Comment by Prismary** [comment]
Has been open forever by now, is this still a thing?
