### ISSUE TITLE
[BUG] /none clears nbt data

### ISSUE THREAD

**Issue by SvenPhillips** [EarthMC/Issue-Tracker#853]
**THIS BUG DOES NOT WORK ANYMORE**

Server:
Factions for sure, maybe others
The Bug: 
Doing /none clears the NBT data of the item you are holding, allowing you make glitched items, clear enchantments, and give tool full durability. 
To Reproduce:
Hold an item like an enchanted book, and do the command /none. This will clear all enchantments. You can also do this to make items to full durability. 
Expected behavior:
That this command wouldn't be available to players. 
Additional context:
It takes a couple of tries to clear NBT data.

You can make uncraftable potions with it.

**Comment by ogxn** [comment]
wow

**Comment by ogxn** [comment]
doesn't occur in towny

**Comment by SvenPhillips** [comment]
> doesn't occur in towny

I tested on a wood picaxe, and it worked on towny.
