### ISSUE TITLE
[Feature] German Channel

### ISSUE THREAD

**Issue by OldArmin** [EarthMC/Issue-Tracker#854]
I think because of the not few German players there should be an additional language channel for German, accessible by /ch join german. That's it.

**Comment by KarlOfDuty** [comment]
We have added language channels more because a majority of the players who speak those languages cannot speak english rather than there just being a lot of them on the server.

Is there really a need for a german channel? I feel like most germans can speak english to some degree.

**Comment by Cactusinapumpkin** [comment]
^^^

**Comment by Warriorrrr** [comment]
German chat now exists.
