### ISSUE TITLE
Make Rule 2.4 Punishments Less Harsh

### ISSUE THREAD

**Issue by laidang08** [EarthMC/Issue-Tracker#855]
I was banned on 2/4/2019 for going past 5 warnings on rule 2.4, even though the 5th was complete bull.
My point is that exceeding 5 warns should not result in a perm ban and should result in a very long mute on both discord and the game. Some people actually enjoy the server and sometimes cannot help themselves when saying racial words. Perm ban is a little too much for saying a word, especially if the chance of getting an appeal accepted is like 5%.

**Comment by DarkRush449** [comment]
You got 5 warnings lmao, what did you expect to happen?

**Comment by FutureLemon** [comment]
When you get 5 warnings you get a perm ban simple as that. Maybe you should've read up on the rules first https://earthmc.net/rules. You could always appeal your ban if you don't feel this is justified on the EMC Support discord https://discord.gg/k44FrKb. Other then that it's quite simple to just shut up after you get your first two warns it's not that hard to not harass people or start fights in chat to be honest.

**Comment by Aitonater** [comment]
No. It's not hard to not break the rules. Its actually very easy to play on the server without breaking any. If you can somehow manage to get 5 warnings you get everything you deserve for being banned. Even if you feel like the reasons why you recieved a warning were tedious just be more careful and don't aggravate the mods or do something that could be construed to be breaking a rule.

**Comment by laidang08** [comment]
> When you get 5 warnings you get a perm ban simple as that. Maybe you should've read up on the rules first https://earthmc.net/rules. You could always appeal your ban if you don't feel this is justified on the EMC Support discord https://discord.gg/k44FrKb. Other then that it's quite simple to just shut up after you get your first two warns it's not that hard to not harass people or start fights in chat to be honest.

I didn’t even harass anyone or start a fight.

**Comment by MineHero43** [comment]
I’ve been on this server for two years now, I’ve only been warned two times as far as I can remember. Five warnings is a lot and you’re expected to have learnt your lesson by your third warning if you haven’t already by then. It really isn’t hard to just play the server without getting any warnings though.

Tough luck mate

**Comment by laidang08** [comment]
> I’ve been on this server for two years now, I’ve only been warned two times as far as I can remember. Five warnings is a lot and you’re expected to have learnt your lesson by your third warning if you haven’t already before then. It really isn’t hard to just play the server without getting any warnings though.
> 
> Tough luck mate

I guess it is tough luck. There has been people that have gone past 5 warning that got unbanned.

**Comment by KarlOfDuty** [comment]
They already aren't very harsh as you just get a warning or a short mute for basically everything. If you wish to appeal your ban you may do so on the support server.
