### ISSUE TITLE
Haste II sign shops do NOT work

### ISSUE THREAD

**Issue by unkosamurai** [EarthMC/Issue-Tracker#856]
hey i own a potion shop and i noticed that you can't sell **working** haste II pots thru the sign shops. what i mean is that the haste II potions you buy thru the sign shops wont give any effect to the players. 

-i also believe this accounts for all of the mcmmo exclusive potions. just fyi.

**Comment by KarlOfDuty** [comment]
Yes, we know, there is no way to fix that.
