### ISSUE TITLE
Re-enable full sugarcane growth

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#857]
0 tick farms used to be a pain in the ass on EMC and that resulted in both cactus being disabled and sugarcane being limited to full growth. A long time ago cactus has been enabled yet, but sugarcane never was. 

Could the full growth of sugarcane be enabled again because 0 tick farms don't work on EMC anymore and the price of sugarcane keeps going up because it's fairly hard to farm now.

**Comment by Cactusinapumpkin** [comment]
There's no need for sugar cane to grow three high I'll show you

**Comment by Cactusinapumpkin** [comment]
Well my laptop pooped itself but basically replace the observers with blocks and put a redstone torch on the top block every 7 blocks. So when that row of seven gets two high the sugar cane will trigger the torch and push that row.

**Comment by Cactusinapumpkin** [comment]
If you wanna see mine. Closest nation spawn is Savoy.
![Screenshot_20191229-165356](https://user-images.githubusercontent.com/48000340/71563842-ee805600-2a5b-11ea-8799-0fa585507ef8.png)

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71567543-7dee2f00-2a85-11ea-80c7-b70cc1fe9ac5.png)

**Comment by jkmartindale** [comment]
I think it's back to three now
![image](https://user-images.githubusercontent.com/11380394/77815997-e351bc00-7084-11ea-9336-d4cd4bed4ff9.png)
