### ISSUE TITLE
Release EarthMC map to the public

### ISSUE THREAD

**Issue by Thatoneguy342** [EarthMC/Issue-Tracker#858]
**Describe the solution you'd like**
I want you guys to finally release the map to the public. I notice your map is bigger and better than a lot of other earth server's maps. By releasing it you could create competition to push your server to be the best. Also it could provide alternatives to those other stinky earth servers.

**Comment by JaVolimKatarinu** [comment]
Also, it would make those stinky earth servers steal our map..

**Comment by KarlOfDuty** [comment]
No, we will not do that.
