### ISSUE TITLE
Chunk  does not display

### ISSUE THREAD

**Issue by Dahtz** [EarthMC/Issue-Tracker#859]
Server Towny.

**Describe the bug**

He is no longer present. There is a big hole instead

It's quite problematic, especially since all players have the same thing.

**To Reproduce**
Come see it at /n spawn Greater_Russia
Pos: X8207 Y : 64 - Z -9126

**Screenshots**
![de23fr6z](https://user-images.githubusercontent.com/58906366/70862148-cdd2df00-1f38-11ea-93db-bd0ea66098cc.png)

Thank you for your future response.

**Comment by KarlOfDuty** [comment]
How long has this happened? Does it persist between server restarts?

**Comment by FutureLemon** [comment]
> How long has this happened? Does it persist between server restarts?

I usually see these happen around shops like Madagascar and Tesco in Britain. This is the shop of Greater_Russia and sometimes a re-log or everyone unloading the chunks works to fix it.

**Comment by Cactusinapumpkin** [comment]
rip

**Comment by Dahtz** [comment]
For now, there is no more problem 🙏

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Cactusinapumpkin** [comment]
Possibly removing some chest will help prevent it from coming back. I don't keep anything at my shop it is just signs. I have learned not to keep all my _eggs_ in one chunk as well

**Comment by Cactusinapumpkin** [comment]
![unknown](https://user-images.githubusercontent.com/48000340/71584489-5ffdea00-2ad8-11ea-825b-57c60eed5a30.png)
This is a picture of my donator head I had on the front of my shop all the chests, items, signs, ect. Turned invisible but kept the outline and erased all the chest items.

**Comment by Dahtz** [comment]
Bug come back ....

![f2r32g3tr](https://user-images.githubusercontent.com/58906366/71773258-708be580-2f5a-11ea-8a82-ebd4db00d1f7.png)

**Comment by JaVolimKatarinu** [comment]
Chunk didn't load correctly. You should leave the area around it for 10-15min until it gets unloaded and return after. After that, the chunk should load normally and it would be okay...
Not only you, everyone near should leave the area around the chunk...

**Comment by Dahtz** [comment]
Ok thank you
