### ISSUE TITLE
[World] Western Australia should be registered as a Savannah biome, not a desert. It already looks like a Savannah I don't know why it's registered as a desert.

### ISSUE THREAD

**Issue by goofytasha** [EarthMC/Issue-Tracker#86]
Please make the Southwestern part of Australia a savannah.

**Comment by Coffeetom** [comment]
Personally south West Australia should be Forest Biome, as it is irl,
However it is too late to change
So yeah make it a savvannah

**Comment by PoppyK** [comment]
This has been partially done but due to lag had to stop.  Will continue when time allows.

**Comment by PoppyK** [comment]
Continued again today but still in process.

**Comment by PoppyK** [comment]
https://i.gyazo.com/ba7602553f2d81b5bdf9cf0e7395773a.png This area was changed to a savannah biome.
