### ISSUE TITLE
Changing permissions on plot for residents does not work.

### ISSUE THREAD

**Issue by Aitonater** [EarthMC/Issue-Tracker#860]
Whenever I try to change the plot permissions to allow specifically residents to do something (i.e. Switch, Build, Destroy...) it does nothing. The permissions remain unchanged.

For example if the plot's perms are Switch:---
and I type:
 /plot set perm resident switch on
nothing changes 
the plot perms will still read instead
Switch:f--
It doesn't change  the correct permission, it allows friends to then have permission for the action but not residents.

This is basically the whole problem. Using the correct towny command specifically for resident permissions changes it for friends and not for residents.
I've tested this with build, switch and destroy.
The only way I've managed to get this to work is by changing the perm to ally to allow residents to build however this isn't the desired outcome incase allies betray you or take advantage of the low security etc...

**Comment by JaVolimKatarinu** [comment]
https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#towny-plot-perms
https://github.com/TownyAdvanced/Towny/wiki/Towny-Commands#plot
Have you read this? Might find something useful..

**Comment by Aitonater** [comment]
> https://github.com/TownyAdvanced/Towny/wiki/How-Towny-Works#towny-plot-perms
> https://github.com/TownyAdvanced/Towny/wiki/Towny-Commands#plot
> Have you read this? Might find something useful..

Yeah the command for allowing residents to switch/useitem/build/destroy does not work

**Comment by Cactusinapumpkin** [comment]
The perms only work for friends, allies, and outsiders. If u want your residents to use a switch you can enable allies. But that will also allow all allies of a nation. I built a six digit button combination lock and allowed switches so they would need the combination to open it.

**Comment by Cactusinapumpkin** [comment]
Also I just set plot fs 0 and they can plot claim it.
