### ISSUE TITLE
[Suggestion] Ender chest command for donators

### ISSUE THREAD

**Issue by taytaytorro** [EarthMC/Issue-Tracker#861]
Would yall ever be willing to add a plugin so donators can put in /echest to access their ender chest.

**Comment by FutureLemon** [comment]
That would be pay to win. I have been donator for over a year now and definitely don't think such command is needed. An alternative to this is just carrying an enderchest on you with a silk touch pickaxe.

**Comment by johnyuki** [comment]
Yeah as Future said, it would make resource gathering OP for donators. You could stay in your mine forever or go through a forest forever without ever having to go back until your echest was full.

**Comment by Aitonater** [comment]
Yeah this would be OP for combat. At least with the current way it's a lot harder to place your echest and dump your gear before you die but if it was as simple as typing a command it would become unfair.

**Comment by docwhomc** [comment]
That would be OP.
