### ISSUE TITLE
[Feature] Add flight ability as a donator perk

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#863]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Building large buildings is a real pain in survival mode, especially tall ones. Flight would allow people to enter flight mode just like creative, so that they can build stuff more easily. Flight mode could be activated via command such as "/fly enable" and "/fly disable". 

Flight mode could only be entered if they were in a claim that they owned, and have not taken damage for x amount of seconds. If they tried to fly in to a claim that they did not own (either someone elses claim or the wilderness), then they would be rubberbanded back. An easier solution would be to have it disable flight mode if they leave their claims, but this would cause issues with people accidentally dying from fall damage if they accidentally leave their claim. 

**Additional context**

Flight Mode would not give people access to creative mode - it would only allow them to fly around as if they were in creative.

**Comment by FutureLemon** [comment]
I love how EarthMC is as close to real life as possible with a lot of things and personally it would ruin the game if donators had flight. I also believe it's a very pay to win aspect.

**Comment by johnyuki** [comment]
I don't really see how it makes you "win"? It just lets you cut out some of the tediousness of building large buildings. You can't gain money from flying, you just get to build faster. Just like how you can buy priority/supporter to get ahead in the queue. It's just a time saver.

**Comment by DasCodes** [comment]
We will not add /fly for donors.
