### ISSUE TITLE
Add back normal sugar cane height, and add mobs like (pigs) being able to move with water current 

### ISSUE THREAD

**Issue by Skater2323** [EarthMC/Issue-Tracker#864]
Now that EMC is less laggy, I think its time to add back the more mainstream vanilla features that where causing a disturbance in the game play. Fix or Karl I am asking for you to re enable sugar cane height, the tree feller mcmmo feature, and mobs like pigs or other mobs to be able to flow with water current just like how it is on factions.
![2019-12-19_20 44 03](https://user-images.githubusercontent.com/50536485/71222984-71f1b880-22a0-11ea-8638-419cbf70e070.png)

**Comment by johnyuki** [comment]
Honestly I kinda prefer not having treefeller. It helps to keep the price of logs low because they are harder to collect. However I do agree with turning back on other features like animals moving bc apparently villagers don't breed anymore bc they can't move to each other in order to do so?

**Comment by FutureLemon** [comment]
> Honestly I kinda prefer not having treefeller. It helps to keep the price of logs low because they are harder to collect. However I do agree with turning back on other features like animals moving bc apparently villagers don't breed anymore bc they can't move to each other in order to do so?

Villagers do still move my breeder works fine it's just mobs from spawners such as blazes and pigs not moving.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71567765-133df300-2a87-11ea-9d20-b42229f3c422.png)

this is a modified two high auto sugar farm, it is very easy to convert your old three high to this. it also is less efficient but also less laggy.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71567839-a8d98280-2a87-11ea-8f25-3b0f6e0ce5f0.png)

and we dont talk about the piggys or bad things happen to the nether.

**Comment by Cactusinapumpkin** [comment]
but seriously do you need infinite pork chops because its not really "realistic", everyones main food source shouldnt be from the pig smelter. It was possibly removed not only because of lag issues but also making it more challenging to get food. I have fishermans diet and get 7 food mutton things each fish and is the best food source for me.

**Comment by KarlOfDuty** [comment]
This should be fixed now that we have switched server software.
