### ISSUE TITLE
[BUG] Votecrate Disappearing

### ISSUE THREAD

**Issue by Mafia-Cats** [EarthMC/Issue-Tracker#865]
**Server**
Towny

**Describe the bug**
I placed a #3 votecrate whilst in a foreign town and it vanished without giving me any gold.

**To Reproduce**
Steps to reproduce the behavior (I don't know if it is reproduceable):
1. Go to CR claim and accept a votecrate
2. Go to the nation spawn NWO
3. Place the crate

**Expected behavior**
I expected for the typical crate window to open and to receive gold

**Screenshots**
N/A.

**Additional context**
N/A

**Comment by johnyuki** [comment]
You don't need to place the crate. You can just right click the air with it. However if placing the crate makes it disappear then it definitely needs to be fixed.

**Comment by DasCodes** [comment]
Need more feedback.
