### ISSUE TITLE
Slow fall usebug

### ISSUE THREAD

**Issue by hydrolien** [EarthMC/Issue-Tracker#867]
**Server**
Faction

**Describe the bug**
If we have the weird jump of the 256 layer, we can use the slow fall potion to fly without falling.

**To Reproduce**
1. Go to 256 layer (in Y)
2. Drink a slow fall potion
3. Get the weird jump
4.. Fly whitout falling more than 1 bloc during 20 to 50 blocs.

**Expected behavior**
the strange property of the jump over layer 256 should be delet in faction serveur.

**Screenshots**
https://youtu.be/HPNiyuYtiVc

**Additional context**
This bug help people to raid some base 10 times more easly than whitout that.
You fix flying machine, great, can you also fix this flying usebug ?

**Comment by DasCodes** [comment]
Related #741.
