### ISSUE TITLE
[Suggestion] Make a new Towny server with a new map that works like Classic or Factions.

### ISSUE THREAD

**Issue by VonApollo** [EarthMC/Issue-Tracker#868]
I hope the admins could make a new server with towny with a completely new map, it would work like Factions or Classic. Terra Nova will not be affected.

Terra Nova has started to be boring and crowded, creating a new server would allow people who enjoy Terra Nova to continue playing, and people who don't to move on to one that they DO enjoy.

**Comment by johnyuki** [comment]
Yeah I would personally like to play EMC on a randomly generated map tbh. At least that way it isn't just a second TN server, and is actually different in some way.

**Comment by DeadGlamour** [comment]
Making it without an earth inspired map would take away from the entire point, also, just gonna leave that here:
https://github.com/EarthMC/Issue-Tracker/issues/840

**Comment by johnyuki** [comment]
There are already three Earth maps on the server though. Adding one that isn't Earth to freshen it up a bit wouldn't take away from the server at all as the other three maps will still be there.

**Comment by docwhomc** [comment]
1. We'd need another server.
2. There is plenty of space in Towny, it is only certain areas that are crowded.
