### ISSUE TITLE
[Suggestion] Heart Of Sea Votecrates

### ISSUE THREAD

**Issue by hazzawazza01** [EarthMC/Issue-Tracker#869]
Hey!
I'm a player who had a trident before votecrates were introduced, and understandably I was very frustrated when tridents were introduced in votecrates. With the amount of daily votes, the chances of a trident drop being 1:5000 as Fix had confirmed to me seem actually quite likely to happen a couple times per month. This devalues an extremely valuable item and takes away the exclusivity from it. Personally, I think this tradeoff of exclusivity should have a benefit of usability and usefulness. That's why I think that the heart of the sea should be introduced in votecrates. Think of it like this, that way, we could use nautilus shells with the heart of the sea in order to make a conduit and not make tridents weather reliant. This can make getting mob heads much easier with channelling, for example, or making valid underwater cities that actually have people living in a constant state of submergence. I think that the inclusion of heart of the sea in votecrates can really revive the image of tridents on the server as static, useless and expensive and bring back some value in terms of use to them. They could be used to farm mob heads with charged creepers, for example, if the heart of the sea was introduced. Furthermore, it would introduce another big player into the economy in terms of valuable items, being the conduit, that can add diversity to the currently very over-saturated and inflated economy. I feel that adding another item like this by making it more easily accessible, although perhaps not universal, would have benefits both for players, in terms of extra and new things you could do on the server, and act as a stabilising force for the economy. Furthermore, due to the performance issues of 1.15, this could be a way to give new meaning to using Minecraft in 1.13 without causing too many performance issues, like enabling the end would for example. Thank you for listening and I hope that this message finds you well and that you are intrigued by it.

Regards,

bunghoIe on EMC.

**Comment by Highlander214** [comment]
this idea could work, i will say the chances of getting a trident are still generally low, but i agree needless to say

**Comment by johnyuki** [comment]
Yeah Trident prices aren't going to be dropping any time soon. They're still incredibly rare. Also it feels a bit biased by saying that you don't want your rare item to be devalued. There are plenty of items that have been heavily devalued over the last 6 months or so, so your argument could be made for any one of them. 

I do agree with your heart of the sea thing though. However I think it should get an expensive custom crafting recipe so that they aren't too rare and down to chance. This would keep the price of making a conduit high, as you have to spend gold to make one, rather than being able to make one for free by getting lucky from voting and fishing, which would inevitably see the price of them drop over time. By giving it a recipe, the cost of conduits will remain high as very few people will want to sell the conduit for lower than it costs to make one.

**Comment by Cactusinapumpkin** [comment]
You still need 8 Nautilus shells to make a conduit. Nautilus shells are not a fishing item with mcmmo fishing.

**Comment by johnyuki** [comment]
> Nautilus shells are not a fishing item with mcmmo fishing.

That can, more than likely, be easily changed though. Fairly certain the mod comes with a config file that lets you set the drops and their droprates at each level.

**Comment by hazzawazza01** [comment]
I think that acquiring nautilus shells via fishing can be easily fixed, just as John Yuki said. The coding shouldn't pose any sort of problem, nor should it affect the lag or the performance of the server. Heart of the sea would be very useful and add another layer of complexity to the server that really fleshes out the Aquatic update, since it does not seem like we are getting another update in terms of 1.15 ANYTIME soon. Likely they will skip to 1.16 anyways on the server.  So I feel that it's necessary, especially with the lack of the end. There needs to be another sort of specialist addition to the aquatic world in EMC that connects it together and tethers it, rather than just having random fish and sometimes, although very rarely, finding a dolphin or two.
