### ISSUE TITLE
[Discussion] What should fix do to reduce the lag?

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#87]
Share your ideas here and comments to my ideas.
I currently have three ideas of how this can be reduced.
The first is mob stacking for any mob except villagers + pets + horses (and different colored sheeps)
The 2nd is splitting the world in two with north and south america as one "server" and europe asia and africa as another like how many servers have different hubs
the last one is reducing player count if funding is the issue and then increase it if more donate.

Furthermore if the issue is claiming lag then claiming land should be restricted for 2 occasions (15 minutes at 12:00 and 15 minutes at 24:00) so all lag happens then. If the issue is mcmmo then disable the abilities that cause lag

**Comment by KarlOfDuty** [comment]
1. Does not help too much. We used to do it before only lead to more issues.
2. Theoretically possible but would likely need server downtime for more than a week. Not something we will consider just yet.
3. We already have basically the best cpu we could get so that isn't really possible.

**Comment by TheGoatOnABoat** [comment]
-turn off hostile mobs and make a shop plugin for the loot
-remove mcmmo
-install clearlag

**Comment by KarlOfDuty** [comment]
1. Mobs are already off.
2. Why...?
3. That doesn't really help.

**Comment by MSatrokrm** [comment]
HASDHASUIF 
Removing mcmmo?
Are you crazy
