### ISSUE TITLE
Absorption

### ISSUE THREAD

**Issue by Dauvid** [EarthMC/Issue-Tracker#870]
Hello,
So basically, my absorption potions have 0 duration time on them please help

**Comment by Cactusinapumpkin** [comment]
Are you using splash potion? Usually if you dont break it on your head it could give you a lower duration.

**Comment by Cactusinapumpkin** [comment]
can you screenshot a picture of the potion stats?

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71774203-360d5300-2f30-11ea-9c7c-788d2833f829.png)

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71774208-47565f80-2f30-11ea-8791-915c2147c164.png)
