### ISSUE TITLE
[BUG] Hoppers only allowing 3 items at a time

### ISSUE THREAD

**Issue by indian7p** [EarthMC/Issue-Tracker#871]
**Server**
Towny

**Describe the bug**
Every time, if you put items in a hopper, instead of taking 8 ticks for processing 1 item, it takes 24 ticks but processes 3 items at once (except if there are boats, then 1 boat processes through after 24 ticks).

**To Reproduce**
1. Go online
2. Make a hopper going into the chest
3. Open the hopper and chuck a stack of anything in
4. Observe

**Expected behavior**
1 item processing every 8 ticks

**Screenshots**
N/A

**Additional context**
N/A

**Comment by RogerRogue** [comment]
I can confirm that hoppers only move 3 items at a time. The times for transit are about right but when working with locking hoppers and such it tends to be inconsistent. Idk though if this is just a bug or a lag reducing plugin. What ever the deal is, this makes it nearly impossible to do precise timing with hoppers which is a BIG DEAL in Redstone. Can we please have vanilla hopper mechanics again? Will make this server much more interesting to be in!

**Comment by indian7p** [comment]
> 
> 
> I can confirm that hoppers only move 3 items at a time. The times for transit are about right but when working with locking hoppers and such it tends to be inconsistent. Idk though if this is just a bug or a lag reducing plugin. What ever the deal is, this makes it nearly impossible to do precise timing with hoppers which is a BIG DEAL in Redstone. Can we please have vanilla hopper mechanics again? Will make this server much more interesting to be in!

The only problem for me is password protected doors

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71567583-c73e7e80-2a85-11ea-90d5-92d8b98bc47e.png)

I have password protected doors without using hoppers.

There was once an issue with hoppers turning into stone because of lag issues.

I dont know if the slow hoppers prevent this from happening but you may want to try a different way for your redstone doors

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71567698-a0cd1300-2a86-11ea-8c9c-2af9e6e58c7d.png)

**Comment by Prismary** [comment]
This is a common thing to do in order to optimize server performance. The configurations for everything have been updated numerous times since this has been posted, so the behaviour is likely different now.
