### ISSUE TITLE
[Suggestion] Get Rid Of Vote Crates

### ISSUE THREAD

**Issue by unbatedaura409** [EarthMC/Issue-Tracker#872]
No one likes vote crates. People hate getting only 6g from two crates. Just return to 10g a day from voting. Everybody liked that.

**Comment by johnyuki** [comment]
10g was far too much. 10g a day meant you could get a full god set and full set of god tools in 3 or 4 days of just voting. End game gear from 4 days of just logging on to vote. The economy is fucked, and one of the reasons for that is the amount of gold coming in to the game.
