### ISSUE TITLE
[Feature] Captcha in queue

### ISSUE THREAD

**Issue by ClonedCopier** [EarthMC/Issue-Tracker#873]
**Is your feature request related to a problem? Please describe.**
ggovi

**Describe the solution you'd like**
In the lobby, the user would have to complete a captcha before using any /joinqueue command. If the user does not complete a captcha within 5 minutes of joining, they get kicked from the server so they're not using resources. Captchas would be word problems rather than math so they can't be solved by a script.

This solution would prevent ggovi's bots from taking up space in the queue, using server resources, and even making it to the main server.

**Additional context**
![image](https://user-images.githubusercontent.com/43768304/71497747-94974a80-2827-11ea-89f1-fa08ac6b9dd9.png)

**Comment by RogerRogue** [comment]
Yeah you know I always wondered why they don't have some sort of humanity check at the lobby. It would really most problems with bot swarms. There are SO MANY WAYS you could implement a bot trap but yet I don't see any of them.

**Comment by Cactusinapumpkin** [comment]
They did this and I got kicked because I didn't know what was going on and had to go back and read it and it ask for the number on a map, got kicked again and then it asked to pick a Matching item in a gui thing. I noticed a lot of people in French discord was having the same issues.

**Comment by Cactusinapumpkin** [comment]
I'm pretty sure it was more than 5 days ago and I didn't have to solve a captcha again after I solved it the first time I logged in. I think it's still being implemented. But idk if it worked well or not.

**Comment by DasCodes** [comment]
The plugin is a bit buggy, we'll implement it once the bug was handled.
