### ISSUE TITLE
[Feature] Make night time actually dark

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#875]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
After seeing a couple people in this issues forum say that they want EMC to be a bit more difficult, as well as just seeing a few youtube videos about darkness in Minecraft, I think it would be a good idea to get a plugin that makes night time actually dark, regardless of the brightness the player uses. 

If you're wandering around a forest in the dark at night in real life, you're not going to see a thing. This would make it harder to walk around during the night, and would require you to actually light up your town. You could also add in a plugin that lets torches in your off hand emit light, so that you can see if you are carrying a torch in one of your hands. 

Not only would this make EMC a bit harder whilst not changing or adding in anything that would affect the economy, but it also makes sneaking around more useful during pvp. To make it even more difficult, dynmap at night time could also not display any players.

**Additional context**
N/A

**Comment by LemonPickles** [comment]
I think this can only be accomplished with client side mods, not server plugins. This means everyone who plays EarthMC would have to install a mod.

**Comment by Cactusinapumpkin** [comment]
Im pretty sure night time and weather like raining has existed on the server before. It was kinda annoying when you could not sleep the night away and rain ofc is annoying but more useful with people with riptide and loyalty enchants on tridents.

I think they could possible enable nights and weather again but you might need a really good reason other than making it harder to see.

Also a plugin that allows torch light in offhand exists already its called dynamic lighting with opitifine.
