### ISSUE TITLE
[Feature] Map Art Dimension

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#876]
A separate dimension for map art consisting of a super flat world were all chunks are claimed by a town, `Map_Art`.  Most if not all chunks would be embassy plots, sold to players wishing to make map art for a modest fee.

**Comment by Cactusinapumpkin** [comment]
seems like it would cause more problems than it would fix, Half the fun of map art is the challenge of not getting greifed or killed. I made the monalisa in the wilderness at Antarctica and hardly used invis pots or got greifed maybe u can make a map at a really high level and just have people ignore you. 
I was killed 2 times and wasnt greifed, and one time somebody came to me and gave me 17 gold ore.

**Comment by Cactusinapumpkin** [comment]
I dont think admins care about a "modest fee" either.
