### ISSUE TITLE
Cant invite people in my town

### ISSUE THREAD

**Issue by OnlyBaaka** [EarthMC/Issue-Tracker#877]
Hello, i am here to tell you that i have a BIG problem about the towny plugin. Everytime i am inviting someone, it says : none of those names are valid, i tried with so many people that were on the server a long time enough and that had no town, doesnt work. I relogged two times, went in the nether, KICKED SOMEONE to see if it will unglitch. Doesnt work. I gave the recruiter rank to someone in my town and its the same issue, None of those names are valid. SlayerMC said that it happened to other players and he thinks the towny plugin is glitched. Please help me fixing this also the /t add command doesnt work too. Tried with full name and a part of the player name. It was working 1 hour ago but now it doesnt work anymore... Any help on how to fix this...?
My in game name is Baakai, and the town name is pinguin_city

there's a screenshot :

https://cdn.discordapp.com/attachments/600695027018104832/660376658800279552/unknown.png

As you can see, i invited this guy and theres no error message like : hes already in a town or he didnt play enough to join one
Just this

Please help me resolving this problem !

**Comment by johnyuki** [comment]
Pretty sure the command is */t add*, not *invite*

**Comment by Cactusinapumpkin** [comment]
@johnyuki 
![image](https://user-images.githubusercontent.com/48000340/71560783-b8c77700-2a33-11ea-9dc0-8f61fa1e406d.png)



![image](https://user-images.githubusercontent.com/48000340/71560767-959cc780-2a33-11ea-88d8-f163caf42c05.png)

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71560826-22e01c00-2a34-11ea-8c57-1799b1c37413.png)

![image](https://user-images.githubusercontent.com/48000340/71560849-7d797800-2a34-11ea-8b2f-f9862a18074b.png)

**Comment by Cactusinapumpkin** [comment]
This is what I get when I try to invite him @OnlyBaaka  and maybe this will help? I am able to invite people to my town maybe you can try another person and see if it has the same results.

**Comment by Cactusinapumpkin** [comment]
please close the ticket or show another example with another player

**Comment by OnlyBaaka** [comment]
It works, well my invite sent limit was reached, so I revoked invited and It worked

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Cactusinapumpkin <notifications@github.com>
Envoyé : Sunday, December 29, 2019 1:15:50 PM
À : EarthMC/Issue-Tracker <Issue-Tracker@noreply.github.com>
Cc : OnlyBaaka <raphael_descoteaux@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [EarthMC/Issue-Tracker] Cant invite people in my town (#877)


please close the ticket or show another example with another player

**Comment by DasCodes** [comment]
Noice, closing this then.
