### ISSUE TITLE
[BUG] Plot Gets revoked from residents!

### ISSUE THREAD

**Issue by CluelssSlime** [EarthMC/Issue-Tracker#878]
**Server**
Towny

**Describe the bug**
Plots, which residents own get unclaimed after a while. (the  plots are still part of the town, but residents don't own them anymore). 

**To Reproduce**
1. Wait like a day.
2. plot gets removed from a resident.
3. Residents get angry.
4. See error.

**Expected behavior**
the expected behavior is that the plots stay in resident hands. 

**Additional context**
After the resident's plot gets taken away, then when you walk into the plot it says "~ Unowned", but if it is an embassy it says "~ [Embassy]"

**Comment by johnyuki** [comment]
Do you have any taxes set?

**Comment by CluelssSlime** [comment]
> Do you have any taxes set?

no

**Comment by CluelssSlime** [comment]
It wasn't a bug. It was because my town had taxes. 0.711 something.

**Comment by CluelssSlime** [comment]
No, The issue still persists after taxes set to 0. My town can't function properly because of that bug

**Comment by Cactusinapumpkin** [comment]
Can you screen shot your /t?

**Comment by CluelssSlime** [comment]
![Capture](https://user-images.githubusercontent.com/59310075/71626923-51a6ef80-2bf8-11ea-95e2-95176ed0afdc.PNG)

**Comment by Cactusinapumpkin** [comment]
You might want to take away your residents ability to build, destroy, use switches and item use. 
Do you give residents a plot by /plot fs 0 and then having them /plot claim?

**Comment by CluelssSlime** [comment]
> 
> 
> You might want to take away your residents ability to build, destroy, use switches and item use to your town.
> Do you give residents a plot by /plot fs 0 and then having them /plot claim?

Yes i /plot fd 0 and then they /plot claim. And yes i set the perms so nobody can destroy or switch anything

**Comment by Cactusinapumpkin** [comment]
I'll get on at some point this week and get an embassy plot in your town and see what happens. I'll pm you in game when I'm on and ready.

**Comment by CluelssSlime** [comment]
> 
> 
> I'll get on at some point this week and get an embassy plot in your town and see what happens. I'll pm you in game when I'm on and ready.

Okay i'm very thankful for your help.

**Comment by Cactusinapumpkin** [comment]
Can you /mail send cactusinapumpkin ur town co-ords.

**Comment by CluelssSlime** [comment]
> 
> 
> Can you /mail send cactusinapumpkin ur town co-ords.
Yes. I will when I log on.

**Comment by Cactusinapumpkin** [comment]
![image](https://user-images.githubusercontent.com/48000340/71677173-bae94880-2d47-11ea-8f6e-31735f47763f.png)

**Comment by Cactusinapumpkin** [comment]
after about 26 hours I was removed.

**Comment by CluelssSlime** [comment]
Yes this is the exact problem.

**Comment by Cactusinapumpkin** [comment]
see if /t toggle taxpercent gives you this message.
![image](https://user-images.githubusercontent.com/48000340/71677862-7068cb80-2d49-11ea-946b-601d726eecaf.png)

**Comment by CluelssSlime** [comment]
When I ran this command it said "percentage based taxes now Enabled"

**Comment by PoppyK** [comment]
Have  you tried the command /towny set taxes 0?  Sounds to me you have a tax collection, whether it be flat rate or percentage going on.  Looks like you disabled percentage rate, but try this command and see if that helps.

**Comment by CluelssSlime** [comment]
> 
> 
> Have you tried the command /towny set taxes 0? Sounds to me you have a tax collection, whether it be flat rate or percentage going on. Looks like you disabled percentage rate, but try this command and see if that helps.

Yes I tried exactly that. before making this issue. Thanks for help.

**Comment by CluelssSlime** [comment]
I might have found a solution to this problem.. I once set the towns plot tax by using this command:
/t set plottax. If i maybe use this command and set it to 0. MAYBE it will fix itself somehow

**Comment by CluelssSlime** [comment]
The problem was that the plottax was set with this command: /t set plottax, because of this every 24hrs The plots got removed from people... I hope if someone has this problem they stumble upon this issue to get it fixed. Thank you very much for help.
