### ISSUE TITLE
[Feature][Plug-in][Crafting recipe suggestion] purpur blocks with redstone

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#879]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I hate how redstone blocks are worthless]

**Describe the solution you'd like**
I want a Crafting recipe for purpur blocks using redstone and possibly another item like lapis.

Redstone is very common and very little value. I bought a whole dchest for like 1g and still haven't used much of it. I don't even mine the redstone ore anymore.

Also it would be cool to have suggestions for flint. I know some people might use it for arrows but it's limited to how many feathers you can farm and I usually just use a Fletcher villager and infinity. I usually just silk touch gravel just to avoid getting flint.

**Comment by Cactusinapumpkin** [comment]
Purpur bump!

**Comment by Prismary** [comment]
Not sure whether it'd make sense to craft purpur blocks with redstone, but you're right about it not having much use currently.

**Comment by Basically-Andrew** [comment]
Purpur Blocks are available for trade with Merchants.

**Comment by Prismary** [comment]
> Purpur Blocks are available for trade with Merchants.

I feel like these and many other items shouldn't be limited to merchants and have their own recipes instead, however there are newer threads about crafting now so it'd make sense to move the discussion there.
