### ISSUE TITLE
[Feature] More arrow, furnace, and chest types. 

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#880]
**Is your feature request related to a problem? Please describe.**
A lot of people complain about bows being useless, and they're right. Also smelting large quantities of items (such as cobble to get stone) takes ridiculously long unless you're using a large auto smelter, which can take up a lot of space. More chest types would just be cool and save on space in storage rooms.

**Describe the solution you'd like**
### **Arrows:**

- More arrow types would add to the usefulness of bows. Arrow types could include:
  
  - Exploding arrows. Arrows explode on impact. This would also make Blast Protection a useful enchantment, and force people to choose their god armour enchantments more carefully as they'd have to choose between prot4, blast prot4, and fire prot4.

  - Arrows of slowness. If the Arrow hits a mob or player, it gives them slowness for a few seconds. This effect could then be removed by using a speed potion, which would also increase the usefulness of speed pots. 

  - Arrows of piercing. Arrows will now go through entities rather than getting stuck in them, allow you to hit more than 1 player at a time with arrows. 

   - Arrows of necromancy. Arrows that hit a player or mob will, instead of doing damage, spawn a skeleton that focuses only on the hit player/mob, and ignores everyone else. Has a long follow distance, and when it loses focus it despawns. 

  - Arrows of blindness. Players that get hit will be blinded for a few seconds.

  - Arrows of poison. Players that get hit will be poisoned for a few seconds. 

  - Arrows of power. Regular arrows with no effect, but they deal 2x damage. 

You get the idea. It just adds more variety to arrows, and makes some more armour enchantments such as Projectile Protection and Blast Protection useful for once. 

### **Furnaces:**

 Furnaces aren't broken or underused or anything, but I thought it would be nice a nice space-saver if furnaces could smelt more than one item at a time, or smelt things twice as fast for example. 

 - Iron Furnace. Smelts 2 items at once with 1 output (2 inputs and 1 output). Both smelted items must be the same for both slots to work, otherwise only 1 slot will work.

 - Diamond Furnace. Smelts items just like a normal furnace with 1 input and 1 output, but smelts them at 2x the speed of a normal furnace.

 - Emerald Furnace. 2 inputs and 2 outputs, but smelts them at 0.75x speed of a normal furnace.

 - Gold Furnace. 2 inputs and 2 outputs. Smelts them at 2x the speed of a normal furnace. Due to the expense of creating this furnace, it could also give a 20% chance of 1 additional thing. So if you put in 20 iron ore, you could expect 22 iron ingots. This could work separately from MCMMO, so at level 1000 smelting you're guaranteed a double smelt, but also an additional 20% of getting a third smelt due to the Gold Furnace bonus.

All furnaces would have the same recipe as a normal furnaces, except cobble would be replaced by Iron Ingots, Diamonds, Emeralds, and Gold Ingots respectively. 

### **Chests:**

Storage rooms take up a lot of space, especially in smaller towns. This can also be very frustrating for players that don't have their own town and have a single plot in someone else's town. It also means that you can sell larger quantities of items in shop signs.

 - Iron chest. One extra row per chest, so doublechests get two extra rows. 

 - Diamond chest. Two extra rows per chest. 

 - Add in a custom recipe for shulker boxes that would work in the same way that vanilla ones would. 

Just a simple mod to help cut down on the storage space required to store all your items.

**Comment by Cactusinapumpkin** [comment]
I agree we need a dragons breath recipe to make lingering potions to make tipped arrows. Also you can make good potions if you grind mcmmo alchemy. Possibly if you can't allow dragons breath possible they could add a cauldron plugin to make tipped arrows

**Comment by docwhomc** [comment]
I'm not finding 1.15 spigot plugins to implement these features.
