### ISSUE TITLE
[Feature] Allow certain items to be stackable.

### ISSUE THREAD

**Issue by johnyuki** [EarthMC/Issue-Tracker#881]
**Is your feature request related to a problem? Please describe.**
It is sometimes difficult to sell large quantities of low value items because they don't stack. A prime example of this would be potions. Because potions don't stack it means that when buying potions from someone, for example Haste 2 pots, you have to buy an entire doublechest full of them manually from the player. By allowing potions to stack it means that they can be sold through shop signs like everything else.

This isn't limited to just potions either. Armour and tools, providing they have the same durability, could also be made to be stackable, buckets of lava, and music discs could also be made to stack.

**Describe the solution you'd like**
Allow all of the above mentioned items (as well as others I may have missed), to be stackable. Maybe not to 64, but maybe to 8 or 16 or something.

**Additional context**
N/A

**Comment by Cactusinapumpkin** [comment]
Some issues with potions and buckets is that you are left with a empty bottle or bucket and where would that go once you use it with stacked items.

**Comment by KarlOfDuty** [comment]
We'd rather not change the vanilla stacking mechanics.
