### ISSUE TITLE
villager despawning glitch, factions/ emc support messages

### ISSUE THREAD

**Issue by chickenjoejim** [EarthMC/Issue-Tracker#883]
PoppyYesterday at 12:47 AM
I use two plots to breed, and move villagers I keep to other plots.  That way you keep breeding more and have a better chance of keeping ones of value.
 
ChickenJoeYesterday at 12:47 AM
i hope were on the same page that this is factions not towny
 
The_DoctorYesterday at 12:48 AM
Shouldn't matter, it's probably the anti-lag plugin either way.
 
ChickenJoeYesterday at 12:50 AM
well what poppy was talking about wasnt related to what was happening with the villagers despawning
they were pretty much isolated from any mob within a 5 chunk radius
rome had villagers two different times, and the first time they lived for like 3 days and died from a raid, the next time they got villagers they put them in the exact same chunk yet they despawned like 20 minutes after the fact
not to mention it sonly happening with villagers
i have a cow farm right next to a 20 spawner blaze farm yet not a single one despawned despite being in the same chunk
theres no way its anti lag, we would have seen something like this happen like 2 weeks ago when we had like 40 villagers in one chunk
the highest we had at one point was 90+
we killed them for space and organization so generally it was around 30-35 villagers there at all times, almost all were named with their specific sales yet none despawned even once
im not saying there isnt an anti lag plugin but this is something completely different to it unless the plugin is broken

**Comment by Cactusinapumpkin** [comment]
Did you check the nether? When my villagers disappeared in towny I found a villager in the nether

**Comment by Cactusinapumpkin** [comment]
Have you thought about making multiple smaller breeding areas. That way you have a fail safe. Then you can see if it's a chunk error. I would space out the farms about 3 chunks apart.

**Comment by DasCodes** [comment]
Possibly got killed by a cheater?

**Comment by KarlOfDuty** [comment]
As villager trading is disabled this isn't really relevant anymore.
