### ISSUE TITLE
Stuck/Cant do anything

### ISSUE THREAD

**Issue by Riipsaw** [EarthMC/Issue-Tracker#884]
**Server**
EarthMC.net

**Describe the bug**
When I join, I got teleport to china, My friend from Saint-Jerome invited me(the owner of Saint-Jerome). Every command he told me to try didnt work out and now I am stuck in a mine :\

**Expected behavior**
Can I get into Saint Jerome town with the commands working( /t accept saint-jerome)

**Screenshots**

**Additional context**

**Comment by Cactusinapumpkin** [comment]
Have you tried /t invite accept saint-jerome?
Have the mayor /t invite -riipsaw and then /t invite riipsaw again and it should prompt you the commands for accepting his town invite again.

**Comment by Cactusinapumpkin** [comment]
![71560767-959cc780-2a33-11ea-88d8-f163caf42c05](https://user-images.githubusercontent.com/48000340/71584757-c59ea600-2ad9-11ea-858f-c7ffb4486081.png)
