### ISSUE TITLE
Suggestion (Putting a Complete List of the custom crafting recipes as the one of the website are outdated) 

### ISSUE THREAD

**Issue by davidboosgarza** [EarthMC/Issue-Tracker#885]
Can someone update the added crafting recipes plz? The ones on the website do not cover all the crafting recipes.

**Comment by Cactusinapumpkin** [comment]
172da87

**Comment by Cactusinapumpkin** [comment]
https://github.com/EarthMC/EMCRecipies/commit/172da87afb769870e6b71aebe2fd65f6c377df76

**Comment by Cactusinapumpkin** [comment]
Here's the older commit..
https://github.com/EarthMC/EMCRecipies/commit/d7949b06ee9b06c6463eb9edc526148e1a1183f4

**Comment by Cactusinapumpkin** [comment]
I tried adding them to one page but I don't think they liked me doing that.

**Comment by Cactusinapumpkin** [comment]
https://earthmc.net/faq
![image](https://user-images.githubusercontent.com/48000340/71768396-30d1e900-2edb-11ea-83d7-f8a98822b024.png)

**Comment by KarlOfDuty** [comment]
Looks to be all of them, otherwise please list the ones that are not included.

**Comment by DeadGlamour** [comment]
![image](https://user-images.githubusercontent.com/53373440/76152153-d4e73480-60c4-11ea-9248-5c6915bead4e.png)
![image](https://user-images.githubusercontent.com/53373440/76152176-2394ce80-60c5-11ea-98a4-b9ff6c7da812.png)
these 2 arent listed
