### ISSUE TITLE
I can't plant seeds

### ISSUE THREAD

**Issue by KaninoPika** [EarthMC/Issue-Tracker#887]
**Server**
Towny

**Describe the bug**
When the lgiht took away the plants I can't plant them back

**To Reproduce**
1. Make a farm 
2. Put a roof over it
3. Start planting 
4. Then the error comes

**Expected behavior**
What happens is that it just takes you crops

**Screenshots**
I need a video for that but I can send to a mod/admin/Fix If you guys need

**Additional context**
Nope

**Comment by KaninoPika** [comment]
Need to redo/make some more steps I realised
4. Wait 
5. Plants dissaper
6. Try where it dissapered
7.There is the bug

**Comment by Cactusinapumpkin** [comment]
Its your light level, and more lights.

**Comment by Cactusinapumpkin** [comment]
I use this "bug" for my potato farm because villagers will are able to plant them and the player isn't.

**Comment by KaninoPika** [comment]
I wasn't sure if it was that that's why I came here thanks :)

**Comment by Cactusinapumpkin** [comment]
Ok please close ticket thank you
