### ISSUE TITLE
[BUG] Book & Quills Crash

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#888]
**Server**
Towny

**Describe the bug**
Book & Quills, writing or reading, will crash my game on 1.14(.4) in certain circumstances.

**To Reproduce**
1. Log on to Towny on 1.14(.4)
2. Open up Book & Quill
3. Flip a few pages and/or copy and paste
4. Game Crashes with error:
_The_ game crashed whilst rendering screen
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: _243_

**Expected behavior**
Able to copy and paste, read pages, and you know book things...

**Screenshots**
None

**Additional context**
None

**Comment by Cactusinapumpkin** [comment]
This is normal this is to prevent overloading the chunk and duping with the book.

**Comment by Basically-Andrew** [comment]
So how do I write a book...?

**Comment by docwhomc** [comment]
Try using 1.15.2 and writing into the book instead of using copy/paste.
