### ISSUE TITLE
Villagers and some mob dispawn

### ISSUE THREAD

**Issue by Doctfr** [EarthMC/Issue-Tracker#889]
@**Server**

All my villagers (around 100) except 2 dispawned and all my cow except 1 and all my cheep dispawned. Also most of the villagers was renamed and all of them was less than 10 per chunks.

**To Reproduce**
1. Go to 'earth mc towny'
2. Load all chunks in your town
3. Be not lucky

**Expected behavior**
Exchange stuff as armor miscellaneous enchanted books....

**Screenshots**

![D01AAFC0-6A61-4098-90EB-7DE4F8A3DCAE](https://user-images.githubusercontent.com/59469147/71713962-357b9c00-2e0c-11ea-9df3-a2257cdcfe52.jpeg)
![47BF6AD8-7B82-403D-92A5-885EFE03A4EE](https://user-images.githubusercontent.com/59469147/71713963-357b9c00-2e0c-11ea-8fd8-2c6ccf912bec.jpeg)
![3ADA5637-58F9-45BA-8163-AC06E725AC0E](https://user-images.githubusercontent.com/59469147/71713964-36143280-2e0c-11ea-9b5c-130ac76a4bf0.jpeg)

**Additional context**
I putted some friend villagers in boat to not dispawned and that working I think.

**Comment by Dahtz** [comment]
I've already lost quite a few like that, again this evening, the spawn mob was reactivated and I lost a bookseller with mending.
I still haven't found a technique to avoid this

**Comment by Doctfr** [comment]
> I've already lost quite a few like that, again this evening, the spawn mob was reactivated and I lost a bookseller with mending.
> I still haven't found a technique to avoid this

Hi, I am really sad for you. My villagers have been respawned by eagle but they re dispawned.

**Comment by Dahtz** [comment]
Ah ok, so we can ask the admins for a spawn from the villagers?
I would like to recover my villagers in this case ...

With experience, I know that there are several causes. The maximum number of villagers on a chunks, and when the spawning mob is activated.

**Comment by Doctfr** [comment]
> Ah ok, so we can ask the admins for a spawn from the villagers?
> I would like to recover my villagers in this case ...
> 
> With experience, I know that there are several causes. The maximum number of villagers on a chunks, and when the spawning mob is activated.

You need some evidence as screenshot and make a ticket on a discord server add me on discord I will invite you on it Doct_fr#4590

**Comment by Dahtz** [comment]
It's easy to know when they're going out, I always put them in carts.
I now have the phobia of empty carts.

![de89r89gr](https://user-images.githubusercontent.com/58906366/72212188-c53ddc00-34d7-11ea-9069-ba4b6a14a5c1.png)

**Comment by Doctfr** [comment]
> It's easy to know when they're going out, I always put them in carts.
> I now have the phobia of empty carts.
> 
> ![de89r89gr](https://user-images.githubusercontent.com/58906366/72212188-c53ddc00-34d7-11ea-9069-ba4b6a14a5c1.png)

Add me on discord. For your screens you need a screenshot of now and before, when they were there

**Comment by Dahtz** [comment]
I add you
Mhm, I think I d'ont have screen before...

**Comment by KarlOfDuty** [comment]
Mobs do disappear sometimes in minecraft, its just something players will have to deal with.
