### ISSUE TITLE
[World] Add savannas and extreme hill biomes

### ISSUE THREAD

**Issue by jmills321** [EarthMC/Issue-Tracker#89]
**Describe the issue**
A clear and concise description of what the issue is.
ive traveled all over north and south america and could not find an actual extreme hills or savannah biome, they were all forest, snowy tundra or desert biomes, this means they cannot support llama spawns

**Coordinates**
X Y Z coordinates.
everywhere with mountains and desert savannahs

**Screenshots**
https://imgur.com/a/njoCYJh

**Comment by KarlOfDuty** [comment]
Southern madagascar is a savannah if anyone really needs llamas before we get to these areas.

**Comment by BowShot118** [comment]
They would be nice.

**Comment by TypicalFernie** [comment]
I'm pretty sure there is also no plain biomes. Which is why people have been spawning horses instead of finding them. The great plains is a forest biome. Savannahs around the map are set as desert biomes. Would be great if it was fixed because more horses and llamas would spawn.
