### ISSUE TITLE
[BUG] Players unable to join my town

### ISSUE THREAD

**Issue by Judestadt** [EarthMC/Issue-Tracker#890]
Hello, my ign is Golden_Bowser003, and I've been experiencing a really weird bug when I try to invite people. When I /t invite or /t add players, they get the invitation, but when trying to join they get "not enough permission" error. I also tried /t invite sen sat to see whether I reached the invite limit, but it wasn't the case. I also tried giving myself recruiter and councillor ranks and trying again, but without any success. Help would be appreciated

**Comment by KarlOfDuty** [comment]
Should be fixed.
