### ISSUE TITLE
I can't describe this bug

### ISSUE THREAD

**Issue by KaninoPika** [EarthMC/Issue-Tracker#893]
**Server**
Towny

**Describe the bug**
Just a weird said he was last online 1970

**To Reproduce**
Steps to reproduce the behaviour:
I just did /res (name)

**Expected behavior**
Like a normal /res (name)

**Screenshots**
![image](https://user-images.githubusercontent.com/18099825/71826347-fa909700-309d-11ea-8541-1e1658307d5a.png)

**Comment by KaninoPika** [comment]
Heck you can't even see the screenshot anyway here it is: https://ibb.co/4V2RNSB

**Comment by KarlOfDuty** [comment]
It happens sometimes if they haven't been saved before.
