### ISSUE TITLE
Sign shops not connecting to chests straight away

### ISSUE THREAD

**Issue by VulgarPotato** [EarthMC/Issue-Tracker#896]
Server
Towny

Describe the bug
Signshops not connecting to chests on the first attempt

To Reproduce

Not quite sure, create a sign shop but before connecting it to a chest
Teleport away
Attempt to connect the sign shop to the chest

Screenshots
https://youtu.be/HRTCFOusBiM

Additional context
It eventually worked on the 15th try.
Details: The signshop was placed in a plot not directly owned by me
The chest was placed in a plot owned by me
The chest is also connected to 4 other sign shops

**Comment by VulgarPotato** [comment]
this was completely not in the right format i'm sorry about that

**Comment by Cactusinapumpkin** [comment]
/set home and /set t spawn closer to ur chests instead of taking longer than 30secs to run over there.

**Comment by VulgarPotato** [comment]
I took 21 seconds, 0:23 to 0:44

**Comment by VulgarPotato** [comment]
plus, it would have shown in chat if the timer ran out

**Comment by Cactusinapumpkin** [comment]
Sometimes that happens but I guarantee if you take less time it will work better.

**Comment by docwhomc** [comment]
This appears to be resolved.
