### ISSUE TITLE
[BUG] "internal exception: java.io.ioexception: an existing connection was forcibly closed by remote

### ISSUE THREAD

**Issue by RolatatorChorico** [EarthMC/Issue-Tracker#897]
**Server**
Towny

**Describe the bug**
This is the only server I play that this happens, I don't know if it's related, but I was browsing dark web with 2 VPNs and Tor, I already uninstalled all of them.

**Comment by Cactusinapumpkin** [comment]
I get this alot too

**Comment by Cactusinapumpkin** [comment]
This is normal, you just try joining again and it will let you. Please close ticket
