### ISSUE TITLE
i have just been banned for being a bot 

### ISSUE THREAD

**Issue by denny9921** [EarthMC/Issue-Tracker#898]
i have just ben banned for being a bot i just joined i have been playing for 2 min
banned by mihal 
user name dennym911

**Comment by denny9921** [comment]
![Capture](https://user-images.githubusercontent.com/32978626/72118355-bacbe880-3305-11ea-9062-ae59e4c16d63.PNG)

**Comment by Cactusinapumpkin** [comment]
Rip

**Comment by Cactusinapumpkin** [comment]
I think emc support discord ticket might be faster to get a ban appeal
