### ISSUE TITLE
Sign Shops for Factions

### ISSUE THREAD

**Issue by Ashe820** [EarthMC/Issue-Tracker#899]
Sign shops still dont work in factions or have been removed. I am 100% sure that they have been working since i made some earlier. Please add them back. Might have forgotten to be enabled again after the bugfix.

**Comment by DasCodes** [comment]
The Sign shop plugin is extremely buggy atm, which is why it was removed from towny until it gets patched. Perhaps another sign shop plugin we can try.

**Comment by lili502** [comment]
Give us sign shop back plz
