### ISSUE TITLE
shield selling panel and buying redirection

### ISSUE THREAD

**Issue by JustStarkSteel** [EarthMC/Issue-Tracker#900]
Hello
I started selling custom shields with banners and I notice that every day shields are sold more with customization but are sold as normal, I think this is due to the restart of the server and therefore I cannot do this trade
while it worked before
with sign
I also noticed that when we put a panel in purchase mode the golds are taken from the enderchest and are not taken from the safe provided for redemption

**Comment by Cactusinapumpkin** [comment]
Have you tried to sell custom banners instead of custom banners shield? Also the gold being taken out of your echest instead of the chest has been changed that way due to gold be duped. You will have to use your echest as your gold supply and not sell gold in a sign
