### ISSUE TITLE
[BUG] Loss of all chests in /cr claim

### ISSUE THREAD

**Issue by Mafia-Cats** [EarthMC/Issue-Tracker#901]
I have read the faq and am aware that there's little that can be done, but I figured I should alert you. I have been away from the 26th and have been unable to log in, but i have still voted most days. Unfortunately, when i logged on not long ago the /cr claim command told me I had no rewards to claim, losing around 30 votecrates. This may be an inactivity feature, I wasn't able to find anything on it, but I figured I should make a new issue. (IGN Mafia_Cats)

**Comment by Warriorrrr** [comment]
You can't vote while offline, so it's expected that you don't get the rewards. You need to be online to vote. /cr claim is only for when you vote while online but when your inventory is full.

**Comment by Mafia-Cats** [comment]
You used to be able to use it while offline

**Comment by DasCodes** [comment]
Offline voting was turned off due to bugs. Follow the #announcements to get updates on it.
