### ISSUE TITLE
[BUG] Claimable Chests cant be claimed

### ISSUE THREAD

**Issue by TimelineYt** [EarthMC/Issue-Tracker#903]
Towny

I Vote for the server when I'm not playing on it and when I try to claim my chests it says I don't have any chests to claim which can't be because I just voted
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '.https://minecraft-mp.com/server/133301/vote/A'
2. Type in Username
3. Verify that your not a Robot 
4. Click on 'vote'
5. Go on Towny server 
6. Type '/cr claim' in chat
7. and chests don't show up in inventory

**Expected behaviour**
The chest should be claimable and loot should be able to be gotten from it

**Comment by Cactusinapumpkin** [comment]
I have noticed this as well

**Comment by Mafia-Cats** [comment]
I too have had this issue

**Comment by Warriorrrr** [comment]
You can't vote while offline, /cr claim is only for when you vote with a full inventory.

**Comment by TimelineYt** [comment]
it used to work before

**Comment by Cactusinapumpkin** [comment]
Yea so I have voted offline before and received vote crates in my /cr claim but have noticed that it had not worked recently and that voting online with full inv does still add it to /cr claim. So this will be something that could be fixed or discontinued

**Comment by DasCodes** [comment]
Offline voting was turned off due to bugs. Follow the #announcements to get updates on it.
