### ISSUE TITLE
Inactive users logging into towns last minute to prevent despawning issue.

### ISSUE THREAD

**Issue by ketchupdrinker** [EarthMC/Issue-Tracker#904]
Recently it has come to my attention that people are abusing systems put into place to prevent town inactivity, this system is simple, they do nothing with their town and are never active, then a few days before it despawns they log in once then leave to continue their cycle.

This has been a problem on earthMC for a year now, and it crowds large areas and ruins the game for most players. Some players use bots to join the game and extend this cycle and other players use alternative accounts to do this to claimblock other people.

**I believe I have a solution for this issue feel free to add suggestions** , if players were required to play for at least 1 hour within the 42 day timespan then their towns would not despawn, this would filter out bots and most players doing this greatly decreasing the amount of people who abused this system.

**EDIT:** Another solution I believe is possible is the amount of claims you have increases the amount of days before your town despawns, I'm not sure if the towny plugin can work out a solution or something similar to this but I suggest pming the creator of the towny bot or edit the script of the bot to include that feature. This is one of the largest issues on EMC especially since the map is not infinite.

**Comment by Cactusinapumpkin** [comment]
Also filter out anyone going on vacation

**Comment by KarlOfDuty** [comment]
Towny does not track play time at all so I don't think that is possible.

**Comment by ketchupdrinker** [comment]
Yeah this is a really large issue on EMC and a temporary solution to this is just restarting the server but that doesn't offer any permanent change.
