### ISSUE TITLE
/warnings and /warningslist show up KarlOfDuty's warnings.

### ISSUE THREAD

**Issue by FutureLemon** [EarthMC/Issue-Tracker#905]
When you do /warnings or /warningslist it will give you your warnings, but the prefix is broken and says not your name but Karls. 
![image](https://user-images.githubusercontent.com/44688587/72439134-9f019000-37a6-11ea-9c2a-95a913d2d2c1.png)
As you can see it says Karl was warned by... But in fact it's a warning I have.

**Comment by KarlOfDuty** [comment]
Wtf
