### ISSUE TITLE
Alchelmy skill not working

### ISSUE THREAD

**Issue by rubydavies** [EarthMC/Issue-Tracker#906]
I am a new player, like a week old, I just want to brew haste potions but I cannot level up because Alchemy skill isn't working. Pls send help.
from: Just another egirl on the server

**Comment by FutureLemon** [comment]
It works fine for me I leveled up my Alchemy level by 100 today. What are you doing to level it up, because you need to unlock the recipe to brew haste first. Here's a link about the Alchemy skill to inform yourself more about Mcmmo. https://mcmmo.fandom.com/wiki/Alchemy

**Comment by Cactusinapumpkin** [comment]
Please close ticket
