### ISSUE TITLE
I lost 20 blocks of gold in last night's server crash

### ISSUE THREAD

**Issue by leathermonster** [EarthMC/Issue-Tracker#907]
I had just logged in to break down some gold blocks I had placed for a fountain at -16955, 84, -7065 and as I traveled back home at about 10:47pm EST on Jan 18th the server crashed and I fell through the ground. When I log back in at about 5:58am on Jan 19th, the blocks are not in the fountain, and not in my inventory. Please get me these black back it took a lot of time to gather the gold

**Comment by Warriorrrr** [comment]
@leathermonster This isn't the place to ask for a refund, you can do so here: https://discord.gg/cC5yjq3.

**Comment by Cactusinapumpkin** [comment]
Please close the ticket

**Comment by leathermonster** [comment]
Okay sorry I'm new to all of this.

**Comment by docwhomc** [comment]
Please close @leathermonster
