### ISSUE TITLE
[Feature] Wipe the faction server and fix mcmmo

### ISSUE THREAD

**Issue by Fr0zen-exe** [EarthMC/Issue-Tracker#908]
The faction server is nearly dead by now and a lot of player enjoyed it since May of 2019. but some others abused the mcmmo system so we need new features to it.

Fix the mccmmo system. Downscale and wipe the factions earth map, keep it the same but just downscale it.

**Comment by docwhomc** [comment]
What do you mean by fix MCMMO?

**Comment by docwhomc** [comment]
As it, what do you have in mind as a way to fix it?
