### ISSUE TITLE
[BUG] Mcmmo Superbreaker issue

### ISSUE THREAD

**Issue by Bidav** [EarthMC/Issue-Tracker#909]
**Server**
All using the new Mcmmo update

**Describe the bug**
Before the server was updated to use the newer version of Mcmmo, the Super Breaker duration skill would go up 1 second per 50 levels progressively getting harder to level up. Although, during the transition this level has seemed to be capped at 22 seconds despite being mentioned as "there is no maximum duration" within the Mcmmo mining explanatory page and it's previous behavior pre-update (https://mcmmo.fandom.com/wiki/Mining). I believe this is a bug due to it's sudden addition and it severely ruins some aspects of mining since there appears to no longer be a reason to train the skill.

**To Reproduce**
1. /mining
2. See the Super Breaker length section under stats

**Expected behavior**
For Super Breaker length to go up in duration in accordance to level of Mining, with no cap.

**Comment by Scorpionzzx** [comment]
On top of this. Obsidian no longer gives double drops or triple drops with super breaker. This makes mining obsidian extremely tedious and no longer worth the time.

**Comment by Bidav** [comment]
In addition, double drops seem to not work around the board. I've also heard complaints about many aspects of MCMMO that seem to be quite varied in problem but all center around a certain skill that stops working or gets servery nerfed to an unusable state.

**Comment by Scorpionzzx** [comment]
Yea I realized that but forgot to add. Double drops aren't working so on top obsidian mining now being useless, there are fewer emeralds in the world for villager trades and also sell quartz for building. The constant (unintentional) nerfs to mining are really discouraging people who want to grind for gold and key resources like emeralds/diamonds.

**Comment by FutureLemon** [comment]
I want my longer superbreaker back and my double drops for stone, iron, emeralds, obsidian and etc...

**Comment by Scorpionzzx** [comment]
@KarlOfDuty

**Comment by Warriorrrr** [comment]
+1 fix pls

**Comment by Prismary** [comment]
Could someone with a high enough mining skill confirm this is still not fixed?

**Comment by Fruitloopins** [comment]
> Could someone with a high enough mining skill confirm this is still not fixed?

no

**Comment by AndrewCheedle** [comment]
> +1 fix pls

@Warriorrrr

**Comment by CorruptedGreed** [comment]
Cap is there on purpose afaik
