### ISSUE TITLE
[Feature] Make the maximum distance of a town to the capital larger.

### ISSUE THREAD

**Issue by KaueTheTrekker** [EarthMC/Issue-Tracker#91]
Let's pick an actual example, me and my friends are from Rio de Janeiro and it's going to be Brazil's capital. Problem is, I did some basic maths and discovered that the distance from Rio de Janeiro to Recife is greater than 3,000, by a small margin but anyway. Making the creation of a nation like Brazil, impossible from Rio de Janeiro.

I think a great solution would be making the limit 7,000. Picked up that number by measuring the distance between Rio Grande do Sul and the most distant point from there(in Brazil). But the suggestion really is, make it bigger. It destroys the fun of the server, that is, making nation that at least resemble their real counterparts in one way or another. It is only fair being able to make all real life nations. Maybe for exception of Russia, because of its size. It is really frustrating that the limit is so small we won't even add a city like Recife to our future nation. Please, change that, we have been planning this since the announcement of Terra Nova only to be taken away by this.

**Comment by BowShot118** [comment]
It sounds like a good idea imo but it sort of defeats what Fix and Karl are going for. An easy solution would be too form multiple capitals, like Canada has.

**Comment by KaueTheTrekker** [comment]
so? what does the staff think about it? if you guys want to keep it as it is just say it already

**Comment by KarlOfDuty** [comment]
We do want to keep it as it is, yes. The issue is left open for the community to respond.

**Comment by sharkfynn1012** [comment]
I mean, I know first hand how painful it is to get screwed over thinking you’ll be in a nation then not be let in. The idea is cool, but with such a thing there will always be that one player that is just outside of the capital radius and can’t get in.

**Comment by BowShot118** [comment]
A potential solution could be a hefty price to increase the nation range by 500 ~ 1000 blocks.

**Comment by sharkfynn1012** [comment]
Or that a nation range increases as they add more towns.

**Comment by KarlOfDuty** [comment]
There is no way to have different ranges for different nations at this point. We also do not want to increase the limit globally either.
