### ISSUE TITLE
Dynmap nation colors

### ISSUE THREAD

**Issue by PatriotDream** [EarthMC/Issue-Tracker#910]
While not exactly a problem which makes the game unplayable, I believe that there should be an option for national leaders to change the colors of their nation as it appears on Dynmap so that they may be able to make out what belongs to them, and not have it all get lost in a sea of blue everywhere. I have been on servers where this has worked and it should not be a major problem to offer a palette from which leaders can choose from.

**Comment by Cactusinapumpkin** [comment]
It's a neat idea but really is just another thing that could cause problems or hard to implement and maintain and therefore will probably not be added.

**Comment by docwhomc** [comment]
[suggestion]

**Comment by KarlOfDuty** [comment]
It is being looked into, but not currently possible.
