### ISSUE TITLE
[SUGGESTION] Outsiders can access the /t spawn of all public towns

### ISSUE THREAD

**Issue by ketchupdrinker** [EarthMC/Issue-Tracker#911]
It's been frustrating attempting to make an active town that doesn't have a nation spawn, it's hard to create shops because likely no one will visit them and a large incentive for building is that other people can easily view your builds.

My idea is that to get to a town outsiders can access public town spawns by first teleporting to the nation spawn that the town is in, then they will have access to the town spawn once they are at the nation. This still puts a use to owning a nation, you will have a range to be a hub for all other nations to teleport from you. An example of this would be, say I want to go to Nice, France. I would have to say /n spawn France, then say /t spawn Nice.

If there is any way to add this to the towny plugin or enable it somehow that would be greatly appreciated.

**Comment by Cactusinapumpkin** [comment]
Also /n spawn Savoy is next to nice. They would also need a way to disable the function if the town doesn't want people teleporting to their town too.

**Comment by Cactusinapumpkin** [comment]
If you want to spawn to a town you can always set up a inn with the town mayor and set your /res spawn there

**Comment by ketchupdrinker** [comment]
Nice isn't in the nation of Savoy, You wouldn't do /n spawn Savoy then /t spawn Nice, because you would have to be at the nation's capital to teleport to Nice.

**Comment by KarlOfDuty** [comment]
That is not possible and I don't think it's something we'd want.
