### ISSUE TITLE
One account but diff name with diff INV [BUG]

### ISSUE THREAD

**Issue by UniBraDa** [EarthMC/Issue-Tracker#912]
So, my original name was UniBraDa and I changed my name to Prisoner_97, then when I try to vote with the name UniBraDa, while my actual name in-game was Prisoner_97, I didn't get any of the vote crates even though the chat said I've voted and got a vote crate. 

Then, I changed my name to Pickled_Cheetos recently, and one of my in-game friends transferred me 32 gold in the name of Prisoner_97, and surpriseeee I didn't get any gold even though it says smth like successfully transferred 32 G to me. 

As I've mentioned before, All 3 names are from the same acc.

**Comment by Warriorrrr** [comment]
I feel like it's clear enough that you need to enter the correct IGN with commands like /vote & /pay. You need to enter the _correct_ IGN to receive it, you can't enter past ones, only your current will work.

**Comment by UniBraDa** [comment]
Lol i get that it was my mistake but what i am saying is that it is still a bug and it would be great if it's fixed

**Comment by Cactusinapumpkin** [comment]
Pickled Cheetos..

**Comment by UniBraDa** [comment]
lol you should see my skin online 
it looks like a messed up cheetos

**Comment by UniBraDa** [comment]
anyway what I want to say is that I am ok with not fixing the bug but I am just saying that it existes thats all :)

**Comment by Cactusinapumpkin** [comment]
It doesn't exist you are just using your old name instead of the current one. Close this ticket

**Comment by DasCodes** [comment]
It's up to the plugin developer to fix it, as we use a plugin to check the voted player's IGN.
