### ISSUE TITLE
Anvils - Crash

### ISSUE THREAD

**Issue by Peanut-Slayer** [EarthMC/Issue-Tracker#913]
Whenever I put any pickax into an anvil my Minecraft completely crashes. All other tools work fine as far as I am aware of just pickaxes.

**Comment by Cactusinapumpkin** [comment]
That's weird

**Comment by docwhomc** [comment]
That might be a client side issue.

**Comment by KarlOfDuty** [comment]
Yeah, that's a client side issue.
