### ISSUE TITLE
/t invite -name (revoke town invites) doesn‘t work.

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#914]
**Server**
towny

**Describe the bug**
/t invite -name doesn‘t work. 
When I try to enter the command, I get no return value and nothing happens.

**To Reproduce**
1. /t invite sent
2. check for a name
3. type „/t invite -name“
4. Nothing happens

**Expected behaviour**
remove the town invite request for one player so new invites can get sent.

**Screenshots**
Nothing to screenshot

**Additional context**
I can‘t invite players anymore because of this. Also apparently no one else has this problem, but JaVolimKatarinu said it is the right command.

**Comment by ketchupdrinker** [comment]
Yeah I have the same problem as you, after I invite a large amount of people it won't let me invite anymore, there's no revoke command and I don't remember everyone who I invited to even revoke the invite in the first place. I've tried relogging and nothing is working.

**Comment by KarlOfDuty** [comment]
Towny devs found the issue, should be fixed next time we update towny.

**Comment by Newbieb3** [comment]
Is this fix? I'm having the same issue

![Image](https://github.com/user-attachments/assets/4f51712e-095b-45e5-91e9-12aacd6f7252)
