### ISSUE TITLE
[Plugin] /t join

### ISSUE THREAD

**Issue by FerraAvirail** [EarthMC/Issue-Tracker#917]
**/t join** should be back. It will make it easier for people to join town, without abusing invites.
**Bots are gone**

**Comment by FutureLemon** [comment]
Yes, I agree. I once made a github post about it as well, but it got shot down due to all the bot attacks the server has. Luckily it seems like the bot attacks are actually gone and perhaps we could enable /t join again.

**Comment by KarlOfDuty** [comment]
We'd rather keep it off for now at least, it has a few ways it can be abused.
