### ISSUE TITLE
[Mechanic] McMMO duration of skills

### ISSUE THREAD

**Issue by JaVolimKatarinu** [EarthMC/Issue-Tracker#919]
**Describe the solution you'd like**
Increase the duration of McMMO skills to unlimited or at least 40-50 seconds 

**Additional context**
With the new update to McMMO ( Overhaul Era) skills have been limited in terms of their durations. Currently, the maximum duration for any skill is 22 seconds. And the increase in duration is received on every 50 levels by 1 second. That is all okay, but take consideration about players who have grinded levels too much and actually got a reduced duration of their skills with the new update. We are already in Retro mode ( 1-1000+ level) meaning that there isn't level limit and most skills don't give anything once you reach 1k-1.1k levels. We are playing on the same map for over a year now and there is a lot of players with skills reaching 2k+ levels. And I don't want to mention players with 1000-2000 levels which all received reduced durations, but not that significant as 2000+...

This has been a pretty much big nerf that I assume you overlooked. Let's hope we can find some way of dealing with this and ease player's lives who are with us for such a long time. ;)

**Comment by FutureLemon** [comment]
#909

**Comment by DasCodes** [comment]
Closing this, please follow #909.
