### ISSUE TITLE
No mob spawns

### ISSUE THREAD

**Issue by Keennoo** [EarthMC/Issue-Tracker#92]
It is nearly impossible to find any mobs, and you can AFK in the nether for 30min and not get attacked by anything. Me and my townsman went 3 nights out and couldn't find a single zombie at all. Please update

**Comment by KarlOfDuty** [comment]
Mob spawns are currently turned off.

**Comment by Keennoo** [comment]
Why?

**Comment by sharkfynn1012** [comment]
The lag possibly.

**Comment by Keennoo** [comment]
The lagg is mostly gone - we can't do basic minecraft expansions such as going to the end or getting villagers. Can we get a time or date when it'll be fixed?

**Comment by KarlOfDuty** [comment]
Mobs are turned back on.
