### ISSUE TITLE
[Idea] Adding /t spawn and/or removing nation claim radius 

### ISSUE THREAD

**Issue by lucasw2011** [EarthMC/Issue-Tracker#921]
I'm not sure how the staff feel about the number of nations on the server but I believe it is a problem. 
As you can see in the screen shots below nations clutter the server. instead of distinct nations you have a handful in one area. if you look at china or Texas you can see what i mean. 
Some nations are made because they want the ability to have people teleport to their town to get more business, on classic this was not a problem because allied town tp was available. 

Some towns dislike the nation they are in so they save up 1000 gold to make their own nation, the server is our 1000 gold and more confusion has been added to the region that the new nation was created in, On classic if a town didn't like the nation they were in they could join any nation on the map. 
There are also Nations making other nations to increase claims and making "colonies" in other parts of the map which takes more gold out of the server. driving the price of nations higher is not the answer, realistic travel is no longer viable. people do not Boat across the Atlantic and they do not ride horseback to travel they use /n spawn then walk or use the nether. 

Please reconsider re-adding one or both of these features they are what helped make Classic so successful and fun.

![Screen Shot 2019-09-30 at 6 03 07 PM](https://user-images.githubusercontent.com/45434705/65920312-ac883b00-e3ac-11e9-942a-71a53a8382e5.png)
![Screen Shot 2019-09-30 at 6 02 56 PM](https://user-images.githubusercontent.com/45434705/65920330-b7db6680-e3ac-11e9-931d-16ae4ef27a91.png)
![Screen Shot 2019-09-30 at 6 02 39 PM](https://user-images.githubusercontent.com/45434705/65920334-bc078400-e3ac-11e9-8b1d-0e7a6b4cae15.png)

**Comment by ImperialFishy** [comment]
Nation tax when^TM. It kills all the inactive nations and is an extra running burden to nations that expand through colony nations
