### ISSUE TITLE
[Idea] Events

### ISSUE THREAD

**Issue by Ra2orLeaf** [EarthMC/Issue-Tracker#922]
So at the moment there aren’t many events on the server. All the events made are made by players and therefore have limited things they can do. What would be cool is for the staff to host some events and maybe rewards could be currently unattainable or extremely rare items like spider eyes and tridents. There would probably need to be a different server the events are hosted on to protect the queue on the server. Examples of events: 
Pvp tournaments 
Build tournaments
Challenges like get 1000000 stone between your town.
Pvp area supply drop zone
Riddles to find treasure
 I don’t really see why this can’t go ahead please say why it might not work.

**Comment by Prismary** [comment]
Events hosted by staff now take place occasionally whenever it makes sense and there's a good idea for one.
