### ISSUE TITLE
Ownership transfer when Owner is banned

### ISSUE THREAD

**Issue by josfire18** [EarthMC/Issue-Tracker#924]
**Exact wording of the rule**
If a nation leader is banned, members of said nation can contact mods to have the next in line promoted to leadership. The members will have to agree on the next in line before contacting any mods.

**How will this rule affect the community**
When a nation's leader is banned, the nation will fall since no one can take ownership after the fact. This is such a bad rule because the leader could do something and it would affect everyone, despite no one else being involved but the leader.

**Do you think this will benefit both the staff and the players**
Yes. Fewer ticket requests and complaining to staff and players don't have to lose their entire nation when one person gets banned. Why punish everyone for the mistakes of one?

**Please use <https://github.com/EarthMC/Issue-Tracker> for issues other than the EarthMC.net website**

**Comment by docwhomc** [comment]
Maybe we delete there player data if the appeal is denied or if they don't open an appeal within one week?

**Comment by KarlOfDuty** [comment]
We will let towny handle the succession.
