### ISSUE TITLE
German Chat and a apartment/hotel plugin

### ISSUE THREAD

**Issue by MrGamingAffeDE** [EarthMC/Issue-Tracker#926]
Hello can you pls add a German chat for us Germans because we want talk in our language. And the second is a hotel plugin for example: Eagle is visiting my Town/Nation and he want stay there a while but don't want buy a plot

**Comment by docwhomc** [comment]
Can't you designate an inn plot?

**Comment by docwhomc** [comment]
If you want more than that, we'd need a new plugin and I'm not aware of any that would do the job.

**Comment by Warriorrrr** [comment]
German chat has been added a while ago, a hotel-type feature has been suggested many times to Towny but never accepted.

**Comment by MrGamingAffeDE** [comment]
Sooooooo Apartments exist now on EMC?

**Comment by jwkerr** [comment]
> Sooooooo Apartments exist now on EMC?
they have for about a year now through my plugin quarters https://github.com/jwkerr/Quarters
