### ISSUE TITLE
Searching for towns on dynamaps

### ISSUE THREAD

**Issue by HelloGaming123** [EarthMC/Issue-Tracker#927]
I think you should be able to search for towns on the dynamap to see where they are because sometimes you don't know where a town is and it is hard to find them on a huge world map.

**Comment by FutureLemon** [comment]
I don’t think that the plugin supports that, but the EarthMC Stats bot for Discord shows you the coords of towns.

**Comment by docwhomc** [comment]
As far as I'm aware, that isn't supported by the towny-dynmap plugin.  You'll have to take it up with the plugin devs.
