### ISSUE TITLE
War System Available

### ISSUE THREAD

**Issue by Goosius1** [EarthMC/Issue-Tracker#928]
Hi admins,

I'm not sure where to post this (I tried messaging on discord, but friend requests still pending),
but I wanted to keep you guys in the loop about the progress of Siege-War.

As you may know, I'm working with the Towny plugin team, and have been developing a new geopolitical war system. It is (by all indications which I have seen) due for final reviews and release some time after 0.0.96.0.

I just wanted to drop you a line because I myself am quite confident that it is ready for use on major servers.

This is because it is already in use !
More than a week ago, CCNET started a full trial of the system on their 'Nations' server, and so far we are seeing only minor bugs (fixed now), apparently good performance and apparently high engagement from the playerbase. They will do a poll in a week to more strictly asses player experience. Other servers are now picking it up too e.g. Datnet just picked up a copy for trial.

The documentation is complete, and I there is a 1.13 compatibility branch available also.

Pr / Wiki / jars: https://github.com/TownyAdvanced/Towny/pull/3541

Let me know if you have any questions etc.
I am on discord also.

Regards,
Goosius.

**Comment by watergod1234** [comment]
I swear to god if this isn't added i'm going to fucking lose it.

**Comment by MineHero43** [comment]
Seems interesting, I hope this is at least tested on emc

**Comment by FranchuFranchu** [comment]
I hope there is an opt-out for this for us users who play EMC for building

**Comment by FutureLemon** [comment]
> I hope there is an opt-out for this for us users who play EMC for building

For most war systems it’s usually a two way consent before it can start.

**Comment by MineHero43** [comment]
> I hope there is an opt-out for this for us users who play EMC for building

The opt out is surrendering ¥.¥

**Comment by ThundorLord** [comment]
I genuinely can't decide whether I'm for or against this, it seems like a great idea, however it may not work with a server that's already been up for many years. As longer lived nations may have the upper hand. This could be tied with a reset, as every nation would grow from nothing alongside this plugin.

**Comment by ThundorLord** [comment]
> > I hope there is an opt-out for this for us users who play EMC for building
> 
> For most war systems it’s usually a two way consent before it can start.

If you read the text file, you cannot completly opt out of war, however you can opt out of the ill effects it may cause.

**Comment by FutureLemon** [comment]
> I genuinely can't decide whether I'm for or against this, it seems like a great idea, however it may not work with a server that's already been up for many years. As longer lived nations may have the upper hand. This could be tied with a reset, as every nation would grow from nothing alongside this plugin.

But everything is so cheap on EarthMC, you can buy a double chest of potions for 2g and a godset for under 30g thats not even half an hour of mining if you vote everyday.

**Comment by ThundorLord** [comment]
> > I genuinely can't decide whether I'm for or against this, it seems like a great idea, however it may not work with a server that's already been up for many years. As longer lived nations may have the upper hand. This could be tied with a reset, as every nation would grow from nothing alongside this plugin.
> 
> But everything is so cheap on EarthMC, you can buy a double chest of potions for 2g and a godset for under 30g thats not even half an hour of mining if you vote everyday.

It still doesn't equate to sheer numbers however, and it really depends on how power hungry the big nations get

**Comment by docwhomc** [comment]
Thanks for letting us know @Goosius1.

By the way, you know there's a bug with town and nation succession, right?  I have a partial fix for it.

**Comment by docwhomc** [comment]
Can we setup a test server similar to the Factions' beta test setup?

**Comment by docwhomc** [comment]
^^^ Made a separate thread for it.

**Comment by DasCodes** [comment]
We are discussing this.

**Comment by D2GameBoy** [comment]
hi. can i pls get a download file. i want to use this

**Comment by Goosius1** [comment]
Sure.
The latest jars are all linked from discord page,
along with install instructions and user guide: https://discord.gg/fDqkzEr

**Comment by Goosius1** [comment]
This war system has now officially been (beta) released as a separate plugin for use alongside the Towny plugin.
All install/user information is here:  https://github.com/TownyAdvanced/SiegeWar
Support is now available on the normal TownyAdvanced discord.
