### ISSUE TITLE
[BUG] Mcmmo potions and sign shops

### ISSUE THREAD

**Issue by Kungfukangaroo** [EarthMC/Issue-Tracker#929]
Towny

Basically someone told me my Haste II sign wasn't giving him the right potion, in that the potions have 0 duration time. I tried it myself and it gave me this weird potion, with no duration timer in its tags. Maybe incompatibility issue? 

**To reproduce:**
Just set up a sign shop with Haste II, unload the chunk, reload the chunk, purchase and you have some useless potions. 

**Expected behaviour:** 
Haste II potions that give you Haste II effect for longer than 0 seconds. (i.e. the ones you put into the source chest)

Edit: Corrected method of recreating the bug.

**Comment by KarlOfDuty** [comment]
Yes, the sign shops are not compatible with mcmmo potions.
