### ISSUE TITLE
[Feature] Streamer rank

### ISSUE THREAD

**Issue by shirazmatas** [EarthMC/Issue-Tracker#93]
There are many streamers from small, to less small playing on the server. I believe that these streamers should get a streamer rank that enables them to log in when the server is full as to not ruin the stream or lack of gameplay.

I have no current idea what the criterias are to get the stream rank.

**Comment by KarlOfDuty** [comment]
We are probably not making a new rank for this but they can reach out to use themselves and we may be able to work something out.
