### ISSUE TITLE
[Plugin] ORE RESPAWN

### ISSUE THREAD

**Issue by lewd-est** [EarthMC/Issue-Tracker#930]
So there is a problem with ores being drained, I have a simple solution!

Add in a plugin that responds ores underground from time to time, very easy and effective

essentially there are players that are leaving because ores are being drained in some places and it hurts new players that are new and want to play, respawning or resetting ores let's say every month or so would fix that, I hope this was helpful!

**Comment by FutureLemon** [comment]
Yes! Let me just write down all the coordinates of gold I've ever found...

**Comment by docwhomc** [comment]
Why write them down when you have map mods?

**Comment by docwhomc** [comment]
So it would have to be randomized and old ore would have to be despawned.

**Comment by docwhomc** [comment]
I'd suggest finding new places to mine.  There are still plenty on the server.  You just may have to travel a little further if your town is in a densely populated area.
