### ISSUE TITLE
[BUG] Brewing stands not included in Itemuse permission

### ISSUE THREAD

**Issue by Warriorrrr** [EarthMC/Issue-Tracker#935]
**Server**
Towny

**Describe the bug**
Brewing stands aren't included in the itemuse permission, meaning that any outsider can go into your town and take stuff out of the brewing stands

**To Reproduce**
1. Go to any town with brewing stands
2. Open a brewing stand
3. See error

**Expected behavior**
That the brewing stand wouldn't open for anyone that doesnt have enough perms

**Additional context** 
This can easily be fixed by the admins, the only thing that would be required is to add brewing stand to the protection section in config.yml for Towny.

**Comment by jkmartindale** [comment]
+1 on this, a few weeks ago someone came in and stole a bunch of potions while I and a friend were operating our brewer. I understand that should've built structures around the brewer to make it harder to climb in, but the same argument could be made for any other itemuse protection.

**Comment by Cactusinapumpkin** [comment]
I usually just use a door to avoid switch perm issue but using them as mail boxes is fun too!

**Comment by KarlOfDuty** [comment]
Fixed next restart.
