### ISSUE TITLE
[Suggestion] Towny Wars Test

### ISSUE THREAD

**Issue by docwhomc** [EarthMC/Issue-Tracker#937]
Related: #928

Since there are some concerns about adding a towny wars plugin since the towny server is already fairly established, why don't we try a test server?

I'm thinking something similar to the factions beta, where the map would be confined to a limited geographic area, player count would be limited, and access would be restricted to premium, donors, and staff.

While we're at it, we could also try some other plugins and/or give 1.15 a try... it is supposed to have better performance after all.

**Comment by docwhomc** [comment]
For the map, I was thinking something centered around [Tel Megiddo](https://en.wikipedia.org/wiki/Tel_Megiddo) would be fitting.

**Comment by KarlOfDuty** [comment]
Not at this time.
