### ISSUE TITLE
Bug with the /plot command.

### ISSUE THREAD

**Issue by Kranzy1373** [EarthMC/Issue-Tracker#938]
The mods suggested me that I should post my bug on the Issue Tracker and here I am. When I give someone an chunk with "/plot forsale 0" and the new member with "/plot claim" the new Town member loses ownership of the chunk after one day. I have NO taxes in my town or my Nation but it still happens and the members didn't leave my town as well. This doesn't apply to all my Town members though. That only makes it stranger. My town is called "Hannover". Located in north Germany

**Comment by Cactusinapumpkin** [comment]
[BUG] Plot Gets revoked from residents! #878

The problem was that the plottax was set with this command: /t set plottax, because of this every 24hrs The plots got removed from people... I hope if someone has this problem they stumble upon this issue to get it fixed. Thank you very much for help.
