### ISSUE TITLE
mcmmo potions don‘t work

### ISSUE THREAD

**Issue by Lagann311** [EarthMC/Issue-Tracker#939]
**Server**
towny

**Describe the bug**
If you try to brew absorption potions, it doesn‘t work.

**To Reproduce**
1. drag quarz shards into brewing stands
2. nothing happens

**Expected behavior**
Brews absorption potions.

**Comment by Cactusinapumpkin** [comment]
Can you screen shot your /alchemy menu?

**Comment by alekb1** [comment]
Not a bug, the level requirement for absorption was changed from 250 to 375. So as Bethesda would say, it's not a bug, it's a feature.

**Comment by Lagann311** [comment]
ah that‘s it then. Guess I have to grind 100 more levels
