### ISSUE TITLE
The server is laggy

### ISSUE THREAD

**Issue by OrangeJuiceMoose** [EarthMC/Issue-Tracker#94]
Ive been trying to place a chest but i keeps on going back to a block.

**Comment by BowShot118** [comment]
The server is very laggy and it took me and add a lot more time to make it then it normally should do :/

**Comment by KarlOfDuty** [comment]
Yes, we are aware of the server lag.

**Comment by KarlOfDuty** [comment]
Two of the three issues causing lag have been fixed, the third biggest one has been identified but needs some time to be fixed. It will be split into it's own issue.
