### ISSUE TITLE
[Suggestion] Release the Classic World Download

### ISSUE THREAD

**Issue by LoganCreeper50** [EarthMC/Issue-Tracker#940]
If Classic has been officially closed (like it was in Sept. 2019) then you should release the world download for it. There is stuff that I want to still look at on it for inspiration on TN, so it is kinda sad to see that I cannot look at it at all.

**Comment by KarlOfDuty** [comment]
We will likely set it up again when issues with the main server is finished. Right now it just dies shortly after startup.
