### ISSUE TITLE
[Suggestion] Stop Trap Killing. 

### ISSUE THREAD

**Issue by AmphireYT** [EarthMC/Issue-Tracker#941]
Trap killing is the worst, frustrating, and just bad in general. No one likes it if the person is the victim. I lost my full set twice because Of it. (And other people lost many things; not saying this because I lost my stuff, but too stop it for once and for all because ive seen people lose worse items than me)  It is the laziest way to get tools and items. It doesn't challenge the player to get the gold themselves by mining and it just encourages them to do more of it. My suggestion is to ban it and many people would agree too. (I made this github account just too make this issue)

What the rules says: “Of course keeping someone stuck for a short period of time for instance if they are attacking your base is allowed”

I am not (other people) attacking there base in any way (they should add a rule to which the spawn area should be safe but the chunks surrounding it can be a pvp area, therefore they get the chance to go back were they need to be)

“you should kill them so they can keep playing as soon as possible”
As I said, /t spawn or something similar.

**Comment by LoganCreeper50** [comment]
Isn't it your own fault that you got trapped?

**Comment by AmphireYT** [comment]
> Isn't it your own fault that you got trapped?
it clearly states "not saying this because I lost my stuff, but too stop it for once and for all because ive seen people lose worse items than me"
Please read, and Yes, it is my fault but it gets annoying when you work hard for your items and it gets lost like that.

**Comment by LoganCreeper50** [comment]
I used your as a general statement not directed at you. If you didn't want to lose items just don't fall for the traps, just because it is annoying doesn't mean it should be banned.

**Comment by AmphireYT** [comment]
> I used your as a general statement not directed at you. If you didn't want to lose items just don't fall for the traps, just because it is annoying doesn't mean it should be banned.

well there no reason why it should stay there and I always try not to, I was unlucky. Plus, people hate it.

**Comment by GreenmanYT** [comment]
I think, when you tp to a nation, the spawn chunk can't be PvP. But if not that then instead of making spawn traps against the rules, make `[messages like this ](https://ptb.discordapp.com/channels/219863747248914433/503664647342391326/678481757971939349)` (caityy_spencee: Come to /n spawn Fiji for drop party. Dropping gold and free stuff) against the rules, as they are luring people into traps.

**Comment by AmphireYT** [comment]
> I think, when you tp to a nation, the spawn chunk can't be PvP. But if not that then instead of making spawn traps against the rules, make Messages Like [This](https://ptb.discordapp.com/channels/219863747248914433/503664647342391326/678481758458740779) (caityy_spencee: Come to /n spawn Fiji for drop party. Dropping gold and free stuff) against the rules, as they are luring people into traps.

I really like that idea! Yea we should do that to

**Comment by Basically-Andrew** [comment]
EarthMC is a server designed to be a Anarchy server with a few rules. I agree that spawn chunks shouldn't allow pvp, but shouls allow players to advertise. Players have the right to advertise id f it relates to EarthMC.

**Comment by AmphireYT** [comment]
> EarthMC is a server designed to be a Anarchy server with a few rules. I agree that spawn chunks shouldn't allow pvp, but shouls allow players to advertise. Players have the right to advertise id f it relates to EarthMC.

“Few rules” and let them advertise all they want idc but stop trap killing/what greenmanYtT said

**Comment by Basically-Andrew** [comment]
My FULL Opinion:

Either disable nation spawn chunks and toen spawn chunks from being pvp enabled or add a notice in /n or durring the countdown after running /n spawn.

Any other types of trap killing should be illegal including advertising them.

**Comment by AmphireYT** [comment]
> My FULL Opinion:
> 
> Either disable nation spawn chunks and town spawn chunks from being pvp enabled or add a notice in /n or durring the countdown after running /n spawn.
> 
> Any other types of trap killing should be illegal including advertising them.

advertising/luring them into spawn killing and the add a notice is a good idea too and add a 5 second countdown or confirmation

ex. /n spawn Britain and then chat says "this nation was found to be trap killing, would you still want to go their?" and the player types /yes or /no / similar commands to accept and decline 
(this is just an example)

**Comment by Basically-Andrew** [comment]
> > My FULL Opinion:
> > Either disable nation spawn chunks and town spawn chunks from being pvp enabled or add a notice in /n or durring the countdown after running /n spawn.
> > Any other types of trap killing should be illegal including advertising them.
> 
> advertising/luring them into spawn killing and the add a notice is a good idea too and add a 5 second countdown or confirmation
> 
> ex. /n spawn Britain and then chat says "this nation was found to be trap killing, would you still want to go their?" and the player types /yes or /no / similar commands to accept and decline
> (this is just an example)

"this nation was found to be trap killing, would you still want to go their?" is completely opinionated. They would never add a message like that. It would just show on the tp message a red (pvp) symbol.

**Comment by AmphireYT** [comment]
> > > My FULL Opinion:
> > > Either disable nation spawn chunks and town spawn chunks from being pvp enabled or add a notice in /n or durring the countdown after running /n spawn.
> > > Any other types of trap killing should be illegal including advertising them.
> > 
> > 
> > advertising/luring them into spawn killing and the add a notice is a good idea too and add a 5 second countdown or confirmation
> > ex. /n spawn Britain and then chat says "this nation was found to be trap killing, would you still want to go their?" and the player types /yes or /no / similar commands to accept and decline
> > (this is just an example)
> 
> "this nation was found to be trap killing, would you still want to go their?" is completely opinionated. They would never add a message like that. It would just show on the tp message a red (pvp) symbol.

its just an example but yea that works too

**Comment by DasCodes** [comment]
We have updated our rule 2.1. Please visit the rules page.
