### ISSUE TITLE
[BUG] THE CRATE AND FRAME

### ISSUE THREAD

**Issue by GracjanGGWIN** [EarthMC/Issue-Tracker#942]
Earthmc.net(Towny)
Which server the bug is on.

Sooo I have museum and I wanted put crates into the frames so ppl can see, but u can't and there show an error when u try put Them.
ear and concise description of what the bug is.

**To Reproduce**
1. Go to FRAME
2. Hold in hand vote crate
3. Gry piy crate into frame

I want that I can put it there and no error:)

I can't not on my pc sorry 
If applicable, add screenshots to help explain your 

Nah

**Comment by Basically-Andrew** [comment]
Have you tried crouching to place the item in the item frame? Otherwise I can't help you and this would go to Fix and Karl.

**Comment by DasCodes** [comment]
Any click while holding the crate will trigger the crate, this is intended.
