### ISSUE TITLE
[BUG] Pistons not retracting on chunk borders

### ISSUE THREAD

**Issue by DiamondDoesStuff** [EarthMC/Issue-Tracker#943]
**Server**
Towny

**Describe the bug**
When a piston is placed on the edge of a chunk facing the opposite side of the chunj you own, next to a chunk you don't own (claimed by someone else) the piston will not retract when the power is stopped.

**To Reproduce**
1. Place a piston directly on the edge of a chunk so that it extends sideways to the opposite border of the chunk next to a chunk claimed by someone else.
2. Power it with redstone(lever, torch, dust whatever)
3. Break/turn off the redstone.
4. The piston will not retract.

**Expected behavior**
The piston should retract when power to it is stopped

**Comment by Cactusinapumpkin** [comment]
...

**Comment by stzups** [comment]
This is intentional. The piston should not be able to interact with blocks across the chunk border. A possible bug with Towny may be allowing the piston to extend into the unclaimed chunk in the first place.

**Comment by DiamondDoesStuff** [comment]
Okay, I really did not do a good job of explaining the bug. The piston head is facing into the chunk owned by me. If I place the piston so that the head is facing up or down it works fine, but not if i place it so that the piston head extends towards the opposite side of the chunk i own.

**Comment by Basically-Andrew** [comment]
This less a bug, but a feature, so that players don't steal blocks from a adjacent chunk. Towny can't tell if its facing outwards or inwards, so it just disables the piston all together from past testing. Id you wanted to you make a seperate issue as a suggestion for Towny on this.

**Comment by stzups** [comment]
`The piston head is facing into the chunk owned by me.`
So the actual piston body is in the chunk not owned by you, and the piston head is facing the chunk owned by you? Or is the piston body in the chunk owned by you, and the piston head is also facing into your chunk.
Can I see screenshots of what works and what Towny prevents with chunk borders on? (F3+G to see chunk borders)?

**Comment by stzups** [comment]
@DiamondDoesStuff Does this replicate your issue? 
![image](https://user-images.githubusercontent.com/55036602/75629869-d8a22500-5bb3-11ea-81b4-57b2b9bc99b6.png)
On the left is a claimed chunk. On the right is an unclaimed chunk. The sticky piston is powered on the top image. On the bottom image, the lever is flicked off, and the piston retracts but does not take the block with it. This is expected behavior, and I can't see a bug here.

**Comment by KarlOfDuty** [comment]
As some have mentioned above, this is how it's supposed to work.
