### ISSUE TITLE
[BUG] Disappearance of my town

### ISSUE THREAD

**Issue by talentedbear13** [EarthMC/Issue-Tracker#944]
**Server**
Towny

**Describe the bug**
Background: There is a France's town called Troyes located in the right-hand side of Paris. The last player and the only player in Troyes- Crazy_RM have not on for 42 days. Troyes fall. (I will call this old Troyes in the content.)

Content
I am a player in Earthmc.net called talentedbear13. At 15/02/2020, around 7:00 am in the server time zone, Old Troyes fall into ruin. I want to protect this fantastic town so I immediately set up another town called Troyes in the same chunks of old Troyes. I have spent around 1000 gold to claim most of the chunks that used to belonging to old Troyes. Some players have been to my new town, including Thanamos, explodingmelons. They don't have perm to do anything in my claimed chunks. Troyes have joined nation France. My /t spawn point is located in the first chunk that I type /t new Troyes.

At that day, around 11:00 am, I log on the server and I located in Troyes, but i don't know why the server keep kick me out for a few times. Then I use /n spawn france. The server finally don't kick me out.

Around 11:00 am to noon, explodingmelons tell me to check Troyes as he found that Troyes disappeared when he is seeing earthmc.net/map/ . I use /t spawn immediately. I spawn into wilderness. All the chunks in Troyes disappeared and turn into wilderness. In my /res, the town is showing Troyes, Hermit talentedbear13. I can talk in nation chat. I can check for /n online. After the nation members knowing the disappearance of Troyes, they loot a lot of valuables happily. Other players loot and destroy my town as well. 

At 16/02/2020, I log on once. I check my /res. It is showing my town Troyes. I am Hermit talentedbear13. I can talk in nation chat and check /n online. But the t spawn is not working as the server said t spawn point is not set.

Now I am asking for compensation. Recovering my town and also give me back the chunk. I also want further compensation. This bug cause huge loss to me. I have spent a lot time trying to contact the staff talking about the situation but the reply is very slow. I feel extremely sad by seeing my town destroyed and loot by other players. 

**To Reproduce**
1.I stand in a chunk using /t new Troyes.
2. I type /t accept invite france.
3. I use /t deposit for around 1000 gold
4. I walk and /t claim chunks

**Expected behavior**
My town-Troyes is owning most of the chunk of old Troyes forever unless I don't log in for 42 days. I am the only player that have perms to edit these chunks.

**Screenshots**
Picture of Old Troyes
![Screenshot_20200215-124135_Chrome](https://user-images.githubusercontent.com/61139059/74643733-2bd9a800-51b0-11ea-9479-1319ebfb87cf.jpg)

Picture of my town-Troyes
![Screen_Shot_2020-02-15_at_11-1](https://user-images.githubusercontent.com/61139059/74643947-8115b980-51b0-11ea-9fb8-575644bcfac1.png)

Picture of the situation of disappearance of Troyes
![Screenshot_20200217-160144_Chrome](https://user-images.githubusercontent.com/61139059/74644053-a73b5980-51b0-11ea-8417-dd389215dfd9.jpg)

Picture of /res talentedbear13
![20200216_193932](https://user-images.githubusercontent.com/61139059/74644152-d0f48080-51b0-11ea-9058-ea9aebb4f2a0.jpg)

Picture of checking n online
![20200216_194102](https://user-images.githubusercontent.com/61139059/74644223-ee294f00-51b0-11ea-9d47-862d393c8dcc.jpg)

Picture of talking in nation chat
![20200216_194121](https://user-images.githubusercontent.com/61139059/74644353-1e70ed80-51b1-11ea-9c4e-6b385059f5a9.jpg)

**Additional context**
I want my my chunk back, recovery of my town and also further compensation.

**Comment by Basically-Andrew** [comment]
Was your town possibly removed due to claimblocking? If possibly I would make a support ticket on the EarthMC Support Discord Server in #support-tickets with -new.

**Comment by talentedbear13** [comment]
I have already make a ticket and the stuff know this case, They are looking into this bug.

**Comment by KyledonGaming** [comment]
Mine did too.
![image](https://user-images.githubusercontent.com/29753329/75103262-f3760780-55bd-11ea-9e00-c508171b6237.png)
![image](https://user-images.githubusercontent.com/29753329/75103267-fbce4280-55bd-11ea-9b52-79eb8536d899.png)
The towns name is Marthropli

**Comment by Cactusinapumpkin** [comment]
I think this has been dealt with

**Comment by Cactusinapumpkin** [comment]
Close ticket

**Comment by Prismary** [comment]
> I think this has been dealt with
