### ISSUE TITLE
[BUG] My Town Disappeared

### ISSUE THREAD

**Issue by JudithSheindlin** [EarthMC/Issue-Tracker#945]
**Server**
Towny.
**Describe the bug**
Please help, I made my town beside Paris at 8:30pm EST, Feb 16 and some time after 9pm, while I was afk in Paris, the town fell unintentionally. I was afk and when I came back the town was no longer there and I had just made it with all my gold in the town bank. I had all my gold from selling my nation and now I can't get my gold.

**To Reproduce**
I was afk when the town fell, I don't know what happened.

**Expected behavior**
I didn't want the town to fall.

**Screenshots**
![Screen Shot 2020-02-16 at 9 58 12 PM](https://user-images.githubusercontent.com/57871146/74657406-2ce1e980-515e-11ea-85f7-2d3f21dad294.png)
These were the player responses after the town fell. (i scrolled up from the channel to find it)
![Screen_Shot_2020-02-16_at_8 45 01_PM](https://user-images.githubusercontent.com/57871146/74657436-3f5c2300-515e-11ea-8665-40f9c4d0e8e0.png)
This was in my dms with Barvaux it shows the town exsisting
![Screen Shot 2020-02-16 at 10 01 08 PM](https://user-images.githubusercontent.com/57871146/74657497-5c90f180-515e-11ea-8126-b64716f5066a.png)
this was when I made the town

**Additional context**
Please give me my gold and town back, I don't know what happened and it just disbanded with all my gold in the bank!

**Comment by Lagann311** [comment]
You should rather make a ticket about it. I think this way mods can adress the issue earlier.
Kind of scary that towns can just randomly disband O.O

**Comment by docwhomc** [comment]
@Lagann311 No, it is a bug, the correct way to report the bug is through the Issue Tracker.  A ticket should be created by the mayor to the town restored or a refund.

**Comment by Basically-Andrew** [comment]
Judy, I belive your town was disbanded by staff due to the logic of claimblocking. Create a ticket to appeal on the EarthMC support Discord Server in #support-tickets with -new.

**Comment by docwhomc** [comment]
Related #944

**Comment by KyledonGaming** [comment]
Mine did too. 
![image](https://user-images.githubusercontent.com/29753329/75103262-f3760780-55bd-11ea-9e00-c508171b6237.png)
![image](https://user-images.githubusercontent.com/29753329/75103267-fbce4280-55bd-11ea-9b52-79eb8536d899.png)
The towns name is Marthropli

**Comment by DasCodes** [comment]
What was your town name? @JudithSheindlin
