### ISSUE TITLE
[BUG] I cannot talk in #earthmc-factions even though I have linked my account.

### ISSUE THREAD

**Issue by k00lk4t** [EarthMC/Issue-Tracker#946]
**Server**
Factions

**Describe the bug**
I wanted to talk in #earthmc-factions on the discord, so i linked my account but it doesnt work? I am still muted.

**To Reproduce**
1) Start with an unlinked account
2) Link it
3) DM the code to the bot (Congratulations you linked your acc with *id*!)
4) Not able to talk?

**Expected behavior**
To be able to talk in #earthmc-factions

**Screenshots**
None

**Additional context**
I asked some staff, they were weirded out.

**Comment by Basically-Andrew** [comment]
What is your Discord tag? You may have been given a mute role. Otherwise, when was the last time you were you able to speak in #earthmc-factions?

**Comment by k00lk4t** [comment]
CanIPlayzz#7969

**Comment by k00lk4t** [comment]
I just joined 3 days ago so i never talked there before

**Comment by Cactusinapumpkin** [comment]
I also have this issue but I have been able to talk in there before

**Comment by Basically-Andrew** [comment]
Try unlinking and relinking your account.

**Comment by k00lk4t** [comment]
I did multiple times

**Comment by KarlOfDuty** [comment]
You should make a support ticket instead and moderators will help you out.
