### ISSUE TITLE
nation chat insufficient permisson bug

### ISSUE THREAD

**Issue by Cactusinapumpkin** [EarthMC/Issue-Tracker#947]
**Server**
towny

**Describe the bug**
reoccurring inability to join nation chat sometimes

**To Reproduce**
-type /ch j nation in towny chat
-get error
-join global
-type /ch j nation in towny chat
-error

**Expected behavior**
join nation chat

**Screenshots**
![image](https://user-images.githubusercontent.com/48000340/74784560-cba93b80-526d-11ea-8d12-3973bc38cb70.png)

**Additional context**
It works after logging and is similar to the spawn command bug

**Comment by RogerRogue** [comment]
I have the same problem sometimes. One time I tried rejoining 3 times but it still wouldn't work.

**Comment by shirazmatas** [comment]
there is no channel called nation. There is a chat called nation which you acess with /nc or nation chat

**Comment by Cactusinapumpkin** [comment]
Ok did you read what you or anyone else posted because this issue has nothing to do with the difference between channel and chat. I'm talking about the ability to access the chat is sometimes blocked. I can understand if nothing can be done and closing it but it seems like you closed the issue without correctly assessing the issues in the beginning.

**Comment by RogerRogue** [comment]
Yeah shirazmatas you did not read what was said here at all. We can not access the national chat sometimes due to this bug. We need it fixed.
