### ISSUE TITLE
Add regular restart every 6-12 hours

### ISSUE THREAD

**Issue by Toadally** [EarthMC/Issue-Tracker#95]
**Is your feature request related to a problem? Please describe.**
As you probably already know, the server sometimes experiences extreme lag spikes especially during peak hours in the US.

**Describe the solution you'd like**
Like many other servers, I think that a regular automatic restart every 6 to 12 could help clear any lag caused by memory overload or other issues

**Comment by KarlOfDuty** [comment]
We have identified the ram leak so this is no longer needed.
