### ISSUE TITLE
[BUG] Not being able to send town invites while having perms to do so

### ISSUE THREAD

**Issue by jasoncookie99** [EarthMC/Issue-Tracker#950]
Towny

When i try to invite someone new to the town it gives me an error saying that the town has to many invites and needs to revoke some, but there was no way to revoke me that i could find.

try to invite someone to the town and it does it everytime

should just send an invite to the person

**Screenshots**

**Additional context**

**Comment by stzups** [comment]
This may be wrong , but go ahead and try it:

To view sent invites, do /t invite list

To revoke an invite, do /t invite -[name]
Make sure to put the - in front of the name to revoke. Old invites that were never accepted/denied can pile up.
