### ISSUE TITLE
[Feature] Name Colors

### ISSUE THREAD

**Issue by Fraggers** [EarthMC/Issue-Tracker#951]
The New K put before players who are the owners of nations is ugly as described by several common server players and doesn't stand out, or look as nice as name colors

I suggest that Yellow donators should get a yellow name color, the other donator (purple maybe?) should get the corresponding color. And last of all, owners of a nation should get a seperate color, 
The "K" should stay alongside this color system, as well as the plus before donator's names

Alternatively, all donators get a color such as purple, leaving yellow for nation owners to match the rest of the yellow branded nation colors.

I believe that this change would be a nice touch and help make nation owners easily identifiable once again

**Comment by tomatochip** [comment]
I think the K symbol should be replaced with a crown doe

**Comment by KarlOfDuty** [comment]
The colouring will be changed in the future.
