### ISSUE TITLE
Mob Spawners

### ISSUE THREAD

**Issue by Futinghe** [EarthMC/Issue-Tracker#952]
**Server**
Towny

**Describe the bug**
Mob spawners dont drop when mined with a silk touch pickaxe

**To Reproduce**
Break a spawner with silk touch

**Expected behavior**
The spawner was supposed to drop when mined with a silk touch pickaxe

**Comment by SolidShock** [comment]
I think that's because the server doesn't have any plugins that would allow you to mine spawners.
In vanilla minecraft your described actions won't result in a placable spawner, that's a plugin that does that.

**Comment by alekb1** [comment]
@SolidShock it was a feature on the 1.13.2 version of the server, so it's "bug" that they have not updated the plugin yet

**Comment by QJWIN** [comment]
lol alekb a BUG is a malfunction , that not the case the spawner plugin is missing, so that cannot be a BUG ...This plugin is not upgraded to 1.15 ...

That a bug only if the plugin is turned on and nothing append when you brake you spawner ...

**Comment by DasCodes** [comment]
This should be fixed now.
