### ISSUE TITLE
[Bug] Items Not Dropping After Death:

### ISSUE THREAD

**Issue by Basically-Andrew** [EarthMC/Issue-Tracker#953]
**Server**: Towny

**Describe the bug**:
When killing a player, items in the player's inventory don't drop. 

**Steps to reproduce the behavior**:
1. Give a player an item
2. Kill the player with the item
3. No items drop

**Expected behavior**:
Player's items will drop after death

**Additional context**:
The bug works in PVP claims and Wilderness. It also works with items on the head (hats).
Recording: http://www.mediafire.com/file/1z84xpzuidqx021/EMC_Issue.mp4/file

**Comment by alsjad** [comment]
Yes this does happen and it needs to be fixed

**Comment by Cactusinapumpkin** [comment]
confirmed this was true with me as well

**Comment by davidboosgarza** [comment]
This happened to me as well! Me and Pro (the mod) were messing around on his island and I fell to my death and lost all my items. Pro went to look and confirmed that they had despawned. Then later today I forcefully drowned someone that was fishing and no fishing rod or other loot was dropped.
