### ISSUE TITLE
Player cannot sit when right clicking any of the new granite/diorite/andesite stairs 

### ISSUE THREAD

**Issue by tomatochip** [EarthMC/Issue-Tracker#954]
**Server**
Towny
**Describe the bug**
Usually, the player can right click a stair block to enter a sitting animation on the step. This is not the case with any of the new staircase blocks added to the 1.15.2 update. The user cannot sit on any type of granite, diorite, or andesite stairs (polished or unpolished). 

**To Reproduce**
1. Craft a granite, diorite, or andesite staircase block
2. Right click base of the stair as you would normally to sit down 
3. When right clicking on the new stair blocks the player does nothing 

**Expected behavior**
The player should enter a sitting animation

You can confirm this by sitting on a wooden staircase for comparison

**Comment by PoppyK** [comment]
I'm pretty sure this is a plugin issue and the dev of that plugin will need to update before it can be added to EMC.

**Comment by jkmartindale** [comment]
RifleDLuffy/RFChairs#7

Plugin looks abandoned

**Comment by jkmartindale** [comment]
Actually, I take that back. EarthMC needs to update the version of RFChairs they have installed.

While the plugin is listed as abandoned on its [plugin page](https://www.spigotmc.org/resources/rifles-chairs-abandoned.58809/), all Minecraft 1.15 stairs work on the last version of the plugin.

I tested all the stairs below with RFChairs 6.0 on a local test server:
![image](https://user-images.githubusercontent.com/11380394/76686615-ca5bfc00-65ea-11ea-8379-d7cde7a9a6b1.png)

**Comment by tomatochip** [comment]
-Poke-
 fix this yo I’m tryina sit

**Comment by jkmartindale** [comment]
mfw 40 plugins get updated but not RFChairs 😔

**Comment by jkmartindale** [comment]
![image](https://user-images.githubusercontent.com/11380394/107055181-a2433180-6796-11eb-80ee-2bd45e26bc36.png)![image](https://user-images.githubusercontent.com/11380394/107055206-a7a07c00-6796-11eb-9159-c32d3378c407.png)

**Comment by KarlOfDuty** [comment]
Fixed.
