### ISSUE TITLE
Pandas for mainland Asian nations

### ISSUE THREAD

**Issue by Rezolent** [EarthMC/Issue-Tracker#955]
Coastal mainland  Asian nations should get pandas and possibly bamboo although bamboo might lag the server significantly.

**Comment by docwhomc** [comment]
Bamboo has been added.

**Comment by docwhomc** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Mapa_distribuicao_Ailuropoda_melanoleuca.png/220px-Mapa_distribuicao_Ailuropoda_melanoleuca.png

**Comment by Colt44Magnum** [comment]
I feel like this would be an easy feature to add into the game and would look forward to it, Panda breeding becomes a way to get slimeballs albeit it is a very low chance as baby pandas need to sneeze one of those goobers out into the world.
