### ISSUE TITLE
[Plugin]add vehicle plugins

### ISSUE THREAD

**Issue by Alkali1234** [EarthMC/Issue-Tracker#956]
Add vehicles plugin so you can travel around faster and easier
Examples:
Ultimate car mod(idk if there is the plugin)
Ultimate vehicles mod

**Comment by stzups** [comment]
These are mods not plugins and would require every single person who joins the server to have forge installed with the right mods. I doubt anything like this will ever happen. Just use boats on ice roads.

**Comment by SolidShock** [comment]
So to sum it up, it won't be happening.

**Comment by KarlOfDuty** [comment]
No.
