### ISSUE TITLE
[BUG] Items don’t drop on death

### ISSUE THREAD

**Issue by Samisol** [EarthMC/Issue-Tracker#957]
**Server**
Earthmc

**Describe the bug**
Items don’t drop when you kill someone anymore. I’ve killed multiple people since the update and everything is gone.

**To Reproduce**
Kill someone with items on them

**Expected behavior**
Items should drop when they have on them.

**Comment by Samisol** [comment]
I’ve killed multiple people since the update and items don’t drop anymore so that stuff is gone forever?

**Comment by Cactusinapumpkin** [comment]
Duplicate #953
