### ISSUE TITLE
[BUG] Problem with Beds

### ISSUE THREAD

**Issue by explodingmelons** [EarthMC/Issue-Tracker#958]
**Server**
Towny

**Describe the bug**
Essentially, you're able to set your /res spawn to any bed, anywhere, within claims owned by players, within claims not owned by players and in the wilderness. It's only possible to do it during the day as during the night it still prevents you from actually sleeping there, yet you're still able to set your /res spawn to whatever bed you please provided that it's not night.

**To Reproduce**
Steps to reproduce the bug:
1. Go to literally any bed that isn't in a plot you own during the day
2. Click on the bed
3. /res spawn

**Expected behaviour**
Should get teleported to the bed you just clicked on

**Comment by docwhomc** [comment]
What is the issue here? @explodingmelons

**Comment by jkmartindale** [comment]
> What is the issue here? 
The restriction that you can only set your spawn point to beds on inn plots and your plots is only enforced at night.

At night you'll get this message after right-clicking on a bed you don't own:
![image](https://user-images.githubusercontent.com/11380394/79083669-e982a200-7cec-11ea-92de-a6a2c0d938e2.png)

During the day no messages display aside from the default Minecraft message:
![image](https://user-images.githubusercontent.com/11380394/79084695-5a788880-7cf2-11ea-9f20-825e59e8763b.png)

But your spawn point is changed to the bed.

**Comment by jkmartindale** [comment]
Fixed in Towny 0.96.3.2 according to the [changelog](https://raw.githubusercontent.com/TownyAdvanced/Towny/master/resources/ChangeLog.txt):

>   \- Fix deny_bed_use not doing very much in the daytime.

**Comment by jkmartindale** [comment]
Fixed in latest server update
![image](https://user-images.githubusercontent.com/11380394/101300007-b3ed7480-37f9-11eb-9fa5-60e3965f579a.png)
