### ISSUE TITLE
[BUG] Position In Queue Rising No Matter What. 

### ISSUE THREAD

**Issue by BusDuster** [EarthMC/Issue-Tracker#959]
**Server**
Which server the bug is on.
[  Hub  ]

**-THE BUG-**
While in queue , ( does not matter what position you are in in the queue.. could be 1st in line or 30th in line ect. ) Player position in queue will rise instead of the number going down as expected. 

**To Reproduce**
1. Launch Minecraft in version 1.15.2
2. Join the server queue
3. Watch and see your position in queue start to rise.

**Expected behavior**
Yes, I know that the server is allergic to bees... And I know that there are many , many people with priority queue/ supporter rank who are trying to log on to the server to experience the new update to 1.15.2. (Obviously they would get to log on before non priority/supporting players.)

**Screenshots*
![image](https://user-images.githubusercontent.com/61428509/75178867-c6287700-56ed-11ea-9d6d-7ab701660473.png)

![image](https://user-images.githubusercontent.com/61428509/75178984-f839d900-56ed-11ea-8943-20ab652ec0f3.png)

![image](https://user-images.githubusercontent.com/61428509/75179075-27e8e100-56ee-11ea-9a7a-0bbbfe54e148.png)

![image](https://user-images.githubusercontent.com/61428509/75179124-3fc06500-56ee-11ea-8827-e57c86d2d82d.png)

![image](https://user-images.githubusercontent.com/61428509/75179167-5b2b7000-56ee-11ea-9381-210aa174c77f.png)

**Additional context**
DocW told me to make this github report. (i don't wanna seem like a wah, wah b*tch for this)

**Even more context**
Sat in queue for 10 hours yesterday because I have no life. Put up with the queue crashing many , many times.  Seen players that i know for a fact don't have prio or supporter get into the server before me even though I queued up hours before them.

Don't tell me to buy priority! Priority players were/are experiencing this same issue.

** What I think is going on**
I'm guessing that since the server is full , it's only letting people with priority or supporter join when someone leaves, and a spot opens up. I really don't know because people who have priority queue have also been claiming that they are being pushed back in queue ( number rising) instead of decreasing/progressing as expected.  

* A poem on the matter* 
"The server did a sneeze because it's allergic to bees. It's got me on my knees. Begging pretty, pretty please let me get through this queue; jeeeez. " 

I'm sure this will get fixed in a few days. Only made this because DocW said i should.
 
Tbh i probably won't check the updates on this report because I already know what the comments will say.

**Comment by BusDuster** [comment]
Reopening this

**Comment by KarlOfDuty** [comment]
This should be fixed now.
