### ISSUE TITLE
[BUG] Entity limitation per chunk

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#960]
**Server**
TOWNY server

**Describe the bug**
Bug on entity limitation for prevent lag

**To Reproduce**
1. Feed animals 
2. Place it on 1 delimited chunk
3. wait baby and feed again
4. Unload the chunk and when you back server should have left only 5 sheep or cow

**Expected behavior**
Normaly get the server limitation to 5 for stabilize server

**Screenshots**
![2020-02-24_21 53 45](https://user-images.githubusercontent.com/61435183/75190787-619f0380-5751-11ea-8eb8-5599fa347741.png)
![2020-02-24_21 19 36](https://user-images.githubusercontent.com/61435183/75190790-62379a00-5751-11ea-8e89-7f3a9026dba9.png)
![2020-02-24_21 18 26](https://user-images.githubusercontent.com/61435183/75190872-85fae000-5751-11ea-8c74-8b04d6d14946.png)

**Additional context**
i tested with bee, sheep , cow and chiken
all same result No limitation working

**Comment by QJWIN** [comment]
olso when we take wheat in hand collision system hurt animals when they are to many 
in the sheep screen when i feed then they all pack beside me and when he was to many we see them die , but not by the limitation system , by the collision betwin sheep

**Comment by KarlOfDuty** [comment]
This isn't really a bug...? It's just normal minecraft mechanics.
