### ISSUE TITLE
[BUG] Villager and bed

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#961]
**Server**
TOWNY server

**Describe the bug**
Changement of /resident position ( bed attrib )

**To Reproduce**
1. Go on a villager farm with new villager 1.15
2. Place bed for villager reproduction
3. Wait the night and dont ring bells
4. Then right click on a bed where a villager sleeping
5. That will wake up the villager and instead say 'you cannot define this bed as ur bed spawn'
that will attribute this bed as you new /resident spawn even if you are not the owner of the plot ( claim )

**Expected behavior**
expexted to do not changing /resident position

**Screenshots**
need a video for it impossible to see on screen

**Additional context**
Our own city have this farm type pos for fast travel 
![2020-02-25_04 45 43](https://user-images.githubusercontent.com/61435183/75213260-d3933f00-5789-11ea-9544-6af80535ba0e.png)

**Comment by PoppyK** [comment]
Has this been fixed? I noticed this too at the beginning of the 1.15 update but lately I've been able to work with villagers' beds without changing my res spawn.

**Comment by KarlOfDuty** [comment]
As villager trading is disabled this isn't really relevant anymore.
