### ISSUE TITLE
[BUG] Bypass /evict for Councillor

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#962]
**Server**
TOWNY server

**Describe the bug**
We are able to bypass mayor command /evict, when we do it that say we do not have this permission, but there is a way to bypass smartly ...

**To Reproduce**
1. Go on a plot u wanna evict a resident
2. use command /plot fs 0 ( to sell it )
3. use command /plot claim ( to claim it )
4. use command /plot unclaim ( for leave plot without owner )
5. use command /plot set name <leave a blanc space for reset name> ( don't reset name with /plot set rest )
6. use command /plot set reset (to reset plot type)  

**Expected behavior**
coucillor should not be able to use /plot fs  or not be able to use /plot claim on a owned plot if /evict is reserved for mayor

**Screenshots**
dont needed screen follow the step below

**Additional context**
Not relly but you can visit my town she was epic ^^

**Comment by KarlOfDuty** [comment]
Chancellors have permissions to use this command, what is the error message?

**Comment by KarlOfDuty** [comment]
I've reported the issue to the devs now.
