### ISSUE TITLE
[BUG] tons of blazes spawn and they make super loud noises

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#963]
blazes make a super loud noise that u can hear from a lot of blocks which kinda ruins /n spawns cuz of the loud fire sound u get from the blazes

also, way more blazes spawn than there should and it lags a lot, here are 4 videos of examples

https://youtu.be/yJyK8IkqX-k
https://youtu.be/65oVGX0Imes
https://youtu.be/bUDGgm9OW9Q
https://youtu.be/3rxawRqbgSA

**Comment by QJWIN** [comment]
https://github.com/EarthMC/Issue-Tracker/issues/960

**Comment by Pengun78** [comment]
it has been fixed no worries brother, but yeah ur technique worked too
