### ISSUE TITLE
Server rollback and stuff dispawn

### ISSUE THREAD

**Issue by Warleid** [EarthMC/Issue-Tracker#964]
**Server**
Towny

**Describe the bug**
The last time the server crashed, there was a pretty big rollback. As a result, all my builds made in the last 10 minutes disappeared. So I rebuilt them. But on my way home, I realized that my stuff that I had put in a safe and put on a armor carrier was gone. There was a suit of armor and a God sword. These items had cost me quite a bit of money, and I would like to get them back, because I looked for them and I couldn't find them anywhere.

**Comment by stzups** [comment]
Make a ticket on the EarthMC support Discord
