### ISSUE TITLE
[Feature] Add chanel discord

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#965]
**Describe the solution you'd like**
Can we have a channel dedicated to share our builds and creations , cause now for share we need to send screen shot into meme or emc meme , and i think  its out of context 

edit : 
its should out of lol, because shiraz mute me into emc meme ! ( purge )
i present you my apology if i does something wrong that was not my intention SRY

**Comment by KarlOfDuty** [comment]
Many of the news org discord servers have channels for that so you can use those.
