### ISSUE TITLE
[BUG] /Resident jail cmd

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#966]
**Server**
TOWNY server

**Describe the bug**
I have try to watch over a resident friendship, and when i have type in to the chat
/resident , the consol propose me few argument , one of them was jail, so for testing what is it
i have enter /resident jail.

We get a weird return i think we should not have a access to it. That returning a list of all connected player

**To Reproduce**
1. /resident jail

**Expected behavior**
Jail part should be turned off if im correct, so its a jail permission bug i think

**Screenshots**
( waiting server back for screen )

**Comment by stzups** [comment]
Can you add a screenshot of the weird return when you do /resident jail?

**Comment by QJWIN** [comment]
yes sry when i post server as crach i will do rn maybe is fixed already
