### ISSUE TITLE
[Feature] Add banner applyable into Leather horse armor

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#967]
**Is your feature request related to a problem? Please describe.**
Its not a real problem actualy, from 1.15 we are able to craft and color leather horse armor,

**Describe the solution you'd like**
That should be awesome if we can put our banner into the leather horse armor like shield .

**Comment by stzups** [comment]
This can only be accomplished with mods unless it was added to Minecraft by Mojang

**Comment by QJWIN** [comment]
yeah and like colored sign i dont see that was a 1.14 feature we can color leather horse armor and sign with dye ... i will close
