### ISSUE TITLE
[Feature] add pvp to lobby

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#968]
**Describe the solution you'd like**
That will be very fun to use the bloked nether portal at lobby to tp player into a small area,
like a small inside castel, where the pvp as turned on, and we can use the /kit pvp only inside this area. /kit pvp => like a complet iron stuff with one bow unenchanted and a iron sword olso unenchanted.

![2020-02-26_11 02 56](https://user-images.githubusercontent.com/61435183/75334387-09b6e880-5888-11ea-8de9-9800aecc2ea3.png)

I think people without priority pass will love it

**Comment by QJWIN** [comment]
and olso pvp player who can fight for training skill and don't loose there stuff

**Comment by KarlOfDuty** [comment]
Barely anyone ever used that while we had that feature so it was removed.
