### ISSUE TITLE
[PLUGIN] add auctions with GUI 

### ISSUE THREAD

**Issue by QJWIN** [EarthMC/Issue-Tracker#969]
**Describe the solution you'd like**

After some exchange with Fix and lot of player at discord into the night of the 25/02/2020,
and to get a market system who as currently out with sign shop plugin,

I find a auction plugin with gui
here is the github feel free to check 
https://github.com/badbones69/Crazy-Auctions

The good think is that will significantly reduce the sign and item frame into the server, because into 
Java Edition item frame as an entity ... i think that will help a lot with server lag

**Comment by KarlOfDuty** [comment]
We prefer shops being regional as it encourages travel and thus seeing more of other large towns and builds on the server, so we will not add this.
