### ISSUE TITLE
Locked MAP ART wiped

### ISSUE THREAD

**Issue by EmperorLelouch0** [EarthMC/Issue-Tracker#972]
**Server**
EarthMc.net

**Describe the bug**
Map Got wiped few days after locking them using carthography table. after the server updated to 1.15 i immeduately put them on lock using carthography table so the map will not be updated at first its fine but then after few days all maps are gone. to review more about bugs visit /n spawn philippines

**Expected behavior**
The map Should be back to normal 

**Screenshots**
![2020-02-27_20 28 33](https://user-images.githubusercontent.com/61547789/75448048-7a9ff280-59a5-11ea-9f78-084656d821d5.png)
![2020-02-27_20 42 32 - Copy](https://user-images.githubusercontent.com/61547789/75448071-87bce180-59a5-11ea-8e18-fe0ce2744bb9.png)

**Comment by docwhomc** [comment]
Seeing as the duplicate issue you opened on this bug (#978) has a more detailed description, I'll close this one instead.
