### ISSUE TITLE
[Feature] Reset the map!

### ISSUE THREAD

**Issue by SolidShock** [EarthMC/Issue-Tracker#973]
I started playing two or three months before the boxtoy child invasion. At that point the world was already decently saturated and hard to find a clear spot to make your own little town. But look at it now! I left for a year or so and now you have a nation capital every 200 blocks. It's so dumb! People have stopped making great towns and cities and now just build some kind of floating art. The world went from having only realistic towns and nations to having pixelart shoved around it! What the hell!?

New year, new server! I believe this is a ideal time to get started working on doing a reset on the server. One reset every 2 years would be absolutely fine! This isn't no 2B2T. I made a nice post regarding the towny plugin and war plugin which both could be improved quite a bit. Link can be found at the bottom of this issue. So you guys can get a brand new plugin and do a reset at the same time! Everyone could start fresh on a clean, realistic world. Make the greatest nations of all time once again!

Link to towny and war plugin discussion: https://github.com/EarthMC/Issue-Tracker/issues/974

**Comment by Aitonater** [comment]
I think the server should only be reset if it starts to rapidly decline in popularity and playability but as it stands there is a constant 200 active players on the server at any given time and often a queue over 150. I personally would probably stop playing if my 350+ hours of progress and game-play went down the drain for no discernible reason.

**Comment by SvenPhillips** [comment]
> I think the server should only be reset if it starts to rapidly decline in popularity and playability but as it stands there is a constant 200 active players on the server at any given time and often a queue over 150. I personally would probably stop playing if my 350+ hours of progress and game-play went down the drain for no discernible reason.

I completely agree. I have spent 300 hours on EarthMC (mostly factions), and although it may seem like we need a new map, and to start fresh, it would discourage old players to go on the server. I think that they should add Towny v2 and maybe Factions v2, but I don’t think people who have invested so much time into this server would like all of their hard work to go down the drain.

**Comment by Pengun78** [comment]
bruh emc classic ran for like 3 years with a small map and u expect the big terra nova server with a bigger map to reset after less than 2 years?

**Comment by KarlOfDuty** [comment]
We will not be resetting the map at this time.
