### ISSUE TITLE
[Plugin Suggestion] Get a new towny plugin that integrates a war system

### ISSUE THREAD

**Issue by SolidShock** [EarthMC/Issue-Tracker#974]
Issue:
As it has been talked over many, many times over the past two years, the towny plugin is unoptimized. One other thing that has been talked over for years is the war system.
There was a pathetic attempt to fix the war system with the creation of the factions server and as much as we can see from the dynmap and overall activity, it was useless.

Possible solutions:
So talking about the towny plugin, I had talked to some staff member and they said it would cost anywhere from 4-5k USD to make a plugin like towny and make it well. As a person who knows a decent about developing software, I couldn't believe this number for a minecraft plugin, so I did some research. I visited around 18 different communities that offer to create custom plugins for other communities. The average price for a fully custom towny plugin (includes war) with a custom currency and continued support would cost around 200-300 USD. For a community this big I believe it could be doable, but that's for you high standing personnel to decide.
Moving on about war you have two options. Make it integrated in the new towny plugin OR make wars like organized events by staff. So if there were a war to happen between two nations it would be like an organized battle moderated by staff. The side who won would dictate the terms, but obviously nothing too insanely stupid, no annexing.

This is a followup to this post: https://github.com/EarthMC/Issue-Tracker/issues/973

**Comment by stzups** [comment]
There is nothing wrong with towny and a war plugin (SiegeWar) is currently in development. Towny represents over 8 years of active open source development by competent individuals and no one can simply make a new towny without some serious time and money.

Also, I think a staff moderated war system would be too high maintenance and would not work.

Additionally you say the new custom towny plugin would be `with a custom currency`. This does not make sense as currency is usually handled by an economy plugin such as TheNewEconomy.

**Comment by SolidShock** [comment]
Towny isn't optimized, exactly due to the fact that it's completely open-source.
SiegeWar seems promising, so I'm totally up for that.

If they decide to leave the current towny and add something like SiegeWar, I can bet you that even less players would be able to get on at once.
And whichever they choose, they need to reset this disgusting pixel art filled crap of a world. (Check refference to my second post)

**Comment by stzups** [comment]
> Towny isn't optimized

 This is a very broad statement. Can you elaborate on what you know about the performance of Towny?

Additionally, how could a new plugin be able to fix this and implement all or most of Towny's current features?
> leave the current towny and add something like SiegeWar

SiegeWar will be part of Towny, therefore EarthMC still has to use Towny. See the pull request [here](https://github.com/TownyAdvanced/Towny/pull/3541).

>  I can bet you that even less players would be able to get on at once.

You have no idea how SiegeWar would affect performance. Even if it did, what would an alternative option be?

**Comment by DasCodes** [comment]
Follow #928.
