### ISSUE TITLE
Created a town and the server crashed. Lost gold, Town wasnt created.

### ISSUE THREAD

**Issue by Hoozt** [EarthMC/Issue-Tracker#975]
**Server**
Towny

**Describe the bug**
The moment i created the town called "Atyrau" the server crashed. When i got into the server again my gold was gone and the town hadnt been created.

**To Reproduce**
1. Create Town
2. Crash server
3. Lost inventory
4. Cry

**Additional context**
Player name: Hoozt

**Comment by stzups** [comment]
Make a ticket on the support discord

**Comment by DasCodes** [comment]
Please make a ticket about it on support discord as @stzups said above.
