### ISSUE TITLE
[Feature] Add creative as a separate server or option while in queue

### ISSUE THREAD

**Issue by Nalasleafheart** [EarthMC/Issue-Tracker#977]
**Is your feature request related to a problem? Please describe.**
As someone who doesn't have queue priority, getting on the server during weekends is a mess. As summer comes closer and closer I know queue is gonna get harder for both priority users and users without priority. The queue has a parkour and hidden spots to discover but over time this gets boring to older players and personally in queue I'll maybe walk around for a minute or two and then tab out and watch YouTube or Netflix. Over time I just get so bored and last week when queue was over 130 I sat in the queue server for about 3-4 hours and got pretty bored. I really just wish I had something other to do than a parkour, pve, or discover parts of the island. Like I said previously there's the YouTube or Netflix option but I'd rather stay playing Minecraft if I could.

**Describe the solution you'd like**
I believe a way to decrease the boredom while in queue is possibly giving an option to build for players. Maybe a separate server or lobby that's just survival or creative, but if I had to choose I'd rather have a creative server. The reason for a creative server over separate survival server for queue is because a lot of players already go to single player creative worlds to design builds for their town and it would be very convent if there was a creative mode part of the server. Even if a creative mode queue server can't be created, I would love a creative mode server in general and I'm sure many other players would find it useful as well so they can test build ideas.

**Comment by DTHMASTER** [comment]
PVP would be great!

Or even add rewards for completing parkour. maybe even gold!?!?!?

**Comment by Cactusinapumpkin** [comment]
I think asking ur mom for 10 bucks would be faster

**Comment by DasCodes** [comment]
We don't have such plans atm. Maybe in future.

**Comment by DTHMASTER** [comment]
> I think asking ur mom for 10 bucks would be faster

???

**Comment by jkmartindale** [comment]
> ???

The joke is that finding some way to scrape together $10 to buy priority is easier than getting a whole creative server running. Which I mean, true, but that doesn't justify being a jerk about it.
