### ISSUE TITLE
[BUG] Map art Collection Wiped

### ISSUE THREAD

**Issue by EmperorLelouch0** [EarthMC/Issue-Tracker#978]
**Server**
EarthMC.net Towny

**Describe the bug**
Map Got wiped few days after locking them using carthography table. after the server updated to 1.15 i immediately put them on lock using carthography table so the map will not be updated at first its fine but then after few days all maps are gone. There is a theory according to WTDpuddles , when a map is locked, the map receives a new ID so essentially it is a new map. On EMC, if a new map is created and there is a server restart soon after, it can roll back the map and bug it out as seen in these screenshots. to view more about bugs visit /n spawn philippines 

**To Reproduce**
1. Get the map
2. Lock it on carthography table
3. Put the map on frame 
4. Theory is that the server crash making the map to rollback and cry

**Expected behavior**
Map art collection rollback

**Screenshots**
![2020-02-27_20 28 33](https://user-images.githubusercontent.com/61547789/75603174-1ac15d00-5b07-11ea-8f40-fd0b17f68604.png)

![2020-02-27_20 28 33](https://user-images.githubusercontent.com/61547789/75603187-2745b580-5b07-11ea-9a3e-b99edbd0ac05.png)
![2020-02-27_20 42 32 - Copy](https://user-images.githubusercontent.com/61547789/75603189-2a40a600-5b07-11ea-8430-82e6c1145268.png)

**Comment by QJWIN** [comment]
I can help you mate ! you provide me a lot for my museum if a locket map can be copied i can provide 
you a great part of what you loose msg me or add me discord ... that will not give you a solution to you problem but if i can give you back the most of them ... i will

**Comment by EmperorLelouch0** [comment]
Thank you brother. can i get your discord

**Comment by QJWIN** [comment]
QJWIN#4671

**Comment by KarlOfDuty** [comment]
Hopefully fixed now with the new server version.
