### ISSUE TITLE
duplication chat

### ISSUE THREAD

**Issue by AmphireYT** [EarthMC/Issue-Tracker#979]
**Server**
Towny

Every time i type in chat, it duplicates my chat

honestly, idk how did it i just switched my chat around and this happened
**Expected behavior**
i did not expect it to happen it just did

![Screenshot_38](https://user-images.githubusercontent.com/60866343/75620312-634b3b80-5b44-11ea-81e7-dc272ca5acb4.png)

**Comment by KarlOfDuty** [comment]
Try /ch leave trade, /ch join trade

**Comment by AmphireYT** [comment]
> Try /ch leave trade, /ch join trade

Can i just keep it tho? Its pretty cool and can get peoples attention faster like lets say I wanna buy/sell something. Im just made to say its a thing

**Comment by jkmartindale** [comment]
> Its pretty cool and can get peoples attention faster
The moment I see someone do this I ignore them for being so annoying

**Comment by AmphireYT** [comment]
> > Its pretty cool and can get peoples attention faster
> 
> The moment I see someone do this I ignore them for being so annoying

by attention I mean only trading and talking to people not advertising and all that nonsense

**Comment by KarlOfDuty** [comment]
This is likely fixed in the next version.
