### ISSUE TITLE
[Plugin/Bug] MCMMO Blast mining doesn't work.

### ISSUE THREAD

**Issue by Synargle** [EarthMC/Issue-Tracker#98]
When players attempt to use blast mining, it doesn't drop anything and regenerates the blast field instead.

**Comment by Arganog** [comment]
Regular TNT explosions also regenerate

On classic, creeper explosions regenerated and TNT explosions did not.

This is ideal so that we can use TNT for it's intended purpose (clearing large amounts of blocks)

**Comment by KarlOfDuty** [comment]
Fixed.
