### ISSUE TITLE
[Bug] Towny doesn't respect Chat: Commands Only

### ISSUE THREAD

**Issue by jkmartindale** [EarthMC/Issue-Tracker#981]
**Server**
Towny

**Describe the bug**
Player chat messages are now considered command output and won't be filtered when Minecraft's chat setting is set to "Commands Only". This is a regression from the 1.15 update, on 1.13.2 player messages would be filtered out unless they came from the Discord bridge.

I like being able to switch off player messages because it lets me focus on what I'm doing in-game, and disabling chat entirely makes it impossible to teleport or work on town particulars until it is re-enabled. Commands Only was a good compromise back when it worked.

**To Reproduce**
1. Open Game Menu in-game
1. Click on **Options...**
1. Click on **Chat Settings...**
1. Toggle **Chat: Shown** to **Chat: Commands Only**

**Expected behavior**
Only command output is displayed, not player chat messages.

**Actual behavior**
No chat filtering is applied.

**Comment by KarlOfDuty** [comment]
This is nothing we can fix as far as I know as it is a change in minecraft itself, but I'll mention it to the developer.
