### ISSUE TITLE
[BUG] No spaces possible in town board

### ISSUE THREAD

**Issue by Pengun78** [EarthMC/Issue-Tracker#984]
I'll keep this simple, you're not able to put spaces in town boards anymore, I remember being able to do so, but it's an "invalid string" now. I keep having to use the _ instead of spaces for messages on my town board, towns like London prove that it used to be possible

![image](https://user-images.githubusercontent.com/44297328/75790278-3d53b000-5d6b-11ea-9885-489159d1632b.png)
![image](https://user-images.githubusercontent.com/44297328/75790307-4ba1cc00-5d6b-11ea-8b33-b76ab023c6fa.png)
![image](https://user-images.githubusercontent.com/44297328/75790396-6ffda880-5d6b-11ea-9fc2-a6117b9955a8.png)

**Comment by KarlOfDuty** [comment]
Should be fixed on next restart.
