### ISSUE TITLE
Villagers and Mobs are bugged

### ISSUE THREAD

**Issue by FruitUniversity** [EarthMC/Issue-Tracker#986]
**Server**
Towny

**Describe the bug**
Villagers and mobs are broken. Mobs (Sheep, pigs, and cows) will look/be frozen until interacted upon such as breeding, feeding, milking, killing, shearing etc. and then they will move but couple minutes later they will freeze and not even turn their head. Now villagers, they will not choose a bed, job, or do anything except move their head and walk a little bit.

**To Reproduce**

Go to: A villager
Click on: try to work with them and have them try to find a job
Scroll down to: They will not choose or loose a job and they will also suddenly disappear for no reason
See error: I have many people who say this also happens to them.
Expected behavior
The animals should move whenever and not be frozen

**Screenshots**
Just go to /n spawn alaska and go to their sheep.

**Additional context**
Please fix this issue.

**Comment by MeikaWinter** [comment]
Yes, I destroyed some job blocks and it's like they're still here. When I interact with one of my villagers, he's able to work without his block, we can hear the sound.

My baby cows don't grow up.
Sheep don't eat so I can shear them.

**Comment by AlexaDesa** [comment]
Same with villagers. And today I tried to bring over a cow to my town and it just dispawned in the boat. I tried to destroy the boat but still no cow.

**Comment by Carabow** [comment]
Same issue with my villagers : they keep to disapear even if I separate them less than 8 in one plot ! Or sometimes less than 3 in one plot ! Even the good ones I tried to protect with a nametag ! It is really annoying.
Same Issue with a nation friend, I tried to give him some of my villagers, but they keep disapearing instead of/before breeding. @Fix Please correct. Help!
I also just realised that my favorite horse disapeared too.
Some cow or sheeps too, but I still have enough of them to breed them back and none of these are special.

**Comment by lemaitrechocolatier** [comment]
Please fix this issue.

**Comment by Vortezz** [comment]
Yes, fix that

**Comment by Carabow** [comment]
Villagers still disapearing... and don't seems to breed...
Cow and sheeps too, but until now by breeding I achieve to maintain 6 cows in a plot and 4 sheeps (5 before) in an other one...

**Comment by lemaitrechocolatier** [comment]
my ticket is open for 2 weeks soon three .. we had a room full of enchanting, farm in 1.13 for weeks and weeks, today they have almost all disappeared, I replace them at least once (all) then he we reappeared, I try to understand, are they reading? the business blocks? the villagoeis numbers? but despite two weeks to refame villagers, nothing, they do not seem to disappear following this or that or even in a "logical" order we lost a total of around 60 villagers, it gives a blow to our motivation and our money , what should you do? I can't get any info on the bug nor on the "alert state" that this provides to the staff ... Do you have any info?

**Comment by FruitUniversity** [comment]
Some of these problems like not restocking are due to the villagers being on 1.14 which happens to be the only version with broken villagers.

**Comment by Aitonater** [comment]
Mine seemed to be working okay then 4 babies despawned and they now refuse to become librarians despite having access to lecterns.

**Comment by AmphireYT** [comment]
plz fix

**Comment by eke223** [comment]
I've found a workaround for the villagers but the issue should still be fixed as even the workaround is slow.

**Comment by jkmartindale** [comment]
@eke223 What's the workaround?

**Comment by eke223** [comment]
> @eke223 What's the workaround?

That I'll keep to myself

**Comment by KarlOfDuty** [comment]
This was a bug with our old server software, it should be fine in this one.
