### ISSUE TITLE
/ignore fix

### ISSUE THREAD

**Issue by SvenPhillips** [EarthMC/Issue-Tracker#987]
**Server**
Factions, haven’t tried on towny.

**Describe the bug**
You can not /ignore people who have dotcom or dotorg at the end of their name.

**To Reproduce**
1. Do /ignore fliddotorg or another thing ending in dotcom or dotorg
2. An error message shows up because you can’t advertise websites. 

**Expected behavior**
That you can /ignore any valid username

**Notes**
I didn’t get screenshots, but this is a way that spammers can annoy everyone on a server and no one can really do anything about it except for pinging mods.

**Comment by KarlOfDuty** [comment]
Should be fixed on next restart.
