### ISSUE TITLE
Can’t do /t

### ISSUE THREAD

**Issue by DTHMASTER** [EarthMC/Issue-Tracker#988]
**Server**
Towny earthmc 

Can’t do/t although can do commands like /t spawn.

**Comment by KarlOfDuty** [comment]
There is apparently some issue with the permissions plugins that causes this at some points, try going through a nether portal or ask a mod to resync you in order to fix it.

**Comment by DTHMASTER** [comment]
I have done all those things - it has been the same for months now, as I said I can do other commands and I don't think the problem has existed for this long. If you want I can send you video proof or something like that.
