### ISSUE TITLE
[Plugin] Re-enable the Axes MCMMO tree in PVP without armor impact.

### ISSUE THREAD

**Issue by CasperFactions** [EarthMC/Issue-Tracker#989]
Why would we enable it again? It's because armor impact was the unbalanced thing, and without it the Axes MCMMO tree is just a fun way of PVP, it will greatly improve the PVP experience against the better players, because it will take more skill to stay alive in difficult battles against the best of the best. Axes is also a way of easily getting rid of hackers, because at high level you can 3 shot someone in god armor if you get 3 mcmmo crits in a row. Also Axes is only good if you have over 250 levels, which is less than 50 players (most of them dont even play anymore). Axes was enabled on factions without armor impact enabled for a while (armor impact was nerfed and enabled which made it OP) and u could still win with a sword if you're better than the enemy so its not totally broken. It would make PVP more diverse with players having the option of high burst damage axes pvp which requires good aim, or high DPS with a sword. Come on staff, at least test it for a week! If anyone complains too much you can disable it again.

**Comment by QJWIN** [comment]
that make no sens to bring axe at pvp if you ask to not have any impact on armor ...
if axe brake more the armor is for a reson no one will use it if that does the same as a sword ...

**Comment by lili502** [comment]
Loool @QJWIN speak but never Pvp.
In faction server many people still use axes to do more damage in 1 hit.
