### ISSUE TITLE
[Plugin] Shop plugin only allows sale of one item at a time.

### ISSUE THREAD

**Issue by IanNotEN** [EarthMC/Issue-Tracker#99]
I just tried to use the new shop plugin to sell wool, but quickly realized a major issue. You can only sell one item at a time. When you click on the chest with the item, it asks you to enter how much you want to sell ONE of the item for. For example, I attempted to sell wool, but it would only allow me the option of selling 1 wool, not more. I figured that I would be able to simply choose a low price for the one wool then. I tried to enter .1 gold, but the lowest amount you can enter is 1. This means that every single item must cost at least one gold, even a single block of dirt. The only solution I can see is to find a different plugin that allows us to sell more than one item at a time.

**Comment by KarlOfDuty** [comment]
Agreed. We have not found another plugin that works better and also is updated for 1.13 however.

**Comment by KarlOfDuty** [comment]
The next shop plugin should fix this.
