### ISSUE TITLE
[Feature] scaffolding recipe

### ISSUE THREAD

**Issue by DeadGlamour** [EarthMC/Issue-Tracker#992]
Currently, there is no way to get scaffolding in emc, that is very problematic for builders like me since its a very useful and pretty block, and there seems to be no intention in adding bamboo due to lag or whatever.

My solution is simple, 1 of these recipes should be added, they are both just as expensive as the mormal recipe in vanilla, personally I prefer the sugar can 1 since its more like the vanilla recipe.
![Screenshot_20200307-174353_Chrome](https://user-images.githubusercontent.com/53373440/76146636-15cb5300-609d-11ea-8840-0a8acce7b889.jpg)
![20200307_174410](https://user-images.githubusercontent.com/53373440/76146638-195eda00-609d-11ea-9f62-4599cf49f709.jpg)

**Comment by DasCodes** [comment]
We have plan to add bamboo on the server, so this won't be necessary.
