### ISSUE TITLE
Fix Ally Requests or Add a way to see if you are already allied

### ISSUE THREAD

**Issue by gabeeebaby** [EarthMC/Issue-Tracker#993]
Right now you can send ally requests even when you are already allied with that nation. A fix for this would either make it so it won't let you send a request if you are already allied with that nation or add some sort of indicator to show that you are already allies, without having to look at your possibly hundreds of current allies. One way to fix this would to add (Allied) next to the nation if you are already allied with them when you do /n (nation). This would be similar to when doing the /res command and it shows (online) if that player is on. This would make false ally requests much less likely or impossible and is a very simple addition to towny.

**Comment by KarlOfDuty** [comment]
Reported to devs. https://github.com/TownyAdvanced/Towny/issues/3749
