### ISSUE TITLE
[Feature] Custom crafting recipe for the thing banner pattern

### ISSUE THREAD

**Issue by ghost** [EarthMC/Issue-Tracker#995]
I make custom banner orders on the server and I noticed that I couldn't make the thing pattern (uses golden apple). I asked the mod Highlander about this and he said the feature is disabled. I think there should be a custom recipe for this because it will open up so many new possibilities for banner and flag designs. Instead of being a golden apple maybe it could be some other valuable like a diamond or emerald.

**Comment by FutureLemon** [comment]
Do you mean the Mojang logo?

**Comment by FutureLemon** [comment]
He means this recipe:
![image](https://user-images.githubusercontent.com/44688587/76549121-1c3c3f00-6490-11ea-82c5-48aa83a54ac4.png)
To get the Mojang logo
![image](https://user-images.githubusercontent.com/44688587/76549142-29592e00-6490-11ea-8a74-96ed2e6086f7.png)

**Comment by Colt44Magnum** [comment]
need to revive this thread. I'm looking for this to exist at some point

**Comment by Warriorrrr** [comment]
See #1244
