### ISSUE TITLE
[MECHANIC] Fishing for gold has been suddenly disabled

### ISSUE THREAD

**Issue by BreachDGates** [EarthMC/Issue-Tracker#996]
**Is your feature request related to a problem? Please describe.**
It seems like you cannot find any gold, gold armor or gold items by fishing. I fish a lot in EMC and even though the chances of finding stuff for someone whose level is above 875 are different, I still get all the possible McMMO items, (from CDs to leather armor). The exception is for gold related stuff.
I used to get 5 gold ingots at once, all pieces of gold armor (unenchanted and enchanted) and gold swords, pickaxes, axes, shovels and hoes.
This McMMO Wiki page claims that you can still get gold related items:
https://mcmmo.fandom.com/wiki/Fishing

**Describe the solution you'd like**
Bring back gold and golden items so that they could be used for decorative purposes.

**Additional context**
I haven't found any gold or golden item in my last 400 fishing levels. This used to work even after the EMC McMMO update and before the EMC 1.15 update.

**Comment by Carabow** [comment]
If it is true, I hope I will be back too soon.

**Comment by Cactusinapumpkin** [comment]
I think you are wanting a higher chance of getting gold ingots than diamonds in the upper lvls to make more since with the server. But I would prefer enchanted diamond armor over gold armor

**Comment by jkmartindale** [comment]
Trying my best to parse what you're saying:

> I think you are wanting a higher chance of getting gold ingots than diamonds in the upper lvls

In McMMO defaults, gold ingots are an uncommon level fishing treasure and diamonds are an epic level treasure. Thus gold ingots are more common than diamonds until Treasure Hunter rank 7 (Fishing level 850), when epic treasures become more common than uncommon treasures. As far as I know EarthMC has no control over treasure probability distributions tied to each rank, but can move items between ranks.

> But I would prefer enchanted diamond armor over gold armor

There's no way to prioritize enchanted armor/tools of one material over another, the enchantment is a random probability based on your Magic Hunter rank.

**Comment by jkmartindale** [comment]
I will ask that if fishing for gold items is going to remain disabled (which I really hope won't be the case), please re-enable Salvage for gold items.

As far as I understand the sole reason for disabling salvaging gold items was so fishers wouldn't get as much gold from fishing, but now that gold fishing is disabled it would be nice to have gold salvage back.

**Comment by FutureLemon** [comment]
All options to gain gold where deliberately disabled except for regular mining or vote crates. The ability to gain gold from fishing was never intended to be turned back on and was only on for a while during the transfer to the newer MCMMO plugin, the same counts for double drops from mining, salvaging or even gold drops from mobs.
