### ISSUE TITLE
Factions Features which are really necessary.

### ISSUE THREAD

**Issue by Ashe820** [EarthMC/Issue-Tracker#997]
Hey its Enni_TNT,

Since a very long time i relized that factions, when it gets its seldom update, its getting the wrong updates which doesnt making it that much better. Here some suggestions for further changes people really want:

- Nether Border Increase 
- Vote Crate Update ( Different Types of Spawners, Totems, other fancy things)
- Maximum amount of allies increase from 3 to 5
- Ability to set faction warps (increase from 0 to 3-5)
- Update to 1.15 asap
- Ability to get player Heads from kills (maybe even a bounty hunter plugin)

Im playing longterm on faction since its release knowing what needs to be expanded.
I hope you take a look eagle, fix and seriously think about those updates. Thanks.

**Comment by RoseBrugs** [comment]
All very good and valid suggestions,
Despite my relatively short time on the server I can say for a fact these suggestions would greatly improve the factions experience allowing for a larger player-base to develop !! Would love to see these soon :))

**Comment by TacoSeller420** [comment]
All of theses would be very nice to add, but it'll also be really appreciated if the "tp cooldown" is reduced a lot since one minute to wait between every teleportation is way too much time lost.

**Comment by xMarie** [comment]
yea the tp cooldown rly needs to be reduced to like atleast 6 sec or somethn

**Comment by docwhomc** [comment]
Why do you want a nether border increase?

**Comment by TacoSeller420** [comment]
A nether where you cant go further from 15 000 is way too small for factions, we can so much more easily find netherbases, like we litterally found some netherbases by pure coincidence.

Also we would be on a shortage of blazes spawners since they'll be so much more rare and harder to find.

Increasing the nether would be very appreciated
