### ISSUE TITLE
Town expansion and trasferring possibility

### ISSUE THREAD

**Issue by Saayuuki** [EarthMC/Issue-Tracker#998]
The idea is u can buy chunk expansion to your town multiple time. The first expansion cost could be 32 gold if you bought it your town maximum chunk will be increasing with 8 chunk and u need tó pay for those chunk the original 16 gold expansion price. The second expansion cost will increase not a big ammount example 48 gold and the price is go slowly up. Second idea is an item which allow u to transfer animals which only tamed by you with the cost is your movement speed will be reduced. And u can't stack those items. The crafting cost should be a lead surrounded by gold ingots this will make you thinking about it u want to craft it or not

**Comment by docwhomc** [comment]
Please split this into separate posts.

**Comment by docwhomc** [comment]
You can increase your town size limit by getting other players to join it and by joining a nation.
