### ISSUE TITLE
Town missing and E-chest emptied?

### ISSUE THREAD

**Issue by Yudokuna** [EarthMC/Issue-Tracker#999]
**Server**
EarthMC Towny

**Describe the bug**
My Town known as "Moron" located in the middle of Mongolia is missing/been deleted.
My characters items and E-chest items are all gone and my character is in Madagascar.

**To Reproduce**
I have no idea, I have been out of town for the past 2 weeks and come back to my town and items completely gone.

**Expected behavior**
The town should still be protected and E-chest should still have items

**Screenshots**
![unknown](https://user-images.githubusercontent.com/62060055/76414710-c9a74800-63e7-11ea-9841-da6a7ad772e4.png)
![unknown (1)](https://user-images.githubusercontent.com/62060055/76414719-cc09a200-63e7-11ea-9651-14648ea12fe6.png)

**Comment by DasCodes** [comment]
What is your in-game name? @Yudokuna

**Comment by Yudokuna** [comment]
In-game name is the same as on here and discord. Yudokuna
